### ISSUE TITLE
Open gitter channel for RxJS

### ISSUE THREAD

**Issue by robwormald** [ReactiveX/RxJS#1005]
Would be a good idea to activate a gitter channel like we have for angular - https://github.com/angular/angular - it helps keep the "how do i x" noise off the github issues and gives people a place to figure stuff out. 

RxJava has one already under the same umbrella https://gitter.im/orgs/ReactiveX/rooms

**Comment by kwonoj** [comment]
Isn't https://gitter.im/Reactive-Extensions/RxJS does job? making it under /ReactiveX?

**Comment by robwormald** [comment]
oh hey, look at that. didn't know that was there :D might be worth adding to the README here then.
