### ISSUE TITLE
Do we need project and thisArg for IteratorObservable?

### ISSUE THREAD

**Issue by staltz** [ReactiveX/RxJS#1009]
Currently, `Observable.from`, when given an iterator, will create `IteratorObservable`, passing null as values to `project` and `thisArg`.

**There is no other case where IteratorObservable is created**, which means `project` and `thisArg` are never used.

Can we take them away?

**Comment by kwonoj** [comment]
What about cases of someone import `IteratorObservable` directly and want to apply projection? `thisArg` could be removed though.

**Comment by staltz** [comment]
I was somewhat assuming that if it's not in `Rx.ts` or `Rx.KitchenSink.ts`, then people wouldn't want to import it directly.

**Comment by blesh** [comment]
So we can do a few things:

1. Allow optional `project` and `thisArg` parameters to `Observable.from`. (I'm cool with the `project`, and I think the `thisArg` bit is gross)
2. Add a `fromIterator` static method that takes these arguments.
3. Remove `IteratorObservable`.

Thoughts?

**Comment by staltz** [comment]
(2) sounds better.

**Comment by blesh** [comment]
I'm going to resubmit this issue with a slightly clearer top comment so we can get some community concensus.  https://github.com/ReactiveX/RxJS/issues/1255
