### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#101]
It's paramount that we make sure this repository is inclusive. I don't want to turn off potentially brilliant contributions because they don't feel comfortable. I know the contributors thus far and I *really* doubt we will ever have a problem. Still, this repository is open to public contribution, so quality might vary.

As such, I think it's really important we have a Code of Conduct and that we enforce that Code of Conduct. 

[http://contributor-covenant.org](http://contributor-covenant.org) was recommended, and it looks pretty solid.

**Comment by mattpodwysocki** [comment]
@blesh please don't reinvent the wheel.  RxJS already had one.  Please use that: https://github.com/Reactive-Extensions/RxJS/tree/master/doc/contributing#code-of-conduct

**Comment by blesh** [comment]
@mattpodwysocki I didn't reinvent anything. The CoC I've added was pre-existing and popular. I honestly didn't see the CoC in RxJS, I didn't think to look in the Contribution Guidelines. Is there something drastically wrong with the one I put up?

**Comment by mattpodwysocki** [comment]
@blesh there's no need to change the one we already had, that's my point.  RxJS has had for quite some time a CoC. Why add/change what we already had?

**Comment by blesh** [comment]
> Why add/change what we already had?

> I honestly didn't see the CoC in RxJS, I didn't think to look in the Contribution Guidelines.

Since there's one in there now, I could *change* it again to whatever you have, then notify @CarolineAda that we won't be using her CoC. Then I'll need to submit a PR to that repo, to have our name removed from the list. 

I actually liked us being part of a more unified effort toward equality in this arena. Seems like unnecessary effort to change again if there is nothing wrong with the one we have in place now, though.

Regardless, I think it should be it's own, all-caps file in the root directory, and linked at the top of our README.

**Comment by blesh** [comment]
@mattpodwysocki We will definitely reuse everything we can from the RxJS Contribution Guidelines. Is there anything else like that you feel we should pay special attention to?

**Comment by mattpodwysocki** [comment]
@blesh Please look or ask before doing this in the future as we had things already defined.  The CoC was very precise in its language as I put a bit of time and effort into this and to have it just chucked out unnerves me.

**Comment by jeremymwells** [comment]
I don't see how utilizing a pre-existing CoC is reinventing the wheel. In my estimation, contributor covenant seems more aligned with community guidelines as regards CoC because it _is_ a community-endorsed set of guidelines for CoC.

**Comment by thejameskyle** [comment]
The Contributor Covenant is an [open](https://github.com/CoralineAda/contributor_covenant) and [peer reviewed](https://github.com/CoralineAda/contributor_covenant/graphs/contributors) document that is maintained by people of many backgrounds and has been adopted by [dozens of major projects](http://contributor-covenant.org/adopters/).

As a member of the LGBT community and as a person who cares very much about diversity, especially in technology, I strongly recommend keeping the Contributor Covenant.

:+1: to close as resolved.
