### ISSUE TITLE
Type Definitions are empty for "add" modules

### ISSUE THREAD

**Issue by robwormald** [ReactiveX/RxJS#1010]
The generated `d.ts` files that correspond to the "patch" operator and observable files are empty, so they are picked up by typescript as invalid modules and the compiler errors:
```
error TS2656: 
Exported external package typings file 'node_modules/rxjs/add/observable/fromEvent.d.ts' is not a module. Please contact the package author to update the package definition.
```

This means TS users are unable to do the desired `'import rxjs/add/operator/map' ` use case. 

Workaround for angular2 users discovering this issue is to simply `'import rxjs/Rx'` which will add all the operators and observables in the meantime without error. 

This appears to go all the way back to alpha.11, which is when the /add syntax was introduced.

**Comment by robwormald** [comment]
cc @jeffbcross @IgorMinar

**Comment by jeffbcross** [comment]
What version of TypeScript shows this error?

**Comment by jeffbcross** [comment]
I reproduced this error with TS 1.7.2, but not 1.6.2. @robwormald is going to talk with TypeScript folks about the best way to solve this.

**Comment by jeffbcross** [comment]
Assigned to myself as a proxy @robwormald :)

**Comment by blesh** [comment]
@robwormald if you could please reference this issue in whatever discussion you have with the TypeScript people, I'd appreciate it. Just so the issues are linked.

**Comment by robwormald** [comment]
Confimed as a bug in Typescript:
```
a module is defined as a file is at least one top level import or export

the build will elide imports that are never used in an exported enitity when it builds the .d.ts file (it assumes it is an implementation detail, that should not be exposed in the declaration file)

the combination results in a declaration file that is not a valid module.

so we should take that in account in that when we are running the check on the file
```

**Comment by robwormald** [comment]
temporary workaround is to spoof an export into the patch modules to force *something* to be emitted in the `.d.ts` files:
```typescript
export type _void: void;`

```
