### ISSUE TITLE
Rename scan to fold?

### ISSUE THREAD

**Issue by staltz** [ReactiveX/RxJS#1015]
I don't have high hopes for this proposal, since due to conservatism there is a strong gravity to keep `scan`, but here goes nothing.

I've always scratched my head with "why is scan called scan?". The name doesn't convey its semantics properly.

`scan` is really just like `fold` from Functional Programming. `fold` is a very well establish name in FP community. Also Elm's `scan` is `foldp` as in "fold from the past". Fold just makes sense. If you imagine the Observable as a timeline of events, if you fold that timeline like you would with origami, it's gonna reduce the events.

So, since we're still in alpha, now would be the best time to rename it. We already have a lot of drastic renames such as `flatMap` => `mergeMap`, so why not fix others as well, like `scan` => `fold`?

PS: same amount of characters. ;)

**Comment by mattpodwysocki** [comment]
@staltz because it's exactly the same as Haskell's [`scanl`](https://www.haskell.org/hoogle/?hoogle=scanl) and that's where we got the name.

**Comment by staltz** [comment]
Ah, that's where it came from. Thanks, I finally know.

Anyway, since Haskell's `foldl` is JavaScript's `reduce`, why can't Haskell's `scanl` be JavaScript's `fold`?

**Comment by blesh** [comment]
I think `scan` is probably one of the more widely understood operators, honestly. I'd hate to rename it. When I've heard other people talk about Rx, they usually mention it in terms of "a reduce that emits its accumulated value every time".

**Comment by mattpodwysocki** [comment]
@staltz please, let's not fork the name to get people confused as to something that is well understood in other languages such as [Haskell](https://www.haskell.org/hoogle/?hoogle=scanl), Scala, [F#](https://msdn.microsoft.com/en-us/library/ee370366.aspx)

**Comment by blesh** [comment]
Also, FWIW: `flatMap` will remain as an alias forever, as far as I'm concerned, because it's pretty idiomatic. `mergeMap` is so named because it makes it easier for people to understand and it's more conventional.

**Comment by staltz** [comment]
Oh well, this won't proceed, so carry on folks.
