### ISSUE TITLE
empty *.d.ts definitions in e.g. rxjs/add/observable/from.d.ts in version 5.0.0-alpha-14

### ISSUE THREAD

**Issue by vladimir-ivanov** [ReactiveX/RxJS#1017]
trying to use rxjs with angular2 (which includes 5.0.0-alpha-14 internally) and getting this

import "rxjs/add/observable/form"; 

(18,8): error TS2656: Exported external package typings file 
'/node_modules/rxjs/add/observable/from.d.ts' is not a module. Please contact the package author to update the package definition.

**Comment by kwonoj** [comment]
Is this issue https://github.com/ReactiveX/RxJS/issues/1010 ?

**Comment by vladimir-ivanov** [comment]
yes, closing, thank you
