### ISSUE TITLE
Add partition operator (or not)

### ISSUE THREAD

**Issue by robwormald** [ReactiveX/RxJS#104]
So I'd already done this by the time @blesh replied :shipit: https://github.com/ReactiveX/RxJS/pull/103

Ergonomically it feels nicer for an if/else type situation, but as perf is the word I'll defer to the experts and I promise to not get all offended if groupBy is preferable :wink:

**Comment by Foxandxss** [comment]
I like the idea. I am not an expert thought, but as an end user and after playing with the idea, I think it is cleaner to "see" what's going on.
