### ISSUE TITLE
upgrade system-builder dependency for Rx.js bundle

### ISSUE THREAD

**Issue by jeffbcross** [ReactiveX/RxJS#1068]
The Rx.js bundle currently uses an old version of system builder, the same version that angular/angular currently depends on. I used this version to ensure no mismatches between rxjs and angular. When https://github.com/angular/angular/issues/4354 lands, we can update the builder here, too.

**Comment by blesh** [comment]
@jeffbcross where does this stand?

**Comment by blesh** [comment]
Since this has been inactive for some time, I'm closing it @jeffbcross
