### ISSUE TITLE
CDN for beta.0 not working

### ISSUE THREAD

**Issue by filipesilva** [ReactiveX/RxJS#1072]
CDN for beta.0, as per readme, doesn't seem to work:
https://npmcdn.com/@reactivex/rxjs@5.0.0-beta.0/dist/global/Rx.js

Is this the new one? I poked around for a bit and it seems to be match
https://npmcdn.com/@reactivex/rxjs@5.0.0-beta.0/dist/global/Rx.umd.js

**Comment by kwonoj** [comment]
Think you just hit cases before this PR (https://github.com/ReactiveX/RxJS/pull/1070) lands in, points latter as you tried :)

**Comment by kwonoj** [comment]
I just checked in changes and believe issue's now resolved, closing it. Please feel free to reopen if it's required.

**Comment by filipesilva** [comment]
Can confirm, CDN gets me the right file. Cheers!
