### ISSUE TITLE
Implement Observable.amb (as Observable.race)

### ISSUE THREAD

**Issue by saneyuki** [ReactiveX/RxJS#1075]
We still don't have [`Observable.amb()`](http://reactivex.io/documentation/operators/amb.html) operator.

This operator is useful in these case to take a 1st returned value like `Promise.race()` with dispatching some operations optimistically.

**Comment by blesh** [comment]
I discussed this one with @trxcllnt a while back. I think we even postulated that it should be named `race` instead of `amb`.  @mattpodwysocki what are your thoughts?

**Comment by mattpodwysocki** [comment]
@blesh [`Observable.race`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/race) is ok with me given the `Promise.race`

**Comment by justinwoo** [comment]
Now in master at https://github.com/ReactiveX/RxJS/commit/ee3b593996096c90a07670b728835424717e9936

**Comment by kwonoj** [comment]
Closing issue by changes are checked in.
