### ISSUE TITLE
groupBy not using lift 

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#1085]
The current implementation of groupBy is no longer using `lift`. This actually muck with some other plans in the works for logging and debugging hooks.

GroupBy should be refactored to use `lift`.

[If you look at it](https://github.com/ReactiveX/RxJS/blob/6303558668016409315bfcd81b5b5f188a4cb174/src/operator/groupBy.ts#L25-L32) the `GroupByObservable` is really just a factory for a `Subscriber`. That's what we use `Operator` class for. I clearly didn't review this one very well when I merged it a long time ago. It seems that `RefCountSubscription` instance could be folded into the operator's subscriber as well.

**Comment by trxcllnt** [comment]
@blesh I noticed this too. I'm working through a fix for `ConnectableObservable`, but don't have time to update `groupBy` just yet.

**Comment by staltz** [comment]
I did that. At the time groupBy wasn't passing tests at all, so I just followed how RxJS 4 implemented it.
