### ISSUE TITLE
npm distribution and source maps

### ISSUE THREAD

**Issue by pkozlowski-opensource** [ReactiveX/RxJS#1089]
Files distributed to npm got source maps (which is good!) but those source maps are pointing to source file that are not included. An example from `Operator.js.map`:

> {"version":3,"file":"Operator.js","sourceRoot":"","sources":["../../src/Operator.ts"],"names":["defaultCallFn"],"mappings":"AACA,2BAAyB,cAAc,CAAC,CAAA;AAMxC,uBAAoC,QAAqB;IACvDA,MAAMA,CAACA,IAAIA,uBAAUA,CAAIA,QAAQA,CAACA,CAACA;AACrCA,CAACA;AAFe,qBAAa,gBAE5B,CAAA"}

See this little `"sources":["../../src/Operator.ts"]` thingy here? 

2 solutions I can think of:
* inline
* distribute sources

**Comment by kwonoj** [comment]
I considered inline source map one time and deferred those decision due to concern's of increasing general library size. Between 2 options suggested, leaning to inline source map though. Thanks for bringing this up, might need some investigations if there's any recommended patterns.

**Comment by pkozlowski-opensource** [comment]
@kwonoj thnx for looking into this one. I've got the same concerns with inlined source maps as you, but both options work for me.

**Comment by david-driscoll** [comment]
Isn't it possible to redirect the source map to a url, we could in theory
use the sourceMapUrl and sourceMapRoot and map directly to the specific
github commit.  It would take a build step to rebuild the source map urls
though.

**Comment by pkozlowski-opensource** [comment]
@david-driscoll It is not only about having source maps in a browser but also available for consumption by bundlers like browserify or webpack.  I would much, much prefer having source maps as part of the npm distribution.

**Comment by kwonoj** [comment]
> Between 2 options suggested, leaning to inline source map though

: Just clarifying once again to be crystal clear, I'm not plan to go ahead to inline source map for build to be deployed. It's just preference 'between..'. In current state, I'll try to spend some time and not sure which conclusion will be.

> we could in theory use the sourceMapUrl and sourceMapRoot and map directly to the specific github commit. 

: I agree in @pkozlowski-opensource for this, if we're shipping source map I'd like to it served for all cases. Though it's interesting approach - wish it could be applicable everywhere. @david-driscoll  Do you may possibly have any references?

**Comment by robwormald** [comment]
This should be easy enough to turn on purely for the dist steps that we build for our npm distributions, I think. Let's keep it simple!

**Comment by robwormald** [comment]
There's an option in the tscompiler config - `mapRoot` - that allows us to redirect the path @pkozlowski-opensource mentioned. so we could just copy the src/ dir to dist/cjs/src and remap to there. Thoughts? I'll do a quick PR if this is okay by y'all.

**Comment by robwormald** [comment]
#yolo

**Comment by kwonoj** [comment]
@robwormald so does angular2 deploys source as well as transpiled result + source maps?

**Comment by pkozlowski-opensource** [comment]
> so does angular2 deploys source as well as transpiled result + source maps?

Yes. Actually multiple transpilation results (TS->ES6, TS->ES5, both with and without sourcemaps)

**Comment by kwonoj** [comment]
Maybe I was thinking in way too complex.. :) I'm fine with those approach too, but it's changing deployment build would like to hear some other opinions too. /cc @blesh

**Comment by blesh** [comment]
@robwormald has a PR #1093 on this, just waiting for a rebase so we can merge it in.

**Comment by robwormald** [comment]
I'll do it this afternoon, thanks for the reminder

**Comment by blesh** [comment]
@pkozlowski-opensource @robwormald @kwonoj @david-driscoll ... is this issue still an issue? @robwormald closed his other PR without merging it. It's holding up the beta.2 release.

**Comment by kwonoj** [comment]
@blesh , yes, it's not yet resolved. Let me try to spend some time to bring up PR. Meanwhile if this is blocking b2 release, what about make this issue out of b2 milestone?

**Comment by blesh** [comment]
Punting this to the next release since the urgency of it seems to have been lost/forgotten.

**Comment by trxcllnt** [comment]
@blesh can we at least switch to compiling inline sourcemaps then? tools like webpack's [`source-map-loader`](https://github.com/webpack/source-map-loader) can compile them, but chokes at build time when the source files they reference aren't there.

**Comment by robwormald** [comment]
doing them alongside works fine, its the coverage stuff that explodes and i have no idea what's going on with coverage. if somebody wants to debug that with me, i'd be happy to run through it.

**Comment by kwonoj** [comment]
I had introduced source map mapping for code coverage - will take a look if I can resolve those issue shortly, after suppress current burning issue at my work.
