### ISSUE TITLE
Remove or change ScalarObservable method optimizations? 

### ISSUE THREAD

**Issue by blesh** [ReactiveX/rxjs#1095]
The optimizations done to ScalarObservable a while back had major performance improve improvements for those cases, but the downside as discussed at the time, was you'd not be able to use the say, `map` to reliably produce side-effects.

I just want to revisit this now that we're in beta. 

Does it require too much mental overhead for the perf benefit? 

Has anyone run into an issue with this so far?

**Comment by trxcllnt** [comment]
@blesh something that concerns me is the eager evaluation of ScalarObservables isn't in line with the overarching philosophy of lazy evaluation. Subscribing to an observable should re-execute its `subscribe` function every time, full-stop.

**Comment by blesh** [comment]
@trxcllnt the idea was that ScalarObservables are always a known value, and there for something like `Observable.of(2).map(x => x + 1)` could just be `Observable.of(3)`. It still doesn't give you a value unless you subscribe to it.

The danger here, of course, is that `x => x + 1` doesn't get executed when some people might expect it. So if they're trying to create side effects there, it will really matter.

The other danger is that maybe it's `Observable.of(1).map(doSomethingExpensive)`, and you might not want `doSomethingExpensive` executed until you subscribe.

I'm on the fence on it. The performance improvements are compelling, but I feel like perhaps the use cases we're optimizing for in this case are edge cases, and not worth the danger to those that would try to use the mapping function to create side effects.

**Comment by blesh** [comment]
This was done forever ago.
