### ISSUE TITLE
Map, Filter, Some, Every must match Array semantics

### ISSUE THREAD

**Issue by mattpodwysocki** [ReactiveX/RxJS#110]
The implementations of `map`, `filter`, `some`, `every` et al must follow the contract of:
```js
Rx.Observable.prototype.map = function (fn, thisArg) { }
```

The `fn` parameter must have:
1. The current value
2. The current index
3. The current Observable

**Comment by blesh** [comment]
cc/ @zenparsing and @jhusain ... if/when ES7 Observable has these sorts of methods, will the above hold true? I know it's been discussed, but I don't feel like it's been written down on the internet. heh.

**Comment by mattpodwysocki** [comment]
@blesh in order to conform with the existing RxJS implementation, it would be ideal, especially since the .NET implementation also follows this minus the `thisArg` and the `Observable` in the callback

**Comment by blesh** [comment]
@mattpodwysocki ... I'd like to conform to one or the other. Right now I guess I'm leaning in favor of the existing RxJS implementation because that's actually something tangible. However, I am *very* interested in meeting the spec if it ever includes that. I suppose if the spec is different, that is what semver is for.

:+1: for meeting the RxJS spec on these.

**Comment by blesh** [comment]
One thing we'll want to be careful of though, is that `thisArg`, using `bind`, `call`, `apply` might have adverse performance implications. We'll want to set up performance tests around this.

**Comment by mattpodwysocki** [comment]
@blesh we're already careful with our `bindCallback` function which determines whether there is a need to do a `Function#call` based upon the `thisArg` being defined.

**Comment by blesh** [comment]
@mattpodwysocki I know, I just wanted to drop a note in here incase a community member got gung-ho with a PR. ;)

**Comment by blesh** [comment]
Per a discussion from a meeting today with myself @trxcllnt, @ktrott and @steveorsomethin: 

@blesh `filter`, `map`, `reduce`, `every` and `some` matching the same signature as Array doesn't seem to make sense. What good is an index on something that isn't indexed? You can't get something from an Observable by and index. What does this mean in terms of a "hot" observable? What index does that return?

@blesh Is there a particular use case for the `thisArg` that makes sense or isn't already covered by arrow functions or bind?

@trxcllnt: not really, no.

@blesh: What could we use the Observable argument passed in for?

**Comment by blesh** [comment]
Aside from backwards compatability with RxJS 2/3, I can't think of a compelling reason to add this feature. 

hat am I missing? @mattpodwysocki, given that this library will be at least one major semver different than current RxJS, is it really an issue to break compatibility?

**Comment by zenparsing** [comment]
@blesh I agree with pretty much all of that.  What was the rationale for .NET's filter ("Select", right?) to include the psuedo-index?  I just assumed that it was for conveniently doing things like selecting the first n records or maybe tiger-stripping stuff.  Of course, all of that is possible with other combinators.

`thisArg` is a legacy oddity in my mind.  There's not too much harm in including it, but there's also very little gain.

**Comment by roganov** [comment]
I sometimes use indexes in observables as pseudo IDs. How would I enumerate an observable in RxNext? `zip` with `range`?
I'm not sure about `thisArg`, but indexes are useful IMHO.

**Comment by blesh** [comment]
@roganov ... the same way you could in current RxJS, really. `map`, `filter`, etc, all ended up having an index argument.   `myObs.map((value, index) => ({ value, index }))` would totally work

**Comment by roganov** [comment]
@blesh Sorry, I mistakenly conjectured from
>What good is an index on something that isn't indexed? You can't get something from an Observable by and index. What does this mean in terms of a "hot" observable? What index does that return?

that you decided not to implement this feature.

**Comment by blesh** [comment]
@roganov ... perhaps I was convinced offline and didn't convey that on GitHub? I dunno what happened.

The long and short of it was this: I tested it with and without the indexing, and it didn't hurt performance. I still feel the `thisArg` is relatively useless, but that's a matter of personal opinion.

**Comment by zenparsing** [comment]
@blesh So are you adding support for "thisArg"?

Also, do you think the index should be clamped to Number.MAX_SAFE_INTEGER?  Array indices, string lengths, etc. are limited to that number.

**Comment by blesh** [comment]
@zenparsing 

> So are you adding support for "thisArg"?

Yes. support is already there.

> Also, do you think the index should be clamped to Number.MAX_SAFE_INTEGER?

Probably not, since an Observable is not bound by anything.
