### ISSUE TITLE
Observable.fromEvent does not pass all event arguments to selector

### ISSUE THREAD

**Issue by earlsioson** [ReactiveX/RxJS#1100]
In the following code, the third argument of eventEmitter.emit is undefined when returned from the selector function. To see if this was an rxjs 5.0 issue, I ran the same code using rx 4.0.7 and discovered that the third argument does return the value 'quux'. I checked both the ChangLog and Migration docs for more info on fromEvent but did not see anything that would help.

```javascript
var EventEmitter = require('events').EventEmitter,
    Rx = require('rxjs');

var eventEmitter = new EventEmitter();

var source = Rx.Observable.fromEvent(
  eventEmitter,
  'data',
  function (foo, bar) { return { foo: foo, bar: bar }; });

var subscription = source.subscribe(
  function (x) {
    console.log('Next: foo -' + x.foo + ', bar -' + x.bar);
  },
  function (err) {
    console.log('Error: ' + err);
  },
  function () {
    console.log('Completed');
  });

eventEmitter.emit('data', 'baz', 'quux');
```

**Comment by kwonoj** [comment]
Yes, seems only first argument is emitted. Will try to look into to see if there's any suspicious..

**Comment by earlsioson** [comment]
Please review pull request https://github.com/ReactiveX/RxJS/pull/1101 for a potential fix.

**Comment by kwonoj** [comment]
Closing this via PR #1101 .
