### ISSUE TITLE
Operators By Category Interface

### ISSUE THREAD

**Issue by HighOnDrive** [ReactiveX/RxJS#1102]
Presently the only new documentation site for RxJS v5 I know of is here: http://reactivex.io/RxJS. As someone learning RxJS I found the Operators By Category section on the older RxJS v4 site very useful: http://reactivex.io/documentation/operators.html

Maybe some speed dial search buttons for operators in specific categories could be added to the header of the new site? Looks like there would be room next to the super slick but general search field. If space gets tight then just put all the the operator speed dial icons in a mini-palette that also expands out from one icon that is hovered over, like the search field does now.

The table on the Source page could also have a column for what category a operator is in: http://reactivex.io/RxJS/source.html

These are just ideas to help developers access RxJS information in quicker and smarter ways, I'm sure the new site will work great when it is completed. Any idea on when that might be?

**Comment by trxcllnt** [comment]
@HighOnDrive We definitely want to include/update the docs for the new library. The decision trees also live in the [RxJS v4](https://github.com/Reactive-Extensions/RxJS) docs ([static](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/gettingstarted/which-static.md) and [instance](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/gettingstarted/which-instance.md)), but need to be updated for the new version. As for timing, I can't say when v5 will be done, but hopefully in the next few months. We'll probably start working more heavily on documentation when we feel confident the core operators and implementation are finalized.

**Comment by HighOnDrive** [comment]
@trxcllnt Sounds good, looking forward to the updates, will keep working with what is available. It will be fantastic to work with RxJS v5 in cycle.js.org, which just released a major new version, synergising dataflow and components in new and powerful ways.

**Comment by blesh** [comment]
I'm going to close this since discussion has died down... but cc @staltz, because he's on point with the documentation work ATM.
