### ISSUE TITLE
Subject.asObservable() missing?

### ISSUE THREAD

**Issue by frankbenoit** [ReactiveX/RxJS#1108]
Hi

either it is missing, or it is missing in the migration guide?

Frank

**Comment by staltz** [comment]
Missing in the migration guide. At least from my perspective it seems we are intentionally removing it instead of forgetting to add it. Is that correct @blesh @kwonoj @trxcllnt ?

**Comment by blesh** [comment]
Yes. Unless there's a compelling reason to add it.

**Comment by mattpodwysocki** [comment]
@blesh of course there's a compelling reason to add it.  For example, exposing Subjects directly is usually a code smell, instead you want to hide the ability for the consumer of the API to send `next` calls, etc to it, so to call `asObservable` prevents that.

**Comment by blesh** [comment]
Fair, but is that a solid enough reason to add the weight to the type, though?

(honestly just playing devil's advocate)

**Comment by mattpodwysocki** [comment]
@blesh absolutely, as there is little to no overhead in doing so as in RxJS v4 [`asObservable`](https://github.com/Reactive-Extensions/RxJS/blob/master/src/modular/observable/asobservable.js)

**Comment by blesh** [comment]
Yep. Just want the consideration in the issue. I totally agree we should add it.
