### ISSUE TITLE
Please add the waterfall

### ISSUE THREAD

**Issue by frankbenoit** [ReactiveX/rxjs#1109]
Çan the waterfall be added to the lib?
See https://github.com/Reactive-Extensions/RxJS/issues/73

**Comment by staltz** [comment]
I would not add this to RxJS 5 Core, because it can be trivially built with mergeMap/concatMap, and we should avoid adding more operators just for the sake of having more.

**Comment by kwonoj** [comment]
Agreed, since in RxJS 5 we're trying to not to expand api surface too much. If `waterfall` has convincible usecases of it'll be used quite commonly then it's feasible to add as operator though it can be composed via existing operator. @frankbenoit , would you able to elaborate more details for this need to be added as operator instead of composing via existing operator?

**Comment by frankbenoit** [comment]
I am to new to this rx concepts at all. I found this implementation very short, but not trivial. 
Hence i thought it would be good to have it in the lib. Same as the other async functions like doWhilst, ...
However if it seems to be inappropriate, close this.

**Comment by kwonoj** [comment]
I don't think it's 'inappropriate' :) just trying to find balances between expanding api. @staltz, would you able to bring up small snippets in you mind via mergeMap/concatMap ? to @frankbenoit may able to see it also.

**Comment by blesh** [comment]
AFAICT, `x.waterfall(a, b, c)` is the same as `x.mergeMap(a).mergeMap(b).mergeMap(c)`

**Comment by trxcllnt** [comment]
I'm not sure if this was ever in the .NET version, but the [AS3 implementation](https://github.com/richardszalay/raix) called this method [`chain`](https://github.com/richardszalay/raix/blob/master/source/raix/src/raix/reactive/IObservable.as#L148) [(source)](https://github.com/richardszalay/raix/blob/master/source/raix/src/raix/reactive/AbsObservable.as#L631).

```es6
Observable.prototype.chain = function(...selectors) {
  return selectors.reduce(function(observable, selector) {
    return observable.mergeMap(selector);
  }, this);
};
```

**Comment by blesh** [comment]
@trxcllnt I can't imagine that is going to perform as well as just chaining the mergeMap operator to begin with. I suppose I can see the utility, I'm just unsure that it's worth us maintaining. I'm open to other thoughts on it though.

**Comment by frankbenoit** [comment]
Here is my example code, using mergeMap and nedb.
As fromNodeCallback is not yet available, i need to do manual error passing.
Can this be written more elegant? Do i have problems in this code?
Could an RX internal waterfall implementation help here?

I marked waterfall relevant lines with (*)

    // delete an item from db, return the deleted item, after deletion.
    delete( id : string ): Rx.Observable<TypeA> {
        let self = this;
        return Rx.Observable.of(0) // (1)
            .mergeMap( (_) : Rx.Observable<TypeA> => {  // (2)
                // find in db
                var s = new Rx.Subject<TypeA>();  // (3)
                self.db.find({type:'x', id:search_id}, function(err: any, docs: any){
                    if( err ) { 
                        s.error(err); 
                    }
                    else if( docs.length !== 1 ){
                        s.error(new Error('docs length not 1: '+docs.length));
                    }
                    else {
                        let p = docs[0];
                        s.next(new TypeA( p.id, p.name ));  // (4)
                        s.complete(); // (5)
                    }
                });
                return s; // (6)
            }).mergeMap( (x:TypeA) : Rx.Observable<TypeA> => {  // (7)
                // delete in db and return the deleted data
                var s = new Rx.Subject<TypeA>(); // (8)
                self.db.remove({type:'project', id:x.id}, (err: any, numRemoved: number) => {
                    if ( err ) {
                         s.error(err);
                    }
                    else if( numRemoved !== 1 ){
                        s.error(new Error('not deleted one: '+numRemoved));
                    }
                    else {
                         s.next(x); // (9)
                         s.complete(); // (10)
                    } 
                });
                return s; // (11)
            });
        );
    }

**Comment by blesh** [comment]
@frankbenoit .. it looks mostly okay. You'd be better off returning an `Observable` in each of those `mergeMap` steps, rather than a `Subject` though. Subjects have additional overhead because they maintain a list of observers under the hood (because they multicast).

Also, it looks like you're using `Observable.of(0)` just to start the chain because you're not really using it. This means you could just start with the Observable you're `mergeMap`-ing to. You could just do something like: 

```js

delete(id: string): Observable<TypeA> {
  return Observable.create(o => {
      this.db.find({ type: 'x', id: search_id }, (err, docs) => {
          if (err) {
              o.error(err);
          } else if (docs.length !== 1) {
              o.error(new Error('docs length not 1: ' + docs.length));
          } else {
              const [{ id, name }] = docs;
              o.next(new TypeA(id, name));
              o.complete();
          }
      })
  }).mergeMap((x: TypeA) => Observable.create(o => {
      this.db.remove({ type: 'project', id: x.id }, (err: any, removed: number) => {
          if (err) {
              o.error(err);
          } else if (removed !== 1) {
              o.error(new Error('not deleted one: ' + removed))
          } else {
              o.next(x);
              o.completed();
          }
      })
  })
}
```

That probable doesn't answer any thing WRT `waterfall`, but hopefully it's helpful.

**Comment by frankbenoit** [comment]
@blesh I think this is relevant. Because if the sequence can be written in a good way, the waterfall is not needed in the lib.
Your fix removed half of the needed lines for creating/returning the subject.
So the pattern can be this:

    myAsyncFunc(): Observable<TypeC> {
        return Observable.create((o:Observer<TypeA>) => {
            ...
        }).mergeMap((x: TypeA) => Observable.create((o:Observer<TypeB>) => {
            ...
        })).mergeMap((x: TypeB) => Observable.create((o:Observer<TypeC>) => {
            ...
        }));
    }

Note nice: the extra parenthesis for second and later mergeMap calls.

    })).mergeMap


A weakness is see is, there is no typed coupling between TypeA and the first argument type of the mergeMap. Seems like everything is accepted.

    myAsyncFunc(): Observable<TypeC> {
        return Observable.create((o:Observer<TypeA>) => {
            ...
        }).mergeMap((x: number /* this should fail? */) => Observable.create((o:Observer<TypeC>) => {
            ...
        }));
    }

Should this be a bug for Observable.create, as it should accept a type argument?
Then the argument type can be inferred.

        return Observable.create<TypeA>((o) => {

**Comment by frankbenoit** [comment]
At runtime, i get this error for mergeMap:

    Observable_1.Observable.create(...).mergeMap is not a function

This depends on the import. Using "import * as Rx from 'rxjs'" with Rx.Observable work. Using "import {Observable} from 'rxjs/Observable'" gives the error above at runtime.

**Comment by kwonoj** [comment]
>  Using "import {Observable} from 'rxjs/Observable'" gives the error above at runtime.

: Yes, it's expected to import operator separately as needed if you're importing core `Observable` only.
https://github.com/ReactiveX/RxJS#commonjs-via-npm

**Comment by blesh** [comment]
Closing this issue as stale.
