### ISSUE TITLE
RxJS must adapt to the existing RxJS unit tests

### ISSUE THREAD

**Issue by mattpodwysocki** [ReactiveX/RxJS#111]
Will be migrating tests to Jasmine for 3.x.  If 4.x does not have these tests that mimic the exact behavior of RxJS 3.x, then it's a no go for me.

**Comment by blesh** [comment]
> Will be migrating tests to Jasmine for 3.x.

That's perfect.

> exact behavior

This is a major version different. I think this expectation should be gauged. `multicast` for example, will not have the exact, same behavior, as it's moved to only take a `Subject` factory: `multicast(() => new Subject())`

That said, I'm excited about not rewriting tests. ;)

**Comment by trxcllnt** [comment]
#14

**Comment by blesh** [comment]
Given that we're all in agreement about this need/effort, and there's a lot of work underway to get us there. I'm going to close this issue only because it's just a general call-to-arms from the past that we've already heeded.
