### ISSUE TITLE
Add throttleLast/inspect operator

### ISSUE THREAD

**Issue by mgamsjager** [ReactiveX/RxJS#1112]
> ### EDIT: to clarify the purpose of this issue (@blesh)
> 
> There is discussion below that brings to light a missing `inspect` or `throttleLast` operator.
> 
> It [starts here](https://github.com/ReactiveX/RxJS/issues/1112#issuecomment-167877365)
> 
> ... now for the original text:

---

Trying out Angular2 with Rxjs beta0.

Copied from this http://jsfiddle.net/bo6ynqf7/3/

From my service: 

```javascript
import {Subject, Observable} from "rxjs/Rx";
var sub = new Subject();
sub.throttleTime(1000).subscribe(res => console.log(res) );
sub.next(value);
```

When I substitute throttle with debounce then it works. Because beta0 isn't on the a CDN I can't provide a failing jsfiddle (sorry :( )

**Comment by kwonoj** [comment]
Would you able to share some more details of doesn't work, doesn't it emit any values? or if it emits, doesn't it work as you've expected?

**Comment by mgamsjager** [comment]
Well it does emit values because the console get's filled with values. What does not work is the throttle itself. The value variables are keys that are entered in an input field. I would expect the throttle to slow down the speed at which the keys are logged to the console

**Comment by trxcllnt** [comment]
@kwonoj I'd venture a guess what @mgamsjager wants is (what I've been calling) `inspectTime`. Where `throttleTime` emits the value that triggers the `throttle` operation (the first event), I believe it's also valuable to have an operator that emits the *last value* that came in before the `throttle` delay completes. Here's a reference implementation:

```es6
import { asap } from 'rxjs/scheduler/asap';
import { Scheduler } from 'rxjs/Scheduler';
import { Subscriber } from 'rxjs/Subscriber';
import { Observable } from 'rxjs/Observable';
import { Subscription } from 'rxjs/Subscription';

function inspectTime(delay, scheduler = asap) {
    return this.lift(new InspectTimeOperator(delay, scheduler));
}

class InspectTimeOperator {
    constructor(delay, scheduler) {
        this.delay = delay;
        this.scheduler = scheduler;
    }

    call(subscriber) {
        return new InspectTimeSubscriber(subscriber, this.delay, this.scheduler);
    }
}

class InspectTimeSubscriber extends Subscriber {

    constructor(destination, delay, scheduler) {
        super(destination);
        this.delay = delay;
        this.value = null;
        this.hasValue = false;
        this.scheduler = scheduler;
    }

    _next(value) {
        this.value = value;
        this.hasValue = true;
        if (!this.throttled) {
            this.add(this.throttled = this.scheduler.schedule(
                this.clearThrottle.bind(this), this.delay, this
            ));
        }
    }

    clearThrottle() {
        const { value, hasValue, throttled } = this;
        if (throttled) {
            throttled.unsubscribe();
            this.remove(throttled);
            this.throttled = null;
        }
        if (hasValue) {
            this.value = null;
            this.hasValue = false;
            this.destination.next(value);
        }
    }
}
```

**Comment by kwonoj** [comment]
Thanks @trxcllnt for fast reference implementation :)

Let's try to clarify issue if we're talking about unexpected behavior of operator or we do want new one as @trxcllnt assume.

In case of `throttleTime`, I'd expect it behaves 

```
var someObservable = cold('---x------x------x------x------x---|');
var someDuration = 100;  //  '----------|';
                                      //  '----------|';
var expected =            '---x------------x--------------x---|';
```

As above marble, that throttle takes one and drop emit from source while duration. Once duration's completes, it emits again then duration starts. @mgamsjager , would you clarify throttleTime won't work in this way, or either you'd expect different behavior such as `inspectTime` above?

**Comment by kwonoj** [comment]
Referencing current spec too. https://github.com/ReactiveX/RxJS/blob/master/spec/operators/throttleTime-spec.js#L35-L42

**Comment by mgamsjager** [comment]
Well bit of both. Given the way I use it is correct I would expect that when I enter a lot of input that some of it would not be emitted and not all input is logged to the console. This is not the case and works differently then the jsfiddle example with click events.

inspectTime looks the thing I want to be honest. I don't want that an array is filtered on every keyup event the user producing. I rather have a "timeout" after which the filter function is executed with the last value the user has entered. 

Given the marble @kwonoj  provided I would expect that I could accomplish that with throttleTime.

**Comment by kwonoj** [comment]
Isn't behavior you wanted `debounce`? (I know you mentioned this in first comment, just wanted to confirm)

**Comment by trxcllnt** [comment]
@mgamsjager to be honest, the definition of `throttle` threw me off initially too. I believe it takes the first value, as it's supposed to approximate "throttling" the *producer*, which (when Rx is extended to include a back-pressure story) would only emit the event that *initiated* the throttle timeout. In a back-pressure world, `inspectTime` wouldn't tell the producer to shut up, but it would drop its events on the floor until the throttle timeout resolves. Both of these are distinct from `debounceTime`, which restarts the throttle timeout each time a new event comes in.

**Comment by staltz** [comment]
Let me try to understand. I only speak marblesh.

**Throttle:**
```js
var source = cold('---a-x-y-z-----b--x--y--z--c----x--yz-d-|');
var delay =     time('----------|';
                             //  '----------|';
                                         //  '----------|';
var expected =    '---a-----------b-----------c----------d-|';
```

**"InspectTime":**
```js
var source = cold('---a-x-y-z-----b--x--y--z--c----x--yz-d-|');
var delay =     time('----------|';
                             //  '----------|';
                                         //  '----------|';
var expected =    '-------------z-----------z-----------z--|';
```

**Debounce:**
```js
var source = cold('---a-x-y-z-----b--x--y--z--c----x--yz-d-|');
var delay =           time('----|';
                                         //  '----|';
var expected =    '-------------z-------------c----------d-|';
```

**Comment by trxcllnt** [comment]
@staltz yes

**Comment by kwonoj** [comment]
Ahha, thanks for clarification.

**Comment by staltz** [comment]
Just in case this new operator gets materialized, a suggested name: ThrottleLast.

**Comment by mgamsjager** [comment]
@staltz thx for the clarification

**Comment by trxcllnt** [comment]
@staltz That's what I thought initially too, but thinking about a theoretical future RxJS with BP, `throttle` would pause the consumer until the timeout resolves, whereas `inspect` would let the consumer keep emitting, but ignore all but the last event before the timeout resolves. I'm just concerned about reusing a term that implies BP semantics for an operator that doesn't have them.

**Comment by staltz** [comment]
Yeah I get it, and I'm concerned a new name "inspect" when seen in a long list of operators would hint towards a new and unique operator, when in practices it's very similar to throttle.

**Comment by kwonoj** [comment]
Let's wrap up issue before proceed further discussions about details of new operator.

@mgamsjager - if you'd like to propose new operator (`inspect..`) to be included, would like to suggest change issue title to have better scope. Or either if you're ok with clarified behavior of current operator and would like to consider new operator in another chances, issue can be closed for now. Thoughts?

**Comment by mgamsjager** [comment]
The problem with debounceTime is that I get each value after the set time has passed which is not handy for this use case. 
````
source =  |---a---b---c---d--|
timeout       ---
                  ---
                       ---
                           ---

expect = |--------a---b---c---d---|  
````

So the proposed inspectTime/throttleLast seems to be the proper way to handle this use case.

**Comment by mgamsjager** [comment]
My last comment kinda got me thinking. The debounce behaviour is very different then what you guys describe how it should work.

What it comes down to is that I made a very stupid mistake in my code. I initialised a new Subject() on each keyUp event and subscribed each time to that new observable. 

Moved all that code to the constructor and just call the subject.next() on each keyUp event fixed it.

`debounceTime` now gives me the behavior I was looking for (last value after x time) and `throttleTime` does its' job as well. 

Sorry to have wasted your time :(

**Comment by blesh** [comment]
While @mgamsjager's issue has been resolved, it's probably worth investigating adding this operator, so I'm reopening the issue and renaming it.

**Comment by paulpdaniels** [comment]
I'm somewhat confused. Isn't the proposed operator just [sample](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/sample.md)?

**Comment by trxcllnt** [comment]
@paulpdaniels not quite: `sample` schedules its timeout upon subscription, and emits the most recent value it has received when its timeout resolves. `inspect` would schedule its timeout *the first time it receives an event*, and emit the most recent event value it has received when the timeout resolves.

**Sample:**
```es6
var source = cold('---a-x-y-z-----b--z--x--y--c----b--yc-d-|');
var delay =  time('----------|');
//                            '----------|';
//                                        '----------|';
var expected =    '----------z-----------x-----------b-----|';
```
**Inspect:**
```es6
var source = cold('---a-x-y-z-----b--z--x--y--c----b--yc-d-|');
var delay =     time('----------|');
//                               '----------|';
//                                           '----------|';
var expected =    '-------------z-----------y-----------c--|';
```

**Comment by staltz** [comment]
Yeah, I'm afraid no existing operator does this out of the box, not even Sample nor WithLatestFrom.

**Comment by kwonoj** [comment]
Closing issue by https://github.com/ReactiveX/RxJS/pull/1219 is now checked in, available as `inspect` and `inspectTime`.
