### ISSUE TITLE
Expose Observable.of as a standalone function

### ISSUE THREAD

**Issue by cburgdorf** [ReactiveX/RxJS#1113]
Currently one has to import `import 'rxjs/add/observable/fromArray';` in order to get `Observable.of` which is pretty confusing. Can we make it so that `import 'rxjs/add/observable/of';` works?

**Comment by kwonoj** [comment]
My assumption's https://github.com/ReactiveX/RxJS/pull/922#issuecomment-162967611 was intention for this which was not landed yet - 

>if we just rename observable/fromArray to observable/of, I think I'm okay just leaving these things out for now

Will update once @blesh confirms my understanding's correct.

**Comment by cburgdorf** [comment]
I see. Thanks for the quick response.

**Comment by blesh** [comment]
I think we can reasonably add an `add/observable/of` file, actually.

**Comment by cburgdorf** [comment]
I read that those are generated from [here](https://github.com/ReactiveX/RxJS/blob/master/tools/generate-operator-patches.ts#L204) but I don't get exactly what to do to make it generate an `add/observable/of` file. Or should I just create it manually?

**Comment by blesh** [comment]
@cburgdorf you could create it manually, I believe, since there are no name conflicts. Just add a comment to the top of the file to indicate it was manually created (since the others have the same for auto created)

**Comment by cburgdorf** [comment]
Ok, guess this should do it https://github.com/ReactiveX/RxJS/pull/1197
I have some problems with the build since I don't have a proper Java environment. It's currently untested.

**Comment by luisgabriel** [comment]
`fromArray` is deprecated in RxJS 4. Couldn't we just rename `fromArray` to `of`?
