### ISSUE TITLE
Difference between importing from 'rxjs/Observable' vs just 'rxjs'

### ISSUE THREAD

**Issue by cburgdorf** [ReactiveX/RxJS#1114]
Does it make any difference whether I write `import {Observable} from 'rxjs/Observable';` or `import {Observable} from 'rxjs';`?

It seems as if `Observable`, `Subject` etc. are just re-expored for convenience but I like to double check if there isn't something that I'm overlooking.

**Comment by cburgdorf** [comment]
I think I did something entirely wrong that lead me to the assumption I could use `import {Observable} from 'rxjs'`. Closing.

**Comment by blesh** [comment]
@cburgdorf glad you got it straightened out. If you have any other issues let us know.
