### ISSUE TITLE
Implement Observable<T>.catch()

### ISSUE THREAD

**Issue by saneyuki** [ReactiveX/RxJS#1119]
We still don't have [`Observable.catch()`](http://reactivex.io/documentation/operators/catch.html) operator. This is need to catch some error which can recover from a fatal.

**Comment by saneyuki** [comment]
s/`Observable<T>.error()`/Observable<T>.catch()/

**Comment by saneyuki** [comment]
oops. Sorry. I missed https://github.com/ReactiveX/RxJS/blob/master/src/operator/catch.ts

**Comment by blesh** [comment]
:) Side note: `catch` now also provides a second argument of the "caught" source observable, so you can do a retry like so:  `s1.catch((err, source) => source)`.
