### ISSUE TITLE
All Creation Operators must use a Scheduler

### ISSUE THREAD

**Issue by mattpodwysocki** [ReactiveX/RxJS#112]
I'm noticing operators such as `empty` lack a scheduler, which is required because you can parameterize when/where empty happens.  All creation operators need a scheduler.

**Comment by blesh** [comment]
Yes, @trxcllnt and I had them in there, then removed them as a performance spike, then discussed re-adding them, but having gotten around to it. The idea that @trxcllnt and I discussed was creating fast-paths for things like the range operator if the `immediate` scheduler is being used.

**Comment by mattpodwysocki** [comment]
@blesh that's fine, but the default should be in there especially if you move to a `nextTick` scheduler.

**Comment by blesh** [comment]
In fact, labeling this as a bug, because it should have been re-added.
