### ISSUE TITLE
from, concatMap & publish operators combined - child Observable not completing

### ISSUE THREAD

**Issue by Nupf** [ReactiveX/RxJS#1120]
I believe I have found an edge case with publish & from: When publishing a child observable, concatMapping its parent values into Observable.from observables leads to the child not completing.

Running this with node 4.0 & RxJS 5.0.0-beta.0 logs only 'completed parent', not 'completed child'.
Interestingly, running the same code in a [jsbin](http://jsbin.com/behilopubi/1/edit?js,console) (RxJS 5.0.0-alpha.8) logs both.

    import { Observable } from 'rxjs';
    
    var parent = Observable
          .from([42])
          .publish();
    
    var child = parent
          .concatMap(value => Observable.from([value])) 
    // only happens with Observable.from; Observable.of(value) completes as expected. 
    // The same goes for mapping each value to itself before publishing. -> .map(value => value)
          .publish();
    
    child.subscribe(undefined, undefined, completed => console.log('completed child'));
    parent.subscribe(undefined, undefined, completed => console.log('completed parent'));
    
    child.connect();
    parent.connect();

**Comment by trxcllnt** [comment]
@Nupf have you seen this behavior from the code currently checked into master?

**Comment by Nupf** [comment]
@trxcllnt: works with the current master branch (dist/es6/Rx.js) - Thanks.
