### ISSUE TITLE
Interface Observer is not exported in rxjs

### ISSUE THREAD

**Issue by frankbenoit** [ReactiveX/RxJS#1122]
Using this import:
    import * as Rx from 'rxjs';

    Rx.Observable<MyType> --> OK
    Rx.Observer<MyType> --> Error

Module '".../node_modules/rxjs/Rx"' has no exported member 'Observer'.

**Comment by blesh** [comment]
Ah... just the TypeScript interface needs exported?  Makes sense.

As a temporary workaround, you can use the `@reactivex/rxjs` package from npm, and find the interface under `src`.

**Comment by divramod** [comment]
@kwonoj i have the same problem. can you give a little more detailed explanation how i can make observer.create running with typescript in version 5.0.0-beta.5?
