### ISSUE TITLE
subscribe method on Subscriber/Observer and unsubscription

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#113]
in speaking with @trxcllnt, he had the idea that `Subscriber.prototype.subscribe` could be used in a similar way to RxJava, but more uniquely for setting up disposal of resources in Observable chains.

The idea is (roughly), this: Each Observable constructor would be expected to set up disposal via a `subscribe` callback that was passed a single shared CompositeSubscription. So basically the whole Observable chain would share a single CompositeSubscription.

```js
var weirdExample = new Observable((subscriber) => {
  var sub1 = someObservable1.subscribe(subscriber);
  var sub2 = someObservable2.subscribe(subserver);
  subscriber.subscribe((subscription) => {
    subscription.add(sub1);
    subscription.add(sub2);
  });
});
```

It seems like this might deviate too far from the ES7 spec to be viable. But it might prove some interest performance benefits. Perhaps fewer object allocations and faster tear down?

Originally I had intended the `subscribe` function on the Observable interface to be a simple callback point for handling an even that fired when subscription had actually started. (Incidentally, it isn't wired up for this yet either).

**Comment by blesh** [comment]
Please review what I've said above, @trxcllnt, to make sure I've captured the spirit of your suggestion.

**Comment by trxcllnt** [comment]
@blesh this isn't quite what I was thinking, but it's moot now as the Subscribers are all sharing the same underlying Subscription.
