### ISSUE TITLE
Related functionality in other packages? Should we change the modular strategy?

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#1130]
I'd like to keep everything in this repository. [Here's a decent article on the advantages of the monolithic repository](http://danluu.com/monorepo/). While, I don't want to go Full-Facebook on it and get crazy. I think it has merit on a smaller scale.

#### Whether or not they should be in separate npm packages is what we're talking about

The hard part of this is figuring out the best way to manage supporting 3 different delivery styles: CJS, ES6 and globals if we're making these separate packages. Particularly since Observable ships with nothing on it in the CJS and ES6 cases. 

If things are in a separate package, then that package will need to reference `rxjs` or `rxjs-es`, depending. *Then* that package would need to import from those referenced rxjs packages, and not from the current repo. This means that any operators added by mutating the prototype on the Observable in the node_modules of that package might be different from elsewhere in the library. This is problematic.

**The easiest and cleanest solution is to have everything under one package.** But that will make some people unhappy because of "node_module bloat". 

I'm looking for any other proposed solutions to this problem.

**Comment by blesh** [comment]
Related #1115

**Comment by blesh** [comment]
### Shorter summary:

- 3 different ways to deliver RxJS (CJS, ES6 and global files)
- 2 of those (CJS, ES6) mutate the prototype of Observable to add operators
- If RxJS-DOM is a separate package, it will probably have it's own copy of Observable under it's own `node_modules`, meaning calls to `ajax` would return an Observable with no operators.

**Comment by blesh** [comment]
I'm wondering if we need to move away from the `import "rxjs/add/something"` style of mutation and go to something where to get the `Observable` constructor you have to call a factory that you pass the desired operators to.

**Comment by blesh** [comment]
To elaborate. I mean something like:

```js
import {ObservableFactory} from 'rxjs/ObservableFactory';
import {map} from 'rxjs/operators/map';
import {filter} from 'rxjs/operators/filter';
import {mergeMap} from 'rxjs/operators/mergeMap';

const Observable = createObservable(map, filter, mergeMap)

import {createAjax} from 'rxjs-dom/createAjax';

const ajax = createAjax(Observable);
```

where `Observable` is an observable with `map`, `filter` and `mergeMap` operators, and `ajax` is a function that returns an `Observable` created from the `Observable` constructor it was passed.

**Comment by blesh** [comment]
... we could also provide a fast-path for people that don't need this level of customization.

**Comment by staltz** [comment]
:+1: for the factory approach. Maybe we can take inspiration from Babel which is all plugin-oriented, with some presets.

**Comment by blesh** [comment]
After thinking about this, I'd like to let the current situation simmer for a while. Perhaps I'll reopen this later.
