### ISSUE TITLE
Implement `pluck` operator

### ISSUE THREAD

**Issue by trxcllnt** [ReactiveX/RxJS#1134]
edit: Implement [`Observable.prototype.pluck`](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/pluck.md) from RxJS v4.

**Comment by mattpodwysocki** [comment]
@trxcllnt is this going to be consistent with RxJS v4 with a recursive pluck?

**Comment by trxcllnt** [comment]
@mattpodwysocki sorry for the empty initial description, was in the middle of something but wanted to capture the issue anyway. I see no reason not to be backwards-compatible here.

**Comment by luisgabriel** [comment]
@trxcllnt are you working on this? I can take it if not.

**Comment by blesh** [comment]
@luisgabriel ... I'm going to guess he is if he filed the issue. That's usually his thing.

**Comment by luisgabriel** [comment]
@blesh Sure, I was suspecting that. It's worth asking anyway. ;)

**Comment by trxcllnt** [comment]
@luisgabriel I have not. In the middle of another project at work, feel free to take the lead on this.

**Comment by luisgabriel** [comment]
@trxcllnt :+1:

**Comment by luisgabriel** [comment]
@mattpodwysocki I'm currently working on this, but I'm not sure if I understand what do you mean by recursive pluck correctly. Could elaborate a little more?

**Comment by mattpodwysocki** [comment]
@luisgabriel meaning that it is compatible with RxJS v4
