### ISSUE TITLE
Type inference not working due to Observable<any> in `switchmap`

### ISSUE THREAD

**Issue by masaeedu** [ReactiveX/RxJS#1139]
The RxJS 5 beta has a new `switchMap` operator that is supposed to replace `flatMapLatest`. The signature for `switchMap`, on [line 76 of CoreOperators.ts](https://github.com/ReactiveX/RxJS/blob/master/src/CoreOperators.ts#L76), looks like this:

    switchMap?: <R>(project: ((x: T, ix: number) => Observable<any>), projectResult?: (x: T, y: any, ix: number, iy: number) => R) => Observable<R>;

Note the `Observable<any>` return type for the `project` func parameter. This means the `R` type won't be inferred if the method is called with a single observable-returning func. Unless I'm misunderstanding, the signature should be:

    switchMap?: <R>(project: ((x: T, ix: number) => Observable<R>), ...)
                                                    _____________

Similar changes would be made for `switchMapTo` (and possibly other operators I'm missing).

**Comment by david-driscoll** [comment]
There are many areas where type inference is a problem, something that was solved in RxJS4's typings.  The deficiencies have been noted, there is just a long haul to get them all in through review for the RxJS5 team to take ownership of them.

I've got a set that at one point was working correctly, #1050, again all the pieces need to be reviewed.

**Comment by masaeedu** [comment]
@david-driscoll Would it be a good idea to just start cleaning these up with small PRs as we come across them?

**Comment by david-driscoll** [comment]
That's the end game, but right now you have to modify the same definition in 3 places (at least it was when I last looked) which is a maintenance nightmare.  I have a proposed automated system, but the team is still unsure if they want to do that or not.

**Comment by blesh** [comment]
> but the team is still unsure if they want to do that or not.

@david-driscoll I think it sounds good. It was just a huge PR to review. I'm delegating to @kwonoj for :+1: or :-1:

**Comment by david-driscoll** [comment]
@blesh I'm fine with breaking things apart, I know I'm not working on the library day to day. :smile: 

Holidays had me busy, I'm working on #1077 tonight.

**Comment by kwonoj** [comment]
As already commented in PR, I also in favor of essence of @david-driscoll 's proposal. What's remaining is to make it happen in codebase such as reviewing changes (taking time due to dependent change such as #1077 and nature of change itself is quite amount), etcs. (Means I'm :+1: in those proposal)

Though I expect @david-driscoll 's PR eventually be landed, due to reasons I think it won't happen in short timeframe such as day or two. So @masaeedu , if this is blocking your usecase I think it's OK to have specific PR to resolve this first while working on final solution for this.

**Comment by masaeedu** [comment]
@kwonoj I'll use explicit typings or `any` to work around the lack of inference until David's PR gets pulled. Thanks all!

**Comment by kwonoj** [comment]
Thanks for confirmation. Let me close this issue for now then.

**Comment by masaeedu** [comment]
@kwonoj It looks like @David's change has been merged, but the type signature for `switchMap` and other operators (e.g. `flatMap`) seem to be unchanged. It might be that I'm just misunderstanding how the typings are supposed to work. For `flatMap`, for instance, I think the typing should not be:

    flatMap: <R>(project: ((x: T, ix: number) => Observable<any>), ...) => Observable<R>;

But rather:

    flatMap: <R>(project: ((x: T, ix: number) => Observable<R> | R[]), ...) => Observable<R>;

The first change (`Observable<any>` to `Observable<R>`) enables type inference, and is what this issue is about. The second change (the addition of `| R[]`) is related to the fact that `flatMap`/`mergeMap` work with array returning functions as well as observable returning functions, and can possibly be considered in a separate issue.

Is this actually an oversight or am I just not grokking how the typings work?

**Comment by kwonoj** [comment]
@masaeedu , changes just checked in is about enabling compiler to not allow implicit `any` in codebase for prerequisite dependency to actual type definition enhancement. Those discussions are in PR https://github.com/ReactiveX/RxJS/pull/1087, you may able to see what'd be expected result of type definition.

Long story in short, just checked in PR does not bring type definition change and it'll happen in other PR currently opened. Is that answers your question?

**Comment by masaeedu** [comment]
@kwonoj It does, thanks. I'm digging into the codebase, will see if I can contributes some small fixes for the most painful methods while this automation effort is still underway.

**Comment by kwonoj** [comment]
@masaeedu appreciate for it, as we're trying to improve type definitions those will be great help :)

**Comment by sbley** [comment]
@masaeedu Thank you for your finding these wrong type definitions for flatMap. I could't figure it out myself. I am using rxjs-5.0.0.-beta2 which has the incorrect type definitions.

Is this fixed in a new version? If not, how can I work around this?

**Comment by masaeedu** [comment]
@sbley There's a bit of churn right now in the type signatures for various operators. @david-driscoll has been cleaning up a bunch of them, and once #1351 and #1352 are merged the user facing typings (including `flatMap`) should work correctly.

If you're impatient you can clone and `npm link` https://github.com/david-driscoll/RxJS-1/tree/addObservableInterfacePatches-squash, which works pretty well for me.
