### ISSUE TITLE
Cannot run build_test

### ISSUE THREAD

**Issue by jeremymwells** [ReactiveX/RxJS#114]
After installing prereqs, and running `npm run build_test`, I get the following failures and output:
> RxJS-Next@0.0.0-prealpha.1 build_test /Users/jeremywells/Javascript/RxJS
> rm -rf dist/ && npm run build_es6 && npm run build_cjs && jasmine

> RxJS-Next@0.0.0-prealpha.1 build_es6 /Users/jeremywells/Javascript/RxJS
> rm -rf dist/es6 && tsc src/RxNext.ts --outDir dist/es6 --target ES6 -d

> RxJS-Next@0.0.0-prealpha.1 build_cjs /Users/jeremywells/Javascript/RxJS
> rm -rf dist/cjs && babel dist/es6 --out-dir dist/cjs --modules common --sourceMaps --loose all

>dist/es6/BehaviorSubject.js -> dist/cjs/BehaviorSubject.js
dist/es6/CompositeSubscription.js -> dist/cjs/CompositeSubscription.js
dist/es6/ConnectableObservable.js -> dist/cjs/ConnectableObservable.js
dist/es6/Observable.js -> dist/cjs/Observable.js
dist/es6/Observer.js -> dist/cjs/Observer.js
dist/es6/RxNext.js -> dist/cjs/RxNext.js
dist/es6/SerialSubscription.js -> dist/cjs/SerialSubscription.js
dist/es6/Subject.js -> dist/cjs/Subject.js
dist/es6/Subscriber.js -> dist/cjs/Subscriber.js
dist/es6/SubscriberFactory.js -> dist/cjs/SubscriberFactory.js
dist/es6/Subscription.js -> dist/cjs/Subscription.js
dist/es6/observable/ArrayObservable.js -> dist/cjs/observable/ArrayObservable.js
dist/es6/observable/combineLatest.js -> dist/cjs/observable/combineLatest.js
dist/es6/observable/empty.js -> dist/cjs/observable/empty.js
dist/es6/observable/fromArray.js -> dist/cjs/observable/fromArray.js
dist/es6/observable/fromEvent.js -> dist/cjs/observable/fromEvent.js
dist/es6/observable/fromEventPattern.js -> dist/cjs/observable/fromEventPattern.js
dist/es6/observable/fromPromise.js -> dist/cjs/observable/fromPromise.js
dist/es6/observable/interval.js -> dist/cjs/observable/interval.js
dist/es6/observable/never.js -> dist/cjs/observable/never.js
dist/es6/observable/of.js -> dist/cjs/observable/of.js
dist/es6/observable/range.js -> dist/cjs/observable/range.js
dist/es6/observable/return.js -> dist/cjs/observable/return.js
dist/es6/observable/throw.js -> dist/cjs/observable/throw.js
dist/es6/observable/timer.js -> dist/cjs/observable/timer.js
dist/es6/observable/value.js -> dist/cjs/observable/value.js
dist/es6/observable/zip.js -> dist/cjs/observable/zip.js
dist/es6/operator/combineLatest.js -> dist/cjs/operator/combineLatest.js
dist/es6/operator/concatAll.js -> dist/cjs/operator/concatAll.js
dist/es6/operator/filter.js -> dist/cjs/operator/filter.js
dist/es6/operator/flatMap.js -> dist/cjs/operator/flatMap.js
dist/es6/operator/map.js -> dist/cjs/operator/map.js
dist/es6/operator/mapTo.js -> dist/cjs/operator/mapTo.js
dist/es6/operator/merge.js -> dist/cjs/operator/merge.js
dist/es6/operator/mergeAll.js -> dist/cjs/operator/mergeAll.js
dist/es6/operator/multicast.js -> dist/cjs/operator/multicast.js
dist/es6/operator/observeOn.js -> dist/cjs/operator/observeOn.js
dist/es6/operator/partition.js -> dist/cjs/operator/partition.js
dist/es6/operator/publish.js -> dist/cjs/operator/publish.js
dist/es6/operator/reduce.js -> dist/cjs/operator/reduce.js
dist/es6/operator/skip.js -> dist/cjs/operator/skip.js
dist/es6/operator/subscribeOn.js -> dist/cjs/operator/subscribeOn.js
dist/es6/operator/take.js -> dist/cjs/operator/take.js
dist/es6/operator/toArray.js -> dist/cjs/operator/toArray.js
dist/es6/operator/zip.js -> dist/cjs/operator/zip.js
dist/es6/operator/zipAll.js -> dist/cjs/operator/zipAll.js
dist/es6/scheduler/NextTickScheduler.js -> dist/cjs/scheduler/NextTickScheduler.js
dist/es6/scheduler/Scheduler.js -> dist/cjs/scheduler/Scheduler.js
dist/es6/scheduler/SchedulerActions.js -> dist/cjs/scheduler/SchedulerActions.js
dist/es6/scheduler/immediate.js -> dist/cjs/scheduler/immediate.js
dist/es6/scheduler/nextTick.js -> dist/cjs/scheduler/nextTick.js
dist/es6/util/Immediate.js -> dist/cjs/util/Immediate.js
dist/es6/util/Symbol_observer.js -> dist/cjs/util/Symbol_observer.js
dist/es6/util/arraySlice.js -> dist/cjs/util/arraySlice.js
dist/es6/util/errorObject.js -> dist/cjs/util/errorObject.js
dist/es6/util/root.js -> dist/cjs/util/root.js
dist/es6/util/tryCatch.js -> dist/cjs/util/tryCatch.js
Started
....FFF..................................

>Failures:
1) Observable.fromPromise should emit one value from that promise
  Message:
    ReferenceError: Promise is not defined
  Stack:
    ReferenceError: Promise is not defined
        at Object.<anonymous> (/Users/jeremywells/Javascript/RxJS/spec/observable/from-promise-spec.js:7:19)

>2) Observable.fromPromise should not emit, throw or complete if immediately unsubscribed
  Message:
    ReferenceError: Promise is not defined
  Stack:
    ReferenceError: Promise is not defined
        at Object.<anonymous> (/Users/jeremywells/Javascript/RxJS/spec/observable/from-promise-spec.js:22:19)

>3) Observable.interval should next 5 times then complete
  Message:
    Expected 0 to be 5.
  Stack:
    Error: Expected 0 to be 5.
        at Object.<anonymous> (/Users/jeremywells/Javascript/RxJS/spec/observable/interval-spec.js:26:35)
  Message:
    Expected undefined to be 0.
  Stack:
    Error: Expected undefined to be 0.
        at /Users/jeremywells/Javascript/RxJS/spec/observable/interval-spec.js:28:43
        at Array.forEach (native)
        at Object.<anonymous> (/Users/jeremywells/Javascript/RxJS/spec/observable/interval-spec.js:27:14)
  Message:
    Expected undefined to be 1.
  Stack:
    Error: Expected undefined to be 1.
        at /Users/jeremywells/Javascript/RxJS/spec/observable/interval-spec.js:28:43
        at Array.forEach (native)
        at Object.<anonymous> (/Users/jeremywells/Javascript/RxJS/spec/observable/interval-spec.js:27:14)
  Message:
    Expected undefined to be 2.
  Stack:
    Error: Expected undefined to be 2.
        at /Users/jeremywells/Javascript/RxJS/spec/observable/interval-spec.js:28:43
        at Array.forEach (native)
        at Object.<anonymous> (/Users/jeremywells/Javascript/RxJS/spec/observable/interval-spec.js:27:14)
  Message:
    Expected undefined to be 3.
  Stack:
    Error: Expected undefined to be 3.
        at /Users/jeremywells/Javascript/RxJS/spec/observable/interval-spec.js:28:43
        at Array.forEach (native)
        at Object.<anonymous> (/Users/jeremywells/Javascript/RxJS/spec/observable/interval-spec.js:27:14)
  Message:
    Expected undefined to be 4.
  Stack:
    Error: Expected undefined to be 4.
        at /Users/jeremywells/Javascript/RxJS/spec/observable/interval-spec.js:28:43
        at Array.forEach (native)
        at Object.<anonymous> (/Users/jeremywells/Javascript/RxJS/spec/observable/interval-spec.js:27:14)

>41 specs, 4 failures
Finished in 0.44 seconds

>An error was thrown in an afterAll
AfterAll Expected false to be true.

>npm ERR! RxJS-Next@0.0.0-prealpha.1 build_test: `rm -rf dist/ && npm run build_es6 && npm run build_cjs && jasmine`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the RxJS-Next@0.0.0-prealpha.1 build_test script.
npm ERR! This is most likely a problem with the RxJS-Next package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rm -rf dist/ && npm run build_es6 && npm run build_cjs && jasmine
npm ERR! You can get their info via:
npm ERR!     npm owner ls RxJS-Next
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 14.3.0
npm ERR! command "node" "/usr/local/bin/npm" "run" "build_test"
npm ERR! cwd /Users/jeremywells/Javascript/RxJS
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/jeremywells/Javascript/RxJS/npm-debug.log
npm ERR! not ok code 0

And here are the contents of the npm-debug.log:

>0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'run', 'build_test' ]
2 info using npm@1.4.3
3 info using node@v0.10.26
4 verbose run-script [ 'prebuild_test', 'build_test', 'postbuild_test' ]
5 info prebuild_test RxJS-Next@0.0.0-prealpha.1
6 info build_test RxJS-Next@0.0.0-prealpha.1
7 verbose unsafe-perm in lifecycle true
8 info RxJS-Next@0.0.0-prealpha.1 Failed to exec build_test script
9 error RxJS-Next@0.0.0-prealpha.1 build_test: `rm -rf dist/ && npm run build_es6 && npm run build_cjs && jasmine`
9 error Exit status 1
10 error Failed at the RxJS-Next@0.0.0-prealpha.1 build_test script.
10 error This is most likely a problem with the RxJS-Next package,
10 error not with npm itself.
10 error Tell the author that this fails on your system:
10 error     rm -rf dist/ && npm run build_es6 && npm run build_cjs && jasmine
10 error You can get their info via:
10 error     npm owner ls RxJS-Next
10 error There is likely additional logging output above.
11 error System Darwin 14.3.0
12 error command "node" "/usr/local/bin/npm" "run" "build_test"
13 error cwd /Users/jeremywells/Javascript/RxJS
14 error node -v v0.10.26
15 error npm -v 1.4.3
16 error code ELIFECYCLE
17 verbose exit [ 1, true ]

**Comment by blesh** [comment]
Looks like we need to setup the configuration point for using your own Promise library. Also, perhaps an optional parameter on `forEach` for a Promise constructor.

**Comment by blesh** [comment]
@trxcllnt addressed this in a PR this morning adding a dev dependency of promise. We still need configuration points, probably. But this issue should now be resolved.
