### ISSUE TITLE
Remove ScalarObservable optimizations for map, filter, reduce, scan, etc?

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#1142]
There is an issue #1140 that just popped up (I was waiting for it). 

I'm neither hot nor cold on these optimizations. So let's discuss them:

#### The Good:

1. The optimizations only effect observables created like `Observable.of(a)`, but not `Observable.of(1,2,3)`. They only effect ScalarObservables.
2. The optimizations doubled or tripled the speed of the operators for these Observables.
3. No one should be doing `Observable.of(a).map(toSomethingElse)` very often. It's code that only really shows up in demos and playground code normally, and/or it's an anti-pattern usually.
4. Generally it's a bad idea to mutate outer scoped variables inside of a map or filter handler.

#### The Bad:

1. Users trying to leverage map to create side effects might see funky behavior for ScalarObservables
2. The mapping or filtering functions are effectively no longer "lazy". If they're expensive or they create side effects, unexpected behavior can result.

**Comment by blesh** [comment]
### AGAIN: I don't care if we keep them or remove them

The idea was that we'd implement them and try them out during beta.

**Comment by kwonoj** [comment]
I'm in favor of this in general, but this specific ` effectively no longer "lazy". If they're expensive or they create side effects, unexpected behavior can result` is bit concern. Every user of `of(x)` need to be aware of behavior if we're going with this.

**Comment by trxcllnt** [comment]
We should make them lazy. If someone wants to optimize so their ScalarObservable chains are only invoked once, they can multicast with a ReplaySubject.

**Comment by blesh** [comment]
This all sounds good... I'll let this simmer overnight.

I think we should also try to add some "protips" or something to the docs that say things like "If you're creating chains like `Observable.of(a).map(doSomething)`, you might be doing something weird."

**Comment by staltz** [comment]
I'm also rather neutral on this one, but I tend to agree with Paul.

**Comment by blesh** [comment]
Meh. Let's remove them for now. Individuals that want this behavior could always monkey-patch ScalarObservable I suppose.

**Comment by chrisprice** [comment]
Just before this is done in response to my issue can I double check that the problem I had is actually what's been discussed? I have a feeling it might just be a bug (see my latest comment on the issue)....

FWIW I do agree though, just not in my name! :smile:

**Comment by blesh** [comment]
There are two issues: 1. the optimization which were discussing removing here, and 2. an apparent bug in the optimization that needs to be fixed or removed with the optimization.
