### ISSUE TITLE
Observable.subscribe type definition

### ISSUE THREAD

**Issue by oegnus** [ReactiveX/RxJS#1146]
I think this definition for error handler is wrong (shouldn't have type T):
```typescript
subscribe(observerOrNext?: Observer<T> | ((value: T) => void),
            error?: (error: T) => void,
            complete?: () => void): Subscription<T>
```
it should be:
```typescript
subscribe(observerOrNext?: Observer<T> | ((value: T) => void),
            error?: (error: any) => void,
            complete?: () => void): Subscription<T>
```

**Comment by luisgabriel** [comment]
I think #1123 fixed this issue.

**Comment by oegnus** [comment]
Ok. Thanks. Didn't know how to find that fix.

**Comment by luisgabriel** [comment]
It was merged early this week. It should be part of the next beta release.

Can you close this issue? Thanks for the report! ;)

**Comment by kwonoj** [comment]
Yes, it's checked in just about a day ago so you may possibly missed it. Let me close this issue by fix is already in place - feel freely reopen if needed. Thanks again!
