### ISSUE TITLE
Observable.from('string') browser compatibility

### ISSUE THREAD

**Issue by kwonoj** [ReactiveX/RxJS#1147]
`Observable.from` can take string and iterate it as 

```
Rx.Observable.from('foo').subscribe(console.log);
// => Next: f
// => Next: o
// => Next: o
// => Completed
```

but fails to do it on some browsers does not support string iterator (IE, for example) 

in RxJS4, seems it has own iterator for string object (https://github.com/Reactive-Extensions/RxJS/blob/master/src/core/linq/observable/from.js#L3-L23) to support this behavior - does RxJS5 need to port same behavior?

I've used  https://jsfiddle.net/v0w220v6/ to test out between different browsers.

**Comment by kwonoj** [comment]
related to https://github.com/ReactiveX/RxJS/issues/998 .

**Comment by blesh** [comment]
I believe some of the infrastructure for this is already in place. So there might be a bug.

**Comment by kwonoj** [comment]
I assume it's `StringIteratror` in `IteratorObservable`, will try to look into what's happening. Marking it as bug meanwhile.
