### ISSUE TITLE
Observable.concat() does not complete with a buffered scalar observable

### ISSUE THREAD

**Issue by emonkak** [ReactiveX/RxJS#1150]
This Observable does not complete.

```javascript
const { Observable } = Rx

Observable
  .create(observer => {
    setTimeout(function() {
      observer.next(1)
      observer.complete()
    }, 1000)
	})
  .concat(Observable.of(2))
  .subscribe(
    x => console.log('Next:', x),
    x => console.log('Error:', x),
    () => console.log('Completed')
  )
```

http://jsfiddle.net/bo6ynqf7/7/

Expected:

```
Next: 1
Next: 2
Complete
```

Actual:

```
Next: 1
Next: 2
```

**Comment by Nupf** [comment]
I just ran into a similiar problem and figured out the solution as far as I can tell. The problem only arises for scalar observables.

Concat is based on [mergeAll-support](https://github.com/ReactiveX/RxJS/blob/master/src/operator/mergeAll-support.ts), which does not subscribe to scalar-observables but [instantly nexts their value](https://github.com/ReactiveX/RxJS/blob/master/src/operator/mergeAll-support.ts#L26-L29). 
However, for [notifyComplete](https://github.com/ReactiveX/RxJS/blob/master/src/operator/mergeAll-support.ts#L46-L55) to be called, the observable has to be subscribed to by an [innerSubscriber](https://github.com/ReactiveX/RxJS/blob/master/src/InnerSubscriber.ts#L20-L23).

I believe someone more experienced should decide how this is best resolved (i.e. I would just change it to subscribe to scalar & non-scalar observables alike)

**Comment by kwonoj** [comment]
Thinking this might be another side effect of ScalarObservable, related to https://github.com/ReactiveX/RxJS/issues/1142.

**Comment by trxcllnt** [comment]
@Nupf yes, `subscribeToResult` already handles ScalarObservable, so any operators that check for `_isScalar` and aren't using `subscribeToResult` should be refactored to always call `subscribeToResult`.

**Comment by blesh** [comment]
@kwonoj @trxcllnt ... do you know if this is still an issue?

**Comment by kwonoj** [comment]
Just tried again with TOT and seems it's still occurring.
