### ISSUE TITLE
Please provide examples on deprecated operators...

### ISSUE THREAD

**Issue by born2net** [ReactiveX/rxjs#1162]
If possible, it would be awesome if we could get examples on how to get the same feature or result from EACH now deprecated Rxjs 4 operator using Rxjs 5...

tx

Sean

**Comment by staltz** [comment]
Good point.

**Comment by HighOnDrive** [comment]
+1

**Comment by blesh** [comment]
bumping for visibility.

**Comment by blesh** [comment]
I believe we've started doing this... closing for now. This is going to be an ongoing thing.

**Comment by born2net** [comment]
great tx for all the support Ben,
regards,
Sean
