### ISSUE TITLE
setImmediate compatibility in IE10 

### ISSUE THREAD

**Issue by kwonoj** [ReactiveX/RxJS#1163]
among major browser engines, IE10 (and above, IE11) have implementation of `window.setImmediate` (https://developer.mozilla.org/ko/docs/Web/API/Window/setImmediate) and current implementation of RxJS `immediate` tries to utilize it. Currently it has 2 issues

- current codebase cannot call `window.setImmediate`
: our codebase assigns it as 
```
if (root.setImmediate) {
      this.setImmediate = root.setImmediate;
```
which brings error like below
```
IE 11.0.0 (Windows 10 0.0.0) AsapScheduler should schedule an action to happen later FAILED
        TypeError: Invalid calling object
```

reason of IE's behavior (https://msdn.microsoft.com/library/gg622930(v=vs.85).aspx).

- `window.setImmediate` has known issue
: has unreliable behavior reported at
http://codeforhire.com/2013/09/21/setimmediate-and-messagechannel-broken-on-internet-explorer-10/ 
and 
https://connect.microsoft.com/IE/feedback/details/801823/setimmediate-and-messagechannel-are-broken-in-ie10

confirmed as 'won't fix'. 

#### Possible options
- solve RxJS side issue only (calling setImmediate), let user decide to use `window.setImmediate` or not explicitly
- ignore `window.setImmediate` and use polyfill (onreadystatechange?)

**Comment by kwonoj** [comment]
My vote is to ignore `window.setImmediate` by it's already known to not to be fixed in further.

**Comment by kwonoj** [comment]
related with https://github.com/ReactiveX/RxJS/issues/998.

**Comment by mattpodwysocki** [comment]
@kwonoj that's not what the error is telling you, it's telling you it's unbound to the proper object.  None of the issues you state above aren't related to this error.  In this case, our code should be:
```js
if (typeof root.setImmediate === 'function') {
  this.setImmediate = root.setImmediate.bind(root);
}
```

The problem is that you were unbound to the `root` for `setImmediate` which is a bug in the code

**Comment by kwonoj** [comment]
@mattpodwysocki What I was thought about first case was regarding below in https://msdn.microsoft.com/library/gg622930(v=vs.85).aspx, seems I was misunderstood about those.
```
The long term fix for this is to use JavaScript's bind API to associate an implicit calling object 
with the method. This is done as follows (again, drawing on the previous example): 

var d = document.writeln.bind(document);
d("<script language=VBScript>"); // Now this is OK.
```

For second item, it is said behavior of `window.setImmediate` itself - can we consider it's not problematic?

**Comment by mattpodwysocki** [comment]
@kwonoj no, it's not any more problematic than any other host object. See the `requestAnimationFrame` wrapper made by @trxcllnt https://github.com/ReactiveX/RxJS/blob/rxjs-dom/src/util/AnimationFrame.ts#L8-L9

**Comment by kwonoj** [comment]
Appreciate for clarification. I'll use this issue to update code base as suggested by second issue (I thought as issue) is not relevant.
