### ISSUE TITLE
Observable.from should handle "array-like" objects like arguments

### ISSUE THREAD

**Issue by mattpodwysocki** [ReactiveX/RxJS#1166]
In order to be compliant with RxJS v4, Rx.Observable.from is missing the following functionality which brings it on par with [`Array.from`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from).  The current `isArray` check is too literal and should only check if it has a `.length` property

```js
// Generate a sequence of numbers
Array.from({length: 5}, (v, k) => k);    
// [0, 1, 2, 3, 4]
```

And so does RxJS v4:
```js
// Generate a sequence of numbers
Rx.Observable.from({length: 5}, (v, k) => k).subscribe(x => console.log(x));    
// [0, 1, 2, 3, 4]
```

Filing this bug as I did not see it in the test suite as it is in [RxJS v4](https://github.com/Reactive-Extensions/RxJS/blob/master/tests/observable/from.js#L46-L63)

**Comment by blesh** [comment]
That's a horrible way to make a series of numbers. haha.  Wouldn't users be better off using `range` for this? Do we really want them using `from` like that?

The better reason is so we can handle "array-like" types like `arguments`... basically anything with this shape:

```
var arrayLike = {
  "length": "3",
  "0": "foo",
  "1": "bar",
  "2": "baz"
};
```

So you can do things like `Observable.from(arguments)`

A better catch is that I don't think we have that result selector implemented.

**Comment by blesh** [comment]
### We need

1. To handle array-likes, in particular arguments
2. To provide an optional resultSelector

**Comment by mattpodwysocki** [comment]
@blesh yes, that's not a great example, and no, range won't do it.  Instead, focus on array like objects such as any `NodeList` object to turn into an Observable

**Comment by blesh** [comment]
I think this is closable as of now. The only hanging issue is defined by the discussion here #1255
