### ISSUE TITLE
TS2315: Type 'Subscription' is not generic

### ISSUE THREAD

**Issue by mastertinner** [ReactiveX/RxJS#1179]
I'm using TypeScript and up until `5.0.0-beta.0` it has worked fine but since the upgrade to `5.0.0-beta.1` i'm getting a TypeScript compiler error: `TS2315: Type 'Subscription' is not generic` for the following piece of code: 
```typescript
import {Subscription} from 'rxjs';

class MyComponent {
  private subscription: Subscription<MyDataModel[]>;`
}
```

Can you tell me what I'm doing wrong?

**Comment by kwonoj** [comment]
Those are newly introduced changes in beta 1 via PR https://github.com/ReactiveX/RxJS/pull/1065, `Subscription` is no longer generic type by interface of `Subscription` does not have usage of type parameter in general. 

would you try with removing type parameter?

```
class MyComponent {
  private subscription: Subscription;
}
```

**Comment by mastertinner** [comment]
That did the trick. Thanks a lot for the quick reply, @kwonoj!

**Comment by kwonoj** [comment]
You're welcome! :) Let me close issue then, feel freely reopen or create new one if there's any issue.
