### ISSUE TITLE
Fix auto-patching operators generator to handle observable subclasses

### ISSUE THREAD

**Issue by luisgabriel** [ReactiveX/RxJS#1183]
This issue was pointed in #1178.

The `tools/generate-operator-patches.ts` is generating patches to some observable subclasses such as `ScalarObservable` and `SubscribeOnObservable` that are not directly export via static operators.

**Comment by luisgabriel** [comment]
I'm working on this one.

**Comment by blesh** [comment]
Was this closed by #1178?

**Comment by luisgabriel** [comment]
No. In the initial version, #1178 was adding to the code base these incorrect patches that the script is currently generating. After review it was removed from the commit but the script is still generating these files.

**Comment by blesh** [comment]
@luisgabriel you might want to take into account #1113 while working on this.

**Comment by luisgabriel** [comment]
@blesh sure. I will. ;)

**Comment by luisgabriel** [comment]
Closing this issue in favor of #1238.
