### ISSUE TITLE
.timestamp() operator

### ISSUE THREAD

**Issue by rudijs** [ReactiveX/RxJS#1192]
Hi,

New RxJS student here again...

If my question here now should be on stackoverflow and not a github issue - please let me know.

I see the .timestamp() operator in rx is not in rxjs.

I think adding a timestamp where I need is pretty simple and straightforward.

The use case I have, from my learning material, uses .timestamp() from rx to timestamp mouse click events.

Though modern browsers support a 'timeStamp' event property the w3schools.com doc does say:

    Not all systems provide this information, therefore, timeStamp may be not available for all systems/events.

That being the case, if one wanted to add a timestamp this approach seems to be OK I think:

```
Rx.Observable.fromEvent(canvas, 'click')
  .map(event => {
    event.customTimeStamp = Date.now();
    return event;
})
.subscribe(e => {
  console.log(e.timeStamp);
  console.log(e.customTimeStamp);
  console.log(e);
})
```

Pretty straight forward and reasonable to assume RxJS will not implement the .timestamp() operator yeah?

Thanks!

**Comment by trxcllnt** [comment]
@rudijs I expect we will implement `timestamp`, but we haven't gotten around to it.

**Comment by rudijs** [comment]
@trxcllnt Ah OK I see. As this library is in beta I was assuming the API was stable, so to speak, and that pretty much everything that was going to be implemented was settled on.

Anything not implemented I figured there was a reason for it.

Thanks for the clarification.
