### ISSUE TITLE
.shareReplay operator?

### ISSUE THREAD

**Issue by justinwoo** [ReactiveX/RxJS#1194]
Should we have this operator? People could just `ReplaySubject`, but maybe this is nice to have.

Might require `replay` to be implemented if this were added though (which, iirc, just uses ReplaySubject under the hood anyway).

[`shareReplay in RxJS4`](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/sharereplay.md)

**Comment by kwonoj** [comment]
There's long discussions in https://github.com/ReactiveX/RxJS/issues/453, shorthanded summary's at https://github.com/ReactiveX/RxJS/issues/1110 also.

**Comment by kwonoj** [comment]
In short, for now `shareReplay` is not added and it's expected.

**Comment by justinwoo** [comment]
Oh, sorry, didn't find it in the search results.

**Comment by kwonoj** [comment]
@justinwoo Don't feel sorry, I also feel searching issue in github is bit hard sometime :) Glad questions solved.

**Comment by staltz** [comment]
`.publishReplay().refCount()`

**Comment by blesh** [comment]
We should have something _similar_ ... but I'm not sure I'd want to name it `shareWhatever` at this point. `share()` has a slightly different and more ergonomic behavior than `publish().refCount()`. I'd like to add some sort of `cache()` operator that does what `shareReplay` was used for, but with perhaps more extensible arguments than a simple count to control things like expirey, etc. We started some discussion in #839 but it petered out.

**Comment by staltz** [comment]
I think we sort of agreed to cut the excess in share operators, and I like it if people understand what a ConnectableObservable is and that you need to call "connect()" and how refCount is sort of auto-connect. Because `share()` can sometimes be understood as a blurred concept of "make this cold become hot".
