### ISSUE TITLE
Include alternatives in the migration document

### ISSUE THREAD

**Issue by iemejia** [ReactiveX/RxJS#1203]
Looking at the [migration document](https://github.com/ReactiveX/RxJS/blob/master/MIGRATION.md) I noticed some changes in the operators. Since
current RxJS code/examples/tutorials will break with the new version, maybe it
is useful to include an additional column in the Operators Renamed/Removed table
to present possible alternatives e.g. replacements,aliases, etc.

I say this because I was trying a really simple example that used the
**Rx.Observable.just** operator and it does not seem to be in the migration table,
and additionally I didn't find any alternative, e.g. is it **Rx.Observable.of** the
appropriate one ?

**Comment by kwonoj** [comment]
Answer of corresponding operator to `just`, yes you can use `of` for those purpose. Thanks for catching it's not included docs.

for usage of migrated operator seems similar to issue https://github.com/ReactiveX/RxJS/issues/1162, is my understanding correct?

**Comment by iemejia** [comment]
When I mentioned the alternatives probably I refer to the same as issue #1162,
so maybe you can mark it as a duplicate.

However I still have one question. What is the 'official' replacement of **.just/.return** operators ?  Looking at the old documentation of the operator of the [.of operator](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/of.md) It seems to achieve the same goal, but it does not have the optional scheduler argument as the [.just/.return ones](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/return.md).

I understand that RxJS 5 is trying to reduce the surface area of the Rx API, but it is a bit confusing to remove an operator that exists in [all the other Rx implementations](http://reactivex.io/documentation/operators/just.html), but well if the documentation says which operator replaces it I suppose it is ok.

**Comment by kwonoj** [comment]
`of` also does accept `scheduler` as optional, such as 

`Observable.of(x, Scheduler.xxx)`

Did you experience issue with type inference or functional(does not schdeuled via scheduler specified?)

**Comment by kwonoj** [comment]
To clarify, you may refer `ArrayObservable` in master repo to see its signature.

**Comment by kwonoj** [comment]
By operator `of` supports scheduler and suggestion for operator guide of migrated is being tracked separately, I'm closing this issue for now. @iemejia , if above doesn't answer your question fully, please feel freely reopen to continue discussions.
