### ISSUE TITLE
Guidance for Custom Operator libraries

### ISSUE THREAD

**Issue by bholloway** [ReactiveX/rxjs#1207]
I can see the number of operator libraries increasing very fast in the near future. I'm concerned about [the guidance given](https://github.com/ReactiveX/RxJS/blob/master/doc/operator-creation.md#adding-the-operator-to-observable) for creation of custom operators.

Guidance item 3 where assignment is made to `Operator.prototype` is a global monkey-patch. This is a dangerous.

If operators share a global namespace then code will not interoperate. For example:

**Use case 1** - libraries that use Rx under the hood.
* library-A implements `Observable.foo()` operator.
* library-B also implements `Observable.foo()` operator for a different purpose.
* => Namespace conflict on `Observable`.

The libraries are mutually exclusive even though they may have completely different features.

In this case guidance item 1 or item 2 are the safer solution and **guidance item 3 should be contra-indicated** as bad practice.

However there is another use case where guidance item 1 and item 2 are problematic.

**Use case 2, implementation 1** - compose from different operator libraries
* operator-library-X implements `BarObservable` that includes operator `.bar()`.
* operator-library-Y implements `BazObservable` that includes operator `.baz()`.
* => Can't create `MyObservable` that includes both operators

What we want is for libraries to define operators without adding them to `Observable`. So that we create the custom Observable sub-class at point of use. Meaning:

**Use case 2, implementation 2** - compose from different operator libraries
* operator-library-X implements operator `.bar()`.
* operator-library-Y implements `.baz()`.
* => My custom code creates `MyObservable` that includes both operators

In this case we have the guidance is the same but we add that libraries should avoid installing operators.

To encourage compliance then `Observable` needs a **static factory method that creates sub-class implementations** and a **cast operator** as a convenience to change an existing Observable to the custom Observable. For example:

```
var MyObservable = Observable.subclassWith(hashOfOperators);
var myObservable = existingObservable.toObservable(MyObservable);
```

**Comment by bholloway** [comment]
An example: https://github.com/bholloway/rx-operators#usage

**Comment by blesh** [comment]
Hey @bholloway, thanks for submitting this issue, it's an important topic!

Did you happen to find [the documentation for creating operators](https://github.com/ReactiveX/RxJS/blob/master/doc/operator-creation.md)?

**Comment by trxcllnt** [comment]
@blesh that's what he referenced above...
@bholloway we already have this with `let`, but I don't think it's in the docs yet. Custom Observable subclasses should implement a static `from` method to convert sources to your custom Observable type:

```es6
source
  .let(FooObservable.from)
  .fooOperator()
  .let(BarObservable.from)
  .barOperator();
```
etc.

**Comment by bholloway** [comment]
@trxcllnt That sounds excellent.

I am thinking that this will augment Guidance 2 in the near future since it uses a subclass (?).

I prefer Guidance 2 but it does take a lot of work. Ideally I would like to see a subclass factory, similar to `subclassWith(operators)`, to make Guidance 2 more compelling. Obviously [this implementation](https://github.com/bholloway/rx-operators/blob/master/utility/subclass-with.js) still needs the `from()` member but works well otherwise.

For me Guidance 3 is good for quickly getting started in JSBin but I think it wise to label it as **unsuitable for distribution**.

Guidance 1 is good for internal use where you want to casually `require()` and operator and use it without changing the nature of the resulting observable.

**Comment by bholloway** [comment]
I withdraw my suggestion of `subclassWith(operators)`.

It is not possible to generalise the form of the `lift()` method in such a way as it can satisfy the different constructor arguments that certain Observables require. For example, you cannot reconcile the constructor args of `ConnectedObservable`, with `Observable`.

This takes away a lot of the utility of the `subclassWith(operators)` concept.

I believe the **scope of this issue** is now only that:
* Guidance 2 needs to be updated for the `from()` operator
* Guidance 3 should be contra-indicated for distribution.

**Comment by blesh** [comment]
> @blesh that's what he referenced above...

Ah, I didn't see the blue text. I think I was reading this on my phone.

**Comment by blesh** [comment]
Closing this issue as stale.
