### ISSUE TITLE
zip operator's type definition is incompatible with RxJS v4

### ISSUE THREAD

**Issue by saneyuki** [ReactiveX/RxJS#1208]
- v4: https://github.com/Reactive-Extensions/RxJS/blob/master/ts/core/linq/observable/zip.ts
- v5
   - https://github.com/ReactiveX/RxJS/blob/master/src/operator/zip.ts
   - https://github.com/ReactiveX/RxJS/blob/master/src/operator/zip-support.ts
   - https://github.com/ReactiveX/RxJS/blob/master/src/operator/zip-static.ts
- maybe related to #1086

**Comment by kwonoj** [comment]
@david-driscoll , as well as #1209 I assume this is related with your current effort of introducing n-number parameter signatures for some operators, is my understanding correct?

**Comment by david-driscoll** [comment]
Yep, most of the work is done on the RxJS4 side, just need to migrate it over to RxJS5 without interuptions.  Once #1086 lands, I was planning on adding more for `zip`, `withLatestFrom`, `combineLatest` (static) and more.

**Comment by david-driscoll** [comment]
Based on one of my previous attempts at getting the typings working, I have the following (at the time generated file) that has pretty much all they typings we're looking for.  It's a little outdated, but I'll be pulling from there to start.

https://github.com/david-driscoll/RxJS-1/blob/all-types/src/operator-typings.ts

**Comment by kwonoj** [comment]
https://github.com/ReactiveX/RxJS/pull/1086 is now checked in, those change can be used as reference to other operators as well.

**Comment by kwonoj** [comment]
Closing this issue via https://github.com/ReactiveX/RxJS/pull/1292.
