### ISSUE TITLE
withLatestFrom operator's type definition is incompatible with RxJS v4

### ISSUE THREAD

**Issue by saneyuki** [ReactiveX/RxJS#1209]
- v4
  - https://github.com/Reactive-Extensions/RxJS/blob/master/ts/core/linq/observable/withlatestfrom.ts
- v5
  - https://github.com/ReactiveX/RxJS/blob/master/src/operator/withLatestFrom.ts
- maybe related to  #1086

**Comment by kwonoj** [comment]
https://github.com/ReactiveX/RxJS/pull/1086 is now checked in, those change can be used as reference to other operators as well.

**Comment by blesh** [comment]
@saneyuki can you more clearly give an example of what the issue is? Is this just a TypeScript typings issue?

**Comment by kwonoj** [comment]
Yes, this is about type definition support. Original issue at https://github.com/ReactiveX/RxJS/issues/1173.

**Comment by saneyuki** [comment]
@kwonoj 

Thank you for the reply instead of me.
This would be resolved by #1293

**Comment by kwonoj** [comment]
Closed via https://github.com/ReactiveX/RxJS/pull/1293.
