### ISSUE TITLE
Multiple Subscribers (beta.1): Observable.publish().connect().subscribe is no longer there

### ISSUE THREAD

**Issue by ThiagoT1** [ReactiveX/RxJS#1215]
While subscribing to angular2 http requests, on beta.0 , Observable.publish().connect().subscribe would allow for multiple subscribers to read the same data, even if the observable was complete.

On beta.1, this will not work and one has to use publishLast() to accomplish (apparently) the same thing.

Did that make it to the changelog?

**Comment by trxcllnt** [comment]
@thiagot1 `connect` returns a Subscription, which doesn't have a subscribe method. Perhaps you're thinking of `refCount`?

**Comment by ThiagoT1** [comment]
I'll give it a try. In beta.0 there was a subscribe method on whatever
connect () was returning. I didnt look what it was because one never digs
into code that works o_Ò

My solution was using

    pub = ob.publishLast();
    pub.connect ();
    pub.subscribe (...)

While on beta0 the following worked:

    ob.publish ().connect ().subscribe (...)

Is that the right way?

Thanks for the reply.

Thiago

**Comment by trxcllnt** [comment]
@ThiagoT1

**Comment by ThiagoT1** [comment]
Thanks for explaining.

Maybe it could be added to the change log so others see it right away.
