### ISSUE TITLE
RefCountSubscriber should forward on `error` and `complete` messages before unsubscribing

### ISSUE THREAD

**Issue by trxcllnt** [ReactiveX/rxjs#1220]
When `RefCountSubscriber` receives an [error](https://github.com/ReactiveX/RxJS/blob/master/src/observable/ConnectableObservable.ts#L91) or [completion](https://github.com/ReactiveX/RxJS/blob/master/src/observable/ConnectableObservable.ts#L96) from its source, it should forward on the message before disposing its subscription to the source. [This example](http://requirebin.com/?gist=ae2154771f58b541c54c) prints:
```
unsubscribe
1. done
2. done
```

but should print

```
1. done
unsubscribe
2. done
```

**Comment by blesh** [comment]
Why is this the desired behavior?

**Comment by trxcllnt** [comment]
@blesh because the order of in subscription is that dispose always runs after `error` or `complete`.

**Comment by blesh** [comment]
I just wanted to make sure it was in the Issue so people could have a reason. (The original post didn't totally describe the problem.)

**Comment by blesh** [comment]
@trxcllnt ... I feel like this has been resolved over the past several months. Can you confirm?

**Comment by trxcllnt** [comment]
@blesh yes this is done.
