### ISSUE TITLE
Missing Observable#toPromise and Observable#just?

### ISSUE THREAD

**Issue by ps2goat** [ReactiveX/RxJS#1221]
I'm using rxjs v. 5.0.0-beta.1 from npm, along with angular2 2.0.0-beta.0.

I see the definitions for `toPromise` and `just` in the TypeScript definition files, but I'm getting the following errors when trying to use them in the browser:

Uncaught TypeError: context.returnsObservable(...).just() is not a function(…)
Uncaught TypeError: context.returnsObservable(...).toPromise() is not a function(…)

My TypeScript class is importing observable-- I couldn't find anything else that I needed to import:
> `import { Observable } from 'rxjs/rx';`

Am I missing something, or has this not been fully implemented, yet?

**Comment by kwonoj** [comment]
You may import `Rx` for module contains core operators like

`import * as Rx from 'rxjs/rx';`

`Rx` is out of box prepared module contains most of common operator for use.

In case of module `Observable`, it allows to import each individual operator you'd like to include instead of import everything at once, such as 

```
import {Observable} from 'rxjs/Observable';
import 'rxjs/add/operator/map';

Observable.of(1,2,3).map(x => x + '!!!'); // etc
```

This (https://github.com/ReactiveX/RxJS#es6-via-npm) will gives brief explanations of importing it.

For operator `just`, you can use `of`.

**Comment by kwonoj** [comment]
@ps2goat , let me close this issue by module import is instructed and believe you can import either core module or separate module. If you're experiencing problems still with those, please feel freely reopen.

**Comment by whitecolor** [comment]
`just` operator  in rx4 was quite explicit and beautiful especially when uses just as "naked" factory:
```
let {just, of} = Rx.Observable

source$ = just(1) // is better than:
source$ = of(1)
```

**Comment by ps2goat** [comment]
`import * as Rx from 'rxjs/rx';` did work for me.  It was just confusing that the typings said a method was there, but it really wasn't until I'd imported each extension (e.g., the `*` alias).

**Comment by J0NNYZER0** [comment]
You are making the same mistake I, and hundreds of other actually made. Simple fix:
npm uninstall rxjs --save
npm install rx --save

There are two libraries on npm and it is quite misleading if you don't look carefully.
On npm:
rx relates to https://github.com/Reactive-Extensions/RxJS
rxjs relates to github.com/ReactiveX/RxJS

Feel free to send a message to jeffbcross and ask him to disclaim the difference between his lib and what I refer to as the official one. If he leaves this it will be a confusing fork in the road which will continue to impact others.

**Comment by trxcllnt** [comment]
@J0NNYZER0 yes, the `rx` package is not this project.

**Comment by alobakov** [comment]
That's very interesting, because @angular v2.1.0 depends on rxjs 5.0.0-beta.12 which is **this** project.
And it does seem to be lacking Observable#just.
Is there anything that could be used instead? Would `of()` with one element produce the same result?

**Comment by trxcllnt** [comment]
@alobakov yes, Observable.of with one element is intended to replace just.
