### ISSUE TITLE
Unintuitive import paths

### ISSUE THREAD

**Issue by luisgabriel** [ReactiveX/RxJS#1226]
Currently, from the user perspective, it's not clear the difference between the operators imported from `rxjs/add/operator/*` and `rxjs/add/observable/*`. Initially, one can think that static operators are placed under the `observable` directory while the instance operators are placed under `operator`. But this is not the case because some static operator such as `zip` and `merge` are placed under `operator` also.

Example:
```typescript
import {Observable} from 'rxjs/Observable';
import 'rxjs/add/observable/never';    // static operator
import 'rxjs/add/operator/map';        // instance operator
import 'rxjs/add/operator/zip-static'; // static operator
```

I think it would be better to have a clear distinction between the two kinds of operators. For example: `operator/<name>` and `operator/static/<name>`.

**Comment by blesh** [comment]
I think `zip-static` should be under `observable` as `rxjs/add/observable/zip`. Because it creates an Observable. Same for other similar ones.

**Comment by luisgabriel** [comment]
#1238 addresses this issue.
