### ISSUE TITLE
Expose RefCountObservable (for extensibility)

### ISSUE THREAD

**Issue by bholloway** [ReactiveX/RxJS#1227]
I appreciate that `refCount()` operator is specific to `ConnectableObservable`. However I was hoping that the class `RefCountObservable` could either be:

A. exposed on module exports
**or**;
B. moved to its own file (obviously taking `RefCountSubscriber` with it).

Right now if I want to extend it I have to do so non-declaratively by intuiting its `constructor`. Specifically:

```javascript
var RefCountObservable = (new Rx.ConnectableObservable())
  .refCount()
  .constructor;
// ... extend procedurally
```

My application [can be seen here](https://github.com/bholloway/rx-operators/blob/master/operator/lifecycle.js) but isn't really relevant aside from saying that I would like to make it clearer with a declarative `class` syntax.

If (A) is as simple as adding the `export` keyword in front of `class RefCountObservable<T>` then I can certainly do a PR for that. However I suspect that (B) is the better solution.

**Comment by trxcllnt** [comment]
@bholloway could you elaborate on why you need to extend `RefCountObservable`? It's likely to be removed in a future refactor in favor of a smarter `RefCountOperator`/`RefCountSubscriber` duo.

**Comment by bholloway** [comment]
Hey @trxcllnt. Sorry to be a thorn in your side but I appreciate the support!

I have a number of [operators](https://github.com/bholloway/rxjs-operators#operator) that each output a RefCountObservable with some changes or additions.

**Example:**

The lifecycle operator.

![](https://github.com/bholloway/rxjs-operators/raw/master/operator/lifecycle.png)

The interesting parts are:
* [Obtaining the reference](https://github.com/bholloway/rxjs-operators/blob/master/operator/lifecycle.js#L5) to RefCountObservable.
* The [constructor](https://github.com/bholloway/rxjs-operators/blob/master/operator/lifecycle.js#L49), per your previous guidance.
* [Overriding `_subscribe`](https://github.com/bholloway/rxjs-operators/blob/master/operator/lifecycle.js#L88) on RefCountObservable, quite messy without declarative class syntax

**Comment by trxcllnt** [comment]
@bholloway I suppose I still don't understand, what problems are you trying to solve? From what I can tell, you're re-implementing [`publishBehavior`](https://github.com/ReactiveX/RxJS/blob/master/src/operator/publishBehavior.ts) and [`publishReplay`](https://github.com/ReactiveX/RxJS/blob/master/src/operator/publishReplay.ts), but I could be wrong.

**Comment by bholloway** [comment]
**Feature**

Ok so the key operator I am interested in would give me an observable reference-count for published observables.

If extending `RefCountObserable` is brittle, then I could probably create a similar but separate operator, that just counts the number of subscriptions without aggregating them. Extending `Observable` and not `RefCountObservable`.

However the more that I think about it, the more I feel that `RefCountObserable.refCount:number` should instead be observable.

This could be added in a non-breaking way by an optional subject parameter `ConnectableObservable.refCount([subject:Subject])`.
```
var observable = new Rx.Subject();
var countSubject = new Rx.BehaviorSubject(0);
var multicasted = observable
  .publish()
  .refCount(countSubject);

countSubject.subscribe();                    // -> countSubject.next(0)
var subscription = multicasted.subscribe();  // -> countSubject.next(1)
subscription.unsubscribe();                  // -> countSubject.next(0)
observable.complete();                       // -> countSubject.complete(), multicasted.complete()
```

**Rationale**

I want to build a data-model that will self-destructs when observers reach zero.

However with my growing knowledge of `Rx` I suspect that the `.finally()` operator will possibly do what I want. I need to investigate further.

**Comment by trxcllnt** [comment]
@bholloway `refCount` subscribes to the source when the subscriber count grows above zero, and unsubscribes from the source when the subscriber count drops to zero. If your model is expressed as an Observable that cleans up when it's disposed, then the current behavior of `refCount` should work fine, right?

**Comment by bholloway** [comment]
Yes @trxcllnt that was what I was thinking.

> However with my growing knowledge of Rx I suspect that the .finally() operator will possibly do what I want. I need to investigate further.

It is good to know that I will find the solution there.

Overall I think that the operator library I have been working on is superfluous. But I am happy for the elegance of RxJS to make further work to be unnecessary. And in writing it (and with thanks again to your assistance) I have gained the insight i need.

As a matter of opinion, I think it is more consistent with the spirit of Rx to observe reference-count. But this is a different matter.
