### ISSUE TITLE
Observable.for

### ISSUE THREAD

**Issue by rgbkrk** [ReactiveX/rxjs#1231]
In RxJS 4, there's a great [guide for people hoping to transition from async.js to RxJS](https://github.com/Reactive-Extensions/RxJS/blob/8f12f812d497acf639588e90f74d504a9fc801ec/doc/mapping/async/comparing.md#asyncmap). These rely on `Observable.for`, which appears to not be included in RxJS5 (unless I'm mistaken).

**Comment by bholloway** [comment]
Dear @rgbkrk, this may be the blind leading the blind but I will have a go.

Definely have a look at [reactivex.io operator list](http://reactivex.io/documentation/operators.html#categorized) if you haven't already seen it. It is very helpful but slightly out of date in one or two operators.

For [this example](https://github.com/Reactive-Extensions/RxJS/blob/8f12f812d497acf639588e90f74d504a9fc801ec/doc/mapping/async/comparing.md#rxjs-version-1) I believe that you can use [`from()`](http://reactivex.io/documentation/operators/from.html#collapseRxJS) to pull in the Array, and promises with[ `flatMap()`](http://reactivex.io/documentation/operators/flatmap.html#collapseRxJS).

```javascript
var fsp  = require('fs-promise'),
    RxJS = requie('rxjs');

RxJS.Observable.from(['file1.txt', 'file2.txt', 'file3.txt'])
  .flatMap(fsp.statSync)
  .forEach(function () {
    // do something
  })
```

**Comment by rgbkrk** [comment]
Ha, that's ok. Still no `from`, that's ok though as `fromArray` works with 

What I ended up noticing last night was that I could use `bindNodeCallback` to create an observable:

```JavaScript
const Rx = require('rxjs/Rx')
const Observable = Rx.Observable

function kernelSpecs(cb) {
  const kd = expectedKernelDirs()
  return Observable.fromArray(kd)
                   .flatMap(x => stat(x))
                   // other ops
}
```

I'm likely breaking this code up a bit differently, though the `fromArray` certainly works.

**Comment by rgbkrk** [comment]
D'oh. I feel like a dolt. You used `from`, not `for`. Sorry about that @bholloway and thank you for chiming in. :smile:

**Comment by bholloway** [comment]
Glad I could help.

The team here has given me so much help its good to pay some back.

**Comment by trxcllnt** [comment]
@rgbkrk thanks for reminding me we need to implement `Observable.for`. Re-opening this issue to track progress @blesh

**Comment by blesh** [comment]
@trxcllnt ... `Observable.for` is the same as `Observable.from`. We chose `from` to meet the spec. Why do we need both?

**Comment by trxcllnt** [comment]
@blesh `for` enumerates the items in the list, runs them through a selector, and concatMaps whatever the selector returns. Sure it can be done with `from(sources).concatMap(sourceItemToObservable)` but it's already public API used in a lot of existing docs, it'd be strange to leave it out.

**Comment by blesh** [comment]
so... it's a static concatMap? Can we call it `Observable.concatMap`? I'd hate for people to trip over `for`/`from`.

**Comment by blesh** [comment]
... I guess I never used `for` in that manner, or maybe I never used it. I'm pretty minimalist with my operator and creation function usage.

**Comment by rgbkrk** [comment]
The other option is to translate the `async` module examples over to RxJS 5 to help people write idiomatic RxJS. I'm not sure if what I have is the best option right now and I wanted to stop myself from polluting your issues with my "how do I do this with RxJS 5" questions.

**Comment by blesh** [comment]
> so... it's a static concatMap? Can we call it Observable.concatMap? I'd hate for people to trip over for/from.

I mean, `for` is terse, but it doesn't accurately describe what it's doing does it? `of`/`for`/`from` are all so similar-ish to me, where static `concatMap` seems more straight forward.

attn @trxcllnt @mattpodwysocki

**Comment by blesh** [comment]
Closing this issue as stale.
