### ISSUE TITLE
Rolling out the documentation

### ISSUE THREAD

**Issue by HighOnDrive** [ReactiveX/RxJS#1233]
Pretty eager here to digest RxJS 5 and get enough of a solid grounding to proceed in a stable way. Toward this end I've been building my self a little/huge database of the the entities and operators and related snippets. It is much easier if there are categories for operators so I've been assigning them to operators as I get to know them.

Looking around it does not really seem that RxJS 5 is anywhere near being ready for documentation, or am I wrong about that? I just saw the issue called ".timestamp() operator #1192" and it seems the timestamp operator fell through the cracks and might yet be developed, huh. What about generators and a whole slew more in my list that are not accounted for?

What I'm shooting for is a table of categorized operators that also has additional information on what will be left behind in RxJS 4. I'm a fair ways towards having assembled this table and am wondering where I might ask a few questions for clarification as I proceed?

Over all, I'm also very interested about when documentation for RxJS 5 might begin to be rolled out?

**Comment by rgbkrk** [comment]
Whoops, I just posted a similar issue in #1242. @blesh convinced me to switch over to RxJS 5 and I'm more than happy to squeeze in bits of documentation time here and there as I'm building with it.

**Comment by staltz** [comment]
I think we can close this issue. it's a dup of #1242

**Comment by kwonoj** [comment]
I think so too. Let's use #1242 as single tracking issue for document if necessary, it already contains most of discussions.

**Comment by kwonoj** [comment]
Thanks @HighOnDrive for opinions, now we started rolling snowballs for documentation and it's growing, with huge contribution from @staltz mostly. I also hope to see full documentation coming soon! :)
