### ISSUE TITLE
Need to identify operators that don't support Promises and Should

### ISSUE THREAD

**Issue by blesh** [ReactiveX/rxjs#1246]
As noted in #1245, there are probably many operators that take functions that return Observables, and should support returning Promises, Arrays, or "observablesque" objects.

I'd greatly appreciate anyone with free time to comb the operators and identify the ones that are missing this feature. Then we can list them out here and create new, separate issues for each one of them.

**Comment by staltz** [comment]
I also noticed this while updating the documentation for operators at reactivex.io. I went through the operators and identified these:

- [ ] buffer (maybe supports Promises, but maybe needs types updated)
- [ ] bufferToggle (!!)
- [ ] bufferWhen (maybe supports Promises, but maybe needs types updated)
- [ ] catch (!!)
- [ ] concat (maybe supports Promises, but maybe needs types updated)
- [x] concatAll
- [ ] concatMap (maybe supports Promises, but needs types updated)
- [ ] concatMapTo (maybe supports Promises, but needs types updated)
- [x] debounce
- [ ] distinct (the flushes parameter)
- [ ] distinctKey (the flushes parameter)
- [x] exhaust
- [ ] exhaustMap (maybe supports Promises, but needs types updated)
- [ ] expand (maybe supports Promises, but needs types updated)
- [ ] merge (maybe supports Promises, but maybe needs types updated)
- [x] mergeAll
- [ ] mergeMap (maybe supports Promises, but needs types updated)
- [ ] mergeMapTo (maybe supports Promises, but needs types updated)
- [ ] mergeScan (maybe supports Promises, but needs types updated)
- [ ] race (maybe supports Promises, but needs types updated)
- [ ] retryWhen (maybe supports Promises, but needs types updated)
- [ ] sample (maybe supports Promises, but needs types updated)
- [ ] skipUntil (maybe supports Promises, but needs types updated)
- [x] switch
- [ ] switchMap (maybe supports Promises, but needs types updated)
- [ ] switchMapTo (maybe supports Promises, but needs types updated)
- [ ] takeUntil (maybe supports Promises, but needs types updated)
- [x] throttle
- [ ] timeoutWith (maybe supports Promises, but needs types updated)
- [ ] window (!!)
- [ ] windowToggle (maybe supports Promises, but needs types updated)
- [ ] windowWhen (maybe supports Promises, but needs types updated)
- [ ] withLatestFrom (maybe supports Promises, but needs types updated)
- [ ] zip (maybe supports Promises, but needs types updated)
- [x] zipAll

**Comment by blesh** [comment]
I believe we've already gone through and done all of this. Closing for now. We can open new issues on a per-operator basis.
