### ISSUE TITLE
OuterSubscriber::notifyNext() to pass its innersubscriber?

### ISSUE THREAD

**Issue by kwonoj** [ReactiveX/RxJS#1250]
I'm not sure if this is legit, please consider it as speaking out my thought - feel freely close if it's not appropriate.

`OuterSubscriber` 's interface for `error` and `complete` passes its innersubscription when it occurs, as 
```
notifyError(error: any, innerSub: InnerSubscriber<T, R>)
notifyComplete(innerSub: InnerSubscriber<T, R>)
notifyNext(outerValue: T, innerValue: R, outerIndex: number, innerIndex: number)
```

while `notifyNext` doesn't. Came to think align interfaces `notifyNext` also, for some cases of support early-unsubscription as soon as inner emits like `delayWhen`, i.e

```
source              : --a--b--|
selector            :   -x--|
                           --x----|
selectorSubscription:   ^!
                           ^ !
```

subscription to selector observable unsubscribes as soon as selector emits, or either completes without emitting. If `notifyNext` passes its subscription, outer subscriber doesn't have to holds reference or need to lookup to manage subscription, allows snippet like

```
notifyNext(..., innseSub) {
//do things
innerSub.unsubscribe();
this.remove(innerSub);
}
```

**Comment by trxcllnt** [comment]
@kwonoj I remember wanting this a while back as well, so I'm in favor of this change.

**Comment by kwonoj** [comment]
I can gladly take effort to create PR if this reaches agreed to have.

**Comment by blesh** [comment]
I'm indifferent. Just be sure to test perf before and after.

**Comment by kwonoj** [comment]
Cool, I'll come up PR with perf comparison to see if this change does not hurt existing operator behavior.
