### ISSUE TITLE
groupby test failures on some browsers

### ISSUE THREAD

**Issue by kwonoj** [ReactiveX/RxJS#1257]
Browser testing shows some of browser does have unexpected behavior on [test case] 
(https://github.com/ReactiveX/RxJS/blob/master/spec/operators/groupBy-spec.js#L7) , like below:

```
Mobile Safari 7.0.0 (iOS 7.1.0) Observable.prototype.groupBy() should group numbers by odd/even FAILED
	Expected 
	{"frame":20,"notification":{"kind":"N","value":"[
		{"frame":0,"notification":{"kind":"N","value":"1","hasValue":true}},
		{"frame":80,"notification":{"kind":"N","value":"3","hasValue":true}},
		{"frame":160,"notification":{"kind":"N","value":"5","hasValue":true}},
		{"frame":200,"notification":{"kind":"C","hasValue":false}}
	]","hasValue":true}}
	{"frame":60,"notification":{"kind":"N","value":"[
		{"frame":0,"notification":{"kind":"N","value":"2","hasValue":true}},
		{"frame":80,"notification":{"kind":"N","value":"4","hasValue":true}}
	]","hasValue":true}}
	{"frame":220,"notification":{"kind":"C","hasValue":false}}
	
	to deep equal 
	{"frame":20,"notification":{"kind":"N","value":"[
		{"frame":0,"notification":{"kind":"N","value":"1","hasValue":true}},
		{"frame":80,"notification":{"kind":"N","value":"3","hasValue":true}},
		{"frame":160,"notification":{"kind":"N","value":"5","hasValue":true}},
		{"frame":200,"notification":{"kind":"C","hasValue":false}}
	]","hasValue":true}}
	{"frame":60,"notification":{"kind":"N","value":"[
		{"frame":0,"notification":{"kind":"N","value":"2","hasValue":true}},
		{"frame":80,"notification":{"kind":"N","value":"4","hasValue":true}},
		{"frame":160,"notification":{"kind":"C","hasValue":false}}
	]","hasValue":true}}
	{"frame":220,"notification":{"kind":"C","hasValue":false}}
```

occurs on < android 5, < IE 11, ios 7.

**Comment by staltz** [comment]
Is this the only test that fails or are there many?

**Comment by kwonoj** [comment]
This one's only failure under groupby so far I observed. You can see full logs in here. https://travis-ci.org/ReactiveX/RxJS/builds/105222911 . (Ignore failure under edge browser which is not test for groupby, it's covered in https://github.com/ReactiveX/RxJS/pull/1225)

**Comment by staltz** [comment]
@kwonoj this error makes no sense to me, specially considering that it's only one test (the simplest one) which is failing. How can I run these tests in saucelabs myself?

**Comment by kwonoj** [comment]
@staltz go to travis configuration, set `SAUCE_USERNAME` and `SAUCE_ACCESS_KEY` in your forked repo.

![image](https://cloud.githubusercontent.com/assets/1210596/12679038/b9ba4eb6-c656-11e5-8c9b-b063c9a3f9dc.png)

**Comment by staltz** [comment]
Ah neat. We need those instructions in CONTRIBUTING too
