### ISSUE TITLE
Break SymbolShim into it's own repository/package

### ISSUE THREAD

**Issue by blesh** [ReactiveX/rxjs#1280]
Because there are a few libraries that would want to use `Symbol.observable` to know how to interop with RxJS 5 (and other Observable libraries). We should split the SymbolShim out into it's own package. This is so other libraries that just want to use `Symbol.observable` don't need to duplicate code or install RxJS just to do so.

**Comment by michaelbpaulson** [comment]
Also found in Falcor itself: https://github.com/Netflix/falcor/pull/699

**Comment by kwonoj** [comment]
Latest codebase dropped shim to Symbol via https://github.com/ReactiveX/rxjs/issues/1425, maybe this issue can be closed?

**Comment by blesh** [comment]
This is already done with `http://github.com/blesh/symbol-observable` at least to some degree with `Symbol.observable`.
