### ISSUE TITLE
RxJS 5 bufferWithTimeOrCount? (add maxCount to bufferTime)

### ISSUE THREAD

**Issue by avielfedida** [ReactiveX/rxjs#1295]
So RxJS 5 currently not containing `bufferWithTimeOrCount`, is it planned to be added in the future?, anyway I was looking for comparable way to "do" `bufferWithTimeOrCount` in RxJS 5, should I create my own operator or there is a nicer combo with the already ported operators?

**Comment by blesh** [comment]
Hmmm... seems like an oversight. I think we can probably add an additional argument to `bufferTime` to cover this without impacting performance greatly.

Until we add that, you could use something like this: 

(I haven't tested it, and it looks a little gross but with some tweaks it may work):

```js
function bufferWithTimeOrCount(source, duration, bufferSize) {
  let reset = false;

  const buffers = source.scan((buffer, x) => {
    if (reset) {
      buffer = [];
      reset = false;
    }
    buffer.push(x);
    return buffer;
  }, []).share();

  const bufferCounted = buffers.filter(buffer => buffer.length < bufferSize);
  const timer = Observable.of(null).merge(bufferCounted).switchMap(() => Observable.timer(duration));
  
  return buffers.sample(timer.merge(bufferCounted)).do(() => reset = true);
}
```

**Comment by blesh** [comment]
Thank you for your patience and for bring this issue up for us, @avielfedida. We'll get it fixed.

**Comment by blesh** [comment]
### Contributors or those looking to implement this:

The idea I have here is that we can add an optional `maxBufferSize` parameter to `bufferTime` (likewise with `windowTime`) that would default to `Number.POSITIVE_INFINITY`. Then rework the the operator to support that functionality.

**Comment by justinwoo** [comment]
Sorry if I have the details wrong, but `bufferTimeOrCount` only allows a single buffer at a time, right? And as soon as a buffer is flushed, the new buffer starts immediately? [(e.g. this JSBin for single/double clicks)](http://jsbin.com/fupexuw/1/edit?js,console,output)

It looks like in the current implementation of `bufferWithTime`, you'd have to purposefully limit the scheduling of opening multiple buffers and all, which sounds hard/like a lot of work.

I have a small implementation for `bufferTimeOrCount` with [this base spec](https://github.com/justinwoo/RxJS/blob/be8a6b89ae9c98542aeca0d0cb417523f289377b/spec/operators/bufferTimeOrCount-spec.js#L7-L22), but I don't know if this necessarily behaves as expected.
