### ISSUE TITLE
chore(community): would be nice to have a gitter chat room

### ISSUE THREAD

**Issue by valorkin** [ReactiveX/RxJS#1296]
Hey, guys
You doing a really great job!

but there so many question, especially for those who only starts to rxjs
and with angular2 coming with rxjs on board it will even more

So it would be really good to have gitter chat room
It will take only a minute of your time,
but it is hard to over estimate value it brings :)

Here is direct link to room creation
https://gitter.im/orgs/ReactiveX/rooms#createroom

Thanks in advance

**Comment by kwonoj** [comment]
There is, please refer https://gitter.im/Reactive-Extensions/RxJS . It's not under ReactiveX org though.

**Comment by kwonoj** [comment]
There is already opened chat channel, and I've created small PR to indicate current repo's document to point those, so let me close this issue. @valorkin , hope this answers your question and feel freely comment / reopen if there's additional followup's required.
