### ISSUE TITLE
Rxjs 5 Beta 1 using System.js in Browser

### ISSUE THREAD

**Issue by ziaukhan** [ReactiveX/RxJS#1299]
I am unable to run Rxjs in browser using System.js

The complete code project is here:
https://github.com/panacloud/learn-typed-rxjs/blob/master/step02_in_browser/

I am getting the following error:
https://www.dropbox.com/s/oj1o5evzu2rv4q5/Screenshot%202016-02-03%2022.16.39.png?dl=0

**Comment by blesh** [comment]
I'm not really a System.js expert, so I'll defer to @robwormald or @jeffbcross on this one... but it looks like something with how you're building [your main.js file](https://github.com/panacloud/learn-typed-rxjs/blob/ab44f4728d64a488357287fea2f7f181b5ab08ec/step02_in_browser/app/main.js#L1). It's calling `System.register("rxjs/Observable")` which is likely trampling the definition of the "real" one in rxjs.

**Comment by ziaukhan** [comment]
At last it is working have pushed the updated code here:
https://github.com/panacloud/learn-typed-rxjs/tree/master/step02_in_browser
Thanks
