### ISSUE TITLE
dispose/unsubscribe inside subscribe function block

### ISSUE THREAD

**Issue by jsec516** [ReactiveX/rxjs#1319]
I've a **subject** called **authenticated** in **_auth** service. 

I want to **dispose/unsubscribe** it **if some condition fails** so that this subscribe doesn't call when next value arrives in authenticated subject.

 ```
this.sub = this._auth.authenticated
      .subscribe((loggedIn) => {
             if (!loggedIn) {
                     this.sub.dispose(); // doesn't work because this.sub is null
                     this._location.replaceState('/');
                     this._auth.doLogout(); // emits value again in authenticated subject
              }
        });
```
What is the rxjs-5 way of doing it?

**Comment by trxcllnt** [comment]
It's difficult to say exactly without knowing how the rest of the code works, but you probably want `takeWhile`. If you remove the `authenticated` Subject, it'll be easier to reason about.

```es6
this._auth.authenticated
  .takeWhile((loggedIn) => loggedIn)
  .concat(() => {
    this._location.replaceState('/');
    this._auth.doLogout(); // <-- this should really return its own Observable
                           // rather than writing to the authenticated Subject
    return Rx.Observable.empty();
  })
  .repeat()
  .subscribe();
```

**Comment by jsec516** [comment]
@trxcllnt Thanks for your reply, I'm trying to implement your code. 
However here is the _auth definition:

```
export class AuthService { 
   authenticated: Subject<Boolean> = new BehaviorSubject<Boolean>(false);

  // login user
  public doLogin(user: string, password: string) {
    this.authenticated.next(true);
  }
   .....
   // logout user
    public doLogout() {
        this.clearCookie(); // clear the cookies
        this.authenticated.next(false); //writing to the subject
        this.router.navigate(['Default']); // routing to default authentication page
    }
   ......
}
```
Basically, authenticated subject initiated as false, then when user logged in I just write a value in authenticated subject (true) and when user logged out/expires session then it emits false value.

I'm new in rxjs and I'm not sure if that's the correct way of doing it.

**Comment by blesh** [comment]
Closing as stale.
