### ISSUE TITLE
Add build for Rx.DOM.umd.js

### ISSUE THREAD

**Issue by randallr** [ReactiveX/rxjs#1322]
Add build target for generating Rx.DOM.umd.js

**Comment by kwonoj** [comment]
@randallr , this issue is being tracked by publishing strategy issue https://github.com/ReactiveX/rxjs/issues/1506 - so let me close this one. If there's suggestion, feel freely suggest via #1506. Once it's established, probably there'll be separate npm package supporting rxjs-dom module.
