### ISSUE TITLE
Include benchmarks in master branch CI build

### ISSUE THREAD

**Issue by jeffbcross** [ReactiveX/rxjs#1325]
Run the benchmarks in one browser on the master branch CI job so that we can verify that benchmarks aren't broken. The data from the benchmarks can be ignored, since the machines the benchmarks will be run on are not likely to have consistent performance.
- [ ] Check that browser console is empty after each spec
- [ ] Add protractor to Travis config

**Comment by blesh** [comment]
They don't appear to "fail" in error situations though. Just return zeroes.

**Comment by jeffbcross** [comment]
@blesh good point, I need to add a check after each benchmark to make sure nothing is logged in the browser console. The issues fixed by #1324 all correlated to errors in the browser console, but the errors aren't visible in the benchpress reports.

**Comment by blesh** [comment]
Closed for staleness
