### ISSUE TITLE
Error when installing via Composer npm-asset/rxjs

### ISSUE THREAD

**Issue by lchambers** [ReactiveX/rxjs#1327]
Hey,

I'm trying to install the library via Composer using the "npm-asset/rxjs": "5.0.0-beta.0" package but when I run the update command I get the following error:

`Could not parse version constraint 20150920.0.0: Invalid version string "20150920.0.0"`

After running the update in verbose mode it lead me to the registry output [here](https://registry.npmjs.org/rxjs).

Within that there's a dev dependency: google-closure-compiler": "20150920.0.0", which has the version number listed in the error above.

Is there any way around this error or can it be updated? I've also tried the version 5.0.0-beta.1 and I get the same error.

Thanks

**Comment by kwonoj** [comment]
It's due to composer's semver component, and seems there isn't simple workaround for this for now. There's opened issue on composer side at https://github.com/composer/semver/issues/32 to discuss this issue.

**Comment by blesh** [comment]
@lchambers can you use a patch version selector like  `5.0.*`? Because that might get you around this problem.

**Comment by lchambers** [comment]
@kwonoj thanks, I found that later on after posting my initial issue. Slightly frustrating issue given the Semver specs dictate how to use version numbering correctly, which has been ignored in this instance.

@blesh no, that won't work as the issue lies in the version number set on the "google-closure-compiler" dev dependency of this package, so changing it to a patch version selector results in the same error.

**Comment by kwonoj** [comment]
Although it's long hanging issue, I'm afraid there aren't many option for this. Either google changes version scheme (not likely) or composer allows its version scheme (also somewhat not likely) or this repo takes out closure or use 3rd party bindings instead of official package.

**Comment by blesh** [comment]
This seems to have gone stale. I'm closing it. @lchambers if you're still having issues, please reopen or open a new issue.
