### ISSUE TITLE
Some macro perf tests are failing or seem off

### ISSUE THREAD

**Issue by blesh** [ReactiveX/rxjs#1328]
So, @jeffbcross fixed the issues we were having with the macro perf tests here: #1324

In running them while reviewing the PR, I saw a lot of strange behavior and errors in those tests.
#### Jasmine Timeouts

Errors were all Jasmine timeout errors: `Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.`

```
1) mergeAll comparison should be fast in Rx2
2) mergeAll comparison should be fast in Rx2
3) mergeAll comparison should be fast in RxNext
4) mergeMap comparison should be fast in Rx2
5) mergeMap comparison should be fast in RxNext
6) mergeMap comparison should be fast in Rx2
7) mergeMap comparison should be fast in RxNext
8) mergeMap comparison should be fast in Rx2
9) mergeMap comparison should be fast in RxNext
10) mergeMap comparison should be fast in Rx2
11) mergeMap comparison should be fast in RxNext
12) windowCount comparison should be fast in Rx2
13) windowCount comparison should be fast in RxNext
14) windowCount comparison should be fast in Rx2
15) windowCount comparison should be fast in RxNext

36 specs, 15 failures
Finished in 514.102 seconds
```
### Strange GC in a few tests

I also noticed a couple of tests had insane amounts of GC for Rx 4 (labelled Rx2) in the tests. `mergeAll Rx2` is an example of this.

```
          gcAmount |             gcTime |        majorGcTime |     pureScriptTime |         renderTime |         scriptTime
------------------ | ------------------ | ------------------ | ------------------ | ------------------ | ------------------
         974670.30 |              44.30 |               5.79 |            1379.97 |               0.21 |            1422.15
         970442.27 |              36.14 |               0.00 |            1261.60 |               0.25 |            1297.74
        1012756.53 |              34.81 |               2.48 |            1313.54 |               0.22 |            1348.33
        1019408.12 |              35.38 |               0.00 |            1298.23 |               0.12 |            1333.60
        1019347.40 |              42.73 |               0.00 |            1311.02 |               0.18 |            1353.74
        1019586.59 |              50.84 |               0.00 |            1299.88 |               0.23 |            1350.72
        1019335.30 |              58.49 |               0.00 |            1312.11 |               0.22 |            1370.59
        1019614.55 |              67.40 |               0.00 |            1310.81 |               0.11 |            1378.20
        1034140.56 |              44.60 |               4.12 |            1325.24 |               0.15 |            1369.79
        1019296.17 |              34.38 |               0.01 |            1319.54 |               0.19 |            1353.91
        1019566.30 |              43.04 |               0.01 |            1286.37 |               0.22 |            1329.41
```
### Possible EventEmitter leak

I've noticed this warning for a long time in these tests:

```
(node) warning: possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at process.addListener (events.js:239:17)
    at process.once (events.js:265:8)
    at module.exports (/GitHub/blesh/RxJS/node_modules/protractor/node_modules/selenium-webdriver/io/exec.js:119:11)
    at /GitHub/blesh/RxJS/node_modules/protractor/node_modules/selenium-webdriver/remote/index.js:173:21
    at [object Object].promise.ControlFlow.runInFrame_ (/GitHub/blesh/RxJS/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:1857:20)
    at [object Object].goog.defineClass.notify (/GitHub/blesh/RxJS/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2448:25)
    at [object Object].promise.Promise.notify_ (/GitHub/blesh/RxJS/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:564:12)
    at Array.forEach (native)
    at [object Object].promise.Promise.notifyAll_ (/GitHub/blesh/RxJS/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:553:15)
    at goog.async.run.processWorkQueue (/GitHub/blesh/RxJS/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/async/run.js:130:15
```

I think we should probably look into that.

**Comment by blesh** [comment]
cc @jeffbcross @tbosch ... your expertise is really needed here. Also I may want to come in for a visit to you guys for some more training around debugging benchpress issues.

**Comment by trxcllnt** [comment]
@blesh jasmine timeouts may have something to do with my PR a while ago to convert all tests to async because of non-deterministic race conditions in jasmine causing test failures. I'm 1000% on board with migrating to a more async-friendly test harness (like mocha or tape) if this turns into a bigger headache than it should be.

**Comment by blesh** [comment]
@trxcllnt I'm indifferent about test harnesses, for the most part. But I'm not indifferent about the time it would take to migrate tests... Can you, by chance, dig up the changes you made that you think might be causing this?

**Comment by trxcllnt** [comment]
@blesh https://github.com/ReactiveX/RxJS/commit/981da851e50cc6744956f351983dfc0db3dae1ed#diff-cc90d733f602b974c90b3ebd101b6ef8

**Comment by blesh** [comment]
@trxcllnt that shouldn't affect it, I don't think. The perf tests aren't loading that helper file.

**Comment by staltz** [comment]
The BDD style we are using in Jasmine is mostly compatible with the BDD style in mocha. Migration would be primarily touching configurations and helpers, not individual tests.

**Comment by kwonoj** [comment]
I also think migrating itself could be done without enormous effort, question's would be if we move into different framework, will it solves problems facing also will it won't cause another regressions. Hard to predict it though.

**Comment by jeffbcross** [comment]
> Errors were all Jasmine timeout errors: Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.

Sometimes this occurs when the person running the benchmarks is doing other work on the computer running the benchmarks, so the browser window doing tests gets throttled and takes longer to run benchmarks or get stable results. The ideal way to run benchmarks is to kill all unneeded processes, start the runner, and step away from the computer. Timeouts can also mean there's been a performance regression that's causing the benchmark to take longer than expected. If none of these issues are the culprit, then we can just increase the timeout (the third argument to it): `it('should ...', done => {...}, HIGH_TIMEOUT)`.

> I also noticed a couple of tests had insane amounts of GC for Rx 4 (labelled Rx2) in the tests. mergeAll Rx2 is an example of this.

We could profile that benchmark manually to make sure the gc numbers are correct. @blesh it'd be great to spend an afternoon going over BenchPress in more detail. Would be good to have @tbosch available as well.

**Comment by tbosch** [comment]
+1 for doing pair programming on this...

**Comment by blesh** [comment]
Closing because stale
