### ISSUE TITLE
Some methods are missing when importing just the desired thing

### ISSUE THREAD

**Issue by kruncher** [ReactiveX/RxJS#1336]
For instance,

**does-not-work-how-i-had-expected.js**
```javascript
var Observable = require("rxjs/Observable").Observable;
console.log(Observable.of); // undefined
```

**works-how-i-had-expected-1.js**
```javascript
var Observable = require("rxjs").Observable;
console.log(Observable.of); // [Function]
```

**works-how-i-had-expected-2.js**
```javascript
var Observable = require("rxjs/Rx").Observable;
console.log(Observable.of); // [Function]
```

**works-how-i-had-expected-3.js**
```javascript
var o = require("rxjs/Observable").Observable;
console.log(o.of); // undefined
require("rxjs");
console.log(o.of); // [Function] - The method gets mixed into `o`.
```

**Comment by kruncher** [comment]
I am a little confused over all the different npm distributions of this; perhaps I should be experimenting with `npm install @reactivex/rxjs` instead?

When RxJS is released; what will be the package name for use with the latest node.js ?

Cheers :)

**Comment by trxcllnt** [comment]
@kruncher the project is split into modules. when you `require('rxjs')`, you're [importing](https://github.com/ReactiveX/RxJS/blob/master/index.js) the most common bits of the library. When you `require('rxjs/Observable')`, you're importing _just_ the Observable class without any operators.

Batteries-included modules exist ([all](https://github.com/ReactiveX/RxJS/blob/master/src/Rx.KitchenSink.ts), [core](https://github.com/ReactiveX/RxJS/blob/master/src/Rx.ts), and [DOM](https://github.com/ReactiveX/RxJS/blob/master/src/Rx.DOM.ts)), but the operators are also individually exported to enable those whose projects are sensitive to file size. Individual operators can be imported and added to the Observable by importing them from the [`rxjs/add/`](https://github.com/ReactiveX/RxJS/blob/master/src/Rx.ts#L9) paths.

**Comment by kruncher** [comment]
`Observable.of` is a part of the ES7 proposal; I am surprised that it would be omitted from the bare-minimal `Observable` import.

I cannot see a `rxjs/add/of` import; but I guess it's hiding inside one of the options that are available.

I'll try and find out where it's hiding.

**Comment by kwonoj** [comment]
you can import `add/fromArray` to import `of`.

**Comment by kruncher** [comment]
@kwonoj thanks :)

**Comment by blesh** [comment]
It's actually `rxjs/add/observable/of` now, I think.

**Comment by kwonoj** [comment]
Oh, you're correct. I missed that. :sweat_smile:

**Comment by kruncher** [comment]
Hmm; so how does one use `rxjs/add/observable/of`?

I tried this:
```javascript
import Observable from "rxjs/Observable";
import of from "rxjs/add/observable/of";

let test = Observable::of(1, 2, 3);
```

and I tried this:
```javascript
import Observable from "rxjs/Observable";
import of from "rxjs/add/observable/of";

let test = Observable.of(1, 2, 3);
```

But neither seem to work for me.

**Comment by kwonoj** [comment]
I'm closing this issue by module structure is explained and resolved.
