### ISSUE TITLE
Concurrent exhaustMap?

### ISSUE THREAD

**Issue by ronag** [ReactiveX/rxjs#1337]
Something on the roadmap or is it possible to emulate it using existing operators?

**Comment by blesh** [comment]
Congratulations on the issue number `1337`!

... can you give us an example of the expected behavior?  is it really just `.map().exhaust()`?

**Comment by trxcllnt** [comment]
@blesh I think @ronag is noticing the lack of a `concurrent` value in `exhaust` and `exhaustMap` (like we have in `mergeMap`). We should probably add it to `switch` and `switchMap` while we're at it.

**Comment by blesh** [comment]
>  We should probably add it to switch and switchMap while we're at it.

Agree, it sounds useful and reasonable.

**Comment by blesh** [comment]
Closing due to lack of interest.
