### ISSUE TITLE
Implement static start creation operator

### ISSUE THREAD

**Issue by trxcllnt** [ReactiveX/rxjs#1344]
https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/start.md 

But can we talk about why it defaults to async scheduling? `Observable.start` would be the perfect middle ground between `Observable.defer` and `Observable.return` except for the async part. @mattpodwysocki

**Comment by trxcllnt** [comment]
@blesh @mattpodwysocki @staltz bump

**Comment by blesh** [comment]
> But can we talk about why it defaults to async scheduling?

No idea.

**Comment by blesh** [comment]
Here's a question: Could we do with with `Observable.from(fn)`? like:

```js
const source = Observable.from(() => 42);
source.subscribe(x => console.log(x));
```

**Comment by trxcllnt** [comment]
@blesh sounds legit, but I feel like the `mapFn` makes it awkward. If you provide an `ish` function and a `mapFn` function, does the `mapFn` get used?

**Comment by mattpodwysocki** [comment]
@trxcllnt @blesh it defaults to async because it's the idea of taking a perfectly synchronous function and turning it async by calling start on it.

**Comment by trxcllnt** [comment]
@mattpodwysocki I see. I suppose I'm looking for an operator to wrap a function and surface its return value as a cold Observable, so I can compose further. Basically converting any sync function to the Observable monad, though I understand why it might be a better fit for Ix (though it'd still be nice to have here).

**Comment by staltz** [comment]
> I suppose I'm looking for an operator to wrap a function and surface its return value as a cold Observable

Sounds like a job for polymorphic `from()`.

**Comment by blesh** [comment]
Closing as inactive.

**Comment by trxcllnt** [comment]
> Sounds like a job for polymorphic from()

💯
