### ISSUE TITLE
Implement the join calculus

### ISSUE THREAD

**Issue by trxcllnt** [ReactiveX/rxjs#1346]
Implement the static [when](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/when.md) and instance [`and`](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/and.md) operators.

**Comment by luisgabriel** [comment]
Maybe we should close #287 and use this issue to track the `when` implementation.

**Comment by blesh** [comment]
closing as inactive.
