### ISSUE TITLE
[Question] Extending Observable

### ISSUE THREAD

**Issue by rolandjitsu** [ReactiveX/RxJS#1353]
Do I need to add the `lift()` method if I only want to extend an `Observable` and not add an operator:
```js
import {Observable} from 'rxjs/Observable';
class MyOwnObservable extends Observable {
    constructor() {
        super();
    }
    lift(operator) {
	const observable = new MyOwnObservable();
	observable.source = this;
	observable.operator = operator;
	return observable;
    }
}
```
Or is it enough to just extend the class:
```js
import {Observable} from 'rxjs/Observable';
class MyOwnObservable extends Observable {
    constructor() {
        super();
    }
}
```

**Comment by trxcllnt** [comment]
@rolandjitsu you only need to override `lift` if you want the Observable operators (such as `map`, `filter` etc.) to return instances of _your_ Observable. This is generally most useful when you're extending to augment the Observable type, but it's also useful for other reasons, for example, to decorate Subscribers  for logging or debugging. It's up to you.

**Comment by rolandjitsu** [comment]
@trxcllnt thanks. It sounds like it is a good idea to have operators return instances of my own observable. Though not really sure if I actually need to extend the Observable. What I am after is:
```js
let obs = new MyClass();
obs.subscribe(() => { ... });
```
And the class returned is not actually an array like object, it's more of a hash. Is it a good pattern or should I look at a different approach here?

**Comment by trxcllnt** [comment]
@rolandjitsu I'm not totally clear on how you intend to use your class that extends Observable, but it's certainly not a problem that you do.

**Comment by rolandjitsu** [comment]
That's alright. I think you already answered my question, so this can be closed. Thanks
