### ISSUE TITLE
static CombineLatest type definition does not accept scheduler

### ISSUE THREAD

**Issue by kwonoj** [ReactiveX/RxJS#1354]
original signature of combinelatest accepts scheduler as last argument, 

```js
export function combineLatestStatic<T, R>(...observables: Array<any | ObservableInput<any> |
                                                    Array<ObservableInput<any>> |
                                                    (((...values: Array<any>) => R)) |
                                                    Scheduler>): Observable<R>
```

but snippet as below

`Observable.combineLatest(a, b, queueScheduler)`

is not being accepted by n-param signature missing scheduler param such as 

`export function combineLatestStatic<T, T2, T3>(v1: ObservableInput<T>, v2: ObservableInput<T2>, v3: ObservableInput<T3>): Observable<[T, T2, T3]>;`

**Comment by david-driscoll** [comment]
Probably just an oversight, should be easy enough to add.
