### ISSUE TITLE
github issue template?

### ISSUE THREAD

**Issue by kwonoj** [ReactiveX/RxJS#1355]
I think RxJS repo can also have benefit from new github issue template (https://github.com/blog/2111-issue-and-pull-request-templates) for easier PR / issue reporting from anyone who wants.

few topics can be included may be..(just came out of my head).

#### PR ####
- fix description
- related issue (if exists)
- additional references to external (if exists) 
- others?

#### Issues ####
- description
- repro code snippet
- external references (if exists)
- others?

**Comment by blesh** [comment]
For Issues, I'd like a short disclaimer saying that questions are best directed at StackOverflow which has a better format for Q&A style things. And that we'd like to keep Issues to technical problems or proposals related to the library.

**Comment by kwonoj** [comment]
> questions are best directed at StackOverflow which has a better format for Q&A style things

: Agree, +1.

**Comment by kwonoj** [comment]
Closed via https://github.com/ReactiveX/RxJS/pull/1432.
