### ISSUE TITLE
Adding child subscriptions to the parent inside of an observer callback

### ISSUE THREAD

**Issue by sbabeal** [ReactiveX/rxjs#1359]
In this example, I am subscribing to an observable that provides an object that has observable properties.  I am subscribing to these properties inside the observer callback.  What I need is that when I call hubOneObsSubscription.unsubscribe(), unsubscribe is called on the countSubscription and statusSubscription subscriptions.  Since the parent observable "hubOneObs" has been created with the .publishReplay().refCount() operators the observer function is called immediately before the assignment call to hubOneObsSubscription.  Therefore I can't call the add method inside of the callback. I tried calling this.add, since this is scoped in the callback to the subscriber however, I get a null reference exception when I try to do this.  The only way I've been able to get it to work is to move the countSubscription and status subscription variables to the outer scope and add them to the subscription after the method executes.  I believe this won't work if I change the behavior back to a non Replay or Behavior Subject since the call back will not have been executed yet and the add method will be called with undefined variables.  Is there a way to expose a method inside of the observer callback on the "this" reference to the subscriber that allows me to add internal subscriptions to the outside subscription container without having to resorts to lifing variable to a higher scope?

```
hubOneObsSubscription = hubOneObs.subscribe(hub => {

    let countSubscription = hub.$count.subscribe(count =>
        $("#hub1output").text(count)  );

    let statusSubscription = hub.connection.status.subscribe(status => {
            writeToLog("HubOne status changed : " + ConnectionStatus[status]);  }
    );

    // have to call to start the connection.  Need to find a better way to do this.
    hub.connection.start();
    },
    error => {

    },
    () => {
        writeToLog("HUB1 stream completed!");

    });
```

**Comment by blesh** [comment]
closing as inactive.

**Comment by trxcllnt** [comment]
@sbabeal rather than subscribing to the inner subscriptions manually, you can use `flatMap` (or `switchMap`, etc.) to do it instead:

```es6
hubOneObsSubscription = hubOneObs.flatMap((hub) => {
  return Observable.merge(
    hub.$count.do(count => $("#hub1output").text(count)),
    hub.connection.status.do(status => writeToLog("HubOne status changed : " + ConnectionStatus[status]))
  )
  .ignoreElements()
})
.subscribe({ complete() { writeToLog("HUB1 stream completed!"); } });
```
