### ISSUE TITLE
Nuget

### ISSUE THREAD

**Issue by ashwin027** [ReactiveX/rxjs#1361]
When will RxJs 5.0 be available on Nuget? I searched with the pre-release flag on and I still couldnt find it.

**Comment by trxcllnt** [comment]
That's a question for @mattpodwysocki

**Comment by ichpuchtli** [comment]
I'll make a nuget this weekend.

**Comment by benlesh** [comment]
Closing due to lack of interest.

Happy to look at this again in the future. I used to use Nuget all the time.
