### ISSUE TITLE
behaviour of publish + refCount !== share?

### ISSUE THREAD

**Issue by christianacca** [ReactiveX/RxJS#1363]
## Problem

My understanding is that **`share` meant to be a shorthand equivalent to `publish().refCount()`** - is my understanding correct?

If so then, I have noticed that there are **cases where this is not so**.

## Example

*Note*: for the running example open [codepen](http://codepen.io/christianacca/pen/gPJxzV?editors=1011)

Take for example:

```js
let fakeUrlPrefixFetch$ = Rx.Observable.interval(2000).take(1);
let fakeMovieListFetch$ = Rx.Observable.interval(3000).take(1).map(x => [x]);
let fakeQueuedMoviesFetch$ = Rx.Observable.interval(2500).take(1).map(x => [x])

// let urlPrefixFetched$ = urlPrefixFetch$.share();
let urlPrefixFetched$ = fakeUrlPrefixFetch$.publish().refCount();

let movieListFetched$ = urlPrefixFetched$.flatMap(url => fakeMovieListFetch$);
let queuedMoviesFetched$ = urlPrefixFetched$.flatMap(url => fakeQueuedMoviesFetch$);
let allMoviesFetched$ = Rx.Observable.concat(movieListFetched$, queuedMoviesFetched$);

printTime("subz1 created");
let subz1 = allMoviesFetched$.subscribe(
  x => printTime(`subz1 ${JSON.stringify(x)}`), 
  null, 
  _ => printTime("subz1 completed"));
```

The subscribed observer receives items emitted from `movieListFetched$` but NOT from  `queuedMoviesFetched$`.

Whereas the if you replace the `publish().refCount()` with:
```js
let urlPrefixFetched$ = fakeUrlPrefixFetch$.share();
```
... the subscriber end up receiving items from BOTH `movieListFetched$` and `queuedMoviesFetched$`.

## My guess at an explanation

My guess is that with `publish().refCount()`, the observable produced (`urlPrefixFetched$`) is not being disconnected when the `concat` operator switches from emitting items from the second observable.

As a consequence `fakeUrlPrefixFetch$` is already completed.

On the other hand with `share`, at the point of `concat` moving between observables, `urlPrefixFetched$`'s ref count drops to 0. It is then reconnected to causing the cold observable (`urlPrefixFetch$`) to emit a new set of (1) items.

**Comment by plievone** [comment]
I don't know the specifics, but from the source it looks like `.share()` is a shorthand for [`.multicast(() => new Subject()).refCount()`](https://github.com/ReactiveX/RxJS/blob/7e32ade/src/operator/share.ts#L20) whereas `.publish()` is a shorthand for [`.multicast(new Subject())`](https://github.com/ReactiveX/RxJS/blob/7e32ade/src/operator/publish.ts#L14). That factory function makes a difference according to the test cases:
https://github.com/ReactiveX/RxJS/blob/master/spec/operators/multicast-spec.js
https://github.com/ReactiveX/RxJS/blob/master/spec/operators/publish-spec.js
https://github.com/ReactiveX/RxJS/blob/master/spec/operators/refCount-spec.js
https://github.com/ReactiveX/RxJS/blob/master/spec/operators/share-spec.js

**Comment by trxcllnt** [comment]
@christianacca @plievone yes, we finally decided to fix a long-standing backwards-incompatible bug with `multicast` in v5. We've kept the old behavior in the `publish` operators (reusing the Subject), but opted for the fixed behavior in the `share` operators (recreating the Subject). More context is available here https://github.com/ReactiveX/RxJS/issues/453#issuecomment-145165630 https://github.com/ReactiveX/RxJS/issues/453#issuecomment-152276434

**Comment by christianacca** [comment]
OK, I see that was a hard decision to make.

Of course expect this to trip quite a number of devs up simply because there are a lot of existing historical mentions ([eg](https://www.youtube.com/watch?v=Jt-_oVQVZlQ#t=28m15s)) that `share` **is** equivalent.

**Comment by OliverJAsh** [comment]
Related issue: https://github.com/ReactiveX/rxjs/issues/1914

It would be good to fix the docs here to avoid further confusion.
