### ISSUE TITLE
Observable's next action runs even when not taken

### ISSUE THREAD

**Issue by pmowrer** [ReactiveX/rxjs#1370]
The following seems like an injection bug starting in `5.0.0-beta.1`:

```javascript
createObserver(2)
  .startWith(1)
  .take(1)
  .subscribe(x => console.log(x));

function createObserver(value) {
  return Rx.Observable.create(observer => {
    console.log('in subscribe');
    observer.next(value);
    observer.complete();  
    
    return function () {
      console.log('disposed');
    };
  }); 
}
```
jsbin: http://jsbin.com/mebonun/6/edit?html,js,console

In RxJS 4.0.6 and in 5.0.0-beta.0, this works like I expect. The created observable is essentially ignored.
```bash
1
```
but as of 5.0.0-beta.1, the observable's subscribe and dispose functions are invoked:
```
1
"in subscribe"
"disposed"
```
It'd seem to make sense these don't get invoked, but I'm not certain about the expected behavior honestly.

**Comment by JaminFarr** [comment]
Possibly related, I've seen similar issues with take and repeat.

```javascript
createObserver(2)
  .startWith(1)
  .repeat(5)
  .take(1)
  .subscribe(x => console.log(x));

output:

1
"in subscribe"
"disposed"
"in subscribe"
"disposed"
"in subscribe"
"disposed"
"in subscribe"
"disposed"
"in subscribe"
"disposed"
```

The repeat is re-subscribing even though the take has completed.

With the repeat directly after the .create the extra "in subscribe", "disposed" still happen but in an unexpected order.

```javascript
createObserver(2)
  .repeat(5)
  .startWith(1)
  .take(1)
  .subscribe(x => console.log(x));

Output:
1
"in subscribe"
"in subscribe"
"in subscribe"
"in subscribe"
"in subscribe"
"disposed"
"disposed"
"disposed"
"disposed"
"disposed"
```

Changing the the repeat count to -1 crashes the program.

**Comment by kwonoj** [comment]
> Changing the the repeat count to -1 crashes the program

: For this specific issue, please refer https://github.com/ReactiveX/RxJS/issues/651#issuecomment-153967978. Long story in short, you may need subscribe on non-recursive, different scheduler for infinite (or largely enough) synchronous repeat.

**Comment by JaminFarr** [comment]
Thanks @kwonoj, I didn't realise that this had been covered. Yes, Schedulers have fixed the issue I was having.

@pmowrer apologies if I've derailed your thread.

**Comment by kwonoj** [comment]
@pmowrer I just tried snippet with current master, seems it's resolved. (Not sure why it was though). Would you mind to confirm on your end too?

**Comment by trxcllnt** [comment]
@kwonoj this was likely fixed by #1516

**Comment by kwonoj** [comment]
@trxcllnt Thanks for clarification :) Let me close this issue for now then. @pmowrer , feel freely reopen if problem persists.

**Comment by pmowrer** [comment]
I can confirm this is fixed on my end. Thanks @kwonoj!
