### ISSUE TITLE
Generated marble diagrams from tests - not usable?

### ISSUE THREAD

**Issue by christianacca** [ReactiveX/RxJS#1372]
I think the idea of generating marble diagrams from the specs awesome. However the **resulting diagram isn't that useful**.

For example, this is the *generated* diagram from the buffer operator [spec](https://github.com/ReactiveX/RxJS/blob/master/spec/operators/buffer-spec.js):

![image](https://cloud.githubusercontent.com/assets/886590/13203064/0befa0c6-d8a6-11e5-9be4-42b88d3e7744.png)

Compare this to the *"hand drawn"* diagram on the [official docs site](http://reactivex.io/documentation/operators/buffer.html):

![image](https://cloud.githubusercontent.com/assets/886590/13203077/5a0adbc2-d8a6-11e5-9d07-ae7dd20aef56.png)

As you can see, the generated diagram is missing most of the useful content.

**Is this generated result what everyone else is seeing** (ie a problem on my machine only)?

Thanks
Christian

**Comment by staltz** [comment]
It seems like a problem on your machine. Your diagrams are missing texts entirely. Might be a problem with ghostscript, which is the most important piece to generate the texts. To me it looks like this:

![buffer](https://cloud.githubusercontent.com/assets/90512/13212403/b762686e-d949-11e5-92d5-9372a93b8ad5.png)

**Comment by christianacca** [comment]
Yes it's a problem on my machine (Windows 7).

From the build output I see an error talking about missing font files:

```cmd
gm convert: Unable to read font (n019003l.pfb) [No such file or directory]
```

I've found the files here: https://sourceforge.net/projects/gs-fonts/

You then have to tell ghostscript where to find the font files. Unfortunately the instructions didn't work for me (I added a GS_LIB environment variable to point to the downloaded font file directory, and rebooted just in case).

Unless someone else can advise on how they set things up, I'm "happy" to give up so as to avoid hours of gnashing of teeth :-0

BTW, here's the instructions I followed from ghostscript:
http://ghostscript.com/doc/current/Use.htm#Finding_files
http://ghostscript.com/doc/current/Use.htm#Font_lookup

**Comment by staltz** [comment]
Mostly you want *need* to generate these diagrams in the first place. Their generation is meant to happen when the docs are built and published to the web.

**Comment by christianacca** [comment]
Yeah I know, just thought it would be a nice tool to help visualize some of the harder / edge case conditions I see in the specs. 

These specs are an excellent source of docs and so I want more than the one or two marble diagrams per operator that are currently being produced!

**Comment by kwonoj** [comment]
Let me close this issue for now by issue is system specific. @christianacca , if you have additional topics to be discussed in here feel freely reopen, or create another issue if needed.
