### ISSUE TITLE
WebSocket missing in bundles

### ISSUE THREAD

**Issue by DydFreeman** [ReactiveX/RxJS#1375]
Hi,

I'm trying to test WebSockets but it seems that definitions are missing from bundles file (rxjs/bundles/Rx.js).
Due to project requirements I would like to go with 'bundles' option, as shown in '5 Minutes quickstart: Angular2'.

**Comment by blesh** [comment]
Yeah, sorry about that. We're not exporting the Rx-DOM bundle yet, as there's some debate about whether or not to move it to another repo or export it separately.

See discussion here: #1278 

We'll try to get this worked out by the next release.
