### ISSUE TITLE
Unclear Docs

### ISSUE THREAD

**Issue by giltig** [ReactiveX/RxJS#1379]
Hello,
I started to look at the new documentation.
It is very inconvenient and unclear.
The typescript signatures are very misleading (we are working with js and ts eventually).
The documentation itself is too dense and verbose - even the previous docs were better.
I think the work you are doing regarding rxjs 5 is amazing and I use this library already,
However I think good documentation is important.

**Comment by staltz** [comment]
We are working on it: https://github.com/ReactiveX/RxJS/pull/1378 https://github.com/ReactiveX/RxJS/pull/1376 https://github.com/ReactiveX/RxJS/pull/1374

**Comment by kwonoj** [comment]
There's meta-issue to tracking general strategy for document at https://github.com/ReactiveX/RxJS/issues/1242, and by @staltz is actively working on issue let me close this issue. If there's high level discussion, can be discussed at #1242 .It is welcome to file separate issue if there's specific topic need to be discussed.
