### ISSUE TITLE
Get JSDocs from TypeScript interfaces to show on ESDoc

### ISSUE THREAD

**Issue by staltz** [ReactiveX/rxjs#1380]
This is just to document an issue to be fixed with the ESDocs pages.

Because TypeScript does not compile interfaces to ES6 (because it can't), also the JSDocs near those interfaces (for instance JSDoc for Observer or Scheduler) do not show, because of this TypeScript issue: https://github.com/Microsoft/TypeScript/issues/2546

I'm working on doing a PR to TypeScript to solve that issue mentioned above, then ESDoc would finally be able to see any JSDoc.

Anyone have a better idea how to solve that?

**Comment by staltz** [comment]
Submitted PR to TypeScript: https://github.com/Microsoft/TypeScript/pull/7213

**Comment by kwonoj** [comment]
Since this is compiler behavior strip out comments, hard to think of elegant way to solve this.

I could think of this kind of hack to declare dummy instance serve to preserve comment strip, like

```js
/**
comments...
*/
const Observer: any = null; //do not export
export interface Observer<T> {
...
}
```

which transpiled into

```js
/**
comments...
*/
var Observer = null;
```

but this isn't beauty at all, first it declares unnecessary objects and output won't be great.

**Comment by staltz** [comment]
I have considered that too. Maybe we can do that as a temp solution until TypeScript folks support `/** ... */` comments. I can try another PR.

**Comment by kwonoj** [comment]
I think this issue is resolved by introducing document-only interface file via https://github.com/ReactiveX/rxjs/pull/1500, can be closed maybe?

**Comment by staltz** [comment]
Yes, it's ugly, but we can close this. An improvement to those MiscJSDoc.ts files would be an improvement to TypeScript, but right now, this issue is solved.
