### ISSUE TITLE
Observable.ajax response is string for IE11

### ISSUE THREAD

**Issue by gbabiars** [ReactiveX/rxjs#1381]
I'm seeing an issue on 5.0.0-beta.2 where the ajax observable returns plain text when `responseType` is either set to `json` or left blank.

Example:
```js
Observable.ajax({
  method: 'GET',
  url: `api/blah`,
  crossDomain: true,
  resultSelector(res) {
    return res.response
  }
});
```

For a payload that is an Array, `res.response` is of type Array in Chrome, however, on IE11 it is a string.  Digging into it, it appears the `responseType` property on the xhr at https://github.com/ReactiveX/RxJS/blob/master/src/observable/dom/AjaxObservable.ts#L353 appears to always be empty, regardless of what `request.responseType` was at https://github.com/ReactiveX/RxJS/blob/master/src/observable/dom/AjaxObservable.ts#L215.

This is easy enough to work around in the resultSelector:
```js
function jsonResultSelector(res) {
  if(typeof res.response === 'string') {
    return JSON.parse(res.response);
  }
  return res.response;
}
```

**Comment by kwonoj** [comment]
I got interested in this and try to reproduce it, but for some reason I wasn't able to do so. I assume I've done something incorrectly.. @gbabiars , would you mind to share some details how I can reproduce this one?

**Comment by blesh** [comment]
I can't reproduce this either. So I'm removing the bug label for now.

**Comment by blesh** [comment]
@gbabiars can you show the full request and response headers that produced this issue?

**Comment by wardbell** [comment]
A plunker or codepen or something like that would help.

**Comment by gbabiars** [comment]
@blesh @kwonoj sorry for the slow response.  I will try to get a repro today that I can share.

**Comment by gbabiars** [comment]
I've created a repo at https://github.com/gbabiars/rxjs-ajax-repro since ajax is not included in the npmcdn build.  The request I'm doing is a CORS request over http (the original was https, so that does not appear to matter).  The repro demo appends the actual type of the response property and the value of the responseType.

On Chrome, I get an object for response and responseType is json.
<img width="348" alt="screen shot 2016-03-17 at 11 10 25 am" src="https://cloud.githubusercontent.com/assets/813293/13856306/d42fb1a4-ec31-11e5-8dae-c6226f294454.png">

On IE11, I am getting string for response and responseType is empty.
<img width="336" alt="screen shot 2016-03-17 at 11 10 16 am" src="https://cloud.githubusercontent.com/assets/813293/13856369/18b18ef6-ec32-11e5-9123-56f67e0e8b7d.png">

I will try to do some more investigating into this, but hopefully this helps for repro steps.

**Comment by kwonoj** [comment]
Thanks! trying now...

**Comment by kwonoj** [comment]
OK, could reproduce issue. Able to confirm XHR responseType is empty instead of being set to json, and after digging into bit more it seems like IE doesn't support json as responseType (https://msdn.microsoft.com/en-us/library/hh872882(v=vs.85).aspx) while other browser (Chrome > 31, Firefox > 10, https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/responseType / http://caniuse.com/#search=XMLHttpRequest) implemented it.

Should ajax implementation takes care of it parse json on IE? Seems there are some of IE specific handling (`onreadystatechange`) so it may makes sense.. /cc @trxcllnt also for asking opinion.

**Comment by trzewiczek** [comment]
Hi, 

I run into similar problem with 400 response. 

```
Response Headers:
    HTTP/1.1 400 Bad Request
    Content-Type: application/json; charset=utf-8
```

```
"xhr": {
    "response": "{\"message\":\"Username can not be changed\"}",
    "responseType": "",
    "status": 400,
    "statusText": "Bad Request"
}
```

Non 2xx status responses fall under AjaxError constructor which does non of the IE magic that AjaxResponse constructor does, see: [AjaxObservable.ts#L451](https://github.com/ReactiveX/rxjs/blob/master/src/observable/dom/AjaxObservable.ts#L451).

Is that on purpose or should be fixed? (Happy to help here)
