### ISSUE TITLE
Problem with `inspect` and Node repl

### ISSUE THREAD

**Issue by tehnomaag** [ReactiveX/rxjs#1387]
I was trying to play with `rxjs` package in Node repl to compare it to v4 but kept on running into `RangeError: Maximum call stack size exceeded` errors.

Specifically when objects implement `inspect` method but its not meant for inspection then problems might occur.

For example with `rxjs` package:

```
> Rx = require("rxjs/Rx")
{ Subject: { [Function: Subject] create: [Function] },
  Observable:
…
> s = new Rx.Subject()
RangeError: Maximum call stack size exceeded
    at Subject.Observable (./node_modules/rxjs/Observable.js:21:24)
    at new Subject (./node_modules/rxjs/Subject.js:17:16)
    at Subject.lift (./node_modules/rxjs/Subject.js:28:23)
```

This is because Node's `util.inspect` (that repl uses to print expression return values) will try to call `s.inspect` but that will recurse and throw an error.

Fix is to disable `customInspect` option for `util.inspect` in Node repl as so:

```
> util = require("util");
> origInspect = util.inspect;
> util.inspect = obj => origInspect(obj, { customInspect: false })
```

Now the same thing as above won't throw:

```
> s = new Rx.Subject()
Subject {
  _isScalar: false,
  destination: undefined,
…
```

The `customInspect` option is [documented here](https://nodejs.org/api/util.html#util_util_inspect_object_options).

I'm not sure if there's anything Rx lib can do to prevent this. But at least a workaround notice in readme would be helpful.

I was using Node 5.6.0 and RxJS 5.0.0-beta2.

**Comment by kwonoj** [comment]
Am I understanding correctly this is naming collision between `Rx.Observable.inspect` to `util.inspect`?

**Comment by tehnomaag** [comment]
It's not a naming collision. Node's `uitl.inspect` has a default way of showing some inspection output for objects, but when the object in question has a `inspect` method of its own then `util.inspect` will try to use that, in similar fashion to how `toString()` is called on objects.

But since `Rx.Observable.inspect` will return another observable, and `util.inspect` will call `inspect` again on this objects, we end up with the call stack error above.

Mind you that that in real running code this problem doesn't appear, but it does in development workflow when using Node repl to test things out.

**Comment by kwonoj** [comment]
I see, thanks for clarification. It's not precise to say it's naming collision. As you said bit unsure if RxJS can do something about this other than add notes in document, but I may miss some possible solutions. Let's see if there's any suggestions around and if there isn't, I'll try to update document to include this topics.

**Comment by tehnomaag** [comment]
One option would be to rename `Rx.Observable.prototype.inspect` to something else. It's somewhat similar to `delayWhen` in operation (and arguments) as I understand, so maybe rename `inspect` to `inspectWhen`?

**Comment by kwonoj** [comment]
Actually those naming pairs are more like relation between `throttle` to `throttleTime`, as `inspect` and `inspectTime` does. Course naming change will avoid this, but (purely personal opinion) I'm bit hesitate about those yet.

**Comment by tehnomaag** [comment]
Node's `util.inspect` will invoke objects `inspect` with some arguments though:

```
> o = {}
{}
> o.inspect = function () { console.log("obj.inspect called", arguments); return "foo"; }
[Function]
> o
obj.inspect called { '0': 2,
  '1':
   { seen: [],
     stylize: [Function: stylizeWithColor],
     depth: 2,
     colors: true,
     showHidden: false,
     customInspect: true } }
foo
```

So one possible way is to do a arguments check in the Rx `inspect` method, for example this quick monkeypatch worked:

```
> origInspect = Rx.Subject.prototype.inspect;
[Function]
> Rx.Subject.prototype.inspect = function () { return arguments.length === 1 ? origInspect.apply(this, arguments) : this.toString(); }
[Function]
> new Rx.Subject()
[object Object]
```

But this would mean putting Node-specific workaround code into .ts files and all the compiled outputs.

**Comment by kwonoj** [comment]
> But this would mean putting Node-specific workaround code into .ts files and all the compiled outputs.

: Yes, that's where my hesitation comes in, node (dev) specific changes. I don't expect `util.inspect` would be used for production code, is my understanding correct?

**Comment by tehnomaag** [comment]
No, not automatically like in repl sessions.

**Comment by trxcllnt** [comment]
lol so node decided they own the word inspect. real great

**Comment by kwonoj** [comment]
@trxcllnt it seems so. I was able to dig up some old issues (https://github.com/nodejs/node-v0.x-archive/issues/410#issuecomment-4220640) and it's decided to not to rename it something like `__inspect__` or similar.

**Comment by kwonoj** [comment]
/cc @blesh also for visibility to conclude. 

I'm still voting to add note into README, do not add specific logics for this.

**Comment by kennethlawrence** [comment]
I did want to mention that this problem extends outside of repl as well, as Node's version  of `console.log`, `console.info`, & `console.warn` all use [util.format](https://github.com/nodejs/node/blob/master/lib/util.js), which itself invokes `inspect`.  For example the following code will throw a RangeError:
```
'use strict'
const Rx = require('rxjs/Rx');

let o = Rx.Observable.of(1,2,3,4);
console.log(o);
```
Produces:
```
util.js:209
function formatValue(ctx, value, recurseTimes) {
                    ^

RangeError: Maximum call stack size exceeded
    at formatValue (util.js:209:21)
    at formatValue (util.js:221:13)
    at formatValue (util.js:221:13)
    ...

```
As above, this shouldn't be used in production code as `console` is not a standardized part of the language, but it is possible that developers may run into this on development code.

Personally I feel that this issue could be considered a bug with Node as opposed to RxJS, and wouldn't really expect any specific action within RxJS to deal with it.  Perhaps it should be noted in the README as well for those left searching for solutions to RangeError bugs while developing.

**Comment by trxcllnt** [comment]
@tehnomaag @kennethlawrence from what I can tell, node's `util.inspect` [passes a depth parameter](https://nodejs.org/api/util.html#util_custom_inspect_function_on_objects) to `inspect`.

@blesh @kwonoj since our `inspect` [takes a function](https://github.com/ReactiveX/RxJS/blob/master/src/operator/inspect.ts#L17), could we add a bit of duck typing to check whether the argument is an integer, and return a string instead? I guess we could throw too, but not throwing seems OK. Since this is in an operator creation function, there won't be much meaningful performance degradation imo.

**Comment by blesh** [comment]
... or we could just rename it.

**Comment by blesh** [comment]
Yeah, given that the `inspect` name was bestowed upon these operators as a variation of the `sample` operators in #1053, I think we have carte blanche to just name them something else. 

Any suggestions?

**Comment by trxcllnt** [comment]
@blesh but I like inspect! :pouts:

**Comment by kennethlawrence** [comment]
@blesh From looking at the documentation and playing around with inspect, perhaps `audit` and `auditTime` would be valid names.

Auditing is synonymous with inspecting, but repeating an audit when there is no change in information will not produce anything new.  In this case the action could be described as "auditing for new information".

**Comment by trxcllnt** [comment]
@blesh @kennethlawrence :+1 for either duck type checking in inspect or `audit` rename

**Comment by kwonoj** [comment]
Let me close this issue, by https://github.com/ReactiveX/rxjs/pull/1512 now `inspect` is renamed to `audit`. Please feel freely reopen if there's remaining issue.
