### ISSUE TITLE
Support returning promises in operators that require Observables to be returned?

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#139]
Some operators, like flatMap will allow a user to return a Promise and will automatically use them without the developer needing to convert them to an observable.

I think that we should wait to implement this until maybe after Alpha release, then try it on one or two operators, but perf test to make sure it doesn't have any negative impact at all.

IMO, most people are going to be dealing with Observables in cases like flatMap, and not Promises. If they are dealing with promises, we have `fromPromise`, which is pretty straight forward. I'd hate to impact performance at all for any edge cases that have simple workarounds.

Thoughts?

**Comment by staltz** [comment]
> IMO, most people are going to be dealing with Observables in cases like flatMap, and not Promises. If they are dealing with promises, we have fromPromise, which is pretty straight forward. I'd hate to impact performance at all for any edge cases that have simple workarounds.

Agreed.

**Comment by robwormald** [comment]
If performance is a significant factor, that should take priority IMO. 

That said, one of the nicest things about flatMap is the promise handling, and its makes it simpler for those transitioning away from / interoperating with promise based APIs and into Observable-land. It's not exactly the right analogy but I've found it quite easy to explain to new users that .flatMap is a sort-of replacement for `Promise.all` - it's actually closer to bluebird's `Promise.map(fn)`, and gives the same sort of contract on ordering: 
```js
Promise.all(urls.map(url => fetch(url)))
  .then(doStuff);

urls$.flatMap(url => fetch(url))
  .subscribe(doStuff);
```
or maybe introduce a standalone operator - something like` Observable.prototype.awaitMap` (as in ES7 async/await) for this specific purpose and leaving flatMap for Observables? I'm not in love with that name (.asyncMap?) but I do like the existing mechanism. 
```js
urls$.awaitMap(url => fetch(url))
  .subscribe(doStuff);
```
The `Rx.Observable.fromPromise` feels much less ergonomic in the middle of a stream.
```js
urls$.flatMap(url => Rx.Observable.fromPromise(fetch(url))
  .subscribe(doStuff);
```

I suspect there's going to be a lot more of this sort of thing in the future and it would be nice to have a first-class operator for it.

**Comment by staltz** [comment]
> The Rx.Observable.fromPromise feels much less ergonomic in the middle of a stream.
>```
urls$.flatMap(url => Rx.Observable.fromPromise(fetch(url))
  .map(doStuff)
  .subscribe();
```

That fact that it's not ergonomic might be a good argument for converting fetch(url) to return an Observable instead of a Promise, paving the way for refactoring from Promises to Observables. If not that, at least it makes the conversion explicit.

**Comment by mattpodwysocki** [comment]
@blesh I think the worries for the most part is unwarranted.  For example, in the current RxJS, it's simple as:
```js
isPromise(value) && (value = Observable.fromPromise(value));
```

Where `isPromise` is nothing more than the following:
```js
function isPromise(obj) {
  return obj && typeof obj.then === 'function';
}
```

It should be as often as possible for us to convert Promises to Observables such as what we have here: https://github.com/Reactive-Extensions/RxJS/blob/master/doc/gettingstarted/promises.md

**Comment by blesh** [comment]
@mattpodwysocki You're most likely correct, but we should back it up with the performance tests, regardless.

**Comment by robwormald** [comment]
@blesh would it be OK to start looking at this now we're at super-alpha-mark-3?

**Comment by trxcllnt** [comment]
@robwormald I think this is currently sitting in PR #354, but I'm not sure if it's ready yet.

**Comment by robwormald** [comment]
ah cheers, thanks!

**Comment by mattpodwysocki** [comment]
@blesh @trxcllnt just be aware that Node seems to be broken where converting from a Promise seems to swallow the error: https://github.com/Reactive-Extensions/RxJS/issues/925  However, I can run the same code in Chrome and Firefox and I get the unhandled error...

**Comment by trxcllnt** [comment]
@mattpodwysocki if I recall, RxJS [re-throws errors thrown in `onNext` instead of forwarding them to `onError`](https://github.com/zenparsing/es-observable/issues/47#issuecomment-129563045), so maybe node's Promises are catching them instead?

**Comment by paulpdaniels** [comment]
@trxcllnt Exactly. Though there appears to be an inconsistency in how libraries handle the issue. Native Promises will throw if there there are no handlers present at the time of rejection. While most libraries I have seen seem to swallow the exception until a handler attaches

**Comment by blesh** [comment]
I don't see anything in the A+ spec that makes this any clearer. Perhaps @domenic could provide some insight?

**Comment by domenic** [comment]
> Native Promises will throw if there there are no handlers present at the time of rejection.

This is not true. Their devtools may expose the error, but it is not thrown.

**Comment by paulpdaniels** [comment]
Ah, yes you are correct @domenic I jumped on the bandwagon too quick. The tests are still spinning even when the dev tools are reporting an unhandled exception. Which still leaves us with the issue of not being able to throw.

**Comment by blesh** [comment]
@paulpdaniels I can force a global throw on unhandled by adding a second `.then` clause and throwing asynchronously.

```
promise.then(x => { observer.next(x); observer.complete(); }, err => observer.error(err))
   .then(null, unhandled => setTimeout(() => {throw unhandled; }))
```

**Comment by blesh** [comment]
I typed that up on my phone... LOL... Sorry for any typos. Anyhow it'll work, Even if it's ugly

**Comment by ktrott** [comment]
Supported now.
