### ISSUE TITLE
combineLatest over an observable of observables

### ISSUE THREAD

**Issue by christianacca** [ReactiveX/RxJS#1399]
There is an existing overload of combineLatest that accepts a `sources` *array* of observables and a `resultSelector` that will receive an array containing the latest items emitted from each observable in `sources`

The problem with this is that you must *know in advance* the set of observables that you want to combine.

**Can a new overload be added that would combine the latest from an *observable* of observables?**

ie:
```ts
combineLatest<TOther, TResult>(souces: Observable<ObservableOrPromise<TOther>>, resultSelector: (...otherValues: TOther[]) => TResult): Observable<TResult>;
```

This new overload would support a set of observables to combine that can grow and shrink over time.

Thanks
Christian

**Comment by staltz** [comment]
`combineAll`

**Comment by christianacca** [comment]
I looked at that but wasn't convinced it has the same behaviour. Specifically:

>  Once the outer observable **completes**, it subscribes to all collected observables and "combines" their values

(emphasis mine).

I read that to mean that the final observable will not start to emit until it itself receives its completed notification. I want the observable to emit asap.

Again that behaviour seems to be what I see in the spec:

```ts
  it.asDiagram('combineAll')('should combine events from two observables', function () {
    var x =    cold(               '-a-----b---|');
    var y =    cold(               '--1-2-|     ');
    var outer = hot('-x----y--------|           ', { x: x, y: y });
    var expected =  '-----------------A-B--C---|';

    var result = outer.combineAll(function (a, b) { return String(a) + String(b); });

    expectObservable(result).toBe(expected, { A: 'a1', B: 'a2', C: 'b2' });
  });
```

**Comment by christianacca** [comment]
... Also that means `combineAll` will wait until all inner observables have been "seen" by the outer observable. The overload I'm suggesting will emit an array whose length will vary as the number of inner observables arrive and complete over time.

**Comment by staltz** [comment]
Yes, I understand, but what is the problem you are trying to solve? We don't want to add more operators just for the sake of having more. Let's think first what is your original problem and look at all the possible solutions.

**Comment by christianacca** [comment]
So here's the scenario...

I'm animating a simple game where a ship can fire a shot. 
* A click represents a shot. 
* Multiple shots can be "in-flight" at any given time.

My thought's are that each click creates its own observable stream. Each of these click streams:
* emit a new screen coordinate position for the shot at a regular interval
* end once the shot moves off the screen

I want to create an observable that combines the latest position of all the shots that are currently visible on the screen as an array.

`combineLatest` seems the closest fitting operator for what I want to achieve. However, for my scenario `combineLatest` would require that the list of observables to combine be taken from an observable stream (a stream of animated click streams). This new overload would support a set of observables to combine that can grow and shrink over time.

Here's what I think the code would (hopefully) look like using the new overload:

```ts
let animationTicker$ = Rx.Observable.interval(40).share();
let clicks$ = Rx.Observable.fromEvent<MouseEvent>(document.body, "click");

let heroShots$ = clicks$
.map((evt) => {
  return {
    x: evt.clientX,
    y: 500
  };
})
.map(shot => {
  let animatedShot$ = animationTicker$
    .map(_ => shot)
    .scan((prev, _) => {
      return {
        id: prev.id,
        x: prev.x,
        y: prev.y - 15
      };
    }, shot)
    .takeWhile(movedShot => movedShot.y >= 0)
    .startWith(shot);
  return animatedShot$
})
.combineLatest((...shots) => shots));
```

As a playbround, I've setup [this jsbin](https://jsbin.com/mawaro/2/edit?js,console,output) that tries (and fails) to express my intent using the current set of operators in rxjs

*note:* I've tried and failed using `scan` to solve the problem, although I have a nagging feeling that this could still be the right approach...

**Comment by trxcllnt** [comment]
@christianacca you're right, there isn't an operator for this. I had a similar problem a while back (you can see how I solved it [here](https://github.com/trxcllnt/reaxtor/blob/master/src/List.js#L25)), but this looks like a great use-case for [`mergeScan`](https://github.com/ReactiveX/RxJS/blob/master/src/operator/mergeScan.ts). [Here's an example jsbin](https://jsbin.com/zewulaqote/1/edit?js,output) that uses mergeScan to accumulate the state of all shots.

**Comment by christianacca** [comment]
That was **so** helpful @trxcllnt! 

Got some questions if I may?

So it seems that `mergeScan` is a melding together of `scan` and `mergeMap` - is my understanding correct? 

So it's like `mergeMap` in that each item from the source observable is transformed (mapped) into an observable stream, which are then flattened. It's like `scan` in that accumulated state is available.

What I feel fuzzy about is the difference in the accumulated state variable between `scan` and `mergeScan`. I wonder if you can confirm whether I'm on the right track?

With `scan` whatever your accumulator function emits becomes the accumulated input for the next call to the accumulator. Whereas it seems with `mergeScan` that subsequent calls to the accumulator function will receive the *latest* item emitted from the observable returned by the previous accumulator function call. This "latest" item might not be the *last* item to be emitted by the previous "inner" observable.

Lastly, why did you change the `animationTicker$` observable to one that you have to manually call connect on? I was thinking that an observable returned by `share` would handle the connection (and disconnection for me) of "ticks". Is that just your preference or is that important to the solution?

**Comment by trxcllnt** [comment]
> @christianacca With scan, whatever your accumulator function emits becomes the accumulated input for the next call to the accumulator. Whereas it seems with mergeScan that subsequent calls to the accumulator function will receive the latest item emitted from the observable returned by the previous accumulator function call. This "latest" item might not be the last item to be emitted by that observable.

Yes, exactly. When a new event from the source causes the `mergeScan` selector to execute again, the accumulator will be the most recent value emitted from any of the inner merged Observables. In my example, all the inner merged Observables are returning a reference to the same accumulator instance, so it's guaranteed that the accumulator will always be the sum of all the shots in flight.

> Lastly, why did you change the `animationTicker$` observable to one that you have to manually call connect on? I was thinking that an observable returned by share would handle the connection (and disconnection for me) of "ticks". Is that just your preference or is that important to the solution?

It's not important to the solution, but it might be important to your game loop. You're right that it will automatically connect/disconnect the subscription to the timer, but that may not always desired.

For example, if the user clicks, and a shot is animated until its `y` goes to zero. The subscription to the shared Observable will be disposed, which will cause `refCount` to dispose of the subscription to the timer. The next time someone clicks, `refCount` re-establishes the subscription to the timer, which will emit an event 40ms later. If the game loop were constantly running (as is the case in my example), if the user clicks in-between a 40ms interval (say, at t-20), the event runs through the `mergeScan` selector again, but this time the inner merged Observable only has to wait 20ms (since 20ms has passed since the last emission from the `$animationTicker`) instead of the full 40ms. It's a minor detail that may not actually make a difference in your case, but is easy to overlook (and cause the game to feel "sluggish") in scenarios like this.

**Comment by blesh** [comment]
Alternatively: Here's a custom operator that does what (I think) you're looking to do

[JSBin here](http://jsbin.com/nowune/2/edit?js,output)

```js
Observable.prototype.combineActive = function () {
  let source = this;
  
  return new Observable((subscriber) => {
    let subs = [];
    let currentValues = [];
    let isComplete = false;
    
    subscriber.add(source.subscribe(function (observable) {
      const sub = new Subscription();
      subscriber.add(sub);
      subs.push(sub);
      sub.add(observable.subscribe(value => {
        let index = subs.indexOf(sub);
        currentValues[index] = value;
        subscriber.next(currentValues);
      }, (err) => {
        subscriber.error(err);
      }, () => {
        let index = subs.indexOf(sub);
        if (index !== -1) {
          subs.splice(index, 1);
          currentValues.splice(index, 1);
        }
        subscriber.remove(sub);
        if (isComplete) {
          subscriber.complete();
        }
      }));
    }))
  });
}
```

**Comment by blesh** [comment]
... I mean, the order of the values in the resulting stream of arrays would be non-deterministic, but I don't think that's what you wanted. You just wanted a list of values you were going to operate over generically anyhow.

**Comment by ccrowhurstram** [comment]
Guys, that was really very helpful. Thank you for taking the time out to help. 

I'm finding the rx learning curve pretty steep and I must say I was losing a bit of hope. You've really helped to keep me going!

**Comment by paulpdaniels** [comment]
I would also posit that this is a good use case for the `generate*` family to be implemented.

Then I think you could just do:

```typescript

let clicks$ = Rx.Observable.fromEvent<MouseEvent>(document.body, "click");

let heroShots$ = clicks$
      .mergeMap((evt) => Rx.Observable.generateWithRelativeTime(
        {x: evt.clientX, y: 500},
        shot => shot.y >= 0,
        shot => ({x: shot.x, y: shot.y - 15}),
        shot => shot,
        shot => 40))

heroShots$.subscribe(/*Do animation rendering*/);

```

**Comment by blesh** [comment]
@ccrowhurstram since you seem satisfied with the answers you've gotten here, I'm going to close this issue if you don't mind. If you feel the need to reopen, please do.

**Comment by ccrowhurstram** [comment]
Yup thanks
