### ISSUE TITLE
Reuse RxJS's existing QUnit tests?

### ISSUE THREAD

**Issue by trxcllnt** [ReactiveX/RxJS#14]
Toying around with the idea of running RxJS's existing QUnit test suite with [node-quint-phantomjs](https://github.com/jonkemp/node-qunit-phantomjs). Would need to copy over nearly all the src/core/test code, but should be easier than rewriting all the tests from scratch.

@blesh

**Comment by blesh** [comment]
I'm not sure this is something we can support directly. We will definitely examine those tests and take queues from them. Closing for now.
