### ISSUE TITLE
Remove the rest of parts which use tryCatch

### ISSUE THREAD

**Issue by saneyuki** [ReactiveX/rxjs#1403]
This is the list of them which we may be able to remove using `tryCatch` from:

- [ ] BoundCallbackObservable
- [ ] BoundNodeCallbackObservable
- [ ] AjaxObservable
- [ ] WebSocketSubject
- [ ] DeferObservable (#1393, by #1484)
- [ ] FromEventObservable
- [ ] FromEventPatternObservable (#1397)
- [ ] IteratorObservable
- [ ] bufferToggle
- [ ] bufferWhen
- [ ] distinctUntilChanged
- [ ] expand
- [ ] inspect
- [ ] mergeScan
- [ ] retryWhen
- [ ] windowToggle
- [ ] windowWhen
- [x] forEach (by #1434)
- [ ] Subscription (#1389)

**Comment by blesh** [comment]
@saneyuki ... I'd like to hold off on these sorts of changes for the time being. We can make these non-breaking changes even after we've pushed out the production release. Right now, I'd like to focus everyone's effort on more critical, possibly breaking changes to RxJS before the 5.0.0 production release.

As such, I'm going to close this issue for now. We can revisit it as time allows. It's definitely something that is on my mind.

Of course, I'll never turn away a PR to improve the performance of the library, and everyone's time here is voluntary. So feel free to work on whatever makes you happy. I just need to prioritize PRs that are more critical to the production release.

**Comment by blesh** [comment]
Also, FWIW: There is some talk about possibly creating a more unified strategy for this that is still efficient. Something that we can use a Babel transform here at Netflix to remove the try/catching entirely for a Node/Panic-mode type build for Node.js server use. That means work around this might change again.

**Comment by saneyuki** [comment]
@blesh Okay. Rather, it was peace of mind that did not become a release blocker.
