### ISSUE TITLE
Are we missing skipLast operator?

### ISSUE THREAD

**Issue by staltz** [ReactiveX/rxjs#1404]
We currently don't have skipLast implemented. Are we removing it intentionally or just forgot to build it?

Notice the discrepancy here:
- `skip`
- `skipUntil`
- `skipWhile`
- `take`
- `takeLast`
- `takeUntil`
- `takeWhile`

**Comment by blesh** [comment]
Maybe. The use-cases for skipLast are slim. But it seems like a missing operator. I'd say it's probably not a core operator though.

**Comment by staltz** [comment]
I'd add it just for symmetry. It's not something I'm really pushing for. Just stumbled upon this when writing docs.

**Comment by bardiarastin** [comment]
i have an issue because of that this is no longer available in Rx5 
http://stackoverflow.com/q/41650365/7091035
