### ISSUE TITLE
RequestAnimationFrame Scheduler

### ISSUE THREAD

**Issue by rgbkrk** [ReactiveX/RxJS#1410]
How is the `RequestAnimationFrame` scheduler supposed to be accessed with RxJS 5?

I'm not seeing it in the top level `require('@reactivex/rxjs')`:

```
> require('@reactivex/rxjs').Scheduler
{ asap: AsapScheduler { active: false, actions: [], scheduledId: null },
  queue: QueueScheduler { active: false, actions: [], scheduledId: null } }
```

Though I see it in the source here in `util`.

**Comment by rgbkrk** [comment]
Seems like this comes down to me not knowing how to use the Rx DOM bindings that are in here.

**Comment by kwonoj** [comment]
No, it's not your fault :) Simply, Rx.DOM is not being exported yet (https://github.com/ReactiveX/RxJS/issues/1375). There's plan to publish it as separate module, perhaps next release I presume.

**Comment by rgbkrk** [comment]
Easy to get to with the commonjs install:

```
> require('rxjs/Rx.DOM').Scheduler.animationFrame
AnimationFrameScheduler { active: false, actions: [], scheduledId: null }
```

Not sure how to do it with the `@reactivex/rxjs` import:

```
> require('@reactivex/rxjs/Rx.DOM')
Error: Cannot find module '@reactivex/rxjs/Rx.DOM'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at repl:1:1
    at REPLServer.defaultEval (repl.js:252:27)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:417:12)
    at emitOne (events.js:82:20)
```

**Comment by rgbkrk** [comment]
@kwonoj Oh, ok!

I'm writing a blog post/tutorial that uses RxJS 5 and was hoping to use it instead of poorly throttling by time (~16ms).

**Comment by rgbkrk** [comment]
This is the blog post I'm working on and the discussion about using `requestAnimationFrame`: https://github.com/getcarina/getcarina.com/pull/636#discussion_r54632175

**Comment by kwonoj** [comment]
@rgbkrk , let me close this issue since there's ongoing-discussion issue for release planning to tackle down this. If you'd like to have additional discussion, please feel freely reopen.

**Comment by trxcllnt** [comment]
@rgbkrk I think if you use the `@reactivex/rxjs` module you have to import it from `dist`:

```es6
import Rx from '@reactivex/rxjs/dist/es6/Rx.DOM';
const { animationFrame } = Rx.Scheduler;
```

**Comment by rgbkrk** [comment]
Do you think it would be better for me to use the commonjs import for a blog post that I'll put out tomorrow?

**Comment by rgbkrk** [comment]
Thanks for letting me know how to extract that out of dist.

**Comment by trxcllnt** [comment]
@rgbkrk that's what I'm doing, though I think the source maps are still messed up @robwormald
