### ISSUE TITLE
forEach should unsubscribe if callback function throws

### ISSUE THREAD

**Issue by zenparsing** [ReactiveX/RxJS#1411]
Test case:

```js
new Rx.Observable(sink => {
    sink.next(1); 
    sink.next(2); 
    sink.complete();
}).forEach(x => {
    console.log(x);
    throw new Error("boom");
}).catch(err => console.log(err));
```

Expected result: Only "1" is logged.
Actual result: "1" and "2" are logged.

I recently fixed this issue over on es-observable:

- [Spec](https://zenparsing.github.io/es-observable/#observable-prototype-foreach-next-functions) (3.2.1 step 3.d)
- [Reference Implementation](https://github.com/zenparsing/es-observable/blob/master/src/Observable.js#L298)

**Comment by blesh** [comment]
Ah... good catch, thank you @zenparsing!

**Comment by blesh** [comment]
Actually, looking at your reference implementation, there's a tricky bit your not covering... consider this:

```js
const syncObservable = new Observable((observer) => {
   const expensiveThing = new ExpensiveThing();
   observer.next('I am a little teapot!');
   return () => expensiveThing.destroy();
});

syncObservable.forEach(x => {
  throw new Error('dammit, I am a sugar bowl');
});
```

In the case above, the error will be thrown synchronously before `subscription` [can be returned](https://github.com/zenparsing/es-observable/blob/c22dd71a3349df30ac8f4e99c1b98008f54f232c/src/Observable.js#L287). So your reference impl [will throw on this line](https://github.com/zenparsing/es-observable/blob/c22dd71a3349df30ac8f4e99c1b98008f54f232c/src/Observable.js#L298)

I haven't tested this, but I think that's what will happen.

I'm working up a solution for RxJS 5 now.

**Comment by zenparsing** [comment]
Yeah, I was trying to simplify the algorithm by letting the error propagate in synchronous case, but clearly I messed it up : )

**Comment by trxcllnt** [comment]
@zenparsing we had to go to quite a bit of trouble to ensure that both a. the source unsubscription logic is run and b. the error is thrown to outside consumers when a next/error/complete handler throws on synchronous dispatch.
