### ISSUE TITLE
Proposal: Changes to retryWhen

### ISSUE THREAD

**Issue by benlesh** [ReactiveX/rxjs#1413]
These would be _breaking changes_, but here goes:
### Problem

Often with retryWhen there is a desire to reset some "state" of your retries when the stream your retrying starts receiving values successfully again. For example, in a network retry scenario where you want to exponentially step back from the first failure. Once you get a value over that network observable, you want to reset your exponential step back to the first level again, because things are going well now.
### Current Solution

The current solution involves adding some peice of mutable state and altering it via side-effects:

``` js
let exponent = 2;
let result = source.retryWhen(errs => errs.switchMap(() => Observable.timer(Math.pow(2, exponent++))))
      .do(() => exponent = 0)
```
### Proposed Change (and solution)

I propose a change that says the first successful value to "next" through the retryWhen subscriber causes the retry nofication subscription to unsubscribe, which will "reset" the state of any observable inside of there.

``` js
let result = source.retryWhen(errs => errors.switchMap((_, i) => Observable.timer(Math.pow(2, i)));
```

The behavior:
1. Subscribe to `result`
2. Subscribes to `source` and passes through successful values and completions
3. On `error` from source, the `error` is pumped into a Subject, and the notifier function passed to `retryWhen` is called  with an Observable created from that Subject.
4. The observable returned from the notifier function is subscribed to.
5. On `next` from the notifier, the `source` subscription is retried.
   a. On first successful message from `source`, unsubscribe from `notifier`, then goto 3.
6. On `error` from the notifier, an error is sent down the chain to the result.
7. On `complete` from the notifier, the completion is sent down the chain to the result.

**Comment by staltz** [comment]
I took a look at retryWhen.ts, thought about your suggestions, and I think it's a reasonable breaking change.

**Comment by blesh** [comment]
I just spoke with @abersnaze here at Netflix, and I think there's a way to do this without a breaking change.

Basically, the idea is to add an optional second parameter that fires for each `next` from `source`, and is called with the `value` from the next, and the `subscription` from the inner `errors` subscription.

```TypeScript
source.retryWhen(errs => errs.switchMap((_, i) => Observable.timer(2**i)), (value, sub) => sub.unsubscribe());
```

Another option would be a second arguemnt that was the same idea, but you just returned a boolean of whether or not to end the subscription.

**Comment by blesh** [comment]
Also, @stealthcode (from Netflix) had some thoughts about a different design (as a new operator). His concern with tearing down the inner subscription and starting it back up was based on the principle that that's an additional teardown and setup that you might not need. He wanted to try to keep the inner subscription  .. so it would look like this:

```TypeScript
retryWhenWithNext(notifierFactory: (errorsOrNexts: Observable<any>) => Observable<any>)
```

The idea here is that each call to next or error would come through the observable passed to the notifierFactory.

```
given:  source.retryWhenWithNext((errorsOrNexts) => errorsOrNexts.filter(x => x instanceof Error))
source ---a---b---c---d---#
errorsOrNexts ---a---b---c---d---#---a---b---c---d---#
```

Given that type-checking in JavaScript isn't a thing, I'm not sure how this approach would work for us, so perhaps in our case it would be better to have a stream of `Notification` in there for that design:

```TypeScript
repeatWhenNotified(notifierFactory: (notifications: Observable<Notification<T>>) => Observable<any>)
```

It's another design, and it's interesting, because it would actually allow for retries on async actions after errors, completions or nexted values.

**Comment by blesh** [comment]
@mattpodwysocki I'd really like your thoughts here, there's a lot in this thread.

**Comment by blesh** [comment]
I'm of the mind, that even if we implement a `repeatWhenNotified` type operator, we might still want to add the optional argument to `retryWhen`, as it wouldn't break the API, and it would be useful. Also `retryWhen` has a concise use case, where `repeatWhenNotified` would not. On the other hand, if those notifications were restricted to errors and nexts, then it would again, and we could call it `retryWhenNotified` I guess.

**Comment by blesh** [comment]
I've edited [my comment above](https://github.com/ReactiveX/RxJS/issues/1413#issuecomment-192409189) to clarify the options presented there.

**Comment by rosendi** [comment]
+1

**Comment by blesh** [comment]
I think this issue still has merit... leaving it for now.

**Comment by jiayihu** [comment]
@benlesh I'm having exactly this issue while implementing a polling library based on RxJS. Is there any current, even dirty and extremely hacky, way to workaround this issue?

**Comment by KwintenP** [comment]
+1

**Comment by benlesh** [comment]
This is pretty old, and there hasn't been much appetite to change it. However, we did at a "reset" to the `retry` operator, so perhaps we might go that route at a later time. Closing for now.
