### ISSUE TITLE
Module paths generated after downloading with jspm are corrupted

### ISSUE THREAD

**Issue by xmichaelx** [ReactiveX/RxJS#1416]
# Symptoms

As an example from observable/ArrayLikeObservable.ts:

```js
import {Scheduler} from '../Scheduler';
import {Observable} from '../Observable';
import {ScalarObservable} from './ScalarObservable';
import {EmptyObservable} from './EmptyObservable';
import {Subscriber} from '../Subscriber';
import {Subscription} from '../Subscription';
```

Generated JS:
```js
/* */ 
"use strict";
var __extends = (this && this.__extends) || function(d, b) {
  for (var p in b)
    if (b.hasOwnProperty(p))
      d[p] = b[p];
  function __() {
    this.constructor = d;
  }
  d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
};
var Observable_1 = require('.js');
var ScalarObservable_1 = require('./ScalarObservable');
var EmptyObservable_1 = require('./EmptyObservable');
```

**var Observable_1 = require('.js');** is what concerns me, because those modules cann't be later properly requested for in browser:

http://localhost:9000/jspm_packages/npm/rxjs@5.0.0-beta.2/observable/.js Failed to load resource: the server responded with a status of 404

# Versions

rxjs: npm:rxjs@^5.0.0-beta.2 (from jspm)
TypeScript: 1.8.2 (C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.8)
npm: 3.6.0
jspm: 0.16.30

# Sample
[TypescriptSystemRxTemplate.zip](https://github.com/ReactiveX/RxJS/files/154391/TypescriptSystemRxTemplate.zip)

Archive contains small template I made to reproduce the issue:
1. npm install
2. jspm install -y
3. typings install
4. gulp watch

It's weird but on some npm environments everything is generated OK and on some not, so far I've tried it on 4 npm environments. 2 OK, 2 have this issue and I wasn't able to get what was the difference between them because they all had the same versions of packages installed.

**Comment by kwonoj** [comment]
(*I'm not expert to JSPM, might be incorrect)

I've tried couple of examples and came to think this is somewhat related in JSPM or its loader. Original distribution via jspm preserves right path context such as 

`var Observable_1 = require('../Observable');`
(npm package rxjs)

and while jspm serves it to browser, served files are augmented and losing those context, while original file still stays same and untouched. 

What I found was those occur only on import name is same as path, such as

`var Observable_1 = require('../Observable');` //there's path 'observable' and module 'observable'
`var Subject_1 = require('../Subject');` //there's path 'subject' and module 'subject'

maybe some of loader, or jspm was not able to distinguish if module and path have same name and reside in same hierarchy. 

Would you be also able to confirm my finding's same to your cases? If so, I'd like to suggest to ask JSPM (or ts loader) also to get some ideas.

**Comment by xmichaelx** [comment]
Yeah, I've noticed the same pattern. I've tried to install rxjs via `npm install rxjs` and imports in the very same files had correct paths.

I'll probably add the same issue to jspm repo and ask why `jspm install npm:rxjs` works in an unexpected way and `npm install rxjs` works just fine.

Thank you for your time.
