### ISSUE TITLE
Data model observables

### ISSUE THREAD

**Issue by sternbel** [ReactiveX/rxjs#1418]
I'd like to create a data model class in Typescript that contains all sorts of observable fields. But I'm not quite sure what the best strategy is with RxJS...

a. Every field should be observable from any external observer in order to react when one is changed.

```ts
export class MyDataModel {
 private _a: number;
 public get a() {return this._a;}
 public set a(a:number) {this._a = a; // here I guess I have to add something to notify my observers?}
 public get aObservable(): Observable<number> {// what should I put here??}
}
```

```ts
export class ViewUpdater {
  MyDataModel model = new MyDataModel();
  model.aObservable.subscribe(a => console.log("new value for a: " + a));
  model.a = 6; // should print "new value for a: 6"
  model.a = 7; // should print "new value for a: 7"
}
```

b. Is it possible to return at once to the observer the old and the new value of `a`? (e.g. `"a has been modified (old: 3, new: 5)"`)

c. Is it possible to make the whole `MyDataModel` itself an Observable? The idea would be here to known which field has changed and get its old value and as well as its new value (e.g. should print `"property a has been modified (old: 3, new: 5)"`).

**Comment by SuperManitu** [comment]
For this, an Observable is the wrong choice. You have to use a Subject, in this particulary case I would choose a BehaviorSubject, like this:
```typescript
export class MyDataModel 
{
 private _a: BehaviorSubject<number> = new BehaviorSubject<number>(/*initial value (required)*/);
 public set a(a:number) {this._a.next(a);}
 public get aObservable(): Observable<number> {return this._a.asObservable():}
}
```
The behavior Subject saves the last value you stored into it and no matter when you subscribe to it, you get this last stored value.

**Comment by sternbel** [comment]
@SuperManitu thanks a lot for your help!

a. What about simply getting a? Can it done like this? 
```ts
public get a() {return this._a.next();}
```
b. ok with `ReplaySubject`, however what I would like is something like 
```ts
model.aObservable().subscribe((oldValue, newValue) => console.log("old: "+oldValue+" new: "+newValue););
```

c. The difference between b. and c. is that b. info about `model.a` property only, where c. could be a global observable at he level of the entire class for all properties at once. For instance:
```ts
export class MyDataModel 
{
  private _a: BehaviorSubject<number>...
  private _b: BehaviorSubject<string>...
  private _c: BehaviorSubject<number>...

  private _modelObs:Observable<any>;
  public get modelObservable(): Observable<any> {return this._modelObs:}

  public set model(model:{a?: number, b?: string, c?: number}) {
     // set a, b and/or c then notify observers with (only) what has been modified
  }
}

// somewhere else outside
model.modelObservable.subscribe(([{propertyName:string, oldVal:any, newVal:any}]) => console.log(...);)
// would display something like: "property a has been modified (old: 3, new: 5)", "property b has been modified (old: abc, new: def)".
```

**Comment by SuperManitu** [comment]
a; Well you could add a second property that is a without Subject and set both (subject and normal value) in the setter

b & c; I'm new to RxJS too, so I have no idea

**Comment by blesh** [comment]
@sternbel so you know, the reason no RxJS member/contributor has chimed in on this issue is because @SuperManitu answered this question nicely.

I'd really like to thank both of you for the discussion in here, and for being great community members.

Since this issue has gone stale, I'm going to close it. If there's anything else we can do, let us know.

**Comment by SuperManitu** [comment]
I'd like to add that you dont have to use a second property, the BehaviorSubject has a nice method called `getValue()`, because it has per definition always exactly one value

**Comment by sternbel** [comment]
@SuperManitu thanks for the `getValue()`!
@blesh @SuperManitu answered part of my questions actually ;-). What about b: (how to get old and new values when subscribed?)

**Comment by blesh** [comment]
> how to get old and new values when subscribed?

@sternbel look into `ReplaySubject` or `publishReplay`. It will save any values it's gotten so far and replay them to new subscriptions.
