### ISSUE TITLE
Source maps "sourceRoot" needs to be relative to the source map file's directory

### ISSUE THREAD

**Issue by trxcllnt** [ReactiveX/RxJS#1423]
See here: https://gist.github.com/trxcllnt/6ec25fe7bc0d0e4fd546

Currently, the `sourceRoot` value in the map files (`filter.js.map` in the gist) is always `"src/"`, but it needs to be relative to the directory that contains the map file (e.g. `"sourceRoot":"../src/"`). This is true of all map files (for example, `observable/dom/AjaxObservable.map.js` needs to be `"sourceRoot":"../../src/"`).

I've tried all the combinations of `--sourceMapRoot` `--mapRoot` `--rootDir` and `--outDir` to no avail, so we probably need a post-build script to recurse and rewrite the `sourceRoot` value of the built files.

**Comment by kwonoj** [comment]
Or what if we amend copy source script to place all source files reside next to sourcemap and transpiled results (and get rid of sourceroot configs) then map can pick up src directly without path lookup.

(it's just thought came out and haven't tested yet, I'll try out on my end)

**Comment by kwonoj** [comment]
> amend copy source script to place all source files reside next to...

: wasn't simple as that, not working :(

**Comment by alexeagle** [comment]
drive-by comment: we found that chrome devtools support for sourcemaps is spotty, and users can fall in a lot of holes where the sourcemaps don't load correctly (eg. server didn't serve the sourcemap, served it at a wrong path, sourcemap reference is not quite right)
For our internal use of TypeScript, we inline the sourcemaps and the sources (in dev mode) and they work every time.

**Comment by blesh** [comment]
> For our internal use of TypeScript, we inline the sourcemaps and the sources (in dev mode) and they work every time.

Seems like a gross workaround, honestly. And not too helpful for debugging production code.

**Comment by kwonoj** [comment]
I supposed this issue is closed via https://github.com/ReactiveX/RxJS/pull/1428, closing issue. If there's unexpected behavior, let's reopen issue or create separate issue to track.
