### ISSUE TITLE
Does RxJS async.series example really execute in series?

### ISSUE THREAD

**Issue by bill-mybiz** [ReactiveX/RxJS#1424]
I have a use case where I need to execute multiple calls to functions that return `AsyncSubject` in order, similar to [`async.series`](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/mapping/async/comparing.md#asyncseries). Here is the primary requirement, quoted from that page:

> The async.series runs an array of functions in series, each one running once the previous function has completed.

Here is the code that I've come up with that works, using TypeScript, RxJS 5:

```
    private _wrapArray<T> (items: T[]): Observable<any[]> {
        return Observable
            .fromArray(items)
            .concatAll()
            .toArray();
    }

    execSync<TItem, TResult>({ items, func }: {
        items: TItem[],
        func: (item: TItem) => AsyncSubject<TResult>
    }): Observable<TResult[]> {
        // defer call is required to execute in order
        var wrapped = this._wrapArray(items.map(t => Observable.defer(() => func(t))));
        // var wrapped = this._wrapArray(items.map(t => func(t))); // doesn't execute in order
        return wrapped;
    }
```

Notice that I had to use `Observable.defer` ([Thanks SO+Brandon!](http://stackoverflow.com/questions/21876275/wait-for-an-async-operation-in-onnext-of-rxjs-observable)) to get it to execute synchronously, which after the fact makes sense, as the call to `map` is executing the `func(t)`. So the array that is passed into `_wrapArray` is already running each function, and thus not in series. 

But this is not what is in the RxJS `async.series` example code:
```
wrapArray([
    Rx.Observable.just('one'),
    Rx.Observable.just('two')
  ])
  .forEach(
    function (results) {
      console.log(results);
    },
    function (err) {
      console.log('Error: %s', err);
    }
  );
```
The purpose of the `async.series` operator is so that you can call AsyncFuncA, AsyncFuncB, etc., in order, so I'm not sure if the `Rx.Observable.just` example is very helpful. Perhaps it could be changed to include an async func and use the call to `Observable.defer` to be slightly more helpful?

```
wrapArray([
    Rx.Observable.defer(Rx.Observable.just('one')),
    Rx.Observable.defer(Rx.Observable.just('two'))
  ])
  .forEach(
    function (results) {
      console.log(results);
    },
    function (err) {
      console.log('Error: %s', err);
    }
  );
```

To check the synchronous aspect of the example solution (without `defer`), I threw the following into one of my mocha unit tests:
```
var Rx = require('rxjs');

function wrapArray (items) {
  return Rx.Observable
    .from(items)
    .concatAll()
    .toArray();
}

function delayFunc(s: string, delayMs: number): Rx.Observable<string> {
    let result = new Rx.Subject();
    setTimeout(() => {
        console.log(s);
        result.next(s);
        result.complete();
    }, delayMs);
    return result.asObservable();
}

wrapArray([
    Rx.Observable.of('one yo'),
    delayFunc("two yo", 500),
    delayFunc("three yo", 10),
    Rx.Observable.of('four yo'),
  ])
  .forEach(
    function (results) {
      console.log(results);
    },
    function (err) {
      console.log('Error: %s', err);
    }
  );

describe('common', () => {
    it('should buy time', (done) => {
        setTimeout(x => {
            done();
        }, 10000);
    });
});
```

With console output:
```
  common
three yo
two yo
[ 'one yo', 'two yo', 'four yo' ]
```

Notice that three is before two, and it doesn't even show up in the final results array.

If I change it to use `defer`:
```
var Rx = require('rxjs');

function wrapArray (items) {
  return Rx.Observable
    .from(items)
    .concatAll()
    .toArray();
}

function delayFunc(s: string, delayMs: number): Rx.Observable<string> {
    let result = new Rx.Subject();
    setTimeout(() => {
        console.log(s);
        result.next(s);
        result.complete();
    }, delayMs);
    return result.asObservable();
}

wrapArray([
    Rx.Observable.defer(() => Rx.Observable.of('one')),
    Rx.Observable.defer(() => delayFunc("two yo", 500)),
    Rx.Observable.defer(() => delayFunc("three yo", 10)),
    Rx.Observable.defer(() => Rx.Observable.of('four yo')),
  ])
  .forEach(
    function (results) {
      console.log(results);
    },
    function (err) {
      console.log('Error: %s', err);
    }
  );

describe('common', () => {
    it('should buy time', (done) => {
        setTimeout(x => {
            done();
        }, 10000);
    });
});
```
with output:
```
  common
two yo
three yo
[ 'one', 'two yo', 'three yo', 'four yo' ]
```

Now it makes sense. Two comes before three, and all four are in the results array.

**Comment by trxcllnt** [comment]
@bill-mybiz Yes, this is the distinction between Observable _creation_ and Observable _subscription_. In both your examples, you're synchronously creating Observables, but when you wrap the call to `func` in `Observable.defer()`, you're delaying the call to `func` to the point at which each inner Observable is _subscribed_ to by `concatAll`.

You can also delay creating each inner Observable until the one before it is completed by using `concatMap`:

```typescript
execSync<TItem, TResult>({ items, func }: {
    items: TItem[],
    func: (item: TItem) => AsyncSubject<TResult>
}): Observable<TResult[]> {
    return Observable.from(items).concatMap(func).toArray();
}```

**Comment by bill-mybiz** [comment]
@trxcllnt I was in the middle of testing changes that you recommended and writing a response when life intervened. I apologize for the delay, and I thank you for your quick response. RxJS's super-active community and extensive documentation is the primary reason we chose RxJS over Bacon and others. 

With that said, it's actually that documentation that I posted this issue about. That `execSync` code was given for some background (i.e. my use case). You phrased the heart of the issue nicely in that it was highlighting the difference between creation and subscription, and the change made to the `execSync` code worked.

However, it's the `async.series` example code that I tried to focus on, as that code is what people learning Rx from the `async` library will be looking at. I only posted the issue because It is **not ** "my example", rather it is the official RxJS example. And as I stated, it doesn't seem to execute synchronously as given, at least to non-expert learners (who I would think compose the target audience). This seems to stem from the example using an observable that acts synchronously (the `just` in the documentation, `of` in my example), as opposed to the actual use case for `async.series`.

And so, do you think the current documentation is correct as-is?

**Comment by trxcllnt** [comment]
@bill-mybiz ah, I understand now. Yes, this example should probably be updated cc: @staltz who has been focusing on this area.
