### ISSUE TITLE
Stop polyfilling all of Symbol

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#1425]
I think we should get out of the business of polyfilling Symbol. Leave that to someone else.

All we need is:

1. To get `Symbol.observable` if it exists, and polyfill it if the environment supports Symbol.
2. Otherwise just get `@@observable`
1. To get `Symbol.iterator` if it exists, or whatever reasonable facsimile we can find.

I don't _think_ we're using `Symbol.for` anywhere, but we can look at that.

The win here would be to make the library a _tiny bit_ lighter, and prevent duplicating any Symbol shimming code other libraries and apps using Rx might have.

**Comment by zenparsing** [comment]
I was just looking into this as well, and I agree.

For interoperability purposes, what should observable libraries (not just RxJS) do here?  They certainly shouldn't be required to polyfill Symbol.  Should they even be required to polyfill `Symbol.observable`?

**Comment by zenparsing** [comment]
If we don't want to require `Symbol.observable` polyfilling, we could use this algorithm:

1. If `Symbol` is present, then
  1. If `Symbol.observable` is present, return `Symbol.observable`.
  1. If `Symbol.for` is present, return `Symbol.for("observable")`.
1. Return the string `"@@observable"`.

**Comment by staltz** [comment]
This proposal deserves the shortest digit of the human hand, the *pollex*, pointing towards the opposite direction to the core of the planet while the remaining human digits are withdrawn together: :+1:

**Comment by blesh** [comment]
@zenparsing ... please see my PR at #1426. I'm doing basically what you suggested, with one exception, I'm polyfilling `Symbol.observable` if a properly-shaped `Symbol` implementation exists in the global scope.

**Comment by blesh** [comment]
Also, attention @jhusain, as I know this pertains to Falcor's use of Symbol.observable.
