### ISSUE TITLE
Update instructions on adding operators

### ISSUE THREAD

**Issue by staltz** [ReactiveX/RxJS#1429]
I noticed it's hard to document operators while more are being added constantly. We should have a better check list to define when an operator is "done". Here are some things to do when adding an operator, we should have these in CONTRIBUTING.md or something like that:

- Should be added to either core or kitchen sink
- Should have `-spec.ts` tests covering the canonical corner cases, with marble diagram tests
- Should have a `asDiagram` test case, **if possible**
- Should have a type definition test at the end of spec to verify type definition for various use cases
- Should have documentation in JSDoc style, including also the PNG marble diagram `img`
- Should be listed in `doc/operators.md` in a category of operators
- Should be put in the operator decision tree file `doc/decision-tree-widget/tree.yml`
- Update MIGRATION.md if it covers migration
- (maybe something else that I forgot, please mention if you remember it)

**Comment by kwonoj** [comment]
+1 for this.

- update MIGRATION.md if it covers migration

if https://github.com/ReactiveX/RxJS/pull/1414 is being landed :
- add type definition test at the end of spec to verify type definition for various use cases

**Comment by kwonoj** [comment]
Maybe should list all of this as checklist in github template for PR? (https://github.com/ReactiveX/RxJS/issues/1355)

**Comment by staltz** [comment]
Thanks for those two, I updated the list above. 

> Maybe should list all of this as checklist in github template for PR? (#1355)

Agreed

**Comment by kwonoj** [comment]
Closed via https://github.com/ReactiveX/RxJS/pull/1432.
