### ISSUE TITLE
throttle + debounce

### ISSUE THREAD

**Issue by ronag** [ReactiveX/RxJS#1445]
I need either a debounce with a max timeout or a throttle that send the latest value when timeout.

Something similar to https://lodash.com/docs#throttle with `{ leading: true, trailing: true }`.

Is this somehow possible?

**Comment by trxcllnt** [comment]
@ronag you want [`inspect`](https://github.com/ReactiveX/RxJS/blob/master/src/operator/inspect.ts) or [`inspectTime`](https://github.com/ReactiveX/RxJS/blob/master/src/operator/inspectTime.ts) ([context](https://github.com/ReactiveX/RxJS/issues/1112)).

**Comment by ronag** [comment]
So I would do?

```javascript
   x$.inspectTime(1000).distinctUntilChanged()
```

I'm unsure whether the `distinctUntilChanged()` is required?

**Comment by ronag** [comment]
@trxcllnt: How do I do this now without `inspectTime`?
