### ISSUE TITLE
Proposal: implement bag 'o Subscriptions as an Object instead of Array

### ISSUE THREAD

**Issue by trxcllnt** [ReactiveX/RxJS#145]
Proposal to implement Subscription's bag o' Subscriptions as an Object instead of an Array.

Presently, a single Subscription instance is shared between all Observers. When the Observable's public `subscribe` method is called, Observable [wraps the callbacks or observer in a Subscriber instance](https://github.com/ReactiveX/RxJS/blob/master/src/Observable.ts#L37), then invokes the Observable's private `_subscribe` method.

The `_subscribe` method passes this first Subscriber to the Operator, which uses the Subscriber as the "destination" for the Operator's Subscriber. The Operator's Subscriber [checks to see if its "destination" has a shared Subscription](https://github.com/ReactiveX/RxJS/blob/master/src/Subscriber.ts#L32). If it finds one, it uses it. If it doesn't, but its destination is a Subscriber, it assumes its destination is the shared Subscription.

Intermediate Subscribers [proxy all the Subscription methods](https://github.com/ReactiveX/RxJS/blob/master/src/Subscriber.ts#L40) to the shared Subscription, except in the case where the Subscriber *is* the shared Subscription.

This technique absolves intermediate Operators of their duty to allocate a Subscription/closure to track their source Subscription, drastically reducing the number of allocations upon subscription. An operator only needs to track additional internal subscriptions it introduces (as is the case with [merge](https://github.com/ReactiveX/RxJS/blob/master/src/operators/merge.ts#L71)).

Operators that introduce inner Subscriptions should remove inner subscriptions when they're no longer active, so we don't introduce memory leaks for long-running (or infinite) Observables. Since inner subscriptions from *all* operators are added to the same underlying shared Subscriber, the O(n) cost of looking up and splicing inner Subscriptions from an Array is quite expensive. My preliminary tests show this is about half as fast in v8 as the equivalent operation using an Object.

**Comment by blesh** [comment]
> Operators that introduce inner Subscriptions should remove inner subscriptions when they're no longer active, so we don't introduce memory leaks for long-running (or infinite) Observables.

Per our discussion today, @trxcllnt, this sounds good to me.

For others: as an example, imagine a Node server running some Observable for a long time that has a flatMap in it... with the *current* code, as it stands, the subscription would build up a growing array of inner subscriptions, most of which are probably long unsubscribed.

This proposal serves to provide an efficient mechanism for trimming dead subscriptions from the built up subscription list.

**Comment by blesh** [comment]
I'm going to close this for now, as unsubscription performance is doing quite well, and we haven't identified any issues.

I think it's a good idea to keep this in our back pocket, but as the library is beginning to stabilize, I think it's probably prudent to avoid potentially volatile changes for now.
