### ISSUE TITLE
switch operator test case behavior with promises

### ISSUE THREAD

**Issue by kwonoj** [ReactiveX/rxjs#1450]
This seems test case design than operator behavior, 

```js
Observable.of<any>(Promise.resolve(1), Promise.reject(2), Promise.resolve(3))
      .switch()
      .subscribe((x: number) => {
        expect(x).toBe(3);
      }, (err: any) => {
        expect(err).toBe(2); //this is not actually asserted
      }, () => {
        done();
      });
```

seems promise elements are being emitted before either it's being resolved or rejected. (and if `error()` is actually being called, `complete` should not be called)

@staltz , is this expected test design? (asking you since it was added with your commit looking at [history](https://github.com/ReactiveX/RxJS/commit/57ad9861baf722fb7c5d07858faf70ed4354eab8#diff-7d20220faf9ec300584166298c9da813R155))

**Comment by staltz** [comment]
That test looks wrong, I wonder why I wrote it like that.

**Comment by staltz** [comment]
Could have been to make coverage larger.

**Comment by kwonoj** [comment]
Closed via https://github.com/ReactiveX/rxjs/pull/1472 .
