### ISSUE TITLE
rx v4 merge(Array) does not work with rx v5

### ISSUE THREAD

**Issue by marcusnielsen** [ReactiveX/RxJS#1454]
I did a quick swap from rxjs v4 to v5 and followed the convertion guide.
RxJS v5 #merge operator didn't work as before when sending in an array of observables.

**RxJS version:**
rxjs@5.0.0-beta.2

**Expected**
Docs say:
` @return {Observable} an Observable that emits items that are the result of every input Observable.`
https://github.com/ReactiveX/RxJS/blob/master/src/operator/merge.ts#L13

This works:
https://github.com/marcusnielsen/rxjs-server/blob/master/app/helpers/eventStreamComposer/index.js#L16

**Code to reproduce:**
This does not work:
https://github.com/marcusnielsen/rxjs-server/blob/merge-with-array-demo/app/helpers/eventStreamComposer/index.js#L16

**Additional information:**
Here's the test:
https://github.com/marcusnielsen/rxjs-server/blob/merge-with-array-demo/app/helpers/eventStreamComposer/index.test.js
Test output:
```
'TypeError: event$.subscribe is not a function'
```
If  I remember correctly, it just returns an array with two Subjects back.

**Comment by kwonoj** [comment]
Is this same as https://github.com/ReactiveX/RxJS/issues/1308?

**Comment by marcusnielsen** [comment]
Yessir, it's a doublett. Sorry about that, and thank you for the quick response.

**Comment by kwonoj** [comment]
Thanks for confirmation. Since there's already opened issue with proposal for discussion, let me close this issue and let's track further suggestions in original issue.

**Comment by marcusnielsen** [comment]
:+1:
