### ISSUE TITLE
share micro perf test invalid

### ISSUE THREAD

**Issue by benlesh** [ReactiveX/rxjs#1457]
The current code to micro perf share is testing the shared Rx4 observable one time, and then every other iteration it fails fast. This is because in Rx4, a "shared" observable cannot be "reshared" once it's complete.
1. `oldShareWithImmediateScheduler` is created and shared here, making it "hot".
2. The first subscription to `oldShareWithImmediateScheduler` happens [here](https://github.com/ReactiveX/RxJS/blob/f7ff7ec72d4d2ab342c669b9532036685a0c4cf2/perf/micro/immediate-scheduler/operators/share.js#L13)
3. The `range` from the source synchronously completes.
4. The second subscription to `oldShareWithImmediateScheduler` is subscribing to a published observable that has a "dead" `Subject` inside of it.

We're not testing apples to apples in this test. The Rx5 version of `share` will actually recycle the Subject on each new subscription after the internal Subject goes "dead". The Rx4 version will just fail fast on subsequent subscriptions to a completed, published observable.

**Comment by blesh** [comment]
Need to double check this again.

**Comment by trxcllnt** [comment]
@blesh forgot about this one. seems like it's still a thing: https://github.com/ReactiveX/rxjs/blob/master/perf/micro/immediate-scheduler/operators/share.js#L5

**Comment by benlesh** [comment]
The micro perf tests all need a complete overhaul. Closing this for now.
