### ISSUE TITLE
Migrate test runner from jasmine to another

### ISSUE THREAD

**Issue by kwonoj** [ReactiveX/rxjs#1460]
**Additional information:**

It is known jasmine behaves unexpectedly time to time, test cases are fail without exact reason. As similar to recent failures (https://github.com/ReactiveX/RxJS/pull/1459) just removing test cases into separate file, or modify test execution order makes it passes again. Problem in here is it becomes hard to trust test failures sometimes, cause it's unclear if given assertion failure is due to actual code behavior or simply jasmine's behavior. Maybe it's time to consider to move into different test runner other than jasmine, depends on migration effort.

**Comment by saneyuki** [comment]
How about [power-assert](https://github.com/power-assert-js/power-assert) or [ava](https://github.com/sindresorhus/ava)? Their failure dump are informative.

**Comment by kwonoj** [comment]
I'd like to discuss go / no-go first in this discussion. I also have some preferences, but need to be evaluated based on certain requirements such as current toolchain support (coverage, esdocs, etcs) and it can be evaluated once got agreements to go. Though I think it's time to consider, there might be other difficulties I could not think of to block to move on.

**Comment by david-driscoll** [comment]
I've had good success with Mocha over the year, it has built in support for promises, so for tests I've done in the past, so async tests can sometimes be as easy as...

```
it('should return 0', () => {
  return Observable.of(1).toPromise().then(result => expect(result).to.be.eql(1));
});
```

**Comment by blesh** [comment]
Given what I saw while working on #1536 ... I find jasmine's fragility to be _very_ disturbing.

**Comment by blesh** [comment]
I'm changing this to "high priority" and "PRs welcome" ... but this is NOT at all critical to release, so it's probably not something I'd want anyone tackling in the short term if they're looking to add the most value.

**Comment by kwonoj** [comment]
I'll try this on my end if this can be done relatively quickly.

**Comment by kwonoj** [comment]
Closing this via https://github.com/ReactiveX/rxjs/pull/1545. One remaining issue is being tracked separately via https://github.com/ReactiveX/rxjs/issues/1549.
