### ISSUE TITLE
Proposal: BehaviorSubject.asObservable overload

### ISSUE THREAD

**Issue by roganov** [ReactiveX/RxJS#1478]
`BehaviorSubject` has a useful method `getValue`, which obviously doesn't exist on `SubjectObservable` instance returned by `asObservable()`. To workaround, I have found no other option but to return `BehaviorSubject` instance directly to consumers, what is "unsafe" since consumers can call `.next()` on the subject.
I would like to propose that `BehaviorSubject.asObservable()` returns a subclass of `SubjectObservable` with a `getValue` method.

**Comment by staltz** [comment]
:-1: in my opinion. Relying on `getValue` is a bad idea to start with. Or... what is your actual use case?

**Comment by roganov** [comment]
My use-case is a redux-like library which exposes an observable of application state.
Though if you think it's a bad idea I believe I can subclass `BehaviorSubject` myself.

**Comment by staltz** [comment]
In that case, with a subscribe you are able to get the current value of the BehaviorSubject. In Redux itself, subscribe does not give you the current value, that's why you need `store.getState()`, but that's not the case with an observable.

**Comment by blesh** [comment]
I agree with staltz here. I wouldn't want to add to the complexity in this area for that use case. The use cases around `getValue` are already questionable (although I have used it myself :P) 

@roganov for the time being, I'm going to close this feature request. If you feel that you have been misunderstood or that you haven't presented your full case, please do reopen and I'm very happy to hear what else you have to say.

Additionally, I hope this doesn't put you off from contributing ideas or code in the future. We really value your input to our project.

**Comment by roganov** [comment]
I understand your and @staltz reasoning (I had doubts if this is a good idea as well) so I'm OK with this issue being closed. :smile:

**Comment by ohjames** [comment]
Consider this example in angular 2:

```
(click)="delete(observableItems | async)"
```

It is invalid because pipes cannot be used in action handlers. To work around this I have to read `observableItems` from within the action handler, but of course it's not possible without `getValue()` or a second additional subscription to the observable and a whole bunch more boiler plate.
