### ISSUE TITLE
Implement static generate creation methods

### ISSUE THREAD

**Issue by trxcllnt** [ReactiveX/rxjs#1482]
Need to implement the [`generate`](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/generate.md) family of static creation operators.

**Comment by blesh** [comment]
This is one of those APIs where a config object would make it much more readable. Thoughts @mattpodwysocki?

Optionally, we should at least have our docs use named functions.

**Comment by kwonoj** [comment]
Closing via https://github.com/ReactiveX/rxjs/pull/1537.
