### ISSUE TITLE
Update static operators to accept promises across the board

### ISSUE THREAD

**Issue by trxcllnt** [ReactiveX/rxjs#1483]
A lot of this is my fault, but given that we've decided to interop with promises in most places, we should probably ensure we do it consistently. That means updating the family of static `defer` creation operators (defer, if, using, etc.) to accept promises, lowercase-o observables, etc. to use our internal `subscribeToResult` function.

**Comment by kwonoj** [comment]
Is this related to https://github.com/ReactiveX/RxJS/issues/1246?

**Comment by trxcllnt** [comment]
@kwonoj yes it is

**Comment by blesh** [comment]
Really, there shouldn't be anything public facing that "accepts" `Observable<T>`, it should always accept `SubscribableOrPromise<T>`. Or at the very least `Subscribable<T>`. Having a function that accepts a strict class type is a 101 mistake, we should have been using interfaces this whole time.

**Comment by blesh** [comment]
We should probably make separate issues for the operators in question.

**Comment by staltz** [comment]
Can I remind people that if future PRs change the signature of an operator, please remember to update also the docs that I wrote for them. Otherwise docs will be a moving target

**Comment by kwonoj** [comment]
I think this one's covered mostly, can this be closed maybe? (Assume `ConnectableObservable` is not fall into this?)

**Comment by kwonoj** [comment]
I think most static operators are now covered as commented, /cc @blesh for visibility before closing this out and switching to open issues for each individuals, in case I miss something should be covered before closing.

**Comment by kwonoj** [comment]
Closing this, if there's remaining operator will file separate.
