### ISSUE TITLE
windowToggle bug in WindowToggleSubscriber#closeWindow

### ISSUE THREAD

**Issue by staltz** [ReactiveX/rxjs#1487]
**RxJS version:** 5.0.0-beta.2

**Code to reproduce:**
```js
var clicks = Rx.Observable.fromEvent(document, 'click');
var openings = Rx.Observable.interval(1000);
var result = clicks.windowToggle(openings, i =>
  i % 2 ? Rx.Observable.interval(500) : Rx.Observable.empty()
).mergeAll();
result.subscribe(x => console.log(x));
```

**Expected behavior:**
No error thrown, some messages in the console when the user clicks.

**Actual behavior:**
`Uncaught TypeError: Cannot read property 'window' of undefined` after 1 second.

**Additional information:**
Seems to happen in `WindowToggleSubscriber#closeWindow`.

JSBin: http://jsbin.com/zenelokita/1/edit?html,js,output

**Comment by blesh** [comment]
Good catch
