### ISSUE TITLE
Provide a bundle containing the test utilities (TestScheduler)

### ISSUE THREAD

**Issue by valotas** [ReactiveX/rxjs#1492]
It would make testing much more easier as it can be easily included to jsfindle/jsbin/plunker.

**Comment by kwonoj** [comment]
If you need `testScheduler` only immediately, I believe Rx.Kitchensink (i.e https://npmcdn.com/@reactivex/rxjs@5.0.0-beta.2/dist/global/Rx.KitchenSink.umd.js) exports it as well as other cores. So far I know rest of test harness like marble, etcs will be published in further releases as well.

**Comment by valotas** [comment]
Sorry, I didn't see that. It looks like the docu needs to get improved there. Is there anything I can do to help? Otherwise I'll close this issue.

**Comment by kwonoj** [comment]
Document is being evloved, so it may not reflect some of latest status as you mentioned. I think this one's also one of topic need to be covered, if you have proposal or suggestion PR, it is greatly appreciate and welcome all time.

**Comment by kwonoj** [comment]
Current repo evolving its document over time (can be checked at http://reactivex.io/rxjs/) and test scheduler itself is already published, I'm closing this issue. @valotas , hope issue's resolved and please feel freely reopen if there's not fulfilled, or create new one if necessary.
