### ISSUE TITLE
Docs missing - what are the params of mergeMap ?

### ISSUE THREAD

**Issue by alvipeo** [ReactiveX/RxJS#1496]
RxJS 5.0 beta 2

Can somebody provide docs for mergeMap? This is one of the most important operators!
What is result selector and how to use it? Use cases?
Also, concurrent parameter - it seems clear but still I think I might miss something. Just like anyone else.

**Comment by paulpdaniels** [comment]
`mergeMap` -> `flatMap`

It is functionally very similar to the [RxJS 4 version](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/selectmany.md).

The concurrency parameter is equivalent to the [`map(fn).merge(maxConcurrency)`](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/mergeproto.md) pattern in RxJS 4 as well.

**Comment by blesh** [comment]
Yes `mergeMap` and `flatMap` are the same thing. Shouldn't differ from RxJS4, other than the new concurrency parameter.

**Comment by blesh** [comment]
I've started a new issue to track adding parameter info to merge map. #1502
