### ISSUE TITLE
mergeMap documentation needs parameter info

### ISSUE THREAD

**Issue by blesh** [ReactiveX/rxjs#1502]
Currently the [parameters](https://github.com/ReactiveX/RxJS/blob/2ec5b24a7513ee8aaa075358c0b5c5634226e70a/src/operator/mergeMap.ts#L22) to `mergeMap` (one of our most important operators) are undocumented.

**Comment by staltz** [comment]
Yes boss, will do. I'm writing detailed operator docs and all the buffer and window operators are already covered. I can give priority to the merge operators, and document them e.g. tomorrow Tuesday.

**Comment by blesh** [comment]
@staltz that would be great. The merge strategy operators are easily the most critical operators that are misunderstood.

**Comment by ladyleet** [comment]
@blesh @staltz this can be closed. ps hai andre. #sobenlesh

**Comment by blesh** [comment]
Thanks @ladyleet
