### ISSUE TITLE
Missing/broken links in doc files. 

### ISSUE THREAD

**Issue by AdamWendell** [ReactiveX/rxjs#1503]
I noticed that there are quite a few broken/missing links in the .md files. 
Is this something that you want help with?

If so I would love too help, just a few questions. 
1. Is doc/manual meant to be a folder or is the root of doc where those files will remain?
2. The links to each operator in [operators.md](https://github.com/ReactiveX/RxJS/blob/master/doc/operators.md), will they link to the operator in http://reactivex.io/RxJS/ or to separate markdown files as in [Reactive-Extensions/RxJS/](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/libraries/main/rx.complete.md).
3. How should the PRs be made, 1 per file worked on or as many links fixed as possible?

**Comment by blesh** [comment]
FYI: the docs are now at http://reactivex.io/rxjs, and that changed just a couple of hours ago. Does that have anything to do with your issues?

**Comment by AdamWendell** [comment]
Yes that seem too fix everything!
