### ISSUE TITLE
Postinstall `typings install` not running on fresh install

### ISSUE THREAD

**Issue by blesh** [ReactiveX/rxjs#1504]
**Steps to reproduce:**

- completely delete local directory and repository.
- get a fresh clone of the repository and `cd` into it
- run `npm install`
- run `npm run build_amd`

**Expected behavior:**

Everything builds

**Actual behavior:**

You get an error that `typings/main.d.ts` cannot be found.

**Additional information:**

Running `npm run postinstall` directly will solve the issue for now. I'm not sure what the npm nuance is to fix this, but I suspect that we need to move the `typings install` command to an `"install"` script and not `"postinstall"`.

**Comment by kwonoj** [comment]
`postInstall` supposed to be triggered after `install` is resolved as single lifecycle, but seems sometimes it 's not occurring. I'll look for better way to hook up those. (or gladly welcome suggestion / PR if someone already knows about this)

**Comment by kwonoj** [comment]
@blesh , I think latest PR resolved this. If problem persists or any other problem occurs, reopen or ping me anytime.
