### ISSUE TITLE
Rename `inspect` to `audit`

### ISSUE THREAD

**Issue by blesh** [ReactiveX/rxjs#1505]
Relates to discussed issue here #1387. Basically, `inspect` is a name-collision in Node because it's an API that should have been a `Symbol`, but couldn't have been because it predates Symbols. /shrug

Anyhow, since the `inspect` operator is brand new with this major version, we can rename it. I think `audit` is a fine name, props to @kennethlawrence for the idea.

Labeling priority `high` because we don't want any breaking changes to existing APIs after production release.

**Comment by kwonoj** [comment]
Closed via https://github.com/ReactiveX/rxjs/pull/1512.
