### ISSUE TITLE
Property 'zip' does not exist on type 'typeof Observable'.

### ISSUE THREAD

**Issue by alvipeo** [ReactiveX/rxjs#1507]
Just upgraded project to beta.3 and got zip does not exist on type 'typeof Observable'.
Other 2:
1. Property 'fromPromise' does not exist on type 'typeof Observable'.
2. Property 'take' does not exist on type 'ReplaySubject<MyClass>'.

What does it mean? (this is angular2 project).

**Comment by kwonoj** [comment]
Would you able to share code snippets how did you import rx into your codebases?

**Comment by kwonoj** [comment]
I've tried to reproduce this with master but so far no luck. @alvipeo , I'm closing this issue for now, please feel freely reopen anytime, if this is still occurs beta.4 or repo's master directly. It'd be appreciate if you can share snippet to reproduce issue.

**Comment by ahmad2smile** [comment]
I'm getting the exact same issue. I imported Observable in Angular 2 project from "rxjs/Observable". No solution on SO either.

**Comment by matthiaskomarek** [comment]
@ahmad2smile solved this issue by importing the zip operator like this
```
import 'rxjs/add/observable/zip';
```

**Comment by matiishyn** [comment]
I'm getting the same issue after upgrading to RxJS6
code:
```ts
import {BehaviorSubject, Observable} from 'rxjs';
//...
// trying to use zip method that returns Observable 
myMethod(params) {
    const places$: Observable<Place>[] = placesKeys
      .map(placeKey => this.placeService.fetchPlaceByKey(placeKey));

    return Observable.zip(...places$)     // <===== DOESNT WORK
      .map((places: Place[]) => {...})
      .flatMap((places: Place[]) => {...})
      // ...
  }
```

When I simply import `zip` from operators that chaining doesn't work `Observable.zip(...places$).map`

Please help me
