### ISSUE TITLE
chore: add VirtualTime and Test Schedulers

### ISSUE THREAD

**Issue by trxcllnt** [ReactiveX/RxJS#151]
Filing issue to track this chore. Since the current Scheduler interface is so small, I'd like to keep the VirtualTime/Test Scheduler interfaces small as well. Would love to hear feedback from @mattpodwysocki and @headinthebox on the minimal API required to get started.

We'll also need the ability to switch on the recursive-vs-trampolining strategies.

```es6
interface Scheduler {
  now() : number;
  schedule<T>(work: (state?: any) => void, delay: number = 0, state?: any): Subscription<T>;
}

interface VirtualTimeScheduler extends Scheduler {
  tick(timeElapsed: number): void;
}

interface TestScheduler extends VirtualTimeScheduler {
  advance(steps: number): void;
}
```

**Comment by blesh** [comment]
Whatever we do, I'd like to avoid the deep magic of the RxJS 2 tests. I'd like the tests to be clear and readable to any newcomer.

**Comment by mattpodwysocki** [comment]
@staltz disagree completely. This raised the bar of contribution to fully understand the ramifications of adding certain operators versus using ones we already have. I'm pretty sure @headinthebox is on board with the same thing. If it doesn't have time based tests, I will not have confidence that we're doing things right.

**Comment by blesh** [comment]
> @staltz disagree completely

I'm not @staltz :P

> If it doesn't have time based tests, I will not have confidence that we're doing things right.

This is true for any temporal operations. But testing say, map or filter, against a synchronous range is completely deterministic.

> This raised the bar of contribution to fully understand the ramifications of adding certain operators versus using ones we already have.

I don't think we should be raising the bar for contributions. As caretakers of this repo, *WE* are the bar that needs to be passed in order for a PR to be merged. There should be no additional barrier to feeling comfortable making a PR. 

We *want* contributions from experts in Rx, sure, but they shouldn't have to be experts in obscure testing methods that have steep learning curves. 

I'd like the virtual time testing methods to have a very shallow learning curve. I think we can do this and accomplish our goals.

**Comment by mattpodwysocki** [comment]
@blesh there really isn't much magic to what we're doing in that you realize the following test cases were covered:
1. Never
2. Empty
3. Single/Multiple Values
4. Infinite Sequences
5. Early disposal, meaning dispose called before the sequence ended.
6. Error in callback
7. Error in stream

Once you understand that those bases need to be covered to ensure that both the operator and scheduler both work in unison together, then you will see the value.  Like I said, without these in place, I have very little confidence that many of the edge cases will be brought out.

**Comment by mattpodwysocki** [comment]
@blesh I think what you're failing to see is that all operators have temporal aspects to them just due to the nature of Rx being virtual time based.  Remember, this was the differentiating factor in Rx and we should never play that down.

**Comment by trxcllnt** [comment]
@mattpodwysocki I agree 100% with your checklist about what needs to be tested, and I think @blesh does too. My main goal with the tests is to make them easy two read/write for people who already know jasmine/mocha/tape, without forcing contributors to learn an Rx-specific harness + matchers.

**Comment by blesh** [comment]
Agreed.

Also we shouldn't have to add anything that impacts performance just to accommodate testing.

**Comment by blesh** [comment]
copied from #150 ... 
-----

The more I think about it, the more I like @staltz's proposal, particularly if we convert over to ES6 for the tests.

I think we could create some jasmine-esque helpers that will do things like subscribed to the scheduled observables and flush the virtual time to assert expectations:

```js

describe('some test', _ => {
  it('should do something', done => {
    let test = new TestScheduler(),
        cold = test.createColdObservable;

    let a = 1, b = 2, c = 3;

    let xs =        cold('----a---b-----|', { a, b });
    let ys =        cold('------c-------|', { c });
    let expected =  cold('----a-c-b-----|', { a, b, c });

    let result = xs.merge(ys);

    expectObservable(result).toEqual(expected);
  });
});


```

Tricker would be the hot observables,  because you want to have a little gap in time before subscription, perhaps we could delinate subscription time with another character, such as a `$`:

```js
describe('some test', _ => {
  it('should do something', done => {
    let test = new TestScheduler(),
        hot = test.createHotObservable;

    let a = 1, b = 2, c = 3, d = 4;

    let xs = hot('----a--$----b---c-----|', { a, b });
    let ys =        cold('------d-------|', { d });
    let expected =  cold('----b-d-c-----|', { b, c, d });

    let result = xs.merge(ys);

    expectObservable(result).toEqual(expected);
  });
});
```

**Comment by staltz** [comment]
> Tricker would be the hot observables, because you want to have a little gap in time before subscription, perhaps we could delinate subscription time with another character, such as a $:

Or something like this:
```js
let s =      '-------|'; // subscription time
let xs = hot('----a--$----b---c-----|', s, { a, b });
let ys =        cold('------d-------|', { d });
let expected =  cold('----b-d-c-----|', { b, c, d });
```

**Comment by blesh** [comment]
Actually, it seems like the subscription time should go on the subscribers:

```js
let s =      '-------|'; // subscription time
let xs = hot('----a-------b---c-----|', { a, b });
let ys =        cold('------d-------|', { d }, s);
let expected =  cold('----b-d-c-----|', { b, c, d }, s);
```

**Comment by headinthebox** [comment]
@blesh 
> Whatever we do, I'd like to avoid the deep magic of the RxJS 2 tests. 
> I'd like the tests to be clear and readable to any newcomer.

I personally do not see any difference between the ASCII notation and the regular Rx tests; the `s` is done by convention in the old Rx style tests (and I predict that you will get bored out of your skull repeating yourself writing that every time ;-), but whatever makes you feel comfortable is OK, as long as we have virtual time-based tests.

**Comment by blesh** [comment]
> (and I predict that you will get bored out of your skull repeating yourself writing that every time ;-)

@headinthebox I think it will be more tedious typing tests the "old" way, honestly:

So I ran the following by a couple of folks that hadn't written an RxJS test before, and the newer way was determined to be easier to follow (not very scientific I know, but whatever):

Consider the old way:

```js
test('Concat_ReturnReturn', function () {
    var e1, e2, msgs1, msgs2, results, scheduler;
    scheduler = new TestScheduler();
    msgs1 = [onNext(150, 1), onNext(220, 2), onCompleted(230)];
    msgs2 = [onNext(150, 1), onNext(240, 3), onCompleted(250)];
    e1 = scheduler.createHotObservable(msgs1);
    e2 = scheduler.createHotObservable(msgs2);
    results = scheduler.startWithCreate(function () {
        return e1.concat(e2);
    });
    results.messages.assertEqual(onNext(220, 2), onNext(240, 3), onCompleted(250));
});
```

vs newer: 

```js
it('should work for two completing hot observables', () => {
    let a = 1, b = 2, c = 3;
    let test = new TestScheduler();
    let hot = test.createHotObservable;
    let e1 =   hot('--a--^-b---|', { a, b })
    let e2 =  hot('--a---^------c---|', { a, c });
    let expected =       '-b----c---|';
    expectObservable(e1.concat(e2)).toEqual(expected);
});
```

And I think we can easily have helpers remove the boilerplate of creating a new TestScheduler each test and pulling out the `hot` function:

```js
it('should work for two completing hot observables', () => {
    let a = 1, b = 2, c = 3;
    let e1 =   hot('--a--^-b---|', { a, b })
    let e2 =  hot('--a---^------c---|', { a, c });
    let expected =       '-b----c---|';
    expectObservable(e1.concat(e2)).toEqual(expected);
});
```

I've moved back to a character such as `^` or `$` for defining the subscription point, and away from @staltz's idea of having a seperate string to define it, I did this mostly because I think it's more readable.

**Comment by blesh** [comment]
@stealthcode brought up a fine point, we need a way to symbolize onError terminal events in this notation. I propose a bang for that: `!`.

```js
var twoValuesAndAnError = cold('---a---b---!`, { a, b});
var threeMenAndABaby =    cold('--a--b--c--!', { a, b, c});
```

**Comment by blesh** [comment]
You can't tell your bangs from your pipes with GitHub's fonts....

**Comment by staltz** [comment]
I propose capital X.

```js
var twoValuesAndAnError = cold('---a---b---X', { a, b });
var threeMenAndDone =     cold('--a--b--c--|', { a, b, c });
```

**Comment by mattpodwysocki** [comment]
@blesh this is why I'd vote against the use of marble charts however nice they may be. They lack the subtlety of virtual time especially when it comes to gaps of 1 versus 10 in virtual time (which does matter btw). To me, there's a little bit too magic for using marble diagrams and how to read them instead of knowing when an operator fires and with what value with a precise time and a precise output.  Am I mistaken here @headinthebox?

**Comment by staltz** [comment]
@mattpodwysocki if one is concerned about the size of the gaps (1 or 10 in virtual time), just use multiple `-`. Let `-` represent `10` virtual time units:

```
-a-b------c----|
```
is `onNext(10, 'a')`, `onNext(30, 'b')`, `onNext(100, 'c')`.

```
-a-------b---------c----|
```
is `onNext(10, 'a')`, `onNext(100, 'b')`, `onNext(200, 'c')`.

Can you come up with virtual time conditions that cannot be isomorphically* equivalent to one of these marble diagrams? 
*and I actually mean https://en.wikipedia.org/wiki/Isomorphism

**Comment by stealthcode** [comment]
@staltz I think it's best to reserve alpha numeric values for data emissions and not have to provide an explanation why 1 of the characters means something different. I think that a special character like the asterisk, the bang, or hash would require less explanation or cognitive overhead.

**Comment by staltz** [comment]
Fair observation, but notice this

![http://reactivex.io/assets/operators/legend.png](http://reactivex.io/assets/operators/legend.png)

Most Rx folks are used to X being the error indicator. I believe most practical and short marble diagrams would not need more than `a`, `b`, `c`, `d`, `e`, `f`, `g`, `h`, and it's not like we are making a programming language out of these. An easy convention would be: always lowercase for onNext events.

**Comment by headinthebox** [comment]
I think the charts are fine; in fact at one time I proposed to represent all tests as data in a form like this, so we could use the same tests across languages by reading the diagrams from a common repo.

You can do `.` fro one tick, and `-` for 10 (or st like that if you want to be super precise)

**Comment by staltz** [comment]
>  one time I proposed to represent all tests as data in a form like this, so we could use the same tests across languages by reading the diagrams from a common repo.

That would be great to ensure consistency. And it's doable.

**Comment by blesh** [comment]
> it's doable.

This is a totally different discussion, but I suspect languages with *real* concurrency might not be able to use our tests. ;)

**Comment by blesh** [comment]
> That is the whole point of the virtual time/test scheduler! You want to control concurrency when you test.

Fair... I just meant something with threading might not be able to keep the same marble diagrams. But perhaps I'm wrong, I've put about 30 seconds of thought into it.
