### ISSUE TITLE
Add a subscription argument to next?

### ISSUE THREAD

**Issue by zenparsing** [ReactiveX/rxjs#1513]
I think we should consider adding an additional "subscription" argument to `observer.next`.

(See https://github.com/zenparsing/es-observable/pull/84 for the spec changes.)

Consider the following:

``` js
// Synchronously emits: 1, 2, 3, done
let observable = new Rx.Observable(sink => {
    sink.next(1);
    sink.next(2);
    sink.next(3);
    sink.complete();
});

observable.first(x => {
    console.log(`First called with: ${ x }`);
    return true;
}).subscribe({
    next(x) { 
        console.log(`Observer called with: ${ x }`);
    }
});
```

Output:

``` js
'First called with: 1'
'Observer called with: 1'
'First called with: 2'
'First called with: 3'
```

Expected output:

``` js
'First called with: 1'
'Observer called with: 1'
```

Looking past the implementation details of Rx's `first`, the general issue here is that it's tricky to implement correct termination semantics in the face of synchronous emission.  The operator wants to unsubscribe in response to a `next` call, but can't because the `subscription` hasn't been made available yet.  This also comes up in the implementation of `forEach`, when we want to unsubscribe if the user callback throws an error.

To correctly handle the synchronous case, you currently have to do something like track whether `subscribe` has returned yet and handle that case differently within the `next` handler.

The proposal is to provide the subscription as a second argument to the observer's next method.  The safe observer automatically adds the parameter when calling through to the consuming observer.  The implementation of `first becomes something like:

``` js
function first(pred) {
    return new Observable(sink => {
        return this.subscribe({
            next(x, subscription) { 
                let take = false;

                try { take = Boolean(pred(x)) } 
                catch (e) { return sink.error(e) }

                if (take) {
                    subscription.unsubscribe();
                    return sink.next(x);
                }
            },
            error(e) { return sink.error(e) },
            complete() { return sink.complete() },
        });
    });
}
```

Thoughts?

**Comment by trxcllnt** [comment]
@zenparsing the first subscriber should be completing + unsubscribing upon the first event that passes its predicate test, thus setting the subscriber state to ignore future next values, regardless of whether the source next's again or not. If this is not the case we have a bug :/

**Comment by zenparsing** [comment]
@trxcllnt Right, it's a bug.  In general though, it's not trivial to write bug-free combinators like this which might need to unsubscribe before the `subscribe` call has completed.  That's why I think it might be helpful to provide the subscription as a second argument to "next".

**Comment by trxcllnt** [comment]
@zenparsing ah, I see the source of the bug. not in finally at all. thanks!

**Comment by trxcllnt** [comment]
@zenparsing just so I'm not confused, are you saying it's difficult to write bug-free combinators which need to unsubscribe based _only_ on the nascent Observable specification, or in Rx in general? For reference, this issue wasn't in the `first` operator (which properly notifies the downstream subscriber of completion), but that the subscription chain wasn't fully linked prior to invoking the source `subscribe` callback.

**Comment by Alxandr** [comment]
@trxcllnt You can see the original issue and discussion here: https://github.com/zenparsing/es-observable/issues/83

Should hopefully make the issue clear.

**Comment by blesh** [comment]
closing because the observable proposal did not end up taking this route.
