### ISSUE TITLE
5.0.0-beta.3 `mergeAll` does not accept concurrency parameter (typescript)

### ISSUE THREAD

**Issue by g00fy-** [ReactiveX/rxjs#1526]
After upgrading from `5.0.0-beta.2` to `5.0.0-beta.3` following code won't compile:

```typescript
import * as Rx from 'rxjs'

Rx.Observable.range(1, 10)
    .map(x => Rx.Observable.defer(() => Rx.Observable.of(x).delay(1000)))
    .mergeAll(1)  // if I don't pass any value it will compile
    .subscribe(e => console.log(e))
```

Not sure if it is a `typescript` issue or incorrect typings.

the tsc error message is:
`src/test.ts(3,1): error TS2346: Supplied parameters do not match any signature of call target.`

**Comment by david-driscoll** [comment]
I'm working on a PR and some typing tests for this.

On Wed, Mar 23, 2016 at 10:48 AM, Piotrek Majewski <notifications@github.com

**Comment by kwonoj** [comment]
Closed via https://github.com/ReactiveX/rxjs/pull/1527.
