### ISSUE TITLE
Update Observable to match latest Observable Proposal

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#153]
The following signature is what has come back from the TC-39 (per @jhusain):

```js
class Observable<T> {
  constructor(_subscribe:(observer: Observer) => Subscription);
  [Symbol.observer](observer: Observer): void;
  observe(observer: Observer): Subscription;
  subscribe(nextFn: (value:T) => void, errorFn?: (error:any) => void, completeFn?: () => void, startFn?: (subscription: Subscription) => void): Subscription;
  forEach(nextFn: (value: T) => void): Promise;
  last(): Promise;
  static of(...items:Array<any>): Observable;
  static from(observableLike:any): Observable;
}

interface Subscription {
  unsubscribe(): void
}

interface Observer {
  next(value: any): any;
  error(error: any): any;
  complete(): any;
  start(subscription: Subscription): void
}
```

I think this looks really promising, and it doesn't really constitute a lot of change on our part.

**Comment by mattpodwysocki** [comment]
:-1: from me for right now because until it hits stage 2 or stage 3, I think we should stay as is.

**Comment by blesh** [comment]
> for right now

I agree, but I want to keep this on the radar, because it's one of the goals for the library.

**Comment by jhusain** [comment]
Is there not an issue in the current implementation to be resolved? Specifically the inability for a consumer to sync unsubscribe.

JH

**Comment by blesh** [comment]
Speaking with @trxcllnt and @jhusain ... this change is minimal to what we already have and I think it has high value. Leaving it as a priority for Alpha release.

**Comment by blesh** [comment]
I think this issue covers some of what we discussed here: #70  ... at least in terms of adding a `start` method to the Observer interface.

**Comment by blesh** [comment]
I'm closing this for now, because the es7 observable spec is a moving target that moves just a little too fast. I'm not sure which branch in the spec's repository current work is living in. As soon as @jhusain and @zenparsing let us know when things are settled down (stage 2 perhaps?), we'll try to match the spec. As it stands now, I think we're very close.

**Comment by zenparsing** [comment]
@blesh FYI I deleted all of those old branches on the es-observable repo.
