### ISSUE TITLE
UnsubscriptionErrors thrown in TestScheduling don't log anything useful.

### ISSUE THREAD

**Issue by blesh** [ReactiveX/rxjs#1534]
**RxJS version:** 5.0.0-beta.3

**Code to reproduce:**

This should do it:
```
let example = Observable.create(() => () => { throw 'bad' });
expectObservable(example).toBe('');
```

**Expected behavior:**
Respond with a test failure outlining all `errors` in the `errors` collection from the UnsubscriptionError thrown.

**Actual behavior:**
Test failures just show "UnsubscriptionError thrown" with no additional information.

**Additional information:**

**Comment by kwonoj** [comment]
I think this issue is now covered by #1591 and recent #1778 .
