### ISSUE TITLE
Error after upgrading to beta 3

### ISSUE THREAD

**Issue by zigzag95** [ReactiveX/rxjs#1540]
I get this error after upgrating to beta 2

Severity	Code	Description	Project	File	Line	Suppression State
Error	TS2436	Build: Ambient module declaration cannot specify relative module name.	node_modules\rxjs\add\observable\bindCallback.d.ts	2

**Comment by kwonoj** [comment]
What version of TypeScript compiler you're using?

**Comment by kwonoj** [comment]
From beta 3, RxJS requires typescript compiler version above 1.8.2 which supports module augmentation (https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#augmenting-globalmodule-scope-from-modules) for moduler operator patching strategy. If you're using lesser, please try with latest release of compiler.

**Comment by kwonoj** [comment]
@zigzag95 , I believe using latest compiler resolves issue you're experiencing, let me close issue. If you're still experiencing same, please reopen anytime to investigate this further.

**Comment by zigzag95** [comment]
Thank you and sorry because i missed your replies.

**Comment by kwonoj** [comment]
You're welcome anytime :)
