### ISSUE TITLE
Removal of the Pausable operator

### ISSUE THREAD

**Issue by hmillison** [ReactiveX/rxjs#1542]
Hello!

I am currently using Rx 4 to implement a multipart file uploading feature for my organization. I was hoping to ensure that our work would be fully compatible with Rx 5 when it is ready for use in production. I noticed in the Migration doc that one operator we are using, the `pausable` operator, won't be implemented in this version.

We're using the `pausable` operator to pause an Observable stream temporarily if the user loses internet connection and then allow them to resume the upload stream when they're ready. 

I'm interested in the reasoning for the removal of this operator. Should we switch to use something else to get the same functionality?

**Comment by blesh** [comment]
It's not been "removed" so much as it hasn't been added. This is mostly because all you need to replicate this functionality is a `switchMap` and `Observable.never`:

```
const source = getSomeSourceObservable();
const pauser = new Subject();

// All the magic is here
const pausable = pauser.switchMap(paused => paused ? Observable.never() : source);

pausable.subscription(x => console.log(x));

pauser.next(true);
```

**Comment by hmillison** [comment]
Thanks for the help @blesh. That's exactly what i was looking for!

**Comment by young-steveo** [comment]
@blesh What about `pausableBuffered`?  I'm still noob enough to not totally see a replacement.

**Comment by tom-mayer** [comment]
For me there is no subscription function on the pausable, so I don't quite get how this works. For example if I have an IntervalObservable that polls a web resource every 2s, would sending false the the pauser really halt the Obervable from polling or would it simply not notify the subscribers but still poll?

**Comment by tom-mayer** [comment]
Hey,

@blesh I stumbled upon a case in which pausable would be helpful which the upper example doesn't cover. In the upper example the subscriber would just stop to receive events from the source. Consider the source being an IntervalObserver that for example polls a web service on every tick and then publishes the results. With the upper code source would not publish results, but the observer would still poll the web service. If I understand the original pausable correctly, pausing would prevent the IntervalObserver itself from generating ticks, thus preventing the polling and not only the publish. 

In either case (even if the original implementation behaves like your example) I think it would be a valuable feature to actually be able to pause an observer.

**Comment by trxcllnt** [comment]
@tom-mayer yes, we should add this to our roadmap (PR's welcome of course!). @blesh should this be tagged blocking 5-oh release?

**Comment by blesh** [comment]
@trxcllnt adding new operators does not incur a major revision change, so no, I wouldn't block on this.

**Comment by jskrzypek** [comment]
@blesh @young-steveo 
I'm also pretty noob but I've taken a stab implementing the 
`pausableBuffered` observable, and it seems to work.
Check out the plunkr: https://plnkr.co/zwLlDmwQ5nL2jN3L31jk/

Here's the core of the javascript:

```js
var pauser = new Rx.Subject();
var source = new Rx.Subject();
/**
 * We need to use a subject subscribed to observable, 
 * otherwise we receive the interval from the 
 * beginning every time the `pausableBuffered` is 
 * toggled (instead of the currently emitted items)
 */
getObservableSomehow.subscribe(source);

var buffer = new Rx.Subject();
source
  .buffer(pauser)
  .concatMap(Rx.Observable.from)
  .subscribe(buffer);

var pausableBuffered = pauser.switchMap(function(paused) {
    return paused ? buffer : source;
  });
pausableBuffered.subscribe(function(x) {
    console.log('Next: ' + x.toString());
  });
```
The `buffer()` will close & emit its array
every time the `pauser` emits. We want to
emit the items from the array in order as fast as
possible. If we use `concatMap(Rx.Observable.from)`
we get this, though there might be a more succinct
way to do this that I'm not familiar with.

Instead of using the `buffer()` method presented
above, you can also use `bufferToggle()` like this:
```
  .bufferToggle(pauser, function (toggle) {
    return toggle ?  Rx.Observable.empty() : pauser;
  })
```

Using `bufferToggle()` may be more performant.
I'm not sure because I haven't inspected the 
implementation, but if it works like I think it
does, then using it would skip buffering emissions
while unpaused. It is more code, however. If the
`pausableBuffered` is going to be running unpaused
most of the time, then the perfomance gain will be 
negligible and the `buffer()` syntax is probably 
preferred.

**Comment by jskrzypek** [comment]
@tom-mayer

Couldn't you just use @blesh's implementation above to send the intervals to `Observable.empty()` before you do the polling? Of course it still could be a good idea to make Observables pausable.

**Comment by kidchenko** [comment]
Hi, I am using the "rxjs": "5.0.0-beta.6", and pausable.subscription(x => console.log(x)); not working for me, but pausable.subscribe works fine, 

More a question, when I am pause and continue, the value is restarted, there are some form to maintain the value?

My code is like this

```
ngOnInit() {
        this.pauser = new Subject();
        this.source = this.getSomeSourceObservable();
        
        const pausable = this.pauser.switchMap(paused => paused ? Observable.never() : this.source);
        pausable.subscribe(t => this.tickerFunc(t));
        
        this.pauser.next(false);
    }
    tickerFunc(tick){
        this.timer = moment().startOf('day').seconds(tick).format('mm:ss'); 
    }

    pause() {
        this.pauser.next(true);
    }

    resume() {
        this.pauser.next(false);
    } 
```

**Comment by jskrzypek** [comment]
If I understand what's going on correctly, this is by design since the source is an observable, instead of a [subject](http://reactivex.io/rxjs/manual/overview.html#subject). Each time your pauser is resumed,  it grabs a new subscription on the observable. Because the observable is unicast, each subscriber gets its own separate replay of the items from the observable. In order to maintain the state between `resume()` calls you should subscribe a subject to the source and listen to that. Something like this: 

```js
ngOnInit() {
        this.pauser = new Subject();
        this.source = new Subject();
        this.getSomeSourceObservable().subscribe(this.source);

        const pausable = this.pauser.switchMap(paused => paused ? Observable.never() : this.source);
        pausable.subscribe(t => this.tickerFunc(t));

        this.pauser.next(false);
    }
    tickerFunc(tick){
        this.timer = moment().startOf('day').seconds(tick).format('mm:ss'); 
    }

    pause() {
        this.pauser.next(true);
    }

    resume() {
        this.pauser.next(false);
    } 
```

**Comment by kidchenko** [comment]
I am trying to make a reactive countdown.

**Comment by Pythic** [comment]
@kidchenko Did you ever manage to get this working?

**Comment by bfricka** [comment]
Is there any plan on implementing this? `pausable` already had slight overhead due to having to push to a subject, but it's certainly better than implementing from scratch each time.

**Comment by EvanWillms** [comment]
I had need of a pausableBuffered operator and have assembled the mixin below.  This conceptually matches the [RX PausableBuffer pattern](http://rxmarbles.com/#pausableBuffered), but is not yet a drop-in replacement for the [RxJS 4 pausableBuffer](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/pausablebuffered.md) because it has not implemented `pause()` and `resume()` on the returned observable.

Demo running at https://jsfiddle.net/ofn7qzmv/

```
Rx.Observable.prototype.pausableBuffered = function pausableBuffered(pauser) {
  const source = this
  const output = new Rx.Subject();
  const sourceComplete = Rx.Observable.create(function(observer) {
    observer.next(false)
    source.subscribe({
      complete: _ => {
        observer.next(true)
        observer.complete()
      }
    })
  })

  const initializedPauser = Rx.Observable.merge(
    Rx.Observable.of(false),
    pauser,
    sourceComplete
  )
  const endPauseSignal = initializedPauser
    .filter(x => !x)
    .distinctUntilChanged()

  const passthrough = initializedPauser
    .switchMap(paused => paused ? Rx.Observable.never() : source)
  const bufferableEvents = initializedPauser
    .switchMap(paused => paused ? source : Rx.Observable.never())

  const buffered = new Rx.Subject()
  bufferableEvents
    .buffer(initializedPauser)
    .subscribe(arr => arr.forEach(val => buffered.next(val)))

  const bufferedOutput = Rx.Observable.merge(
    passthrough,
    buffered
  )

  // Becuase Rx.Observable.never doesn't complete, the resulting merge
  // will not either
  sourceComplete
    .switchMap(complete => complete ? Rx.Observable.empty() : bufferedOutput)
    .subscribe(output)

  return output
}
```

**Comment by MikeDabrowski** [comment]
Hey, I got a slight problem with this approach.

I implemented spaseships game in angular based on code from the book Reactive Programming with RxJS by Sergi Mansilla

No I want to improve the game by adding pause menu. So i added it as follows:

```
const game$ = Observable.combineLatest(
      this.starsService.starStream$(),
      this.heroService.Spaceship$(this.canvasRef.nativeElement),
      this.enemiesService.Enemies$(),
      this.heroService.HeroShots$(this.canvasRef.nativeElement),
      Score, (stars, spaceship, enemies, heroShots, score) => ({
        stars, spaceship, enemies, heroShots, score
      }))
      .sampleTime(GameOptions.SPEED)
      .takeWhile(actors => this.helpersService.gameOver(actors.spaceship, actors.enemies) === false);

    this.pauser.switchMap(paused => paused ? Observable.empty() : game$)
      .subscribe(render, error, complete);
    this.pauser.next(false);
  }
```
```
starStream$() {
    return Observable.range(1, GameOptions.STAR_NUMBER)
      .map(() => ({
          x: parseInt((Math.random() * GameOptions.CANVAS_WIDTH).toString(), 10),
          y: parseInt((Math.random() * GameOptions.CANVAS_HEIGHT).toString(), 10),
          size: Math.random() * 3 + 1
        }))
      .toArray()
      .flatMap(stars => Observable.interval(GameOptions.SPEED)
        .map(() => {
          console.log(GameOptions.STAR_NUMBER);
          stars.forEach(star => {
            if (star.y >= GameOptions.CANVAS_HEIGHT) {
              star.y = 0;
            }
            star.y += star.size;
          });
          return stars;
        })
      );
  }
```

It works fine for spaceships and shots, but doubles stars number each pause/start cycle.
I then went on and used publishReplay(1) and connect on game$, which solves stars problem  and doubles spaceships and shots now.

Can anyone point me in the right direction?
