### ISSUE TITLE
Re enable browser test

### ISSUE THREAD

**Issue by kwonoj** [ReactiveX/rxjs#1549]
**RxJS version:**
master

**Code to reproduce:**
`npm run test_karma`

**Additional information:**
After migration of test cases into mocha test runner via https://github.com/ReactiveX/rxjs/pull/1545, current browser based test configurations are not working correctly. I've tried couple of ideas but it wasn't quick & easy with local custom interfaces. This issue is track down effort to update configurations, along with any PR / suggestions around.

**Comment by staltz** [comment]
Good tools in general (not sure how they fair with local custom interfaces): testem, zuul.

**Comment by kwonoj** [comment]
I tried testem yesterday bit but no luck (assume my configuration's not correct?). Need bit more investigation especially how to coordinate custom interfaces.

**Comment by blesh** [comment]
I thought karma had mocha integration or at least some sort of support.

**Comment by kwonoj** [comment]
Yes it is, issues about dealing with local custom interface with `karma-mocha` plugin. I'm looking possibilities on several ways for now, hope it could be done via karma.

**Comment by kwonoj** [comment]
Existence of custom interface makes this really touch task. I'm still trying to find feasible solutions but so far no luck.
