### ISSUE TITLE
Add simple imports for observable creation methods

### ISSUE THREAD

**Issue by blesh** [ReactiveX/rxjs#1554]
### Problem

Currently when you want to use a creation method in an ad-hoc way, you need to import the type of Observable, then use it's static `create` method or new it up directly.

This poses two problems:

1. You have to know the name of the observable: `rxjs/observable/FromObservable` for example
2. It makes using it ugly:

```js
import { FromObservable } from 'rxjs/observable/FromObservable';
const from = FromObservable.create;

from([1,2,3]).subscribe(console.log.bind(console));
```

### Solution

Add *additional* files next to the observable files that export the `create` methods under a more useful name:

eg:

src/observable/from.ts
```TypeScript
import { FromObservable } from './FromObservable';

export const from = FromObservable.create;
```

src/observable/never.ts
```TypeScript
import { NeverObservable } from './NeverObservable';

export const never = NeverObservable.create;
```

etc.

That means that using these in an ad hoc way would be as simple as:

```js
import { from } from 'rxjs/observable/from'; //LOL: from from from

from([1, 2, 3]).subscribe(console.log.bind(console));
```

**Comment by staltz** [comment]
How do you suggest to import `throw`?

**Comment by blesh** [comment]
@staltz right now it's `import { _throw } from XXX` same for `_do`, `_finally` and `_catch`.
