### ISSUE TITLE
Type definition claims missing property?

### ISSUE THREAD

**Issue by kwonoj** [ReactiveX/rxjs#1568]
**RxJS version:**
master

**Code to reproduce:**
```js
///<reference path="./typings/main/ambient/es6-shim/index.d.ts" />
///<reference path="./spec/es5.d.ts" />

import * as Rx from '.dist/cjs/Rx';

Rx.Observable.of(1).subscribe(_ => {
  console.log(_);
});
```

**Actual behavior:**
`../RxJS/dist/cjs/Observable.d.ts(11,13): error TS2339: Property 'observable' does not exist on type 'SymbolConstructor'.`

**Additional information:**
tsconfig.json
```
{
  "compilerOptions": {
    "removeComments": false,
    "preserveConstEnums": true,
    "sourceMap": true,
    "declaration": true,
    "target": "es5",
    "module": "commonjs"
  },

  "files":["index.ts"]
}
```

Maybe I'm missing something essential after having es5 declarations, @david-driscoll - would you mind to point out what I did missing?

**Comment by david-driscoll** [comment]
That is really weird, I'm seeing it too.... it's not picking up https://github.com/ReactiveX/rxjs/blob/master/src/symbol/symbol.d.ts for some reason.... must be the compiled output... I'll dig in tonight.

**Comment by david-driscoll** [comment]
interesting in `dist/cjs/symbole` there is `/// <reference path="../src/symbol/symbol.d.ts" />
which is wrong...  I guess probably the only way to fix it up is part of the post build steps (where package.json is dropped in, etc).

Does that sound like a decent solution?

**Comment by kwonoj** [comment]
isn't it because of ambient referencing in original code (observable.ts)?

**Comment by david-driscoll** [comment]
It gets stranger... it's gotta be a bug in the TypeScript code, but I have a one line fix that appears to the solve the problem.

**Comment by kwonoj** [comment]
Closed via https://github.com/ReactiveX/rxjs/pull/1569.

**Comment by kwonoj** [comment]
@david-driscoll , reopened this issue by update with latest beta https://github.com/ReactiveX/rxjs/pull/1569#issuecomment-205857392 . Seems ambient type import is not way to go.

**Comment by kwonoj** [comment]
re-closing this issue by https://github.com/ReactiveX/rxjs/pull/1582. To try out this with npm package, may need next version publish though.
