### ISSUE TITLE
Observable.merge does not work as expected

### ISSUE THREAD

**Issue by SuperManitu** [ReactiveX/rxjs#1576]
Hi,
I have that code:
```typescript
dates.flatMap<T>(t => {
    console.log(new Date(t));
    return Observable.merge(
        streams[1]
        .map(e => { console.log(new Date(t), e.ProbeDate); return e; })
        .filter(element => {
            //console.log(new Date(t), element);
            return key(element) === t;
        }),
        Observable.of(defaultValue(t))
    )
    .first<T>();
}).subscribe(a => {});
```
But the console output is confusing me, first I get (near others) `Thu Mar 31 2016 17:40:12 GMT+0200`, which means that the date I'm searching for is indeed queried. But then, the only dates that I get with the second console.log are `Thu Mar 31 2016 17:35:59 GMT+0200` and `Sat Apr 02 2016 15:00:28 GMT+0200` (as the first of the two logged dates).
Can someone explain that behavior to me?

**Comment by trxcllnt** [comment]
@supermanitu it's tough to discern your expectations of this code with such little context into your data. Could you be more specific about your problem, or come up with a simpler example?

**Comment by SuperManitu** [comment]
This code snippet is part of a new Observable operator i was going to propose. It's the operator I would need for my initial problem in #1560 .
’dates’ is a observable of distinct merged dates as unix timestamps. For each element of this Observable i want to look for a matching date in the input array (’streams’). If there is one, that is used, otherwhise a lamda for creating a default value is called.
I use this operator for visual representation, but in the second dataset (’streams[1]’) i get only the values matches that werent matched in the first stream, although the streams shouldnt know each other, and as stated before, the date that should be matched in the second stream too, is not.
I can post the complete code of the operator tomorrow, when im back at my pc.

**Comment by SuperManitu** [comment]
So, here is the complete operator:
```typescript
private mergeOn<T>(
        streams : Observable<T>[],
        key : (e : T) => any,
        defaultValue : (k : any) => T
    ) : Observable<T>[]
    {
        const merged : Observable<any> = Observable.from(streams, x => x)
        .flatMap<T>(obs => obs)
        .distinct((x, y) => key(x) === key(y))
        .map<any>(element => key(element));

        //This is only for debugging
        if (streams.length > 1)
        {
            merged.flatMap<T>(t => {
                console.log(new Date(t));
                return Observable.merge(
                    streams[1]
                    .map(e => { console.log(new Date(t), e.ProbeDate); return e; })
                    .filter(element => {
                        //console.log(new Date(t), element);
                        return key(element) === t;
                    }),
                    Observable.of(defaultValue(t))
                )
                .first<T>();
            }).subscribe(a => {});
        }

        return streams.map(stream => {
            return merged.flatMap<T>(t => {
                return Observable.merge(
                    stream.filter(element => key(element) === t),
                    Observable.of(defaultValue(t))
                )
                .first<T>();
            });
        });
    }
```

**Comment by blesh** [comment]
@SuperManitu, can you come up with a concise example of how `merge` doesn't work as expected? That is, an example that only has the merge operator in it showing the unwanted behavior?

**Comment by SuperManitu** [comment]
@blesh I think this is the shortest working example I can get, it doesnt produce any console output (but it should): https://plnkr.co/edit/xFTvpHcGdFQxzTD77aFa?p=preview

**Comment by roganov** [comment]
@SuperManitu
It does produce 'Hello', but if you expected the line ` { console.log(new Date(t), e); return e; }` to also execute, you are not correct.
You have `.first()` on the `Observable.merge(..., Observable.of(defaultValue(t))).first()` which in your case is equvalent to just  `Observable.of(defaultValue(t))`.

**Comment by SuperManitu** [comment]
@roganov is there another way for the matching with default value? I tried isEmpty, but that doesn't seem to work either

**Comment by SuperManitu** [comment]
THis is the isEmpty version. Why is that not working? Why am I not getting any output?
```typescript
private mergeOn<T>(
        streams : Observable<T>[],
        key : (e : T) => any,
        defaultValue : (key : any) => T
    ) : Observable<T>[]
    {
        const merged : Observable<any> = Observable.from(streams, x => x)
        .flatMap<T>(obs => obs)
        .map<any>(element => key(element))
        .debounceTime(10);

        return streams.map(stream => {
            return merged
            .flatMap<T>(k => {
                const filtered : Observable<T> = stream.filter(e => e === k);

                return filtered
                .isEmpty().map(t => {console.log(t); return t})
                .flatMap<T>(empty => empty ? Observable.of(defaultValue(k)) : filtered);
            });
        });
    }
```

**Comment by blesh** [comment]
I'm sorry, @SuperManitu, I still can't discern what you're saying is wrong with merging.

Can you put together an example, that *only uses the operator you're saying doesn't as expected*, that shows the unwanted or confusing behavior?

Then, from there, you should write down the _expected_ behavior, and the _actual_ behavior.

In fact, I think maybe we can just start this issue over. **Can you file a new issue and use the issue template provided?** I think that will help provide more context so we can help. Be sure to keep the example as minimal as possible.

I'm sorry if this is frustrating for you, I want to help, but I'm not sure what you're asking for here.

**Comment by trxcllnt** [comment]
@supermanitu I can't tell for sure, but it seems like you might want to use `distinctUntilChanged`, `defaultIfEmpty`, and `groupBy` together.

**Comment by SuperManitu** [comment]
@trxcllnt defaultIfEmpty is exactly what I need, but it seems that it's not working with filter and a hot observable (see here: https://plnkr.co/edit/p2sjZP4f50eg0bRhoeYM?p=preview )
I should get always an "a" and then either a "b" or a "c". But I only get "a". In my project I get with the actual data and the same code the "a"s and the "b"s, but never the "c"s.
