### ISSUE TITLE
Compose subscriptions in single operation

### ISSUE THREAD

**Issue by matthewwithanm** [ReactiveX/rxjs#1583]
Small feature request:

I'd like a way to compose multiple subscriptions in a single operation. Something like `Subscription.create(...subscriptions: Array<Subscription>): Subscription`. (I'm assuming that the constructor doesn't do this for perf reasons, so supporting var-args in `add` would be my second choice.)

If this is something that would be merged, I can put together a PR.

**Comment by kwonoj** [comment]
I'm not sure if I understood correctly (please point me if I'm wrong), is this means flowwise similar as below? (pseudo, course)

```js
const existingSubs:Array<Subscription> = [....];
const sub = new Subscription();

existingSubs.forEach(x => sub.add(x));
```

**Comment by matthewwithanm** [comment]
Yup! Just a way to do that with a single expression/function call.

**Comment by kwonoj** [comment]
I'd consider this could be achieved relatively short code externally, without introducing additional interface to subscription. Would you able to elaborate use case bit more?

**Comment by matthewwithanm** [comment]
Yes, this is definitely a convenience. For use cases, you can check out how we use Atom/event-kit's `CompositeDisposable` in [Nuclide](https://github.com/facebook/nuclide). Basically, we create a composite subscription at the same time as subscribe and then treat it as essentially immutable:

```js
new CompositeDisposable(
  a.subscribe(...),
  b.subscribe(...),
  c.subscribe(...),
);
```

Often, this is used as an argument to another function, e.g.

```js
atom.commands.add(
  new CompositeDisposable(
    ...
  ),
);
```

It's certainly possible to do this by iterating over a list of subscriptions and adding them, but not nearly as elegant.

At first I thought that I could achieve something similar by chaining `.add()` calls but now I see that that interface isn't actually fluent (i.e. if I do `a.add(b).add(c)` and unsub `b`, it'll unsubscribe `c` too).

**Comment by kwonoj** [comment]
I will not conclude this by myself and would like to wait other suggestions as well - as implementation itself is somewhat trivial only concern I'm having is api surface to `Subscription` where I'd prefer minimum surface as much.

**Comment by blesh** [comment]
### Current possible solutions

Technically, right now you could do `subscription.add(sub1).add(sub2).add(sub3)`. But that's less than ideal, I suppose. Because you'd be making `sub2` a descendant of `sub1`.

Also, right now you could do this: `new Subscription(() => [sub1, sub2, sub3].forEach(x => x.unsubscribe()))`

### Proposal

We could have `new Subscription` optionally accept functions or subscriptions in rest args.

```js
new Subscription(someUnsubFunc, subscription1, subscription2);
```

The risk here is that Subscription becomes too polymorphic and it negatively impacts performance. Another risk is that the implementation inefficiently allocates an array or other resources before it has to.

**Comment by matthewwithanm** [comment]
> But that's less than ideal, I suppose. Because you'd be making sub2 a descendant of sub1.

Yeah, this was actually the source of a pretty nasty bug of mine! I had assumed that `a.sub(b)` was equivalent to `a.sub(() => { b.unsubscribe(); })`. Oops!

The constructor option would definitely be the least surprising API IMO but like I mentioned in the OP, `add` would be alright. You could avoid the unnecessary array allocation (without accessing `arguments` which I guess has its own optimization issues) by adding an `isArray` check to `add`. `new Subscription().add([a.subscribe(), b.subscribe(), c.subscribe()])` is definitely not as appealing though and I guess you'd be throwing away the original subscription too, which also makes this a surprising API. Of course a new static is always an option, e.g. mirroring ES6 Arrays with `Subscription.of()`.

**Comment by BrainCrumbz** [comment]
Before going to ask in the [wild](http://stackoverflow.com/), I thought to quickly try here. Sorry if this is a little bit off-topic.

Does anyone know how to _extend_ `Subscription` TypeScript class (_extend_ as in adding a method to JS `prototype`, or as in defining a C# extension method) with a new method? We'd like to write code like this:

```typescript
let rootSubscription = new Subscription();

someObservable$
  .subscribe(someValue => doSomething(someValue))
  .addTo(rootSubscription);

anotherObservable$
  .subscribe(anotherValue => doSomethingElse(anotherValue))
  .addTo(rootSubscription);
```

`addTo()` _extended_ method would be something like this:

```typescript
function addTo(
    collectorSub: Subscription, // this is the explicit parameter
    thisSub: Subscription  // this is the "implicit" instance
  ): void {
  collectorSub.add(thisSub);
}
```

Thanks, and sorry again for temporarily diverting this issue.

**Comment by blesh** [comment]
closing this as inactive. Feel free to reopen if needed.
