### ISSUE TITLE
beta.5 Observable typings are missing 

### ISSUE THREAD

**Issue by micaelmbagira** [ReactiveX/rxjs#1584]
**RxJS version:**
5.0.0-beta.5

**Code to reproduce:**
Create a simple project using webpack

**Actual behavior:**
````
ERROR in webapp/node_modules/rxjs/Observable.d.ts
    (12,6): error TS2304: Cannot find name 'Symbol'.
    
    ERROR in webapp/node_modules/rxjs/Observable.d.ts
    (15,42): error TS2304: Cannot find name 'Iterable'.
    
    ERROR in webapp/node_modules/rxjs/Observable.d.ts
    (1,1): error TS2654: Exported external package typings file cannot contain tripleslash references. Please contact the package author to update the package definition.
````

**Additional information:**
Not happening if I roll back to beta.4

**Comment by kwonoj** [comment]
Thanks, it's related to https://github.com/ReactiveX/rxjs/issues/1568 and PR https://github.com/ReactiveX/rxjs/pull/1582 trying to resolve this issue.

**Comment by morocarlo** [comment]
+1

**Comment by andykais** [comment]
was having this same issue with `5.0.0-beta.2`, switching to `beta.4` until `beta.5` is fixed

**Comment by kwonoj** [comment]
Let me close this issue by https://github.com/ReactiveX/rxjs/pull/1582. To try out this with npm package, may need next version publish though. For now, I'd suggest to use b4 until next version published or directly use `master` branch if available. 

Apologies for troubles with new version, will think about more bulletproof way of test / verification per changes in further.

**Comment by neolwc** [comment]
+1

**Comment by kubosho** [comment]
I encountered this issue. RxJS version is `5.0.0-beta.4`.
My package.json & tsconfig.json is https://gist.github.com/kubosho/17b5016e4427726381051cf58efb6203#file-package-json
