### ISSUE TITLE
Have UnsubscriptionError log something nicer to console

### ISSUE THREAD

**Issue by blesh** [ReactiveX/rxjs#1590]
**RxJS version:** 5.0.0-beta.5

**Code to reproduce:**

```js
const source1 = Observable.create(() => () => { throw new Error('I am an error'); });
const source2 = Observable.timer(1000);
const source3 = Observable.create(() => () => { throw new Error('I am another error'); });
const source = source1.merge(source2, source3);

const subscription = source.subscribe();

subscription.unsubscribe();
```
**Expected behavior:**

Console logs out something readable to the effect of `UnsubscriptionError: 1) Error: I am an error 2) Error: I am another error`.

**Actual behavior:**

Console only logs out `UnsubscriptionError`. User is expect to catch it an analyze the `errors` property to glean information.

**Additional information:**

Ideally we could even link additional information about what an Unsubscription error is.

Important note for the example above. `source2` should still be torn down.

**Comment by blesh** [comment]
cc/ @juliemr for visibility and additional information or desires around this functionality.

**Comment by juliemr** [comment]
Thanks! The readable console log would be great, it would have sped up my recent debugging incident.
