### ISSUE TITLE
Suggestion: adopt task-based build system (such as gulp)

### ISSUE THREAD

**Issue by Igorbek** [ReactiveX/rxjs#1592]
I'm working on Windows (don't blame me, I like it) and it's ridiculously hard to work with npm commands that are using bash. All my attempts to make these more Windows-friendly have failed. I couldn't work efficiently before I've configured more comprehensive build system.
So my suggestion is to add (or replace existing with) gulp-based build system, that would especially be extremely helpful for development time.

Here's what I've done for myself:
```js
// gulpfile.js
var gulp = require('gulp');
var ts = require('gulp-typescript');
var merge = require('merge');
var sourcemaps = require('gulp-sourcemaps');
var concat = require('gulp-concat');

var es6Project = ts({
  noImplicitAny: true,
  outDir: 'dist/es6',
  module: 'es2015',
  target: 'es6',
  suppressImplicitAnyIndexErrors: true,
  declaration: true,
  diagnostics: true,
  pretty: true
});
gulp.task('compile_es6', function () {
  var tsResult = gulp.src('src/**/*.ts')
    .pipe(sourcemaps.init())
    .pipe(es6Project);
  return merge([
    tsResult.js
      .pipe(sourcemaps.write())
      .pipe(gulp.dest('dist/es6')),
    tsResult.dts.pipe(gulp.dest('dist/es6'))
  ]);
});

var cjsProject = ts({
  noImplicitAny: true,
  outDir: 'dist/cjs',
  module: 'commonjs',
  target: 'es5',
  suppressImplicitAnyIndexErrors: true,
  declaration: true,
  diagnostics: true,
  pretty: true
});
gulp.task('compile_cjs', function () {
  var tsResult = gulp.src([
    'typings/main/ambient/es6-shim/index.d.ts',
    'spec/es5.d.ts',
    'src/**/*.ts'])
    .pipe(sourcemaps.init())
    .pipe(cjsProject);
  return merge([
    tsResult.js
      .pipe(sourcemaps.write())
      .pipe(gulp.dest('dist/cjs')),
    tsResult.dts.pipe(gulp.dest('dist/cjs'))
  ]);
});

var amdProject = ts({
  noImplicitAny: true,
  outDir: 'dist/amd',
  module: 'amd',
  target: 'es5',
  suppressImplicitAnyIndexErrors: true,
  declaration: true,
  diagnostics: true,
  pretty: true
});
gulp.task('compile_amd', function () {
  var tsResult = gulp.src([
    'typings/main/ambient/es6-shim/index.d.ts',
    'spec/es5.d.ts',
    'src/**/*.ts'])
    .pipe(sourcemaps.init())
    .pipe(amdProject);
  return merge([
    tsResult.js
      .pipe(sourcemaps.write())
      .pipe(gulp.dest('dist/amd')),
    tsResult.dts.pipe(gulp.dest('dist/amd'))
  ]);
});

var specProject = ts.createProject('spec/tsconfig.json');
gulp.task('build_spec', function () {
  var tsResult = specProject.src()
    .pipe(ts(specProject));
  return tsResult.js.pipe(gulp.dest('spec-js'));
});

gulp.task('watch', ['compile_cjs', 'build_spec'], function () {
  gulp.watch('src/**/*.ts', ['compile_cjs']);
  gulp.watch('spec/**/*.ts', ['build_spec']);
});
```

I tried to align with existing commands in npm.
If you guys don't mind I can open PR as a start point.

**Comment by kwonoj** [comment]
I was thought about this bit while ago and actually becomes bit opposite recently. Having those kind of task runner requires additional effort to write / maintain in further, especially hitting edge cases makes it tough. I'm on Windows (and only) too, but I'm on vote for existing npm scripts. I have couple of thoughts for making it more Window friendly (such as introduce https://github.com/shelljs/shx once published) but it's based on npm still.

**Comment by kwonoj** [comment]
Just additional off-topic, Bash on W10 in next update would make windows more script friendly, possibly can resolve some of chruns windows users having. I'm on msys2 currently and it works well in general but it's sometimes not good.

**Comment by staltz** [comment]
Bash on Windows 10 (Microsoft itself is acknowledging Windows was not so good for development tools) or just install Linux on a virtual machine like with VirtualBox. It's free, doesn't take much of your time, and works. But gulp... no thanks, I've been there, don't want to go back.

**Comment by Igorbek** [comment]
Oh, didn't expect you would be so strongly against it. Ok, I'll be using it for myself only. Just curious, as an off-topic, why are you guys prefer npm over gulp?

**Comment by kwonoj** [comment]
It's not strong objection, just prefer over npm script and does not have strong benefits to move over :) For me, grunt / gulp or any other task runner, it requires additional effort to make task runner working, while npm's just script invocation in general as I commented above. Especially, I've hit couple of edge cases that current plugin doesn't supports certain scenarios, then it makes quite hard to make another choices after.

**Comment by Igorbek** [comment]
Oh, they work from command line as well. Just `gulp compile_es6` or `gulp watch` and that's it. It also perfectly integrates with IDEs such as `vscode`. I really couldn't move forward in contribution to Rx without that gulp configured.

**Comment by kwonoj** [comment]
What I'm saying is not about how to use, internals of how to compose each task. Running command is not a matter to me.

**Comment by kwonoj** [comment]
I'll leave this opened bit more to hear additional suggestion to conclude. For now, I'd like to suggest to include gulp config into `gitignore` to allow manage it separately.

**Comment by kwonoj** [comment]
@Igorbek , let me close this issue and track this effort via https://github.com/ReactiveX/rxjs/issues/1601. I'm all for script should be windows compatible as much, but for now do not see compelling reason to move everything forward to specific task runner. As I have plan to use cross-platform *nix command implementation (https://github.com/shelljs/shx), I'll update current script accordingly once those are published into npm packages. Only thing blocking it currently is it's yet published. 

Hope this doesn't disappoint you much, I promise to improve current script as fast as I can.
