### ISSUE TITLE
Observabke.d.ts - Illegal triple slash, Can not find "Symbol", cannot find "Iterable"

### ISSUE THREAD

**Issue by Son-Lam** [ReactiveX/rxjs#1595]
**RxJS version: 5.0.0beta.5

**Code to reproduce:**
build ng2-material 0.2.13
**Expected behavior:**
Should not produce error
**Actual behavior:**
/home/son-sparq/workspace/sparqapp/node_modules/rxjs/Observable.d.ts(1,1): error TS2654: Exported external package typings file cannot contain tripleslash references. Please contact the package author to update the package definition.
/home/son-sparq/workspace/sparqapp/node_modules/rxjs/Observable.d.ts(12,6): error TS2304: Cannot find name 'Symbol'.
/home/son-sparq/workspace/sparqapp/node_modules/rxjs/Observable.d.ts(15,42): error TS2304: Cannot find name 'Iterable'.
**Additional information:**

**Comment by kwonoj** [comment]
Please refer https://github.com/ReactiveX/rxjs/issues/1584, https://github.com/ReactiveX/rxjs/issues/1568 and PR https://github.com/ReactiveX/rxjs/pull/1582 resolves this. Apologize for inconvenience, fix is planned to be published next version.

**Comment by kwonoj** [comment]
Forgot to mention this :) until new version's published, please use beta.4 for immediate solution.
