### ISSUE TITLE
Obserable Create methods docs and overview missing

### ISSUE THREAD

**Issue by SteveALee** [ReactiveX/rxjs#1602]
**RxJS version: Master branch

**Code to reproduce: n/a

**Expected behavior: n/a

**Actual behavior: n/a

**Additional information:**
Looking for the creation methods in the docs I found only a reference in [observable.md](https://github.com/ReactiveX/rxjs/blob/master/doc/observable.md) to **Creation Methods** fragment in overview.md. That appears to be missing.

**Comment by staltz** [comment]
Mmm, I don't think it's missing: file:///Users/amed/Development/RxJSNext/tmp/docs/manual/overview.html#creation-operators

**Comment by SteveALee** [comment]
I was looking here in github  https://github.com/ReactiveX/rxjs/tree/master/doc. No overview.md there.  I guess I'm miss understanding the docs generation process.

**Comment by staltz** [comment]
https://github.com/ReactiveX/rxjs/pull/1607

**Comment by SteveALee** [comment]
OK :)
