### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by omerts** [ReactiveX/rxjs#1606]
**RxJS version:**
@reactivex/rxjs@5.0.0-beta.5

**Code to reproduce:**
npm install @reactivex/rxjs

**Expected behavior:**
installation success

**Actual behavior:**
```
npm ERR! @reactivex/rxjs@5.0.0-beta.5 install: `typings install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @reactivex/rxjs@5.0.0-beta.5 install script 'typings install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @reactivex/rxjs package,
```

**Additional information:** Windows machine

**Comment by kwonoj** [comment]
Related with https://github.com/ReactiveX/rxjs/issues/1580,  current repo takes it back but need to wait for next version publish. Please use b.4 for immediate resolution.
