### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#161]
RxJS 2 has the idea of configuration via a namespace: `Rx.config`. so you can do `Rx.config.Promise = MySuperSweetPromiseImpl` if you so choose.

I've played with having an ES6 `config` module that I can import to each file that requires configuration, and I can attach to the global export... but TypeScript didn't seem to like exporting an object literal as default.

... perhaps there's another way.

this seems like an easy problem to solve, it's just not a high priority ATM.

**Comment by trxcllnt** [comment]
@blesh .@steveorsomethin et. al. have a pattern they call *functor modules*. Essentially, all their modules are factory functions, that when invoked, return the contents of the module. Instead of using import/require, the functor accepts the dependencies as arguments.

Here's an example of the [Rx](https://github.com/ReactiveX/RxJS/blob/master/src/Rx.ts) module implemented this way:

```es6
// Rx.ts
import ObserverFactory from './Observer';
import OperatorFactory from './Operator';
import ObservableFactory from './Observable';
import SubscriberFactory from './Subscriber';
import SubscriptionFactory from './Subscription';

import noop from './util/noop';
import throwError from './util/throwError';
import tryOrOnError from './util/tryOrOnError';

export default function RxFactory({
  Promise,
  setTimeout, clearTimeout,
  setInterval, clearInterval,
  $$observer
}) {
  const Observer = ObserverFactory({ noop, throwError, tryOrOnError });
  const Subscription = SubscriptionFactory();
  const Operator = OperatorFactory({ Observer, Subscription });
  const Subscriber = SubscriberFactory({ noop, throwError, tryOrOnError, Observer, Subscription });
  const Observable = ObservableFactory({ Promise, Operator, $$observer, Observer, Subscriber, Subscription });

  return { Observer, Subscription, Operator, Observable };
}
```
```es6
// index.js for node/CommonJS
var Rx = require('./Rx');
module.exports = Rx({
  Promise,
  setTimeout, clearTimeout,
  setInterval, clearInterval,
  $$observer: Symbol.observer });
```

**Comment by blesh** [comment]
@trxcllnt ... I don't dislike this, but it would diverge drastically from the current common pattern. Not so bad, but it would mean the onus would be on the end-user-author to maintain the "namespace" they've created with the `Rx` function you're proposing. It may not be ergonomic.

I'm not against it, I'm just not sure I'm *for* it.

I think the implied counter-proposal is to examine global state for an `Rx.config` object, as is the status quo. However, I'm not sure that's too great going forward either.

**Comment by trxcllnt** [comment]
@blesh the exported Rx factory function would itself be initialized with defaults, so the end-user wouldn't have to call it, but I agree that it's a departure from existing patterns (dependency injection vs. service location).

**Comment by steveorsomethin** [comment]
Well, clearly it should be a common pattern :)

My original motivation was to parameterize my modules for trivial testing/library replacement/de-duping without a ton of weird require/context hacks. Also, sync/async becomes an implementation detail external to the actual modules.

The same concept exists in OCaml, which is so hot right now:

https://realworldocaml.org/v1/en/html/functors.html

**Comment by blesh** [comment]
For now, I've added the global configuration, since I think we can support both at a later time.
