### ISSUE TITLE
docs(operators): All the operator links are broken.

### ISSUE THREAD

**Issue by jisaacks** [ReactiveX/rxjs#1613]
Not sure, if this counts as a bug so if this is the wrong place to post this, I apologize. 

All the links here are broken: https://github.com/ReactiveX/rxjs/blob/master/doc/operators.md#creation-operators

Not sure if that is something y'all are aware of.

**Comment by kwonoj** [comment]
Actually it is not, https://github.com/ReactiveX/rxjs/pull/1607 just created to instruct `doc` is for publishing document into http://reactivex.io/rxjs/ .

**Comment by jisaacks** [comment]
@kwonoj ah got it. Thanks

**Comment by kwonoj** [comment]
Appreciate for catching this! @staltz was just about couple of day faster for those PR :)
