### ISSUE TITLE
Why no index or observable arguments in scan's accumulator?

### ISSUE THREAD

**Issue by rickmed** [ReactiveX/rxjs#1614]
Sorry if this kind of question is out of place or out of format.

**Comment by kwonoj** [comment]
I don't recall why `index` is missing, but in general in RxJS 5 passing `source` observable is dropped by it doesn't have much use cases in general. It'd be appreciate if you can elaborate bit more if you'd like to have it, or else. 

In case of `index`, it can be easily retrieved via accumulator of `scan`, something like

```js
Rx.Observable.of('a','b','c','d').scan((acc, value) => {
  acc.idx++;
  acc.value = value;
  return acc;
}, { idx : -1, value: null }).subscribe(x => {
  console.log(`index: ${x.idx}, value: ${x.value}`);
});
```

(just wrote in a hurry only for pseudo purpose)

**Comment by rickmed** [comment]
@kwonoj I ended doing something like that in my case but it felt forced. I understand the dropped of observable but all (most?) of the operators with selector functions have an index argument, no?

**Comment by kwonoj** [comment]
Most of operators requiring `predicate` passes its index, yes. Some of resultSelectors are not while. For this one I don't have exact answers though. /cc @blesh

**Comment by staltz** [comment]
I believe we could add at least the index without any negative impact. Should be there IMO.

**Comment by kwonoj** [comment]
I agree it can be added, just curious if there was reason to not to.
