### ISSUE TITLE
BehaviorSubject.getValue() after completion

### ISSUE THREAD

**Issue by matthewwithanm** [ReactiveX/rxjs#1620]
**RxJS version:** 5.0.0-beta.6

**Code to reproduce:**

```js
const s = new BehaviorSubject(1);
s.complete();
s.getValue();
```

**Expected behavior:**

In v4, the equivalent code would output `1`.

**Actual behavior:**

`ObjectUnsubscribedError`

**Additional information:**

Is this expected behavior with Rx 5?

**Comment by kwonoj** [comment]
in RxJS 5 it's expected to not allow get value from unsubscribed / completed subject (https://github.com/ReactiveX/rxjs/blob/815f775346a4295f7906635060acaf34543af99f/spec/subjects/BehaviorSubject-spec.ts#L25)

**Comment by matthewwithanm** [comment]
Sorry, why is this desirable? The previous behavior had promise-like semantics (subscribing before or after resolution/completion gave the same result). With the new behavior, it seems like you need to use promises (and you need to convert to a promise before completion) in order to get that.
