### ISSUE TITLE
Proposal: `do` optional async blocking behavior

### ISSUE THREAD

**Issue by blesh** [ReactiveX/rxjs#1622]
### Problem

Currently if you want to model sequence processing with Rx, and you want to create some async side effect and wait for it to complete, you end up needing to use `flatMap` (`mergeMap`) to do so, even though it's only a side effect.

```js
source.map(x => x + x)
  // the x => x below is to send along the original value no matter what
  .flatMap(x => asyncSideEffect(x), x => x)
  // ... more here
```

I've been asked a few times "what if I want to do some async side effect, then what?" and I always tell people to use `flatMap` and the next question is "Is that okay?".

Since we have a distinguished line between `map` and `do`, I think it might be good to have a line between `flatMap` and `???`. I think that `???` could just be `do`.

### Proposal

Have `do` callbacks accept optional async type returns. This would mean if a callback from `do` or an observer passed to `do` returned a `Promise`, or `Observable`, it would then wait for that to resolve or complete before sending the original value down the observable chain.

That means the above would just be:

```js
source.map(x => x)
   .do(x => asyncSideEffect(x))
```

### Risks

Right now we don't really have the `Observer` interface returning anything. It's just returning `void` from the methods. However, I think that @zenparsing's spec *does* have `next`, `error` and `complete` returning values. This could be a use case for those values.

### Other Proposal

We add a `doAsync`, `block` or `blockUntil` or some such operator that is used for side effects, that would be the same thing. I like this idea less, because it's yet another operator.

**Comment by Dorus** [comment]
I'm not against this idea, it sounds reasonable to me, but i got some ideas/additions.

While a `Promise` is (usually) guaranteed to complete, an `Observable` is not. Also, you need to decide on waiting for the first element, last element, or `Completed` from the `Observable`.

Wouldn't it be a better idea to just use `.delay` in this case? I have some doubts about adding side effects in `delay`, but if the only side effect you want to communicate is the delay, that should be fine.

Lastly, also keep in mind that `flatMap()` can reorder elements, while `do` does not.

**Comment by staltz** [comment]
I'd prefer `doAsync` over `do`. One of the reasons I like `do` is that when reading it you are guaranteed that the output will be identical to the input, besides the fact a side effect is happening. Doing this:

> This would mean if a callback from do or an observer passed to do returned a Promise, or Observable, it would then wait for that to resolve or complete before sending the original value down the observable chain.

Would mean the output Observable is not anymore identical to the input Observable because the time of emission of `next` values may be substantially different.

Another names I would consider for the new operator: `mergeDo` and `switchDo` and `concatDo`. Think about it, once you add an async operation, you should also be able to tell how to handle concurrency and whether to cancel previous operations, like `switchMap` does. It would also make it easier to understand these new operators, since the comparison between `map` and `do` could be extended to `mergeMap` and `mergeDo`.

**Comment by david-driscoll** [comment]
What about a different synonym for `do`?  `determine` or `undertake` both imply something should happen first.

Taking grammar away, I'm in favor of @staltz's `mergeDo`, `switchDo`, etc.

I feel like the naming and behavior might be confusing at first, but it's essentially an alias for `.mergeMap(x => Observable.timer(1000), (x, y) => x)`

**Comment by mattpodwysocki** [comment]
👎 to this as our surface area is already too large and confusing. If they simply want side effects with their chaining strategy, use the right chaining mechanism and ensure you're returning the same input (or modified/side effected input).

**Comment by Dorus** [comment]
Building this from existing operators isn't hard:

`mergeDo(selector)` = `mergeMap(mergeDo, x => x)`
`concatDo(selector)` = `concatMap(selector, x => x)`
`switchDo(selector)` = `switchMap(selector, x => x)`

I'm making good use of the `resultSelector: function(outerValue: T, innerValue: I, outerIndex: number, innerIndex: number): any)` here.

**Comment by blesh** [comment]
Okay. I think we'll just leave it as-is. Thanks for the feedback everyone!
