### ISSUE TITLE
Can't install rxjs@5.0.0-beta.6 via npm

### ISSUE THREAD

**Issue by drager** [ReactiveX/rxjs#1623]
Hey, I'm having some trouble getting `rxjs@5.0.0-beta.6` installed.

Running the commands: `npm install @reactivex/rxjs@5.0.0-beta.6` or `npm install @reactivex/rxjs` gives me the following error: `npm ERR! cb() never called!`. The same error occurs for `@reactivex/rxjs@5.0.0-beta.5` as well.

`@reactivex/rxjs@5.0.0-beta.4` works just fine though.

**RxJS version:** 5.0.0-beta.6

**Node version:** v5.9.1

**Npm version:** v3.8.6

I'm running Ubuntu 15.10.

Thanks!

**Comment by kwonoj** [comment]
I just tried windows (npm 3.8.7) and linux (npm 3.8.3) and both of them installs b6 without problem. Would you mind to share npm log bit in detail?

**Comment by blesh** [comment]
@drager check your npm version. I think npm v2 has some issues installing namespaced packages from time to time. I know that's a bit hand-wavey... but if you're on npm v2, updating npm to v3 might solve your issue.

**Comment by drager** [comment]
@kwonoj: Hmm, not getting any npm-debug.log...

@blesh: I'm using node v5.9.1 and npm v3.8.6

**Comment by kwonoj** [comment]
@drager what does console output says?

**Comment by drager** [comment]
@kwonoj: Just `npm ERR! cb() never called!`

**Comment by kwonoj** [comment]
I wish I could provide additional triage but given message's so generic, it's really hard to tell what's happening. 

I'd like to suggest isolate via 1. using completely different system 2. try on empty repo just install rx to see if this is package issue, or npm / system issue.

**Comment by drager** [comment]
@kwonoj: Okey, now I tried with the same node version and the same npm version in an empty folder, which resulted in the same issue.

I also tried updating node to v5.10.1 using npm v3.8.6 and it worked just fine then. I also tried node v5.8.0 and npm v3.7.3 which also worked. So it's a problem with node v5.9.1...

**Comment by kwonoj** [comment]
Thanks for checking. let me close this issue for now that I think package itself is fine.
