### ISSUE TITLE
trailing behavior on throttleTime

### ISSUE THREAD

**Issue by matthewwithanm** [ReactiveX/rxjs#1625]
It's possible that this could be considered a feature request, however, I think the implemented behavior is actually not the generally desired one. Underscore and lodash both default their throttles' `leading` and `trailing` options to true.

**RxJS version:** 5.0.0-beta.6

**Code to reproduce:**

``` js
Observable.interval(1000)
  .take(4)
  .merge(Observable.never())
  .do(x => console.log('<-', x))
  .throttleTime(2000)
  .subscribe(
    x => console.log('->', x),
    err => console.log('err', err),
    _ => console.log('complete')
  );
```

**Expected behavior:**

```
<- 0
-> 0
<- 1
<- 2
-> 2
<- 3
-> 3
```

**Actual behavior:**

```
<- 0
-> 0
<- 1
<- 2
-> 2
<- 3
```

**Additional information:**

I would argue that even if the source observable completes (i.e. the `.merge(Observable.never())` line is removed), the output should contain the final `-> 3`.

**Comment by matthewwithanm** [comment]
Sorry, maybe I'm just confused about the purpose of `throttleTime` and I should be using `sampleTime` instead.

Though in Rx 4, that will include `-> 3` regardless of completion (my desired behavior) and in Rx 5 it doesn't include the final value if the source completes first. 😕

**Comment by blesh** [comment]
Yeah, currently the behavior of throttleTime matches Rx4 exactly when comparing this code. Is it that you just want to add the last value to your stream?

```
let source = Observable.interval(1000).share();

source.take(4)
  .merge(Observable.never())
  .do(x => console.log('<-', x))
  .throttleTime(2000)
  .concat(source.last())
  .subscribe(
    x => console.log('->', x),
    err => console.log('err', err),
    _ => console.log('complete')
  );
```

**Comment by blesh** [comment]
Currently the behavior matches the behavior shown in RxJS 4. Testing this organically without a virtual scheduler might yield more random results, but it was the same for me.

As for the change to `sample` I feel like this was something that was asked for by @staltz or @trxcllnt and discussed, but I could be wrong.

**Comment by blesh** [comment]
... here is the relevant discussion about the sample operator. Incidentally, this is also the birthplace for the  idea of the marble tests: https://github.com/ReactiveX/rxjs/issues/150

**Comment by matthewwithanm** [comment]
> Yeah, currently the behavior of throttleTime matches Rx4 exactly when comparing this code. Is it that you just want to add the last value to your stream?

That's close…I guess I was expecting `throttle` to behave more like underscore/lodash's; namely:

```
source ---1------2-----345------6-|
timer  --------0----0----0----0----0----0-->
out    ---1---------2----5---------6|
```

(where the timer is dictated by the delay)

So:

1. The interval starts when the source first emits
2. The output contains the latest item from the source since the last tick (if there's been one)
3. The last item of the source is always in the output, but…
4. …like all other items in the output, its timing is dictated by the timer
5. The output stream completion is delayed relative to the source stream in the same manner as any item.

In my experience, the only common variation is to defer the leading element:

```
source ---1------2-----345------6-|
timer  --------0----0----0----0----0----0-->
out    --------1----2----5---------6|
```

(This corresponds to `leading = false` with underscore/lodash.)

**Comment by staltz** [comment]
Have you seen the variants auditTime, throttleTime, debounceTime, sampleTime?
I just pushed the docs for these. Before Ben puts them online at reactivex.io/rxjs, you can see them directly in the source code:

https://github.com/ReactiveX/rxjs/blob/master/src/operator/auditTime.ts
https://github.com/ReactiveX/rxjs/blob/master/src/operator/debounceTime.ts
https://github.com/ReactiveX/rxjs/blob/master/src/operator/sampleTime.ts
https://github.com/ReactiveX/rxjs/blob/master/src/operator/throttleTime.ts

I recommend looking also at the marble diagrams in PNG and in the test files.

**Comment by matthewwithanm** [comment]
Thanks @staltz 😊. I hadn't seen `auditTime`, but it still seems like none of them has the behavior of my diagram. Basically, it just corresponds to "I want output immediately, I want the final output to be correct (i.e. match the final input), and I want everything in the output stream to be at least n ms apart."

**Comment by staltz** [comment]
Isn't that throttleTime? At least according to your description, it fulfills the need.

**Comment by matthewwithanm** [comment]
Sorry, I guess my description wasn't complete. `throttleTime` has the "issue" described in the OP. For every element in the source stream, there should be an element (though not necessarily the same one) in the output stream <= n ms later.

**Comment by sod** [comment]
Example punkr: https://plnkr.co/edit/NZwb3ol8CbZFtSc6Q9zm?p=preview

I would love to emulate the default lodash throttle behavior with rxjs without writing my own operator. Or could we combine two operators to achieve that?

**Comment by corsen2000** [comment]
I'm also looking for this behavior. @sod I am unsure why [my reproducer](http://jsbin.com/saguhoqoje/edit?html,js,console,output) is different than yours, but mine seems to show `auditTime` not getting the last value where yours does and only has a problem with first value lag.

[Kefir's implementation of throttle](https://rpominov.github.io/kefir/#throttle) is consistent with lodash throttle and seems to be what I want. I'd like to have an implementation like this in `RxJS`.

**Comment by trxcllnt** [comment]
Ok, so it seems like we should have operators that do this, either by parameterizing the existing ones, or adding new ones.

I believe the present operator behavior is correct with respect to error and completion messages (they are not delayed), as opposed to the `delay` operator, which affects all messages.

Perhaps adding an optional `delay` bool to the operator signatures, or `throttleTimeDelay` etc. variants would be worthwhile additions here. @blesh thoughts?

**Comment by staltz** [comment]
bool arguments :-1:
throttleTimeDelay, maybe :+1:

**Comment by sod** [comment]
auditTime just needs two changes to achieve lodash.throttle behavior. Just called it auditTimeImmediate for the lack of a better word :)

https://plnkr.co/edit/4NkXsOeJOSrLUP9WEtp0?p=preview
http://stackoverflow.com/a/37155747/435413

**Comment by kzaher** [comment]
Hi guys,

we are currently trying to fix `throttle` operator behavior in RxSwift :)

RxSwift version of throttle was first made consistent with Rx.NET version, but it looks that because of some historical reasons, throttle operator was actually debounce :(

To resolve that issue, I've thought it would be a good idea to try to make it consistent with RxJS version, but it seems that version isn't also the version we need :)

If throttle would emit last element in RxJS like @matthewwithanm is suggesting, that would be really awesome because that is the behavior that I would expect and users need. We got a lot of requests for that particular operator behavior in RxSwift, and we would really want to implement it that way.

Could somebody shed some light on this and maybe provide some reasoning why is throttle operator behaving the way it currently is and not always emitting latest element?

If we would want to model typical autocomplete throttling, it seems to me that always emitting last element (state) is the preferred behavior.

I don't have any historical insights or access to any throttle design rationale so I'm kind of confused :)

Is there some really good reason why we would want this throttle behavior, or was the intention backwards compatibility only?

**Comment by mbonneau** [comment]
I was implementing this for RxPHP and having an almost identical discussion as this thread with @davidwdan . For our purposes, getting the last element (and an the most recent element after the timeout) makes sense and it would be great to have an rxjs operator that works this way.

**Comment by blesh** [comment]
I'm not opposed. I think for the sake of library size and operator proliferation, it might be better to have this be an overloaded version of `throttleTime`. Similarly with `debounceTime` and the leading value.

**Comment by ronag** [comment]
Question, but couldn't this be easily achieved with?

```javascript
x$.publish(x$ => x$.throttleTime(time).concat(x$.last()))
```

**Comment by savega** [comment]
I'm not sure why, but this the following didn't work for me. 
`x$.publish(x$ => x$.throttleTime(time).concat(x$.last()))`

However, `x$.auditTime(time)` is exactly what {trailing:true} is in lodash.

**Comment by DomiR** [comment]
@ronag your solution will only work if the input stream is closed => last() will be triggered. This would solve this problem: 
```
source ---1------2-3---456-7-|   <= last() is 7
timer  --------0----0----0----0----0----0-->
out    --------1----3----6----7|   <= what we want
```

The plunker-examples show a continuous input stream. 
```
source ---1------2-3---456-7----------->    <= no last()
timer  --------0----0----0----0----0----0-->
out    --------1----3----6--------->   <= not 7, PROBLEM for autocompletion and react state usages
```

**Comment by trxcllnt** [comment]
@DomiR off the top of my head, it looks like @ronag's pretty close. I think this should work:

```javascript
function throttleTrailing(due, scheduler) {
    return source
        .throttleTime(due, scheduler)
        .publish(shared => shared
            .merge(shared.switchMapTo(shared
                .timeoutWith(due, Observable.empty(), scheduler)
                .takeLast(1))
            )
        );
}
```

**Comment by ronag** [comment]
How about?

```js
function throttleTrailing(due, scheduler) {
    return source
        .publish(shared => shared
            .take(1)
            .merge(shared.auditTime(due )
        );
}
```

**Comment by trxcllnt** [comment]
@ronag yes, after looking back at @matthewwithanm's original comment, I think you're right. I thought this issue was about getting the inverse.

**Comment by ronag** [comment]
@trxcllnt: Another try...

```js
function throttleTrailing(due, scheduler) {
    return source
        .publish(shared => shared
            .take(1)
            .merge(shared.skip(1).take(1).delay(due))
            .repeat()
        );
}
```

**Comment by ronag** [comment]
What's the status on this? I'm repeatedly running into needing this functionality...

**Comment by blesh** [comment]
@ronag... I think this is a reasonable addition. I don't think anyone has worked on a design or PR, unless I'm forgetting something.

**Comment by sanex3339** [comment]
Here any implementation of this behaviour
```
source ---1------2-3-----456-7-|
timer  --------0------0----0----0----0----0-->
out    ---1------2----3----6----7|
```
using existing operators?

**Comment by sanex3339** [comment]
```
.publish((source) => Rx.Observable.merge(source.debounceTime(750),source.throttleTime(750)))
```

this works exactly same as underscore/lodash throttle
https://plnkr.co/edit/cZzSOqyelxhDl5PwAzXZ?p=preview

**Comment by ronag** [comment]
@sanex3339: It's not quite the same...

**Comment by samal84** [comment]
So I wasn't happy with the current state of throttleTime as it still has several open bugs, so I made my own simpler lettable implementation that is always both leading and trailing. Just sharing here in case anyone is interested.

```
import { Observable } from 'rxjs/Observable';

export function throttleTime<T>(
    time: number
): (source: Observable<T>) => Observable<T> {
    return (source: Observable<T>) => {
        let timeoutHandle;
        let lastValue: T;
        let lastEmittedValue: T;
        return Observable.create((observer) => {
            let setTimeoutFn = () => {
                timeoutHandle = setTimeout(
                    () => {
                        if (lastEmittedValue !== lastValue) {
                            lastEmittedValue = lastValue;
                            observer.next(lastValue);
                            setTimeoutFn();
                        } else {
                            timeoutHandle = undefined;
                        }
                    },
                    time
                );
            };

            let sourceSubscription = source
            .subscribe({
                complete: () => {
                    observer.complete();
                },
                error: (error) => {
                    observer.error(error);
                },
                next: (value: T) => {
                    if (timeoutHandle === undefined) {
                        setTimeoutFn();
                        lastEmittedValue = value;
                        observer.next(value);
                    }

                    lastValue = value;
                },
            });

            return () => {
                sourceSubscription.unsubscribe();
                sourceSubscription = undefined;
                lastValue = undefined;
                lastEmittedValue = undefined;
                if (timeoutHandle) {
                    clearTimeout(timeoutHandle);
                    timeoutHandle = undefined;
                }
                setTimeoutFn = undefined;
            };
        });
    };
}
```

**Comment by pkelleter** [comment]
I don't really understand why this issue has been closed.
Whilst throttleTime supports a leading/trailing config now, it still doesn't offer any way to configure throttleTime in order to match the expected behavior when you are coming from lodash or similar implementations.

Whilst (for example) lodash will "buffer" the events in the given time frame, and replay the latest event as soon as the next "window" opens, RxJS will just forget about any events fired while throttling.
Not only does this consequently result in different values emitted than by lodash's approach, but most importantly there is a big chance of ignoring the very last value of the given input stream.

This means that if you are for example throttling a scroll or mousemove event, you will most likely perform the final action on values which have not been the actual last values of the original input stream.

Assume the following stream, which emits values from 0 to 49, each including
`Rx.Observable.interval(10).take(50)`

No matter how I configure a throttleTime of 150, there is no way to emit the final value of 49
```
Rx.Observable.interval(10).take(50)
	.throttleTime(
		150,
		Rx.Scheduler.async,
		{
			leading: false/true,
			trailing: false/true
		}
	)
	.subscribe(console.log);
```

Even with true/true, this will emit [0, 14, 15, 29, 30, 44, 45], but not the final event of 49.

**Comment by tony-gutierrez** [comment]
Yeah, this is not very useful if it never processes the last event....

**Comment by ericmarcos** [comment]
Is there any way to throttle events and get ALL the events emitted during the last period?

Like:
```
---1------2-3----456--78|
-------0-------0-------0-------0-------0-------0-->
------[1]-----[2,3]---[4,5,6]--[7,8]|
```

Thanks

**Comment by activeperception** [comment]
@ericmarcos buffertime

**Comment by jscti** [comment]
+1 on that, need that last event

**Comment by ronag** [comment]
I think something like this is what most people are looking for: https://github.com/nxtedition/nxt-lib/blob/master/rxjs/throttleTime2.js

**Comment by MickL** [comment]
@pkelleter Its closed because Ben Lesh implemented exactly what @matthewwithanm wanted. Just read the issue carefully and you will notice the pull request with explaination: https://github.com/ReactiveX/rxjs/commit/bb0738f3e6df643158c4a7d1e38f035978b42882

Use it at so `throttleTime(500, undefined, {leading: false, trailing: true}`

If you found a bug with this please open a new issue.
