### ISSUE TITLE
Support .Publish(...)

### ISSUE THREAD

**Issue by Dorus** [ReactiveX/rxjs#1629]
For reference, the [Rx Design Guidelines](http://blogs.msdn.com/b/rxteam/archive/2010/10/28/rx-design-guidelines.aspx) [5.10](http://xgrommx.github.io/rx-book/content/guidelines/using/index.html#use-the-publish-operator-to-share-sideeffects) suggest to use this operator.

The operator `.publish()` returns an `ConnectableObservable`, this means you first need to subscribe all your sources, `.connect()` it, keep a reference to your connect to prevent leaks, and then you also end up with a hot observable, so downstream subscribers better be ready as well.

Most of the time you only want to duplicate a stream locally. RxJS 4 and many other Rx implementations allow you to write 

    xs.publish(ob => ob.zip(ob.skip(1), (x, y) => {...}))

Here we use publish to peek at the next item in the source. Another favorite of mine is

    xs.publish(ob => ob.window(ob.debounce(100)))

Because often you want to use a source for its own window-boundary.

This operator is very similar to `.let`, but avoid subscribing to the source twice. Useful on cold observables, but also to avoid the overhead of subscribing multiple times to a hot source. (imagine you use this trick 4x in a row with `let`, you end up with 2^4th subscriptions.)

**Comment by kwonoj** [comment]
Would you elaborate bit more? so far I know current `publish` already returns `ConnectableObservable` (https://github.com/ReactiveX/rxjs/blob/34cdef5a3d652c75a546e5bd73733fd21dc64fc0/src/operator/publish.ts#L15) would you mind to share some snippet of pusedo for suggested behavior?

**Comment by Dorus** [comment]
The operator `publish([selector])` should not return an `ConnectableObservable`, instead it returns the result of creating the connectable observable, passing the connectable observable to the `selector`, 

aka
```JS
function publish(source, selector) {
  return Rx.Observable.create(ob => {
    var xs = source.publish();
    return selector(xs).subscribe(ob).add(xs.connect());
  });
}
```
Similar to publish in [RxJS 4](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/publish.md) and [Rx.Net](https://msdn.microsoft.com/en-us/library/hh229147%28v=vs.103%29.aspx).

> selector
    Type: System.Func<IObservable<TSource>, IObservable<TResult>>
    The selector function which can use the multicasted source sequence as many times as needed, without causing multiple subscriptions to the source sequence.

**Comment by kwonoj** [comment]
Thanks for clarification. I actually noticed RxJS 5 missing `publish` accepts `selector` compare to RxJS 4, and wasn't able to look up reason. @staltz , @blesh , remember there was discussions to align sharing operators in RxJS 5, is this conclusion of it or it's yet migrated from RxJS 4?

**Comment by staltz** [comment]
Yeah, I think this makes sense to implement.

**Comment by kwonoj** [comment]
I'll try to introduce those changes.
