### ISSUE TITLE
Make the "source" field public in Observable.d.ts

### ISSUE THREAD

**Issue by jpleclerc** [ReactiveX/rxjs#1635]
I have to use the "source" field to solve my problem: 
http://stackoverflow.com/questions/36654920/how-to-catch-an-error-on-a-request-then-open-a-modal-then-retry-when-modal-clo/36656026?noredirect=1#36656026

Right now I access it with observable["source"]

**RxJS version:**
5.0.0-beta.2

**Comment by blesh** [comment]
@jpleclerc can you clarify how you had to use the `source` field to solve your problem? That really shouldn't be the case.

For your example, it looks like what you really want to use is `retryWhen`:

```js
getSomeData().retryWhen((errors) => 
  errors.switchMap((err) => err.status === 401 ? awaitLoginModal() : Observable.throw(err))
```

where `awaitLoginModal()` is a function that returns an observable that wraps the process of showing the modal and a successful log in.

```js
var loginForm = document.querySelector('#loginForm');
function awaitLoginModal() {
  return Observable.fromEvent(loginForm, 'submit')
    .take(1)
    .flatMap(() => submitLoginInformationViaAJAX());
}
```

**Comment by blesh** [comment]
I haven't seen a compelling reason to make `source` public. But perhaps I'm missing something?

**Comment by jpleclerc** [comment]
Ok so I refactored my code with your solution and it seems to work. I guess it was me not using the library correctly.

Here is my final solution:

```
public get(url: string, options?: RequestOptionsArgs): Observable<Response> {
    return super.get(url, options).retryWhen((errors: any) => this.errorHandler(errors));
}
private errorHandler(errors): any {
    return errors.switchMap((err) => {
        if (err.status === 401) {
            let closedSubject = new Subject();
            this.modalService.open(new ModalConfig({
                content: LoginModalComponent,
                close: () => { closedSubject.next(err); }
            }));
            return <any>closedSubject;
        }
        else {
            return Observable.throw(err.json());
        }
    });
}
```
