### ISSUE TITLE
Moving Schedulers to a separate package?

### ISSUE THREAD

**Issue by blesh** [ReactiveX/rxjs#1638]
Clearly the Schedulers are a _requirement_ for this library. However, I feel like the schedulers are generally more useful than just for RxJS. @mattpodwysocki, it seems like these schedulers would be useful for IxJS and other async types the Reactive community might come up with. What do you think?

Also @mhevery and @IgorMinar ... I know that you have a lot of work in the scheduling arena, we have _different_ needs here, but they do have some overlap. What do you think about the plan to have a separate agnostic package for our schedulers? How could this mesh with your goals around Zones, etc?

This is just a discussion. Of course.

Again: We'd still need to export/include the schedulers with this library.

**Comment by blesh** [comment]
cc/ @jayphelps for visibility, since he's looking into breaking out things like DOM functionality into different packages for us.

**Comment by kwonoj** [comment]
I'm +1 to this, including publish other packages as well if it's allowed.

**Comment by IgorMinar** [comment]
The only big thing to be mindful off is that once the schedulers are in a
separate package, we could get into a situation where there are multiple
copies of schedulers lurking around which would likely be very bad.

**Comment by blesh** [comment]
I agree @IgorMinar, it would mean people would have to be careful to only use them as a peer dependency or something. We already have a few issues with RxJS around that because of operator patching. Worse yet, peer dependencies are sort of a pain.

**Comment by mattpodwysocki** [comment]
@IgorMinar we could easily get around that by installing schedulers into globals at that point to keep multiple ones from hanging around.  That's how others have done it with two RxJS packages sticking around...

**Comment by blesh** [comment]
> installing schedulers into globals

@mattpodwysocki my currency-bug-sense is tingling on this one. I can see one library getting a handle to a scheduler from a global, then another library swapping out the reference and using a different one. Then the first library scheduling on two different scheduler instances and not realizing it. Or all sorts of other crazy outcomes.

**Comment by benjamingr** [comment]
What we do with bluebird promises is ship with a single scheduler and then let users override it. 

I think you could do the same in Rx, ship with one simple scheduler (or two, since IIRC that's needed) and then encourage others include schedulers themselves when needed.

**Comment by blesh** [comment]
closing as inactive.
