### ISSUE TITLE
Missing Observable.from in API Documentation 

### ISSUE THREAD

**Issue by martinsik** [ReactiveX/rxjs#1639]
In the [CHANGELOG.md](https://github.com/ReactiveX/rxjs/blob/master/CHANGELOG.md) it's mentioned that since `5.0.0-beta.4` `Observable.fromArray` has been removed in favor of `Observable.from`.

However,  `Observable.from` is not documented anywhere. I'd expect it to be among other `from*` methods in http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html but it's not.

**Comment by staltz** [comment]
Documentation is still work in progress.

**Comment by blesh** [comment]
This exists now. Closing
