### ISSUE TITLE
docs: missing parameters in ReplaySubject.race method

### ISSUE THREAD

**Issue by BrainCrumbz** [ReactiveX/rxjs#1641]
While browsing API reference at http://reactivex.io/rxjs/class/es6/ReplaySubject.js~ReplaySubject.html, you can see that `race()` operator is listed with no arguments. 

If you then go to http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#instance-method-race, on the top it still misses any argument, but then it mentions an `...observables` input (as it makes sense from operator functionality) under _Params_ section.

Q1: Is that intended?
Q2: If that's a bug, where can one find the sources for that?

Thanks

**Comment by BrainCrumbz** [comment]
Side note: still for ReplaySubject, `scan` method has a typo in returned value: `Obervable`.

**Comment by kwonoj** [comment]
Since documentation is being evolved currently, I assume it's simply not yet ready at this moment.

**Comment by BrainCrumbz** [comment]
Thanks for feedback. Do you know where the sources for those docs can be found in repository? So that we can submit a PR?

**Comment by blesh** [comment]
This has documentation now
