### ISSUE TITLE
Proposal: Rename `merge` operators to `flatten` operators.

### ISSUE THREAD

**Issue by blesh** [ReactiveX/rxjs#1642]
### Reasoning:
1. There is currently a [proposal](http://bterlson.github.io/proposal-flatMap/) by @bterlson to add `flatten` and `flatMap` to `Array.prototype`. 
2. `flatMap` is more widely known than `mergeMap`.
3. `mergeMap()` was a new name for `flatMap` to better link the idea or `.map().mergeAll()` being the same as `flatMap()`.
### Proposed changes:
- `mergeAll` -> `flatten`
- `mergeMap` -> `flatMap`
- `mergeScan` -> `flatScan`
### Risks

We've just spent months teaching people `mergeAll` and `mergeMap`... _\* sigh *_. Lack of `mergeAll` may confuse some people, I suppose.

cc/ @mattpodwysocki @staltz @jhusain

**Comment by blesh** [comment]
This proposal is urgent as we're closing in on time to solidify the API.

**Comment by mattpodwysocki** [comment]
@blesh I think it would be confusing for `flatten` for `mergeAll` because we also have `concatAll`, so what does `flatten` mean in that regard?

**Comment by blesh** [comment]
@mattpodwysocki 

well we currently have:

- `mergeAll`
- `concatAll`
- `switch`

One of these things is not like the other anyway.

There's always:

- `concatAll` -> `concatten`  :P

**Comment by blesh** [comment]
FWIW: I'm neither for nor against this proposal, I'm simply putting it to the community.

cc/ @zenparsing as well, I guess.

**Comment by blesh** [comment]
I think that `merge` probably makes more sense for async things, and `flatten` makes more sense for an array of arrays, because they're really static structures and you're flattening them down one level.

**Comment by blesh** [comment]
Actually. what would we do with `Observable.merge`? `Observable.flat`? haha.. that's dumb.

I'm liking this idea less and less.

I suppose we could add an alias for `flatten`?

**Comment by mattpodwysocki** [comment]
@blesh You certainly could alias `flatten` with `mergeAll`, I wouldn't mind given the default style of combining sequences is merging, not concat.

**Comment by blesh** [comment]
Then again, people can alias things all the want now like:

```js
import { mergeAll as flatten } from 'rxjs/operators/mergeAll';
```

**Comment by staltz** [comment]
I totally agree with this:

- `mergeAll` -> `flatten`
- `mergeMap` -> `flatMap`
- `mergeScan` -> `flatScan`

And it still keeps the API that Jafar originally suggested with `____Map`. ConcatAll would become the outlier since there's already `switch`, but I don't have a good suggestion yet to solve that.

**Comment by david-driscoll** [comment]
I know the goal is not to have aliases, but in this case couldn't it be helpful?

In fact today we still have an alias for [`flatMap` and `flatMapTo`](https://github.com/ReactiveX/rxjs/blob/master/src/add/operator/mergeMap.ts#L10-L11), so the only new ones would be...

* `mergeAll` alias `flatten`
* `mergeScan` alias `flatScan`

Now we could shift the default naming such that `mergeMap` becomes `flatMap` for anyone consuming the operators themselves.

That does confuse the difference between `Observable.merge` and `o.flatten`, which are essentially the same thing.  With this change shouldn't it also become `Observable.flatten`?

**Comment by zenparsing** [comment]
@blesh I agree with the goal of aligning observable method names with array method names.

`mergeAll` only flattens one level, correct?  It doesn't do recursive flattening, does it?  Currently the flatten/flatMap array proposal has `flatten` doing recursive flattening.  I've argued against this, on the grounds that other data types (i.e. Observable) aren't going to want that behavior.  If you agree, you might want to lend your voice to that discussion.

**Comment by bterlson** [comment]
@zenparsing fwiw I am convinced that non-recursive flattening is correct. I haven't had time to update the proposal - I will do so though!

**Comment by blesh** [comment]
> mergeAll only flattens one level, correct? It doesn't do recursive flattening, does it?

@zenparsing Correct, it only flattens one level. I don't think I'd want to recursively flatten, because at some levels you might want to `switch` or something instead.

**Comment by alxhub** [comment]
I prefer `mergeMap` to `flatMap`.

One distinction between the Rx operation and the `flatMap` found in functional languages (and the proposed `Array.prototype.flatMap` is that the Rx version is potentially async.

I've seen plenty of code in the wild where people write `someRandomEvent.flatMap(v => http.get(makeUrl(v)))`, not realizing that if two events arrive in quick succession then the order of the results is undetermined. To me the `mergeMap` name at least makes it clear that this is a _merging_ operation where the initial order of the inputs isn't considered.

**Comment by trxcllnt** [comment]
@blesh @zenparsing @bterlson perhaps the Array version of `>>=` should be named `concatMap`, as it's concatenating the results of the map operation (and critically, preserving order). Then the behavior would line up 1-1 with Observable's current `concatMap` as well. `mergeMap`/`flatMap` for Arrays is undefined, though could be an alias for `concatMap`. cc: @jhusain from which this idea originated.

**Comment by mattpodwysocki** [comment]
@trxcllnt I would argue against that as `flatMap` is standard in many languages such as `Scala`, `Java` via the Java 8 Streams, Swift, which all come down to meaning `map(fn).concat()`.  In push based collections, that's unreasonable, hence defaulting to `merge` as a default for the `flatMap` strategy.  

It's the same way we did it in .NET with `SelectMany` being `Select(fn).Concat()` in LINQ to Objects and `SelectMany` in Rx .NET being `Select(fn).Merge()`.

**Comment by blesh** [comment]
I think we can all agree that `map + mergeAll === flatMap` doesn't make much sense to the newbie Rx developer, though. Esp. in the face of `map + mergeAll === mergeMap`. Likewise `map + flatten === flatMap` makes more sense.

A bigger concern I have though is Array `flatten`'s proposed recursive flattening strategy, which would be a no-go here. Default/recursive flattening as it exists in Promises is weird enough, that sort of behavior would be a no-go for me with observable.

**Comment by mattpodwysocki** [comment]
@blesh according to @bterlson it sounded like he was not considering recursive flattening so I don't think that's an issue

**Comment by blesh** [comment]
At this point, I'm inclined to close this issue, as it would be a non-breaking change to alias `mergeAll` as `flatten` up front at a later point, and then add deprecation warnings if we decide to fully move to `flatten` over `mergeAll`.

I'll leave it open for a while, though. As maybe there are compelling reasons to switch ahead of the production release of 5.0.0.

**Comment by bterlson** [comment]
Fwiw, I agree concatMap is the right naming of the current ECMAScript flatMap proposal. Although there is an open issue about whether we should actually be using concat semantics or iterable semantics. If we arrive at iterable semantics then I would argue for naming the ECMAScript built-in flatMap as concatMap will be misleading in that case.

**Comment by blesh** [comment]
closing this as inactive.
