### ISSUE TITLE
`utils/root` returns undefined in Jest

### ISSUE THREAD

**Issue by blesh** [ReactiveX/rxjs#1643]
**RxJS version:** 5.0.0-beta.6

**Code to reproduce:**

Create a test for Jest and include this at the top:

```js
import * as Rx from 'rxjs';
```

**Expected behavior:**

No errors

**Actual behavior:**

TypeError: Cannot read property 'Symbol' of undefined

**Comment by blesh** [comment]
this might be an issue with jest, too. .

**Comment by kwonoj** [comment]
I believe this is related with jest's automocking behavior.

```js
jest.unmock('rxjs/Rx'); //disable automock for Rx module
var Rx = require('rxjs/Rx');
```

makes it work. Not sure how does automocking work internally, need to look into bit more to see what's happening though..

**Comment by kwonoj** [comment]
After digging this bit more, https://github.com/facebook/jest/issues/90#issuecomment-151586811 / https://github.com/pimterry/loglevel/issues/85#issuecomment-159259324 seems jest's automocking has known issues of failing mock for some modules.

I'd suggest to leave note to not to mock `root` for RxJS cases for immediate resolution such as 

```js 
jest.unmock('rxjs/util/root'); //do not mock root module only, do not need to unmock everything
var Rx = require('rxjs/Rx');

...test goes here
```

while mock gets improved to support this cases as well.

**Comment by denisw** [comment]
Another related issue with the same symptom happens when configuring Jest to run in the "node" environment (as is the default in create-react-app 0.3.0-alpha): `root.js` checks if `global.global === global` to determine whether it's running in a Node environment, but Jest doesn't define `global.global`.

I created https://github.com/facebook/jest/pull/1394 to fix this.

**Comment by blesh** [comment]
I think that @kwonoj's response to this particular issue is the answer to the post.

@denisw thanks for chiming in with that related issue, hopefully it helps anyone that lands here.

I'm going to close this issue for now.
