### ISSUE TITLE
Export all operators and observables from index file

### ISSUE THREAD

**Issue by mrtnbroder** [ReactiveX/rxjs#1646]
When using the es next function bind method of importing operators, it's kind of tedious to write it all one line after each other, like this:

```
import { debounceTime } from 'rxjs/operator/debounceTime'
import { map } from 'rxjs/operator/map'
import { repeat } from 'rxjs/operator/repeat'
import { scan } from 'rxjs/operator/scan'
import { takeUntil } from 'rxjs/operator/takeUntil'
```

it would be great to have an index file that exports all operators so we can import our operators like this:

```
import { debounceTime, map, repeat, scan, takeUntil } from 'rxjs/operator'
```

same thing for observable(s)

**Comment by tim-mcgee** [comment]
I think this issue is related to https://github.com/ReactiveX/rxjs/issues/1386

**Comment by blesh** [comment]
@staltz @trxcllnt you both 👍 'ed this.. does this have some bundling/modularity/tree-shaking benefit I'm not aware of? It seems like it would be bad for bundling to use this because it would include a whole mess of modules you probably don't want to use. However, it might work with tree-shaking? I don't know.

**Comment by trxcllnt** [comment]
@benlesh from what I understand, webpack etc. should be able to tree-shake ES6 exports/imports done this way. Worth testing to make sure though.

**Comment by david-driscoll** [comment]
It would be great if those operators were "lodash" like, in that the first argument is the observable, so you don't have to do weird ways of calling them.

```typescript
map.call(filter.call(of('a'), x => !!x), x => x * 2);
```

vs

```typescript
map(filter(of('a'), x => !!x), x => x * 2);
```

This way we wouldn't have to wait for a new version to change them later.

**Comment by mattpodwysocki** [comment]
@david-driscoll that's exactly what I'm doing for IxJS so that we don't have that silly `.call` behavior https://github.com/reactivex/ixjs

**Comment by imgx64** [comment]
Is this bug fixed by [Lettable Operators](https://github.com/ReactiveX/rxjs/blob/master/doc/lettable-operators.md)? From that page:
```
import { map, filter, scan } from 'rxjs/operators';
```

**Comment by kwonoj** [comment]
I think it's no longer an issue with export organization changes in v6.
