### ISSUE TITLE
TypeError: Rx.Observable.from(...).distinct is not a function

### ISSUE THREAD

**Issue by miguelmota** [ReactiveX/rxjs#1647]
**RxJS version:**

```
5.0.0-beta.6
```

**Code to reproduce:**

```javascript
const Rx = require('rxjs/Rx');

Rx.Observable.from([1,2,2,3])
.distinct()
.subscribe(x => console.log(x));
```

**Expected behavior:**

```javascript
[1,2,3]
```

**Actual behavior:**

```javascript
TypeError: Rx.Observable.from(...).distinct is not a function
```

**Additional information:**

**Comment by kwonoj** [comment]
Please import `Rx.KitchenSink` for extended operator (https://github.com/ReactiveX/rxjs/issues/1560#issuecomment-203342688) .

**Comment by miguelmota** [comment]
Thanks for the quick reply, is that in the documentation somewhere?

**Comment by kwonoj** [comment]
Documentation is currently evolving, as far as I remember those detail's are not yet published into documentation.

**Comment by staltz** [comment]
Related: #1650
