### ISSUE TITLE
Update migration document

### ISSUE THREAD

**Issue by Dorus** [ReactiveX/rxjs#1653]
https://github.com/ReactiveX/RxJS/blob/master/MIGRATION.md

A number of changes are missing from this document. I keep running into them and as the migration document is one of my key reference points when looking for methods in RxJS 4 vs 5, it would be good to see it updated.

I'm not sure if these changes are on the radar, but the first one i want to propose is:
[`windowToggle`](http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#instance-method-windowToggle) makes a good replacement for the old pausable.

**Comment by staltz** [comment]
Hi, thank you for taking your time to send us this issue. We appreciate it. Can you submit a PR whenever you find something that is missing in the migration guide?

**Comment by Dorus** [comment]
I'll try to make a more complete list of what i missed before and might do so then.

Do you agree on `windowToggle` for `pausable`? Because it's not completely the same.

**Comment by Dorus** [comment]
Found another one:

`startAsync` is now `defer` (as defer now takes a promise as well as observable).
`fromPromise(factory)` is now also `defer(factory)`, as `fromPromise` no longer takes a factory.

Again, if i'm spewing nonsense please tell me, else i'm assuming this is correct.

**Comment by blesh** [comment]
closing as inactive. I think this is mostly covered now, also.
