### ISSUE TITLE
Add External Resources section

### ISSUE THREAD

**Issue by paulpdaniels** [ReactiveX/rxjs#1666]
Proposing the addition of an learning resources section for books, blogs, videos and the like.
The docs are coming along, but there should be links as well to additional learning resources (particularly those focused around RxJS5).

I can submit a PR if needed, but given that it is a new section, I am not sure where it would be best located.

**Comment by blesh** [comment]
I heard you have a book. ;)

It's not a bad idea. cc/ @staltz

**Comment by staltz** [comment]
Big yes to this

**Comment by paulpdaniels** [comment]
More of half a book right now :P.

Would it make sense to add a new section at http://reactivex.io/rxjs/?

**Comment by staltz** [comment]
Yes it would, but it would have to be under "Manual" or "Tutorial", because ESDoc doesn't support adding a new top-level section

**Comment by blesh** [comment]
Manual seems fine, I think.
