### ISSUE TITLE
finally is not passing observable through properly

### ISSUE THREAD

**Issue by johnpapa** [ReactiveX/rxjs#1672]
**RxJS version:**
rxjs 5 beta 6

**Code to reproduce:**
```
  getSessions() {
    this.spinnerService.show();
    return <Observable<Session[]>>this.http
      .get(sessionsUrl)
      .map(res => this.extractData<Session[]>(res))
      .catch(this.exceptionService.catchBadResponse)
      .finally(() => this.spinnerService.hide());
  }
```

See code example here ...
https://github.com/johnpapa/event-view/commit/da21a922faf74aa3f2b6fbf1af5d1d666419b24e#diff-a115014ed5c151b197295d50f1ce2a54R24

**Expected behavior:**
TypeScript's `tsc` should think `getSessions` should return `Observable<Session[]>` 

**Actual behavior:**
TypeScript's `tsc` thinks `getSessions` is  returning `Observable<{}>` 

**Additional information:**
- When I comment out the `finally` TypeScript is happy
- When I cast the return type  as `<Observable<Session[]>>` tsc is happy

**Error message:**
```
> tsc -p ./src/client

src/client/app/+sessions/session-list/session-list.component.ts(34,9): error TS2322: Type '{}' is not assignable to type 'Session[]'.
```

cc // @david-driscoll @blesh @robwormald @wardbell

**Comment by kwonoj** [comment]
Think I found cause.

**Comment by kwonoj** [comment]
@johnpapa , I believe this is fixed by latest changes in master branch. If you're ok please check with master, or it'll be published in next release. Thanks for catching this.

**Comment by blesh** [comment]
@johnpapa next release will be Monday unless I get a deluge of requests prior to ng-conf.

**Comment by johnpapa** [comment]
trying it now.

just noticed i have this line ... which is not what you changed. i am on beta 6 (as it matches angular 2 beta 17)
```
   <T>(finallySelector: () => void): Observable<T>;
```

**Comment by kwonoj** [comment]
Yes, that's prior to master including changes. Next package will be published in next week as @blesh mentioned, or for immediate trying you may need to pull down master branch.

**Comment by johnpapa** [comment]
![image](https://cloud.githubusercontent.com/assets/1202528/14932229/4bab13c8-0e41-11e6-9321-98beade05681.png)

**Comment by johnpapa** [comment]
Same error :(

**Comment by david-driscoll** [comment]
worst case you could manually set the type `.finally<Session[]>(() => this.spinnerService.hide());`

**Comment by johnpapa** [comment]
Right. I'm casting now. But I think this issue should be reopened as it is not fixed from.what I tried. See above

**Comment by kwonoj** [comment]
I just confirmed locally with master and it's working as expected. @johnpapa , would you be isolate to create small repo using bare Rx master only, without involving ng2?

**Comment by david-driscoll** [comment]
I wonder if there is a nested rxjs folder that's getting picked up over a custom build.

I'm hanging out on the ReactiveX, OmniSharp and ASP.NET Core slacks if you want to chat a little more real time.

**Comment by johnpapa** [comment]
i can try to do a smaller repo later, but for now here is the repo where i cast it. https://github.com/johnpapa/event-view/blob/master/src/client/app/shared/speaker-services/speaker.service.ts#L39-L46

**Comment by david-driscoll** [comment]
Looks like catch might have an indirect problem as well, I'll see what I can do.

**Comment by david-driscoll** [comment]
With the changes in that additional PR, I was able to do this (without the cast in front as well!)
![image](https://cloud.githubusercontent.com/assets/1269157/14933253/c5aa3478-0e56-11e6-9d20-3e6e9225966c.png)

I also made one other change to `catchBadRequest`

```typescript
  catchBadResponse: <T>(errorResponse: any) => Observable<T> = (errorResponse: any) => {
    let res = <Response>errorResponse;
    let err = res.json();
    let emsg = err ?
      (err.error ? err.error : JSON.stringify(err)) :
      (res.statusText || 'unknown error');
    this.toastService.activate(`Error - Bad Response - ${emsg}`);
    // return Observable.throw(emsg); // TODO: We should NOT swallow error here.
    return Observable.of();
  };
```

**Comment by kwonoj** [comment]
Just checked in changes for `catch` as well.

**Comment by johnpapa** [comment]
thanks for the help. it is not working in the repo i pointed at (event-view). I made those two changes in catch and finally files. But I am on beta 6, so maybe there are other things behind.

i can look more later. need to focus on some other things first. thanks tho

**Comment by bzuillsmith** [comment]
I am getting this problem as well even with the latest. I was running Beta 6 and now running Beta 9. I'm using Visual Studio Code.
An example of the call I'm making:
```javascript
this.userService.doSomething() //returns Observable<any>
        .finally(
            () => this.status = ''
        ) // VS Code shows this returns Observable<{}>
        .subscribe(
            result => {
                this.x = result.x; //complains here because result is of type {}
            },
            error => this.errorMessage = error
        )
```

**Comment by kwonoj** [comment]
@bzuillsmith I'll try with master, meanwhile would you mind to share complete snippet to able to reproduce issue? it might be possible with specific cases only, would like to confirm it as well.
