### ISSUE TITLE
Update reduce marble

### ISSUE THREAD

**Issue by Dorus** [ReactiveX/rxjs#1685]
http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#instance-method-reduce => http://reactivex.io/rxjs/img/reduce.png

Reduce now has the seed as the first parameter, the marble shows it as the second.

**Comment by staltz** [comment]
The documentation is wrong, the source code actually has the seed as the second. https://github.com/ReactiveX/rxjs/blob/master/src/operator/reduce.ts#L23

**Comment by kwonoj** [comment]
I think this is closed via https://github.com/ReactiveX/rxjs/pull/1689.
