### ISSUE TITLE
`npm run commit` is not committing

### ISSUE THREAD

**Issue by sarbbottam** [ReactiveX/rxjs#1691]
Is it only me?

[Looks like latest version of `commitizen` expects the adapter path w/o `node_modules/` prefix.](https://github.com/commitizen/cz-cli#commitizen-for-project-maintainers)

```json
...
  "config": {
    "commitizen": {
      "path": "cz-conventional-changelog"
    }
  }
```

**Comment by sarbbottam** [comment]
It works if I modify the  adapter path w/o `node_modules/` prefix.

**Comment by kwonoj** [comment]
I haven't noticed this with current version of commitizen, may related with its version. Left few comments in PR.
