### ISSUE TITLE
Dependency conflict around sinon, sinon-chai

### ISSUE THREAD

**Issue by lmeyerov** [ReactiveX/rxjs#1693]
**RxJS version:** 5.0.0-beta.7

**Code to reproduce:** `npm install`

**Expected behavior:** Install

**Actual behavior:**

Peer conflict between sinon, sinon-chai

**Additional information:**

Digging a bit, my system installed packages of these versions w/ the constraints below. It looks like RxJS wants sinon 2+ and sinon-chai 2.8+, but its sinon-chai 2.8 wants a peer dependency of sinon < 2. 

In local testing, I downgraded sinon-chai to `^1.0.0`, which seemed to have worked.

RxJS:
```
    "sinon": "^2.0.0-pre",
    "sinon-chai": "^2.8.0",
```

Sinon
```
     "version": "2.0.0-pre",
```

Sinon-chai
```
     "version": "2.8.0",
    "peerDependencies": {
        "sinon": ">=1.4.0 <2"
    devDependencies": {
        "sinon": "^1.10.3"
```

**Comment by kwonoj** [comment]
To overcome browser testing support, `sinon` 2.0 should be used. Once official release of sinon 2.0 will published `sinon-chai` will bump up its peerdependency as well(https://github.com/domenic/sinon-chai/issues/73).

**Comment by kwonoj** [comment]
Forgot to add last comment - meanwhile, please use `npm@3` if available. npm 3 loosens requirement of peerdependency, works with current configuration in general.

**Comment by lmeyerov** [comment]
@kwonoj We're in the process of updating these things (npm3, until about 2mo ago, had bugs that prevented it working for us). I think that was the issue -- we compiled w/ npm2, and so this broke on us.
