### ISSUE TITLE
Invalid module name in augmentation

### ISSUE THREAD

**Issue by wizardnet972** [ReactiveX/rxjs#1695]
Hi,

In visual studio, i got this error in every d.ts file under node_modules\rxjs\add\observable\ : 
Invalid module name in augmentation, module '../../Observable' cannot be found.
example code: declare module '../../Observable' {

how to fix that please?

**Comment by kwonoj** [comment]
Please ensure visual studio uses latest typescript release. Rxjs 5 uses module augumentation introduced at 1.8 (https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#augmenting-globalmodule-scope-from-modules ) for imported operator's supporting type definitions and requires those version of typescript compiler.
