### ISSUE TITLE
Observable.ajax throws exception when it receives HTTP 405 Method not allowed

### ISSUE THREAD

**Issue by joehmchan** [ReactiveX/rxjs#1699]
RxJS version: 5.0.0-beta.6
Code to reproduce: 
`Observable.ajax.getJSON('https://freegeoip.net/json/')`

Expected behavior:
If the api doesn't support HTTP OPTIONS, it should proceed to HTTP GET instead of throwing exception.

Actual behavior:
The freegeoip returns HTTP Error 405 Method not allowed. An exception is thrown from the Observable.

**Comment by blesh** [comment]
Sorry for the incredibly late response. By definition, any 400 status is an error.

What's interesting here, is a basic XHR send seems to work, there's something about that `getJSON` call that is causing the pre-flight request and error. I'll either need to bone-up on my XHR voodoo again, or refer to someone else.

**Comment by blesh** [comment]
@jeffbcross or @robwormald ... maybe you have some insights here, since you worked on something similar for Angular?

**Comment by benlesh** [comment]
This is expected behavior with our implementation. Responses with error codes are treated as errors.
