### ISSUE TITLE
ReactiveX, Reactive-Extensions and .NET

### ISSUE THREAD

**Issue by BrainCrumbz** [ReactiveX/RxJS#17]
Don't know if this is the right place to ask, please let me know if there's a better one.

Is your ReactiveX Github organization/entity related to **Reactive-Extensions** Github organization found at https://github.com/Reactive-Extensions ?
Is one more up-to-date than the other? 

And in particular, where should I look for the most complete documentation related to Rx.NET? 

*Yours* at https://github.com/ReactiveX/Rx.NET is empty, *theirs* at https://github.com/Reactive-Extensions/Rx.NET is not empty, but has an empty wiki and certainly lacks in documentation when compared to RxJS, RxJava, ...

Thanks for your time

**Comment by BerkeleyTrue** [comment]
I think this is for the next versions of Rx* coming out. I don't believe this versions are out in the general public. You should stick to document found at Reactive-Extentions and http://reactivex.io/

**Comment by blesh** [comment]
@BrainCrumbz ... I think @BerkeleyTrue adequately answered this, but just in case:

This is the proving ground for the next version of RxJS... the *current* version can be [found here](https://github.com/Reactive-Extensions/RxJS)

This will be the future home of RxJS once *this* version is finalized and out of beta. (it's currently pre-alpha)

**Comment by BrainCrumbz** [comment]
Thanks both for your answers, By extension, https://github.com/Reactive-Extensions/Rx.NET should be the *current* official home of Rx.NET, right?

**Comment by blesh** [comment]
Well the "home" I think is [here](https://msdn.microsoft.com/en-us/data/gg577609)... but yes, that's the repository right now.
