### ISSUE TITLE
Inaccuracy of Benchmark.js tests (micro perf tests)

### ISSUE THREAD

**Issue by blesh** [ReactiveX/rxjs#1702]
While rewriting the Subjects, I ran into a curious case wherein I could literally copy and paste code from RxJS 4 into RxJS 5 and that code, and _only_ that code, would run 50% slower in the latter. 

... that is until I swapped the order of the tests and then all of a sudden Rx4 would be much slower.

In talking to @igorminar and @jeffbcross, it seems this is why something like benchpress is really necessary. Since benchmark.js is running in the same engine as the code it's testing, it's likely that the test harness itself can become optimized by the JIT and be faster for one test than it is for another, even if they're both testing the same code.

In fact, we should probably be relying more heavily on the benchpress tests than the benchmark tests... either that or figure out a way to get the micro perf tests to run in a more sandboxed way.

Thoughts?

**Comment by luisgabriel** [comment]
I was afraid that we would face this kind of problem sometime in the future. When I was playing with the perf tests, I noticed some inconsistencies that I could not come up with reasonable explanations. Like repeating the same perf test multiple times and getting inconsistent results (20-30% difference in performance).

I'm not sure how Benchmark.js works but I was hoping there were some javascript library like [Criterion](http://www.serpentine.com/criterion/) (Haskell) and [Core_bench](https://blogs.janestreet.com/core_bench-micro-benchmarking-for-ocaml/) (OCaml) with a more robust methodology.

**Comment by blesh** [comment]
closing as inactive. I guess it it what it is for now.
