### ISSUE TITLE
ConnectableObservable, refCount, and connection state

### ISSUE THREAD

**Issue by trxcllnt** [ReactiveX/rxjs#1704]
@blesh @mattpodwysocki @benjchristensen @headinthebox

I'm revisiting `ConnectableObservable` and soliciting feedback on how to proceed so we can close our outstanding issues before release. Please chime in with additional thoughts or points I've overlooked.

##### `ConnectableObservable` connection state has become problematic

At the moment, `ConnectableObservable` caches and shares the same connection to the underlying source with all its subscribers. This means multiple calls to `refCount` share the same connection, which each `RefCountObservable` will choose to connect or disconnect based on its local subscription count. This is philosophically problematic, as the `RefCountObservable` can no longer guarantee referential transparency. For example:
```es6
import Rx from 'rx';

const numbers = Rx.Observable.interval(10).publish();
const firstFour = numbers.refCount().take(4);
const skipTwo = numbers.refCount().skip(2);

firstFour.subscribe(::console.log); // <-- prints 0, 1, 2, 3
skipTwo.subscribe(::console.log); // <-- prints         2, 3
```

In this example, the subscription count of `firstFour` drops to zero after taking four values. `skipTwo's`  subscription count remains at one, but `firstFour's` disposes the `numbers` connection anyway.

One potential solution to this problem is to move the refCount state to `ConnectableObservable`, so it can be shared and mutated alongside the connection subscription. This would eliminate the difference between multiple subscribers to a single `RefCountObservable`, and one subscriber to each of multiple `RefCountObservables`:
```es6
import Rx from 'rx';

const numbers = Rx.Observable.interval(10).publish();

// This behavior is identical...
const refCounted1 = numbers.refCount();
const refCounted2 = numbers.refCount();
refCounted1.take(5).subscribe(::console.log);
refCounted2.skip(5).take(20).subscribe(::console.log);

// ... to this behavior
const refCounted = numbers.refCount();
refCounted.take(5).subscribe(::console.log);
refCounted.skip(5).take(20).subscribe(::console.log);
```

I've attempted to brainstorm other alternatives that don't involve the `ConnectableObservable` maintaining connection state, but don't see any viable alternatives.

**Comment by Dorus** [comment]
Random idea, so I'm not sure if this make sense or would break anything:

Make `ConnectableObservable` work like refCount itself. If you call `connect` twice, you have 2 disposable connections. Require them both to be disposed/unsubscribed before the `ConnectableObservable` stops.

That way, the connection kept by `refCounted1` and `refCounted2` wont interfere.
