### ISSUE TITLE
Feature request: Add clearTimeout-like functionality to timeout* operators

### ISSUE THREAD

**Issue by frederikschubert** [ReactiveX/rxjs#1712]
In some use cases it would be helpful if the `timeout*` operators would accept an observable that had the possibility to clear the timeout. So when the observable that the timeout is subscribed to emits something and the "clearing" observable emits `true` in the timespan till the timeout is reached, the timeout is cleared.
One use case would be a spinner that is shown after a certain amount of time for long running actions but should not be shown for short actions.

**Comment by staltz** [comment]
I think you can achieve that with [switch](http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#instance-method-switch).

**Comment by frederikschubert** [comment]
Alright I figured it out. Thanks for the suggestion!
