### ISSUE TITLE
Subject isUnsubscribed should stay `false` after subject is unsubscribed, errored or completed

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#172]
I noticed that whenever Subject was rewritten there was a change that flags `isUnsubscribed` back to `false` at the end of `_complete`. I think that should stay `true` because Subjects should not be able to be resubscribed to after they're completed.

The lines of code in question are [here](https://github.com/ReactiveX/RxJS/blob/6d9f6ae63867efe9e2f52e17e9f7abae1d946da5/src/Subject.ts#L164) and [here](https://github.com/ReactiveX/RxJS/blob/6d9f6ae63867efe9e2f52e17e9f7abae1d946da5/src/Subject.ts#L148)

@trxcllnt can you shed some light on what the intent was here?

**Comment by trxcllnt** [comment]
@blesh that line is only to block `next`-ing back into the Subject from an Observer's `complete` or `error` callbacks. The `errorSignal`/`completeSignal` flags will catch subscribers that attempt to subscribe to the Subject after it's received an `error`/`complete` message.
