### ISSUE TITLE
SystemJs Builder - Error calculate canonical name

### ISSUE THREAD

**Issue by meriturva** [ReactiveX/rxjs#1725]
We are trying to build our solution with SystemJs Builder without success.
RxJs version: 5.0.0-beta.6

We have problems and we had already some help from SystemJs guy: https://github.com/systemjs/builder/issues/587#issuecomment-220835913

We have developed a simple project to test build process:

https://github.com/meriturva/SystemJsBuilder-587

Just clone it and run `gulp build` and you will see problems related to RxJs package:

```
error { [Error: Error tracing ./node_modules/rxjs/Subject.js at file:///H:/Projects/github.com/SystemJsBuilder-587/node_modules/rxjs/Subject.js
        Loading ./node_modules/@angular/core/core.umd.js
        Loading app/main.js
        Unable to calculate canonical name to bundle file:///H:/Projects/github.com/SystemJsBuilder-587/node_modules/rxjs/Observable. Ensure that this module sits within the baseURL or a wildcard path config.]
  originalErr: [Error: Unable to calculate canonical name to bundle file:///H:/Projects/github.com/SystemJsBuilder-587/node_modules/rxjs/Observable. Ensure that this module sits within the baseURL or a wildcard path config.] }
```

We also would like to use umd version but we need WebSocket class that it is not already included https://github.com/ReactiveX/rxjs/issues/1506

Any ideas how to solve it?
Thanks.
Diego

**Comment by blesh** [comment]
Related PR #2381

**Comment by benlesh** [comment]
I don't think this is any longer an issue.
