### ISSUE TITLE
Subject<void> and next() optional value

### ISSUE THREAD

**Issue by artaommahe** [ReactiveX/rxjs#1728]
Can we make Subject's `next()` method  `value` optional? It's usefull for some use cases then u just need to trigger some action without any data providing to it
```ts
this.smthSubject = new Subject<void>();
...
this.smthSubject.next();
```
currently it will fall with error
```
Error TS2346: Supplied parameters do not match any signature of call target.
```
My current usecase is to trigger ng1(2) directive action. Directive is scrollbar wrapper and i need to trigger scrollbar update on some parent element events. I used $scope.$broadcast() for this with ng1, but currently i write ng1 code in TS with ng-metadata for further upgrading to ng2 and in search for this use case implementation without scope pubsub.

**Comment by trxcllnt** [comment]
Yes, we should do this.
