### ISSUE TITLE
TSLint is really slow

### ISSUE THREAD

**Issue by benlesh** [ReactiveX/rxjs#1731]
Do we have any other alternatives to TSLint?

cc/ @alexeagle @robwormald @david-driscoll

**Comment by david-driscoll** [comment]
What part feels slow for you?  I've never had large issues with perf on TSLint itself, but that's just my experience.

Does your editor have a TSLint plugin to help linting warning as you go?
(without knowing the setup it's hard to say!)

**Comment by alexeagle** [comment]
There is discussion going on about a replacement that's based on TS language services (tslint can't do cross-file program analysis at present because it can't boot up a typechecker)
Do you have a link on your CI or somewhere showing the timing?

**Comment by trxcllnt** [comment]
@alexeagle our current travis config runs `npm install && npm run lint` [together](https://travis-ci.org/ReactiveX/rxjs#L294), so we don't have the linter timing isolated. Together they took ~125s in the most recent build.

**Comment by kwonoj** [comment]
linking https://github.com/palantir/tslint/issues/1131 for reference.

**Comment by kwonoj** [comment]
just fyi, maybe https://github.com/eslint/typescript-eslint-parser this can shed light in further. (long, long time later since it's experimental for now..)

**Comment by prabirshrestha** [comment]
When **Lint extensions** land in typescript it could solve the perf problem. https://github.com/Microsoft/TypeScript/pull/10162

**Comment by kwonoj** [comment]
This one is not immediate concern anymore by lint-stage hooks and we can improve over once we have better way, closing.
