### ISSUE TITLE
TypeError: Rx.Observable.case is not a function

### ISSUE THREAD

**Issue by miguelmota** [ReactiveX/rxjs#1733]
Is `Rx.Observable.case` available is RxJS5? If not, what is the closest alternative to being able to switch observables based on a flag?

**Comment by roganov** [comment]
I believe it's quite easy to implement yourself (not 100% equivalent):
```js
function caseO(selector, sources, defaultO) {
  return Rx.Observable.defer(() => sources[selector()] || defaultO);
}
```

**Comment by miguelmota** [comment]
@roganov thanks for the clarification
