### ISSUE TITLE
Add subscribeOnError (and friends) to the migration guide.

### ISSUE THREAD

**Issue by IanVS** [ReactiveX/rxjs#1734]
**RxJS version:** 5.0.0-beta.8

It seems that [`subscribeOnError`](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/subscribeonerror.md) and friends `subscribeOnNext` and `subscribeOnCompleted` are missing.  Perhaps that's intentional, but it is also not mentioned in the [migration guide](https://github.com/ReactiveX/rxjs/blob/master/MIGRATION.md).  Is the intent to add those convenience methods, or should the migration guide be updated?

Thanks!

**Comment by blesh** [comment]
Yes, we need to just mention that in the migration guide.   `subscribe({ error(err) { /* do something */ } })` will work. Or `subscribe(null, fn)`

**Comment by benlesh** [comment]
Closing as stale.
