### ISSUE TITLE
Catch documentation is missing

### ISSUE THREAD

**Issue by Sinewyk** [ReactiveX/rxjs#1735]
http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#instance-method-catch is dead.

This link was from the cool utility when asked "I have one existing Observable, and when an error occurs I want to start a new Observable." ... which obviously brought me to catch which seems to be missing.

**Comment by staltz** [comment]
Documentation for operators is still work in progress.

**Comment by blesh** [comment]
this exists now.
