### ISSUE TITLE
Add flow typings to the package(s)

### ISSUE THREAD

**Issue by blesh** [ReactiveX/rxjs#1742]
https://github.com/facebook/nuclide has partial flow-typings for RxJS 5. I think we should look into adding these to our distribution.

Related: https://github.com/facebook/nuclide/issues/529

**Comment by kwonoj** [comment]
I think this can be closed on behalf of flowtyped (https://flowtype.org/blog/2016/10/13/Flow-Typed.html) which already shipped definition for v5. (https://github.com/flowtype/flow-typed/tree/master/definitions/npm/rxjs_v5.0.x)

**Comment by apaatsio** [comment]
I think this should be reopened. The definition for RxJS in `flow-typed` is incomplete and inconsistent. There was an attempt to fix some issues (https://github.com/flowtype/flow-typed/pull/427) but this seems to be abandoned.

I believe it would lead to much more useful end result if the flow type definitions were a responsibility of the RxJS project itself.

**Comment by rgbkrk** [comment]
I've been making PRs and hope it stays updated: https://github.com/flowtype/flow-typed/pull/1616

Otherwise, wow do I wish for the day when we can generate the most basic of flow definitions from typescript.

**Comment by GAntoine** [comment]
@rgbkrk You can use https://github.com/joarwilk/flowgen to translate basic definitions.
