### ISSUE TITLE
npm linking consumer with library causes TS2322: Observable not assignable to Observable

### ISSUE THREAD

**Issue by vankeer** [ReactiveX/rxjs#1744]
**RxJS version:** 5.0.0-beta.6 and also tried npm linking with master today - no change

**Code to reproduce:**

You need:
- A library that exposes a method returning an Observable ([example](https://github.com/vankeer/ng2-example-library/blob/master/src/services/wiki.service.ts#L11))
- A consumer that consumes this method and returns an Observable as well ([example](https://github.com/vankeer/ng2-example-consumer/blob/master/src/client/app/%2Bwiki/wiki.component.ts#L32-L34))
- `npm link` the two before building

Example:

```
git clone https://github.com/vankeer/ng2-example-library.git
cd ng2-example-library
npm i
npm link
cd ..

git clone https://github.com/vankeer/ng2-example-consumer
cd ng2-example-consumer
npm i
npm link ng2-example-library
gulp build.dev
```

**Expected behavior:**

The library and the consumer build normally.

**Actual behavior:**

The consumer throws this error:

> src\client\app\+wiki\wiki.component.ts(33,12): error TS2322: Type 'Observable<any[]>' is not assignable to type 'Observable<any[]>'.
> Property 'source' is protected but type 'Observable<T>' is not a class derived from 'Observable<T>'.

**Additional information:**

This only happens when `npm link`ing the repos.

One way to avoid this problem is by having rxjs methods return an interface for Observable instead of Observable. Of course, this would require a rather large refactoring. PR for this suggested change: #1741 

Another way to avoid the problem is by explicitly installing the typings in the consumer (have not managed to do this yet with this specific example though).

**Comment by blesh** [comment]
It's probably that both libraries should have `rxjs` as a peer dependency, rather than a direct dependency. You'd run into this issue with any library that passed through a type like that. I'm not sure there's anything rxjs can do about it.

**Comment by vankeer** [comment]
Unfortunately having `rxjs` as peer dependency does not fix this problem. I updated my example repos.

I am unsure how to fix this (besides explicitly installing typings in the consumer) and I don't quite understand why this is not an issue for more people? Aren't more people npm linking different libraries like this and running into this same problem? Not sure what I'm missing.

**Comment by blesh** [comment]
@vankeer oh, to clarify, this is a TypeScript build failure? cc/ @david-driscoll

**Comment by david-driscoll** [comment]
I believe it's an issue with the compiler still. I get the issue as well.

Work around is pretty easy, at least for working locally. Just make a
node_modules in the parent directory and put rxjs and symbol observable in
there. Less than ideal but it works for now.

I'll test with typescript@next and see if its been resolved.
On Thu, Jun 16, 2016 at 8:57 PM Ben Lesh <notifications@github.com> wrote:

> @vankeer <https://github.com/vankeer> oh, to clarify, this is a
> TypeScript build failure? cc/ @david-driscoll
> <https://github.com/david-driscoll>
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/ReactiveX/rxjs/issues/1744#issuecomment-226655101>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABNdpYMcDd2GhmHO0Xk0I-f7lhm1Zk-Aks5qMfDegaJpZM4IuuAe>
> .
>
-- 
Thanks,
David

**Comment by vankeer** [comment]
@blesh Yup, it's a Typescript build failure. Thanks for following up this issue

@david-driscoll Thanks for your response. Using typescript@next did not solve the issue for me. Also, I'm not sure what you mean with installing rxjs and symbol-observable in the parent dir to fix the issue, since that alone is not enough to fix it for me. But, deleting `[consumer]/node_modules/[library]/node_modules/rxjs` does solve the issue for me, since Typescript will then rely on `[consumer]/node_modules/rxjs` for typings I guess. I thought that should be the behavior when specifying rxjs as peerDependency, but it's not apparently.

It's a bit of a hassle, especially when working with lots of libraries, but it's another workaround for this issue, other than installing typings explicitly.

**Comment by david-driscoll** [comment]
This may be a decent case to give a change like https://github.com/ReactiveX/rxjs/pull/1741 a second look.

**Comment by fredrikbonander** [comment]
I think this https://github.com/Microsoft/TypeScript/issues/6496 is related, unclear if it's gonna be fixed from the TS side.

**Comment by kwonoj** [comment]
As similar to https://github.com/ReactiveX/rxjs/issues/2092 I don't think there's viable option on RxJS codebase side at this moment, rather to wait compiler side update and close this issue. /cc @blesh for visibility, please reopen if needed.
