### ISSUE TITLE
WebSocketSubject not applying operators

### ISSUE THREAD

**Issue by fingermark** [ReactiveX/rxjs#1745]
**RxJS version:**
5.0.0-beta.8

**Code to reproduce:**

http://jsbin.com/kidawe/edit?js,console

```
const url = 'ws://ws.websocketstest.com:80/service';

Rx.Observable
  .webSocket({
    url: url,
    resultSelector: (e) => e.data
  })
  .map((x) => 'prefix-' + x)
  .map(x => x)
  .subscribe((x) => console.log(x));
```

**Expected behavior:**

`prefix-connected,`

**Actual behavior:**

`connected,`

**Additional information:**

I ran into an issue where I was trying to map on Observable.webSocket and noticed the `map`s weren't getting invoked.  Others have confirmed the bug.  See more here:

https://github.com/redux-observable/redux-observable/issues/42

**Comment by jayphelps** [comment]
Just to clarify, if you only apply a single operator, it works. `Observable.webSocket().map(x => x)` but if you apply more than one, none of them get applied. `Observable.webSocket().map(x => 'prefix-' + x).map(x => x)`

**Comment by blesh** [comment]
Ouch... nasty. Def a result of #1701 ... :\ I did that.
