### ISSUE TITLE
Cannot find property defineProperty of undefined

### ISSUE THREAD

**Issue by rkichenama** [ReactiveX/rxjs#1753]
Using beta.8, I get an error in webpack that Object does not have defineProperty. When I debug, I find the issue around

```javascript
 function(module, exports, __webpack_require__) {
  'use strict';

  Object.defineProperty(exports, "__esModule", {
    value: true
  });
  exports.timer = undefined;

  var _TimerObservable = __webpack_require__(348);

  var timer = exports.timer = _TimerObservable.TimerObservable.create;
  //# sourceMappingURL=timer.js.map
}
```

**Comment by kwonoj** [comment]
Can I possibly ask small repo to reproduce this?

**Comment by david-driscoll** [comment]
Also what browser are you testing in?

**Comment by kwonoj** [comment]
@rkichenama , please feel freely to update / create new issue once you're avail to provide small repo to reproduce. Let me close issue for now until have more details to dig in.
