### ISSUE TITLE
Subscribing to an observable including a BehaviorSubject seems to force needless reevaluation when future subscriptions occur

### ISSUE THREAD

**Issue by labriola** [ReactiveX/rxjs#1762]
**RxJS version:**
5.0.0-beta.8

**Code to reproduce:**
const user$ = new BehaviorSubject('bob');
const userData$ = user$.switchMap(function (user) {
    console.log('userData$ switchmap triggered');
    return Observable.interval(100).take(1);
});

userData$.subscribe( x=>console.log( 'user data sub ' +  x) );
userData$.subscribe( x=>console.log( 'user data sub ' +  x) );

**Expected behavior:**
Console would output a single line of 'userData$ switchmap triggered' and that a later subscription would not cause the switchMap to trigger.

**Actual behavior:**
The output is received twice and the observable in the switchMap is recreated

**Additional information:**
This may be unavoidable but subscribing to the observable switchMap-ed from the BehaviorSubject seems to force the next() as away of informing the new subscription of the initial/last value derived from the subject, Ultimately the issue is that there is a potential side-effect to the act of subscribing when a BehaviorSubject is used initially

**Comment by labriola** [comment]
Sorry for the edit. Simplified the case to make it clearer

**Comment by trxcllnt** [comment]
@labriola hey Mike, good to see you again. I know you closed this issue, but feel free to reach out if you have any more questions about why Observables behave this way. Cheers.
