### ISSUE TITLE
Why does import { Observer } from 'rxjs' show undefined?

### ISSUE THREAD

**Issue by fingermark** [ReactiveX/rxjs#1768]
**RxJS version:**

rxjs@5.0.0-beta.9

**Code to reproduce:**

```
import { Observable, Observer } from 'rxjs';
// import { Observer } from 'rxjs/Observer'; // also fails
console.log('Observable', Observable);
console.log('Observer', Observer);
```

**Expected behavior:**

```
Observable function() { ... }
Observer function() { ... }
```

**Actual behavior:**

```
Observable function() { ... }
Observer undefined
```

**Additional information:**

This seems trivial and I'm sure I'm doing something wrong.

**Comment by david-driscoll** [comment]
`Observer` is strictly an interface, and isn't directly created by the user.  Instead you to create an observer, you need to use `Observable.create`, and then when you subscribe to the resulting observable, an `observer` will be created for you.

```typescript
Observable.create(observer => {
  observer.next(1);
  observer.next(2);
  observer.next(3);
  observer.complete();
});
```

**Comment by kwonoj** [comment]
Or you could use object fulfills requirement of `observer` does, having `next`,`error`,`complete` or partial of it. Any case @david-driscoll 's correct, `observer` itself is just interface and for actual implementation you may need instantiation which implements those interface.

**Comment by blesh** [comment]
I'm going to close this since it was answered adequately. @fingermark, please do reopen if you feel the answers are incorrect.
