### ISSUE TITLE
symbol-observable/lib.js does not exist

### ISSUE THREAD

**Issue by hlobil** [ReactiveX/rxjs#1769]
**RxJS version:**
rxjs 9 (upgraded from version 8), version 1.0.0 of symbol-observable

**Code to reproduce:**

**Expected behavior:**
should use /node_modules/symbol-observable/index.js

**Actual behavior:**
I am getting 404 error as it's looking for the following file.
/node_modules/symbol-observable/lib.js

**Additional information:**
System.js loader

map {
'symbol-observable': '/node_modules/symbol-observable'
}
packages {
'symbol-observable': {defaultExtension: 'js', main: 'index.js'},
}

**Comment by kwonoj** [comment]
I think this is related to https://github.com/ReactiveX/rxjs/pull/1766 . What's version of `symbol-observable`?

**Comment by blesh** [comment]
> 1.0.0 of symbol-observable

Yeah, we're stuck on 0.2.* until we can fix whatever is going on with #1766

**Comment by hlobil** [comment]
if I change from 
module.exports = require('./lib/');
to 
module.exports = require('./lib/index');

seems to fix my loading problem, I just don't know if that is the real fix for the issue.
