### ISSUE TITLE
chore(subject): remove lift override from Subject

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#177]
This was a hotly contested thing a few weeks ago with @jhusain, @trxcllnt and myself. I believe @headinthebox was also involved in those discussions.

The resolution, at that time, was to not change the semantics of operators coming from Subject (such as `mySubject.filter(x => x > 2)` for example), and have them continue to return Observable, rather than Subjects.

[I think this code here may have snuck into the codebase when it was experimental](https://github.com/ReactiveX/RxJS/blob/47b178bddba65272f957602b8a6c69f79cc73da6/src/Subject.ts#L36-L40)... it basically means that all operators from Subject will return a Subject. While I *personally* find this to be interesting and cool, it was agreed that we would keep the library as-is for that case, since anyone that *did* want that functionality could simply patch the `lift` method on Subject to make that happen.

**Comment by mattpodwysocki** [comment]
@blesh I also talked with @jhusain about this and came to the conclusion this is a bad idea given the hot nature of Subjects versus Observables so the behavior would no longer be consistent.

**Comment by trxcllnt** [comment]
@mattpodwysocki which functionality is no longer consistent? Everything still works the same way as far as I can tell.

**Comment by headinthebox** [comment]
@mattpodwysocki AFAIK the *observer* side of the subject would still be the original subject. I.e. if you do `subject_A_B.map(f_B_C)`, the result would be `subject_A_C` (using fantasy JS type notation). I think this works just fine.

**Comment by blesh** [comment]
Well, like I said... 

> I personally find this to be interesting and cool

Can anyone come up with an *actual* scenario where this breaks down? Like a code example? I can't think of anything...

Otherwise, I'm willing to close this issue and leave the Subject lift method in there. I'll let this simmer for a while.

**Comment by headinthebox** [comment]
Why don't we leave it in and see if it meets your expectations. Personally I never use subjects so I do not feel your pain, but I would like to see if this actually works, and then I'll steal it for RxMobile.

**Comment by blesh** [comment]
So, thinking about this some more... what happens if you have a delay or something in your chain?

```js
let sub1 = new Subject();
let sub2 = sub1.delay(60000);

sub2.subscribe(x => console.log('> ' + x), null, () => console.log('done'));

sub1.next(1);
sub1.next(2);
sub1.complete();

setTimeout(function(){
  sub1.next(3); // sub1 is unsubscribed, so you can't next into it
  sub2.next(4);  // but what about sub2? It's not done yet!
}, 1000);
```

I'm not sure how this pans out, usability wise.

**Comment by headinthebox** [comment]
I think that is exactly what you expect, if you draw the wire diagram.

**Comment by blesh** [comment]
@headinthebox maybe I'm dumb, but I guess I was saying I don't know what to expect in that case.

**Comment by trxcllnt** [comment]
@blesh `sub2` would print out `> 4`, then 59s later print out `done`.

**Comment by blesh** [comment]
@trxcllnt I see. It seems like operating on a Subject might incur a lot of extra allocations (observers lists, observer methods, etc)... maybe people should opt into this behavior? Something like `subject.compose()` that returns a `ComposableSubject` with `lift` implemented?

**Comment by blesh** [comment]
@trxcllnt also in the case of a web socket subject returned by `fromWebSocket` in `Rx-DOM` for example... next-ing into that subject will send over the web socket... if I operate on that subject, with say `filter()` is the returned subject going to still have that same behavior when I call `next` on it? How would that work?

**Comment by trxcllnt** [comment]
@blesh hm, nevermind. I think I was mistaken earlier.

**Comment by blesh** [comment]
So do you see what I was getting at with my `sub1` `sub2` example above?

**Comment by benjchristensen** [comment]
I don't like the idea of `subject.list(operator)` return a `Subject`. This is exposing `onNext` entry points into the stream at every `lift` along the way. 

As the `Subject` is passed around a code-base (and since Subjects are hot), anyone can `lift` it, retain a reference, pass it on. Then any of them can `onNext` to it whenever they wish. This is confusing. 

Also, what side of the `Subject` is `lift` applying to, the `Observer` or `Observable`? It can't apply to both. 

I think that composition should only happen on the `Observable` side, and once you start using `lift` on it it loses the `Observer` side as that should be retained only at the source. 

```js
var s1 = new Subject();
var s2 = s1.map(s -> getSomething(s));
var s3 = s2.doOnNext(s -> ... side effect here ...);

// now another chain off of s1
var s4 = s1.flatMap(s -> doAsyncFetch(s));

s1.next(someValue);
s2.next(someOtherValue);
s3.next(aValue);
s4.next(data);
```

Does nexting into `s3` skip the `map` defined on `s2`, or does it somehow flow through the top? What are the types of `next` values? Are they always the type `T` of `s1`, or does the `Observer` side changes from `s1` to `s2`?

What happens with the `s4.next`? Does that also flow through `s2` and `s3`?

I find it a very confusing API if a `Subject/Observer` is returned at each `lift`.

**Comment by blesh** [comment]
@benjchristensen ... nexting into any of the subjects up there nexts into the observer in the "lead" subject (s1). Essentially it's doing the same thing it would do if it were "unlifted" and returning only Observables, but it's wrapping it in a Subject and gluing on the original Observer.

At this point, I think my *only* concern is the overhead of creating underlying observer lists etc. I think we should build some macro perf tests and test both the lifted Subject and the unlifted Subject. If they perform the same, I think we can probably leave them in there.

**Comment by blesh** [comment]
I've created this issue for tracking the creation of macro perf tests that should help us: #262

**Comment by trxcllnt** [comment]
@blesh the intermediate BidirectionalSubjects created by lift don't have their own list of subscribers afaik.

**Comment by blesh** [comment]
This doesn't seem to have any performance or ergonomic impacts. Closing for now.
