### ISSUE TITLE
Discuss: stop publishing system bundle 

### ISSUE THREAD

**Issue by jeffbcross** [ReactiveX/rxjs#1776]
The original reason I added the systemjs bundle was because angular 2 was publishing system bundles in our docs, and was distributing them in our npm package. Now we only publish umd bundles alongside our commonjs and es6 modules. Since maintaining the system bundles takes some work, I recommend stop publishing system bundles unless others in the community are depending on them.

**Comment by blesh** [comment]
This sounds good to me. Any objections? I'll leave this open for a week or so to find out.

**Comment by kwonoj** [comment]
Just curiosity, (since I'm not familiar with SystemJS) after stop publishing systemjs bundle, what would be needed if anyone would like to use Rx as SystemJS?

**Comment by robwormald** [comment]
@kwonoj it would just mean using the modules individually, vs a big bundle blob of code... SystemJS will load basically any format (ES6, CJS, etc...)

**Comment by kwonoj** [comment]
got it, thanks for explanation.

**Comment by kwonoj** [comment]
Closing via #1781 /
