### ISSUE TITLE
Older version of symbol-observable still getting installed with beta.9

### ISSUE THREAD

**Issue by martypdx** [ReactiveX/rxjs#1785]
**RxJS version:** 5.0.0-beta.9

**Code to reproduce:** 

```npm i rxjs-es```

Also have example [repo](https://github.com/martypdx/rollup-rxjs) where I identified the issue and have a workaround.

**Expected behavior:**

Installs and uses `1.0.1` ES6ified version of `symbol-observable`

**Actual behavior:**

Look in `node_modules/rxjs-es`, there's a child `node_modules` folder that has `v0.2.4`

(side questions: shouldn't it be a sibling in top-level `node-modules`?)

**Additional information:**

Using `rollup` with `RxJS` which works great except that CJS require gets stuck in from older `symbol-observable`

**Comment by kwonoj** [comment]
It is expected. PR https://github.com/ReactiveX/rxjs/pull/1772 has been checked in after publishing beta.9,  so latest package still points at old version of `symbol-observable`. Next package will point latest package dependencies. Let me close this issue for now, please feel freely reopen / file other issues if there's other issues unresolved.
