### ISSUE TITLE
 Invalid module name in augmentation, module '../../Observable' cannot be found

### ISSUE THREAD

**Issue by giorgiopiatti** [ReactiveX/rxjs#1786]
version: 5.0.0-beta.6
When try to debug a ionic 2 app the debugger show me that error : Invalid module name in augmentation, module '../../Observable' cannot be found. on

 ```
\node_modules\rxjs\add\observable\bindCallback.d.ts line 2 and in all the file where is:
declare module '../../Observable' {
  ...... {
       .....
    }
)



```

**Comment by kwonoj** [comment]
Would you able to share what version of typescript compiler do you use?

**Comment by kwonoj** [comment]
Before having additional detail, I think this is related to module augumentation feature introduced at typescript@1.8. If you could verify debugger configuration and it's using older version, please try to bump up it. As similar to https://github.com/ReactiveX/rxjs/issues/1696, lot of different IDE / debugger might have its own configuration of compiler not using local npm tsc module / or global npm module.

**Comment by kwonoj** [comment]
Let me close this issue as I currently believe this can be resolved by compiler configuration. Please fell freely reopen / create new issue if there's problem persists, it'd be appreciate to provide small repo to reproduce issue.
