### ISSUE TITLE
Use cases: operators important for Cycle.js

### ISSUE THREAD

**Issue by staltz** [ReactiveX/RxJS#179]
Ben Lesh asked me to list a couple of important and common operators when developing Cycle.js applications, since I'm planning to update its RxJS version to ReactiveX/RxJS as soon as it's stable.

- [x] map
- [x] filter
- [x] merge
- [x] scan
- [x] catch
- [x] flatMap
- [x] flatMapLatest
- [x] just
- [x] empty
- [x] never
- [x] combineLatest
- [x] withLatestFrom
- [x] startWith
- [x] take(Until)
- [x] skip(Until)
- [x] publish
- [x] replay or "publishReplay"
- [x] publishBehavior (multicast with a BehaviorSubject)
- [x] refCount
- [x] connect
- [x] switchAll
- [x] mergeAll
- [x] bufferWithCount or pairwise
- [x] debounce

We can tick the checkboxes for the ones that are implemented already.

**Comment by blesh** [comment]
refCount is done, I believe

**Comment by staltz** [comment]
Correct

**Comment by blesh** [comment]
This seems to be complete as of today. Closing this issue. If I'm wrong, let me know @staltz and I'll reopen.

**Comment by staltz** [comment]
Yes! Seems great. I'd add subjects to that list too, but I know they are implemented already. The list above is just the minimum to get most things rolling.
