### ISSUE TITLE
Typing files seems to assume ES6 target.

### ISSUE THREAD

**Issue by evansb** [ReactiveX/rxjs#1793]
**RxJS version:** 5.0.0-beta.9

**Code to reproduce:**
1. Create TypeScript project, in `tsconfig.json` set compiler target to ES5
2. Import RxJS
3. Compile it using `tsc -p`

**Expected behavior:**
No error

**Actual behavior:**
```
node_modules/@reactivex/rxjs/dist/cjs/Observable.d.ts(10,66): error TS2304: Cannot find name 'Promise'.
```

**Additional information:**
As expected, it is fine if the compilation target is changed to ES6.

**Comment by evansb** [comment]
Nevermind, I found that installing `es6-promise` or `es6-shim` typings globally in the project will fix the issue.

**Comment by kwonoj** [comment]
You can configure local type definition as well, such as https://github.com/ReactiveX/rxjs/issues/1604#issuecomment-222493862 way.
