### ISSUE TITLE
Remove Observable.from projection function and context argument? 

### ISSUE THREAD

**Issue by blesh** [ReactiveX/rxjs#1795]
I think we should investigate whether or not to leave the projection function and context argument in the `Observable.from` signature. Currently, my gut tells me "no" because:

1) It's minimally useful. We could get the same behavior in a more readable way with `map`, and any perf concerns could be mitigated with some perf work on collapsing sync operations like map, reduce, scan, filter, etc.

2) It's not in @zenparsing's spec. I think Rx will always have the need to have the scheduler argument, but I wouldn't want to conflict with any additional arguments added to the real spec down the road.

3) I hate `context` arguments anyhow. They seem silly in the face of the more explicit (and now reasonably performant) `.bind()` method.

4) I've literally never seen a need to use this.

5) It should slightly reduce the code size for `Observable.from`.

Related #1788

**Comment by blesh** [comment]
cc/ @chrisprice @jhusain @mattpodwysocki @staltz @kwonoj

**Comment by kwonoj** [comment]
While I'm in bit favor of this, I'm curious of original design decisions of having projections, and possibly any solid case projection can do but `map` can't. (I couldn't think of myself..)

**Comment by staltz** [comment]
I agree with Ben.

**Comment by chrisprice** [comment]
As there seems to be more sentiment in favour of this than against it, I'll modify my PR to remove the projection function and context arguments

**Comment by chrisprice** [comment]
PR #1788 updated

**Comment by blesh** [comment]
This was closed by #1788
