### ISSUE TITLE
Import SerialDisposable from RxJS 4.x

### ISSUE THREAD

**Issue by paulcbetts** [ReactiveX/rxjs#1796]
SerialDisposable seems to be missing as a concept from RxJS 5.x, it's quite useful to implement the "I have exactly Zero Or One of a Subscription at all times" pattern.

**Comment by blesh** [comment]
Currently, we just have one Subscription, it's essentially CompositeSubscription. While a SerialSubscription might allow for more expressiveness, It's debatable how much value it would add given that it may (or may not) increase the size of the library.

In truth, I think consumers of RxJS should do less imperative subscription management (which is what SerialSubscription would be used for) and more functional subscription management using things like `switchMap` and `takeUntil` to manage their subscriptions.

**Comment by paulcbetts** [comment]
Crying as I implement this from scratch again nbddddd

**Comment by deviousasti** [comment]
@blesh Their value is in writing Rx operators, not in actual observable streams. Why you are going to such lengths to break the implementation, I will never know.

**Comment by kwonoj** [comment]
just fyi, if anyone's interested in using `serialdisposable` immediately, @paulcbetts created implementation at https://github.com/paulcbetts/rxjs-serial-subscription .

**Comment by kwonoj** [comment]
I don't think we'll going to have this in 5 at least, closing as inactive. We'll revisit usecases if it need to be included in core but at this moment I believe user level module serves well enough.
