### ISSUE TITLE
Observable closed property

### ISSUE THREAD

**Issue by calebmer** [ReactiveX/rxjs#1798]
The [`es-observable`](https://github.com/zenparsing/es-observable#subscriptionobserver) specification calls for a `closed` property on `SubscriptionObserver`. It seems like rxjs has a similar property called [`isUnsubscribed`](https://github.com/ReactiveX/rxjs/blob/master/src/Observer.ts), but according to the specification it should be called `closed`. Is this intended behavior?

For more information see this issue: https://github.com/zenparsing/es-observable/issues/90

**Comment by SekibOmazic** [comment]
`closed` method came later to the specification (https://github.com/zenparsing/es-observable/commit/b0535051f574ffa20f9a4414681a24294c8614fc)
`isUnsubscribed` is longer a part of RxJS5. But I guess it will be aligned with the specification.

**Comment by blesh** [comment]
Yeah, I think we should rename `isUnsubscribed` to `closed`, honestly. The intent there is the same. It was mostly just sitting there because I anticipated more bike shedding about the name.

cc/ @zenparsing

**Comment by calebmer** [comment]
Opened a PR to make this change: https://github.com/ReactiveX/rxjs/pull/1844
