### ISSUE TITLE
Incorrect AsyncSubject behaviour

### ISSUE THREAD

**Issue by unao** [ReactiveX/rxjs#1800]
**RxJS version:** https://cdnjs.cloudflare.com/ajax/libs/rxjs/5.0.0-beta.9/Rx.umd.js

**Code to reproduce:**

```javascript
var subject = new Rx.AsyncSubject();

subject.next(1);
subject.complete();
subject.subscribe(v => console.log(v));

subject.next(2);
var sub = subject.subscribe(v => console.log(v));
```
[PLNKR](http://plnkr.co/edit/XYZTee4hxrW0Lh3cTeZy?p=preview)

**Expected behavior:**
`subject.next(2)` should have no effect.

**Actual behavior:**
It is possible to publish values after the stream completed.
`1` is the result of the async computation and it should be used for any future `subscribe`s.

**Additional information:**
afaik, it violates the Observable interface.

**Comment by unao** [comment]
This one is pretty interesting as well: 
 
```javascript
var subject = new Rx.AsyncSubject();

subject.asObservable().delay(0).subscribe(v => console.log('delayed', v));

subject.next(1);
subject.complete();
subject.subscribe(v => console.log(v));

subject.next(2);

subject.asObservable().subscribe(v => console.log(v));
```

[PLNKR](http://plnkr.co/edit/XYZTee4hxrW0Lh3cTeZy?p=preview)

**Comment by kwonoj** [comment]
indeed, seems current implementation missing guard to `next` when it's completed.
