### ISSUE TITLE
Observable.pairs(dict) missing in RxJS 5

### ISSUE THREAD

**Issue by appsforartists** [ReactiveX/rxjs#1804]
**RxJS version:**
5.0.0-beta.9

**Code to reproduce:**
`Observable.pairs({a: 1, b: 2})`

**Expected behavior:**
An Observable of `[['a', 1], ['b', 2]]` 

**Actual behavior:**
`Observable.pairs is not a function`

**Additional information:**
https://github.com/Reactive-Extensions/RxJS/issues/704 says the correct way to convert a dictionary to an Observable is with `Observable.pairs(dict)`, but that doesn't seem to be defined in RxJS 5.  Is there a creation operator for dictionaries/maps/Objects?

One of the nice things about collection libraries like Immutable and underscore is that they treat both lists and dictionaries as collections, letting you {map, filter, reduce} as appropriate.  To avoid bloat, it would be nice to use RxJS's collection methods for this, but I don't see any native way to operate on an Object.

**Comment by kwonoj** [comment]
Currently not all of operators are migrated from RxJS 4 to RxJS 5 yet.
