### ISSUE TITLE
rxjs-es build cannot be complied by Babel

### ISSUE THREAD

**Issue by mitchlloyd** [ReactiveX/rxjs#1806]
@blesh As a follow up from https://twitter.com/BenLesh/status/750378713905192960, here is an issue for this workaround that I've seen in a couple of code bases.

**RxJS version:**

5.0.0-beta.9

**Code to reproduce:**

Compile rxjs source with Babel.

See existing workarounds as example:
* https://github.com/mike-north/ember-rx-shim/blob/master/index.js#L10
* https://github.com/orbitjs/ember-orbit/blob/master/index.js#L28

**Expected behavior:**

Babel compiles rxjs-es source without errors.

**Actual behavior:**

Babel throws Unexpected Token error similar to this: https://babeljs.io/repl/#?evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-2&code=let%20Scheduler%20%3D%20%7B%0A%20%20asap%2C%0A%20%20async%2C%0A%20%20queue%2C%0A%20%20animationFrame%0A%7D%3B

**Comment by kwonoj** [comment]
Is my understanding correct that needed thing is update `Scheduler` object to not use enhanced object literal?

**Comment by blesh** [comment]
@mitchlloyd that looks like a problem with Babel. `async` might be a new keyword, but it's still a valid variable name.

For those reading this, the problem appears to be to name of the async scheduler: `Scheduler.async`

Babel is unable to process creating an object literal like so:

```js
let foo = 'whatever';
let async = 'test';
let obj = {
  async,
  foo
};
```

Interestingly, this works:

```js
let foo = 'whatever';
let async = 'test';
let obj = {
  foo,
  async
};
```

**Comment by kwonoj** [comment]
I just gave it a try bit more, and came to agree with @blesh . If you're enabling `stage-3` preset or above in babel, it fails to build. (Assume `transform-async-to-generator` is culprit maybe?) 
https://babeljs.io/repl/#?evaluate=true&lineWrap=true&presets=es2015&code=let%20Scheduler%20%3D%20%7B%0A%20%20asap%2C%0A%20%20async%2C%0A%20%20queue%2C%0A%20%20animationFrame%0A%7D%3B

**Comment by blesh** [comment]
I have a fix inbound. Just a workaround we can do to accommodate until babel's issue is resolved.

**Comment by mitchlloyd** [comment]
Awesome! Agreed that this appears to be a Babel bug. It's kind of rxjs to include a workaround so the community can be shielded until a fix for Babel can land.

Issued filed by @blesh: https://phabricator.babeljs.io/T7479
