### ISSUE TITLE
AjaxObservable: ajax.get() sync error on xhr.send() if name not resolved

### ISSUE THREAD

**Issue by blesh** [ReactiveX/rxjs#1810]
**RxJS version:** beta.9

**Code to reproduce:**

``` js
import { ajax } from 'rxjs/observable/dom/ajax';
ajax.get('nothing/good/here').subscribe(null, () => console.log('error happened'));
```

**Expected behavior:**

Should log `error happened`.

**Actual behavior:**

Bombs at `xhr.send` call.

**Additional information:**

I just ran into this, I haven't checked the latest version. Just wanted to log the issue if others have seen it.

**Comment by blakef** [comment]
Can't reproduce on [beta 11](http://codepen.io/blakef/pen/AXkabW?editors=0010)

**Comment by blesh** [comment]
This has been fixed, apparently.
