### ISSUE TITLE
takewithtime deprecated?

### ISSUE THREAD

**Issue by lmeyerov** [ReactiveX/rxjs#1818]
**RxJS version:** 5.0.0-beta.10

**Code to reproduce:**  https://github.com/ReactiveX/rxjs/search?utf8=%E2%9C%93&q=takewithtime&type=Code

**Expected behavior:** See results with takewithtime

**Actual behavior:** None

**Additional information:**

I could not find mentions of `takewithtime` in https://github.com/ReactiveX/rxjs/blob/master/MIGRATION.md , as it was in v4 but does not appear to be so in v5. If it is deprecated, I would have expected that to be noted in `migration.md`, and if not, for it to be in the docs.

**Comment by lmeyerov** [comment]
If it helps, I replaced our original use with `.takeUntil(Rx.Observable.timer(duration))`, though I didn't look too closely at the original.

**Comment by blesh** [comment]
closing as inactive
