### ISSUE TITLE
`WebSocketSubject` closes underlying socket when any observer unsubscribes

### ISSUE THREAD

**Issue by marshall007** [ReactiveX/rxjs#1827]
**RxJS version:** `5.0.0-beta.10`

**Code to reproduce:**

JSBin: http://jsbin.com/xisajopedo/3/edit?js,console

``` js
let socket = Rx.Observable.webSocket({
  url: 'ws://echo.websocket.org',
  resultSelector: e => e.data,
  openObserver: {
    next: () => console.log('open'),
    error: e => console.error(e)
  },
  closeObserver: {
    next: () => console.log('close')
  }
});

socket.subscribe(
  e => console.log(`res: ${e}`),
  e => console.error(e),
  () => console.log('complete')
)

socket.multiplex(() => 'handshake_start', () => 'handshake_end', () => true)
  //.takeUntil(n => n !== 'handshake_start')
  .subscribe(null, null, () => console.log('handshake_complete'))

socket.multiplex(() => 'query_start', () => 'query_end', () => true)
  .takeUntil(Rx.Observable.interval(1000).take(2))
  .subscribe(null, null, () => console.log('query_complete'))
```

**Expected behavior:**

I would expect that the socket would remain open after the `query` subscription completes since the `handshake` subscription is still open.

**Actual behavior:**

The underlying socket is closed once the first observer unsubscribes, thus unsubscribing all other observers as well.

**Comment by deontologician** [comment]
Looking at this, it seems like this guard: https://github.com/ReactiveX/rxjs/blob/master/src/observable/dom/WebSocketSubject.ts#L206 might need to also check that `this._output.observers.length === 0`
