### ISSUE TITLE
Errors in Observable.create arg not caught

### ISSUE THREAD

**Issue by matthewwithanm** [ReactiveX/rxjs#1833]
**RxJS version:**

5.0 beta 10

**Code to reproduce:**

``` js
Observable.create(() => { throw new Error('oops'); }).subscribe({error: _ => console.log('got it')});
```

**Expected behavior:**

`> got it`

**Actual behavior:**

`Error: oops`

**Additional information:**

Rx 4 exhibits the expected behavior here (catching the error and sending it to the observer).

cc @hansonw

**Comment by trxcllnt** [comment]
@matthewwithanm hm, good catch. I think I can get a PR for this ready soon.

**Comment by wbinnssmith** [comment]
hi! I can still reproduce this with the latest stable RxJS as of now (5.4.3). Is d4a9aac7fa151695fe5567192f370164b001501b a breaking change targeted at 6.0 only or will this patch land in v5 at some point?

**Comment by trxcllnt** [comment]
@wbinnssmith I would expect this should go out in a patch release. @benlesh thoughts?
