### ISSUE TITLE
Proposal: Throw in FromEventObservable if invalid source

### ISSUE THREAD

**Issue by matthewwithanm** [ReactiveX/rxjs#1834]
I just spent a while tracking down a bug. It turns out the emitter I was passing to `fromEvent` wasn't one that Rx knows how to handle. It would be cool if that threw an error instead of failing silently.

**Comment by staltz** [comment]
I believe we could accept a PR for this.

**Comment by matthewwithanm** [comment]
👍 otw

**Comment by kwonoj** [comment]
I assume this issue is now resolved? /cc @jayphelps

**Comment by jayphelps** [comment]
Indeed! thanks @kwonoj
