### ISSUE TITLE
Support for event options (fromEvent)

### ISSUE THREAD

**Issue by tjoskar** [ReactiveX/rxjs#1836]
**RxJS version:** 5.0.0-beta.10

**Code to reproduce:** 
```javascript
import { Observable } from 'rxjs/Observable';

const eventOptions = {passive: true};
Observable.fromEvent(window, 'scroll', undefined, eventOptions)
```

**Expected behavior:**
Added an event listener on the window object with the option `{passive: true}`.

**Actual behavior:**
Typescript error: `Supplied parameters do not match any signature of call target`

**Additional information:**
According to the [docs for RxJS 4](https://github.com/Reactive-Extensions/RxJS/blob/12267b74674109dc4e8ed9c72bee659352eeafe3/doc/api/core/operators/fromevent.md) one can add event options as a fourth parameter but when I look at the [souce code of version 5](https://github.com/ReactiveX/rxjs/blob/88651eede343d9891b806f932908fb37c4b4f8a7/src/observable/FromEventObservable.ts#L102) the [addEventListener](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#Parameters)-method is only called with the `type` and `listener` parameter. Not with `options` or `useCapture` which [addEventListener](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#Parameters) also takes.

Are there any plans of extending `fromEvent` so it can take event options as a parameter and pass it to `addEventListener`?

**Comment by trxcllnt** [comment]
Yes, we want to support this. Happy to review a PR with the change.

**Comment by tfiers** [comment]
@tjoskar Thanks for the fix. Could you edit the "Code to reproduce" section in your original comment to not include the `undefined` argument? Including it breaks the program with an unhelpful error.
(A Google search for `observable fromevent options` brought me here).

**Comment by tjoskar** [comment]
I don't think it's a good idea to change the original issue post, you can however take a look at the [signatures](https://github.com/ReactiveX/rxjs/blob/69d051bc56cb337148db30515029363c1e78b90d/src/observable/FromEventObservable.ts#L58) to determine how to use the method.

E.g. you can use the following signature to pass `eventOptions` but do not want to pass any `SelectorMethod`:

```js
import { Observable } from 'rxjs/Observable';

const eventOptions = {passive: true};
Observable.fromEvent(window, 'scroll', eventOptions);
```

**Comment by tfiers** [comment]
Indeed, calling it like that works.
As can be seen in both the source code and the documentation for `fromEvent` that you linked, the `options` argument comes before the `selector` argument; i.e. these work as intended:
```js
Observable.fromEvent(window, 'click', {passive: true}, (e) => 'x')
Observable.fromEvent(window, 'click', {passive: true}, undefined)
Observable.fromEvent(window, 'click', {passive: true})
``` 
whereas this one does not:
```js
Observable.fromEvent(window, 'click', undefined, {passive: true})
```
When this is subscribed to and the first event happens, the supplied `{passive: true}` object is being used as the `selector` function, which generates the error: `Uncaught TypeError: tryCatchTarget.apply is not a function`.

(The argument order is slightly confusing, because in RxJS 4.0, these arguments _are_ [switched](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/fromevent.md)).

**Comment by tjoskar** [comment]
@tfiers, the reason for the argument swap was because typescript will accept a function as `eventOptions` since non of the properties on the object are required.

Let's say we didn't do the argument swap and have the following code:
```ts
function select(e: Event): string {
    return e.timeStamp.toString();
}
/* Typescript will now think that the select function is the option object, since it satisfies the
  criteria for "eventOptions". 
  The function (select) will however be treated as a select function under runtime */
Observable.fromEvent<number>(window, 'scroll', select); // OK

Observable.fromEvent<number>(window, 'scroll', select, { passive: true }); // Typescript will now know that `select` is the select function since we pass 4 arguments. Typescript will therefore give the following error: "the select function should return a number" 
```

If we just swap the arguments, the problem will go away :)

You can read more about the discussion here: https://github.com/ReactiveX/rxjs/pull/1845#r71985944
