### ISSUE TITLE
Use new features introduced from TypeScript Compiler v2.0

### ISSUE THREAD

**Issue by saneyuki** [ReactiveX/rxjs#1837]
After upgrade tsc to 2.0, we can use more compiler options to make our code more safety, cleanly, and massive.

## Examples:

- `strictNullChecks`compiler option.
- `noUnusedLocals` compiler option.
- `noImplicitThis` compiler option.
- `noUnusedParameters` compiler option.
- Use npm's @types packages to manage d.ts files.
- Use `readonly` modifiers.
- Use `never` types.
- Glob support in tsconfig.json
- And mores...

## Official release note:

- [What's new in TypeScript · Microsoft/TypeScript Wiki](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#typescript-20)

**Comment by saneyuki** [comment]
@kwonoj could you change labels of this issues? I don't have the permission to edit it.

**Comment by saneyuki** [comment]
@kwonoj thank you.

**Comment by kwonoj** [comment]
related issue : https://github.com/ReactiveX/rxjs/issues/1915

maybe non-nullable type's also needed.

**Comment by saneyuki** [comment]
We gathered related issues to this once, but I think this is too generic "meta" bug. We have been landed upgrading tsc 2.0. So we should considers for each issues.
