### ISSUE TITLE
Proposal: Argument order in concat, merge, zip, concatLatest should be changed

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#184]
Currently the arguments for both `concat` and `merge` having optional arguments *first* with splat params for Observables after:

### Current

```js
merge(scheduler?:Scheduler, concurrent?:number, ...observables:Array<Observable<T>>)
concat(scheduler?:Scheduler, ...observables:Array<Observable<T>>)
```

### Proposed

I'd like to change the order and remove the splat params:

```js
merge(observables: Array<Observable<T>>, concurrent?:number, scheduler?:Scheduler)
concat(observables: Array<Observable<T>>, scheduler?:Scheduler)
```

Reasons are as follows:

- any function that has an optional Scheduler argument should have that argument be the last argument, for consistency.
- Passing an array rather than splat params means we no longer have to analyze  the `arguments` object and do any `slice` trickery to get the array of Observables out of it, and should optimize better.
- Having all optional arguments come last means we no longer have to do any `typeof` assertions to figure out what argument is what.

(TLDR: less polymorphic functions)

**Comment by blesh** [comment]
FWIW, I think we should avoid the splat param type arguments were possible. and always work to limit typeof checks, even if it's only an up-front cost, because we don't know where people are creating new observables using these operators. They could be created inside of a flatMap on every nexted value or something.

**Comment by staltz** [comment]
I think you are putting implementation convenience over user experience (user = developer using RxJS).

> Passing an array rather than splat params means we no longer have to analyze the arguments object and do any slice trickery to get the array of Observables out of it, and should optimize better.

```js
Rx.Observable.merge(source1, source2, source3)
``` 
is more ergonomic/logical than 
```js
Rx.Observable.merge([source1, source2, source3])
```

`arguments` or not, that's implementation detail.

> Having all optional arguments come last means we no longer have to do any typeof assertions to figure out what argument is what.

Implementation detail.

**Comment by staltz** [comment]
The other alternative is to allow only the *instance* variant of the operator, with a single Observable as argument. This is what Erik is doing in RxMobile, for instance.

```js
concat(other: Observable<T>, scheduler?:Scheduler)
```
But I definitely prefer to keep
```js
concat(scheduler?:Scheduler, ...observables:Array<Observable<T>>)
```

**Comment by blesh** [comment]
> I think you are putting implementation convenience over user experience

Not at all.. I'm concerned about the performance of having to do type assertions and Array.splicing arguments every time someone wants to merge or concat.

> is more ergonomic/logical than
> Rx.Observable.merge([source1, source2, source3])

In an IDE, you literally have added `[` to your typing cadence. I think your ergonomics standards are too high. haha. :)

> ... implementation detail
> Implementation detail.

You keep saying that, but when [implementation is this](https://github.com/ReactiveX/RxJS/blob/3f743ab12476f0b689c79a68637dff2f1cd1d475/src/operators/merge.ts#L13-L32): 

```TypeScript
export default function merge(scheduler?: any, concurrent?: any, ...observables: Observable<any>[]) {
  const xs = [];
  if (typeof this.subscribe === "function") {
    xs.push(this);
  }
  if (concurrent && typeof concurrent.subscribe === "function") {
    xs.push(concurrent);
    concurrent = scheduler;
  }
  if (scheduler && typeof scheduler === "object") {
    if (typeof scheduler.subscribe === "function") {
      xs.push(scheduler);
      scheduler = undefined;
      concurrent = Number.POSITIVE_INFINITY;
    } else if(typeof scheduler.schedule === "function") {
      concurrent = Number.POSITIVE_INFINITY;
    }
  }
  return new ArrayObservable(xs.concat(observables), scheduler).lift(new MergeOperator(concurrent));
}
```

vs something like this (pseudocode):

```TypeScript
export default function merge(...observables: Observable<any>[], concurrent:number=Number.POSITIVE_INFINITY, scheduler: Scheduler=Scheduler.nextTick) {
  return new ArrayObservable(observables, scheduler).lift(new MergeOperator(concurrent));
}
```

... I think it's safe to say it will have better execution time. Given that: 1) there are fewer assertions, and 2) The function is no longer examining `arguments` and splicing out an array.

**Comment by blesh** [comment]
FWIW... if I were concerned about "implementation convenience" I definitely would not be using TypeScript. :P haha.

**Comment by staltz** [comment]
You know, you don't really need to Array.splice the `arguments` if you are any way willing to do anything for performance's sake.

**Comment by blesh** [comment]
Well, I mistyped, it's `slice`, not `splice`, but either way, I'm not sure what you could do that would be more performant than slicing the items out into an array if you need an array. Anyhow, that's just one of my issues with it.

**Comment by blesh** [comment]
To be clearer (and I realize that micro-perf can be a goose chase at times), [here's a jsperf demonstrating the speed of only the code in question](http://jsperf.com/big-fn-little-fn-jiggity-jig).
![screen shot 2015-08-17 at 2 25 02 pm](https://cloud.githubusercontent.com/assets/1540597/9316741/caefdf44-44eb-11e5-86c2-003db3d259e6.png)

**Comment by blesh** [comment]
To be clearer, I've put together a [micro perf test](http://jsperf.com/big-fn-little-fn-jiggity-jig) of just the code in question (the code for figuring out the arguments to `merge`, specifically).

![screen shot 2015-08-17 at 2 29 49 pm](https://cloud.githubusercontent.com/assets/1540597/9316854/a50f561e-44ec-11e5-8495-7206de9b7cce.png)

**Comment by blesh** [comment]
Also on the "developer ergonomics" front, the current signature required all arguments to be of type `any` just to work, so anyone using TypeScript won't benefit much from that. I'm not really that "pro-TypeScript", but I can say that a lot of things that are difficult or unergonomic in TypeScript generally don't perform very well (polymorphic functions, etc).

**Comment by ktrott** [comment]
Discussion: We would want to change the order of arguments for all operators w/ splat arguments including:
* merge
* concat
* zip
* combineLatest

**Comment by blesh** [comment]
@staltz @ktrott @trxcllnt ... I think I have some changes that will improve this greatly *and* keep the same syntax... 

You'll notice in the results for `merge4` below, the signature is the same as `merge1`, which is the current implementation.

The speed is up there, not as fast as the original proposal, but I think it strikes a balance between speed and ergonomics. (although I still think having the scheduler come first is bizarre, and it should come last, because it doesn't work that way on any of the others).

Outside of that I think we can implement each prototype method seperately in the same file and export it, to remove a `typeof` check to see if `this` is an Observable

![screen shot 2015-08-17 at 5 27 08 pm](https://cloud.githubusercontent.com/assets/1540597/9319636/8ef0630a-4505-11e5-9500-7937900a10d4.png)
![screen shot 2015-08-17 at 5 30 03 pm](https://cloud.githubusercontent.com/assets/1540597/9319645/9f5a7ea6-4505-11e5-9472-b1a98d823838.png)

**Comment by staltz** [comment]
So you want `merge3`, @blesh ?

**Comment by blesh** [comment]
I think so? Awaiting feedback, really. `merge4` keeps the same signature. I just think it's inconsistent with the rest of the library

**Comment by blesh** [comment]
Also I'd like to run each of these through the macro perf tests and see how it effects it.

**Comment by staltz** [comment]
merge3 seems totally fine IMO.

**Comment by blesh** [comment]
@trxcllnt pointed out to me that `merge3` actually adheres to [Microsoft's Rx API design guidelines](http://go.microsoft.com/fwlink/?LinkID=205219), which states that if there's a scheduler argument it should be *last*, with the provision that C# only allows `params` arguments as the last argument. We're not hindered by that strong-typery... so damn the torpedoes! let's go for consistency with the rest of this library.

![screen shot 2015-08-19 at 4 23 37 pm](https://cloud.githubusercontent.com/assets/1540597/9372021/afc8939c-468e-11e5-9df1-beb98649f6d9.png)


In my perf testing, I found no discernible macro perf difference in any of the merge implementations. There were some micro-perf wins, but nothing more than 5% or so, which could be a rounding error, regardless of how consistent it was.

as such, I'm going with `merge3`.

**Comment by trxcllnt** [comment]
@blesh do you have a PR for this yet? need in current Falcor upgrade.

**Comment by blesh** [comment]
@trxcllnt incoming...
