### ISSUE TITLE
Add just/return operator

### ISSUE THREAD

**Issue by cburgdorf** [ReactiveX/rxjs#1842]
Currently there doesn't seem a simple way to create an Observable that emits with a single value and doesn't complete.

Today the simples thing I can think of would be `new Observable(obs => obs.next(3))`. If there was an implementation of the [`just/return`](http://reactivex.io/documentation/operators/just.html) operator, one would be able to simply write `Observable.just(3)` instead.

**Comment by david-driscoll** [comment]
There is `Observable.of`, which lets you send 1 or many items as emissions.  That said it always completes.  Also the linked operator also completes after emitting just one value.

I don't think there is an operator with the behavior you're looking for.

**Comment by staltz** [comment]
> Currently there doesn't seem a simple way to create an Observable that emits with a single value and doesn't complete.

Observable.of

**Comment by blesh** [comment]
Yeah, just use `of`. Also, we've put together this handy-dandy migration guide: 
https://github.com/ReactiveX/rxjs/blob/master/MIGRATION.md#operators-renamed-or-removed

**Comment by cburgdorf** [comment]
But `Observable.of(3)` gives you an Observable that emits and then completes. I want one that doesn't complete.

**Comment by staltz** [comment]
`just` in RxJS v4 also completes.

`Observable.of(3).concat(Observable.never())` doesn't complete

**Comment by cburgdorf** [comment]
> `Observable.of(3).concat(Observable.never())` doesn't complete

yep, but don't you think this is such a general case that it deserves it's own operator. I think not having an operator for that would be really odd.

**Comment by staltz** [comment]
An observable that emits one value **and** does not complete? No, I don't think it's common at all. Sounds like a code smell. I wonder why you need that in the first place.
