### ISSUE TITLE
.first() emits more than one value

### ISSUE THREAD

**Issue by danielrasmuson** [ReactiveX/rxjs#1850]
**RxJS version:**
Test on rxjs@5.0.0-beta. 8 - 11

**Code to reproduce:**
```
var x = Rx.Observable.from(new Rx.Subject());
var z = x.filter((num) => num === 3);

z.take(1).subscribe(()=>{
  console.log('take1')
  z.next(3)
})

z.first().subscribe(()=>{
  console.log('first')
  // z.next(3) // <-- infinite loop
})

z.next(3)
```

**Expected behavior:**
I would expect `.take(1)` and `.first()` to behave the same.

**Actual behavior:**
`.take(1)` only accepts one item from the emitted stream. While `.first()` will accept values if the emitter is within the on subscribe function.

**Comment by kwonoj** [comment]
It seems dupe of #1759 - @danielrasmuson , would you able to confirm if this is same case? (comment https://github.com/ReactiveX/rxjs/issues/1759#issuecomment-227566970 / https://github.com/ReactiveX/rxjs/issues/1759#issuecomment-227575178 as well)

**Comment by danielrasmuson** [comment]
👍  Yes it does look like a dupe.
