### ISSUE TITLE
Compile TypeScript directly to ES5

### ISSUE THREAD

**Issue by trxcllnt** [ReactiveX/RxJS#186]
- [x] Add Promise typedef so TypeScript compiler doesn't barf
- [x] Alter the `build_amd` and `build_cjs` npm commands to target ES5

**Comment by jeffbcross** [comment]
I started on this, and also assumed that the `build_global` script should use TypeScript directly. Is that not the case @trxcllnt? The global build is where I started running into an issue of the output Rx.js being empty for some reason.

**Comment by blesh** [comment]
@jeffbcross currently it doesn't. I set up a really weird build process that is basically TS -> ES6 -> Babel -> CJS ->  Browserify -> Global 

This was because of the weirdness with out TS output CJS files more than anything. The whole process needs revamped.

**Comment by blesh** [comment]
Nice! Thanks @jeffbcross!
