### ISSUE TITLE
timeout() operator always emits error, even if given a promise or another observable

### ISSUE THREAD

**Issue by igorsechyn** [ReactiveX/rxjs#1865]
**RxJS version:** 5.0.0-beta.10

**Code to reproduce:** 
```
const rx = require('rxjs');
const source = rx.Observable
    .of(42)
    .delay(5000)
    .timeout(200, Promise.resolve(42));

const subscription = source.subscribe(
    function (x) { console.log('Next: %s', x); },
    function (err) { console.log('Error: %s', err); },
    function () { console.log('Completed'); });
```

**Expected behavior:**
Output: Next 42
**Actual behavior:**
Output: Error: [object Object]
**Additional information:**
According to documentation the timeout operator, if passed a promise or another observable, should emit this value. Currently, regardless of what is being passed into the operator, the value is being emitted as error

**Comment by kwonoj** [comment]
You may need `timeoutWith` to supply continuing observable when timeout occurs. due to polymorphic behavior of timeout, it has splitted into `timeout` and `timeoutWith` (refer https://github.com/ReactiveX/rxjs/issues/244 for background, https://github.com/ReactiveX/rxjs/pull/245 for implementation)

**Comment by igorsechyn** [comment]
Awesome, thanks. Maybe worthwhile updating the documentation and/or the [migration](https://github.com/ReactiveX/rxjs/blob/master/MIGRATION.md) guideline

**Comment by kwonoj** [comment]
Yes, seems migration guide missing it, need to be updated.
