### ISSUE TITLE
MUST KILL NO SPACE BRACES

### ISSUE THREAD

**Issue by blesh** [ReactiveX/rxjs#1868]
This is a special issue for @ladyleet, who wants to contribute in a meaningful way.

I HATE no space imports in our files. I hate them. We all hate them. @jayphelps hates them. @kwonoj hates them. There's so much hate. End our hate, Tracy. End it.

You wanted to contribute, @ladyleet, here it is... kill those no-space imports!

GOOD: 

```js
 import { foo } from 'foo';
```

BAD:

```js
import {foo} from 'foo';
```

 related #1867

**Comment by blesh** [comment]
I'm assigning myself so no one else takes this one up. But it's all you, @ladyleet.

**Comment by trxcllnt** [comment]
lol I thought that was how you liked it since I saw it done everywhere.

**Comment by jayphelps** [comment]
![image](https://cloud.githubusercontent.com/assets/762949/17452939/722253d8-5b29-11e6-8c9e-779ace8ce2b6.png)

**Comment by ladyleet** [comment]
@jayphelps you're way more interesting on github than twitter. i'm kind of digging it.

**Comment by jayphelps** [comment]
@ladyleet github is life

**Comment by staltz** [comment]
I love `import {foo} from 'foo';`. Seriously.

**Comment by blesh** [comment]
NO @staltz! I'll accept your [Finnish Notation](https://medium.com/@benlesh/observables-and-finnish-notation-df8356ed1c9b#.5bll32gfw), but you can't have no-space-braces! You can't!

**Comment by staltz** [comment]
Yeah, I understand you americans. Inches, Fahrenheit, Feet, AM/PM, Miles. And now... spaces for braces. I guess if you use wrong standards, you gotta consciously and consistently use wrong standards everywhere. :)

`</sarcasm>`

**Comment by blesh** [comment]
@staltz: Trump's nukes won't care if they miss by inches or centimeters. The end is nigh.

**Comment by staltz** [comment]
But heating something up to 100 degrees (Celsius? Fahrenheit?) might mean life or death.
