### ISSUE TITLE
requestIdleCallback scheduler?

### ISSUE THREAD

**Issue by ronag** [ReactiveX/rxjs#1870]
Would be nice to have for making web apps more responsive.

**Comment by blesh** [comment]
It could be added. The only reason it hasn't been is there isn't really a great way to polyfill this functionality. There are, of course, polyfills... but nothing I've seen that I think is definitively great.

It could be that RxJS just decides to fallback to a standard async behavior in environments that don't support requestIdleCallback.

**Comment by blesh** [comment]
closing as inactive.
