### ISSUE TITLE
sequenceEqual operator

### ISSUE THREAD

**Issue by jskz** [ReactiveX/rxjs#1882]
What is the suggested means for checking equality between two observable streams with the removal of the _sequenceEqual_ operator in RxJS 5?   I am trying to make a comparison between a buffered or windowed list of integer values and a known array of values, in the context of a mergeMap.

**Comment by blesh** [comment]
We should probably add this one. A home-brew implementation would be non-trivial. But something like this might do in the mean time:

```js
function sequenceEqual(b$) {
  let a$ = this;
  return new Observable(observer => {
    let lastA;
    let lastB;
    let oneComplete = false;

    const error = observer.error.bind(observer);

    const emit = (value) => {
      observer.next(value);
      observer.complete();
    };

    const checkDone = () => {
      if (oneComplete || lastA !== lastB) emit(false);
    };

    const subA = a$.subscribe(a => {
      lastA = a;
      checkDone();
    },
    observer.error.bind(observer),
    () => {
      if (oneComplete) {
        emit(lastA === lastB);
      } else {
        oneComplete = true;
      }
    });

    const subB = b$.subscribe(b => {
      lastB = b;
      checkDone();
    },
    observer.error.bind(observer),
    () => {
      if (oneComplete) {
        emit(lastA === lastB);
      } else {
        oneComplete = true;
      }
    });

    return () => {
      subA.unsubscribe();
      subB.unsubscribe();
    };
  });
}
```

Apologies if it's buggy, just pulled that out of nowhere.

I'll put it on my agenda to add the sequenceEqual operator.

**Comment by jskz** [comment]
Thank you!

**Comment by blesh** [comment]
Actually... @jskz ... that implementation will not work at all... haha. I'm working on a legit version of the operator now. :)

**Comment by blesh** [comment]
@jskz ... PR #1883 will give you the sequenceEqual operator.
