### ISSUE TITLE
Order of unsubscribe calls is incorrect when combining .share() and .switchMap()

### ISSUE THREAD

**Issue by tomachristian** [ReactiveX/rxjs#1884]
**RxJS version:** 5.0.0-beta11

**Code to reproduce:**

``` javascript
var obs1 = Observable.create(observer => {
    observer.next("obs1 1");
    observer.next("obs1 2");

    return () => {
        console.log("unsub obs1");
    };
});

var obs2 = Observable.create(observer => {
    observer.next("obs2 1");
    observer.next("obs2 2");

    return () => {
        console.log("unsub obs2");
    };
});

// One:
var sharedObs1 = obs1.share();

sharedObs1.switchMap(() => obs2)
    .subscribe(() => console.log("emit"))
    .unsubscribe();

// Outputs
// > unsub obs1
// > unsub obs2

// and Two:
obs1.switchMap(() => obs2)
    .subscribe(() => console.log("emit"))
    .unsubscribe();

// Outputs
// > unsub obs2
// > unsub obs1
```

**Expected behavior:**
Both options, One and Two, should do the unsubscriptions in the same order, their console outputs should be the same. The output for Two seems to be the correct one.

**Actual behavior:**
For One: The unsubscription happens for the source observable and then for the 'switched' one.
For Two: The unsubscription is done in the correct order, first from the switched one and then from the source one.

**Additional information:**
The console.log('emit') outputs were ignored.

**Comment by blesh** [comment]
I'm not sure this is a bug so much as it is the fact that `share` internally does reference counting to know when to unsubscribe. Since subscriptions to the source are ref counted, as soon as the first and only subscription to it unsubscribes, it unsubs from the source, then child subscriptions are torn down.

@trxcllnt do you concur? If so, I'm inclined to close this.

**Comment by trxcllnt** [comment]
@blesh I see what's happening: both [`ConnectableSubscriber`](https://github.com/ReactiveX/rxjs/blob/master/src/observable/ConnectableObservable.ts#L85) and [`RefCountSubscriber`](https://github.com/ReactiveX/rxjs/blob/master/src/observable/ConnectableObservable.ts#L168) dispose the shared connection in their private `_unsubscribe` methods, which are called from the public [`unsubscribe`](https://github.com/ReactiveX/rxjs/blob/master/src/Subscription.ts#L93) method _before_ child subscriptions are disposed. This means the connection subscription to the source will be disposed before the `SwitchMapSubscriber`, leading to this call pattern.

The ConnectableObservable's subscription order is a delicate balancing act to ensure it works with sync retry and repeat, but I can revisit the order to see if it can be changed.

**Comment by trxcllnt** [comment]
@blesh after digging deeper, it doesn't seem like something we can change easily while still supporting repeat and retry with synchronous sources.

**Comment by tomachristian** [comment]
I wouldn't say that this is nondeterministic behavior, although it is nonintuitive, IMO. I managed to work around it, but I don't remember how as this was posted a long time ago. I wouldn't mark it as urgent or important.

**Comment by benlesh** [comment]
Closing as stale
