### ISSUE TITLE
skipUntil doesn't unsubscribe notifier after first event

### ISSUE THREAD

**Issue by matthewwithanm** [ReactiveX/rxjs#1886]
**RxJS version:** 5.0.0-beta11

**Code to reproduce:**

`Observable.never().skipUntil(Observable.interval(100).do(x => console.log(x))).subscribe()`

**Expected behavior:**

`0` will be logged

**Actual behavior:**

Lots of numbers are logged.

**Additional information:**

This works as expected in v4.

**Comment by trxcllnt** [comment]
Looks like skipUntil doesn't close its subscription to the notifier unless the source completes, which isn't happening in this case. And while I'm thinking about it, skip/takeUntil should both be refactored to subscribe to the notifier after their source subscription has occurred, so they don't superfluously subscribe to the notifier if the source completes synchronously.

**Comment by blesh** [comment]
@trxcllnt I know this is horrifying... But you could have a synchronous source observable with a takeUntil notifier that's a subject, and side effect next into that subject during the execution of the synchronous source observable. So you probably don't want to wait

**Comment by trxcllnt** [comment]
@blesh I mean you _could_ do anything, but that's not how it's [supposed to work](https://github.com/Reactive-Extensions/RxJS/blob/master/src/modular/observable/takeuntil.js#L30).

**Comment by blesh** [comment]
I guess what I'm disagreeing with is here:

>  skip/takeUntil should both be refactored to subscribe to the notifier after their source subscription has occurred

The notifier should probably be subscribed to _first_. That way if it notifies synchronously it effects the source. In case the source firehoses synchronously.
