### ISSUE TITLE
Could add support for bower installation? Thanks.

### ISSUE THREAD

**Issue by hungtruongquoc** [ReactiveX/rxjs#1887]
**RxJS version:**

**Code to reproduce:**

**Expected behavior:**

**Actual behavior:**

**Additional information:**

**Comment by bpceee** [comment]
upvote! due to legacy project..

**Comment by aabm00** [comment]
So if I have a project that uses Bower in the client side to load the dependencies and I don't want to hardcode a CDN in the index.html how I can load RXJs 5 in my project?

Thanks

**Comment by trxcllnt** [comment]
I don't think anybody here uses bower, but we'd gladly accept a PR to add it

**Comment by kwonoj** [comment]
@trxcllnt `bower` itself seems giving deprecation notice over https://github.com/bower/bower/issues/2460#issuecomment-305536061 , yet alive due to there isn't simple migration path over. Is it really we do want to publish new pkgs for deprecated one?

**Comment by kwonoj** [comment]
I'm closing this issue - at this moment, as bower itself implicitly started declare deprecation I don't think we'll going to publish new packages for it.
