### ISSUE TITLE
Port map benchmark to benchpress

### ISSUE THREAD

**Issue by jeffbcross** [ReactiveX/RxJS#19]

**Comment by ktrott** [comment]
RxJS Next meeting discussion:
(attendees: @blesh, @jhusain, @trxcllnt)
* flatMap is in benchpress right now.
* need to identify what are several really good macro performance tests

We'll create a new issue on the macro perf tests

**Comment by blesh** [comment]
I think at this point we probably don't need macro perf benchmarks for simple operators. Micro perf is probably fine for these. Macro perf, on the other hand is a necessity for any of the operators that are internally creating new observables, or subscribing multiple times to inner observables.

Closing for now in favor of #126
