### ISSUE TITLE
fromEventPattern signal missing

### ISSUE THREAD

**Issue by dwieeb** [ReactiveX/rxjs#1900]
**RxJS version:** 5.0.0-beta.11 

In v4, there was a way to take the _signal_ (the thing returned from `addHandler`) and use it in `removeHandler` for proper disposal. [See v4 docs for `fromEventPattern`](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/fromeventpattern.md#example), under the Dojo toolkit example. I think this functionality is still useful and it [appears to be missing](https://github.com/ReactiveX/rxjs/blob/master/src/observable/FromEventPatternObservable.ts#L60).

I can attempt to submit a PR, but I was wondering if there was a reason for its removal.

**Comment by blesh** [comment]
cc @trxcllnt

**Comment by trxcllnt** [comment]
@blesh was I responsible for `fromEventPattern`? If so, I apologize, and this should definitely be fixed.

**Comment by blesh** [comment]
@trxcllnt no worries, it was an add you made very very early on in development. I can look at it too, I was just traveling when this crossed my screen.

**Comment by kwonoj** [comment]
Closing via #2224.
