### ISSUE TITLE
NPM module `rxjs` does contain bundle in system register format

### ISSUE THREAD

**Issue by unlight** [ReactiveX/rxjs#1901]
**RxJS version:** 5.0.0-beta.11
**Expected behavior:** npm module `rxjs` does contain bundle in system register format.
**Actual behavior:** npm module `rxjs` DOES NOT contain bundle in `system register` format.
**Additional information:**
Module of version `5.0.0-beta.9` contained such bundle.
It allows to load `rxjs` by SystemJS without any configuration.

**Comment by kwonoj** [comment]
From latest release systemjs bundle is no longer published and encouraged to configure systemjs as needed. Details can be found at https://github.com/ReactiveX/rxjs/issues/1776.
