### ISSUE TITLE
publish<T>(selector?: function(Observable<T>): Observable<R> ): Observable<R> should be allow to get type changed.

### ISSUE THREAD

**Issue by Dorus** [ReactiveX/rxjs#1905]
The method signature for publish(selector) should be 

```
function publish<T>(selector?: (source: Observable<T>) => Observable<R>): Observable<R> | ConnectableObservable<R>
```

like `let` to allow type changes in the selector. Currently it is using 

```
function publish<T>(selector?: (source: Observable<T>) => Observable<T>): Observable<T> | ConnectableObservable<T>
```

https://github.com/ReactiveX/rxjs/blob/master/src/operator/publish.ts#L19

**Comment by staltz** [comment]
Seems legit.

**Comment by daixtrose** [comment]
I propose to provide 2 different methods here. One with and one without argument. In a strongly typed world it is surprising to have the return type depend on the availability of an argument.

- `publish()`
- `mapPublish(selector ...)`

**Comment by Dorus** [comment]
I like that idea. Could this pattern be mimicked for other operators that return a ConnectableObservable?

`publishReplay` could have an `mapReplay` similar to this [`Replay`](https://msdn.microsoft.com/en-us/library/hh229288(v=vs.103).aspx) operator from Rx.Net

Same with:
`publishBehavior` => `mapBehavior`
`publishLast()` => `mapLast` (?)

There is also `multicast()` that seems to do something with `ConnectableObservable` but i do not quite understand it.

**Comment by david-driscoll** [comment]
Publish should be changed, the main signature to update (until we move to 2.0 features) is [here](https://github.com/ReactiveX/rxjs/blob/master/src/operator/multicast.ts#L44-L47).

We probably also need to make changes to all the multicast observables, as [`multicast`](https://github.com/ReactiveX/rxjs/blob/master/src/operator/multicast.ts#L44-L47) has the same issue.

**Comment by kwonoj** [comment]
I'm not sure where we at for this issue, probably still need to update type definitions? /cc @david-driscoll

**Comment by Dorus** [comment]
Small update to the op: `ConnectableObservable<T>` should have been `ConnectableObservable<R>` too. I've changed that up here.

**Comment by benlesh** [comment]
The typings and definitions have changed so much around this, that I'm pretty sure this thread is no longer relevant. Feel free to reopen if I'm in error.

Thanks!
