### ISSUE TITLE
Why is the "while" removed?

### ISSUE THREAD

**Issue by iexplore** [ReactiveX/rxjs#1908]
I am learning RxJS v5 and I am trying to create a scrape script that get's a webpage (async via node request) and scrapes items from that page. On that same page there is a next-page url from which the next page can loaded en processed and so on.

In RxJS 4 there is a "while" constructor which handles this perfectly, but in RxJS 5 this constructor is removed. My question is is there a reason why it is no longer available and are there other ways to start async-sequences in v5?

Thanks!

**Comment by kwonoj** [comment]
It is not removed, RxJS 5 is not yet implemented all of operators in RxJS 4 and gradually adding it. You can see list of operators which exists in 5 & 4 both and doesn't at [here](https://github.com/ReactiveX/rxjs/blob/master/MIGRATION.md#operators-renamed-or-removed) '-` stands for 'not yet implemented for now'. (noticed `while` itself is not included in table which need to be updated)

**Comment by iexplore** [comment]
Ok, clear.
Thanks for your very prompt answer.
