### ISSUE TITLE
Usecase for windowWithTimeOrCount() in RxJS 5

### ISSUE THREAD

**Issue by RAlfoeldi** [ReactiveX/rxjs#1909]
As requested I do have a usecase for the dropped operator `windowWithTimeOrCount()`

What I am trying to do is bundle requests to a server without waiting longer than maxWait ms. 

This is part of a rather elaborate DataService/Cacheing scheme that often retrieves thousands of data elements, but sometimes only 2-3. I don't want to get more than, say, 1000 elements, but also don't want to wait longer than, say, 50 ms. I would assume that this is a rather standard usecase.

I've implemented what I needed - as good as I could - and it works almost perfectly, but looses the last element of every 'chunk'. (As this isn't a support forum, I'm just linking to the StackOverflow [question](http://stackoverflow.com/questions/39209560/rxjs-using-windowwhen-for-maxwait-and-maxelements-windows), which has my implementation included.)

**Comment by kwonoj** [comment]
I think issue https://github.com/ReactiveX/rxjs/issues/1301 tracks this, though it hasn't been updated while. I'll try to look into once I have some time after some priorities I have.

**Comment by blesh** [comment]
I believe this has been added.
