### ISSUE TITLE
combineAll does not emit on empty array

### ISSUE THREAD

**Issue by marcusnielsen** [ReactiveX/rxjs#1910]
Using rxjsv5 combineAll, I have an issue forming a state tree of children states. 

If I have an array of state streams, I can get the state data in an array corresponding to the streams. But if I switchMap from an array with n state streams to an array with zero state streams (empty array), combineAll will not emit anything. 

This makes the app state tree contain the old state data of the last non-empty array of state streams. 
I have fixed it right now by mapping the array of state streams to always concat a dummy stream with a dummy value, which is really confusing for other developers looking at the code and state tree.

* Stackoverflow link: http://stackoverflow.com/questions/39231343/combineall-does-not-emit-on-empty-array

* JS Bin link: http://jsbin.com/potiqa/edit?js,console

**Comment by trxcllnt** [comment]
`combineAll` won't emit unless the combined Observables emit at least one value, but you could check to ensure the collection you're combining is empty or not, and either combine or emit an empty Array:

```es6
var arrayOfStreamsStream = Rx.Observable
    .of(
        [], [
            Rx.Observable.of('blah-1'), // component state.
            Rx.Observable.of('blah-2'),
            Rx.Observable.of('blah-3')
        ], [], [
            Rx.Observable.of('foo-1'),
            Rx.Observable.of('qux-2')
        ]
    )
    .switchMap(function onMap(coll) {
        return coll.length === 0 ?
            Observable.of(coll) :
            Observable.combineLatest(...coll);
    })
    .subscribe(function onSubscribe(data) {
        console.log('onSubscribe START')
        console.dir(data)
        console.log('onSubscribe END')
    })
```

**Comment by marcusnielsen** [comment]
I will totally accept that as a good solution! Many thanks.

Please post to Stackoverflow if you'd like an accepted answer, or tell me otherwise so I can post it and close that one.

**Comment by marcusnielsen** [comment]
Wrote the answer on SO.
