### ISSUE TITLE
Bad typings for concat

### ISSUE THREAD

**Issue by OliverJAsh** [ReactiveX/rxjs#1915]
Version 5.0.0-beta.11

I'm having trouble with some of the provided typings. For example:

``` js
const x = Observable.of(1) // Observable<number>
const y = x.concat(x) // Observable<any>
```

I expected `y` to be `Observable<number>`. I tried to debug the typings but couldn't find where the generic was being lost. It seems to be related to `ObservableInput`, because if I change `concat`’s parameter typing from that to `Observable`, it works as expected.

Same problem with `Observable.merge(Observable.of(1))`

**Comment by kwonoj** [comment]
I'm seeing some interesting behavior of type inference regarding this. Seems small fix can be applied, will raise it as PR to check feasibility.

**Comment by david-driscoll** [comment]
This is actually related to #1880 and I've actually pinned myself to beta10 because this bug is so painful.  (There just hasn't been a beta12 / rc1 release yet)

**Comment by kwonoj** [comment]
I'd put this as bit long-term issue to revisit after TS 2.0 release.

**Comment by OliverJAsh** [comment]
Is this fixed now #1880 is closed?

**Comment by blesh** [comment]
Ping @kwonoj

**Comment by kwonoj** [comment]
As far as I remember plan to bump up to typescript 2.0 removes separate signature (https://github.com/ReactiveX/rxjs/pull/1978) will include additional changes. I'd close out this issue once PR checked in.

**Comment by OliverJAsh** [comment]
Not sure if this will also fix the typings for

``` ts
Observable.merge(
	Observable.of(1),
	Observable.of(2),
)
```

**Comment by kwonoj** [comment]
As #1978 checked in, closing issue now.
