### ISSUE TITLE
rxjs-es modules cannot be compiled with webpack2 & babel6

### ISSUE THREAD

**Issue by OshotOkill** [ReactiveX/rxjs#1917]
**dependencies version:**

rxjs : 5.0.0.beta-11
webpack: 2.1.0-beta.21
babel-core: 6.14.0

**Code to reproduce:**

`.babelrc`:

```
{
  "presets": [
    ["es2015", { "modules": false }]
  ]
}
```

`app.js`:

```
import { Observable } from 'rxjs-es/Observable'
import 'rxjs-es/add/observable/of'
import 'rxjs-es/add/operator/map'

const a = Observable.of(1, 2, 3, 4 ,5).map(x => x + 1)

a.subscribe(x => console.log(x))
```

**Expected behavior:**

tree-shaking codes without commonjs and compile them into es5 

**Actual behavior:**

![default](https://cloud.githubusercontent.com/assets/6079112/18231309/67b0ce20-72e9-11e6-93cb-654b4180432b.PNG)

`class Observable` still remains. Using `webpack.optimize.UglifyJsPlugin` will cause an error. 

![default](https://cloud.githubusercontent.com/assets/6079112/18231305/3ba8a5aa-72e9-11e6-957e-ade0807729d7.PNG)

However I tried some normal es6 codes with import/export and they had been compiled correctly.

According to #1806 I don't find any `async` word and `scheduler` to be used.

**Comment by kwonoj** [comment]
I assume this is somewhat similar to https://github.com/ReactiveX/rxjs/issues/1575, would you make sure your webpack config correctly configured to transpile modules under `./node_modules` as well? AFAIK webpack + babel by default exclude to transpile under `node_modules` requires explicit setup.

**Comment by OshotOkill** [comment]
@kwonoj How Foolish I am . I forgot to remove `exclude:  /node_modules/` in configuration files. Thanks for the help.
