### ISSUE TITLE
Question) operation for delta value.

### ISSUE THREAD

**Issue by mixed** [ReactiveX/rxjs#1918]
Hi. I`m rxjs newbie. I have a question. Sometimes, I need some operator for change value.
**example)**
When Delta value of window.scrollY moved more than 100px,  I need operator like delta.
```js
Observable.fromEvent(window, 'scroll')
	.observeOn(Scheduler.animationFrame)
	.map((item) => {
		return window.scrollY;
	})
	.delta((scrollY, standardScrollY, count) => {
		return Math.abs(scrollY - standardScrollY) >= 100;
	})
	.subscribe((e) => {
		let color = getRandomColor();
		let test = document.getElementById('test');	
		test.style.backgroundColor = `${color}`;
	});
```

![image](https://cloud.githubusercontent.com/assets/22300/18242122/bcd59ee8-738f-11e6-8239-4795373bbd32.png)

 I have developed prototype code.
 ```js
 Observable.prototype.delta = function (callback) {
	return Observable.create((observer) => {
		var idx = 0, standardItem;
		return this.subscribe(
			(x) => {
				var result;
				try {
					if(idx === 0){
						standardItem = x;
					}
					result = callback(x, standardItem, idx);
					idx++;
				} catch (e) {
					observer.error(e);
					return;
				}
				if(result){
					idx = 0;
					standardItem = x;
					observer.next(x);
				}
			},
			observer::error(),
			observer::complete()
		);
	});
};

```
**Question 1)**
How could I make this logic using another operator? I can`t found proper operator.

**Question 2)**
If RXJS not support similar operator. I think that this operator be useful. What do you think about this operator? If you agree with me. I going to send pr that fit [guide](https://github.com/ReactiveX/rxjs/blob/master/doc/operator-creation.md)  after I transform to ts

**Comment by kwonoj** [comment]
What about using `scan`? Rough code will looks like

```js 
Rx.Observable.of(100, 110, 150, 160, 190, 200, 250, 270, 320, 340, 350)
  .scan((acc, val, index) => {
    acc.value = val;
    acc.withinThreshold = Math.abs(val - acc.initial) >= 100;
    if (index === 0 || acc.withinThreshold) {
      acc.initial = val;
    }
    return acc;
  }, {
    initial: 0,
    val: null,
    withinThreshold: false
  })
  .filter(x => x.withinThreshold)
  .subscribe(console.log.bind(console));
```

and output will be

>{ initial: 100, val: null, withinThreshold: true, value: 100 }
{ initial: 200, val: null, withinThreshold: true, value: 200 }
{ initial: 320, val: null, withinThreshold: true, value: 320 }

**Comment by mixed** [comment]
Thank @kwonoj for your comments. :) I have been seen your idea like reduce...and...filter. I think that This case have low readability for me. but  Many people seems to use this pattern. [[1](http://stackoverflow.com/a/28330830/2168994)]
