### ISSUE TITLE
Unexpected behavior when an Observable throws while performing a map and is converted to a promise

### ISSUE THREAD

**Issue by joeeames** [ReactiveX/rxjs#1922]
**RxJS version:**
5.0.0-beta.11
**Code to reproduce:**
http://plnkr.co/edit/EsawlcM58rQfBa8Nuub7?p=preview

In this plunk, I have a simple observable, which I map over. During the map, on the first value, I return Observable.throw. Then I take the result and call toPromise() to it. I expect the resulting promise to be rejected, but it's not.

**Expected behavior:**
The resulting promise is rejected, just as when you call throw from an observable without mapping over it.

**Actual behavior:**
the promise is resolved, but it's resolved with a ErrorObservable object

**Additional information:**

**Comment by kwonoj** [comment]
That's cause `map` returns `Observable` itself, while it doesn't 'flatten` inner observables. I assume what you'd expect is `flatMap` (or `mergeMap`) such as 

```js
let o1 = Observable
      .of(42).flatMap(val => {
      return Observable.throw('some error');
    })
  
o1.toPromise()
  .then((value) => console.log('Resolved!', value, arguments))
  .catch((err) => console.log('Rejected!', err));
```

**Comment by joeeames** [comment]
Thank you. Sorry this ended up being a "I don't understand" issue.
