### ISSUE TITLE
_catch vs catch breaks ESM code built against the rxjs umd bundle

### ISSUE THREAD

**Issue by IgorMinar** [ReactiveX/rxjs#1924]
**RxJS version:**
beta.11

**Code to reproduce:**
```
import {_catch} from 'rxjs/operator/catch';
```
full source: https://github.com/angular/angular/blob/ee88c3c976654f15d41f8d35345ad96026fe5fe8/modules/%40angular/router/src/apply_redirects.ts#L14

+ rollup config:
```
export default {
  entry: '../../../dist/packages-dist/router/index.js',
  dest: '../../../dist/packages-dist/router/bundles/router.umd.js',
  format: 'umd',
  moduleName: 'ng.router',
  globals: {
    ...
    'rxjs/operator/catch': 'Rx.Observable.prototype'
  }
}
```
full source: https://github.com/angular/angular/blob/ee88c3c976654f15d41f8d35345ad96026fe5fe8/modules/%40angular/router/rollup.config.js#L30

**Expected behavior:**

the router bundle should be able to get hold of the `_catch` operator from the prototype via `_catch` property.

**Actual behavior:**

the `_catch` operator is not found because in the UMD bundle it was exported as `catch` (without the leading underscore).

**Additional information:**

Angular router bug that first raised this issue: https://github.com/angular/angular/issues/11300
Reproduction: http://plnkr.co/edit/aSPFwbLNxlT5sQzSyGIN?p=preview

**Comment by jayphelps** [comment]
For our reference, these are all the operators I could find that would have this problem:

* `_catch`
* `_switch`
* `_do`
* `_finally`

**Comment by jayphelps** [comment]
@IgorMinar Just so we have all the bases covered with full context, are you not adding the operators to an Observable prototype because you want _absolutely no_ operators on them by default?

**Comment by IgorMinar** [comment]
@jayphelps correct. we don't want loading of Angular's router to have a side-effect of monkey-patching the Observable prototype.
