### ISSUE TITLE
Error on complete when using .bufferTime().take() and supplying a maxBufferSize

### ISSUE THREAD

**Issue by sbm007** [ReactiveX/rxjs#1944]
**RxJS version:**
rxjs@5.0.0-beta.12

**Code to reproduce:**
[jsbin example](https://jsbin.com/megavewube/1/edit?js,console)

```
Rx.Observable.interval(100)
  .bufferTime(1000, null, 5)
  .take(5)
  .subscribe(console.log.bind(console.log));
```

**Expected behavior:**
Stream should complete without any errors.

**Actual behavior:**
Throws a TypeError on complete:

```
Uncaught TypeError: Cannot read property 'push' of null
    BufferTimeSubscriber.openContext @ Rx.js:6288
    BufferTimeSubscriber.onBufferFull @ Rx.js:6280
    BufferTimeSubscriber._next @ Rx.js:6256
    Subscriber.next @ Rx.js:1301
```

**Additional information:**
- This bug only occurs when supplying a maxBufferSize and using a bufferCreationInterval of null.
- Looking at the code the problem is quite obvious, need to guard `this.contexts` in `BufferTimeSubscriber.prototype.openContext`
- Very similar to issue #1763 / PR #1764

**Comment by kwonoj** [comment]
Thanks for report. as I did similar changes to guard, let me take a look at this as well.
