### ISSUE TITLE
doc error

### ISSUE THREAD

**Issue by aiyadingya** [ReactiveX/rxjs#1947]
!(error document)[http://reactivex.io/rxjs/manual/overview.html]
error:
 
      var button = document.querySelector('button');
      Rx.Observable.fromEvent(button, 'click')
          .throttle(1000)
          .scan(count => count + 1, 0)
          .subscribe(count => console.log('Clicked ${count} times'));
`throttle(1000)` => `throttleTime(1000)`,

**Comment by jayphelps** [comment]
Thanks for reporting! This has already been fixed, just hasn't been published to the docs yet. https://github.com/ReactiveX/rxjs/commit/89688b9551f00363d61246c0e5cc7695b344621c
