### ISSUE TITLE
[Subscriber] next context/binding

### ISSUE THREAD

**Issue by MadMub** [ReactiveX/rxjs#1948]
Not sure if this is intended behaviour but passing functions to the operators ends up binding `this` within those functions to `SafeSubscriber`.
**RxJS version:**
5.0.0-beta10
**Code to reproduce:**

```
let obj = {
  foo() {
    this.bar();
  },
  bar() { }
};

someObservable.do(obj.foo).subscribe();    
```

**Expected behavior:**
`foo` can call `bar` without the need for the developer to bind
**Actual behavior:**
`this` inside `foo` refers to SafeSubscriber
**Additional information:**
someone in the rxjs gitter helped trace though the js code to the following
http://reactivex.io/rxjs/file/es6/Subscriber.js.html#lineNumber213

the following code from that file:

```
        let context = this;
        if (isFunction(observerOrNext)) {
            next = observerOrNext;
        }
        else if (observerOrNext) {
            context = observerOrNext;
            next = observerOrNext.next;
            error = observerOrNext.error;
            complete = observerOrNext.complete;
            if (isFunction(context.unsubscribe)) {
                this.add(context.unsubscribe.bind(context));
            }
            context.unsubscribe = this.unsubscribe.bind(this);
        }
        this._context = context;
```

leads me to believe `isFunction` evaluates to true, thus the context is set to `SafeSubscriber` ~~and not left alone (which is what I think should happen). Apologies if this is not a bug and intended behaviour, might be worth noting in the docs that we should not pass functions by reference directly to the operators.~~

EDIT: I could have sworn binding was only ever needed for prototyped methods, putting some raw es5 code in the jsfiddle proves to error as well.

```
var obj = {
    foo: function() {
      this.bar()
    },
    bar: function() {
      console.log('i work');
    }
}

function callThing(fn) {
 fn();
}

callThing(obj.foo);
```

Will close unless having `this` bound to SafeSuscriber is erroneous

**Comment by jayphelps** [comment]
Passing a function by reference, like `do(obj.foo)` _definitely_ detaches the context aka `this`. That's just JavaScript*

So I think ideally `this` in this example should actually be `undefined`. It's simply the instance of `SafeSubscriber` because we're accidentally leaking internal details. While not a "bug", it is something we should probably not do, so keeping this open for now.

If you want to keep the `this` context, you can do one of these:

```js
.do(value => obj.foo(value))
// or
.do(obj.foo.bind(obj))
```

*in JS, `this` isn't normally something that is truly "set" or not when dealing with function references. `this` inside of a function is typically the object in which the function was _called on_. So when invoking it as `obj.foo()`, we're calling the `foo` function _on the context of `obj`_, so it is the `this`. But if you did `const foo = obj.foo; foo()`, we're not calling `foo` on any object, so there's no context at all. In strict mode/ES2015, `this` will be `undefined`. All of this is moot if you use `foo.bind(obj)`, in which you are saying "bind this object as the `this` no matter what".

**Comment by trxcllnt** [comment]
@MadMub functions defined on Object literals aren't automatically bound to the Object instance, so passing them by reference as arguments to `do` or `subscribe` doesn't guarantee they'll be executed in the context of the Object instance.

The code you've referenced is us jumping through all the hoops to ensure that `next`, `error,` `complete`, and `unsubscribe` actually _are_ called in the context of the Object they're defined on, assuming you pass that Object as the `Subscriber` to `do` or `subscribe`:

```es6
import { Observable } from 'rxjs';

let anonymousObserver = {
  next(value) { this.bar(`next value: ${value}`); },
  unsubscribe() { this.bar('unsubscribed!'); },
  bar(value) { console.log(`bar says ${value}`); }
};

Observable.of(10).subscribe(anonymousObserver);
```

`SafeSubscriber` also ensures that errors thrown while synchronously notifying are caught, so the source Observable has a chance to return its unsubscribe logic, then synchronously re-thrown to the caller:


```es6
import { Observable } from 'rxjs';

const reallyExpensiveSyncObservable = Observable.create((subscriber) => {
  var reallyExpensiveThing = /*allocate a bunch of memory*/ {};
  console.log(`allocated a bunch of memory O.O`);
  while (!subscriber.closed) {
    subscriber.next('some events');
    // If `subscriber.next()` throws, this function would never
    // get a chance to return `deallocateExpensiveThing`, which
    // could be a big problem for someone.
  }
  return function deallocateExpensiveThing() {
    /* de-allocate the memory on unsubscribe */
    reallyExpensiveThing = null;
    console.log(`de-allocated all that memory =)`);
  };
});

// errors thrown while a source is synchronously emitting
// are synchronously re-thrown so they can be caught in a
// try-catch
try {
  reallyExpensiveSyncObservable.subscribe((value) => {
    throw "bad value :(";
  })
} catch (e) {
  console.log(`caught an error! ${e}`);
}
```

Hope this helps.

**Comment by kwonoj** [comment]
I'm closing this issue as it's inactive, think provided answer explains current behavior sufficiently. Please feel freely reopen if you believe there's some incorrect behavior in Rx side need to be fixed.

**Comment by HoumanKml** [comment]
A useful pattern is to bind this to the callback function

```
// subscribing to an Observable<HttpResponse>
const httpReponseSub = httpResponse$().first()
      .do(sideEffects.bind(this));
      .subscribe(onSuccess.bind(this), onError.bind(this));
````
