### ISSUE TITLE
Property 'target' and also length does not exist on type '{}' -  angular 2

### ISSUE THREAD

**Issue by WaqarMH** [ReactiveX/rxjs#1951]
```typescript
import { Component } from '@angular/core';
import { Http } from '@angular/http';
import { Observable } from 'rxjs/observable';
import 'rxjs/Rx';

@Component({
moduleId: module.id,
selector: 'app-root',
template: '<input type="text" id="search" placeholder="Write Something" class="input input-lg">',
styleUrls: ['app.component.css'],
})

export class AppComponent {
        constructor() {
            var keyups = Observable.fromEvent(document, 'keyup')
            .map(e => e.target.value)  //[ts] Property 'target' does not exist on type '{}'.any
            .debounceTime(200)
            .filter(text => text.length >= 3); //Property 'length' does not exist on type '{}'.

            keyups.subscribe(data => console.log(data));
        }
}
```

*mod_edit: wrapped source code in \`back ticks\`*

**Comment by trxcllnt** [comment]
@WaqarMH looks like TypeScript can't infer the event type. I don't know the exact name, but something like `Observable.fromEvent<KeyEvent>(document, 'keyup')` should work.

**Comment by WaqarMH** [comment]
export class AppComponent {
        constructor() {
            var keyups = Observable.fromEvent($('#search'), 'keyup') // it also give error on this 
            .map(e => e.target.value)
            .debounceTime(200)
            .filter(text => text.length >= 3);

            keyups.subscribe(data => console.log(data));
        }
}

**Comment by david-driscoll** [comment]
It's the same error, the type system can't infer the event type.  It's possible to combine it with the mappings from `lib.d.ts` but that would be a lot of work for not a ton of gain really.

Also it would likely cause issues if someone is using rxjs with TS2.0 and doesn't include the `lib.dom.d.ts` which is a completely valid scenario for nodejs or service workers, etc.

Now we could add additional overloads, that excludes `T` and substitutes it for `any`, but then it won't be so obvious to the consumer that _could_ add a type annotation.  I feel like this error at least makes you think about what event type your consuming, so you don't get hit by it later on.

**Comment by blesh** [comment]
Yes, given what [we have in here](https://github.com/ReactiveX/rxjs/blob/e91d113e49acc9b0e12e2524040fa84cf3fa2c78/src/observable/FromEventObservable.ts#L54-L57), which is the best we can do considering what that function does, you'll want to follow @trxcllnt's advice and supply a type to `fromEvent<KeyEvent>`. Since `fromEvent` will work on *anything* is an `addEventListener` or `on` etc... and those don't necessarily *have* to return any specific type, there isn't much we can do to help on our end. You'll just have to provide a type... from there you'll be fine.

I'm closing this issue for now.

**Comment by franzkurt** [comment]
getFiles(e){
        this.files= e.dataTransfer ? e.dataTransfer.files : e.target.files;
}

**Comment by AhHa45** [comment]
`KeyEvent` doesn't exist in ES6, `KeyboardEvent` doesn't have a `target` attribute.
Simply use `any` like this
`Observable.fromEvent(yourEvent).map((event: any) => { return event.target.value; });`
