### ISSUE TITLE
timer on animationFrame scheduler is broken in 5.0.0-beta.12

### ISSUE THREAD

**Issue by chirayuk** [ReactiveX/rxjs#1952]
**RxJS version:**  v5.0.0-beta.12

**Code to reproduce:**

```
Rx.Observable.timer(0, 1000, Rx.Scheduler.animationFrame).subscribe((x) => console.log(x));
```

**Expected behavior:**
I expect no exceptions and a console log every second.

**Actual behavior:**
A stacktrace every second (as long as there is no other animation frame scheduler action already queued by by something else.)

```
Uncaught TypeError: Cannot read property 'execute' of undefinedAnimationFrameScheduler.flush @ main_bundle.js?FXszpMTp_x7svlvayVh8cQ==:54276
setInterval (async)AsyncAction.requestAsyncId @ main_bundle.js?FXszpMTp_x7svlvayVh8cQ==:54449
AnimationFrameAction.requestAsyncId @ main_bundle.js?FXszpMTp_x7svlvayVh8cQ==:54225
AsyncAction.schedule @ main_bundle.js?FXszpMTp_x7svlvayVh8cQ==:54444
TimerObservable.dispatch @ main_bundle.js?FXszpMTp_x7svlvayVh8cQ==:43938
AsyncAction._execute @ main_bundle.js?FXszpMTp_x7svlvayVh8cQ==:54495
AsyncAction.execute @ main_bundle.js?FXszpMTp_x7svlvayVh8cQ==:54470
AnimationFrameScheduler.flush @ main_bundle.js?FXszpMTp_x7svlvayVh8cQ==:54276
requestAnimationFrame (async)AnimationFrameAction.requestAsyncId @ main_bundle.js?FXszpMTp_x7svlvayVh8cQ==:54232
AsyncAction.schedule @ main_bundle.js?FXszpMTp_x7svlvayVh8cQ==:54444
Scheduler.schedule @ main_bundle.js?FXszpMTp_x7svlvayVh8cQ==:40084
TimerObservable._subscribe @ main_bundle.js?FXszpMTp_x7svlvayVh8cQ==:43943
Observable.subscribe @ main_bundle.js?FXszpMTp_x7svlvayVh8cQ==:39607
(anonymous function) @ VM3011:1
```

**Additional information:**
I think this used to work in `v5.0.0-beta.9`

**Comment by chirayuk** [comment]
Stepping into the debugger, it appears that it goes executes [`let action: AsyncAction<any> = actions.shift();`](https://github.com/ReactiveX/rxjs/blob/master/src/scheduler/AnimationFrameScheduler.ts#L14) and then the do loop using this action—but the actions array has no items.

**Comment by trxcllnt** [comment]
Ah looks like I forgot the initial action argument in the Asap and AnimationFrame Schedulers' flush methods. Will prepare a fix this weekend.

@chirayuk in the meantime, you can use `Scheduler.async`, since that's what the Asap and AnimationFrame Schedulers default to if the scheduled delay is > 0.

**Comment by trxcllnt** [comment]
@kwonoj @chirayuk fix easier than I expected, #1953 awaiting review.

**Comment by chirayuk** [comment]
@trxcllnt Thanks for the quick fix.  I'm using a workaround.  Are the beta releases scheduled at some regular cadence?

**Comment by kwonoj** [comment]
as new packages are published I think this issue is now resolved. Closing for now - @chirayuk , feel freely reopen if it's still occurring.
