### ISSUE TITLE
rxjs-es cannot be bundled by rollup or webpack

### ISSUE THREAD

**Issue by mistyharsh** [ReactiveX/rxjs#1954]
I am trying to use ES6 version of the rxjs by following instructions written in docs http://reactivex.io/rxjs/manual/installation.html:

``` bash
npm install rxjs-es --save
```

and using in my file as:

``` javascript

import Rx from 'rxjs/Rx';
Rx.Observable.of(1,2,3)
```

This throws the error: `Error: Could not resolve 'rxjs/Rx.js'`. So i modified my import to make it work:

``` javascript
import * as Rx from 'rxjs-es/Rx.js';
```

Now this generates a bundle but I see the error on browser console: `Uncaught ReferenceError: OuterSubscriber is not defined`
After debugging a bit I realized that bundle is not being generated the way it should be. However If I modify my imports to pick only what I need then it works:

``` javascript
import {Observable} from 'rxjs-es/Observable';
import 'rxjs-es/add/observable/of';
import 'rxjs-es/add/operator/map';

let observable = Observable.of(1,2,3);
```

I looked through old commits, issues and stackoverflow but could not find anything substantial. My rollup.js script looks like this:

``` javascript
gulp.task('jsbundle', () => {

    return rollup({
        entry: './src/commons/js/main.js',
        treeshake: true,
        plugins: [
            nodeResolve({
                module: true,
                jsnext: true,
                main: true
            }),
        ]
    }).then(bundle => {
        return bundle.write({
            format: 'iife',
            dest: './dist/commons/js/main.js'
        });
    });
});
```

Then I switched to commonjs package using `npm install rxjs` and tried to consume this using rollup via `rollup-plugin-commonjs` plugin. Then it works perfectly.

To further investigate, I did the same with **Webpack**. And I found the similar result. If I try to import entire core set of `Rx` functionality, then **rxjs-es** package doesn't work.

I am still not able to entirely figure out exact cause of the problem. I am willing to raise a PR if I can find out exact problem.

**Comment by kwonoj** [comment]
as RxJS no longer publishes `rxjs-es` and recommend to use `rxjs` or `@reactivex/rxjs`, I think this issue can be closed by recommend to use CJS package published.
