### ISSUE TITLE
More idiot-proof npm install commands in README?

### ISSUE THREAD

**Issue by alex-dixon** [ReactiveX/rxjs#1964]
Hey. Thanks for your work. I really appreciate it.

Would it be possible to feature the simplest, most one-size-fits-all `npm install` command front and center in your README? Seems like that's just `npm install rxjs` but that wasn't obvious to me. I think it's listed second and was accompanied by ES5 examples, which as an ES6/7 user made me avoid it. 

Also might be nice to add `--save` to the `npm install`s in the README for those who copy and paste into their terminal. My guess is most of us intend to write `rxjs` to package.json.

😅

**Comment by ladyleet** [comment]
i like this issue @blesh

**Comment by blesh** [comment]
I hope to see your PR soon, @ladyleet

**Comment by benlesh** [comment]
PING @ladyleet  ... a year and a half later :P haha.

**Comment by ladyleet** [comment]
hahaha :)

**Comment by alex-dixon** [comment]
Not enough idiots out there. Closing.
