### ISSUE TITLE
feat(TypeScript): enable 'noUnusedLocals' options

### ISSUE THREAD

**Issue by saneyuki** [ReactiveX/rxjs#1969]
- This would be useful to clean up our codes.
- We detect unused variables at compile time.
- We can replace tslint's `no-unused-variable`.

**Comment by saneyuki** [comment]
And we could be able to disable tslint's `no-unused-variable` rule. It might be decrease the time to run tslint

**Comment by kwonoj** [comment]
@saneyuki , please aggregate into single issue to track enabling TS 2.0 specific features. I don't think it's need to be tracked as separated issue for each options.

**Comment by kwonoj** [comment]
Long-hanging task tracking issue https://github.com/ReactiveX/rxjs/issues/1837 can be used for those purpose.

**Comment by saneyuki** [comment]
@kwonoj Ah, okay. I'll change title and description of #1837

**Comment by saneyuki** [comment]
Duplicated #1837

**Comment by saneyuki** [comment]
I'll reopen as a separated tracking issue.

**Comment by saneyuki** [comment]
If we replace tslint's `no-unused-variable`, the exec time of tslint will be decreased.

## The result of `time npm run lint_src` 
env: MacBook Pro (Retina, 15-inch, Mid 2014), 2.8 GHz Intel Core i7


| | real | user | sys|
|---|----|------|-------
| before |  6.85 | 6.97 | 0.28|
| after |  5.26 | 5.16 | 0.29 |

**Comment by kwonoj** [comment]
as this issue is discussed in https://github.com/ReactiveX/rxjs/pull/2104 and concluded to not to introduce compiler level option, I believe issue can be closed.
