### ISSUE TITLE
enable 'noUnusedParameters' options

### ISSUE THREAD

**Issue by saneyuki** [ReactiveX/rxjs#1970]
This would be useful to clean up our codes.

**Comment by saneyuki** [comment]
Duplicated #1837

**Comment by saneyuki** [comment]
We tried to enable once at #2024, but then we could not make a consensus to land it because we'd like to focus to ship v5 stable and there still be inconsistent the naming conventions. (see also [the meeting note](https://github.com/ReactiveX/rxjs-core-notes/blob/master/2016-10/october-24.md#outstanding-prs)).

So I'll reopen this as a tracking bug for the future.

**Comment by kwonoj** [comment]
Note TSlint now deprecated `no-unused-variable` and consider to remove it in a further version.

https://github.com/palantir/tslint/issues/1617

**Comment by benlesh** [comment]
Closing as stale.
