### ISSUE TITLE
chore(package.json): Use npm's @types packages to manage d.ts files

### ISSUE THREAD

**Issue by saneyuki** [ReactiveX/rxjs#1972]
- We can remove the dependency for `typings` package.
- And it will simplify a dependency management.

**Comment by saneyuki** [comment]
Duplicated #1837

**Comment by saneyuki** [comment]
I'll reopen as a separated tracking issue.

**Comment by kwonoj** [comment]
I believe this issue is already resolved in latest master.

**Comment by saneyuki** [comment]
@kwonoj Oops, I missed it. Thank you!
