### ISSUE TITLE
Add API for passive event listeners to Observable.fromEvent

### ISSUE THREAD

**Issue by appsforartists** [ReactiveX/rxjs#1973]
There's now a [passive mode on event listeners](https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md) that explicitly opts out of calling `event.preventDefault`, which allows the browser to guarantee composited scrolling without being blocked by the event loop.

Can we add an options object to the signature of Observable.fromEvent:

```javascript
Observable.fromEvent(element, 'pointerup', selectorFn);
```

becomes

```javascript
Observable.fromEvent(element, 'pointerup', namedArgs, selectorFn);
```

where `namedArgs` could be `{passive: true}`?

**Comment by appsforartists** [comment]
There's also a [`once` parameter](https://trac.webkit.org/changeset/201735/trunk/Source).  Perhaps RxJS should look for known named args in the named args dict and do the right thing (e.g. `complete()` after the first emission) if it knows the semantics of a named arg.

**Comment by blesh** [comment]
This request seems reasonable

**Comment by appsforartists** [comment]
Looks like [this has been done](https://github.com/ReactiveX/rxjs/pull/1845/files#diff-b66649012c6589d424eccfd864157c59R57)
