### ISSUE TITLE
Non expected behavior in tutorial example

### ISSUE THREAD

**Issue by markmeyerphoto** [ReactiveX/rxjs#1975]
The first example in rxjs/doc/tutorial/basics.md - Creating observables - produces no output. 

    var myObservable = Rx.Subject.create();  
    myObservable.subscribe(value => console.log(value));  
    myObservable.next('foo');
 
Is this a typo? Show it be `var myObservable = new Rx.Subject` ?

**Comment by blesh** [comment]
> Is this a typo? Show it be var myObservable = new Rx.Subject

Yes. this is a typo. `Subject.create` does something completely different than `new Subject()`. It's made for combining an observer and an observable into a subject, not simply newing up a subject.

This is probably a point for debate for future versions of the library (the current behavior mirrors what's existed in prior versions), but at the very least, this is a bug in the docs.
