### ISSUE TITLE
What is the relationship between `Reactive-Extensions/RxJS` and `ReactiveX/rxjs`?

### ISSUE THREAD

**Issue by xareelee** [ReactiveX/rxjs#1979]
I found two RxJS libraries on Github, one is [ReactiveX/rxjs](https://github.com/ReactiveX/rxjs), another one is [Reactive-Extensions/RxJS](https://github.com/Reactive-Extensions). What is the relationship and difference between them?

**Comment by kwonoj** [comment]
Please refer https://github.com/ReactiveX/rxjs/blob/master/README.md#rxjs-5-beta for more detailed description, basically this repo is major version update of RxJS and rewrite of implementation.
