### ISSUE TITLE
observer.next does not allow point free style

### ISSUE THREAD

**Issue by rasmusvhansen** [ReactiveX/rxjs#1981]
**RxJS version:**
beta12

**Code to reproduce:**
http://jsbin.com/gicizoxefi/edit?js,console

**Expected behavior:**
I would expect 

    sayHi(observer.next);

to work, 

**Actual behavior:**
but it throws a cryptic error.
´´´
error_handler.js:45EXCEPTION: Cannot read property 'isStopped' of nullErrorHandler.handleError @ error_handler.js:45next @ application_ref.js:273schedulerFn @ async.js:82SafeSubscriber.__tryOrUnsub @ Subscriber.js:223SafeSubscriber.next @ Subscriber.js:172Subscriber._next @ Subscriber.js:125Subscriber.next @ Subscriber.js:89Subject.next @ Subject.js:55EventEmitter.emit @ async.js:74onError @ ng_zone.js:120onHandleError @ ng_zone_impl.js:64ZoneDelegate.handleError @ zone.js:207Zone.runGuarded @ zone.js:113(anonymous function) @ zone.js:86
´´´

If I do 

    sayHi(m => observer.next(m));

it works

**Additional information:**

**Comment by trxcllnt** [comment]
JavaScript doesn't explicitly bind prototype methods to their instance, and neither do we. Additionally, the Observer notification methods aren't implemented as closures on the Observer for performance' sake.

**Comment by rasmusvhansen** [comment]
Fair enough. Could the error message be improved maybe? By checking `this` inside the observer.next function and throw if it is not as expected.

**Comment by trxcllnt** [comment]
@rasmusvhansen it's likely lead to a significant performance regression, which would be a non-starter for us. Minimizing operations inside `next` is critical to real-world performance metrics.

I believe there's work planned soon to create special internal Observers (even more sparse, but will be easier for JIT to inline), but enhance the public Observer types at the ends of each sequence. It might be possible to put more error condition checking after that's done cc: @blesh who knows more about that timeline

**Comment by blesh** [comment]
> I believe there's work planned soon to create special internal Observers (even more sparse, but will be easier for JIT to inline), but enhance the public Observer types at the ends of each sequence. It might be possible to put more error condition checking after that's done cc: @blesh who knows more about that timeline

Even in that case, we won't be able to provide what @rasmusvhansen is asking for in a performant way. The observer provided when constructing an Observable contains important internal state to provide safety in terms of things like not being able to `next` after an `error` for example. Basically, observers must be able to be `closed` and check that state from within `next`, `error` or `complete`.

I'm going to mark this issue as "won't fix" and close it for now.

Sorry, @rasmusvhansen, it's just not something that's possible with our goals for this library.

However, you might be happy to learn that the performance of `bind()` has increased _substantially_ across many browsers over the last year, and I expect that trend to continue.
