### ISSUE TITLE
scan function returns ReduceSignature interface rather than ScanSignature interface

### ISSUE THREAD

**Issue by FabienInext** [ReactiveX/rxjs#1984]
RxJS version: 5.0.0-beta.12

Since 5.0.0-beta.11 "scan" function returns ReduceSignature interface rather than ScanSignature interface.

The return type is always T rather than R which is not the expected behavior.

Thank you.

Fabien

**Comment by kwonoj** [comment]
`scan` and `reduce` shares same signature by both of them have same type definition, and it support different return value as signature defined as below : 

```js
export interface ReduceSignature<T> {
  (accumulator: (acc: T, value: T, index: number) => T, seed?: T): Observable<T>;
  (accumulator: (acc: T[], value: T, index: number) => T[], seed?: T[]): Observable<T[]>;
  <R>(accumulator: (acc: R, value: T, index: number) => R, seed?: R): Observable<R>;
}
```

you may need supply type to allow compiler infer it though (example: https://github.com/ReactiveX/rxjs/blob/e20cdb73e9a6255d704e39c2e867b3227207b4b0/spec/operators/reduce-spec.ts#L253-L262)

Just fyi, there's opened PR to remove ***signature and use function type directly via TypeScript 2.0, so naming difference will eventually go.
