### ISSUE TITLE
Consuming rxjs-es using webpack and babel causes invalid code while resolving imports

### ISSUE THREAD

**Issue by jh3141** [ReactiveX/rxjs#1992]
**RxJS version:** 5.0.0 beta 12

**Code to reproduce:**
In a project using webpack and babel to translate ES6 to traditional javascript:
* Add an 'include' directive to the babel loader to allow babel to translate the rxjs-es module
* Add `import Rx from 'rxjs-es';` to the main source file of the project
 
**Expected behavior:**
rxjs-es is transpiled down to standard javascript and can be used in the project

**Actual behavior:**
The transpiled code contains the following chunk of invalid javascript that causes a runtime error during initialisation:

```
/*!***********************************!*\
  !*** ../~/rxjs-es/util/assign.js ***!
  \***********************************/
/***/ function(module, exports, __webpack_require__) {

	'use strict';
	
	Object.defineProperty(exports, "__esModule", {
	    value: true
	});
	exports.assign = undefined;
	
	var _root = __webpack_require__(/*! ./root */ 417);
	
	var Object = _root.root.Object;

```

This does not work because the existence of the variable `Object` shadows the standard variable `Object` which the import code expects to be able to access, but because the definition is later in the file its value is not available at the time the import code needs it.  As `Object` is not exported from this module, renaming it to something else would be a suitable workaround for this issue.

**Additional information:**

See also this bug filed against webpack: https://github.com/webpack/webpack/issues/2618

While it does seem the problem is essentially webpacks, it doesn't seem they're making much progresss on solving a potentially difficult issue, whereas it would be trivial to work around it here.

**Comment by kwonoj** [comment]
Related to https://github.com/ReactiveX/rxjs/issues/1671 . Actually there's discussion to not publish sole ES2015 package, which will remove these problems eventually (I hope).

**Comment by jayphelps** [comment]
We've decided to stop publishing rxjs-es for now per #2019 because it's caused more problems than it solved. We'll continue considering similar solutions for the future!
