### ISSUE TITLE
Observable.merge

### ISSUE THREAD

**Issue by softchris** [ReactiveX/rxjs#1994]
**RxJS version:**
 rxjs@5.0.0-beta.12
**Code to reproduce:**
function getData() {
return Rx.Observable.merge(
            Rx.Observable.from([1,2,3,4]),
            Rx.Observable.from([5,6,7,8])
        )
}

getData.subscribe((data) =>  console.log(data) );
**Expected behavior:**
1,5,2,6,3,7,4,8   like it did in Rx 4.x.   
**Actual behavior:**
it outputs 1,2,3,4,5,6,7,8  thereby no different from concat

  

**RxJS version:**

**Code to reproduce:**

**Expected behavior:**

**Actual behavior:**

**Additional information:**

**Comment by trxcllnt** [comment]
@softchris this is because Observables now emit synchronously by default. You can use the `queue` or `asap` schedulers if you want sync Observables to emit interleaved values:

```javascript
Rx.Observable.merge(
  Rx.Observable.from([1,2,3,4], Rx.Scheduler.asap),
  Rx.Observable.from([5,6,7,8], Rx.Scheduler.asap)
)
 ```

**Comment by blesh** [comment]
@trxcllnt is correct. Closing this for now. Feel free to add additional contents if you have questions

**Comment by softchris** [comment]
thanks for the clearification :)
