### ISSUE TITLE
Commit `dist` folder with each PR

### ISSUE THREAD

**Issue by trxcllnt** [ReactiveX/RxJS#200]
@blesh @jeffbcross We can't use the library in non-TypeScript projects without committing the `dist` folder. We should commit the latest built files as a part of each PR.

**Comment by ktrott** [comment]
Shouldn't we set up CI do those steps as part of the merge rather than
developers committing the dist?

On Aug 21, 2015, at 3:54 AM, Paul Taylor <notifications@github.com> wrote:

@blesh <https://github.com/blesh> @jeffbcross
<https://github.com/jeffbcross> We can't use the library in non-TypeScript
projects without committing the dist folder. We should commit the latest
built files as a part of each PR.

—
Reply to this email directly or view it on GitHub
<https://github.com/ReactiveX/RxJS/issues/200>.

**Comment by ktrott** [comment]
Or sorry is that what you meant?

On Aug 21, 2015, at 3:54 AM, Paul Taylor <notifications@github.com> wrote:

@blesh <https://github.com/blesh> @jeffbcross
<https://github.com/jeffbcross> We can't use the library in non-TypeScript
projects without committing the dist folder. We should commit the latest
built files as a part of each PR.

—
Reply to this email directly or view it on GitHub
<https://github.com/ReactiveX/RxJS/issues/200>.

**Comment by blesh** [comment]
@trxcllnt I think the plan was to start publishing all built files to npm very, very soon.

**Comment by blesh** [comment]
The problem with committing the dist is it makes for some really hellish merges.

**Comment by trxcllnt** [comment]
@ktrott I'm fine with CI doing the build, but I'm not certain if it can (force) push a follow-up commit with the new built code.

> @blesh The problem with committing the dist is it makes for some really hellish merges.

But since our commits are so granular, the `dist` merge shouldn't be any more difficult than the rest of the merges, right?

**Comment by blesh** [comment]
> But since our commits are so granular, the dist merge shouldn't be any more difficult than the rest of the merges, right?

This is probably one of those things that's true 80% of the time. But considering that we have 5-6 types of distributed files (AMD, CJS, ES6, ES5 global, TypeScript, Minified, etc) the odds that you'll run into a hellish merge are much, much higher.

I think we should either:

1) Start publishing this to npm and use a pre-publish step to build out the dist folder

or 

2) Add something to CI that takes successfully built commits from master, builds the dists and pushes them to another repository that is then published to npm as `canary` or `master`. It would also push Tagged builds. I know tools like this exist, I'm just not sure where. I think Ember does something like this.

**Comment by staltz** [comment]
> 1) Start publishing this to npm and use a pre-publish step to build out the dist folder

Yes. And the pre-alpha (pre-whatever) status of the library on npm can be reflected as a version tag, e.g. `0.0.0-alpha1` so it can't be installed with patterns like `0.0.x`, you need to specifically ask for `0.0.0-alpha1`.

**Comment by blesh** [comment]
@trxcllnt ... did this discussion flesh things out for you a little? Can we close this issue and proceed as planned? (the plan being some sort of pre-publish step that builds and publishes built files to npm)

**Comment by trxcllnt** [comment]
@blesh sure, but can we open another issue to track creating that pre-publish step? This is something I'd like to get in relatively soon.

**Comment by blesh** [comment]
@trxcllnt, yes, we should open something if we don't have one open already.
