### ISSUE TITLE
Make AnonymousSubject public

### ISSUE THREAD

**Issue by bisubus** [ReactiveX/rxjs#2002]
This is a duplicate of closed Reactive-Extensions/RxJS#227 issue. The mentioned issue has a good point that it is a nice base class for creating subject subclasses.

In RxJS 5, `AnonymousSubject` isn't exported as `Rx.AnonymousSubject`, again.

**Comment by kwonoj** [comment]
I don't see strong reason to prevent export it in index, but in current package you can still access it such as `import {AnonymousSubject} from 'rxjs/Subject'`.

**Comment by blesh** [comment]
What's the use case for needing it externally? It's basically just `Subject.create`. The only negative I could see is if we move it to another module, it could end up creating more module code in the output bundle.

**Comment by bisubus** [comment]
Currently I'm using it like

```
class CustomSubject<T> extends AnonymousSubject<T> {

	constructor(...) {
		...
                let customSubject = new SomeSubject(...);
                let customObservable = customSubject.asObservable().do(...)...;

		super(customSubject, customObservable);
	}

	next(value: T): void {
		somePromise.then(() =>super.next(value));
	}
}
```

It does the job. There's nothing wrong with importing it from `rxjs/Subject` directly but I'm concerned about using a private class from package internals.

**Comment by blesh** [comment]
Hmmm... that's a strange use case. But I think that extending AnonymousSubject seems like a valid use case on it's own.

Seems legit.
