### ISSUE TITLE
Extra options request when using ajax

### ISSUE THREAD

**Issue by laurentdesmet** [ReactiveX/rxjs#2008]
**RxJS version:**
5.0.0-beta.12

**Code to reproduce:**

``` javascript
import { ajax } from 'rxjs/observable/dom/ajax'

ajax({
  url: 'https://jsonplaceholder.typicode.com/posts/1'
})
.subscribe(res => console.log('res', res))
```

**Expected behavior:**

1 HTTP GET call to the REST api

**Actual behavior:**

1 HTTP OPTIONS request followed by the actual GET request

**Additional information:**

This behavior can be circumvented by setting the `crossDomain` property to `true`. The actual cause of the extra OPTIONS request is because of [this line](https://github.com/ReactiveX/rxjs/blob/master/src/observable/dom/AjaxObservable.ts#L191) which adds a `X-Requested-With=XMLHttpRequest` header to the request which leads to the [preflight request](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Preflighted_requests) and apparently this is [a security measure](http://stackoverflow.com/questions/17478731/whats-the-point-of-the-x-requested-with-header). It seems pretty cumbersome that you need to opt in for cross domain calls (which requires you to add the crossDomain property to every ajax request) without preflight requests, which is the default behavior when using standard browser HTTP APIs like `fetch` and `XMLHttpRequest`.

**Comment by benlesh** [comment]
This one is really stale... closing.
