### ISSUE TITLE
'cache()' should allow subscribe after unsubscribe

### ISSUE THREAD

**Issue by newsash** [ReactiveX/rxjs#2010]
**RxJS version:** Latest
**Code to reproduce:**
``` typescript
var cached = Observable.timer(200).cache();
var subscription = cached.subscribe(v => console.log(v));
setTimeout(() => {
    subscription.unsubscribe();
    cached.subscribe(v => console.log(v));
}, 100);
```
**Expected behavior:**
"0" in console.
**Actual behavior:**
Nothing in console.
**Additional information:**
Subject should be nulled on outerSub unsubscribtion
https://github.com/ReactiveX/rxjs/blob/master/src/operator/cache.ts#L55

**Comment by blesh** [comment]
... and here's another issue that leads me to believe `cache` should be removed from v5 until we more specifically bikeshed it's behavior.

**Comment by newsash** [comment]
Oh, it's probably a dupe of #1959 
Use case from my project (`serviceCall` is angular 2 `http.post` with retry logic):
``` typescript
cache.observable = serviceCall
    .expand(() => Observable.timer(period).concatMap(() => serviceCall))
    .cache(1, period);
```

**Comment by jayphelps** [comment]
@newsash we ended up removing the `.cache()` operator [for RC1](https://github.com/ReactiveX/rxjs/blob/master/CHANGELOG.md#500-rc1-2016-10-11) because in it's current state it was too confusing and [poorly] trying to solve too many problems.
