### ISSUE TITLE
flatMap() returns Observable<any> when should have type

### ISSUE THREAD

**Issue by dcbroad3** [ReactiveX/rxjs#2014]
RxJS version:5.0.0-beta12
(Don't know if it's relevant, but Typescript 2.0.3)

Code to reproduce:
```
let a = (b: string) => { return Rx.Observable.of('test'); }
let c = (d: string) => { return Rx.Observable.of('test'); }
a('test').flatMap(c).subscribe(e => e);
```

Expected behavior:
Typescript should interpret 'e' as 'string.' 

Actual behavior:
Typescript interprets 'e' as 'any.' 

Additional information:
Playing around a bit, if I declare c as:
`let c = (d: string): Subscribable<string> => { return Rx.Observable.of('test'); }`
Then Typescript interprets 'e' correctly as a string. Also, if I go into Observable.d.ts and change line 11:
`export declare type ObservableInput<T> = SubscribableOrPromise<T> | ArrayLike<T>;`
To:
`export declare type ObservableInput<T> = Subscribable<T> | ArrayLike<T>;`
Then Typescript also interprets 'e' correctly as a string. I don't know enough to figure out why, but it seems like the inclusion of Promise<T> causes a problem here.

**Comment by david-driscoll** [comment]
This is related to #1937 which I don't believe has been released yet.  Once it's released you should see typings flowing nicely again.

If you want to try the change locally, you can find it here.  It's just the line above where you made the change. 😄 
https://github.com/ReactiveX/rxjs/commit/36c7676492daa733603652a1c22363ecf10431dd

**Comment by blesh** [comment]
@dcbroad3, can you confirm that the changes currently in master resolve your issue? Perhaps try npm install from master?

**Comment by dcbroad3** [comment]
Just checked - works as expected from master. Thanks, and will keep an eye out for the next release.

**Comment by blesh** [comment]
Cool. I'm going to close this issue then, thanks @dcbroad3
