### ISSUE TITLE
Include es6 type definition via TypeScript compiler or 3rd party module

### ISSUE THREAD

**Issue by kwonoj** [ReactiveX/rxjs#2016]
**RxJS version:**
.Beta.12

**Additional information:**
related to https://github.com/ReactiveX/rxjs/issues/2011#issuecomment-252418870

Lot of confusion from TypeScript user is RxJS rely on some of 3rd party type definition to support ES2015 signatures and they have to install it by themselves. From TS@2.0, there's newly introduced mechanism to supply 3rd party type definition by installing published npm packages, like `es6-shim`(https://www.npmjs.com/package/@types/es6-shim) . 

RxJS can specify them as dependency to remove those issues completely, or set loosely as peerDependency to consumer knows it's requires, feel freely choose between @types package or their own (i.e, typings).

I believe `redux-observable` is aim for similar, /cc @jayphelps as well for opinions.

**Comment by jayphelps** [comment]
I was playing with the new @types and man this is such a confusing situation DefinitelyTyped vs typings vs types vs lib provides it already.

Can you share what changes you're recommending specifically? e.g. the package.json changes?

**Comment by kwonoj** [comment]
I also tried this bit yesterday and found it's bit confusing to me as well, since it isn't super clear origin of @types package comes in, and possible conflict based on user configuration, etcs.

I don't have concrete configurations at this moment - but current suggestion is set as peerDependency to not cause trouble to existing configs but let user know they need to supply 3rd party type definition. Consumer can freely choose to supply it via installing peerDependency, or use their own existing config like `typings`. (Note: this only applies npm@3 and above which doesn't install peerDependency explicitly)

**Comment by kwonoj** [comment]
in short, proposal will looks like

```js
"peerDependencies": {
    "@types/es6-shim": "version we want"
}
```

**Comment by david-driscoll** [comment]
Do we need third part shims to be a part of the library itself?  With Ts2.0 we can simply set the `lib` appropriately, and then anyone consuming downstream just has to have the same or similar lib items.

**Comment by kwonoj** [comment]
@david-driscoll you're referring https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#including-built-in-type-declarations-with---lib , is that correct? Yes, this seems neat and more feasible (if it works as expected)

**Comment by kwonoj** [comment]
Changed subj.

**Comment by david-driscoll** [comment]
@kwonoj yeah, the new lib part of `tsconfig.json` allows greater control.  We can just build with as few primitives as necessary.  And this should also allow us to bring back `Iterable<T>` and `Iterator<T>`.

**Comment by kwonoj** [comment]
That makes much more sense than original proposal. Let's evaluate those.
