### ISSUE TITLE
property names and collisions

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#203]
While trying to add the `window` operator `windowTime`, I ran into a name collision with `windowTime` on `ReplaySubject`... which isn't a big deal, I privatized and renamed the one on `ReplaySubject` to `_windowTime`. It did strike me, though, that we might want to look into renaming everything that is a privatized property to be prefixed with an underscore to prevent those sorts of collisions. Particularly anything on the `Observable` types.

**Comment by jeremymwells** [comment]
I agree. It's a simple thing and it favors style.

**Comment by blesh** [comment]
Closing this for now. It's not really a priority.
