### ISSUE TITLE
RC1 compile errors with Typescript 2.0.3

### ISSUE THREAD

**Issue by Skuriles** [ReactiveX/rxjs#2032]
**RxJS version:**
Rxjs V5 - RC1

**Code to reproduce:**
`import` { Observable }   from 'rxjs/Observable';

**Expected behavior:**
compile without error

**Actual behavior:**
following error will be thrown (error occurs in each operator, but to show this example uses only observable operator)

`D:/proj/AcoemTestServer/Minitestserver/TestClient/node_modules/rxjs/operator/catch.d.ts(12,38): error TS1138: Parameter declaration expected.
D:/proj/AcoemTestServer/Minitestserver/TestClient/node_modules/rxjs/operator/catch.d.ts(12,42): error TS1005: ';' expected.
D:/proj/AcoemTestServer/Minitestserver/TestClient/node_modules/rxjs/operator/catch.d.ts(12,57): error TS1109: Expression expected.
D:/proj/AcoemTestServer/Minitestserver/TestClient/node_modules/rxjs/operator/catch.d.ts(12,67): error TS1005: ';' expected.
D:/proj/AcoemTestServer/Minitestserver/TestClient/node_modules/rxjs/operator/catch.d.ts(12,124): error TS1005: '(' expected.
D:/proj/AcoemTestServer/Minitestserver/TestClient/node_modules/rxjs/operator/catch.d.ts(12,125): error TS1005: ';' expected.
D:/proj/AcoemTestServer/Minitestserver/TestClient/node_modules/rxjs/operator/catch.d.ts(12,140): error TS1005: '(' expected.
D:/proj/AcoemTestServer/Minitestserver/TestClient/node_modules/rxjs/operator/debounceTime.d.ts(49,41): error TS1138: Parameter declaration expected.
D:/proj/AcoemTestServer/Minitestserver/TestClient/node_modules/rxjs/operator/debounceTime.d.ts(49,45): error TS1005: ';' expected.
D:/proj/AcoemTestServer/Minitestserver/TestClient/node_modules/rxjs/operator/debounceTime.d.ts(49,60): error TS1109: Expression expected.
D:/proj/AcoemTestServer/Minitestserver/TestClient/node_modules/rxjs/operator/debounceTime.d.ts(49,69): error TS1005: ';' expected.
D:/proj/AcoemTestServer/Minitestserver/TestClient/node_modules/rxjs/operator/debounceTime.d.ts(49,89): error TS1109: Expression expected.
........
`

**Additional information:**
Using gulp-typescript to compile, Typescript version is 2.0.3, Angular 2.1.

If I use V5_beta12 all is working fine!

tsconfig.json
`{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false
  }
}`

**Comment by david-driscoll** [comment]
Are you absolutely sure the version of TypeScript picked up by `gulp-typescript` is TS 2.0?   I can replicate that behavior if I return to TS 1.8.10, but no issues with TypeScript 2.0.3

As I recall if you needed to use a different version of TypeScript with `gulp-typescript` you had to pass it to your project.

I would verify that it is indeed a TS 2.0 issue by installing `tsc` globally (`npm install -g typescript@2.0.3`) and run `tsc` from the folder that contains your `tsconfig.json`.

If it still fails to compile when using just `tsc` then it may definitely be something we'll have to address ASAP.

**Comment by Skuriles** [comment]
Thank you for the hint.
It was not a rxjs issue but a gulp-typescript one. Updated it to version 3 which is the official version for typescript 2. NPM don't auto update  from V2 to V3 automatically. After that done all works fine without any errors.
