### ISSUE TITLE
How to get the stacktrace of an error when using rxjs?

### ISSUE THREAD

**Issue by stavalfi** [ReactiveX/rxjs#2040]
I'm using angular-cli to build a small angular2 web app and I'm debugging with chrome dev-tools.

Clearly I'm doing something wrong if I need to guess each time where is the source of the error and what is the stack-trace of that error.

 I dont know where is the appropriate place to ask that so I wrote a details question in [stackoverflow](https://stackoverflow.com/questions/40064857/how-to-get-the-stacktrace-of-an-error-when-using-rxjs) also.

Please consider responding here or there. I'm losing my mind on how to find the source of simple errors.

Thanks everyone!

**Comment by jayphelps** [comment]
Discussion continued on StackOverflow.
