### ISSUE TITLE
Thoughts on the current scheduler implementation...

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#205]
I was talking with @abersnaze here at Netflix about `observeOn` `materialize` and `notifications` and I'm wondering if our current implementation has missed the mark to some degree?

Just spitballing.. but would it be better to put a bunch of `Notifications` in a ring-buffer and schedule those when dealing with the `nextTick` scheduler? Would it be better to have the scheduling interface be less generic and more specialized to Rx needs?  For example: `scheduler.schedule(delay, notification, subscriberToNotify)`? 

It seems like if the scheduler had access to the subscriber to notify and the notification, it would be able to add and remove it's subscription from the subscriber's subscription collection, and maybe that would help us to some degree? It's a common task in this library to schedule something, get the action back, then set that action up to be unsubscribed when appropriate.

I guess I'm proposing that rather than doing this in our subscribers:

```TypeScript
_next(value) {
  this.add(scheduler.schedule(delay, { subscriber: this, value }, SomeSubscriber.dispatchNext));
}

static dispatchNext({ subscriber, value }) {
   subscriber.next(value);
   //TODO: something here to unbloat the underlying composite subscription
}
```

we could do something more like this and the scheduling itself could manage everything involving it's unsubscription and completion:

```TypeScript
_next(value) {
  this.scheduler.schedule(delay, { kind: 'N', value: value }, this);
}
```

Thoughts @trxcllnt?

**Comment by blesh** [comment]
I guess the question is: Are we ever scheduling things *other* than notifications?

**Comment by blesh** [comment]
Now I know I'm talking to myself here... but to answer my own question: 

> Are we ever scheduling things other than notifications?

Yes, me, we are... We schedule when to start windowing or buffering which are not notifications, necessarily.

**Comment by blesh** [comment]
I'm going to close this one for right now... I think what we're doing is fine the more I think about it. I just wanted to put my thoughts out here on Github.

**Comment by trxcllnt** [comment]
@blesh it may behoove us to consolidate common scheduling patterns into scheduler methods so we don't have so much duplicated code, but it'd (somewhat) defeat the modularity goal, as you'd potentially be using a larger scheduler than you may need. Let's put it on the back-burner and revisit when we're looking for common operations to factor out.

**Comment by blesh** [comment]
@trxcllnt sounds fair.

On a related note: At the very least, we should probably be reusing the `Notification` type in `observeOn`.
