### ISSUE TITLE
MIGRATION.md and RxJS API

### ISSUE THREAD

**Issue by Pappa** [ReactiveX/rxjs#2057]
I recently opened a [pull request](https://github.com/ReactiveX/rxjs/pull/2051) for the `some` operator and was confronted with a discussion about whether the operator should be included. As a new contributor, hoping to give some time to the project, I find the guidance on operator inclusion confusing. 

The [MIGRATION.md](https://github.com/ReactiveX/rxjs/blob/master/MIGRATION.md) document states that there are many operator that are "Not yet implemented", suggesting that the project would like contributors to implement them. I haven't found any kind of discussion on what should/shouldn't be included in the API. I don't know if this discussion has happened, but not been published anywhere easily accessible, or only occurs in pull request discussions.

I'd like to contribute more to RxJS development, but I think there needs to be more clarity on what contributions are needed/wanted for the API. Currently that's really not obvious from the documentation available.

**Comment by kwonoj** [comment]
Yes, it is bit unclear in those document. Primary reason for those is discussion for finalizing api surface for v5 has just started recently, and for each individual operator it need to be discussed per each use cases. Sometimes it seems not needed operator but there is possible usecase couldn't think of, and sometimes proposal for operator can be achieved easily with current operators.

General goal for v5 is settle down api surface and do not extend more unless there is significant usecases, and discuss over next release after make v5 public release out of beta. There will be periodic discussion and meeting notes will be published as well clears several topics regarding several topics.

It is great appreciate for existing PR's effort and further effort for contribution. If something's unclear in current documentation and need clarification, feel freely open issue anytime first. Then you can bring it as following PR by its conclusion.

**Comment by jayphelps** [comment]
@Pappa agreed! We're all learning and improving this process as we go, please forgive our lack of transparency but do continue to hold us accountable.

I'd echo what @kwonoj said as well.

**Comment by Pappa** [comment]
Thanks for the feedback.

**Comment by kwonoj** [comment]
@Pappa , I hope question is answered, let me close issue for now. Please feel freely reopen if there's remaining issue.

**Comment by jayphelps** [comment]
I wanna keep this open for my reference to make the MIGRATION doc more clear in many ways.

**Comment by benlesh** [comment]
Closing as stale.
