### ISSUE TITLE
Issue with bufferCount?

### ISSUE THREAD

**Issue by poyannabati** [ReactiveX/rxjs#2062]
**RxJS version:**
5.0.0.rc-1

**Code to reproduce:**
http://codepen.io/nabati/pen/kkVLwr

**Expected behavior:**
When clicking three times in the document, expecting PING PING PING, PING PING PONG. 

**Actual behavior:**
Getting PING PING PING, PING PONG PING. 

**Additional information:**
Seems like adding a delay(0) before the last map solves the issue, as such 
```
// ...
	.delay(0)
	.map(action => store$.next(action));
```

**Comment by jayphelps** [comment]
v4 vs v5 demo http://jsbin.com/nedosim/edit?js,output
