### ISSUE TITLE
document links broken

### ISSUE THREAD

**Issue by kushwahashiv** [ReactiveX/rxjs#2063]
**RxJS version:**

**Code to reproduce:**

**Expected behavior:**

**Actual behavior:**

**Additional information:**

**Comment by kwonoj** [comment]
Would you mind to share details which links are not working? Just in case if you're referring under `doc`, it is intended to generate document for http://reactivex.io/rxjs/ and its link won't work in this repo.

**Comment by kushwahashiv** [comment]
@kwonoj yes I was referring to [https://github.com/ReactiveX/rxjs/blob/master/doc/operators.md](https://github.com/ReactiveX/rxjs/blob/master/doc/operators.md) operator links

**Comment by kwonoj** [comment]
As noted in https://github.com/ReactiveX/rxjs/tree/master/doc#rxjs-official-docs-at-httpreactivexiorxjs, those documentations are source of documentation for reactivex.io/rxjs and not intended to be read directly inside of repo. So it is expected to broken in repo state.
