### ISSUE TITLE
distinct improvements

### ISSUE THREAD

**Issue by blesh** [ReactiveX/rxjs#2065]
After working on #2049, I think there is a lot of room to improve the `distinct` operator, as a whole. There are a few paths to choose from:

### Problem Areas

1. Memory leaks with long-lived uses of `distinct`. Basically, if you have a situation where an observable with `.distinct()` on it has been running for a very long time, it's going to save each of those values in memory.
2. Perf on machines that don't support `Set`.
3. `distinct` can't really support any sort of use-case like "distinct in the last 3 minutes" currently

### ~~Proposed Solution~~

1. ~~Use a `WeakMap` instead of a `Set`. If it's a `WeakMap` the `value` from the `key/value` pair could be meta data the users defines.~~
2. ~~The user could have access to the `value` and the `WeakMap` or `Set` in an argument that is a comparer function that is made to check the `value` against what's in the `WeakMap` or `Set`. This comparer function could be used to clear the `WeakMap` or `Set` as well as evict values based off of meta data stored (if we're using a `WeakMap`). ~~

**~~Basic Usage~~**
```js
// EDIT: REMOVED ... bad idea
```
### ~~Risks~~

1. ~~`WeakMap` is a pain to polyfill in a foolproof way.~~
2. ~~The `distinct` API becomes less straight forward for more advanced use-cases.~~
3. ~~It's a breaking change. (This isn't something I think we need to land in 5.0, but it's something to be aware of)~~

# EDIT: Removed bad proposal

**Comment by jayphelps** [comment]
Also extremely important to remember that WeakMap keys can only be objects, no primitives like numbers, strings, etc. this would limit the things the operator would work on. This may be a non-starter cause having an operator that only works with certain values is pretty odd.

**Comment by blesh** [comment]
> Also extremely important to remember that WeakMap keys can only be objects, no primitives like numbers, strings, etc. this would limit the things the operator would work on. This may be a non-starter

Yup, it's a non-starter. I had forgotten that important bit. :\

**Comment by blesh** [comment]
Now that I think about it, it seems this could be solved trivially with `let` and `scan`, which gives you total control over how your dealing with distinct values, whether you want to use WeakMap or not, etc.

```js
source.let(source => {
  return new Observable(observer => {
    return source.scan((state, value) => {
      state.forEach((key, value) => { 
        if (value < Date.now() - 180000) {
          state.remove(key);
        }
      });
      if (!state.has(value)) {
        state.add(value, Date.now());
        observer.next(value);
      }
    }, new WeakMap())
    .subscribe();
  });
});
```

It's not ergonomic for new Rx users, but it should work.

**Comment by jayphelps** [comment]
We could let users override some of the default implementation of `distinct` so that it's easy to use `WeakMap` for situations where it makes sense (e.g. values are objects, not primitives). I can definitely see myself using that ability at some point, especially because of how attractive the garbage collection benefits of it are.
