### ISSUE TITLE
feat(TypeScript): enable 'strictNullChecks' option

### ISSUE THREAD

**Issue by saneyuki** [ReactiveX/rxjs#2066]
## Pros
- This would make our code base more solidly, more clearly to decrease a bug. 
- This option enables full control-flow basis analysis of tsc.
  - This option is introduced from tsc 2.0.
## Cons
- We may need change a public signatures as breaking change.

cc: @david-driscoll @kwonoj

**Comment by jayphelps** [comment]
I'm absolutely for this in theory--huge advocate for non-nullable types. I'm mostly worried about consumers of RxJS who _don't_ have `strictNullChecks` enabled. Presumably they will still be able to pass `null` against our TS definitions right? i.e. this is mostly for our internal sake?

Off hand I can't think of any signatures we would _want_ to accept `null` as valid. We sometimes call having no scheduler the "null scheduler" but this is really a misnomer IMO and I'd like to stop doing that. Can anyone think of any?

**Comment by kwonoj** [comment]
> Presumably they will still be able to pass null against our TS definitions right? i.e. this is mostly for our internal sake?

: I expect same behavior. this option's affecting compile time behavior, I don't think it can control consumer's compile time options.

> Off hand I can't think of any signatures we would want to accept null as valid. 

: Maybe someone might use `null` where `undefined` as valid value as well?

**Comment by saneyuki** [comment]
@jayphelps 

> I'm absolutely for this in theory--huge advocate for non-nullable types. I'm mostly worried about consumers of RxJS who don't have strictNullChecks enabled. Presumably they will still be able to pass null against our TS definitions right? i.e. this is mostly for our internal sake?

- Yes. I think this would be a internal sake basically if we don't change public interface signatures.
- After we enables `strictNullChecks`, it would be a problem if the consumer of RxJS compiles their codes & rxjs's raw TypeScript code without `strictNullChecks`.
  - But I think this is very very rare case. Almost (maybe ~99.9%) consumers uses only rxjs via npm with bundled d.ts.

**Comment by saneyuki** [comment]
In the following case, 

- It would not be a compile error if the consumer _disable_ `strictNullChecks`.
- It would be a compile error if the consumer _enable_ `strictNullChecks`.

Thus I think that there would not be a problem if we don't change public interface.

```ts
// bar.d.ts
export function bar(a: number): void;
```

```ts
// consumer's code
import {bar} from 'bar';

bar(1);
bar(null); // compile error with `strictNullChecks`
bar(undefined); // compile error with `strictNullChecks`
```

**Comment by benlesh** [comment]
I think we're currently happy with the TS settings. 

Anyway this issue is stale.
