### ISSUE TITLE
RFC: Should make Observable's constructor private?

### ISSUE THREAD

**Issue by saneyuki** [ReactiveX/rxjs#2073]
## Motivation

- This intent to make `Observable` and drived types constructors non-public.
- This change will sort to use only factory methods for our user.

## Detailed Design

From TypeScript 2.0, we can use [private/protected constructor for a class](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#private-and-protected-constructors).

## Compatibility Risk

- This will be breaking change definitely.
  - At least, even if we accept this change, we must land this change to post-v5 major release line.

**Comment by jayphelps** [comment]
So this would prevent `new Observable(subscribe)` but not `Observable.create(subscribe)`? I may be alone on this, but I actually prefer `new Observable(observer => {})` these days because I've found it gives people the "a ha!" moment sooner because it's more similar to `new Promise((resolve, reject) => {})` but obviously this is fairly minor difference.

**Comment by kwonoj** [comment]
Question in here is as @jayphelps said does `Observable` expected to not expose instantiation except factory. I think it's ok, but also brings some alignment question not only compare to `promise`, but internal implementation like `Subject`. General pattern to create instance of subject is `new Subject()`, and by this `new Observable()` is prohibited.

**Comment by blesh** [comment]
Unfortunately, we cannot do this. One of the goals of this library is to match the [Observable proposal](https://github.com/tc39/proposal-observable) as closely as we reasonably can, and the proposal defines a constructor.

I understand the spirit, _entirely_. But I'm going to close this as it simply defies one of the core goals of RxJS 5.
