### ISSUE TITLE
Compile errors when using TypeScript 1.x

### ISSUE THREAD

**Issue by OliverJAsh** [ReactiveX/rxjs#2074]
TS version 1.8.7

``` ts
Observable.of(1,2).scan((acc, items) => { acc.push(items); return acc; }, [])
// Supplied parameters do not match any signature of call target.
```

Seems to work fine in TS 2

**Comment by kwonoj** [comment]
Yes, from rc.1 (https://github.com/ReactiveX/rxjs/blob/master/CHANGELOG.md#breaking-changes) minimum compiler requirement is TS@2.0.
