### ISSUE TITLE
Rx has no default export 

### ISSUE THREAD

**Issue by web265p3** [ReactiveX/rxjs#2085]
I just followed the easy steps to install the package. When I type "npm install rxjs" nothing is created, so I created my own package.json file like the following:

```
{
  "name": "@reactivex/rxjs",
  "version": "5.0.0-rc.1",
  "description": "Reactive Extensions for modern JavaScript",
  "main": "index.js"
}
```

After running "npm install rxjs" again I get the node_modules folder with everything inside. But when I want to import "import Rx from 'rxjs/Rx';" I get the error message, that Rx has no default export. 
Actually there is not a lot to do wrong here, but I'm stuck. Any proposals?

**Comment by jayphelps** [comment]
Bare with me please, I'm having troubling understanding. Can you elaborate? Running `npm install rxjs` in a directory that contains a valid `package.json` for an app seems to work fine. Where I get pretty confused is

> so I created my own package.json file like the following

Why did you need to create a package.json with the name `@reactivex/rxjs`? Your `package.json` should be _your_ app's, not RxJS's.

> I get the error message, that Rx has no default export. 

What is the actual error message and what tool is emitting it? node? TypeScript? webpack? Can you provide details on what build environment you're using?

While I don't mean to be entirely dismissive, it's _extremely_ likely this isn't an issue with RxJS because we'd be getting our doors knocked down with people running into this. 😄 So keep that in mind when we're searching for the cause.

**Comment by jayphelps** [comment]
There is differing implementations on how ES6 default exports are determined when dealing with source which uses CommonJS modules.

You probably want:

```js
import * as Rx from 'rxjs';

// or things like

import { Observable } from 'rxjs';
```

**Comment by web265p3** [comment]
Thanks for your reply. I am using Visual Studio Code - sorry, I forgot this. In the first place I thought, that the package.json shouldn't even be necessary to exist in an empty directory where I want to download rx/js. But whenever I try to "npm install rxjs" nothing is downloaded, so I created my own package.json (this might have been the wrong approach, but I do not know npm very well)

import * as Rx from 'rxjs';

Works fine for me! But then I would have to import anything...

**Comment by kwonoj** [comment]
Would you mind share bit more detail? are you referring to import necessary operator such as

```js
import { Observable } from 'rxjs/Observable';
import 'rxjs/add/operator/map';

Observable.of(1,2,3).map(x => x + '!!!'); // etc
```

at https://github.com/ReactiveX/rxjs#es6-via-npm ?

**Comment by web265p3** [comment]
I just tried whats in the tutorial:

To import the entire core set of functionality:

```
import Rx from 'rxjs/Rx';

Rx.Observable.of(1,2,3)
```

Here "Rx" is not the default export

**Comment by kwonoj** [comment]
Sorry, so you're saying `import * as Rx from` works and `import Rx` doesn't work?

**Comment by jayphelps** [comment]
@web265p3 What is the actual error message and what tool is emitting it? node? TypeScript? webpack? Can you provide details on what build environment you're using?

**Comment by web265p3** [comment]
I am using Visual Studio code and installed TypeScript. What kwonoj is saying is right. Exactly that happens.

**Comment by kwonoj** [comment]
@web265p3 , I'd like to provide additional details as much I can but I'm pretty much out of idea as @jayphelps does. Currently there is barely no information we can guess about your project setup. If you have minimum repo can reproduce current behavior, it'd appreciate to share it to able to try. Each transpiler / bundler setup might have different configurations.

**Comment by ds82** [comment]
Let me help a bit (because I just had the same issue and this thread helped me):

```
mkdir rxjs-typescript-test; cd rxjs-typescript-test
npm i typescript rxjs@5.0.0-rc.1
./node_modules/.bin/tsc --init
echo "import Rx from 'rxjs/Rx';" > index.ts // <-- this line is from your README and @web265p3 refers to it
./node_modules/.bin/tsc index.ts
```

That emits this error:

```
index.ts(1,8): error TS1192: Module '"/Users/dsaenger/code/rxjs-typescript-test/node_modules/rxjs/Rx"' has no default export.
```

Changing ``import Rx from 'rxjs/Rx';`` to ``import * as Rx from 'rxjs/Rx';`` fixes it.

**Comment by web265p3** [comment]
That is enough for me actually ;)

**Comment by taji** [comment]
@ds82, this worked for me with typescript 2, node js (4.3.2), rxjs 5.0.3 and typings es6shim installed as per the docs.   Thanks!

**Comment by Neutrino-Sunset** [comment]
Fyi, 1 year later, your documentation is still wrong.

http://reactivex.io/rxjs/manual/installation.html

**Comment by jayphelps** [comment]
@Neutrino-Sunset hey, thanks for he heads up. Could you send a PR that corrects it appropriately?

**Comment by thor-the-norseman** [comment]
@jayphelps Nope, he couldn't. And neither can I. But fix it, please?
