### ISSUE TITLE
fromEventPattern throwing exceptions for removeHandler 

### ISSUE THREAD

**Issue by omerts** [ReactiveX/rxjs#2086]
**RxJS version:** 5.0.0-beta.11

**Code to reproduce:** https://jsfiddle.net/omerts/7d3znmmq/

**Expected behavior:** According to (older) docs, removeHandler parameter is optional, and should not throw exceptions if not provided.

**Actual behavior:** "TypeError: removeHandler is not a function"

**Additional information:** In the fiddle, click the button twice.

**Comment by kwonoj** [comment]
In latest package removehandler is not optional, if docunent is outdated it may need to be updated. Would you mind share which document youvre referring?

**Comment by kwonoj** [comment]
In latest package removehandler is not optional, if docunent is outdated it may need to be updated. Would you mind share which document you're referring?

**Comment by omerts** [comment]
The only normal reference I found is this: https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/fromeventpattern.md

**Comment by kwonoj** [comment]
Yes, that document refers v4 and there are breaking changes. Current latest document is hosted at http://reactivex.io/rxjs/
