### ISSUE TITLE
defaultIfEmpty doesn't work for subjects

### ISSUE THREAD

**Issue by bisubus** [ReactiveX/rxjs#2087]
**RxJS version:**

5.0.0-rc.1

**Code to reproduce:**

[A plunk](http://plnkr.co/edit/4BHrJZ6mQMCxGS7VCEDP):

```
var emptyObservable = Rx.Observable.empty();
var emptySubject = new Rx.Subject();
var emptySubjectObservable = emptySubject.asObservable();

emptyObservable
.defaultIfEmpty()
.subscribe(() => console.log('empty observable'));

emptySubject
.defaultIfEmpty()
.subscribe(() => console.log('empty subject'));

emptySubjectObservable
.defaultIfEmpty()
.subscribe(() => console.log('empty subject observable'));
```

**Expected behavior:**

`defaultIfEmpty` is supposed to work for any empty observables and output:

> empty observable
> empty subject
> empty subject observable

**Actual behavior:**

`defaultIfEmpty` works only for observables created with `Observable.empty()` and outputs:

> empty observable

**Comment by trxcllnt** [comment]
The Subject you've created isn't empty, it's infinite. add `emptySubject.complete()` at the bottom of your test case to terminate the Subject.

**Comment by bisubus** [comment]
@trxcllnt Thanks, that's my mistake, the manual clearly says that `defaultIfEmpty` is for completed observables. I presume that there's no way to figure out if incomplete observable is empty (has no values to subscribe) at this moment, is it?

**Comment by mattpodwysocki** [comment]
@bisubus currently the only thing that `isEmpty` or any of those other operators can function is if it has some completion semantics, else it's the same as `Observable.never()` which is an infinite sequence of nothing.

**Comment by jayphelps** [comment]
Let us know if you need further clarification.
