### ISSUE TITLE
Private properties defined in an external npm package interrupt variable assignment

### ISSUE THREAD

**Issue by jeffwhelpley** [ReactiveX/rxjs#2092]
**RxJS version:** 5.0.0-beta.12

**Code to reproduce:**

```
// in one npm module A
export class HttpAdapter {
    request(url: string, options?: HttpRequestOptionsArgs): Observable<HttpResponse> {
        return Observable.of({});
    }
}

// in completely separate npm module B that references module A
// issue occurs when you do npm link from module B to A 
export class HttpRequestAdapter implements HttpAdapter {
    request(url: string, options?: HttpRequestOptionsArgs): Observable<HttpResponse> {
        return Observable.of({});
    }
}
```

**Expected behavior:** No Errors

**Actual behavior:**

```
Error:(10, 14) TS2420:Class 'HttpRequestAdapter' incorrectly implements interface 'HttpAdapter'.
  Types of property 'request' are incompatible.
    Type '(url: string, options?: HttpRequestOptionsArgs) => Observable<HttpResponse>' is not assignable to type '(url: string, options?: HttpRequestOptionsArgs) => Observable<HttpResponse>'.
      Type 'Observable<HttpResponse>' is not assignable to type 'Observable<HttpResponse>'.
        Property 'source' is protected but type 'Observable<T>' is not a class derived from 'Observable<T>'.
```

**Additional information:**

According to [this open TypeScript issue](https://github.com/Microsoft/TypeScript/issues/6496#issuecomment-256828753) this problem appears because of private variables within the Observable type. Technically this should be a bug that is fixed within TypeScript, but it would be extremely helpful if in the meantime we could make the Observable properties public so that npm linking works as expected. It seems like this is something that may not be resolved in the TypeScript lib for some time.

**Comment by kwonoj** [comment]
Is this same issues with https://github.com/ReactiveX/rxjs/issues/1744 and https://github.com/ReactiveX/rxjs/issues/1858 ?

**Comment by blesh** [comment]
>  Technically this should be a bug that is fixed within TypeScript, but it would be extremely helpful if in the meantime we could make the Observable properties public so that npm linking works as expected.

I feel like there will be other problems if we make properties that should be private public.

**Comment by jeffwhelpley** [comment]
@blesh yeah, no worries if you feel that is going to adversely affect the project. I will just close this and focus on seeing how to get it resolved in TypeScript core. I just opened in case you didn't care one way or another about the private/public designation.
