### ISSUE TITLE
JSONP Requests

### ISSUE THREAD

**Issue by dawidvdh** [ReactiveX/rxjs#2095]
**RxJS version:**
5.0.0-rc.1
**Code to reproduce:**

``` javascript
Observable.ajax({ url:`https://api.behance.net/v2/fields?client_id=h43jKXcM5DA1ivEbnXvMUVp8cnjGdBRE`, crossDomain: true })
  .catch(err => console.log('Observable.ajax error crossDomain', err))
  .subscribe(res => console.log('Observable.ajax crossDomain', res))
```

**Expected behavior:**
for it to log out a response from the ajax request.
**Actual behavior:**
returns this error: No 'Access-Control-Allow-Origin' header is present on the requested resource.
**Additional information:**
Behance API requires JSONP requests.

**CODEPEN DEMO:** http://codepen.io/dawidvdh/pen/xEoREB?editors=0012

_also I am aware that I shouldn't share the `client_id` but I will delete the associated app after the bug has been resolved_

**Comment by jayphelps** [comment]
`Observable.ajax` is for making XMLHttpRequests, which _are not JSONP requests_. XMLHttpRequests _always_ require CORS headers for cross origin.

[JSONP](https://en.wikipedia.org/wiki/JSONP) uses `<script>` tags to get around this:

```js
var tag = document.createElement('script');
tag.src = 'some-api?callback=foo';

document.getElementsByTagName('head')[0].appendChild(tag);
```

The URL you are trying to hit doesn't actually return JSONP formatted results either--and you're also not providing a callback function to it, even if it did. I don't know that API service, but a quick Google search suggests they support JSONP but [you must opt-in to it](https://www.behance.net/dev/api/endpoints/).

```js

window.myCallbackFunction = function (response) {
  console.log(response);
};

var tag = document.createElement('script");
tag.src = 'http://behance.net/v2/users/matiascorea?api_key=1234567890&callback=myCallbackFunction';

document.getElementsByTagName('head')[0].appendChild(tag);
```

We don't have any plans to support JSONP, since it was primarily a short-trick before browsers had CORS support.

If you'd like further help with JSONP, you'll get the best results on [StackOverflow](stackoverflow.com). Thanks!

**Comment by jayphelps** [comment]
@dawidvdh here's a custom observable that has basic JSONP support you can use as a reference: http://jsbin.com/yuhugew/edit?js,output

```js
const jsonp = (url, callbackKey) => new Observable(observer => {
  jsonp.counter++;
  const key = '__jsonp_callback' + jsonp.counter;
  window[key] = (response) => {
    script.parentNode.removeChild(script);
    observer.next(response);
    observer.complete();
  };

  const script = document.createElement('script');
  script.src = url + key;
  script.onerror = (err) => observer.error(err);

  document.getElementsByTagName('head')[0].appendChild(script);
});
jsonp.counter = 0;

jsonp('https://api.behance.net/v2/fields?client_id=h43jKXcM5DA1ivEbnXvMUVp8cnjGdBRE&callback=')
  .subscribe(
    value => console.log(value),
    err => console.error(err)
  );
```

**Comment by dawidvdh** [comment]
@jayphelps Thank you for the run down a rather silly question in retrospect but I just figured that you would eventually add in JSONP support much like [RXJS-DOM](https://github.com/Reactive-Extensions/RxJS-DOM/blob/master/doc/operators/jsonprequest.md) did, but totally get it and I have made alternative plans by using `Observable.from` to handle the API requests.

```javascript
import fetchJsonp from 'fetch-jsonp';

const fetchFields = () => fetchJsonp(`https://api.behance.net/v2/fields?client_id=h43jKXcM5DA1ivEbnXvMUVp8cnjGdBRE&callback=JSONPCallback`)
  .then(response => response.json());

export function fetchCreativeFieldsEpic(action$) {
  return action$.ofType(FETCH_CREATIVE_FIELDS)
  .switchMap(() =>
    Observable.from(fetchFields)
    .map(receiveCreativeFields)
    .takeUntil(action$.ofType(FETCH_CREATIVE_FIELDS))
    .catch(error => Observable.of({
        type: FETCH_CREATIVE_FIELDS_FAILED,
        payload: error,
        error: true
      })
    ));
}

```

But will definitely look into the above example you posted. Greatly Appreciated Thank you!
