### ISSUE TITLE
docs typo

### ISSUE THREAD

**Issue by degroote22** [ReactiveX/rxjs#2097]
at http://reactivex.io/rxjs/manual/overview.html#what-are-operators-

second paragraph: 
An Operator is a function **take** creates a new Observable based on the current Observable. This is a pure operation: the previous Observable stays unmodified.

**Comment by kwonoj** [comment]
I think it's updated in https://github.com/ReactiveX/rxjs/pull/1898, but new document is not published yet. (it'll be soon).

**Comment by kwonoj** [comment]
I believe newly published documentation now reflect this (http://reactivex.io/rxjs/manual/overview.html#what-are-operators-), closing issue.
