### ISSUE TITLE
first() produce a lot more than 1 data in some recursive situation.

### ISSUE THREAD

**Issue by futurizing** [ReactiveX/rxjs#2098]
It is pretty hard to describe in text. The code below might be more understandable.

I have a `Subject` that is connected with `first()` and subscribed with a observer that will fire a data synchronously to the same `Subject` with `next()`. It turns out that the observer receives a lot of data even though it is chained with `first()`.

I found this bug in more personal complicated code, but below is a simplified repro one. Also, I'm not sure if this is expected behavior or not.

**RxJS version:**
5.0.0-beta.12

**Code to reproduce:**
```js
const valueSubject = new Subject();
const result = [];

valueSubject.first().subscribe(val => {
    result.push(val);
    valueSubject.next(false);
});

valueSubject.next(true);

// Expect result.length to be 1.
```

**Expected behavior:**
Data should be received once.

**Actual behavior:**
Large amount of data fired to observer. Sometimes, the Error `Maximum call stack size exceeded` shows up.

**Additional information:**
When data is pushed asynchronously, the test will pass. Here is the asynchronous test in Jasmine:
```js
it('should behave correctly', (done) => {
    const valueSubject = new Subject<boolean>();
    const result: boolean[] = [];

    valueSubject.first().subscribe(val => {
        result.push(val);
        setTimeout(() => valueSubject.next(false), 0);
    });

    valueSubject.next(true);

    setTimeout(() => {
        expect(result.length).toBe(1);
        done();
    }, 100);
});
```

In this case, the test passes.

**Comment by kwonoj** [comment]
I think this is similar case to https://github.com/ReactiveX/rxjs/issues/1759#issuecomment-227575178 to try synchronous reentrant causes those behavior. As your last snippet does, if you explicitly make it asynchronous to trap out from synchronous boundary it'll work, as similar `observeOn` or other different scheduling approach does.

/cc @trxcllnt to confirm in case if I understood this incorrectly and this is unexpected behavior.

**Comment by trxcllnt** [comment]
Yes we should likely guard after the first emission, similar in spirit to https://github.com/ReactiveX/rxjs/pull/1967

**Comment by blesh** [comment]
I'll have a look
