### ISSUE TITLE
TypeScript: `do` operator does not compile with next callback only

### ISSUE THREAD

**Issue by trainerbill** [ReactiveX/rxjs#2102]
**RxJS version:**
5.0.0-rc.1
**Code to reproduce:**
```js
let test = [
      {
        name: 'sure'
      },
      {
        name: 'thing'
      }
    ]

    Rx.Observable.from(test)
      .do(x => console.log(x.name))
      .map(x => x.name = 'map')

    Rx.Observable.from(test)
      .do({ next: x => console.log(x.name) })
      .map(x => x.name = 'map')
```
**Expected behavior:**
Should be able to use do with just a callback:  .do(x => console.log(x.name))
**Actual behavior:**
The typing on the next callback is ignored unless you specifically add the next property:  .do({ next: x => console.log(x.name) })
**Additional information:**
TSC errors.  Screenshot from VSCode
![image](https://cloud.githubusercontent.com/assets/3578259/20014622/c328cebc-a285-11e6-86f4-1cc3b6a6c15d.png)

**Comment by astanet** [comment]
Same problem.
I've downgraded back to 5.0.0-beta.12 and errors cleared.

**Comment by blesh** [comment]
Cc @david-driscoll

**Comment by david-driscoll** [comment]
this was fixed by #2022 

Just pending release at the moment.

**Comment by astanet** [comment]
Thank you!
I'm looking forward to recieve next release.

**Comment by jayphelps** [comment]
rc2 has landed. https://github.com/ReactiveX/rxjs/blob/master/CHANGELOG.md#500-rc2-2016-11-05
