### ISSUE TITLE
Documentation Generation Broken

### ISSUE THREAD

**Issue by blesh** [ReactiveX/rxjs#2111]
Currently the documentation, when generated, is missing all of the operator documentation. This is a bit of a fire we need to put out because they've been generated and pushed to http://reactivex.io/rxjs ... so we need to fix this ASAP, (before any other changes are merged) and republish the docs.

**Comment by staltz** [comment]
Sigh, we need to do better PR reviewing.

**Comment by jayphelps** [comment]
published updated docs. looks good to me, but others should confirm.

**Comment by staltz** [comment]
Looks correct IMO.
