### ISSUE TITLE
Changes in API docs not helpful

### ISSUE THREAD

**Issue by slmyers** [ReactiveX/rxjs#2115]
Recently some changes appear to have been made to the [docs](http://reactivex.io/rxjs/). I can not seem to find any documentation w.r.t. `classes` or `operators`. Instead I can only find `variables` and `types`. Before I could easily look up (seemingly) all the available operators easily. 

```
example 
-> I search concat in the search bar
-> I click the 'method' link 
-> link is broken
-> other links are not helpful
```

Currently these docs are in a more-or-less unusable state, unless I'm missing something non-obvious, and if so please help me and close issue. Thanks.

**Comment by kwonoj** [comment]
Seems related to https://github.com/ReactiveX/rxjs/issues/2111.

**Comment by slmyers** [comment]
thanks
