### ISSUE TITLE
rxjs/Rx has no default export

### ISSUE THREAD

**Issue by Modellium** [ReactiveX/rxjs#2116]
Hey,

Not sure if it applies as an "issue", but it sure would be great to update the README documentation.

Where it say: 

"To import the entire core set of functionality:

import Rx from 'rxjs/Rx'; "

There is no default export on rxjs/Rx and I don't think there have been for some time.

It can be confusing

Adam Kettani

**Comment by jayphelps** [comment]
Thanks! I believe this is the same as #2085. Whether or not you see a default export depends on the loader you're using...we're going to try to rework our README instructions to be more explicit about these sorts of things.

**Comment by AdamKettani** [comment]
Alright thank you, what loader is currently working?

**Comment by awerlang** [comment]
Add this to your `tsconfig.json`:

```json
  "compilerOptions": {
   ...
    "allowSyntheticDefaultImports": true,
  }
```

**Comment by sikharsaikia** [comment]
Changing Changing import Rx from 'rxjs/Rx'; to import * as Rx from 'rxjs/Rx'; fixes it. Thanks to Denis https://github.com/ReactiveX/rxjs/issues/2085

**Comment by benlesh** [comment]
No longer relevant in v6
