### ISSUE TITLE
Finally called multiple times

### ISSUE THREAD

**Issue by Liplattaa** [ReactiveX/rxjs#2117]
Hi,

Sample code:
`console.log('OBSERVER');`
`    let source: Observable<number> = Observable.create(observer => {`
`      observer.next(5);`
`      observer.complete();`
`    }).finally(() => console.log('FINALLY'));`
`    source.subscribe(() => {});`
`    source.subscribe(() => {});`

I would expect finally callback to be called once, when the observable is completed. Instead it's called as many times as it's subscribed to. 
The Output:
`OBSERVER`
`FINALLY`
`FINALLY`

Is it intentional behavior? Is it any method that is called one per observable when it actually is terminated?

**Comment by trxcllnt** [comment]
Yes. Finally is executed when a subscription is disposed (on error, complete, or unsubscribe). You've subscribed twice (and subscribers are executed in isolation), so your finally selector will execute for each subscription.

**Comment by jinroh** [comment]
@Liplattaa to reuse an analogy (I think used by @trxcllnt), defining an Observable is like defining a function that can return zero, one or multiple values over time. `subscribe`ing is like invoking the function.

So, your example could be compared to this one:

```js
function source() {
  try {
    return 5;
  } finally {
    console.log('FINALLY')
  }
}

source();
source();
```

**Comment by blesh** [comment]
I feel this has been adequately answered. I'm going to close it.

Feel free to reopen it continue discussion. 

Thanks for filing the issue and caring about the quality of this library#
