### ISSUE TITLE
No typings about 'this' of observer taken by Observable.prototype.subscribe()

### ISSUE THREAD

**Issue by saneyuki** [ReactiveX/rxjs#2126]
**RxJS version:**

- 5.0.0-rc2

**Code to reproduce:**

By unit tests, an observer arguments of `Observable.prototype.subscribe()` can call `this.unsubscribe()`

- https://github.com/ReactiveX/rxjs/blob/68af9ef/spec/Observable-spec.ts#L336
- https://github.com/ReactiveX/rxjs/blob/68af9ef/spec/Observable-spec.ts#L489

But there is no type information about its `this`.

- https://github.com/ReactiveX/rxjs/blob/68af9ef7307f1652b06049079458d6fec329d082/src/Observable.ts#L74-L106
- https://github.com/ReactiveX/rxjs/blob/68af9ef7307f1652b06049079458d6fec329d082/src/Observer.ts

**Expected behavior:**

- We should decide to:
  - clarify the type of `this` for an observer arguments of `Observable.prototype.subscribe()`.
  - or make `spec/` not use `this.unsubscribe()`

**Comment by trxcllnt** [comment]
I'm unaware of whether TS has a solution to this, but essentially Observable's subscribe method takes in three callbacks or an Observer, but then wraps and returns the callbacks/Observer in a Subscriber. `next`, `error`, and `complete` are run in the context of the Subscriber that we created internally, so it's possible to do `this.unsubscribe()` in a `next` call.

Does TS have a way to annotate that the `this` binding for the notification callbacks (assuming no arrow functions) is going to be a specific type?

**Comment by blesh** [comment]
> so it's possible to do this.unsubscribe() in a next call.

We don't want people doing that.

**Comment by blesh** [comment]
The fact people can do this is really just leaky implementation. We don't want to guide people to do this with typings information.

**Comment by trxcllnt** [comment]
@blesh I thought that was a core feature of using Subscribers? We [bend over backwards](https://github.com/ReactiveX/rxjs/blob/master/src/Subscriber.ts#L177) to make it possible to call `this.unsubscribe()` inside all the notification methods. Would certainly make things easier if this _wasn't_ a thing we had to support.
