### ISSUE TITLE
Maximum Call Stack Exceeded When Passing oberver.next

### ISSUE THREAD

**Issue by marwan-at-work** [ReactiveX/rxjs#2140]
**RxJS version:** "^5.0.0-rc.3"

If I want to create an observable that subscribes to another observable, I'd have to pass anonymous functions that calls the `observer.next` function. Instead, I'd like to just pass `observer.next` top level. I'm not sure why I get a `Maximum call stack size exceeded`. 

**Code to reproduce:**

Code that causes an error:

```js

import { Observable } from 'rxjs/Rx';

const stream$ = new Observable(observer => {
  Observable.fromPromise(fetch('www.example.com'))
  .subscribe(observer.next, observer.error, observer.complete)
})

stream$.subscribe(console.log, console.log, console.log)
```

Code that passes:

```js
import { Observable } from 'rxjs/Rx';

const stream$ = new Observable(observer => {
  Observable.fromPromise(fetch('www.example.com'))
  .subscribe((x) => {
    observer.next(x);
  }, (err) => {
    observer.error(err);
  }, () => {
    observer.complete()
  });
})

stream$.subscribe(console.log, console.log, console.log);
```

**Expected behavior:**
I should be able to pass `observer.next` as a function to the higher-order `subscribe`

**Actual behavior:**

```
RangeError: Maximum call stack size exceeded
    at SafeSubscriber.Subscriber.next (/node_modules/rxjs/Subscriber.js:87:42)
    at SafeSubscriber.Subscriber.next (/node_modules/rxjs/Subscriber.js:89:18)
    at SafeSubscriber.Subscriber.next (/node_modules/rxjs/Subscriber.js:89:18)
    at SafeSubscriber.Subscriber.next (/node_modules/rxjs/Subscriber.js:89:18)
    at SafeSubscriber.Subscriber.next (/node_modules/rxjs/Subscriber.js:89:18)
    at SafeSubscriber.Subscriber.next (/node_modules/rxjs/Subscriber.js:89:18)
    at SafeSubscriber.Subscriber.next (/node_modules/rxjs/Subscriber.js:89:18)
    at SafeSubscriber.Subscriber.next (/node_modules/rxjs/Subscriber.js:89:18)
    at SafeSubscriber.Subscriber.next (/node_modules/rxjs/Subscriber.js:89:18)
    at SafeSubscriber.Subscriber.next (/node_modules/rxjs/Subscriber.js:89:18)
```

**Additional information:**
Would love to know the reason if this is expected.

**Comment by kwonoj** [comment]
So far I know when passing function as reference it detaches context. By doing so, internally created subscriber cannot track of its critical state such as if it's closed, etcs. To preserve each context, you may need invoke as you tried like

`.subscribe(val => observer.next(val));`

or bind context 

`.subscribe(observer.next.bind(observer));`

There are similar cases reported and explained behavior in detail, refer https://github.com/ReactiveX/rxjs/issues/1981, https://github.com/ReactiveX/rxjs/issues/1948, or other similar.

**Comment by marwan-at-work** [comment]
cool, in this case babel's `::observer.next` can also be passed i presume. 
Thanks for the info!

**Comment by trxcllnt** [comment]
@marwan-at-work alternatively, you can pass the `observer` as the only argument to subscribe.

**Comment by kwonoj** [comment]
I think this issue is resolved, closing for now. Please feel freely reopen as needed, or it's not fully resolved.
