### ISSUE TITLE
error in JQuery promise appears not to be handled correctly.

### ISSUE THREAD

**Issue by samueljseay** [ReactiveX/rxjs#2150]
Trying to get around #2149 . using `rx-observable` again, I thought I'd use a JQuery ajax call instead which handles the timeout better with some status text indicating a timeout.. But then came across another issue which seems like a bug. I tried to understand the code where the error is raised, but I'm not sure why it happens... Is this due to JQuery promises not being A+?

**RxJS version:** 5.0.0-rc.4 (and jquery 1.11.3)

**Code to reproduce:**

```javascript
export default action$ =>
  action$
    .ofType(ACTION_TYPES.FETCH_COMPARISON_FROM_CHANGESET)
    .mergeMap(action => {
        return Observable.fromPromise($.ajax({
          ...
         }).promise())
         .map(payload => {
          ...
         })
        .catch((error) => {
          ...
        })
```

**Expected behavior:** errors as a result of a timeout are caught so they can be handled

**Actual behavior:** an error from the xhr timeout is handled in the catch, but an additional `Uncaught undefined` exception is raised.

**Additional information:** The exception is raised here: https://github.com/ReactiveX/rxjs/blob/master/src/observable/PromiseObservable.ts#L76 and the `err` is undefined.

**Comment by unao** [comment]
> an error from the xhr timeout is handled in the catch, but an additional Uncaught undefined exception is raised.

how exactly is it handled? do you return an observable from `.catch`?

**Comment by samueljseay** [comment]
@unao yes, returning an `Observable.of` with a plain object. The exception is not raised in the catch though (just in case that isn't clear) the exception is raised in `PromiseObservable`

I struggle to understand what kind of error would be `undefined` in this case

**Comment by benlesh** [comment]
Closing this as stale.

Pretty sure it has to do with JQuery's promise behavior at the time of the issue being filed.
