### ISSUE TITLE
rc4 compilation failure with operator/distinctKey

### ISSUE THREAD

**Issue by alexeagle** [ReactiveX/rxjs#2161]
src/add/operator/distinctKey.ts(2,29): error TS2307: Cannot find module '../../operator/distinctKey'

**Comment by Brooooooklyn** [comment]
`distinctKey` was removed https://github.com/ReactiveX/rxjs/commit/89612b2914fe0f48123ceaa66e3e63b5f7975873

**Comment by jayphelps** [comment]
We forgot to remove the file https://github.com/ReactiveX/rxjs/blob/c7cfe444642407f3227a09a0cdf38fd495b867e1/src/add/operator/distinctKey.ts
