### ISSUE TITLE
Why different generics for Subscriber and Observable

### ISSUE THREAD

**Issue by donaldpipowitch** [ReactiveX/rxjs#2166]
Not sure if this is a bug or not.

**RxJS version:**

`5.0.0-rc.4`

**Code to reproduce:**

https://github.com/ReactiveX/rxjs/blob/e91d113e49acc9b0e12e2524040fa84cf3fa2c78/src/Observable.ts#L56

**Expected behavior:**

```ts
  static create: Function = <T>(subscribe?: <T>(subscriber: Subscriber<T>) => TeardownLogic) => {
    return new Observable<T>(subscribe);
  };
```

**Actual behavior:**

```ts
  static create: Function = <T>(subscribe?: <R>(subscriber: Subscriber<R>) => TeardownLogic) => {
    return new Observable<T>(subscribe);
  };
```

**Additional information:**

Maybe I misunderstood this part of RxJS, but I thought the Observable and Subscriber would share the same generic type here? Aren't the values I pass to `subscriber.next` from the same type I get when I use `value$.map`?

**Comment by kwonoj** [comment]
Actually I lost history in my memory for background of this - /cc @david-driscoll : any idea?

**Comment by david-driscoll** [comment]
that looks odd at first glance and probably needs to be changed.

that said since subject has a different create method than observable the typings mean nothing as it only has a function type.

**Comment by blesh** [comment]
Looks incorrect to me.

**Comment by kudoz83** [comment]
I came across this because I'm experiencing an issue where Typescript is not properly resolving the return value for Observable.create.  

```
static create: Function = <T>(subscribe?: <T>(subscriber: Subscriber<T>) => TeardownLogic) => {
    return new Observable<T>(subscribe);
};
```

I think assigning create the global Function type is the issue.  I believe this would resolve it...
```
static create = <T>(subscribe?: <T>(subscriber: Subscriber<T>) => TeardownLogic) => {
    return new Observable<T>(subscribe);
};
```

```
static create = (subscribe?: <T>(subscriber: Subscriber<T>) => TeardownLogic) => {
    return new Observable<T>(subscribe);
};
```
