### ISSUE TITLE
TestScheduler ColdObservable unable to emit synchronously

### ISSUE THREAD

**Issue by benlesh** [ReactiveX/rxjs#2169]
According to @trxcllnt's comment [here](https://github.com/ReactiveX/rxjs/pull/2158#issuecomment-263513890), `cold('(a|)')` will not synchronously emit `a` like `Observable.of('a')` would.

`Observable.of('a')` and `cold('(a|)')` should be equivalent.

**Comment by benlesh** [comment]
@kwonoj is this still the case? This is a really old issue. Can you verify?

**Comment by kwonoj** [comment]
This is still an issue and tried attempt few way to resolve this but wasn't successful so far.

**Comment by benlesh** [comment]
I guess we could just examine the marbles we get, and if all notifications are on `0`, we synchronously subscribe. It'll be some gross conditionals, but it should work.

**Comment by kwonoj** [comment]
correct, I could make gross conditional but somehow failed to coordinate synchronous subscription with other marbles created. I'm feeling I did something very incorrect, just need some more trial & errors.

**Comment by benlesh** [comment]
@kwonoj maybe put up a PR as a WIP and we can have a look?

**Comment by kwonoj** [comment]
makes sense, I'll prep it to anyone can see error I saw (and possibly can mock me about mistakes I made there :lol:)

**Comment by benlesh** [comment]
This is something the new design @jayphelps and I came up with should cover.

**Comment by benlesh** [comment]
As it's not something that is really a bug with the current ColdObservable, I'm going to close this.
