### ISSUE TITLE
Difference between ReactiveX/RxJS and Reactive-Extensions/RxJS

### ISSUE THREAD

**Issue by timotei** [ReactiveX/RxJS#217]
Hello,

I haven't found anything on what is the difference between the 2 projects (except their owners) and what are the (functional) differences between them.

Can anyone shed light on this?

Thanks!

**Comment by staltz** [comment]
As far as I know: ReactiveX/RxJS is a rewrite of Reactive-Extensions/RxJS and is intended to supersede it once it's ready. It's more performant and built with modern JavaScript (TypeScript to be more precise). The Reactive-Extensions/RxJS is built with JavaScript ES5 and doesn't even use CommonJS modules for instance.

**Comment by mattpodwysocki** [comment]
@timotei the official line is that this is a rewrite with performance and modularity in mind. RxJS in the Reactive-Extensions group will continue for the foreseeable future while this is in development.  Once it has met and surpassed the existing RxJS in terms of functionality and performance, then we will do a cutover to the new architecture.  This means there is a lot work ahead of us in terms of ensuring our virtual time tests are correct here in addition to any other work items that we have here.  We'd love to have help with both obviously, RxJS in the existing repository in the short run in terms of performance and features, and here with building the future!

**Comment by blesh** [comment]
Yes... @timotei this is a (currently) pre-alpha "future" of RxJS. If you start using this now, I can roughly guarantee you'll pay some heavy pioneer's tax over the short term. The reason it's over *here* (ReactiveX) is to join RxJS with the rest of the ReactiveX community.

**Comment by timotei** [comment]
Thanks a lot for the info!

**Comment by arlair** [comment]
Thanks for the info. I was confused about this as it is not apparent from the home page what is happening with the two projects. It took a few different avenues for me to arrive here.
