### ISSUE TITLE
Examples do not have resulting output

### ISSUE THREAD

**Issue by stepanzarubin** [ReactiveX/rxjs#2171]
Documentation examples does not have resulting output, which is not obvious and makes study process difficult.

```
var weight = Rx.Observable.of(70, 72, 76, 79, 75);
var height = Rx.Observable.of(1.76, 1.77, 1.78);
var bmi = Rx.Observable.combineLatest(weight, height, (w, h) => w / (h * h));
bmi.subscribe(x => console.log('BMI is ' + x));
```

How can I know the output without running it myself? Am I missing something?

**Comment by jayphelps** [comment]
I think that's a definitely fair critique. Thanks for letting us know!

As a side note, the marble diagrams do show you the results of using an operator, but it's not the results from the example section 🙁  http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#instance-method-combineLatest

![image](https://cloud.githubusercontent.com/assets/762949/20895779/a2675470-bacf-11e6-8fbf-c74b1180893f.png)

We're also will missing docs for many of the operators. We know this, just lack the resources/contributors at the moment.

**Comment by jrroman** [comment]
@jayphelps are these answers something that you would like added to the README.md? If so I would be more than happy to help out.

**Comment by jayphelps** [comment]
@jrroman we don't wanna add operator specific docs to the README itself, but certainly if you have cycles to amend the inline ESDoc documentation and showing what the example would output, please do!

**Comment by jrroman** [comment]
@jayphelps that sounds good to me!

**Comment by stepanzarubin** [comment]
@jayphelps I can contribute on my free time by adding examples output whenever possible, just give me a single example so that we have a standard formatting.

**Comment by stepanzarubin** [comment]
@blesh this does not affect public docs,  is this what community wants to avoid here?[http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#static-method-combineLatest](http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#static-method-combineLatest)

**Comment by jrroman** [comment]
@stepanzarubin What do you mean by, this does not affect public docs?

**Comment by blesh** [comment]
@stepanzarubin I think it's that we didn't update the docs yet.

**Comment by benlesh** [comment]
Closing as stale
