### ISSUE TITLE
Stop Rx.Subject/Observable from emitting like event.stopPropagation do

### ISSUE THREAD

**Issue by kstro21** [ReactiveX/rxjs#2175]
Probably this is out of the Observable Pattern and can not be even considered, can be a feature request or I can't found in the docs the right function to do it, so, here is my example:

```javascript
var source = new Rx.Subject();

source.map((data) => {console.log('map1'); return data;})
	.subscribe((data) => {
		console.log('subscribe1', data);
		if(someCondition) {
			source.stop(); //????????
		}
	});

source.map((data) => {console.log('map2'); return data;})
	.subscribe((data) => {
		console.log('subscribe2', data);
	});
```
So, when I call `source.next("Hello World");` only the first subscriber will be notified. Of course this will fail in `source.stop()` because the `stop` function does not exist but it is just to elaborate my question.

I know that I don't have a chain where the value goes like `source` => `subscribe1` => `subscribe2`. Right now I have `source` => `subscribe1` and then `source` => `subscribe2`. But in the console it prints

```
map1
subscribe1
map2
subscribe2
```
so there is a sequence. So, exist a way to say: `"Hey, do not emit any more for now"`, like event.stopPropagation do?

**Comment by studds** [comment]
You could try something like:

(Getting rid of the maps which seem to do nothing - if you want to observe with no side effects, try `do`.

```
var source = new Rx.Subject();

// filtered source will only "fire" if some condition is true
var filteredSource = source.filter((data) => someCondition);

// by subscribing to source, I get everything
source.subscribe((data) => {
		console.log('subscribe1', data);
	});

// by subscribing to filteredSource, I only get those events which match `someCondition`
filteredSource((data) => {
		console.log('subscribe2', data);
	});
```

**Comment by kstro21** [comment]
I was hopping that RxJS has an option/fucntion so the sequence could be stopped, filter does not suggest it can block the item from getting to the next observer at all, at least the name of the function doesn't :-). Your answer is kind of a hack, but your idea help me to accomplish what I wanted. Thanks

**Comment by blesh** [comment]
I think the difficulty here is it's not really a "propagation", per se. It's more notifiying a list of observers that have no hierarchy.

**Comment by kwonoj** [comment]
Closing for now as some answers been provided.

**Comment by 12kb** [comment]
Looks like some bad practice. If event fired on some channel ALL it's subscribers should be called (otherwise one can expect hardly understandable bugs). And in my understanding it's better not to assume any order of called subscribers. So that it could happen that 2nd subscriber will be called first (that should be implementation dependant). With knowing the order you breaking encapsulation.

In this case running subscribers separately is correct solution. Create another stream for 2nd subscriber. E.g. with filter (as it was already proposed) or takeUntill (if you need to unsubscribe 2nd subscriber) operator.
