### ISSUE TITLE
Custom error object is no longer typeof Error from TypeScript 2.1

### ISSUE THREAD

**Issue by kwonoj** [ReactiveX/rxjs#2178]
**RxJS version:**

**Code to reproduce:**

**Expected behavior:**

**Actual behavior:**

**Additional information:**
Was shared in meeting, it is actually intended design of TS 2.1 (https://github.com/Microsoft/TypeScript-wiki/blob/master/Breaking-Changes.md#extending-built-ins-like-error-array-and-map-may-no-longer-work) that no longer allows to extend built in object by default. 

Means, all of custom errors in RxJS v5 (i.e `TimeoutError`) is not typeof `Error`, will break existing code if anyone does type checking for those, as well as existing test cases too.

**Comment by kwonoj** [comment]
Assigning myself for now.

**Comment by kwonoj** [comment]
Seems 2.2 have enhancement support for this : https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#support-for-newtarget

**Comment by saneyuki** [comment]
@kwonoj 

> Seems 2.2 have enhancement support for this

IE9 & IE10 does not have `__proto__`. I feel it would not work well for them.

**Comment by kwonoj** [comment]
I'm closing this issue since we don't have exact plans to bump up compiler, can revisit later once things are getting clear.
