### ISSUE TITLE
update type definition of 'pluck' to support type inference correctly, without 'this' context

### ISSUE THREAD

**Issue by SimonSchick** [ReactiveX/rxjs#2179]
**RxJS version:** 5.0.0-rc.5

**Code to reproduce:** 
```
Observable.of({ a: 'test' }).pluck<string>('a')
```

**Expected behavior:**
First parameter is the return type.

**Actual behavior:**
Previously the first generic parameter of `pluck` was the return type, now it's the type to pluck from.
This causes code that previously build fine to fail and requires the addition of another (redundant) parameter.

```
Observable.of({ a: 'test' }).pluck<Object, string>('a')
```

**Additional information:**
Reversing the order of the generic parameters should fix this.

**Comment by kwonoj** [comment]
So, this is actually not `reversed` order of generics - it's due to newly introduced TS@2 `this` context syntax in operator signature preempt instead of delivering type to return type <R>, makes no way to automatically infer return type.

Seems this is regression https://github.com/ReactiveX/rxjs/pull/1978. 
/cc @david-driscoll

**Comment by david-driscoll** [comment]
There is no real easy fix at the moment (besides dropping the `this` context changes), I imagine the compiler could maybe fix this somehow but I don't think that it would be trivial.

With TS2.1 this can be easily addressed however by using the `keyof` and `T[K]` features, and bonus is that we would get real type inference here.  #2181

**Comment by kwonoj** [comment]
Yes, TS@2.1 breaking feature seems a solution for this.

**Comment by kwonoj** [comment]
Basically using `keyof` will looks similar to proposal at https://github.com/ReactiveX/rxjs/issues/2295#issue-201684463 .
