### ISSUE TITLE
Rx.js bundle issue with Angular 2

### ISSUE THREAD

**Issue by nording** [ReactiveX/rxjs#2185]
When I try to load RxJS as a bundled file I get a few issues.
Today with RxJS (5.0.0-rc.4) you get a few exports in the rxjs/bundles/Rx.js file, but the exports are not flatted out.

With Angular 2 this is a issue. For example Angulars 2 (core.umd.js) trying to import "rxjs/operator/concatMap".
When concatMap is bundled together in the Rx.js file, and you trying to run the code, you get a error because concatMap is only available if you go thru the exported Observable object, like this Observable.prototype.concatMap.

It is not available in the root of the export, which is expected when you import a file like "rxjs/operator/concatMap" as rxjs_operator_concatMap and then run rxjs_operator_concatMap.concatMap(...).

Could we export this different in the bundled file?
Not sure if I missing something, if I do please let me know.

**RxJS version: 5.0.0-rc.4**

**Code to reproduce:**

**Expected behavior:**

**Actual behavior:**

**Additional information:**

**Comment by benlesh** [comment]
This is a really old issue. I'm going to close it. Probably a better question for the Angular/Angular-CLI folks.
