### ISSUE TITLE
"scan" definition is not correct on 5.0.1

### ISSUE THREAD

**Issue by ovrmrw** [ReactiveX/rxjs#2192]
`"rxjs": "5.0.1"`

If my scan has a seed, "A" is used yet "B" is expected.
```
// node_modules/rxjs/operator/scan.d.ts
import { Observable } from '../Observable';
export declare function scan<T>(this: Observable<T>, accumulator: (acc: T, value: T, index: number) => T, seed?: T): Observable<T>; // A
export declare function scan<T>(this: Observable<T>, accumulator: (acc: T[], value: T, index: number) => T[], seed?: T[]): Observable<T[]>;
export declare function scan<T, R>(this: Observable<T>, accumulator: (acc: R, value: T, index: number) => R, seed?: R): Observable<R>; // B
```

My solution is comment out "A" but this is not ideal.
```
import { Observable } from '../Observable';
// export declare function scan<T>(this: Observable<T>, accumulator: (acc: T, value: T, index: number) => T, seed?: T): Observable<T>; // A
export declare function scan<T>(this: Observable<T>, accumulator: (acc: T[], value: T, index: number) => T[], seed?: T[]): Observable<T[]>;
export declare function scan<T, R>(this: Observable<T>, accumulator: (acc: R, value: T, index: number) => R, seed?: R): Observable<R>; // B
```

**Comment by ovrmrw** [comment]
I think this is a good idea.
```
import { Observable } from '../Observable';
export declare function scan<T>(this: Observable<T>, accumulator: (acc: T, value: T, index: number) => T): Observable<T>;
export declare function scan<T, R>(this: Observable<T>, accumulator: (acc: R, value: T, index: number) => R, seed: R): Observable<R>;
```

**Comment by kwonoj** [comment]
It's a bit hard to think given suggestion is expected signature of operator behavior, as in case of `T->T`, it is still available to supply seed as needed. Provided signature in https://github.com/ReactiveX/rxjs/issues/2192#issuecomment-266630569 prohibits to supply those use cases.

Before getting a conclusion, I'd like to ask code snippet you've tried to get some more detailed clarification. what type of value supplied in seed? is it `<T>` and type definition still infers to have `<R>`? I just tried on my end, 

```js
class TypeA {
  a: boolean;
}

class TypeB {
  b: string;
}

//infers to  '(acc: TypeA, value: TypeA, index: number) => TypeA', 
//which (acc: T, value: T, index: number) =>T
Rx.Observable.of(new TypeA()).scan((acc, value) => { }, new TypeA());

//infers to  '(acc: TypeB, value: TypeA, index: number) => TypeB'
//which (acc:R, value:T, index: number) =>R
Rx.Observable.of(new TypeA()).scan((acc, value) => { }, new TypeB());
```

looks type inference works as expected.

**Comment by ovrmrw** [comment]
In my case.
```
import { Subject } from 'rxjs/Rx';

class Increment {
  constructor() { }
}

class Decrement {
  constructor() { }
}

type Action = Increment | Decrement;

const dispatcher = new Subject<Action>();

const num: number = 0;

dispatcher.scan((state, action) => {
  if (action instanceof Increment) {
    return state + 1; // <--- state is recognized as Action, so this line becomes type error.
  } else {
    return state;
  }
}, num);

dispatcher.next(new Increment());
```

**Comment by kwonoj** [comment]
@ovrmrw that's because your signature of `scan` is actually `scan<Action, number>`, since original Observable is `Observable<Action>` by type of `dispatcher`, so supplied seed `num` is  number as `<R>` and state becomes `Action` as `<T>`.

I hope this clarifies your issue, closing it now as I believe there isn't issue related with type inference.

**Comment by kwonoj** [comment]
@ovrmrw that's because your signature of `scan` is actually `scan<Action, number>`, since original Observable is `Observable<Action>` by type of `dispatcher`, so supplied seed `num` is  number as `<R>` and state becomes `Action` as `<T>`.

I hope this clarifies your issue, closing it now as I believe there isn't issue related with type inference.

**Comment by kwonoj** [comment]
Actually thinking bit more, it explains why your signature falls back into given signature but have to think a bit more if this is legit ergonomics. (maybe I'm also confused) - reopening.

**Comment by ovrmrw** [comment]
@kwonoj I found very confused solution. Is this a bug of TypeScript... ?

```
import { Subject } from 'rxjs';

class Increment {
  constructor() { }
  value; // <--- add a property in class.
}

class Decrement {
  constructor() { }
  value; // <--- add a property in class.
}

type Action = Increment | Decrement;

const dispatcher = new Subject<Action>();

const num: number = 0;

dispatcher.scan((state, action) => {
  if (action instanceof Increment) {
    return state + 1; // <--- then, state is recognized as "number". why ... ??
  } else {
    return state;
  }
}, num);

dispatcher.next(new Increment());
```

**Comment by kwonoj** [comment]
I'm not sure where this landed but it's quite old, guess new TS compiler improved ergonomics. Closing for now, will revisit if needed.

**Comment by deebloo** [comment]
@kwonoj I am seeing this issue with ts 2.4 now. not sure if anyone found a workaround

**Comment by hiepxanh** [comment]
me too, same issue in ts 2.4
