### ISSUE TITLE
Document hint in VS Code shows HTML tags

### ISSUE THREAD

**Issue by BrainCrumbz** [ReactiveX/rxjs#2197]
Hello all. Not sure this is strictly limited to RxJs, but I've noticed it only on a method from this particular library.

**RxJS version:**
5.0.0-rc.1

**Code to reproduce:**
1. have an Angular 2 / TypeScript 2 web application
1. open it in Visual Studio Code, v1.8.0
1. reach for an `Observable<>.do()` invocation
1. over mouse to show documentation tooltip

**Expected behavior:**

Text should be something like:

```
Perform a side effect for every emission on the source Observable, but return an Observable that is identical to the source.

Intercepts each emission on the source and runs a function, but returns an output which is identical to the source.

[here there could be an image, or nothing]
```

**Actual behavior:**

Text shows as: 

```
Perform a side effect for every emission on the source Observable, but return an Observable that is identical to the source.

<span class="informal">Intercepts each emission on the source and runs a function, but returns an output which is identical to the source.</span>

<img src="./img/do.png" width="100%">
```

**Additional information:**

Also looking at the bottom part of text, scrolling down, there are some other `@return` tags, don't know if they should show up like that.

Here's a screenshot showing the actual issue:

![vscode rx help hover](https://cloud.githubusercontent.com/assets/3185573/21218438/de4f6e26-c2b0-11e6-9893-ba80efd8559a.png)

**Comment by staltz** [comment]
JSDoc allows HTML tags embedded into it. Our JSDocs as they are right now are crucial for generating the webpage. I think this issue is with VSCode, not RxJS. Or what do you suggest we do instead?

**Comment by BrainCrumbz** [comment]
Given that RxJs docs adhere to JSDoc standard, I'd say RxJs is all set then. Will submit this to VS Code, in case its team is not aware of already.

**Comment by staltz** [comment]
Also, as far as I remember, Intellij IDEA is able to embed HTML `img` in JavaDoc comments when you hover for docs.
