### ISSUE TITLE
Randomly emitting partial values

### ISSUE THREAD

**Issue by Blightwidow** [ReactiveX/rxjs#2204]
**RxJS version:**
5.0.0-beta.12 in Angular 2.2.1

**Code to reproduce:**
```JavaScript
getComments(key: string): Observable<Array<Comment>> {
return Observable.zip(
      this.comments$.distinct(),
      this.commentsPerArticle$.distinct(),
      (comments, assoc) => { return { comments: comments, assoc: assoc }; }
    )
      .do(console.log)
      .map(data => { return data.comments.filter(com => data.assoc.find(rule => rule.$key == key)[com.$key]); });
}
```
**Expected behavior:**
If you ignore the console.log for debugging purposes, the only purpose is to return an observable containing an array of Comments objects.

It filter the comments$ Observable using the commentsPerArticle$ association node list in my Firebase DB.

**Actual behavior:**
It work most of the time, showing the following in the console:
![Scrot1.png](https://s28.postimg.org/j8g7m9ict/Scrot1.png)

Sometimes thought, when the function is called once, here is the output:
![Scrot1.png](https://s28.postimg.org/slhsy7771/Scrot2.png)

Even thought the two parent Observables didn't change value at all (checked thought subscription), the Observable is applying the map and zip functions on part of the observables value. The map and zip functions are called with only parts of the data of the current Observable state.

**Additional information:**
The function is called by an Angular components, but as this behavior is not supposed to happen and has nothing to apparently do with angular, i'm posting it here.

**Comment by kwonoj** [comment]
Would you able to provide small working snippet in jsbin or similar, or repo? attached code snippet seems legit, but can't say for sure cause it misses some context of source observables and can't run it by myself.

**Comment by Blightwidow** [comment]
I'll try tomorrow to put a working example, but it's pretty hard to mimic as this behavior appear pretty unpredictably.

For context the values of each Observable are just lists of Object pulled from FireBase.

**Comment by Blightwidow** [comment]
### A small update

While making the plunkr (https://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=preview), I understood the bug:

The observable I create through behavior subject in the Plunkr are actually a bit different in my code as it come from a FireBase DB:

```JavaScript
this.articles$ = this.af.database.list('/articles').do(val => this.articleKeys = val.map(v => { return v.$key; }));
    this.comments$ = this.af.database.list('/comments');
    this.commentsPerArticle$ = this.af.database.list('/commentsPerArticle');
```

I was then returning the different Observables from the service. The problem seems to be the way angularFire build his Observables. It was emitting not the complete values but some part of it. 

Adding the share() method the the af.database.list() Observables fixed the issue but I'm still unsure exactly why.
