### ISSUE TITLE
Missing SubjectSubscriber

### ISSUE THREAD

**Issue by kostonstyle** [ReactiveX/rxjs#2207]
Hi all

I am using https://cdnjs.cloudflare.com/ajax/libs/rxjs/5.0.1/Rx.min.js and could not create an object of 
`
let oEditSubject = new Rx.SubjectSubscriber();`

What am I doing wrong?

Thanks

**Comment by kwonoj** [comment]
`SubjectSubscriber` is not exported in global namespace `Rx`, so it is expected. In case of cjs / ES module you can import it via `Subject/SubjectSubscriber`, but not sure how to in UMD module (since I haven't use UMD in general)

**Comment by blesh** [comment]
@kostonstyle that's a private API, and I would not recommend using it as it may change in a refactor without use considering it a "breaking change".

**Comment by kostonstyle** [comment]
Ok thanks guys for helping.
