### ISSUE TITLE
Specify deprecation notice in `rxjs-es` package

### ISSUE THREAD

**Issue by kwonoj** [ReactiveX/rxjs#2218]
**RxJS version:**
b.12

**Code to reproduce:**
https://www.npmjs.com/package/rxjs-es

**Expected behavior:**

**Actual behavior:**

**Additional information:**
Currently `rxjs-es` package is stay there with last available (b.12, https://www.npmjs.com/package/rxjs-es) , and there isn't any update further since newly published package won't include any ES2015 packages. NPM no longer allows delete package so anyone search npm packages can find, install unsupported package. While it is not available to remove packages, at least it is possible to specify given package's deprecated and not recommended to use -  such as `ghooks` does recently (https://www.npmjs.com/package/ghooks), by publishing one dummy package with deprecation notice.

Thoughts? /cc @blesh, @jayphelps .

**Comment by jayphelps** [comment]
Npm still supports the deprecate command, I believe? It would then warn the user when they install. Ben will have to do it.

**Comment by kwonoj** [comment]
If that's supported, that's good :+1:

**Comment by aluanhaddad** [comment]
👍 for [npm deprecating](https://docs.npmjs.com/cli/deprecate) this if it is indeed abandoned. I still see recommendations to use `rxjs-es` with Rollup fairly often. It is confusing.

**Comment by alexlur** [comment]
The [official documentation](http://reactivex.io/rxjs/manual/installation.html) still recommends installing `rxjs-es`. Perhaps time to update the docs?

**Comment by jayphelps** [comment]
@benlesh ^^^

**Comment by benlesh** [comment]
@jayphelps I think what's in master would be in a bad state for publishing docs just now because of the extra docs around the new lettable operators. Once we get that fixed, I'll republish the docs.

**Comment by jayphelps** [comment]
@benlesh could you checkout the commit before the stuff you don't want, then publish from there?

**Comment by benlesh** [comment]
@jayphelps .. I could... might be a bit of digging.

**Comment by benlesh** [comment]
Closing this. I don't think this is any longer an issue.
