### ISSUE TITLE
`share`d observable does not receive first value from `withLatestFrom` another observable

### ISSUE THREAD

**Issue by umidbekkarimov** [ReactiveX/rxjs#2220]
**RxJS version:**
5.0.2

**Code to reproduce:**

```javascript
const {Subject, Observable} = Rx

const doSomeExpensiveJob = (foo) => foo

const rootSubject = new Subject()

const rootStream = rootSubject
  .asObservable()

const modifiedFooStream = rootStream
  .pluck('foo')
  .map(doSomeExpensiveJob)
  //.share() 
  // if you uncomment previous line `{foo: 1, bar: 2}` will never appear in `resultStream`

const modifiedFooPlusBarStream = modifiedFooStream
  .withLatestFrom(
    rootStream.pluck('bar'), 
    (modifiedFoo, bar) => modifiedFoo + bar
  )

const resultStream = rootStream
  .combineLatest(modifiedFooStream, modifiedFooPlusBarStream, (root, modifiedFoo, modifiedFooPlusBar) => ({
    ...root, modifiedFoo, modifiedFooPlusBar,
  }))
    
resultStream
  .subscribe((props) => {
    console.log(props)   
  })

rootSubject.next({foo: 1, bar: 2})
rootSubject.next({foo: 10, bar: 20})
rootSubject.next({foo: 30, bar: 40})
```

Here [jsbin](https://jsbin.com/xizakuv/79/edit?js,console)

**Comment by blesh** [comment]
It's hard to say just looking at the example code from my phone. There might be a subscription order problem. But I need to look at a more minimal example before I can tell. When I get back to a computer I'll try to have a look

**Comment by umidbekkarimov** [comment]
Thanks for the response.

Here more minimal examples: 
Working [jsbin](https://jsbin.com/xizakuv/109/edit?js,console)
Not working [jsbin](https://jsbin.com/xizakuv/110/edit?js,console)

Difference in one `.share()` operator
___
P.S. as i start working on these examples I start to think that i'm doing something terribly wrong (making react+rxjs app work like knockoutjs with all these observations)

Basically I have stream of props and want to 

1.  Subscribe to `location.query` and transform it to `Filter` class.
2. Subscribe to redux `state`
3. Subscribe to combined `filterStream` and redux `stateStream` and get list based on filter
4. Subscribe for combined filter `stream` and `fetch` redux action and call action with filter every time it changes `.do` 
5. combine everything with propsStream

As I used filter stream 3 times (in 3, 4, and 5) i decided to share this stream and that caused this behavior
