### ISSUE TITLE
Single file typescript declarations for latest v5.0.2

### ISSUE THREAD

**Issue by roblav96** [ReactiveX/rxjs#2221]
For the previous versions of `rxjs@4.1.0` I've been able to find the typescript declarations in a single file:
https://github.com/Reactive-Extensions/RxJS/blob/master/ts/rx.d.ts
I prefer downloading the minified file off the CND from:
https://cdnjs.cloudflare.com/ajax/libs/rxjs/4.1.0/rx.js
Then importing that file using:
```typescript
global.RX = require('./rx.min')
```

But I can't find this single file declarations for the latest `rxjs@5.0.2` anywhere. I tried downloading the release and running all the `npm run compile_dist_*` but the single file declarations was never produced.

Is there any other way I can generate all the declarations into one contained file that represents the CND's minified release builds? Thank you! :D

**Comment by kwonoj** [comment]
Unfortunately no, RxJS v5 does not provide merged (flattened) type definition and no short-term plan to support this. There was actually discussion regarding this topic to support UMD type of build to have type definitions as well (https://github.com/ReactiveX/rxjs/issues/1481), but current compiler support lacks of features to merge, or flatten type definitions into a single definition from multiple definitions.

In case of RxJS v4 (and other definition such as @types package) is those are handwritten and does not have relation to actual source code, but in case of Rx v5 type is generated via actual codebases, so manual handcrafting on each type definition is something hard to be done. 

There is open discussion in compiler side support (https://github.com/Microsoft/TypeScript/pull/5332) but seems it hasn't been got lot of attention at the moment. If compiler supports those features, then it may possible to explore on this codebase if it's workable with existing codebases.

**Comment by kwonoj** [comment]
For now there isn't actionable item for this issue I'd like to suggest close and revisit once there's possible tool support as same as #1481 - what do you think @roblav96 ?

**Comment by kwonoj** [comment]
related note, https://github.com/Microsoft/TypeScript/issues/2568 maybe one possible approach but it doesn't support UMD directly, not sure if it'll work with UMD when targetted to other module types, also not sure how to validate those as well.

**Comment by roblav96** [comment]
@kwonoj Thanks so much for these resources!

I'm thinking what I might try is compress/minify the `v5.0.2` package into one file then use the https://github.com/TypeStrong/dts-bundle
I'll let you know how this turns out :D

**Comment by kwonoj** [comment]
@roblav96 yes, I was considered dts-bundle and generator (https://github.com/ReactiveX/rxjs/issues/1481#issuecomment-206167119) at the moment with original issue, no luck then. Hope it may changed and updated.

**Comment by kwonoj** [comment]
Typescript compiler considers this as 2.3 milestone https://github.com/Microsoft/TypeScript/issues/4433 , will not be able to achieve until proper upstream supports comes in.

**Comment by kwonoj** [comment]
It seems upstream issue is stall without exact milestone, I'm going to close issue for now as blocked by upstream. Once we have TSC supports we can revisit this.

**Comment by timocov** [comment]
Hi there!

I have a tool which allows to bundle single dts file - https://github.com/timocov/dts-bundle-generator.

[Here](https://gist.github.com/timocov/7427b97a05733ddc63ff2cf0e5ea86f9) is bundled dts created by `dts-bundle-generator` (entry point was `src/index.ts`). Possible that this tool is what you need until original issue from TypeScript is fixed 🙂.  Please let me know if it built something wrong or if it not worked as you expect.

/cc @kwonoj
