### ISSUE TITLE
the example code of subscription at manual overview page let me confused

### ISSUE THREAD

**Issue by Phinome** [ReactiveX/rxjs#2226]
The code at http://reactivex.io/rxjs/manual/overview.html where its executed result maybe fault.
```javascript
var observable1 = Rx.Observable.interval(400);
var observable2 = Rx.Observable.interval(300);

var subscription = observable1.subscribe(x => console.log('first: ' + x));
var childSubscription = observable2.subscribe(x => console.log('second: ' + x));

subscription.add(childSubscription);

setTimeout(() => {
  // Unsubscribes BOTH subscription and childSubscription
  subscription.unsubscribe();
}, 1000);
```
the website showed executed result is:
```javascript
second: 0
first: 0
second: 1
first: 1
second: 2
```
but as the `Subscriptions can also be put together, so that a call to an unsubscribe() of one Subscription may unsubscribe multiple Subscriptions. You can do this by "adding" one subscription into another`
meaning, up code when executed will output :
```javascript
second: 0
first: 0
second: 1
first: 1
```
i execute by Rxjs@5.0.2 , the result is 
```javascript
second: 0
first: 0
second: 1
first: 1
```

so it's a mistake or my fault ? thx

**Comment by kwonoj** [comment]
Is it? here's my result with same code :

![image](https://cloud.githubusercontent.com/assets/1210596/21517709/362230cc-cc96-11e6-9066-553776b40955.png)

rx@5.0.2 with code snippet above.

**Comment by Phinome** [comment]
my code is: 
```javascript
import Rx from "@reactivex/rxjs"

var observable1 = Rx.Observable.interval(400);
var observable2 = Rx.Observable.interval(300);

var subscription = observable1.subscribe(x => console.log('first: ' + x));
var childSubscription = observable2.subscribe(x => console.log('second: ' + x));

subscription.add(childSubscription);

setTimeout(() => {
  // Unsubscribes BOTH subscription and childSubscription
  subscription.unsubscribe();
}, 1000);
```
my node_modules is:
![image](https://cloud.githubusercontent.com/assets/1940194/21522040/0ad172aa-cd3d-11e6-8066-e6c82e7e4612.png)

the code result at chrome devtools console panel is:
![image](https://cloud.githubusercontent.com/assets/1940194/21522118/dc723178-cd3d-11e6-9b40-c833b10c012f.png)


maybe i import rxjs incorrectly or my code is incorrectly somewhere ? thx

**Comment by kwonoj** [comment]
Closing as inactive / lacks of information.
