### ISSUE TITLE
Run browser testing via global builds

### ISSUE THREAD

**Issue by kwonoj** [ReactiveX/rxjs#2229]
**Additional information:**

Currently all of testing even including browser test uses CJS build package. It'd be more ideal if browser testing uses global build package instead, to detect possible regressions on global build pipeline.

**Comment by kwonoj** [comment]
Related PR to enable test pipeline: https://github.com/ReactiveX/rxjs/pull/2225 / https://github.com/ReactiveX/rxjs/pull/2227

**Comment by benlesh** [comment]
This is old. We tried browser testing, and it was too flaky so we stopped.
