### ISSUE TITLE
subject.hasObserver not deprecated in version 4 but not included in version 5

### ISSUE THREAD

**Issue by jamesrhaley** [ReactiveX/rxjs#2232]
**RxJS version:**
5.0.2

**Code to reproduce:**
var subject = new Rx.Subject();

console.log(subject.hasObservers());

**Expected behavior:**
false

**Actual behavior:**
TypeError: subject.hasObservers is not a function

**Additional information:**
hasObserver has not been listed as deprecated in version 4 or what it has been migrated to in version 5 but as far as I can see, it is no longer an instance method of subject anymore.

**Comment by benlesh** [comment]
Closing this due to lack of interest.
