### ISSUE TITLE
Proposal: add `defaultObservableIfEmpty` to Rx.Observable.prototype

### ISSUE THREAD

**Issue by xareelee** [ReactiveX/rxjs#2239]
The [defaultIfEmpty](http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#instance-method-defaultIfEmpty) only accepts a value, not an observable, if there is no value before completed.

I think there should be a method like `defaultObservableIfEmpty` to take an Observable to be triggered if the source observable completes without emitting any next value.

For example:

```js
Observable.pairs( { a:1, b:2, c:3} )
  // won't trigger this default observable if there is any next value emitted
  .defaultObservableIfEmpty(Observable.throw(error))

Observable.pairs( {} )
  // throw an error if there is no next value before completed
  .defaultObservableIfEmpty(Observable.throw(new Error(...)))

Observable.pairs( {} )
  // use another observable if there is no next value before completed
  .defaultObservableIfEmpty(anotherObservable)
```

The implementation of `defaultObservableIfEmpty` should be like (provided by @Dorus in [gitter](https://gitter.im/Reactive-Extensions/RxJS)):

```js
function defaultObservableIfEmpty(default) {
  return this.publish(src_ => src_.merge(src_.isEmpty().filter(e => e).mergeMapTo(default)));
}

Rx.Observable.prototype.defaultObservableIfEmpty = defaultObservableIfEmpty;
```

**Comment by stvkoch** [comment]
+1

**Comment by kwonoj** [comment]
Closing on behalf of https://github.com/ReactiveX/rxjs/blob/master/doc/operator-creation.md#publish-your-operator-as-a-separate-library . We do recommend to create custom operator as separate module first before add it into core library/
