### ISSUE TITLE
Proposal: Create Observable and next method pair

### ISSUE THREAD

**Issue by mariusGundersen** [ReactiveX/rxjs#2241]
I might be doing something very wrong, but I often run into the issue of having to create a `next` and an `Observable` pair when integrating with other libraries. For example, when mapping a react event into an observable:

```js
<button onClick={event => /*push event into an observable here*/} />
```

This can be solved like this:
```js
let next = null;
const observable = new Rx.Observable(s => next = v => s.next(v));
```

which isn't exactly nice. What if there was a static method for creating this pair? For example:

```js
const {observable, next} = Rx.Observable.createPair();
```

**Comment by trxcllnt** [comment]
Recompose has a [`createEventHandler()`](https://github.com/acdlite/recompose/blob/master/docs/API.md#createeventhandler) method for this use-case

**Comment by staltz** [comment]
Yeah, and in general you're looking for a Subject if you want to `next` values into it, not an Observable.

**Comment by blesh** [comment]
I think @staltz is correct.

I think a _unicast_ observable that you could next into could be interesting, but probably not very useful. (That's still not what this issue is proposing, though, because you could only get a `next` at subscription time if it were unicast)

**Comment by kwonoj** [comment]
Closing as answered adequately.
