### ISSUE TITLE
Memory Leak with Queue Scheduler and Subject

### ISSUE THREAD

**Issue by MikeRyan52** [ReactiveX/rxjs#2244]
**RxJS version:** 5.0.2

**Code to reproduce:**
Observing a subject using the `queue` scheduler creates many `QueueAction`s that are never freed.

Plnkr demonstrating issue: https://plnkr.co/edit/BBkHlpIf6MiP2eOPdIlz

Minimal code to reproduce:
```ts
import 'rxjs/add/operator/observeOn';
import { interval } from 'rxjs/observable/interval';
import { BehaviorSubject } from 'rxjs/BehaviorSubject';
import { queue } from 'rxjs/scheduler/queue';

const source$ = new BehaviorSubject(0);

source$.observeOn(queue).subscribe();

interval(50).subscribe(source$);
```

Create two heap allocation snapshots about 20 seconds apart and use the comparison tools to see the allocation delta. Example:

![Heap Allocation Snapshot Example](http://i.imgur.com/Mh3q5Q1.png)

**Expected behavior:**
No memory leak of previous values.

**Actual behavior:**
Previous values are retained in `QueueAction`s

**Comment by kwonoj** [comment]
So the issue seems occurring on `observeOn` operator by holding observed notification's subscription. Please check https://github.com/ReactiveX/rxjs/pull/2245 for reference, local verification shows leaks are gone with given changes.

**Comment by MikeRyan52** [comment]
@kwonoj Pulled down the latest from your branch and I am still seeing a leak of `QueueAction`s. Also seeing a leak of instances of `ObserveOnContext`. All are being held by `ObserveOnSubscriber._subscriptions`

**Comment by kwonoj** [comment]
@MikeRyan52 can you share setup you've used to repro issue (maybe github repo)?

**Comment by MikeRyan52** [comment]
@kwonoj I created a demo repository here that reproduces the problem with both the latest published release of rxjs and your branch: https://github.com/MikeRyan52/rxjs-memory-leak

**Comment by blesh** [comment]
I see the problem right now and I'm working on a solution.

**Comment by blesh** [comment]
@MikeRyan52 try the PR #2248 ... it should solve your problem.

Thank you so much for reporting this one.

**Comment by blesh** [comment]
@MikeRyan52 the patch is published. 5.0.3

**Comment by JamesHenry** [comment]
Thanks @blesh and @MikeRyan52!

@blesh, just FYI the latest on npm appears to still be `5.0.2`

**Comment by blesh** [comment]
@jameshenry oops it looks like I published to Netflix's internal registry and not npm. Fixed.

**Comment by JamesHenry** [comment]
Thanks!
