### ISSUE TITLE
Why observable does not get subscribed

### ISSUE THREAD

**Issue by kostonstyle** [ReactiveX/rxjs#2253]
Hi all
I have following observable, that validate changes on the model.

The code snippet looks as follow:

  ```es6
const oSaveCancelStateOb = this.determineSaveCancelStateOb(oTableItemChanges, oSaveCancelStateModelOb);
  oSaveCancelStateOb.subscribe(function (oOb) {
    console.log("Subscribe 1");
  });

  oDelBtnOb
    .switchMapTo(oSaveCancelStateOb)
    .subscribe(function (oOb) {
      console.log("Subscribe 2");
    });
```
The implementation of `determineSaveCancelStateOb` looks as follow:

```es6
determineSaveCancelStateOb: function (oInspectionServiceOb, oSaveCancelStateModelOb) {
  return oInspectionServiceOb
    .map(function (bState) {
      return bState ? {bSave: true, bCancel: true} : {bSave: false, bCancel: false};
    })
    .switchMap(function (oState) {
      return oSaveCancelStateModelOb
        .map(function (oModel) {
          return {oModel: oModel, oState: oState};
        })
    });
},
```
The `oSaveCancelStateOb` verify, if somethings has changed on the model, it is a cold observable.

The second observable `oDelBtnOb` is a hot observable, it listen on the mouse button click.

My expectation is, when I clicked on the button, it should show me on the console:

```
Subscribe 1
Subscribe 2
```
But I've got only
`Subscribe 2`
Why the first observable does not get subscribed?

And take a look to the following code snippet:

```es6
//Create an observable that emits a value every second
const sample1$ = Rx.Observable.of(true);
sample1$.subscribe(val => console.log(val))
//Create an observable that emits every time document is clicked
const sample2$ = Rx.Observable.fromEvent(document, 'click');

sample2$.switchMapTo(sample1$).subscribe(val => console.log(val))
```
When I click on the document, I am expecting the true will output twice.

Thanks

**Comment by crunchie84** [comment]
This issue is also posted at http://stackoverflow.com/questions/41501354/why-observable-does-not-get-subscribed

**Comment by kostonstyle** [comment]
Yes I posted it. I think no one can answer the question, except rxjs team, that why I post it here.

Thanks

**Comment by kwonoj** [comment]
SO has accepted answer, closing.
