### ISSUE TITLE
Rx.Observable.catch(args) absent

### ISSUE THREAD

**Issue by crunchie84** [ReactiveX/rxjs#2255]
The static `Rx.Observable.catch()` method [present in Rxjs 4.x](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/catch.md) seems to be absent in RxJs 5.0.2

**RxJS version:**
5.0.2

**Code to reproduce:**
```
Rx.Observable.catch(
  Rx.Observable.throw(new Error()),
  Rx.Observable.of('only i will be emitted'),
  Rx.Observable.of('never subscribed to')
)
.take(1)
.subscribe(
 v => console.log(v), 
 err => console.log(err.message), 
 () => console.log('completed')
)
```

**Expected behavior:**
```
"only i will be emitted"
"completed"
```
**Actual behavior:**
```
"TypeError: Rx.Observable.catch is not a function"
```

**Comment by Dorus** [comment]
I don't think this operator is needed, it's trivial to write.

```Js
Rx.Observable.of(
  Rx.Observable.throw(new Error()),
  Rx.Observable.of('only i will be emitted'),
  Rx.Observable.of('never subscribed to')
).reduce((ob1, ob2) => ob.catch(() => ob2), Rx.Observable.throw(''))
.mergeAll()
```

**Comment by crunchie84** [comment]
This was not 100% trivial for me to write. Learned something today though! :+1: So it seems that this issue can be resolved in one of the following ways:

1) Document absent `catch()` overload in `MIGRATION.md` + point to how to do this yourself?
2) Implement missing overload

**Comment by Dorus** [comment]
Trivial to write, probably not trivial to come up with :)

**Comment by blesh** [comment]
More trivially than that, `Observable.catch(a, b, c)` is really just `a.catch(() => b).catch(() => c)`:

```js
Observable.throw(new Error())
.catch(() => Observable.of('only I will be emitted'))
.catch(() => Observable.of('never subscribed to'))
```

I hope that helps.

**Comment by ofabricio** [comment]
+1 for adding `Observable.catch()`

**Comment by kwonoj** [comment]
Closing as I believe it won't be added in core as it's achievable via existing opeartor chains.
