### ISSUE TITLE
Documentation missed for .finally() operator

### ISSUE THREAD

**Issue by fetis** [ReactiveX/rxjs#2256]
**RxJS version:**
5.x

**Code to reproduce:**
N/A
**Expected behavior:**
N/A
**Actual behavior:**
N/A
**Additional information:**

I've just found that there's no `finally` operator described as Observable method here http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html
But this method exists and successfully migrated from 4.x

**Comment by crunchie84** [comment]
Just verified that this method is indeed implemented but documentation is missing.

The source is located https://github.com/ReactiveX/rxjs/blob/master/src/operator/finally.ts
It is working as intended in RxJs `5.0.3` - https://jsbin.com/jugogiy/edit?html,js,console

**Comment by kwonoj** [comment]
It is known documentation is not fully migrated and missing, instead of having each individual issue I've created umbrella issue at #2656 to track it.
