### ISSUE TITLE
Timeout operator does not accept custom Error to throw

### ISSUE THREAD

**Issue by crunchie84** [ReactiveX/rxjs#2257]
The [documentation of rxjs5](http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#instance-method-timeout) states that you can still call `.timeout(100, new MyError(), scheduler)` but this seems not to be the case.

**RxJS version:**
5.0.2 (npm)

**Code to reproduce:**
```
Rx.Observable.of('foo')
  .delay(1000)
  .timeout(200, new Error('nope'), scheduler)
  .subscribe(null, err => console.log('err: ' + err.message));
```  
**Expected behavior:**
the console.log is executed using the custom error `Error` in this case

**Actual behavior:**
`timeout hit TypeError: this.scheduler.schedule is not a function`

**Additional information:**

**Comment by kwonoj** [comment]
Yes, it has been deprecated but document has not updated yet. (https://github.com/ReactiveX/rxjs/blob/master/CHANGELOG.md#features), due to interface is not clear enough brings confusions (https://github.com/ReactiveX/rxjs-core-notes/blob/master/2016-12/december-05.md).

**Comment by crunchie84** [comment]
@kwonoj ACK! Should this issue then not be kept open as a reminder to update the documentation?

**Comment by matthewwithanm** [comment]
For people who stumble on this later, you can use `.timeoutWith(2000, Observable.throw(new Error('delay exceeded')))` 😊
