### ISSUE TITLE
Show version of RxJs in documentation

### ISSUE THREAD

**Issue by crunchie84** [ReactiveX/rxjs#2258]
http://reactivex.io/rxjs/identifiers.html does not show the exact version of RxJs it has been generated upon. This confused me a few times when i was checking between `MIGRATION.md`, the documentation and the sourcecode.

**Comment by kwonoj** [comment]
related with https://github.com/ReactiveX/rxjs/issues/2369.

**Comment by benlesh** [comment]
I believe the docs team is tracking this elsewhere.
