### ISSUE TITLE
Support question - Alternative to reduce

### ISSUE THREAD

**Issue by ORESoftware** [ReactiveX/rxjs#2263]
I asked this question on SO and didn't get any outstanding answers. Say we have this code:

```js
const Rx = require('rxjs');

const obs = Rx.Observable.interval(100)
    .take(5)
    .map(function(v){
        console.log(v);
        return v;
    })
    .reduce(function (prev, curr) {
        return prev.concat(curr);
    },[])
    .last(function (results) {
        console.log('results => ', results);
        return results;
    });


obs.subscribe();
```

this does what I want it to do, and logs out this info:

```
0
1
2
3
4
results =>  [ 0, 1, 2, 3, 4 ]
```

However, what I am wondering is: is there a way to do the same thing _without_ reduce?

What I am thinking is - there must be a way to merge observables themselves, and then unwrap their combined results? (Instead of unwrapping them all first, and manually combining their results with reduce). If the question is not clear, please lmk, thanks!

**Comment by ORESoftware** [comment]
Ok so I wrote this custom method on the prototype like so. It's designed to only continue on, if the onCompleted callback is fired, and to buffer all results that arrive before onComplete. This serves a simpler option than reduce()

```js
const Rx = require('rxjs');

const proto = Rx.Observable.prototype;

proto.whenCompleted = function () {

    const source = this;

    return Rx.Observable.create(sub => {

        const ret = [];

        return source.subscribe(
            function (v) {
                ret.push(v);
            },
            function (e) {
                sub.error(e);
            },
            function () {
                sub.next(ret);
            }
        )

    });

};

```

this is so simple and does exactly what I want, I would be willing to bet other people would want it and somehow I doubt that this functionality wouldn't already be in RxJS core. Anyone? thanks

**Comment by trxcllnt** [comment]
@ORESoftware if you want all the values of an Observable sequence emitted as an Array when the sequence completes, you can use `toArray()`. Indeed, it seems the custom operator you've come up with is the [`toArray` operator](https://github.com/ReactiveX/rxjs/blob/master/src/operator/toArray.ts).

If you have an Observable of Observables, want to subscribe to all of them, aggregate the last values from each, then onNext a sorted list of the final values, you can use `takeLast` and `combineAll`. We should have a prototype form of `forkJoin` available, so the fact we don't seems to be an oversight. Here's an example of using `takeLast` and `combineAll` to get a similar result:

```es6
// some Observable of Observables
Observable.of(
  Observable.range(0, 10),
  Observable.range(5, 15)
)
// `takeLast(1)` instead of `last()` won't throw an error if an inner sequence is empty
.map(obs => obs.takeLast(1))
// combine all the inner sequences onComplete in the order they were emitted
.combineAll()
.subscribe(values => console.log(values))
```

In general, Rx includes a rich set of Observable flattening operators, that is, operators which combine sequences of inner Observables. The most commonly used are merge, concat, switch, exhaust, expand, combine, and zip.

**Comment by kwonoj** [comment]
Closing as it's answered.
