### ISSUE TITLE
feature request - reduce() should work without an accumulator

### ISSUE THREAD

**Issue by ORESoftware** [ReactiveX/rxjs#2265]
say I have this code:

```js

const Rx = require('rxjs');

var i = 0;

const obs = Rx.Observable.interval(100)
    .map(() => i++)
    .flatMap(function(val){
        return Rx.Observable.create(obs => {
            obs.next(val)
        });
    })
    .take(10)
    .reduce(function (prev, curr) {
        return prev.concat(curr);
    }, [])
    .map(function (results) {
        console.log('all done = > ', results);
        return true;
    });


obs.subscribe();
```

in my uneducated naive opinion, the following should do the same by default

```js

const Rx = require('rxjs');

var i = 0;

const obs = Rx.Observable.interval(100)
    .map(() => i++)
    .flatMap(function(val){
        return Rx.Observable.create(obs => {
            obs.next(val)
        });
    })
    .take(10)
    .reduce()   /// <<<<<<<<<<< don't need to pass anything here
    .map(function (results) {
        console.log('all done = > ', results);
        return true;
    });


obs.subscribe();
```

would this make any sense or not?

I really think we should be able to call concat on whatever comes back, whether it's plain values or observables or whatever

**Comment by trxcllnt** [comment]
What would reduce without an accumulator do? You can use `toArray()` if you want to reduce the results to a list.

**Comment by ORESoftware** [comment]
I guess reduce without an accumulator would just be the same as toArray() given my knowledge of toArray()

*but* reduce with a series of Observables would yield one master Observable, like so:

```js
const Rx = require('rxjs');

var i = 0;

const obs = Rx.Observable.interval(100)
    .map(() => i++)
    .map(function(val){
        return Rx.Observable.create(obs => {
            obs.next(val)
        });
    })
    .take(10)
    .reduce(function (prev, curr) {
        return prev.concat(curr);
    })
    .map(function (results) {
        console.log('all done = > ', results);
        return true;
    });


obs.subscribe();

```

**Comment by trxcllnt** [comment]
We can't really change the [definition of reduce](https://hackage.haskell.org/package/base-4.8.2.0/docs/Data-Foldable.html#t:Foldable), but you can use concatMap to concatenate inner Observable sequences and ensure order is preserved.

**Comment by blesh** [comment]
Sorry, @ORESoftware, I tend to agree with @trxcllnt here. I don't think we can change the behavior of reduce as you've requested. `toArray` and `concatAll` will give you the other behaviors you're requesting.

**Comment by ORESoftware** [comment]
sure no problem will checkout toArray and concatAll - if they do give the behavior I am looking for, that's all I need thanks
