### ISSUE TITLE
bufferCount

### ISSUE THREAD

**Issue by buctwbzs** [ReactiveX/rxjs#2267]
**RxJS version:**
5.0
**Code to reproduce:**
```
var clicks = Rx.Observable.fromEvent(document, 'click');
var buffered = clicks.bufferCount(3,4);
buffered.subscribe(function(x){console.log(x)} );
```
**Expected behavior:**

**Actual behavior:**
step1、click 3 times then  emit a array that contains 3 click event.
step2、click 4 times  then emit a array that contains 3click ecent.
....
it means when  set  arg2>arg1,i will miss somthing. in this case,i missed the 4th/8th/12th/etc... click 。i have proved it by check event's coordinates。
i think let 7th/11th/etc... click missed is better than  the 4th/8th/12th...etc click 。
**Additional information:**
when bufferTime's  arg1 >arg2 has the similar problem。besides,the docs in  http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#instance-method-bufferTime says:
![image](https://cloud.githubusercontent.com/assets/19690435/21750256/178e1cfe-d5ea-11e6-8100-f9e3cf09a653.png)     in'(emits and resets)',it says the interval of emit is determined by  bufferTimeSpan,infact,it emit every bufferCreationInterval

**Comment by buctwbzs** [comment]
the word 'check' after 'by'--->checking.thanks.

**Comment by blesh** [comment]
@buctwbzs what behavior were you expecting?

**Comment by kwonoj** [comment]
Seems this issue been inactive without having further detail, let me close issue for now. Please reopen freely if needed.
