### ISSUE TITLE
Unnecessary README.md special case instructions for TypeScript

### ISSUE THREAD

**Issue by billba** [ReactiveX/rxjs#2269]
The current instructions direct TypeScript users to install using `npm install @reactivex/rxjs`.

However it works just fine to do it the simple way: `npm install rxjs` followed by e.g. `import { Observable } from 'rxjs';`

**Comment by kwonoj** [comment]
so `@reactive/rxjs` is not specifically for typescript, `rxjs` for CJS while `@reactive/rxjs` does have all builds includeded. Probably need to update document bit to have better clarity.

**Comment by DomiR** [comment]
@billba how does your tsconfig look like? 

I can't seem to get it working with mine, as it always says it cannot find the module: 
```
{
	"compilerOptions": {
		"target": "es6",
		"allowJs": true,
		"jsx": "react",
		"outDir": "artifacts",
		"rootDir": "src",
		"inlineSourceMap": true,
		"noImplicitAny": false,
		"experimentalDecorators": true,
		"forceConsistentCasingInFileNames": true,
		"locale": "en",
		"pretty": true,
		"noFallthroughCasesInSwitch": false,
		"noImplicitReturns": false,
		"preserveConstEnums": true,
		"noEmitOnError": true,
		"stripInternal": true,
		"skipLibCheck": true
	},
	"exclude": [],
	"include": [
		"src/**/*.ts",
		"src/**/*.tsx",
		"global.d.ts"
	]
}
```

What would be the correct way to import rxjs for TypeScript users?

**Comment by DomiR** [comment]
It was brought to my attention, that `"moduleResolution": "node"` does the trick.
