### ISSUE TITLE
Major problem with this lib (?) - takeUntil will supercede chained calls, which means critical code may be skipped

### ISSUE THREAD

**Issue by ORESoftware** [ReactiveX/rxjs#2273]
**RxJS version:** RxJS 5.0.2

**Code to reproduce:**

I wrote this test, to test my suspicion that takeUntil will supercede a pre-registered chain of calls

the idea is that if we do something like this:

```js
Rx.Observable.interval(100)
 .criticalCall1()
 .criticalCall2()
 .criticalCall3()
 .takeUntil(someObservableEvent());
```

what might happen is that `someObservableEvent` will fire, and this chain will break, such that `criticalCall1` may fire, but `criticalCall2` and `criticalCall3` will not. This is especially problematic if we know that we need these second two calls to run, if `criticalCall1` runs...

Here is a test that demonstrates the problem:

```js
'use strict';


const Rx = require('rxjs');

let countIn = 0;
let countOut = 0;

function makeTimerIn() {
    return Rx.Observable.timer(50)
        .do(function () {
            countIn++;
            console.log(' => Count in => ', countIn)
        })
}


function makeTimerOut() {
    return Rx.Observable.timer(50)
        .do(function () {
            countOut++;
            console.log(' => Count out => ', countOut);
        })
}


function makeTimerUntil() {
    const r = Math.ceil(Math.random() * 1500);
    return Rx.Observable.timer(r);
}


Rx.Observable.interval(30)
    .flatMap(() => {
        return makeTimerIn();
    })
    .flatMap(() => {
        return makeTimerOut();
    })
    .takeUntil(makeTimerUntil())
    .subscribe(function (v) {
        console.log('v => ', v);
    }, function (e) {
        console.error(' => error => ', e);
    }, function () {
        console.log(' final in => ', countIn);
        console.log(' final out => ', countOut);
    });
```

**Expected behavior:**

We would expect (or desire) that `countIn` would be equal to `countOut` when `onComplete` is fired in the single subscriber. Furthremore, with takeUntil, we'd expect to see countIn and countOut be the last things to be logged to the console.

**Actual behavior:**

Actual behavor is that we get something like this logged out:

```
=> final in =>  14
=> final out =>  12
```

2 problems with that

Problem 1:
Everytime I have run this script, when it completes, `countIn` and `countOut` have different integer values which means that they are not running 1 for 1. If this were a Promise chain, then you should be guaranteed that all your subsequent calls would at least be invoked if there were no errors; but with RxJS5 it looks like we are "jumping out of the chain" before the chain completes, which is very unexpected and now takes some extra effort to make sure things do the right thing.

Problem 2: 
We see that even with the error above, that "final in => " and "final out =>" are not the last items to be logged. So if RxJS5 wants to play that game, then why can't RxJS5 just finish the job and complete the chain before firing onComplete in the subscriber?

**Additional information:**

I am simply hoping that I am wrong and/or there is a way around this behavior because it makes things pretty arbitrary and unpredictable this way.

**Comment by david-driscoll** [comment]
The behavior of `takeUntil` is such that it will simply unsubscribe from any active tasks, until it has taken all the values it's expecting.  If there are any other operations in flight they will be unsubscribed from.  It's up to the operator what to do when the subscription is unsubscribed.

In the case of `timer` that operator just unschedules it self, so you get this behavior.

If you have the ability to rearranging things, such that you can do your processing after...  The following code does work as expected.

```typescript
Rx.Observable.interval(30)
    .flatMap(() => {
        return makeTimerIn();
    })
    .takeUntil(makeTimerUntil())
    .flatMap(() => {
        return makeTimerOut();
    })
    .subscribe(function (v) {
        console.log('v => ', v);
    }, function (e) {
        console.error(' => error => ', e);
    }, function () {
        console.log(' final in => ', countIn);
        console.log(' final out => ', countOut);
    });
```

That of course doesn't solve the case where you are return an observable that does a take until.

In that event, once you emit the value, you can queue up your tasks, in such a way that they won't be unsubscribed from, and they will complete.  It just might not land at completion of the takeUntil operator.

```typescript
Rx.Observable.interval(30)
    .flatMap(() => {
        return makeTimerIn()
    .flatMap(() => {
        return makeTimerOut().toPromise();
    });
    })
    .takeUntil(makeTimerUntil())
    .subscribe(function (v) {
        console.log('v => ', v);
    }, function (e) {
        console.error(' => error => ', e);
    }, function () {
        console.log(' final in => ', countIn);
        console.log(' final out => ', countOut);
  setTimeout(() => {
        console.log(' after final in => ', countIn);
        console.log(' after final out => ', countOut);
  }, 60);
    });
```

**Comment by blesh** [comment]
Your `takeUntil` is simply in the wrong spot. Move it *before* your critical actions.

```js
Rx.Observable.interval(30)
    .takeUntil(makeTimerUntil()) //<--- here.
    .flatMap(() => {
        return makeTimerIn();
    })
    .flatMap(() => {
        return makeTimerOut();
    })
    .subscribe(function (v) {
        console.log('v => ', v);
    }, function (e) {
        console.error(' => error => ', e);
    }, function () {
        console.log(' final in => ', countIn);
        console.log(' final out => ', countOut);
    });
```

**Comment by ORESoftware** [comment]
thanks all, @blesh I tried that and I wasn't getting the behavior I was looking for, I will try it again

**Comment by blesh** [comment]
@ORESoftware well, if you need additional help, let us know. I presume what you're looking for in your example is to get `countIn` and `countOut` to be the same value at the end. The code I provided above does do that.  Think of this this way:

```js
someTriggers$
.takeUntil(youWantToStopTriggering$)
.everything()
.here()
.willBe()
.processed()
.forEvery()
.triggerThat()
.makesItPast()
.theTakeUntil()
```

**Comment by ORESoftware** [comment]
thanks @blesh in my case simply putting the `takeUntil() `at the top of the chain causes another problem for me - basically that the sequence never fires an `onComplete` event in any subscriber. So I decided to try putting it at the bottom. Putting the call at the bottom of the chain means the chain *will* eventually fire an onComplete(), but then that introduces the problem for which I opened this issue.

Now I have one takeUntil() at the top and an identical call at the bottom :)

this however, is problem incorrect, because the problem for which I opened this question should still exist.

**Comment by ORESoftware** [comment]
If I could share my project with you, that would be really neat, this is a classic problem case, let me know and I will share it; I knew RxJS would be hard to learn and it has proven so :)

**Comment by trxcllnt** [comment]
@ORESoftware if you can come up with an example on http://codepen.io/ (you can add Rx as a JS dependency by clicking Settings, then linking to https://cdnjs.cloudflare.com/ajax/libs/rxjs/5.0.3/Rx.min.js), we'd be happy to review.

**Comment by ORESoftware** [comment]
thanks, I think I figured it out, one of the many observables in the chain wasn't sending a complete() call, so once I changed that and put takeUntil() only at the top it seems to work; but if I am wrong I might enlist your help via codepen, thanks again

**Comment by blesh** [comment]
> one of the many observables in the chain wasn't sending a complete() 

I figured as much from your other comment.

**Comment by ORESoftware** [comment]
yeah thanks anyway, I don't think I would have figured it out without this conversation.

a "common pitfalls" write-up might include this problem
