### ISSUE TITLE
Rx.Observable.merge should return same type regardless of input

### ISSUE THREAD

**Issue by ORESoftware** [ReactiveX/rxjs#2274]
https://github.com/btroncone/learn-rxjs/issues/26#issuecomment-272173571

Mr. btroncone  and I are both curious and concerned about the API for `Rx.Observable.merge` -

it seems to return different types based off the input, which is at the very least confusing.

You can see the difference when comparing `Rx.Observable.of` with `Rx.Observable.merge`, see code below.

**RxJS version:**

5.0.2

**Code to reproduce:**

```js
const Rx = require('rxjs');

var example = Rx.Observable.of(
    Rx.Observable.timer(1),
    Rx.Observable.timer(1),
    Rx.Observable.timer(1)
);

console.log(example.constructor.name);

var example = Rx.Observable.of([
        Rx.Observable.timer(1),
        Rx.Observable.timer(1),
        Rx.Observable.timer(1)
    ]);

console.log(example.constructor.name);


var example = Rx.Observable.merge(
    Rx.Observable.timer(1),
    Rx.Observable.timer(1),
    Rx.Observable.timer(1)
);

console.log(example.constructor.name);

var example = Rx.Observable.merge([
    Rx.Observable.timer(1),
    Rx.Observable.timer(1),
    Rx.Observable.timer(1)
]);

console.log(example.constructor.name);
```

The output is:

```
ArrayObservable
ScalarObservable
Observable
Array
```

**Expected behavior:**

```
ArrayObservable
ScalarObservable
Observable
SomeObservable  // <<<

```
**Actual behavior:**

```
ArrayObservable
ScalarObservable
Observable
Array  // <<< an array?

```

**Additional information:**

Maybe there is a good reason for this, but it seem bad on the face of things

**Comment by paulpdaniels** [comment]
`merge` does not accept an `Array`. See the [declarations](https://github.com/ReactiveX/rxjs/blob/master/src/operator/merge.ts#L75-L88).

If you pass it a single array argument you would hit [this conditional](https://github.com/ReactiveX/rxjs/blob/master/src/operator/merge.ts#L163-L165), which would just return the `Array` back casted to an `Observable`.

If you want to use it with an array you need to destructure it, the following should work:


```typescript

var example = Rx.Observable.merge(...[
    Rx.Observable.timer(1),
    Rx.Observable.timer(1),
    Rx.Observable.timer(1)
]);

```

**Comment by ORESoftware** [comment]
ok so here is the thing:

if it doesn't currently accept an array  (which seems clear)  - it should accept an array, because it obviously should given the arguments it accepts; but if the API really really can't accept an array, then it should throw an error IMO.

if it does accept an array, then please make the return value consistent, in this case, an Observable 

I like TypeScript and am using it to interface with RxJS in some case, but in other cases I am interfacing with RxJS with plain JS and nothing is really stopping me from passing an array to the merge method etc. 

It would help if:

(a) it allowed for arrays, (which it really should)
or
(b) throw an error if an array is passed

my 2 cents

**Comment by kwonoj** [comment]
I am considering this issue as same as #2294 and #2144, about runtime validation and soundness, linking each.

**Comment by kwonoj** [comment]
I'll use #2153 as umbrella issue to discuss runtime validations.
