### ISSUE TITLE
Reduce() overload invoked with index=undefined

### ISSUE THREAD

**Issue by crunchie84** [ReactiveX/rxjs#2290]
**RxJS version:**
5.0.3
**Code to reproduce:**
```
Rx.Observable.from([1,2,3,4,5])
  .reduce((acc,curr,index) => `${acc}\ncurr:${curr}@index(${index})`, '')
  .subscribe(console.log);
```

**Expected behavior:**

```
curr:1@index(0)
curr:2@index(1)
curr:3@index(2)
curr:4@index(3)
curr:5@index(4)"
```
**Actual behavior:**

```
curr:1@index(undefined)
curr:2@index(undefined)
curr:3@index(undefined)
curr:4@index(undefined)
curr:5@index(undefined)"
```

**Additional information:**

The `seed` argument does not matter, results are the same

**Comment by crunchie84** [comment]
Note; the index argument is[ not documented in the documentation ](http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#instance-method-reduce)of RxJS5 ([but was in RxJs4](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/reduce.md)).

The code seems to suggest the overload should work: https://github.com/ReactiveX/rxjs/blob/master/src/operator/reduce.ts#L6-L8

**Comment by kwonoj** [comment]
Yes, there's mismatch between signature to implementation. Need to be update either case.
