### ISSUE TITLE
Proposal: Type inference for `pluck` function (Typescript)

### ISSUE THREAD

**Issue by ErikCupal** [ReactiveX/rxjs#2295]
## Example

Let's create `user` object and Observable from the object

```typescript
const user = {
    name: "Johny Little",
    age: 32,
    address: {
        street: "Lonely Road 32",
        city: "Fantaspolis",
        country: "Fantasy land"
    },
    daddy: {
        name: "Luke Little",
        age: 58,
        address: {
            street: "High Road 5",
            city: "Pikopolis",
            country: "Fantasy land"
        }
    }
}

const userObservable = Observable.of(user)
```

Now let's create a new Observable by plucking `age` from `userObservable `:

```typescript
// Infered type: Observable<{}>
// Actual type: Observable<number>
const userAgeObservable = userObservable.pluck("age")
```

As you can see, there is no type inference. I think it would be great if the type was automatically inferred.

```typescript
// Inferred type: Observable<number>
const userAgeObservable = userObservable.pluck("age")
```

It would be even better if we could infer the type from nested properties:

```typescript
// Inferred type: Observable<string>
const daddiesCityObservable = userObservable.pluck("daddy", "address", "street")
```

## Implementation

The current type declaration looks like this:

```typescript
export declare function pluck<T, R>(this: Observable<T>, ...properties: string[]): Observable<R>;
```

We can add overload declaration to get type inference if call pluck with one argument (e.g. `pluck("age")`):

```typescript
export declare function pluck<T, K1 extends keyof T>(this: Observable<T>, property: K1): Observable<T[K1]>;
export declare function pluck<T, R>(this: Observable<T>, ...properties: string[]): Observable<R>;

// userObservable.pluck("age") <- this now works - inferred type Observable<string>
// userObservable.pluck("daddy", "address", "street") <- this still doesn't - inferred type Observable<{}>
```

We can go further and add more:

```typescript
// 2 more overloads

export declare function pluck<T, K1 extends keyof T>(this: Observable<T>, property: K1): Observable<T[K1]>;
export declare function pluck<
    T,
    K1 extends keyof T,
    K2 extends keyof T[K1]
    >(this: Observable<T>, property1: K1, property2: K2): Observable<T[K1][K2]>;
export declare function pluck<
    T,
    K1 extends keyof T,
    K2 extends keyof T[K1],
    K3 extends keyof T[K1][K2]
    >(this: Observable<T>, property1: K1, property2: K2, property3: K3): Observable<T[K1][K2][K3]>;
export declare function pluck<T, R>(this: Observable<T>, ...properties: string[]): Observable<R>;

// userObservable.pluck("daddy", "address", "street") <- it works - inferred type Observable<string>
```

It looks pretty nasty, but works as expected. If you better way to do this in Typescript, please comment :).

In most cases we don't need to pluck property nested more than 5 levels deep. Therefore, I think it's sufficient to have 5 - 10 overloads, then it falls into the default one.

What do you think :)? If you think it's a good idea I can make PR.
___________________________________________________

**RxJS version:** 5.0.3

**Editor:** VS Code

**Expected behavior:** Type inference

**Actual behavior:** No type inference (always returns Observable<{}>)

**Comment by kwonoj** [comment]
Yeah, probably we're going similar way by @david-driscoll suggested, but `keyof` is blocked by ts 2.1. It is currently tracked  at https://github.com/ReactiveX/rxjs/issues/2179

**Comment by david-driscoll** [comment]
`keyof` is definitely the way to go, but we're not able to support it yet, as it's a breaking to anyone using TS < 2.1.

**Comment by ErikCupal** [comment]
Ok, shame it can't be supported now.

**Comment by kwonoj** [comment]
@ErikCupal , I've updated original to reflect issue more clearly, and closing this issue to track further effort in single issue. Appreciate for writing up actual proposal, we'd like to have it asap with TS 2.1.

**Comment by ErikCupal** [comment]
Ok, fine :)

**Comment by sandangel** [comment]
Hello everyone, with new Lettable operator in rxjs 5.5, I think we can improve type inference for pluck.
Here is my implementation:
```ts
const myPluck = <T, M extends T[keyof T] = T[keyof T]>(prop: keyof T) => (source: Observable<T>) =>
  new Observable<M>(obs => {
    return source.pipe(pluck<T, M>(prop)).subscribe({
      next(val) {
        obs.next(val);
      },
      error(err) {
        obs.error(err);
      },
      complete() {
        obs.complete();
      }
    });
  });
```

I think user don't often pluck many nested prop, if they want to, just add another pluck in pipe. So instead of give prop parameter type string[], we can constrain it with generic type as describe above, add a few overload, 3 perhaps, And user can now take advantage of fantastic type checking.

for example: 
```ts
 data = this.route.data.pipe(myPluck<{messages: Mail[]}>('messages')); 
```
