### ISSUE TITLE
Template for creating new operators

### ISSUE THREAD

**Issue by mattpodwysocki** [ReactiveX/rxjs#2299]
I would like to see some sort of RFC process for adding new operators to Rx itself.  Currently, there is no defined standard for acceptance criteria for what is included and not included in the library itself.

Taking some hints from the [Rust RFC Process](https://github.com/rust-lang/rfcs), we can glean a bit on how others handle substantial changes to the language/runtime/etc.  Changes such as these are not to be taken lightly, as Rx can suffer from an API bloat as we cover a wide array of use cases already.  If a new solution can simply be made from existing operators, that should be preferred, over writing a new core operator.  Conversely, it could also remain in user land for the users who really need said operator to import it as needed from another repository.

Here is what I think the minimum bar should be in order to add a new operator to Rx:

- A thorough explanation of the operator and its use cases.  This also includes error handling, completion, early unsubscription, and infinite case semantics just as we define in our unit tests.

- An explanation of how current operators cannot accomplish this task, or if they can, but performance is not ideal.

- Complete documentation including marble diagrams for further discussion

From there, the core team should enter discussions on whether to proceed or not.

**Comment by staltz** [comment]
> Currently, there is no defined standard for acceptance criteria for what is included and not included in the library itself.

There is something: https://raw.githubusercontent.com/ReactiveX/rxjs/master/.github/PULL_REQUEST_TEMPLATE.md

> If a new solution can simply be made from existing operators, that should be preferred, over writing a new core operator. 

Complicated to follow this rule, since we can do `.mergeMap(x => Observable.of(f(x)))` instead of `map(f)`. Should we drop map?

> - A thorough explanation of the operator and its use cases. This also includes error handling, completion, early unsubscription, and infinite case semantics just as we define in our unit tests.
> - An explanation of how current operators cannot accomplish this task, or if they can, but performance is not ideal.
> - Complete documentation including marble diagrams for further discussion

Agreed a lot.

**Comment by mattpodwysocki** [comment]
@staltz 

> There is something: https://raw.githubusercontent.com/ReactiveX/rxjs/master/.github/PULL_REQUEST_TEMPLATE.md

But that's already for a pull request, and this discussion should happen before a pull request even happens, because we don't want to waste anyone's time in having them implement the full operator without a chance of it being accepted.

> Complicated to follow this rule, since we can do .mergeMap(x => Observable.of(f(x))) instead of map(f). Should we drop map?

No, because as I stated, if performance is not ideal, then it should be considered.

**Comment by benlesh** [comment]
I know we talked about doing something like this... but I think with the new pipe operators people can roll their own so trivially, we probably don't need this. Also, there's been very, very few new operators purposed.

I'm going to close this as stale, feel free to reopen.
