### ISSUE TITLE
rxjs5 @types => https://www.npmjs.com/package/@types/rx is for v4.x

### ISSUE THREAD

**Issue by ORESoftware** [ReactiveX/rxjs#2303]
Hi all, sorry if this is a duplication question

I don't see @types/rxjs or @types/rxjs5 - is that because this library is built with TypeScript, and therefore we don't need a separate d.ts for RxJS5?

It looks like https://www.npmjs.com/package/@types/rx is for Rx v4.x

please advise, thanks!

**Comment by staltz** [comment]
Yes, you don't need a separate .d.ts, it's already defined once you npm install this. https://github.com/ReactiveX/rxjs/blob/master/package.json#L202

This issue can be closed.

**Comment by ORESoftware** [comment]
@staltz  thanks for the info

**Comment by penguin020** [comment]
The typings, as defined in the rxjs package, do not seem to be usefull for projects not using package management (i.e. using global).

I am doing some simple experiments with rxjs and TypeScript.

I am not familiar enough with the module systems to work that all out right now, and that is not my goal at the moment.  I want to reduce my unknowns so I am dealing just with rxjs!

Therefore, I am including rxjs5 via a script tag in my HTML:

`<script  src="node_modules/@reactivex/rxjs/dist/global/Rx.js"></script>`

and I would like to use typings via my `/node_modules/@types` directory, as @ORESoftware mentioned (e.g.  https://www.npmjs.com/package/@types/rx).

I tried copying the typings from the `/node_modules/@reactivex/rxjs/dist/typings` directory into my `/node_modules/@types` directory, but this did not work, as I suspected.

Would you concider outputing an @types directory to `node_modules/@reactivex/rxjs/dist/global/`?

**Comment by ivoshabarkov** [comment]
I have the same problem.
I'm using AngularJS with typescript and I don't have a module loader. All other typings I use are global and don't need to be imported. Could you suggest how to use rxjs with typescript without the need to use modules?
