### ISSUE TITLE
Documentation not mobile friendly

### ISSUE THREAD

**Issue by crunchie84** [ReactiveX/rxjs#2307]
The documentation at http://reactivex.com/rxjs is not easy to use on a mobile due to the frameset and one big page with anchor tags instead of page per operator.

**Comment by jayphelps** [comment]
Good to know. We'll definitely keep it in mind, but to be transparent, it's unlikely we'll be able to make it mobile-friendly soon. Unless, of course, someone from the community steps in.

**Comment by staltz** [comment]
Yeah this is more of an issue about ESDoc, which generates the page for us.

**Comment by blesh** [comment]
> Unless, of course, someone from the community steps in.

🙏

**Comment by Podlas29** [comment]
https://github.com/esdoc/esdoc/pull/379 there are already prs open for making doc layout responsive.

**Comment by kwonoj** [comment]
Let me close this issue via upstream issues.
