### ISSUE TITLE
Webstorm + RxJS

### ISSUE THREAD

**Issue by ORESoftware** [ReactiveX/rxjs#2311]
Hey all

Looking the docs, I am not clear on what the actually difference is between:

`const Rx = require('rxjs');`

and

`const Rx = require('rxjs/Rx');`

it turns out that Webstorm complains when I use the former, but the latter is all good.

Which is correct? Any idea why Webstorm would complain about the former? The former works, and my code runs fine, but Webstorm says "module is not installed" when I use` require('rxjs') `but does not complain when I use `require('rxjs/Rx')`;

**Comment by trxcllnt** [comment]
@ORESoftware I'm not a Webstorm user, but it might be related to the _Rx has no default export_ issue https://github.com/ReactiveX/rxjs/issues/2085

**Comment by kwonoj** [comment]
I also agree it might be related to @trxcllnt related with default export behavior, so for now closing as dupe. If you find it's not related, please feel freely reopen issue as needed. I don't use webstorm as well so I can't say for sure why it behaves on specific editor, but seems worth to ask Jetbrain's support to get clarification why it doesn't work with non-default-export libraries.

**Comment by ORESoftware** [comment]
for sure thank you
