### ISSUE TITLE
Observable constructor shouldn't give people a Subscriber<T> type.

### ISSUE THREAD

**Issue by benlesh** [ReactiveX/rxjs#2314]
`Subscriber<T>` is really an implementation detail of this library. While I don't mind "power users" knowing it's there, I really don't recommend the everyday user use the `Subscriber<T>`'s non-Observer<T> APIs.

We should be giving people an Observer<T> type.  Unfortunately at this point, it may be a breaking change and not a "fix"... even though it's really a "fix". It's not a particularly nasty one though, since people can still cast around it.

Upcoming changes to scheduling might break people that are using Subscriber's non-Observer APIs more than others who have stayed on the beaten path.

**Comment by blesh** [comment]
Related #2196

**Comment by kwonoj** [comment]
Related note, I think there are additional few places we're exposing implementation having additional details instead of interfaces. If we're going to make this change for next breaking changes, worth to visit possible cases and introduce at once.
