### ISSUE TITLE
`just`, `value`, and `return` vs `of`

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#232]
In the name of reducing the API surface area. I'd like to remove `just`, `value`, and `return` (I think we already removed `just`) in favor of using `of`. 

In order to make of more comparable to `value` or `return`, we could return a `ScalarObservable` if `of` is just one value.

**Comment by mattpodwysocki** [comment]
Getting rid of `return`/`just` doesn't make sense from a perf perspective at least in my mind because you're talking about a recursive scheduling versus a single onNext/onCompleted.

**Comment by blesh** [comment]
@mattpodwysocki .. you're correct, but what I was going to do is simply check `arguments.length === 1` and return an `ScalarObservable`, which is exactly what you'd want.

**Comment by blesh** [comment]
The performance tests show no measurable difference between `Observable.of()` checking argument length and returning a scalar, vs `Observable.return`, `value` or `just`.

**Comment by blesh** [comment]
In fact, I'd wager we can remove `fromPromise` and `fromArray` and just use `from`, based on this same sort of premise.
