### ISSUE TITLE
Proposal: Missing some()/any()

### ISSUE THREAD

**Issue by paulpdaniels** [ReactiveX/rxjs#2321]
We appear to be missing the `some()` operator that was present in RxJS 4. I don't think it is a core operator though I did come across an issue in our team's code base where it would have been useful.

I propose adding it if only for symmetry (since we have `every()`). Creating it seems to be possible in a couple ways but it is somewhat goofy IMO:

```typescript

source.first(predicate).catch(() => Observable.empty());
source.skipWhile(value => !predicate(value)).take(1)
source.flatMap(value => predicate(value) ? Observable.of(value) : Observable.empty()).take(1);

```

**Comment by jayphelps** [comment]
Hey @paulpdaniels this was discussed in #2051 where there's backstory and status (which hasn't changed). Let's follow the discussion there. 👍
