### ISSUE TITLE
Documentation from contributor days

### ISSUE THREAD

**Issue by jkup** [ReactiveX/rxjs#2325]
At RxJS contributor days we talked about additions we could make to the documentation / github readme to help people understand RxJS. Here are the suggestions we came up with:

- [ ] Add tiny use case examples to the github README (maybe an event handler and API call with retry logic)
- [ ] Move the /docs folder out to a docs branch so github users can't click on broken links
- [ ] Add a link to http://reactivex.io/rxjs/ on the README
- [ ] Find and fill in missing documentation for operators
- [ ] Add a glossary of RxJS specific terms (Observable, Operator, Scheduler, etc)

**Comment by Podlas29** [comment]
I made a pr where I make docs for certain operator (bindCallback) much more in depth, compared it to other similar operators and added more examples with different ways you can use it.

I was planning to go over every operator (as a challenge to learn rx.js as well as possible) and do the same in each doc.

Please let me know if such effort would be in line with what you had in mind.

**Comment by blesh** [comment]
Thank you for adding this, @jkup!

**Comment by benlesh** [comment]
So, I know we're all busy, but I want to ping you again. @jkup, have you messed with this at all. @Yonet, are you still interested in this? I'm not sure who else was involved in the discussion.

**Comment by jkup** [comment]
@benlesh Sorry I got distracted! I haven't worked on this at all. It might be cool to break some of these out into separate issues so people can grab them if they want? Also I think some of the items (like adding a glossary) are a bit intimidating since I don't know the lib as well and don't want to misspeak.

**Comment by ladyleet** [comment]
- companies that use RxJS
- how tos
- fix the import stuff
- codelinks link to lines in github

**Comment by Yonet** [comment]
@benlesh yes I am interested. We have not come to a conclusion to how to display the examples. Should I just follow @mpodlasin's pull request as an example?
@jkup it is a great idea to separate into different issues.

**Comment by benlesh** [comment]
@ladyleet we should make sure the docs team knows about this issue as well.

**Comment by ladyleet** [comment]
@benlesh which part? this?  

Add tiny use case examples to the github README (maybe an event handler and API call with retry logic)
  Move the /docs folder out to a docs branch so github users can't click on broken links
  Add a link to http://reactivex.io/rxjs/ on the README
  Find and fill in missing documentation for operators
  Add a glossary of RxJS specific terms (Observable, Operator, Scheduler, etc)

**Comment by benlesh** [comment]
FINALLY working on a better guide here: #5592
