### ISSUE TITLE
would be nice to have a less backward idiomatic use of startWith

### ISSUE THREAD

**Issue by machty** [ReactiveX/RxJS#233]
Because `startWith` is chained off of an observable, you end up having to write code that looks backwards from what's actually happening:

    range(1,5).startWith(0);

It'd be nice to have some solution/alternative to chained `startWith` such that the thing you're starting off with, appears to the left of the observer it's supposed to precede, e.g. something like

    Rx.Observable.startWith(0, range(1,5))

Yes, you could always write `concat(just(0), range(1,5)`, but then what's the point of `startWith` other than to remove a `just`?

/cc @blesh

**Comment by blesh** [comment]
Sounds good to me. Should be pretty straightforward to implement with little to no impact on performance.

**Comment by headinthebox** [comment]
It is actually designed to be like that, because in practice you create a complex expression and then at the end you say `startWith`. That is just my 2 cents as the guy that designed `startWith`.

**Comment by blesh** [comment]
@headinthebox ... would you say it would be problematic to extend `startWith` to support this feature? Would you rather see a `prepend` type operator? like: `myComplexObservable.prepend(someOtherObservable)` 

Or do you feel this isn't necessary?

**Comment by headinthebox** [comment]
I think it is not necessary; as I said, you usually only know at the very end of defining a long an complex `someOtherObservable` that you want it to start with a certain value. 

The `range` example is not a very good convincing example, because if you want to start with `0` you start with `0` in the `range`.

**Comment by staltz** [comment]
I've been teaching startWith as if it would be "prepend" to people, and no one found it awkward.

**Comment by blesh** [comment]
@staltz @headinthebox 

So we're clear, the proposed API change is just:  `someObservable.startWith(1, 2, 3)` would work as basically `Observable.of(1, 2, 3).concat(someObservable)`

**Comment by machty** [comment]
Agree `range` isn't a convincing example, but in general it's very common for me to make an observable that fires now, and then is invalidated at some point in the future. It's useful for things with value semantics, among other use cases, and not so much when I'm building up something very complex but just need something to fire at the beginning.

**Comment by headinthebox** [comment]
Then you use `concat` (I do not understand at all what you mean by `to make an observable that fires now, and then is invalidated at some point in the future`)

**Comment by trxcllnt** [comment]
@machty as @headinthebox said, isn't this behavior the concat operator? `just(0).concat(range(1, 5))`

**Comment by machty** [comment]
@trxcllnt confirm.

At this point I guess I just wonder if `startWith` is worth the API bloat, but maybe that can't/shouldn't be changed at this point. Happy to have this issue closed.

**Comment by blesh** [comment]
I'm still not against this idea. I've not read a compelling argument not to add this feature. It would be a non-breaking change.

**Comment by blesh** [comment]
I guess if it greatly impacted performance, or severely broke some highly important tenet of Rx, I would be against it, but I see no evidence to that effect. It's not even adding a new operator, just enhancing an existing one.

**Comment by staltz** [comment]
Readability. `startWith` reads as "prepend", but "prepend" makes no sense in this case:

```js
Rx.Observable.startWith(0, range(1,5))
```

Why not `concat(0, range(1,5))` could detect if the argument is non observable and wrap it in a `just` Observable?

**Comment by blesh** [comment]
@staltz 'Rx.Observable.startWith(0, range(1,5))' wouldn't do anything. 

I think the proposal was simply `myObservable.startWith(value, value, value, value)`. It was just to allow more than one value. It wouldn't break the API, I don't think it's unreadable. My only concern would be effects on the performance of `startWith`.

My counter-proposal was `myObservable.prepend(Observable.of(value, value, value, value))` where `prepend` is really just a specialization of `concat`.

Of the two I can see the value of either. However I think the latter has a higher value proposition, because it's more flexible. The only problem being is I'm relatively adverse to operator bloat.

**Comment by staltz** [comment]
:-1: to prepend.
That example could have been pretty readable as 
`Observable.of(value, value, value).concat(myObservable)`

I'm indifferent to startWith with multiple parameters, although I can't see it being that useful, and we don't have anyone in this thread actively advocating it, so I wouldn't add it.

**Comment by blesh** [comment]
I'm neither inclined to agree or disagree.

I'm not a fan of adding unnecessary operators though. So yes, :-1: to `prepend`. `concat` is fine for that case.

Also, you can always do:  `Observable.of(3, 4, 5).startWith(2).startWith(1)`

Re-closing I guess.

**Comment by blesh** [comment]
I'm going to just reclose. There doesn't seem to be a lot of interest in a static `startWith`, a multiparam `startWith` or a `prepend`.
