### ISSUE TITLE
Chrome scrollbar "search result highlight" missing in docs

### ISSUE THREAD

**Issue by zertosh** [ReactiveX/rxjs#2331]
By scrolling on the content container instead of the body, Chrome won't show the highlight indicators on the scrollbar for "Find" results. (This has been Chrome's behavior for a long time).

**Actual:**
![actual](https://cloud.githubusercontent.com/assets/830952/22632326/4b5d30a8-ebe6-11e6-8979-5dab34b13743.png)

**Expected:**
![expected](https://cloud.githubusercontent.com/assets/830952/22632330/503bdb24-ebe6-11e6-8df7-1df6478e831e.png)

**Comment by staltz** [comment]
This is either an ESDoc issue or a Chrome issue, not an RxJS issue.

**Comment by kwonoj** [comment]
I'm closing this as upstream issue, since we just use ESDoc without customizations.
