### ISSUE TITLE
Why did tap get dropped in favor of do?

### ISSUE THREAD

**Issue by jayzawrotny** [ReactiveX/rxjs#2334]
As the title asks, why did the `.tap()` method get dropped in favor of the `.do()` method? This isn't a complaint nor criticism, it's more that I have a deep love for this library and want to better understand the thinking behind it. It's a simple adjustment however It seems like a lot of stream-like interface implementations use the name `.tap()` to describe that behavior, especially in the node stream libraries world.

My first guess was that the spec outlined a `.do()` method for side-effects operations so I checked out https://tc39.github.io/proposal-observable/ but it doesn't seem to mention any such method unless I'm mistaken.

**Comment by blesh** [comment]
It was asked around the core team and other community members, we we decided to merge `tap` and `doAction` into `do`. Just a preference thing, nothing more than that. Although `do` being a keyword does prove problematic in some cases.


I hope that answers your question. Thanks for asking, @jayzawrotny! :)
