### ISSUE TITLE
[Docs] Fragment identifier does not show correct part of the page

### ISSUE THREAD

**Issue by SamVerschueren** [ReactiveX/rxjs#2336]
Hi

I'm working on an Alfred workflow that makes it super easy to search through all the operators and link directly to the documentation of an operator. But while I was working on it, I noticed that the documentation page does not bring up the correct section of the page.

For instance, this is the [mergeMap](http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#instance-method-mergeMap) operator. It sometimes works, but most of the time it doesn't and brings me somewhere close to the operator, but not accurate.

I'm not sure if this is something that can be fixed or why this is the case, maybe because of the marble diagrams coming in slowly, page navigates to the correct section, images pop up and push the page down.

**Comment by benlesh** [comment]
Closing as stale.
