### ISSUE TITLE
Observable.of not observing in Angular 2 

### ISSUE THREAD

**Issue by AhadCove** [ReactiveX/rxjs#2337]
I am trying to use Observable.of To watch for changes in my array with no luck.
I am importing both:
```
import {Observable} from 'rxjs/Observable';
import 'rxjs/add/observable/of';
```
In my main service in Angular 2

I am getting an array from a socket.io server that changes when users connect or disconnects
I set the data after every change, which I know works, but when I try to watch for changes in my component, it does not catch the changes.

My function to get userList from Main service and bring it inside component:
```
  getUsers(){
        return Observable.of(this.userList);
      }
```
I am trying to both subscribe to the userList var, and use an async pipe, but neither are updating, They only work the first time then stop.
How do I make it actually indefinitely observe for changes?

**Comment by trxcllnt** [comment]
@AhadCove `Observable.of` just creates a synchronous Observable from the arguments. `Observable.from` converts any kinds of non or possibly Observable things into an Observable. For example, `Observable.from([1, 2, 3])` will onNext, 1, 2, and 3, then complete.

**Comment by kuncevic** [comment]
@trxcllnt say I have an array `things= [];` and function `newThing() { this.things.push(1) }`. On `ngOnInit()` I want to subscribe for changes on `things`: `Observable.from(this.things).subscribe(() => console.log("new thing"));` - seams to be not working for me.

**Comment by kwonoj** [comment]
either `of` or `from`, or other Observable creation method does not setup dynamic value changes into original source, instead it sets up Observable from state of value when provided.

**Comment by AhadCove** [comment]
Look up Subjects, that's what I was missing. Once you understand and implement subjects it will be much easier

**Comment by kuncevic** [comment]
Yeah it is what I was pointing out that it just not working this way, the subject is the way to go

**Comment by AhadCove** [comment]
Gotcha

**Comment by saurabhraja** [comment]
My issue is just the opposite. Observable.of is observing changes for a property. But the same doesn't seem to be working with Subject. Here is my scenario,

I have a private property for my component.
`private cellColor: string = "orange";`

I'm using Observable.of to mimick an api call and update cellColor;
```
Observable.of(true)
      .delay(2000)
      .subscribe((success) => {
        if(success){
          this.cellColor = 'white';
          this.cdr.markForCheck();
        }
      });
```
This successfully updates cellColor property to white and the view also is updated.

However, my actual requirement is to use a Subject for inter component communication. Here in my case, I have created a Subject inside my common service. From component 1 I'm pushing the new value for cellColor property and subscribing to it from Component 2. On subscription, the property cellColor gets updated though view is not. Below is the code snippet.

```
this.subscription = this.styleService.getCellColorMessage()
      .subscribe((message) => {
          this.cellColor = message.cellColor; 
          this.cdr.markForCheck(); 
        });
```

What is the catch here?
