### ISSUE TITLE
Reduce logs as array, but erroring as object

### ISSUE THREAD

**Issue by rohitsodhia** [ReactiveX/rxjs#2338]
**RxJS version:**
5.1.0

**Code to reproduce:**
```typescript
this.searchSubscription = this.filtersSubject
  .takeLast(2)
  .reduce((acc, cur) => {
    console.log(acc);
    acc.push(cur);
    return acc;
  }, [])
  .debounceTime(1000)
  .subscribe(x => this.emitFilters());
```

**Error:**
Code fails to compile because error claiming acc is an object (thus, no push method), even though the console.log shows acc to be an array.

**Additional information:**
I was told by [this StackOverflow answer](http://stackoverflow.com/questions/42080580/rxjs-reduce-logs-as-array-but-erroring-as-object#42080580) that this is a bug with RxJS? If I'm wrong, please ignore.

**Comment by trxcllnt** [comment]
pinging our resident typings police @kwonoj @david-driscoll

from the StackOverflow answer:
> Your code is correct but there is a bug in rxjs5 that is preventing it from type checking.
> 
> Looking at the source code of reduce we see the following signature
> ```
> export function reduce<T>(this: Observable<T>, accumulator: (acc: T, value: T, index: number) => T, seed?: T): Observable<T>;
> 
> export function reduce<T>(this: Observable<T>, accumulator: (acc: T[], value: T, index: number) => T[], seed?: T[]): Observable<T[]>;
> 
> export function reduce<T, R>(this: Observable<T>, accumulator: (acc: R, value: T, index: number) => R, seed?: R): Observable<R>;
> ```
> When writing overloads in TypeScript it is necessary to order them from greatest to least specificity with respect to their types including their type arguments. Is it because TypeScript intentionally picks the first matching overload. The last declaration of the overload set actually needs to come first.

**Comment by kwonoj** [comment]
So this is dupe to #2339?

**Comment by rohitsodhia** [comment]
Yah, the gentleman who answered my q also put up a report it seems. Close whichever is fit :)

**Comment by aluanhaddad** [comment]
@rohitsodhia, @kwonoj I apologize for the duplicate. I wanted to make sure it got reported.

**Comment by jayphelps** [comment]
@aluanhaddad @rohitsodhia I'm not able to reproduce this:

[Playground](http://www.typescriptlang.org/play/#src=class%20Observable%3CT%3E%20%7B%0A%20%20reduce%3CT%3E(this%3A%20Observable%3CT%3E%2C%20accumulator%3A%20(acc%3A%20T%2C%20value%3A%20T%2C%20index%3A%20number)%20%3D%3E%20T%2C%20seed%3F%3A%20T)%3A%20Observable%3CT%3E%3B%0A%20%20reduce%3CT%3E(this%3A%20Observable%3CT%3E%2C%20accumulator%3A%20(acc%3A%20T%5B%5D%2C%20value%3A%20T%2C%20index%3A%20number)%20%3D%3E%20T%5B%5D%2C%20seed%3F%3A%20T%5B%5D)%3A%20Observable%3CT%5B%5D%3E%3B%0A%20%20reduce%3CT%2C%20R%3E(this%3A%20Observable%3CT%3E%2C%20accumulator%3A%20(acc%3A%20R%2C%20value%3A%20T%2C%20index%3A%20number)%20%3D%3E%20R%2C%20seed%3F%3A%20R)%3A%20Observable%3CR%3E%3B%0A%20%20reduce%3CT%2C%20R%3E(this%3A%20Observable%3CT%3E%2C%20accumulator%3A%20(acc%3A%20R%2C%20value%3A%20T%2C%20index%3F%3A%20number)%20%3D%3E%20R%2C%20seed%3F%3A%20R)%3A%20Observable%3CR%3E%20%7B%20return%20new%20Observable()%3B%7D%0A%7D%0A%0Alet%20o%3A%20Observable%3Cstring%3E%3B%0Ao.reduce((acc%2C%20cur)%20%3D%3E%20%7B%0A%20%20console.log(acc)%3B%0A%20%20acc.push(cur)%3B%0A%20%20return%20acc%3B%0A%7D%2C%20%5B%5D)%3B) is there something else besides just using reduce that is triggering the incorrect override to be selected?

**Comment by aluanhaddad** [comment]
@jayphelps Here is a reproduction: [Playground](http://www.typescriptlang.org/play/#src=class%20Observable%3CT%3E%20%7B%0A%20%20reduce%3CT%3E(this%3A%20Observable%3CT%3E%2C%20accumulator%3A%20(acc%3A%20T%2C%20value%3A%20T%2C%20index%3A%20number)%20%3D%3E%20T%2C%20seed%3F%3A%20T)%3A%20Observable%3CT%3E%3B%0A%20%20reduce%3CT%3E(this%3A%20Observable%3CT%3E%2C%20accumulator%3A%20(acc%3A%20T%5B%5D%2C%20value%3A%20T%2C%20index%3A%20number)%20%3D%3E%20T%5B%5D%2C%20seed%3F%3A%20T%5B%5D)%3A%20Observable%3CT%5B%5D%3E%3B%0A%20%20reduce%3CT%2C%20R%3E(this%3A%20Observable%3CT%3E%2C%20accumulator%3A%20(acc%3A%20R%2C%20value%3A%20T%2C%20index%3A%20number)%20%3D%3E%20R%2C%20seed%3F%3A%20R)%3A%20Observable%3CR%3E%3B%0A%20%20reduce%3CT%2C%20R%3E(this%3A%20Observable%3CT%3E%2C%20accumulator%3A%20(acc%3A%20R%2C%20value%3A%20T%2C%20index%3F%3A%20number)%20%3D%3E%20R%2C%20seed%3F%3A%20R)%3A%20Observable%3CR%3E%20%7B%20return%20new%20Observable()%3B%7D%0A%7D%0A%0Alet%20o%3A%20Observable%3Cstring%3E%3B%0Ao.reduce((acc%2C%20cur)%20%3D%3E%20%7B%0A%20%20console.log(acc)%3B%0A%20%20acc.push(cur)%3B%0A%20%20return%20acc%3B%0A%7D%2C%20%5B%5D)%3B).

For reference, here is the triggering snippet
```ts
class Observable<T> {
  reduce<T>(this: Observable<T>, accumulator: (acc: T, value: T, index: number) => T, seed?: T): Observable<T>;
  reduce<T>(this: Observable<T>, accumulator: (acc: T[], value: T, index: number) => T[], seed?: T[]): Observable<T[]>;
  reduce<T, R>(this: Observable<T>, accumulator: (acc: R, value: T, index: number) => R, seed?: R): Observable<R>;
  reduce<T, R>(this: Observable<T>, accumulator: (acc: R, value: T, index?: number) => R, seed?: R): Observable<R> { return new Observable();}
}

let o: Observable<number>;
o.reduce((acc, cur) => {
  console.log(acc);
  acc.push(cur.toString()); // error argument of type 'string' is not assignable to parameter of type 'number';
  return acc;
}, []);
```
Correcting the order of the overloads fixes this, giving `acc` the inferred type `any[]` which matches the behavior of the declarations for `Array.prototype.reduce` in **lib.d.ts**. While `any` is not desirable, the compiler cannot infer better without a type annotation, but the current declaration, but introducing an additional type parameter, clearly wants to allow seed to be of a different type (reduce is pretty limited if it cannot be).

Also note that the overload taking a seed of type `T[]` is unnecessary as its usecase is fully covered when the overload taking type arguments `T` and `R` is actually used which it currently never is.

**Comment by WiseBird** [comment]
@aluanhaddad Hello, sorry for bothering you but could you give me a small explanation. Currently code snipped like:
```
import {Observable} from 'rxjs';

let o: Observable<number>;
o.reduce((acc, cur) => {
    console.log(acc);
    acc.push(cur.toString());
    return acc;
}, []);
```
produces the same error: `TS2345: Argument of type 'string' is not assignable to parameter of type 'number'.`

Is it expected? By discussion I expected that after declarations rearranging it should go away.
