### ISSUE TITLE
.repeat() causes RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by alancnet** [ReactiveX/rxjs#2341]
**RxJS version:**
5.1.0

**Code to reproduce:**
`require('rxjs').Observable.of(1).repeat().subscribe(() => {})`

**Expected behavior:**
Code should block forever and do nothing.

**Actual behavior:**
RangeError: Maximum call stack size exceeded

**Additional information:**
rx 4.1.0 behaves correctly:
`require('rx').Observable.just(1).repeat().subscribe(() => {})`

**Comment by kwonoj** [comment]
Check this issue https://github.com/ReactiveX/rxjs/issues/651 which explains in detail (especially comment https://github.com/ReactiveX/rxjs/issues/651#issuecomment-153944205) for background details why it's behavior's changed between two implementations. In short in v5 default scheduling strategy has changed, so if you'd like to repeat synchronous observable you need to schedule it accordingly via `subscribeOn`.  

I believe issue itself is sufficiently explained in original issue, closing it as dupe.

**Comment by alancnet** [comment]
@kwonoj, it seems the proper technique would be to use `.subscribeOn`, but what scheduler would you use? Is the trampoline scheduler still there somewhere?

PS: This is not an edge case for me, as I often write entire programs based in RX, including a computer learning algorithm where I encountered this issue.

**Comment by kwonoj** [comment]
@alancnet check https://github.com/ReactiveX/rxjs/blob/master/MIGRATION.md#schedulers-renamed migration guide for schedulers. you may able to use `asap`, which is `default` scheduler in v4.

**Comment by trxcllnt** [comment]
@alancnet `Scheduler.queue` will give you identical behavior to Rx 4
