### ISSUE TITLE
Runaway promise with mergeMap and finally

### ISSUE THREAD

**Issue by jeremejevs** [ReactiveX/rxjs#2343]
**RxJS version:** 5.0.3

**Code to reproduce:**
```js
Observable
  .of(1, 2, 3)
  .mergeMap(x => Observable.fromPromise(Promise.resolve(x)))
  .finally(() => Promise.resolve())
  .subscribe(x => console.log(x))
```

**Expected behavior:** No runaway promises, no warnings from Bluebird.

**Actual behavior:** There's a runaway promise somewhere (resulting in a Bluebird warning):
```
Warning: a promise was created in a handler at /sync/orange/customizer/node_modules/rxjs/src/Subscriber.ts:131:22 but was not returned from it, see http://goo.gl/rRqMUw
    at new Promise (/sync/orange/customizer/node_modules/bluebird/js/release/promise.js:77:14)
```

**Additional information:** If I comment out either the `.mergeMap` or the `.finally` line, then the warning goes away. However, when both lines are present, I get a warning. Not sure if related or not, but there's [an SO question with a similar problem](http://stackoverflow.com/q/34728324/242684).

**Comment by trxcllnt** [comment]
I'm not familiar with Bluebird, but I guess [we should be returning `null`](http://bluebirdjs.com/docs/warning-explanations.html#warning-a-promise-was-created-in-a-handler-but-was-not-returned-from-it) in our Promise `then` callbacks?

**Comment by jeremejevs** [comment]
Yep, sounds right, not sure what else can be done about it.

**Comment by benlesh** [comment]
Closing as stale

**Comment by vanyadymousky** [comment]
@benlesh But the issue still exists, cannot this be fixed?
