### ISSUE TITLE
WebRTC examples

### ISSUE THREAD

**Issue by tauren** [ReactiveX/rxjs#2352]
I'm building a realtime app that uses WebRTC for video streams and two-way data communication. The current implementation relies heavily on event emitters and promises, with some generators thrown in as well. Needless to say, it needs to be refactored as the codebase is becoming harder to grok and I fear it will  become difficult to maintain. Testing is maddening due to all the possible states.

I experimented with RxJS a couple years ago and really liked what I saw, but didn't have the opportunity to pull it into a project. I'm exploring it again now as it may help to add better structure to this complex code. It would really help to see some examples of using RxJS with WebRTC. Unfortunately, I cannot seem to locate much of anything. 

I'm looking for WebRTC examples that illustrates topics such as:

* peer connection lifecycle to handle offer, icecandidates, answer, etc.
* error handling with automatic reconnection
* datachannel message and error handling

Can anyone point me to anything at all related? the closest I've found is [rxjs-broker](https://github.com/chrisguttandin/rxjs-broker) for datachannels.

**Comment by blesh** [comment]
cc @jkup
