### ISSUE TITLE
Websocket binaryType setting

### ISSUE THREAD

**Issue by tauren** [ReactiveX/rxjs#2353]
[Websockets](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket) have a property called `binaryType` that takes a value of `blob` (default) or `arraybuffer`. In my app, I have to change it to `arraybuffer`, but there is no simple mechanism in `WebSocketSubject` to do this.

For now, I'm setting the property once the socket has been opened. For instance:

```
  let subject = Observable.webSocket({
    url: '',
    openObserver: {
      next: e => { e.currentTarget.binaryType = 'arraybuffer' }
    }
  })
```

This seems to work, but I'm worried there could be a race condition where data is sent or received before the `binaryType` is set. When this value is not set correctly, `TypeError: First argument to DataView constructor must be an ArrayBuffer` is thrown.

I propose that a `binaryType` property be accepted in the config object passed to `Observable.webSocket`. It will immediately set the property on the socket instance as soon as it is created:

```
        try {
            socket = this.protocol ?
                new WebSocketCtor(this.url, this.protocol) :
                new WebSocketCtor(this.url);
            this.socket = socket;
            if (this.binaryType) {
                this.socket.binaryType = this.binaryType
            }
        }
```

Thoughts?

**Comment by blesh** [comment]
It seems like we should expose this via configuration object.

**Comment by tauren** [comment]
Awesome, that was fast!
