### ISSUE TITLE
feature: if no error function passed to subscribe, need to at least console.error

### ISSUE THREAD

**Issue by born2net** [ReactiveX/rxjs#2365]
@feature: if no error function passed to subscribe, need to at least console.error!

I am working with rxjs5 and did not pass an error function handler for my subscription and sure enough my errors got trapped and never displayed to the console.
I believe that be default, if a user does not provide an error handler, the least rxjs should do is catch the error and console.error() so new users (and old ones who forget) will be notified of swallowed bugs.

this relates also to Ben's blog:
https://medium.com/@benlesh/on-the-subject-of-subjects-in-rxjs-2b08b7198b93#.itwajvi1m
and so I agree that we should not trap the errors and be as verbose as possible when any exception is raised,

I use latest rxjs 5.0

to "solve" the problem I don't use subscribe and instead use my own ```.sub``` which forces me to add it via typescript. But not everyone uses TS and reporting of errors should take place to the console, always.

My current hack:

```
Observable.prototype.sub = Observable.prototype.subscribe;

declare module "rxjs/Observable" {
    interface Observable<T> {
        sub: (observerOrNext: PartialObserver<T> | ((value: T) => void),
              error: (error: any) => void,
              complete?: () => void) => AnonymousSubscription;
    }
}
```

Angular 2 Kitchen sink: http://ng2.javascriptninja.io
and source@ https://github.com/born2net/Angular-kitchen-sink
Regards,

Sean

**Comment by trxcllnt** [comment]
Without an error handler, the error is be re-thrown globally, which most environments have a way of notifying. We can't use console, since it's not available in all envs. Where are you seeing uncaught errors swallowed?

**Comment by born2net** [comment]
I had a situation that I did a subscribe and in it has another subscribe, I know an anit pattern, and I fixed it but still the error in the 2nd sub got swallowed, until I put the 2nd onError function, which I think should always show the trace. I will close the PR but just my 2 cents.

regards
