### ISSUE TITLE
when used repeatWhen() operator, I can't receive anything in complete stage.

### ISSUE THREAD

**Issue by chgc** [ReactiveX/rxjs#2371]
RxJS version: 5.1.0

Code to reproduce:
```
Rx.Observable.interval(500)
    .take(3)
    .repeatWhen(attempts => attempts.delay(1000).take(1))
    .subscribe(
        x => console.log('Next: %s', x),
        err => console.log('Error: %s', err),
        () => console.log('Completed')
    );
```
Expected behavior:
```
Next: 0
Next: 1
Next: 2
//waits 1 second
Next: 0
Next: 1
Next: 2
Completed
```

Actual behavior:
```
Next: 0
Next: 1
Next: 2
//waits 1 second
Next: 0
Next: 1
Next: 2
```
 
I ain't sure what's the right behavior for repeatWhen.

**Comment by kwonoj** [comment]
Do you have repo to reproduce issue and details of version you're using? 

this is I got with latest using your code snippet.

https://travis-ci.org/kwonoj/repeatwhen-test#L175-L192

https://github.com/kwonoj/repeatwhen-test/blob/master/index.ts#L3-L10

![image](https://cloud.githubusercontent.com/assets/1210596/22946095/44de1460-f2ab-11e6-9872-44236ade9eb5.png)

**Comment by chgc** [comment]
So, I re-run the code on version 5.1.1. the result came out correctly. 
issue close
