### ISSUE TITLE
[TS Typing] allow mergeAll on Observable<T[]> like mergeMap(x => x) allows

### ISSUE THREAD

**Issue by Dorus** [ReactiveX/rxjs#2372]
On an observable of an array, it's possible to call `.mergeMap(x => x)` instead of `.mergeMap(x => Rx.Observalble.from(x))`.

While `.mergeMap(x => x)` should be identical to `mergeAll()`, in TS it's not allowed to call `mergeAll()` on Observable<T[]>, but `.mergeMap(x => x)` is allowed.

**Comment by kwonoj** [comment]
I'm not sure if I understood issue correctly. Can you provide detail with snippet example for clarity?

**Comment by Dorus** [comment]
Code sample:

```Js
Rx.Observable.of([1,2,3]).mergeMap(x => x)
```

```Js
Rx.Observable.of([1,2,3]).mergeAll()
```

This will produce the same result, and observable of `1,2,3`, but in Ts, the second one wont compile.

**Comment by kwonoj** [comment]
Maybe I'm lost, but isn't this in above code snippet?

https://travis-ci.org/kwonoj/mergeall-test#L162-L171

![image](https://cloud.githubusercontent.com/assets/1210596/22943268/ccbbd69c-f2a1-11e6-9e73-d5292c6fa59a.png)

**Comment by kwonoj** [comment]
Oh, now I see. Sorry for confusions.

**Comment by Dorus** [comment]
@kwonoj Sorry for the confusion, i should have added `subscribe` to the observable. My point is that the second line will return `Number[]` instead of `Observable<number>`

**Comment by kwonoj** [comment]
Actually I was surprised we have updated `concatAll` for similar reason but forgot mergemap. https://github.com/ReactiveX/rxjs/issues/1436 :p think you can blame me for that.
