### ISSUE TITLE
add publishWebsocket

### ISSUE THREAD

**Issue by Dorus** [ReactiveX/rxjs#2383]
For a while i was under the impression i could use `source.websocket(...).subscribe(...)`, but that bit me when i actually tried to us it.

A workaround for this is to use `source.multicast(() => Rx.Observable.webSocket(...), e=>e).subscribe(...)`. Using this pattern made me realise that we got a `publish*` function for almost all different subjects, but not for `WebSocketSubject`. It would be nice to have one too.

**Comment by benlesh** [comment]
Closed for lack of interest.
