### ISSUE TITLE
Observable fails to load even after importing

### ISSUE THREAD

**Issue by j0nimost** [ReactiveX/rxjs#2385]
have been trying to implement an Observable variable with angular2, I get an unidentified error.

Here's a sample code
```
         .... Other imports...
    import {Observable} from 'rxjs/Observable';

    @Injectable()
    export class UserService {
     
      fileUrl: string ='URL';

     constructor (private http:Http){}
     
     getItems(terms: Observable<string>)
      {
           return terms.denounceTime(200).distinctUntilChanged().switchMap(term => this.searchTerm(term));
  }



  searchTerm(term){
       return this.http.get(this.fileUrl+term).map(res => res.json());

        }

     }
```
The observable returns unidentified which means it doesn't load

**RxJS version:**  5.0.1

**Code to reproduce:**

**Expected behavior:**  search item from json file

**Actual behavior:** returns unidentified term

**Additional information:**

**Comment by kwonoj** [comment]
(I've updated to mark code correctly)

Just by reading given code snippet, it seems you've only imported `Observable<T>` and does not import other operators. If you imported other operators in your code and still it's occurring, please update issues with

- minimal repo to able to reproduce issue. It is better to separate out with ng2.
- details of stack traces and error messages.

**Comment by j0nimost** [comment]
I have all other imports I haven't included them since they all seem to be working and I have focused on the observable since my error only seems to originate from there

**Comment by kwonoj** [comment]
My question is not about `other` imports, about `RxJS operators` you've used in code which aren't listed in above example snippet.

**Comment by j0nimost** [comment]
I thought Observable was independent, never the less I have not included them here but in my code they are there 

# map
# debounceTime
# distinctUntilChange
# switchMap

# Subject

All were included and I ran the app with no error from these operators my issue arose with

 Observable<T>

**Comment by kwonoj** [comment]
With given snippet and your report, it is not clear what error you are currently encountering and hard to provide possible reasons for your case. I'd like to give details as much as I can, but to do those need some additional details as mentioned https://github.com/ReactiveX/rxjs/issues/2385#issuecomment-280902350.

**Comment by trxcllnt** [comment]
@j0nimost is the Observable reference undefined, or is it missing operators? Either of these should work:
```typescript
import {Observable} from 'rxjs';
// or...
import {Observable} from 'rxjs/Observable';
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/debounceTime';
import 'rxjs/add/operator/distinctUntilChange';
import 'rxjs/add/operator/switchMap';
```
