### ISSUE TITLE
Ajax requests do not handle ampersand correctly

### ISSUE THREAD

**Issue by ebeloded** [ReactiveX/rxjs#2389]
**RxJS version:** 5.1.0

**Code to reproduce:**
`Rx.ajax.post('my-api',{ url: 'bla&foo=bar' })`

**Expected behavior:**
Expected to send post request with a single parameter (*url*)

**Actual behavior:**
Sends post request with two parameters: *url* and *foo*

**Additional information:**
The problem could be resolved by setting `Content-Type` to `application/json` manually on each request, but presumably these requests should work out of the box.

**Comment by ericponto** [comment]
I think the body key/value pairs need to be encoded with `encodeURIComponent` instead of `encodeURI`. I can submit a PR for these changes.

**Comment by zorji** [comment]
I am having the same issue can we approve the pull request?

**Comment by benlesh** [comment]
This should be addressed with #3502
