### ISSUE TITLE
Remove `fromArray`, `fromPromise` in favor of just `from`

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#239]
Now that `from` does exactly the same thing as `fromArray` or `fromPromise` if an array or a promise is passed to it, perhaps we can remove those two methods to reduce the API surface area.

This is similar to the removal of `just`, `value` and `return` in favor of just using `of`.

**Comment by trxcllnt** [comment]
@blesh I am in favor of this

**Comment by blesh** [comment]
After @kwonoj generously made a PR around this, and some experimentation with performance, `from(array)` has proven to be much slower than `fromArray(array)`. So much so that I'm going to close this issue.

Thanks @kwonoj, if not for your PR, we wouldn't have known.

**Comment by kwonoj** [comment]
It is glad I could find out this :) Will continue effort on other topics. Thanks!
