### ISSUE TITLE
All window* operators emit Subjects instead of Observables

### ISSUE THREAD

**Issue by martinsik** [ReactiveX/rxjs#2391]
All `window*` operators emit Subjects instead of Observables.

**RxJS version:** 5.1.1

**Code to reproduce:**
```
const Observable = Rx.Observable;

Observable.timer(0, 200)
  .window(Observable.timer(0, 1000))
  .take(1)
  .subscribe(observable => console.log('window', observable.constructor.name));

Observable.timer(0, 200)
  .windowCount(5)
  .take(1)
  .subscribe(observable => console.log('windowCount', observable.constructor.name));

Observable.timer(0, 200)
  .windowTime(1000)
  .take(1)
  .subscribe(observable => console.log('windowTime', observable.constructor.name));

Observable.timer(0, 200)
  .windowToggle(Observable.timer(0, 1000), () => Observable.timer(1000, 1000))
  .take(1)
  .subscribe(observable => console.log('windowToggle', observable.constructor.name));

Observable.timer(0, 200)
  .windowWhen(() => Observable.of(1).delay(1000))
  .take(1)
  .subscribe(observable => console.log('windowWhen', observable.constructor.name));
```

Demo: https://jsbin.com/qiseles/3/edit?js,console

This prints to console:
```
window Subject
windowCount Subject
windowTime Subject
windowWhen Subject
windowToggle Subject
```

**Expected behavior:**
All `window*` operators should emit only Observables.
I checked RxJS 4 and all `window*`s emit `AnnonymousObservable`'s.

RxJS 4 Demo: https://jsbin.com/hehozin/2/edit?js,console

This prints to console:
```
window AnonymousObservable
windowCount AnonymousObservable
windowTime AnonymousObservable
windowWithTimeOrCount AnonymousObservable
```

**Actual behavior:**
All `window*` operators emit Subjects.

**Additional information:**

This would be obviously easy to fix with `asObservable()` but I'm wondering if this is intentional behavior. Since `window*` operators are going to be used probably with `switch()` then you don't have many ways to unintentionally misuse the Subjects. Even if I try to emit manually values to a Subject from `window*` it won't be reemitted because it's before the `switch()` subscribes to it. So this example won't produce unexpected results:

```
Observable.timer(0, 200)
  .window(Observable.timer(0, 1000))
  .do(subject => subject.next('ignore me'))
  .switch()
  .take(5)
  .subscribe(val => console.log('next', val));
```

Only if I do something really wrong it'll lead to unexpected emissions (demo https://jsbin.com/xoxibay/3/edit?js,console):

```
Observable.timer(0, 200)
  .window(Observable.timer(0, 1000))
  .do(subject => Observable.timer(0, 250)
    .map(n => String.fromCharCode(97 + n))
    .take(3)
    .subscribe(subject)
  )
  .switch()
  .take(20)
  .subscribe(val => console.log('next', val));
```

So I'd expect all `window*` operators to emit only Observables similarly to RxJS 4 but maybe this is intentional. Also I checked that the `asObservable()` was committed in January 2016 and at that time all `window*` operators were already implemented so maybe this is a bug?

**Comment by kwonoj** [comment]
I think it's unintentionally leaking details of operator behavior, so it seems legit to make carry Observable instead.

**Comment by martinsik** [comment]
As explained by @blesh in #2408 this is intentional.
