### ISSUE TITLE
Error Observable has incorrect signature

### ISSUE THREAD

**Issue by raybooysen** [ReactiveX/rxjs#2395]
In master currently, ErrorObservable<T> has the following code: 

```
  static create<T>(error: T, scheduler?: IScheduler): ErrorObservable<T> {
    return new ErrorObservable(error, scheduler);
  }

  static dispatch(arg: DispatchArg) {
    const { error, subscriber } = arg;
    subscriber.error(error);
  }

  constructor(public error: T, private scheduler?: IScheduler) {
    super();
  }
```

I don't think any of the `error` parameters should be of type `T`.  They should be of type `Error` or most likely `any`.  The documentation even says this: 
`   * @param {any} error The particular Error to pass to the error notification.`

**Comment by kwonoj** [comment]
I think this signature comes while overriding base classes static creation method. `Error` itself doesn't have type constraint so even generating ErrorObservable with given type it is not being used actually, so probably it'd better to remove out for clarity.

**Comment by raybooysen** [comment]
Thanks @kwonoj
