### ISSUE TITLE
Basic docs (Readme) on installation, usage and extension

### ISSUE THREAD

**Issue by jeffbcross** [ReactiveX/RxJS#24]

**Comment by duncanmak** [comment]
I see that this effort is now underway and I'd love to contribute where I can.

Other than the spec differences (I see that OnNext/OnError/OnComplete has been renamed), what are the major differences between the currently available RxJS 2 and the new RxJS 3? I saw mentions of performance gains and also talk of reduction of closure usage, how do they fit together?

It'd be nice to have a list of tasks for people to come in and help out. Do we need to port all the Observable operators from RxJS 2?

cc @blesh

**Comment by blesh** [comment]
@duncanmak this library is extremely alpha at the moment. The current efforts are around getting the initial structure of the project and the library correct, and that requires we limit the number of "cooks in the kitchen". Once that subsides, however, there will be a concise laundry list of operators to implement, as well as a list of differences between RxJS 2 and RxJS 3. 

The best thing you can do for the time being is review the code and comment on issues with concerns or thoughts.

**Comment by blesh** [comment]
I think we're good for the spirit of this issue for now. There's definitely a LOT left to do, but I wouldn't want it to impend an Alpha release.
