### ISSUE TITLE
Remove MapPolyfill

### ISSUE THREAD

**Issue by DaSchTour** [ReactiveX/rxjs#2407]
**RxJS version: 5.2.0**

**Code to reproduce:**
Load rxjs through SystemJS and wonder why a file called MapPolyfill.js is loaded

**Expected behavior:**
Map is provided by external polyfill like core-js, polyfill.io or the browser

**Actual behavior:**
MapPolyfill is hard wired into rxjs

**Additional information:**

I'm wondering why there is an own polyfill for Map inside rxjs. Given the fact that Map even has basic support in IE11 and that many people add own polyfills I think rxjs shouldn't ship it's own polyfill but giving the choice to developers. There are many ways to add polyfills for ES6 features and maybe some even would like to choose using no pollyfills and don't support IE11 (all other common browsers already have nearly full ES6 support).

**Comment by kwonoj** [comment]
As far as I can tell if you have either native map or correctly polyfilled map, those internal implematation won't be used. (https://github.com/ReactiveX/rxjs/blob/master/src/util/Map.ts#L4) . Is this about Rx shouldn't fall back to any internal polyfill and consumer should provide polyfill if they need it, or own polyfill doesn't work even if user correctly setup their own polyfill?

**Comment by DaSchTour** [comment]
@kwonoj It's just about the fact, that RxJS ships it's own polyfill. I think that this isn't a good approach. And even if there is already a polyfill or native support the rxjs polyfill will be shipped. After I created this issue I've also seen, that there is some kind of "polyfill" for Sets and maybe even other ES6 features.

**Comment by benlesh** [comment]
>  I think that this isn't a good approach. 

I don't think there were any better alternatives offered in this issue. You're welcome to file a PR with your ideal solution and argue the merits. Until then I need to close this, as it's not actionable, it's more of a complaint. (Which is noted, and I'll give it some thought, but it's not a priority for us at this time)

**Comment by DaSchTour** [comment]
@benlesh thought I listed enough alternatives.

1. No Polyfill needed because project only supports browsers that have ES6 support
2. Polyfill is needed and can be chosen by developers
   1. [core-js](https://github.com/zloirock/core-js)
   2. [polyfill.io](https://polyfill.io) 
   3. [es6-map](https://github.com/medikoo/es6-map)

**Comment by benlesh** [comment]
@DaSchTour I'm warming up to this idea. However, I might want to track it as a separate issue, because we're polyfilling more than just Map.

We're going to need to discuss this, as it would be a major breaking change, so I don't know if there will be any fast movement on this.

Reopenning this issue for now.

**Comment by DaSchTour** [comment]
As I see this is "fixed" in V6.
