### ISSUE TITLE
Documentation Ideas

### ISSUE THREAD

**Issue by robwormald** [ReactiveX/RxJS#241]
just added a super basic dgeni workflow that parses TS source and spits out an API document. Dgeni can do most anything, so the next stage is a question of what we'd like the complete Rx site to look like / contain.
- API docs (generated from source code)
- Tutorial / introductory guides / howdoi
- Marble diagrams?

Currently site is static, not sure we necessarily want to introduce a framework for SEO goodness. Discuss?

**Comment by robwormald** [comment]
@jeremymwells i know you'd asked about docs

**Comment by kwonoj** [comment]
What about 'Do vs. Don't do' guidelines for common patterns? (maybe included under topics of 'howdoi' ?)

**Comment by staltz** [comment]
How about not reinventing the wheel and instead joining forces with reactivex.io?

**Comment by blesh** [comment]
@staltz I think we're going to do that regardless. However that doesn't change the fact that some of the RxJS docs are specific to this JavaScript implementation.

**Comment by staltz** [comment]
Correct, I think this is mandatory

> - API docs (generated from source code)

But these start to be questionable:

> - Tutorial / introductory guides / howdoi
> - Marble diagrams?

If I'd write tutorials, I'd keep it as specific as possible for ReactiveX/RxJS, and not about Rx in general.

**Comment by jeremymwells** [comment]
I don't think anyone means to do anything new or different than what is/was done with the [reactive-extensions](https://github.com/Reactive-Extensions/RxJS/tree/master/doc) rxjs docs; however, it still bears discussion, no?

**Comment by robwormald** [comment]
making a note here for myself for dash https://kapeli.com/docsets

**Comment by xgrommx** [comment]
I could create some template like this http://xgrommx.github.io/rx-book.

**Comment by blesh** [comment]
@xgrommx ... I'm for any template. At this point the most important thing is just landing the ability to generate the docs, preferably from JSDocs  with markdown, etc.

**Comment by staltz** [comment]
@blesh here is how I generate markdown from JSDoc: https://github.com/cyclejs/cycle-core/blob/master/scripts/make-api-docs.js

**Comment by robwormald** [comment]
@staltz nice find, thanks! this works about a thousand times better than what i was doing ;-)

**Comment by blesh** [comment]
It seems like this issue has gone a little stale. There is some ongoing work around this, though. So I'm going to mention @thejameskyle here, so he sees it, and then I'm going to close it for now. I think we've got a solid foot in the door for documentation, and we're probably going to lean heavily on the reactivex.io site for everything but the API docs.

**Comment by thejameskyle** [comment]
Ongoing work over here: https://github.com/thejameskyle/reactivex-experimental-docs
