### ISSUE TITLE
A minor documentation bug in tutorial

### ISSUE THREAD

**Issue by ivan7237d** [ReactiveX/rxjs#2412]
The examples in this section 

http://reactivex.io/rxjs/manual/tutorial.html#producing-values

are meant to start with listening to key events on the first line, not `'input'` events.

**Comment by lachlanhunt** [comment]
The event should probably be `"keypress"` and the observables should use `.pluck("key")` to get anything like the expected output in the comments.

**Comment by benlesh** [comment]
Our documentation is now officially at rxjs.dev.
