### ISSUE TITLE
Consider rename observable symbol $$observable => observable 

### ISSUE THREAD

**Issue by DzmitryShylovich** [ReactiveX/rxjs#2415]
**Actual behavior:**
I use [transform-es2015-modules-umd](https://babeljs.io/docs/plugins/transform-es2015-modules-umd/)  Babel plugin. And [I need](https://github.com/angular/angular/pull/14722/files) to map `import {$$observable} from 'rxjs/symbol/observable';` 

Observable symbol is exported as `Rx.Symbol.observable` but exported symbol from `rxjs/symbol/observable` is called `$$observable`. Because symbols have different names I cannot just map it like `"rxjs/symbol/observable": "Rx.Symbol"`

**Expected behavior:**
I see 3 possible solutions:
1. Rename `$$observable` => `observable` so it will be possible to do `"rxjs/symbol/observable": "Rx.Symbol"`
2. export `$$observable` from `Rx` as is => `Rx.$$observable`
3. export `$$observable` from `Rx.Symbol` => `Rx.Symbol.$$observable`

I can also accomplish it by changing import `import {$$observable} from 'rxjs/symbol/observable';`  => `import {Symbol} from 'rxjs/Rx';`  but I don't want to import the whole lib :)

**Comment by DzmitryShylovich** [comment]
@benlesh can you take a look please? async pipe is broken for rollup users because of this.
the simplest none breaking solution would be 
```
export const $$observable = getSymbolObservable(root);
export const observable = $$observable;
```

**Comment by benlesh** [comment]
@DzmitryShylovich Ugh. I see the problem. It sucks a little because I'm not sure what we'd do for a deprecation path for this. There's no way to detect if someone is using the "wrong" one via direct import, AFAICT.

**Comment by DzmitryShylovich** [comment]
@benlesh I submitted a pr https://github.com/ReactiveX/rxjs/pull/2435 
please take a look when you have time. thanks

**Comment by DzmitryShylovich** [comment]
ping @benlesh it also affects es5 users :)
