### ISSUE TITLE
TypeScript compile error: 'Promise' only refers to a type, but is being used as a value here.

### ISSUE THREAD

**Issue by Pappa** [ReactiveX/rxjs#2422]
I'm seeing the following compile error when trying to compile a small Angular/Rx project:

```
$ tsc -p .
node_modules/rxjs/Observable.d.ts(69,60): error TS2693: 'Promise' only refers to a type, but is being used as a value here.
node_modules/rxjs/operator/toPromise.d.ts(3,79): error TS2693: 'Promise' only refers to a type, but is being used as a value here.
```

**RxJS version: 5.2.0**

**Code to reproduce:**

`typings.json`

```
{
  "globalDependencies": {
    "es6-shim": "registry:dt/es6-shim#0.31.2+20160726072212"
  }
}
```

`tsconfig.json`

```
{
  "compilerOptions": {
    "outDir": "./dist/js/",
    "target": "es5",
    "noImplicitAny": false,
    "sourceMap": true,
    "module": "commonjs",
    "allowSyntheticDefaultImports": true
  },
  "include": [
    "./src/**/*",
    "./node_modules/typescript/lib/lib.es6.d.ts"
  ],
  "exclude": [
    "node_modules"
  ]
}
```

`Angular service (edited)`

```
import Rx from 'rxjs/Rx';
import {angular, ng} from "angular";

export class TweetEvents {
    requests = {
        getSentiment: new Rx.Subject<string>()
    }
    responses = {
        getSentimentSuccess: new Rx.Subject<Models.Sentiment>()
    }
    static $inject = [
        "$http"
    ];

    constructor(
        private $http: ng.IHttpService
    ) { 
        this.initGetSentiment();
    }

    private initGetSentiment(): void {
        this.requests.getSentiment
        .flatMap((search: string) => {
            return Rx.Observable.fromPromise(
                this.$http({
                    url: 'https://example.com'
                  })
            )
        })
        .subscribe((response) => {
            this.responses.getSentimentSuccess.next(response);
        });
    }
}

angular.module("events")
    .service("TweetEvents", TweetEvents);
```

I'm pretty stumped and can't find examples online of other people with seeing exactly the same issue.

**Comment by kwonoj** [comment]
While I can't try this on my end, some things caught my eyes like `including lib.es6.d.ts manually` etcs. It'd be easier if you have repo can provide reproduce this issue.

**Comment by Pappa** [comment]
It seems the cause was declaring `commonjs` modules in `tsconfig.json` while I'm using ES6 modules.

**Comment by thomas3577** [comment]
If I transpile my Typescript Project (a NodeJS-Application), then I get exactly the same two errors. I use commonjs modules in tsconfig.json

node_modules/rxjs/Observable.d.ts(1,25): error TS2307: Cannot find module 'promise'.
node_modules/rxjs/operator/toPromise.d.ts(3,79): error TS2693: 'Promise' only refers to a type, but is being used as a value here.

**Comment by thomas3577** [comment]
Here my Repo to reproduce

https://github.com/thomas3577/rxjs-node-typescript

Just run npm start

**Comment by ds82** [comment]
Can we please reopen this issue? It's still an issue .. @thomas3577 repo demonstrates it quite well.

**Comment by ds82** [comment]
Fixed by adding `bluebird` (as Promise lib) & `core-js` (as common ES6 polyfill). Use `@types/core-js <= 0.9.36` to avoid other errors.

**Comment by prajwal78** [comment]
@ds82 Even I am facing the same issues with rxjs. Could you please help how did you integrate bluebird and corejs libraries within the code?

**Comment by prajwal78** [comment]
@ds82 Anything to be included in tsconfig.json ?

**Comment by ds82** [comment]
Nope.
You can see it working in this project: https://github.com/ds82/openhab1-rest

**Comment by Nexxado** [comment]
I'm still receiving this error when targeting `es5`.

Tried to all sorts of combinations with `lib` in `tsconfig.json`'s `compilerOptions`.
Tried adding `@types/es6-promise`, `@types/core-js` and even tried to include the libraries themselves and not just the types.

But i'm still receiving:
```
ERROR in [at-loader] ./node_modules/rxjs/Observable.d.ts:58:60
    TS2693: 'Promise' only refers to a type, but is being used as a value here.

ERROR in [at-loader] ./node_modules/rxjs/Observable.d.ts:73:59
    TS2693: 'Promise' only refers to a type, but is being used as a value here.
```

**Comment by LukasBombach** [comment]
FWIW, I have this same error on my own project and I have identified this is because my repo is a monorepo

**Comment by salmazov** [comment]
What does it mean? I have the same error.

**Comment by tje3d** [comment]
Same error in reactxp

**Comment by steph643** [comment]
Thanks a million @tje3d!
Notice that `"lib": ["es2015"]` seems to be enough for me to fix the 'Promise' issue.

**Comment by kakins** [comment]
I'm using Visual Studio with an Angular CLI-based project and experienced Typescript intellisense errors referring to this issue and several others.  In my case, I need to still target older browses (which apparently is what the "es5" settings is for).  

This is what I had to do for es2017:
```
"compilerOptions": {
    "target" : "es5",
    "lib": ["es5", "es2017", "dom"]
}
```
