### ISSUE TITLE
Issue with using Sinon Fake Timers and the delay() operator

### ISSUE THREAD

**Issue by meenie** [ReactiveX/rxjs#2423]
I'm trying to write tests for my RxJS functions and some of them use the `.delay()` operator.  In doing so, I need to be able to use SinonJS's `useFakeTimers()` functionality to achieve proper test results.  I've created a very simple use case in jsfiddle that illustrates my point. The link is below.

**RxJS version:** 5.2.0

**Code to reproduce:** https://jsfiddle.net/cnmqnb6s/

**Expected behavior:** It should trigger the delay when you tick the timer to greater or equal to the amount of the delay

**Actual behavior:** The `do()` operator never fires after the delay.

**Additional information:**  If you uncomment the second line of code where noted and comment out the last line of code, the test actually works.  This is how I've had to get around the issue in my actual tests, but it creates a huge delay in the actual test runs.

**Comment by kwonoj** [comment]
Can I ask reason to not to use `testScheduler` but try to use faketimers instead? Scheduler has vary implementation per each usecases, and doesn't guarantee it's controlled by mocking `setTimeout`.

**Comment by meenie** [comment]
@kwonoj: I'm not exactly sure how to use `TestScheduler` in this instance.  Are you able to provide a quick example based off my original jsfiddle?

**Comment by kwonoj** [comment]
if you're trying to test is behavior of `delay`, it could be something similar to

```js
const scheduler = createTestScheduler(); //pseudo function, you may need to create instance per your usecase
const source = Observable.something.delay(100, scheduler).do(() => someState change).subscribe();

expect(state).not.changed;
scheduler.flush();
expect(state).changed
```

this is super simplified pseudo logics, and can vary by scope of test and etcs. If you'd like to check stream of source being delayed correctly, you can use marble diagram instead like https://github.com/ReactiveX/rxjs/blob/master/spec/operators/delay-spec.ts#L26-L37 , or you could use 3rd party module to have rx4 style of time controlling via https://github.com/kwonoj/rxjs-testscheduler-compat.

**Comment by meenie** [comment]
@kwonoj Thank you! I'll close this as it's not actually a bug.
