### ISSUE TITLE
subscribe ignores second argument of event emitter

### ISSUE THREAD

**Issue by benjaminhon** [ReactiveX/rxjs#2431]
I am using redis, which exposes the event emitter as follows with 2 arguments, without rxjs, i can get both arguments, however with rxjs, the second argument is missing.

```
r.on 'message', (channel, message) ->
  console.log channel, message

# => Greet, Hello

Rx.Observable.fromEvent(r, 'message').subscribe (channel, message) ->
  console.log channel, message

# => Greet, undefined
```

is this supposed to be the case?

**Comment by Podlas29** [comment]
That is how it works at the moment. You can get access to the second parameter by using project function:

```javascript
Rx.Observable.fromEvent(r, 'message', (channel, message) => [channel, message])
.subscribe(arr => {
  console.log(arr[0]); // logs value of channel
  console.log(arr[1]); // logs value of message
});
```

That being said it seems like a strong case to make `fromEvent` behave like `bindCallback` which emits an array if there are many arguments in callback.

**Comment by Podlas29** [comment]
Does redis have an `off` function for canceling subscriptions? How do you stop listening to events?

**Comment by benjaminhon** [comment]
yea it has,

```

sub.unsubscribe()

```

**Comment by Podlas29** [comment]
When you unsubscribe `fromEvent` it will try to call `off` function on redis. Since (as I understand) it is not there, your code will crash.
Use `fromEventPattern` which allows you to customize how callback is registered and unregistered.

I have made prs for refined docs for these two operators, if you still have trouble figuring out which does what: https://github.com/ReactiveX/rxjs/pull/2411 
https://github.com/ReactiveX/rxjs/pull/2416
If these are helpful or if they still need some clarifications, please leave some comment in a pr. ;)

**Comment by trxcllnt** [comment]
We should probably update `fromEvent` to work with EventEmitters too, as I constantly have this problem as well. From what I remember, EventEmitters have `on` and `removeListener` methods. Does that sound right?

**Comment by kwonoj** [comment]
> , EventEmitters have on and removeListener methods. 

doesn't node `evemtEmitter` works already via `addListener`  (https://nodejs.org/api/events.html#events_emitter_addlistener_eventname_listener)  /`removeListener` ?(https://github.com/ReactiveX/rxjs/blob/7c41c08119cecb0c039ed40b2e1f3a0e6ac0d56e/src/observable/FromEventObservable.ts#L10-L13)

**Comment by benjaminhon** [comment]
@Podlas29 that does the job

**Comment by kwonoj** [comment]
I'm not sure where this issue has landed - is there specific we need to resolve in this issue?

**Comment by felixfbecker** [comment]
It would probably be a more ergonomic API to default to an array if multiple args are provided, but it would also be a breaking change. At the same time, the workaround is very concise:
```ts
Observable.fromEvent(r, 'message', Array.of)
  .subscribe(([channel, message]) => {
    // ...
  })
```

**Comment by felixfbecker** [comment]
or you could even create an object with lodash:
```ts
Observable.from(r, 'message', partial(zipObject, ['channel', 'message']))
  .subscribe(event => {
    console.log(event.channel)
    console.log(event.message)
  })

**Comment by benjaminhon** [comment]
zeromq for node alse use multipart replies which requires the above

**Comment by raycarter** [comment]
A simple use case about this issue and more about #3048 and RP #3049:

```javascript
const Observable = require('rxjs').Observable;
const Oboe = require('oboe');

// create oboe instance
const oboe = Oboe({
  url: 'http://test-streaming.shengsoft.net',
  method: 'GET'
});

// original usage of oboe node event
oboe.on('node', '!.*', function() {
  console.log('from original oboe node event callback');
  console.log(arguments); // here 3 arguments are passed in
  console.log('');
});

// create another oboe instance
const oboe1 = Oboe({
  url: 'http://test-streaming.shengsoft.net',
  method: 'GET'
});

// use fromEventPattern to convert oboe event in Observable
const oboeObs = Observable.fromEventPattern((handler) => {
  oboe1.on('node', '!.*', handler);
});

oboeObs.subscribe(function() {
  console.log('from Observable handler');
  console.log(arguments); // !!! only the first argument is passed in
  console.log('');
});
```
In this simple use case Observable combines Oboe to consume a json-streaming server. The server returns only a part of a whole json object every second. Observable is introduced to process the data returned from the json-streaming server. But it got only the first argument while the original Oboe event passed 3 arguments in event handler. I have created a simple [repo](https://github.com/raycarter/rxjs-fep-arguments-problem-showcase) for you to retry what I mean.

**Comment by benlesh** [comment]
This is no longer an issue. `fromEvent` will emit an array of arguments if it gets more than one argument back from the handler.
