### ISSUE TITLE
[PROPOSAL][AWAITING TS 2.1] Retry to move to @types/ type definitions

### ISSUE THREAD

**Issue by saneyuki** [ReactiveX/rxjs#2437]
1. Before to release v5, we tried to move to `@types/***` type definitions from `typings/`.
   - Worked in https://github.com/ReactiveX/rxjs/pull/2120
2. But we had faced to https://github.com/Microsoft/TypeScript/issues/11849, so we backout-ed the above change. 
3. For the future if we move to use TypeScript 2.1 or later, we can retry to do it.

**Comment by kwonoj** [comment]
I've migrated into @types packagage in other codebases and generally in favor of this, but not sure how to verify regression.

**Comment by alexeagle** [comment]
To verify regression, you can use a typings test like Angular:
https://github.com/angular/angular/tree/master/integration/typings_test_ts21

The formula:
- for each version of TypeScript you support users having
  - install that version
  - install the distribution you publish to npm
  - compile a file that exhaustively imports all the public APIs

if there's anything in your distro that would break users type-checking your lib, this should detect it.

**Comment by kwonoj** [comment]
This is completed in master.
