### ISSUE TITLE
audit - no last value when source is finished

### ISSUE THREAD

**Issue by alvipeo** [ReactiveX/rxjs#2440]
Please look at this plunkr - http://plnkr.co/edit/syjMAHIJDX40m7lzNHO6. It feels like a hack. Should it emit the last value when the source Observable is finished?

**Comment by martinsik** [comment]
Both `audit` and `auditTime` emit only when the "duration" Observable emits or the duration elapses respectively so I guess it makes sense that the last value is discarded. It's a lossy operator anyway...
