### ISSUE TITLE
Rxjs not working in firefox webextensions

### ISSUE THREAD

**Issue by fouadbhatti** [ReactiveX/rxjs#2446]
**RxJS version:**
5.2.0 / Firefox version: 52
rxjs@5.2.0/bundles/Rx.min.js
**Code to reproduce:**
const subject = new Rx.Subject();
**Expected behavior:**
Rxjs should work
**Actual behavior:**
Getting the following error on loading rxjs
```XrayWrapper denied access to property "random" (reason: object is not safely Xrayable). See https://developer.mozilla.org/en-US/docs/Xray_vision for more information. Note that only the first denied property access from a given global object will be reported. Rx.min.js:214:186```

Firefox is throwing error a ```TypeError: a.Math.random is not a function  Rx.min.js:214:186```. Also when tried to create a subject throws this error ```TypeError: Rx.Subject is not a constructor```
**Additional information:**
Working perfectly fine in safari and chrome extensions. Only in firefox webextensions it throws the above mentioned errors and fails.

**Comment by benlesh** [comment]
@fouadbhatti do you have the minimal code to reproduce the error? It's unlikely we'll be able to look into this without a "working" example that shows the behavior you're seeing.

**Comment by fouadbhatti** [comment]
@benlesh Sure. Here is the minimal code. This is a basic firefox webextension in which i have added rxjs.

**RxJS Version**
5.2.0
rxjs@5.2.0/bundles/Rx.min.js

**Firefox Version**
Firefox version: 52

**How to install**
1. Open firefox and go to about:debugging, click on Load Temporary Addon and open the boderify folder and then select manifest.json and open. 

2. Now extension will load. Just click on debug for boderify on the about:debugging page. Accept the incoming request dialog. Keep it open, please don't close it for now.

3. Open any page now in firefox, and then go back to debugger window. You will see these errors throw.
` 
XrayWrapper denied access to property "random" (reason: object is not safely Xrayable). See https://developer.mozilla.org/en-US/docs/Xray_vision for more information. Note that only the first denied property access from a given global object will be reported.  Rx.min.js:214:167
TypeError: a.Math.random is not a function  Rx.min.js:214:186
TypeError: Rx.subject is not a function  borderify.js:6:15
TypeError: a.Math.random is not a function  Rx.min.js:214:186
TypeError: Rx.subject is not a function
`

**Code to reproduce**
borderify.js
`
document.body.style.border = "5px solid red";
var subject = Rx.subject();
console.log(subject);
`

**Attatched webextension**
[borderify.zip](https://github.com/ReactiveX/rxjs/files/830244/borderify.zip)

P.S In love with RxJS keep up the awesome work. Shipped many apps with RXJS Kudos!! 😍 . Would love to contribute.

**Comment by kwonoj** [comment]
Most weird part is it fails with `TypeError: a.Math.random is not a function`. I assume this prevents remaining module loads, does not allow to create any instances.

Rx does uses `Math.random ` in only single place (https://github.com/ReactiveX/rxjs/blob/69d051bc56cb337148db30515029363c1e78b90d/src/util/Immediate.ts#L132) but it's simply try to access in global object where possible and `Math.random` should be available in general environment. Does ff extension has some constraints related with using native functions?

**Comment by benlesh** [comment]
@kwonoj, @fouadbhatti if a common JavaScript API does not exist in the environment running the script, isn't the onus on that developer to supply a polyfill?

**Comment by kwonoj** [comment]
I'd guess so but I'm bit suspicious if this is polyfill issue as math.random is supported in every browser. Guess is this is more like kind of security issues try to access math.random from non-default-global object (we're accessing it via `root.`, which we resolves internally)

**Comment by fouadbhatti** [comment]
@benlesh yes agreed should be, issues seems to be that window.Math is undefined in firefox webextensions content scripts scope. However Math is available as a global variable in all browsers including in content scripts scope in firefox web extensions. Adding the following line before RxJS lib solves the problem for now.
`window.Math = Math`
Any idea why are we using root.Math can't we just simply access the Math global; available in all browsers.

**Comment by benlesh** [comment]
@fouadbhatti they should be the same thing. There's no reason, IMO, we couldn't have just called Math.random() directly there, given it's a JavaScript API, and not even browser specific.

Either way, I don't think RxJS can or should polyfill Math.random. Unless I'm misunderstanding the request here, I think you're asking us to polyfill it.

**Comment by fouadbhatti** [comment]
@benlesh yes agreed should be the same thing. Somehow firefox mucks it up in webextensions context for content scripts. For safari and chrome works perfectly fine. Lets close this for now. Will try to report an issue at firefox and see what do they have to say. Thanks

**Comment by benlesh** [comment]
Okay, thanks @fouadbhatti

**Comment by felixfbecker** [comment]
This commit made rxjs work for us in Firefox our extension (ignore the formatting changes): https://github.com/rothfels/rxjs/commit/17f6393e189957ba86ae56db16efd4ea623532f8#diff-f3e092d2d04d24bd6ab161baf5b7b24dR132

We currently have this published under https://www.npmjs.com/package/@sourcegraph/rxjs, but would like to avoid maintaining a fork of course.

Would you accept the above patch as a PR? I don't see any harm in it (no polyfill needed)
