### ISSUE TITLE
first operator does not accept default value only signature with null-value predicate

### ISSUE THREAD

**Issue by kwonoj** [ReactiveX/rxjs#2447]
**RxJS version:**
latest

**Code to reproduce:**
`Rx.Observable.range(0, 10).first(null, null, true);`

**Expected behavior:**

**Actual behavior:**
> error TS2345: Argument of type 'null' is not assignable to parameter of type '(value: number, index: number, source: Observable<number>) => boolean'.

**Additional information:**
This seems bit weird since default signature allows optional values for predicate / resultselector (https://github.com/ReactiveX/rxjs/blob/69d051bc56cb337148db30515029363c1e78b90d/src/operator/first.ts#L76) and test case exists (https://github.com/ReactiveX/rxjs/blob/69d051bc56cb337148db30515029363c1e78b90d/spec/operators/first-spec.ts#L46) - not sure why it's being caused. Maybe signature ordering causes this.

**Comment by martinsik** [comment]
I tested this with `rxjs@5.2.0` and `typescript@2.2.1` and it compiled without any problem. What Typescript version are you using?

**Comment by kwonoj** [comment]
2.1 / 2.2 both seems have issues.

https://travis-ci.org/kwonoj/rxjs-first-signature-demo/builds/209822410#L172

https://github.com/kwonoj/rxjs-first-signature-demo/blob/f971b3426f8c5e497b219632bb27e57c0b70ec6b/index.ts#L3

**Comment by jsayol** [comment]
`null` is indeed not assignable to that type, even if it's optional. What you're looking for is this:

`Rx.Observable.range(0, 10).first(undefined, undefined, true);`

**Comment by kwonoj** [comment]
Yes, I am aware this can be avoided. Still type definition need to be looked into.

**Comment by seveves** [comment]
Does something like this look valid? I could create a PR then ...
```ts
export function first<T, R>(this: Observable<T>, predicate?: (value: T, index: number, source: Observable<T>) => boolean | undefined | null,
                            resultSelector?: ((value: T, index: number) => R) | void | undefined | null,
                            defaultValue?: R): Observable<T | R> {
  return this.lift(new FirstOperator(predicate, resultSelector, defaultValue, this));
}
```

**Comment by martinsik** [comment]
I'm looking at this again after more than a year and I think this should be the expected behavior. Even when the method is defined as optional it shouldn't accept `null` in my opinion. If I want to skip any of the parameters I should use `undefined`.

**Comment by benlesh** [comment]
This is no longer an issue.
