### ISSUE TITLE
how to access to _refCount

### ISSUE THREAD

**Issue by qina83** [ReactiveX/rxjs#2448]
Hello,
is there a way to access to _refCount variable as in "should count references" test?
My goal is to know how many subscription are active for an observer.

thanks

**Comment by staltz** [comment]
There is no public API for that, if that's your question.

**Comment by benlesh** [comment]
@qina83 you shouldn't be doing that, really. If you need to know how many times you've subscribed to something, you can that by incrementing something at the time you subscribed. One method (of many) is to use `defer`:

```ts
let myRefCounter = 0;

Observable.defer(() => {
  myRefCounter++;
  return source$.finally(() => myRefCounter--);
});
```
