### ISSUE TITLE
Document Observable.subscribe()

### ISSUE THREAD

**Issue by staltz** [ReactiveX/rxjs#2449]
We missed the most basic thing: to document the `subscribe` method under Observable. It's currently missing. For context: https://twitter.com/Shahor/status/839512270061334530

**PRs welcomed**

**Comment by Podlas29** [comment]
Yeah, I had that in mind. I guess I will make it a priority. More involved description of an `Observer` (and partial observers as well) should probably be a companion.

**Comment by Podlas29** [comment]
The real question is if we want it te be dry and precise, or newcomer-friendly? What I wrote so far sounds more like an introduction to how subscriptions work and what is a lifecycle of Observable stream (next, complete, error). I am not sure if that is a good or should I just focus on what subscribe accepts etc.

**Comment by staltz** [comment]
The newcomer-friendly part is the Manual, where we explain those types of stuff. The JSDoc can be more technical (and/or type aware) description. The exception is operators, which need newcomer-friendly description because they aren't described in the Manual.

Essentially the Manual teaches the essential concepts and methods in RxJS, but the API ref explains operators and factories in details.

**Comment by ps-aux** [comment]
I was wondering if there is a reason that `subscribe()` is currently missing from the online [documentation](http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html)

![image](https://user-images.githubusercontent.com/4789301/33280320-f2eee4f8-d3a1-11e7-94ad-1b4c7b538d7b.png)
