### ISSUE TITLE
Bad import in "src/MiscJSDoc.ts"

### ISSUE THREAD

**Issue by josh-sachs** [ReactiveX/rxjs#2453]
**RxJS version:**
`5.2.0`
**Code to reproduce:**

**Expected behavior:**

**Actual behavior:**

**Additional information:**

path: `src/MiscJSDoc.ts`

At the top of the file there is an: `import './scheduler/MiscJSDoc';`

There is no ` ./scheduler/MiscJSDoc` ... only Zoul. 

https://github.com/ReactiveX/rxjs/tree/master/src/scheduler

**Comment by kwonoj** [comment]
Seems simple error while updating import paths?

**Comment by staltz** [comment]
Someone deleted it, sigh.

**Comment by josh-sachs** [comment]
It looks like it was moved, not deleted? 

`import './scheduler/MiscJSDoc';`  => `import './observable/dom/MiscJSDoc';`

Also... I'm not gonna get anything for my obscure 80's Ghost Busters reference?   What happened to the internet I came to know and love?

**Comment by benlesh** [comment]
> Also... I'm not gonna get anything for my obscure 80's Ghost Busters reference?
I love all Ghostbusters references

**Comment by NColey** [comment]
Hi, it looks like the new import statement (`import './observable/dom/MiscJSDoc';`) was already added, its just that the old one was never removed. I noticed this issue was still open so I made a PR to fix it here: https://github.com/ReactiveX/rxjs/pull/2494.
