### ISSUE TITLE
docs for how to use rxjs without requireJS or commonJS 

### ISSUE THREAD

**Issue by snimavat** [ReactiveX/rxjs#2456]
There doesnt seem to be any example of how to use rxjs without using requireJS or commonJS 
is it possible at all ? it would be great if there was a simple example.

**Comment by kwonoj** [comment]
Our readme have instructions using CDN to get global build, and also if you're using local global build simply pointing path would be sufficient. Once you loaded global build, `Rx` is exposed globally.

https://github.com/ReactiveX/rxjs#cdn
