### ISSUE TITLE
`isNumeric` implementation seems overkill

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#246]
In the past I've used `isNumeric` impls like: 

```js
function isNumeric(val) {
  return !isNaN(parseFloat(val)) && isFinite(val);
}
```

what we [currently have is here](https://github.com/ReactiveX/RxJS/blob/03853ac4a510a6cede2ef294f56eaa503e5479d6/src/util/isNumeric.ts#L11):

```TypeScript
var is_array = Array.isArray;

export default function isNumeric(val) {
  return !is_array(val) && (val - parseFloat(val) + 1) >= 0;
};
``` 

I think the `is_array` check and the adding `1` bit is dubious. @trxcllnt do you have any reasoning/examples of why this is necessary?

I don't think this is something that is necessarily impacting performance meaningfully, but wanted to hash out what it was doing and why, so we could make sure the code is doing things that make sense.

**Comment by trxcllnt** [comment]
@blesh this function was lifted from jQuery, and afaik is the best way to check if a value can be cast to a Number.

**Comment by blesh** [comment]
@trxcllnt strange, it makes me wonder if this is for supporting some crazy old IE implementations or something?

**Comment by blesh** [comment]
This isn't really an issue, right now. Closing.
