### ISSUE TITLE
Dead links in docs

### ISSUE THREAD

**Issue by philipooo** [ReactiveX/rxjs#2461]
I just noticed that the links provided on https://github.com/ReactiveX/rxjs/blob/master/doc/operators.md are dead.

Cheers

**Comment by staltz** [comment]
They're not missing, they are relative links, and that markdown document is used to generate the website. The markdown file is *not* meant to be read directly from github. This issue can be closed.

**Comment by staltz** [comment]
Notice e.g. the README disclaimer here at the bottom https://github.com/ReactiveX/rxjs/tree/master/doc

**Comment by kwonoj** [comment]
closing as this has been answered adequately.

**Comment by philipooo** [comment]
Oh sorry, missed that.
