### ISSUE TITLE
Is it safe to subscribe on class members inside the class?

### ISSUE THREAD

**Issue by fetis** [ReactiveX/rxjs#2464]
**RxJS version:**
any

**Code to reproduce:**
```
class GetFilteredValueFromServer {
  items = new Subect();
  private filters = new Subject()

  constructor() {
    this.filters
      .debounceTime(300)
      .distinctUntilChanged()
      .switchMap(filters => this.doHttp(filters))
      .subscribe(items => this.items.next(items));
  }

  setFilters() {
    ...
  }

  private doHttp(): Observable<any> {
    ...
  }
}
```

**Additional information:**
I was working on the class that provides filtered items from the backend and came up with solution which I posted above. So, I subscribe on `filters` Subject and every change of it triggers HTTP-request and yields new data to the user. 

Everything works fine and I really like this solution, but I have concern about  is it safe to subscribe on your own class member or not. Since JS doesn't have destructors and relay only on Garbage collector, I don't have opportunity to unsubscribe. 

Can you shed light on it, since I don't familiar with tech insights of the library.

**Comment by kwonoj** [comment]
>  I don't have opportunity to unsubscribe.

You should unsubscribe, or either limit source to complete accordingly to make subscriptions auto-unsubscribed. Ben's article explains this in quite plenty of detail. https://medium.com/@benlesh/rxjs-dont-unsubscribe-6753ed4fda87#.hubvvw3gh

**Comment by kwonoj** [comment]
As I believe this topic is covered, closing it for now.

**Comment by fetis** [comment]
@kwonoj thank you. you answer my question. but I still don't see the proper solution in Angular services for unsubscribing. Maybe it's not a big issue, because service exists during all application life.

**Comment by emilio-martinez** [comment]
@fetis Angular won't unsubscribe Observables for free unless it's via Async Pipe or something like that. Also, the constructor isn't really part of the Component lifecycle.

I would suggest using an operator like `takeUntil` triggered on ngOnDestroy, for example, especially if you're doing HTTP requests
