### ISSUE TITLE
Remove Set polyfill

### ISSUE THREAD

**Issue by benlesh** [ReactiveX/rxjs#2467]
We're currently polyfilling `Set` for everyone, really only to support `distinct`. I'd like in the spirit of #2407, I'd liek to propose removing the `Set` polyfill entirely, placing the onus on developers targeting IE10 and lower to provide their own polyfill.

### Pros

1. Smaller library size
2. Less to maintain
3. I suspect the native Set impls may have better performance
4. All "modern" browsers support Set, it seems

### Cons

1. Definitely a breaking change
2. I'm unsure if there are any quirks to this functionality between browser versions in the wild.
3. Might hurt more esoteric JS runtime targets (ala SmartTVs at Netflix?)

**Comment by trxcllnt** [comment]
👍 ⚡️

**Comment by kwonoj** [comment]
I believe this is done via https://github.com/ReactiveX/rxjs/pull/3040.
