### ISSUE TITLE
New Operator Suggestion: `mush` (or a better name...)

### ISSUE THREAD

**Issue by matantsu** [ReactiveX/rxjs#2468]
On a current project of mine I use `Firebase` and `AngularFire2`, that uses `Observables` to query the real-time database. A common thing to do is to fetch an object from the database, and to fill it with other objects based on references within the object. 
Eg:
```
interface Manager {...}
interface Owner{...}
interface Job {
   managerKey: string,
   ownerKey: string
}

interface FilledJob {
   manager: Manager
   owner: Owner
}
```

lets look at our options for this: `combileLatest`, `forkJoin`

- Both of these operator wait for both the `Observable<Manager>` and `Observable<Owner>`
  to return something, and only when both are available it emits.
- Instead, I would like to fetch them **independently** and have my `FilledJob` model filled incrementally
  when the manager is available I emit a `{manager: ..., owner: null}`, and when the owner is available,
  I emit `{manager: ..., owner: ...}` so now both are available.

Let's define a new operator:

```
// ----------1-2------3---------------5-----------------
// ------*--------*-----------/-------------*-----------
// ---------A---------B----C------D---------------------
//                           ||
//                           \/
// ------a--bc-d--e---f----g--h---i---j-----k-----------
// where a = f(null,*,null)
//       b = f(null,*,A)
//       c = f(1,*,A)
//       d = f(2,*,A)
//       e = f(2,*,A)
//       f = f(3,*,B)
//       g = f(3,*,C)
//       h = f(3,/,C)
//       i = f(3,/,D)
//       j = f(5,/,D)
//       k = f(5,*,D)
export function mush<Q>(f: (...any) => Q , ...o: Observable<any>[]): Observable<Q> {
    let mapped = o.map((r, i) =>
        r.map(x => {return {index: i, val: x}; })
    );
    let init = o.map(v => null);
    let accumilator = (acc, n) => acc.map((val, i) => i === n.index ? n.val : val);
    return Observable.merge(...mapped)
        .scan(accumilator, init)
        .map(arr => f(...arr));
}
```

So now we can do:
```
interface FilledJob {
   manager?: Manager
   owner?: Owner
}

manager$ = (job: Job): Observable<Manager> => ...
owner$ = (job: Job): Observable<Owner> => ...
filledJob$ = (job: Job): Observable<FilledJob> => mush((m, o) => ({manager: m, owner: o}), manager$(job), owner$(job));
```

I think this is a good pattern, you are always up-to-date with all sources of information, when something changes, you instantly know it. You don't have to wait for another thing to happen.

advantages:
1. It's general: I think this is a very common pattern, can be used instead of `combineLatest` and `forkJoin`.
2. It's the RX way: your app feels more responsive to changes, it never hangs to wait for something, you get it as soon as it's there.
3. It's smarter: once you are up-to-date with all of your information you are in a position to make the best decisions.

improvements:
- a better name...
- let the user provide an empty value, instead of having `null`. it's better to differentiate `null` as pending from `null` as nothing.
- also fire `init` immediately, before anything happens.

**Comment by staltz** [comment]
Can I suggest just using startWith for each participant observable, and then combineLatest?

```js
combineLatest(a$.startWith(null), b$.startWith(null), f)
```

Does this solve your use case?

**Comment by matantsu** [comment]
Yes... 💯
