### ISSUE TITLE
Is this considered production ready?

### ISSUE THREAD

**Issue by walshie4** [ReactiveX/rxjs#2471]
From the README
>Reactive Extensions Library for JavaScript. This is a rewrite of Reactive-Extensions/RxJS and is intended to supersede it once this is ready

I can't seem to find any direct statement about if this library should be chosen over v4 (https://github.com/Reactive-Extensions/RxJS), can someone fill me in?

**Comment by trxcllnt** [comment]
@walshie4 We're working towards feature-parity (and/or migration assistance) with Rx 4 before we remove that line. RxJS5 is in Angular 2 core and many popular libs have already switched from 4-5. Also this: 
<img width="352" alt="screen shot 2017-03-16 at 3 22 15 pm" src="https://cloud.githubusercontent.com/assets/178183/24021192/e6f05b82-0a5c-11e7-8317-923161c0cc35.png">

**Comment by benlesh** [comment]
Yes, it's production ready. We just need to update the README.
