### ISSUE TITLE
Feature request: routeCase operator (explained below)

### ISSUE THREAD

**Issue by Arlen22** [ReactiveX/rxjs#2477]
In making a HTTP server that handles incoming requests and sends them down different observable chains depending on the request method, I realized that I needed a clean way to select which branch (track, if you will) to use for each request. 

The way I use it looks like this:

```js
ServerRequestListener
.routeCase( state => state.req.method, {
    'POST': obs => obs.mergeMap(RecieveMyDataUpload)
}, obs => obs.mergeMap(HandleMyGETRequest))
.subscribe( state => {
    //do whatever I want... basically nothing.
})
```
And here is my code for the function (which I have not tested yet).
```js
function routeCase<T>(this: Observable<T>,
    selector: (obj: T) => string,
    routes: { [selection: string]: ((obs: Observable<T>) => (Observable<T>)) },
    defaultRoute: (obs: Observable<T>) => void
): Observable<T> {
    var parts = [];
    var keys = Object.keys(routes);
    var def = keys.reduce((obs, e) => {
        var part = obs.partition(f => selector(f) === e);
        parts.push(routes[e](part[0]));
        return part[1];
    }, this.multicast<any>(new Subject()).refCount());
    parts.push(defaultRoute(def));
    //check if any route factories returned undefined and throw if they did
    keys.forEach((e, i) => keys[i] = [i, e].join(','))
    keys.push('default');
    var bads = parts.map((e, i) => [e, keys[i]])
        .filter(e => typeof e[0] !== 'object' || e[0] === null);
    if (bads.length > 0)
        throw 'These routes returned undefined: ' + bads.map(e => (e[1])).join(', ');
    return Observable.from(parts).mergeMap(a => {
        return a;
    })
}
```

After searching around, it seems like I can't really find a more concise way of doing this. So I thought I would post this as a feature request.

**Comment by kwonoj** [comment]
Just looking at glimpse of signature (sorry, have not read full snippet below yet) of suggestion this looks very similar to groupBy's possible variant. Is there specific limitation in current operator you couldn't achieve via current one? if so, what was reason? (you can refer https://github.com/ReactiveX/rxjs/issues/2299#issue-201963204) for few discussions regarding new operator discussions.

**Comment by Arlen22** [comment]
The main difference is that groupBy is dynamic whereas this is static. GroupBy could be made to work, I suppose, but the entire paradigm is different, and even then I'm not sure if I could cleanly generate static routes like I want to.

**Comment by trxcllnt** [comment]
@Arlen22 take a look at this https://www.npmjs.com/package/rx-router

**Comment by kwonoj** [comment]
As userlevel module suggested, closing.
