### ISSUE TITLE
operators documentation is broken

### ISSUE THREAD

**Issue by zoharlevin** [ReactiveX/rxjs#2480]
operators documentation leads to 404.

click on any of the operators here:  [operators.md](https://github.com/ReactiveX/rxjs/blob/master/doc/operators.md) and you'll get a 404 error.
for example [bufferWhen](https://github.com/ReactiveX/rxjs/blob/master/class/es6/Observable.js~Observable.html#instance-method-bufferWhen)

**Comment by staltz** [comment]
Go here and scroll to the bottom. https://github.com/ReactiveX/rxjs/tree/master/doc

This issue can be closed.
