### ISSUE TITLE
Outdated installation guide on http://reactivex.io/rxjs?

### ISSUE THREAD

**Issue by zs-zs** [ReactiveX/rxjs#2482]
Hi guys,

This isn't really an issue with the code. I started to try out RxJS 5 and followed the installation guide on [this page](http://reactivex.io/rxjs/manual/installation.html). This site states that I should install the `rxjs-es` package. It took me a while to realize that this package is outdated and I should have followed the installation guide on GitHub instead.

**Comment by kwonoj** [comment]
it's simply documentation on page is not published using latest documentation need include updated installation guides.

**Comment by kwonoj** [comment]
It is known documentation is not fully migrated and missing, instead of having each individual issue I've created umbrella issue at #2656 to track it.
