### ISSUE TITLE
Observable.throw doesn't throw the error when used inside Observable.fromPromise().catch()

### ISSUE THREAD

**Issue by rrhvella** [ReactiveX/rxjs#2485]
**RxJS version:** 5.2.0

**Code to reproduce:**

Refer to the following two fiddles:
[RxJS 5.2.0](https://jsfiddle.net/48pxewrs/3/)
[RxJS 5.0.1](https://jsfiddle.net/b3pq14nb/2/)

**Expected behavior:**

In both examples I expect there to be an unhandled error. 

**Actual behavior:**

There is only an unhandled error if version 5.0.1 is used, subsequent versions do not seem to behave this way, including the latest version.

**Additional information:**

I have global error handlers in my javascript code

If I have code inside a promise, inside an observable, then perform some error handling using .catch and throw any errors I don't want to handle using Observable.throw, then the errors I throw again do not reach my global error handlers. It's as if an error wasn't thrown at all.

Actually throwing the error instead of using Observable.throw actually works, however this is not ideal, as I think Observable.throw is supposed to throw the error again. It certainly does when fromPromise isn't used, as show in [this fiddle](https://jsfiddle.net/6p62u57d/2/).

**Comment by kwonoj** [comment]
Closing via #2552.
