### ISSUE TITLE
Error can't handle by subscriber.

### ISSUE THREAD

**Issue by perfectworks** [ReactiveX/rxjs#2490]
**RxJS version:**
5.2.0

**Code to reproduce:**
https://jsfiddle.net/e1g0smc7/5/

```javascript
const Observable = Rx.Observable;
const con = tag => console.log.bind(console, tag);

let a = Observable.create(observer => {
   setTimeout(() => observer.error('haha'), 1000);
}).publish();

a.connect();
a.subscribe(con('a1')); // KEYLINE 1
a.subscribe(con('a2'), con('a3')); // KEYLINE 2
```

**Expected behavior:**
console output: "a3 - haha"

**Actual behavior:**
uncaught error

**Additional information:**
If I remove `KEYLINE 1`, all things go right. Someone told me the second subscriber can't catch it because the first subscriber consumed the error . But if I remove `KEYLINE 1` and duplicate `KEYLINE 2`, I can get correct output "a3 - haha" twice, that's what I excepted.

Another wired thing is I can got 'a3 - haha' if use synchronize way to call `observer.error('haha')`. 

So I wondering why the error handler missed the error when I add `KEYLINE 1`.

**Comment by Brooooooklyn** [comment]
seems to be same as https://github.com/ReactiveX/rxjs/issues/2428

https://github.com/ReactiveX/rxjs/blob/master/src/Subscriber.ts#L222-L224

**Comment by benlesh** [comment]
Closing as stale
