### ISSUE TITLE
Move duplicate installation/usage out of README, keep only in doc/installation.md

### ISSUE THREAD

**Issue by jayphelps** [ReactiveX/rxjs#2492]
There have been many many times where [doc/installation.md](https://github.com/ReactiveX/rxjs/blob/master/doc/installation.md) and [README.md](https://github.com/ReactiveX/rxjs/blob/master/README.md) have gotten out of sync. Primarily the installation/usage sections. Instead of maintaining two copies that will continue to get out of sync, how about slim down the README to be mostly just a bunch of links to other documents like [doc/installation.md](https://github.com/ReactiveX/rxjs/blob/master/doc/installation.md).

Thoughts?

The latest inconsistency is that the installation doc still recommends rxjs-es at the top

![image](https://cloud.githubusercontent.com/assets/762949/24306992/bedf0cbe-107f-11e7-9f4a-0bf94fd580ed.png)

That means that the website is recommending it too http://reactivex.io/rxjs/manual/installation.html

**Comment by kwonoj** [comment]
related with https://github.com/ReactiveX/rxjs/pull/2292 .

**Comment by benlesh** [comment]
Closing as stale
