### ISSUE TITLE
takeWhile using Observable

### ISSUE THREAD

**Issue by intellix** [ReactiveX/rxjs#2495]
I'm trying to implement a stream of events with pause/resume functionality. 

Looking down the list of operators, TakeWhile sounds exactly what I need. I want to take values while something is true. I see that it only accepts a predicate function and am wondering why I can't also provide `Observable<boolean>`?

```ts
const button = document.querySelector('button');
const click$ = Rx.Observable.fromEvent(button, 'click');
const toggle$ = click$.scan(prev => !prev, false).startWith(true);

Rx.Observable
  .timer(0, 100)
  .takeWhile(toggle$)
  .subscribe(console.log);
```

**Comment by Boshen** [comment]
Take a look at `takeUntil` and `repeatWhen`. `takeWhile` will complete your stream, you need `repeatWhen` to repeat it.

```
const click$ = Rx.Observable.fromEvent(document.body, 'click');
const toggle$ = click$.scan(prev => !prev, true);
Rx.Observable
  .timer(0, 100)
  .takeUntil(toggle$)
  .repeatWhen(() => toggle$)
  .subscribe(console.log);
```

**Comment by martinsik** [comment]
@intellix Have a look at #1542 there's explained how to make a workaround using `switchMap()`.

**Comment by shusson** [comment]
@martinsik #1542 doesn't help with hot observers what I want is a lossless backpressure mechanism as explained in https://github.com/Reactive-Extensions/RxJS/blob/master/doc/gettingstarted/backpressure.md#pausable-buffers

**Comment by benlesh** [comment]
Closing as stale
