### ISSUE TITLE
ReferenceError: __extends is not defined

### ISSUE THREAD

**Issue by kalitine** [ReactiveX/rxjs#2499]
**RxJS@5.2.0**
I use RxJS in my library which is built with Rollup. As I'm using ES6 module, I did the following:
- `npm install @reactivex/rxjs`
- `cd node_modules/@reactivex/rxjs`
- `npm install`
- `npm run build_es6`

Then in code I've imported Rx as follow:
`import * as Rx from 'node_modules/@reactivex/rxjs/dist/es6/Rx'`

And I use it as: `Rx.Observable...`

The library build is passing without problem, but at runtime I've encountered this error:
```
ReferenceError: __extends is not defined
    at [MYTESTFILE].test.js:1864:5
    at Object.<anonymous> ([MYTESTFILE].test.js:1875:2)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at ...node_modules/jasmine/lib/jasmine.js:87:5
```

I've seen #2177, but here it seems to be a problem with es6 build which lacks `tslib` I guess.

**Comment by kalitine** [comment]
While this bug remains, I've found a solution for those who might be interested.

The idea is to use [rollup-plugin-commonjs](https://github.com/rollup/rollup-plugin-commonjs) which converts CommonJS modules to ES2015. So:
- `npm install rxjs`
- Add this plugin to Rollup

The following configuration works for my project:
```
commonjs({
    extensions: [ '.js' ],
    sourceMap: false,
    ignoreGlobal: false
})
```
Then in the code import like this:
`import * as Rx from 'node_modules/rxjs/Rx'` (resolving path depends on your Rollup configuration)
Then use as normal `Rx.Observable` for example.

Unfortunately this imports the whole RxJS library, but I think it's possible to import only specific modules also.

**Comment by kwonoj** [comment]
You can't assume you can build non-supported package (es6 in this case) using build script, while those module package is not published as working manner. At this moment build_es6 is not intended to create actual es6 distro package but only being used for internal documentation, so it is not gaurantee to work. 

I'm closing this as sort of dupe to https://github.com/ReactiveX/rxjs/issues/2335, as this is due to we don't publish es6 module packages and will be resolved via those.
