### ISSUE TITLE
Proposal: Higher order pipeline

### ISSUE THREAD

**Issue by alancnet** [ReactiveX/rxjs#2500]
# Pipeline Proposal

I continuously find myself writing many types of functions to pass into my stream composition:

1. `(V) => V` functions, or mappers
2. `(V) => Observable<V>` functions, or flatMappers
3. `(Observable<V>) => Observable<V>` functions or... Well, to my knowledge an operator doesn't exist for this.

My solution has been to convert the `Observable<V>` into `Observable<Observable<V>>`, then pass in the function to flatMap:

```javascript
const myPipelineFunction1 = (observable) => observable.whatever().else().goes().here();
const myPipelineFunction2 = (observable) => observable.something().different().here();
const myPipelineFunction3 = (observable) => observable.additional().logic().goes().here();

const pipeline = input
  .groupBy(() => 1).flatMap(myPipelineFunction1)
  .groupBy(() => 1).flatMap(myPipelineFunction2)
  .groupBy(() => 1).flatMap(myPipelineFunction3);
```

This approach allows for logical segmentation of code, and better isolation and testability of that code. For instance, `myPipelineFunction1` is more easily testable on its own than `myPipelineFunction1`, `myPipelineFunction2`, and `myPipelineFunction3` all mashed together.

My proposed solution is a new operator called **pipeline**, or whatever you feel would be appropriate. In short (and in JavaScript), the operator would look like this:

```javascript
Observable.prototype.pipeline = function(fn) {
  return this.groupBy(() => 1).flatMap(fn);
};
```

Then the composed pipeline would look like this:

```javascript
const myPipelineFunction1 = (observable) => observable.whatever().else().goes().here();
const myPipelineFunction2 = (observable) => observable.something().different().here();
const myPipelineFunction3 = (observable) => observable.additional().logic().goes().here();

const pipeline = input
  .pipeline(myPipelineFunction1)
  .pipeline(myPipelineFunction2)
  .pipeline(myPipelineFunction3);
```

I am, of course, ready, willing, and able to produce this operator myself, conforming to contribution guidelines. But I'd like your feedback before I do.

**Comment by david-driscoll** [comment]
@alancnet see #2489 😄

**Comment by alancnet** [comment]
@david-driscoll Yes, I saw this proposal. I thought it was the answer to my problem.. But it seems to be in a different spirit. When I dug into the code, I found his implementation of `map`:

```typescript
export function map<T, R>(
  project: (value: T, index: number) => R,
  thisArg?: any
): (source: Observable<T>) => Observable<R> {
  return (source: Observable<T>) => mapProto.call(source, project);
} 
```

This seems to imply a too-high-order function. Does this function not ignore `source` and return a new function that takes a new `source`? 

Meaning my pipeline would look like this:

```javascript
const pipeline = input
  .pipe(() => myPipelineFunction1)
  .pipe(() => myPipelineFunction2)
  .pipe(() => myPipelineFunction3);
```

To quote @benlesh directly:

> This `pipe` method will take a rest args of "pipeable operators", which are higher-order functions that return `(source: Observable<T>) => Observable<R>`.

I'm absolutely glad to be wrong here, and be entirely misinterpreting the PR, but for this PR to be what I'm proposing, the above quote would have to read:

- This `pipe` method will take a rest args of "pipeable operators", which are ~~higher-order~~ functions ~~that return~~ _of the signature_ `(source: Observable<T>) => Observable<R>`.

(`pipe` is already a higher-order function. Why pass more higher-order functions into it?)

**Comment by kwonoj** [comment]
Maybe I'm looking example snippet in glimpse and could be wrong, but isn't this

```
const myPipelineFunction1 = (observable) => observable.whatever().else().goes().here();
const myPipelineFunction2 = (observable) => observable.something().different().here();
const myPipelineFunction3 = (observable) => observable.additional().logic().goes().here();

const v = input
  .let(myPipelineFunction1)
  .let(myPipelineFunction2)
  .let(myPipelineFunction3);
```

working cases?

**Comment by alancnet** [comment]
@kwonoj you're absolutely correct! I just tested it and it works. Unfortunately, `let` doesn't exist in [the documentation](http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html), so I didn't know about it.

I see `letProto`, but there's no description. Is `let` an officially supported operator?

**Comment by kwonoj** [comment]
> Is let an officially supported operator? 

: sure. Documentation is just bit behind.

**Comment by alancnet** [comment]
Awesome! Thanks! I think .let makes #2489 obsolete as well.
