### ISSUE TITLE
take() breaks other observables

### ISSUE THREAD

**Issue by Kraoz** [ReactiveX/rxjs#2510]
**RxJS version:** 5.2.0

**Code to reproduce:**
`Rx.Observable
.interval(1000)
.do(() => console.log("TICK 1"))
.subscribe();

Rx.Observable
.interval(2000)
.do(() => console.log("TICK 2"))
.take(1)
.subscribe()`

**Expected behavior:**
"TICK 1" to be logged infinitely

**Actual behavior:**
"TICK 1" logged twice

**Additional information:**
take(1) seems to 'break' the first interval.

[5.2.0](https://jsfiddle.net/Kraoz/L4eobfs7/) is a fiddle that shows this behavior.
[4.1.0](https://jsfiddle.net/Kraoz/z5yagb2g/) is a fiddle where it works as expected.

Note that if you pass a onNext callback to the first interval subscribe(), it works as expected.

**Comment by trxcllnt** [comment]
This is fixed by #2238, which hasn't made it into a release. In the interim, pass an empty Object to each `subscribe()` call.
