### ISSUE TITLE
find yields single value (undefined) when no match

### ISSUE THREAD

**Issue by gluck** [ReactiveX/rxjs#2515]
**RxJS version:**

`5.2.0` / master

**Code to reproduce:**

    Observable.empty().find(_ => false)

**Expected behavior:**

Should not yield any result, as expected (and as per rxjs4 behavior and doc), cf unit test:
https://github.com/Reactive-Extensions/RxJS/blob/master/tests/observable/find.js#L63

**Actual behavior:**

Yields a single value (undefined) before completion, as per:
https://github.com/ReactiveX/rxjs/blob/master/src/operator/find.ts#L104

**Additional information:**

I believe the cause is that both `find`/`findIndex` operators were implemented by same subscriber, and `findIndex` does emit a value (-1) when not found (also in rxjs4).

**Comment by gluck** [comment]
(can work out a PR if you confirm rxjs 4 is the wanted behavior)

**Comment by david-driscoll** [comment]
The behavior makes sense to me. 
cc @kwonoj @mattpodwysocki @benlesh

**Comment by kwonoj** [comment]
Yes, I think it's my fault when I implemented this (https://github.com/ReactiveX/rxjs/pull/393) while Rx v4 doc states (https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/find.md) 

> An Observable sequence with the first element that matches the conditions defined by the specified predicate, if found; otherwise, an empty sequence.

case of `find` in opposite to `findIndex`.

**Comment by felixfbecker** [comment]
The current signature also is misleading, it says to return `Observable<T>` when it really returns `Observable<T | undefined>`

**Comment by david-driscoll** [comment]
We can't adjust the interface until the next major anyway because we're not yet using a version of TypeScript that supports the unit types `null` or `undefined`.

**Comment by kwonoj** [comment]
Closing as changes are checked in.
