### ISSUE TITLE
buffer operation on BehaviorSubject is broken

### ISSUE THREAD

**Issue by suwigyarathore** [ReactiveX/rxjs#2517]
**RxJS version:5.0.0-rc.4

**Code to reproduce:
 private handleScroll$: BehaviorSubject<any> = new BehaviorSubject<any>(null);
this.handleScroll$
.buffer(this.handleScroll$.debounceTime(SCROLL_HANDLER_DEBOUNCE_VALUE))
.map(this.reduceScrollEvents)
.subscribe(this.handleScroll);

**Expected behavior:
Should work as expectedly

**Actual behavior:**
this.handleScroll$.buffer is not a function

**Additional information:**

**Comment by kwonoj** [comment]
can you share snippet how did you import rx / operators?

**Comment by suwigyarathore** [comment]
import { Observable } from 'rxjs/Observable';
import { BehaviorSubject } from 'rxjs/BehaviorSubject';
import 'rxjs/add/operator/debounceTime';

**Comment by kwonoj** [comment]
https://github.com/ReactiveX/rxjs#es6-via-npm

if you're import observable only via `rxjs/Observable` and import each operator partially, you should import operator you're going to use as same as you patched `debounceTime` in your import snippet.
