### ISSUE TITLE
Typo/error in withLatestFrom() test?

### ISSUE THREAD

**Issue by apaatsio** [ReactiveX/rxjs#2526]
There is a test called "should combine events from *cold* observables" but the test itself uses `hot()`.

Link to the section in code: https://github.com/ReactiveX/rxjs/blob/master/spec/operators/withLatestFrom-spec.ts#L16-L24

Here's the test code:

```typescript
  asDiagram('withLatestFrom')('should combine events from cold observables', () => {
    const e1 =   hot('-a--b-----c-d-e-|');
    const e2 =   hot('--1--2-3-4---|   ');
    const expected = '----B-----C-D-E-|';

    const result = e1.withLatestFrom(e2, (a: string, b: string) => String(a) + String(b));

    expectObservable(result).toBe(expected, { B: 'b1', C: 'c4', D: 'd4', E: 'e4' });
  });
```

**Comment by kwonoj** [comment]
uh..seems so? I can't recall which one's intended though (description vs. test) 😅

**Comment by kwonoj** [comment]
marking as 'bug', at least it's incorrect state.

**Comment by martinsik** [comment]
I think it should use `cold()` because hot Observables are tested right in the next text case: https://github.com/ReactiveX/rxjs/blob/master/spec/operators/withLatestFrom-spec.ts#L26
