### ISSUE TITLE
.subscribe() without handler gets unsubscribed eventually

### ISSUE THREAD

**Issue by cmaart** [ReactiveX/rxjs#2531]
**RxJS version:** < 5.3.0; Seems to work in 5.3.0. The question is, if it was consciously fixed in 5.3.0 or just behaves different there. I couldn't find any release notes mentioning this issue.

**Code to reproduce:** http://codepen.io/cmaart/pen/ryEeMP

**Expected behavior:** 'Request finished' should be shown in console (see Codepen above)

**Actual behavior:** Doesn't show 'Request finished' on rxjs < 5.3.0

**Additional information:** Concerning the general usage of an empty subscribe call: For example consider an HTTP DELETE call that returns an Observable without any result. I need to call subscribe in order to trigger the http call but don't have get any result. So it has be okay to subscribe without success handler. As seen in the codepen, writing this `request$.subscribe(() => {})`does not unsubscribe. But it's an ugly workaround at best.

**Comment by kwonoj** [comment]
Yes, it is intended fix in 5.3 https://github.com/ReactiveX/rxjs/blob/master/CHANGELOG.md#bug-fixes, via https://github.com/ReactiveX/RxJS/commit/a1778e0.
