### ISSUE TITLE
Default values for do() parameters

### ISSUE THREAD

**Issue by felixfbecker** [ReactiveX/rxjs#2534]
`promise.then()` and `subscribe()` can be called with passing `undefined` as the first parameter, e.g. to only handle errors or completions. `do()` requires to pass a noop function like `() => undefined`. It should just have this as default value.

`doOnComplete` and `doOnError` shorthands would also be nice.

**Comment by MidnightWonderer** [comment]
Did you know that you can safely pass `null` to `do` operator?  
reference:  
https://github.com/ReactiveX/rxjs/blob/01a2d15/spec/operators/do-spec.ts#L94
https://github.com/ReactiveX/rxjs/blob/01a2d15/src/Subscriber.ts#L169

**Comment by felixfbecker** [comment]
Not according to the signature:
```ts
export declare function _do<T>(this: Observable<T>, next: (x: T) => void, error?: (e: any) => void, complete?: () => void): Observable<T>;
```

**Comment by david-driscoll** [comment]
It's entirely possible that the signature is incorrect, however it feels like a corner case.  What would someone be trying to accomplish by calling `do()` by itself?

As to `doOnComplete` and `doOnError` you can easily do `do({ error(e) { /**/ } });` or `do({ complete() {} });

**Comment by felixfbecker** [comment]
For example to implement OpenTracing:
```ts
const span = childOf.tracer().startSpan('my operation', { childOf })
return someAction()
  // ... apply operators ...
  .do(undefined, err => {
    span.setTag('error', true);
    span.log({ 'event': 'error', 'error.object': err });
  })
  .finally(() => {
    span.finish();
  })
```

**Comment by david-driscoll** [comment]
Unfortunately I can safely say that the shorthand operators for `do` (and their counter parts for `subscribe`) probably won't be making it back into the core library.  We already have enough operator overload with the current number, adding more will just make things more confusing for others.

However you could easily make your own using augmentation for your application / library.  You could even make it an npm package if you wanted! 🎉 

See:
https://github.com/ReactiveX/rxjs/blob/bc1e1e53897aeca61288378cc8e2b33ed20dbbcf/src/add/operator/do.ts

**Comment by kwonoj** [comment]
as same as @david-driscoll , I don't think we'll bring back variant of `doOn..` but making signature of `do` to make `next` to optional seems considerable option. Only thing I'd like to have is if there's some way to make partial param must have one at least (either `next`, `error`, or `complete`) which seems not trivial.

**Comment by felixfbecker** [comment]
you could add overloads for all 2^3 cases. But why would you want this? Can't you just return the source if no argument is passed? Where's the benefit to restricting it?

**Comment by kwonoj** [comment]
Functionally it'll work as you'd described. Reason for this is mostly about explicitness of api definition signature - compare to `subscribe` doesn't have any observer contract param, `do` is all about triggering side effect by provided handler and would not like to implicit assumption you could do `do()` which actualy doesn't `do` anything. We're trying to make TS definition as correct api signature even JS user can refer it to clarify behavior of api.

**Comment by artaommahe** [comment]
this `do(null, () => null)` does not work with `strictNullChecks` enabled
```
[ts] Argument of type 'null' is not assignable to parameter of type '(x: IUser) => void'.
```

**Comment by martinsik** [comment]
@artaommahe You can use `undefined` instead:
```
do(undefined, () => null)
```
