### ISSUE TITLE
toPromise not work

### ISSUE THREAD

**Issue by tossp** [ReactiveX/rxjs#2536]
**RxJS version:** 5.0.1

**Code to reproduce:** https://jsfiddle.net/tossp/nmf9jg32/

**Comment by david-driscoll** [comment]
`toPromise` is essentially `observable.last().subscribe()`

If you add `.take(1)` just before you call `toPromise` then things will start to work.

ie
`example.do((value)=>console.log('do!!!',value)).take(1).toPromise()`

**Comment by tossp** [comment]
Thank you so much

**Comment by cjk** [comment]
I just spend 3 hours fighting `toPromise` returning _nothing_ and wondering why until I found this issue.
This behaviour was not obvious (to me) when reading the RxJs docs. Still trying to wrap my head around why `take(1)` solved it for me as well.

**Comment by david-driscoll** [comment]
@cjk `toPromise` will never resolve until the observable it is sourced from calls `complete`.  So if you bind to a keyboard event `Observable.fromEvent(document, 'onload')`, that observable will never complete, unless you force it to through something like `take(1)`.
