### ISSUE TITLE
Subscribe function parameter implicitly has any type

### ISSUE THREAD

**Issue by Karasuni** [ReactiveX/rxjs#2545]
Using TypeScript I'm constantly getting type errors for implicit any types on typed Observables.

Example:
```typescript
// Register a function returning a typed observable.
getRandomNumberObservable() : Observable<number> {
  return Observable.of(4); // chosen by fair dice roll.
                           // guaranteed to be random.
}

// Grab the observable and subscribe to it
getRandomNumberObservable().subscribe((number) =>
  console.log('My random number: %d', number)
);
```

This code will be greeted by `TS7006:Parameter 'number' implicitly has 'any' type.`.

The typings for `.subscribe()`:
```typescript
/**
 * Registers handlers for handling emitted values, error and completions from the observable, and
 *  executes the observable's subscriber function, which will take action to set up the underlying data stream
 * @method subscribe
 * @param {PartialObserver|Function} observerOrNext (optional) either an observer defining all functions to be called,
 *  or the first of three possible handlers, which is the handler for each value emitted from the observable.
 * @param {Function} error (optional) a handler for a terminal event resulting from an error. If no error handler is provided,
 *  the error will be thrown as unhandled
 * @param {Function} complete (optional) a handler for a terminal event resulting from successful completion.
 * @return {ISubscription} a subscription reference to the registered handlers
 */
subscribe(): Subscription;
subscribe(observer: PartialObserver<T>): Subscription;
subscribe(next?: (value: T) => void, error?: (error: any) => void, complete?: () => void): Subscription;
```

Is there a way to update the typing for this function such that TypeScript can properly resolve the type from the context?

**Comment by kwonoj** [comment]
this isn't due to rx typings - your compiler config enabled `noimplicitany` and it doesn't allow to auto infer by specifiyng param without explicit type. with this option enabled, you can observe same behavior on any other cases than other rx.

**Comment by Karasuni** [comment]
That is the issue. It shouldn't infer `any`. If you compare to `.map()` there the type would be correctly inferred as `Observable<T>`:

```typescript
// map.d.ts
export declare function map<T, R>(this: Observable<T>,
  project: (value: T, index: number) => R, thisArg?: any): Observable<R>;
```

The problem with `subscribe` is that it loses this type. Shouldn't it be `subscribe<T>(observer: PartialObserver<T>): Subscription<T>;` or similar?

**Comment by Karasuni** [comment]
I don't understand. I create an object `Observable<T>` and it has functions `map<T>` and `subscribe`. What other type is overruled at that point? You'd expect this to work with `do((x) => {})` and `.subscribe({ next: (x) => {}})` too, for example, since you're working specifically with the type you're observing.

**Comment by kwonoj** [comment]
You can simply try your suggestion to see how it works.

[Playground link](https://www.typescriptlang.org/play/#src=class%20Observable%3CT%3E%20%7B%0D%0A%20%20%20%20subscribe%3CT%3E(next%3A%20(value%3A%20T)%20%3D%3E%20void)%20%7B%0D%0A%20%20%20%20%20%20%20%20%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Aclass%20ObservableActual%3CT%3E%20%7B%0D%0A%20%20%20%20subscribe%3CR%3E(next%3A%20(value%3A%20R)%20%3D%3E%20void)%20%7B%0D%0A%20%20%20%20%20%20%20%20%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Aclass%20CustomType%20%7B%0D%0A%20%20%20%20id%3A%20string%0D%0A%7D%0D%0A%0D%0Aconst%20v1%20%3D%20new%20Observable%3CCustomType%3E()%0D%0Av1.subscribe((a)%20%3D%3E%20a.id)%3B%20%2F%2Fyou%20see%20compiler%20error%2C%20T%20is%20inferred%20to%20%7B%7D%0D%0A%0D%0Aconst%20v2%20%3D%20new%20ObservableActual%3CCustomType%3E()%0D%0Av2.subscribe((a)%20%3D%3E%20a.id)%3B%20%2F%2Fthis%20is%20actual%20shape%20of%20generic%20you%20suggested%20to%20have%20subscribe%20have%20generic%0D%0A%0D%0A%2F%2Fto%20make%20type%20works%20with%20your%20suggestion%2C%20you%20have%20to%20specify%20type%20for%20each%20subscribe%20calls%20%0D%0Av1.subscribe%3CCustomType%3E((a)%20%3D%3E%20a.id)%3B%0D%0Av2.subscribe%3CCustomType%3E((a)%20%3D%3E%20a.id)%3B)

```js
class Observable<T> {
    subscribe<T>(next: (value: T) => void) {
        
    }
}

class ObservableActual<T> {
    subscribe<R>(next: (value: R) => void) {
        
    }
}

class CustomType {
    id: string
}

const v1 = new Observable<CustomType>()
v1.subscribe((a) => a.id); //you see compiler error, T is inferred to {}

const v2 = new ObservableActual<CustomType>()
v2.subscribe((a) => a.id); //this is actual shape of generic you suggested to have subscribe have generic

//to make type works with your suggestion, you have to specify type for each subscribe calls 
v1.subscribe<CustomType>((a) => a.id);
v2.subscribe<CustomType>((a) => a.id);
```

This is really about behavior of typescript, not about RxJS.

**Comment by david-driscoll** [comment]
What version of the compiler are you using?  With the current playground, I'm not able to get any errors to popup, with similar code.

[see here](http://www.typescriptlang.org/play/#src=class%20Observable%3CT%3E%20%7B%0D%0A%20%20%20%20public%20static%20_of%3CR%3E(value%3A%20R)%3A%20Observable%3CR%3E%20%7B%20return%20undefined%3B%20%7D%0D%0A%0D%0A%20%20%20%20public%20subscribe(next%3A%20(value%3A%20T)%20%3D%3E%20void)%20%7B%0D%0A%20%20%20%20%20%20%20%20%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0A%2F%2F%20Register%20a%20function%20returning%20a%20typed%20observable.%0D%0Afunction%20getRandomNumberObservable()%20%3A%20Observable%3Cnumber%3E%20%7B%0D%0A%20%20return%20Observable._of(4)%3B%20%2F%2F%20chosen%20by%20fair%20dice%20roll.%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20guaranteed%20to%20be%20random.%0D%0A%7D%0D%0A%0D%0A%2F%2F%20Grab%20the%20observable%20and%20subscribe%20to%20it%0D%0AgetRandomNumberObservable().subscribe((number)%20%3D%3E%0D%0A%20%20console.log('My%20random%20number%3A%20%25d'%2C%20number)%0D%0A)%3B%0D%0A)
