### ISSUE TITLE
takeUntil does not complete when notifier completes.

### ISSUE THREAD

**Issue by jbaudanza** [ReactiveX/rxjs#2549]
**RxJS version:**
5.3.0

**Code to reproduce:**

```js
Rx.Observable.interval(1000)
    .takeUntil(Rx.Observable.empty()) // complete event should terminate observable
    .subscribe(
      (value) => console.log('next', value),
      (err) => console.log('error', error),
      () => console.log('complete')
    )
```

**Expected behavior:**
According to the docs for `takeUntil`, the complete notification from `Observable.empty` should cause the outer observable to unsubscribe from the source and complete right away.

From the docs:
>  `takeUntil` subscribes and begins mirroring the source Observable. It also
>  monitors a second Observable, `notifier` that you provide. If the `notifier`
>  emits a value **or a complete notification**, the output Observable stops
>  mirroring the source Observable and completes.

**Actual behavior:**
Outer observable runs without interruption.
> next 0
> next 1
> next 2
> next 3

etc..

**Additional information:**

I suspect that either the docs are out-of-date/wrong, or this line needs to be updated: https://github.com/ReactiveX/rxjs/blob/master/src/operator/takeUntil.ts#L76

I'm happy to submit a PR for either scenario. Let me know.

**Comment by kwonoj** [comment]
is this #2160 and https://github.com/ReactiveX/rxjs/pull/2521 ?

**Comment by jbaudanza** [comment]
Yes, seems so. I apologize for the dupe. FWIW, I would vote to have the behavior changed rather than the docs.
