### ISSUE TITLE
Type of mergeAll() returns Subscribable instead of Observable

### ISSUE THREAD

**Issue by felixfbecker** [ReactiveX/rxjs#2551]
`mergeAll()` returns an `Observable`, but the typings say it returns a `Subscribable`. The typings are also a bit weird because they don't use `ObservableInput`. `Observable<string>.mergeAll()` returns `string`.

Actual:
```ts
export declare function mergeAll<T>(this: Observable<T>, concurrent?: number): T;
export declare function mergeAll<T, R>(this: Observable<T>, concurrent?: number): Subscribable<R>;
```

Expected:
```ts
export declare function mergeAll<T>(this: Observable<ObservableInput<T>>, concurrent?: number): Observable<T>;
```

**Comment by david-driscoll** [comment]
Last time we tried this (granted that was a while ago!) we ran into issues where we couldn't add additional constraints to the type `T` in the `Observable<T>` interface.  I'm not sure if that problem still continues today, it's worth exploring again.

**Comment by felixfbecker** [comment]
Well, right now the signature is completely broken:
```ts
let obs: Observable<string[]>
obs.mergeAll() // returns string, can't use any operators
obs.mergeAll<Observable<string>>() // error, Observable<string> is not assignable to string[]
obs.mergeAll<any>() // returns any, type safety lost even for operators
obs.mergeAll<any, string>() // returns Subscribable, can't use any operators
```
Even if this isn't possible I would prefer a return type of `Observable<any>` or `Observable<T>` where T is user-provided, because casting in an operator chain looks super ugly with the parenthesis.

**Comment by david-driscoll** [comment]
I just saw the actual problem you're seeing with the subscribable... That is definitely a bug we need to fix asap.  I'll look at that shortly.

**Comment by prolink007** [comment]
What is the status on getting this fixed?
