### ISSUE TITLE
progressSubscriber not work when downloading!

### ISSUE THREAD

**Issue by windreamlion** [ReactiveX/rxjs#2553]
Dear all:

when i create ajax to get a image, i can't get  onProgress when downloading, 
i need some help,Thx!!

Observable.ajax({url, crossDomain: true, ...options})

**RxJS version: 5.3.0**

**Code to reproduce:**

let ps = new Subscriber((e)=>console.log(e));

Observable.ajax({'imgUrl', crossDomain: true, progressSubscriber:ps,timeout:5000,}).subscribe()

**Expected behavior:**

i hope get onProgress eventData on downloading;

**Actual behavior:**

progressSubscriber not work;

**Additional information:**

i saw the code ,maybe root.XDomainRequest  interrupt the xhr.onprogress ;

if (root.XDomainRequest) {
          xhr.onprogress = xhrProgress;
}

**Comment by Brooooooklyn** [comment]
see https://github.com/ReactiveX/rxjs/issues/2428

**Comment by benlesh** [comment]
Seems to be a duplicate of #2448
