### ISSUE TITLE
Adding operators does not work when bundled with rollup

### ISSUE THREAD

**Issue by slikts** [ReactiveX/rxjs#2554]
[Repo with a simplified reproducible example](https://github.com/slikts/rxjs-rollup-example)

```js
import { Observable } from 'rxjs/Observable'
import 'rxjs/add/operator/scan'
console.log(Observable.prototype.scan) // -> undefined
```

**Comment by kwonoj** [comment]
I'd like to suggest take this to rollup side first, caused I noticed below:

code:
```js
import { Observable } from 'rxjs/Observable'
import 'rxjs/add/observable/never'; //any static creation operator doesn't matter like of, empty...
import 'rxjs/add/operator/scan';

console.log(Observable.prototype.scan)
```
result:
![image](https://cloud.githubusercontent.com/assets/1210596/25048485/91121ac4-20f1-11e7-9b1a-5348e1b0526f.png)

code:
```js
import { Observable } from 'rxjs/Observable'
import 'rxjs/add/operator/scan'

console.log(Observable.prototype.scan)
```
![image](https://cloud.githubusercontent.com/assets/1210596/25048573/078c71f4-20f2-11e7-8285-0152ebb4c75f.png)

just importing any static creation method makes prototype patch works. if you compare those 2 bundled output results, only if static creation method imported prototype patch is actually bundled.

![image](https://cloud.githubusercontent.com/assets/1210596/25048736/c8baf2a6-20f2-11e7-968b-9c75f5a8fe02.png)

**Comment by slikts** [comment]
I've made a [simplified example][branch] for the problem. This is the part from the distributed package that causes the problem in rollup:

```js
var Observable_1 = require('./Observable')
var scan_1 = require('./scan')
Observable_1.Observable.prototype.scan = scan_1.scan
```
Changing it to this makes it work:
```js
var Observable = require('./Observable').Observable
var scan = require('./scan').scan
Observable.prototype.scan = scan
```
So I guess the actual problem is with [rollup-plugin-commonjs][plugin].

[branch]: https://github.com/slikts/rxjs-rollup-example/tree/simplified
[plugin]: https://github.com/rollup/rollup-plugin-commonjs

**Comment by kwonoj** [comment]
I'm closing issue for now as it seems upstream issue of bundler. Feel freely reopen if there's further detail shows Rx doing something wrong.
