### ISSUE TITLE
Timeout can't take error as parameter

### ISSUE THREAD

**Issue by wbhob** [ReactiveX/rxjs#2555]
**RxJS version:** 5.1.1

**Code to reproduce:**
```ts
            let sub = this.http.get(this.url + 'teams/' + teamId, {
                headers: this.headers
            })
                .retryWhen(error => error.delay(500))
                .timeout(2000, new Error('delay exceeded'))
```

**Expected behavior:** Should not throw compiler error when using error as a parameter for the timeout method of an observable.

**Actual behavior:** It throws an error saying that `Argument of type 'Error' is not assignable to parameter of type 'IScheduler'.`

**Additional information:** Angular v4

**Comment by kwonoj** [comment]
https://github.com/ReactiveX/rxjs/blob/master/CHANGELOG.md#500-rc5-2016-12-07

**Comment by wbhob** [comment]
@kwonoj how can I pass data into the timeout error?

**Comment by kwonoj** [comment]
@wbhob it is no longer supported to carry forward different error (or any other object) when timeout error is being thrown. If you really need to deliver error other than default timeouterror, you may need `.catch()` then rethrow by `Observable.throw` your custom error.

**Comment by wbhob** [comment]
What does that look like (thanks for all your help by the way)

**Comment by matthewwithanm** [comment]
For people who stumble on this later, you can use `.timeoutWith(2000, Observable.throw(new Error('delay exceeded')))` 😊
