### ISSUE TITLE
Don't publish typings folder

### ISSUE THREAD

**Issue by felixfbecker** [ReactiveX/rxjs#2561]
The typings folder with installed TypeScript declarations from the typings definition manager is not .npmignored. The definitions in there are all global, which causes conflicts, because you cannot define the same global symbols twice. It is not possible to use own typings for node without compiler conflicts because rxjs has its own version bundled (`registry:env/node#6.0.0+20161105011511`). Environmental (ambient) typings should not be bundled. All other typings in the typings folder are devDependencies, so I would completely .npmignore the folder.

**Comment by kwonoj** [comment]
makes sense. Eventually we have to move all types to @types devdep to avoid this issue.

**Comment by kwonoj** [comment]
relates to https://github.com/ReactiveX/rxjs/issues/2437 .

**Comment by felixfbecker** [comment]
While that would make sense for module dependencies, environmental typings like `@types/node` must still remain a devDependency, because they are still global and would still cause conflicts.

**Comment by kwonoj** [comment]
yes, as said.
>to @types devdep to avoid this issue

I'll leave this issue opened, cause npmignore should be updated before moving into @types.
