### ISSUE TITLE
ReplaySubject.asObservable with thrown error in next after subscribing

### ISSUE THREAD

**Issue by repkins** [ReactiveX/rxjs#2565]
Hello!

I have faced with issue regarding of ReplaySubject `asObservable()` returning Observable behavior. I have a ReplaySubject instance, from which have "extracted" Observable-like instance with method `asObservable()`. While Observable instance has no any subscribers, observable instance ReplaySubject instance have received one notiication using `.next(...)`. When i do subscribe with function, where has `throw ...` error, then unexpectly it **silently swallows error** instead of re-throwing it.

Code below:

    let subject = new ReplaySubject<boolean>();
    let obs$ = subject.asObservable();

    subject.next(true);

    obs$.subscribe(() => {
      throw new Error('Error thrown in subscriber')
    });

RxJS version: 5.2.0

**Comment by kwonoj** [comment]
maybe it's same as https://github.com/ReactiveX/rxjs/issues/2564? I thought in #2564 it's shallowed by jasmine, seems not.

**Comment by repkins** [comment]
No, there is not being used jasmine.

**Comment by kwonoj** [comment]
yes, that's what I mean. I originally thought it's jasmine, and since your issue isolated it I came to think #2564 is not jasmine side issuen basically this 2 issues looks same to me. @repkins
