### ISSUE TITLE
How often are the docs published? This commit does not appear to be live yet it is in the stable, released, 5.3.0 version.

### ISSUE THREAD

**Issue by nelsonjchen** [ReactiveX/rxjs#2567]
https://github.com/ReactiveX/rxjs/commit/3ced24f2192289e441e88368c02c9df86bcb11e0

This commit is in `5.3.0` and `5.3.0` appears to have been released to NPM yet this commit does not appear to be in effect at:

http://reactivex.io/rxjs/manual/installation.html

**Comment by kwonoj** [comment]
Currently there is no aligned schedules between package version publishing, cause there is no automatic mechanism to link for those and need some manual handcrafting for it. We're trying to keep up to date docs as much as we can but sometimes it can be bit fall behind.
