### ISSUE TITLE
Calling pluck is cumbersome, when working with runtime generated arrays.

### ISSUE THREAD

**Issue by awildturtok** [ReactiveX/rxjs#2572]
When working with user input and pluck, it is rather ugly to write code that uses dynamic arrays: Where you would just compose with previously known values, you now have to call `pluck.apply`, which is ugly and additionally harder to maintain.

**RxJS version:**
5.1.0
**Code to reproduce:**
```
pluck.apply(
    this.subject
        .filter(...)
        .map(...)
    , path.split("/")
)
    .filter((val: any) => val != undefined);
```
**Expected behavior:**
```
this.subject
    .filter(...)
    .map(...)
    .pluck(path.split("/"))
    .filter((val: any) => val != undefined);
```

**Comment by david-driscoll** [comment]
@awildturtok we could add an additional operator for handling arrays with pluck, however you can also use the spread (`...`) operator in mean time.

```typescript
this.subject
    .filter(x => !!x)
    .map(x => ({ x }))
    .pluck(...path.split("/"))
    .filter((val: any) => val != undefined);
```

**Comment by awildturtok** [comment]
This seems like a good solution thank you! I am rather new to ts and had no clue this existed.

**Comment by david-driscoll** [comment]
No problem!!

Infact it's not something TypeScript specific it is part of ECMAScript, MDN has a good run down [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_operator)

**Comment by kwonoj** [comment]
It seems issue itself have workaround via latest specs, do we want to push forward to discuss updating operator behavior or consider it as resolved? Personally I think (at this moment) we may not need to think of changing operator behavior. opinions? /cc @awildturtok @david-driscoll

**Comment by kwonoj** [comment]
Closing as inactive, as well as behavior itself works with ES specs at the moment.
