### ISSUE TITLE
Observable.concat typings seem too loose

### ISSUE THREAD

**Issue by paulspiteri** [ReactiveX/rxjs#2573]
RxJS version: 5.3.0

Just want to check if the following code is considered acceptable? (it does work)

    const obs1 = Observable.of<string>('abc');
    const obs2 = Observable.of<boolean>(false);
    const obs3 = Observable.concat(obs1, obs2);

Personally, I'd hope it would fail.

Thanks
Paul Spiteri

**Comment by kwonoj** [comment]
Would you mind share bit detailed reason why you're expecting it would fail?

Above snippet's `concat` makes type inference to resolve into `Observable<string|boolean>`, as we have supported numbered generic params for these kind cases. (https://github.com/ReactiveX/rxjs/blob/e38711379f357f55290ead7fabcf8c70c5b31961/src/operator/concat.ts#L72-L77) as `concat` itself allow polymorphic forms of value types, I don't see reason type checking asserts for this case while runtime should work without problem.

**Comment by paulspiteri** [comment]
Ok I guess I'm concerned that there's no way to explicitly turn on the support for different types in the same stream. 
As there are looser typings (i.e. ones with numbered generic params) as overloads, it's  basically impossible to get the "standard" one to fail - it'll just be skipped.

export function concatStatic<T>(...observables: (ObservableInput<T> | IScheduler)[]): Observable<T>;

I suppose this is a common problems when you have so many overloads with the same name.

**Comment by kwonoj** [comment]
I don't think that's intended scope of type definition supports. type definition try to match api's behavior as much as possible, and while actual underlying api does allows param have polymorphic form its type definition should reflect its behavior precisely.

this is not loose / poor support of type assert, just reflecting api correctly.

**Comment by paulspiteri** [comment]
Ok, sorry to reopen the issue but I've done some more testing which took me away from looking at the overloads with multiple type params.

If you delete all the overloads of concat except for:
```export declare function concatStatic<T>(...observables: (ObservableInput<T> | IScheduler)[]): Observable<T>;```

even then, the compiler is happy with:
```    const obs1 = Observable.of<string>('abc');
    const obs2 = Observable.of<boolean>(false);
    const obs3 = Observable.concat(obs1, obs2);```

Surely that isn't the intention? Only if ObservableInput<T> is changed to Observable<T> does the expected error occur.

Many thanks
