### ISSUE TITLE
withLatestFrom called twice on a single subscription

### ISSUE THREAD

**Issue by afriedma** [ReactiveX/rxjs#2581]
**RxJS version:**
5.2.0
**Code to reproduce:**
```
sowSubject: BehaviorSubject<Array<any>> = new BehaviorSubject(Array<any>());
	sowObservable: Observable<Array<any>> = this.sowSubject.asObservable();
	
	realtimeSubject: Subject<any> = new Subject();
	realtimeObservable: Observable<any> = this.realtimeSubject.asObservable();

        notifications: Observable<any[]> = new BehaviorSubject([]).asObservable();

        var sowObserver = sowObservable
            .withLatestFrom(notifications, (sow, current) => {
                return current;
            });
        var realtimeObserver = realtimeObservable
            .withLatestFrom(notifications, (realtime, current) => {
                return current;
            });
        
        notifications = Observable.merge(realtimeObserver, sowObserver);
```
        

**Expected behavior:**
Anytime next is called on sowSubject or realtimeSubject, callback is raised in the body of withLatestFrom once
**Actual behavior:**
Anytime next is called on sowSubject or realtimeSubject, callback is raised in the body of withLatestFrom twice
**Additional information:**
In my actual code, notifications Observable is being subscribed to via Angular Async pipe.

**Comment by afriedma** [comment]
Hi,

Was anyone able to take a look at the issue?  Please advise.
If I missed anything in description, please let me know, I will fix it.

Thanks in advance,

Alex

**Comment by trxcllnt** [comment]
@afriedma I'm running your example in [esnextb.in](https://esnextb.in/?gist=fe931a1b030a2997aa9e6168c1fec25a) and seeing correct results. Do you have another example where withLatestFrom isn't working?

**Comment by afriedma** [comment]
@trxcllnt , thanks for your reply.

Please see below plunkr, it reproduces the issue
https://plnkr.co/edit/yW3sDygDwCb86hP29tdc?p=preview

I think I figured what the issue is, as async pipe used twice, but if you can suggest a workaround, it would be super helpful.
As I do need to check length of the array, to avoid displaying other data.

**Comment by trxcllnt** [comment]
@afriedma it looks like you're trying to aggregate the results of two sources into a list. Have you considered merging the Observables and scanning the merged results into a list? Something like:

```typescript
this.notifications = Observable.merge(
    this.sowObservable,
    this.realtimeObservable
).scan((xs, x) => [...xs, x], []);
```

**Comment by afriedma** [comment]
Thank you for reply.  This issue has been solved with native angular changes.  Async pipe was subscribing twice and duping the results.  Workaround below, in case someone has a similar issue.


<ng-container *ngIf="heroes|async;let heroesItems">
        <ul class="custom-dropdown" *ngIf="heroesItems.length > 0">
                <li *ngFor="let hero of heroesItems">{{hero.name}}</li>
        </ul>
</ng-container>



On May 8, 2017, at 4:26 PM, Paul Taylor <notifications@github.com<mailto:notifications@github.com>> wrote:


@afriedma<https://github.com/afriedma> it looks like you're trying to aggregate the results of two sources into a list. Have you considered merging the Observables and scanning the merged results into a list? Something like:

this.notifications = Observable.merge(
    this.sowObservable,
    this.realtimeObservable
).scan((xs, x) => [...xs, x], []);

**Comment by kwonoj** [comment]
Think issue is resolved, closing.
