### ISSUE TITLE
Error from Immediate when using asap scheduler in nativescript-angular application

### ISSUE THREAD

**Issue by daveware-nv** [ReactiveX/rxjs#2584]
**RxJS version:**
5.2.0
**Code to reproduce:**
```
import {Observable} from "rxjs/Observable";
import {asap} from "rxjs/scheduler/asap";

Observable.from([10, 20, 30], asap).subscribe((val) => {
    console.log(val);
});
```
**Expected behavior:**
```
10
20
30
```
**Actual behavior:**
```
TypeError: Cannot read property 'currentlyRunningATask' of undefined
JS:     at ImmediateDefinition.runIfPresent (file:///data/data/org.nativescript.scratch/files/app/tns_modules/rxjs/util/Immediate.js:137:17) //this corresponds to if (this.currentlyRunningATask) { in ImmediateDefinition.prototype.runIfPresent
JS:     at result (file:///data/data/org.nativescript.scratch/files/app/tns_modules/rxjs/util/Immediate.js:84:25) //this corresponds to hander.apply..... in ImmediateDefinition.prototype.partiallyApplied
JS:     at ZoneDelegate.invokeTask (file:///data/data/org.nativescript.scratch/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:398:31)
JS:     at Object.onInvokeTask (file:///data/data/org.nativescript.scratch/files/app/tns_modules/@angular/core/bundles/core.umd.js:4143:37)
JS:     at ZoneDelegate.invokeTask (file:///data/data/org.nativescript.scratch/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:397:36)
JS:     at Zone.runTask (file:///data/data/org.nativescript.scratch/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:165:47)
JS:     at ZoneTask.invoke (file:///data/data/org.nativescript.scratch/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:460:38)
JS:     at timer (file:///data/data/org.nativescript.scratch/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:1634:29)
JS:     at ZoneDelegate.invoke (file:///data/data/org.nativescript.scratch/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:365:26)
JS:     at Object.onInvoke (file:///data/data/org.nativescript.scratch/files/app/tns_modules/@angular/core/bundles/core.umd.js:4152:37)
JS:     at ZoneDelegate.invoke (file:///data/data/org.nativescript.scratch/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:364:32)
JS:     at Zone.runGuarded (file:///data/data/org.nativescript.scratch/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:138:47)
JS:     at file:///data/data/org.nativescript.scratch/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:116:29
JS:     at Object.run (file:///data/data/org.nativescript.scratch/files/app/tns_modules/tns-core-modules/timer/timer.js:18:13)

```

**Additional information:**
Unfortunately I haven't been able to get this to fail in a smaller example, only as part of a nativescript-angular (3.0rc) application, I've filed the bug here since from my naive inspection of the stack trace there is a problem with rxjs.

It seems to me that the `Immediate.runIfPresent` method shouldn't pass itself to `partiallyApplied` without using some method of fixing `this` since the very first thing it does is dereference `this`, so it can't ever be safely called by itself without taking such a measure. 

Let me know if I've misinterpreted something and need to file this with nativescript instead, or fix my own code.

**Comment by kwonoj** [comment]
In a first glimpse, this looks like internal patched by zones.js introduces some unexpected behavior. What happens if you execute same code without zones.js?

**Comment by daveware-nv** [comment]
It's probably not possible to run the nativescript-angular app without zone. But I did try running the code by itself in node and it ran correctly as expected. However it never touched `ImmediateDefinition.runIfPresent` in this scenario.

**Comment by kwonoj** [comment]
@daveware-nv it's cause synchronous observable branches not to take those execution paths for scheduler (which makes think it may be related with zone.js, cause plain node env synchronous observable doesn't hit it) if you try simple async observable like `Rx.Observable.interval(100, Rx.Scheduler.asap).take(3)` on plain node, you can see it hits.

**Comment by daveware-nv** [comment]
`Rx.Observable.interval(100, Rx.Scheduler.asap).take(3)` still doesn't ever trigger `ImmediateDefinition.runIfPresent` for me in plain node.

I fiddled a bit more with my in place install of rxjs in my nativescript-angular application and adding a method to `ImmediateDefinition` like:
```
  runIfPresentWrap() {
    return (handle: any) => {
      this.runIfPresent(handle);
    };
  }
```
And then replacing the instances of `partiallyApplied(x.runIfPresent)` with `partiallyApplied(x.runIfPresentWrap())` prevents the crash from occurring and seems to at least superficially do the right thing.

I'd like to try it out from a properly built one, but the package.json seems to be for the `@reactivex/rxjs` cjs build rather than the `rxjs` CommonJS/ES6 build which is what nativescript-angular references. Are they similar enough that I can just change the name in the package.json?

**Comment by benlesh** [comment]
Closed because of lack of information.
