### ISSUE TITLE
Observable.of is observing changes but Subject subscribe is not (Angular)

### ISSUE THREAD

**Issue by saurabhraja** [ReactiveX/rxjs#2590]
Observable.of is observing changes for a property. But the same doesn't seem to be working with Subject. Here is my scenario,

I have a private property for my component.
`private cellColor: string = "orange";`

I'm using Observable.of to mimick an api call and update cellColor;

```
Observable.of(true)
      .delay(2000)
      .subscribe((success) => {
        if(success){
          this.cellColor = 'white';
          this.cdr.markForCheck();
        }
      });
```
This successfully updates cellColor property to white and the view also is updated.

However, my actual requirement is to use a Subject for inter component communication. Here in my case, I have created a Subject inside my common service. From component 1 I'm pushing the new value for cellColor property and subscribing to it from Component 2. On subscription, the property cellColor gets updated but view does not. Below is the code snippet.

```
this.subscription = this.styleService.getCellColorMessage()
      .subscribe((message) => {
          this.cellColor = message.cellColor; 
          this.cdr.markForCheck(); 
        });
```

What is the catch here?

**Comment by jfinci1** [comment]
Certainly does not sound like a problem with this library perse.  I use the same pattern regularly with no issue.  Can you show your component '1' and how it is interacting with it?

**Comment by saurabhraja** [comment]
Simply by calling like so,

`this.myService.sendCellColorMessage('white');`

And inside my service I have two functions for sending and receiving messages.

```
private mySubject = new Subject<any>();

sendCellColorMessage(color: string) {
    this.mySubject .next({ cellColor: color });
  }
 
  getCellColorMessage(): Observable<any> {
    return this.mySubject .asObservable();
  }
```

**Comment by jfinci1** [comment]
Can you try to just return the subject in `getCellColorMessage` and subscribe to it? Perhaps mark the subject as readonly as well.

**Comment by jfinci1** [comment]
I think you can ignore the above.  How are you providing the service?  If you are not providing it via the `app.module`, and instead are providing it to each component, they will not share the same instance of your service.

**Comment by kwonoj** [comment]
as discussed above, it is hard to say if it's related with practices of writing ng component or incorrect behavior on Rx side. It'd be helpful to provide minimal repo isolated from ng but using Rx only to reproduce this issue.

**Comment by saurabhraja** [comment]
@jfinci1 I'm providing the service via `app.module` only.

**Comment by kwonoj** [comment]
Closing issue as inactivity. If this is still issue, please provide details via isolated examples using Rx only.
