### ISSUE TITLE
Synchronous inspection

### ISSUE THREAD

**Issue by felixfbecker** [ReactiveX/rxjs#2591]
Provide an API to synchronously check whether an Observable has already completed or not.

### Use Case
Suppose you have a function that returns an Observable, but caches it so subsequent calls return the same Observable.

```ts
let cached: Observable<number> | undefined;
function foo(): Observable<number> {
  if (!cached) {
    cached = Observable.of(123).delay(1000).publishReplay().refCount();
  }
  return cached;
}
```

Also, this function is traced, for example with [OpenTracing](https://github.com/opentracing/opentracing-javascript).

Currently there are two options:
#### Trace only the first invocation
Major disadvantage: Subsequent calls that get a cached Observable that has not completed yet are not traced even though waiting for the cached Observable to complete is part of the operation.
  
```ts
let cached: Observable<number> | undefined;
function foo(childOf: Span): Observable<number> {
  if (!cached) {
    const span = childOf.tracer().startSpan('foo', { childOf });
    cached = Observable.of(123)
      .delay(1000)
      .publishReplay()
      .refCount()
      .finally(() => {
        span.finish();
      });
  }
  return cached;
}
```

#### Trace every invocation
Disadvantage: Subsequent calls that get an already-completed cached Observable get a zero-length span. That can spam the trace with countless of zero-length spans.

```ts
let cached: Observable<number> | undefined;
function foo(childOf: Span): Observable<number> {
  const span = childOf.tracer().startSpan('foo', { childOf });
  if (!cached) {
    cached = Observable.of(123).delay(1000).publishReplay().refCount();
  }
  return cached.finally(() => {
    span.finish();
  });
}
```

### Ideal solution:
Trace all calls, but only if the Observable didn't complete yet.
This requires an API for synchronous inspection of the completion (like [Bluebird has](http://bluebirdjs.com/docs/api/isfulfilled.html)): 
```ts
let cached: Observable<number> | undefined;
function foo(childOf: Span): Observable<number> {
  if (!cached) {
    cached = Observable.of(123).delay(1000).publishReplay().refCount();
  }
  if (cached.isCompleted) {
    return cached;
  }
  const span = childOf.tracer().startSpan('foo', { childOf });
  return cached.finally(() => {
      span.finish();
  });
}
```

**Comment by benlesh** [comment]
Given that an Observable is basically a function that accepts an observer (and does some things to provide safety), there's really no way to do what you want to do for *every* observable. However, if you're looking at a Subject, you could test `closed`. 

Otherwise, you'd want to just do something yourself. Perhaps with `finally` like:

```js
let completed = 0;
const counted$ = someObservable$.finally(() => completed++);
```

now you can check `completed > 0` to know if `counted$` has ever been run to completion. You may or may not want to combine that with some sort of multicasting (`share` for example).

**Comment by staltz** [comment]
Yes seems like it's important to understand the distinction between an Observable and a Subject. As a rule of thumb, it helps to replace the word Observable with "an *idea* of many values", so the phrase "check whether an *idea of many values* has already completed or not" makes no sense since an idea is just imaginary, not executing for real.

**Comment by felixfbecker** [comment]
But in this case I am using the publishReplay operator, so it is not anymore just an object that wires you up to a producer once you subscribe, it already holds all the values and replays them on subscription, so it knows about whether it completed or not.

**Comment by staltz** [comment]
publishReplay hides the Subject behind an Observable, so again you get just an idea of an async execution, not the actual execution. You could use multicast and pass a Subject, which you then can use with `closed` like Ben said. Note that publishReplay implementation is very thin, it just calls multicast.

**Comment by felixfbecker** [comment]
I am struggling to implement this with a Subject, could someone give me an example code?

**Comment by benlesh** [comment]
```ts

if (!cached) {
  const replaySubject = new ReplaySubject();
  cached = source$.multicast(replaySubject).refCount();
}
if (replaySubject.closed) {
  return replaySubject;
}
// whatever else you're doing here.
```
