### ISSUE TITLE
ObservableInput not exported

### ISSUE THREAD

**Issue by felixfbecker** [ReactiveX/rxjs#2600]
**RxJS version:** 5.3.0

I find it often helpful to explicitly type a `mergeMap` function:
```ts
.mergeMap((definition: ts.DefinitionInfo): Observable<SymbolLocationInformation> => {
  // ...
});
```
so when I change the return type of some code, TS compile errors are narrowed to the arrow function instead of the whole outer method.

unfortunately, that fails if there is an early return like this:
```ts
.mergeMap((definition: ts.DefinitionInfo): Observable<SymbolLocationInformation> => {
  if (!definition.fileName) {
     return [];
  }
  // ...
});
```
I would like to type the function to return `ObservableInput` instead, but it is not exported.

**Comment by kwonoj** [comment]
`ObservableInput` is exported but not only for top level, and TS can import individual like `{ObservableInput} from 'rxjs/Observable` or similar (I might incorrect for actual path, it's just example).

We don't plan to export everything into top level export, especially if it's type for TS definition.
