### ISSUE TITLE
Rx.Subject with differing in & out types

### ISSUE THREAD

**Issue by jmzhang** [ReactiveX/rxjs#2602]
I'm trying to create a Subject using `Subject.create(observer, observable)`, where my observer takes an object of type `R` and the observable emits objects of type `T`. But the function signature disallows this in typescript. So I'm wondering if it is absolutely necessary to have the destination and the source share the same type parameter? 

It seems to me that adding another type parameter to `AnonymousSubject` will do the job:
```
export class AnonymousSubject<T, R> extends Subject<T> {
  constructor(protected destination?: Observer<R>, source?: Observable<T>) {
    super();
    this.source = source;
  }

  next(value: R) {
    const { destination } = this;
    if (destination && destination.next) {
      destination.next(value);
    }
  }

  ...
}
```

**Comment by mickliddy** [comment]
I have encountered a similar problem while trying to abstract out a few common patterns in my code. I'm not sure if my approach to antithetical to the intentions of the developers of this library, or if it's a valid use case which has been overlooked.

**Comment by benlesh** [comment]
Closing as stale.
