### ISSUE TITLE
Scheduler.asap doesn't use `nextTick`?

### ISSUE THREAD

**Issue by matthewwithanm** [ReactiveX/rxjs#2603]
**RxJS version:**

5.4.0

[**Code to reproduce:**](https://runkit.com/583f40c75c4c7e0014a0f256/591b4a96bd9b4000111389f6)

```js
process.nextTick(() => { console.log('nextTick 1'); });
setImmediate(() => { console.log('setImmediate 1'); });
Observable.of('now!', Scheduler.asap).subscribe(x => console.log(x));
setImmediate(() => { console.log('setImmediate 2'); });
process.nextTick(() => { console.log('nextTick 2'); });
```

**Expected behavior:**

```
"nextTick 1"
"now!"
"nextTick 2"
"setImmediate 1"
"setImmediate 2"
```

**Actual behavior:**

```
"nextTick 1"
"nextTick 2"
"setImmediate 1"
"now!"
"setImmediate 2"
```

**Additional information:**

Am I misunderstanding something? I reached for the asap scheduler because the docs say it's supposed to schedule using nextTick (when available), but it doesn't appear to be doing so.

**Comment by trxcllnt** [comment]
@matthewwithanm hey Matt, sorry for the confusion. The asap scheduler attempts to use setImmediate, and falls back to nextTick if it isn't available (you can see how it's resolved [here](https://github.com/ReactiveX/rxjs/blob/master/src/util/Immediate.ts#L23)). Let me know if you have any suggestions on a better approach.

**Comment by matthewwithanm** [comment]
@trxcllnt Cool. I saw that but I wasn't sure if it was intended, since [the scheduler docs][1] say otherwise:

> Schedules on the micro task queue, which uses the fastest transport mechanism available, either Node.js' process.nextTick() or Web Worker MessageChannel or setTimeout or others. Use this for asynchronous conversions.

Not to mention that the "asap" name is kinda misleading I think, since there's another async option that would schedule it sooner.

Does that mean there's no `nextTick` scheduler anymore?

[1]: https://github.com/ReactiveX/rxjs/blob/master/doc/scheduler.md#scheduler-types

**Comment by hexuanzhang** [comment]
@trxcllnt Truly appreciate your explanation. But now i have a question about the async scheduler. According to [the scheduler docs](https://github.com/ReactiveX/rxjs/blob/master/doc/scheduler.md#scheduler-types), the async scheduler works with setInterval. Does it excute like setInterval that will push into macroTasks other than microTasks?

**Comment by trxcllnt** [comment]
@hexuanzhang I'm not sure what your asking exactly. The async scheduler delegates periodic time scheduling to the runtime's setInterval.

**Comment by trxcllnt** [comment]
@matthewwithanm that sounds like a mistake in the docs. I believe the intention was to always use setImmediate if available, as that's the standardized method for microtask scheduling. As far as I know, process.nextTick is a node-specific API they invented to enforce the convention that node-callback-style API's never call a callback synchronously.

**Comment by matthewwithanm** [comment]
> I believe the intention was to always use setImmediate if available, as that's the standardized method for microtask scheduling.

@trxcllnt `setImmediate()` is task scheduling, not microtask, right?

**Comment by trxcllnt** [comment]
@matthewwithanm now that you bring it up, I'm not even sure. I do remember we expected asap to be the microtask scheduler. pinging @benlesh who might remember better.

**Comment by benlesh** [comment]
@matthewwithanm @trxcllnt 

Correct, `setImmediate` is the standardized "microtask" scheduler. (I believe the vernacular they're going with is "job"). So if it's available, we want to use that first and foremost. Otherwise we fallback (basically polyfilling it). 

Honestly, I would have expected your example to yield:

```
"nextTick 1"
"setImmediate 1"
"now!"
"setImmediate 2"
"nextTick 2"
```

What version of Node are you running?

This might also be a quirk WRT some difference between `process.nextTick` and `setImmediate`. While I'd expect them to both do the same thing, they very well might not.

**Comment by trxcllnt** [comment]
@benlesh I think what @matthewwithanm is pointing out is that setImmediate isn't the microtask scheduling method ([see here](https://github.com/YuzuJS/setImmediate#macrotasks-and-microtasks)). Furthermore, [setImmediate docs on MDN](https://developer.mozilla.org/en-US/docs/Web/API/Window/setImmediate) seem to indicate setImmediate is dead, so we should probably find an alternative.

**Comment by matthewwithanm** [comment]
I mentioned to @benlesh offline that I think there should be a `Scheduler.task` and `Scheduler.microtask`. Not sure if I'll be able to work on it anytime soon, but I think that explicitness would be 💯

**Comment by benlesh** [comment]
Since `setImmediate` is now off the roadmap and deprecated, `asap` schedule now uses Promise-based "micro task" scheduling.
