### ISSUE TITLE
Stop duplicating TypeScript class helpers in every CJS file output

### ISSUE THREAD

**Issue by benlesh** [ReactiveX/rxjs#2605]
Currently, we're outputting the class helpers in ever CJS file we output, that means that anyone bundling them will end up having N copies of `__extend` methods in their bundle, where N in the number of our modules they import that use classes.

This is a particular problem for the Angular team.

cc/ @IgorMinar

**Comment by kwonoj** [comment]
Check issue https://github.com/ReactiveX/rxjs/issues/2436, I guess this is dupe.

**Comment by benlesh** [comment]
this is done
