### ISSUE TITLE
Subject behaves differently then Observable when using Scheduler.asap

### ISSUE THREAD

**Issue by dgutride** [ReactiveX/rxjs#2609]
**RxJS version:** 5.4.0

**Code to reproduce:**  http://plnkr.co/edit/N98zZR?p=preview - see app.ts

**Expected behavior:**  Subject and Observable should behave the same when a scheduler is provided.

**Actual behavior:**  Subjects do not continue to emit values if a subscribe function throws an error internally.

**Additional information:**
We are building a message bus based on observables and using Subjects internally. If one of the consumers throws an error in the subscribe processing code, the Subject no longer emits any errors. This appears to be a known issue but the workaround described here: https://medium.com/@benlesh/on-the-subject-of-subjects-in-rxjs-2b08b7198b93 doesn't work with subjects (only with the example code).

**Comment by kwonoj** [comment]
Let's try to narrow down issue.

1. When subscriber throws subscribed from `Subject` is swallowing exception 👉  https://github.com/ReactiveX/rxjs/issues/2565

2. When one of subscriber throws exception, than observable / subject does not continue(emit) values anymore : this is expected, current observable contract stops sources if exception is unhandled in consumer(subscriber) level. There is discussions about this behavior but no concrete conclusion yet.

and possibly any other cases I couldn't think of?

**Comment by kwonoj** [comment]
I'm closing this for now due to inactivity.
