### ISSUE TITLE
Operator change a Subject from multicast to unicast ?!

### ISSUE THREAD

**Issue by code-tinker** [ReactiveX/rxjs#2615]
I thought a Subject is still multicast after apply a operator, but i was wrong.
```javascript
const eggStream = new Rx.Subject();
const eggWithSugarStream = eggStream.map(i => {
  return withSugar(i);
});

const childASubscription = eggWithSugarStream.subscribe();
const childBSubscription = eggWithSugarStream.subscribe();

eggStream.next(1);
```

I expect function withSugar will be call only once, but actually it depends on the number of subscriptions, which mean a Rx operator will change a multicast subject's behaviour into unicast ?

1. Is this behaviour a bug ? If not, why ?
2. If i want to keep a stream always multicast, do i need to apply a Multicasting Operator in the end every time i apply a Transform Operator ? 
```javascript
const eggWithSugarStream = eggStream.map(i => {
  return withSugar(i);
}).share();
```
pls help me 🙏

**Comment by staltz** [comment]
Not a bug. Why? Because every Rx Operator will create a new Observable, and observables are cold. Subjects are the only source of multicasting.

> If i want to keep a stream always multicast, do i need to apply a Multicasting Operator in the end every time i apply a Transform Operator ?

Yes. But you can probably refactor in order to multicast only where necessary, and pure functions in `map` don't need to be multicasted.

If you want to *persistently* go from unicast to multicast, you can convert from [RxJS to xstream, and then back if needed](https://staltz.com/why-we-actually-built-xstream.html)

```js
const incObs = sources.DOM.select('.inc').events('click').map(() => +1);
const refreshObs = sources.DOM.select('.ref').events('click').startWith(0);
const sumObs = incObs.startWith(0).scan((x, y) => x + y);
const lastSumObs = refresh$.switchMap(_ => sum$);
// From cold world (RxJS, above) to hot world (xstream, below)
const lastSum$ = xs.from(lastSumObs);
const vdom$ = lastSum$.map(view);
```

**Comment by code-tinker** [comment]
@staltz 
But according to the source code of version 3.5.1, Subject class overrides the lift function of the base class Observable, and return a Subject class not a Observable, which mean apply a Rx Operator to a Subject will return a Subject not a Observable, see below:
```javascript
Subject.prototype.lift = function (operator) {
        var subject = new AnonymousSubject(this, this);
        subject.operator = operator;
        return subject;
};
```
So I think the author first intention is making the subject still multicast after applying a Rx Operator. But the implementation of Operator changes the behaviour somehow.

**Comment by benlesh** [comment]
@code-tinker the Subject returned really has the `next`, `error` and `complete` methods of the source subject. The "observable" side of it is a "cold" observable like anything else.

The usefulness of this is debatable I suppose, but there it is.
