### ISSUE TITLE
Proposal: add transformation from TestMessage[] to marble string in TestScheduler

### ISSUE THREAD

**Issue by jiayihu** [ReactiveX/rxjs#2620]
I'm trying to test a lib based on RxJS and I noticed that Developer Experience could be improved a lot. For instance this is the output using Jest matcher for `deepEqual` passed to `TestScheduler`.

![schermata 2017-05-27 alle 15 34 53](https://cloud.githubusercontent.com/assets/10067273/26521801/29d921a4-42f2-11e7-9bcd-1480676491d1.png)
![schermata 2017-05-27 alle 15 26 52](https://cloud.githubusercontent.com/assets/10067273/26521803/2e78453c-42f2-11e7-8fa9-b27e865c088a.png)

Actually it's not that bad because Jest did a great work with diffs, but if you try instead `assert.deepEqual` from Node or other test runner matchers you get a much worse result.

![schermata 2017-05-27 alle 15 37 18](https://cloud.githubusercontent.com/assets/10067273/26521826/93ff194e-42f2-11e7-9df0-7c62337e3ed3.png)

To improve this situation in my testing I've created a small utility to convert from `TestMessage[]`, passed to the matcher, back to a marble string. I think this could be done directly by `TestScheduler` and different test runners like Mocha, Jasmine or Jest could take advantage from it.

The current result is this:
![schermata 2017-05-27 alle 15 26 48](https://cloud.githubusercontent.com/assets/10067273/26521847/2b9b3b20-42f3-11e7-87a7-f3b3455b2b9a.png)

You can catch the problems immediately or look at `TestMessage[]` for more granular info.

**Comment by kwonoj** [comment]
I'm closing this issue for now via umbrella issue https://github.com/ReactiveX/rxjs/issues/1775, I've been working to create new test interfaces but too busy, it's bit stalled. Once we have initial design for new impl we can discuss enhancements from there.

**Comment by jiayihu** [comment]
I think the issue should be kept open to since it's not solved and in #1775 there isn't any explicit point about it. Anyway thank you for your hard work on RxJS, I really don't have complains!
