### ISSUE TITLE
Observable.timer(0, 0, animationFrame).take(n) throws "executing cancelled action" errors

### ISSUE THREAD

**Issue by benlesh** [ReactiveX/rxjs#2625]
**RxJS version:** 5.4.0

**Code to reproduce:**
http://jsbin.com/senabobafi/1/edit?js,console
```js
Rx.Observable.timer(0, 0, Rx.Scheduler.animationFrame)
  .take(100)
  .subscribe(x => console.log(x));
```

**Expected behavior:**
No errors should be thrown, and animation scheduled loop should stop.

**Actual behavior:**
After the `take` completes the observable, the animation actions keep getting scheduled, and they throw an error repeatedly.

**Additional information:**
Workarounds:

```
Rx.Observable.interval(0, Rx.Scheduler.animationFrame)
  .take(100)
  .subscribe(x => console.log(x));
```

```
Rx.Observable.range(0, Number.POSITIVE_INFINITY, Rx.Scheduler.animationFrame)
  .take(100)
  .subscribe(x => console.log(x));
```

**Comment by kwonoj** [comment]
This seems similar case to https://github.com/ReactiveX/rxjs/issues/2594, we have some odds for handling tasks in scheduler.

**Comment by kwonoj** [comment]
closing via #2638.
