### ISSUE TITLE
distinctUntilChanged() Method Signature on Documentation is Inconsistent

### ISSUE THREAD

**Issue by jongunter** [ReactiveX/rxjs#2631]
I'm trying to get `distinctUntilChanged()` working properly in 5.4.0, but I can't even get a good idea of the proper method signature without looking in the source code.

This page in the docs says it only has one parameter, which is a **comparer** function:
http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#instance-method-distinctUntilChanged

This page of the docs says it has one parameter, which is **key selector** function:
http://reactivex.io/documentation/operators/distinct.html

**Which is it?** That's that million-dollar question!

Well, digging around in the source code, I found the following (with both arguments in its function signature)...so... "none of the above", I guess!
```
function distinctUntilChanged(compare, keySelector) {
    return this.lift(new DistinctUntilChangedOperator(compare, keySelector));
}
```

I've been working with Rx for almost a year now and I consider myself pretty proficient, but I am so confused about this. Is there something I'm missing?

I'm guessing the code is the source of truth here (and my testing seems to confirm that), but **the various pieces of docs need to be updated or more clearly marked with a specific version number**.

**Comment by jongunter** [comment]
This seems to have been an issue for quite some time:
https://stackoverflow.com/questions/37172395/rxjs-distinctuntilchanged-object-comparsion

**Comment by kwonoj** [comment]
Documentation update issue is well aware we are just trying to followup as fast but haven't able to do it yet unfortunately.

**Comment by kwonoj** [comment]
I'm closing this and place under umbrella issue https://github.com/ReactiveX/rxjs/issues/2656.
