### ISSUE TITLE
'repeat' does not exist on type 'typeof Observable'

### ISSUE THREAD

**Issue by fingerpich** [ReactiveX/rxjs#2637]
**RxJS version: 5.1**

**Code to reproduce:**
i just copy the code from http://reactivex.io/documentation/operators/repeat.html
```
import {Observable} from 'rxjs/Rx';
Rx.Observable.repeat(42, 3)
```
static repeat does not exist.

and it produce this error
`Property 'repeat' does not exist on type 'typeof Observable'.`

**Comment by tomasklingen** [comment]
That static method doesn't exist in RxJs 5 anymore. The documentation that you pointed to is outdated.

However:
`Rx.Observable.of(42).repeat(3)` does exactly the same.

http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#instance-method-repeat
