### ISSUE TITLE
Return type of .ignoreElements() and .empty() should be Observable<never>

### ISSUE THREAD

**Issue by felixfbecker** [ReactiveX/rxjs#2640]
**RxJS version:** 5.4.0

**Code to reproduce:**
```ts
/** Returns an Observable of files */
function fetchFiles(): Observable<string> {
  return Observable.of('foo', 'bar', 'baz')
}

const files = new Set<string>()

/** Returns an Observable that emits no items and completes when the task is done */
function updateFiles() {
  return fetchFiles()
    .do(file => {
      files.add(file)
    })
    .ignoreElements()
}
```

**Expected behavior:**
Inferred return type of `updateFiles` should be `Observable<never>`. The Observable never emits items, so the items don't have a type, similar to how a function that always throws has no return type - it `never` emits/returns.

**Actual behavior:**
Emitted return type is `Observable<string>`

**Comment by felixfbecker** [comment]
`Observable.empty()` should too

**Comment by staltz** [comment]
Hi @felixfbecker.
Would `a.concat(b)` type check correctly in TypeScript if `a: Observable<number>` and `b: Observable<never>`? That's the only concern I have, otherwise I agree with you in doing this change.

**Comment by felixfbecker** [comment]
Yep. As said, in a union with `never`, the `never` disappears:
```ts
declare let a: Observable<never>;
declare let b: Observable<number>;

const c = a.concat(b); // Observable<number>
```
