### ISSUE TITLE
Get array from ReplaySubject by buffering

### ISSUE THREAD

**Issue by benjaminhon** [ReactiveX/rxjs#2642]
I want to get my past requests as an array, not one at a time

```
pastRequests$ = new Rx.ReplaySubject(10, 10000)

pastRequests$
  .bufferTime(100)
  .subscribe (past) ->
    console.log 'past', past
  .unsubscribe()
```

i use the buffer with a 100ms time, because the replay subject replays immediately,
however, i get nothing. Can anyone tell me how to get the past data as an array? i need it for some calculations.

BTW i have tried the follwing
```
pastRequests$
  .scan(
    (acc, curr) ->
      acc.push(curr)
      return acc
    , []
  )
  .subscribe (past) ->
    console.log 'past', past
  .unsubscribe()
```

however it returns
```
[data1]
[data1,data2]
[data1,data2,data3]
```
where as i only want
```
[data1,data2,data3] 
```
and not the past calculations as well

Thanks

**Comment by benjaminhon** [comment]
i managed to solve it like this

```
pastRequests$
  .bufferTime(0)
  .take(1)
  .subscribe(...
  )
```

Would like to check if there is a better way though

**Comment by benlesh** [comment]
Closed for lack of interest.
