### ISSUE TITLE
Permission issues after updating to Node 8

### ISSUE THREAD

**Issue by dhniels** [ReactiveX/rxjs#2644]
**RxJS version:** 5.4.0

**Additional information:** After updating my node/npm versions to latest (8.0.0 and 5.0.2) removing the node_modules folder and running `npm install` I have a weird issue where rxjs doesnt install into node_modules with the proper permissions. It isnt allowing read access at all to the user, therefore it breaks my app with a bunch of 403 errors on rxjs dependencies. I'm unable to determine if this is an issue with rxjs or with npm. My hunch is its originating from rxjs, as all my other packages install correctly with proper permissions.

I tried completely removing and uninstalling node and reinstalling, clearing the cache, etc but with no success. I just had my coworker upgrade his node/npm version and he began having the exact same issue.

**Comment by kwonoj** [comment]
Would you able to confirm if this is https://github.com/npm/npm/issues/16766 ?

**Comment by dhniels** [comment]
No, thanks for linking - similar issue but on mine the owner/group is indeed correct - its the permissions that are incorrect, and only on files inside node_modules/rxjs folder. My coworker upgraded his npm version and did an npm install and is having the same problem as me now. In the meantime I just ran `chmod -R 755 /node_modules/rxjs/*`

**Comment by kwonoj** [comment]
🤔 weird. Somewhat looks similar to https://github.com/ReactiveX/rxjs/issues/2522 but doesn't explain npm 5 specific...

**Comment by dhniels** [comment]
Yeah, we spent several hours on it today but are totally stumped. I did see that issue but we arent getting any EACCES errors, or any errors at all from npm. it appears to install perfectly fine. The only error is when loading the site in the browser (403 errors on all rxjs stuff)

**Comment by kwonoj** [comment]
I'd suggest to file on npm issue as well meanwhile. It could reveal more detail to triage this issues.

**Comment by dhniels** [comment]
Willdo, thanks. Ill update and link here if I find a resolution.

**Comment by kwonoj** [comment]
Seems this issue has been dealt with npm side, closing for now.
