### ISSUE TITLE
Adds multi topic EventEmitter aka application Event Bus

### ISSUE THREAD

**Issue by stalniy** [ReactiveX/rxjs#2647]
**RxJS version:** 5.1.1

**Expected behavior:**
Provide built-in `Events` service.

**Actual behavior:**
No built-in `Events` service.

**Additional information:**
Currently almost every SPA uses shared event bus and people reimplement the wheel all the time. For me it looks like a good fit for library as `rxjs` to provide a unified way to create event bus based on `Subject`s. I created created a PR for such a bus in Ionic2 project, so you can take a look: 
PR: https://github.com/ionic-team/ionic/pull/11861
Issue: https://github.com/ionic-team/ionic/issues/11770

Basically it's just a service with one method `topic(name: string)` which returns `Subject`.
```js
import { Subject } from 'rxjs'

@Component({ ... })
export class MyComponent {
   constructor(private events: Events) {
     this.destroyed = new Subject()
   }

   ngOnInit() {
      this.events.topic('app:offline')
         .takeUntil(this.destroyed)
         .subscribe(() => this.doStuff())
   }

  ngOnDestroy() {
    this.destroted.next(true)
    this.destroyed.complete()
  }
}
```

**Benefits**:
* allows to integrate `Events` service with other `rxjs` application logic easier
* easier unsubscribing with help of `takeUntil`
* easier merging with other observables
* adds all `rxjs` methods to application wide events (e.g., `debounceTime`, `throttleTime`, etc)

**Comment by kwonoj** [comment]
Looking into PR, it seems it's lightweight wrapper around single subject as you mentioned. In that case, I could think of this could be separate modules other than to be included in core library, and it'll allow to fulfill most of benefits you've described. Is there specific constraint this should be included in core, like it should rely on some internals of implementation can't be achieved by separate module?

I do see of values of this, but also thinking about cases like our mono-package contains lot of unused paths for certain environment (i.e we've had node-specific types caused browser users pain, ajax impl, etcs) would like consider separated way first.

**Comment by stalniy** [comment]
@kwonoj such thing as `ApplicationEvents` are normally used in any SPA application.
I believe it's very useful to have such functionality based on `rxjs` when you use `Observable`s. 

There is no other reasons  why this should be a part of `rxjs`, only convenience and this can be implemented separately

**Comment by kwonoj** [comment]
It's my personal opinion and other commiter's may have different opinion (reason I labeled discussion) but I'd usually advocate approaches as

- create userland module first
- then consider migrating into core repo once if needed

Once something is added to core, it is not trivial to move back to separate module as similar to what we've discussed over some other functionalities. Primary reason for those is make core as much as lightweight, in terms of size / api surface both and if someone wants additional features, they can opt in by installing those modules.

**Comment by stalniy** [comment]
I see your point and it makes sense. So I close the issue
