### ISSUE TITLE
Observable.if does not appear in the documentation

### ISSUE THREAD

**Issue by ggranum** [ReactiveX/rxjs#2648]
I only discovered that the `if` operator had been migrated by accident, when I found https://github.com/ReactiveX/rxjs/pull/1348 while searching Issues. I'm assuming this is supposed to be exposed?

**RxJS version:**
As of commit  [be91989] (https://github.com/ReactiveX/rxjs/commit/be91989c7c0f718b33cba7e07945a2c21d70564f) 

Not sure how to find version info on the docs at reactivex.io, but as of the creation date of this ticket.

**Expected behavior:**
*  Should be mentioned in migration docs: https://github.com/ReactiveX/rxjs/blob/master/MIGRATION.md
* Should be present on Observable docs under static methods: http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html

**Comment by kwonoj** [comment]
It is known documentation is not fully migrated and missing, instead of having each individual issue I've created umbrella issue at #2656 to track it.
