### ISSUE TITLE
Change scheduler `schedule` signature

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#265]
Funny enough, I feel like this is the first way I did scheduling, but @trxcllnt is resurrecting it...

Instead of:

```TypeScript
schedule(delay: number, state:any, work:(state?: any) => Subscription | void) : Subscription
```

it should be:

```TypeScript
schedule(work:(state?: any) => Subscription | void, delay: number = 0, state?: any) : Subscription
```

This actually brings it *sort of* inline with methods like `setTimeout` to a degree.

**Comment by headinthebox** [comment]
Any reason you have the state parameter?

**Comment by blesh** [comment]
@headinthebox it's to pass data/parameters to the `work` function, mostly.

```js
someScheduler.schedule(dispatch, 100, { name: 'world' });

function dispatch(state) {
  console.log('hello ' + state.name);
}
```
