### ISSUE TITLE
forkJoin lost some parallel async functionality in v5

### ISSUE THREAD

**Issue by cerebrl** [ReactiveX/rxjs#2650]
**RxJS version:**

5.4.0

**Code to reproduce:**

```
var times1 = [ 10000, 5000 ],
	times2 = [ 7000, 10000 ];

function delay(time, callback) {
	console.log('Initiate ' + time +': ' + new Date().getSeconds());
	setTimeout(function () {
		console.log('Complete ' + time +': ' + new Date().getSeconds());
		callback(null, 'Hello, ' + time + '!');
	}, time);
}

Rx.Observable.forkJoin(
	Rx.Observable
		.from(times1)
		.concatMap(function (time) {
			return Rx.Observable.bindNodeCallback(delay)(time);
		}),
	Rx.Observable
		.from(times2)
		.concatMap(function (time) {
			return Rx.Observable.bindNodeCallback(delay)(time);
		})
)
.subscribe(
	function (data) {
		console.log(data);
	},
	function (err) {
		console.log(err);
	},
	function () {
		console.log("I'm complete!");
	}
);
```

**Expected behavior:**

Version 5 should mimic the exact behavior of version 4.

Expected output (from version 4):

```
"Initiate 10000: 53"
"Initiate 7000: 53"
"Initiate 5000: 53"
"Initiate 10000: 53"
"Complete 5000: 58"
"Complete 7000: 0"
"Complete 10000: 3"
"Complete 10000: 3"
["Hello, 5000!", "Hello, 10000!"]
"I'm complete!"
```

Notice that the total time (53 being the second it starts, and 3 being the second it stops) is 10 seconds, meaning that it was 100% async/parallel.

**Actual behavior:**

Version 5's output (with the exact same sample code):

```
"Initiate 10000: 11"
"Initiate 7000: 11"
"Complete 7000: 18"
"Initiate 10000: 18"
"Complete 10000: 21"
"Initiate 5000: 21"
"Complete 5000: 28"
"Complete 10000: 29"
["Hello, 5000!", "Hello, 10000!"]
"I'm complete!"
```

Notice that the total time (11 being the second it starts, and 29 being the second it stops) is 18 seconds, meaning that it was _NOT_ 100% async/parallel.

**Additional information:**

This seems to be related to a combination of `forkJoin` with internal `concatMaps`. Here's some JSBins that produce the reported behavior:

Version 4: http://jsbin.com/hirehut/edit?js,console
Version 5: http://jsbin.com/qeleyus/edit?js,console

Another note is that it is reproducible in all versions of 5.x. Let me know if you have any other questions.

**Comment by david-driscoll** [comment]
imo it appears rxjs 4 has a bug.  Looks like the bug is with `fromNodeCallback` based on my testing, it's immediately invoking the underling node method before anything actually is subscribed to.

Based on the given times `var times1 = [ 10000, 5000 ], times2 = [ 7000, 10000 ];` the total duration should always be at least 17 seconds when you use `concatMap` versus 10 seconds if you use `mergeMap`.

* `forkJoin` takes the final value from all observables, so they must complete.
* `concatMap` waits until the inner observable completes before continuing.  A total time of 15s and 17s means that this will always take at least 17s.  You see a difference of 18 because of other overhead or if you were in the second half of the second when it started.

**Comment by kwonoj** [comment]
I'm feeling same with @david-driscoll . if it is `mergeMap` total 10 sec is expected, but it's for concat. I'm /cc'ing @benlesh and @mattpodwysocki for visibility.

**Comment by cerebrl** [comment]
Thank you all for responding, but I have to admit, this is freaking me out O_o 

So, what I'm gathering here, and it looks like it's true (I wrote some simplified cases to be sure) that concatMap is truly sequential in it's operation, when not combined with `fromCallback` or `fromNodeCallback`. My original understanding of `concatMap` is that it was done asynchronously (all observables were fired off in parallel), but the returned values from those Observables were just preserved in the order of the original iterable.

Now that I'm looking at the docs, it sure as heck says it's sequential:

> ... in a serialized fashion waiting for each one to complete before merging the next.

I can't believe this bug in 4 has lead me to believe something entirely different. Now, I'm going to have rewrite a TON of code in multiple applications to account for this unfortunate situation. :(

Thanks again for your help. Wish my luck as a spend all weekend rewriting :`(

**Comment by cerebrl** [comment]
Closing because the bug was in my understanding :)
