### ISSUE TITLE
Make fromPromise support promise cancellation?

### ISSUE THREAD

**Issue by felixfbecker** [ReactiveX/rxjs#2652]
Many non-standard promise implementations support a `promise.cancel()` method that cancels the promise:
- WinJS (used in Visual Studio Code)
- Angular 1 (`$timeout` has `cancel()`)
- Bluebird (if enabled)

The only way to currently convert these to Observables is to write by hand:
```ts
return new Observable(subscriber => {
  const promise = foo();
  Observable.fromPromise(promise).subscribe(subscriber);
  return () => promise.cancel();
})
```

Would there be any downside to have `PromiseObservable` check if the promise has a `cancel` method, and if present, invoke it on unsubscription?

**Comment by staltz** [comment]
I think this is a good idea to consider.

**Comment by MychaelZ** [comment]
How is this not supported?

**Comment by felixfbecker** [comment]
I have since changed my opinion on this. The standard way to cancel Promises in JS is `AbortSignal` now, Angular 1, WinJS and Bluebird are rarely used anymore.

**Comment by kwonoj** [comment]
Closing as core team trying to follow spec complaint abortsignal.
