### ISSUE TITLE
Subject.create is missing from Documentation.

### ISSUE THREAD

**Issue by vaibhav93** [ReactiveX/rxjs#2655]
Documentation is missing for `Subject.create`
[http://reactivex.io/rxjs/file/es6/Subject.js.html#lineNumber113](http://reactivex.io/rxjs/file/es6/Subject.js.html#lineNumber113)

RxJS version : 5.4.0

RxJS 4 doc for reference 
[https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/subjects/subject.md#subject-class-methods-1](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/subjects/subject.md#subject-class-methods-1)

**Comment by kwonoj** [comment]
It is known documentation is not fully migrated and missing, instead of having each individual issue I've created umbrella issue at #2656 to track it.
