### ISSUE TITLE
Documentation missing for operator / interface need to be updated

### ISSUE THREAD

**Issue by kwonoj** [ReactiveX/rxjs#2656]
**RxJS version:**

**Code to reproduce:**

**Expected behavior:**

**Actual behavior:**

**Additional information:**
This is umbrella issue to track documentation status. It is known there are missing documentations around operators, interfaces and website(reactivex.io) need to be updated.

`Subject.create` https://github.com/ReactiveX/rxjs/issues/2655
`Observable.if` https://github.com/ReactiveX/rxjs/issues/2648
`Timeinterval` https://github.com/ReactiveX/rxjs/issues/2627
`installation guide on http://reactivex.io/rxjs` https://github.com/ReactiveX/rxjs/issues/2482
`finally` https://github.com/ReactiveX/rxjs/issues/2256
https://github.com/ReactiveX/rxjs/issues/2656

**Comment by SangKa** [comment]
I will supplement it:
 - publishBehavior
 - publishLast
 - publishReplay
 - timeout
 - timeoutWith
 - timeoutWith
 - timeoutWith
 - timeoutWith

**Comment by wldcordeiro** [comment]
* `ajax`/`get/post/put/etc`

Since @kwonoj closed my issue I'd figured I'd add to the list.

**Comment by mpodlasin** [comment]
I created `timeout` docs: https://github.com/ReactiveX/rxjs/pull/2724.
Also gentle reminder, that of those mentioned here, I have opened PRs for `if` (https://github.com/ReactiveX/rxjs/pull/2419) and `finally` (https://github.com/ReactiveX/rxjs/pull/2511). 
:)

**Comment by benjamenweber** [comment]
It doesn't look like there is an issue to update the website.  It would be nice if at least some of the merged documentation updates made it there.  Ended up finding this from #2400 and #2449

**Comment by JSchneidler** [comment]
`forkJoin` is also missing documentation. I would submit a PR for it if I was more experienced with RxJS.

**Comment by rinfan** [comment]
@JSchneidler it's already there https://github.com/ReactiveX/rxjs/pull/2400/commits/5cdef625ed7ed312399aec4c2a2ebe62fb0a210b  there just hasnt been any updates to the website to use newly generated docs in who knows how long.

**Comment by dahei** [comment]
Please update the website docs. It's very confusing for newcomers not to find the API-docs for e.g. "Observable.subscribe()"

As the docs are added to the actual sources (5 months ago in the case of "subscribe" - see https://github.com/ReactiveX/rxjs/issues/2449#issuecomment-285445755), the generation of the website docs shouldn't be too much effort.

**Comment by karptonite** [comment]
Also missing is 

- `shareReplay`
- `skipLast`

**Comment by mnquintana** [comment]
Another one for the list for whenever y'all get the chance 🙇 : `let`

**Comment by benlesh** [comment]
cc @ladyleet @kwonoj  ... can this be closed? Is this accounted for as part of the documentation effort?

**Comment by takamori** [comment]
Subject is missing documentation for all of its methods, both on this site and at GitHub. https://github.com/ReactiveX/rxjs/tree/master/src
http://reactivex.io/rxjs/file/es6/Subject.js.html

**Comment by ladyleet** [comment]
@benlesh I don't see why not - @mnquintana @takamori @karptonite @dahei @rinfan @benjamenweber @mpodlasin @wldcordeiro @SangKa this is a super old issue - but if any are still outstanding please create issues on the new rxjs docs initiative. https://github.com/ReactiveX/rxjs-docs/issues // @kwonoj

**Comment by rinfan** [comment]
@ladyleet 
Is there an issue for updating the website's documentation?  Looks like forkJoin for example is still missing even though the documentation comment was updated months ago. 
http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#static-method-forkJoin
https://github.com/ReactiveX/rxjs/commit/5cdef625ed7ed312399aec4c2a2ebe62fb0a210b

**Comment by takamori** [comment]
@ladyleet Opened https://github.com/ReactiveX/rxjs-docs/issues/164 (out of date docs, as noted by @rinfan ) and https://github.com/ReactiveX/rxjs-docs/issues/165 (Subject missing any docs) for the specific issues I came here for.

**Comment by ladyleet** [comment]
@rinfan speaking with the team about the best way to handle this - also @takamori thank you! :)

**Comment by anodynos** [comment]
As everyone says, please update the site docs! **It should be priority No1,** cause it's extremely frustrating, for both old and new users, to find outdated or missing information! Please please please, no new features, just docs!

**Comment by ladyleet** [comment]
@anodynos the new repo for this is currently at http://github.com/reactivex/rxjs-docs. if you pull down the project or run it with stackblitz you should be able to see the beta docs and find some level of docs. we also welcome new contributors that care about the docs!

**Comment by anodynos** [comment]
Thanks @ladyleet - any idea when they will be available online (i.e http://reactivex.io/rxjs/)?
Also, I was under the impression the docs & marble images were generated from the code and/or specs, is that the case?

**Comment by ladyleet** [comment]
@anodynos no actual timeline yet!

**Comment by scottescue** [comment]
I almost drove myself mad this morning trying to figure out why the 'subscribe' method I've seen used in multiple tutorials and examples isn't included in the Observable class documentation. I honestly thought the operator might have been removed in RxJS 5 and I was actually finding dated examples, or the operator might actually be implemented in a subclass of Observable.

I know +1's generally aren't helpful, but I feel compelled to second @anodynos frustration that the docs published to http://reactivex.io/rxjs are not complete, in part because it appears this has been a problem for quite awhile.

@ladyleet if this is something a noob can help move along, I'm willing to help

**Comment by benlesh** [comment]
This issue is really too vague, probably don't need an umbrella issue for this.

**Comment by torinthiel** [comment]
Sorry, but I don't see how this is too vague: Please regenerate documentation from sources. That would be it. Or give a hint how a guy like me that is a programmer, but has no knowledge of rxjs internals can help with it (as the label suggests).

**Comment by benlesh** [comment]
@tomraithel it's vague because there's no specific way to say "we're done" and close the issue.

>  Or give a hint how a guy like me that is a programmer, but has no knowledge of rxjs internals can help 

The documentation is inline JSDoc comment style documentation. You'd have to make a pull request that updated these JSDoc comments. There's not a lot of knowledge of internal necessary, I suppose. Just knowledge of behaviors.

**Comment by tomraithel** [comment]
@benlesh I think this was meant for @torinthiel 🤣

**Comment by benlesh** [comment]
@tomraithel hahahahaha... @torinthiel I'm so confused. :rofl:

**Comment by torinthiel** [comment]
@benlesh  Well, I haven't yet sat to checking this, but guessing by https://github.com/ReactiveX/rxjs/issues/2656#issuecomment-320876207 it's not that simple. I can deal with preparing the docs (well, assuming I'll know what to write, but that's a different question - reading the source should at least give me a starting point for review), but what I was referring to as "we're done" was rather the problem described in https://github.com/ReactiveX/rxjs-docs/issues/164 than a lack of specific descriptions. And for some reason I was under impression that the current issue has evolved into global 'get the site in sync with the JSDoc' issue.

**Comment by benlesh** [comment]
As of last week, the current site is in sync with the JSDocs... however it looks like some of the links are missing or broken to me. Probably a separate issue, though.
