### ISSUE TITLE
Calling toPromise invokes callback asynchronously

### ISSUE THREAD

**Issue by bdrobinsonbbc** [ReactiveX/rxjs#2657]
When I convert an observable to a promise it appears to no longer get invoked synchronously:

**RxJS version:**
5.4.0

**Code to reproduce:**
```js
const sub = new Rx.Subject()
const first = sub.first().toPromise()
result = first.then(console.log)

console.log('sending 3')
sub.next(3)
console.log('sending 4')
sub.next(4)
```

**Expected behavior:**
```
// 'sending 3'
// 3
// 'sending 4'
```

**Actual behavior:**
```
// 'sending 3'
// 'sending 4'
// 3
```

Whereas if I did the whole thing using observables and `subscribe` rather than promises and `then`, I **do** get the behaviour I would expect:
```js
const sub = new Rx.Subject()
const first = sub.first()
result = first.subscribe(console.log)

console.log('sending 3')
sub.next(3)
console.log('sending 4')
sub.next(4)
// 'sending 3'
// 3
// 'sending 4
```

This makes me think that calling `toPromise` must do something to make the callback get called asynchronously. Is this true? Or have I misunderstood something?

Thanks.

**Comment by kwonoj** [comment]
Think I didn't fully understood question - you mentioned above 
> promise it appears to no longer get invoked synchronously
 
This is true, cause observable converted into native promise which resolves _always_ asynchronously

and then you said 
> toPromise must do something to make the callback get called asynchronously.

It is already as you mentioned above, so nothing's required to do so.

The reason you're seeing given execution order in observable without promises, by default in Rx 5 it doesn't schedule unless explicitly specified. for example, if you observe subject in specific scheduler like

```
const sub = new Rx.Subject()
const first = sub.first().observeOn(Rx.Scheduler.async)
const result = first.subscribe((x) => console.log(x))

console.log('sending 3')
sub.next(3)
console.log('sending 4')
sub.next(4)
```

then output will be 
```
sending 3
sending 4
3
```

as same as `toPromise` does, cause now it's asynchronously observed.

**Comment by david-driscoll** [comment]
This is intended behavior when you refer to the [Promise Spec](https://promisesaplus.com/).  Promises will always resolve asynchronously.

> Here "platform code" means engine, environment, and promise implementation code. In practice, this requirement ensures that onFulfilled and onRejected execute asynchronously, after the event loop turn in which then is called, and with a fresh stack. This can be implemented with either a "macro-task" mechanism such as setTimeout or setImmediate, or with a "micro-task" mechanism such as MutationObserver or process.nextTick. Since the promise implementation is considered platform code, it may itself contain a task-scheduling queue or "trampoline" in which the handlers are called.
>

**Comment by bdrobinsonbbc** [comment]
Ahh I see. That's very useful, thanks for clarifying that!
