### ISSUE TITLE
Exhaust causes type issues

### ISSUE THREAD

**Issue by krasi** [ReactiveX/rxjs#2658]
**RxJS version: 5.0.1**

**Code to reproduce:**
.exhaust()

**Expected behavior:**
Flattens an Observable-of-Observables by dropping the next inner Observables
while the current inner is still executing.

**Actual behavior:**
Does not flatten the Observable.

**Additional information:**
There was a change in this commit 
[7b23e88](https://github.com/ReactiveX/rxjs/commit/96377faa58ce1f23ca8422dcf48028b2912d2467#diff-20d891a331152011cdf8fffd501873f1),
which updates the type of exhaust from **SwitchFirstSignature<T>** to **typeof exhaust**.
The first one is of type Generic, while the other one's type is Observable.
This will cause Typescript issues such as "error TS2322: Type 'Observable<any>' is not assignable to type..."

**Comment by kwonoj** [comment]
I can't look for signature change in given commits - would you provide small snippet can reproduce issue?

**Comment by krasi** [comment]
Hello,

Here is a code written in TypeScript 2.3.4, which reproduces the issue:

```
ngOnInit() {
  let c: number;
  this.source_one()
    .map( (val) => {
      return this.source_two(val);
    })
    .exhaust()
    .subscribe((result) => {
      c = result; // error TS2322: Type 'Observable<any>' is not assignable to type 'number'.
    });
}

source_one(): Observable<any> {
  let a: number = 42;
  return Observable.create((observer) => {
    observer.next(a);
    return () => {};
  });
}

source_two(val): Observable<any> {
  let b: number = 35;
  return Observable.create((observer) => {
    observer.next(val + b);
    return () => {};
  });
}
```

**Comment by kwonoj** [comment]
I think this one's fixed via https://github.com/ReactiveX/rxjs/pull/2690.
