### ISSUE TITLE
6.0.0-alpha.0 is detected as next stable version by package managers instead of 5.4.1

### ISSUE THREAD

**Issue by AlainD-** [ReactiveX/rxjs#2666]
**RxJS version:** 5.4.0

**Code to reproduce:**
* `yarn outdated`
* `npm outdated`

**Expected behavior:**
I expect to get the version `5.4.1` instead of the alpha version right?
```
Package Current Wanted Latest        Package Type URL
rxjs    5.4.0   5.4.0  5.4.1 dependencies  
```
**Actual behavior:**
```
Package Current Wanted Latest        Package Type URL
rxjs    5.4.0   5.4.0  6.0.0-alpha.0 dependencies  
```
**Additional information:**
npmjs shows 6.0.0-alpha.0 as the current version instead of 5.4.1

**Comment by d3viant0ne** [comment]
@AlainD- Looks like someone forgot to add the tag and put it out on `@latest`

**Comment by benlesh** [comment]
This has been fixed as of yesterday.

Thank you for reporting @AlainD-
