### ISSUE TITLE
Question about import Rx 

### ISSUE THREAD

**Issue by wangming-0215** [ReactiveX/rxjs#2668]
when I write my code like this : 
`
import Rx from 'rxjs/Rx;
console.log(Rx.Observable.of('123'));
'`
but I got an error : Uncaught TypeError: Cannot read property 'Observable' of undefined

**Comment by wyeo** [comment]
You probably don't understand how observable/observer works.. You need to subscribe

**Comment by kwonoj** [comment]
It's cause our module is named export, so import via named or import everything like

```
import * as Rx from 'rxjs/Rx';
```

I found readme seems bit out of sync with actual module, probably I can update it.
