### ISSUE TITLE
WANTED: Size measurement on build

### ISSUE THREAD

**Issue by benlesh** [ReactiveX/rxjs#2670]
### Purpose

We need to start measuring and comparing changes in size to RxJS bundles. Network time is easily one of the biggest perf bottlenecks apps can face, and RxJS needs to take that more seriously. We have to lose weight.

### Need

RxJS is in immediate need of a simple tool to measure the size of bundled output in the following ways:

- Unminified
- Unminified and gzipped
- Minified 
- Minified and gzipped

### More Info

Inevitably we want to track changes to bundle size over time. We also want to be able to set thresholds and warn if the growth exceeds that threshold. It might be nice to provide something telling us how close we are to a goal weight.

**Comment by kwonoj** [comment]
Do we want post this into PR, or leave it somewhere else (for a starting point)? if prior, I think it can be done bit easily.

**Comment by benlesh** [comment]
Ooo... posting it in the PR would be pretty cool, @kwonoj.

**Comment by benlesh** [comment]
It definitely needs to be reported at the end of the build though. I'd love developer feedback.  "It was this, now it's this, % change"

**Comment by kwonoj** [comment]
let me stab it quickly.

**Comment by kwonoj** [comment]
clarify, first changes probably won't contain size comparison. I'll look for way to it too.

**Comment by benlesh** [comment]
## Clarifying for everyone

Just because OJ is working on a solution, doesn't mean I don't want more ideas. We TOTALLY want more ideas.

**Comment by kwonoj** [comment]
we got initial implementation for this 

![image](https://user-images.githubusercontent.com/1210596/27249693-3382e38c-52d0-11e7-96c6-6a409ae1657d.png)

and thinking about what could be improved over.
note: threshold check is avail & ready, just not enabled.

**Comment by benlesh** [comment]
It's improved for sure... I'm going to close this for now.
