### ISSUE TITLE
[QUESTION] Regarding behavior of RxJS and GC

### ISSUE THREAD

**Issue by wis-ekubesh** [ReactiveX/rxjs#2683]
At the beginning I really sorry for my post. I know that questions should be posted on stackoverflow or chat, but nobody can't answer on my question on stackoverflow.

So, the question:

I want to understand how RXjs work. Let's imagine that I have `Subject` and I have subscribers for this `Subject`.
WHEN GC will destroy those subscribers? WHEN GC will destroy objects in my callbacks for subscribers? 
Should I use `complete&unsubscribe` for that or it's not necessary?

Because I have about ~10 000 subscribers for about ~ 30 Subjects on one page and it's really problem, because I'm not sure what I need to do with it. I'm worry about memory leaks.
`takeWhile` and `takeUntil` can prevent execution of my callback, but what about memory? GC will destroy those objects? Or they will still at the memory?

When I'm trying to call `unsubscribe` for about 10 000 objects it's really slow and take about 20-30 sec.

So, I'm again sorry for the question, but I really want to know how GC will behave with objects and I think what here I can find right answer.

Thank you a lot.

**Comment by kwonoj** [comment]
you should manage subscription to unsubscribed to allow gc collects it. it doesn't mean manual unsubscription onle, but also using othe limiting operator like take*, which does manage subscription internally. 

this is same question as https://github.com/ReactiveX/rxjs/issues/2464#issuecomment-286818365 and as written in comment Ben explained about streategy regarding unsubscription in his article. (https://medium.com/@benlesh/rxjs-dont-unsubscribe-6753ed4fda87#.hubvvw3gh)
