### ISSUE TITLE
Timer Observable docs are in code but not showing on site

### ISSUE THREAD

**Issue by ladyleet** [ReactiveX/rxjs#2693]
http://reactivex.io/rxjs/class/es6/observable/TimerObservable.js~TimerObservable.html

**Comment by ladyleet** [comment]
yo @jayphelps brah.

**Comment by ladyleet** [comment]
says @benlesh

**Comment by jayphelps** [comment]
I have no idea why ben thinks I can help with this 😜

**Comment by mpodlasin** [comment]
@ladyleet These docs are visible here - http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#static-method-timer

There should be no docs for `TimerObservable` since this subclass is just an implementation detail and should not be exposed in docs (as far as I understand).

**Comment by martinsik** [comment]
@ladyleet I think this should be now available under `/api/index/function/timer`.

**Comment by JWO719** [comment]
This isn't relevant to the new docs. Therefore I close it for now.
Feel free to reopen it, if there is anything missing in the new docs
