### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'e.execute') in AsapScheduler.flush

### ISSUE THREAD

**Issue by crooy** [ReactiveX/rxjs#2697]
**RxJS version:**
5.4.1

**Actual behavior:**

```
TypeError: undefined is not an object (evaluating 'e.execute')
flush — AsapScheduler.ts:17
(anonymous function)
exports — _invoke.js:5
(anonymous function) — _task.js:31
_ — _task.js:19
y — _task.js:23
```

**Additional information:**
The error occurs in our cordova ReactJS + RxJs app, at the moment our UI switches from not logged in to logged in. I cannot find what code produces this error sadly. I suspect its somehow related to unsubscribing various streams. We use lots of streams that are mapped, filtered, published, refcounted, scanned etc.

This error does not create any issues for the user as far as i can find.

**Comment by kwonoj** [comment]
Unfortunately it isn't possible to tell if this is occurring in library's behavior or user code with given information. If there's reproducible code snippet it'll be helpful.

**Comment by kwonoj** [comment]
I'm closing this issue as inactive / lacks of information. Feel freely reopen if there is reproducible code snippet can be shared.
