### ISSUE TITLE
Bug in tests (misprint?)

### ISSUE THREAD

**Issue by Jabher** [ReactiveX/rxjs#2698]
**Version:** HEAD of master

I suggest there's a wrong line in a tests, here: https://github.com/ReactiveX/rxjs/blob/046b03de09c1edfdad6ee735237a329ff79a33bc/spec/operators/multicast-spec.ts#L556

```javascript
    expect(results1).to.deep.equal([1, 2, 3, 4]);
    expect(results1).to.deep.equal([1, 2, 3, 4]);
```

I'm pretty sure it should be comparator of both `results1` and `results2` here.

Should I create a PR for this?

**Comment by kwonoj** [comment]
yeah, go ahead ✨

**Comment by piq9117** [comment]
@Jabher can I make this PR based on your findings?:smiley:

**Comment by Jabher** [comment]
@piq9117 sure, definitely not an issue! Sorry, tons of work, did not have, like, 15 minutes to do this.

**Comment by sheeldotme** [comment]
@kwonoj, this was merged a while ago, we can probably close it!
