### ISSUE TITLE
Compilation failes with TypeScript 2.4.X

### ISSUE THREAD

**Issue by alan-agius4** [ReactiveX/rxjs#2706]
The new release of typesriptes break the usage of rxjs library due to stricter generics.

https://github.com/Reactive-Extensions/RxJS/issues/1487

**Comment by kwonoj** [comment]
dupe of #2699 , #2539, #2700 . #2701 #2702 #2703 https://github.com/ReactiveX/rxjs/issues/2704 https://github.com/ReactiveX/rxjs/issues/2705

**Comment by alan-agius4** [comment]
Which one is the main post for this issue?

**Comment by kwonoj** [comment]
not closed one.

**Comment by whymarrh** [comment]
Spoiler for future readers: #2539 is the "not closed one."
