### ISSUE TITLE
Cannot find module 'tslib'

### ISSUE THREAD

**Issue by GLJK24** [ReactiveX/rxjs#2709]
**RxJS version:**
6.0.0-alpha.0
**Code to reproduce:**

**Expected behavior:**

**Actual behavior:**
When I use mocha to run my unit testing, it get this error:
Cannot find module 'tslib'          node_modules/rxjs/Subject.js:3:15
And I find that tslib is not installed.

**Additional information:**
"mocha": "^3.4.2"
"typescript": "2.3.4"
 "typings": "^1.3.2"

**Comment by kwonoj** [comment]
I'm closing this as changes are checked in, still new package need to be published.
