### ISSUE TITLE
throttle and throttleTime implementation

### ISSUE THREAD

**Issue by pshev** [ReactiveX/rxjs#2713]
The [docs](http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#instance-method-throttleTime) explain how throttleTime works pretty well, so if I have the following code:

`Rx.Observable.interval(1000).throttleTime(1250).subscribe(x => console.log(x))`

it will be logging every 2000 milliseconds, skipping every other value. ([jsfiddle](https://jsfiddle.net/30jdrj9o/3/))

This behavior however is not quite what I would expect without reading the docs. 
There are a few different throttle implementation around: underscore, lodash, `throttle-debounce` npm package and other. But none of them work this way. They are all different but running the same code with those more or less produces the same result - logging the latest value every 1250 milliseconds or so. Which is incidentally what https://www.learnrxjs.io/operators/filtering/throttletime.html also says: "Emit latest value when specified duration has passed.". That makes sense.

So I guess I'm just wondering why is RxJS's implementation so different? Is it because it would be difficult to achieve the same behavior with Observables or is Rx implementation considered superior for some reason?

Thank you!

**Comment by kwonoj** [comment]
Check https://github.com/ReactiveX/rxjs/issues/1625 and uodated configuration in operator, I think it covers question.

**Comment by pshev** [comment]
That was an interesting thread, however I only found more unexpected behavior..

For a second it looked like this code might do the trick:
```
Rx.Observable.interval(1000)
   .throttleTime(1250, undefined, {leading: true, trailing: true})
   .subscribe(x => console.log(x))
```

It does emit the first value after 1250ms but next value is emitted after 750ms! And so it goes for all the other values - one is emitted after 1250, and next after 750. All values are emitted. ([plunkr](https://plnkr.co/edit/MPN4JWOi8snp7zp0IOdY?p=preview))
That doesn't seem right. When I say throttleTime(1250) I certainly mean: "emit no more often than 1250ms".

I feel like I should be missing something but I tried other combinations of leading and trailing configuration with no luck.

**Comment by kwonoj** [comment]
thought question was trailing behavior, but seems I was misreading something. It is worth to check `debounce*` operator as well and check issues in here about operator behavior. Long story in short, Rx's original impl has not 100% compliant to other impl and v5 still follows it. (note: it is better to read source's comment for operator explanation with unit test cases)

**Comment by pshev** [comment]
You were right to think that the question was about the trailing behavior. Reading [this commit](https://github.com/ReactiveX/rxjs/commit/bb0738f3e6df643158c4a7d1e38f035978b42882) was helpful and it looks like in the next version trailing will be true by default to match lodash behavior. 

But as I said in my previous comment, setting 'trailing' to true results in buggy behavior where observable emits more often than the given interval.

Is there a bug opened for this?

**Comment by a1650078** [comment]
Looking at the code the bug is that after emitting a 'trailing' value the observable is no longer in a 'throttled' state - so the next value would be allowed through immediately as if it were 'leading'. That is obviously wrong. I would fix it but I don't understand how trailing is supposed to work. I think the correct logic for _next is to store value and schedule callback to emit it, but if leading is set, emit the value (also don't emit it again in this case). In the callback, if the value hasn't changed from the previous next then it is 'trailing'.

Something along these lines:

```javascript
protected _next(value: T) {
  this._latest = value;
  this._changedSinceThrottle = true;

  if (!this.throttled) {
    this.scheduleThrottleEnd();
    if (this.leading) {
      this._ignoreNext = true;
      this.destination.next(value);
    }
  }
}

scheduleThrottleEnd() {
   this._changedSinceThrottle = false;
   this._ignoreNext = false;
   this.add( ... );
}

clearThrottle() {
    /* clear throttle subscription here */

    // This is the last value in a sequence but not the first
    const trailingValue = this.trailing && !(this._changedSinceThrottle || this._ignoreNext);
    
    if (this._changedSinceThrottle || trailingValue) {
      this.destination.next(this._latest);
      this.scheduleThrottleEnd();

      // Careful not to emit trailing value twice
      if (trailingValue) {
        this._ignoreNext = true;
      }
    }
}
```
