### ISSUE TITLE
In marble testing use regex for matching errors

### ISSUE THREAD

**Issue by arichiardi** [ReactiveX/rxjs#2720]
Hello again!

I was using the `#` for errors in marble testing and it would be great to specify a regex for matching test against the text of errors.

At the moment the deep equal requires the exact text which is not useful in some case. I am checking [here](https://github.com/ReactiveX/rxjs/blob/master/src/testing/TestScheduler.ts#L231).

What do you folks think?

**Comment by kwonoj** [comment]
We'll going to improve test scheduler interface and plan to not to assert in testscheduler itself but extract out notification values to allow any custom assertion works. I'm closing this issue on behalf of https://github.com/ReactiveX/rxjs/issues/3231 for general tracking.
