### ISSUE TITLE
Is it possible to groupby then sum an array elements?

### ISSUE THREAD

**Issue by afriedma** [ReactiveX/rxjs#2723]
Hi,  I tried looking at stackoverflow but the re seems to be no example of what I am trying to accomplish.  It seems to be a easy task, but I don't see an elegant solution.

I have an array `{[Quantity:25, Name: 'John', Price:1.4], [Quantity:45, Name: 'John', Price:1.8], [Quantity:15, Name: 'Peter', Price:1.0]}`

I would like to groupBy Name then sum Quantity and Price.  Expected result would be `{[Name:'John', Quantity:70, Price: 3.2],[Quantity:15, Name: 'Peter', Price:1.0]}`

Thank you in advance for your help,  I think your answer would be very helpful to the community.

**Comment by jotatoledo** [comment]
Create a question in SO, the issue tracker is no place for this

**Comment by benlesh** [comment]
Closing as stale
