### ISSUE TITLE
throttleTime(n, undefined, {leading: true, trailing: true}) ... double output

### ISSUE THREAD

**Issue by sod** [ReactiveX/rxjs#2727]
**RxJS version:** 6.5.1
**Code to reproduce (6.5.1):** https://stackblitz.com/edit/rxjs-tthiju
**Expected behavior:** One value initially, then defer next value for given `duration`
**Actual behavior:** One value initially, two values each `duration`
**Additional information:**

Test:

```javascript
import { interval } from 'rxjs'; 
import { throttleTime, take } from 'rxjs/operators';

interval(50).pipe(
  throttleTime(1234, undefined, {leading: true, trailing: true}),
  take(8),
).subscribe(x => console.log(x));

// actual output: 0----24-25----49-50----74-75----99|
// expected output: 0----24----49----74----99----124----149----174|
```

**Comment by jscti** [comment]
Has anybody found a work around on this ?

**Comment by tim-kuteev** [comment]
Hi **jscti**,

I think the work around for that might be to to give up on leading value.
```JavaScript
.throttleTime(1234, undefined, {leading: false, trailing: true})
```
Note that in this case you will be missing the first value. And there is also opened issue for single value #2859.

**Comment by simeyla** [comment]
Would `distinctUntilChanged()` work after `throttleTime` - at least for some situations?

**Comment by ubugnu** [comment]
> Would `distinctUntilChanged()` work after `throttleTime` - at least for some situations?

Yes it would work, for example:

```
distinctUntilChanged((prev, curr) => curr - prev < minWaitTime/1000)
```

**Comment by sod** [comment]
Well, let me try to propose a fix again via https://github.com/ReactiveX/rxjs/pull/4864 :D

**Comment by adolgoff** [comment]
Are there any plans to merge it?

**Comment by sod** [comment]
Oh nice, thank you for fixing it ben 🥳
