### ISSUE TITLE
Subscription doesn't work if we create observable from empty array.

### ISSUE THREAD

**Issue by zinovyevdmitry** [ReactiveX/rxjs#2729]
**RxJS version:**
5.4.2

**Code to reproduce:**
`let arrayOfObservables = [];`
`Observable.forkJoin(arrayOfObservables).subscribe(() => { console.log(1) });`
`arrayOfObservables.push(Observable.of(null));`
`Observable.forkJoin(arrayOfObservables).subscribe(() => { console.log(2) });`

**Expected behavior:**

> 1
2

**Actual behavior:**

> 2

**Comment by Brooooooklyn** [comment]
This code is working as except.
forkJoin from an empty array means no value would be emitted from `Observable`. It just completed.

Try:
```ts
let arrayOfObservables = [];
Observable.forkJoin(arrayOfObservables)
  .subscribe({ complete() => console.log(1) });
arrayOfObservables.push(Observable.of(null));

Observable.forkJoin(arrayOfObservables)
  .subscribe(() => { console.log(2) });
```

**Comment by kwonoj** [comment]
Closing as adequately answered. refer https://github.com/ReactiveX/rxjs/issues/2427 for details.
