### ISSUE TITLE
Bring back support for promiseFn in fromPromise

### ISSUE THREAD

**Issue by rochdev** [ReactiveX/rxjs#2734]
In RxJS 4, `fromPromise` supported a callback that returns a promise. This enables using other operators such as `repeat` and `retry`.

See https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/frompromise.md

**Comment by paulpdaniels** [comment]
The work around is trivial, just use `Observable.defer(promiseFn)`

**Comment by rochdev** [comment]
Since both `fromPromise(promiseFn)` and `defer(promiseFn)` existed in RxJS 4, is there any difference between the two in this specific case?

**Comment by paulpdaniels** [comment]
@rochdev implementation wise I believe there was a slight difference, but practically speaking no, other than that `defer` is more flexible in what it accepts.

**Comment by rochdev** [comment]
Just tried `defer` and it works perfectly. Thanks @paulpdaniels !
