### ISSUE TITLE
Suggestion: optional parameter to filter

### ISSUE THREAD

**Issue by staeke** [ReactiveX/rxjs#2735]
**RxJS version:**
5.3

Suggestion: make the first parameter to `filter` optional, which would then default to identity function and boolean casting.

Justification: this is so common

Old:
```typescript
filter(predicate: (value: T, index: number) => boolean, thisArg?: any)
```

Suggested new:
```typescript
filter(predicate?: ((value: T, index: number) => boolean) = x => !!x, thisArg?: any) 
```

**Comment by kwonoj** [comment]
It is trivially achievable with existing operator like `let` so I don't think this should be included in core api behavior, especially one of core design goal of v5 was reducing polymorphic behavior including via default param values as much.
