### ISSUE TITLE
Possible bug: Parallel active subscriptions with interweaved delay

### ISSUE THREAD

**Issue by marwesfur** [ReactiveX/rxjs#2739]
**RxJS version:** 5.0.3

**Code to reproduce:**

~~~
function noop() {}

Observable.interval(1000).take(1)
	.do(() => console.log('step I of first finished'))
	.delay(1000)
	.do(() => console.log('step II of first finished'))
	.subscribe(/* noop, noop, noop */);   // uncomment to "fix"

setTimeout(() =>
	Observable.interval(1000).take(1)
		.do(() => console.log('second finished'))
		.subscribe(),
	500);
~~~

**Expected behavior:**

~~~
step I of first finished
second finished
step II of first finished
~~~~

**Actual behavior:**

 it stops at `second finished`. 

**Additional information:**

The problem can be worked around by uncommenting the three `noop` callbacks to the first 
`subscribe`.

The problem was observed in version 5.0.3 -- it has since disappeared and in 5.4.2 it's working just fine.

However, I was unable to connect this to any of the bugfixes mentioned in the changelog and since my client is rather cautious with updating 3rd party libs before the go-live, I'd be very interested to hear if this has explicitly been addressed or if I'm just doing something wrong.

Thanks in advance and best regards!
Markus

**Comment by kwonoj** [comment]
I think this is it? https://github.com/ReactiveX/rxjs/issues/2237

**Comment by marwesfur** [comment]
yes, you're right. Sorry -- I assumed we previously had 5.0.3 but upon a closer look it was actually 5.0.2. That's why I didn't find it in the changelog...
Now I have good reason for updating :)

Thanks a lot!
