### ISSUE TITLE
dynamicInterval

### ISSUE THREAD

**Issue by NN---** [ReactiveX/rxjs#2744]
I suggest to add dynamicInterval operator which is similar to interval but allows dynamically select next interval.
It can be easily implemented with generateRelativeTime #2033, #2296 but has simpler usage:

```ts
dynamicInterval(iterate, intervalSelector, scheduler = async) {
  return generateWithRelativeTime(0, ()=>true, i => i + 1, i => i, intervalSelector, scheduler)
}
```

**Comment by kwonoj** [comment]
I'd rather focus the discussion to `generativeRelativeTime` at this moment. As same as other operator cases, if it's trivally achievable via one operator we usually do not create variant operator based on that. I'm not sure where discussion for `generateRelativeTIme` will land, but let's reopen this one if those operator is not accepted.
