### ISSUE TITLE
Ajax PATCH seems to fail in Firefox with 'ajax error 0'

### ISSUE THREAD

**Issue by wldcordeiro** [ReactiveX/rxjs#2747]
**RxJS version:** 5.4.2

**Code to reproduce:** jsbin.com/pucudeyebo/

**Expected behavior:** The PATCH is performed and doesn't fail

**Actual behavior:** The request fails with a cryptic uncaught exception.

`error uncaught exception: Error: ajax error 0 (line 0)`

**Additional information:**

**Comment by vagusX** [comment]
so how's it going? I found it's same in Chrome
