### ISSUE TITLE
`debounceTime` dropping values received in subscription

### ISSUE THREAD

**Issue by maxkostow** [ReactiveX/rxjs#2748]
**RxJS version:** 5.4.2

**Code to reproduce:**

```javascript
const s = new Subject()
s.debounceTime(0).subscribe(n => {
    if (n === 1) {
        s.next(2)
    }
    console.log(n)
})
s.next(1)
```

**Expected behavior:**
Should output `-1-2`

**Actual behavior:**
Output: `-1`

**Additional information:**
`lastValue`/`hasValue` are cleared out after `_next` is called synchronously.
https://github.com/ReactiveX/rxjs/blob/master/src/operator/debounceTime.ts#L98-L102

**Comment by kwonoj** [comment]
https://github.com/ReactiveX/rxjs/issues/2155#issuecomment-263715419

Basically Rx v5 doesn't guarantee reentrancy by default. If you explicitly observe in different scheduler like `.observeOn(Rx.Scheduler.asap)` then you can see it's not trapped anymore. 

![image](https://user-images.githubusercontent.com/1210596/28188954-cc33d362-67d8-11e7-95bf-7436eb6e2727.png)

**Comment by maxkostow** [comment]
Cool, thanks that's exactly the workaround I came up with.
