### ISSUE TITLE
AsyncSubject no longer releases value when unsubscribed

### ISSUE THREAD

**Issue by mburnell** [ReactiveX/rxjs#2750]
In rxjs 4, AsyncSubjects discarded references to their values when disposed. This behavior has not been ported to rxjs 5; unsubscribed AsyncSubjects retain their values, so they cannot be collected even though they cannot be used again. While it's unlikely to cause issues (you'd need long-lived, unsubscribed AsyncSubjects with large values in them in order to notice), I see no reason not to release values immediately upon disposal.

**Comment by benlesh** [comment]
Closing as stale
