### ISSUE TITLE
Documentation: Contribution.md.

### ISSUE THREAD

**Issue by piq9117** [ReactiveX/rxjs#2752]
First of all, thank you for this library its one of my favorite! 😃 

When installing the dependencies do I use `npm` or `yarn`? I did `npm install` and it created a `package-lock.json`.  I also tried `yarn` and it created a `yarn-lock`, and I don't think I should add that to the project. If guidance is provided I can submit a PR 

**RxJS version:**5.4.2

**Comment by kwonoj** [comment]
Would you mind share some more details about questions? is it about check in lockfiles in user code, or repo in here?

**Comment by piq9117** [comment]
Oh. I'm sorry. 😅 When installing the dependencies, are we suppose to have a specific version of `npm` or are we suppose to install it with `yarn` because `npm5` and `yarn` create `lock` files and I don't wanna accidentally push that. I apologize for this naive issue, I'm a beginner trying to contribute to OSS. 😅

**Comment by kwonoj** [comment]
we are limiting required npm engine via https://github.com/ReactiveX/rxjs/blob/master/package.json#L205 and lockfiles are completely opt-in per userlevel code requirement, as library itself does not require locking dependencies - it has only one dependency (https://github.com/ReactiveX/rxjs/blob/master/package.json#L209) which is quite stable, does not bumps up most cases.

**Comment by piq9117** [comment]
I think that answers all my questions. Thank you! 😃
