### ISSUE TITLE
WebSocketSubjectConfig's resultSelector is excepting an not necessary generic type T

### ISSUE THREAD

**Issue by fangpenlin** [ReactiveX/rxjs#2754]
**RxJS version:**

5.4.2

**Code to reproduce:**

Say if you want to make WebSocket subject emits raw MessageEvent, and you write

```typescript
import * as Rx from 'rxjs/Rx'

Rx.Observable.webSocket<MessageEvent>({
  url: 'ws://localhost:8080',
  resultSelector: (e: MessageEvent) => e
})
```

**Expected behavior:**

It should compiles

**Actual behavior:**

```
[ts]
Argument of type '{ url: string; resultSelector: (e: MessageEvent) => MessageEvent; }' is not assignable to parameter of type 'string | WebSocketSubjectConfig'.
  Type '{ url: string; resultSelector: (e: MessageEvent) => MessageEvent; }' is not assignable to type 'WebSocketSubjectConfig'.
    Types of property 'resultSelector' are incompatible.
      Type '(e: MessageEvent) => MessageEvent' is not assignable to type '<T>(e: MessageEvent) => T'.
        Type 'MessageEvent' is not assignable to type 'T'.
(property) resultSelector: (e: MessageEvent) => MessageEvent
```

**Additional information:**

I just upgraded to typescript 2.4.1, maybe it has something to do with [this change](https://github.com/Microsoft/TypeScript/pull/16072)

I can work around the issue either by returning `any` type from the `resultSelector` function, or make it a generic function like this

```typescript
import * as Rx from 'rxjs/Rx'

function resultSelector<T> (e: MessageEvent): T {
  return e as any as T
}

Rx.Observable.webSocket<MessageEvent>({
  url: 'ws://localhost:8080',
  resultSelector
})
```

But returning any is losing the type check, as we know exactly what type to be expected as it's given as an `Rx.Observable.webSocket` type argument. And for the second working around, which is even more awkward .

So, maybe a more ideal solution is to make `WebSocketSubjectConfig` also a generic type, and use the T as the return value from resultSelector?

**Comment by kwonoj** [comment]
Yes, it seems legit and this seems oversight when we didn't have strict generic checks.

**Comment by fangpenlin** [comment]
@kwonoj created a bugfix at #2755

**Comment by jrmcdona** [comment]
I am still facing issues with this.

Here is the code for the WebSocketSubjectConfig.
```
   this.wsSubjectConfig = {
      url: url,
      closeObserver: {
        next: (e: CloseEvent) => {
          this.socket = null;
          this.connectionObserver.next(false);
        }
      },
      openObserver: {
        next: (e: Event) => {
          this.connectionObserver.next(true);
        }
      },
      resultSelector: (e: MessageEvent) => {
        return this.serialization.handle(e);
      }
    };
```

here is the error:
```
src/core/events/rxWebSocket.subject.ts(37,5): error TS2322: Type '{ url: string; closeObserver: { next: (e: CloseEvent) => void; }; openObserver: { next: (e: Event...' is not assignable to type 'WebSocketSubjectConfig'.
  Types of property 'resultSelector' are incompatible.
    Type '(e: MessageEvent) => DataEvent' is not assignable to type '<T>(e: MessageEvent) => T'.
      Type 'DataEvent' is not assignable to type 'T'.
```

Notice anything I should be doing different?

**Comment by benlesh** [comment]
Closing this, as resultSelector has been deprecated for some time.

**Comment by mfit** [comment]
@benlesh but how can the OP's use case be fulfilled (not apply JSON.parse) on the incoming messages ?
