### ISSUE TITLE
TestScheduler need manually call flush ?

### ISSUE THREAD

**Issue by mrdulin** [ReactiveX/rxjs#2756]
**RxJS version:** `^5.4.2`

**Code to reproduce:** 

```ts
it('should combine a source with a second', () => {

    const values = {
      a: 1,
      b: 2,
      c: 3,

      x: 99,
      y: 98,
      z: 97,

      q: [1, 99],
      w: [2, 98],
      e: [3, 97],

      i: 1 + 99,
      o: 2 + 98,
      p: 3 + 97
    };

    const e1 = rxTestScheduler.createHotObservable('---a---b---c---', values);
    const e2 = rxTestScheduler.createHotObservable('--x--y--z--', values);

    const expected = '---q---w---e';

    rxTestScheduler.expectObservable(e1.zip(e2)).toBe(expected, values);

    const expected2 = '---i---o---p';
    const actual$ = e1.zip(e2, (x: number, y: number) => x + y);
    rxTestScheduler.expectObservable(actual$).toBe(expected2, values);

    rxTestScheduler.flush();

  });
```

**Expected behavior:**

From the official document, It says `TestScheduler` will call the `flush` method automatically at the end of unit test `it`. 

**Actual behavior:**

If I do not call the `flush` method, this unit test always pass.

**Additional information:**

Test framework: `jest`  + `ts-jest`

**Comment by kwonoj** [comment]
You should call `flush`, reason it's auto-flushed is RxJS repo have custom mocha interface flushes for each `it` execution.

**Comment by mrdulin** [comment]
@kwonoj  Can you give me a code link for the auto-flushed setup? Thanks.

**Comment by kwonoj** [comment]
@mrdulin https://github.com/ReactiveX/rxjs/blob/master/spec/helpers/testScheduler-ui.ts .

**Comment by mrdulin** [comment]
@kwonoj Ok. Thanks. I know it.
