### ISSUE TITLE
Should we import from rxjs/Rx or import every single operators

### ISSUE THREAD

**Issue by blackholegalaxy** [ReactiveX/rxjs#2765]
I want to ask a simple question, which is quite debated in my team.

We have a massive Angular app using Rxjs v5. Bundled with webpack.

Currently our imports looks like a mess:
```ts
import { Observer } from 'rxjs';
import { Observable } from 'rxjs/Observable';
import { BehaviorSubject } from 'rxjs/Rx';
```

but it allows to use for example `Observable.combineLatest()` without having to import combineLatest operator.

So my question / discussions. Is there any performance/advantage/best practice improvement to import only the operators from the proper path rather than importing from `rxjs` or `rxjs/Rx`?

Thanks for this maybe "non issue" discussion.

**Comment by benlesh** [comment]
You want to import directly if you can. Try not to use `rxjs/Rx`. While that gives you all the operators, the downside is that you get _all_ the operators, which means you're shipping them all to the browser, even if you're not using them.

so:

```ts
import { Observable } from 'rxjs/Observable';
import { BehaviorSubject } from 'rxjs/BehaviorSubject';
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/filter';
```
