### ISSUE TITLE
thenSource of if() still running even though condition is false

### ISSUE THREAD

**Issue by patrickmcd** [ReactiveX/rxjs#2768]
**RxJS version:**
5.4.2

**Code to reproduce:**

I have an issue where `Observable.if()` isn't protecting me against a null value like I expect it would.

If I have a variable, `whatever`, that can be null or a simple object...

```
let whatever = null;
// or
whatever = {something: 'abc123'};
```

...and if I use `Observable.if()` like this...

```
Rx.Observable.if(
  () => !!whatever,
  Rx.Observable.of(`true: ${whatever.something}`),
  Rx.Observable.of('unprotected condition false')
).subscribe(next => {
  console.log(`unprotected:`, next);
});
```

...when `whatever` is `null`, I get an error: **Cannot read property 'something' of null**.

Shouldn't the false condition stop the `thenSource` from running?

If I "wrap" the `thenSource` stream in a `switchMap`, it works; I'm protected from the null value and the `elseSource` runs.

```
Rx.Observable.if(
  () => !!whatever,
  Rx.Observable.of('discard')
    .switchMap(discard => Rx.Observable.of(`true: ${whatever.something}`)),
  Rx.Observable.of('condition false')
).subscribe(next => {
  console.log(`protected:`, next);
});
```

**Additional information:**

Here's a codepen to play with:
https://codepen.io/patrickmcd/pen/BZeeQK?editors=0010

**Comment by paulpdaniels** [comment]
The `of` isn't running but you are setting up the initial value immediately by doing 
```
`true: ${whatever.something}`
```

That isn't an RxJS issue it is a javascript one. Personally I have always wished that `if` was passed function that *create* Observables rather than just being fed Observables. But if you want to work around it you can do as you did or you can do:

```javascript

Observable.if(
  () => !!whatever,
  Observable.defer(() => Observable.of(`true: ${whatever.something}`))
)

```

**Comment by patrickmcd** [comment]
Got it. At least I'm not going crazy.

Put another way, I think, is that the word **"if"** has fooled me into expecting it to work as an if/else statement, and caused me to forget that `if()` is just a function.

Thanks for the defer tip. That looks way less hacky than my solution.

And congrats on the book release btw. I'm looking forward to another read when I get my dead tree version.

**Comment by paulpdaniels** [comment]
No problem and thanks!
