### ISSUE TITLE
suggestion: distinctUntilKeysChanged operator

### ISSUE THREAD

**Issue by obedm503** [ReactiveX/rxjs#2773]
As it stands it is possible to emit when a single key changed using `distinctUntilKeyChanged`, but that operator doesn't allow multiple keys to be watched. And sometimes you need the subscriber to execute when either of multiple keys have changed. I open the issue to ask if adding this would be beneficial and worth submitting a pr for.

my current implementation goes like this (based on distinctUntilKeyChanged implementation):
```ts
function distinctUntilKeysChanged<T>(this: Observable<T>, keys: string[], compare?: (x: T, y: T) => boolean): Observable<T> {
  return distinctUntilChanged.call(this, function(x: T, y: T) {
    // if no value changed,
    // the array will only have true values,
    // includes(false) will be false,
    // convert to oposite (!),
    // returns true;
    // => true = do nothing

    // if any value changed,
    // the array will include some false,
    // includes(false) will be true,
    // convert to oposite (!),
    // returns false;
    // => false = emit

    return !keys
      .map(key => compare ? compare(x[key], y[key]) : x[key] === y[key]) // converts to boolean[]
      .includes(false); // if any value changed
  });
};
```
I also answered an SO question https://stackoverflow.com/questions/44660184/how-to-compare-multiple-keys-with-distinctuntilkeychanged

**Comment by kwonoj** [comment]
For new operator, our current suggestion is https://github.com/ReactiveX/rxjs/issues/2733#issuecomment-314128137 , summarizing, please refer https://github.com/ReactiveX/rxjs/pull/2524 as general guidance and create it as user-land operator. We're currently trying to reduce surface in core operator and trying to expand userlevel operator for extended set of behavior to avoid core api surface getting increased.
