### ISSUE TITLE
Move all files to root

### ISSUE THREAD

**Issue by bkniffler** [ReactiveX/rxjs#2775]
Hey, I'd like to suggest an improvement. There is an excellent babel plugin https://www.npmjs.com/package/babel-plugin-transform-imports which aims at killing unused code by transforming 
```
import { Grid, Row, Col } from 'react-bootstrap';
```
to
```
import Grid from 'react-bootstrap/lib/Grid';
import Row from 'react-bootstrap/lib/Row';
import Col from 'react-bootstrap/lib/Col';
```

which is the ultimate solution for importing only whats necessary. Unfortunately, rxjs exports its modules from different paths (import 'rxjs/add/observable/of', import 'rxjs/add/operator/map'), so its impossible to take advantage of this solution.

Would you consider to move everything to the root level (like lodash) so we can comfortably import everything we need and let babel take care of eliminating unused modules?

**Comment by kwonoj** [comment]
I think this is sort of dupe to https://github.com/ReactiveX/rxjs/issues/2460 ?

**Comment by bkniffler** [comment]
True! Thanks for pointing to it
