### ISSUE TITLE
ErrorObservable should be subtype of Observable<never>

### ISSUE THREAD

**Issue by 101100** [ReactiveX/rxjs#2776]
RxJS version: 5.4.2

Code to reproduce:

```ts
/**
 * Asserts (by resulting in an errored stream) that the given stream produces
 * only true values.
 */
export function assertValid(streamToTest: Observable<boolean>): Observable<never> {
    return streamToTest
        .flatMap(test => {
            return test
                ? Observable.empty()
                : Observable.throw("Invalid value in stream.");
        });
}
```

Expected behaviour:

The above code should compile without errors since neither `Observable.empty` nor `Observable.throw` actually produce values, they should both return `Observable<never>`.

Actual behaviour:

The above code produces a compiler error:

```
Type 'Observable<any>' is not assignable to type 'Observable<never>'.
```

This is because the return type of `Observable.throw` is `Observable<any>`.

**Note**: In RxJS version 5.4.2, `Observable.empty` also produces `Observable<any>`, but this was fixed in #2691.  See #2640 for further justification of using `never` for streams that produce no values.

**Comment by jayphelps** [comment]
I think this is a duplicate of #2640, which was fixed in #2691, but since it is a breaking change it's being held off until the next major release, v6

**Comment by 101100** [comment]
Actually, this is an extension of #2691.  That fixes the issue for empty observables.  This fixes the issue for error observables (which also do not produce a value).  The line that needs to be changed is here:

https://github.com/ReactiveX/rxjs/blob/27576f749ecac85cc4238eead8b1e54673e1e440/src/observable/ErrorObservable.ts#L16

`ErrorObservable` should extends `Observable<never>`.

**Comment by 101100** [comment]
This was done in #3288.
