### ISSUE TITLE
zip loses type information with rest parameters

### ISSUE THREAD

**Issue by cartant** [ReactiveX/rxjs#2784]
**RxJS version:** 5.4.2

**Code to reproduce:**

```js
const others = [
  Rx.Observable.of(1),
  Rx.Observable.of(2)
];
const zipped: Rx.Observable<Date> = Rx.Observable
  .of(0)
  .zip(...others);
```

**Expected behavior:**

A TypeScript error similar to the following ought to be effected:

```
Type 'Observable<number[]>' is not assignable to type 'Observable<Date>'.
  Type 'number[]' is not assignable to type 'Date'.
    Property 'toDateString' is missing in type 'number[]'.
```

**Actual behavior:**

There is no TypeScript error.

**Additional information:**

There appears to be a problem with the TypeScript signature for the instance `zip` method that matches the rest parameters usage.

If no `project` function is specified, `R` cannot be inferred and the result is typed as `Observable<{}>` - so the value's type information is lost, rendering any strong typing ineffectual and hiding problems.

The signature that it matches is this one:

```ts
export declare function zipProto<T, R>(
  this: Observable<T>,
  ...observables: Array<ObservableInput<T> | ((...values: Array<T>) => R)>
): Observable<R>;
```

And the issue can be fixed by adding another signature before it:

```ts
export declare function zipProto<T, R>(
  this: Observable<T>,
  ...observables: Array<ObservableInput<T>>
): Observable<T[]>;
```

I've found similar problems with `combineLatest` and `withLatestFrom`. (And there are some signatures in `forkJoin` that don't look right to me either.)

I'm happy to submit a PR with the fixes, but I'm not sure to what extent - if any - the type declarations are tested. Other than the changed signatures, is there anything I should be including in the PR?

**Comment by kwonoj** [comment]
I don't think proposed signature is correct one. In short, by supplying array via rest operator, output should be type of `T` instead of `Array<T>`.

```js
const values = [1,2,3]
zip(values); //this signature is zip(value: Array<number>)
zip(...values): //this sigature is zip(v1: number, v2: number, v3: number)
```

so in your example above, return type of `zip` is `Observable<number>` and should not be `Observable<Array<number>>`. 

Of course still current behavior is bit incomplete to infer correct output type, but there are some limitations of inferring types in rest parameters in TSC compiler at this moment - unless we're manually handcraft hugh numbers of combination, we can't create precise signature and reason why we provide `R` as output type to be specified explicitly.

**Comment by cartant** [comment]
I disagree. There was an error in the proposed signature: it should not have included an `R` type variable. It should be:

```ts
export declare function zipProto<T>(
  this: Observable<T>,
  ...observables: Array<ObservableInput<T>>
): Observable<T[]>;
```

The `zip` operator emits an array of zipped values, so I beleive it's correct.

The absence of the signature is also inconsistent with the static `zip` - which includes it:

```ts
export declare function zipStatic<T>(
  ...observables: Array<ObservableInput<T>>
): Observable<T[]>;
export declare function zipStatic<T, R>(
  ...observables: Array<ObservableInput<T> | ((...values: Array<T>) => R)>
): Observable<R>;
```

And note that the return type is `Observable<T[]>`.

So should these be included, for consistency?

**Comment by kwonoj** [comment]
Uh, I just checked output type and yes I was incorrect, misread zip's behavior.

**Comment by cartant** [comment]
Is it a no or a yes to a PR being welcomed to address the inconsistencies between the static and instance signature overloads for `combinedLatest` and `zip`?

**Comment by kwonoj** [comment]
I guess it'd make sense to have changes for consistency. /cc @david-driscoll.

**Comment by cartant** [comment]
Sure. I'll get it done and will submit a PR. I will do `withLatestFrom`, too.

I've looked at some of the PRs from @david-driscoll and I've seen how type-declaration-related tests are wrapped in a `type()` call. I will include those as necessary.

**Comment by kwonoj** [comment]
I would like to suggest go with one operator for first. Once it's reviewed others can follow easily.

**Comment by cartant** [comment]
Sure. Just a single PR for `zip` then.
