### ISSUE TITLE
[proposal] user-land organization

### ISSUE THREAD

**Issue by kwonoj** [ReactiveX/rxjs#2786]
**RxJS version:**

**Additional information:**
RxJS 5 and further updates aims to reduce size of library in terms of bytesize and api surface both. For those we do recommend custom opertors or others as separate module and publish it - and we don't have way to organize it for people easily search around.

This issue is proposal to create sort of 'user land' organization to aggregate codes into, as well as providing single scope namespace to npm. Probably it'll look lot similar like Electron's userland (https://github.com/electron-userland/) or zsh (https://github.com/zsh-users) and we can create collection of custom operators, tools, etcs.

**Comment by staltz** [comment]
I think this is a good idea. The Cycle.js community created the `cyclejs-community` github org, I wasn't originally involved, and it turned out to be a good and safe space and for experimentation.

**Comment by kwonoj** [comment]
I still believe this is idea we can push forward, but doesn't seem to get enough attention to make a move at this moment. /cc @benlesh for ping and closing issue for now.
