### ISSUE TITLE
[discussion] clean imports to replace `rxjs/add/observable/xyz`

### ISSUE THREAD

**Issue by jeysal** [ReactiveX/rxjs#2795]
Now that lettable operators are coming (#2667) to get rid of the `import 'rxjs/add/operator/xyz'` mess, the static Observable methods for creation (`of`, `timer`, ...) and composition (`merge`, `zip`, ...) will probably need the same treatment to get rid of `import 'rxjs/add/observable/xyz'`.

I didn't find any issue or PR for this (probably not in scope of #2667, judging by the title and current commits), but I'm sure @benlesh has some ideas already?

It already seems to be possible to import these static methods properly using `import { merge } from 'rxjs/observable/merge'` etc, although this is not documented in the installation section of the docs.
However, if I didn't miss anything this approach seems quite clunky because
1. each method requires a separate import statement
2. the imports are not available on one central object like they are on `Observable` when using the `add/observable` imports
3. resulting from 2, they may need to be aliased because e.g. `merge` is a very generic name that does not convey correlation with RxJS

My personal comments on this:
1 could be resolved by centralizing the exports of the static methods similar to the `rxjs/operators` from #2667
2 does not appear to have an obvious solution, unfortunately there is no `import { merge, zip } as ObservableFactoryThingy` unless you're importing everything (`*`)
3 is probably not a large problem, especially since the same thing will apply for lettable operators (`map`, `min` etc). I certainly don't think it justifies exporting them as `observableOf`, `mergeObservables` etc instead. Either way, a possible solution to 2 might resolve 3 as well.

**Comment by jeysal** [comment]
@benlesh do you have some thoughts about the static methods already?

**Comment by jeysal** [comment]
Closing due to apparent lack of relevance.
If anybody is interested in this, feel free to comment / reopen.

**Comment by kenborge** [comment]
After upgrading to the newest rxjs with angular 5 now i was actually looking for exactly the same thing. How to get rid of the ```import 'rxjs/add/observable/xyz'```. Assuming from this issue that this is still the way to do it for static methods

**Comment by OliverJAsh** [comment]
This PR seems to have quite a bit of interest judging from the votes on the original post. I think the points are still valid as well. Could we re-open this issue?

I have just migrated to lettable operators, but I'm still using the old method of "import patching" for static creation/composition methods like `fromEvent`. (Confusingly, some methods *are* available without specifying imports, like `of`. I'm not sure if this is intended or documented anywhere?)

I occasionally run into bugs whereby I've forgotten to import a static method. Thus, I would like to switch to using real dependencies, however I am hesitant because of the issues mentioned by @jeysal. Primarily this is because of 3 (ambiguous naming like `merge` requires aliasing).

**Comment by jeysal** [comment]
It seems like https://github.com/ReactiveX/rxjs/pull/3145 will mostly resolve those problems with v6.

**Comment by benlesh** [comment]
FWIW: There has always been the ability to import these directly via:

```ts
import { of } from 'rxjs/observable/of';
import { fromEvent } from 'rxjs/observable/fromEvent';
import { timer } from 'rxjs/observable/timer';
```

The only noteworthy exceptions are `throw` and `if`, which are exported with underscores because of keyword collisions:

```ts
import { _if } from 'rxjs/observable/if';
import [ _throw } from 'rxjs/observable/throw';
```

**Comment by jeysal** [comment]
Yeah I mentioned that in the issue description, but 1. was rather about the central import path for all creation methods, which is introduced only as of #3145. But maybe @kenborge didn't see that so thanks for pointing it out again 👍

**Comment by kenborge** [comment]
I did actually miss that part so thanks

**Comment by jeysal** [comment]
I'll go ahead and close this again because I think #3145 will make everyone happy.
