### ISSUE TITLE
Match Latest Observable Spec ...

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#28]
According to Jafar, the latest spec is here: https://github.com/zenparsing/es-observable

This has changed a bit since the original spec that this was based off of, but it seems to be stablizing.

Notably, subscription returns a generator rather than a subscription object.

**Comment by blesh** [comment]
This is a must for a Beta, IMO. cc/@trxcllnt @jhusain

**Comment by thejameskyle** [comment]
Can this be closed? as per https://github.com/ReactiveX/RxJS/issues/57#issuecomment-118560662 and https://github.com/zenparsing/es-observable/issues/35

**Comment by blesh** [comment]
@thejameskyle I agree. I'll close.
