### ISSUE TITLE
`retry` operator hangs in infinite loop when `undefined` passed as count

### ISSUE THREAD

**Issue by artaommahe** [ReactiveX/rxjs#2800]
**RxJS version:**
5.4.2

**Code to reproduce:**
```ts
const count: number;

Observable.throw(null)
  .do(() => null, () => console.log('ERROR'))
  .retry(count)
  .subscribe();
```

**Expected behavior:**
No retries, single `ERROR` in console

**Actual behavior:**
Infinite retries

**Additional information:**
It's case when we passed retries count from above and it can be undefined.

**Comment by kwonoj** [comment]
For me this is similar cases to https://github.com/ReactiveX/rxjs/issues/2144#issuecomment-261801399, in general you can't expect default behavior with unexepcted input value, in this case `undefined`. `retry` strictly requires number as parameter and caller should ensure input, either providing 0 to get no retry behavior or certain other numbers.
