### ISSUE TITLE
missing 404 operator docs

### ISSUE THREAD

**Issue by apasternack** [ReactiveX/rxjs#2808]
404 response on operator doc links on operators.md page:

https://github.com/ReactiveX/rxjs/blob/master/doc/operators.md

It appears as if every link returns a 404 not found.  I tried about 15 of them.  Is this a known issue of missing docs or maybe they just changed location?

Thanks!

**Comment by kwonoj** [comment]
Check https://github.com/ReactiveX/rxjs/blob/master/doc/README.md. it's expected.
