### ISSUE TITLE
add/observable/throw.d.ts is empty

### ISSUE THREAD

**Issue by yokots** [ReactiveX/rxjs#2810]
**RxJS version:**
5.4.3

**Code to reproduce:**

**Expected behavior:**

**Actual behavior:**

**Additional information:**

**Comment by kwonoj** [comment]
Checking it, only `add/throw` seems missing module augmentation, (https://github.com/ReactiveX/rxjs/blob/master/src/add/observable/throw.ts) not sure if this is intended or just simple miss. 

/cc @david-driscoll anything you can recall?

**Comment by yokots** [comment]
@kwonoj I figured out it, add/throw and add/if missing module augmentaion, because if and throw are javascript keywords, and they are Observable static method. So they can't declare as follow: 
```javascript
import { _throw as throwStatic } from '../../observable/throw';
declare module '../../Observable' {
    namespace Observable {
        let throw: typeof throwStatic; //error
    }
}
```
When use it, just import 'rxjs/add/observable/throw'. And you can close  this issue.

**Comment by kwonoj** [comment]
Thanks for clarification.
