### ISSUE TITLE
Some operators e.g. rxjs/operator/multicast pulls in code for *all* operators now

### ISSUE THREAD

**Issue by jayphelps** [ReactiveX/rxjs#2812]
It looks like now that the older operator files import the lettable operators, they (unintentionally?) import _all_ operators.

https://github.com/ReactiveX/rxjs/blob/de9f2c8543381ae5f2fa31eb2c9968329ef4fbe0/src/operator/multicast.ts#L4

https://github.com/ReactiveX/rxjs/blob/de9f2c8543381ae5f2fa31eb2c9968329ef4fbe0/src/operator/buffer.ts#L3

https://github.com/ReactiveX/rxjs/blob/de9f2c8543381ae5f2fa31eb2c9968329ef4fbe0/src/operators/index.ts#L1-L59

***

I also see this pattern is used in [some pending PRs too](https://github.com/ReactiveX/rxjs/pull/2806/files#diff-d31027c07027614c655a42b473b41792R2)

I've been out of the loop, so it's entirely possible I'm confused or there is some magic that prevents it from being a problem--without _requiring_ people use treeshaking. Or maybe that's the plan?

**Comment by cartant** [comment]
Using this harness with a non-tree-shaking, CommonJS bundler:

```ts
const Observable = require("rxjs/Observable");
require("rxjs/add/operator/map");
```

When bundling `rxjs@5.4.3`, the resultant bundle size is **39,151** bytes.

When bundling `rxjs@5.5.0-beta.2`, the resultant bundle size is **550,768** bytes.

If, in `operator/map.ts`, this were to be used instead:

```ts
import { map as higherOrder } from '../operators/map'; 
```

The resultant bundle size would be **42,638** bytes.

**Comment by jayphelps** [comment]
@cartant good catch. I was wrong: it's not the lettable operators which pull in the others, it's the older operator files that do that now, as they defer their implementation to the lettable forms.
