### ISSUE TITLE
为什么官方api文档还是js版的。。。 我用的rxjs@5.x版本。。。

### ISSUE THREAD

**Issue by lei1996** [ReactiveX/rxjs#2818]
**RxJS version:**

**Code to reproduce:**

**Expected behavior:**

**Actual behavior:**

**Additional information:**
please（请） update (更新)  一下 api 文档 （ts版本的）。 
api文档里面的大部分还是js方法。

**Comment by haoliangyu** [comment]
Just a bit translation

Why is the official API documentation using JS code? I am using rxjs@5.x

Please update the ts-version of API documentation, which is still mostly referring js code and method.

**Comment by benlesh** [comment]
@haoliangyu thank you for the translation.

@lei1996 we are currently working on updated documentation that will derive from the TypeScript files directly. Currently we're using ESDoc to generate the documentation, and that requires us to build to ES2015, then generate docs from that. That is why you see ES2015 when you click the file links. My apologies for the inconvenience.

**Comment by kwonoj** [comment]
closing, for documentation progress, you can check https://github.com/ReactiveX/rxjs-docs .
