### ISSUE TITLE
rxjs-es vs rsjx

### ISSUE THREAD

**Issue by alexlur** [ReactiveX/rxjs#2821]
#### Website
![image](https://user-images.githubusercontent.com/8125011/29954085-398df5fa-8ea3-11e7-96cf-85bb42fcd7e5.png)

#### GitHub README
![image](https://user-images.githubusercontent.com/8125011/29954096-4417b196-8ea3-11e7-8acf-0840d7bc0bac.png)

Which one is correct?

**Comment by kwonoj** [comment]
Es pkg is deprecated, we haven't updated some places yet. https://github.com/ReactiveX/rxjs/issues/2218
