### ISSUE TITLE
Observable.from is not ES-compliant

### ISSUE THREAD

**Issue by jods4** [ReactiveX/rxjs#2824]
According to the current TC39 proposal, `Observable.from(x)` returns `x[Symbol.observable]()` if it exists and is an Observable.

This is not what `FromObservable` does. It checks for the presence of `x[Symbol.observable]` but calls it inside `subscribe()`. A `FromObservable` wrapper is always created unless `x` itself is an `Observable`.

This break various assumptions one could make. 
For instance if `[@@observable]` is implemented as `return new Observable(...)`, one would expect this code to only create a single instance:
```js
let observable = Observable.from(x);
observable.subscribe(a);
observable.subscribe(b);
```
With current implementation `[@@observable]` is called twice and two instances are created.

If `[@@observable]` returns a cached value (singleton), one would expect `Observable.from(x) === Observable.from(x)` to be true.
With current implementation it's not true because a new `FromObservable` wrapper is returned for each call.

The spec also say you should check if `x[@@Symbol.observable]` is an instance of `Observable` and wrap it otherwise, which you don't do.

**Comment by jods4** [comment]
PS: I know tree-shaking and minimizing size are key objectives for you guys, but since the ES proposal includes `Observable.from` and `Observable.of`, it would be nice if they would be included in `rxjs/Observable`, always.

**Comment by benlesh** [comment]
> includes Observable.from and Observable.of, it would be nice if they would be included in rxjs/Observable, always.

Planning on this.

I work very closely with @jhusain and this library has always been intended as a reference implementation of the proposal. That said, given it's wide use, we need to be a little slower to move so we don't break people. I'll need to look at the proposal's specification again around `from` to see what you're saying. TMK, we aren't doing anything that breaks there.

**Comment by benlesh** [comment]
Given goals around reducing bundle sizes and the lack of traction by any Observable proposals, I'm closing this issue.
