### ISSUE TITLE
Performance issue with debounceTime operator

### ISSUE THREAD

**Issue by phobos2077** [ReactiveX/rxjs#2834]
**RxJS version:** 5.4.2

**Code to reproduce:**
```someObservable.debounceTime(100).subscribe(...)```

**Actual behavior:**
setInterval and clearInterval functions are called internally, which are quite slow for my browser (Chrome  60.0.3112.113) - about 0.11 milliseconds average. I studied the code a bit and found out that AsyncScheduler is used for this, which uses setInterval internally. While this may be logical for AsyncScheduler itself, if you think about what debounce is all about, setTimeout should be sufficient and it is quite faster - about 0.03 milliseconds.

Is it possible to switch to using setTimeout for this operator?

**Additional information:**
My app uses RxJS to process messages from server which are coming from server at the rate of up to 100 messages per second, so each millisecond of processor time is accounted for :)

**Comment by kwonoj** [comment]
I'd rather supply separate scheduler for opeator `debounceTime(time, otherScheduler)` instead of changing the internals of operator. Operator itself is designed to accept custom scheduler for purpose of changing scheduling behavior.

**Comment by phobos2077** [comment]
@kwonoj , if you look at the implementation of schedulers, they all inherit from AsyncScheduler and use it's logic when delay is > 0, so basically what scheduler you pass doesn't matter.

**Comment by kwonoj** [comment]
@phobos2077 What I said is creating custom scheduler based on setTimeout, instead of using existing one. As you mentioned current scheduler isn't based on setTimeout, but you can create one.

**Comment by kwonoj** [comment]
To clarify, it might be considerable further to have another scheduler in core, but it's not available at this moment and having custom one is the quickest way to go.

**Comment by phobos2077** [comment]
@kwonoj , good suggestion.
