### ISSUE TITLE
AJAX responseType Handling.

### ISSUE THREAD

**Issue by Parakleta** [ReactiveX/rxjs#2835]
I've been trying to retrieve an XML document via `rx.Observable.ajax.get()` and I've come across a few problems with the way the `XHR.responseType` field is handled.

The first is that the AJAX constructor sets a default `.responseType` of "json" if none is provided.
https://github.com/ReactiveX/rxjs/blob/7bb8280181bf1d5b0a2d3338ede8bea5e30f64c7/src/observable/dom/AjaxObservable.ts#L155-L166

Note that there is already a `getJSON()` method which sets this value explicitly.https://github.com/ReactiveX/rxjs/blob/7bb8280181bf1d5b0a2d3338ede8bea5e30f64c7/src/observable/dom/AjaxObservable.ts#L92-L101

This is a problem because it means that non-JSON data cannot actually be retrieved via the default `get()` method.  From the XHR response there are 3 ways to retrieve the body of the response: `.response`, `.responseText`, and `.responseXML`.  If the `.responseType` is set then the body of the response must be successfully parsed by the associated parser or else the `.response` field is set to `null`.  Note that `.responseText` is null unless the `.responseType` is unset or is set to "text".  Similarly `.responseXML` is null unless the `.responseType` is unset or is set to "document".

The `.responseType` should be left unset as provides the most versatility, as then the `.response`, `.responseText`, and `.responseXML` fields may all be available depending on the source document.

The second is that a `.responseType` of "xml" is documented/used in the following code.  The correct enumeration to request an XML response is "document".
https://github.com/ReactiveX/rxjs/blob/7bb8280181bf1d5b0a2d3338ede8bea5e30f64c7/src/observable/dom/AjaxObservable.ts#L414-L415
https://github.com/ReactiveX/rxjs/blob/7bb8280181bf1d5b0a2d3338ede8bea5e30f64c7/src/observable/dom/AjaxObservable.ts#L430-L432
If it is preferred to use "xml" as a more user-friendly value this shouldn't be exposed to the XHR object.
https://github.com/ReactiveX/rxjs/blob/7bb8280181bf1d5b0a2d3338ede8bea5e30f64c7/src/observable/dom/AjaxObservable.ts#L258

**Comment by Parakleta** [comment]
Just noticed that this also relates to #2007.

**Comment by dolezel** [comment]
Can someone look into it, please? It really prevents me from using ajax through rxjs.

**Comment by benlesh** [comment]
This has been resolved in version 7
