### ISSUE TITLE
Where is the @types/rx library located/named?

### ISSUE THREAD

**Issue by ORESoftware** [ReactiveX/rxjs#2838]
I know there must be TypeScript typings for this project

prior to this I installed using
`npm install rxjs`

but now I just want to install the typings, not the whole library.

But I cannot find the typings library name.

**Comment by felixfbecker** [comment]
The typings are bundled in the `rxjs` package.

**Comment by kwonoj** [comment]
closing as it's answered.

**Comment by ORESoftware** [comment]
I think it might be nice to have a `@types/rxjs` package, in the offchance someone just wants the types?

**Comment by felixfbecker** [comment]
If you just want the types (I can't imagine why you would want that) you can just install the full package and only use the types. It would be a nightmare of maintenance to publish types _also_ to DT.

**Comment by ORESoftware** [comment]
Can't you just publish a git-subtree or git-submodule to `@types/rxjs`?

**Comment by felixfbecker** [comment]
DT does not support git submodules. What is your use case? What's the problem with the main package?

**Comment by ORESoftware** [comment]
This is the problem :)

![npm-modules](https://user-images.githubusercontent.com/11139560/31305201-9b7ba512-aae8-11e7-96f9-2114f77b3a93.png)

Another reason I ask - I am wondering how I can publish this [project](https://github.com/sumanjs/suman-types) to `@types/suman`

**Comment by felixfbecker** [comment]
My question was more, why would you need the types but not the actual implementation?

**Comment by ORESoftware** [comment]
Yes I will try to answer your question - I have a project which uses RxJS _types_ for testing, but does not need the library itself. That's because I support Observables, but I don't use Observables in the codebase, if that makes sense.

for example:

https://github.com/sumanjs/suman/blob/master/lib/test-suite-helpers/handle-promise-generator.ts#L28

**Comment by abdulkareemnalband** [comment]
I also need just type definitions to write some auto imported interfaces
https://stackoverflow.com/questions/47032606/typescript-d-ts-file-import-rxjs-type-definitions-only

**Comment by valeriob** [comment]
how can i use types without a module system ?

**Comment by ORESoftware** [comment]
@valeriob what do you mean? You can import types (.d.ts) files using node.js.

**Comment by valeriob** [comment]
No, i mean just link a rx.js on the page and you are good to go, without any compiler, boundler etc..

**Comment by valeriob** [comment]
Yes ofc they are,
but if you use typescript with namespaces instead of modules types have to be exported as namespace
https://github.com/zspitz/TypeScript-Handbook/blob/release-2.0/pages/Modules.md#umd-modules
