### ISSUE TITLE
Add .toBehaviorSubject() and .toReplaySubject() methods

### ISSUE THREAD

**Issue by diestrin** [ReactiveX/rxjs#2841]
I find it really verbose to convert an observable to either beahvior or replay subjects.

Every time I need to do this I have to:
```ts
const replay$ = new Replay<string>();
source$.subscribe(replay$);
```

Wouldn't be better to have shortcuts for this? Like:
```ts
const replay$ = source$.toReplaySubject();
const behavior$ = source$.toBehaviorSubject('inital value');
```

I can get into the code and hack it and PR, but I'd like to hear the thoughts first. Maybe there's a reason not to have this?

Regards.

**Comment by diestrin** [comment]
Is [publishBehavior](http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#instance-method-publishBehavior) the same thing?

**Comment by diestrin** [comment]
I'm trying to do the same thing with `publishBehavior`, but it still is a multi step process (now I need 3 lines, and 2 variables) and I can't seem to have access to the observable:
```ts
const connectable$ = source$.publishBehavior('initial value');

// this method is protected, and there's no other way to get access
// to the BehaviorSubject created
const behavior$ = connectable$.getSubject();

connectable$.connect();
```

**Comment by benlesh** [comment]
It looks like we missed putting a selector on `publishBehavior` like `publish` has.

However, you can do everything in one step with `multicast`:

```
source$.multicast(new ReplaySubject(3), replayed =>
  replayed.map(x => x + x); // do stuff here
)
.subscribe(x => console.log(x))
```

**Comment by benlesh** [comment]
Closing in favor of #2844 and #2845.

**Comment by diestrin** [comment]
Awesome, thanks :)
