### ISSUE TITLE
Support for spaces in marbles strings

### ISSUE THREAD

**Issue by rkrisztian** [ReactiveX/rxjs#2842]
The following example can be read in [Anatomy of a Test](https://github.com/ReactiveX/rxjs/blob/master/doc/writing-marble-tests.md#anatomy-of-a-test):

```js
var e1 = hot('----a--^--b-------c--|');
var e2 = hot(  '---d-^--e---------f-----|');
var expected =      '---(be)----c-f-----|';

expectObservable(e1.merge(e2)).toBe(expected);
```

However, this kind of formatting is not auto-formatter friendly, and I would not follow incompatible practices. And if I recall, the Clean Code book by Robert C. Martin also advises against columned alignment.

What would work however if you let those marbles strings contain spaces. Having to trim manually is an overhead however that I would not do myself, to keep things easily readable.

**Edit:** I know that we already started using columned alignment in the strings. But by exceeding the boundaries of strings for columned alignment, we make this problem even worse. So all I'm saying is that we keep this special formatting inside the strings where no auto-formatter cares what we do in it.

**Comment by benlesh** [comment]
AFAIK, this is supported now. I haven't tried it in a while though.

**Comment by rkrisztian** [comment]
While spaces are allowed, they influence the frame count, which is bad in my case because I need it only for alignment.

**Comment by kwonoj** [comment]
if you're ok with 3rd party module, peek https://github.com/kwonoj/rx-sandbox . (disclaimer: I wrote it) which support whitespace align in marbles.

**Comment by cartant** [comment]
Closing this because spaces have no meaning when the `TestScheduler` is used in `run` mode.

**Comment by rkrisztian** [comment]
@cartant, I was a bit confused at this reasoning first, just to clarify, this issue was opened a long time ago, I can see [the user guide](https://github.com/ReactiveX/rxjs/blob/master/docs_app/content/guide/testing/marble-testing.md) updated now with the following:

> ' ' whitespace: horizontal whitespace is ignored, and can be used to help vertically align multiple marble diagrams.

As well as:

```
testScheduler.run(({ hot, expectObservable }) => {
  const source = hot('--a--a--a--a--a--a--a--');
  const sub1 = '      --^-----------!';
  const sub2 = '      ---------^--------!';
  const expect1 = '   --a--a--a--a--';
  const expect2 = '   -----------a--a--a-';

  expectObservable(source, sub1).toBe(expect1);
  expectObservable(source, sub2).toBe(expect2);
});
```

That is cool, however, one part isn't clear:

> Each whitespace ' ' equals 1 frame, same as a hyphen '-'

If it has no meaning, why does it equal a frame? That sounds wrong, and probably needs a correction.

So I'm really confused here.

**Comment by cartant** [comment]
Note that it's only ignored when the `run` method is used. The `run` method was introduced after this issue was opened and its behaviour is very different from that of the original `TestScheduler` implementation.
