### ISSUE TITLE
Is RxJS not lazy?

### ISSUE THREAD

**Issue by gunar** [ReactiveX/rxjs#2843]
**RxJS version:** 5.4.3

**Code to reproduce:**
```js
Rx.Observable.from([1, 2])
  .map(x => {
    if (1) throw Error('should not have been called')
    else return x
  })
  .skip(1)
  .subscribe(x => {
    console.log('success')
  }, e => {
    console.log(e.message)
  })
```

**Expected behavior:**
Logging `success`

**Actual behavior:**
Logs `should not have been called`

**Additional information:**
None

**Comment by kwonoj** [comment]
I don't see problem here. In what reason you think it should log success? Observable does `lazy` in terms of it doesn't iterate all source values at once, but chains each source into operators each time source emits. In here, `1` maps to `throw` so it doesn't pass forward to any other operator chain but terminates source streams by calling observer's error handler.
