### ISSUE TITLE
Add selector to publishBehavior

### ISSUE THREAD

**Issue by benlesh** [ReactiveX/rxjs#2845]
We need to add an optional selector argument to `publishBehavior` similar to what `publish` has.

**Comment by benlesh** [comment]
related #2841 and #2844

**Comment by jayarjo** [comment]
Was this ever finalized?

**Comment by benlesh** [comment]
This is related to #5432

**Comment by cartant** [comment]
Closing this 'cause `publishBehavior` is now deprecated.
