### ISSUE TITLE
throttle and throttleTime broken for single values when trailing is true.

### ISSUE THREAD

**Issue by Parakleta** [ReactiveX/rxjs#2859]
**RxJS version:**

5.4.3

**Code to reproduce:**

```js
const after100 = ()=>Observable.interval(100).first();
Observable.interval(500).take(5)
    .throttleTime(100, undefined, {trailing;true})
    .subscribe(x=>console.log(x));
Observable.interval(500).take(5)
    .throttle(after100, {trailing:true})
    .subscribe(x=>console.log(x));
Observable.interval(500).take(5)
    .throttle(after100, {leading:true, trailing:true})
    .subscribe(x=>console.log(x));
```

**Expected behavior:**

```
0....1....2....3....4|   <- source stream
.0....1....2....3....4|
.0....1....2....3....4|
0....1....2....3....4|
```

**Actual behavior:**

```
.....................|
.....................|
00...11...22...33...4|
```

**Additional information:**

The changes introduced by #2465 were sorely needed but somewhat botched.  The handling of the trailing value is different between `throttle` and `throttleTime` and wrong in both cases.  In both versions if `leading` is disabled then the first value is discarded despite the fact that it might actually be the trailing value.  In the `throttle` case there is also the problem that for some reason if the leading and trailing values are both enabled it keeps the first value and emits this for both (duplicating the value).

I strongly recommend that #2749 is replicated to cover the `throttle` version as well and merged as soon as possible.  It resolves this issue, as well as #2727 which it was written to solve, and also #2466.

**Comment by tim-kuteev** [comment]
> In both versions if `leading` is disabled then the first value is discarded despite the fact that it might actually be the trailing value.

Is there any chance that this one will be fixed the near future?
