### ISSUE TITLE
Reconsidering the name "lettable"?

### ISSUE THREAD

**Issue by karptonite** [ReactiveX/rxjs#2863]
Lettable operators look awesome, and I understand where the name comes from, but it's a bit confusing, and will be especially confusing to newcomers once the `let` operator is not in common use.

Have you considered as an alternative "pipeable" operators? Also maybe not great, but it has the advantage of making it clear that these are the operators you use with `pipe()`.

**Comment by cartant** [comment]
Before it becomes regrettable?

**Comment by benlesh** [comment]
@cartant wins

So far, I don't think the phrase "lettable" shows up in the codebase... I believe I called it an `OperatorFunction` in the code/typings.  "Lettable" is just something born of RxJS community jargon. 

Totally open to suggestions on better names.

**Comment by karptonite** [comment]
Ah, then it is only an issue for the docs--still important though. I already suggested "pipeable" which is not necessarily better, but seems more clear to me. Could we call them "piped operators", maybe?

**Comment by cartant** [comment]
Suggest a new name? Hmm ... that's so much harder than just saying you don't like the current one.

**Comment by kylecordes** [comment]
"pipeable" ?

**Comment by staltz** [comment]
"thisless" operators?

**Comment by kylecordes** [comment]
Could borrow from the functional folks and call them "pointfree"... but I don't think this is a great idea.

**Comment by MVSICA-FICTA** [comment]
line | step | gate | flow | duct | drip | port | door | series operators?

pipeline = pipe + line, so line operators?

duct, gate and port also covey ongoing event flow.

series operators? Passing along events through a sequence of steps?

Just some quick tasty late night ideas :)

**Comment by rgbkrk** [comment]
I think of them as _composable_.

**Comment by rgbkrk** [comment]
🤔  They're so nice and composable that you could probably write and render via JSX:

```
<Pipe source={source$}>
  <Filter predicate={x => x %2 === 0} />
  <Map project={x => x + x} />
  <Scan accumulator={(acc, x) => acc + x} seed={0} />
</Pipe>
```

I am a monster.

**Comment by MVSICA-FICTA** [comment]
Composable is a good term to describe the type of operators that can be composed. Just change pipe to compose and the meaning becomes clear through and through.

Pipe Definition
a tube of metal, plastic, or other material used to convey water, gas, oil, or other fluid substances

Compose Definition
to make or form by combining things, parts, or elements, which constitute or make up (a whole) "the system is composed of a group of machines"

**Comment by cartant** [comment]
Seeing as though the TC-39 [pipeline operator proposal](https://github.com/tc39/proposal-pipeline-operator) has moved to [stage-1](https://github.com/tc39/proposals/commit/1a90e2888a494b7b0aa6d6e72bf30b86a51cbddf) and lettable operators play nice with the pipeline operator:

```ts
import { range } from 'rxjs/observable/range';
import { map, filter, scan } from 'rxjs/operators';

const value$ = range(0, 10)
  |> filter(x => x % 2 === 0),
  |> map(x => x + x),
  |> scan((acc, x) => acc + x, 0);
value.subscribe(x => console.log(x));
```

How about just calling them RxJS **pipeline operators**?

**Comment by benlesh** [comment]
@cartant ... `pipeline operator` would then be ambiguous, no?  and "pipelineable operator" seems weird.

How about "pipeable operators"?

Alternatively: "functional operators"

**Comment by cartant** [comment]
@benlesh Yeah. That's fair enough. I would have been happy with any name that had "pipe" in it, but now that you've suggested it, I kinda like "functional operators", too. Naming things is hard.

**Comment by karptonite** [comment]
This seems to have stalled, but even with the release of 5.5, I think it is worth renaming. I'd suggest that "pipeable operators" seems to have the most support, and the least pushback in this thread.

**Comment by MVSICA-FICTA** [comment]
Some name that reflects the idea of composition and data-flow/control would be best. How about cascade operators? I don't mind "functional operators" because pipe operators are pure and functional, yet it is quite generic and misses the opportunity to convey the real usage. Depends on the context and what is most important, coolness or meaning or both. An example of a name that truly conveys meaning is cycle as used by CycleJS.

cas·cade
kaˈskād/
noun
noun: cascade; plural noun: cascades

    1.
    a small waterfall, typically one of several that fall in stages down a steep rocky slope.
    synonyms:	waterfall, cataract, falls, rapids, white water
    "a roaring cascade"
        a mass of something that falls or hangs in copious or luxuriant quantities.
        "a cascade of pink bougainvillea"
        a large number or amount of something occurring or arriving in rapid succession.
        "a cascade of antiwar literature"
    2.
    a process whereby something, typically information or knowledge, is successively passed on.
    "the greater the number of people who are well briefed, the wider the cascade effect"
        a succession of devices or stages in a process, each of which triggers or initiates the next.

verb
verb: cascade; 3rd person present: cascades; past tense: cascaded; past participle: cascaded; gerund or present participle: cascading

    1.
    (of water) pour downward rapidly and in large quantities.
    "water was cascading down the stairs"
    synonyms:	pour, gush, surge, spill, stream, flow, issue, spurt
    "rain cascaded from the roof"
        fall or hang in copious or luxuriant quantities.
        "blonde hair cascaded down her back"
    2.
    arrange (a number of devices or objects) in a series or sequence.

**Comment by manekinekko** [comment]
What about a **compose** (or **composable**) operator. The type signature* of the `pipe` function looks somehow similar to function composition in math:

`(f ∙ g)(x) = f(g(x))`

or 

`const pipe = (f, g) => x => f(g(x));`

NOTE (*): I'm talking about the function signature, not the inner implementation.

**Comment by Meligy** [comment]
Umm ... pipe operators?

**Comment by Jerry-Hong** [comment]
I think `composable operators` is more reasonable.
it is from functional programming concept, we can use it with ramda.js

```js
import R from 'ramda';
import { filter, map } from 'rxjs/operators'
import { from } from 'rxjs/observable/from'

const obs1 = from([1,2,3]);
const obs2 = from([4,5,6]);

const getOddAndToString = R.compose(map(x => x + ''), filter(x => x % 2 === 1));
// same as pipe: 
// const getOddAndToString = R.pipe(filter(x => x % 2 === 1), map(x => x + ''))

getOddAndToString(obs1)
.subscribe(...)

getOddAndToString(obs2)
.subscribe(...)

```

**Comment by benlesh** [comment]
Done. Pipeable
