### ISSUE TITLE
lettable toPromise?

### ISSUE THREAD

**Issue by Delagen** [ReactiveX/rxjs#2868]
**RxJS version:** 5.5.0-beta

**Code to reproduce:**
```
import { of } from "rxjs/observable/of";
import {
	map,
	toPromise
} from "rxjs/operators";

export function demoFn(): Promise<void> {
	return of([null])
		.pipe(
			map(() => {}),
			toPromise()
		);
}
```

**Expected behavior:**
No error
**Actual behavior:**
```
Error:(11, 4) TS2345: Argument of type 'UnaryFunction<Observable<void>, Promise<void>>' is not assignable to parameter of type 'UnaryFunction<Observable<void>, Observable<{}>>'.
  Type 'Promise<void>' is not assignable to type 'Observable<{}>'.
    Property '_isScalar' is missing in type 'Promise<void>'.
```

**Additional information:**

**Comment by Delagen** [comment]
Any response? It works in result, but typechecking fails (

**Comment by benlesh** [comment]
`toPromise` isn't really an operator, it's a means to subscribe to an observable. An operator would return an Observable.

**Comment by Delagen** [comment]
@benlesh I understand it, but it exported as lettable. What the preferred way of convert to promise with support of tree shaking?

**Comment by felixfbecker** [comment]
To support tree shaking I'd just use `toPromise()` as a static function, i.e.

```ts
const promise = toPromise()(myObservable)
```

**Comment by benlesh** [comment]
>  but it exported as lettable

... Oops.

That doesn't seem right. Since it doesn't compose via `pipe`, it should probably be a method on Observable. Perhaps a permanent property? It would effect size a little, I suppose, but it's a pretty small function overall.

**Comment by benlesh** [comment]
cc @kwonoj

**Comment by mebibou** [comment]
So what is the proper way of using `toPromise` on `Observable` now?

**Comment by harangue** [comment]
@mebibou Don't pipe. It's on the Observable object by default.
```ts
Observable.of('foo').toPromise(); // this
Observable.of('foo').pipe(toPromise()); // not this
```

**Comment by adrm** [comment]
Thanks, @harangue , I hope pipeable operators docs were as clear on this :)
