### ISSUE TITLE
A method Rx.Observable.when

### ISSUE THREAD

**Issue by xgrommx** [ReactiveX/rxjs#287]
Hi all! Exists in plan implementing methods like `Rx.Observable.when` and `Rx.Observable.update`?

**Comment by blesh** [comment]
@xgrommx yes... the plan is to eventually move all/most of the existing operators and methods over to RxNext. The current list we're working on was sort of the minimum requirement to push the library to alpha.

**Comment by kwonoj** [comment]
I'm also interested in this topic about expanding operator implementations from existing RxJS. It'd be great if I can participate for some of operator implementations but since it's yet pre-alpha stage not sure if window for PR is opened at this moment. @blesh May I able to ask about milestone plans or PR for operator is acceptable currently?

**Comment by blesh** [comment]
Anyone may PR any operator they like! 

The set that shows up in issue #100 was just a minimum viable set. This library is modular, so we can add operators without including them in the global export if we choose

**Comment by kwonoj** [comment]
Related with https://github.com/ReactiveX/RxJS/issues/396, it seems some sort of categorization such as *"should have / good to have / need discussion"* would be helpful. @blesh What do you think?

**Comment by blesh** [comment]
I had a talk with some folks at Netflix, and I think the prevailing wisdom is to have two sets of operators: core and extended. Where core is actually published as part of Observable, and "extended" operators will simply exist in their own modules. Will discuss further in another issue.

**Comment by staltz** [comment]
@blesh  Since this is just a suggestion for an operator implementation which isn't core, I would close this issue. It doesn't mean we aren't open to receive PRs to implement this operator as "extended".

**Comment by blesh** [comment]
I'll leave this one open but unassigned to any milestone. If someone wants to add it, they can, otherwise it's not a high priority.

**Comment by chicoxyzzy** [comment]
Should issue title be updated then?

**Comment by blesh** [comment]
@chicoxyzzy Maybe? Updated to what?

**Comment by chicoxyzzy** [comment]
@blesh something like "Implement new operators and old ones from RxJS 4"

**Comment by blesh** [comment]
Oh. I think the issues should be specific to people's requested and needed operators

**Comment by blesh** [comment]
Closing this issue as stale.
