### ISSUE TITLE
BehaviorSubject is throwing next is not a function error! - In latest 5.4.3 version

### ISSUE THREAD

**Issue by Raghavendra15** [ReactiveX/rxjs#2873]
**RxJS version:**

**Code to reproduce:**
import {BehaviorSubject} from "rxjs/BehaviorSubject";
import 'rxjs/Rx';
export class DashboardService{
count = new BehaviorSubject<number>(0);
count$=this.count.asObservable();

addCount(data){
this.count.next(data);
}
**Expected behavior:**
this.count.next is supposed to work but it's saying next is not a function!
**Actual behavior:**

**Additional information:**

**Comment by kwonoj** [comment]
Please provide reproducible code via github repo or jsbin.

**Comment by kwonoj** [comment]
Please provide `reproducible` codes, instead of current code snippet you shared - it is not possible to try out to see where is problem, especially given angular code it is not easy to setup codebases. You can use like https://jsbin.com , allows to share reproducible code easily.

**Comment by kwonoj** [comment]
And just peeking current code, it seems you're reassigning `this.numberOfFacts=(data['factsCount']);` - isn't it cases?

**Comment by Raghavendra15** [comment]
Whoa ! Thanks a ton :D That's the issue it seems, i was assigning it again
by force which resulted in an unexpected behavior. I should have simply
used add function i wrote! I don't know how to thank you for this :) But
i'm curious as in what exactly went wrong.

Thanks,
Raghavendra SS

**Comment by kwonoj** [comment]
I'm closing issue for now as I believe this isn't issue in core of Rx.
