### ISSUE TITLE
Support for composability?

### ISSUE THREAD

**Issue by wshager** [ReactiveX/rxjs#2887]
Currently I'm in the process of converting a project to Rx that uses transducers a lot. It appears that there's no easy way to use transducers with rxjs, as `lift` needs to be called. For instance, I can't seem to compose `concatMap` with other functions.

Perhaps I'm missing something here? If not, are there any plans to support composable operators?

**Comment by wshager** [comment]
I may seek support for the transducer protocol in the wrong place, but it seems to me interoperability is important enough to (re)start the discussion.

**Comment by benlesh** [comment]
It's hard to say without seeing precisely what you're trying to do... but it sounds like the pipeable/lettable operators are probably what you're looking for. They're just higher-order functions that return `<T, R>(source: Observable<T>) => Observable<R>`

**Comment by wshager** [comment]
@benlesh Thanks, I'll look into `pipe`, but my question regards a generic solution. I think not all (my) cases, especially "traditional" collections, are eligible for conversion to Observables, while on the other hand, transducers implementations don't handle Observables well. I would prefer a generic transducers implementation that just handles collections like arrays or iterators and returns arrays or iterators. 

Perhaps I shouldn't fret and just go all in with Observables, but I just want to avoid the overhead where possible.

**Comment by wshager** [comment]
What I'm trying to say is that truly composable functions are (collection) type agnostic. Either Rxjs adapts a transducers protocol, or some transducer library will handle Observables properly.

**Comment by benlesh** [comment]
I'm sure implementations of things similar to Observables exist for what you're talking about (maybe the Fantasyland spec enables what you want?)

RxJS is trying to optimize for performance, so our functions are really mostly just going to deal solely with our Observable type(s), rather than generically with any sort of set.

**Comment by wshager** [comment]
I don't think rxjs needs to sacrifice performance to be compatible, but it's up to you I guess. I just don't see how I could live with two kinds of operators that have the same name, but work on different collection types.

**Comment by wshager** [comment]
By the way, I do think rxjs is generally headed in the right direction. I don't know about fantasyland or Ramda, but the way you do modularity the ES-next way seems like a really good idea (not sure about TS though, but who knows). I can imagine this discussion needs more involvement from the community at large, but personally I don't see any other outcome than going all the way with composable functions for collections, so I guess it's just a matter of time.

**Comment by benlesh** [comment]
>  but work on different collection types.

FWIW: RxJS supports converting nearly every collection type to an Observable pretty seamlessly.

**Comment by wshager** [comment]
Well, I can think of a category that isn't supported: immutable (in-memory) collections. I'm considering making a distinction between wrapped values and immutable collections, but I'm neither really happy nor convinced about it yet. In any case, thanks for your replies, and we'll just have to see what happens. Exciting times for functional JS.

**Comment by wshager** [comment]
@benlesh oh and anything that needs fast access or updates of course, which is quite a lot. Not everything can be solved with streams.

**Comment by benlesh** [comment]
@wshager thank you for your thoughts, we're always keeping an eye out for ways to make the library more compatible and/or have more interop with other types and libraries

**Comment by wshager** [comment]
@benlesh Just FYI, after giving this some more thought, it seems to me the transducers approach is a bit misleading. The goal of transducers is to provide composable, step-based operations that are collection-agnostic, for collection types that don't have them yet. However, I can't think of any case where sequences can't be used as intermediary collection: when transformation is done, you can just recreate the desired concrete structural type (like a map or array), just like transducers do in the background. So Observable can be used as an intermediary collection type for step-based transformations, provided performance is comparable to, or better than lazy iteration. So yeah, I may be overlooking something, but Rx for everything (except getter/setters).
