### ISSUE TITLE
export pipe() as function for concise use

### ISSUE THREAD

**Issue by kylecordes** [ReactiveX/rxjs#2888]
I'm working with `5.5.0-beta.2` though the exact version does not matter, this is about pipe() in general. In trying to make concise use of the new legible operators, I end up using variants of this snippet of code repeatedly:

```
    someObs.mergeMap(x => x.pipe( ...
```

I'm hoping to eliminate the superfluous `x => x.` from here, using a top level pipe available directly rather than only as an operator on Observable. So instead I could do something like:

```
import { pipe } from 'rxjs/somewhere';

    someObs.mergeMap(pipe( ...
```

I think this pipe() may be just a function composition function under the good, with all the right TypeScript stuff in place to preserve the developer experience.

**Comment by benlesh** [comment]
it's exported from `rxjs/util/pipe`:

`import { pipe } from 'rxjs/util/pipe';` should work for you.

**Comment by kylecordes** [comment]
@benlesh Excellent, thank you.

Feature request: that whatever final form emerges to make it possible to mostly import all the stuff needed from RxJs from a single module (ideally) or at most a couple of modules, that `pipe` be included.

**Comment by rgbkrk** [comment]
> `import { pipe } from 'rxjs/util/pipe';` should work for you.

D'oh, I just upgraded all our code bases to the rx 5.5 beta instead so that `pipe` would be available. It's all worth it though, I love the standalone operators. ❤️  Thank you.

**Comment by benlesh** [comment]
> Feature request: that whatever final form emerges to make it possible to mostly import all the stuff needed from RxJs from a single module (ideally) or at most a couple of modules, that pipe be included.

I'm hoping that by the final release of v6 everyone will be able to just import straight from `rxjs` like:

```ts
import { Observable, Subject, map, filter, asyncScheduler } from 'rxjs';
```

What remains to be seen is whether that will work well with bundlers or not. It seems like bundlers have some catch-up to do.

**Comment by kylecordes** [comment]
@benlesh If it's published as a FESM like Angular uses, it should yield excellent results for anyone using current-gen bundling tools.

**Comment by benlesh** [comment]
I think this issue has been resolved. Closing
