### ISSUE TITLE
Enable greenkeeper?

### ISSUE THREAD

**Issue by kwonoj** [ReactiveX/rxjs#2894]
**Additional information:**
We have few core dependency needs regular bump up and all of them are manual - maybe we can enable https://greenkeeper.io/ and let bot creates bump up PR automatically?

**Comment by benlesh** [comment]
Are there specific dependencies that are problematic when they get out of date?

Currently the only worry I have is it updating TypeScript, which doesn't adhere to semver at all. That alone might make greenkeeper a no-go... I dunno.

**Comment by kwonoj** [comment]
yeah, TS / and other TS releated dependencies are only thing I am concerning. We are manual, and we haven't actively tested it as soon as it comes out. Other devDependencies are not huge concern.

**Comment by felixfbecker** [comment]
Greenkeeper doesn't only do PRs to update dependencies, it runs builds for new in-range updates and opens issues when they break the build. Very valuable to have.

**Comment by kwonoj** [comment]
Closing as stale.
