### ISSUE TITLE
Some inner subscriptoins are calling `subscribe` and not `_subscribe`

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#290]
If we already have a `Subscriber` instance, there's no need to call `subscribe` on an `Observable`, instead, `_subscribe` can be called directly.

**Comment by blesh** [comment]
Digging into this, it's a non-issue. In my zeal to create this issue, I had forgotten that calling subscribe was required to settle void|Function|Subscription into just being a Subscription. I'll keep investigating to see if I can stream-line this at all, but I doubt it.

**Comment by trxcllnt** [comment]
@blesh we could assume it's always safe to call `_subscribe` if we moved to the `Observer.prototype.start` API and disregarded functions/Subscriptions returned by `_subscribe`.

**Comment by blesh** [comment]
@trxcllnt I did some work and found a way to make sure this does what we want it to. There was a modest, but consistent 1-2% performance increase. Nothing major, but worth merging, I think. PR dropping in 3... 2... 1...
