### ISSUE TITLE
Potential inconsistency in BehaviorSubject, catch() and skip()

### ISSUE THREAD

**Issue by YoungCatChen** [ReactiveX/rxjs#2903]
**RxJS version:** 5.4.3

**Code to reproduce:**
```ts
function setup(obsv) {
    return obsv.map((n) => {
        if (n===2) throw 'two';
        return n * 100;
    }).catch((err, caught) => {
        return setup(obsv.skip(1));
    });
}
function subcr(obsv) {
    obsv.subscribe(
        res => console.log(res),
        res => console.log('erro', res),
        res => console.log('complete\n'));
}

// Case A
let subject = new Rx.BehaviorSubject(1);
subcr(setup(subject));
subject.next(2);
subject.next(3);
subject.next(4);
subject.complete();

// Case B
subject = new Rx.BehaviorSubject(1);
subcr(setup(subject));
subject.next(2);
subject.next(2);  // <--- note here
subject.next(3);
subject.next(4);
subject.complete();
```

**Expected output:**
```
100
300
400
complete

100
300
400
complete
```

**Actual behavior:**
```
100
300
400
complete

100
400   // <--- 300 is missing.
complete
```

**Additional information:**

I could be wrong, but a potential inconsistence is noticed. In the code above, I tried to use `catch()` to "resume" the observable killed by a thrown error. Given that errors are thrown when the value is 2 and that it tries to skip such values to continue with remaining numbers, the output should always be `100,300,400`, whether the input is `1,2,3,4` or `1,2,2,3,4`.

Thanks for reading!

**Comment by kwonoj** [comment]
Isn't this sort of re-entrant by supplying throwing condition twice and returns source observable so skipping occur twice as well? I need to dig bit more to confirm but at a glance that looks cases.

**Comment by benlesh** [comment]
@YoungCatChen the `setup` function is recursive within the bounds of `catch`.... you're adding a `skip` on for each thrown error caught... so `obs.skip(1)` then `obs.skip(1).skip(1)` then `obs.skip(1).skip(1).skip(1)` and so on.

I think we can close this one.

:)

**Comment by YoungCatChen** [comment]
I got it. Thanks to both for clarification!

**Comment by benlesh** [comment]
No problem, @YoungCatChen! <3 Happy we could help.
