### ISSUE TITLE
`Observable.prototype_subscribe` and `Operator.prototype.call` should only accept a type Subscriber<T>

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#291]
... that way we know at build-time if we accidentally passed it a duck-typed observer (which should go to `subscribe` and not `_subscribe`)

Similarly, there's no reason Operator's `call` method should accept any `Observer`, it should also require a `Subscriber`, which we know has all guarantees, etc.

**Comment by kwonoj** [comment]
Not sure if this is already work in progress, may I possibly give it a try for PR?

**Comment by blesh** [comment]
@kwonoj sure.

**Comment by kwonoj** [comment]
Thanks! Trying to make it :)
