### ISSUE TITLE
forkJoin completes immediately when one of the sources is already complete

### ISSUE THREAD

**Issue by miguelalvarezi** [ReactiveX/rxjs#2915]
**RxJS version:** 5.4.3

**Code to reproduce:**

```
var subject1 = new Rx.Subject();

setTimeout(function () {
  subject1.next('b');
  console.log('subject 1 completes');
  subject1.complete();
}, 2000);

var subject2 = new Rx.Subject();

setTimeout(function () {
  subject2.next('c');
  console.log('subject 2 completes');
  subject2.complete();
}, 6000);

setTimeout(function () {
  console.log('just before subscribe');
  Rx.Observable.forkJoin([subject1, subject2]).subscribe({
    next: x => console.log('got value ' + x),
    error: err => console.error('something wrong occurred: ' + err),
    complete: () => console.log('forkJoin completes'),
  });
  console.log('just after subscribe');
}, 4000);
```

**Expected behavior:**

Console output:

```
> subject 1 completes
> just before subscribe
> just after subscribe
> subject 2 completes
> forkJoin completes
```

**Actual behavior:**

Console output:

```
> subject 1 completes
> just before subscribe
> forkJoin completes
> just after subscribe
> subject 2 completes
```

**Additional information:**

Maybe this is expected behavior, but I couldn't find any documentation or example backing the actual behavior.

If I filter out subjects with `isStopped === true` before calling forkJoin, thinks work as expected, so I'll use this filter as a workaround.

I observed the same behavior for version `5.5.0-beta.5`.

Great library and documentation, thanks!

**Comment by kwonoj** [comment]
I'm seeing this makes sense. forkJoin by default when one of source completes without value, it short curcuits. In here subscription occurs on 4000, while subject 1 already completed at 2000, starting forkjoin from immediate completed state without value. Similar test case would be https://github.com/ReactiveX/rxjs/blob/92547a04b625cf057f43ec1bf9bb2ad1b5683577/spec/observables/forkJoin-spec.ts#L187 while it is not completely identical cases.
