### ISSUE TITLE
mergeMap(fn) and map(fn), mergeAll() showing different behavior in 5.5.0-beta.5

### ISSUE THREAD

**Issue by skokenes** [ReactiveX/rxjs#2918]
**RxJS version:**
5.5.0-beta.5

**Code to reproduce:**
https://gist.github.com/skokenes/8462324033ad8d249f7a65ff3447d637

**Expected behavior:**
`mergeMap(fn)` and `map(fn), mergeAll()` should essentially function the same, given the same parameters. Also,  `mergeMap(fn)` should always subscribe to the value returned by the provided function, assuming that value is subscribeable.

**Actual behavior:**
The code linked to above shows an example where `map(fn), mergeAll()` and `mergeMap(fn)` do not behave the same, and specifically `mergeMap(fn)` does not produce values as expected.  

In the example, `map(), mergeAll()` will properly map values to Observables, and then subscribe to those Observables and merge the values into a single stream. However, replacing the code with a `mergeMap` does not produce the same result. With `mergeMap`, no values are provided to the subscriber. It appears as if in this scenario, the `mergeMap` is not adding the inner subscriptions. I suspect this is a bug.

**Additional information:**
Here is context for where I am encountering this problem, and the mocked up example I provided:
I have an open source library built on top of RxJS. This library is responsible for handling API requests and responses between a client and a server. The communication between the client and server is via a websocket. The library allows you to make an API call to the server and returns an Observable for the response to the API call.

The library is built using RxJS 5.5.0-beta.5's lettable operators. The library distribution includes a bundled build that can be used in the browser. When the browser bundle is being used, it is likely that someone would be using the RxJS bundled library as well.

In the example posted here, I've mocked up an extremely simple version of the library. The library has an "ask" function that will make a fake API call and return an Observable for the response. In the `index.html` file, I am simulating using the library with an RxJS bundle. Specifically, I am trying to create a stream of API call responses using mergeMap. The mergeMap operator does not appear to be adding the inner subscriptions. However, if I use map(), mergeAll() instead, the API call response stream works as expected.

**Comment by skokenes** [comment]
One thing I'll add that I noticed, but don't understand.

The Observable that is the source for `mergeMap`, etc in the example has a `delay` operator on it. If I remove the `delay` operator, it works fine. However, with the `delay` operator, even with a value of `0`, the `mergeMap` stops working but the `map(),mergeAll()` continues working.

I'm specifically talking about this function in the mocked up lib (`index.js`):
```
// Mock up a delayed event for triggering API calls
function triggerAPICalls() {
    return Observable.of("init").pipe(
        delay(1000)
    );
}
```

**Comment by kwonoj** [comment]
it's very weird, cause when I tried your example on plain node.js with 5.5beta-5, it actually emits value:

![image](https://user-images.githubusercontent.com/1210596/31300516-fa5f5398-aaa8-11e7-8e95-55752e0c66f9.png)

and you're saying it's not emitting *any next* value with mergemap, is that correct?

**Comment by skokenes** [comment]
Yes that's correct. I can try putting this example on Jsfiddle or something
equivalent if it helps.

**Comment by kwonoj** [comment]
if you can create plain node.js based code snippet in one github repo, I think that'll be most isolated reproducible code.

**Comment by skokenes** [comment]
Ok but what if I can't reproduce in Node?   that doesn't mean there isn't a
bug visible in the browser.

**Comment by kwonoj** [comment]
snippet you shared seems pretty much isomorphic, I would be bit confused if given code makes differences between browser to node. That'll be already one isolation, next step would be what specific difference causes it.

**Comment by skokenes** [comment]
Got it, will try to reproduce there and post results.

**Comment by skokenes** [comment]
I've replicated it in Node in a weird way that I think may help point to the problem.

The issue does not exist when you are just using RxJS directly. It seems to arise when you mix the bundled build with other builds like the CJS modules. This is problematic for me because I am shipping a library built on RxJS that may be loaded in the browser and used in conjunction with the RxJS bundle. See this snippet:
```
var { Observable } = require("rxjs/observable");
var { of } = require("rxjs/observable/of");

var { Subject } = require("rxjs/subject");
var { delay, map, mergeAll, mergeMap, publishReplay, refCount, filter, take } = require("rxjs/operators");

// Bundled
var Rx = require("rxjs/bundles/Rx.js");


// Mock for an API request that returns a value
function ask(n) {
    return of(n).pipe(
        delay(1),
        take(1)
    );
}

// Mock up a delayed event for triggering API calls
function triggerAPICalls() {
    return of("init").pipe(
        delay(1000)
    );
}


var call$ = triggerAPICalls();

call$.pipe(
    //mergeMap(()=>ask(0)) // This works (mergeMap coming from CJS)
    Rx.operators.mergeMap(()=>ask(0)) // This does not work (mergeMap coming from bundle)
)
.subscribe(s=>console.log("mergemap next: ", s));

call$.pipe(
    Rx.operators.map(()=>ask(0)),
    Rx.operators.mergeAll()
)
.subscribe(s=>console.log("mergeall next: ", s));
```

I suspect that there is some issue with how Rx.operators.mergeMap is handling the inner subscription when the returned value is not an instance of Observable but does have the Symbol.observable (in the `subscribeToResult()` function). That is where the inner subscriber gets created in the code above (I think, if I traced it properly), but I don't think its being subscribed to properly in this situation...

Does this help?

**Comment by kwonoj** [comment]
wait, so you mean there are 2 RxJS loaded actually?

**Comment by skokenes** [comment]
Yea, right. I realize that makes no sense if you are doing a legit web development project where you are bundling up code and therefore common dependencies are being shared. But I believe it's valid for bundled builds in the browser.

Think of it this way: how do you ship a library of custom operators that can co-exist with an RxJS bundle loaded into the browser? My library of custom operators will most likely already load in the Observable class from an RxJS CJS or ESM before getting bundled up. Then a user uses that library next to the RxJS bundled library. That is where the issue is arising, where `mergeMap` isn't properly handling the Subscribe-able from my library that it doesn't recognize as the same Observable class from the main RxJS bundle.

Even if it's an unusual use-case, in general I think it's fair to say that if `mergeMap` (and also concatMap, switchMap, and maybe some other operators) can't properly handle Subscribe-ables from other libraries, then that is a bug.

If that is not the case, then how do we build custom libraries of operators that can co-exist in the browser with the main RxJS bundle?

**Comment by kwonoj** [comment]
First, I don't think it's a bug. If you're loading library in 2 different way, it's surely 2 separate set and you can't expect contexts are shared among those 2. I think it'll be pretty much same not only for RxJS, generally applicable for other cases.

Secondly, I think I lost somewhere - making custom operator set based on Rx doesn't mean you have to ship bundles causing duplicated loading of Rx. For example, well-known `redux-observable`(https://github.com/redux-observable/redux-observable) exactly does have custom observable classes but does not ship Rx for itself. I am not completely understand what your code trying to achieve when you create operator set, but you really shouldn't try to bundle them up - custom operator library set just try to use user side library.

**Comment by kwonoj** [comment]
In short - if your code is application, ensure to load single set of library. If your code is library, do not try to ship peerDependency and let user control dependency.

I do believe this is out of scope of this library itself, closing issue for now.

**Comment by skokenes** [comment]
Ok, I agree with you that if you are shipping a library as a browser bundle that should augment RxJS, then it should require the user have loaded an instance of RxJS into the global namespace. That makes sense.

I feel like closing this issue is debatable however because there is still the matter of `mergeMap` not responding to the Subscribeable properly. Regardless of how the Subscribe-able got there, the source code in https://github.com/ReactiveX/rxjs/blob/master/src/util/subscribeToResult.ts implies that is meant to be handled. According to the `if` statement, it checks not only for an Observable but also for a Promise and other types, with ways to handle the subscription. In this case, it is failing to handle the subscription of something that is absolutely subscribeable.

Or I could be misinterpreting `mergeMap`, and it should ONLY handle an Observable. But the code doesn't say that...

**Comment by skokenes** [comment]
Specifically I am talking about this section of `subscribeToResult`

```
else if (result && typeof result[Symbol_observable] === 'function') {
    const obs = result[Symbol_observable]();
    if (typeof obs.subscribe !== 'function') {
      destination.error(new TypeError('Provided object does not correctly implement Symbol.observable'));
    } else {
      return obs.subscribe(new InnerSubscriber(outerSubscriber, outerValue, outerIndex));
    }
```
In my example above, the observable passes the checking of having Symbol.observable and it has the `.subscribe` function, and yet it doesn't subscribe properly. May be worth looking into.

**Comment by kwonoj** [comment]
> In my example above, the observable passes the checking of having Symbol.observable and it has the .subscribe function, and yet it doesn't subscribe properly. May be worth looking into.

I thought that's cases where duplicated bundle set exists. If it's real case, that's obviosuly need to looked into - but I think better with new issue (this one's already tied with duplicated bundle set issue).

So you're saying observable check fails even with single library is loaded? if so, would you mind share reproducible code and separate issue for those?

**Comment by kwonoj** [comment]
and you're correct most of higher order observable variant should accept not only observable but also other subscribable.

**Comment by skokenes** [comment]
Ok I'll see if I can reproduce without duplicated bundle set. If so, I'll make a new issue. Thanks

**Comment by skokenes** [comment]
Seems to work fine using an Observable from `xstream`, I'm not going to dig any further. Thanks for the patience
