### ISSUE TITLE
shareReplay fix does not support lift

### ISSUE THREAD

**Issue by cartant** [ReactiveX/rxjs#2921]
The fix made to `shareReplay` in #2910 sees a non-lifted observable returned. The previous implementation returned an observable lifted from the source.

**RxJS version:** 5.5.0-beta.5

**Comment by kwonoj** [comment]
what's exact issue? is there regression occurred?

**Comment by cartant** [comment]
Yes, the previous implementation used `multicast` which calls `lift` on the source observable, allowing a source-determined instance to be returned. However, the fix uses `Observable.create` and the source's `lift` is no longer called and a source-determined instance won't be returned.

I can give you example code if you really want it, but I thought the issue was clear. That is, the source's implementation of `lift` will no longer be called.

**Comment by kwonoj** [comment]
I recall there were few not lifted around multicasting behavior, but can't recall exactly. /cc @benlesh

**Comment by kwonoj** [comment]
@cartant 
> implementation of lift will no longer be called.

yes, that's part I need to confirm that I recall there was few non-lifted around multicast already but I can't recall exactly (I mostly didn't write those)

**Comment by cartant** [comment]
I just noticed this in looking more closely at the fixed `shareReplay` in an attempt to determine what its expected behaviour ought to be - as I'd thought the previous, unfixed implementation was the expected behaviour.

Whether or not it should be lifted, I doubt is especially important. And it's not a regression that affects me. But it is a change.

**Comment by cartant** [comment]
Regarding `multicast` calling `lift`: it does. I checked the behaviours of the pre and post fix `shareReplay` implementations before creating this issue.

**Comment by benlesh** [comment]
FWIW: `shareReplay` has waffled between supporting `lift` and not, I think I can fix this before we close the beta.
