### ISSUE TITLE
Filter operator incorrect type inference

### ISSUE THREAD

**Issue by Iorg** [ReactiveX/rxjs#2927]
**RxJS version:** 5.5.0-beta.5

**Code to reproduce:**
```typescript
const a = Observable.from([1, '1'])
    .pipe(
        filter((x): x is string => typeof x === 'string')
    );

const b = Observable.from([1, '1'])
        .filter((x): x is string => typeof x === 'string');
```
**Expected behavior:**
Type of `a` and `b` must be `Observable<string>`

**Actual behavior:**
Type of `a` and `b` inferred as `Observable<string | number>`

**Additional information:**
Typescript: 2.5.3

tsconfig.json: 
```
{
    "compileOnSave": false,
    "compilerOptions": {
        "outDir": "./dist/out-tsc",
        "sourceMap": true,
        "declaration": false,
        "moduleResolution": "node",
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "target": "es5",
        "typeRoots": ["node_modules/@types"],
        "lib": ["es2016", "dom", "es2017.object"],
        "strictNullChecks": true,
        "noImplicitAny": true,
        "noImplicitThis": true,
        "noImplicitReturns": true,
        "strictFunctionTypes": true,
        "plugins": [
            {
                "name": "@angular/language-service"
            }
        ]
    }
}
```
Hi folks,

You created the most awesome reactive library I ever used. But I faced with the issue I cannot explain to myself.

PS: Are there any additional information I can collect to help with this issue?

**Comment by cartant** [comment]
This looks like a TypeScript problem, to me. And not a problem with the RxJS typings.

Interestingly, if `x: any` is specified in the arrow function passed to `filter`, the types will be inferred as you are expecting:

```ts
const a = Observable.from([1, '1'])
    .pipe(
        filter((x: any): x is string => typeof x === 'string')
    );

const b = Observable.from([1, '1'])
        .filter((x: any): x is string => typeof x === 'string');
```

**Comment by Iorg** [comment]
@cartant Thanks for answering,
It seems you are right here and this is a typescript problem. So we can close this issue.

BTW, did you faced with some relevant issue on TS repo?

**Comment by Iorg** [comment]
I guess, that one: https://github.com/Microsoft/TypeScript/issues/18562

**Comment by cartant** [comment]
Closing this as it's a TypeScript issue - see the comment above.
