### ISSUE TITLE
Handle stream like maybe monad

### ISSUE THREAD

**Issue by ghost** [ReactiveX/rxjs#2930]
Hi all 

Consider following stream:
```
     const oEmailValid$ = oEmailInput$
          .map(_catchInputCtrlValue)
          .map(_isStringNotEmpty) 
          .map(...)
          .map(...)
          .map(...)
          .map(...)
          .subscribe((predicate) => console.log(predicate))
```

Suppose `_isStringNotEmpty` returns `false`, so I wan't to continue the stream but still want to receive on the subscribe function the returned value of `_isStringNotEmpty`, in this case is `false`.   

How to get it? 

To clarify, what I mean, consider the following `Haskell` code:
 
`(Just 3) >>= (\_ -> Just 4) >>= (\_ -> Just 7) >>= (\_ -> Nothing) >>= (\_ -> Just 10)`

As the result I've got `Nothing`, because the 4th computation returns `Nothing`.  

Thanks

**Comment by benlesh** [comment]
@kostonstyle ... I believe you're looking for `mergeMap` rather than `map` above, and you'd have each of those functions return an `Observable`, rather than a plain value.

**Comment by BioPhoton** [comment]
Hi @ghost!

Here you ave a working example for your problem. If you need any further help just comment.
If your problem is solved please close this issue

```typescript
const _isValidName = (arr) =>  (v) => ({validName: arr.includes(v)});
const _isStringNotEmpty = (v) => ({StringNotEmpty: v !== ''});

fromEvent(document.getElementById('input'), 'input')
  .pipe(
    map(e => e.target.value),
    switchMap(v => 
      merge(
        of(v).pipe(map(_isValidName(['Tom', 'Eric']))), 
        of(v).pipe(map(_isStringNotEmpty))
      )               
    ),
    scan((e, v) => ({...e, ...v}))      
  )
  .subscribe((predicate) => console.log(predicate))
```
