### ISSUE TITLE
include sourcesContent in source-maps in npm package

### ISSUE THREAD

**Issue by Delagen** [ReactiveX/rxjs#2934]
**RxJS version:** 5.5.0-beta.5

**Code to reproduce:**
Any bundler, i.e Webpack

**Expected behavior:**
No errors

**Actual behavior:**
Multiple errors
```
Cannot find source file '../src/Scheduler.ts': Error: Can't
 resolve '../src/Scheduler.ts' in '....\node_modules\rxjs'
```

**Additional information:**

**Comment by benlesh** [comment]
cc @jasonaden

**Comment by Delagen** [comment]
@benlesh Doesn't fixed
```
Emitted value instead of an instance of Error) Cannot find source file './src//util/EmptyErr
or.ts': Error: Can't resolve './src//util/EmptyError.ts' in '...\node_modules\rxjs\util'
```
and many similar errors.
Again: In NPM package NO TS source files.

**Comment by benlesh** [comment]
@Delagen this is in `5.5.0-beta.7` now?

**Comment by Delagen** [comment]
@benlesh Yes. As you can see, path changed )
