### ISSUE TITLE
Incorrect documentation about operator `share`.

### ISSUE THREAD

**Issue by mocheng** [ReactiveX/rxjs#2937]
**RxJS version:**
5.4.3

**Expected behavior:**
The documentation of `share` should be correct.

**Actual behavior:**
The doc https://github.com/reactivex/rxjs/blob/master/src/operators/share.ts#L16 reads

> This is an alias for .publish().refCount()

This is not correct. The operator `share` is actually  a alias for `.multicast(() => new Subject()).refCount()`. There is difference between these two definition.

For `.publish().refCount()`, subscription after source completion will not re-execute the pipeline. However, for `share()`, subscription after source completion do re-execute the pipeline.

Check below example
```
import {Observable} from 'rxjs/Observable';
import 'rxjs/add/observable/interval';
import 'rxjs/add/operator/publish';
import 'rxjs/add/operator/take';

const tick$ = Observable.interval(1000).take(3);
const sharedTick$ = tick$.publish().refCount();

sharedTick$.subscribe(value => console.log('observer 1: ' + value));
setTimeout(() => {
  sharedTick$.subscribe(value => console.log('observer 2: ' + value));
}, 4500);
```
Output of above code is:
```
observer 1: 0
observer 1: 1
observer 1: 2
```

And for share:
```
import {Observable} from 'rxjs/Observable';
import 'rxjs/add/observable/interval';
import 'rxjs/add/operator/share';
import 'rxjs/add/operator/take';

const tick$ = Observable.interval(1000).take(3);
const sharedTick$ = tick$.share();

sharedTick$.subscribe(value => console.log('observer 1: ' + value));
setTimeout(() => {
  sharedTick$.subscribe(value => console.log('observer 2: ' + value));
}, 4500);
```

Above code has below output:
```
observer 1: 0
observer 1: 1
observer 1: 2
observer 2: 0
observer 2: 1
observer 2: 2
```

**Comment by benlesh** [comment]
Yup... you're right. That is a miss on the docs.

cc/ @ladyleet

**Comment by crunchie84** [comment]
I wanted to fix this but it seems that this is already (partly) addressed in https://github.com/ReactiveX/rxjs/blob/master/src/operator/share.ts but that is a different file (`src/operator/xx` vs `src/operators/xx`). Based on other files in those folders it is hard to discern where the documentation should reside. 

@benlesh @ladyleet which of those paths should be the one containing the documentation of the operator?

**Comment by staltz** [comment]
Done with PR #2990
