### ISSUE TITLE
Path mapping instructions are incorrect

### ISSUE THREAD

**Issue by filipesilva** [ReactiveX/rxjs#2979]
**RxJS version:** 5.5.0

**Code to reproduce:** follow https://github.com/ReactiveX/rxjs/blob/master/doc/lettable-operators.md#build-and-treeshaking

**Expected behavior:** `rxPaths()` function call works.

**Actual behavior:**
```
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.resolve (path.js:186:7)
    at module.exports (D:\sandbox\master-project\node_modules\rxjs\_esm5\path-mapping.js:8:31)
```

**Additional information:**
`rxPaths` source seems to receive a path that it will use for the replacement. It looks like it should be called with the path to the project's node_modules. Perhaps it should be using `__dirname` instead to avoid passing the path?

**Comment by kwonoj** [comment]
It's cause we updated logic after 5.5 and not yet published new changes - refer https://github.com/ReactiveX/rxjs/pull/2974/files . So you're correct, current 5.5 need to provide dirname as param. I'm closing this as it'll be resolved once we push new patch release.

**Comment by filipesilva** [comment]
Got it, will wait on Angular CLI support then.

**Comment by hansl** [comment]
@kwonoj @benlesh Why can’t you use the __dirname from the path-mapping script to figure out the path, instead of using an argument (or alternatively if the argument is undefined)? Seems like an easier option.

**Comment by kwonoj** [comment]
That's way newly changed script doing. It is just not published yet.
