### ISSUE TITLE
Version 5.5 bug

### ISSUE THREAD

**Issue by vmagalhaes** [ReactiveX/rxjs#2989]
Hi,

I changed my rxjs version to 5.4.1 because 5.5.0 doesn't work.
When I tried to run the app this problems are display to me: 

![screenshot from 2017-10-23 11-25-45](https://user-images.githubusercontent.com/14242447/31891532-72246460-b7e5-11e7-835b-4fb7456a9dc6.png)

And bug any route too

![screenshot from 2017-10-23 11-34-06](https://user-images.githubusercontent.com/14242447/31891755-1bca656e-b7e6-11e7-927d-09a3ea27590d.png)

My systemjs.config.js

`(function(global) {

  // map tells the System loader where to look for things
  var map = {
    '@angular':   'node_modules/@angular',
    'moment':     'node_modules/moment',
    'rxjs':       'node_modules/rxjs'
  };

  // packages tells the System loader how to load when no filename and/or no extension
  var packages = {
    'moment':     { main: 'moment.js', defaultExtension: 'js' }
  };

  var ngPackageNames = [
    'common',
    'compiler',
    'core',
    'forms',
    'http',
    'platform-browser',
    'platform-browser-dynamic',
    'router',
    'router-deprecated',
    'testing',
    'upgrade'
  ];

  // Individual files (~300 requests):
  function packIndex(pkgName) {
    packages['@angular/'+pkgName] = { main: 'index.js', defaultExtension: 'js' };
  }

  // Bundled (~40 requests):
  function packUmd(pkgName) {
    packages['@angular/'+pkgName] = { main: 'bundles/' + pkgName + '.umd.js', defaultExtension: 'js' };
  }

  // Most environments should use UMD; some (Karma) need the individual index files
  var setPackageConfig = System.packageWithIndex ? packIndex : packUmd;

  // Add package entries for angular packages
  ngPackageNames.forEach(setPackageConfig);

  var config = {
    defaultJSExtensions: true,
    map: map,
    packages: packages
  }

  // filterSystemConfig - index.html's chance to modify config before we register it.
  if (global.filterSystemConfig) { global.filterSystemConfig(config); }

  System.config(config);

})(this);
`

Do you know what can I do to fix this?

**Comment by richtera** [comment]
I am also running into problems with 5.5.0. It seems it no longer patches Observable with the loaded operators. Is there a way to patch them or are you required to use the "::" operator?

**Comment by montella1507** [comment]
Check closed issues. Already solved and there will be fix in new version.

**Comment by richtera** [comment]
Thank you. I am currently using a workaround
```javascript
// Setup what we need of the rxjs system.
import { Observable } from 'rxjs/Observable';
import { mergeMap } from 'rxjs/operator/mergeMap';
import { take } from 'rxjs/operator/take';
import { map } from 'rxjs/operator/map';
import { mapTo } from 'rxjs/operator/mapTo';
import { takeUntil } from 'rxjs/operator/takeUntil';
import { race } from 'rxjs/operator/race';
import { filter } from 'rxjs/operator/filter';
import { of } from 'rxjs/observable/of';
import { race as Srace } from 'rxjs/observable/of';

Object.assign(Observable.prototype, { mergeMap, take, map, mapTo, mergeMap, flatMap: mergeMap, takeUntil, race, filter });
Object.assign(Observable, { race: Srace, of });
```
When will the release be up?

**Comment by richtera** [comment]
BTW: The import using @reactivex/rxjs vs rxjs is going to be a problem until redux-observable uses the new import. Or is there a standard way to alias modules that way?

**Comment by kwonoj** [comment]
closing as v6 changed most of import ergonomics.
