### ISSUE TITLE
CHANGELOG changes link problem

### ISSUE THREAD

**Issue by kylecordes** [ReactiveX/rxjs#2994]
The CHANGELOG currently has this link for the changes in 5.5.1:

`https://github.com/ReactiveX/RxJS/compare/5.5.0...v5.5.1`

https://github.com/ReactiveX/RxJS/compare/5.5.0...v5.5.1

This link doesn't work, because of a spurious "v". This link does work:

`https://github.com/ReactiveX/RxJS/compare/5.5.0...5.5.1`

https://github.com/ReactiveX/RxJS/compare/5.5.0...5.5.1

**Comment by princemaple** [comment]
Was about to report this one, found it's already reported ;) ^^^
