### ISSUE TITLE
Not working in web workers

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#300]
After discussing with @vsavkin, it was determined that our utility for getting a reference to the root or global scope was not properly handling scenarios where RxJS Next was being run in a Web Worker.

In a web worker, the global scope is `self` and not `global` or `window`.

**Comment by trxcllnt** [comment]
@blesh @vsavkin we should probably remove the global stuff anyway (in favor of some flavor of DI).

**Comment by blesh** [comment]
but I can DI anything sideways in JavaScript! :P look at me:

```js
window.setTimeout = function(cb) {
  console.log('haha! no timeout for you!');
  cb();
  return 'LOLZ';
};
```

**Comment by trxcllnt** [comment]
@blesh that's exactly why we should move to "functor modules" like @steveorsomethin uses.

**Comment by blesh** [comment]
Yeah, I like that idea. I'm concerned about the consumption by "the masses" a little. Just default usage seems like it would be really strange for people.

`Rx().Observable` ... people would be like "why is the namespace a function?". I think i most cases, many developers would end up calling `Rx()` over and over again, rather than caching the result, when 99.999999% of the time they just want one instance and configuration of Rx.

As it currently stands, given the modular nature of the library, experts would be welcome to do that on their own, of course.

**Comment by trxcllnt** [comment]
@blesh my proposal:

- `import Rx from '@ReactiveX/RxJS'` would give you Rx like normal
- `import ObservableFactory from '@ReactiveX/RxJS/Observable'` would give you back the Observable's "functor module" which accepts all its dependencies as parameters (including the classes it would normally import).

Then people can instrument versions of Rx with overridden globals, etc. as would have been the solution here.

**Comment by blesh** [comment]
That might mesh well with Angular's DI, actually. @vsavkin? @jeffbcross?

**Comment by robwormald** [comment]
@blesh this also fixes the wacky TVJS (appleTV) bug i discovered the other day :+1: 

I don't believe we're dependency-injecting Observables anywhere in NG2 (yet) but I'm all for @trxcllnt's proposal.
