### ISSUE TITLE
Barrel for observable creation operators ?

### ISSUE THREAD

**Issue by ghetolay** [ReactiveX/rxjs#3003]
Just wondering why there isn't a barrel file at `rxjs/observable/` reexporting all operators like for `rxjs/operators` ?

So we could do 
```ts
import { of, from, interval } from 'rxjs/observable';
```

**Comment by davideast** [comment]
I like this idea. We would have to check to see that it would still be easy to tree-shake out unneeded dependencies.

Thoughts @benlesh?

**Comment by benlesh** [comment]
I was discussing something similar with @jayphelps the other day.

At first I wanted to just export everything from `rxjs`...but realized that the static methods would be problematic,,, e.g. `concat` the observable creation method, and `concat` the functional operator.

There are a few options here, and this is one of them that has been discussed.

**Comment by benlesh** [comment]
I think I'd like to keep the discussion over here: #2912

Closing this as a duplicate
