### ISSUE TITLE
operators.js bug in SystemJS

### ISSUE THREAD

**Issue by vmagalhaes** [ReactiveX/rxjs#3011]
Hi,

Someone know if in 5.5.3 version the bug 'operators.js not found' will be fixed for SystemJS projects? I'm having to place the operators.js file inside my build and it's super wrong. 

Any news about it?

Thanks.

**Comment by jasonaden** [comment]
@ViictorG1 This should have been fixed with 5.5.1. If you're still seeing issues, please give us a repro case.

**Comment by jasonaden** [comment]
@ViictorG1 I see the other issue now. Yes, I can send a PR for this.

**Comment by ViictorG1** [comment]
@jasonaden Are you do a new version to work thr systemjs projects?

**Comment by mlc-mlapis** [comment]
@jasonaden ... from your comment here https://github.com/ReactiveX/rxjs/issues/2971#issuecomment-337746248 we all supposed that the problem with missing `operators.js` is clear.

**Comment by kwonoj** [comment]
I think we'd dealt most in v5 and this is outdated issue, closing.
