### ISSUE TITLE
Create a test for SystemJS support

### ISSUE THREAD

**Issue by jasonaden** [ReactiveX/rxjs#3012]
There are a few issues around SystemJS support. A test is needed to confirm that SystemJS is working as expected.

**Comment by ViictorG1** [comment]
Yes, in my project, the version 5.5.2 don't fix the path bug of operators.js

**Comment by benlesh** [comment]
@jasonaden is this done? Does this still need done?

**Comment by jasonaden** [comment]
@benlesh I think this was done [here](https://github.com/ReactiveX/rxjs/pull/3412). I'll close.
