### ISSUE TITLE
takeUntil doesn't work with ignoreElements

### ISSUE THREAD

**Issue by errorx666** [ReactiveX/rxjs#3016]
**RxJS version:**
5.5.2

**Code to reproduce:**
```js
const { Observable } = require( 'rxjs' );

const done = Observable.timer( 1000 ).ignoreElements();

done
.subscribe(
    console.log.bind( console, 'done next' ),
    console.log.bind( console, 'done error' ),
    console.log.bind( console, 'done complete' )
);

Observable.timer( 0, 100 )
.takeUntil( done )
.subscribe(
    console.log.bind( console, 'next' ),
    console.log.bind( console, 'error' ),
    console.log.bind( console, 'complete' )
);
```

**Expected behavior:**
Timer completes when done completes.

**Actual behavior:**
Done completes, but timer continues to emit items.

**Additional information:**
According to http://reactivex.io/documentation/operators/takeuntil.html:

The TakeUntil subscribes and begins mirroring the source Observable. It also monitors a second Observable that you provide. If this second Observable emits an item **or sends a termination notification**, the Observable returned by TakeUntil stops mirroring the source Observable and terminates.

**Comment by errorx666** [comment]
Just noticed this is a duplicate of #2160.

**Comment by benlesh** [comment]
Yeah.. this is to be expected.

`complete` isn't a single that you have something to use... it's a signal that you're not going to get anything to use.  We really just need the docs to be updated, I think.
