### ISSUE TITLE
"flatCatchMap"

### ISSUE THREAD

**Issue by masaeedu** [ReactiveX/rxjs#3023]
Doing error handling with `flatMap` is a little annoying, because you have to turn `.flatMap(i => promisy())` into `.flatMap(i => Rx.Observable.from(promisy()).catch(e => ["substitute busted items"]))`. 

It'd be nice if we had something like `flatCatchMap` (name totally negotiable), which would accept a projection to transform values into observable-likes, and another projection to transform errors into observable-likes.

**Comment by staltz** [comment]
Hi @masaeedu 

The basic `catch` operator is like flatMap, because

- `mergeMap(projectNext)`
- `catch(projectError)`

Where

- `projectNext` has type `(t: T) => Observable<R>`
- `projectError` has type `(err: any) => Observable<R>`

So you can actually do

```js
source$
  .flatMap(i => Rx.Observable.from(promisy())
  .catch(err => someObservableHere)
```

**Comment by masaeedu** [comment]
@staltz The parentheses in there aren't balanced; I'm not sure whether you intended an extra closing parens after `Rx.Observable.from(promisy())` or after `someObservableHere)`. 

Assuming you're saying I should use:

```
source$
  .flatMap(i => observableLike(i))
  .catch(err => someObservableHere)
```

, this doesn't work the same way as:

```
source$
  .flatMap(i => Rx.Observable.from(observableLike(i)).catch(err => someObservableHere))
```

The important difference is that in the second snippet multiple errors can be produced and handled, whereas in the former you basically abort the flatmap and substitute the entire result with something else as soon as a single error occurs.

**Comment by staltz** [comment]
You're correct about that nesting, and it depends what you want to achieve. If you want to handle multiple errors from multiple promises, then nesting is required. If you want to make a shortcut operator for this use case, you can do that quite easily as a normal function, then utilize it with `let(myFunction)`. When it comes to operators in RxJS, it's important to stay with only fundamental operators, so we reduce learning costs, documentation efforts, analysis paralysis, test redundancy, and overall maintenance cost.

**Comment by masaeedu** [comment]
The problem here is that `flatMap` is about as fundamental an operator as you can get, and in 90% of projects that's the only one I really use (most other things you can implement on top of that). If I'm flatMapping over 10 levels of asynchronicity or many-ness and keep having to do `.catch(e => ["failed"])` to propagate errors down the chain, the code becomes really unwieldy and verbose.

There's a proposal in #2929 for removing `resultSelector` from `flatMap`, I think the newly freed up second argument would be a good place for an error selector.

I could write my own operator as you said, but I'd have to package it, distribute it, manage compatibility and versioning, add an extra dep in each project, etc.

**Comment by staltz** [comment]
> I could write my own operator as you said, but I'd have to package it, distribute it, manage compatibility and versioning, add an extra dep in each project, etc.

Yes. Either way someone would have to package it, distribute it, maintain it, etc. :)

**Comment by masaeedu** [comment]
@staltz My point is that work for packaging and distributing operators is already done here, it's amortized over the total cost of doing development for this library. Doing all that for a single operator is more tedious.

**Comment by benlesh** [comment]
Honestly, most of the time you want to compose the error handling into the observable *inside* of your flattening operator:

```ts
source.flatMap(() => from(promisey()).catch(err => empty()))
```

And maybe you want `retry` or `retryWhen` or maybe you just want to let it die and handle it further down the pipe.

**Comment by masaeedu** [comment]
@benlesh I know that the error handling is supposed to happen *inside* the flattening operator, my point is that it's less verbose to do this:

```
.flatMap(async () => { ... await foo }, err => [])
```

Than to do:

```
.flatMap(() => Rx.Observable.from(async () => { ... await foo }).catch(err => []))
```

especially given the frequency with which you have to do this in code using Rx.

**Comment by benlesh** [comment]
Now that we have pipe, it's trivial to create and use (or even publish) your own operators. Given that, I think we can close this.
