### ISSUE TITLE
Named import of `let` is called `letProto` in CJS/ESM but `letBind` in UMD builds

### ISSUE THREAD

**Issue by jayphelps** [ReactiveX/rxjs#3024]
https://github.com/ReactiveX/rxjs/blob/c7cfe444642407f3227a09a0cdf38fd495b867e1/src/add/operator/let.ts#L3-L6

Since the name of the import itself `letProto` is different than what's on the prototype `letBind`, you cannot resolve `letProto` correctly with a UMD build. e.g. redux-observable wanted to use `letProto` internally, but when I build a UMD of redux-observable the `letProto` resolution fails as described.

This process of mapping ESM path -> prototype is done by [webpack-rxjs-externals](https://github.com/jayphelps/webpack-rxjs-externals/blob/ef6a41ab5537c0ff4a44c4d2192a1ead7e7045e7/index.js#L2-L9)

This seems like a case where, while this is a bug, people likely rely on these names as they are so changing them would break things. However, perhaps adding `Observable.prototype.letProto` would be an OK compromise for v5 since its additive?

**Comment by jayphelps** [comment]
btw for our particular case, we don't even need to use `letProto` after all because (duh) it's so simple we can just call the function ourselves. So this isn't blocking me.

**Comment by benlesh** [comment]
This is no longer an issue. People should be using pipe.
