### ISSUE TITLE
Documentation: Add "IsFinite" information

### ISSUE THREAD

**Issue by montella1507** [ReactiveX/rxjs#3028]
**RxJS version:**
All

**Additional information:**
I think one of the biggest problem is, a user has no easily found information about  the "lifetime" of  a subscription. 

For example it would be nice to know, when do you have to Unsubscribe (because the operator will make unfinite observable)  and when not (take())

is it possible to add "Finite: true/false" information to every operator?

**Comment by kwonoj** [comment]
what does `finite` exactly means?

**Comment by montella1507** [comment]
finite / infinite observables?

Observable.interval(500)  // infinite  -> emits values forever, you have to unsubscribe, or you would have possible wrong behavior / memory leaks (hoisting in callback)
Observable.interval(10).take(1)  // finite -> emits limited values, you do not have to unsubscribe, the memory will be freed

**Comment by benlesh** [comment]
It's a reasonable suggestion, but there hasn't been much additional interest, closing for now.
