### ISSUE TITLE
refCount.js is blocked by ad blockers

### ISSUE THREAD

**Issue by Yoten** [ReactiveX/rxjs#3033]
**RxJS version:**
5.5.2

**Code to reproduce:**
N/A

**Expected behavior:**
All files should load as expected

**Actual behavior:**
"operators/refCount.js" is blocked by the "EasyPrivacy" 3rd-party list used by default by ad blockers such as uBlock Origin, causing fetch errors when other files such as "share.js" depend on it.

**Additional information:**
Screenshot of fetch error & uBlock Origin entry:

![blocked](https://user-images.githubusercontent.com/7014187/32283641-59c7d74a-befb-11e7-8155-7f04508cd798.PNG)

I realize this is more of an issue of EasyPrivacy needing to tweak their filters rather than an RXJS problem, but this seems severe enough that I'm surprised I haven't been able to find anyone else talking about it.

**Comment by kwonoj** [comment]
This feels super weird, our refCount impl doesn't do any network request  and any ad-related (of course). Is it able to find reason why it's blocked? without knowing reason I don't know what can we do from our end.

**Comment by Yoten** [comment]
My best guess is that some kind of tracking scripts/cookies/etc. is using the name "refcount" in one of their files and that's what got the name added to the anti-privacy list. It's not that they're specifically blocking RXJS's refCount.js, but that the name "refcount.*" in general is blocked -- the filter is set too vaguely.

I don't think there's anything you guys need to do on your end code-wise, but it might be worth posting on the EasyList forums and asking if they can change the filter on their end to prevent this false positive:

https://forums.lanik.us/viewforum.php?f=64

**Comment by kwonoj** [comment]
I don't think there's much actionable on our end, closing issue for now. ad blockers should correct their listing mechanism.

**Comment by JoshKisb** [comment]
How about just changing the name?

**Comment by trahloff** [comment]
Could you guys please just rename it? 
Being blocked by an AdBlocker is a serious business hazard for a company. 
I just came here because a client phoned me...
