### ISSUE TITLE
toPromise and do are not importable via operators

### ISSUE THREAD

**Issue by NCC1701M** [ReactiveX/rxjs#3037]
**RxJS version:** 5.5.2

**Code to reproduce:**
```ts
import { do, map, toPromise } from "rxjs/operators";
```

**Expected behavior:**
do and toPromise should be importable from rxjs/operators like e.g. map, buffer debounce and so on.

**Actual behavior:**
do and toPromise are not importable via the statement above instead the following statements are required:
```ts
import "rxjs/add/operator/do";
import "rxjs/add/operator/toPromise";
```
this is inconsistant.

**Comment by kwonoj** [comment]
https://github.com/ReactiveX/rxjs/blob/master/CHANGELOG.md#bug-fixes-4 for `toPromise` and https://github.com/ReactiveX/rxjs/blob/master/doc/lettable-operators.md#lettable-operators for `do->tap` .
