### ISSUE TITLE
fromEventPattern not assignable to Subscription

### ISSUE THREAD

**Issue by getabetterpic** [ReactiveX/rxjs#3038]
**RxJS version:**
5.4.3

**Code to reproduce:**
```typescript
elementSubscription: Subscription;

listenForElementReady(element): void {
  this.elementSubscription = Observable.fromEventPattern((handler) => element.on('ready', handler) );
  this.elementSubscription.subscribe((resp) => {
    this.elementIsReady = true;
  });
}
```

**Expected behavior:**
Allow a subscription to be set from an `Observable.fromEventPattern`.

**Actual behavior:**
```
Type 'FromEventPatternObservable<{}>' is not assignable to type 'Subscription'.
  Property 'closed' is missing in type 'FromEventPatternObservable<{}>'
```

**Comment by kwonoj** [comment]
`Observable.fromEventPattern` returns observable you can subscribe, and `subscribe` returns subscription. You did subscribe as expected, but trying to assign observable into subscription variable instead of actual subscription returned by subscribe.

**Comment by getabetterpic** [comment]
Ah, I see my mistake now. Thanks!
