### ISSUE TITLE
Marble diagram tests just don't work for synchronous scenarios

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#304]
For example: `Observable.of(1,2,3)` ... how are you going to represent 3 values and a completion in 1 frame? `123|`? and then how does that "line up" to expected results? What about 3 values and an error? what about 100ms, then 14 synchronous values, then 200ms then one value and it completes?

It's a shame because I find the look of the test DSL very compelling.

@mattpodwysocki can say "I told you so". :p

cc/@staltz and @trxcllnt

**Comment by staltz** [comment]
Why do you even need a marble diagram for purely synchronous cases? I think the DSL should be used only where convenient.

**Comment by headinthebox** [comment]
And since it is just a string, you can invent new notation for the sync case, like [1,2,3] or 1#2#3.

**Comment by blesh** [comment]
>Why do you even need a marble diagram for purely synchronous cases? I think the DSL should be used only where convenient.

Imagine `last`,  observable runs for some amount of time, then when it completes, it synchronously nexts, then completes in the same frame. That's not `------a|` by our notation.

I've been thinking of something like @headinthebox was saying, but it messes with the ability to line them up.

```
e3.withLatestFrom(e1,e2)


e1 -a---|
e2 ---b-----|
e3 ------c---d----|
r  ------[cab]----|

// What about `[dab]`? 
```

I spouse the upside is, since they're tests you can specify that this shouldn't happen, but it worries me that I'll run into something else I haven't considered

**Comment by staltz** [comment]
Then just define e3 differently:

e3.withLatestFrom(e1,e2)

```
e1 -a---|
e2 ---b-----|
e3 ------c-----d----|
r  ------[cab]-[dab]--|
```

**Comment by blesh** [comment]
Right. That's what I was saying. I'm just worried that there's something else I'm missing

**Comment by staltz** [comment]
Completely irrelevant to this thread, but since we're at it, for purely aesthetic purposes I prefer parentheses:

`r ----(cab)--|`

**Comment by blesh** [comment]
I like that, it doesn't visually match the pipe as much
