### ISSUE TITLE
`Rx.Observable.from` does not properly handle `NodeList`

### ISSUE THREAD

**Issue by Dorus** [ReactiveX/rxjs#3041]
Consider the following code:
```Js
const buttons = document.querySelectorAll('.btn');

const button$ = Rx.Observable.from(buttons);
const button2$ = Rx.Observable.from(buttons);

button$.subscribe(x => console.log('observer 1 ', x)); // emit
button$.subscribe(x => console.log('observer 2 ', x)); // nothing
button2$.subscribe(x => console.log('observer 3 ', x)); // emit
```

`Rx.Observable.from` should result in a cold observable that emit the same list each time it is subscribed. However, in this example the source is a [NodeList](https://developer.mozilla.org/en-US/docs/Web/API/NodeList) and the second subscription does not emit.

**Comment by kwonoj** [comment]
does fromObservable suppose to return cold explicitly? I thought it depends on source type, like from(Promise) you won't get cold suscribes into new promise each time automatically.

**Comment by Dorus** [comment]
As far as i know promises are eager so it's not even possible for `from(Promise)` to be anything other than cold. Only `fromPromise(() => Promise)` is able to rerun the Promise.

**Comment by david-driscoll** [comment]
Makes me think that for `NodeList` (and friends) if it finds the `Iterator` it's pulling that out.  Not 100% sure on that however.

**Comment by kwonoj** [comment]
I think my main question in here is this: does `from` explicitly intended to return cold? I think I didn't have indication around those. Dealing with NodeList from static creation seems separate discussion.

**Comment by Dorus** [comment]
Interesting enough, `from` does reread the source. I stand corrected:

```Js
var ar = [1,2,3];
const ar$ = Rx.Observable.from(ar);
ar$.subscribe(x => console.log('observer 1 ', x)); // 1,2,3

ar[2] = 5
ar$.subscribe(x => console.log('observer 2 ', x)); // 1,2,5
```

**Comment by cartant** [comment]
Regarding the iterator, in stable, it's [obtained in the `constructor`](https://github.com/ReactiveX/rxjs/blob/stable/src/observable/IteratorObservable.ts#L48-L56). However, in master, it's [obtained in `_subscribe`](https://github.com/ReactiveX/rxjs/blob/master/src/observable/IteratorObservable.ts#L56-L59). So the next version will behave as the OP is expecting.

**Comment by kwonoj** [comment]
I just came to remind this, is this related with https://github.com/ReactiveX/rxjs/pull/2497 ?

**Comment by kwonoj** [comment]
oh @cartant already pointed it.

**Comment by Dorus** [comment]
I think i actually prefer `from` to reread the source, that's quite neat. So all we have to do is wait for the next major.

My question is answered so it can be closed for me, unless anyone has another reason to keep it open?

**Comment by kwonoj** [comment]
@Dorus let me close issue, and sorry for bringing confusion. I did misread original issue obviously and caused confusions around.

**Comment by cartant** [comment]
@Dorus You likely already know this, but you can work around the problem in version 5 using `defer`:

```js
const button$ = Rx.Observable.defer(() => Rx.Observable.from(buttons));
```

**Comment by Dorus** [comment]
@cartant Yes i did know that, but thanks for the suggestion anyway. It's exactly what i suggested @mocheng on gitter [3 november 2017 12:14](https://gitter.im/Reactive-Extensions/RxJS?at=59fc4fa3614889d4753554be) as he's the one that came up with this scenario.

@kwonoj No prob about the confusion, at least it kept the issue active and quickly resolved :)
