### ISSUE TITLE
Observable.interval in inactive tab work different than plain js setInterval()

### ISSUE THREAD

**Issue by nikshik** [ReactiveX/rxjs#3042]
Observable.interval in inactive tab work different than plain js setInterval()

Open http://jsbin.com/muvaqipaqa/1/edit?html,js,console,output
See 'i:0', 'j:0', ... in console. Switch to another browser tab for 30 seconds or so. Switch back to jsbin tab. See that i have much more different value than j

**RxJS version:**
5.5.2

**Code to reproduce:**
http://jsbin.com/muvaqipaqa/1/edit?html,js,console,output

**Expected behavior:**
i and j have same values
**Actual behavior:**
i and j have different values

**Comment by kwonoj** [comment]
you can't expect interval observable works identical to setInterval as interval observable have scheduling to create inverval values.

this seems browser implementation does try to prevent js execution in background for inactive tabs. I'm not sure devtools allows to disable it - if it's possible, please check with it to confirm.

**Comment by nikshik** [comment]
Rly? So if Observable.interval will be called after 1500 ms instead of expected 1000 ms this is fine?
You mean I should not expect Observable.interval to work correctly in browsers? 
I'm pretty sure this is an issue with rxjs implementation...

**Comment by nikshik** [comment]
If you check it in jsbin with RxJs 5.0.3 it works as expected, in 5.5.2 it doesn't!
Please reopen issue

**Comment by kwonoj** [comment]
hmm, yeah that sounds odd. I thought it's happening all time.

**Comment by kwonoj** [comment]
Reopened.

**Comment by benlesh** [comment]
You need to be careful relying on setInterval, setTimeout, etc in JSBin, I've seen some odd behavior there, and I think it's being patched or hooked in some way by JSBin.

**Comment by nikshik** [comment]
Thanks for the hint! I will pay attention to it.
Anyway I initially found the issue on my local environment, just added example to jsbin.
