### ISSUE TITLE
Can't update catch to 5.5 (lettable operator)?

### ISSUE THREAD

**Issue by mmc41** [ReactiveX/rxjs#3046]
**RxJS version:**
5.5.2

**Code to reproduce:**
I am trying to update old rxjs code to 5.5.2 by updating this code:

```
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/catch'

getTextFile(url: string): Observable<string> {
    return this.http.get(url, { responseType: 'text' })
                    .catchError((error, source) => ... );
  }
```

to this code as noted in the rxjs release notes: 
```
import { map, catchError } from 'rxjs/operators';

 getTextFile(url: string): Observable<string> {
    return this.http.get(url, { responseType: 'text' })
                    .catchError((error, source) => ...);
  }

```
**Expected behavior:**
Should compile.

**Actual behavior:**
Get error:
message: 'catchError' does not exist on type 'Observable<string>'

So it does not like the new catchError or what ?

**Comment by jlariza** [comment]
I am having the same issue, were you able to solved it?

**Comment by martinsik** [comment]
@jlariza `catchError` is an operator that needs to go inside the `.pipe()`:
```
this.http.get(...).pipe(catchError(...))...
```

**Comment by jlariza** [comment]
@martinsik thank you! that worked. The documentation is not very clear about that migration.

Thanks!
