### ISSUE TITLE
Proposal for .takeWhen

### ISSUE THREAD

**Issue by machtyn** [ReactiveX/rxjs#3056]
This is a proposal to add `.takeWhen` and `.skipWhen` methods.

I had a requirement where I needed to poll a service and then take the response only when a specific property of the response was equal to a term.  `.takeWhile` gave me all the responses up to the last.  `.skipWhile` gave me the last response and then kept calling.  I ended up using a combination of `.skipWhile().take(1)`.  Essentially, `.takeWhen(true)` will mimic `.skipWhile(true).take(1)`

![takewhen](https://user-images.githubusercontent.com/16729235/32509117-6cbeee4c-c3ba-11e7-8da0-620222067e60.png)

`.skipWhen` will be the inverse of that. Essentially the observable will pass the response only when `.skipWhen(false)`

![skipwhen](https://user-images.githubusercontent.com/16729235/32509116-6cb0f6f2-c3ba-11e7-8b98-812eb0eead5a.png)

**Comment by kwonoj** [comment]
with `let` and new pipe-able operator structure introduce in 5.5, we are recommding creating new operator as user-level one (https://github.com/ReactiveX/rxjs/blob/master/doc/operator-creation.md#publish-your-operator-as-a-separate-library) for now. Core team is discussing about processes of pick / removing core level operator as separate topic.

**Comment by paulpdaniels** [comment]
This should be a trivial implementation of `filter`:

```javascript

const takeWhen = value => source => source.filter(v => v === value);
const skipWhen = value => source => source.filter(v => v !== value);

```

**Comment by machtyn** [comment]
For whatever reason, `filter` isn't working for me the way I want it. But I do agree that what I've described is a `filter` behavior.
