### ISSUE TITLE
Refactor `Operator` classes to be just functions?

### ISSUE THREAD

**Issue by benlesh** [ReactiveX/rxjs#3057]
### Problem

Given that closures do not seem to be as costly in newer versions of V8 (and presumably soon in other engines), it seems like we can do away with so many classes in RxJS. Classes add a lot of generated boilerplate, and according to @jasonaden, they add some problems for tree-shakers because when they're down-leveled to functions in ES5 by typescript, they're wrapped in an immediately executed function, and the tree-shakers can't gaurantee there aren't any side-effects, so they don't shake them away.

### Proposal

move to a higher-order function signature like:

```ts
type OperatorLink = <T, R>(...args: Array[]) => (source: Observable<T>, destination: Subscriber<R>) =>  Subscription;
```

For example, map might be more like:

```ts
const mapOperatorLink = (project: (value: T, index: number) => R) => (source: Observable<T>, destination: Subscriber<R>) => source.subscribe(new MapSubscriber(desination, project));
```

(Above examples assume current architecture with Subscriber)

**Comment by felixfbecker** [comment]
I think this would make rxjs so much easier to contribute to and understand. As a newcomer the operator classes can be really confusing, so it's hard to find examples of how write custom operators. Functions are so easy to understand. This probably also shaves bytes off the bundle size

**Comment by trxcllnt** [comment]
@benlesh I've [proposed this](https://github.com/ReactiveX/rxjs/pull/2135#issuecomment-266331056) before, but how about redefining the `Operator` interface as a [hybrid type](https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Interfaces.md#hybrid-types)? That way we can rewrite the Operator classes internally to just be Operator functions, without breaking backwards compatibility?

**Comment by benlesh** [comment]
Closing this, as it doesn't seem like a big win or particularly important.
