### ISSUE TITLE
Add a note to lettable-operators.md that static methods do not need a lettable variant.

### ISSUE THREAD

**Issue by Dorus** [ReactiveX/rxjs#3059]
A few times already i've had questions on gitter about lettable operators ( https://github.com/ReactiveX/rxjs/blob/master/doc/lettable-operators.md ) and why static operators like `fromEvent` have no lettable variant.

Obvious, (at least to me,) is that lettable operators are made to replace instance methods (that modify `Observable.prototype`) with static methods, so that you can tree shake, remove dead code etc. 
Operators that are already static (all creating operators like `of`, `fromEvent` and the static variant of `combineLatest`) have no need for a lettable variant. Thus upgrading to lettable operators, there is no need to modify code that uses already static operators, or to import them differently.

This note should probably be added to the docs somewhere.

**Comment by OliverJAsh** [comment]
> why static operators like fromEvent have no lettable variant.

AFAICS, they do:

``` ts
import { fromEvent } from 'rxjs/observable/fromEvent';
import { of } from 'rxjs/observable/of';
import { defer } from 'rxjs/observable/defer';
```

Do I misunderstand?

Alternatively, users may continue to import patches, such as

``` ts
import 'rxjs/add/observable/of';
```

Is this correct?

**Comment by OliverJAsh** [comment]
Actually, going by the definition of "lettable operators", these imports are not technically "lettable operators":

``` ts
import { fromEvent } from 'rxjs/observable/fromEvent';
```

> any function that returns a function with the signature: <T, R>(source: Observable<T>) => Observable<R>.

https://github.com/ReactiveX/rxjs/blob/339092628201a1f9a784dcde1905f700dacffe0a/doc/lettable-operators.md#what

**Comment by cartant** [comment]
Closing this. Now that 'lettable' operators are officially called 'pipeable' operators, this is - hopefully - a little less confusing for people.
