### ISSUE TITLE
Add `start` method to Observers

### ISSUE THREAD

**Issue by benlesh** [ReactiveX/rxjs#3061]
The TC39 spec has a `start` method to prevent this scenario from being a problem:

```ts
const subscription = range(0, 10000000).subscribe({
  next(value) { 
    if (value > 3) {
      // try to unsubscribe here, I dare you.
      subscription.unsubscribe();
    }
  }
});
```

The solution was to add an optional `start` method to Observer:

```ts
const subscription = range(0, 10000000).subscribe({
  start(subs) { this.subscription = subs; },
  next(value) { 
    if (value > 3) {
      // this.subscription is literally the same reference you'd get back
      // from the subscribe call itself.
      this.subscription.unsubscribe();
    }
  }
});
```

**Comment by benlesh** [comment]
And no, I won't be adding this to the 3-callbacks version upfront, it's sort of to cover an edge case, not sure it needs to have some ergonomic considerations.

**Comment by felixfbecker** [comment]
Why is the scenario a problem?

**Comment by benlesh** [comment]
@felixfbecker if a consumer wishes to cancel a synchronous firehose, they cannot do so easily with the basic observable impelmentation. They could "Rx" around it:

```ts
const stop = new Subject();
// a hypothetical synchronous firehose of data.
const firehose = range(0, Number.POSITIVE_INFINITY);

firehose.takeUntil(stop);
  .subscribe({
    next(value) {
      doSomeSideEffect(value);
      if (checkSomeExternalState()) stop.next();
      console.log(value);
    }
  });
```

**Comment by benlesh** [comment]
Regardless, I think we're going to move away from the `start` method if we use `abortSignal`:  #3122

**Comment by felixfbecker** [comment]
Ah, got it.

**Comment by martinsik** [comment]
It feel like this could be easily solved by using `publish()`:

```
const source = range(0, 10000000).publish();

const subscription = source.subscribe({
  next(value) { 
    if (value > 3) {
      // try to unsubscribe here, I dare you.
      subscription.unsubscribe();
    }
  }
});

source.connect();
```

**Comment by benlesh** [comment]
@martinsik this is meant to round out the type on its own and it's coming from the standards proposals in flight.

**Comment by benlesh** [comment]
And, of note, I was wrong.. even with abort signal, we'd need start.
