### ISSUE TITLE
Subscription extended method doesn't work in forkJoin

### ISSUE THREAD

**Issue by kokhooi** [ReactiveX/rxjs#3063]
Hi All,
Encountering issue where extended function in Subscription not working when using forkJoin

**RxJS version:**
5.5.2

**Code to reproduce:**
``` Javascript
declare module 'rxjs/Subscription' {
  interface Subscription {
    showLoading: ShowLoadingSignature;
  }
}

export function showLoading(): void {
  var loadingService = _injector.get(LoadingService);
  loadingService.setSubscription(this);
}

export interface ShowLoadingSignature {
  (): void;
}

Subscription.prototype.showLoading = showLoading;

Observable.forkJoin()
.subscribe()
.showLoading() // function not found

this.service()
.subscribe()
.showLoading() // working fine
```
**Expected behavior:**
Extended method should work

**Actual behavior:**
Extended method not found

**Additional information:**
Working fine in 5.4.3

**Comment by kwonoj** [comment]
v5's `subscribe()` returns `Subscription` as interface, it does guarantee returned object satisfies subscription interface, but does not gaurantee returned subscription object is identical over different operator / behaviors. Internally based on operator different type / class of object is being created for subscription, so except interface contract `Subscription` itself, you can't rely on other characteristics of object.
