### ISSUE TITLE
False statement in docs/lettable-operators

### ISSUE THREAD

**Issue by felixfbecker** [ReactiveX/rxjs#3065]
I love lettable operators, but this is a false claim:

> Unused operators that are being imported in apps ***cannot be detected reliably by any sort of build tooling or lint rule***. That means that you might import scan, but stop using it, and it's still being added to your output bundle. With lettable operators, if you're not using it, a lint rule can pick it up for you.

(emphasis mine)

I've been using https://www.npmjs.com/package/rxjs-tslint-rules and it does exactly that - make sure you have the right `add` imports per file or project, prevent you from importing the whole rxjs library and error if you import operators that you don't actually use.

It can also be used to enforce lettable operators by forbidding the add imports completely, so it may be worth a mention.

**Comment by cartant** [comment]
Hey, Felix. I'm the author of `rxjs-tslint-rules` and I would suggest that the statement is not false.

It's qualified; stating that the unused imports cannot be detected *reliably*.

There is a [gotcha](https://github.com/cartant/rxjs-tslint-rules#observablecreate) with `Observable.create` that prevents reliable detection as the return type of `Observable.create` is `any`. I have no issue with the statement made in the documentation.

**Comment by felixfbecker** [comment]
Fair enough.

**Comment by jayphelps** [comment]
@felixfbecker good to go?

**Comment by felixfbecker** [comment]
Yeah
