### ISSUE TITLE
'do' as a lettable operator?

### ISSUE THREAD

**Issue by darkbasic** [ReactiveX/rxjs#3068]
Is it possible to use `do` as a lettable operator? I cannot import it from `rxjs/operators`

**Comment by martinsik** [comment]
It was renamed to `tap`:

- https://github.com/ReactiveX/rxjs/blob/master/src/operators/tap.ts

- https://github.com/ReactiveX/rxjs/blob/master/doc/lettable-operators.md#lettable-operators

**Comment by darkbasic** [comment]
Thanks
