### ISSUE TITLE
‘distinct’ can't work as the description in tutorials 

### ISSUE THREAD

**Issue by liuyunwei** [ReactiveX/rxjs#3069]
the test code in http://reactivex.io/rxjs/manual/tutorial.html#producing-values

```javascript
// typing "hello world"
var input = Rx.Observable.fromEvent(document.querySelector('input'), 'input');
// Only pass unique values through
input.pluck('target', 'value').distinct()
  .subscribe(value => console.log(value)); // "helo wrd"
```
When I type "hello world", it prints "hello world", is there anything wrong?

**RxJS version:**
5.0.3
**Code to reproduce:**
copy the demo codes to make a online demo
http://reactivex.io/rxjs/manual/tutorial.html#producing-values
http://jsbin.com/kiwumisoja/edit?html,js,console,output
**Expected behavior:**
http://reactivex.io/rxjs/manual/tutorial.html#producing-values
print "helo wrd" in console tab
**Actual behavior:**
print "hello world"
**Additional information:**

**Comment by martinsik** [comment]
@liuyunwei I think it works as expected. When you write for example "Hello" then clear the input and start writing the same "Hello" again it'll be ignored as expected. But if you wrote "Hello2" you'll see a new log in the console "Hello2" because you haven't written this term yet.

**Comment by SangKa** [comment]
The operators are fine, but the tutorials would confuse some guy.
The following sample code is better for  illuminate `distinct` or `distinctUntilChanged`:
```
Rx.Observable
  .of('h', 'e', 'l', 'l', 'o', ' ', 'w', 'o', 'r', 'l', 'd')
  .distinct()
  .subscribe(x => console.log(x));  // h, e, l, o,  , w, r, d
```

**Comment by dengwanc** [comment]
as far as i'm concerned, 
1. the doc is totally confuse new one
2. in this case simplely
```
 input.pluck('target', 'value')
  .map(value => distinct(value)) // distinct need implement
  .subscribe(value => console.log(value)); // "helo wrd"
```

RxJS is not doing every thing, focus on the import part __lodash for async__

**Comment by benlesh** [comment]
This is outdated it seems.
