### ISSUE TITLE
Error in Observables

### ISSUE THREAD

**Issue by vmagalhaes** [ReactiveX/rxjs#3070]
Hi

I'm trying to use the rxjs 5.4.3 version instead of the new version, I'm waiting for the new release to go out and run in my SystemJs project.

Meanwhile with the old version 5.4.3 these errors appear for me, there is not much because this happens because I did not update the library, you know how I can solve all this erros? Route errors by observables etc.

![screenshot from 2017-11-14 09-41-07](https://user-images.githubusercontent.com/14242447/32778297-8120de34-c920-11e7-81ba-3525a2b45e25.png)
![screenshot from 2017-11-14 09-41-23](https://user-images.githubusercontent.com/14242447/32778298-81c03100-c920-11e7-8e93-ff4142fb464d.png)
![screenshot from 2017-11-14 09-59-39](https://user-images.githubusercontent.com/14242447/32778830-8d8bb50c-c922-11e7-8ae1-82ee3adb3973.png)

**Comment by benlesh** [comment]
Are you still having this issue with 5.5? Do you have a minimal reproduction?

**Comment by vmagalhaes** [comment]
@benlesh Yes, I'm still waiting for 5.5.3 version with fixes, has a fix in pull request to do a new version

**Comment by benlesh** [comment]
We don't really have enough information to figure out what might be going on here. We'd need (minimal) reproduction code. Closing this one for now.
