### ISSUE TITLE
Feature request: latestMap

### ISSUE THREAD

**Issue by EloB** [ReactiveX/rxjs#3071]
I would love a method to is almost like an `.switchMap()` but the big difference is that it should wait until the latest "project" Observable is completed before it starts the latest "project" Observable.

# Why?
When you are working with an api that isn't cancelable and that specific function can only be executed once and have to wait until the callback is executed before you can executed that function/method again and only the lastest value is important. 

# A use case
When you have a player for instance and want to seek to a current time in playback. Doing multiple seeking at the same time is not desired and in my case also actually crashes the app (smart tv development). To write this code right now is very complicated. We added debounce the seek but this sometimes fails because of slow buffering.

**How our code looks like right now**
```js
currentTimeChanged$
  .debounceTime(1000)
  .switchMap(currentTime => Observable
    .create((observer) => {
      // This api has no cancelation of setCurrentTime and
      // can only be executed while not currently seeking.
      player.setCurrentTime(currentTime, (error) => {
        if (error) return observer.error(error);
        observer.complete();
      });
    })
    // The only solution right now is to do something like this
    // but sometimes crashes probably because legacy browser and unstable native api.
    .retryWhen(error$ => error$.delay(100))
  );
```

**Desired code**
```js
currentTimeChanged$ // A stream that represent a progress bar
  .debounceTime(1000)
  // Should subscribe next latest project when idle.
  // Should not subscribe latest project until previous project is completed.
  .latestMap((currentTime) => { 
    return Observable.create((observer) => {
      // player.setCurrentTime can only be executed while not "running"
      player.setCurrentTime(currentTime, () => observer.complete());
    });
  });
```

**Comment by staltz** [comment]
Have you looked at concatMap and exhaustMap?

**Comment by EloB** [comment]
@staltz yes,
`concatMap` will execute all currentTimeChanged$ in sequence and I'm only interested that the latest value is executed.
`exhaustMap` will execute seek but won't always execute the latest currentTime depending on timing issues.

**Comment by EloB** [comment]
It's like a combination between a `exhaustMap` and a `switchMap` is what I want.

**Comment by kwonoj** [comment]
with let and new pipe-able operator structure introduce in 5.5, we are recommding creating new operator as user-level one (/doc/operator-creation.md@master#publish-your-operator-as-a-separate-library) for now. Core team is discussing about processes of pick / removing core level operator as a separate topic.

**Comment by trxcllnt** [comment]
@EloB from what I can tell, I _think_ this is `auditMap` -- if so, you should be able to achieve something similar via `source.auditTime(1000).exhaustMap((x) => asyncThing(x))`

**Comment by EloB** [comment]
@trxcllnt I like the name `auditMap`. I think your example has some timing issues `source.auditTime(1000).exhaustMap((x) => asyncThing(x))`. If the exhaustMap gets a new emitted value while running asyncThing. Then that value gets lost. It's important that it always runs the last value.

Example: Drag and Drop = DnD
DnD progressbar emits values while dragging -> Seek and wait until finished -> Repeat the process if the DND changed while seek.

**Comment by EloB** [comment]
I'm not sure about the code above that I written but I really would like something that takes care of this in Rxjs core because the teardowns cannot be async...

**Comment by benlesh** [comment]
This is basically audit. Closing this issue as stale. With pipeable operators users can easily create their own if they have a need.
