### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by adc613** [ReactiveX/rxjs#3072]
**RxJS version:**
5.5

**Code to reproduce:**
```
const subject = new Subject<number>();

it('will not receive error', () => {
  const s1 = subject.subscribe(() => {});  // No error handler

  const errorSpy = jasmine.createSpy('subscription error spy')
  const s2 = subject.subscribe(() => {}, errorSpy);
  expect(() => {
    subject.error(1);
  }).toThrow(1);
  expect(errorSpy).toHaveBeenCalled();  // Will fail
});

it('will receive error', () => {
  const s1 = subject.subscribe(() => {}, () => {});  // With error handler

  const errorSpy = jasmine.createSpy('subscription error spy')
  const s2 = subject.subscribe(() => {}, errorSpy);
  expect(() => {
    subject.error(1);
  }).not.toThrow(1);
  expect(errorSpy).toHaveBeenCalled(); // Will pass
});
```

**Expected behavior:**
All subscriptions should receive error events.

**Actual behavior:**
A race condition is created where only the first subscribers receive an error event. Once one subscribe doesn't override the default error handler an error is thrown and code execution is halted. 

**Additional information:**
This is been an issue for us when dealing with XML requests. Some of our code relies on receiving an error event. In our codebase we now have to be very careful and can't rely on publicly exposed observables to receive errors.

**Comment by kwonoj** [comment]
it is known behavior of unhandled subscriber can stop upstream sources, and for those reason we have introduced https://github.com/ReactiveX/rxjs/pull/3062 to follow TC39 proposal - and as it's breaking changes we're targeting next major for this.

**Comment by adc613** [comment]
For anyone else who's had the same issue, we've come up with a temporary fix that works for our use case:

`observable = Observable.fromPromise(observable.toPromise)`

**Comment by jayphelps** [comment]
Consolidating the discussion to #2145 (though there's nothing actionable, its as-designed in v5 and v6 changes it)
