### ISSUE TITLE
Find all tests with `setTimeout` in them and replace them

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#309]
Now that we have the TestScheduler, I'm sick of waiting for the tests with *actual* timing in them. I need to find them and kill them, replacing them with TestScheduler "marble" tests.

**Comment by kwonoj** [comment]
Candidates are (most of) all test cases exist under /spec/**, is that correct?

**Comment by blesh** [comment]
Yes, that's what I'm talking about.

**Comment by blesh** [comment]
I think we've accomplished this for the most part.
