### ISSUE TITLE
Add Documentation - skipLast - Real World Example

### ISSUE THREAD

**Issue by RHGeek** [ReactiveX/rxjs#3094]
Add a real world code example to the documentation to demonstrate how the operator can be used. Provide code that demonstrates what it can do but also a real world example of when you would use it.

**Comment by david-driscoll** [comment]
@RHGeek Is there a specific reasoning you're spamming the repository with 3 issues per operator about documentaiton?

**Comment by RHGeek** [comment]
@david-driscoll it is a part of the docs initiative to add these for missing operators https://github.com/ReactiveX/rxjs-docs/issues/4

**Comment by david-driscoll** [comment]
Should that not go on the rxjs-docs repo?

**Comment by RHGeek** [comment]
The discussion / decision was to add them over here. There are some previously made, these were the last that were needed. Looping in @ladyleet for explanation.

**Comment by ladyleet** [comment]
@rhgeek no, we made a decision to add all issues to the rxjs docs repo and it was already done - check the issues on the docs repo! Thx for your effort though. Ashwin did this awhile ago.

**Comment by RHGeek** [comment]
@ladyleet oh no. that was my misunderstanding. when i created the first 3 and linked them, we said everything looked good and then i created the first batch. I was finishing them up. my apologies and mess up. I'll clean this mess up then.

**Comment by ladyleet** [comment]
@rhgeek no worries! It was awhile ago so someone proceeded on the issue so they could get going with the docs.

**Comment by rgbkrk** [comment]
On a positive note, this made me realize that there was an rxjs-docs effort with a bunch of various folks since I only follow `ReactiveX/rxjs` sparingly.

**Comment by ladyleet** [comment]
Hahaa love it! :)

**Comment by martinsik** [comment]
@rgbkrk I didn't know about it either until I read your comment :(.

**Comment by RHGeek** [comment]
well, at least there is some positive to my goofing then @rgbkrk and @martinsik. Glad to raise awareness ;-)

**Comment by ladyleet** [comment]
Happy about it too! We def welcome more contributors to the docs!
