### ISSUE TITLE
RxJS vNext instead of v 3?

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#31]
According to @mattpodwysocki, he needs to introduce breaking changes to RxJS 2 to fix some bugs (this is my primitive understanding). Breaking changes, according to NPM's semver guidelines, mean a major revision.

Thoughts? Concerns?

**Comment by BerkeleyTrue** [comment]
Would that mean this version would eventually come out as v4.0.0?

**Comment by blesh** [comment]
Heh well, yes... unless @mattpodwysocki introduces a newer version. :p 

This repository is for a total rewrite of RxJS. The intention is to have as much backwards compatibility as possible, though.

**Comment by BerkeleyTrue** [comment]
So, just refer to this version as RxNext instead of RxJS 3.0? Yeah I can dig it.

**Comment by blesh** [comment]
This is done.
