### ISSUE TITLE
Add Documentation - Observable.timestamp - Description

### ISSUE THREAD

**Issue by RHGeek** [ReactiveX/rxjs#3108]
Add description to the docs for operator. Include description of what the operator does, how it works, as well as any values it returns and fully defining parameters including name, type, attribute and description.

**Comment by david-driscoll** [comment]
@RHGeek Is there a specific reasoning you're spamming the repository with 3 issues per operator about documentation?

**Comment by RHGeek** [comment]
@david-driscoll it is a part of the docs initiative to add these for missing operators ReactiveX/rxjs-docs#4
