### ISSUE TITLE
Empty d.ts files (throw.d.ts, if.d.ts, toPromise.d.ts)

### ISSUE THREAD

**Issue by denisnikolayev** [ReactiveX/rxjs#3121]
Hi.
There are few empty d.ts files in rxjs npm package:

"node_modules\rxjs\add\operator\toPromise.d.ts"
"node_modules\rxjs\add\observable\if.d.ts"
"node_modules\rxjs\add\observable\throw.d.ts"
because of this and couple of bugs in typescript/awesome-typescript-loader. We have very big performance issue in building our project.

**Comment by kwonoj** [comment]
https://github.com/ReactiveX/rxjs/blob/master/src/add/operator/toPromise.ts

it is literally empty and left for backward compatibility in v5, probably will go away in v6 but not in v5. Empty `d.ts` is not good, but still valid - how does it affect / causes issues?

**Comment by denisnikolayev** [comment]
@kwonoj https://github.com/s-panferov/awesome-typescript-loader/issues/517 
I already opened issue for author of awesome-typescript-loader

**Comment by denisnikolayev** [comment]
Author of awesome-typescript-loader fixed the issue on his side.
