### ISSUE TITLE
Type is not inferred correctly using filter operator

### ISSUE THREAD

**Issue by rafaelss95** [ReactiveX/rxjs#3125]
**RxJS version:**
5.5.2

**Code to reproduce:**
Consider this piece of code:

```
constructor(private router: Router) { }

ngOnInit() {
  this.router.events.pipe(
    filter(e => e instanceof NavigationEnd)
  ).subscribe(
    // e is inferred as RouterEvent | RouteConfigLoadStart | RouteConfigLoadEnd | ChildActivationStart | ChildActivationEnd | ActivationStart | ActivationEnd
    e => console.log(e)
  );
```

**Expected behavior:**
I'd expect `e` to be inferred as `NavigationEnd`.

**Actual behavior:**
I'm using Angular 5 and in code above, I'm using `filter` operator to "_listen_" only events referent to `NavigationEnd`, however the type isn't being inferred correctly. Instead of getting `e` as `NavigationEnd`, I'm getting `e` as `RouterEvent | RouteConfigLoadStart | RouteConfigLoadEnd | ChildActivationStart | ChildActivationEnd | ActivationStart | ActivationEnd`.

**Additional information:**
[DEMO](https://stackblitz.com/edit/angular-gitter-pjkkjx)

**Comment by cartant** [comment]
The problem is that the function you are passing to `filter` is not a type guard, so [the overload signature that accepts a type guard](https://github.com/ReactiveX/rxjs/blob/5.5.2/src/operators/filter.ts#L8-L9) is not matched and no narrowing is performed. You need to indicate to TypeScript that the function is a type guard:

```ts
filter((e: Event): e is NavigationEnd => e instanceof NavigationEnd)
```

**Comment by rafaelss95** [comment]
Thanks for your comment, but it doesn't work for me.

`filter((e: Event): e is NavigationEnd => e instanceof NavigationEnd)` doesn't compile:

> Type 'RouterEvent' is not assignable to type 'Event'.

So, I removed the `(e: Event)` part:

`filter((e): e is NavigationEnd => e instanceof NavigationEnd)`

... and it doesn't change nothing at all.

Btw, the solutions I came up are:

1 - Cast it:

```
this.router.events.pipe(
    filter<NavigationEnd>(e => e instanceof NavigationEnd)
  ).subscribe(
    // e is inferred as NaviagtionEnd
    e => console.log(e)
  );
```

2 - Crazy option -> Don't use `filter`:
```
this.router.events.subscribe(
  e => {
    if (e instanceof NavigationEnd) {
      // e is inferred as NavigationEnd
      console.log(e);
    }
  }
);


```

**Comment by cartant** [comment]
I briefly looked at the Angular docs and those that I saw suggested the `events` observable in the `Router` emitted `Event` instances. If that's wrong or out-of-date, just use what the appropriate type:

```ts
filter((e: RouterEvent): e is NavigationEnd => e instanceof NavigationEnd)
```

The key point is that this is not an RxJS issue; it's a TypeScript issue. The function has to be explicitly made a type guard, it won't be inferred as one just because it happens to return the result of an `instanceof` expression.

**Comment by rafaelss95** [comment]
Strange. How is it a typescript issue if I can get the correct type with the following code?

```
this.router.events.subscribe(
  e => {
    if (e instanceof NavigationEnd) {
      // e is inferred as NavigationEnd
      console.log(e);
    }
  }
);
```

**Comment by ptitjes** [comment]
@rafaelss95 To complete @cartant's answer, you can read more in TypeScript's documentation about the so-called [Type Guards](http://www.typescriptlang.org/docs/handbook/advanced-types.html#type-guards-and-differentiating-types). Note the use of the special return type for the function passed to `filter`: `aParam is AType`, that is the key that helps TypeScript's type inference!

**Comment by cartant** [comment]
Because this:

```ts
if (e instanceof NavigationEnd) {
```

is a [type guard](https://basarat.gitbooks.io/typescript/docs/types/typeGuard.html), but this:

```ts
e => e instanceof NavigationEnd
```

is not a user-defined type guard. However, this:

```ts
(e: RouterEvent): e is NavigationEnd => e instanceof NavigationEnd
```

is a user-defined type guard.

**Comment by rafaelss95** [comment]
Ok, I got it. Now the question is: does it works as intended or its a bug?

**Comment by ptitjes** [comment]
I think rxjs can't do more than what TypeScript is capable. So you can consider that it is as intended. :)

**Comment by rafaelss95** [comment]
I just enabled `--strict` on `tsconfig.json` and the proposed solution doesn't work.

```
this.router.events.pipe(
  // doesn't compile ... e is not assignable...
  filter((e: RouterEvent): e is NavigationEnd => e instanceof NavigationEnd)
).subscribe(
   // ... 
);
```

**Workaround**:

```
this.router.events.pipe(
  filter(e => e instanceof NavigationEnd),
  map(event => event as NavigationEnd)
).subscribe(
   // ... 
);
```

**Comment by sandangel** [comment]
not work for me too.

![dec-03-2017 20-10-18](https://user-images.githubusercontent.com/22189661/33524765-1041ab26-d866-11e7-91e7-bc2b02fdb398.gif)

**Comment by benschulz** [comment]
This is not a rxjs issue. Related upstream issues are Microsoft/TypeScript#5101 and Microsoft/TypeScript#10734.

**Comment by kwonoj** [comment]
I'm going to close issue as it's sufficiently explained for reason, and it's upstream issue that we can't make action at this moment until we get compiler support.

**Comment by Hotell** [comment]
any idea how to hotfix this for `ofType` lettable operator ? -> https://github.com/redux-observable/redux-observable/issues/382

cc @cartant
