### ISSUE TITLE
Error does not go to the second subscriber's error handler if the first subscriber does not have an error handler

### ISSUE THREAD

**Issue by Gebov** [ReactiveX/rxjs#3128]
**RxJS version:**
5.5.2

**Code to reproduce:**
https://plnkr.co/edit/nwLQGmm4DtyOczbKPxfd?p=preview

**Expected behavior:**
Expecting that the second subscriber's error handler will get called, even if the first one is not there.
**Actual behavior:**
The second subsriber's error handler does not get called.

**Additional information:**

**Comment by jayphelps** [comment]
Hey @Gebov, actually not a bug in v5 but v6 will change this behavior at the expense of unhandled errors not being rethrown. The topic is pretty confusing 😞  See #2145 and for v6 #3062
