### ISSUE TITLE
skipWhile is not a function

### ISSUE THREAD

**Issue by sharpmachine** [ReactiveX/rxjs#3130]
I upgraded from 5.4.3 to 5.5.2 and now I get an error:

```
Uncaught (in promise): TypeError: this.subjectInfo$.skipWhile is not a function`.
```
I downgraded back to 5.4.3 and error goes away.

**RxJS version:**
5.5.2

**Code to reproduce:**
```
this.lastFormInstanceId$.skipWhile(formInstanceId => (formInstanceId == null)).first().subscribe(formInstanceId => {
    this._router.navigate([formUid + '/' + formInstanceId], { relativeTo: this._route });
});
```
**Expected behavior:**
To be able to use `skipWhile` without getting an error.

**Actual behavior:**
`Uncaught (in promise): TypeError: this.subjectInfo$.skipWhile is not a function`

**Comment by martinsik** [comment]
https://github.com/ReactiveX/rxjs/blob/master/doc/lettable-operators.md

**Comment by sharpmachine** [comment]
Are you saying I need to do this:
```
import { skipWhile } from 'rxjs/operators';
```

**Comment by benlesh** [comment]
It's hard to say what's going on here without seeing the whole application, but at first glance it looks like you've forgotten to `import 'rxjs/add/operator/skipWhile'`. However it's the RxJS team's recommendation to use Pipeable operators:

```ts
import { skipWhile } from 'rxjs/operators';

source$.pipe(skipWhile(x => x > 10)).subscribe(fn);
```
