### ISSUE TITLE
No exports for operator and add

### ISSUE THREAD

**Issue by jfpicard1** [ReactiveX/rxjs#3137]
**RxJS version: 5.5.2**

**Code to reproduce:**
Try to import catch from the add/operator  or throw from the add/observable

**Expected behavior:**
It should be imported in the TypeScript style like map or Observable:

import { catch'} from 'rxjs/add/operator/catch';
import { throw'} from 'rxjs/add/observable/throw';

**Actual behavior:**
We must use the old style import like this

import 'rxjs/add/operator/catch';
import 'rxjs/add/observable/throw';

**Additional information:**
If there is a reason why we import all in operators with the construct:
import { } from from 'rxjs/operators'
and we cannot do the same with all the operator in 'rxjs/add', I would like to know why.

**Comment by Hongbo-Miao** [comment]
You can import by

```
// JavaScript ES7 Function Bind Syntax
import {Observable} from "rxjs/Observable";
import "rxjs/add/observable/interval";
import {take} from "rxjs/operator/take";
import {map} from "rxjs/operator/map";
import {bufferCount} from "rxjs/operator/bufferCount"

Observable
  .interval(200)
  ::take(9)
  ::map(x => x + "!!!")
  ::bufferCount(2)
  .subscribe(::console.log);
```

Source: https://gist.github.com/MichalZalecki/d78c52ec55d7ec7b53f7

**Comment by jfpicard1** [comment]
I already know that. But for operator, there is an operator.ts that export all the operator present in rxjs/operators but there is no files named operator.ts that exports all from rxjs/add/operator so that we can do the same import as map like this:

import { catch'} from import 'rxjs/add/operator';

like 

import { map } from 'rxjs/operators';

**Comment by benlesh** [comment]
`rxjs/add/*` modules are not designed to export anything, they're designed to patch the prototype to have those methods.
