### ISSUE TITLE
toArray() duplicates items for each subscription

### ISSUE THREAD

**Issue by kane77** [ReactiveX/rxjs#3141]
**RxJS version:**
5.5.2

**Code to reproduce:**
```javascript
const count = Rx.Observable.interval(1000).take(10)
const countArray = count.toArray()
countArray.subscribe(i => console.log(i))
countArray.subscribe(i => console.log(i))
```
**Expected behavior:**
In both cases an array with 0 to 9 is returned:
```
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
```
**Actual behavior:**
The values returned are duplicated for each subscription:
```
[0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9]
[0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9]
```
**Additional information:**
This is a regression from 5.4.3, where the values are as expected

**Comment by benlesh** [comment]
@kwonoj I believe your PR the other day fixed this.
