### ISSUE TITLE
Where can I read on the performance of the Subject object?

### ISSUE THREAD

**Issue by splincode** [ReactiveX/rxjs#3143]
Are there any tips on the use of RxJS? If I use many subscribers, will it affect performance? Is there any checklist?

**Comment by kwonoj** [comment]
There is no specific checklist for performance. Since most of Rx operator is based on plain functions and by default Subject / Observable iterates over subscribers without specific scheduling, you may need to manage subscriptions and can run profiler to see how does it performs.
