### ISSUE TITLE
types inferring problem with scan operator

### ISSUE THREAD

**Issue by ghetolay** [ReactiveX/rxjs#3150]
I'm having a problem when using `scan` with 2 different type for item and accumulator/seed on ts 2.5+ (didn't try older versions).
You can see it here : https://stackblitz.com/edit/ts-fn-overload-bug?file=test.ts

```ts
of('0').pipe(
  scan((acc, str) => acc + parseInt(str), 0)
);
```
gives the following error : 
> Argument of type 'UnaryFunction<Observable<number>, Observable<any>>' is not assignable to parameter of type 'UnaryFunction<Observable<string>, Observable<any>>'.
  Types of parameters 'source' and 'source' are incompatible.
    Type 'Observable<string>' is not assignable to type 'Observable<number>'.
      Type 'string' is not assignable to type 'number'.

Even if scan has a signature matching that use case (the last one) : 
```ts
function scan<T>(accumulator: (acc: T, value: T, index: number) => T, seed?: T): MonoTypeOperatorFunction<T>;
function scan<T>(accumulator: (acc: T[], value: T, index: number) => T[], seed?: T[]): OperatorFunction<T, T[]>;
function scan<T, R>(accumulator: (acc: R, value: T, index: number) => R, seed?: R): OperatorFunction<T, R>;
```

As it's shown on the stackblitz, order seems to matter so it's most likely a ts bug.
But looking closely on those types, @NaridaL pointed out that the last signature should be enough to cover all cases. Indeed `R` can totally be inferred with the same type as `T` or `T[]`.

So the question is : is there any reason for having those *subtype* signatures ? especially since now it seems to create a bug ?

P.S: Couldn't find a corresponding ts issue but didn't do much digging
P.S2: I think the same applies for `reduce`.

**Comment by cartant** [comment]
Probably related to #2897. See discussion therein.

**Comment by ghetolay** [comment]
Oh sorry, I missed that. 

But now there is a game changer as it's causing errors. I'll dig into typescripts issues see if I can find something.

**Comment by ghetolay** [comment]
I thought the problem was because I update my ts but it's not, it's because I refactored my code to use pipe. 
I can go as low as 2.0 with that code and I got the error while the *non-pipeable* version, with `this` on the signature, works fine.

I found this new issue https://github.com/Microsoft/TypeScript/issues/20305 but I'm not sure it's exactly the same problem.

**Comment by benlesh** [comment]
This has been addressed to the best of our ability in RxJS 7.
