### ISSUE TITLE
Observable constructor doesn't require any parameter

### ISSUE THREAD

**Issue by martinsik** [ReactiveX/rxjs#3153]
**RxJS version:** 5.5.3

**Code to reproduce:**

```
import { Observable } from 'rxjs/Observable';

const o = new Observable();
// const o = Observable.create();

o.subscribe();
```

**Expected behavior:**

Throw compilation error or run fine and do nothing.

**Actual behavior:**

Compiles fine but throws error when run.

**Additional information:**

I've seen this question on StackOverflow at least three times where people misunderstood the difference between Subject and Observable classes. They created an instance of Observable and then didn't know what to do next.

What's confusing is that you can create an Observable with just `new Observable()` (or `Observable.create()`) because the `subscribe` callback is optional but when they try to subscribe it throws an error:

```
/Users/.../node_modules/rxjs/Observable.js:165
                throw sink.syncErrorValue;
                ^

TypeError: Cannot read property 'subscribe' of undefined
    at Observable._subscribe (/Users/.../node_modules/rxjs/Observable.js:231:27)
    at Observable._trySubscribe (/Users/.../node_modules/rxjs/Observable.js:172:25)
    at Observable.subscribe (/Users/.../node_modules/rxjs/Observable.js:160:65)
    at Object.<anonymous> (/Users/.../general/subscribe_01.js:6:3)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
```
The error is thrown because [this line by default](https://github.com/ReactiveX/rxjs/blob/master/src/Observable.ts#L202) checks if `this.source` exists:
```
sink.add(this.source ? this._subscribe(sink) : this._trySubscribe(sink));
```
but then it tries [to use `this.source` anyway](https://github.com/ReactiveX/rxjs/blob/master/src/Observable.ts#L254):
```
return this.source.subscribe(subscriber);
```

So maybe the constructor should require either the `subscribe` callback or a `source` to be always set. For example like this:

```
constructor(subscribeOrSource: (this: Observable<T>, subscriber: Subscriber<T>) => TeardownLogic | Observable<any>) {
```

**Comment by kwonoj** [comment]
If I recall correctly, this was due to signature incompatibility with Subejct as same as signature of static `create` (which accepts general `Function` only, cannot have strong types). May need to revisit if that's still cases, but since Subject doesn't require param on construct not sure unless we bend over some types.

**Comment by kwonoj** [comment]
I still have to check once again and see if that's true though.

**Comment by martinsik** [comment]
So at the end this might be related to this: #2004

**Comment by martinsik** [comment]
I checked it again today with `rxjs@6.3.3` and it doesn't throw any error and does nothing in both cases which is I think fine so I'm going to close this.

https://stackblitz.com/edit/rxjs-7diu1c?file=index.ts
