### ISSUE TITLE
rxjs 5.5.0 no pipe documentation

### ISSUE THREAD

**Issue by TrentonAdams** [ReactiveX/rxjs#3156]
**RxJS version:** 5.5.0

**Code to reproduce:** n/a

**Expected behavior:** documentation should be updated for current version.

**Actual behavior:** The documentation is not up to date, and there is no mention of pipe, and the need to pass map, filter, tap, etc, as arguments to pipe, rather than as functions on the observable.

**Additional information:**

For example, the following typescript code does not work.

```
const source$ = range(0, 10);

source$.map(x => x + 1)
  .subscribe(x => console.log(x));
```
The following code does work...
```
const source$ = range(0, 10);

source$.pipe(map(x => x + 1))
  .subscribe(x => console.log(x));
```

It's my understanding that with earlier versions of rxjs, you could call map() on the observable, but now it must be passed through pipe().  The current documentation on the site shows that Observable has a "map" method, but you get an error if you try and use it that says "TypeError: source$.map is not a function".

http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html

**Comment by kwonoj** [comment]
> It's my understanding that with earlier versions of rxjs, you could call map() on the observable, but now it must be passed through pipe().

It is absolutely not and previous chainable method still works. Please check how you did import observables and operators with your build configuration.

**Comment by kwonoj** [comment]
For docs we have https://github.com/ReactiveX/rxjs/blob/master/doc/lettable-operators.md but reactivex.io site is bit outdated, you can check prgress for new docs at https://github.com/ReactiveX/rxjs-docs.
