### ISSUE TITLE
Mapped subjects have a "next" method.

### ISSUE THREAD

**Issue by ohjames** [ReactiveX/rxjs#3162]
**RxJS version:** 5.5.2

**Code to reproduce:**

```
const o =  (new rx.Subject()).map(v => v * 2)
o.subscribe(console.log)
o.next(2)
```

**Expected behavior:**
I should get an exception: `TypeError: o.next is not a function`

Calling `.next` should return an Observable (at least according to the typescript definitions), and Observable should not have a `next` operator.

**Actual behavior:**
`.next(2)` targets the subject and 4 is mapped to the console.

**Additional information:**
If this really is allowed (but it seems like a source of confusion) then the typescript definitions need to be updated to allow it also.

**Comment by benlesh** [comment]
This was by design (for better or worse).  TypeScript can't support it because TypeScript doesn't support higher-kinded types. You can always cast.

**Comment by ohjames** [comment]
Thanks for the info, I doubt I will use it as it will probably just confuse whoever adopts the code but it's good to know.
