### ISSUE TITLE
[Docs] - Lines of code overflowing in tutorial page

### ISSUE THREAD

**Issue by paulotokimatu** [ReactiveX/rxjs#3163]
In smaller screens one line of code can go through its element.

**Link:**
http://reactivex.io/rxjs/manual/tutorial.html

**Expected behavior:**
Code stays in <code> element

**Actual behavior:**
![screenshot-2017-12-5 tutorial](https://user-images.githubusercontent.com/12735004/33615463-64240278-d9c1-11e7-894d-b50dafd44359.png)

**Additional information:**

To fix it, just add `overflow: auto` in https://github.com/ReactiveX/rxjs/blob/master/doc/styles/main.css#L232

Tested in the latest versions of Mozilla Firefox and Google Chrome.

**Comment by dengwanc** [comment]
you should just send a PR

**Comment by JWO719** [comment]
This is just a problem for the old docs and can therefore be closed.
Feel free to reopen it, if I get something wrong
