### ISSUE TITLE
TypeScript errors not reported in tests

### ISSUE THREAD

**Issue by cartant** [ReactiveX/rxjs#3166]
TypeScript errors are not being reported by the tests, so all of the tests within the `type()` tests are ineffectual.

**RxJS version:** current master

**Code to reproduce:**

Adding an incorrectly typed constant to `debounce-spec.ts`, say, like this:

```ts
import { expect } from 'chai';
import * as Rx from '../../src/Rx';
import marbleTestingSignature = require('../helpers/marble-testing'); // tslint:disable-line:no-require-imports

const n: number = "1"; // Obviously an error
```

should effect a TypeScript error, but it does not.

**Expected behavior:**

An error should be reported and the tests should fail.

**Actual behavior:**

No error is reported

**Additional information:** -

**Comment by kwonoj** [comment]
I accidently close issue, it's https://github.com/ReactiveX/rxjs/issues/3020. basically we don't run compiler to specs yet.

**Comment by cartant** [comment]
I see. No worries.

**Comment by cartant** [comment]
Closing in favour of #3411.
