### ISSUE TITLE
Is it necessary to kill cold stream?

### ISSUE THREAD

**Issue by sergamers** [ReactiveX/rxjs#3175]
1. **If subscribe isn't exist, the stream does not work?**
2. **Is it necessary to kill subscribe in cold stream?** For example: operator  .take(1) or .first() or common .unsubscribe, so other. **or may is it necessary to kill himself stream?** .complete()
Or does not it  affect performance in the future?
A simple example:
Create 100 cold stream

```ts
function test() {
let obs = Rx.Observable
            .create(observer => observer.next(Date.now()))

obs.subscribe(v => console.log("1st subscriber: " + v));
obs.subscribe(v => console.log("2nd subscriber: " + v));
}
for(var i = 0; i < 100; i++){
  test()
}
```

**Comment by benlesh** [comment]
If you create an Observable that you never call `observer.complete()` inside, like you did above, it will never stop until you unsubscribe.

These sorts of questions are best asked on stackoverflow.
