### ISSUE TITLE
The Single operator returns undefined when no values match predicate

### ISSUE THREAD

**Issue by acutmore** [ReactiveX/rxjs#3182]
**RxJS version:**
5.x (all versions and in current master)

**Code to reproduce:**

```js
Rx.Observable.of(1).single(v => v === 2).subscribe(
  v => console.log('next', v),
  e => console.log('error', e),
  () => console.log('complete')
);
```

**Expected behavior:**
Logs an error.

**Actual behavior:**
Logs ('next' 'undefined) ('complete')

**Additional information:**

This behavior matches the rxjs5 spec:

https://github.com/ReactiveX/rxjs/blob/efcd922384116b2a45e7d7859e09cf6da34d7371/spec/operators/single-spec.ts#L143-L154

But does not match the jsdoc description or the behaviour in rxjs 4.

https://github.com/ReactiveX/rxjs/blob/efcd922384116b2a45e7d7859e09cf6da34d7371/src/operators/single.ts#L11-L18

This was an unexpected change while in process of updating an RxJs4 code base to RxJs5.

**Comment by kwonoj** [comment]
v5 is major semver upgrade with breaking changes, does not gaurantee 100% compatible to v4. Though this specific change is not listed, https://github.com/ReactiveX/rxjs/blob/master/MIGRATION.md covers major breaking changes between v4 to v5.

**Comment by acutmore** [comment]
@kwonoj the jsdoc in this repo does not match the behaviour. It describes the behaviour that v4 had.

I will open a PR just on train at the moment.

**Comment by kwonoj** [comment]
I'll dbl check behavior, thanks.
