### ISSUE TITLE
shareReplay is not listed in the docs

### ISSUE THREAD

**Issue by IgorMinar** [ReactiveX/rxjs#3184]
**RxJS version:**
5.5.4

**Code to reproduce:**
http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#instance-method-share

**Expected behavior:**
`shareReplay` should be listed right under `share`

**Actual behavior:**
docs missing

**Comment by benlesh** [comment]
cc @ladyleet

**Comment by ladyleet** [comment]
thx @IgorMinar for pointing this out!

**Comment by Airblader** [comment]
So this issue should be closed since @ladyleet opened one over at rxjs-docs, right?

**Comment by JWO719** [comment]
So shareReplay is now listed in the new docs, but the documentation is really poor and should be improved with an example and a description what this operator is actually doing

**Comment by cartant** [comment]
Closing this as it's now listed.
