### ISSUE TITLE
Provide error as alias for _throw

### ISSUE THREAD

**Issue by felixfbecker** [ReactiveX/rxjs#3188]
With lettable operators I like to not use `Observable.throw()` and other static methods, because I want to avoid using `/add` monkeypatch imports. Instead I like to import the Observable factories directly. Like we have an alias `tap` for `do`, `finalize` for `finally`, we should have an alias `error` for `_throw` so we don't have to use underscore-prefixed functions.

**Comment by LayZeeDK** [comment]
Until then, we can bake it to our own liking:

```
import { _throw as error } from 'rxjs/observable/throw'
```

Delicious!

**Comment by benlesh** [comment]
In RxJS 6 this is called `throwError`. But `error` isn't bad. Perhaps open a different issue for renaming `throwError` in the v6 alpha?

I don't think we're going to do this in 5.x, because as a new feature, it would mean releasing a 5.6, and I'm trying to focus our limited resources/time on v6.

**Comment by felixfbecker** [comment]
I think `throwError` is good because it is symmetric to `catchError` (`catch` => `catchError`, `throw` => `throwError`)
