### ISSUE TITLE
combineLatest doesn't complete with an empty collection

### ISSUE THREAD

**Issue by RafaelSalguero** [ReactiveX/rxjs#3189]
**RxJS version:** 5.5.5

**Code to reproduce:**
```
const rx = require("rxjs");
const obs = rx.Observable.combineLatest([]);
obs.subscribe( () => console.log("hello"));
```

**Expected behavior:**
`hello` should be printed, since the resulting observable should complete immediately with an empty array

**Actual behavior:**
Observable never completes

**Additional information:**
This issue has been fixed for RxSwift https://github.com/ReactiveX/RxSwift/issues/1205

**Comment by kwonoj** [comment]
`combineLatest` requires all observable emits to call `next`. Is this question about completing like

```
obs.subscribe( { complete: () => console.log("hello")});
```
?

**Comment by mperezguendulain** [comment]
Yes, I have the same problem, I use the version 5.5.2 of RxJS

**Comment by kwonoj** [comment]
I'm closing this issue as lacks of details. As opposed to issue linked in RxSwift, RxJS currently _does complete_ correctly with empty sequences:

![image](https://user-images.githubusercontent.com/1210596/36493365-48376400-16e4-11e8-9928-3fed310a145a.png)

it's just not emitting any `next` value and it is designed behavior of operator. If you are experiencing it isn't actually completes, it'd be appreciate to let us have reproducible examples to investigate.
