### ISSUE TITLE
Class constructor BehaviorSubject cannot be invoked without 'new' in angular app with es6 target

### ISSUE THREAD

**Issue by IlyaSurmay** [ReactiveX/rxjs#3191]
**RxJS version:**
5.5.4

**Code to reproduce:**
1) Clone this repo: https://github.com/ShinDarth/angular-test-app
2) `npm install`
3)  `ng serve --aot` or `ng serve --prod`
then you can install rxjs 5.4.3 and app will work fine.

**Expected behavior:**
App works as expected

**Actual behavior:**
App throws `Class constructor BehaviorSubject cannot be invoked without 'new'` at start

**Additional information:**
Everything works fine if I downgrade rxjs to 5.4.3. Looks like regression or a breaking change
https://github.com/angular/angular-cli/issues/8910
https://github.com/valor-software/ngx-bootstrap/issues/3252

**Comment by ShinDarth** [comment]
Are there any news about this issue? It looks quite serious...

**Comment by ShinDarth** [comment]
I tried using version `5.5.6` and I get:

`ERROR Error: Uncaught (in promise): ReferenceError: a296996 is not defined`

this happens only when the compile target is `es6`.  The bug does not affect `es5`.

**Comment by valorkin** [comment]
@benlesh hey, is this issue fixed?
Thanks in advance :)

**Comment by ShinDarth** [comment]
Bug still present in:

```
Angular CLI: 1.6.4
Node: 8.9.1
OS: linux x64
Angular: 5.2.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.4
@angular-devkit/build-optimizer: 0.0.37
@angular-devkit/core: 0.0.24
@angular-devkit/schematics: 0.0.45
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.4
@schematics/angular: 0.1.12
typescript: 2.6.2
webpack: 3.10.0
```

**Comment by benlesh** [comment]
I'm looking into it... but honestly a _minimum_ reproduction is what we want.

**Comment by benlesh** [comment]
Seems like it's been fixed downstream. I have no reproduction now. 

I'm not entirely sure what the code was that you thought should work, so I'm not sure what to test.

**Comment by ShinDarth** [comment]
@benlesh please reopen this because I've just tried using version `5.5.7` and the issue is still the same.

Also, as mentioned in the original issue report, there is a repository which reproduce the issue:

```
- Clone this repo: https://github.com/ShinDarth/angular-test-app
- npm install
- ng serve --aot or ng serve --prod

then you can install rxjs 5.4.3 and app will work fine.```

**Comment by ShinDarth** [comment]
![image](https://user-images.githubusercontent.com/75517/37522867-94e7f456-2925-11e8-92ed-cda34e01da7a.png)

![image](https://user-images.githubusercontent.com/75517/37522961-c897a116-2925-11e8-81a4-0aaeff112bb7.png)

**Comment by ShinDarth** [comment]
@benlesh please can you check this?
