### ISSUE TITLE
Transducer Support

### ISSUE THREAD

**Issue by c0nscience** [ReactiveX/rxjs#3193]
The version 4.x of rxjs (Reactive-Extensions/RxJS) provided support to use transducers to transform a stream. The [migration guide](https://github.com/ReactiveX/rxjs/blob/master/MIGRATION.md) says it is 'No longer implemented'.
Are there already plans or discussions around bringing transducer support back to rxjs 5?

**Comment by kwonoj** [comment]
No at this point. As guide says, it was not added as breaking changes between two versions. I remember there were few discussions around but we don't have any specific plans for it.
