### ISSUE TITLE
Unable to receive all data when merge two observables.

### ISSUE THREAD

**Issue by slim-hmidi** [ReactiveX/rxjs#3194]
I created two observables from a database: 
```
const roomData$ = estab
      .query()
      .where('estab.type', 'like', 'rooms')
      .then((rooms) => {
        rooms.forEach((room) => {
          observer.next(room.data);
        });
      });
  }).map(data => ({
    roomsData: [
      ...data.rooms,
    ],
  }));
const hotelData$ = Observable.create((observer) => {
        estab
          .query()
          .where('estab.type', 'like', 'hotels')
          .then((hotels) => {
            hotels.forEach((hotel) => {
              observer.next(hotel.data);
            });
          });
      }).map(data => ({
        hotelsData: [
          ...data.hotels,
        ],
      }));  
const hotelContentData$ = Observable.merge(roomData$, hotelData$);
hotelContentData$.subscribe((data) =>  {
    fs.appendFile('data.json', (err) => { 
         if (err) throw err;
         console.log('file has been appended!);
   }      
})
```
In the `data.json` file I found only the data received from the `roomData$` observable. I change the order in `Observable.merget(hotelData$, roomData$)` and now I get the data of hotel observable. Why only one Observable is executed? How can I execute both of them and get data from `hotelData$` and `roomData$`?

**Comment by kwonoj** [comment]
merge supposed to work regardless of order. is there any reproducible code? without it, hard to say what causes this.

**Comment by slim-hmidi** [comment]
@kwonoj based to the documentation it merge the data from the different observables.But in my case it take only the the data of the first one.

**Comment by cartant** [comment]
It's unlikely that `merge` is the problem. It's more likely that your database does not support concurrent queries. I'd suggest replacing `merge` with `concat`, but that won't work as your observables don't complete.

**Comment by slim-hmidi** [comment]
@cartant I think that the problem is due to the database.

**Comment by slim-hmidi** [comment]
I solved it with `combineLatest()` in place of  `merge`
