### ISSUE TITLE
Documentation outdated?

### ISSUE THREAD

**Issue by NicBright** [ReactiveX/rxjs#3196]
Hi there,

here it says the following (see yellow highlight):

![image](https://user-images.githubusercontent.com/1225659/34307687-aa7730d4-e749-11e7-8d36-f9bb3e2e2b3c.png)

But I can't find any documentation regarding the new lettable operators on http://reactivex.io/rxjs
I had to read the file on github (which was recommended not to do by the yellow highlight!) to learn about it.

From here I would have guessed that there should be an "overview.md" somewhere, linking to the sub-documentatoin md files. I couldn't find one:

![image](https://user-images.githubusercontent.com/1225659/34307953-09741006-e74b-11e7-8880-a7b4fcf81ebc.png)

![image](https://user-images.githubusercontent.com/1225659/34307956-0e19edd8-e74b-11e7-8f9f-f27cd57ae937.png)

This raises the question to me, how the current documentation (http://reactivex.io/rxjs) is generated in the first place?

If you need help regarding documentation, I'd be happy to contribute!

Regards,
Nicolas

**Comment by kwonoj** [comment]
please checkout current progress at https://github.com/ReactiveX/rxjs-docs for new documentation. outdated contents will be dealt with also.
