### ISSUE TITLE
takeLastBuffer method

### ISSUE THREAD

**Issue by rmakarov94** [ReactiveX/rxjs#3199]
Hello.
There is a method in rxjs4 [takeLastBuffer](http://reactivex.io/documentation/operators/takelast.html#collapseRxJS)
[docs](http://xgrommx.github.io/rx-book/content/observable/observable_instance_methods/takelastbuffer.html)
Are there any reasons why it's not implemented in 5th version? I'm very new to rx and looks like the only way to do the same is writing my own queue and pushing to it in subscribe?

**Comment by kwonoj** [comment]
v5 version aims reduced core api surface, makes some breaking changes including dropping few operators. With 5.5's pipe operator, it is easier to create custom operators and we do welcome to publish custom operators core api set doesn't cover.
