### ISSUE TITLE
debounce() and throttle()’s selector argument has wrong return type

### ISSUE THREAD

**Issue by mernen** [ReactiveX/rxjs#3204]
Here’s the current signature for `debounce()`:

https://github.com/ReactiveX/rxjs/blob/c1721e3dd582c509064e141425c15622f68d60cb/src/operators/debounce.ts#L53

One thing that confused me is that it asks for your function to return a `SubscribableOrPromise<number>`. The documentation compounded my confusion ("A function (…) for computing the timeout duration for each source value”): is my selector supposed to return the number of milliseconds? Turns out the result of that observable/promise is completely discarded.

**RxJS version:** 5.5.6 (and, looking at the code, [the next branch](https://github.com/ReactiveX/rxjs/blob/27576f749ecac85cc4238eead8b1e54673e1e440/src/operator/debounce.ts#L52), too)

**Additional information:** `throttle()` has the same issue. Interestingly, `audit()` is correctly using `SubscribableOrPromise<any>`:

https://github.com/ReactiveX/rxjs/blob/c1721e3dd582c509064e141425c15622f68d60cb/src/operators/audit.ts#L52

**Comment by cartant** [comment]
Regarding `debounce`, see #3164 and #3169. I will have a look at the `throttle` typings.

**Comment by mernen** [comment]
Ah, that’s nice! Sorry, it completely forgot to search for past reports. My bad.

**Comment by cartant** [comment]
No worries; you're right. `throttle` also uses `number` instead of `any`. I'll create another PR.
