### ISSUE TITLE
No "do" operator in `/src/operators.ts`

### ISSUE THREAD

**Issue by hanvyj** [ReactiveX/rxjs#3209]
**RxJS version:** Latest (looking at source). Tested on 5.5.5

**Code to reproduce:**

    import { do } from 'RxJs/Operators';
or

    import { do } from 'RxJs/Operators/do';

**Expected behavior:**

The operators.ts file allows lettable imports of operators, I'd expect `do` to be present.

**Actual behavior:**

The following errors:

> Module '"/RxJs/Operators"' has no exported member 'do'.

OR

> Cannot find module 'RxJs/Operators/do'.

**Comment by kwonoj** [comment]
Please refer renamed operators section. https://github.com/ReactiveX/rxjs/blob/master/doc/lettable-operators.md#lettable-operators

**Comment by ZR87** [comment]
it became  the `tap` operator meanwhile 
https://www.learnrxjs.io/operators/utility/do.html
