### ISSUE TITLE
Cannot build docs. Getting TypeScript errors

### ISSUE THREAD

**Issue by iansinnott** [ReactiveX/rxjs#3213]
I can't get the docs to build. I'm running in to this issue because I build the docs locally every so often in order to update the [Rxjs Dash docset](https://github.com/iansinnott/rxjs-dash-docset). It seems to be an issue with the typescript compilation that gets run in the `build_docs` script.

Thanks for the help.

**RxJS version:** 5.5.3

**Code to reproduce:**

```
npm install
npm run build_docs
```

**Expected behavior:**

Docs are built successfully.

**Actual behavior:**

A wall of TS errors is printed to the console and the build fails.

**Additional information:**

I also tried running this in a `node:8.9` docker container and got the same result.

**Comment by kwonoj** [comment]
It is expected current doc script in this repo is not working, and current progresses is being handled at https://github.com/ReactiveX/rxjs-docs.

**Comment by iansinnott** [comment]
@kwonoj thanks. Didn't realize there was a separate repo for this
