### ISSUE TITLE
When exception is thrown in resultSelector function of forkJoin error is not propagated to subscriber.

### ISSUE THREAD

**Issue by mihailstefanov** [ReactiveX/rxjs#3216]
When exception is thrown in resultSelector function of forkJoin error is not propagated to subscriber.
I am not sure if it is normal behaviour or a bug?

**RxJS version:**
5.5.6

**Code to reproduce:**
```ts
Observable.forkJoin(
    Observable.of(1),
    Observable.of(2),
    (i, buffer) => {
        throw new Error('error');
    }).catch((error) => {
        return Observable.of(3);
    }).subscribe(console.log,
    (error) => {
        console.log('error!');
    });
```

**Expected behavior:**
to catch the error and print : error!

**Actual behavior:**
`node_modules/rxjs/Observable.js:165
                throw sink.syncErrorValue;`

**Additional information:**

**Comment by benlesh** [comment]
Confirmed. Thank you for reporting this @mihailstefanov
