### ISSUE TITLE
Docs: Dark theme toggle should also change code theme

### ISSUE THREAD

**Issue by siddharthkp** [ReactiveX/rxjs#3217]
**RxJS version:** All? (docs)

**Code to reproduce:**:  On this link, http://reactivex.io/rxjs/manual/tutorial.html

**Expected behavior:** The code block should also have a dark theme?

**Actual behavior:** Only the UI does 😢 

**Additional information:** Here's a gif

![dark-theme](https://user-images.githubusercontent.com/1863771/34651110-9b899f80-f3f1-11e7-9857-96e63103b641.gif)

I would volunteer to implement it, but I have no idea how it works 😅

**Comment by siddharthkp** [comment]
Also, if this is lame and you've bigger fish to fry, feel free to close this 😄

**Comment by benlesh** [comment]
It's a good idea... but we have a totally different documentation effort going on at github.com/reactivex/rxjs-docs

THanks @siddharthkp! :)
