### ISSUE TITLE
Rx.Subject complete event isn't work for concatMap

### ISSUE THREAD

**Issue by dorado-lmz** [ReactiveX/rxjs#3219]
```javascript
var subject$ = new Rx.Subject();
var result$  = subject$.concatMap(() => Rx.Observable.interval(1000).take(3))

result$.subscribe((val) => console.log(val));
//subject$.next(1);
subject$.complete();
```

The results have nothing to output in console.
when uncomment  `subject$.next(1)`, there is result `0 1 2` in console.

**RxJS version: 5.5**

**Code to reproduce: [JSBIN demo](http://jsbin.com/wozokig/edit?html,js,console)**

**Expected behavior: console output (0, 1, 2)**

**Actual behavior:no output in console**

**Additional information:**

**Comment by paulpdaniels** [comment]
This is expected behavior. In your example you aren't sending any data through the `Subject` so there is nothing to concatenate. When you call complete without any in flight streams then it will complete the whole stream.

**Comment by cartant** [comment]
@dorado-lmz Yep, expected behaviour. See [this test](https://github.com/ReactiveX/rxjs/blob/5.5.6/spec/operators/concatMap-spec.ts#L70-L82).

**Comment by benlesh** [comment]
This is expected behavior. Sorry for the confusion, @dorado-lmz 

`concatMap` only recieves _nexted_ values to map into new observables. `complete` won't send anything through `concatMap`, it just passes completion along.

I hope that helps!
