### ISSUE TITLE
old-way rxjs operators and factory methods vs lettable ones

### ISSUE THREAD

**Issue by fastovezz** [ReactiveX/rxjs#3222]
I posted this question [here](https://github.com/Reactive-Extensions/RxJS/issues/1540) but didn't get an answer. I think this question relates to the library documentation improvements so I put it here too.

I bumped into the problem with lettable operators, in particular, with timer.

For instance, this:
```import 'rxjs/add/operator/catch'```
-- still works and even changes Observable object globally so there's no need to import that '```catch```' again in a certain ts file once it is imported in project module file.

And this:
```import 'rxjs/add/observable/timer'```
-- doesn't work anymore, instead:
```import { timer } 'rxjs/observable/timer'```
-- should be used and it doesn't modify Observable object, it is used as an independent function, and it cannot be imported globally, it should be imported in each ts file individually if it is needed.

Why is
```import 'rxjs/add/operator/catch'```
still in use and has its counterpart of
```import {catchError} from 'rxjs/operators/catchError'```
and
```import 'rxjs/add/observable/timer'```
is no longer in use?

Is there any documentation on the topic? On the import syntax migration?

Thank you.

**Comment by dmitrysteblyuk** [comment]
I guess operators can be imported the old way (```import 'rxjs/add/operator/catch'```) because otherwise they wouldn't be available in observable chain (they're prototype methods). But methods like ```timer``` are static and being used only to create a new observable.

I think this approach (being forced to import static methods in every file) less error-prone because before for example you could import static method in a lazy module and it still would be ok with ts compiler to use it everywhere across your app, but would cause an error at runtime

**Comment by fastovezz** [comment]
leaving possibility to import operators in an old way while having new-way lettable operators saves lots of nerves to developers who use rxjs.

Why backward compatible support of some factory methods (timer, interval...) was removed while some other are still supported (of...) -- that's a mystery and a huge headache.

**Comment by benlesh** [comment]
They're all still there in 5.5.

Technically, I would advise against using any of the `rxjs/add/*` variants, unless you're really sure you know what you're doing. It can just cause a lot of pain in larger projects or in bigger teams.

**Comment by benlesh** [comment]
I think this can be closed. It was a misunderstanding.
