### ISSUE TITLE
Reinstate the "prevent unwanted clearInterval" PR

### ISSUE THREAD

**Issue by cartant** [ReactiveX/rxjs#3225]
I left [a comment](https://github.com/ReactiveX/rxjs/pull/3152#issuecomment-354638226) on the PR that reverted PR #3044. After Zone.js 0.8.19 was released I looked into the reported Angular problem and discovered that PR #3044 was not the cause.

The comment is repeated below.

---

FYI, the problem with 5.5.3 is **unrelated** to PR #3044 and it was **not** the reversion of that PR that solved the problem of Angular's routing module effecting an `EmptyError`.

Instead, the problem appears to have been the way in which the `.js` files in 5.5.3 were generated.

I can reproduce the effected error by taking the `util/EmptyError.js` file from 5.5.3 and overwriting the file in the 5.5.2 distribution.

In fact, if you look at the files that are incorporated into [the Plunk](http://plnkr.co/edit/LW7lfgL0BZmnYzsbMgsD), you will see that `scheduler/AsyncAction.js` - the file modified in PR #3044 - does not even form part of the build.

The 5.5.2 [`EmptyError.js` file](https://unpkg.com/rxjs@5.5.2/util/EmptyError.js) looks like this:

```js
"use strict";
var __extends = (this && this.__extends) || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
};
/**
 * An error thrown when an Observable or a sequence was queried but has no
 * elements.
 *
 * @see {@link first}
 * @see {@link last}
 * @see {@link single}
 *
 * @class EmptyError
 */
var EmptyError = (function (_super) {
    __extends(EmptyError, _super);
    function EmptyError() {
        var err = _super.call(this, 'no elements in sequence');
        this.name = err.name = 'EmptyError';
        this.stack = err.stack;
        this.message = err.message;
    }
    return EmptyError;
}(Error));
exports.EmptyError = EmptyError;
//# sourceMappingURL=EmptyError.js.map
```

Whereas the 5.5.3 [`EmptyError.js` file](https://unpkg.com/rxjs@5.5.3/util/EmptyError.js) looks like this:

```js
"use strict";
var __extends = (this && this.__extends) || (function () {
    var extendStatics = Object.setPrototypeOf ||
        ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
        function (d, b) { for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p]; };
    return function (d, b) {
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
/**
 * An error thrown when an Observable or a sequence was queried but has no
 * elements.
 *
 * @see {@link first}
 * @see {@link last}
 * @see {@link single}
 *
 * @class EmptyError
 */
var EmptyError = /** @class */ (function (_super) {
    __extends(EmptyError, _super);
    function EmptyError() {
        var _this = this;
        var err = _this = _super.call(this, 'no elements in sequence') || this;
        _this.name = err.name = 'EmptyError';
        _this.stack = err.stack;
        _this.message = err.message;
        return _this;
    }
    return EmptyError;
}(Error));
exports.EmptyError = EmptyError;
//# sourceMappingURL=EmptyError.js.map
```

The `EmptyError` implementation in 5.5.3 seems to mess with [this `instanceof` test](https://github.com/angular/angular/blob/5.1.2/packages/router/src/apply_redirects.ts#L169-L175) in Angular's router.

Why the two generated files differ, I have no idea. The [`EmptyError.js` generated for 5.5.4](https://unpkg.com/rxjs@5.5.4/util/EmptyError.js) is identical to that generated for 5.5.2, yet there appear to be [no configuration changes](https://github.com/ReactiveX/rxjs/compare/6ebc565d05eff5bf20bfc0f77feba4b099d51f82...f0ff5bcf4da474f3fafb5e82befacf7a286cdca1) between 5.5.3 and 5.5.4, so I can only presume that the build environment for 5.5.3 was not what it should have been.

The Zone.js bug - in the [PR](https://github.com/angular/zone.js/pull/935) that I referenced above - does not effect the `EmptyError`. The bug is related to my PR, as there was a (far more subtle) problem with Zone.js and `setInterval`, but that has been fixed with the release of version 0.8.19 of Zone.js.

Given that the reported problem was unrelated to the reverted PR and that the PR fixes a problem with intervals drifting (see [this issue](https://github.com/ReactiveX/rxjs/issues/3042) and [this SO question](https://stackoverflow.com/q/47946750/6680611)) I think [the commit](https://github.com/ReactiveX/rxjs/commit/7d722d4d36debcf5bb79fa4006f455bd72caeee1) should be reinstated. If not into stable, then definitely into master.

**Comment by benlesh** [comment]
That... might have been the time I built 5.5 with the wrong version of TypeScript.

That said, we need to be careful with 6.0, as it's using a newer version of TypeScript.

**Comment by cartant** [comment]
@benlesh FYI, the [`internal/util/EmptyError.js`](https://unpkg.com/rxjs@6.0.0-alpha.2/internal/util/EmptyError.js) generated by the version of TypeScript used with 6.0.0-alpha.2 is fine.

It's different to the 5.5.2 `EmptyError.js` and is more similar to the 5.5.3 `EmptyError.js`, but it includes a call to `Object.setPrototypeOf(_this, EmptyError.prototype);` which suggests it will work fine with `instanceof EmptyError`.

I guess there was a TypeScript bug in an earlier version that has since been fixed.
