### ISSUE TITLE
rxjs/util/pipe/pipeFromArray<T,R> only works if T==R

### ISSUE THREAD

**Issue by andresenmichael** [ReactiveX/rxjs#3228]
**RxJS version:** 5.5.6

**File:** [util/pipe.ts](https://github.com/ReactiveX/rxjs/blob/5.5.6/src/util/pipe.ts)

**Code to reproduce:**
```typescript
type T = Observable<string>;
type R = Observable<number>;

const op1: UnaryFunction<T, R> = map((value: string) => parseInt(value);
const op2: UnaryFunction<T, R> = map((value: string) => value.length); // maps to undefined

const operators: Array<UnaryFunction<T, R>> = [op1, op2];
const op12: UnaryFunction<T, R> = pipeFromArray(operators);

ObservableOf('16').pipe(op12).subscribe(
    (value) => console.log(value.toPrecision(1)) // ==> ERROR: read property of undefined
);
```

**Actual behavior:**
` pipeFromArray<T, R>(fns: Array<UnaryFunction<T, R>>): UnaryFunction<T, R>` only works if `T==R`.

**Additional Info:**
I think pipeFromArray<T, R> should be replaced by
```typescript
declare function pipeFromArray<T>(fns: Array<UnaryFunction<T, T>>): UnaryFunction<T, T>;
```

**Comment by benlesh** [comment]
attn @david-driscoll

**Comment by david-driscoll** [comment]
This would enforce that all the methods have the same input and output types, when the output type could vary.

I think the method itself should be something like
`declare function pipeFromArray<T = any, R = any>(fns: Array<UnaryFunction<any, any>>): UnaryFunction<T, R>;`

**Comment by benlesh** [comment]
Hold on... I see the problem..

You're mapping a string to a number, then you're looking at the `length` property... on a `Number`. :smile: 

We can close this one.

Also: You probably shouldn't be using `pipeFromArray`. Although using the `pipe` utility is kosher. We're fixing that in v6.
