### ISSUE TITLE
Align single() interface to last() to allow emit default value?

### ISSUE THREAD

**Issue by kwonoj** [ReactiveX/RxJS#323]
In case of [`last`](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/last.md) operator, it's allows to specify default value if there isn't any matching element.

`Rx.Observable.prototype.last([predicate], [thisArg], [defaultValue])`

[`single`](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/single.md) does similar jobs as operator that returns first matching element instead of last, but it does not allows to specify default value as 

`Rx.Observable.prototype.single(predicate, [thisArg])` 

so if there isn't any matching element only `undefined` will be emitted. 

Maybe it'd be better to align `single` also can accept default value?
Initial PR mimics existing behavior (do not accept default value) is created at https://github.com/ReactiveX/RxJS/pull/322

**Comment by kwonoj** [comment]
Or maybe just use `first` only instead of having `single` and `first` both?

**Comment by kwonoj** [comment]
At second thought, feel it may be better to leave `single` as is singe `first` does jobs for default value and `single` specifically guarantees if there is only single matching element. Leave issue opened to get clarification for now.

**Comment by blesh** [comment]
I'm closing this for now, as I think when it was asked, there was some confusion about the behavior of `single`.
