### ISSUE TITLE
jQuery promises are not working with retry

### ISSUE THREAD

**Issue by srikrishnacj** [ReactiveX/rxjs#3243]
```
$(function () {
    Rx.Observable
        .fromEvent($("html"), "click")
        .switchMap(() => Rx.Observable.fromPromise($.get('https://api.fixer.io/latest')).retry(3).catch(() => {
            console.log("Error")
            return Rx.Observable.empty();
        }))
        .subscribe(console.log)
})
```
![2018-01-20 20_16_01-currency converter](https://user-images.githubusercontent.com/4404755/35184672-cfc8da72-fe1e-11e7-9fc9-ff8dbcd33cae.png)
![2018-01-20 20_16_13-currency converter](https://user-images.githubusercontent.com/4404755/35184674-d1bf7e4e-fe1e-11e7-9a6f-59cfe07e10f0.png)

retry is set to 3 but only one network request is happening.
using latest versions of JQuery(3.x) and RxJS(5.x)

**Comment by paulpdaniels** [comment]
You can't retry raw `Promises`. You need to wrap them in a `defer` block in order to retry.

`defer(() => $.get('https://api.fixer.io/latest')).retry(3)`

**Comment by srikrishnacj** [comment]
Yes It works now. Thank you very much.
