### ISSUE TITLE
Missing documentation for leading/trailing configuration options of throttleTime

### ISSUE THREAD

**Issue by the-rasmussen** [ReactiveX/rxjs#3245]
I can't find any documentation for the leading and trailing options that were added to the throttleTime operator in this commit: 
https://github.com/ReactiveX/rxjs/commit/bb0738f3e6df643158c4a7d1e38f035978b42882

I expected to find these options explained along with the throttleTime method here:
http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#instance-method-throttleTime

**Comment by martinsik** [comment]
This seems to be already added here https://github.com/ReactiveX/rxjs/blob/master/src/internal/operators/throttleTime.ts#L46-L47.

Just the docs is not up to date.
