### ISSUE TITLE
Missing documentation for the `Observable.subscribe` method.

### ISSUE THREAD

**Issue by demurgos** [ReactiveX/rxjs#3255]
The [subscribe](https://github.com/ReactiveX/rxjs/blob/c3c56867eaf93f302ac7cd588034c7d8712f2834/src/internal/Observable.ts#L77) method of `Observable` is not documented on the website.
I'd like to link to documentation for this function but this currenly not possible, despite this method being largely discussed in the documentation.

**RxJS version:** Current documentation website (2018-01-24).

**Expected behavior:** <http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#instance-method-subscribe> should link to a rendered documentation of the instance method `subscribe` of `Observable`.

**Actual behavior:** This method is not documented on the website.

**Comment by torinthiel** [comment]
Most probably a duplicate of #2656.

**Comment by demurgos** [comment]
Thanks. I searched for `subscribe` and `documentation` but did not found the issue.
I see that `subscribe` was [mentioned in a comment](https://github.com/ReactiveX/rxjs/issues/2656#issuecomment-320876207).
