### ISSUE TITLE
[docs, opinionated] Creating custom observables, function bind operator

### ISSUE THREAD

**Issue by ducin** [ReactiveX/rxjs#3256]
Hi Guys, I love you all for Rx stuff you do!

However, there is one thing that slapped me in the face as I was reading on [how to create custom observables](https://github.com/ReactiveX/rxjs/blob/master/doc/operator-creation.md#adding-the-operator-to-observable) and that is the **function bind operator**...  I was wondering why I have never heard of that and now I know - it's [Stage 0](https://github.com/tc39/proposals/blob/master/stage-0-proposals.md). I know we all have our subjective/opinionated preferences, but using a Stage 0 proposal in a tutorial is introducing more confusion that makes things clear, IMHO, as majority might have never heard of such concept. As a result, instead of getting to know what nice feature you added into Rx, one has to spend some time digging into the proposal... which s not even close to being considered by TC39...

My suggestion is to use current ECMAScript, or at least Stage 3, as it already requires at least two implementations, so that *some* people might know it (such as React was using object spread operator, being Stage 3, for a long time).

Again, I admire your work! ❤️

**Comment by benlesh** [comment]
You might want to leave this issue over on https://github.com/reactivex/rxjs-docs, which is the new documentation effort.

But I'm pretty sure we're not going to show the bind operator over there.

FWIW: The bind operator was hot at the time.

cc @ladyleet

**Comment by cartant** [comment]
Closing this as it's my understanding that the bind operator is not mentioned in the current, v6 docs.
