### ISSUE TITLE
docs snippet are displaying html tags

### ISSUE THREAD

**Issue by phra** [ReactiveX/rxjs#3257]
**RxJS version:** `master`

**Expected behavior:**
no html tags are displayed in the docs popup

**Actual behavior:**
see `<span class="informal">` element.
![screenshot from 2018-01-25 16-57-45](https://user-images.githubusercontent.com/984628/35397968-24e44a16-01f1-11e8-87cf-a86d7c0aae15.png)

**Comment by benlesh** [comment]
@phra do you have a link? I'm not seeing this issue in the current docs. I see a LOT of other issues, though. haha.. Maybe you're looking at the new docs? File an issue on https://github.com/reactivex/rxjs-docs

cc @ladyleet

**Comment by JWO719** [comment]
This shouldn't occur in the new doc and is therefore closed
