### ISSUE TITLE
Remove Symbol.observable polyfill

### ISSUE THREAD

**Issue by benlesh** [ReactiveX/rxjs#3259]
Have rxjs examing for the presence of Symbol.observable and use it appropriately, otherwise, just skip that bit. It's important for interop, so anyone that wants to use it will have to have a polyfill somewhere anyhow.

**Comment by cartant** [comment]
Closing this because `symbol-observable` was moved to a dev dependency in https://github.com/ReactiveX/rxjs/commit/44006283f4d818c42a0814eb48cc91785bc40c4c and is no longer used as a polyfill in the published package.
