### ISSUE TITLE
Pipe operator publishReplay cannot infer generic type.

### ISSUE THREAD

**Issue by bowenni** [ReactiveX/rxjs#3260]
**RxJS version:**
5.5.0

**Code to reproduce:**
```ts
declare const obs: Observable<number>;
const temp: null = obs.pipe(publishReplay(1));
```
**Expected behavior:**
I'm expecting `Type 'Observable<number>' is not assignable to type 'null'.`

**Actual behavior:**
`Type 'Observable<any>' is not assignable to type 'null'.`

**Comment by benlesh** [comment]
Thanks, @bowenni.

This could just be an issue with TypeScript. cc @david-driscoll, can you please have a look at this?
