### ISSUE TITLE
6.0 alpha: Merge rxjs and rxjs/create into just rxjs?

### ISSUE THREAD

**Issue by benlesh** [ReactiveX/rxjs#3262]
In 6.0, so far we have:

- `rxjs`: Classes, schedulers and utilities: (`Observable`, `Subject`, `pipe`, `asyncScheduler`, etc)
- `rxjs/create`: Observable creation functions (`of`, `from`, `fromEvent`)
- `rxjs/operators`: Pipeable operators

I think we should probably merge `rxjs/create` and `rxjs`, because:

1. There are no name collisions
2. We want to export the `EMPTY` constant, and it's weird to export a constant from `rxjs/create`, and even weirder to export `empty()` from one spot and `EMPTY` from another.
3. One less import location

Thoughts?

**Comment by rgbkrk** [comment]
I like this proposal!

**Comment by benlesh** [comment]
This is done, it's all just `rxjs` now.
