### ISSUE TITLE
New operator: switchDo

### ISSUE THREAD

**Issue by mfp22** [ReactiveX/rxjs#3267]
I have a proposal for an operator called `switchDo`. 

As `switchMap` is to `map`, `switchDo` would be to `do`. Instead of returning nothing, as `do` does, `switchDo` would return an observable which would return nothing and have no effect on the main observable chain. But subscriptions to the main stream would be passed to `switchDo`'s inner observable.

To implement it with other operators would be something like 
```
const sourceWithSideEffect$ = source$.withLatestFrom(sideEffect$, 
  (source, sideEffect) => source
)
```

The same arguments for wanting to perform side effects with `do` apply to wanting to perform side effects within `switchDo`, just with an observable instead. 

My specific use case is wanting to write an `active` status on the server whenever certain data is being read. When all observers unsubscribe from sourceWithSideEffect$, I want sideEffect$ to write the `active` status to `false`.

**Comment by cartant** [comment]
You might not need a new operator to do what you seem to want to do.

Your description of what you want is something I find a little confusing, as the functions passed to `do` are called for each notification. However, you seem to be more interested in the subscriptions than the notifications:

> ... subscriptions to the main stream would be passed to switchDo's inner observable.

The [`using`](https://github.com/ReactiveX/rxjs/blob/master/src/internal/observable/UsingObservable.ts#L13-L43) observable creator might be what you are looking for. It takes a factory that creates a resource and a factory that creates an observable. With `source` and `sideEffect` observables, you could do something like this:

```ts
import { using } from 'rxjs/observable/using';
const sideEffect = ...
const source = ...
const sourceWithSideEffect = using(() => sideEffect.subscribe(), () => source);
```

Here, `sideEffect` will be subscribed to and unsubscribed from when `sourceWithSideEffect` is subscribed to and unsubscribed from. And the notifications from `sourceWithSideEffect` will be those from `source`.

Also, the resource does not have to be an observable, so if you are only interested in setting something active/inactive, you might not need an obserable for the side effect:

```ts
import { using } from 'rxjs/observable/using';
const source = ...
const sourceWithSideEffect = using(() => {
  /* set something active */
  return { unsubscribe: () => { /* set something inactive */ } };
}, () => source);
```

**Comment by mfp22** [comment]
Okay that's awesome. That works great. Thanks for the clear examples.
