### ISSUE TITLE
Is the some operator missing?

### ISSUE THREAD

**Issue by bkinsey808** [ReactiveX/rxjs#3268]
**RxJS version:**
5 or 6 alpha

**Code to reproduce:**
import { some } from 'rxjs/operators'

**Expected behavior:**
found

**Actual behavior:**
not found

**Additional information:**

it seems like this operator existed in RxJS 4 
https://github.com/Reactive-Extensions/RxJS/blob/6770d24307ed4baaecdbb21cfc178c13e459f42f/doc/api/core/operators/some.md

Looking at the example of every.ts, it seems pretty easy to add some back in.
https://github.com/ReactiveX/rxjs/blob/master/src/internal/operators/every.ts

I'd be willing to do a PR if it would be helpful.

**Comment by kwonoj** [comment]
Checkout migration guide from v4, https://github.com/ReactiveX/rxjs/blob/master/MIGRATION.md#operators-renamed-or-removed, `some` is deprecated on behalf of other operator substitution.

**Comment by bkinsey808** [comment]
Thanks! That was exactly what I was looking for!
