### ISSUE TITLE
Operator that executes after subscribe

### ISSUE THREAD

**Issue by amineparis** [ReactiveX/rxjs#3269]
It would be great if we have an operator that executes after subscribe. Having subscribe as the last function to be executed among all operators produces some restrictions : 

**Exemple :**
* `foo` is a function in class `A` that calls `subscribe`.
* classes that inherits from this class need to define some specific post processing logic after `foo ` subscribe is executed. 

Having such an operators allows doing this (which is not possible right now) :
```
Class A{

    foo(){
     this.http.subscribe(res=>{
        // do something
     })
    }
}

Class Aa extends A{
    constructor() { super(); }
    foo(){
       super.foo().wantedOperator(param=>{
       // do something after subscribe is executed
    })
    }
}
```

**Comment by Dorus** [comment]
Couple ideas:

1) `merge` with an observable that does your thing on subscribe.
This observable could a function that return an observable function, but also `create(ob => {... do stuff ... ob.complete() ... return teardown })` or `defer(() => { ... do stuff ... return an observable )`.

2) use `.let((src => { ... do stuff ... return src})`

3) use [`Observable.using`](http://reactivex.io/rxjs/test-file/spec-js/observables/using-spec.js.html).

**Comment by benlesh** [comment]
Since `subscribe` is executed immediately, all you'd need to do is compose some code right after:

```ts
class Aa extends A {
  foo() {
    super.foo();
    // subscribe is done being called at this point, execute whatever you like here.
  }
}
```

**Comment by amineparis** [comment]
this will not wait for foo to finish since it's async

**Comment by Dorus** [comment]
If `foo` is async it has no place in subscribe and should be placed inside a `mergeMap` or one of the other operators that can handle async calls.
