### ISSUE TITLE
Rxjs reference includes duplicate methods on Observable

### ISSUE THREAD

**Issue by hjfreyer** [ReactiveX/rxjs#3271]
For instance, here every() appears twice: http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#instance-method-every

In some cases (such as share()), the docs differ between the two versions, which is quite confusing.

**Comment by deanolium** [comment]
This is also the case for (the somewhat infamous) takeUntil method, where the documentation lists the method twice. The first listed documentation for the method is the old, incorrect text which mentions this works until the notifier sends a value or a complete notification; whilst the second listed documentation (which is directly after the first) has the corrected text, with the mention of complete notification removed.

It looks like the generation of the documentation probably merged the previous version with the fixes over the last year or so. Of course, this will be massively confusing for people just learning the library.

**Comment by benlesh** [comment]
I suspect this is due to duplicate documentation from the move to pipeable operators.

**Comment by souvikbasu** [comment]
Can I pick this up? It will be a good first issue for me to get started contributing to RxJs

**Comment by cartant** [comment]
Closing this as it appears to have been resolved with the v6 docs.
