### ISSUE TITLE
Circular dependency detection broken

### ISSUE THREAD

**Issue by benlesh** [ReactiveX/rxjs#3275]
Apparently, an update to [dependency-cruiser](https://github.com/sverweij/dependency-cruiser/issues/28) the other day caused our Travis builds to start breaking. 

We'll need to pin this to an older version until we figure out a better solution.

**Comment by kwonoj** [comment]
now's time to have `package-lock.json` with pinned version? thoughts?

**Comment by benlesh** [comment]
Probably. I'm going to just pin it in package.json for now tho... quick fix.

**Comment by kwonoj** [comment]
makes sense.
