### ISSUE TITLE
question about buffer operators

### ISSUE THREAD

**Issue by snackycracky** [ReactiveX/rxjs#3278]
Hello, why do operators such as bufferWhen that call a users function every time they open a new buffer/window don't let you react to values going through ?
I would like to flush the buffer when some condition on the buffered accumulation is met.

**Comment by snackycracky** [comment]
I mean, is there a reason for this design? I am sure it was discussed before.

**Comment by benlesh** [comment]
cc @mattpodwysocki ... bufferWhen is based off of one of behaviors of `buffer` from RxJS 4 and under. I'm not sure what the rationale was with the design... only how I've used it.

Referring to The Man himself for the design info. :raised_hands:

**Comment by snackycracky** [comment]
this question is based on an answer on so: https://stackoverflow.com/q/48526452/170881

**Comment by snackycracky** [comment]
@mattpodwysocki ping ping :)

**Comment by BioPhoton** [comment]
@snackycracky Is your request still relevant? 
If not, would you mind closing this issue? If yes please let me know. :)

**Comment by BioPhoton** [comment]
Hi @snackycracky 

Could you provide the condition in the trigger observable?

```typescript
const fakeSource = of(1,2,42,3,4,2,3,6,42,1,2,3,1,42)
  .pipe(delay(100),share());

const conditionMet = fakeSource.pipe(filter(v => v === 42));
fakeSource.pipe(
  buffer(conditionMet)
).subscribe(x => console.log(x));
```

Does that help?

**Comment by BioPhoton** [comment]
Hi @snackycracky!

I tried hard to get your desired answer. I pinged multiple people. And I had to give up on this. 
I'm sorry I could not help you further.

If you would be so kind and close this issue and help to keep the number of open issues small.

Best Michael

**Comment by snackycracky** [comment]
Thanks Michael for your hard work, but no. I will post the answer whenever I find it and then close this „hard to answer“ question.

**Comment by BioPhoton** [comment]
Thanks @snackycracky!

There might be the chance that i meet Matt in 2020 so I can ask.

Other than that I have no chance to figure out the real intentions of Matt and the initial design in rxjs.

Feel free to reopen ask or open a new issue. 
🙏
