### ISSUE TITLE
map operator behaves differently when passing function vs calling the function inside lambda

### ISSUE THREAD

**Issue by Venthe** [ReactiveX/rxjs#3279]
**RxJS version:** 5.5.* (reproduced on 5.5.6)

**Code to reproduce:** [JSFiddle](http://jsfiddle.net/Venthe/L24ettj7/)
```ts
interface Action {
  type: string;
}

const subarray_1: Action[] = [{
  type: "sample_1_1"
}, {
  type: "sample_1_2"
}];

const subarray_2: Action[] = [{
  type: "sample_2_1"
}, {
  type: "sample_2_2"
}];

const subarray_3: Action[] = [{
  type: "sample_3_1"
}, {
  type: "sample_3_2"
}];

const sample_subarray_1: Observable < Action[] > = Rx.Observable.of(subarray_1);
const sample_subarray_2: Observable < Action[] > = Rx.Observable.of(subarray_2);
const sample_subarray_3: Observable < Action[] > = Rx.Observable.of(subarray_3);

const sample_array: Observable < Observable < Action[] > [] > = Rx.Observable.from([
  sample_subarray_1, sample_subarray_2, sample_subarray_3]);

const result: Observable<Action[]>= sample_array
  .concatAll()
  .toArray()
  .do(a=>{console.warn("Result map 1",a)})
  .map( _.flatMap)
  .subscribe(a=>{console.error("After map 2",a)});

const result2: Observable<Action[]>= sample_array
  .concatAll()
  .toArray()
  .do(a=>{console.warn("Result map 2",a)})
  .map(a=>{ return _.flatMap(a); })
  .subscribe(a=>{console.error("Result map 2",a)});

const result3: Action[] = _.flatMap([subarray_1,subarray_2,subarray_3]);
console.error("Result 3",result3);
```

**Expected behavior:**
result==result2==result3 (ofc ignoring observables)

**Actual behavior:**
When function is passed as a parameter, it behaves differently than when it's called inside a lambda

**Additional information:**
Requires lodash
Based on the same example as https://github.com/ReactiveX/rxjs/issues/3280

**Comment by benlesh** [comment]
I've formatted the code in the OP a little so I can read it a little better :D

**Comment by benlesh** [comment]
@Venthe OOooo... this was a tricky one at first.

RxJS's map signature is the same as Array's map (basically): `map((value: T, index: number) => R)`

Calling, lodash's function with two arguments, and array and a number, causes this different behavior.


so... `map((value, i) => _.flatMap(value, i))` is equivalent to `map(_.flatMap)` :smile: 

Tricky, but this isn't a bug.  Thanks for the fun one.

**Comment by Venthe** [comment]
Thanks for clarifying, it seems obvious in retrospect, yet it was a reason for a lot of hair pulled out :)
