### ISSUE TITLE
Typings after concatAll on observable array of observables are incorrect

### ISSUE THREAD

**Issue by Venthe** [ReactiveX/rxjs#3280]
**RxJS version:** 5.5.* (reproduced on 5.5.6)

**Code to reproduce:**
```ts
interface Action {
  type: string;
}

const subarray_1: Action[] = [{
  type: "sample_1_1"
}, {
  type: "sample_1_2"
}];

const subarray_2: Action[] = [{
  type: "sample_2_1"
}, {
  type: "sample_2_2"
}];

const subarray_3: Action[] = [{
  type: "sample_3_1"
}, {
  type: "sample_3_2"
}];

const sample_subarray_1: Observable < Action[] > = Rx.Observable.of(subarray_1);
const sample_subarray_2: Observable < Action[] > = Rx.Observable.of(subarray_2);
const sample_subarray_3: Observable < Action[] > = Rx.Observable.of(subarray_3);

const sample_array: Observable < Observable < Action[] > [] > = Rx.Observable.from([sample_subarray_1, sample_subarray_2, sample_subarray_3]);

const result: Observable<Action[][]>= sample_array.concatAll().toArray();
```

**Expected behavior:**
Code transpiles

**Actual behavior:**
TS Error: Cannot map Observable<Observable<Action[]>[]> to Observable<Action[][]>

**Additional information:**
Based on the same real code as in https://github.com/ReactiveX/rxjs/issues/3279

**Comment by benlesh** [comment]
The result of `Observable<Observable<T>>` after `concatAll()` is `Observable<T>`... so `Observable<Observable<Action[]>>` after `concatAll()` would be `Observable<Action[]>`.

Your compilation problem is actually here:

```ts
const sample_array: Observable < Observable < Action[] > [] > =
  Rx.Observable.from([sample_subarray_1, sample_subarray_2, sample_subarray_3]);
```

`Rx.Observable.from([sample_subarray_1, sample_subarray_2, sample_subarray_3])` returns `Observable<Observable<Action[]>>`, not `Observable<Observable<Action[]>[]>`, you'd have to use `Observable.of` for that.

**Comment by Venthe** [comment]
Shouldn't concat all flatten this results? And if I may ask, why this works? Because it does work, only typings are showing me a wrong value

**Comment by benlesh** [comment]
`concatAll` will flatten `Observable<T[]>` into `Observable<T>`
