### ISSUE TITLE
Class 'Subject<T>' incorrectly extends base class 'Observable<T>'. 

### ISSUE THREAD

**Issue by amar-muratovic** [ReactiveX/rxjs#3281]
Dear all,

besides problems with Opaque Token, this is my second issue when I start my Ionic App. I really don't have any more ideas how to solve this issue. 

Complete message:

Class 'Subject<T>' incorrectly extends base class 'Observable<T>'. Types of property 'lift' are incompatible. Type '<R>(operator: Operator<T, R>) => Observable<T>' is not assignable to type '<R>(operator: Operator<T, R>) => Observable<R>'. Type 'Observable<T>' is not assignable to type 'Observable<R>'. Type 'T' is not assignable to type 'R'.

Error:

*/
--
  | export declare class Subject<T> extends Observable<T> implements ISubscription {
  | observers: Observer<T>[];

Enviroment: 

Ionic Framework: 3.9.2
Ionic App Scripts: 3.1.8
Angular Core: 5.0.3
Angular Compiler CLI: 5.0.3
Node: 6.10.3
OS Platform: Windows 10
Navigator Platform: Win32
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36

**Comment by kwonoj** [comment]
What version of Rx you are using?

**Comment by amar-muratovic** [comment]
5.5.6  @kwonoj

**Comment by kwonoj** [comment]
5.5.6 includes fixes library side issues regression.
Please ensure
1. if there's any other duplicated dep have lower version
2. if there's extending / subclassing on user code

if both are not the case, it'd appreciate to provide reproducible repo, without ng / or ionic to isolate from library side behavior.

**Comment by ramakanthreddyk** [comment]
Save this line this to a TypeScript file (test.ts):
import {Subject} from 'rxjs/Subject';

this solved my problem in angular2

**Comment by kwonoj** [comment]
I'm closing this issue as lacks of detail to investigate more. Please feel freely reopen / create new issue with suggested steps in https://github.com/ReactiveX/rxjs/issues/3281#issuecomment-362032012 .
