### ISSUE TITLE
package.json `main` key should not point to Rx.js

### ISSUE THREAD

**Issue by sarunint** [ReactiveX/rxjs#3286]
**RxJS version:** 6.0.0-alpha.2

**Code to reproduce:** N/A

**Expected behavior:** When I import RxJS like this:
```typescript
import { Observable } from 'rxjs';
```
I should get only the classes (Observable, Subject, etc.) which are not patch with the *old-style* operators.

**Actual behavior:** 
I got the whole RxJS library. And `Observable` is patched with pre-pipeable operators.

**Additional information:** If this issue is confirmed, I'd be happy to send a PR to fix.

Furthermore, shouldn't prototype patching be deprecated in v6? I'm not sure about the roadmap for v6.

**Comment by berlysia** [comment]
This issue seems to be resolved by #3316
