### ISSUE TITLE
Types not properly inferred when passing a generator to `from`

### ISSUE THREAD

**Issue by benlesh** [ReactiveX/rxjs#3294]
Just filing this after a conversation here #1497 

Basically the report was that TypeScript won't compile `from(function* () { yield of('test'); }())` properly.

Still requires investigation and confirmation.

**Comment by cartant** [comment]
See also #2306.

**Comment by benlesh** [comment]
As I stated over in the other thread, maybe the real solution is just to type the input to `from` as `any`:  `from<T>(input: any, scheduler?: IScheduler): Observable<T>` ... seems gross, but the type checking here doesn't seem to work and we have to check it again at runtime anyhow.

**Comment by cartant** [comment]
I'm not sure that the TypeScript signatures for `Array.from` rely upon the use of `any`.

The pre-ES2015 `ArrayConstructor` is [here](https://github.com/Microsoft/TypeScript/blob/v2.7.1/lib/lib.d.ts#L1262-L1271) and the ES2015 core lib adds `from` signatures using [`ArrayLike`](https://github.com/Microsoft/TypeScript/blob/v2.7.1/lib/lib.es2015.core.d.ts#L69-L89):

```ts
from<T>(arrayLike: ArrayLike<T>): T[];
from<T, U>(arrayLike: ArrayLike<T>, mapfn: (v: T, k: number) => U, thisArg?: any): U[];
```

The ES2015 iterable lib adds `from` signatures using [`Iterable`](https://github.com/Microsoft/TypeScript/blob/v2.7.1/lib/lib.es2015.iterable.d.ts#L70-L84):

```ts
from<T>(iterable: Iterable<T> | ArrayLike<T>): T[];
from<T, U>(iterable: Iterable<T> | ArrayLike<T>, mapfn: (v: T, k: number) => U, thisArg?: any): U[];
```

**Comment by benlesh** [comment]
This is no longer a problem in 6.0.0-alpha.4 which targets a newer version of TS.
