### ISSUE TITLE
Support - need help finding alternative operator to Observable.zip

### ISSUE THREAD

**Issue by ORESoftware** [ReactiveX/rxjs#3300]
I have this question on SO
https://stackoverflow.com/questions/48636114/observable-zip-but-get-first-value-dont-wait-for-all-values

doubt I will get an answer, so coming here for some action. Here is the question:

Say I have this:

```js
const a = new BehaviorSubject(0);
const b = new BehaviorSubject(0);

Observable.zip(
    a.asObservable(),
    b.asObservable()
)
.subscribe(v => {
    // this will fire with [0,0]
    // but I want it to also fire with [1,0]
});

a.next(1);
```

how can I achieve what's in the comment in the subscribe next function? I believe I need to find a different operator than Observable.zip(), something like Observable.first().

if I call b.next(2), hen I will get [1,2] in the callback. But for the purpose of the question, b.next() is never called, only a.next().

**Comment by dengwanc** [comment]
zip only works the shortest observable.
__combineLatest should work__

**Comment by benlesh** [comment]
Looks like the SO question was answered. Closing.
