### ISSUE TITLE
map(atob) doesn't work without wrapper function

### ISSUE THREAD

**Issue by franciscotln** [ReactiveX/rxjs#3305]
**RxJs version**
5.5.2 (also in the docs page, in the console, same problem)

**Code to reproduce:**
```js
Rx.Observable.of("eyJmaXJzdE5hbWUiOiJSYWZhbCIsImxhc3ROYW1lIjoiTWFzemtvd3NraSIsImVtYWlsIjoidGVzdEB0ZXN0LnBsIiwidG9rZW4iOiJ0b2tlbiJ9")
.map(atob)
.subscribe(console.log);
```

**Expected behavior:**
should log `"{"firstName":"Rafal","lastName":"Maszkowski","email":"test@test.pl","token":"token"}"`

**Actual behavior:**
logs error: Uncaught TypeError: Illegal invocation at eval (eval at MapSubscriber._next (0-Rx.js:5709)

**Additional information:**
the problem I found in the source code is in MapSubscriber. The project function `this.project` is called via `this.project.call(this.thisArg, value, this.count++);` but `atob` doesn't work if the thisArg isn't null/undefined/window.

**Comment by dengwanc** [comment]
the correct way is
```
Rx.Observable.of("eyJmaXJzdE5hbWUiOiJSYWZhbCIsImxhc3ROYW1lIjoiTWFzemtvd3NraSIsImVtYWlsIjoidGVzdEB0ZXN0LnBsIiwidG9rZW4iOiJ0b2tlbiJ9")
.map(i => atob(i))
.subscribe(console.log);
```

**Comment by franciscotln** [comment]
@dengwanc what do you mean by the correct way? We know that using a fat arrow and then calling atob works but I think this is not the point of the issue. `atob` is a valid function to be directly passed to `.map()` so I don't understand the correctness of map(v => atob(v)) over map(atob)

**Comment by dengwanc** [comment]
window.atob(arg)
is not equal
atob.call(null, arg)

call atob depend on window

**Comment by dengwanc** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/atob

map(atob, window) should also work

**Comment by dengwanc** [comment]
i will check again.

i think this is atob itself problem,
not rxjs design problem.

**Comment by berlysia** [comment]
This problem seems to be the same as `console.log` in old browsers.
It had to be written as `console.log.bind(console)`, but now we can use it without bind in major environment.

+1 for this issue is not RxJS's problem.
ref: https://stackoverflow.com/questions/8159233/typeerror-illegal-invocation-on-console-log-apply

**Comment by benlesh** [comment]
@dengwanc's solution is correct. Closing this one.
