### ISSUE TITLE
TypeError: Rx.Observable.mergeDelayError is not a function

### ISSUE THREAD

**Issue by Nerketur** [ReactiveX/rxjs#3307]
**RxJS version:**
RxJS 5+

**Code to reproduce:**

var source1 = Rx.Observable.of(1,2,3);
var source2 = Rx.Observable.throw(new Error('whoops!'));
var source3 = Rx.Observable.of(4,5,6);

var merged = Rx.Observable.mergeDelayError(source1, source2, source3);

var subscription = merged.subscribe(
  function (x) { console.log('Next: %s', x); },
  function (err) { console.log('Error: %s', err); },
  function () { console.log('Completed') } );

**Expected behavior:**
Behavior described in the documentation: http://reactivex.io/documentation/operators/merge.html (down at the bottom, expand RxJS.  the three streams are merged as if Concat was used, and the error doesn't appear until the end

**Actual behavior:**
An error appears on the console: 'TypeError: Rx.Observable.mergeDelayError is not a function' in Firefox.

**Additional information:**
It seems that this function did exist in RxJS 4, but the current documentation (linked above) seems to imply that the function still exists.  Either I'm missing something, or this is a documentation bug.
(Also, if I posted this in the wrong location, please tell me where I need to put it.  I'm not sure if there's a "ReactiveX docs" repository, but I figured since the issue isn't specific to the RxJS docs themselves, here would be better than the 'rxjs docs' repo.  If I'm wrong, kindly let me know and I can make an issue over there instead :) )

**Comment by cartant** [comment]
I don't know where you should report issues with the multi-language Rx documentation that you have referenced, but the language-specific documentation for RxJS 5 is [here](http://reactivex.io/rxjs/) and it's generated from the JSDoc/TSDoc in this repo. It's currently being re-worked and the new documentation repo is [here](https://github.com/ReactiveX/rxjs-docs).

There is also a document in this repo that highlights the differences between RxJS versions 4 and 5: [MIGRATION.md](https://github.com/ReactiveX/rxjs/blob/stable/MIGRATION.md)

**Comment by kwonoj** [comment]
`mergeDelayError` is not included in core of v5. For documentation side, we have progresses in https://github.com/ReactiveX/rxjs-docs to reflect latest changes of RxJS in further.
