### ISSUE TITLE
Standardize <void>ReplaySubject to behave like <void>Subject

### ISSUE THREAD

**Issue by euangoddard** [ReactiveX/rxjs#3312]
**RxJS version:** 5.5.6

**Code to reproduce:** 
```typescript
const replaySubject = new ReplaySubject<void>(1);
// At some later point
replaySubject.next();
```

**Expected behavior:** I can call `next()` without any arguments since the subject is a `void` type.

**Actual behavior:** I have to call `next()` with `undefined` or `null` to signal that something has happened to the replay subject.

**Additional information:** Essentially I want to use a replay subject to indicate whether something has happened. I need to use a ReplaySubject so that new subscribers connecting can know whether the subject has emitted in the past, but the value that subject emits is irrelevant to any subscribers (hence using a void replay subject).

This behaviour seems at odds with how `Subject` works and their implementation of `next()` differs. I noticed that this behaviour was changed here: https://github.com/ReactiveX/rxjs/issues/1728, but am unsure whether my proposed change will be accepted given this issue: https://github.com/ReactiveX/rxjs/issues/2852

I will be happy to submit a PR for this if this change would be accepted.

**Comment by kwonoj** [comment]
As discussed in https://github.com/ReactiveX/rxjs/pull/3074, we will wait for upstream change https://github.com/Microsoft/TypeScript/issues/12400#issuecomment-342999977 to properly support behavior around those. We probably won't going to introduce interim changes until then as it may break between changes we introduce.

**Comment by BioPhoton** [comment]
@kwonoj  or @cartant 

This is already resolved. I tested it.

So imho this issue can be closed.

**Comment by cartant** [comment]
Closing this because the problem has been resolved in v7 - in https://github.com/ReactiveX/rxjs/pull/5307, IIRC.
