### ISSUE TITLE
Add Documentation - Observable.publishReplay

### ISSUE THREAD

**Issue by jonathanconway** [ReactiveX/rxjs#3318]
Add description to the docs for this operator. Include description of what the operator does, how it works, as well as any values it returns and fully defining parameters including name, type, attribute and description.

To be added to the [Publish](http://reactivex.io/documentation/operators/publish.html) section of the docs.

**Comment by kwonoj** [comment]
We are handling docs to do list separately on https://github.com/ReactiveX/rxjs-docs , please check current progresses in there.
