### ISSUE TITLE
custom comparer not working for distinct

### ISSUE THREAD

**Issue by errorx666** [ReactiveX/rxjs#3323]
**RxJS version:**
5.5.6

**Code to reproduce:**
```js
Observable.of( 1, 1, 2, 2, 3, 4 )
.distinct( x => x, ( a, b ) => a !== b )
.subscribe( console.log.bind( console ) );
```

**Expected behavior:**
```
1
2
3
4
```

**Actual behavior:**
no output

**Additional information:**
It doesn't seem to matter what the comparer function is, when I pass the parameter nothing happens.

**Comment by kwonoj** [comment]
distinct doesn't accept comparer. https://github.com/ReactiveX/rxjs/blob/stable/src/operators/distinct.ts#L56

`distinct<T, K>(keySelector?: (value: T) => K, flushes?: Observable<any>)`

**Comment by errorx666** [comment]
@kwonoj 
http://reactivex.io/documentation/operators/distinct.html

In RxJS, the distinct operator has two optional parameters:

a function that accepts an item emitted by the source Observable and returns a key which will be used instead of the item itself when comparing two items for distinctness
a function that accepts two items (or two keys) and compares them for distinctness, returning false if they are distinct (an equality function is the default if you do not supply your own function here)

**Comment by kwonoj** [comment]
There are outdated document issues and it's tracked separately by https://github.com/ReactiveX/rxjs-docs currently. Typescript definition is currently most accurate source for getting exact signature, or otherwise refer in-progress document.

**Comment by errorx666** [comment]
Is there no way to perform distinct with a composite (tuple-valued) key then?

**Comment by kwonoj** [comment]
There are several variant of distinct in v5. https://github.com/ReactiveX/rxjs/blob/stable/src/operators/distinctUntilChanged.ts#L10 / https://github.com/ReactiveX/rxjs/blob/stable/src/operators/distinctUntilKeyChanged.ts#L5
