### ISSUE TITLE
Rename `flatMap` to `mergeMap`

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#333]
Again, the result of bike shedding elsewhere. cc/ @jhusain 

However with this one, since flatMap is so popular and known from other languages/libraries, we might want to leave an alias.

**Comment by saneyuki** [comment]
I think we __should__ leave `flatMap()` as an alias if we do this change. flatMap is very popular terminology as to flattening mapping name so it's not better to remove `flatMap` name for interoperability of concept of this area.
