### ISSUE TITLE
Cannot read property 'lift' of undefined when using .pipe and pure function operators

### ISSUE THREAD

**Issue by Draccoz** [ReactiveX/rxjs#3333]
**RxJS version:**
5.5.6

**Code to reproduce:**
https://codepen.io/Draccoz/pen/QQrvgg/

**Expected behavior:**
Should throw no errors. Should match the behavior of the same flow with operators added to the Observable prototype ([example](https://codepen.io/Draccoz/pen/NyMpWm/))

**Actual behavior:**
An error is thrown `Cannot read property 'lift' of undefined` in `throttleTime.js` (works the same for every other operator that is first in the pipe). Code does not run further.

**Additional information:**
The above examples use ES Modules to pull in RxJS, please use browser that supports them.

**Comment by cartant** [comment]
The functions in the `rxjs/operator` director are the operators that are patched onto `Observable.prototype` and they need to be called with a context.

Instead, you should use the functions in the `rxjs/operators` directory - note the plural. (And `_do` has been [renamed to `tap`](https://github.com/ReactiveX/rxjs/blob/master/doc/pipeable-operators.md).)

**Comment by Draccoz** [comment]
OK, that was my bad then. Thank you a lot for a quick response :).
