### ISSUE TITLE
Exclude src/ from published npm package

### ISSUE THREAD

**Issue by roblg** [ReactiveX/rxjs#3334]
**RxJS version:**

At least version 5.5.6

**Expected behavior:**

`src/` folder (in particular, the BUILD.bazel file) is excluded from published npm package.

**Actual behavior:**

`src/` folder including BUILD.bazel file is included in published npm package, and gets picked up by our bazel in node_modules (we're currently using bazel primarily for Java, and not yet for JS for development):

```
(08:20:56) ERROR: error loading package 'node_modules/rxjs/src': Extension file not found. Unable to load package for '@build_bazel_rules_typescript//:defs.bzl': The repository could not be resolved
```

**Additional information:**

Love that you're using bazel in an open source JS project! <3 Bazel.

**Comment by kwonoj** [comment]
I'm not entirely sure if it's accident to include bazel, what I vaguely remember is it is intended for ng build process. /cc @alexeagle for clarity.

In any cases, at this point we don't officially support bazel-based build (as a build process of consumer application's build steps) yet, expect something might not work.

**Comment by alexeagle** [comment]
@roblg Bazel is descending into the `node_modules/rxjs` folder because you didn't tell it that it's a separate workspace.

Just add 
```
local_repository(name = "rxjs", path = "node_modules/rxjs/src")
```
to your `WORKSPACE` file, then these targets won't be picked up in your build unless  you use a label like `@rxjs//:some-label`

**Comment by roblg** [comment]
Thanks for the suggestion @alexeagle. I agree that that will work to fix this specific instance, but that doesn't really seem like a long-term solution. (I'd hate to have to randomly go add things to our WORKSPACE that happen to end up in node_modules during local development. What happens if we get a dependency conflict, and we end up with two copies in node_modules?). From our perspective, rxjs isn't a bazel dependency at all, it's just an npm package that we depend on (transitively) that happens to contain its `src/` folder, which has a BUILD file in it.

I'm not super familiar with this project (it's only a transitive dependency of... something. I'm not even sure what yet... 😬). Is there a reason that it ships `src/` in the published package? 

If `rxjs` needs to ship `src/BUILD`, we can work around it locally; just seems suboptimal...

**Comment by alexeagle** [comment]
I've discussed with @benlesh about switching rxjs off the package.json scripts and onto Bazel. I think as part of that, we should change the model for how Bazel users get rxjs - they should have a WORKSPACE dep on the rxjs source tree, not on the npm published package.

One problem is version skew - we don't have a good way for npm to fetch version 6.0.0 for example, while making sure that Bazel WORKSPACE doesn't fetch 6.0.1.

I need to find some time to use https://github.com/pubref/rules_node and understand it better, then maybe discuss with @pcj

**Comment by benlesh** [comment]
src/ is being used for source maps, I believe.
