### ISSUE TITLE
MS Edge fails with SCRIPT1028: Expected identifier, string or number

### ISSUE THREAD

**Issue by szellcsaba-ge** [ReactiveX/rxjs#3339]
**RxJS version:**
5.5.6

**Code to reproduce:**
N/A, we have a complicated build process, can't strip out the code to repro.
Angular5, webpack, Polymer, etc.

**Expected behavior:**
RxJS should work in MS Edge

**Actual behavior:**
SCRIPT1028: Expected identifier, string or number
App fails to render anything, blank page.

**Additional information:**
After a short investigation, the problem is on this line (marked with * the exact position):
```
const { request, request: { user, method, url, async*, password, headers, body } } = this;
```

This line is the part of the AjaxSubscriber class' send() method.

If I replace the 'async' variable names in the method for eg. 'asynch', everything starts to work without any problem.

**Comment by kwonoj** [comment]
With this issue without isolation in build steps, I have suspect this is related to your build configurations.

Specific code line you mentioned is simply transpiled down into like below: (CJS, umd both)

```
AjaxSubscriber.prototype.send = function () {
        var _a = this, request = _a.request, _b = _a.request, ..... async = _b.async, password = _b.password, headers = _b.headers, body = _b.body;
```

while having `var async = ${something}` isn't great practices, it doesn't have conflict to global scope async keyword at least afaik. 

If you can't strip out code, what happens if you import bare rx without involving anything in Edge? (no angular, no polymer, etcs)

**Comment by kwonoj** [comment]
Also may worth to check http://reactivex.io/rxjs/ (it loads umd build of Rx inside) on Edge to see global build fails with same transpiled results. (it did work on me).

**Comment by szellcsaba-ge** [comment]
The code looks like this:

```
class AjaxSubscriber extends __WEBPACK_IMPORTED_MODULE_4__Subscriber__["a" /* Subscriber */] {
    constructor(destination, request) {
        ....
    }
    next(e) {
        ....
    }
    send() {
        const { request, request: { user, method, url, asynch, password, headers, body } } = this;
```

**Comment by szellcsaba-ge** [comment]
Downgrading the transpile to es5 works around the problem.

**Comment by kwonoj** [comment]
I'm feeling it'd better to rename variable name in further eventually, for cases if we have runtime doesn't need any transpilation one day.

**Comment by sbradl** [comment]
Just run at this problem too. For me `fromPromise` causes this error.

**Comment by marsc** [comment]
Ran into this problem with Angular 8 and Edge. Same code piece as above.

**Comment by kwonoj** [comment]
Since old EDGE itself is deprecated, closing issue and recommend to use latest rxjs & support chromium based edge.
