### ISSUE TITLE
typesafe error handling

### ISSUE THREAD

**Issue by harunurhan** [ReactiveX/rxjs#3343]
It would be nice to support types for errors so that we have types`catch`, `catchError`, `onError` etc.

like `Observable<T, E>` and ideally type is inferred if any operator returns `ErrorObservable`.

**Comment by harunurhan** [comment]
I haven't checked up to what level it's possible but I can create a PR, if the feature is agreed to have.

**Comment by kwonoj** [comment]
There were some discussions around those, in general we won't going to expand generics for class `Observable` for errors at least for now.

**Comment by harunurhan** [comment]
@kwonoj I'd be very happy if you point me to the discussion or explain why.

**Comment by harunurhan** [comment]
I don't see why `<T, E = any>` would be a problem, maybe by the time you discussed TypeScript was lower than `v2.3` and you didn't want to introduce breaking changes or "ugly" workarounds.

https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-3.html

**Comment by kwonoj** [comment]
@harunurhan it's not `was`, it `is` - our stable branch still based on 2.0.x for compatibility issue.

**Comment by harunurhan** [comment]
@kwonoj ok, in that case I don't know if it could be done with backwards compatibility. I think we can still leave the issue here, because I couldn't find another issue related to this.

**Comment by benlesh** [comment]
The error typing here isn't really critical. This comes up from time to time, but we're not doing anything different than what TypeScript is doing with promises. It was decided that adding generic typing to the error channel would add even more complexity to our typings without any real valuable gain.
