### ISSUE TITLE
pipe overload doesn't fall back to default signature

### ISSUE THREAD

**Issue by kwonoj** [ReactiveX/rxjs#3346]
**RxJS version:**

**Code to reproduce:**

**Expected behavior:**

**Actual behavior:**

**Additional information:**
related with https://github.com/ReactiveX/rxjs/pull/3341 . We won't going to remove overloads but need to make fallback correctly.

**Comment by cartant** [comment]
@kwonoj This was fixed in #3292, but it has not been cherry picked into [stable](https://github.com/ReactiveX/rxjs/blob/stable/src/Observable.ts#L291-L302).

**Comment by kwonoj** [comment]
interesting, when I tried with master I still could see same thing. Will double check.

**Comment by benlesh** [comment]
@kwonoj what is the status of this one? Can it be closed?

**Comment by kwonoj** [comment]
need check on stable if it's fixed in 5.x.

**Comment by cartant** [comment]
This can be closed. It was fixed in #3549, but I didn't change the cherry-picked commit message to effect automatic closure.

**Comment by benlesh** [comment]
Thank you for reminding me, @cartant :)
