### ISSUE TITLE
zip operator does not work with array of observables.

### ISSUE THREAD

**Issue by pavan-nw** [ReactiveX/rxjs#3347]
```
const zip = require('rxjs/observable/zip').zip;
const of = require('rxjs/observable/of').of;
const from = require('rxjs/observable/from').from;
 
const obs = [];
  obs.push(of(3));
  obs.push(of(4));
  zip(obs).subscribe(v => console.log('===>', v)); // not working
 
// but

zip(
  of(3), 
  of(4)
).subscribe(v => console.log('===>', v)); // this works
```
zip does not take array.. is there any version of zip which addresses this use case.? please reply with example.

**Comment by kwonoj** [comment]
if you need to supply array, you could use rest operator. https://github.com/ReactiveX/rxjs/blob/c7e33e43224f8c2292335ecd9d933c3fbd5f9d74/spec/operators/zip-spec.ts#L604 zip itself doesn't expand array into observable values.
