### ISSUE TITLE
Subject doesn't inherit from Observable

### ISSUE THREAD

**Issue by wytrych** [ReactiveX/rxjs#3348]
**RxJS version:**
`5.5.6`

**Code to reproduce:**
```js
const Rx = require('rxjs');
typeof Rx.Subject.fromEventPattern
```
**Expected behavior:**
`"function"`

**Actual behavior:**
`"undefined"`

**Comment by kwonoj** [comment]
Subject inherits Observable and it's instance of Observable but it doesn't not provide static creation method for Observable. 

```
new Rx.Subject() instanceof Rx.Observable //this is true

Rx.Subject.xxxx //accessing static creation method for `Rx.Observable` is not possible
```

**Comment by wytrych** [comment]
@kwonoj 
Hmm, why then when I go to http://reactivex.io/ open then console I get:

<img width="517" alt="screen shot 2018-02-25 at 21 04 42" src="https://user-images.githubusercontent.com/10600101/36645880-8c18a600-1a6f-11e8-9e97-c4d272752d39.png">

**Comment by kwonoj** [comment]
🤔 I thought it was in that way all along, but maybe this was accidentally changed when organizing structure with pipable.

**Comment by wytrych** [comment]
Extending a class with `extend` will normally extend them to the subclass in both Javascript and TypeScript

**Comment by kwonoj** [comment]
@wytrych Rxjs doesn't no normal extend around static creation method due to several reasons.

**Comment by benlesh** [comment]
It's recommended that you use:

```ts
import { fromEventPattern } from 'rxjs/observable/fromEventPattern';  // v5.0+

import { fromEventPattern } from 'rxjs'; // v6.0+
```

And no, you can't really get a Subject from event pattern like this. :)

**Comment by benlesh** [comment]
Also, it's probably an artifact of how we're using TypeScript in the `rxjs/add/*` modules to add the function to `Observable`? I'm not sure. Either way, I'd recommend against using this pattern.

**Comment by kwonoj** [comment]
Yes, I'd object if to try static creation method in those way. I just thought this wasn't avail all time and curious what's been changed.
