### ISSUE TITLE
throttleTime does not emit last value

### ISSUE THREAD

**Issue by ronag** [ReactiveX/rxjs#3351]
`throttleTime` does not have a `_complete` handler which means that even if we specify `trailing: true` we might not get the last value of the stream.

Not sure if this is intentional, but it seems rather unintuitive. Also looking at the spec test the end of stream scenario isn't really defined so it's difficult to tell how it should work.

**Comment by dengwanc** [comment]
could you provide more details and reproductions steps ?

**Comment by deadbeef84** [comment]
```js
Observable.timer(1000)
  .throttleTime(500, undefined, { trailing: true })
  .subscribe(x => console.log('value', x), undefined, () => console.log('complete'))
// completes without value
```

I.e. if the source observable completes, the "current" throttled value will get lost.

**Comment by benlesh** [comment]
We need a reproduction please. :)

**Comment by yozo1984** [comment]
Unlike auditTime, I feel throttleTime is mostly used to limit the number of calls to a certain function or of emissions of values. With the current implementation, the last value can be lost if the observable completes before the throttle time is up.

I feel the last throttle value should be emitted right away in this case but can also be persuade that the we should wait until the throttleTime to emit.

e.g.
```js
const e1 =   hot('-a-xy-----b--x--cxx| ');
const e1subs =   '^                   !';
const t =   time('----|                ');
const expected = '-----y--------x-----(x|)';
```
