### ISSUE TITLE
at gh-pages, ./img/forkJoin.png not found

### ISSUE THREAD

**Issue by t-f-m** [ReactiveX/rxjs#3352]
See, 
http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#static-method-forkJoin
https://github.com/ReactiveX/rxjs/tree/gh-pages/img

**Comment by claudiordgz** [comment]
this seems simple enough for me to start, can I get this one?

**Comment by claudiordgz** [comment]
Is this supposed to be in this other repo? https://github.com/ReactiveX/rxjs-docs/issues

**Comment by claudiordgz** [comment]
I see it now, there is no forkJoin spec test on gh-pages, on it then

**Comment by claudiordgz** [comment]
Added a diagram generating test on #3377

**Comment by dengwanc** [comment]
I need this #3377 very well
