### ISSUE TITLE
New operator: switchTap

### ISSUE THREAD

**Issue by gagle** [ReactiveX/rxjs#3353]
I want to wait until an observable completes but  I want to ignore the result. Basically I want to execute an asynchronous operation inside a flow of observables but I don't want to replace the current value of the pipe, I just want to execute async operations and wait until they finish. `switchMap/mergeMap` will solve the problem but they also replace the current value. All I need is an asynchronous `tap`.

`of(1).pipe(switchMap(() => of(2))).subscribe(console.log); // expected: 1`

Proposal: switchTap

```
export function switchTap<T, R>(next: (x: T) => Observable<R>): MonoTypeOperatorFunction<T>;
export function switchTap<R>(observable: Observable<R>): MonoTypeOperatorFunction<R>;
export function switchTap<T, R>(
  arg: Observable<T> | ((x: T) => Observable<R>)
): MonoTypeOperatorFunction<T> {
  const next: (x: any) => Observable<T | R> =
    typeof arg === 'function' ? arg : (x: any): Observable<T> => arg;
  return switchMap<T, T>(value => next(value).pipe(ignoreElements(), concat(of(value))));
}
```

Usage:

`of(1).pipe(switchTap(of(2))).subscribe(console.log) // 1`

or with a function:

```
of(1)
      .pipe(
        switchTap(value => {
          console.log(value); // value: 1
          return of(value + 1);
        })
      )
      .subscribe(console.log); // 1
```

What do you think?

**Comment by kwonoj** [comment]
with introduction of pipeable operator, we do recommend to create custom operator on user level (https://github.com/ReactiveX/rxjs/blob/master/doc/operator-creation.md#publish-your-operator-as-a-separate-library) instead of adding it into core.
