### ISSUE TITLE
error TS2416: Property 'lift' in type 'Subject<T>' is not assignable to the same property in base type 'Observable<T>'.   Type '<R>(operator: Operator<T, R>) => Observable<T>' is not assignable to type '<R>(operator: Operator<T, R>) => Observable<R>'.     Type 'Observable<T>' is not assignable to type 'Observable<R>'.       Type 'T' is not assignable to type 'R'.

### ISSUE THREAD

**Issue by deep1219** [ReactiveX/rxjs#3355]
**RxJS version:**  "^5.5.6",

**Code to reproduce:**

**Expected behavior:**

**Actual behavior:**

**Additional information:**

**Comment by kwonoj** [comment]
There are distinct numbers of report around compilation error usually related to application code, while 5.5.6 have fixes library side code. as suggested in https://github.com/ReactiveX/rxjs/issues/3281#issuecomment-362032012, 

Please ensure
1. if there's any other duplicated dep have lower version
2. if there's extending / subclassing on user code

if both are not the case, it'd appreciate to provide reproducible repo, without ng / or ionic to isolate from library side behavior.

**Comment by kwonoj** [comment]
I'm tentatively closing issue as there's no information we can track this down further with this issue. Feel freely create new issue if you have isolated repro case as suggested above.

**Comment by sretepk** [comment]
I am having this issue using Visual Studio 2015:

Severity	Code	Description	
Error	TS2416	Property 'lift' in type 'Subject<T>' is not assignable to the same property in base type 'Observable<T>'.
  Type '<R>(operator: Operator<T, R>) => Observable<T>' is not assignable to type '<R>(operator: Operator<T, R>) => Observable<R>'.
    Type 'Observable<T>' is not assignable to type 'Observable<R>'.
      Type 'T' is not assignable to type 'R'.	TypeScript Virtual Projects

**Comment by AgitSoft** [comment]
update typescript it will helps you
