### ISSUE TITLE
Observable.of() and repeatWhen

### ISSUE THREAD

**Issue by eliaslecomte** [ReactiveX/rxjs#3378]
I am having unexpected behavior with Observable.of() and repeatWhen. I was wondering if this is correct behavior or not, and why?

**RxJS version:** 5

**Code to reproduce:**

const value = 5;
let variable = 0;

const getValue = () => {
    variable = variable + 1;
    return value * variable;
}

function test () {
    Observable.of(getValue())
        .repeatWhen(obs => obs.delay(1000))
        .subscribe(value => console.log(value);
}

**Expected behavior:**

Expected: 5 10 15 20 ...

**Actual behavior:**

Result: 5 5 5 5 ...

**Additional information:**

Apparently, the value returned by Observable.of() is reused for each subsequent subscribe. How, why?

**Comment by dengwanc** [comment]
`getValue()` called once, because JavaScript is __call by value__

**Comment by kwonoj** [comment]
`Observable.of()` is designed as one-off value so in here `Observable.of(getValue())....subscribe` is equilvalent to `Observable.of(5)...subscribe`, value when it get's evaluated.

**Comment by eliaslecomte** [comment]
Observable.defer is what I was looking for 👍.
