### ISSUE TITLE
pipe typings don't work with Array Destructuring

### ISSUE THREAD

**Issue by benneq** [ReactiveX/rxjs#3381]
**RxJS version:** 5.5.6

**Code to reproduce:**
```js
someObservable.pipe(
  map(val => ["foo", 42]),
  map(([str, num]) => null)
);
```

**Expected behavior:**
`str` should be detected as type `string` and `number` should be of type `number`

**Actual behavior:**
TypeScript says: `str` and `num` are both of type `string | number`

**Additional information:**
Tested with TypeScript 2.6.2 and 2.7.2

The exact same code works when used within `subscribe`:
```js
someObservable.pipe(
  map(val => ["foo", 42])
)
.subscribe(([str, num]) => console.log(str, num));
```

**Comment by felixfbecker** [comment]
This is not an RxJS issue - TS infers an array type for array literals, not a tuple. Anything else would be very annoying:
```ts
const a = ['a', 'b', 'c']
a.push('d')
a[3] // error if a is a 3-element tuple
```
You just need to tell TS the array is a tuple:
```ts
someObservable.pipe(
  map((val): [string, number] => ["foo", 42]),
  map(([str, num]) => null)
);
```

**Comment by benneq** [comment]
But why does it work within the `subscribe` method?

**Comment by benlesh** [comment]
@benneq This is because subscribe is able to infer types directly from the class it lives on, where `pipe` has to do some complicated type inference, that frankly is new and still a little broken. This isn't something we can fix on the RxJS side.

You'll need to add typings as @felixfbecker recommended.
