### ISSUE TITLE
Where is documentation for stable 5.0 ?

### ISSUE THREAD

**Issue by oliverjanik** [ReactiveX/rxjs#3393]
Documentation is such a mess for this project! There are zero hopes for any newbies picking up this library if there's no definitive source for documentation.

You guys are marching on with v6 which is alpha. Github points here: http://reactivex.io/rxjs/

That is definitely not v5. Is it v6?

Can you not have a version picker for your docs? Like this one? https://angular.io/docs

So many inconsistencies:
http://reactivex.io/rxjs/function/index.html#static-function-catchError

This callled catchError, but all examples are catch? 

Also are all the signatures dumbed down?

Documentation states:
```
public catchError(selector: function): Observable
```
My project which is on v5 has this:
```
export declare function _catch<T, R>(this: Observable<T>, selector: (err: any, caught: Observable<T>) => ObservableInput<R>): Observable<T | R>;
```

**Comment by kwonoj** [comment]
Yes, we are aware of inconsistency and sorry for the inconvenience. You may want to check https://github.com/ReactiveX/rxjs-docs for latest documentation update tracking and particularary https://github.com/ReactiveX/rxjs-docs/issues/162 for versioned documentation for resolving this specific issue.
