### ISSUE TITLE
catchError with `throw` degrades type inference to empty type, causing unsafe code

### ISSUE THREAD

**Issue by mprobst** [ReactiveX/rxjs#3395]
**RxJS version:** 6

**Code to reproduce:**

Consider this code that tries to convert an error thrown by an `Observable` into its own error class:

```typescript
class SomeClass {
  private x: number;
  someClassField: string;
}
class UnrelatedClass {
  private y: number;
  unrelatedField: string;
}

declare const obs: Observable<SomeClass>;
// Working as expected.
obs.pipe(map(v => v.someClassField));
// Broken!
obs.pipe(
    catchError(e => {
      throw new Error(e);
    }),
    // Ouch, v cannot be of type UnrelatedClass here, should be SomeClass!
    map((v: UnrelatedClass) => 1));
```

The problem here is in the signature of `catchError`. Because the error handling function given doesn't return any value, its return type is inferred as `never`. `catchError` is defined as:

```typescript
function catchError<T, R>(
    selector: (err: any, caught: Observable<T>) =>
        Observable<R>): OperatorFunction<T, T|R>;
```

So if you pass in a `selector` that's `(e: any) => never`, you end up with `R` being inferred as `{}` (the empty type), because there is no return. That in turn leads to the `pipe` chain degrading to `{}`. And now because in TypeScript callbacks are bivariant, that means users can pass any arbitrary type in place of the `v` passed down, e.g. `UnrelatedClass` above.

**Expected behavior:**

Should give a compile error that `v` is not of type `UnrelatedClass`.

**Actual behavior:**

Code is silently accepted, generic types are a lie, fails at runtime and is super confusing for newer users.

**Comment by mprobst** [comment]
I was going to suggest adding an overload to `catchError` like so:

```
function catchError<T>(
    selector: (err: any, caught: Observable<T>) =>
        never): OperatorFunction<T, T>;
```

That'll make sure that if `selector` never returns a value, we don't end up with an `Observable<{} | T>` as the result, but just an `Observable<T>`. That's an improvement because it fixes the type inference decision here, so that we know the result above is an `Observable<SomeClass>`.

However testing this out, it turns out there's another more fundamental problem: because TypeScript considers callback functions bivariant, we can specify any type we want in the `map` function, and TS will accept it silent. That's independent of `catchError`:

```
declare const obs2: Observable<SomeClass>;
obs.pipe(
  map(v => v.someClassField),
  // v must be string here, but bivariance ruins the day :-(
  map((v: UnrelatedClass) => v.unrelatedField));
```


I've created a [playground for this here](https://www.typescriptlang.org/play/#src=export%20type%20UnaryFunction%3CT%2C%20R%3E%20%3D%20(source%3A%20T)%20%3D%3E%20R%3B%0D%0Aexport%20type%20OperatorFunction%3CT%2C%20R%3E%20%3D%0D%0A%20%20%20%20UnaryFunction%3CObservable%3CT%3E%2C%20Observable%3CR%3E%3E%3B%0D%0A%0D%0Adeclare%20class%20Observable%3CT%3E%20%7B%0D%0A%20%20pipe%3CA%3E(op1%3A%20OperatorFunction%3CT%2C%20A%3E)%3A%20Observable%3CA%3E%3B%0D%0A%20%20pipe%3CA%2C%20B%3E(op1%3A%20OperatorFunction%3CT%2C%20A%3E%2C%20op2%3A%20OperatorFunction%3CA%2C%20B%3E)%3A%0D%0A%20%20%20%20%20%20Observable%3CB%3E%3B%0D%0A%7D%0D%0A%0D%0A%2F%2F%20declare%20function%20catchError%3CT%3E(%0D%0A%2F%2F%20%20%20%20%20selector%3A%20(err%3A%20any%2C%20caught%3A%20Observable%3CT%3E)%20%3D%3E%0D%0A%2F%2F%20%20%20%20%20%20%20%20%20never)%3A%20OperatorFunction%3CT%2C%20T%3E%3B%0D%0Adeclare%20function%20catchError%3CT%2C%20R%3E(%0D%0A%20%20%20%20selector%3A%20(err%3A%20any%2C%20caught%3A%20Observable%3CT%3E)%20%3D%3E%0D%0A%20%20%20%20%20%20%20%20Observable%3CR%3E)%3A%20OperatorFunction%3CT%2C%20T%7CR%3E%3B%0D%0A%0D%0Adeclare%20function%20map%3CT%2C%20R%3E(%0D%0A%20%20%20%20project%3A%20(value%3A%20T%2C%20index%3A%20number)%20%3D%3E%20R%2C%0D%0A%20%20%20%20thisArg%3F%3A%20any)%3A%20OperatorFunction%3CT%2C%20R%3E%3B%0D%0A%0D%0A%2F%2F%20User%20code%20follows.%0D%0A%0D%0Aclass%20SomeClass%20%7B%0D%0A%20%20private%20x%3A%20number%20%3D%201%3B%0D%0A%20%20someClassField%3A%20string%20%3D%20'a'%3B%0D%0A%7D%0D%0Aclass%20UnrelatedClass%20%7B%0D%0A%20%20private%20y%3A%20number%20%3D%202%3B%0D%0A%20%20unrelatedField%3A%20string%20%3D%20'b'%3B%0D%0A%7D%0D%0A%0D%0Aconst%20fn%20%3D%20catchError((e%3A%20any)%20%3D%3E%20%7B%0D%0A%20%20throw%20new%20Error(e)%3B%0D%0A%7D)%3B%0D%0A%0D%0Adeclare%20const%20obs%3A%20Observable%3CSomeClass%3E%3B%0D%0A%2F%2F%20Working%20as%20expected.%0D%0Aobs.pipe(map(v%20%3D%3E%20v.someClassField))%3B%0D%0A%0D%0Aconst%20v%20%3D%20obs.pipe(catchError(function%20named(e%3A%20any)%20%7B%0D%0A%20%20throw%20new%20Error(e)%3B%0D%0A%7D))%3B%0D%0Av.pipe(map((x%3A%20UnrelatedClass)%20%3D%3E%201))%3B%0D%0A%0D%0Aobs.pipe(%0D%0A%20%20%20%20catchError(function%20named(e%3A%20any)%20%7B%0D%0A%20%20%20%20%20%20throw%20new%20Error(e)%3B%0D%0A%20%20%20%20%7D)%2C%0D%0A%20%20%20%20%2F%2F%20Ouch%2C%20v%20should%20not%20be%20of%20type%20UnrelatedClass%20here!%0D%0A%20%20%20%20map((v%3A%20UnrelatedClass)%20%3D%3E%20v.unrelatedField))%3B%0D%0A), to make it a bit easier to throw around ideas.

**Comment by benlesh** [comment]
It seems this is more of an issue with TypeScript and type inference within the `pipe` method. Currently, you can type things however you want inside of `pipe` and TypeScript seems to let you do it. I'm not sure there's anything we can do on the RxJS side.

**Comment by benlesh** [comment]
I'm labelling this but leaving it open. I don't think we can fix it, but I want to track it.

**Comment by benlesh** [comment]
Okay, after more thought, I'm going to close this one. The reason you get a loss of type safety here is because the function doesn't return anything TypeScript can infer a type from. This isn't anything rxjs can fix.
