### ISSUE TITLE
RxJS infrastructure

### ISSUE THREAD

**Issue by dengwanc** [ReactiveX/rxjs#3396]
IS there any introduce about rxjs infrastructure ? (OR I just missed something 😄)

* From code perspective and project module mostly
* I want to contribute this project quickly
* I LOVE RxJS

BTW (I have solved some issue if you are noticed) 

@benlesh

**Comment by kwonoj** [comment]
There is no specific documents around, mostly source code itself / docs in repo serves for those purpose.
