### ISSUE TITLE
About versions in this repository

### ISSUE THREAD

**Issue by chinesedfan** [ReactiveX/rxjs#3397]
>- master - commits that will be included in the next major release (breaking changes)
> - next - commits that will be included in the next minor or patch release

> Most PRs should be made to master, unless you know it is a breaking change.

Should it be `unless you know it is ** NOT ** a breaking change.`?

**Comment by kwonoj** [comment]
I think those are slight outdated, currently master points v6, stable is for v5.x. (next is unused anymore)
