### ISSUE TITLE
Where is the do operator?

### ISSUE THREAD

**Issue by RavenHursT** [ReactiveX/rxjs#3399]
This is in the RxJS docs: https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/do.md

But I see no operator to be imported here? https://github.com/ReactiveX/rxjs/tree/master/src/internal/operators

**Comment by berlysia** [comment]
dupe? #3010 #3068

Describe with v6 compatible links:
- `do` operator has been renamed [`tap`](https://github.com/ReactiveX/rxjs/blob/6319f3c5be315de65db50db371486515afabae64/src/internal/operators/tap.ts).
- Renamed operators are listed in [Pipeable Operators](https://github.com/ReactiveX/rxjs/blob/master/doc/pipeable-operators.md#pipeable-operators)

**Comment by RavenHursT** [comment]
![image](https://user-images.githubusercontent.com/496983/37108437-b3a2c9dc-21fc-11e8-868b-655d5e2843c5.png)
@berlysia
