### ISSUE TITLE
Can you include tap method in Rxjs API doc?

### ISSUE THREAD

**Issue by SLYJason** [ReactiveX/rxjs#3419]
https://github.com/ReactiveX/rxjs/blob/24854cf66172f91f55729765c4d64e61607563c8/src/operators/tap.ts#L14

**Comment by benlesh** [comment]
We're working on it. The docs generation is in a bit of flux right now, but we're going to have an all-new (and MUCH improved docs site soon). I'm terribly sorry for the poor quality of the docs up to this point.
