### ISSUE TITLE
Can't use patching from rxjs/create

### ISSUE THREAD

**Issue by olegdunkan** [ReactiveX/rxjs#3435]
**RxJS version:**
rxjs@6.0.0-alpha.4

> To import only what you need by patching (this is useful for size-sensitive bundling):  
``` 
import { from, of, range } from 'rxjs/create';
```

when I installed `npm i rxjs@alpha` I get no files to import  rxjs/create (no index.d.ts or any other )

**Comment by benlesh** [comment]
It was moved to just `rxjs` in alpha.3 [see notes here](https://github.com/ReactiveX/rxjs/blob/master/CHANGELOG.md#breaking-changes-1)

:)
