### ISSUE TITLE
Notification `create` methods could return consts in some cases

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#346]
In #206, @abersnaze pointed out that we could save on object allocations in `materialize` and `dematerialize` (as well as our TestScheduler) by returning the same references, or perhaps tokens of some sort (to further reduce object allocations), for common return values like `Notification.createComplete()` and `Notification.createNext(null)`, etc.

**Comment by kwonoj** [comment]
Interested in creating PR for this - which way would be feasible? Initial thought I could think some ways like
- create `NotificationLite` class as similar to RxJava does have
- allow additional parameter into existing interface like `createComplete(getStaticReference?:boolean)` to return specific object reference
- let existing interface automatically returns by value, i.e `createNext(value) { if (!value) { return existingReference }....}`

Or possibly other, better way. Any suggestion would be appreciated.

**Comment by blesh** [comment]
I think our current implementation is already pretty "lite"... but we can probably just use a static reference for all `complete` notifications, as well as `undefined` value notifications.

**Comment by kwonoj** [comment]
Got it, will try to create to return static reference per specific cases as similar to 3rd way's pseudo does.
