### ISSUE TITLE
Add concurrency parameter to switch and switchMap

### ISSUE THREAD

**Issue by benlesh** [ReactiveX/rxjs#347]
Carried over from #215.

The idea is that you could then switch between more than one of the most recently emitted observables.

I think the usefulness of this in comparison to potential performance degradation is dubious, but it's worth trying and comparing numbers, since it should be a non-breaking change.

**Comment by staltz** [comment]
Is this issue done?

**Comment by blesh** [comment]
I don't believe so.

**Comment by trxcllnt** [comment]
@blesh isn't this just the difference between popping off the end of the pending queue instead of shifting? Though since this is `switchMap` we're talking about, we can implement this as a ring buffer instead of an unbounded Array.

**Comment by blesh** [comment]
Closing this issue as stale.

**Comment by d3lm** [comment]
I'd like to bump this issue as I think that there are use cases where a concurrency parameter is very useful for `switchMap`. We already have such parameter for `mergeMap` and it would be great to have the same for `switchMap`. I have implemented `switchMapWithConcurrency` as a lettable operator. Maybe this can help.

```
function switchMapWithConcurrency<T>(project: (value) => Observable<T>, concurrent = 1) {
  const subscriptions: Array<Subscription> = [];

  return (source: Observable<any>): Observable<T> => {
    return Observable.create((observer: Observer<T>) => {
      const subscription = source.subscribe((sourceValue) => {
        if (subscriptions.length >= concurrent) {
          let lastSubscription = subscriptions.shift();
          lastSubscription.unsubscribe();
        }

        let innerSubscription = project(sourceValue).subscribe(innerValue => observer.next(innerValue));
        subscription.add(innerSubscription);
        subscriptions.push(innerSubscription);
      });

      return subscription;
    });
  }
}
```

This can either be used with `.let` or within `.pipe`. Here's a working demo on [JSBin](https://jsbin.com/qubufuhobu/1/edit).

**Comment by benlesh** [comment]
Yeah... I think this feature has merit... it's just that:

1. It's a low priority
2. `switchMap` is a very hot-path operator, so whatever we do would have to have minimal impact on both the perf and the size of the operator.

**Comment by BioPhoton** [comment]
Hi @benlesh 

> 2. switchMap is a very hot-path operator, so whatever we do would have to have minimal impact on both the perf and the size of the operator.

As 2 got even more important (usage of RxJS exploded) and the last activity on this issue was more than 2 years ago I believe it could be closed.

Please let me know your opinion.

**Comment by benlesh** [comment]
Yeah. It's gone stale again. It's apparently not a feature people are hot to get.
