### ISSUE TITLE
Proposal: instanceOf operator

### ISSUE THREAD

**Issue by jayoungers** [ReactiveX/rxjs#3473]
I've run into several situations where it would be nice to have an 'instanceOf' like operator (as have others it looks like: #2340, #3125).

I think it could be done relatively easily by adding something like this to src/internal/operators/filter.ts:

```
export function instanceOf<T, S extends T>(type: { new(...args: any[]): S }): OperatorFunction<T, S> {
  return function filterOperatorFunction(source: Observable<T>): Observable<S> {
    return source.lift(new FilterOperator(val => val instanceof type));
  };
}
```

If it belongs in a separate file I think you'd just need to expose the `filter` internals (or duplicate).

With it you can then do:

```
this.router.events.pipe(
  instanceOf(NavigationEnd),
  tap((e) => /* e is typed as NavigationEnd */)
);
```

It may make sense to allow for multiple types (`instanceOf(NavigationStart, NavigationEnd)`), but I'm not 100% sure what the signature would look like

**Comment by kwonoj** [comment]
As introduction of pipeable operator we do recommend custom operator in user level. If you think this should be included in core operator, fell freely reopen / create new issue includes examples can't be achieved via user level custom operator.

**Comment by jayoungers** [comment]
Fair enough.  I've copied the code from filter.ts to create the full operator in a gist for anyone else who stumbles upon this:

https://gist.github.com/jayoungers/63bf0bce77d28e448a41f5bb4c531264
