### ISSUE TITLE
Sourcemaps in v6

### ISSUE THREAD

**Issue by Delagen** [ReactiveX/rxjs#3479]
**RxJS version:** 6.0.0-beta.3

**Code to reproduce:** any webpack bundle

**Expected behavior:** no warnings

**Actual behavior:**
multiple warnings such as
(Emitted value instead of an instance of Error) Cannot find source file '../../../../../src/internal/observable/dom/WebSocketSubject.ts': Error: Can't resolve '../../../../../src/internal/observable/dom/WebSocketSubject.ts'

**Additional information:**
I think need to enable `inlineSources` in tsconfig.json

**Comment by benlesh** [comment]
cc @jasonaden
