### ISSUE TITLE
rxjs-compat missing 'toPromise' operator

### ISSUE THREAD

**Issue by Enngage** [ReactiveX/rxjs#3482]
Hi!

I'm depending on a library that imports `toPromise` operator like:

```javascript
import { toPromise } from 'rxjs/operators/toPromise';
```

Looking at the compatibility package, I didn't find such operator under:

`node_modules\rxjs\operators`
`node_modules\rxjs-compat\operators`

Is there any workaround I can use or was this operator forgotten?

Thank you!

**Comment by daiki-ojima** [comment]
The pipeable toPromise operator seems to be deleted with #2868.

It's on the Observable object by default.
```
Observable.of('foo').toPromise(); // this
Observable.of('foo').pipe(toPromise()); // not this
```

**Comment by daikiojm** [comment]
@Enngage 

The pipeable toPromise operator seems to be deleted with #2868. 

It's on the Observable object by default. 
``` Observable.of('foo').toPromise(); // this
Observable.of('foo').pipe(toPromise()); // not this
```

**Comment by Enngage** [comment]
Yeah, I think thats fine. The main problem is that its not present in the compatibility support which means that if this is used in 3rd party library that haven't moved to rxjs 6, we will have to manually fix these issues.

**Comment by benlesh** [comment]
`toPromise` was only available in `rxjs/operators` during a beta of `5.5`. It was removed because it doesn't make any sense, it's not an operator, it's a method of subscription that results in a promise.

What library is it you're depending on?

**Comment by Enngage** [comment]
Ah, I see. Its the [Covalent ](https://github.com/Teradata/covalent/issues/1133)for Angular. I raised an issue with them and they will be updating library quite soon. Workaround is quite easy, so we will go with that one for now. Thank you for getting back to me!

**Comment by benlesh** [comment]
No problem. Have them reach out to me if they're having a hard time updating.

**Comment by QuentinRoy** [comment]
Going back on this issue, what is the recommended way to update code relying on `toPromise` while dropping the compatibility layer?
