### ISSUE TITLE
Add micro perf tests for existing operators

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#350]
From #100 

- [x] buffer (buffer(obs))
- [ ] bufferTime (bufferWithTime)
- [ ] bufferToggle (buffer(obs, fn))
- [ ] bufferWhen (buffer(fn))
- [ ] delay
- [x] forkJoin
- [x] mapTo (map(obj))
- [ ] multicast
- [ ] publish
- [x] retry
- [ ] retryWhen
- [x] skipUntil
- [ ] subscribeOn
- [ ] switchMap
- [ ] takeUntil
- [x] toPromise
- [ ] window (window(obs))
- [ ] windowTime (windowWithTime)
- [ ] windowToggle (window(obs, fn))
- [ ] windowWhen (window(fn))
- [ ] withLatestFrom
- [ ] zipAll

**Comment by mattpodwysocki** [comment]
@blesh maybe I'm naive here, but why is `mapTo` required when `map` for example in RxJS supports wrapping objects that are passed in.

**Comment by blesh** [comment]
> @blesh maybe I'm naive here, but why is mapTo required when map for example in RxJS supports wrapping objects that are passed in.

reducing type checking in a really, really commonly used operator as well as making it less polymorphic.

**Comment by blesh** [comment]
I think for the most part we have the metrics we need here. Anything missing can be added ad hoc. Closing this issue.
