### ISSUE TITLE
Merged observables not showing properly in html

### ISSUE THREAD

**Issue by rbrand21** [ReactiveX/rxjs#3507]
**RxJS version:**
5.5.8

**Code to reproduce:**
*.ts:
```ts
    let temp_observable2: Observable<any[]>;
    let temp_observable3: Observable<any[]>;

    //Firestore collection with one document that contains one attribute:date
    temp_observable2 =
      this.db.collection(
        'testing_merge/'
      ).valueChanges()

    //Firestore collection with one document that contains one attribute:date
    temp_observable3 =
      this.db.collection(
        'testing_merge_2/'
      ).valueChanges()
    
    this.eventObservables = Observable.merge(temp_observable3, temp_observable2)
    this.eventObservables.subscribe(items =>{
      for(let item of items){
        console.log(item.date)
      }
    })
```

*.html:
```html
<ion-content>
  <ion-list>
    <ion-item *ngFor="let event of eventObservables | async">
      <h1>static text</h1>
      <h1>{{event.date}}</h1>
    </ion-item>
  </ion-list>
</ion-content>
```
**Expected behavior:**
Expect that the html has the same two dates printed that the console.log statement printed.

**Actual behavior:**
The html view only gets output of one of the merged observables (whichever was last in the list of merging). Meanwhile the subscribe call with the console.log has expected behavior and prints out both dates.

**Additional information:**

**Comment by benlesh** [comment]
If the console log is logging as expected, RxJS is doing what you'd expect. You're going to want to file this against Angular or Firebase. My gut tells me, though, that this has something to do with the Observables returned by Firebase. If you add a `shareReplay(1)` to those temp_observables, it might wor
