### ISSUE TITLE
Additional rx* prefixed exports

### ISSUE THREAD

**Issue by bisubus** [ReactiveX/rxjs#3508]
Currently pipeable operator and observable creation exports lack a namespace and pollute a module where they are used with very succinct names that can collide with other imports and user variables.

The suggestion is to provide *additional set* of prefixed exports to the package. They won't provide breaking changes, won't significantly increase package footprint (especially if tree-shaking is in use) and won't increase output size (especially if minification is in use).

There are several important concerns that could be addressed this way. They primarily apply to observable methods/factories and operators, but other exports are affected, too (`Symbol`, `Observable`):

* Increasingly complex API. Due to collisions between reserved words and package exports, same things have been available under different names (weird `tap`->`do`->`tap` change).

* Ambiguity leads to a lack of context. In a module that is dedicated to observables, it's easy to spot that RxJS is in use and follow which variable names belong to RxJS API and which are not. In most real-life scripts, it becomes significantly harder to read and develop RxJS code without constantly checking import list or IDE hints; also results in name collisions.

* Name collisions. The burden of resolving naming conflicts in imports is placed on a developer. It's easy to unintentionally mix them up or end up with inconsistent naming.
    * Observable factories vs. operators (`merge`, `zip`, etc.)
    * Observable factories and operators vs. other FP APIs like Lodash and ponyfill imports (`every`, `find`,  `debounce`... plenty of them).
    * vs. globals (principally `window`, `Symbol`, potentially `Observable`)
    * vs. common user variables (`count`, `pipe`, `delay`, etc.)
    *  `never` operator vs. TypeScript `never` (doesn't affect anything, just confusing)

* Auto-imports. Export names are ambiguous, they should be picked by hand on IDE auto-import, and it's impossible for IDE to provide auto-imports automatically (for a piece of code that is pasted).

* Single `rxjs` entry point. No confusing variety of imports like `rxjs/operators` (a potential cause for a [known issue](https://github.com/ReactiveX/rxjs/blob/master/doc/pipeable-operators.md#known-issues)).

All of these concerns can be addressed by adding prefixes to exports:

* Operators: `zip` -> `rxZip`, `catchError` -> `rxCatch` (canonical names can be used for operators that collide with reserved words)
* Observable factories : `zip` -> `rxCreateZip`/`rxStaticZip`/???
* Others: `Symbol` -> `RxSymbol`

**Comment by roblav96** [comment]
@bisubus Couldn't agree more. This lib is already an organizational deterrent :/

**Comment by benlesh** [comment]
Please use the template provided when submitting the issue. I'm not sure what version you're talking about.

> Observable factories vs. operators (merge, zip, etc.)

The operator versions of these are being removed.

> never operator vs. TypeScript never

This is only a concern for TypeScript users, but I see your point, probably worth a separate issue, along with `of` and `observableOf` etc.

> prefixing things with `rx`... 

You can all do that on your own if you which

```ts
import { zip as rxZip } from 'rxjs'

// or even

import * as rx from 'rxjs/operators';

// use rx.map, rx.zip etc. My understanding is that modern tree shakers will pick this up.
```

I'm going to close this one for now.

**Comment by bisubus** [comment]
@benlesh I didn't use issue template because this is proposal/feature request, not bug report. It affects current RxJS version, 6.0.0-rc.0. I can add a template if it's the only problem.

> The operator versions of these are being removed.

It's good to know, but the rest of the points are applicable:

> The burden of resolving naming conflicts in imports is placed on a developer.

> Auto-imports. Export names are ambiguous, they should be picked by hand on IDE auto-import

**Comment by roblav96** [comment]
@bisubus Do something like this:
```typescript
import * as ops from 'rxjs/operator'
```
