### ISSUE TITLE
`observableOf` and `observableFrom` instead of `of` and `from`

### ISSUE THREAD

**Issue by benlesh** [ReactiveX/rxjs#3514]
### Issues

- People have strong feelings
- IDEs like to color `of` in error
- People that aren't used to RxJS don't know what `of(1, 2, 3)` means

### Proposal

Rename `of` and `from` to `observableOf` and `observableFrom`.

**Pros**

- It's less ambiguous and more explicit what code is doing
- IDEs are happier about it
- can make the change gradually without breaking everyone with an alias and a deprecation

**Cons**
- It's WAY more verbose and makes code a bit more annoying to read.
- It's another change to the library.
- Most people using RxJS a lot in their apps know what `of` and `from` mean

### Other thoughts

- People can already to this with import aliases. `import { of as observableOf } from 'rxjs'; and the five extra characters there probably isn't going to kill them.
- It might actually encourage the use of Arrays as return values (which is totally fine) inside of `mergeMap` et al:  `source$.pipe(mergeMap(() => of(1, 2, 3)))` is the same as `source$.pipe(mergeMap(() => [1, 2, 3]))`. The readability of this versus `of` is debatable.
- `observableFrom` is probably the more annoying of the two changes, as it would be used more often to convert a promise ahead of other operators inside of flattening operators.

**Comment by kwonoj** [comment]
I'm indifferent with this one, but *if we'are going to rename* `of`, I'd vote to go for `just` instead - which most of Rx bindings (including .net's) are using but RxJS is different one. It'll allow alignment between other bindings, instead of making name verbose like `observableOf`.

**Comment by c69** [comment]
On our project, we already rename all such imports, e.g `import { of as observableOf } from ...`.

**Comment by alex-okrushko** [comment]
The following works without any drawbacks:
```typescript
import * as observable from 'rxjs';

observable.of(foo)
```

**Comment by morlay** [comment]
we renamed all observables and operators 😅 

![image](https://user-images.githubusercontent.com/1667873/39237700-d3763ce8-48ae-11e8-9927-d8158f1e2b51.png)

```
utils/
  rxjs/
    __tests__/
      generator.spec.ts
    index.ts
```
and automated generated by typescript

```ts
// generator.spec.ts

import * as fs from "fs";
import { upperFirst } from "lodash";
import * as path from "path";
import * as ts from "typescript";

const rxRenamer: ts.TransformerFactory<ts.SourceFile> = (context: ts.TransformationContext) => {
  const visitor: ts.Visitor = (node) => {
    if (node.kind === ts.SyntaxKind.ExportDeclaration) {
      const exportDeclaration = node as ts.ExportDeclaration;
      const moduleSpecifier = exportDeclaration.moduleSpecifier as ts.StringLiteral;
      const importPath = moduleSpecifier.text;

      const isStaticObservable = importPath.indexOf("internal/observable") > -1;

      let exportClause = undefined;

      if (exportDeclaration.exportClause) {
        const elements = [] as ts.ExportSpecifier[];
        exportDeclaration.exportClause.elements.forEach((element: ts.ExportSpecifier) => {
          let nextExportSpecifier = element;
          if (isStaticObservable && upperFirst(element.name.text) !== element.name.text) {
            const id = ts.createIdentifier(element.name.text);
            const alias = ts.createIdentifier(`observable${upperFirst(element.name.text)}`);
            nextExportSpecifier = ts.createExportSpecifier(id, alias);
          }
          elements.push(nextExportSpecifier);
        });
        exportClause = ts.createNamedExports(elements);
      }

      return ts.createExportDeclaration(
        undefined,
        undefined,
        exportClause,
        ts.createLiteral(moduleSpecifier.text.replace("./", "rxjs/")),
      );
    }
    return ts.visitEachChild(node, visitor, context);
  };

  return (node) => ts.visitNode(node, visitor);
};

const rxOperatorRenamer: ts.TransformerFactory<ts.SourceFile> = (context: ts.TransformationContext) => {
  const visitor: ts.Visitor = (node) => {
    if (node.kind === ts.SyntaxKind.ExportDeclaration) {
      const exportDeclaration = node as ts.ExportDeclaration;
      const moduleSpecifier = exportDeclaration.moduleSpecifier as ts.StringLiteral;

      let exportClause = undefined;

      if (exportDeclaration.exportClause) {
        const elements = [] as ts.ExportSpecifier[];
        exportDeclaration.exportClause.elements.forEach((element: ts.ExportSpecifier) => {
          let propertyName = element.propertyName;
          if (!propertyName) {
            propertyName = ts.createIdentifier(element.name.text);
          }
          const alias = ts.createIdentifier(`rx${upperFirst(element.name.text)}`);
          elements.push(ts.createExportSpecifier(propertyName, alias));
        });
        exportClause = ts.createNamedExports(elements);
      }

      return ts.createExportDeclaration(
        undefined,
        undefined,
        exportClause,
        ts.createLiteral(moduleSpecifier.text.replace(/\.+\//, "rxjs/")),
      );
    }
    return ts.visitEachChild(node, visitor, context);
  };

  return (node) => ts.visitNode(node, visitor);
};

const transform = (content: string, ...transformers: Array<ts.TransformerFactory<ts.SourceFile>>) => {
  return ts.transpileModule(content, {
    compilerOptions: {
      module: ts.ModuleKind.ESNext,
    },
    transformers: {
      before: transformers,
    },
  }).outputText;
};

describe("generate", () => {
  it("#rxjs", () => {
    const rxContent = String(fs.readFileSync(require.resolve("rxjs").replace("index.js", "index.d.ts")));
    const rxOperatorContent = String(
      fs.readFileSync(require.resolve("rxjs/operators").replace("index.js", "index.d.ts")));

    fs.writeFileSync(path.join(__dirname, "../index.ts"), `
${transform(rxContent, rxRenamer)}
${transform(rxOperatorContent, rxOperatorRenamer)}
`);
  });
});
```

**Comment by Airblader** [comment]
@alex-okrushko Importing like that will prevent tree-shaking, AFAIK. Also it requires you to prefix everything, not just the two functions in question.

**Comment by alex-okrushko** [comment]
@Airblader to take the guessing out of the equation here are the results:

```ts
import { Component, Input } from '@angular/core';
import * as observable from 'rxjs';
import {take} from 'rxjs/operators';

@Component({
  selector: 'hello',
  template: `<h1>Inteval at {{interval | async}}!</h1>`,
  styles: [`h1 { font-family: Lato; }`]
})
export class HelloComponent  {
  interval = observable.interval(1000).pipe(take(10));
}
```
*Before* I added the `take` operator and `interval` here how it looked after
`ng build --prod --build-optimizer --source-map --eval-source-map`

<img width="1429" alt="screen shot 2018-05-09 at 12 28 39 pm" src="https://user-images.githubusercontent.com/2830407/39827128-fb6e77c0-5384-11e8-9a12-5e08c898fe30.png">

There are some operators, but those are using by Angular itself.

Here is after I added interval to the above mentioned Component:

![interval](https://user-images.githubusercontent.com/2830407/39827254-6b089836-5385-11e8-9f19-55cd39b30490.png)

As you can see even though `import * as observable from 'rxjs';` was used only `interval` appeared in the optimized code.

I think this should resolve it.

**Comment by Airblader** [comment]
> I think this should resolve it.

Certainly, thanks :-) I do have more questions about it, but that's a bit off topic here. I'll research it on my own.

**Comment by r3h0** [comment]
If you decide to rename `of` and `from` because of naming collisions with TypeScript keywords, please also consider doing the same with `never`, which you mentioned in [this issue](https://github.com/ReactiveX/rxjs/issues/3508#issuecomment-377817127).

**Comment by benlesh** [comment]
@r3h0. `NEVER` is a constant now, differing from TypeScript `never` in case.

**Comment by ajcrites** [comment]
I am personally in favor of not removing operators (unless there is a collision), so I wouldn't want the rename. Doing `import * as rx` or `import { of as rxOf }` and the like are simple and acceptable alternatives that will keep the existing library more backwards compatible.

**Comment by shexrawa** [comment]
> @Airblader to take the guessing out of the equation here are the results:
> 
> ```ts
> import { Component, Input } from '@angular/core';
> import * as observable from 'rxjs';
> import {take} from 'rxjs/operators';
> 
> @Component({
>   selector: 'hello',
>   template: `<h1>Inteval at {{interval | async}}!</h1>`,
>   styles: [`h1 { font-family: Lato; }`]
> })
> export class HelloComponent  {
>   interval = observable.interval(1000).pipe(take(10));
> }
> ```
> 
> _Before_ I added the `take` operator and `interval` here how it looked after
> `ng build --prod --build-optimizer --source-map --eval-source-map`
> 
> <img alt="screen shot 2018-05-09 at 12 28 39 pm" width="1429" src="https://user-images.githubusercontent.com/2830407/39827128-fb6e77c0-5384-11e8-9a12-5e08c898fe30.png">
> 
> There are some operators, but those are using by Angular itself.
> 
> Here is after I added interval to the above mentioned Component:
> 
> ![interval](https://user-images.githubusercontent.com/2830407/39827254-6b089836-5385-11e8-9f19-55cd39b30490.png)
> 
> As you can see even though `import * as observable from 'rxjs';` was used only `interval` appeared in the optimized code.
> 
> I think this should resolve it.
