### ISSUE TITLE
Add micro perf tests for creation methods

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#352]
From #100 

- [x] fromEvent
- [x] fromEventPattern
- [x] fromPromise
- [x] interval
- [x] timer
- [x] zip

**Comment by kwonoj** [comment]
- `never` is covered at https://github.com/ReactiveX/RxJS/pull/342 though it might need some investigation separately?

- isn't `just/value` is deprecated and `of` covers it instead?

**Comment by blesh** [comment]
@kwonoj you're correct. That was a copy-pasta mistake. Edited.

**Comment by kwonoj** [comment]
`fromPromise` also seems covered via https://github.com/ReactiveX/RxJS/pull/303

**Comment by blesh** [comment]
Looks like we can close this... thanks for all the hard work @kwonoj!
