### ISSUE TITLE
Docs on Observable methods are all duplicated

### ISSUE THREAD

**Issue by LiandriCorp** [ReactiveX/rxjs#3526]
Not a standard bug, but I couldn't find anywhere else to inform you.

Currently on the website I'm seeing ~~all~~ many methods for http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html listed twice. This makes the page huuuuuge. In the table as well as the detailed description.
![screen shot 2018-04-05 at 08 29 54](https://user-images.githubusercontent.com/2708556/38375667-986e1aa2-38ab-11e8-9323-e66680e44e00.png)
![screen shot 2018-04-05 at 08 30 06](https://user-images.githubusercontent.com/2708556/38375669-98848e86-38ab-11e8-95ce-4f3184de0dd9.png)

**Comment by benlesh** [comment]
Yeah. The document generation is in horrible shape. We're working on making our documention better. This is a known problem.

**Comment by enzupmeditab** [comment]
Its been a year and the issue still persists.

> Yeah. The document generation is in horrible shape. We're working on making our documention better. This is a known problem.

I recommend using distinct(), distinctUntilChanged() while generating the document  :p

**Comment by benlesh** [comment]
Docs are now all at rxjs.dev
