### ISSUE TITLE
Uncaught TypeError: this.observer$.unsubscribe is not a function

### ISSUE THREAD

**Issue by tech-a-go-go** [ReactiveX/rxjs#3533]
Hi there,

I'm getting the error....but I don't know why.
Plz help me out.

**RxJS version:**

rxjs@5.5.8

**Code to reproduce:**

rxjs is used in a react componet as follows. 
```
import {Observable} from 'rx';

class MyComponent extends React.Component {

  componentDidMount() {
    this.observer$ =  Observable.timer(0, 1000).flatMap(() => {
        return Observable.fromPromise(this.foo());
      }).subscribe(() => {
      });
  }
  componentWillUnmount() {
     console.log(this.observer$);
    if (this.observer$) {
      this.observer$.unsubscribe();      <--- this line throws an error.
    }
  }
  ...
}
```
**Expected behavior:**

this.observer$ will unsubscribe the stream without any errors.

**Actual behavior:**

When componentWillUnmount() is called, I get the following error.

> Uncaught TypeError: this.observer$.unsubscribe is not a function

**Additional information:**

The output of console.log in componentWillUnmount() is as follows.

> AutoDetachObserver {isStopped: false, observer: AnonymousObserver, m: Rx.SingleAssignmentDisposable}

Cheers

**Comment by kwonoj** [comment]
Rx v5 and above doesn't have `AutoDetachObserver`. Are you sure it's 5.x, and there is no any other instance of Rx not 5 version?

**Comment by kwonoj** [comment]
v5 of rxjs module name is `rxjs`, not `rx`. Seems you're importing old version of module and tried to use v5 interfaces.

**Comment by kwonoj** [comment]
reference: 

https://www.npmjs.com/package/rx
https://www.npmjs.com/package/rxjs
