### ISSUE TITLE
Safari 9.0 | 404 errors on all files in rxjs folder

### ISSUE THREAD

**Issue by TimHawkHodg** [ReactiveX/rxjs#3541]
**RxJS version:**
5.5.8

**Code to reproduce:**
Open Apple simulator using iOS 9 or simply open safari browser version 9.0

ng new PROJECT-NAME
cd PROJECT-NAME
ng serve

app.component.ts

```
import { Component, OnInit } from '@angular/core';
import { Observable } from 'rxjs/Observable';
import 'rxjs/add/observable/timer';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'app works!';

  constructor() {
    Observable.timer(100).subscribe(x => {
      console.log('This will never log');
    });
  }
}

```
**Expected behavior:**
Statement to be logged

**Actual behavior:**
Statement never logged. 404 errors on rxjs observables

**Additional information:**
For the current project I am working on I am getting 404 errors on nearly all the files in node_modules > rxjs folder. This only occurs in safari version 9. Adding an import statement to the path of the missing files, as suggested in the README, does not seem to help. Also there are over 80+ 404 errors so it would not be ideal to add an import statement for each missing file in every component. 

Any idea on how I can resolve this?

<img width="801" alt="screen shot 2018-04-10 at 11 28 07 am" src="https://user-images.githubusercontent.com/32336115/38568140-e69edcbc-3cb5-11e8-8494-98d788daf7ae.png">

**Comment by benlesh** [comment]
Thanks for letting us know, this seems to have something to do with Angular cli. Please report this error on the [Angular project](https://github.com/angular/angular/issues).
