### ISSUE TITLE
Typescript: Fails to compile when 10 or more operators are used with the `pipe()`-Method

### ISSUE THREAD

**Issue by johe7436** [ReactiveX/rxjs#3547]
**RxJS version:** 5.5.9
**Typescript version:** 2.8.1

If you use 10 or more arguments with the `pipe()`-Method, the TypeScript compiler will throw the following error: "test.ts(4,1): error TS2554: Expected 0-9 arguments, but got 10."

**Code to reproduce:**

The following compiles without errors: 

```typescript
import {of} from 'rxjs/observable/of';
import {first} from 'rxjs/operators';

of(1).pipe(
    first(), // 1
    first(), // 2
    first(), // 3
    first(), // 4
    first(), // 5
    first(), // 6
    first(), // 7
    first(), // 8
    first(), // 9
);
```

However, if you add one more operator to the pipe method, it fails to compile:

```typescript
import {of} from 'rxjs/observable/of';
import {first} from 'rxjs/operators';

of(1).pipe(
    first(), // 1
    first(), // 2
    first(), // 3
    first(), // 4
    first(), // 5
    first(), // 6
    first(), // 7
    first(), // 8
    first(), // 9
    first(), // 10
);
```

tsconfig.json:

```json
{
  "compilerOptions": {
    "moduleResolution": "node",
    "target":"es2016",
    "lib": ["es2017"]
  },
  "files": ["test.ts"]
}
```

**Expected behavior:**
It compiles without errors

**Actual behavior:**
It doesn't compile

**Additional information:**

**Comment by cartant** [comment]
See #3346.

**Comment by johe7436** [comment]
Oh, I didn't find that issue. Closing this because it's a duplicate.

**Comment by cartant** [comment]
@johe7436 I'd remembered seeing it, but I thought it had been fixed/closed, recently. I was wrong. I'll open a PR that cherry picks that change into the `stable` branch.

**Comment by johe7436** [comment]
Thank you!
