### ISSUE TITLE
GroupedObservable is not exported from root

### ISSUE THREAD

**Issue by evertbouw** [ReactiveX/rxjs#3551]
I'm using the type GroupedObservable, but I have to import this from /internal

`import { GroupedObservable } from "rxjs/internal/operators/groupBy";`

**RxJS version:**
6.0.0-terrific-rc.3

**Comment by benlesh** [comment]
You're using it as a *type* or you're creating it with a constructor?

**Comment by evertbouw** [comment]
As a type only, I liked to extract and reuse the inner function

**Comment by benlesh** [comment]
Thanks, I'll look into it
