### ISSUE TITLE
Documentation isn't clear about the differences between Observable / Subject

### ISSUE THREAD

**Issue by SetTrend** [ReactiveX/rxjs#3553]
From the documentation it doesn't get clear what the repercussions of prefering a `Subject` over an `Observable` are.
<br/>

## (a) Compare these two explanations:
<hr/>

### [ReactiveX/rxjs/doc/observable.md](https://github.com/ReactiveX/rxjs/blob/e91d113e49acc9b0e12e2524040fa84cf3fa2c78/doc/observable.md)

You can write the same behavior above, but with Observables:

```js
var foo = Rx.Observable.create(function (observer) {
  console.log('Hello');
  observer.next(42);
});

foo.subscribe(function (x) {
  console.log(x);
});
foo.subscribe(function (y) {
  console.log(y);
});
```

And the output is the same:

```none
"Hello"
42
"Hello"
42
```
<hr/>

### [ReactiveX/rxjs/doc/subject.md](https://github.com/ReactiveX/rxjs/blob/e91d113e49acc9b0e12e2524040fa84cf3fa2c78/doc/subject.md)

In the example below, we have two Observers attached to a Subject, and we feed some values to the Subject:

```js
var subject = new Rx.Subject();

subject.subscribe({
  next: (v) => console.log('observerA: ' + v)
});
subject.subscribe({
  next: (v) => console.log('observerB: ' + v)
});

subject.next(1);
subject.next(2);
```

With the following output on the console:

```none
observerA: 1
observerB: 1
observerA: 2
observerB: 2
```
<hr/>

These explanations basically show the same behaviour.

<br/>

## (b) The reference page on `Subject` doesn't have any comment/remark on the peculiarities of that class:
![subject](https://user-images.githubusercontent.com/9283914/38668135-b936b0c6-3e43-11e8-8da6-41e0162ef58b.png)
<hr/>

<br/>

I feel the documentation should further elaborate on this part for learning and offline reading.

**Comment by MichaelSolati** [comment]
@benlesh It's not marked as a `status: PRs welcome` but I wouldn't mind doing some clarification of the docs. This as well as other bits as/if they show up.

**Comment by benlesh** [comment]
@MichaelSolati feel free. :+1:

**Comment by cartant** [comment]
Closing this as the associated PR has been merged.
