### ISSUE TITLE
already-handled errors are also "unhandled"

### ISSUE THREAD

**Issue by mattflix** [ReactiveX/rxjs#3561]
**RxJS version:**
5.5.8

**Code to reproduce:**
```javascript
window.onerror = function() {
  console.log(`onerror event fired anyway`);
};

Rx.Observable
  .of(`something`)
  .observeOn(Rx.Scheduler.async)
  .flatMap(() =>
    Rx.Observable
      .create(
        observer => {
          throw `trantrum`
        }
      )
  )
  .catch(
    error => {
      console.log(`totally handled the error`);
      return Rx.Observable.empty();
    }
  )
  .subscribe();
```
**Expected behavior:**
```
totally handled the error
```

**Actual behavior:**
```
totally handled the error
onerror event fired anyway
```

**Additional information:**
This behavior seems to have been introduced in 5.5.0.  Versions < 5.5.0, such as 5.4.3, exhibit the expected behavior.

If the `Observable.create()` call is replaced with `Observable.defer()` (that still synchronously throws an error), we get the expected behavior, even with versions > 5.4.3, including 5.5.8.

If this behavior is expected, it seems completely surprising, and very painful to deal with.  Why create observables with supposedly self-contained error-handling logic, and yet have to ALSO deal with the onerror events?

**Comment by mattflix** [comment]
See also #3560.

**Comment by benlesh** [comment]
This is because you're expected to handle your own errors inside of the init function passed to the `Observable` constructor (aka `Observable.create`), then hand those errors to the `observer.error` yourself.

```ts
new Observable(() => { throw new Error('test'); });

// vs

new Observable(o => o.error(new Error('test')));
```

**Comment by mattflix** [comment]
@benlesh, your comment doesn't seem to explain why the error is delivered BOTH to the `.catch()` to also to the unhandled error callback.  (See my repro case.)

Are you saying that behavior (one error going to two handlers in contradiction with each other; handled vs. unhandled) is by-design?  If so, can you provide the rationale behind that?
