### ISSUE TITLE
Slow Development/Test Cycle

### ISSUE THREAD

**Issue by darthtrevino** [ReactiveX/rxjs#3563]
The instructions in README.md indicate that the way to start working in this project is to use the `build_all` and `test` scripts. These scripts appear to clean and retranspile the entire project - that makes sense for CI, but it's a very slow feedback loop for experimenting with ideas locally.  Even the `watch` script just thunks down to this process, and it takes quite a while to re-run.. 

It may make sense to either update the watch script or add a new develop script that runs `tsc` in watch mode to improve the feedback loop time.

**Comment by darthtrevino** [comment]
How open would you be to a PR that switches to Jest?

**Comment by kwonoj** [comment]
Jest doesn't give lot of benefit for our cases. Our test execution isn't slow and doesn't need lot of utilities like mocks jest provides.

**Comment by darthtrevino** [comment]
@kwonoj - when you develop on RxJs, do you use the `build_all` and `test` scripts, or do you have another mechanism you use to watch tests?

**Comment by kwonoj** [comment]
I'm using wallaby(https://wallabyjs.com) as test runner. Clarifying, it's way I am doing and I do not say it as any kind of recommendation or vice versa.

**Comment by darthtrevino** [comment]
That makes sense - Wallaby is great (and now I see the wallaby.js file)

So my thoughts for using Jest are:

* You can configure it to transpile using the tsconfig.json in the spec folder. It looks like with mocha and ts-node, you have to use the tsconfig at the top-level.
* It looks like you're using nyc to generate coverage. It's a great tool and all, but Jest has coverage built-in.
* Jest can run tests in parallel, which may or may not be important

**Comment by kwonoj** [comment]
All 3 is benefit, but not relavant with given topic itself. Our repo's issue is build script is complex and doesn't have great way for incremental build which jest can't solve anyway.

I do have most of my codebase / at work codebase with jest running and agree all 3 benefits but that doesn't currently strongly reasoning to convert all our test setup with around 2000 test cases.

**Comment by benlesh** [comment]
Some of this comes from the fact that we need to update all of tests to not use dot-chained operators, then we can get off of using rxjs-contrib, and then we can move back to faster tests with ts-node or the like.
