### ISSUE TITLE
Suggestion/Conversation: Lossy Schedulers

### ISSUE THREAD

**Issue by darthtrevino** [ReactiveX/rxjs#3567]
Context:
I've been experimenting with RxJs and using it to mitigate jankiness in web-apps. I want the event handling code to get as close to 60fps as possible and degrade gracefully as backpressure increases.

https://codepen.io/darthtrevino/pen/xWBNjR - In this example, the goal is to set up a basic RxJs-based drag observable and let it gracefully degrade as we introduce backpressure and jank.

I went through a few different approaches to getting 60fps animations:
1) Throttling the event stream to only emit events every 1/60th of a second.
2) use .observeOn to synchronize with the AnimationFrameScheduler
3) Use .observeOn to synchronize with the AnimationFrameSceduler and also use a .sample() operator to limit the events to those nearest to animation frame events. 

The first experiment worked well, but I'm not convinced that it would scale out into a full-blown webapp, because we want to align animation-based work with the animation callbacks. If this work happens in-between paint cycles it could cause some jank.

The second experiment worked well without jank, but when we introduce backpressure it became clear that the AnimationFrameScheduler was flushing too many events per frame to make it feel responsive. 

So this led to the third experiment, where we time the event handling to occur on animation frames and we also cull the events down. This experiment felt like a nice graceful degradation, where it felt choppy under jank, but the drag event was not lagging. It would sputter to where you are at the moment.

So there may be a better way to pull this off in the existing API, but it seems like listening to an animationFrame stream and using that to sample is a little wonky. Would it make sense instead to have the notion of a "lossy scheduler" or to have async schedulers in a lossy mode? If this is something that you guys would be open to, I would be glad to cut a PR to open up a conversation. This would look something like `observable.observeOn(AnimationFrameScheduler.lossy)` and the flush() operation would only process the last item in the queue

Thanks!
Chris

**Comment by cartant** [comment]
Won't `auditTime(0, Rx.Scheduler.animationFrame)` do what you want? That is, process only the most recently received event?

**Comment by darthtrevino** [comment]
I think you're right yeah - thanks @cartant
