### ISSUE TITLE
Introduce proxy directories for all importable stuff

### ISSUE THREAD

**Issue by Andarist** [ReactiveX/rxjs#3568]
**Expected behavior:**

Not having to use special rx mapping in bundlers (i.e. webpack) configs.

**Actual behavior:**

Having to use special rx mapping in bundlers (i.e. webpack) configs.

**Additional information:**

I see you are familiar with "proxy directories" technique which allows node, bundlers and others to pick the right file (in understandable format), as you have such i.e. under `src/operators/package.json` which ofc is later copied to appropriate "format" directories.

Why stop there? Why not to provide more of those (script-generated ofc)? For each importable thing? 
 i.e. `dist/operators/map/package.json`? 

**Intent to implement**
Yes 👍 if you agree that you want this.

**Comment by benlesh** [comment]
:) Sorry, but as a goal we wanted to purposefully limit the number of import sites withing rxjs to prevent confusion. This would be contrary to our goals.

**Comment by Andarist** [comment]
@benlesh 
not sure how my proposal increase import sites - on the contrary, it kinda limits them (everything else becomes "private"/internal).

One of your goals is "Provide more modular file structure in a variety of formats" and IMHO my proposal gets you closer to this higher level goal - user wouldn't even have to think about formats, he/she would just import something and that would **automatically** (without bundler plugins and such!) resolve to appropriate format.
