### ISSUE TITLE
"rxjs" or "RxJS" - what's in the casing? There are multiple modules with names that only differ in casing.

### ISSUE THREAD

**Issue by gitfortee** [ReactiveX/rxjs#3575]
This warning pops up recently in my angular project.. 

```
    WARNING in ./node_modules/RxJS/Subscriber.js
    There are multiple modules with names that only differ in casing.
```

 

This warning is repeated for other files mentioned below.. 

```
    node_modules/RxJS/InnerSubscriber.js
    node_modules/RxJS/Observable.js
    node_modules/RxJS/Observer.js
    node_modules/RxJS/OuterSubscriber.js
    node_modules/RxJS/Subscriber.js
```

and so on... 

I do have the module imports that differ in casing in my `.ts` files as follows.. 

    import { forkJoin } from 'RxJS/observable/forkJoin';
    import { takeUntil } from 'rxjs/operators'; 
    import { Subject } from 'rxjs/Subject';

I found that these warnings are gone if i changed the references of `RxJS -> to rxjs` (note the casing) in my `.ts` files as follows.. 

    import { forkJoin } from 'rxjs/observable/forkJoin';

But want to understand what is the significance in changing the letter casing that got rid of the warnings and also, want to know whether i am going in the right direction and referencing the right things by changing the casing.

**Comment by cartant** [comment]
The package's name is `rxjs`:

```
$ npm dist-tag ls rxjs
alpha: 6.0.0-alpha.4
beta: 6.0.0-beta.4
forward-compat: 5.6.0-forward-compat.4
latest: 5.5.10
rc: 6.0.0-uncanny-rc.7
smoosh: 6.0.0-smoosh.1
unsmoosh: 6.0.0-smoosh.2
```

```
$ npm dist-tag ls RxJS
npm ERR! dist-tag ls Couldn't get dist-tag data for RxJS
npm ERR! code E403
npm ERR! Registry returned 403 for GET on https://registry.npmjs.org/-/package/RxJS/dist-tags
```

**Comment by benlesh** [comment]
Package name: `rxjs`
Formal, written name: `RxJS`

There shouldn't be any code files or directories named `RxJS`
