### ISSUE TITLE
Class constructor BehaviorSubject cannot be invoked without 'new' in angular app with es6 target

### ISSUE THREAD

**Issue by ShinDarth** [ReactiveX/rxjs#3579]
I'm opening this new issue since the previous one was closed:

https://github.com/ReactiveX/rxjs/issues/3191

it was said that the issue was not there anymore, well it is still there.

Also in the original issue thread there is a repository containing a reproduction of the problem.

**Comment by benlesh** [comment]
This is a bug with the Angular app.  `BehaviorSubject` is a proper ES6 class, and cannot be invoked without `new`. So it looks like something in that angular app is trying to do: `const b = BehaviorSubject()` or the like.

I'm afraid there's nothing we can do on our end.
