### ISSUE TITLE
Incorrect marbles parsing in TestScheduler

### ISSUE THREAD

**Issue by uakennysoft** [ReactiveX/rxjs#3580]
**RxJS version:**
 all <= 5.5.10
**Code to reproduce:**
https://stackblitz.com/edit/jasmine-testing-k1q6mh?file=src%2Fmerge.spec.ts
**Expected behavior:**
Expected $[3].frame = 40 to equal 70 - should not be thrown,
while parsing marbles, parenthesis should not increase asserted frames
cold('x-(xy)-x') where X [0f] - [1f] (xy) [2f] - [3f] x [4f] 
**Actual behavior:**

it('why is this failed?', function () {
    const one$ = cold('x-x-x');  - length: 4 frames * frameTimeFactor = 40
    const two$ = cold('--y--'); - length: 4 frames * frameTimeFactor = 40 
    expect(one$.merge(two$)).toBeObservable(cold('x-(xy)-x'));  - on parsing the last frame, grouping is ignored and it compiles to 7 frames (each token as frame)
  });

**Additional information:**

**Comment by cartant** [comment]
Please see #3581. The characters covered by the synchronous group count as actual frames. The commit mentioned in that issue introduced an error to the documentation.

**Comment by uakennysoft** [comment]
Thanks, @cartant . But how can i test such a case using marbles? single emission after grouped
 it('should not failed', function () {
    const one$ = cold('x-x-x');
    const two$ = cold('--y--');
    expect(one$.merge(two$)).toBeObservable(cold('x-(xy)-x'));
  });

**Comment by cartant** [comment]
You just need to space things out a bit by using more `-` characters. For padding, so to speak.

**Comment by uakennysoft** [comment]
Ah, got it, 
const one$ = cold('x-x----x');
Thanks a lot
