### ISSUE TITLE
Rxjs compat failed to compile

### ISSUE THREAD

**Issue by Frennetix** [ReactiveX/rxjs#3582]
**RxJS version:**
6.0.0-uncanny-rc.7

**Rxjs compat version**
6.0.0-uncanny-rc.7

**Code to reproduce:**

**Expected behavior:**

**Actual behavior:**

ERROR in node_modules/rxjs-compat/add/operator/audit.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'audit'.

node_modules/rxjs-compat/add/operator/auditTime.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'auditTime'.

node_modules/rxjs-compat/add/operator/buffer.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'buffer'.

node_modules/rxjs-compat/add/operator/bufferCount.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'bufferCount'.

node_modules/rxjs-compat/add/operator/bufferTime.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'bufferTime'.

node_modules/rxjs-compat/add/operator/bufferToggle.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'bufferToggle'.

node_modules/rxjs-compat/add/operator/bufferWhen.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'bufferWhen'.

node_modules/rxjs-compat/add/operator/catch.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member '_catch'.

node_modules/rxjs-compat/add/operator/combineAll.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'combineAll'.

node_modules/rxjs-compat/add/operator/combineLatest.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'combineLatest'.

node_modules/rxjs-compat/add/operator/concat.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'concat'.

node_modules/rxjs-compat/add/operator/concatAll.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'concatAll'.

node_modules/rxjs-compat/add/operator/concatMap.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'concatMap'.

node_modules/rxjs-compat/add/operator/concatMapTo.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'concatMapTo'.

node_modules/rxjs-compat/add/operator/count.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'count'.

node_modules/rxjs-compat/add/operator/debounce.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'debounce'.

node_modules/rxjs-compat/add/operator/debounceTime.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'debounceTime'.

node_modules/rxjs-compat/add/operator/defaultIfEmpty.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'defaultIfEmpty'.

node_modules/rxjs-compat/add/operator/delay.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'delay'.

node_modules/rxjs-compat/add/operator/delayWhen.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'delayWhen'.

node_modules/rxjs-compat/add/operator/dematerialize.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'dematerialize'.

node_modules/rxjs-compat/add/operator/distinct.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'distinct'.

node_modules/rxjs-compat/add/operator/distinctUntilChanged.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'distinctUntilChanged'.

node_modules/rxjs-compat/add/operator/distinctUntilKeyChanged.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'distinctUntilKeyChanged'.

node_modules/rxjs-compat/add/operator/do.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member '_do'.

node_modules/rxjs-compat/add/operator/elementAt.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'elementAt'.

node_modules/rxjs-compat/add/operator/every.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'every'.

node_modules/rxjs-compat/add/operator/exhaust.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'exhaust'.

node_modules/rxjs-compat/add/operator/exhaustMap.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'exhaustMap'.

node_modules/rxjs-compat/add/operator/expand.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'expand'.

node_modules/rxjs-compat/add/operator/filter.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'filter'.

node_modules/rxjs-compat/add/operator/finally.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member '_finally'.

node_modules/rxjs-compat/add/operator/find.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'find'.

node_modules/rxjs-compat/add/operator/findIndex.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'findIndex'.

node_modules/rxjs-compat/add/operator/first.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'first'.

node_modules/rxjs-compat/add/operator/groupBy.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'groupBy'.

node_modules/rxjs-compat/add/operator/ignoreElements.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'ignoreElements'.

node_modules/rxjs-compat/add/operator/isEmpty.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'isEmpty'.

node_modules/rxjs-compat/add/operator/last.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'last'.

node_modules/rxjs-compat/add/operator/let.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'letProto'.

node_modules/rxjs-compat/add/operator/map.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'map'.

node_modules/rxjs-compat/add/operator/mapTo.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'mapTo'.

node_modules/rxjs-compat/add/operator/materialize.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'materialize'.

node_modules/rxjs-compat/add/operator/max.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'max'.

node_modules/rxjs-compat/add/operator/merge.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'merge'.

node_modules/rxjs-compat/add/operator/mergeAll.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'mergeAll'.

node_modules/rxjs-compat/add/operator/mergeMap.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'mergeMap'.

node_modules/rxjs-compat/add/operator/mergeMapTo.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'mergeMapTo'.

node_modules/rxjs-compat/add/operator/mergeScan.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'mergeScan'.

node_modules/rxjs-compat/add/operator/min.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'min'.

node_modules/rxjs-compat/add/operator/multicast.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'multicast'.

node_modules/rxjs-compat/add/operator/observeOn.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'observeOn'.

node_modules/rxjs-compat/add/operator/onErrorResumeNext.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'onErrorResumeNext'.

node_modules/rxjs-compat/add/operator/pairwise.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'pairwise'.

node_modules/rxjs-compat/add/operator/partition.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'partition'.

node_modules/rxjs-compat/add/operator/pluck.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'pluck'.

node_modules/rxjs-compat/add/operator/publish.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'publish'.

node_modules/rxjs-compat/add/operator/publishBehavior.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'publishBehavior'.

node_modules/rxjs-compat/add/operator/publishLast.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'publishLast'.

node_modules/rxjs-compat/add/operator/publishReplay.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'publishReplay'.

node_modules/rxjs-compat/add/operator/race.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'race'.

node_modules/rxjs-compat/add/operator/reduce.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'reduce'.

node_modules/rxjs-compat/add/operator/repeat.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'repeat'.

node_modules/rxjs-compat/add/operator/repeatWhen.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'repeatWhen'.

node_modules/rxjs-compat/add/operator/retry.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'retry'.

node_modules/rxjs-compat/add/operator/retryWhen.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'retryWhen'.

node_modules/rxjs-compat/add/operator/sample.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'sample'.

node_modules/rxjs-compat/add/operator/sampleTime.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'sampleTime'.

node_modules/rxjs-compat/add/operator/scan.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'scan'.

node_modules/rxjs-compat/add/operator/sequenceEqual.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'sequenceEqual'.

node_modules/rxjs-compat/add/operator/share.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'share'.

node_modules/rxjs-compat/add/operator/shareReplay.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'shareReplay'.

node_modules/rxjs-compat/add/operator/single.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'single'.

node_modules/rxjs-compat/add/operator/skip.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'skip'.

node_modules/rxjs-compat/add/operator/skipLast.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'skipLast'.

node_modules/rxjs-compat/add/operator/skipUntil.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'skipUntil'.

node_modules/rxjs-compat/add/operator/skipWhile.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'skipWhile'.

node_modules/rxjs-compat/add/operator/startWith.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'startWith'.

node_modules/rxjs-compat/add/operator/subscribeOn.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'subscribeOn'.

node_modules/rxjs-compat/add/operator/switch.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member '_switch'.

node_modules/rxjs-compat/add/operator/switchMap.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'switchMap'.

node_modules/rxjs-compat/add/operator/switchMapTo.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'switchMapTo'.

node_modules/rxjs-compat/add/operator/take.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'take'.

node_modules/rxjs-compat/add/operator/takeLast.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'takeLast'.

node_modules/rxjs-compat/add/operator/takeUntil.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'takeUntil'.

node_modules/rxjs-compat/add/operator/takeWhile.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'takeWhile'.

node_modules/rxjs-compat/add/operator/throttle.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'throttle'.

node_modules/rxjs-compat/add/operator/throttleTime.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'throttleTime'.

node_modules/rxjs-compat/add/operator/timeInterval.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'timeInterval'.

node_modules/rxjs-compat/add/operator/timeout.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'timeout'.

node_modules/rxjs-compat/add/operator/timeoutWith.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'timeoutWith'.

node_modules/rxjs-compat/add/operator/timestamp.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'timestamp'.

node_modules/rxjs-compat/add/operator/toArray.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'toArray'.

node_modules/rxjs-compat/add/operator/window.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'window'.

node_modules/rxjs-compat/add/operator/windowCount.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'windowCount'.

node_modules/rxjs-compat/add/operator/windowTime.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'windowTime'.

node_modules/rxjs-compat/add/operator/windowToggle.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'windowToggle'.

node_modules/rxjs-compat/add/operator/windowWhen.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'windowWhen'.

node_modules/rxjs-compat/add/operator/withLatestFrom.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'withLatestFrom'.

node_modules/rxjs-compat/add/operator/zip.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'zipProto'.

node_modules/rxjs-compat/add/operator/zipAll.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/internal-compatibility/index"' has no exported member 'zipAll'.

**Additional information:**

**Comment by shainti** [comment]
Why it's is closed without solutions? it's still not working.
