### ISSUE TITLE
ThrowIf Operator, proposal

### ISSUE THREAD

**Issue by MatthiasKunnen** [ReactiveX/rxjs#3586]
Recently I found myself in need of a pipeable operator that would throw an error if a predicate is met.  It acts in the opposite way compared to filter throwing an error when the predicate function returns true effectively filtering out the emitted value and raising an error. 

Current implementation: https://gist.github.com/MatthiasKunnen/bc82adb90068072fed1031045f245074.

Example usage:
```TypeScript
// Where http is an instance of the HttpClient class of Angular
http.get('https://example.com').pipe(
    throwIf(v => v === null, 'Result is null'),
).subscribe(
    v => console.log('Successfully fetched'),
    console.error,
);
```

**Comment by benlesh** [comment]
You can roll this yourself now:

```
import { tap } from 'rxjs/operators';

const throwIf = <T>(predicate: (value: T) => boolean, message: string)  =>
  tap(v => {
    if (predicate(v)) throw new Error(message);
  });
```

Usage would be exactly what you have in your example above.

**Comment by MatthiasKunnen** [comment]
For future visitors: I created a library for this _throwIf_ operator which can be found here: https://www.npmjs.com/package/rxjs-throw-if.
