### ISSUE TITLE
Using publish() inside a pipe doesn't return a right type

### ISSUE THREAD

**Issue by Pittan** [ReactiveX/rxjs#3595]
**RxJS version:**
6.0.0-uncanny-rc.7

**Code to reproduce:**
https://stackblitz.com/edit/rxjs6-publish-and-connect

**Expected behavior:**
It should be no error for TS compiler.

**Actual behavior:**
TS compiler outputs error, even when I added `ConnectableObservable<any>` to variable.

**Additional information:**

**Comment by evertbouw** [comment]
According to the TypeScript definition of `pipe` the output of an operator is always an `Observable`, but this is not the case with `publish`. To work around this, you can apply the operator outside of pipe:

```ts
import { interval } from 'rxjs';
import { filter, publish } from 'rxjs/operators';

const source = interval(400)
const observable = publish()(source.pipe(
  filter(x => x % 2 === 0),
))

observable.connect()
```

**Comment by Pittan** [comment]
@evertbouw 
Looks weird to me... but it worked perfectly! Thank you!
