### ISSUE TITLE
React Native Components are not supported by `fromEvent`

### ISSUE THREAD

**Issue by pvinis** [ReactiveX/rxjs#3598]
I tried to use rxjs' `Observable.fromEvent` to get the `onPress` for a `Button`, but Im getting `TypeError: Invalid event target`.

What could we do to support that too? or maybe Im doing it wrong?

**RxJS version:**
5.5.10
**Code to reproduce:**
```ts
class SomeScreen extends Component<Props> {
  constructor(props) {
    super(props)
    this.doneButton = React.createRef()
  }

  componentDidMount() {
    const tap = fromEvent(this.doneButton.current, 'onPress')
    tap.subscribe(() => console.log('rx press'))
  }

  render() {
    return (
      <Button
        ref={this.doneButton}
        title='Done'
        onPress={() => console.log('normal press')}
      />
    )
  }
}
```

**Expected behavior:**
to have the `rx press` printed
**Actual behavior:**
i get an error about type
**Additional information:**

**Comment by staltz** [comment]
This shouldn't have anything to do with RxJS, It's a React Native issue. Actually, better, it should be its own library decoupled from both RxJS and RN.

**Comment by benlesh** [comment]
I agree with @staltz here. I'm not steeped in React Native, but I'm pretty sure that the `onPress` of `doneButton.current` is just a place to register a single function handler. `fromEvent` is designed to deal with event sources that are more like Subjects (in the Observer Pattern sense), which have "addListener" and "removeListener" type registration points.

Given that, you'll probably just want to create a `Subject` and register a handler that nexts values through the subject.
