### ISSUE TITLE
migration guide google doc vandalized

### ISSUE THREAD

**Issue by dominikg** [ReactiveX/rxjs#3599]
guide located at https://docs.google.com/document/d/12nlLt71VLKb-z3YaSGzUfx6mJbc34nsMXtByPUN35cg

(linked from https://github.com/ReactiveX/rxjs/blob/master/MIGRATION.md)

looks like this

![bildschirmfoto 2018-04-25 um 08 23 52](https://user-images.githubusercontent.com/611613/39229252-36f23972-4862-11e8-9cc2-fd7a726ba7d8.png)

(maybe not a good idea to allow anonymous editing?)

**Comment by kwonoj** [comment]
Thanks for reporting. /cc @benlesh

**Comment by jmurzy** [comment]
@dominikg In the dropdown in the toolbar, Select `Viewing` to remove all the garbage.

Also, kudos to the RxJS team for finally normalizing the import paths! I think this is the biggest selling feature in v6! 🎉

**Comment by benlesh** [comment]
Okay, it's all fixed. Thanks @dominikg!
