### ISSUE TITLE
Does pipeable combineLatest have a limit of 5?

### ISSUE THREAD

**Issue by dereklin** [ReactiveX/rxjs#3601]
We are using version 5.5.8

When we try to do this:

sudo code:
This is fine:
```
0$.pipe(
combineLatest(1$, 2$, 3$, 4$, 5$)
)
```

We get a type error doing this:
```
0$.pipe(
combineLatest(1$, 2$, 3$, 4$, 5$, $6)
)
```

This workaround works:
```
0$.pipe(
combineLatest(1$, 2$, 3$, 4$, 5$)
).pipe(
combineLatest(6$)
)
```
Has anyone tried to combine more than 5 observables?  Maybe this has been fixed in a later version?

**Comment by benlesh** [comment]
Unfortunately, TypeScript has some limitations. Basically we provided 5-6 type overloads for this function, beyond that, you'll have to type it manually.

```ts
combineLatest<any>(a$, b$, c$, d$, e$, f$).pipe(
  // Manually typed arguments below :(
  map(([a, b, c, d, e, f]: [string, number, string, Foo, Bar, Baz]) => doStuff(a, b, c, d, e, f))
)
```

**Comment by benlesh** [comment]
@dereklin I'm unable to reproduce your issue: https://stackblitz.com/edit/typescript-w8vc7y

The error message you posted there looks unrelated to the original issue.

If you have some concise reproduction of your issue, please file a new issue with that code.

**Comment by dereklin** [comment]
@benlesh I am using combineLatest from rxjs/operators:

https://stackblitz.com/edit/typescript-krkep6?file=index.ts
