### ISSUE TITLE
RxJS v6 TimeoutError is missing name property

### ISSUE THREAD

**Issue by felixfbecker** [ReactiveX/rxjs#3602]
**RxJS version:** 6.0.0

**Code to reproduce:**

```ts
export const browserExtensionInstalled = fromEvent(document, 'custom-event').pipe(
    mapTo(true),
    timeout(500),
    catchError(err => {
        if (err.name === 'TimeoutError') {
            return [false]
        }
        throw err
    }),
)
```
**Expected behavior:**

Should emit `false` after 500ms.

**Actual behavior:**

Throws an error `Error: Timeout has occurred`. (worked in RxJS 5)

**Additional information:**

This broke in commit https://github.com/ReactiveX/rxjs/commit/2f395da56189090215462bb88cfd2014c842be57#diff-cd4b33df1ab129e23dc2bc5c12d8369b

`UnsubscriptionError` still has the `name` set, but `TimeoutError` doesn't, and it's not mentioned in the release notes, so I assume this is an unintentional bug (in any case it can be reintroduced in a semver-patch).

https://github.com/ReactiveX/rxjs/blob/b948e651949eb7b4c1103d7013fc43f49ac1b870/src/internal/util/UnsubscriptionError.ts#L5-L13

https://github.com/ReactiveX/rxjs/blob/b948e651949eb7b4c1103d7013fc43f49ac1b870/src/internal/util/TimeoutError.ts#L8-L13

_Why not use `instanceof`?_ `instanceof` breaks when multiple RxJS versions are in play, or even just the same version had to be installed multiple times because deduping wasn't possible. It asserts the implementation, `err.name` asserts an interface. All browser errors use it (e.g. `AbortError`).

**Comment by cartant** [comment]
This might be the first issue that'll effect a 6.0.1 release. I wonder if you get a prize? :thinking:

**Comment by martinsik** [comment]
This seems to be fixed in https://github.com/ReactiveX/rxjs/pull/3656.
