### ISSUE TITLE
Should the race operator be deprecated?

### ISSUE THREAD

**Issue by cartant** [ReactiveX/rxjs#3603]
**RxJS version:** 6.0.0

**Code to reproduce:**

```ts
const winner = of(1).pipe(race(of(2)));
```

**Expected behavior:**

I expected a TSLint deprecation warning, as the `race` operator has a namesake observable factory function.

**Actual behavior:** 

No warning is effected.

**Additional information:**

The other operators that have namesake observable factory functions (`concat`, `merge`, etc.) are deprecated, but [`race` is not](https://github.com/ReactiveX/rxjs/blob/6.0.0/src/internal/operators/race.ts#L6-L11).

**Comment by benlesh** [comment]
Yes. It should be deprecated. Thanks for catching that.

**Comment by natmegs** [comment]
I'll work on a PR for this!

**Comment by cartant** [comment]
Closed by #3611.
