### ISSUE TITLE
mergeMap/concatMap with limited concurrency will blow the stack

### ISSUE THREAD

**Issue by ubnt-michals** [ReactiveX/rxjs#3609]
**RxJS version:** 5.5.10

**Code to reproduce:**

```.js
const { Observable, Subject } = require('rxjs');

const signal = new Subject();
const terminate$ = signal.take(1).publishLast();

terminate$.connect();

const create = () => Observable.timer(1000).takeUntil(terminate$);

Observable.range(1, 1000)
  .mergeMap(() => create(), 10) // or concatMap
  .subscribe();

setTimeout(() => {
  signal.next();
}, 500);
```

**Expected behavior:**
I would expect it to not blow the stack

**Actual behavior:**
RangeError: Maximum call stack size exceeded

**Additional information:**
I haven't tested 6.0.0

**Comment by cartant** [comment]
This is fixable. It's a re-enterancy issue that's due to synchronous `complete` notifications from buffered observables. I'll create a PR with a fix sometime soon. However, I'm curious: did you come across this problem in a real-world situation?

**Comment by ubnt-michals** [comment]
@cartant This and #3604 is from production. We maintain a lot of long running WebSocket connections - this particular case is an edge case that happened probably because of a network outage when all connections disconnected at once.

**Comment by cartant** [comment]
The solution to the problem is to use the `QueueScheduler`:

```js
const { Observable, Scheduler, Subject } = require('rxjs');

const signal = new Subject();
const terminate$ = signal.take(1).publishLast();

terminate$.connect();

const create = () => Observable.timer(1000)
  .takeUntil(terminate$)
  .observeOn(Scheduler.queue); // HERE

Observable.range(1, 1000)
  .mergeMap(() => create(), 10)
  .subscribe();

setTimeout(() => {
  signal.next();
}, 500);
```

The re-enterant behaviour is [by design](https://github.com/ReactiveX/rxjs/pull/3621#issuecomment-386356358) and [using `observeOn`](https://github.com/ReactiveX/rxjs/pull/3621#issuecomment-386472093) is the mechanism to effect the non-re-enterant behaviour.

**Comment by ubnt-michals** [comment]
> The re-enterant behaviour is by design and using observeOn is the mechanism to effect the non-re-enterant behaviour.

This is not a good design then... It was non trivial to find this issue in our codebase, especially when there are a lot of operators involved. 

Also this essentially means that every Observable I use in concatMap&friends has to be using `QueueScheduler` otherwise SO is possible if someone adds cancellation, right?

**Comment by cartant** [comment]
@ubnt-michals Yeah, it means that if you anticipate a large number of observables accumulating in a limited-concurrency `mergeMap`/`concatMap` - where those observables could complete synchronously - you should use something like [this `queue` helper](https://github.com/cartant/rxjs-etc/blob/v6.2.0/source/observable/queue.ts) to ensure they all use the `QueueScheduler`:

```ts
mergeMap(...queue(a, b, c), 1)
```

And that's just the way it is, I guess.

**Comment by ubnt-michals** [comment]
@cartant Thanks - will check it out. 

Closing the issue.
