### ISSUE TITLE
Inconsistency of fromEventPattern

### ISSUE THREAD

**Issue by crimx** [ReactiveX/rxjs#3613]
**RxJS version:**
6.0.0

https://github.com/ReactiveX/rxjs/blob/76b7e272433a5c94832b2a2f945af526236e0fde/src/internal/observable/fromEventPattern.ts#L66-L67

`fromEventPattern` now produces two types of result, which is quite annoying to deal with.

Also if the result could be a single array, there is no way to tell the difference.

It this is about backward compatibility, It should only produce the first argument in compat-mode, and produce the array of arguments in 6.x.

**Comment by benlesh** [comment]
This is a non-breaking change from v5, actually. WIth v5, only one argument was returned, so you were expected to call the handler manually and do something with the values if you had multiple values to emit.

In v6, we've just added the feature that if the handler is called with more than one argument, it will automatically group them into an array.

This isn't really a bug, and it actually maintains consistency with `fromEvent`.

Changing it to do anything else would now be a breaking change. So I think we're going to close this one.
