### ISSUE TITLE
[Feature requests] default operator 

### ISSUE THREAD

**Issue by michaeljota** [ReactiveX/rxjs#3615]
**Rxjs version** 6

**Code to reproduce**

```typescript
interval<string>(1000).pipe(
  tap(value => throw Error(""),
  default(() => "Hello from an error")
).subscribe(value => console.log(value));
```

**Expected behavior**

Logging of "Hello from an error" string every second

**Actual behavior**

As far I can tell, you can do this with catchError. Still, it would be nice to have an operator that does not actually handle the error, but just provides a default value if an error gets throw.

**Additional information**

**Comment by kwonoj** [comment]
With pipe operator, we do strongly recommend to create operator in user land first before consider it to be added into core api set. Also as you suggested this is some variant of existing catch operator, so either can use existing or easily can be created as user land operator.
