### ISSUE TITLE
combineLatest deprecated

### ISSUE THREAD

**Issue by macliems** [ReactiveX/rxjs#3618]

**Comment by alan-agius4** [comment]
Yes that has been deprecated. You need to use the static version and not the pipeable operator. 

This can be imported directly from rxjs.

**Comment by benlesh** [comment]
FWIW you can still use any of the statics within pipe:

```ts
source$.pipe(
  a$ => combineLatest(a$, b$, c$),
)
```

**Comment by tony-gutierrez** [comment]
The migration tool modifies to the deprecated syntax.

**Comment by sssalib42** [comment]
Here is my stackoverflow question with a detailed example:

https://stackoverflow.com/questions/50276165/combinelatest-is-deprecated-deprecated-in-favor-of-static-combinelatest
