### ISSUE TITLE
rxjs-5-to-6-migrate import comma

### ISSUE THREAD

**Issue by zygimantas** [ReactiveX/rxjs#3620]
rxjs-5-to-6-migrate -p tsconfig.json

**RxJS version:**
5.5 to 6.0
**Code to reproduce:**
```
import {
    filter,
} from "rxjs/operators/filter";
import {
    map,
} from "rxjs/operators/map";
import {
    tap,
} from "rxjs/operators/tap";
```
**Expected behavior:**
```
import {
    filter,
    map,
    tap,
} from "rxjs/operators";
```
**Actual behavior:**
```
import {
    filter,
, 
    map,
, 
    tap,
} from "rxjs/operators";
```
**Additional information:**

**Comment by cartant** [comment]
The [`rxjs-tslint`](https://github.com/ReactiveX/rxjs-tslint/issues) repo would be the best place for this particular issue.

**Comment by benlesh** [comment]
Please report these issues to https://github.com/reactivex/rxjs-tslint
