### ISSUE TITLE
Single entry for all operators and observable creators

### ISSUE THREAD

**Issue by BetterCallSky** [ReactiveX/rxjs#3622]
**Feature request.**

Currently, we must import operators and observable creators from different paths.
Example:

```ts
import { Observable, Subject, ReplaySubject, from, of, range } from 'rxjs';
import { map, filter, switchMap } from 'rxjs/operators';


range(1, 200)
  .pipe(filter(x => x % 2 === 1), map(x => x + x))
  .subscribe(x => console.log(x));
```

In my current project, I am using a helper `rx.ts` file that re-exports functions from the original `rxjs` module.

Example:

```ts
// rx.ts

export * from 'rxjs/operators';
export { from } from 'rxjs/observable/from';

// if there is confilct with operators, I add `Obs` suffix.
export { concat as concatObs } from 'rxjs/observable/concat';
```

Example usage:
```ts
// sample.ts
import * as Rx from './rx';


Rx.range(1, 200)
  .pipe(Rx.filter(x => x % 2 === 1), Rx.map(x => x + x))
  .subscribe(x => console.log(x));
```

Such approach is more convenient because there is always a single import entry for all functions. Similar to lodash or Ramda.

Also, tree-shaking eliminates unused code, and there is no problem that the output bundle is big.

My suggestion is that we could support it by default in `rxjs`. The only issue is that some operators and creators have the same name.

**Comment by benlesh** [comment]
I don't deny, that *I personally* like this. So it's always going to be on my radar, but I'm going to close this for now, as we're committed to the current export scheme, and I don't want to break it again if I can avoid it for v7.
