### ISSUE TITLE
How to use rxjs inside polymer 3 ?

### ISSUE THREAD

**Issue by AchuthSankar** [ReactiveX/rxjs#3624]
**RxJS version:** 5.0

**Code to reproduce:**
import {PolymerElement} from '@polymer/polymer/polymer-element.js';
import Rx from 'rxjs/Rx';

/**
 * `test-element`
 * 
 *
 * @customElement
 * @polymer
 * @demo demo/index.html
 */
class TestElement extends PolymerElement {
  static get template() {
    return `
      <style>
        :host {
          display: block;
        }
      </style>
      <h2>Hello [[prop1]]!</h2>
    `;
  }
  static get properties() {
    return {
      prop1: {
        type: String,
        value: 'test-element',
      },
    };
  }
}

window.customElements.define('test-element', TestElement);

**Expected behavior:**
Browser should render TestElement. I used chrome.

**Actual behavior:**
Uncaught SyntaxError: The requested module './node_modules/rxjs/Rx.js' does not provide an export named 'default'

**Additional information:**

**Comment by kwonoj** [comment]
Rx v5 doesn't export default, so `import Rx from ..` doesn't provide any exports. Either imports everything `import * as Rx .. ` (Though this is strongly not recommended for production) or import individual as guided https://github.com/ReactiveX/rxjs#es6-via-npm .
