### ISSUE TITLE
Proposal: add `catchTo`

### ISSUE THREAD

**Issue by bradsk88** [ReactiveX/rxjs#3625]
I've found the mapTo variants to be quite useful for writing clean, concise code using RXJS.

I think it would be handy to have `catchTo` added to the current toolkit.  For example:

```
/** 
 Does something of low importance.  We want to know if it's successful or not, 
 but we don't care to take any further action.
*/
doSomething(): Observable<boolean> {
  const url = 'http://example.com/do/something';
  return this.http.post(url, {})
     .switchMapTo(Observable.of(true))
     .catchTo(Observable.of(false));
}
```

The current implementation of rxjs requires replacing the `catchTo` above with:
```
  .catch(() => Observable.of(false));
```

Which isn't monumentally worse.  But, that function argument (`() =>`) is completely unnecessary.

As an aside, I wonder if there could be a function that would allow me to do the following and achieve the same results I've outlined above:
```
  .catchTo(false)
```

**Comment by kwonoj** [comment]
With pipe operator, we do strongly recommend to create operator in user land first before consider it to be added into core api set. Also as you suggested this is some variant of existing catch operator, so either can use existing or easily can be created as user land operator.
