### ISSUE TITLE
rxjs-compat is required (tslint)

### ISSUE THREAD

**Issue by rmsmq** [ReactiveX/rxjs#3629]
**RxJS version:** 6.0.0

**Code to reproduce:** `import {Observable} from 'rxjs';`

**Expected behavior:** There should be no tslinting errors in the lastest rxjs package standalone.

**Actual behavior:** Error: Cannot find module 'rxjs-compat/Observable'. It seems that the rxjs-compat package is required for 6.0.0

**Additional information:** I am making the assumption that the rxjs-compat package is not *required* if you wish to migrate to version 6.0.0 completely.

**Comment by cartant** [comment]
This needs more context. Ideally, a reproduction of the problem. TSLint can be used to lint `rxjs` v6 with and without `rxjs-compat` installed.

**Comment by benlesh** [comment]
This seems like a bug with rxjs-tslint maybe?

EIther way, it's not really a bug with rxjs. @rmsmq, I'm going to close this, but can you work out with @cartant which tslint rule you were using that caused this and maybe file an issue with that repo?
