### ISSUE TITLE
types for jasmine (v2.8.3) does not match with those for TestScheduler

### ISSUE THREAD

**Issue by oNora** [ReactiveX/rxjs#3633]
I have project with Angular 5, rxjs v 5.5.6, typescript v2.5.3
Now I am struggling with unite tests for rxjs. When I try to create a new TestScheduler, typescript start to complaining

```
const testScheduler = new TestScheduler(
      (actual, expected) => expect(actual).toEqual(expected)
    );
```

And typescript says:

> [ts]
> Argument of type '(actual: any, expected: any) => Promise<void>' is not assignable to parameter of type '(actual: any, expected: any) => boolean | void'.
>   Type 'Promise<void>' is not assignable to type 'boolean | void'.
>     Type 'Promise<void>' is not assignable to type 'void'.

When I revert the version of types/jasmine form 2.8.3 to 2.5.38 everything is ok.
I am wondering is there something that I have missed? Or there is really mismatch with types

**Comment by jayphelps** [comment]
You're returning a Promise where one is not expected. The function you provide to TestScheduler should not return anything. Change it to:

```ts
const testScheduler = new TestScheduler(
  (actual, expected) => { expect(actual).toEqual(expected); }
);
```

**Comment by oNora** [comment]
It seems that I really missed something. Thanks!
