### ISSUE TITLE
Subject performance issue with many subscribers

### ISSUE THREAD

**Issue by jmis** [ReactiveX/rxjs#3634]
**RxJS version: 5.5.10**

**Code to reproduce: **

**Expected behavior:**

**Actual behavior:**

**Additional information:**

I'm seeing a performance issue when creating and removing a large number of subscribers (1000+) from a Subject.  Internally, the Subject class uses an array to track subscribers which, when large, incurs a performance penalty.  I created a quick & dirty solution where I converted the array to an object which solved my performance problem.  I used I'm an incremented counter as the object's property names.

**Comment by jayphelps** [comment]
Can you provide a way to easily confirm and reproduce the performance? If you're able to provide your quick and dirty solution you mentioned that would also be great!

**Comment by jmis** [comment]
I can't repeat the performance issue in isolation so I'm going to close this issue out.  I'll keep doing some investigation and, if I find something, I'll open another issue with the information.
