### ISSUE TITLE
export `create` from `rxjs`

### ISSUE THREAD

**Issue by ronag** [ReactiveX/rxjs#3635]
Currently the only factory method not exported as root from `rxjs` is `Observable.create`. I see no reason why this couldn't be the case? For consistency.

e.g.

```js
const { defer, of, timer, Observable } = require('rxjs')
```
vs
```js
const { defer, of, timer, create } = require('rxjs')
```

**Comment by wldcordeiro** [comment]
👍 This confused me I saw the migration docs imply that they all were removed and it seemed like `from` was the one to use but it turns out that `Observable.create` is still around and `new Observable` is more [idiomatic](https://github.com/ReactiveX/rxjs/issues/3619#issuecomment-385573434)

**Comment by martinsik** [comment]
Links were updated in #3846.

**Comment by BioPhoton** [comment]
As `create` is deprecated we can close this issue.
See https://github.com/angular/components/issues/14785

**Comment by cartant** [comment]
Closing 'cause `create` is deprecated.
