### ISSUE TITLE
Discuss v7 and the Pipeline Operator

### ISSUE THREAD

**Issue by mcoetzee** [ReactiveX/rxjs#3655]
Just want to start off by saying thanks for all the great work that went into v6 👏👏👏

Ok so I have read through the [v7 design doc](https://docs.google.com/document/d/1DBOhMQ89e2xtWNN0EqCHXOFn4QJjKZcXEvUivp4W2r0/edit#) and I see it is considering dropping compatibility with the [pipeline operator](https://github.com/tc39/proposal-pipeline-operator). I would like to make the case for not dropping compatibility.

Mr Lesh pointed out in Feb that 

> The pipeline operator could be the single best feature since destructuring added to JavaScript if it lands 

https://twitter.com/benlesh/status/959541023796940800?lang=en

After giving it some thought, I think Mr Lesh is right. Here is my case:

1. Like reactive programming, piping (via an operator) is a concept that stretches across languages. Even if you haven't used an operator like this in your programming, there is a good chance you have used it in the terminal (`$ cat ~/.bash_history | grep foo`). Being able to capitalize on that shared mental model that many programmers already have will be a big help in up-skilling RxJS beginners.

2. The functional trend is here to stay, and I believe the pipeline operator will be an important tool in the functional toolbox. If RxJS isn't compatible with this core building block of functional programming, and instead uses a parallel concept, then it could hurt adoption of RxJS in the coming years.

3. This point is a bit subjective, but there is a case to be made that the pipeline operator offers an improvement in readability. Below are some examples to illustrate this point.

**_E.g. 1 Without Operator:_**
```js
const result$ = some$.pipe(takeUntil(someOther$.pipe(filter(value => value === 'END'))))
```

**_E.g. 1 With Operator:_**
```js
const result$ = some$ |> takeUntil(someOther$ |> filter(value => value === 'END'))
```

**_E.g. 2 Without Operator:_**
```js
const saveEpic = action$ =>
  action$.pipe(
    ofType(c.SAVE_REQUESTED),
    switchMap(action => 
      Api.save(action.payload).pipe(
        map(response => saveFulfilled(response)),    
        catchError(err => of(saveFailed(error))),
        takeUntil(action$.pipe(ofType(c.SAVE_CANCELLED)))
      )
    ),
  )
```

**_E.g. 2 With Operator:_**
```js
const saveEpic = action$ =>
  action$
    |> ofType(c.SAVE_REQUESTED)
    |> switchMap(action => 
      Api.save(action.payload)
        |> map(response => saveFulfilled(response))
        |> catchError(err => of(saveFailed(error)))
        |> takeUntil(action$ |> ofType(c.SAVE_CANCELLED))
    )
```
The difference for me is that with the pipeline operator, I am able to quickly scan the code to build up my mental model, as the operator stands out and highlights the logical breakpoints in the composition. Without the operator I find myself having to carefully read the code to build up my mental model, which takes more time and increases the cognitive load. And if I'm experiencing a reduction in cognitive load by using the pipeline operator, then chances are others would too. 

### Conclusion
The pipeline operator proposal has a lot of support behind it (already over 3000 stars), and if it lands, it'll likely become popular as functional programming grows. It seems like a perfect fit for RxJS and I think it would be wise i.t.o. the bigger picture, if RxJS does not drop compatibility with it.

**Comment by benlesh** [comment]
It's not dropping compatability. :).. I really appreciate all of the thought that went into this, but I've landed on a design where pipeline works just fine.

**Comment by mcoetzee** [comment]
Awesome you just made my day @benlesh! I'm looking forward to reading about the new design 🙌 🎉
