### ISSUE TITLE
Type of first parameter of fromEvent not exposed

### ISSUE THREAD

**Issue by CarstenLeue** [ReactiveX/rxjs#3658]
**RxJS version:**
6.1.0

**Code to reproduce:**

I would like to create a function that accepts an object that can be passed in to fromEvent as a first parameter. According to the API this is of type "FromEventTarget", but "FromEventTarget" is not exposed in rxjs as an exported type. 

How can I write my function in a typesafe way?

Example:

```typescript
import { fromEvent, Observable } from 'rxjs';

function myFunction(aTarget: ??): Observable<any> {
  return fromEvent(aTarget, 'click');
}
```

**Comment by cartant** [comment]
As it's a parameter type and not a return type, I don't think there's anyway you can refer to it.

`FromEventTarget` is exported from [`fromEvent.ts`](https://github.com/ReactiveX/rxjs/blob/6.1.0/src/internal/observable/fromEvent.ts) and, as it's exposed via the public API, it should probably be re-exported from [`index.ts`](https://github.com/ReactiveX/rxjs/blob/6.1.0/src/index.ts).

**Comment by CarstenLeue** [comment]
Yes, I think that it would make sense to re-export it. Shouldn't this be also the case for all types that are referenced by this type transitively?

**Comment by cartant** [comment]
Maybe. However, if `FromEventTarget` can be exported without the transitively referenced types also having to be exported, I can see some advantage in their being kept internal, as they just an implementation detail.

In the past, I've run into seemingly related issues, but off the top of my head I cannot remember all of the details.

**Comment by CarstenLeue** [comment]
On the other hand the `FromEventTarget` type together with its transitive dependencies is exposed in the API. Doesn't this conceptually also expose all of these types in the API? I understand that the actual decomposition of `FromEventTarget` into "helper level" types is an implementation detail, but the final result should be public, because of its exposure. 

Can `FromEventTarget` really be made public without making its components public, too?

**Comment by cartant** [comment]
The transitively referenced types have to be exported from `fromEvent.ts`, but they don't have to be re-exported from the `index.ts` barrel file. Basically, that's what's happening with the current situation with the re-exported `fromEvent` factory function and the non-re-exported `FromEventTarget` type.

**Comment by benlesh** [comment]
@CarstenLeue you're probably better off rolling a matching type that is specific to your system. RxJS could possibly change what we accept in `fromEvent` over time (maybe accept more types, maybe less, I don't know why, but it's possible). It's probably best for you to control your own type rules for functions within your application.

I'm going to close this one for now, but I'll remember it if this comes up a lot. :)

**Comment by CarstenLeue** [comment]
@benlesh ok, I can define my own type, but I do not fully understand why this is a good solution.
In my usecase I'll simply dispatch part of my own input to "fromEvent", so I am sure I want to match that signature exactly to that of fromEvent. Having a reusable type would make this so much easier, at the end "fromEvent" is an API in rxjs, so why not expose all aspects of that API?

You mention that the method might accept less types in the future. I understand that that's possible, but wouldn't that be a breaking change in  the API?
