### ISSUE TITLE
The docs & manual at reactivex.io/rxjs/ don't seem to be up to date for v6

### ISSUE THREAD

**Issue by mattdiamond** [ReactiveX/rxjs#3662]
I'm a bit confused by the online API docs... for example, where is the documentation for the `generate` operator? I'm only seeing 3 items under the `operators` heading, which seems wrong. Am I just looking in the wrong place?

The manual has a section on [creation operators](http://reactivex.io/rxjs/manual/overview.html#creation-operators), but the `generate` link appears to be broken. (Also, the manual describes the old chaining syntax rather than the new pipe syntax.)

I know this is a very recent release, so I understand that there's a lot of work to be done to update everything. When should I expect the v6 documentation to be complete?

**Edit:** Just found https://github.com/ReactiveX/rxjs-docs... I see it's still a work in progress.

**Comment by benlesh** [comment]
Okay, so for now, I have http://reactivex.io/rxjs redirecting to the newer docs (with an HTML redirect unfortunately, until we have the new domain setup)

Sorry for the inconvenience. We're trying to move to a newer documentation system.
