### ISSUE TITLE
delayWhen doesn't emit when the duration selector is empty()

### ISSUE THREAD

**Issue by Airblader** [ReactiveX/rxjs#3663]
**RxJS version:** 6.1.0

**Code to reproduce:**

```
of(42).pipe(() => empty())
  .subscribe(console.log);
```

**Expected behavior:**

This should log `42` immediately, as `empty` completes immediately which according to [the docs](http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#instance-method-delayWhen) should suffice even if the duration selector doesn't emit:

> The source value is emitted on the output Observable only when the duration Observable emits a value or completes.

**Actual behavior:**

The observable completes without emission.

**Comment by Airblader** [comment]
```
of(42).pipe(() => empty().delay(0));
```
does work as intended, so this seems to be an issue with the synchronicity.

**Comment by cartant** [comment]
Looking at the existing implementation of `delayWhen` I found another problem. See #3665 if you are interested in fixing it whilst you are working with that particular operator's implementation. The fix should to into its own PR, of course.

**Comment by Airblader** [comment]
Yeah, I thought about this when first looking at it as well and then just forgot about it. I think my first PR attempt is no good. We'll need a better solution.

**Comment by Airblader** [comment]
OK, `subscribeToResult` memorizes the outerValue, so I think we can use that and be good. Updating the PR.

**Comment by benlesh** [comment]
The OP here isn't valid.  `of(42).pipe(() => empty())` should return `empty`, effectively... so there would be no emission.

**Comment by Airblader** [comment]
@benlesh But this is explicitly documented behavior (which is broken).

**Comment by Airblader** [comment]
@benlesh Sorry, I messed up my OP when editing it. It's missing the delayWhen.

The correct example was

```
of(42).pipe(delayWhen(() => empty()))
  .subscribe(console.log);
```
