### ISSUE TITLE
Disable VS Code's organizeImports feature?

### ISSUE THREAD

**Issue by cartant** [ReactiveX/rxjs#3666]
Should a `.vscode/settings.json` file be added to the RxJS repo to override any user-specified `organizeImports` setting with a workspace setting that disables the feature?

John Papa mentioned it as a possible solution - for dealing with unnecessary re-arrangement of imports in PRs - in [this tweet](https://twitter.com/John_Papa/status/991136803544551425):

![](https://pbs.twimg.com/media/DcE5qWMWAAEWSai.jpg)

**Comment by benlesh** [comment]
I'm relatively indifferent. If people do it, they'll get raspberries during code review is all. I'm okay with them doing it in a separate commit.
