### ISSUE TITLE
 Could not install from "tsconfig.json" as it does not contain a package.json file.

### ISSUE THREAD

**Issue by digish777** [ReactiveX/rxjs#3668]
After upgrading to RXJS 6.1 when I ran this command:
 npm i -g rxjs-tslint rxjs-5-to-6-migrate -p ./tsconfig.json

I got the error.
Could not install from "tsconfig.json" as it does not contain a package.json file.

How to deal with this?

**Comment by benlesh** [comment]
Please file this issue on https://github.com/reactivex/rxjs-tslint
