### ISSUE TITLE
Invalid target event

### ISSUE THREAD

**Issue by caciobanita** [ReactiveX/rxjs#3669]
**RxJS version:**
V. 5.4.x
**Code to reproduce:**
My redux observable epic:

```ts
export const loginEpic = (action$) =>
  action$
    .ofType(LOGIN_REQUEST)
    .debounceTime(1000)
    .mergeMap((action) => {
      return Observable.fromPromise(
        axios.post('auth/login', {
          username: action.payload.username,
          password: action.payload.password,
        })
      )
        .map((response) => response.data)
        .mergeMap((data) => {
          if (data) {
            if (data.errors) {
              return [loginFailure(data.errors)]
            } else {
              return [loginSuccess(data)]
            }
          } else {
            return []
          }
        })
        .catch(() =>
          Observable.of(
            loginFailure({ serverFailureMesssage: 'Login-ul nu a functionat.' })
          )
        )
    })
```

**Expected behavior:**

**Actual behavior:**
I get this error: invalid event target

setupSubscription ../node_modules/rxjs/observable/FromEventObservable.js:189:32

**Additional information:**
React native version 0.55.x
React version 16.2.x

If i run the react native application  i get the above error.

**Comment by benlesh** [comment]
I can't really read the code you have there, and there's no expected behavior.

**Comment by natmegs** [comment]
Hey @caciobanita if you're able to come up with a minimal reproduction case and some more details about what's expected, I'd be happy to take a look! Can't debug your provided code sample as it contains codebase-specific properties like LOGIN_REQUEST

**Comment by caciobanita** [comment]
hello @natmegs 
I have tried to reproduce the error using Expo, i have some errors there, i'm haven't work with expo.

https://snack.expo.io/@aciobanita/rxjs---redux-observable-example

**Comment by benlesh** [comment]
@caciobanita at first glance, I'd say you have some other code that is using `fromEvent` against the wrong object. The problem isn't in the code you've posted, it's somewhere else. Probably something that's feeding into this chain.

**Comment by caciobanita** [comment]
This can be closed. I have update to this v 6.
