### ISSUE TITLE
BehaviourSubject: There should be a way to register a handler without firing it immediately.

### ISSUE THREAD

**Issue by upondeep** [ReactiveX/rxjs#3676]
**RxJS version:**
Current
**Code to reproduce:**
(BehaviourSubject)
**Expected behavior:**
To register a handler without firing the function.
**Actual behavior:**
Immediately firing handler on subscribe
**Additional information:**
There should be a way to do so, cause I want to register the handler first then wait for ".next()" to trigger the handler.

**Comment by cartant** [comment]
There is a way: use `skip(1)`.

**Comment by upondeep** [comment]
I think I tried it before and failed. It appeared to skip all the first value every time I call `.next(value)`. Maybe I didn't do it right. I'll try it again tmr. Thanks for the response.

**Comment by zhaparoff** [comment]
If you don't need the initial state in you subscription, probably, you don't need BehaviourSubject at all and could use usual Subject? Probably with some buffering in a pipe, if you need previous values for later subscriptions.

**Comment by upondeep** [comment]
Alright, it works. Thanks a lot. I'm closing this.   😄
