### ISSUE TITLE
Documentation is actively misleading after release of v6

### ISSUE THREAD

**Issue by b-gran** [ReactiveX/rxjs#3684]
All of the documentation seems to indicate that operators are available on the prototype of Observables. There are dozens or hundreds of examples that all use this model. Here's an example [chosen at random](http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#instance-method-concatAll). This example uses operators on the prototype.

With the release of v6, it looks like all operators are now static functions, which breaks **all of the official documentation and practically every third-party tutorial**, of which there are thousands.

To make matters more confusing, the migration guide doesn't state this very consequential change in straightforward language. In order to figure out what was going on, I had to write some test code and manually examine the prototype of an Observable.

This documentation/API mismatch is serious enough to drive away many new users. Imagine: you read some blog post about why `rxjs` is great, but none of the code works and there isn't even a straightforward migration to make the example work in v6.

#### Proposed actions

At minimum, we should document in the `MIGRATION` file the consequences of the changes to operators, in clear and highly visible language.

We should also be thinking about how the community will be affected by this. Google searches for "do X in `rxjs`" will now turn up non-working code that can't be easily migrated in all cases. 

I've also opened a PR that makes the changed more prominent: #3700

**Comment by ltoshev** [comment]
Completely agree. I had spent hours trying to figure out something, where it just pops up to old documentation and samples! Complete madness!

**Comment by mxhllnn** [comment]
This is my first week using rxjs. I appreciate all of the hard work that has gone into the 6.0 release. However, I am now switching to baconjs because I am losing too much time trying to translate the 5.x documentation to the 6.0 version. It's strange to find a major version, especially one involving significant revision of the API, that has been released without updated documentation. I hope this doesn't sound like piling on. I just want to emphasize that docs are an essential part of the user experience.

**Comment by benlesh** [comment]
The rxjs documentation is in a bit of flux at the moment. We have a new documentation site we're trying to publish this week. Everything on reactivex.io is not to be trust WRT RxJS>

**Comment by benlesh** [comment]
Okay, so for now, I have http://reactivex.io/rxjs redirecting to the newer docs (with an HTML redirect unfortunately, until we have the new domain setup)

Hopefully this will help limit confusion.
