### ISSUE TITLE
skipUntil - v6.1.0 - throws an exception 'unsubscribe' of undefined

### ISSUE THREAD

**Issue by claylaut** [ReactiveX/rxjs#3685]
**RxJS version:** 6.1.0 / 6.0.0 (tested on both)

**Code to reproduce:**
https://stackblitz.com/edit/rxjs-skipuntil-issue

**Expected behaviour:**
it should work without throwing an exception

**Actual behaviour:**
Throwing an exception:
Error in rxjs@6.1.0/internal/operators/skipUntil.js (60:32)
Cannot read property 'unsubscribe' of undefined

**Additional information:**
This issue is related to this change:
https://github.com/ReactiveX/rxjs/pull/3512/files#diff-fb87e1b2c0661f48fca4bf43fb5a19a3R60

**PR including Fix**
https://github.com/ReactiveX/rxjs/pull/3686

This works perfectly in 5.5.10 and lower versions.

**Comment by Stephanemw** [comment]
We're also seeing this using a BehaviorSubject that initially contains undefined (for deferred population).

```typescript
deferredBehaviorSubject = new BehaviorSubject<any>(undefined);
// ... 
obs.pipe(skipUntil(this.deferredBehaviorSubject))
````

Hacking skipUntilSubscriber to add a check works around this, but I don't know enough about rxjs internals to judge if that's the proper approach:
````typescript
if (this.innerSubscription) {
  this.innerSubscription.unsubscribe();
}
````
