### ISSUE TITLE
isObservable(null) throws an exception

### ISSUE THREAD

**Issue by demenskiy** [ReactiveX/rxjs#3687]
**RxJS version:** 6.1.0

**Code to reproduce:**

```ts
import {isObservable} from 'rxjs';

console.log(isObservable(null));
```

**Expected behavior:**

```js
false
```

**Actual behavior:**

```
Error: Cannot read property 'lift' of null
```

**Comment by bbonnet** [comment]
@demenskiy https://github.com/ReactiveX/rxjs/pull/3688 should fix it!
