### ISSUE TITLE
TypeScript interface augmentation for `SymbolConstructor` conflicts with `symbol-observable`

### ISSUE THREAD

**Issue by aikoven** [ReactiveX/rxjs#3697]
**RxJS version:**

`6.1.0`

**Code to reproduce:**

Include `rxjs@6.1.0` and `symbol-observable@1.2.0` into compilation

**Expected behavior:**

No TypeScript errors

**Actual behavior:**

TypeScript error
```
node_modules/rxjs/internal/symbol/observable.d.ts(4,9): error TS2687: 
    All declarations of 'observable' must have identical modifiers.
```

**Additional information:**

Type definition from `symbol-observable`:

```ts
declare global {
  export interface SymbolConstructor {
    readonly observable: symbol;
  }
}
```

Type definition from `rxjs`:

```ts
declare global {
  interface SymbolConstructor {
    observable: symbol;
  }
}
```

Note the difference in `readonly`.

**Comment by JacobChang** [comment]
I don't know whether this will help. But this error happens when compiling code below

    import { ajax } from "rxjs/ajax";

    export function get() {
      return ajax("/api/v1/books");
    }

    get().subscribe(() => console.log('done'))

but when adding import "rxjs";  It works

    import "rxjs"
    import { ajax } from "rxjs/ajax";

    export function get() {
      return ajax("/api/v1/books");
    }

    get().subscribe(() => console.log('done'))

**Comment by benlesh** [comment]
We should be defining it as `readonly` as well.
