### ISSUE TITLE
ResultSelector for MergeMap

### ISSUE THREAD

**Issue by dymafr** [ReactiveX/rxjs#3698]
**RxJS version:**
6.1.0

**Code to reproduce:**
[Stackblitz](https://stackblitz.com/edit/mergemap-result-selector)

**Expected behavior:**

Since 6.0.0-beta.0 it is written in the changelog that:

> mergeMap|concatMap|concatMapTo: mergeMap, concatMap and concatMapTo no longer support a result selector, if you need to use a result selector, use the following pattern: source.mergeMap(x => of(x + x).pipe(map(y => y + x)) (the pattern would be the same for concatMap).

**Actual behavior:**
The resultSelector is still working for mergeMap. 
Should we expect that it will be removed in the future? 

**Additional information:**
Thanks a lot for this amazing library ;)

**Comment by wldcordeiro** [comment]
Migration document says that it will be removed in 7 I think. They just announced the deprecation to give people plenty of time to migrate.

> The resultSelector parameter for first() and last() are removed in v6. If these are used, the code must be updated to run without the rxjs-compat package.

> The resultSelector parameter available for many mapping operators has been deprecated for v6 and the implementation re-written to be much smaller. They will continue to work without the compatibility package, but must be replaced before the v7 release. See Deprecations.

**Comment by martinsik** [comment]
@dymafr https://github.com/ReactiveX/rxjs/blob/master/MIGRATION.md#deprecations

**Comment by dymafr** [comment]
Thanks @wldcordeiro @martinsik
