### ISSUE TITLE
RxJS v6 docs are in repo but not released?

### ISSUE THREAD

**Issue by denisw** [ReactiveX/rxjs#3710]
I was just about to create a PR that updates the _Installation_ page at http://reactivex.io/rxjs/manual/installation.html, which is still describing RxJS 5, only to find out that it has been updated already 2 months ago in GitHub!

Why is it that these and all other v6 changes in the `doc/` folder have not been released to the http://reactivex.io/rxjs site? Right now, the published docs are really misleading.

**Comment by benlesh** [comment]
The docs are in flux right now. We have a brand new documentation site, and we're in the process of getting it published. Sorry for the confusion.

**Comment by benlesh** [comment]
Okay, so for now, I have reactivex.io/rxjs redirecting to the newer docs (with an HTML redirect unfortunately, until we have the new domain setup)

**Comment by staltz** [comment]
Note that the OP was concerned about instructions in the *installation* page and the new docs site also have the same outdated instructions in the installation page: https://beta-rxjsdocs.firebaseapp.com/guide/installation

Another concern is: how does one access the old site, now? In case they want, e.g., to read the long-form tutorial or use the operator selection widget.

**Comment by denisw** [comment]
As @staltz mentioned, the new site seems to have the same outdated state of the docs as the old one when it comes to the guides. Perhaps just redeploy the old ESDoc-based page so that the guides are up-to-date?

By the way, is there a particular reason that there is a new custom-written docs page in the works? Are there any limitations of ESDoc that caused you to make that decision?

**Comment by JWO719** [comment]
The new documentation offers additional opportunities for accessibility for example. Also the old docs were kinda complicated to edit. The new ones should be easier to understand
