### ISSUE TITLE
Cannot call connect() after using publish()

### ISSUE THREAD

**Issue by Niladri24dutta** [ReactiveX/rxjs#3713]
In order to create hot observable i was following the below approach 

 1. Create Observable from `interval()`
 2. Publish that Observable using `publish()` to create a ConnectableObservable
 3. Call `connect()` on that ConnectableObservable

But I am getting the below error - 

`Property 'connect' does not exists on type `Observable<any>` . I know `connect` exists only on `ConnectableObservable` but in Rxjs 5 this below code was working fine. 

    let $hotstream = Observable.interval(1000)
                               .take(6)
                               .publish();
    $hotstream.connect();

**RxJS version:**  6.0.0

**Code to reproduce:**  This is my code for Rxjs 6

    let $hotstream = interval(1000).pipe(take(6),publish());
    $hotstream.connect()

**Expected behavior:** Should be able to call `connect` after using `publish`.

**Actual behavior:** I have to perform an explicit cast like below to call `connect`.
   ` let $hotstream = <ConnectableObservable<any>>interval(1000).pipe(take(6),publish());
    $hotstream.connect();`
   P.S The same issue is occurring for `refCount`. 

**Additional information:** Is it required to do an explicit casting like this to call `connect()` now?
I also noticed few changes in the `publish` method from 5x to 6x version. 
in 5x version the below signature was called -
`export function publish<T>(this: Observable<T>): ConnectableObservable<T>;` 
But in 6x version the signature has changed to -
`export function publish<T>(): UnaryFunction<Observable<T>, ConnectableObservable<T>>;` which basically returns a function that accepts an Obervable parameter and returns a `ConnectableObservable<T>`. So what is the best way to call `connect` in 6x version?

**Comment by cartant** [comment]
See #2972.

**Comment by benlesh** [comment]
Closing as duplicate.
