### ISSUE TITLE
Plans to add SwitchIfEmpty?

### ISSUE THREAD

**Issue by jonahbron** [ReactiveX/rxjs#3714]
The docs for `DefaultIfEmpty` mention a couple of other languages that support a similar operator called `SwitchIfEmpty`

http://reactivex.io/documentation/operators/defaultifempty.html

Are there plans to bring `SwitchIfEmpty` to RxJS, or has it been omitted intentionally?  It would be very handy.

I've found a solution that achieves a similar result when dealing with a single-item observable, but having that operator would make it much easier.

    Observable.of('set value').concat(Observable.of('default value')).first(); // 'set value'
    Observable.empty().concat(Observable.of('default value')).first(); // 'default value'

**Comment by benlesh** [comment]
[defaultIfEmpty](https://github.com/ReactiveX/rxjs/blob/fcbe278125dfa131f73ee0b137f4fb6bf46d25cd/src/operators/index.ts#L20) is a thing already.

Is there something else you needed?

**Comment by jonahbron** [comment]
@benlesh It's not `DefaultIfEmpty` that I need, it's `SwitchIfEmpty`.  Removing a pronoun in my original comment to make that more clear.

**Comment by jonahbron** [comment]
Here's a solution for multi-item streams:

```
const default_placeholder = {};
const defaultObservable = doSomethingByDefault();
Source.defaultIfEmpty(default_placeholder).mergeMap(value => {
	if (value === default_placeholder) {
		return defaultObservable;
	} else {
		return Observable.of(value);
	}
});
```

**Comment by benlesh** [comment]
I see what you're asking for now. Switch seems like the wrong word to me. concatIfEmpty? I dunno. I'll think about this one

**Comment by jonahbron** [comment]
@benlesh I agree concatIfEmpty would make sense, but consistency with the other implementations is desirable.

**Comment by gabrielalan** [comment]
No news about that? I was really in need of something like that and I don't know how to actually handle the situation without it...

I have a Observable that can be empty, and another one that has some pipe calculation. If the 1st is empty I want to use the 2nd... any ideas?

**Comment by cartant** [comment]
@gabrielalan Have a look at https://github.com/cartant/rxjs-etc/blob/master/source/operators/defaultObservableIfEmpty.ts

**Comment by gabrielalan** [comment]
Thanks @cartant

**Comment by simeyla** [comment]
I thought I wanted `defaultIfEmpty` this for this situation:

    obs$.pipe(defaultIfEmpty(throwError('Your source observable was empty')))

But this is even better:

    obs$.pipe(throwIfEmpty(() => 'Your source observable was empty')))

This can be useful in `combineLatest` where an `EMPTY` input deadlocks. You'd put this on every input. Similar to [this](url).

So I feel like I don't really need `defaultIfEmpty(obs: Observable<T>)`, but still curious why it is in some flavors of Rx but not RxJS.

**Comment by BioPhoton** [comment]
@benlesh and @cartant I guess we can close this. Right?

**Comment by jakovljevic-mladen** [comment]
One way to do it with existing operators would be:

```ts
import { EmptyError, Observable } from 'rxjs';
import { catchError, throwIfEmpty } from 'rxjs/operators';

export function solve(first: Observable<string>, second: Observable<string>): Observable<string> {
  return first.pipe(
    throwIfEmpty(),
    catchError((err, caught) => err instanceof EmptyError ? second : caught)
  );
}
```

**Comment by jakovljevic-mladen** [comment]
One way to do it with existing operators would be:
```ts
import { EmptyError, Observable, throwError } from 'rxjs';
import { catchError, throwIfEmpty } from 'rxjs/operators';

export function solve(first: Observable<string>, second: Observable<string>): Observable<string> {
  return first.pipe(
    throwIfEmpty(),
    catchError((err) => err instanceof EmptyError ? second : throwError(err))
  );
}
```

**Comment by kwonoj** [comment]
Closing as userland workaround suggested.

**Comment by kanimaru** [comment]
Heyho @jakovljevic-mladen, 
wouldn't this be the better option:

`import { OperatorFunction } from 'rxjs';
import { EmptyError, Observable, throwError } from 'rxjs';
import { catchError, throwIfEmpty } from 'rxjs/operators';

export function switchIfEmpty<T, U>(fallback: Observable<U>): OperatorFunction<T | null | undefined, T | U> {
  return (source: Observable<T>) => {
    return source.pipe(
        throwIfEmpty(),
        catchError((err) => err instanceof EmptyError ? fallback : throwError(err))
    );
  }
}`

or do I miss something?

**Comment by jakovljevic-mladen** [comment]
@kanimaru, yes, that would be the proper way. When I wrote this, I was quite new to the RxJS.
