### ISSUE TITLE
Redundant tests for the first/last operators

### ISSUE THREAD

**Issue by cartant** [ReactiveX/rxjs#3717]
Whilst fixing the typing problems in the test suite, I found a [seemingly redundant test](https://github.com/ReactiveX/rxjs/blob/6.1.0/spec/operators/first-spec.ts#L173-L230) for the `first` operator:

```ts
it('should support type guards without breaking previous behavior', () => {
```

`first` does not accept a used-defined type guard, so the test does nothing. Indeed, it will fail once type checking is enabled for the test suite.

Whether or not the test should be removed or the signature of `first` should be modified to accept a user-defined type guard, I don't know. Hence the opening of this issue.

**Comment by cartant** [comment]
There is a similar problem with `last`.

**Comment by benlesh** [comment]
Yeah, it just looks poorly written. We do need to make sure that type guards work with operators like `first`, `last`, `filter`, etc.

**Comment by cartant** [comment]
I'll come back and fix these up, then, once the test suite is type-checked. Some overload signatures will need to be added for the type guards to effect narrowed observable types.
