### ISSUE TITLE
Observable.fromEvent and Observable.fromEventPattern T | T[] creates dependency on event handler.

### ISSUE THREAD

**Issue by bafolts** [ReactiveX/rxjs#3720]
**RxJS version:**
rxjs@6.1.0

**Code to reproduce:**
```js
var rx = require("rxjs/index");
require("rxjs/add/observable/fromEventPattern");
require("rxjs/add/operator/take");

var events = [];

rx.Observable.fromEventPattern(
    function add(e) {
        events.push(e);
    },
    function remove() {
        // not implemented for example
    }
)
    .take(2)
    .subscribe((argument) => {
        console.log(argument);
    });

// publish two different methods
events[0].call(null, ["foo", "bar"]);
events[0].call(null, "foo", "bar");
```

**Expected behavior:**
I would expect `argument` to get `["foo", "bar"]` and then `"foo"`

**Actual behavior:**
`argument` always gets `["foo", "bar"]`

**Additional information:**
I am upgrading from RXJS5 to RXJS6. We have some horrible written code which emits events in a liberal fashion where we don't know how many arguments will be provided. I believe in RXJS6 there was a change which now maps that to an array for us. This now makes it difficult to know whether we are getting an array we emitted or the array that RXJS created emitted. I was surprised to see that RXJS6 was creating an array. The `T | T[]` type is difficult to work with. 

https://github.com/ReactiveX/rxjs/blob/master/src/internal/observable/fromEventPattern.ts#L66

**Comment by benlesh** [comment]
If the event has a callback that takes one value, it comes through as a single value. If the event has a callback with more than one value, it is grouped as an array. This change was made to bring `fromEventPattern` inline with `fromEvent`, and it's expected behavior.

Sorry for any confusion.
