### ISSUE TITLE
use debounceTime on angular 6 width RxJs 6

### ISSUE THREAD

**Issue by ldenblyd** [ReactiveX/rxjs#3723]
Hello i just upgrade my web app from angular 5 to 6 and i have a problem width debounceTime

import { debounceTime } from 'rxjs/operators';
this.form.valueChanges.debounceTime(500).subscribe(val => {
   // ...
});

error TS2339: Property 'debounceTime' does not exist on type 'Observable<any>'.

Someone have a solution ?
thanks

**Comment by natmegs** [comment]
If you're using rxjs 6 without rxjs-compat, try 
```
this.form.valueChanges.pipe(debounceTime(500)).subscribe(val => {
...
})
```

**Comment by ldenblyd** [comment]
Yeah It's Work !!

Thanks !!
