### ISSUE TITLE
Bandwidth Quota Exceeded for Docs (Firebase Hosting)

### ISSUE THREAD

**Issue by webberwang** [ReactiveX/rxjs#3726]
The link to the docs https://beta-rxjsdocs.firebaseapp.com can't be accessed.

![image](https://user-images.githubusercontent.com/26264925/40342638-ae35e676-5d40-11e8-9711-e63be2d31961.png)

**Comment by bojoyzhou** [comment]
+1

**Comment by PaulNoth** [comment]
If it helps, at least the manual page is accessible http://reactivex.io/rxjs/manual/index.html

**Comment by andrewckor** [comment]
Still happening, let's wait for a generous sponsor or an unlimited free-plan from Google :D

**Comment by benlesh** [comment]
It's taken care of.

**Comment by franklinyu** [comment]
<https://rxjs-dev.firebaseapp.com/> is also working.
