### ISSUE TITLE
Different behavior of takeUntil in RxJS 5 and 6

### ISSUE THREAD

**Issue by d3lm** [ReactiveX/rxjs#3727]
**RxJS version:** 6.2.0

**Code to reproduce:**

```ts
import { from, interval, of } from 'rxjs';
import { share, filter, takeUntil, tap } from 'rxjs/operators';

const rules = [true, true, true];

const results$ = from(rules).pipe(
  share()
);

const fails$ = results$.pipe(
  filter(value => !value),
  tap(value => console.log('FAIL'))
);

results$.pipe(
  takeUntil(fails$)
).subscribe(value => console.log('SUBSCRIBE', value));
```

**Expected behavior:** There are a two core streams involved in the code above, `results$` and `fails$`. `fails$` is based off of `results$` and filters out all truthy source values, meaning it only emits falsy values. `results$` should now emit values until `fails$` produces a value. So when `results$` synchronously emits 3 values `[true, true, true]`, `fails$` should never emit and it doesn't because of the filter operator. Hence the observer passed to `subscribe` should be called 3 times.

**Actual behavior:**

The next callback should be called 3 times. However, no values are propagated via the observer passed to `results$.subscribe(...)`. When `takeUntil` is removed, everything works as expected. Even if I leave `takeUntil` in and only change the `notifier` to something like `interval(1000)`, it works as expected.

Here's a [StackBlitz](https://stackblitz.com/edit/typescript-534u39?file=index.ts) that demonstrates the issue.

It somehow makes sense in this situation as everything is happning synchronously. This means that `takeUntil` creates a subscription to `fails$`, which then subscribes to `results$`. The thing is that `results$` emits synchronously when `takeUntil` subscibres and it completes so the outer subscription on `results$` will never receive any values. This is just a guess and my shot at explaining this behavior. The weird thing is that it works when using RxJS 5.5.11. Is this some edge case that was "fixed" in RxJS 6 or which one is incorrect?

Here's a [runnable demo](https://stackblitz.com/edit/typescript-ps9d9t?file=index.ts) on StackBlitz.

We have noticed the issue while upgrading MachineLabs to RxJS 6.x. Here's the corresponding [PR](https://github.com/machinelabs/machinelabs/pull/819). Due to failing tests we were able to spot a different behavior, so we started to investigate.

**Comment by benlesh** [comment]
I think the fix to keep sources from being subscribed to if the notifier synchronously emits is what you're setting here: https://github.com/ReactiveX/rxjs/pull/3504

Yes, this is expected behavior.

**Comment by d3lm** [comment]
Thanks for replying to this issue and pointing me to the corresponding PR.
