### ISSUE TITLE
Republish 6.2.0

### ISSUE THREAD

**Issue by clayne11** [ReactiveX/rxjs#3729]
It looks like 6.2.0 doesn't exist in npm.

**Comment by zhaparoff** [comment]
+1

Getting _No matching version found for rxjs-compat@^6.2.0_ while trying to update packages.

Seems like today's issues with NPM registry have affected publish somehow:
https://status.npmjs.org/incidents/b307lbjrdql7
https://status.npmjs.org/incidents/3rjzvts6v98k

**Comment by benlesh** [comment]
Ah... rxjs-compat is missing? Sorry about that.

**Comment by clayne11** [comment]
rxjs 6.2.0 itself also isn't in NPM.

**Comment by benlesh** [comment]
That's... startling, considering I published yesterday and confirmed it multiple times. Checking my logs now.

**Comment by clayne11** [comment]
It shows up [here](https://www.npmjs.com/package/rxjs) but both `npm show rxjs` and `yarn info rxjs` show `6.1.0` as the last published version.

**Comment by benlesh** [comment]
NPM is having issues, apparently... It's showing as 6.2.0 on their [website](https://www.npmjs.com/package/rxjs), but `npm` in terminal is telling a different story.

Seems related to either this bug, or whatever they're trying to fix this bug: https://github.com/npm/npm/issues/20714

**Comment by benlesh** [comment]
![rxjs-on-npm](https://user-images.githubusercontent.com/1540597/40395967-6b58ef3e-5ddf-11e8-8de1-9ba5567bb5f8.png)

**Comment by clayne11** [comment]
So you think it's just going to resolve itself?

**Comment by benlesh** [comment]
@clayne11 I'll give it a bit.. Publishing is currently a bit of a PITA, so I'm hopeful npm resolves the issue themselves. I've filed a ticket.

**Comment by benlesh** [comment]
npm has resolved this <3
