### ISSUE TITLE
Comprehensive marble tests for zip

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#373]
Match current RxJS unit tests with marble tests for zip

Should adhere to the guidelines in our contribution docs.

**Comment by staltz** [comment]
There are still a lot of tests missing to mirror from RxJS 4 (see https://github.com/Reactive-Extensions/RxJS/blob/master/tests/observable/zip.js), so I feel like assigning myself to this task, unless @adrianomelo plans to continue doing marble tests for this like he started with #407.

@blesh ?

**Comment by adrianomelo** [comment]
@staltz,
To be honest, I wasn't expecting replicate all the tests from RxJS 4, but seems fair. I can do this mirroring of tests for zip.

**Comment by adrianomelo** [comment]
Done in #429

I didn't added a failing test. Should I create a new issue?
There is a commit with this test at https://github.com/adrianomelo/RxJS-1/commit/169c05aba266298b8d13f1d8488a29f5d44ef674.

**Comment by staltz** [comment]
This should be closed.
