### ISSUE TITLE
rxJs 6 and IE10

### ISSUE THREAD

**Issue by rbmanian75** [ReactiveX/rxjs#3737]
It is recommended that for ie10 we have to use setprotypeof polyfill.

Is there any recommended npm repository available for this. I tried to use https://www.npmjs.com/package/setprototypeof and got the error module is undefined.

How to fix this issue.

Thanks

**Comment by kwonoj** [comment]
Our supported IE target in v6 is 11, and can't officially comment around lower version unfortunately. For polyfills, we do not have official recommendation too as well unfortunately. Please try out based on your application's need.
