### ISSUE TITLE
AjaxTimeoutError/setPrototypeOf causes fatal crash on Android (React-Native)

### ISSUE THREAD

**Issue by ksaldana1** [ReactiveX/rxjs#3738]
**RxJS version:**
6.0.0

**Code to reproduce:**
I don't have a proper code example, since this is manifesting itself in particular error/network conditions. It seems to happen for any timeout error on a React Native Android APK that is using rxjs/ajax under the hood. 

**Expected behavior:**
Error processed and handled gracefully.

**Actual behavior:**
Fatally crashing app.

**Additional information:**
```
TypeError: undefined is not a function (evaluating 'Object.setPrototypeOf(n,r.prototype)')
  at AjaxTimeoutError(node_modules/rxjs/internal/observable/dom/AjaxObservable.js:392:22)
  at arguments(node_modules/rxjs/internal/observable/dom/AjaxObservable.js:434:28)
  at listener(node_modules/raven-js/src/raven.js:368:71)
  at invariant(node_modules/event-target-shim/lib/event-target.js:171:37)
  at value(node_modules/react-native/Libraries/Network/XMLHttpRequest.js:204:5)
  at XMLHttpRequest(node_modules/react-native/Libraries/Network/XMLHttpRequest.js:433:42)
  at arguments(node_modules/react-native/Libraries/Network/XMLHttpRequest.js:589:18)
  at _lastFlush(node_modules/react-native/Libraries/vendor/emitter/EventEmitter.js:181:40)
  at flushedQueue(node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:357:10)
  at _inCall(node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:119:17)
  at flushedQueue(node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:318:12)
  at value(node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:119:17)
```

This is related to the use of `Object.setPrototypeOf` in the [AjaxObservable](https://github.com/ReactiveX/rxjs/blob/master/src/internal/observable/dom/AjaxObservable.ts#L509) file. Android/RN does not provide this polyfill, so we need to [include it ourselves](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/setPrototypeOf#Polyfill).

Similar issue in [apollo-client](https://github.com/apollographql/apollo-client/issues/3236)

There was a mention of IE10 and below needing this polyfill in the [6.0.0-alpha.1](https://github.com/ReactiveX/rxjs/blob/b8759d00389f3330594930bde61a45f30033e144/CHANGELOG.md) breaking changes, however this wasn't very easy information to find, nor did it cover this particular crash case. If nothing else, I hope this issue can be useful to someone else who runs into it.

**Comment by tuomohopia** [comment]
Did you actually manage to sort this issue out anyhow? I keep hitting the same problem, as outlined here:
https://github.com/ReactiveX/rxjs/issues/3878

**Comment by tuomohopia** [comment]
@ksaldana1 Thanks a lot! 

It indeed does seem to be fixed just with that, except for the custom timeout that I set does not seem to take effect.

**Comment by markgoodyear** [comment]
@ksaldana1 That worked for me too, thanks!

**Comment by spock123** [comment]
Thanks @ksaldana1 

I was on the verge of switching to Axios. Super weird but, wonder why they haven't fixed it yet.

**Comment by ksaldana1** [comment]
@spock123 Glad the fixed helped. 

This is honestly more of an issue with the JavaScript environment bundled with the Android runtime environment in React Native than it is an RxJS issue. `setPrototypeOf` is [widely available](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/setPrototypeOf#Browser_compatibility) across modern browsers, so I agree with the RxJS team's decision to remove it as a documented breaking change in v6.

The polyfill approach will have to do for now until the [JSC is upgraded](https://github.com/facebook/react-native/issues/19737).

**Comment by spock123** [comment]
@ksaldana1  thanks for the information - interesting. Yes, definitely I think this can be closed now. Thanks again.

**Comment by kwonoj** [comment]
it's bit late but yes, our supported target is browser > IE which all have `setPrototypeOf` support. If runtime doesn't support it, it may need to be polyfilled.
