### ISSUE TITLE
Comprehensive marble tests for mergeMap

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#374]
Should duplicate the current RxJS 3/4 tests

Should adhere to our contribution guidelines and operator authoring docs.

**Comment by staltz** [comment]
I assign myself to this.

**Comment by blesh** [comment]
@staltz ... since I can't "assign" you, I'll put myself on it and follow up.

**Comment by staltz** [comment]
All tests for mergeMap are done in PR #423, except for one case: #422

**Comment by staltz** [comment]
I would close this issue because we already have a separate issue for the problematic test, #422.
