### ISSUE TITLE
path-mapping.js paths are broken

### ISSUE THREAD

**Issue by RueDeRennes** [ReactiveX/rxjs#3742]
the folder structure from rxjs package is is another than path-mapping.js
an example (on windows):

rollup search for:
'c:\node_modules\rxjs\_esm5\internal\Subscriber.js'

an entry from the path-mapping.js:
```
{
 "rxjs/util/toSubscriber": "rxjs-compat/_esm5/util/toSubscriber",
}
```

i think the 'internal' segment is missing in the path-mapping.js.

**Comment by RueDeRennes** [comment]
i solved this problem for myself...

rollup externals = `['rxjs', 'rxjs/operators', 'rxjs/webSocket', 'rxjs/ajax', 'rxjs/testing']`
DONE!

**Comment by benlesh** [comment]
Hi, @RueDeRennes, I'm trying to understand this issue. Is there something not configured properly in this library? Do you have replication instructions? Is there a reproduction repo we can look at?

**Comment by kwonoj** [comment]
I'm going to close this as lacks of info, can't determine further with given information.
