### ISSUE TITLE
Add custom headers to WebSocketSubject

### ISSUE THREAD

**Issue by mcelayir** [ReactiveX/rxjs#3743]
Hi All,

I am creating a websocket connection using WebSocketSubject class using the code below.

```ts
 this.socket = new WebSocketSubject<any>(this.wsSubjectConfig);
        this.socket.asObservable().subscribe(
            (m) => {
                this.next(m.data);
            },
            (error: Event) => {
                console.log(error);
                if (!this.socket && !this.reconnectionObservable) {
                    this.reconnect();
                }
            });
```

I want to add custom header to websocket connect request to handle protocol requirements. How can I add custom headers?

RxJS version:5.4.2

**Comment by Qquanwei** [comment]
YOU can using `protocol` options.

```javascript
var ws = new WebSocketSubject({
  url: "ws://example.com/path", 
  protocol: ["protocol1", "protocol2"]
 });
```
will set header
```json
Sec-WebSocket-Protocol: protocol1, protocol2
```

**Comment by benlesh** [comment]
> RxJS version:5.4.2

This *might* be the issue, I'd recommend updating to _at least_ 5.5.11. In the end, I'd recommend updating to 6.0+ (we have [a lot of options](https://github.com/ReactiveX/rxjs/blob/master/MIGRATION.md) on how to do that seamlessly, esp if you're a TypeScript user)
