### ISSUE TITLE
Module not found: Error: Can't resolve 'rxjs/Rx'

### ISSUE THREAD

**Issue by deepshikha02** [ReactiveX/rxjs#3744]
I am using angular CLI and visual studio code. 
my suggested import for Observable is 
import { Observable } from 'rxjs/internal/observable';
although this does not import catch and throw.
import 'rxjs/add/operator/catch';
import 'rxjs/add/observable/throw'
I went through a few issues raised which said to import from import {Observable} from 'rxjs/Rx';
But this gives me a module not found. 
 Node version : v8.9.4
npm version : 5.6.0

I am just extremely new to angular and don't know what I am doing wrong or the corrective steps. 
Please help.

**Comment by natmegs** [comment]
Hey @deepshikha02, which version of RxJS are you using? In version 6, you import Observable as:
`import { Observable } from 'rxjs'`

**Comment by natmegs** [comment]
Also, in RxJS 6 `throw` is now `throwError` and can be imported as
```
import { throwError } from 'rxjs'
and `catch` is now `catchErrror` and can be imported as
```
import { catchError } from 'rxjs/operators'
```

**Comment by kwonoj** [comment]
specifically import site `'rxjs/Rx'` is not exist on v6 at least. As @natmegs suggested, please try with `rxjs` for top-level import.
