### ISSUE TITLE
What happened to rxjs 4.0`delaySubscription` operator?

### ISSUE THREAD

**Issue by kzaher** [ReactiveX/rxjs#3746]
**RxJS version:** 5.x, 6.x

**Code to reproduce:**

```ts
let x: Observable<number>
x.pipe(delaySubscription(1000))
```

**Expected behavior:**

The code should compile.

**Actual behavior:**

Compile error.

**Additional information:**

Hi, I was looking for rxjs 4.0 `delaySubscription` operator. I couldn't find anything in migration docs or compatibility lib. Was this operator removed or is this somewhere on roadmap?

**Comment by kwonoj** [comment]
It's removed in v5 - while migration doc might be outdated, you could assume non-exist operators are mostly deprecated. You may need your own operator to chain via pipe.

**Comment by benlesh** [comment]
@kzaher you can delay subscription yourself a lot of ways:

Something like this will work for a pipeable operator that will do what you want.

```ts
function delaySubscription<T>(time: number) {
  return (source: Observable<T>) => timer(time).pipe(switchMapTo(source));
}

// usage

someObservable.pipe(delaySubscription(1000))
```
