### ISSUE TITLE
[fromEvent] consistency of single / multiple argument event emissions

### ISSUE THREAD

**Issue by j2L4e** [ReactiveX/rxjs#3751]
Taken here from #3362 

The current `fromEvent` implementation emits single argument events unchanged and wraps multiple arguments in an array. There's an edge case I find worth discussing when a single argument is an array:

```ts
fromEvent(myEmitter, 'myEvent').subscribe(console.log);

myEmitter.emit('myEvent', 1);
// 1

myEmitter.emit('myEvent', 1, 2);
// [1, 2]

myEmitter.emit('myEvent', [1, 2]);
// [1, 2]
```

There's no way for the observable consumer to tell cases 2 and 3 apart.

@benlesh mentioned the possibility of undeprecating the `fromEvent` result selector.

Another (breaking) solution that comes to mind would be wrapping single arguments as well: 
```ts
myEmitter.emit('myEvent', 1);
// [1]

myEmitter.emit('myEvent', 1, 2);
// [1, 2]

myEmitter.emit('myEvent', [1, 2]);
// [[1, 2]]
```

**Comment by BioPhoton** [comment]
@kwonoj is there a way to proceed with this or close it?

**Comment by cartant** [comment]
Closing this in favour of #4736 because [this comment](https://github.com/ReactiveX/rxjs/issues/4736#issuecomment-811065078) describes the favoured solution:

> Maybe with all of the functions that do this (`bindCallback` and friends also do this), we could return the result selector, and just the result collector gets `args[]` but the default, without the result selector will always just be the first argument.
>
> So, let's say your `fromEvent` source has 3 args: `number, string, boolean`:   `fromEvent(thing, 'whatever')` would return `Observable<number>` always. BUT, `fromEvent(thing, 'whatever', (a: number, b: string, c: boolean) => of([a, b, c]))` would give you `Observable<[number, string, boolean]>`.
>
> It's an idea. Of course, we'd need to wait a long time to introduce this, because it's a breaking change.
