### ISSUE TITLE
RxJs as a side-effect free library

### ISSUE THREAD

**Issue by filipesilva** [ReactiveX/rxjs#3756]
RxJs is marked as being free from side effects in its package.json:

https://github.com/ReactiveX/rxjs/blob/d7bfc9ddff01bd65c91ed3e4e6cc6930d4ceeae7/package.json#L6

For dead code elimination purposes, being side effect free means that any call to a function in this library whose value is not saved, returned, or thrown can be dropped. 

In other words, since nothing was done with the result of the function call, and the library has no side effects, calling or not calling that function is the same.

While doing some testing on this topic I found a couple of places where RxJs seems to have side effects, causing code to be dropped:

- these lines are dropped since `_enable_super_gross_mode_that_will_cause_bad_things` is false at the module toplevel, and calling `config.useDeprecatedSynchronousErrorHandling =  true` should have no side effects
https://github.com/ReactiveX/rxjs/blob/d7bfc9ddff01bd65c91ed3e4e6cc6930d4ceeae7/src/internal/config.ts#L23-L28

- the following function calls are dropped because nothing is done with their return value
https://github.com/ReactiveX/rxjs/blob/d7bfc9ddff01bd65c91ed3e4e6cc6930d4ceeae7/src/internal/util/Immediate.ts#L16
https://github.com/ReactiveX/rxjs/blob/d7bfc9ddff01bd65c91ed3e4e6cc6930d4ceeae7/src/internal/util/subscribeTo.ts#L18-L19
https://github.com/ReactiveX/rxjs/blob/d7bfc9ddff01bd65c91ed3e4e6cc6930d4ceeae7/src/internal/util/subscribeToArray.ts#L9
https://github.com/ReactiveX/rxjs/blob/d7bfc9ddff01bd65c91ed3e4e6cc6930d4ceeae7/src/internal/util/subscribeToArray.ts#L12
https://github.com/ReactiveX/rxjs/blob/d7bfc9ddff01bd65c91ed3e4e6cc6930d4ceeae7/src/internal/util/subscribeToIterable.ts#L9
https://github.com/ReactiveX/rxjs/blob/d7bfc9ddff01bd65c91ed3e4e6cc6930d4ceeae7/src/internal/util/subscribeToIterable.ts#L12
https://github.com/ReactiveX/rxjs/blob/d7bfc9ddff01bd65c91ed3e4e6cc6930d4ceeae7/src/internal/util/subscribeToIterable.ts#L20-L24
https://github.com/ReactiveX/rxjs/blob/d7bfc9ddff01bd65c91ed3e4e6cc6930d4ceeae7/src/internal/util/subscribeToPromise.ts#L5-L14
https://github.com/ReactiveX/rxjs/blob/d7bfc9ddff01bd65c91ed3e4e6cc6930d4ceeae7/src/internal/Observer.ts#L12

**Additional information:**

I came across this while testing Build Optimizer with ES2015 modules (https://github.com/angular/devkit/pull/981) in Angular.io. The version of RxJs used there is `6.0.0-uncanny-rc.7`.

When using Build Optimizer with ES2015 modules on Angular.io, the page would load, not show any console errors, but remain in a permanent content loading state with a red loading bar at the top. Top nav bar would show but no content was loaded beneath it.

The specific dead code elimination that causes Angular.io to break is the dropped lines in `src/internal/util/subscribeTo.ts`. 

I do not know why this is not a problem with ES5 code.

cc @IgorMinar @benlesh @jasonaden @hansl @gkalpak

**Comment by IgorMinar** [comment]
Theory: Isn't the problem in that setters/getters and lambdas are considered by build optimizer as top level functions? This is wrong. Once the code is transpiled into es5 they all become regular functions and then they are processed correctly.

**Comment by filipesilva** [comment]
@IgorMinar's theory was correct. 

This stemmed from me misunderstanding the semantics of `"sideEffects": false`. I thought it meant library usage was free from side effects but it only means module loading.

Discussed this further with @IgorMinar and he explained it:
> Pure for build optimizer and webpack means that *loading* the module has no non-local side-effects.
> 
> So if the code in a module is used loading the module will execute whatever is at the top level. If we stop using that module, we will stop executing the top level code. If this code had some side-effects outside of the module (monkey patching dom, registering with a global registry, etc) then we could be breaking stuff.
> 
> If however the side effects were local to that module (e. g. Monkey patching a class defined in the same module) then loading or not loading the module has no observable side effects outside of that module.
> 
> And in those cases we can remove the code without anyone noticing.
