### ISSUE TITLE
Rxjs 6 compatibility with systemjs builder broken

### ISSUE THREAD

**Issue by pitAlex** [ReactiveX/rxjs#3757]
With changes in Rxjs 6 regarding import statement I am having trouble trying to find a way to bundle my app without including the entire rx library.

I am not using webpack, but systemjs builder and now this creates a problem:

```import { Subject } from 'rxjs';```

Previously it was just this and the builder could exclude unused things easy.

```import { Subject } from 'rxjs/Subject';```

With the new way the builder will take everything from rxjs ending up with a big bundle size. Anyway around this? Or has it become mandatory for everyone and everything to use webpack and rollup?

**Comment by benlesh** [comment]
I'm not sure what we can do about this without making the API surface area broad and confusing again.

**Comment by benlesh** [comment]
cc @kwonoj

**Comment by kwonoj** [comment]
I haven't used systemjs all time and not sure how to resolve these kind of issues. Does upstream SystemJS have some ideas around this cases? @pitAlex What's recommendation from SystemJS perspective?

**Comment by pitAlex** [comment]
Well, given the structure the only thing I thought of is that for things I use in my code do import { Subject } from "rxjs/internal/Subject" and for a platform like angular, scan the code, take all the imports and construct a dynamic  module "rxjs" that imports from rxjs/internal all the things angular uses. Of course this would need to altered with each upgrade...and its not pretty.

Its just that it doesn't have tree shaking...it could be done through a plugin by keeping track of imports and removing the unused one from the source, but that to me feels that it won't be perfect and take a lot of hard work to make.

**Comment by kwonoj** [comment]
I am honestly admit I don't have insight / possible actions on our end. I'd like to suggest to file upstream issues on systemjs side first to get some details.
