### ISSUE TITLE
errors in next handler shouldn't be scheduled and rethrown async

### ISSUE THREAD

**Issue by Dynalon** [ReactiveX/rxjs#3780]
With the update to `v6` came a change in error handling, where errors in the _observable pipeline_ are caught and rethrown via a scheduled `setTimeout()`. I watched [Ben Leshs v6 intro video with the reasoning of this change](https://www.youtube.com/watch?v=JCXZhe6KsxQ) and understand and agree with the reasoning.

But it seems errors inside of the `onNext` function passed to `subscribe()` are also caught and rethrown via a `setTimeout` scheduler. Code example:

```typescript
import { of } from "rxjs"

const onNext = () => {
    throw new Error("Sample error");
}

const onError = (err) => {
    // This function is not triggered for errors in the onNext function
    // but errors in the observable pipeline
    console.info("Error handler received error: ", err);
}

try {
    of(undefined).subscribe(onNext, onError);
} catch {
    // catch is not triggered here
    console.info("catch triggered");
}
```

Execution result log:
```
/Users/timo/Projects/rxjs6-test/node_modules/rxjs/internal/util/hostReportError.js:9
    setTimeout(function () { throw err; });
                             ^

Error: Sample error
    at SafeSubscriber.onNext [as _next] (/Users/timo/Projects/rxjs6-test/dist/test.js:5:11)
    at SafeSubscriber.__tryOrUnsub (/Users/timo/Projects/rxjs6-test/node_modules/rxjs/internal/Subscriber.js:263:16)
    at SafeSubscriber.next (/Users/timo/Projects/rxjs6-test/node_modules/rxjs/internal/Subscriber.js:201:22)
    at Subscriber._next (/Users/timo/Projects/rxjs6-test/node_modules/rxjs/internal/Subscriber.js:139:26)
    at Subscriber.next (/Users/timo/Projects/rxjs6-test/node_modules/rxjs/internal/Subscriber.js:103:18)
    at Observable._subscribe (/Users/timo/Projects/rxjs6-test/node_modules/rxjs/internal/observable/scalar.js:6:20)
    at Observable._trySubscribe (/Users/timo/Projects/rxjs6-test/node_modules/rxjs/internal/Observable.js:177:25)
    at Observable.subscribe (/Users/timo/Projects/rxjs6-test/node_modules/rxjs/internal/Observable.js:162:93)
    at Object.<anonymous> (/Users/timo/Projects/rxjs6-test/dist/test.js:13:26)
    at Module._compile (module.js:652:30)
```

This is very unexpected to me. While I understand the async nature of the observable pipeline requires the schedule so the errors get noticed on the global error handler, for the `onNext` function I'd expect them to be thrown synchronously as the subscription handler is not of async nature at all.

Now, as a workaround I could put the `try/catch` block inside of the subscription handler:
```typescript
someObservable.subscribe(() => {
    try {
       doSomethingSyncThatThrowsAnError();
    } catch {
        console.info("caught error in the onNext function");
    }
});
```

But the above workaround provides a pitfall which is not easily visible to rxjs beginners: The subscription will not be unsubscribed, and any other possibly added unsubscription handlers to the subscription will not trigger, and  for `share()/publishReplay()`'d observables, the subscription staying intact might cause other unwanted behaviour.

I tested the above code with `rxjs@6.2`. For  the `v5.5` release, the catch block gets correctly executed. Is there any particular reason or requirement for errors in `onNext` functions to be thrown via setTimeout? While I agree that errors in operators should have never been caught in `try/catch` blocks and code that breaks due to this when upgrading to rxjs6 *should* break, I think for the above situation a try/catch block was reasonable all along and might confuse people expecting this behavior when upgrading to v6.

**Comment by jeffrafter** [comment]
@Dynalon 👋I'm running into a similar issue in another project and just wondering if you came up with any solutions?

**Comment by benlesh** [comment]
Sorry for the delayed response.

The reason it is scheduled is actually the same reason we have to schedule errors that are unhandled due to not having an error handler. If an error is thrown in any of the handlers (next, error, or complete), they are part of a call stack that will unwind back through your operators, multicasts, etc. Failing to throw the error on another call stack means that an error in a next handler will not only kill the observable you're in, but it will also cause "producer interference", where an upstream multicast would stop notifying other streams that may have nothing to do with the one that threw an error.

I hope that clarifies things.
