### ISSUE TITLE
Subjects: Own unsubscribe callback.

### ISSUE THREAD

**Issue by fbadiola** [ReactiveX/rxjs#3786]
## Bug Report

**Current Behavior**
When you create an *Observable* you call with function that receives `observer` like first parameter and returns an own unsubscribe callback.
Subject omits these and it's not possible call to own unsubscribe function.

**Reproduction**
https://stackblitz.com/edit/typescript-weeq4t

**Expected behavior**
Subject would be allow set a own unsubscription callback handler.

**Environment**
- Runtime: All node versions. All browsers.
- RxJS version: v6.x

**Possible Solution**
- **Simple way:** Allow constructor subject receive a subscriber callback that returns de unsubscription callback. This way I think break with subject philosophy. 
- Allow Subject constructor (or make setter) set unsubscribe callback and calls it from `Subscription.prototype.unsubscribe` (calls `_unsubscribe`)

**Additional context**
We're using `BehaviorSubject` because we emit data from streaming channel and must save last value emitted. But when all subscribers calls `unsubscribe` method we need be able to cancel streaming flow. Subscribers have no idea from streaming flow only know RxJS subscriptions so they cannot check if there are subscribers listening yet to cancel flow.

**Comment by fbadiola** [comment]
NOTE: I wanna know better implementation you think. When we' have the best solution, I'll code it and send PR.

**Comment by fbadiola** [comment]
Thanks @cartant!
It works fine! Great!
I doesn't know *finalize* operator, thanks for your support.

I'm going to close issue because isn't issue haha!

**Comment by cartant** [comment]
No worries. I just noticed that my suggestion won't behave quite the same as a direct subscription to the `BehaviorSubject`, as only the first subscriber will receive the subject's initial/current value. To get the same behaviour, you could use `publishReplay(1), refCount ()` instead of `share()`.

I often miss things if I post a comment before I've had my morning coffee. :smile:

**Comment by fbadiola** [comment]
Hahaha! Don't worry, @cartant  thanks!!
No coffee, no dev...

![No coffee, no dev](https://cdn.dribbble.com/users/6749/screenshots/2255392/write-code.png)
