### ISSUE TITLE
window pipeable operator conflict with global window?

### ISSUE THREAD

**Issue by xp44mm** [ReactiveX/rxjs#3788]
## Bug Report
```javascript
export { window } from '../internal/operators/window';
```
as title's speak. at least has some of risk. some editor treat `window` as a keyword and highlight red color.

**Comment by benlesh** [comment]
Yeah, we'll probably need to come up with a better name.

Thanks for this report, I'm surprised we didn't think of it.


### Suggested Workaround

```ts
import { window as someOtherName } from 'rxjs/operators';
```

**Comment by xp44mm** [comment]
seem the `of` is keyword also?

**Comment by cartant** [comment]
@xp44mm `of` isn't a [keyword](https://www.ecma-international.org/ecma-262/#sec-reserved-words). This is valid JavaScript:

```js
let of = true;
```

See also https://github.com/ReactiveX/rxjs/issues/3747.

**Comment by xp44mm** [comment]
the `window` maybe rename to `windowed`, witch i have seen in some libraries.

**Comment by benlesh** [comment]
Closing in favor of #5296
