### ISSUE TITLE
Timestamp type used in timestamp operator is exported from internal module

### ISSUE THREAD

**Issue by reppners** [ReactiveX/rxjs#3790]
**RxJS version:**
v6.2.0

**Code to reproduce:**
```
import { Timestamp } from "rxjs/internal/types";
import { timestamp } from "rxjs/operators";
```

**Expected behavior:**
It feels sort of invalid to have to import the type used in an operator from an location under `internal`

**Actual behavior:**
The `Timestamp` type interface should be available without having to import it from `internal` as this is rather a red flag to me.

**Comment by natmegs** [comment]
Hey @reppners, the Timestamp interface is made available from the 'rxjs' import site (`import { Timestamp } from 'rxjs'`
This is because the index.ts file is reexporting everything from the internal/types file:
```
export * from './internal/types';
```

**Comment by reppners** [comment]
Awesome, thank you!

I relied on webstorm's autocompletion to let me choose from available import sites and it didn't suggest the top level module.
