### ISSUE TITLE
Missing marble image for endWith

### ISSUE THREAD

**Issue by moniuch** [ReactiveX/rxjs#3796]
### Documentation Related To Component:
endWith

### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [x] needs example (needs a marble diagram image)

### Description Of The Issue
- The diagram needs to be generated and made available at https://rxjs-dev.firebaseapp.com/img/endWith.png
- jsdoc needs to be updated with the image link

**Comment by martinsik** [comment]
I think you can close this one. It should be fixed in #3846.

**Comment by JWO719** [comment]
Basically you are right and I think this one could be resolved, but I would like to check in the next deployment if it is actually exisiting. So it will stay open, till we can full verify that it is working

**Comment by sajidali** [comment]
@JWO719 long time, no fix. :(

**Comment by PowerKiKi** [comment]
Please close this issue, as it is a duplicate of #4366.
