### ISSUE TITLE
Comprehensive marble tests for toPromise

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#380]
Should duplicate the current RxJS 3/4 tests

Should adhere to our contribution guidelines and operator authoring docs.

**Comment by staltz** [comment]
Seems like this could be closed. 

I don't see the point making marble tests for this operator, and RxJS 3/4 anyway doesn't have comprehensive tests: https://github.com/Reactive-Extensions/RxJS/blob/master/tests/observable/topromise.js

**Comment by blesh** [comment]
I think the thing about this one is it would require a Promise implementation that could use the TestScheduler. We've got some tests around this already, and they're probably enough.
