### ISSUE TITLE
some name duplicate both `rxjs` and `rxjs/operators`

### ISSUE THREAD

**Issue by xp44mm** [ReactiveX/rxjs#3801]
## Bug Report
some name duplicate both `rxjs` and `rxjs/operators`, the name has
onErrorResumeNext

if i want to use `onErrorResumeNext` by static and instance in same file, i will must rename one of them?

and some others has been deprecated in  `rxjs/operators`, but still exists in both:
merge
concat
combineLatest
race
zip

**Comment by benlesh** [comment]
@xp44mm yep, we're aware...all of those that appear in `rxjs/operators` are deprecated and will not be in the next major version of RxJS. Instead, you can use the static versions.
