### ISSUE TITLE
Support React Native EventEmitter type with fromEvent

### ISSUE THREAD

**Issue by ajcrites** [ReactiveX/rxjs#3809]
## Feature Request
React Native defines its own EventEmitter type that it claims is a subset of the Node.js EventEmitter type, but it is a bit different: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-native/index.d.ts#L143

Specifically, `removeListener` returns `void`. The return type of `addListener` and parameters are also different, but this doesn't cause a typing problem.

**Is your feature request related to a problem? Please describe.**
If you attempt to use `fromEvent` with a React Native EventEmitter implementation such as https://github.com/urbanairship/react-native-module you will get a type error:

```ts
fromEvent(UrbanAirship, 'pushReceived');

Argument of type 'typeof UrbanAirship' is not assignable to parameter of type 'FromEventTarget<{}>'.
  Type 'typeof UrbanAirship' is not assignable to type 'ArrayLike<EventTargetLike<{}>>'.
    Index signature is missing in type 'typeof UrbanAirship'.
```

**Describe the solution you'd like**
There are at least two solutions:

1. Add a `ReactNativeEventEmitter` type.
2. Allow `addListener` and `removeListener` for `NodeStyleEventEmitter` to return `any`.

The `isNodeStyleEventEmitter` check can be used for both, but unfortunately I don't think there is a way to know whether the provided EventEmitter is Node.js style or React Native except based on type. However, the return types for `addListener` and `removeListener` are not used, so being able to distinguish between them at runtime won't matter at this time.

**Describe alternatives you've considered**
You can of course do `fromEvent(UrbanAirship as any...` or use `fromEventPattern`, but these are more verbose and you lose type safety you could get from the former.

**Comment by cartant** [comment]
I would like to see the Node-style declarations relaxed, too.

But rather than `any`, I'd like to see the return values declared as `void | {}`. As @ajcrites has pointed out, the return values are not used in RxJS, so this should not be a problem.

Did you want to submit a PR for this, Andrew, or do you want me to do it?

**Comment by ajcrites** [comment]
I'll be happy to -- other than changing the return type to `void | {}`, React Native's `EventEmitter.addListener` handler returns `EmitterSubscription`, so it is incompatible with `NodeEventHandler`. Can we change that return type to `void | {}` as well?

**Comment by cartant** [comment]
I don't think `NodeEventHandler` needs to change, but I do think `symbol` needs to be removed from the first parameter's union type:

```ts
interface NodeStyleEventEmitter {
    addListener: (eventName: string | symbol, handler: NodeEventHandler) => this;
    removeListener: (eventName: string | symbol, handler: NodeEventHandler) => this;
}
declare type NodeEventHandler = (...args: any[]) => void;

interface RelaxedNodeStyleEventEmitter {
    addListener: (eventName: string, handler: NodeEventHandler) => void | {};
    removeListener: (eventName: string, handler: NodeEventHandler) => void | {};
}

interface EmitterSubscription {
    context: any;
}
interface EventEmitterListener {
    addListener(eventType: string, listener: (...args: any[]) => any, context?: any): EmitterSubscription;
}
interface EventEmitter extends EventEmitterListener {
    removeListener(eventType: string, listener: (...args: any[]) => any): void;
}

declare const nodeEmitter: NodeStyleEventEmitter;
declare const reactNativeEmitter: EventEmitter;

const e1: NodeStyleEventEmitter = reactNativeEmitter; // Error
const e2: RelaxedNodeStyleEventEmitter = reactNativeEmitter; // OK
const e3: RelaxedNodeStyleEventEmitter = nodeEmitter; // OK
```

When you submit a PR, could you please add some `type` tests to make sure that actual Node-style event emitters and React Native event emitters play nice with `fromEvent`. Just use interface declarations, like those above, within each `type` test.

See [here](https://github.com/ReactiveX/rxjs/blob/6.2.0/spec/observables/zip-spec.ts#L581-L588) for an example.
