### ISSUE TITLE
Comprehensive marble tests for buffer

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#381]
Should duplicate the current RxJS 3/4 tests

Should adhere to our contribution guidelines and operator authoring docs.

**Comment by staltz** [comment]
Should not yet be closed.

Tests from RxJS 3/4 are mostly covered. Just a few still missing.

**Comment by staltz** [comment]
I can this one.

**Comment by blesh** [comment]
Looks like `bufferToggle` is the last one on this list requiring tests.

**Comment by staltz** [comment]
Yep
