### ISSUE TITLE
Need explanation on documentation

### ISSUE THREAD

**Issue by DullReferenceException** [ReactiveX/rxjs#3811]
- [ ] typo
- [x] documentation doesn't exist
- [x] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue

As someone just trying to figure out how to use `rxjs`, I'm getting extremely confused. The repository description has a link to http://reactivex.io/rxjs which describes itself as a beta site, which isn't clear, so I tried to proceed with its documentation. It lists operators like `flatMap`, however, which are not available, so now I'm not sure if the documentation is actually for version 5 or if it's just wrong. The markdown files in the repo are full of broken links, so I'm unclear if those are a reliable source or not. 

It'd be helpful to describe the status of rxjs@6 documentation right in the readme so we aren't mislead or sent to a dead end. If the answer is "documentation isn't ready yet," then that would be helpful for those of us that don't want to use an undocumented library.

**Comment by benlesh** [comment]
>  has a link to http://reactivex.io/rxjs which describes itself as a beta site, 

Yeah, @JWO719, we can probably remove the beta warning.

> It lists operators like flatMap, however, which are not available

@DullReferenceException... `flatMap` is definitely available. It's an alias for `mergeMap`. Perhaps there's some documentation out of date? Try:

```ts
import { pf, from } from 'rxjs';
import { flatMap } from 'rxjs/operators';

of(1, 2, 3).pipe(flatMap(x => from([x, x, x]))
  .subscribe(x => console.log(x));
```

> The markdown files in the repo are full of broken links

Which ones?

> If the answer is "documentation isn't ready yet," then that would be helpful for those of us that don't want to use an undocumented library.

I understand your frustration. The documentation is ready to use, however, there are undoubtedly holes in the documentation.

**Comment by DullReferenceException** [comment]
Ah, you're right about `flatMap`. I was confused because there's no `flatMap` file in the directory, but I see it in the index. At first I noticed that it was no-longer attached to the prototype, but I understand now that you have to use `.pipe` for most of those operators, something that the [examples docs don't point out](https://rxjs-dev.firebaseapp.com/api/operators/flatMap) (they show the chaining syntax).

As for broken links, I was referring to the markdown docs in this repo, not in the docs repo.  For example, clicking the link to `mergeMap` in here:

https://github.com/ReactiveX/rxjs/blob/master/doc/operators.md

Leads to https://github.com/ReactiveX/rxjs/blob/master/class/es6/Observable.js~Observable.html#instance-method-mergeMap, which is a 404 error.

I'm not sure if the 404s are an oversight or if those documents are obsolete and should be ignored.

**Comment by eppsilon** [comment]
Will the 5.x docs be hosted somewhere on the new site too? Not sure where to go to find them now.

**Comment by JWO719** [comment]
For the beta warning I created an issue, see #3816

**Comment by benlesh** [comment]
@eppsilon, for the most part, the docs aren't that much different, as long as you're 5.5 and higher. If you need a previous version of the docs, they're all in-line next to the code, and you can jump back to them using the tags for this repository (sorry, that's the best we have for now until we are able to get versioning going for the docs) (docs are hard)

**Comment by kievsash** [comment]
Just created a doc (article) about queue vs null scheduler difference. Do we have some documentation issue where i can post it? (https://medium.com/@alexanderposhtaruk/so-how-does-rx-js-queuescheduler-actually-work-188c1b46526e)

**Comment by benlesh** [comment]
This issue is open ended, and I think we can close it as too vague and more of a complaint than anything constructive. This isn't an "undocumented library" although the documentation could use some help from contributors.

@JWO719 we might want to look into having links in the documentation that take people to an edit page on Github to update documentation they're currently looking at?
