### ISSUE TITLE
Type errors for operators that return ConnectableObservable

### ISSUE THREAD

**Issue by natmegs** [ReactiveX/rxjs#3812]
## Bug Report

**Current Behavior**
Operators that return `ConnectableObservable`s (ex: multicast, publish, publishBehavior, etc) lead to type errors when used in V6 with the `pipe` function. 

**Reproduction**

```ts
const connectable = of(1, 2, 3, 4).pipe(multicast((new Subject<number>())));

connectable.subscribe();

connectable.connect();
```
The type error occurs on the last line when calling the `connect()` method:
```ts
[ts] Property 'connect' does not exist on type 'Observable<number>'
```
Because the `pipe` function expects to return an `Observable` type but the operator is actually returning a `ConnectableObservable` with additional methods.

**Expected behavior**
Expect that `pipe` could infer the return type based on the operators.

**Environment**
- Runtime: Node
- RxJS version: 6.x

**Possible Solution**
Seems to me the `pipe` function needs to be able to infer its return type instead of assuming it will be a plain Observable? Or maybe I am just missing something (if so I'd love to know :) )

**Comment by benlesh** [comment]
This is an unfortunate limitation of TypeScript.

You can work around this with a cast:

```ts
const multicast$ = source$.pipe(multicast(new Subject<number>())) as ConnectableObservable<number>;
```
