### ISSUE TITLE
Willing to help on document translation  in Traditional Chinese

### ISSUE THREAD

**Issue by chgc** [ReactiveX/rxjs#3814]
## Feature Request

Angular Taiwan is willing to help on document translate in Traditional Chinese. 
How do we start to help it?

**Comment by benlesh** [comment]
cc @JWO719 @ladyleet

**Comment by ladyleet** [comment]
@chgc hey Kevin! Yeah... we still need to figure out how to get dgeni to work. @petebd so... can we start somehow? is this discussion happening elsewhere?

**Comment by chgc** [comment]
@ladyleet Nope, it isn't any discussion happening yet. I
Just another thought about multi-language document. Have you seen dotnet core document website? They host different language document in separate GitHub repo. (https://github.com/aspnet/Docs.zh-tw).

**Comment by benlesh** [comment]
I think with our _very_ limited resources we just dropped the ball on this one. Probably don't have a lot of time address translations when we still need to flush out our docs more.

@niklas-wortmann, I'm going to close this, but if you see merit in keeping it open, please reopen and assign it to yourself.
