### ISSUE TITLE
Remove Beta Warning

### ISSUE THREAD

**Issue by JWO719** [ReactiveX/rxjs#3816]
The new doc site currently shows a a beta warning in the header. This one can be removed now.

**Comment by felixrabe** [comment]
There are also two different kinds of "beta docs" referenced via http://reactivex.io/rxjs/:

-   https://rxjs-dev.firebaseapp.com/ – `<meta http-equiv="refresh" content="0;url=https://rxjs-dev.firebaseapp.com/" />`

-   https://beta-rxjsdocs.firebaseapp.com/ – `If you're not redirected,
      <a href="https://beta-rxjsdocs.firebaseapp.com/" style="font-weight: bold; color: lightcyan">click here</a>`

**Comment by felixrabe** [comment]
Also, I found the "old docs", available via some Google searches (http://reactivex.io/rxjs/manual/index.html seems like a nice starting point), to be very useful and sometimes more complete.
