### ISSUE TITLE
Malformed "See Also" in Doc Reference

### ISSUE THREAD

**Issue by JWO719** [ReactiveX/rxjs#3817]
Sometimes the @see leads to a wrong formatted Doc Reference.

E.g. The docs of auditTime prints "@see audit @see debounceTime @see delay @see sampleTime @see throttleTime". But also sometimes for example with ArgumentOutOfRangeError, there it prints a seperate "See Also" chapter, how it is should be.

We have consistently create the "See Also" Chapter and find out what causes the error to be aware of that in future prs.

**Comment by martinsik** [comment]
I think you can close this one. It should be fixed in #3846.

**Comment by JWO719** [comment]
closed by #3846
