### ISSUE TITLE
Comprehensive marble tests for bufferCount

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#382]
Should duplicate the current RxJS 3/4 tests

Should adhere to our contribution guidelines and operator authoring docs.

**Comment by staltz** [comment]
Should not yet be closed.

Missing still this test: https://github.com/Reactive-Extensions/RxJS/blob/master/tests/observable/bufferwithcount.js#L176

**Comment by staltz** [comment]
I'll take this one.
