### ISSUE TITLE
Promise-like Subscription chainable callback register

### ISSUE THREAD

**Issue by odahcam** [ReactiveX/rxjs#3829]
## Feature Request

**Is your feature request related to a problem? Please describe.**
This is related to the famous Node.js callback hells.

**Describe the solution you'd like**
The method `.subscribe(next, error, complete)` returns a `Subscription`, it would be nice to call `.next().error().complete()~.finalize()~` on a `Subscription object to register what callbacks we'd like to call. It would allow us to return subscriptions from methods and still add callbacks to it.

**Describe alternatives you've considered**
None, this is just a curious idea with some `async` difficulties to work on.

**Additional context**
I have enough callbacks with the `pipe` operator, I don't wanna a callback hell again. :cry:

**Comment by benlesh** [comment]
So the request here is to add methods to Subscription that allow handling `complete` `next` and `error` events? I'm not sure about this one.

Subscription has a very specific use case. It's designed to be used as a cancellation mechanism, not really a registry point for events.

At the same time, I'm not sure what having those methods for that sort of composition would buy us over simply using what's available at the time `subscribe` is called. Is the goal here to know when a subscription is complete? There are ways to do that. `subscriptoin.add(() => console.log('finalized'))` for example.

There's also the issue that the proposed change here would not align with any existing Observable proposal for the TC39 or the WHATWG.

While it's an interesting design idea, overall, I'm :-1: on this feature request.

Thank you so much for your thoughtful contribution, @odahcam. But not at this time.

**Comment by odahcam** [comment]
Thanks for the nice reply @benlesh. 

I was thinking about fluent design and what Promises vs. Callbacks have teached to us. The new methods would register handlers for each one of the events mentioned and Subscription would execute the handlers for each event when it occours the same way it does with callbacks, but asynchronous and with `n` handlers per event.

I perfectly understand your position and but I still think this would be nice for some cases and still think `rxjs` is a very nice tool. 😄
