### ISSUE TITLE
Finally operator strange behaviour

### ISSUE THREAD

**Issue by MasDevProject** [ReactiveX/rxjs#3831]
## Bug Report

**Current Behavior**
Hi,
I noticed that it not possible to unsubscribe from an Observable (created using an `of` operator) in its `finally` operator.

**Reproduction**

```js
const sub = Observable.of(null)
			.finally(() => {
				debugger; 
				sub.unsubscribe(); // sub in null here
			})
			.subscribe(
				res => console.log(res),
				err => console.log(err)
			);
```

I also noticed that using:
```
.finally(() => sub.unsubscribe())
```
the `subscription` is not typed. It is an `any` and not a `subscription` object.

Adding the brackets it is typed correctly:
```
.finally(() => { sub.unsubscribe() })
```

**Expected behavior**
The subscription object should not be `undefined`.
Not sure if it is a bug or my fault.

**Environment**
- Runtime: Chrome 67
- RxJS version: 5.5.8
- Angular 5

**Comment by martinsik** [comment]
This is the same case as described #3689.

**Comment by cartant** [comment]
It's not a bug. To unsubscribe within the function passed to an operator - or the function passed to `subscribe` as the `next` handler - you do so using the `this` context:

```ts
const sub = Observable.of(null)
    .finally(function (this: Subscription) {
        console.log(this);
        this.unsubscribe();
    })
    .subscribe(
        res => console.log(res),
        err => console.log(err)
    );
```

However, doing this within `finally` is pointless, as the subscription will be unsubscribed immediately after the `finally` operator in any case.

**Comment by MasDevProject** [comment]
Thank you guys.

@cartant 
In my case the observable is "one shot" (http call) so I would like to unsubscribe from it as soon as it completes in order to avoid memory leaks.

I noticed that finally is called when the observable completes, not when it is unsubscribed.

**Comment by cartant** [comment]
@MasDevProject `finally` will be called upon unsubscription - explicit or otherwise. When an observable completes or errors, subscribers are automatically unsubscribed.

**Comment by MasDevProject** [comment]
@cartant I did not know this behavior.
In the angular world everyone is scared about Observable because of the boilerplate code to unsubscribe from them ([article](http://brianflove.com/2016/12/11/anguar-2-unsubscribe-observables/)).
Is good to know that an httpcall observable does not need to be unsubscribed by code.

**Comment by cartant** [comment]
@MasDevProject If you want to understand the expected subscription/unsubscription behaviour, the [Observable Contract](http://reactivex.io/documentation/contract.html) is worth a read.
