### ISSUE TITLE
Migration Guide is too hidden in the documentation menu

### ISSUE THREAD

**Issue by benlesh** [ReactiveX/rxjs#3836]
### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [x] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue

The migration guide shouldn't be hidden in the menu. Let's make it a top-level menu item.

**Comment by JWO719** [comment]
Do you want it as a top level entry in the sidebar or directly in the header?

**Comment by martinsik** [comment]
@benlesh I'd like to know that too :).

**Comment by benlesh** [comment]
I think it's been taken care of, it just wasn't referenced in the pr.
