### ISSUE TITLE
Premature linking to new documentation

### ISSUE THREAD

**Issue by daotoad** [ReactiveX/rxjs#3838]
### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [X] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue

The new beta documentation is so empty that it is useless as anything other than a list of types and methods.  This is particularly troubling as, traditionally, one of the great strengths of this project has been its excellent documentation.

Please provide a link to the old docs (maybe under the beta warning) while the new docs are in beta.

**Comment by JWO719** [comment]
Hi, Thanks for this feedback. What are the points you are missing in the new docs? That would be really valuable feedback so that we can improve it appropriately

**Comment by Knacktus** [comment]
The new doc site has only the reference and a small introduction. All the guides are missing. Where can I find the old documentation? The new one is really useless.

**Comment by daotoad** [comment]
If I go to look for information on an operator, such as `catchError()` or `startsWith()`, I used to get great docs with example code.  Now I just get the function signature.

**Comment by benlesh** [comment]
@Knacktus and @daotoad ... apologies for the issues while we're migrating everything. All of the old documentation content still exist under the `/doc` directory [here](https://github.com/ReactiveX/rxjs/tree/master/doc)

**Comment by daotoad** [comment]
A *lot* more documentation is available now.  The big problem seems to be broken image links, etc.  So, thank you.

However, next time a major rework of the docs is planned, please do not remove access to the old documentation until the new docs approach at least 80% of the functionality of the old.

**Comment by daotoad** [comment]
Can you add a link to it somewhere in the new docs, so that if something is missing, it is easier for people to find?

Maybe under the "Warning: this is a beta site" text in the header?  In small type: **(old documentation may be found here)**.

The new docs and site look like they will eventually be a nice improvement, BTW.

**Comment by benlesh** [comment]
The docs are now all at https://rxjs.dev
