### ISSUE TITLE
import for throwerror 

### ISSUE THREAD

**Issue by hjjobs** [ReactiveX/rxjs#3840]
can anyone tell me what has to be imported for throwError my lint check is failing

**Comment by martinsik** [comment]
```
import { throwError } from 'rxjs';
```

**Comment by benlesh** [comment]
Thank you for answering this one, @martinsik

**Comment by hjjobs** [comment]
import { throwError } from 'rxjs/internal/observable/throwError'; This worked for me. 
import { throwError } from 'rxjs'; This was giving error continuously.

**Comment by martinsik** [comment]
@hjjobs What RxJS version you have?

**Comment by hjjobs** [comment]
"rxjs": "^6.0.0",
"rxjs-compat": "6.0.0",
