### ISSUE TITLE
Error with compat it looks like

### ISSUE THREAD

**Issue by danboone** [ReactiveX/rxjs#3849]
## Bug Report
I upgraded project to angular 6 and rxjs and rxjs compat here is from package.json:
     "rxjs": "^6.2.1",
    "rxjs-compat": "^6.2.1",

Now when i run my app i get this error in the console:

 Unexpected token <
  Evaluating http://localhost:5555/rxjs/add/observable/concat

**Expected behavior**
Expected site to launch as expected

**Comment by benlesh** [comment]
Do you have a reproduction? 

Where in the codebase is the error coming from?

**Comment by danboone** [comment]
No i don't have a reproduction.

Here is the entire error

Error: Unexpected token <
  Evaluating http://localhost:5555/rxjs/add/observable/concat
  Evaluating http://localhost:5555/app/operators.js
  Evaluating http://localhost:5555/app/app.component.js
  Evaluating http://localhost:5555/app/app.module.js
  Evaluating http://localhost:5555/app/main.js
  Loading app/main
    at eval (<anonymous>)
    at evaluate (evaluate.js:106)
    at instantiate.js:394
    at doEvaluateDynamic (register-loader.js:685)
    at register-loader.js:545
    at Object.eval (operators.ts:3)
    at eval (operators.ts:35)
    at eval (operators.ts:35)
    at eval (<anonymous>)
    at evaluate (evaluate.js:106) "GENERIC GFS ERROR"

**Comment by danboone** [comment]
do you need more information still?

**Comment by kwonoj** [comment]
This requires reproducible code to dig, chances are likely related with loader / bundler configuration. Closing as inactive, please feel free to file new issue with details.
