### ISSUE TITLE
Add a deprecations page to the docs site

### ISSUE THREAD

**Issue by benlesh** [ReactiveX/rxjs#3852]
Basically, it would be great if we had a page of what is going to change in the (as of right now unplanned) upcoming major release of RxJS. The idea would be to find all `@deprecated` markers in the source and display information about what's being deprecated and why (we would be able to glean that from the deprecation message)

In a pinch, we could do this manually.

**Comment by JWO719** [comment]
I'll take a look at it!

**Comment by ladyleet** [comment]
@JWO719 any progress on this one?

**Comment by JWO719** [comment]
Unfortunately not  yet. I have generated a JSON file with all the deprecated this, but I have to add a template to render some content

**Comment by ladyleet** [comment]
@JWO719 👍

**Comment by JWO719** [comment]
closed by #3981.... it could be improved to also display deprecated instance or overloaded methods
