### ISSUE TITLE
about rxjs6 pipe operator

### ISSUE THREAD

**Issue by z3214965** [ReactiveX/rxjs#3856]
Hi：i have a question about pipe operator，when filter return false，takeUntil and tap operator Continue to execute？

    const dragObserver = downEventObservable$.pipe(
      map((movement) => this.triggerPick(movement)),
      filter((result) => {
        return result.cesiumEntities !== null && result.cesiumEntities !== undefined
      }),
      mergeMap((result: any) => {
        return moveObservable$.pipe(map((movement: any) => {
          result.movement = movement
          lastMove = result;
          return lastMove;
        }))
      }),
      takeUntil(upObservable$),
      tap(undefined, undefined, () => {
        if (lastMove) {
          const dropEvent = Object.assign({}, lastMove);
          dropEvent.movement.drop = true;
          dropSubject.next(dropEvent);
        }
      })
    );

**Comment by kwonoj** [comment]
pipe operator is nothing different to previous way of operator chaining:

`filter(predicate).mergeMap().takeUntil().`

if predicate doesn't met and filtered out, those element won't be passed into further operator chain.

**Comment by z3214965** [comment]
The above is my code, the completed function is the left mouse button press select object, the mouse moves to change the position of the object, the mouse lifts the end。
now when filter return false , this upObservable$(ConnectableObservable<any>) and tap(ConnectableObservable<any>)  continue to execute，the left mouse button press select object and the mouse moves mergeMap not execute。I don't know why？ my code error？

**Comment by kwonoj** [comment]
you may need to distinguish few things to define what is running. filter prevent emission of source based on predicate, while subscription is still remaining. Takeuntil subscribes to input observable `upObservable` will stay until source subscription reaches completion. If you'd like to clean up all subscription, you have to teardown subscription instead of filter.

**Comment by z3214965** [comment]
@kwonoj 
you mean，i must have two Observable，one control mouse event，the other one control select object?
