### ISSUE TITLE
Comprehensive marble tests for count()

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#386]
Should duplicate the current RxJS 3/4 tests

Should adhere to our contribution guidelines and operator authoring docs.

**Comment by staltz** [comment]
I assign myself. (Can't actually do that in Github so I'll just comment :P)

**Comment by staltz** [comment]
Ok, I remove my assignment because I noticed #406 exists, just before pushing. :P
@blesh we need to really start using the assignee feature here.

**Comment by blesh** [comment]
@staltz can this be closed now? Do we have parody with the old tests?

**Comment by staltz** [comment]
Yes, can be closed
