### ISSUE TITLE
Why is the argument of BehaviorSubject not optional? (d.ts)

### ISSUE THREAD

**Issue by Domvel** [ReactiveX/rxjs#3862]
## Bug Report

**Current Behavior**
The creation of an instance of BehaviorSubject requires to pass the initial value.
But this should be an optional parameter. Like in JavaScript.

**Reproduction**
Try to create BehaviorSubject without any arguments in TypeScript.

```js
let subject = new BehaviorSubject();
```

**Expected behavior**
I expected the same behavior like in JavaScript. The type file should be accept empty initial arguments. Evaluating as undefined? In this case the subscriber should not notificated with the initial value.

**Environment**
- Ionic CLI 3.20.0
- Ionic angular 3.9.2
- cordova 8.0.0
- ionic/app-scripts: 3.1.9
- npm 5.5.1
- os Windows 10

**Possible Solution**
The constructor argument of BehaviorSubject `initial value` should be optional.
In JS you get no error if no argument is passed.

Workaround could be: 
`new BehaviorSubject (undefined)`

**Comment by cartant** [comment]
This behaviour is by-design.

The `BehaviorSubject` class implements a subject that has a current value and, for that reason, an initial value is required.

If you need a subject which doesn't have an initial value, use `Subject`.

To have an `undefined` initial value, you can use `BehaviorSubject` like this:

```ts
const subject = new BehaviorSubject<number | undefined>(undefined);
subject.subscribe(value => console.log(value));
subject.next(1);
```

Which will log:

```
undefined
1
```
