### ISSUE TITLE
Reconsider Removing Result Selectors

### ISSUE THREAD

**Issue by bd60** [ReactiveX/rxjs#3865]
### Documentation Related To Component:

https://github.com/ReactiveX/rxjs/blob/master/docs_app/content/guide/v6/migration.md

### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [x ] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue

Removing result selectors punishes every developer who took advantage of the feature.  The library is rapidly changing and this is yet another breaking change that is punishing developers for taking advantage of the features you provided.  Some amount of backwards compatibility needs to be retained for this lib to be useful in a real world environment.  I understand the desire to reduce package sizes, but realistically as PWA's grow in popularity, it's becoming less and less relevant, how big of a win can removing result selectors possibly be?

**Comment by c69** [comment]
Just use an extra `map`.

See the docs: https://github.com/ReactiveX/rxjs/blob/master/docs_app/content/guide/v6/migration.md#result-selectors

**Comment by bd60** [comment]
I fully understand the recommended approach, the point is that it’s
needlessly punishing developers who took advantage of a feature for little
gain.

**Comment by BioPhoton** [comment]
@bd60 and @benlesh 
As changes are already done and a lot of discussion and decisions related to applied changes were made we can close this one.

**Comment by cartant** [comment]
Closing this because it has been reconsidered and only some of the result selectors have been deprecated. See https://rxjs.dev/deprecations/resultSelector
