### ISSUE TITLE
Really missing "Find the right operator" flow in new site. Need to reference it to the old site without redirect.

### ISSUE THREAD

**Issue by alex-okrushko** [ReactiveX/rxjs#3866]
### Please check those that apply

- [ ] typo
- [ x ] documentation doesn't exist, **but it used to be there**
- [ ] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue

Old site had an extremely useful flow for "Find the right operator". Unfortunately it used to leave at the root of http://reactivex.io/rxjs/ which now redirects to the new site, that doesn't have this flow.

This was one of the most important ways to discover operators for RxJS beginners.
@benlesh can it temporarily moved to some path at the old site that doesn't redirect? Alternatively, is there a cookie/localStorage/queryparam flag I can set to not redirect? Queryparam would actually be ideal, since I can just provide the link to it.

Thanks!

**Comment by slashkite** [comment]
@alex-okrushko Did you mean http://reactivex.io/rxjs/manual/index.html ?

**Comment by alex-okrushko** [comment]
Exactly what @cartant pointed to. And also HUGE +1 for a more visible and easily linkable spot. My typical instructions for the old doc very "open http://reactivex.io/rxjs/ and scroll all the way to the bottom".

**Comment by cartant** [comment]
This should be addressed by https://github.com/ReactiveX/rxjs/pull/4334
