### ISSUE TITLE
please provide official implementation or official replacement for the pausableBuffer

### ISSUE THREAD

**Issue by dmitriyse** [ReactiveX/rxjs#3868]
Probably this is duplicate of the https://github.com/ReactiveX/rxjs/issues/1542

it's a shame, I cannot find any solution across the internet to put in my application pausableBuffer compomnent.
RxJS is aimed to cover all async tasks, But in fact is too poor compared to TPL/C# async ecosystem.

Please provide clear documentation how to create Async Buffer / Channel abstraction in observables ecosystem.

**Comment by dmitriyse** [comment]
```JavaScript
const source = getSomeSourceObservable();
const pauser = new Subject();

// All the magic is here
const pausable = pauser.switchMap(paused => paused ? Observable.never() : source);

pausable.subscription(x => console.log(x));

pauser.next(true);
```

Put somewere in the documentation this patter as a best practice. Please do not force developers to discover this solution in the closed issue through multiple non perfect alternatives.

**Comment by dmitriyse** [comment]
Or better get back pausableBuffer operator. Pattern above it's too mind bending for rxjs noobs.

**Comment by hwhelchel** [comment]
Agree with @dmitriyse here. I'm a pretty proficient developer but am struggling to figure out how to pause and resume an observable. Very much appreciate the work of the project leads. Still, wish this was easier!

**Comment by BioPhoton** [comment]
IMHO there is no need to introduce the `pausableBuffer` as we have the already mentioned solution:

```typescript
const source = interval(500);
const pauser = new Subject();
const pausable = pauser.pipe(switchMap(paused => paused ? NEVER : source);

pausable.subscription(x => console.log(x));
pauser.next(true);
``` 

@JWO719 could you suggest a good place in the docs where we can put this? 
Also please close this issue and if you know the right location you could open a new one with the required change.

**Comment by JWO719** [comment]
For now I don't see any proper place within the documentation for such a scenario. One could write a blog post about that but this is a very specific scenario. If one comes up with a good place within the docs, feel free to file an issue or pr, but in the meantime I will close this issue
