### ISSUE TITLE
Make AnonymousSubject public in v6+

### ISSUE THREAD

**Issue by Sawtaytoes** [ReactiveX/rxjs#3869]
## Feature Request

**Is your feature request related to a problem? Please describe.**
In a prior issue (#2002), `AnonymousSubject` was made public. Problem is, `AnonymousSubject` is no longer in the main `index.js` file in v6. I have to go to `rxjs/internal` to get to it.

**Describe the solution you'd like**
I'd like to see `AnonymousSubject` made public again in v6 and on.

**Describe alternatives you've considered**
Using `rxjs/internal`.

**Additional context**
 In RxJS v5, I made a `SignalRHubConnection` observable for the C# SignalR similar to the `WebSocket` version which also used `AnonymousSubject`. I don't feel comfortable referencing things in `rxjs/internal` for my own observables using internal functionality.

**Comment by frankwallis** [comment]
Reference to same v5 issue: https://github.com/ReactiveX/rxjs/issues/2002

Also I have found that importing from `rxjs/internal` can cause big increases in the webpack bundle size for some reason.

**Comment by kwonoj** [comment]
Related with https://github.com/ReactiveX/rxjs/issues/3513 : eventually we may want to change fate of anonymous subject itself, not sure we'll expose it as public interface at the moment.
