### ISSUE TITLE
Typescript confusion on generics in pipes

### ISSUE THREAD

**Issue by DavidDecraene** [ReactiveX/rxjs#3870]
## Bug Report

**Current Behavior**
Typescript confusion on generics in pipes

**Reproduction**
```js
dataModel = new ReplaySubject<any>(1);
dataModel.pipe(take(1)).subscribe(model => {});
```

Results in typescript error in editor/linter  (but not in angular cli build/serve):
Argument of type 'MonoTypeOperatorFunction&lt;{}>' is not assignable to parameter of type 'UnaryFunction&lt;Observable&lt;any>, Observable&lt;any>>'.
Types of parameters 'source' and 'source' are incompatible.
Type 'Observable&lt;any>' is not assignable to type 'Observable&lt;{}>'.
Types of property 'source' are incompatible. Type 'Observable&lt;any>' is not assignable to type 'Observable&lt;any>'. Two different types with this name exist, but they are unrelated. 

**Environment**
- Runtime: angular 6.0.6, typescript 2.7.2
- RxJS version: 6.2.1, rxjs-compat 6.2.1

Any clue what I should be doing differently here (besides having an &lt;any> subject?)
```js
dataModel.pipe(take<any>(1))
```
Does not resolve this linter error.

**Comment by cartant** [comment]
Please include the declaration of `dataModel`.

**Comment by DavidDecraene** [comment]
It is, see line
dataModel = new ReplaySubject&lt;any>(1);

or better, in my class:
public dataModel = new ReplaySubject&lt;any>(1);

**Comment by cartant** [comment]
With the RxJS version that you've specified - for `rxjs` and `rxjs-compat` - the following does not effect the error that you've described:

```ts
import { ReplaySubject } from "rxjs/ReplaySubject";
import { take } from "rxjs/operators";
const dataModel = new ReplaySubject<any>(1);
dataModel.pipe(take(1)).subscribe(model => {});
```

**Comment by ladyleet** [comment]
Closing this - thanks @cartant for helping!
