### ISSUE TITLE
Spelling bugs

### ISSUE THREAD

**Issue by DickBaker** [ReactiveX/rxjs#3875]
### Documentation Related To Component:

documentation

### Please check those that apply

- [X] typo
- [ ] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue
spelling mistakes(2)

In URL 
https://www.npmjs.com/package/rxjs
text contains "seperate GitHub Repostory"

Please replace with "separate GitHub Repository"

**Comment by ladyleet** [comment]
Ah @benlesh are you the only one that can update this? happy to help if i can.
