### ISSUE TITLE
scan() definition

### ISSUE THREAD

**Issue by Karql** [ReactiveX/rxjs#3879]
Hi!

I've just started my journey with rxjs ;)
Reading overview I've gone to scan() documentation.
After some lecture I thought "why seed is type of T|R"

I checked the source code:
https://github.com/ReactiveX/rxjs/blob/6.2.1/src/internal/operators/scan.ts

Ok seed is type T|R in case of use first value of source when is not passed.
But imo this is correct behavior when T == R

When T != R it can case errors like this:

![scan](https://user-images.githubusercontent.com/173098/42131959-485e3d42-7d0e-11e8-997c-b83025607966.png)

Imo to avoid this seed should be mandatory when T != R.
It imiples on change in definition from:
`export function scan<T, R>(accumulator: (acc: R, value: T, index: number) => R, seed?: R): OperatorFunction<T, R>;`
to:
`export function scan<T, R>(accumulator: (acc: R, value: T, index: number) => R, seed: R): OperatorFunction<T, R>;`

What do you think? Should I create PR for this?

**Comment by bafolts** [comment]
Requiring users to pass the initial value of their seed seems like the safest route. If not requiring users to provide a value for the first seed the final scan really gets `T | R`.

```
export function scan<T, R>(accumulator: (acc: T | R, value: T, index: number) => R, seed?: R): OperatorFunction<T, R>;
```

If not requiring an initial value for the seed `undefined` for the original value would make sense. It is strange to me that the seed becomes of type `T` in this final case.

**Comment by BioPhoton** [comment]
@cartant I believe we can close this issue please correct me if not and in the best case suggest a way to proceed with this
