### ISSUE TITLE
You must provide a root Epic to createEpicMiddleware

### ISSUE THREAD

**Issue by temurih** [ReactiveX/rxjs#3882]
## Bug Report

**Current Behavior**
Error: `Property 'run' does not exist on type 'EpicMiddleware<Action<any>, {}, any, Action<any>>'`
OR
Error: `You must provide a root Epic to createEpicMiddleware`

**Reproduction**

```ts
const epicMiddleware = createEpicMiddleware({
    dependencies: { ... }
});

let middleware: Middleware[] = [];
middleware.push(epicMiddleware);
...

export const configureStore = (initialState: object): Store<IStore> => {
    const store = createStore(
        rootReducer,
        initialState,
        applyMiddleware(...middleware)
    );

    epicMiddleware.run(rootEpic);

    return store;
};
```
This is the error I am getting,

`Property 'run' does not exist on type 'EpicMiddleware<Action<any>, {}, any, Action<any>>'.`

When I change the type of `epicMiddleware` to `any`, then it throws a runtime error, `You must provide a root Epic to createEpicMiddleware`

P.S. I am using the latest version of `redux-observable` (1.0.0)

**Comment by kwonoj** [comment]
I believe this should be reported in redux-observable, as those interfaces are provided by redux-observable, not rxjs.

**Comment by temurih** [comment]
Yes, sorry I had few tabs open, and I thought I was in `redux-observable`.
