### ISSUE TITLE
broken stream after error

### ISSUE THREAD

**Issue by michal90r** [ReactiveX/rxjs#3883]
## Bug Report

**Current Behavior**

After first catched error I cannot make second Api call. Only actions before first error match and trigger api call. 
```export const postCredentialsEpic = action$ =>
  action$.pipe(
    ofType(POST_CREDENTIALS),
    mergeMap(action =>
      apiCall
        .post('/api/users/login', action.credentials)
        .pipe(
          map(ajaxResponse => postCredentialsSuccess(ajaxResponse.response))
        )
    ),
    catchError(e => {
      return of(postCredentialsError(e));
    })
  );

export const postCredentialsError = error => ({
  type: POST_CREDENTIALS_ERROR,
  payload: error.xhr.response,
  error: true
});
```

**Expected behavior**
I would like to trigger action even if error occurs in previous api call
**Environment**
- Runtime: [e.g. Node v10.5.0, Chrome v67.0.3396.99]
- RxJS version: 6.2.1

**Comment by kwonoj** [comment]
same as https://github.com/ReactiveX/rxjs/issues/3815#issuecomment-395660527. 

Once observable meets error, it is terminating condition of observable and no way to continue original stream. To prevent outer observable stops, inner observable should catch error.

**Comment by michal90r** [comment]
Thank you!
