### ISSUE TITLE
Unit tests failed in master branch (under '/docs_app')

### ISSUE THREAD

**Issue by mattyao1984** [ReactiveX/rxjs#3885]
## Bug Report

**Current Behavior**
When running 'npm run test' in master branch under '/docs_app', it throws errors.

**Reproduction**

```
cd docs_app
npm run test
```

**Expected behavior**
Tests should all pass in master branch and there is no error.

**Environment**
- Runtime: Node v9.7.0, NPM v5.6.0
- RxJS version: Latest version

**Possible Solution**
- Check Webpack configurations
- Check Unit-test settings
- Check angular configurations

@JWO719 please review this issue

**Additional context/Screenshots**
![image](https://user-images.githubusercontent.com/2015156/42222723-4a01d318-7f19-11e8-922d-86bab28c3bdf.png)

**Comment by JWO719** [comment]
so the problem is that these tests were all related to angular.io. We should check which of the running tests are useful for us, fix/ remove the broken tests and maybe add new ones depending on the coverage.

**Comment by JWO719** [comment]
#4032 improves the tests and ignores some of the failing. I think for now we can close this and afterwards improve the code coverage of the docs app
