### ISSUE TITLE
Comprehensive marble tests for map

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#389]
Should duplicate the current RxJS 3/4 tests

Should adhere to our contribution guidelines and operator authoring docs.

**Comment by luisgabriel** [comment]
I'll start migrating tests from: https://github.com/Reactive-Extensions/RxJS/blob/master/tests/observable/select.js

**Comment by blesh** [comment]
Okay, great.

**Comment by luisgabriel** [comment]
@blesh Is there a special reason to keep `map()` and `mapTo()` as separate operators?

**Comment by blesh** [comment]
@luisgabriel there are a few reasons:

1. JavaScript doesn't really have "overloading" of methods. You can leverage dynamic typing and reflection to mimic it, but it's not the same thing. because....
2. reflection/type assertions are slow.

For such a commonly used operator as map, I didn't want to incur a penalty at each call to check to see what type of thing was passed to map.

... so.. we have two different operators.

**Comment by luisgabriel** [comment]
@blesh got it. Makes sense. I'll work on some tests for `mapTo()` then.
