### ISSUE TITLE
Link to GitHub Page

### ISSUE THREAD

**Issue by JWO719** [ReactiveX/rxjs#3893]
I think it would be useful to add a link/icon to the rxjs github page.
Maybe there are other Social Media links which could be added here.

**Comment by ladyleet** [comment]
@JWO719 yeah we dont really have any social media links. what link to github page? where? on the docs site you mean?

**Comment by JWO719** [comment]
Yeah of course I was talking about the docs, sorry for being that rough. I think it would be helpful if you could direclty jump to the github project :D

**Comment by martinsik** [comment]
Related: #3180
