### ISSUE TITLE
Observable.of() and Observable.of(void 0) behave differently

### ISSUE THREAD

**Issue by pdkovacs** [ReactiveX/rxjs#3894]
## Bug Report

**Current Behavior**
`Observable.of()` behaves like `Observable.empty()` instead of `Observable.of(void 0)`

**Reproduction**
```
Observable.of()
.subscribe(
    nextValue => console.log("I expect next to be called with undefined"),
    error => console.log("Unlikely erro here"),
    () => console.log("completed")
);
```
Observe that the only line output by the code is "completed". The callback for the next value is never called.

**Expected behavior**
Based on my (admittedly not enormously extensive) JavaScript experience, when a function expects an argument and is called without passing any to it, the function behaves as if the argument was undefined. The presence in the RxJS API of `Observable.empty()` which very specifically covers the case where `completed` is called without calling `next` only reinforces one's expectation that `Observable.of()` will behave "normally" (and differently from `Observable.empty()`).

**Environment**
- Runtime: any (node v8.11.3 in my case)
- RxJS version: any (5.5.11 in my case)
- Not applicable

**Possible Solution**
It would be more intuitive (more consistent with the general JavaScript "experience"), if `Observable.of()` would behave like `Observable.of(void 0)`. At the very least (but not ideally), I would expect the API doc for `Observable.empty()` to mention that it is just a "short-hand" for `Observable.of()`. (A somewhat *longer* (!) "short-hand"...)

**Additional context/Screenshots**
Not applicable

**Comment by cartant** [comment]
Any change to this would be a breaking change, but beyond that, I disagree that this needs to be changed at all.

`of` is essentially a function that takes a variable number of arguments. That is, you can call `of(1)` or `of(1, 2, 3)`, etc. In this way, having `of()` return an empty observable makes sense.

For a standard equivalent of the current behaviour, have a look at `Math.min`. Note that `Math.min()` is not the same as `Math.min(undefined)`. The former returns `Infinity` and the latter returns `NaN`.

**Comment by pdkovacs** [comment]
> takes a variable number of arguments [...] having of() return an empty observable makes sense.

Yep, that makes sense.

>  Math.min() is not the same as Math.min(undefined)

Good to know! :-)

Thanks for the clarifications.
