### ISSUE TITLE
[Discussion] Add Blog to Documentation

### ISSUE THREAD

**Issue by JWO719** [ReactiveX/rxjs#3895]
I think it would be useful to add a blog-like page to the docs with rxjs related blogs.

I see 2 possible solutions for this:

1. Like angular.io we could link to a medium account. 
pro: 
              -  it is a well known blog platform with a lot of features like comments
              - not that much work to setup
con:
              - not that flexible for using code
              - share account details
              - I don't know if it is possible to add a review process before an article is published

2. We could add a new site to the docs, where we reference pages which could be inside the docs_app or across the internet.
pro:
               - more or less easy to prepare
               - kinda flexible with code and other stuff
               - easy to find content to start with
               - review could be done easily via github
cons:
              - no(not easily) blog-like features like comments
              - linked pages could be remove and therefore we reference a dead page or the content changes in a way not compliant to the rxjs code of  conduct.

Any opinions or other solutions?

**Comment by pertrai1** [comment]
@JWO719 is there any way that we can make use of https://github.com/ReactiveX/reactivex.github.io ?

**Comment by JWO719** [comment]
Could you please elaborate what you have in mind, I actually don't get it

**Comment by pertrai1** [comment]
Seeing that it used Jekyll to create the site, I thought we could look over the structure of how the content is being delivered. Once that is done, it could have a section devoted strictly towards RxJS content. One of the pros that this checks off is the use of code reviews for any content that would be added. I think it is very flexible yet also know that it is not the docs site right now. 

Throwing out ideas as they come to me.

**Comment by JWO719** [comment]
I think we can do pretty much the same with dgeni what we are currently using. Therefore I don't see a benefit in using jekyll, or maybe I just don't get it. Theoretically authors could just file a pr with an md in the content folder and this would generate an html page in it. Then we would have the content, but I don't think that many authors will do that. Maybe it would rather be an option for rxjs contributors to use that way. But I'd still prefer a json file with the references. Something like: 
```json
[{
  "title": "some awesome title",
  "author": "some awesome author",
  "level": "beginner",
  "link": "....",
  "tags": ["rxjs", "testing", "dunno", ....],
  "releasedAt": "some date"
}]
```
Those have to be added manually, but I think it would be pretty straightforward to do so and also we could provide search and filter functions easily. Having a component which loads and renders this json file would come with easy unit tests and so on...

**Comment by pertrai1** [comment]
Sure this sounds like a good path to take. I don't know much about dgeni. My only recommendation is that this would be an iterative process. With what we are discussing right now, it could be a longer process of getting external resources available for people. Having one markdown file like I had in the proposed PR could be a good start and could incorporate the same properties that you are showing in your example above. I would consider it to be a phase 1 and phase 2 pipeline of deliverables.

**Comment by JWO719** [comment]
Oh yeah that's totally fine for me. Good suggestions

**Comment by pertrai1** [comment]
@JWO719 cool. I will structure the content based on the JSON format that you have given above in a regular markdown style file. Then while a more thorough external reference is being created, this file can be updated so we have that information to port into the 2nd phase.

**Comment by JWO719** [comment]
With the merge of the external resources, this can be closed IMHO.
