### ISSUE TITLE
Subject constructor when called without `new` should return undefined

### ISSUE THREAD

**Issue by Jabher** [ReactiveX/rxjs#3899]
## Bug report

It would be waaaay better developer experience if `const o = Subject()` would either throw or act like `new Subject()`.
Right now it is acting in weird way, returning, honestly, something weird for some child classes:
```javascript
> Rx.Subject()
{ Observable: { [Function: Observable] create: [Function] },
  ConnectableObservable: [Function: ConnectableObservable],
  GroupedObservable: [Function: GroupedObservable],
  observable: '@@observable',
  Subject: { [Function: Subject] create: [Function] },
  BehaviorSubject: [Function: BehaviorSubject],
  ReplaySubject: [Function: ReplaySubject],
  AsyncSubject: [Function: AsyncSubject],
```

Moreover, as long as this strange object is including `pipe` in it...
```javascript
> Rx.Subject().pipe
[Function: pipe]
```
...it is considered valid `Observable` which brings this **async** error behavior which is totally not good
```javascript
> void Rx.merge(Rx.Subject()).subscribe(console.log)
undefined
> TypeError: You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.
    at Object.exports.subscribeTo (C:\Users\crbru\WebstormProjects\devilbox\detokex-frontend\src_managed\detokex-frontend\node_modules\rxjs\internal\util\subscribeTo.js:42:15)
    at Object.subscribeToResult (C:\Users\crbru\WebstormProjects\devilbox\detokex-frontend\src_managed\detokex-frontend\node_modules\rxjs\internal\util\subscribeToResult.js:7:26)
    at MergeMapSubscriber._innerSub (C:\Users\crbru\WebstormProjects\devilbox\detokex-frontend\src_managed\detokex-frontend\node_modules\rxjs\internal\operators\mergeMap.js:75:38)
    at MergeMapSubscriber._tryNext (C:\Users\crbru\WebstormProjects\devilbox\detokex-frontend\src_managed\detokex-frontend\node_modules\rxjs\internal\operators\mergeMap.js:72:14)
    at MergeMapSubscriber._next (C:\Users\crbru\WebstormProjects\devilbox\detokex-frontend\src_managed\detokex-frontend\node_modules\rxjs\internal\operators\mergeMap.js:55:18)
    at MergeMapSubscriber.Subscriber.next (C:\Users\crbru\WebstormProjects\devilbox\detokex-frontend\src_managed\detokex-frontend\node_modules\rxjs\internal\Subscriber.js:64:18)
```

**Comment by cartant** [comment]
I don't believe that making changes to the behaviour you've described is the responsibility of this package, as the ES5 implementation of `Subject` is generated by TypeScript.

Note that there is an ES2015 distribution of the source under the `_esm2015` directory. And also note that with ES2015, attempting to create an instance of a class without using `new` will effect an error:

```
TypeError: Class constructor Subject cannot be invoked without 'new'
```

Also, TypeScript will effect it's own compile-time error if `new` is not used:

```
[ts] Value of type 'typeof Subject' is not callable. Did you mean to include 'new'?
```

**Comment by Jabher** [comment]
Usually I'm using es2015, but for this specific project I had to use precompiled files :)

So, you're saying it is throwing an error for ES2015 and TS classes, and only for compiled ones it is acting like it's fine, and to `Subject` and its ancestors it is returning some object with `{pipe(): something}`, and for `Observable` it is returning undefined? Sounds like unconsistent behavior, probably it should also throw an error after it is compiled.

**Comment by cartant** [comment]
Well, the TypeScript error is a compile-time error, but, yes, ES2015 will throw a run-time error if you attempt to create a class without using `new`.

> ... and for `Observable` it is returning `undefined`?

I don't understand what you mean by this, but I don't think it matters regarding the point I was making which was that, IMO, the behaviour of the transpiled output is not something for which this RxJS is responsible and any requests for alternate behaviour would be better directed to TypeScript.

IMO, the behaviour affects only users who are using neither ES2015 nor TypeScript and are misusing `Subject` in the first place.

**Comment by Jabher** [comment]
Agree, it is rare case. But on other hand:
1. lot of people do not like TS - I personally use flow, lot of people just do not use typings
2. AFAIK by default webpack and other bundlers (except ts, of course) are importing the es5+imports if possible, otherwise es5. Es2015 bundle is rarely used
3. Rare case producing an extremely unclear and non-consistent error is making people super-confused. I'm 2+ years rxjs user and experienced JS developer and spent 2 days trying to figure out that I simply missed `new` keyword by accident.

Totally not blaming anyone, but I'm pretty sure that behavior of constructors should be consistent all across the environments (which is definitely a bug fix) and can be fixed by simple config update.

If you agree I can do it

**Comment by cartant** [comment]
IMO, it's a TypeScript issue and is not the responsibility of this package.

The RxJS distribution includes ES5 and ES2015 code. And the ES5 code is generated using TypeScript.

I don't believe that this issue warrants tweaking the generated TypeScript output and I would be surprised other members of the core team feel differently about this.

**Comment by Jabher** [comment]
Agreed. 
On one hand - my bad, missed it.
On another - it's weird TS behavior, looked through the issues and this is intended to not be fixed.

Looked through the issues of TS - have a strong feeling this is an intended behavior.

But it's sad that missed `new` can cause such crazy bug.

**Comment by Jabher** [comment]
I think this is really not rxjs issue, so I'm closing it to keep the numbers better
