### ISSUE TITLE
WebSocketSubject is not assignable to Observable

### ISSUE THREAD

**Issue by mpodlasin** [ReactiveX/rxjs#3905]
I try to hide implementation details by returning `WebSocketSubject` as an `Observable`.

User of API should not know what is the source of incoming data.

I end up with type error from typescript - "WebSocketSubject is not assignable to Observable"

**Comment by cartant** [comment]
Do you have a reproduction of the problem? This seems fine:

```ts
import { Observable } from "rxjs";
import { WebSocketSubject } from "rxjs/webSocket";
declare const w: WebSocketSubject<string>;
const o: Observable<string> = w;
```

**Comment by mpodlasin** [comment]
Hey, I am sorry for that. I was between upgrade from 5 to 6 and something must have worked wrong. It works now on latest rxjs version.
