### ISSUE TITLE
Major performance impact in rxjs v6

### ISSUE THREAD

**Issue by Sawtaytoes** [ReactiveX/rxjs#3915]
Using rxjs `6.2.1`, I noticed an greater-than tenfold slowdown in the application I'm working in. I was able to track down the change determined it was the upgrade commit which caused the issue. I even rewrote all my imports and did not use rxjs-compat, but this did not correct the issue. I also made sure there were no multi-parameter operators.

I did not have these performance issue with rxjs `5.5.10`.

The code causing the issue is using redux and redux-observable loading a react-table grid where each cell would load up a component that dispatched a Redux action on mount. This action would be passed a string of styles. Those strings would be rendered in a different area of the page, but would also cause a state change to do so.

Because I cannot open source this project, I would like help creating a testable environment where I could replicate the issue and assist in finding the problem. I also used Chrome's Performance tab and am willing to provide before-and-after profiles; although, I don't know where to host them.

**Comment by kwonoj** [comment]
I believe we should have some reproducible code to verify this, currently it is not easily guess what could be root cause for.

**Comment by Sawtaytoes** [comment]
Would it be helpful to have the saved profile files from Chrome? The rxjs 6 one is 270MB whereas the rxjs 5 one is 8MB. I removed the screenshots from these and can upload them somewhere for examination. It should provide a good look into the actual issue. Sadly, I'm not versed in figuring out exactly what's causing the issue, but once we know that, I could put together a reproducible performance test.

**Comment by kwonoj** [comment]
before sharing profile, mind elaborate what could you reveal in those profiles around bottleneck? if you think rxjs regresses in perf, I think you have some numbers in profile data already.

**Comment by Sawtaytoes** [comment]
The way I know it's the rxjs 6 upgrade from 5 because I can go back to the commit before I did the upgrade, pull down rxjs 6 w/ rxjs-compat, and experience this issue. No other changes necessary.

The different is greater than 10 times slower.

Looking at the profile data, I'm unaware what's specifically causing the issue. I'm not versed in how to read these.

When going through the debugger, I get caught in some loops where I'm hitting the same areas of code over and over again. It looked like those `.next` calls were being called recursively.

This is what I'm seeing in the profiler. I took the entire slice from rxjs 5 and put that on top of the same slice from rxjs6. Notice how the AjaxSubscriber.next gets called a second time in rxjs6 where it's not called again in rxjs5

LEFT rxjs6, RIGHT rxjs5
![image](https://user-images.githubusercontent.com/3948069/42528450-1a22dc3c-8441-11e8-9e27-13b3337acb20.png)

Zooming out some more, I'm seeing it gets called 6 times which could possibly be why this is taking so much longer (rxjs6):
![image](https://user-images.githubusercontent.com/3948069/42528564-7bf8ceee-8441-11e8-933a-16f9326729b0.png)

**Comment by kwonoj** [comment]
Except stack gets deeper, I don't see there's noticeable thing rx is doing wrong - esp. most of stacks are narrowed down by blocking calls to `dispatch`, `onStateChange`, or else which isn't belong to rx itself. Feel free to create new issue if you still think it's rx issue, but please provide minimal reproducible code. Peeking a screenshot of profiling limits to dig down further.

**Comment by Sawtaytoes** [comment]
I understand. I'm not working on this particular project any longer so I can't get an example from it. I'll have to see what I can do in the future if it shows up again. At this point in time, it'd be tough for me to recreate it.
