### ISSUE TITLE
Missing image for forkJoin and skipLast

### ISSUE THREAD

**Issue by gabrielnemeth** [ReactiveX/rxjs#3917]
### Documentation Related To Component:

forkJoin
skipLast
### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue

There are missing 2 marble diagrams for forkJoin and skipLast.
http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#static-method-forkJoin
http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#instance-method-skipLast

![missing](https://user-images.githubusercontent.com/11211316/42570034-dd124382-8512-11e8-8e1e-6283ca023d77.jpg)

**Comment by ladyleet** [comment]
Ccing in @JWO719 - was this included in the new documentation at all? @gabrielnemeth if you'd like to submit a PR for this as well, feel free to! :)

**Comment by JWO719** [comment]
I am really not sure. But I'll check that. Thanks for pointing

**Comment by martinsik** [comment]
I checked `docs_app` in the current `master` and both operators do have images.

![screen shot 2018-07-14 at 13 04 46](https://user-images.githubusercontent.com/238765/42723823-b2ef6d04-8766-11e8-8580-9d0c19f3316d.png)
![screen shot 2018-07-14 at 13 05 15](https://user-images.githubusercontent.com/238765/42723824-b311bd82-8766-11e8-8dea-9727f7ca3274.png)

**Comment by JWO719** [comment]
thanks @martinsik for checking!
