### ISSUE TITLE
"First" operator has been removed but no documentation to say what to use instead

### ISSUE THREAD

**Issue by ChrisDevinePimss** [ReactiveX/rxjs#3918]
I used to use the first() operator to get the first result and close/unsubscribe from the observable but with RXJS 6 the first() operator has been removed and i was wondering what i should use instead. 

Also this should the alternative/s should be added to the upgrade documentation

**Comment by ChrisDevinePimss** [comment]
Your right, thanks I read the docs wrong, i got mixed up with resultSelector first.

This can be closed and thanks

**Comment by ladyleet** [comment]
Thx @bafolts! Closing.
