### ISSUE TITLE
Upgrading to rxjs 6.2.1 creates a typing issue

### ISSUE THREAD

**Issue by fr0** [ReactiveX/rxjs#3919]
## Bug Report

**Current Behavior**
A clear and concise description of the behavior.

```
ERROR in node_modules/atlas-client-web/node_modules/rxjs/internal/symbol/observable.d.ts(4,9): error TS2687: All declarations of 'observable' must have identical modifiers.
src/app/activity-query.ts(58,35): error TS2345: Argument of type 'MonoTypeOperatorFunction<any>' is not assignable to parameter of type 'OperatorFunction<any, any>'.
  Types of parameters 'source' and 'source' are incompatible.
    Type 'Observable<any>' is not assignable to type 'Observable<any>'. Two different types with this name exist, but they are unrelated.
      Types of property 'source' are incompatible.
        Type 'Observable<any>' is not assignable to type 'Observable<any>'. Two different types with this name exist, but they are unrelated.
```

Here is the code that is causing the problem:

```
      this.activitiesRefresh.pipe(takeUntil(done))
        .subscribe(() => { /* ... */    });
```

`activitiesRefresh` is a `Subject<any>`, imported from `'rxjs'`. `takeUntil` is imported from `'rxjs/operators'`.

This issue does not happen with rxjs 6.2.0.

**Environment**
- Runtime: [e.g. Node v${x}, Chrome v${x}]
- RxJS version:
- (If bug is related) Loader, build configuration: [e.g webpack, angular-cli version, config]

```
Node: 8.11.1
rxjs: 6.2.1 (no rxjs-compat)
@types/node: 8.10.18
```

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by cartant** [comment]
> Two different types with this name exist, but they are unrelated.

That sounds like there are multiple versions of `rxjs` in `node_modules`.

Run this command to see what's in there:

```
npm list rxjs
```

**Comment by fr0** [comment]
Here's the output of `yarn list rxjs`:

```
├─ @angular-devkit/architect@0.6.8
│  └─ rxjs@6.2.0
├─ @angular-devkit/build-angular@0.6.8
│  └─ rxjs@6.2.0
├─ @angular-devkit/core@0.6.8
│  └─ rxjs@6.2.0
├─ @angular-devkit/schematics@0.6.8
│  └─ rxjs@6.2.0
├─ @angular/cli@6.0.8
│  └─ rxjs@6.2.0
├─ @schematics/update@0.6.8
│  └─ rxjs@6.2.0
├─ atlas-client-web@1.0.0-alpha.38
│  └─ rxjs@6.2.0
└─ rxjs@6.2.1
```

It does seem odd that 6.2.0 and 6.2.1 are both present. Not sure why that is.

**Comment by rewathkafley** [comment]
Any update on this. I have only one version of RxJs I still get the same errror.
![screen shot 2018-12-12 at 12 34 01 am](https://user-images.githubusercontent.com/9987781/49821884-b7ce9380-fda5-11e8-8ae0-69750f0f8b3f.png)

**Comment by CoreyCole** [comment]
I'm getting this error with a project structure where I'm sharing model files between two sub-projects within one project:
```
Type
    'import(".../bar/node_modules/rxjs/internal/Observable").Observable<any>'
is not assignable to type 
    'import(".../foo/node_modules/rxjs/internal/Observable").Observable<any>'.
          Types of property 'operator' are incompatible.
```
Where my folder structure is like
```
project
└ foo
    └ node_modules
    └ models
└ bar
    └ node_modules
```
Where in the bar project, I import models from foo using relative paths, i.e. `../foo/models/example-model.ts`
