### ISSUE TITLE
rxjs-dev.firebaseapp.com points to wrong analytics account

### ISSUE THREAD

**Issue by StephenFluin** [ReactiveX/rxjs#3920]
### Documentation Related To Component:
https://rxjs-dev.firebaseapp.com/api

### Description Of The Issue
The analytics account points at the wrong GA id. It should not point to: UA-8594346-15

**Comment by JWO719** [comment]
Oh thanks for pointing. Not even thought about that. @benlesh Do we have an analytics account too or should it be just removed?

**Comment by ladyleet** [comment]
@benlesh poking again for this

**Comment by ladyleet** [comment]
@benlesh omg i'm poking you again! but really i'm coming here to say maybe @IgorMinar has access and can help too? // @StephenFluin
