### ISSUE TITLE
ReplaySubject with bufferSize=0 will buffer and emit a value as if bufferSize=1 was used

### ISSUE THREAD

**Issue by Dynalon** [ReactiveX/rxjs#3924]
## Bug Report

**Current Behavior**
The `ReplaySubject` takes a `bufferSize` argument in the constructor. When given a `bufferSize` of `0`, I'd expect it to behave (almost) like a regular `Subject`, so does not buffer any values at all. However, there will be a buffer of length 1 and the `ReplaySubject` behaves as if a `bufferSize` of 1 was given. This happens when omitting the `windowSize` parameter.

**Reproduction**
See <https://stackblitz.com/edit/angular-fcpqzk> or use this code:

```typescript
import { ReplaySubject } from "rxjs"
  
const rs1 = new ReplaySubject<string>(0);
const rs2 = new ReplaySubject<string>(0, Number.POSITIVE_INFINITY);

setTimeout(() => {
    rs1.next("rs1_1 ITEM");
    rs1.next("rs1_2 ITEM");

    rs2.next("rs2_1 ITEM");
    rs2.next("rs2_2 ITEM");
}, 500);

setTimeout(() => {
    rs1.subscribe(rs1Next => console.info({ rs1Next }));
    rs2.subscribe(rs2Next => console.info({ rs2Next }));
}, 1000);
```
** Output **
```
{ rs1Next: 'rs1_2 ITEM' }
{ rs2Next: 'rs2_2 ITEM' }
```

**Expected behavior**
For bufferSize=0 there should be no buffer, and if subscribed after an emit, there should be no emit on the ReplaySubject.

**Environment**
- Runtime: Node 10.5 as well as StackBlitz with Angular6 
- RxJS version: 6.2.2

**Comment by cartant** [comment]
This appears to be by design: https://github.com/ReactiveX/rxjs/blob/6.2.2/src/internal/ReplaySubject.ts#L22

**Comment by SanderElias** [comment]
@Dynalon If you need that behaviour,  can't you use a normal `Subject` instead of a `replaySubject`?
I'm wondering your use-case for this.

I think current behaviour makes sense, one would not use a `replaySubject` and then expect it to behave as a normal `Subject`.

**Comment by Dynalon** [comment]
@SanderElias You are right, if now do use ReplaySubject/Subject based on the bufferSize for my use case. I just wondered if the API should throw an exception or something when trying to pass 0 as an argument as - at least for me - it was pretty unclear that the 0 gets internally ignored and a 1 is assumed.
