### ISSUE TITLE
SelectAfterCompleted operator

### ISSUE THREAD

**Issue by zheeeng** [ReactiveX/rxjs#3925]
## Feature Request

**Is your feature request related to a problem? Please describe.**

I'm gonna to get a sticky pickup effect, as this demo: https://codepen.io/zheeeng/pen/ZjbKeV which is forked from https://codepen.io/joshblack/pen/zGZZjX

To implements this effect, I used `.take()` and `repeat()` to simluate such a process

```text
--+----+-----+-----------------------
  |    |     |
  |    |     ----A----B---C--D-|
  |    ----1----2---3---4--|
  --a--b-|
          SelectAfterCompleted
----a--b---------A----B---C--D----
 ```

stream `----1----2---3---4--|` be depreacted coz it started before a sub stream completed.

**Describe the solution you'd like**

Wish we have such the operator `SelectAfterCompleted`.

**Describe alternatives you've considered**

I used `.take()` and `repeat()` to reaptedly start the main stream after its substream completed. It seems weird.

**(If this is new operator request) describe reason it should be core operator**

The `switch` operator always depreacte the old stream and switch into the newer. We could an operator always keep the old stream and switch after the old one completed

**Comment by cartant** [comment]
Are you sure that [`exhaustMap`](https://rxjs-dev.firebaseapp.com/api/operators/exhaustMap) isn't what you are looking for?

**Comment by zheeeng** [comment]
@cartant Thx, it is. Not being familiar with some newer operators. May ask is there any operator like `window` but not buffering streams?  Assume it is called `cut`, we use it like `mousemove$.cut(mousedown$)` or `mousemove$.cut(mousedown$, mousedown$)`?

**Comment by cartant** [comment]
I'm not sure about what you mean with `window` not buffering.

And I'm not sure of what it is you are talking about with `cut`. If you are looking to obtain only the moves whilst the mouse button is down, the idiomatic mouse up/down/move code looks like this:

```js
const mousedrag$ = mousedown$.pipe(
  switchMap(() => mousemove$.pipe(takeUntil(mouseup$)))
);
```

**Comment by zheeeng** [comment]
@cartant  I want a sticky pickup effect, the first mousedown on an item, pick it up, the next mousedown again put it down. Not the drag effect.

`mousemove$.window(mousedown$)` buffers mousemove$ between mousedowns, `mousemove$.window(mousedown$).flatten()` emit mousemove$ after the second mousedown. I'm looking for an operator is convenient as `window` but it emits mousemove$ between mousedowns

**Comment by zheeeng** [comment]
The assumed `cut` likes;
```text
--+----+-----+---------+------------- md$
+++++++++++++++++++++++++++++++++++++ mm$
    cut
--++++++-----+++++++++++-------------
```

**Comment by cartant** [comment]
FWIW, I was thinking about this this morning.

Unless, you particularly want to subscribe and unsubscribe from the source, it would be simpler to just filter based on the indexed notifier - rather than use `windowToggle`.

If you do want to subscribe and unsubscribe based on the notifier, I'd use something like this [`toggle`](https://github.com/cartant/rxjs-etc/blob/v7.4.0/source/observable/toggle.ts) function - which splits a notifier into several states - in conjunction with the mouse drag [`switchMap` idiom](https://github.com/cartant/rxjs-etc/blob/v7.4.0/source/observable/toggle-spec.ts#L13-L29).

**Comment by zheeeng** [comment]
@cartant Thx for this factory. Maybe I need to dig out some efficient factories/patterns.
