### ISSUE TITLE
Rename all operators that are duplicates of static operators to `xWith` variants

### ISSUE THREAD

**Issue by benlesh** [ReactiveX/rxjs#3927]
concat -> concatWith
zip -> zipWith
merge -> mergeWith

etc.

Related #3798

**Comment by benlesh** [comment]
The plan here, of course, is to add aliases and deprecations in the short term.

**Comment by SanderElias** [comment]
Go for it, one thing less that can cause confusion. While at this, can you make it so that (Not sure this is possible at all) the old operators can't be found anymore by the auto-import tools in editors? 
Every now and then I lose a bit of time because my auto-import tool imported the wrong thing.

**Comment by Pappa** [comment]
I ran into this over the weekend, and spent several hours trying to work out why `concat` wasn't working as expected when I was inadvertently importing the `rxjs/operators` one. Semantically, I think using `...With` is clearer too.

**Comment by jgbpercy** [comment]
As someone that spends a fair bit of time introducing people to rxjs, this is an early pain point. While the two import locations make sense once you're experienced, it's something that seems really arbitrary early on, and the type errors you get from it are not helpful or enlightening to beginners. And even for experienced users it degrades the editor experience... Would be awesome to see fixed in v7!

**Comment by martinsik** [comment]
I think renaming them is a good idea because this confusion keeps popping on StackOverflow regularly and from the error it throws it's not obvious what you're doing wrong.

**Comment by martinsik** [comment]
I'm now thinking if when some static operators like `merge` are marked as deprecated does this issue mean that they won't be deprecated and just renamed?

**Comment by BioPhoton** [comment]
@benlesh 
Is the renaming still a thing? I really really hope so!!!!

**Comment by BioPhoton** [comment]
Following things should be considered:
- combineLatest, merge, concat, zip got deprecated in version 6.0.0-rc.0 and should be removed
-  race got deprecated in version 6.2.0 and should be removed

**Comment by cartant** [comment]
Closing this because it has been done - except for `onErrorResumeNext` which is going to be removed entirely.
