### ISSUE TITLE
functional pipe

### ISSUE THREAD

**Issue by itaied246** [ReactiveX/rxjs#3933]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Hard to reuse pipe of functions.

**Describe the solution you'd like**
Add a new `pipe` function which execute the functions to the last input,
like [`ramda`](https://ramdajs.com/docs/#pipe) `pipe`.

Use case:

I have a `pipe` which uses `mergeMap` to communicate with a database.
If the response was ok (i.e found and updated), then I want to continue the stream,
so to filter out errors or empty updates.
But I use it in several places for several functions:

```js
...
from(startSomeUpdate(arg1, arg2))
        .pipe(
          map(pipe(isNil, not)),
          filter(identity),
          mapTo(e))

...
from(startSomeOtherUpdate(arg1, arg2, arg3))
        .pipe(
          map(pipe(isNil, not)),
          filter(identity),
          mapTo(e))
```
It could be great if I have `pipe` to work like this:

```js
const filterOutEmpty = pipe$(
    map(pipe(isNil, not)),
    filter(identity),
    mapTo(e))

filterOutEmpty(from(startSomeUpdate(arg1, arg2)))
filterOutEmpty(from(startSomeOtherUpdate(arg1, arg2, arg3)))
```

Then we could compose more complex streams:

```js
pipe$(
    map(inc),
    filter(isEven),
    accessDb,
    filterOutEmpty,
    continueWithPipes
)(stream$)
```

And it is all reusable

**Comment by kwonoj** [comment]
Short glimpse without actual try, does `let` works for you? or you are more interested in ergonomics of proposed behavior?

**Comment by itaied246** [comment]
@kwonoj What is `let`?
I know `let` as the new `var` reserved word.

I'm interested in composing `rxjs` `operators`, like the `filterOutEmpty` in the original post

**Comment by kwonoj** [comment]
`let` is operator in rxjs. i.e https://www.learnrxjs.io/operators/utility/let.html

**Comment by cartant** [comment]
@itaied246 are you aware that there is a static `pipe` function that can be used to do something that's close to what you appear to want? See [Combining Operators](https://blog.angularindepth.com/rxjs-combining-operators-397bad0628d0).

**Comment by itaied246** [comment]
@kwonoj I didn't find `let` in the new docs, but it doesn't seems to be what I'm looking for.

@cartant It seems exactly what I need, can't believe I missed it...
I'll try it soon, if it's not what I meant I'll reopen it, thanks !
