### ISSUE TITLE
Operator find does not unsubscribe on match

### ISSUE THREAD

**Issue by TPReal** [ReactiveX/rxjs#3934]
## Bug Report

**Current Behavior**
The `find` operator does not unsubscribe from the source observable when a match is found, but rather only after the result observable is unsubscribed from. This means that `find(()=>true)` behaves differently from `first()`, and the behaviour of `first()` is better.

**Reproduction**
https://rxviz.com/v/1o7zEN08
https://stackblitz.com/edit/typescript-ghjbsy

```js
// Test 1:
let test1='t1';
interval(200).pipe(
  take(10),
  // This happens only once as the interval is unsubscribed from after first() matches.
  tap(()=>test1+='-'),
  first(),
  delay(900),
  map(()=>test1),
).subscribe(v=>console.log(v));

// Test 2:
let test2='t2';
interval(200).pipe(
  take(10),
  // This happens many times because find does not unsubscribe on match.
  tap(()=>test2+='-'),
  find(()=>true),
  delay(900),
  map(()=>test2),
).subscribe(v=>console.log(v));
```

**Expected behavior**
Find should unsubscribe from the source when it matches the first element. It is not justified to hold the subscription as we know that no more elements from the source observable will be useful for us.

**Environment**
- Runtime: Chrome 67.0.3396.87
- RxJS version: 6.2.2

**Comment by cartant** [comment]
This seems related to https://github.com/ReactiveX/rxjs/pull/2457 - which needs to be refactored/rebased for the V6 changes. `find` is not the only operator with this problem.

**Comment by cartant** [comment]
Nope, I was wrong. I'm refactoring #2457 at the moment and the problem is solves is unsubscriptions that are effected in the other direction. That is, the fix within that PR ensures that subscribers are unsubscribed when the **source** completes or errors.

The problem described in this issue is different.
