### ISSUE TITLE
Add "Choose your own operator" back to the docs front page.

### ISSUE THREAD

**Issue by ladyleet** [ReactiveX/rxjs#3936]
### Documentation Related To Component:

Docs

### Please check those that apply

- [ ] typo
- [x ] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue

Re-add back the choose your own operator by copy/pasting the functionality (lol hopefully it's just that) from the old docs repo to the new docs so folks can use it again.

**Comment by jsonberry** [comment]
Started on this one today, porting it into `docs_app/src/app/custom-elements/choose-your-own-operator`

**Comment by cartant** [comment]
Closing this because the associated PR has been merged.
