### ISSUE TITLE
Remove "beta" from docs

### ISSUE THREAD

**Issue by ladyleet** [ReactiveX/rxjs#3937]
### Documentation Related To Component:

Docs

### Please check those that apply

- [x ] typo
- [ ] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue

Per @benlesh let's remove beta from the docs so it stops confusing people. Opening this issue so any "issues" folks have can be discussed. @JWO719 you had some issues but I think all is good? Also, is there an outstanding PR already? Or am I remembering wrong?

**Comment by mattyao1984** [comment]
@ladyleet @JWO719 I can look after this issue if needs to be done. I just did a quick global search the keyword "beta" and I can find them in the following files:

doc: installation.md 
docs_app/content/guide: installation.md
docs_app: package.json
docs_app/scripts: deploy-to-firebase.sh

Perhaps there are other places I am missing. Let me know if it is okay for me to fix these files.

**Comment by JWO719** [comment]
So in general the beta label we used to have is already removed. It might be possible that there are still some beta references but I think that the files listed above aren't about the rxjs docs beta, more some other beta stuff, don't know :D

At the moment there isn't any work todo with this issue, it is used to discuss about this topic. But thanks for your offer!

**Comment by JWO719** [comment]
the label is already removed
