### ISSUE TITLE
Webstorm imports from /internal by default auto-import

### ISSUE THREAD

**Issue by therepo90** [ReactiveX/rxjs#3940]
## Bug Report

**Current Behavior**
When doing auto-import in webstorm it imports by default 
`import { interval } from 'rxjs/internal/observable/interval';`

**Expected behavior**
should import
`import { interval } from 'rxjs'`

**Comment by mattlewis92** [comment]
I had the same problem, but only on certain projects which lead me to believe it was a webstorm issue. What fixed it for me was deleting the project from webstorm, closing webstorm, deleting the `.idea` directory from the root of the project and then re-adding the project into webstorm. After that everything imports properly from `rxjs` 😄

**Comment by stas-kh** [comment]
The same issue on my side.

Looking forward to have it fixed

**Comment by Seedmanc** [comment]
Same happens in Idea, but I'm not sure why shouldn't we import from internals in the first place? What would be the difference?

**Comment by Roman-Simik** [comment]
I can confirm the paths are written properly like is @kwonoj saying.

I have got into this problem recently and figured out the problem - the WebStorm in previous versions had propably **set option to not import RXJS items from the normal path by default**
![image](https://user-images.githubusercontent.com/41468539/48829279-3a010480-ed72-11e8-9a24-43b8f3006d47.png)

**Fix**: Just remove the rxjs/Rx from that "Do not import..." input (located in Settings - Code style - Typescript)
