### ISSUE TITLE
minify version cause Arrray.from() failed under IE11 with es6-shim.js

### ISSUE THREAD

**Issue by waitingsong** [ReactiveX/rxjs#3941]
## Bug Report

**Current Behavior**
Array.from( \<Set\> ) return empty.
rxjs.umd.min.js  version >=6
es6-shim.js v0.35.3

**Reproduction**
```html
<!DOCTYPE html>
<html lang="zh-CN"><head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="renderer" content="webkit">
<title>rxjs test</title>
</head>
<body>
  <h>rxjs test</h>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/es6-shim/0.35.3/es6-shim.js" ></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/rxjs/6.2.2/rxjs.umd.min.js" ></script>

  <script>
  var st = new Set()
  st.add('foo')

  try {
    var arr = Array.from(st)
    console.log(arr)
    alert(arr)
  }
  catch(ex) {
    alert(ex)
  }
  </script>
</body>
</html>

```

**Expected behavior**
Should alert "foo"

**Environment**
- Runtime: [windows7 64bit, IE v11] 
- RxJS version:  all v6  minify version

**Possible Solution**

**Additional context/Screenshots**
No issue with un-compress verison, eg:
>   <script src="https://cdnjs.cloudflare.com/ajax/libs/rxjs/6.2.2/rxjs.umd.js" ></script>

**Comment by cartant** [comment]
The polyfills that are incorporated in the [Closure-built](https://github.com/ReactiveX/rxjs/blob/master/tools/make-closure.js) minified bundle are responsible for this error being effected, but that's as far as I'm gonna take this because ... IE.

**Comment by cartant** [comment]
Closing, as this should be resolved by https://github.com/ReactiveX/rxjs/pull/4487
