### ISSUE TITLE
UMD module name changed from "Rx" to "rxjs"

### ISSUE THREAD

**Issue by martinsik** [ReactiveX/rxjs#3943]
### Documentation Related To Component:

CHANGELOG.md

### Please check those that apply

- [ ] typo
- [X] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue

Everyone who has been using RxJS by importing it with `<script>` for example is used to prefix everything with `Rx` (eg. `Rx.Observable.of`).

This commit https://github.com/ReactiveX/rxjs/commit/556c904ea61a8424e5d24f170b20eadbc05d01f0#diff-6d2911fe563068b8126098588db98a84R28 renamed the module name to `rxjs` but this change is not mentioned in `CHANGELOG.md`.

I don't know if this is intentional or it was just forgotten.

**Comment by cartant** [comment]
FWIW, my understanding is that it was renamed so that the usage can be similar to what would be done with imports, e.g.:

```js
const { of } = rxjs;
const { map } = rxjs.operators;
/* ... etc. */
```

Whether or not this should be in the CHANGELOG or elsewhere, I don't know.

**Comment by benlesh** [comment]
It should probably be added to the `MIGRATION.md`, maybe?

**Comment by macklinu** [comment]
Was this resolved by the `MIGRATION.md` update in #4063?

**Comment by BioPhoton** [comment]
@benlesh I guess we can close this one. If not please let me know whats missing
