### ISSUE TITLE
Bike-shedding: The value of `find` and `findIndex`?

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#396]
It seems to me like `find` and `findIndex` were added to observable purely by the merit of the fact they exist on `Array.prototype`, but I don't feel like they add a lot of value.

`find` itself doesn't to much that is discernible from `first`, IMO. `first` is perhaps better because it allows a default argument.

`findIndex` is of little value, IMO, because Observable doesn't allow random access, what good would getting an index of a thing be?

similarly, an `indexOf` operator doesn't make sense to me. I want to discourage people from thinking that indices mean anything in terms of Observable.

Either way, I think both `find` and `findIndex` can be accomplished with `first` which already exists. However it does make me think that maybe first should have a `resultSelector` similar to something like `mergeMap/flatMap` has.

attn: @mattpodwysocki @trxcllnt

**Comment by blesh** [comment]
@kwonoj this relates to your PR #393

**Comment by staltz** [comment]
Agreed.

**Comment by mattpodwysocki** [comment]
@blesh 

> findIndex is of little value, IMO, because Observable doesn't allow random access, what good would getting an index of a thing be?
> 
> similarly, an indexOf operator doesn't make sense to me. I want to discourage people from thinking that indices mean anything in terms of Observable.

Incorrect, we have an operator that already gets the element at a given index, so any of these index operators are perfectly valid.  Remember `elementAt` anyone?

**Comment by blesh** [comment]
> Remember elementAt anyone?

`elementAt` can be accomplished with `first` also:  `myObs.first((x, i) => i === 3)`.

FWIW, I think `elementAt` is weird. `index` is a misnomer. What does that mean in terms of a "hot" observable? Besides isn't `elementAt` really `skip(n).first()` or `skip(n).take(1)`?

I still think there is no concept of "index" in an observable. "count" maybe, but because of the nature of it, it's never really going to be an index. An index is for random access, imperative-type programming.

Indices only get used for a few things:

1. To randomly access an item in a collection (`var x = arr[i]`)
2. To mutate a value in a collection (`arr[i] = x`)
3. As a location for use in mutating a collection (e.g. `Array.prototype.splice`)
4. As a marker for use in creating a new collection from an existing one: (e.g. `Array.prototype.slice`)

What would an "index" be used for in an Observable? 2 and 3 are doable, but really weird. 1 and 4 are covered with `skip` and `take`. If we wanted to do that in one subscription, why not make a more flexible operator than `elementAt`? something like a `slice` perhaps?

**Comment by blesh** [comment]
I'd just really like to limit the API surface area by giving people everything they need to get what they want done and not have a bunch of redundant operators just because we can make them.

Smaller API surface area generally equates directly with higher adoption rates. Kitchen sink APIs are confusing and off-putting.

**Comment by staltz** [comment]
Everyone will be fine without `elementAt(i)`: just `skip(i).take(1)`.

**Comment by staltz** [comment]
> Smaller API surface area generally equates directly with higher adoption rates.

Yes to this so much. I've been doing a lot of RxJS and still I bump into operators I've never heard of before. Just imagine how much energy is wasted in beginners' neurons when they are going through each operator in a huge list trying to find that one simple and important operator (such as `combineLatest`, `flatMap`, etc) for their problem at hand.

**Comment by roganov** [comment]
+1 to reducing the API surface area
If an operator can be trivially expressed via chaining two existing operator, then I believe it shouldn't be in the library.

**Comment by blesh** [comment]
Issue #401 discusses guidance for this. I'm going to get the ball rolling and move `elementAt` and `distinctUntilKeyChanged` over to an `extended` directory and add a "kitchen-sink" module. I think `find` and `findIndex` belong there as well.

I think `first` should be implemented, and should have a result selector to enable the selection of the index.
