### ISSUE TITLE
[Docs] Ajax is missing

### ISSUE THREAD

**Issue by JWO719** [ReactiveX/rxjs#3961]
For some reason the ajax Observable isn't listed in the documentation. After a brief look into the source code I think there is some api documentation which could be used. I don't know if this might need some updates, but making it available again should be high prio.

Propably related to #3962

**Comment by JWO719** [comment]
I really appreciate your help. So basically there are already some api documentation in the source code but for some reasons it is just not shown in the docs website. At the moment I have no clue what could lead to that behaviour. I just could imagine that in the jsdoc comments there is something like @internal or something like that. But I really don't know at the moment.

**Comment by mattyao1984** [comment]
I am pushing a PR for this issue.

**Comment by JWO719** [comment]
closed by #3984
