### ISSUE TITLE
[Docs] Websocket is missing

### ISSUE THREAD

**Issue by JWO719** [ReactiveX/rxjs#3962]
For some reason the Websocket Observable isn't listed in the documentation. After a brief look into the source code I think there is some api documentation which could be used. I don't know if this might need some updates, but making it available again should be high prio.

Propably related to #3961

**Comment by mattyao1984** [comment]
@JWO719 I am pushing a PR for this issue.

**Comment by JWO719** [comment]
closed by #3984
