### ISSUE TITLE
Adding things like `fromPromise` doesn't work in webpack 4

### ISSUE THREAD

**Issue by mrahhal** [ReactiveX/rxjs#3964]
I've tried countless times upgrading to webpack 4 in one of our big projects, but each time I do I end up getting multiple errors, which I tracked back to rxjs. I haven't opened this issue until after I read so many similar looking problems, but none resolved my issue, and I'm still confused as to why this is happening in the first place.

In someplace, I do:

```ts
import { Observable } from 'rxjs/Observable';

// Use Observable.fromPromise()
```

In `vendor.ts`, which is an entry module that I use to import things, I do this:

```ts
import 'rxjs/add/observable/fromPromise';
```

Please note that this worked completely fine with webpack 3. Only after I update to webpack 4 do I get the problem. Furthermore, if I import from `rxjs/Rx` instead, this particular problem seems to be fixed, which means it's a problem related to `fromPromise` not being imported.

I had the following webpack config before I updated, in webpack 3:

```js
new webpack.optimize.CommonsChunkPlugin({
  names: ['vendor', 'polyfills'],
}),
```

I have this after the update, in webpack 4:

```js
optimization: {
	splitChunks: {
		cacheGroups: {
			vendor: {
				test: /[\\/]node_modules[\\/]/,
				name: 'vendor',
				chunks: 'all',
			},
		},
	},
},
```

**Environment**
- Runtime: all major browsers
- RxJS version: 6.2.2
- Webpack: 4.16.3 (and all versions of webpack 4)

![image](https://user-images.githubusercontent.com/4404199/43324775-a2ce3a8e-91bd-11e8-8961-b79b004bb465.png)

**Comment by mattyao1984** [comment]
Please use `from` instead of `fromPromise` if you are using RxJS 6.2.2. This is duplicated in 
https://github.com/ReactiveX/rxjs/issues/3525

**Comment by mrahhal** [comment]
After tinkering a lot with webpack, it seems to be working now. I have no idea what was wrong, maybe it's just a change in webpack 4.
