### ISSUE TITLE
Typing error on combineLatest detected as deprecated from when using trailing coma

### ISSUE THREAD

**Issue by blackholegalaxy** [ReactiveX/rxjs#3965]
## Bug Report

**Current Behavior**
When we add a trailing coma to the arguments of combinaLatest, then combineLatest is flagged with deprecated type signature and lint errors appear along with deprecation notice

**Reproduction**
- REPL or Repo link:
https://stackblitz.com/edit/angular-v5aknc?file=src%2Fapp%2Fapp.component.ts

As you can see, using a trailing coma:

```js
const combined = combineLatest(
      timerOne,
      timerTwo,
      timerThree, // PLEASE NOTE THAT COMA WHICH CAUSES THE TYPE ERROR
      );
```
Causes the combineLatest to be detected with a resultSelector which of course doesn't exist here.

![image](https://user-images.githubusercontent.com/11064123/43340037-0be56750-91a9-11e8-9001-1b2b608e3700.png)

**Expected behavior**
Adding a trailing coma to combineLatest and similar operators should not trigger the deprecated signature.

Trailing coma is often a requirements in large companies to avoid merge conflicts due only to comas.

**Environment**
- RxJS version: 6.2.2
- Angular any version above 6, CLI same

**Comment by cartant** [comment]
This sounds like a TypeScript problem to me and not an RxJS problem.

The signature with the result selector is deprecated. However, when a trailing comma is specified, the usage could match the deprecated signature and the warning is effected.

**Comment by kwonoj** [comment]
fyi https://github.com/Microsoft/TypeScript/issues/7279#issuecomment-221059525 and some other issues around trailing comma - compiler allows it with somewhat latest version (it wasn't allowed), but it can't provide proper type inference to param signature with overload. In short, this is compiler's behavior we can't resolve.
