### ISSUE TITLE
"throwError" documentation is referenced as "throw"

### ISSUE THREAD

**Issue by cassiomolin** [ReactiveX/rxjs#3979]
### Documentation related to component:

`throwError` documentation is referenced as `throw`

### Please check those that apply

- [x] typo
- [ ] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description of the issue

In the [API reference page](https://rxjs-dev.firebaseapp.com/api), there's no documentation for the `throwError` funtion. However, it's possible to find documentation for the `throw` function, as can be seen in the image below:

![image](https://user-images.githubusercontent.com/2189398/43459664-36cd211a-949c-11e8-817f-3dd71042434f.png)

The URI  `/api/index/function/throwError` is correct, but the title is misleading (`throw`):

![image](https://user-images.githubusercontent.com/2189398/43459766-8c725e00-949c-11e8-9790-ce176991bb6e.png)

The example seems to be correct:

![image](https://user-images.githubusercontent.com/2189398/43459834-d1be0ac2-949c-11e8-9edc-3f8aa51d5c5d.png)

**Comment by cartant** [comment]
Should be resolved by #3980.
