### ISSUE TITLE
Deprecate `create` static methods

### ISSUE THREAD

**Issue by benlesh** [ReactiveX/rxjs#3982]
The `create` static methods, like `Observable.create` and `Subject.create` are rife with problems.

While it's GREAT to have a functional way to create these things without the `new` keyword... it should be noted that:

1. TypeScript hates what we're doing here.
2. `Subject.create` doesn't actually create a `Subject`, but rather an `AnonymousSubject`, which I would REALLY like to rename as `FrankenSubject` because that describes what it is, you basically glue an Observer to an Observable and call it a "Subject".
3. None of the Subjects have a `create` method that makes sense, they all get the one from `Subject` (see 2)
4. Neither does `ConnectableObservable`... it just gets the one from `Observable`.

### Proposal

Deprecate all `create` methods.

Then either:

1. Do nothing - no other library deals with wrapping constructors in functions for people, afaik.
2. Supply lowercase functional versions of each:  `subject`, `behaviorSubject`, `connectableObservable`
3. Make each constructor callable without `new` (the experimental version can do this, but the current version here can't really because we're using ES2015 classes). So like `Observable(fn)` is the same as `new Observable(fn)`

Thoughts?

**Comment by jayphelps** [comment]
I'm for removing `create` methods, then doing nothing for now. Is there an argument for "functional" versions that don't require `new`, other than disliking the keyword?

**Comment by benlesh** [comment]
> Is there an argument for "functional" versions that don't require new, other than disliking the keyword?

1. You can't call ES2015 class constructors properly with `call` or `apply`. 
2. You can pass a constructor to a function that accepts a function and have it realize it needs to be called with `new`.  e.g. `function execute(fn) {  fn(); }`... (UNLESS You try/catch and handle the `TypeError: Class constructor Test cannot be invoked without 'new'` and then call it appropriately, I guess)

Those are really the only solid arguments.

**Comment by cartant** [comment]
> no other library deals with wrapping constructors in functions for people, afaik

FWIW, Leaflet does this. It provides classes and [lower-case factory functions](https://github.com/Leaflet/Leaflet/blob/v1.3.3/src/layer/tile/TileLayer.js#L242-L247).

**Comment by cartant** [comment]
> Make each constructor callable without `new`

Changing `Observable`, etc. to not be a class would be a breaking change, so I don't see how, in v6, the `create` functions could be deprecated and replaced with ctors that are callable without `new`.

My vote would be to deprecate and then do nothing.

**Comment by benlesh** [comment]
Notes from core team meeting: In favor of deprecating `create` methods.

**Comment by tomblachut** [comment]
I wasn't even aware that there are create methods, so +1 for deprecation.

As for what to do next, i think new-less ctors align nicely with web platform, e.g. `Array()` but are not a necessity. This is in contrast with factory functions like [createImageBitmap](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/createImageBitmap) - notice the `create` prefix.

**Comment by dkosasih** [comment]
What would be the deprecate message? or just mark it as deprecate?

**Comment by cartant** [comment]
@dkosasih The message should say something about using `new` instead. E.g. for [`Observable.create`](https://github.com/ReactiveX/rxjs/blob/6.3.0/src/internal/Observable.ts#L44-L55):

```ts
/**
 * Creates a new cold Observable by calling the Observable constructor
 * @static true
 * @owner Observable
 * @method create
 * @param {Function} subscribe? the subscriber function to be passed to the Observable constructor
 * @return {Observable} a new cold observable
 * @nocollapse
 * @deprecated use new Observable instead
 */
static create: Function = <T>(subscribe?: (subscriber: Subscriber<T>) => TeardownLogic) => {
  return new Observable<T>(subscribe);
}
```

**Comment by voliva** [comment]
I found this github issue by trying to find why wasn't `create` being exported as other creation methods such as `from`, `fromEvent`, `interval`, etc.

Is it possible to deprecate this static method, but export a function with the same name? such as this:

```
export const create = <T>(subscribe?: (subscriber: Subscriber<T>) => TeardownLogic) =>
     new Observable<T>(subscribe);
```

**Comment by cartant** [comment]
Closing this because the PR that deprecated the methods has been merged.
