### ISSUE TITLE
Proposal: switchMapIf operator

### ISSUE THREAD

**Issue by cyrilletuzi** [ReactiveX/rxjs#3992]
## Feature Request

**Is your feature request related to a problem? Please describe.**
It happens very often that you need a value which can come from multiple sources you request in some order. For example, you could try in `IndexedDB` first, then if no value in `localStorage`, and last a default value.

If your operations are synchronous, you'll end up with something like this:
```typescript
observableFromFirstSource.pipe(
  map((value) => value ? value : observableFromSecondSource),
  map((value) => value ? value : 'default')
);
```

It will get worse if your operations are asynchronous:
```typescript
observableFromFirstSource.pipe(
  switchMap((value) => value ? of(value) : observableFromSecondSource),
  map((value) => value ? value : 'default')
);
```

As the callback in `switchMap` must return an `Observable`, we have to recreate an `Observable` with the same value.

Those examples are not too complicated, but if your condition becomes a little more complex, you'll need to imbricate in the old style way, which is not the spirit of functional programming:
```typescript
observableFromFirstSource.pipe(
  switchMap((value) => {
    if (someTest) {
      return of(value);
    } else {
     return observableFromSecondSource;
    }
  }),
  map((value) => value ? value : 'default')
);
```

**Describe the solution you'd like**
```typescript
observableFromFirstSource.pipe(
  switchMapIf((value, null) => observableFromSecondSource),
  mapIf((value, null) => 'default')
);
```

Maybe shortcuts too, as the `null` condition is the most frequent:
```typescript
observableFromFirstSource.pipe(
  switchMapIfNull((value) => observableFromSecondSource),
  mapIfNull((value) => 'default')
);
```

**(If this is new operator request) describe reason it should be core operator**
It can be do as a user-land operator but it's a very common case.

**Comment by paulpdaniels** [comment]
I think this can be done pretty readily with existing operators, don't even need user-land stuff.

```typescript
observableFromFirstSource.pipe(
  onErrorResumeNext(observableFromSecondSource),
  defaultIfEmpty('default'),
  take(1)
)
```

**Comment by cyrilletuzi** [comment]
@paulpdaniels The operators you suggest are when there is an error, or when no value is emitted. Which is not the case I present: in my examples, the `Observable`s emit but with a `null` value.

**Comment by cartant** [comment]
@cyrilletuzi See [this comment](https://github.com/ReactiveX/rxjs/issues/3585#issuecomment-382571620).

**Comment by cyrilletuzi** [comment]
OK, I'll see those solutions.
