### ISSUE TITLE
Unsubscription needs code example

### ISSUE THREAD

**Issue by Med-Seif** [ReactiveX/rxjs#3993]
### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [x] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue

```javascript
var observable = Rx.Observable.create(function subscribe(observer) {
    //Keep track of the interval resource
    var intervalID = setInterval(() => {
        observer.next('hi');
    }, 1000);
    // Provide a way of canceling and disposing the interval resource
    return function unsubscribe() {
        clearInterval(intervalID);
    };
});
```

In this example, there is no description of how we can call unubscribe from the observable variable.

How can We use the return variable?

```javascript
 ....
 return function unsubscribe() {
        clearInterval(intervalID);
    };
...
```
Thank you

**Comment by moreJs** [comment]
there is no unubscribe function in Observable, but in Subscription. so you must subscribe the Observable, then use unubscribe in Subscription. code like this:

    observable.subscribe(() => { dosomething(...)})
                .unsubscribe();

**Comment by Brooooooklyn** [comment]
```ts
observable.subscribe(() => { dosomething(...)})
  .unsubscribe();
```
haha, never use `unsubscribe` in this way, or the `dosomething` will never be called.

```ts
const subscription = observable.subscribe(...);

setTimeout(() => {
  subscription.unsubscribe() // clearInterval 1000 ms later
}, 1000)
```

**Comment by moreJs** [comment]
@Brooooooklyn  you u right.

**Comment by benlesh** [comment]
It appears this question was answered, @Med-Seif. Closing the issue.
