### ISSUE TITLE
RxJS 5.5.6: pipeable switchMap operator does not fire any event

### ISSUE THREAD

**Issue by Mokkapps** [ReactiveX/rxjs#3995]
## Bug Report

**Current Behavior**
We want to upgrade to RxJS 6 and therefore migrated to the pipeable operators as described in [RxJS v5.x to v6 Update Guide](https://github.com/ReactiveX/rxjs/blob/master/docs_app/content/guide/v6/migration.md).

We faced twice the issue that the switchMap operator does not work correctly and does not fire an event. As a solution we had to add tap() operator before to make the switchMap operator to fire an event.

And yes, we always subscribe to the observable ;-)

**Reproduction**

Simple StackBlitz example with the same dependencies but there I cannot reproduce the issue:
https://stackblitz.com/edit/angular-946rlj

Code snippets from our project:
```js
    return this.userService.user$.pipe(
      // if this tap is removed, no events are fired from the switchMap operator below
      tap(() => {
        return;
      }),
      switchMap(user => this.getZoneInformationOfUser(user.id, productRoles))
    );
```

```js
Observable.forkJoin(
  this.translateService.get('Translation1'),
  this.translateService.get('Translation2')
)
  .pipe(
    // if this tap is removed, no events are fired from the switchMap operator below
    tap(() => {
      return;
    }),
    switchMap(([title, text]) => {
      const ref = this.modal.open(ConfirmDialogComponent, {
        data: {
          title,
          text
        }
      });
      return ref.afterClosed;
    })
  )
  .subscribe(result => {
    if (result === 'confirm') {
      this.confirmUpdate();
    }
  });
```

**Expected behavior**
I would expect that the switchMap operator does work as before without the pipeable operators in RxJS 5.5.6

**Environment**
- Runtime: Chrome v68.0.3440.84
- RxJS version: 5.5.6
- Angular 5.2.7 without CLI

**Comment by cartant** [comment]
Can you provide a reproduction that does not involve your project-specific services, etc.? That is, can you provide a stand-alone reproduction?

**Comment by Mokkapps** [comment]
@cartant: Sure. Unfortunately it is not reproducible in a simple standalone reproduction:

https://stackblitz.com/edit/angular-946rlj

**Comment by Mokkapps** [comment]
@cartant That makes sense. So I will close this issue and we have to investigate on our side. Thanks for your time!

**Comment by cartant** [comment]
No worries. Hopefully, you'll be able to either figure out what's going on or create a reproduction. If you're able to reproduce the behaviour, I'll be happy to investigate it.

**Comment by tmair** [comment]
We did solve our issue.

The root cause for the issue was that the rxjs library was provided twice in our project. Somewhere (I suspect this line https://github.com/ReactiveX/rxjs/blob/5.5.6/src/util/toSubscriber.ts#L11) there is an `instanceof` check. Because the `Subscriber` is from the other rxjs instance the check fails and we end up in another code branch.

By removing one of the rxjs instances we where able to solve the issue.
