### ISSUE TITLE
Support: Scheduler: Multiple queues

### ISSUE THREAD

**Issue by abdulkareemnalband** [ReactiveX/rxjs#3998]
`rxjs` exports single `queue` object and [QueueSchduler Constructor](https://github.com/ReactiveX/rxjs/blob/37c5c090c04a4bd1bfa31fbfc289c825e8e2a81e/src/internal/scheduler/QueueScheduler.ts#L3) is private and thus not exported.

how can we create multiple queues.

I know `concat`  can be used as Queue but it does not provide same api as scheduler

**Comment by abdulkareemnalband** [comment]
My bad I understood `queue` in wrong sense

BUT 

My Requirement is I want to download certain assets after some high priority assets have been downloaded first .

my pseudo code follows

```
const newQueue = new SomeQueue();


lowPriorityObservable$.queueOn(newQueue).subscribe(assets => do whatever);

// queueOn is some psuedo operator which wait on Some queue to start/ or previouly queued subsbription to to end before subscribing next thing


// some time later when all highpririty assets are loaded
newQueue.start() // completly madeup code

**Comment by kwonoj** [comment]
Closing as inactive, and think above would probably solve particular usecases for now.
