### ISSUE TITLE
ES5/ES3 builds?

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#4]
We need to determine what sort of support we'll offer for ES5/ES3 out of the gate. Will we build a bundle for those targets? Or shall we expect that authors transpile from our modules on their own?

I suspect the former would be the most prudent.

**Comment by gaearon** [comment]
Usually compiling as `npm prepublish` step is the most painless solution for everyone.

**Comment by blesh** [comment]
I think the plan for ES5/ES3 will be to output AMD and CJS modules, as well as some "Globally" registered files that contain subsets of the operators/functionality. Similar to RxJS 2 with `lite`, `all`, etc.

I know that @trxcllnt has some ideas around this, and so does @jhusain...

**Comment by matthewp** [comment]
I work on a tool that is useful for exactly this purpose, will transpile your es6 code to AMD, CommonJS and Global builds. http://stealjs.com/docs/steal-tools.export.html  I agree with @gaearon that doing this as a pre-publish step is usually the best  way to go.  I could submit a PR that includes a build script if you'd like to take a look at it, should be pretty simple.

**Comment by gaearon** [comment]
What does Steal use for transpilation? The momentum behind Babel is incredible, does Steal use it?

**Comment by matthewp** [comment]
You can use either Babel or Traceur.

**Comment by blesh** [comment]
Currently I'm using Babel and Broccoli. But the whole thing needs work. I'm open to any solution, but I can't guarantee I'll use said solution. Speed, ergonomics and extensibility are pretty important.

Ultimately I may even use Rx to build itself?

**Comment by blesh** [comment]
I think this is handled adequately for now. We're not supporting ES3, but I think everything else someone might need is being built? closing for now.
