### ISSUE TITLE
Ajax with PUT and CORS

### ISSUE THREAD

**Issue by Agraphie** [ReactiveX/rxjs#4003]
## Bug Report

**Current Behavior**
Ajax PUT is not sending the cookie in the header.

**Reproduction**
- Create a simple request and have a cookie in your store
- Try ajax PUT

```js
update(id, data) {
        return ajax({
            url: `/test`,
            method: "PUT",
            body: JSON.stringify(data),
            crossDomain: true,
            withCredentials: true
        })
    }
```

**Expected behavior**
When exchanging "PUT" with "POST" a cookie is sent. PUT should behave the same way.

**Environment**
- Runtime: Firefox 61.0.2
- RxJS version: 6.2.2

**Additional context/Screenshots**
I'm not sure if I'm doing something incorrectly here, but when using "POST" everything works as expected. A cookie is sent and I can use my IP. But when using "PUT" I can see that the header does not include any cookie. Any help is appreciated!

**Comment by DCtheTall** [comment]
I'd like to take a crack at this, probably not over the long weekend but some time in the next week or so.

**Comment by DCtheTall** [comment]
@benlesh I have a PR with the general implementation set up. I will get to unit testing it at some point in the next couple days. Let me know if this is what you had in mind 😄
