### ISSUE TITLE
switchAll Operator is not documented

### ISSUE THREAD

**Issue by JWO719** [ReactiveX/rxjs#4009]
The SwitchAll operator is visible in the new Docs, but it is more or less empty. A detailed explanation how this operator is supposed to work and what it is useful for, would be really nice.

see #4004

**Comment by luillyfe** [comment]
@JWO719 I'll take care of it.

**Comment by cartant** [comment]
Closing this as it's addressed in https://github.com/ReactiveX/rxjs/pull/4242
