### ISSUE TITLE
API surface and packaging strategy

### ISSUE THREAD

**Issue by ktrott** [ReactiveX/RxJS#401]
Need a strategy that improves on management of the API / operator surface and packaging.

Today, it is often the case people try to use lite but it has more than they need but missing an operator they need. Seems like we want people to build their own Rx module of the operators they want.

We would still define the base Rx that has the core set of operators. Extended operators would be allowed in an extended area.

If you want to use more specialized / custom operators then this could be the pattern...

```js
const Observable = Rx.Observable.withOperators({
    elementAt: require('rx/extras/elementAt'),
    toPromise: require('rx/extras/toPromise'),
});
```

The above would return a sub-classes Observable that would mix those properties in.

We'd also have an `rx-kitchensink.ts` module

Consumers could also create their own Rx module with exactly what they want.

**Comment by blesh** [comment]
So to reiterate what the direction is here... most of the operators that exists now, and some of those that still need to be developed will be "core" operators. Those operators will be "built-into" the Observable in the `Rx.ts` file.

All other operators will be kept, but put into an `extended` directory under `operators`. They will not be added to the Observable exported from `Rx.ts`.  We *will* however have an `rx-kitchensink` module that exports everything on a `KitchenSinkObservable`, for those that really, really, really want it all. This will also be the one we use for testing `extended` operators.

The guidance for what is "core" and what is "extended" is pretty straightforward:

- If it can be done trivially with an existing operator or two, it's not core.
- if it cannot be done trivially with an existing operator, it should be *considered* for core.
- if it seems like its usefulness is edge-case, regardless of how hard it is to implement with core operators, it should not be core.

The overall goal here is to reduce bike-shedding on what should be implemented.

**Comment by blesh** [comment]
This directly relates to #396
