### ISSUE TITLE
(feat) Add mergeDelayError operator

### ISSUE THREAD

**Issue by AbakumovAlexandr** [ReactiveX/rxjs#4015]
## Feature Request

`rxjs\index.d.ts` of rxjs@6.2.2 package doesn't contain `mergeDelayError` operator which is described as a part of RxJS [here](http://reactivex.io/documentation/operators/merge.html#collapseRxJS). Also, there is no such operator throughout the package contents.

**Comment by kwonoj** [comment]
`MergeDelayError` was exist in v4, not carried over into v5 and beyond (which this repo contains) caused out of sync between documentation and latest version. There is no known plan to carry over all operators in v4 at this moment, as we are trying to reduce more api surface from core.
