### ISSUE TITLE
TestScheduler: Allow expectObservable to schedule observable subscription at non-0 time.

### ISSUE THREAD

**Issue by 12wrigja** [ReactiveX/rxjs#4017]
## Feature Request
In order to provide more control over timings in tests created using `TestScheduler`, allow `expectObservable` to start observable subscription at a non-0 time. This would allow for `TestScheduler` to better schedule sets of expectations which start at different times.

As `expectObservable` already accepts a subscription diagram, this change could simply involve using the start time in that diagram (if present) as the initial subscription time. I have a change that does this I can propose.

My primary use-case for this sort of behavior is testing that subscribing to an observable at two different times does not cause repeat work in a service that it depends on. Currently, I can't offset the second subscription to the method, and it makes the tests less effective.

**Comment by cartant** [comment]
Have a look at https://github.com/ReactiveX/rxjs/pull/3997

**Comment by 12wrigja** [comment]
Thanks! Interesting how similar our proposals are. Looking forward to seeing this merged.

**Comment by cartant** [comment]
Yeah, I will remember to mention - in the team meeting - that it was feature that you've requested, too.
