### ISSUE TITLE
Unsubscribe from marble tests

### ISSUE THREAD

**Issue by ktrott** [ReactiveX/RxJS#402]
Can't do tests with the marble tests to show if someone wants to unsubscribe at some point: explicit disposable vs. completion. Need some way to tell the test scheduler to unsubscribe from the test observable at a particular frame.

**Comment by staltz** [comment]
While making tests for mergeMap I think I figured one potential way of making this happen.

- - -

The subscription is done in `TestScheduler.expect()`:
```ts
    this.schedule(() => {
      observable.subscribe((value) => {
        actual.push({ frame: this.frame, notification: Notification.createNext(value) });
      }, (err) => {
        actual.push({ frame: this.frame, notification: Notification.createError(err) });
      }, () => {
        actual.push({ frame: this.frame, notification: Notification.createComplete() });
      });
    }, 0);
```
We need to keep that subscription inside `expect()`. We can change `expect`'s signature to be

```ts
expect(observable: Observable<any>, unsubscriptionMarbles?: string)
```
So you can optionally provide a marble diagram for the unsubscription moment. And then use it like this:
```js
var e1 = hot('--a-^---b--c----d-------e--f--g--|');
var expected =    '-----b--c----d---';
var unsub =  '----------------------|';

expectObservable(e1.delay(20), unsub).toBe(expected);
```

Notice the second parameter given to `expectObservable`.

What do you think? Does this solve also tricky use cases we had for switch/switchMap? I would know how to implement that above.

**Comment by blesh** [comment]
That's not bad. But wouldn't the unsub marbles be:

```js
var e1 = hot('--a-^---b--c----d-------e--f--g--|');
var expected =   '-----b--c----d---';
var unsub =      '----------------------|';

expectObservable(e1.delay(20), unsub).toBe(expected);
```

So that the `^` and first `-`'s are aligned?

**Comment by staltz** [comment]
Correct, was my mistake.

**Comment by blesh** [comment]
@staltz, I like it, but I think the character should be different than `|`... maybe this is a good place for `!`, since it looks similar. That would also mean fewer changes and assertions in the code to parse the marbles and process them.

**Comment by staltz** [comment]
Ok, let's do exclamation then. Another character I considered was underscore, because it would look a bit like the opposite of `^`. Subscribe is up `^`, unsubscribe is down `_`. 

```js
var e1 = hot('--a-^---b--c----d-------e--f--g--|');
var expected =   '-----b--c----d---';
var unsub =      '----------------------_';

expectObservable(e1.delay(20), unsub).toBe(expected);
```

But I'm fine with exclamation:
```js
var e1 = hot('--a-^---b--c----d-------e--f--g--|');
var expected =   '-----b--c----d---';
var unsub =      '----------------------!';

expectObservable(e1.delay(20), unsub).toBe(expected);
```

**Comment by staltz** [comment]
This issue can be closed since it's fully implemented.
