### ISSUE TITLE
Migrate groupBy Documentation from RxJS Docs Repository

### ISSUE THREAD

**Issue by JWO719** [ReactiveX/rxjs#4029]
In the rxjs-docs repo there is an improved documentation of the groupBy operator (see: https://github.com/ReactiveX/rxjs-docs/blob/master/src/operator-docs/transformation/groupBy.ts).

Please migrate this to the new documentation by updating the JSDoc comments.

**Comment by JWO719** [comment]
I think a real assignment isn't needed. But glad that you take care of it. Thank you very much

**Comment by pertrai1** [comment]
@JWO719 is the JSDoc comments here the same as what you are referring to? https://github.com/ReactiveX/rxjs/blob/master/src/internal/operators/groupBy.ts or am I looking in the wrong place?

**Comment by JWO719** [comment]
That's the right file? Why are there any problems`?

**Comment by JWO719** [comment]
closed by #4036
