### ISSUE TITLE
distinctUntilChanged should have initial value or should pass through the comparing method

### ISSUE THREAD

**Issue by didii** [ReactiveX/rxjs#4030]
## Feature Request

FYI, I'm using angular 2+. I have no idea how to write the code correctly in JS, so the code is in TS. I hope this won't confuse people too much.

**Is your feature request related to a problem? Please describe.**
Consider the following:
```{ts}
const subject = new Subject<string>();
subject.next('INITIAL'); // The initial value of the subject

subject.pipe(
    debounceTime(500),
    distinctUntilChanged((a,b) => {
        console.log({a,b}); // never logs
        return a === b;
    })
).subscribe(x => console.log('"' + x + '"'));

// Somewhere else
setTimeout(subject.next('A'), 100);
setTimeout(subject.next('INITIAL'), 300); //> "INITIAL"
```
In this case, `distinctUntilChanged` cannot know what happened before the subscribe so it regards the `next('INITIAL')` as a unique value. There is currently no way to manipulate this as far as I know.

**Describe the solution you'd like**
I'd like `distinctUntilChanged` to allow setting either a initial value to which it can compare itself the first time or that the value is passed to the comparing method with the first parameter set to `undefined`.

**Additional context**
In angular with reactive forms we set an initial value for a text input field (`''`) and then subscribe to its value changes. When the user now enters something and immediately removes the text again, the event is triggered which triggers a fetch and resets some other fields. When using IE, focusing the input field is enough to trigger an event.

Our current workaround is to force the value again to its initial value after subscribing. This outputs a second event after the debounceTime which is still not idea.

**Comment by abdulkareemnalband** [comment]
Possible solutions
use [`BehaviorSubject`](https://rxjs-dev.firebaseapp.com/api/index/class/BehaviorSubject) like
``` ts
const subject = new BehaviorSubject(INITIAL_VALUE);
```

or use [`startWith`](https://rxjs-dev.firebaseapp.com/api/operators/startWith) like
```ts
observable.pipe(startWith(INITIAL_VALUE), distinctUntilChanged(comparator))
```

If you want to skip first one then you can use [`skip`](https://rxjs-dev.firebaseapp.com/api/operators/skip) operator.

**Comment by cartant** [comment]
Closing this, as the issue has not received much interest and:

> Our general recommendation is if implementation is trivial / and doesn't require modification in core, we do recommend for user-land first. We want to gather usecases around how much common it is before we include into core, since adding new api surface is easy but deprecating / changing behavior is exceptionally hard, as well as we don't want to core api surface it too broad (it is already, and we are trying to shrink it down).

You could use the suggestion in the comment above to implement a user-land operator:

```ts
fuction distinctUntilChangedWithInitialValue<T>(
  initialValue: T,
  comparator?: (left: T, right: T) => number
): MonoTypeOperatorFunction<T> {
  return source => source.pipe(
    startWith(initialValue),
    distinctUntilChanged(comparator),
    skip(1)
  ); 
}
```
