### ISSUE TITLE
`refCount` with delay

### ISSUE THREAD

**Issue by OliverJAsh** [ReactiveX/rxjs#4033]
## Feature Request

**Is your feature request related to a problem? Please describe.**
I have a `Observable<Array<Observable<T>>>` which I want to map to `Observable<Array<T>>`.

When a new array is emitted, the inner observables should unsubscribe/subscribe as follows:

- If `Observable` exists in previous array and the new/current array, *retain* pre-existing subscription
- If `Observable` did not exist in previous array but does exist in new/current array, *create new subscription*
- If `Observable` existed in previous array but does not exist in new/current array, *unsubscribe* from pre-existing subscription

I hoped to achieve this using `switchMap` on the outer observable and then passing `Array<Observable<T>>` into `combineLatest`. However, `switchMap` will unsubscribe from its previous inner `Observable` before subscribing to the new inner `Observable`, which means inner subscriptions are not retained as desired.

Example:
- https://stackblitz.com/edit/typescript-b4wgr1
- https://stackoverflow.com/questions/51875557/combinelatest-switchmap-and-retaining-inner-subscriptions/51901191

**Describe the solution you'd like**
To offset the fact that `switchMap` unsubscribes to the previous inner observable before subscribing to the new inner observable, I would like the `refCount`ing to be delayed, thereby ensuring that subscriptions to the inner observables are retained.

This is the solution suggested in [this article](https://medium.com/@volkeron/rxjs-unsubscribe-delay-218a9ab2672e
). An alternative `refCount` with delay operator can be found [here](https://gist.github.com/marinho/3637210b13c0f298e1692a0b7b104e64).

**Describe alternatives you've considered**

**(If this is new operator request) describe reason it should be core operator**
From my research this seems like something people want but it's not easy to do. I discovered issues/articles/examples on the internet, but there doesn't seem to be anything in the core to help with this.

**Additional context**
- Related discussion: https://github.com/ReactiveX/rxjs/issues/171
- Issue which needed this: https://stackoverflow.com/questions/51875557/combinelatest-switchmap-and-retaining-inner-subscriptions/51901191#51901191
- Example: `refCountWithDelay` implementation: https://gist.github.com/marinho/3637210b13c0f298e1692a0b7b104e64
- Example: `delayedRefCount` implementation: https://medium.com/@volkeron/rxjs-unsubscribe-delay-218a9ab2672e

**Comment by aaronjensen** [comment]
Thank you for writing this up. I ran into the same thing. For now, I'm actually memoizing the slow operation (it was an http call) and allowing the stream to reset. It's not perfect, but it seems to work in my case.

The operator (or flag to `switchMap`) you're proposing here would be great.

**Comment by OliverJAsh** [comment]
@aaronjensen IIRC, I ended up working with @cartant on a `combineLatestHigherOrderArray` operator, which felt like a better solution at the time: https://github.com/cartant/rxjs-etc/blob/master/source/observable/combineLatestHigherOrderArray-spec.ts. That might help in your case too!

**Comment by aaronjensen** [comment]
That's helpful, thank you @OliverJAsh. It looks like that package has `refCountDelay` as well and some other handy operators. I'll try it out.

**Comment by benlesh** [comment]
This has come up a few times, and now that we've revamped the `share`-type operators in 7.x it might be time to have a look to see if we can accommodate this with that new API somehow. 

Off the top of my head, maybe something like (not at all set on this, it requires some thought):

```ts
source$.pipe(
  share({
    resetOnRefCountZero: () => timer(1000) // Where it could be a boolean or a reset timer factory? 
  });
)
```

I'll add this to agenda items.
