### ISSUE TITLE
Incorrect markdown in throwError doc

### ISSUE THREAD

**Issue by ViieeS** [ReactiveX/rxjs#4044]
### Documentation Related To Component:

**throwError**

### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [ ] documentation needs clarification
- [x] error(s) in example
- [ ] needs example

### Description Of The Issue

JS operator `throw` uses instead `throwError` in description:

![image](https://user-images.githubusercontent.com/8194543/44400486-f8cf3d80-a553-11e8-9852-e4d83cffe32c.png)

Also Incorrect markdown in example:

https://rxjs-dev.firebaseapp.com/api/index/function/throwError#examples

![image](https://user-images.githubusercontent.com/8194543/44400561-49469b00-a554-11e8-9355-8708d11083a4.png)

I think it is related to #3880

**Comment by cartant** [comment]
This might have been addressed in https://github.com/ReactiveX/rxjs/pull/3980

**Comment by pertrai1** [comment]
@benlesh should this be closed now that this has been merged?

**Comment by JWO719** [comment]
closed by #4046
