### ISSUE TITLE
docs: add example to publish operator

### ISSUE THREAD

**Issue by pertrai1** [ReactiveX/rxjs#4052]
### Documentation Related To Component:

https://rxjs-dev.firebaseapp.com/api/operators/publish

### Please check those that apply

- [x] needs example

### Description Of The Issue

The new docs do not have a working example of how publish could be used in a real world scenario

**Comment by luillyfe** [comment]
I'll take care of it.

**Comment by cartant** [comment]
Closing this as `publish` now appears to have an example.
