### ISSUE TITLE
docs: add documentation for ajax observable

### ISSUE THREAD

**Issue by JDWong-wag** [ReactiveX/rxjs#4053]
### Documentation Related To Component:

ajax

### Please check those that apply

- [ ] typo
- [ x ] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue

can't find it https://rxjs-dev.firebaseapp.com/api

**Comment by JWO719** [comment]
Thanks for submitting this issue, but it was already fixed by #3984. It is just not deployed yet. Therefore I will close this issue for now.
