### ISSUE TITLE
How is rxjs-compat published?

### ISSUE THREAD

**Issue by wbinnssmith** [ReactiveX/rxjs#4075]
I'm trying to figure out why the artifacts of https://github.com/ReactiveX/rxjs/pull/3855 weren't included in yesterday's release.

I see rxjs's publish script in the repo, but no indication of how rxjs-compat gets published.

I'd like to address this myself but need a bit of direction. Thanks!

**Comment by benlesh** [comment]
it's manual...


First, build the root and publish `@reactivex/rxjs` (soon to be deprecated)
- run `npm publish` from root

then for `rxjs-compat`:
- run `npm publish` from `dist-compat/package`
