### ISSUE TITLE
overload takeWhile with type guard

### ISSUE THREAD

**Issue by chrisguttandin** [ReactiveX/rxjs#4081]
## Feature Request

Hi, I would like to propose overloading the type definition of the takeWhile operator with a signature similar to the one used by the filter operator.

**Describe the solution you'd like**

I think of something similar to this:

```typescript
function takeWhile<T, S extends T>(predicate: (value: T, index: number) => value is S): OperatorFunction<T, S>;
```

This would help with the following scenario:

```typescript
of('hello', 'world', null)
  .pipe(
    takeWhile((word): word is string => (word !== null)),
    map((word) => word.toUpperCase())
  );
```

Currently TypeScript will complain about this code, as it doesn't know that only strings can possibly reach the map operator.

The example is of course contrived but I run often into situations like that when selecting something from a redux store.

**Describe alternatives you've considered**

It is currently possible to add explicit type casts or even an additional filter operator to achieve the same behavior, but I think overloading takeWhile would be the cleaner solution.

In case you agree, I'm happy to submit a PR for that.

**Comment by cartant** [comment]
Yes, I think a type guard overload would be entirely appropriate.

TBH, most of the time I see people using this operator, I see them using an external boolean as a sort of signal - something I consider to be misuse and a code smell.

A type guard better reflects how the operator should be used. I'd be happy to see you submit a PR.
