### ISSUE TITLE
is TestScheduler.frameTimeFactor can not be set 1000 or bigger num

### ISSUE THREAD

**Issue by JmSeason** [ReactiveX/rxjs#4094]
## Bug Report

**Current Behavior**
i have timeout test, because i do want test run fast, so i set TestScheduler.frameTimeFactor to 1000, test throw an error, but set TestScheduler.frameTimeFactor to 100 is working.

```js
//here is my simple test code
const {of} = require('rxjs');
const {timeout, catchError,} = require('rxjs/operators');
const {assert} = require('chai');
const {TestScheduler} = require('rxjs/testing');

let scheduler = new TestScheduler(assert.deepEqual.bind(assert));
const originalTimeFactor = TestScheduler.frameTimeFactor;
TestScheduler.frameTimeFactor = 1000;
const source = '------(a|)';
const expected = '---(a|)';
const source$ = scheduler.createColdObservable(source, {a: 1});
scheduler.expectObservable(source$.pipe(
    timeout(3000, scheduler)).pipe(
    catchError(err => {
        return of(2);
    }))).toBe(
    expected, {
        a: 2
    });
scheduler.flush();
TestScheduler.frameTimeFactor = originalTimeFactor;

it would thorw an error like this:
AssertionError: expected [] to deeply equal [ Array(2) ]

but if i set TestScheduler.frameTimeFactor = 100, and timeout(3000, scheduler) to timeout(300, scheduler) then it worked, it confused me.
```

**Expected behavior**
i think TestScheduler.frameTimeFactor can be set any number.

**Environment**
- Runtime: Node v10.8.0
- RxJS version: 6.3.1
- os: windows7

**Comment by kwonoj** [comment]
afaik there are internal limit in current test scheduler, but that may go away since it doesn't have strong reason. But in any case,

>  i do want test run fast,

This is not relevant to `frameTimeFactor` at all since testscheduler should synchronously schedule all marble values.

**Comment by kwonoj** [comment]
Let me close issue as inactive, especially I have answered frametimefactor is not relavant to speed of test itself. Please feel freely file a new issue if there is a problem.
