### ISSUE TITLE
Can I make simple .pipe() typing after updating RxJS to 6.3.0?

### ISSUE THREAD

**Issue by cheolheon** [ReactiveX/rxjs#4103]
Hi, After updating RxJS to 6.3.0, I have a issue with typing `.pipe()`.

### Before RxJS 6.3.0
`translate$.pipe<MapTypes.TransformBoundary>(pluck('boundary'), shareReplay(1), distinctUntilChanged())`

### Error Message after updating RxJS to 6.3.0
`[ts] Expected at least 0 arguments, but got 3.`

### Solve problem on RxJS 6.3.0
`translate$.pipe<MapTypes.TransformBoundary, MapTypes.TransformBoundary, MapTypes.TransformBoundary>(pluck('boundary'), shareReplay(1), distinctUntilChanged())`

---

Is it a best solution? Is there any way to use it more simple?

I think I need to have to declare type for this `.pipe()` once because its type is changed once when it is passed into `pluck()`.

Thank you.

**Comment by kwonoj** [comment]
inferring types in `pluck` won't work?

```
pipe(
  pluck<TransformBoundary & {....}, TransformBoundary>('boundary'),
  shareReplay(1),
  distinctUntilChanged()
).subscribe((x) => /*x: TransformBoundary */)
```

**Comment by cartant** [comment]
Why do you need to provide the type parameters in the first place? Is an error effected if you use:

```ts
translate$.pipe(pluck('boundary'), shareReplay(1), distinctUntilChanged());
```

The bottom line is that there were two RxJS versions that used 'fixed' signatures for the rest parameters signature (which was incorrect and never matched in previous versions of RxJS) and those 'fixed' signatures broke `pipe`'s type checking, so they were replaced with a signature that includes the rest parameters argument *after* the ninth operator.

If, for some reason you do need to specify type parameters, you should do so on the operators themselves.

**Comment by kwonoj** [comment]
I believe @cartant suffeciently answers q, and my snippet isn't fully accurate (auto infer would work I guess).

**Comment by cartant** [comment]
The PR that removed the signature that accepted a single type parameter was https://github.com/ReactiveX/rxjs/pull/3945

**Comment by cheolheon** [comment]
Yes I need to specify type parameters.

When I don't specify it, plunked `Observable`'s type will be `Observable<{}>` although `translate$` has specific type `Observable<MapTypes.Translate>`.

```tsx
interface Translate {
   ...
   boundary: TranslateBoundary
}
```

@kwonoj 's answer helped me! Thank you everyone.
