### ISSUE TITLE
Issue with rxjs-compat

### ISSUE THREAD

**Issue by policz** [ReactiveX/rxjs#4104]
I have an with issue with rxjs-compat.
currently i'm using Angular 6 .
my rxjs version 6.2.2

ERROR in node_modules/ngx-editor/app/ngx-editor/common/services/message.service.                                                                                                                                  d.ts(1,10): error TS2305: Module '"C:/Users/frontend/node_modules/rx                                                                                                                                  js/Observable"' has no exported member 'Observable'.
node_modules/rxjs/Observable.d.ts(1,15): error TS2307: Cannot find module 'rxjs-                                                                                                                                  compat/Observable'.

**Comment by pertrai1** [comment]
@policz can you share your package.json please

**Comment by Matvey1308** [comment]
Hello, have the same problem, trying to install ngx-editor, so i got the same error.
Here is my own package.json

`{
  "name": "map-viser",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "build:ssr": "npm run build:client-and-server-bundles && npm run webpack:server",
    "serve:ssr": "node dist/server",
    "build:client-and-server-bundles": "ng build --prod && ng run MapViser:server",
    "webpack:server": "webpack --config webpack.server.config.js --progress --colors"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^6.1.6",
    "@angular/common": "^6.1.6",
    "@angular/compiler": "^6.1.6",
    "@angular/core": "^6.1.6",
    "@angular/forms": "^6.1.6",
    "@angular/http": "^6.1.6",
    "@angular/platform-browser": "^6.1.6",
    "@angular/platform-browser-dynamic": "^6.1.6",
    "@angular/platform-server": "^6.1.6",
    "@angular/router": "^6.1.6",
    "@asymmetrik/ngx-leaflet": "^4.0.0",
    "@nguniversal/express-engine": "^6.1.0",
    "@nguniversal/module-map-ngfactory-loader": "^6.1.0",
    "angular-owl-carousel2": "^1.0.6",
    "angular2-universal": "^2.1.0-rc.1",
    "animate.css": "^3.7.0",
    "body-parser": "^1.18.3",
    "bootstrap": "^3.3.7",
    "clip-path": "^1.1.0",
    "core-js": "^2.5.4",
    "express": "^4.16.3",
    "leaflet": "^1.3.4",
    "leaflet-active-area": "^0.1.1",
    "ngx-bootstrap": "^3.0.1",
    "ngx-editor": "^3.3.0",
    "ngx-perfect-scrollbar": "^6.3.1",
    "ngx-swiper-wrapper": "^6.4.0",
    "preboot": "^6.0.0-beta.5",
    "rxjs": "^6.3.1",
    "swiper-animation": "^1.2.2",
    "ts-loader": "^4.5.0",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.6.8",
    "@angular/cli": "~6.0.8",
    "@angular/compiler-cli": "^6.1.6",
    "@angular/language-service": "^6.1.6",
    "@fortawesome/fontawesome-free": "^5.3.1",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/leaflet": "^1.2.10",
    "@types/node": "~8.9.4",
    "body-scroll-lock": "^2.5.7",
    "codelyzer": "~4.2.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~1.7.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^2.0.3",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.3.0",
    "ts-node": "~5.0.1",
    "tslint": "~5.9.1",
    "typescript": "~2.7.2",
    "webpack-cli": "^3.1.0"
  }
}
`

**Comment by StefanTT** [comment]
I had the same problem. Installing rxjs-compat fixes it.
Tested with rxjs 6.3.3

My humble opinion is that this issue can be closed.

**Comment by cartant** [comment]
Closing this, as, in version 6, `Observable` should be imported from `rxjs` and not `rxjs/Observable`. The latter import location is the version 5 location and to continue to use that with version 7, `rxjs-compat` needs to be installed.
