### ISSUE TITLE
static pipe operator is not the same as Observable.pipe

### ISSUE THREAD

**Issue by dkosasih** [ReactiveX/rxjs#4109]
## Bug Report

**Current Behavior**
Static pipe function in the recently merged fixed (#3945) for Observable pipe function signature overload is not in sync. 

**Reproduction**
Rest parameters overload like below show also exists in static pipe function.
```js
pipe<A, B, C, D, E, F, G, H, I>(op1: OperatorFunction<T, A>, op2: OperatorFunction<A, B>, op3: OperatorFunction<B, C>, op4: OperatorFunction<C, D>, op5: OperatorFunction<D, E>, op6: OperatorFunction<E, F>, op7: OperatorFunction<F, G>, op8: OperatorFunction<G, H>, op9: OperatorFunction<H, I>, ...operations: OperatorFunction<any, any>[]): Observable<{}>;
```

**Expected behavior**
It should behave the same as Observable pipe function and be able to compose static pipe functions separately and pass on to Observable pipe.

**Environment**
- RxJS version: 6.3.2

**Comment by cartant** [comment]
Closing this, as it has been addressed in a PR.
