### ISSUE TITLE
timeout(), timeoutWith() behavior differ to RxJS3?

### ISSUE THREAD

**Issue by kwonoj** [ReactiveX/RxJS#411]
Could observe different behavior while try to migrate test cases, would like to confirm if this is expected.

##### timeout()

*RxNew*
```
RxNew.Observable.interval(100).take(5).map(function(x) { return x + ': new timeout source'})
  .concat(RxNew.Observable.interval(200).take(3))
  .timeout(150, new Error('Timeout has occurred.'))
  .subscribe(function(x) { 
      console.log(x); 
    }, function(x) { 
      console.log(x);
    },function() { 
      console.log('new timeout completed'); 
    });
```
>0: new timeout source
>[Error: Timeout has occurred.]

`dueTime` is total time passed after source starts.
> source : ----------0----------1----------2----------3----------4--------------------0'--------------------1'.....
> output : ---------------#

*RxOld*
```
Rx.Observable.interval(100).take(5).map(function(x) { return x + ': old timeout source'})
  .concat(Rx.Observable.interval(200).take(3))
  .timeout(150, new Error('Timeout has occurred.'))
  .subscribe(function(x) { 
      console.log(x); 
    }, function(x) { 
      console.log(x);
    },function() { 
      console.log('old timeout completed'); 
    });
```

>0: old timeout source
>1: old timeout source
>2: old timeout source
>3: old timeout source
>4: old timeout source
>[Error: Timeout has occurred.]

`dueTime` is time window between each source element emits
> source : ----------0----------1----------2----------3----------4--------------------0'--------------------1'.....
> output :  ----------0----------1----------2----------3----------4---------------#

##### timeoutWith()

*RxNew*
```
RxNew.Observable.interval(100).take(5).map(function(x) { return x + ': new timeoutWith source'})
  .concat(RxNew.Observable.interval(200).take(3))
  .timeoutWith(150, 
    RxNew.Observable.interval(100).take(3).map(function(x){return x+': new timeoutWith other'}))
  .subscribe(function(x) { 
      console.log(x); 
    }, function(x) { 
      console.log(x);
    },function() { 
      console.log('new timeoutWith completed'); 
    });
```

>0: new timeoutWith source
>0
>1: new timeoutWith source
>0: new timeoutWith other
>2: new timeoutWith source
>1: new timeoutWith other
>1
>3: new timeoutWith source
>2: new timeoutWith other
>new timeoutWith completed

source still emits after timeout?
> source : ----------0----------1----------2----------3----------4--------------------0'--------------------1'.....
> output  : ----------0-----0'-----1----x-----2----y----1'... 
>(marble timeframe may not correctly reflect actual results timeframe)

*RxOld*
```
Rx.Observable.interval(100).take(5).map(function(x) { return x + ': old timeout source'})
  .concat(Rx.Observable.interval(200).take(3))
  .timeout(150, 
    Rx.Observable.interval(100).take(3).map(function(x){return x+': old timeout other'}))
  .subscribe(function(x) { 
      console.log(x); 
    }, function(x) { 
      console.log(x);
    },function() { 
      console.log('old timeout completed'); 
    });
```

>0: old timeout source
>1: old timeout source
>2: old timeout source
>3: old timeout source
>4: old timeout source
>0: old timeout other
>1: old timeout other
>2: old timeout other
>old timeout completed

`dueTime` is time window between each source element emits
> source : ----------0----------1----------2----------3----------4--------------------0'--------------------1'.....
> output :   ----------0----------1----------2----------3----------4---------------x----------y--------.....

RxJS3's behavior matches with ReactiveX [documentation](http://reactivex.io/documentation/operators/timeout.html) and .Net implementation [documentation](http://www.introtorx.com/content/v1.0.10621.0/13_TimeShiftedSequences.html#Timeout).

**Comment by blesh** [comment]
Yeah, that's a bug. The behavior should be identical.

**Comment by kwonoj** [comment]
Thanks for confirmation. May I give it a try for fix?

**Comment by blesh** [comment]
PRs welcome. ;)

**Comment by kwonoj** [comment]
Cool, will work on it :smiley:

**Comment by staltz** [comment]
I suppose this issue can be closed?
