### ISSUE TITLE
Operator request: startWithDeferred<T>(selector: () => T)

### ISSUE THREAD

**Issue by fljot** [ReactiveX/rxjs#4113]
## Feature Request

**Is your feature request related to a problem? Please describe.**
In my experience I often saw situations, when we're interested in some initial emission from stream. Often it can be that stream is produced in View/Presentation Model, so initial value is being read from some stateful domain model and then used to render UI with actual state.
In such scenario it is easy to make mistake and use `startWith` operator. With `startWith` value will be "baked" into stream and will be used as initial emission for all subscriptions even those created after model state changes, causing stale value in UI.

**Describe the solution you'd like**
I would like to have basic operator similar to `startWith`, but it should use function to resolve value to start with.

**Describe alternatives you've considered**
Technically It could be achieved via
```
merge(
  defer(
    () => of(something.mutable)
  )
)
```
or
```
merge(
  of(undefined).pipe(
    map(() => something.mutable)
  )
)
```

**(If this is new operator request) describe reason it should be core operator**
I think it should be core operator because
1) I have seen many situations when it's needed
2) It's simple and can be written in an optimal way (relative to alternatives above)
3) Having proper operator with a similar name could remind devs to choose wisely (talking about IntelliSense/autocompletion).

---

I would be happy to implement if idea is welcomed.

**Comment by cartant** [comment]
Closing this as it could be implemented pretty easily as a [user-land operator](https://github.com/ReactiveX/rxjs/issues/3585#issuecomment-382571620):

> Our general recommendation is if implementation is trivial / and doesn't require modification in core, we do recommend for user-land first. We want to gather usecases around how much common it is before we include into core, since adding new api surface is easy but deprecating / changing behavior is exceptionally hard, as well as we don't want to core api surface it too broad (it is already, and we are trying to shrink it down).
