### ISSUE TITLE
RXJS 5 feature does not work in RXJS 6 

### ISSUE THREAD

**Issue by JesseSoldat** [ReactiveX/rxjs#4127]
In Angular I used to import all my operators into a single file and then import that file into the app.module
example: from RxJs 5
`import 'rxjs/add/operator/distinctUntilChanged';
import 'rxjs/add/observable/fromEvent';
import 'rxjs/add/observable/empty';
`

I tried a few things while upgrading Rxjs 6
#1 
`import { filter } from "rxjs/operators"; `

#2
`import 'rxjs/operator/distinctUntilChanged';
import 'rxjs/observable/fromEvent';
import 'rxjs/observable/empty';
`

neither of these seemed to work. 

So now I have to import each operator into the component that I use it in

Not sure if this is just a problem with the Typescript not knowing about this new pattern or not.

Did some searching on the net and did not find anyone talking about this issue.

Any  ideas

**Comment by kwonoj** [comment]
https://github.com/ReactiveX/rxjs/blob/master/docs_app/content/guide/v6/migration.md#backwards-compatibility

**Comment by Gurvinder-Abhaypal** [comment]
i have installed the rxjs-compat, still i am facing this issue. Its showing the errors on empty() and publishReplay() as well. 
Any idea ?

**Comment by cartant** [comment]
@Gurvinder-Abhaypal Please don't comment on closed issues. If you have a problem, create a new issue - filling out the issue's template - and reference this issue if you think it's related.

Regarding your comment on this issue, it contains next to no information and nothing actionable.

https://itnext.io/how-to-write-a-bug-report-3333d8e41efb

**Comment by Gurvinder-Abhaypal** [comment]
My bad... Have fixed it now.
I will remove my comment as soon as possible
