### ISSUE TITLE
Implement fetch with readable streams

### ISSUE THREAD

**Issue by EloB** [ReactiveX/rxjs#4128]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Using the native function `fetch` and `ReadableStream` is terrible at the moment. The native api is based on `Promise`'s to make a streams so I think an `Observable` would fit this much better.

**Describe the solution you'd like**
I provided an example how it could work. http://jsbin.com/pumimey/edit?js,console,output

```js
import fetch$ from 'rxjs/fetch$';

fetch$('/get/some/json')
  .json() // should also be implemented: arrayBuffer(), blob(), text()
  .subscribe(json => console.log(json));

fetch$('/get/alot/of/text')
  // To be able to get chunks.
  // If the browser doesnt support body then we could polyfill that with one emit of arrayBuffer.
  .steam()
  .text() // will transform Uint8Array chunks to string
  .subscribe((chunkText) => console.log(chunkText));
```

I think this in the long term can replace the current ajax implementation too.

Sorry for my bad english! 😸

**Comment by kwonoj** [comment]
as similar to other feature request, I believe this is well fits for our recommendation for user-land implementation. (i.e I have xhr-based one as userland here as well https://github.com/kwonoj/oxid). We'd like to encourage to have wide user level operator / implementations and would like to discuss what to be included in core among those. 

Appreciate for interest.

**Comment by EloB** [comment]
Whats the reason to use legacy technology? Who nowadays uses XMLHttpRequest? I mean if you create something new? Fetch can be polyfilled if needed. Also has better funcationality under the hood.

**Comment by kwonoj** [comment]
> Whats the reason to use legacy technology? Who nowadays uses XMLHttpRequest?

@angular/http (https://github.com/angular/angular/blob/master/packages/common/http/src/xhr.ts) and other major http request uses it still. in native fetch, you can't have cancellation with observables anyway.

Secondly, the reason issue being closed is not saying we don't want to this thing. We do encourage new implementation goes for userland first, before introducing either breaking changes / or increasing core api surface.

**Comment by EloB** [comment]
It can be cancelled with the AbortController?

**Comment by kwonoj** [comment]
> It can be cancelled with the AbortController?

it's only available from quite modern browser (i.e chromium M66) and rx itself have ongoing dicussions (https://github.com/ReactiveX/rxjs/issues/3122), as core lib there's practically no way to keep compatibility to xhr provides.

Again, there are several factors like above core try to move in conservative way and reason recommend to start off from user level first.

**Comment by EloB** [comment]
My example has cancellation...

**Comment by kwonoj** [comment]
in you example what I see is only

```
const AbortController = window.AbortController || class FakeAbortController {
  signal = null;
  abort() {}
};
```

which isn't correct for core perspective since we have to support browser doesn't have abortcontroller.  fakeabortcontroller isn't answer for us.

Still again, it's not details like having abortcontroller or etcs, as explained above for new attempt we would like to encourage to use user level module first, unless it is significantly requires internals of core implementation to be achieved. 

If you believe this _should_ be in core, feel freely create new issue including details in our feature request template. That's majority of core team's rational to determine some new feature discussion to include in core library. just fyi, below is template (you can find it when you open new issue though)

```
xJS strongly recommends to create new features via pipable function and publish it as user-land module. If this feature request is

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**
A clear and concise description of what you want to happen.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered.

**(If this is new operator request) describe reason it should be core operator**
A clear and concise description of reason it can't be achieved via user-land module.
```

**Comment by kwonoj** [comment]
> it can't be achieved via user-land module

is part we majorly would like to hear around.

**Comment by EloB** [comment]
How do you stream content with XMLHttpRequest? As far I know it’s not possible with the legacy technology. That’s one of the feature I’m looking for. Where Observable is way better then the native implemenation. To be able to stream data to Indexeddb etc.
