### ISSUE TITLE
Type inference for pluck operator

### ISSUE THREAD

**Issue by michaeljota** [ReactiveX/rxjs#4131]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Currently pluck operator does not have type inference in the returning object.

**Describe the solution you'd like**
Actually, this was discussed before in #2295. I think is the only way so far to do this properly.

**Describe alternatives you've considered**
Maybe no too many overloads (?)

**Additional context**
Back then the original OP was closed because this project wasn't yet using TS 2.1. But now that it uses TS3.0 it would be a great feature to have.

**Comment by kwonoj** [comment]
Yeah, I think we can try with new compiler features + dtslint verification.

**Comment by michaeljota** [comment]
Looking at the source code, I think this could be done just with regular overloads, but I don't know if you feel good about it.

**Comment by cartant** [comment]
I think you'll have to use overloads - like [this](https://github.com/cartant/rxjs-etc/blob/master/source/operators/pluck.ts) - as the current release has to work with 2.8. And I'm not sure that the tuple parameter extraction in 3.0 will be of any use, anyway, as the parameters chain - with each depending upon the previous, etc.

**Comment by cartant** [comment]
Closing as #4232 has been merged.
