### ISSUE TITLE
Operator: Add property value to object

### ISSUE THREAD

**Issue by Qquanwei** [ReactiveX/rxjs#4133]
## Feature Request

With pipable operator, RxJS strongly recommends to create new features via pipable function and publish it as user-land module. If this feature request is

**Is your feature request related to a problem? Please describe.**

Sometimes I want set a value to Object, but rxjs seems haven't this operator . 

**Describe the solution you'd like**

```javascript
sink$.switchMap(value => {
  return ob$.pipe(set('value', value))
})
```

`
 set(key: string, value: any): OperatorFunction
`

**Comment by kwonoj** [comment]
As mentioned in issue template we do recommend to create user level operator for new feature if it doesn't require internal core changes. 

It's bit unclear with current proposal's detail what's required. Please try with user level operator, and fell freely create new issue if it should be core operator with some additonal details.
