### ISSUE TITLE
[Documentation] Link to Types in Parameterlist

### ISSUE THREAD

**Issue by niklas-wortmann** [ReactiveX/rxjs#4136]
To make the api docs more explorable it would be helpful if we link to the doc page of the referred type, e.g. a function takes an observable as input then one should be able to click on observable and this navigates the user to the observable page.
In total this is a bit more complex because what we currently have, for interfaces for example, that you can jump to the dedicated method description. In such cases the link to the type could be in the method documentation.

This is pretty much the behaviour of angular.io. Maybe we can adapt that too, because I think the UX is quiet good.

Side Note: It could become difficult, when there is a type not documented (because it is not part of rxjs or not exported publicly). We have to think what we want to do in such cases. But even the described behaviour above would improve the UX of the docs very much IMO.

**Comment by benlesh** [comment]
Since we now have a fork of angular's docs, I think we can close this. :)
