### ISSUE TITLE
RxJs 6 merged.subscribe is not a function

### ISSUE THREAD

**Issue by evgeny-t** [ReactiveX/rxjs#4146]
### Documentation Related To Component:

merge

### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [ x] documentation needs clarification
- [ x] error(s) in example
- [ ] needs example

### Description Of The Issue

Hi 👋 

I took an example from the docs: https://rxjs-dev.firebaseapp.com/api/index/function/merge#examples:

    const {interval, operators: {take, merge}} = rxjs;
    const timer1 = interval(1000).pipe(take(10));
    const timer2 = interval(2000).pipe(take(6));
    const timer3 = interval(500).pipe(take(10));
    const concurrent = 2; // the argument
    const merged = merge(timer1, timer2, timer3, concurrent);
    merged.subscribe(x => console.log(x));

created a fiddle https://jsfiddle.net/evgeny_t/7je14aoq/9/, added https://cdnjs.cloudflare.com/ajax/libs/rxjs/6.3.2/rxjs.umd.min.js, but I get `Uncaught TypeError: merged.subscribe is not a function` in the console. Is there some discrepancy between the docs and the code? Am I doing it wrong?

Thanks!

**Comment by kwonoj** [comment]
So there's `merge` for creation, and one for `operators`. 

`merge(...)` is being used to creation method, one in `operators/merge` won't work in those cases.

```
const {interval, merge, operators: {take}} = rxjs; //import creation method `merge` here

...same snippets below
```

for operators, you can use it for `pipe` operator like `someobservable.pipe(merge(...));`.
