### ISSUE TITLE
"Getting Started" should point to Introduction

### ISSUE THREAD

**Issue by benlesh** [ReactiveX/rxjs#4148]
The landing page is a sore point right now.

- The `Getting Started` link that is so prominent needs to point to the "Introduction" content.

- A link to the API documentation should also be shown prominently on the main page, but not in "getting started"

**Comment by JWO719** [comment]
Getting started link is already fixed, just the api link needs to be improved

**Comment by dzhavat** [comment]
This issue can be closed now. The described changes have been made and are already live.

**Comment by cartant** [comment]
Thanks for the heads up, @dzhavat
