### ISSUE TITLE
Improve breakdown and searchability of API Index reference

### ISSUE THREAD

**Issue by ajcrites** [ReactiveX/rxjs#4156]
### Documentation Related To Component:
This is in reference to the Reference landing page documentation: https://rxjs-dev.firebaseapp.com/api

### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [x] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue
The documentation builder breaks the API reference into sections based on the source files, so we get "index" and "operators." Additionally, the widget for searching breaks down the types by Class, Const, Enum (which isn't used), etc.

I don't think that either of these divisions are very useful except maybe "operators." I think a different section and/or Type breakdown would be more useful for everyone using the docs. I understand that this will take more work since the breakdown by file system is much simpler, but it comes with advantages.

My proposed breakdown would be to match the existing operator types: https://github.com/ReactiveX/rxjs/blob/master/doc/operators.md#categories-of-operators -- Creation, Transformation, etc. I would also suggest separating higher-order operators from others. possibly this could be done by Type which I would suggest breaking down as Interfaces, Observable creator classes (Observable, Subject, etc. for example), constants, observable creation operators, and pipeable operators.

I'm very open to suggestions on this, but I do think that a clearer breakdown of the API reference would be useful to new and veteran RxJS developers alike.

**Comment by benlesh** [comment]
This has been handled since releasing the new docs site here: https://rxjs.dev
