### ISSUE TITLE
I want to dynamically change the output stream according to switchcase.

### ISSUE THREAD

**Issue by fukai007** [ReactiveX/rxjs#4169]
**RxJS version:**
5.2.0
**Code to reproduce:**

		var subject = new Rx.Subject();		
		var i = 0;

		var coa = subject.map(function(x){ return "mapA---"+x})
		var cob = subject.map(function(x){ return "mapB---"+x})
		var co = subject.map(function(x){return x})
				
		var ssm = subject.switchMap(function(val){ // switchMap
			let index = val % 3;
			switch(index){
				case 0:
					return coa
				case 1:
					return cob
				case 2:	
					return co
				default:
					return co
			}
		})
		
		ssm.subscribe(function(val){
			console.log("subscribe--a---------------------->",val);
		});
		
		ssm.subscribe(function(val){
			console.log("subscribe--b---------------------->",val);
		});
		
		setInterval(function(){
			ssm.next(i);
			i++;
		},2000);
**Expected behavior:**
I want to dynamically change the output stream according to switchcase.

if  index == 0 return a coa
if index == 1 return a cob
...
**Actual behavior:**
 ssm.next(i) don't work
**Additional information:**

**Comment by kwonoj** [comment]
first, trying `ssm.next` is not working since `switchMap` returns observable and not original subject. Secondly, switchMap's inner subscription occurs when observable has returned via projection, so at the moment inner subscription started value has been already emitted - due to subject is not unicastable observable. i.e you could use normal observable instead of reusing subject.

```
var subject = new Rx.Subject();
var i = 0;

var coa = (x) => Rx.Observable.of(x).map(function(x) { return "mapA---" + x });
var cob = subject.map(function(x) { return "mapB---" + x })
var co = subject.map(function(x) { return x })

var ssm = subject.switchMap(function(val) { // switchMap
    let index = val % 3;
    switch (index) {
        case 0:
            return coa(index)
    }
})

ssm.subscribe(function(val) {
    console.log("subscribe--a---------------------->", val);
});

ssm.subscribe(function(val) {
    console.log("subscribe--b---------------------->", val);
});

setInterval(function() {
    subject.next(i);
    i++;
}, 2000);
```

**Comment by fukai007** [comment]
it work  , thank you ,

**Comment by fukai007** [comment]
@kwonoj  if  i  use var coa = (x) => Rx.Observable.of(x).debounceTime(1000).map(function(x) { return "mapA---" + x });
i think  debounceTime function  will don't work .

**Comment by fukai007** [comment]
@kwonoj  i don't konw  "teardown" . what is mean ?  how to understand it .  would  you told me  ?
