### ISSUE TITLE
Wrong output of `.reduce`, `.scan` and `.toArray` with asap scheduler

### ISSUE THREAD

**Issue by unao** [ReactiveX/rxjs#4172]
## Bug Report

Wrong output of `.reduce`, `.scan` and `.toArray` with asap scheduler.

*6.3.2* 

[PLNKR](http://plnkr.co/edit/HZt9T1hvNylrpXd5x0f0?p=preview)

```js
const { take, tap, toArray, observeOn } = rxjs.operators

const s = new rxjs.Subject()

s.pipe(
  // observeOn(rxjs.asyncScheduler),
  take(5),
  tap(n => s.next(n + 1)),
  toArray()
).subscribe(vs => console.log(vs))
s.next(0)
```

**Expected behavior**
`vs` should be `[0, 1, 2, 3, 4]` but is `[4]`

**Possible Solution**
A workaround is to `observeOn` with an `asyncScheduler`.

Later next week could take a look into it and try to fix unless someone else immediately knows how to fix. It feels to be rather small thing.

**Comment by kwonoj** [comment]
Looking flow this doesn't look like bug - in 'tap', there is reentrant occurs. Reentrant isn't supported cases unless explicitly schedules differently. If you create observable wuthout reentrant is it still occurs?

**Comment by unao** [comment]
If you observer on `asyncScheduler` it works as expected and most likely without reentrant as well. Could you reference me to more context why exactly this should not be a supported use case?

**Comment by kwonoj** [comment]
Yes, this is synchronous reentrant so it cannot trap out. To more simplify, like

```
s.pipe(
  tap(n => s.next(n + 1)),
).subscribe(vs => console.log(vs))

s.next(0);
```

then you can observe it never reaches next handler. refer closed issues https://github.com/ReactiveX/rxjs/issues/2155#issuecomment-263715419 and other via search for reasoning, but mostly as said above this is due to default scheduler behavior from v5.

**Comment by unao** [comment]
@kwonoj not sure about it - in your case there is an infinity loop - in my case `[4]` is reported which definitely is a wrong result. If this behavior is not supported then way better would be to throw an error in my opinion.

**Comment by kwonoj** [comment]
You are limiting sync entrancy via take. Either cases, point is subject don't suppprt reentrancy by default so you may encounter any kind of unexpected behavior. Trap out via scheduler is right way to go if you need it.
