### ISSUE TITLE
Broken image in concat

### ISSUE THREAD

**Issue by dzhavat** [ReactiveX/rxjs#4174]
### Documentation Related To Component:

[concat](https://rxjs-dev.firebaseapp.com/api/index/function/concat)

### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [x] documentation needs clarification
- [x] error(s) in example
- [ ] needs example

### Description Of The Issue

There's a broken image in the “Description” section.

![image](https://user-images.githubusercontent.com/1096332/45948092-fb133480-bff6-11e8-931b-c6405ebbd16d.png)

**Comment by JWO719** [comment]
Thanks for pointing. Unfortunately it's not just related to concat. For each operator the image is missing. We are working on it. I'll add new informations to this issue

**Comment by PowerKiKi** [comment]
Please close this issue, as it is a duplicate of #4366.

**Comment by dzhavat** [comment]
Yeah, good idea to get rid of duplicate issues and have just one place to track things.
