### ISSUE TITLE
Enable declarationMap in typings

### ISSUE THREAD

**Issue by kwonoj** [ReactiveX/rxjs#4176]
## Feature Request

**Additional context**
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-9.html

> Enabling --declarationMap alongside --declaration causes the compiler to emit .d.ts.map files alongside the output .d.ts files. Language Services can also now understand these map files, and uses them to map declaration-file based definition locations to their original source, when available.

> In other words, hitting go-to-definition on a declaration from a .d.ts file generated with --declarationMap will take you to the source file (.ts) location where that declaration was defined, and not to the .d.ts.

Since our package includes source anyway, enabling declaration map will allow more easier navigation experiences.

**Comment by kwonoj** [comment]
what we need to resolve:

 our package layout places src other than resolvable in package: try this for check

```
npm run build_all
cd dist/packages/typings
open one of .map
```

check src reference,  👉 is part need to be resolved cause our `packages` flattens our src into different location.

**Comment by felixfbecker** [comment]
Would love to see this because it enables cross-repository jump-to-definition on sourcegraph.com

**Comment by benlesh** [comment]
This no longer seems to be an issue. Closing for now.
