### ISSUE TITLE
rjxs-dev shows 503 error due to service worker

### ISSUE THREAD

**Issue by StephenFluin** [ReactiveX/rxjs#4178]
### Documentation Related To Component:
https://rxjs-dev.firebaseapp.com/

### Please check those that apply
- [x] error(s)

### Description Of The Issue
![image](https://user-images.githubusercontent.com/165056/45974507-598be300-bff6-11e8-924c-59f007a9b154.png)

I receive a 503 error when refreshing the RxJS docs. It looks like this 503 is coming from the service worker. I do not receive this error when I "bypass service worker for network".

**Comment by JWO719** [comment]
Thank you very much for the hint., I will figure out what's happening here.
