### ISSUE TITLE
bug will occur in 'from' When operation dom

### ISSUE THREAD

**Issue by kejiacheng** [ReactiveX/rxjs#4188]
### html
```
<div class="wrap">
  <p class="item">1</p>
  <p class="item">2</p>
  <p class="item">3</p>
  <p class="item">4</p>
  <p class="item">5</p>
  <p class="item">6</p>
</div>
```
### js
```
let dom = document.getElementsByClassName('item')

from(dom)
      .subscribe(x => x.parentNode.removeChild(x))
```

page will remove 1, 3, 5,  remain 2, 4, 6

## reason

dom will change in real time when getting HTMLCollection by document.getElementsByClassName

## solution

1.  from.ts
```
export function from<T>(input: ObservableInput<T>, scheduler?: SchedulerLike): Observable<T> {
    input instanceof HTMLCollection && ( input = Array.from(input) )
    ...
}
```
the solution will influence type judgment

2. subscribeToArray.ts, fromArray.ts
```
similar to solution 1
```
the solution may be influence other operators

**Comment by hexuanzhang** [comment]
```
let dom = Array.from(document.getElementsByClassName('item'));

from(dom).subscribe(x => {
    const parent = x.parentNode;
    parent && parent.removeChild(x);
});
```

**Comment by cartant** [comment]
This is not a bug and this is not specific to RxJS. If you mutate the DOM whilst iterating a collection of nodes, the same behaviour will be effected.

If you intend to mutate the DOM whilst iterating, you'll need to copy the collection to an array - as you've suggested.

**Comment by kejiacheng** [comment]
> This is not a bug and this is not specific to RxJS. If you mutate the DOM whilst iterating a collection of nodes, the same behaviour will be effected.
> 
> If you intend to mutate the DOM whilst iterating, you'll need to copy the collection to an array - as you've suggested.

thanks
