### ISSUE TITLE
Share operator don't work correctly

### ISSUE THREAD

**Issue by clitetailor** [ReactiveX/rxjs#4195]
Sorry if i disturb you guys. What i want to ask is whether the `share` operator works correctly. 
I know that the document is still incomplete but based on what i read: "share operator makes the stream hot". Because if it doesn't, i should have another implementation of it. So what i expect is the following program don't log anything:

```jsx
const source = of(1, 2, 3, 4).pipe(
  share()
)

source.subscribe(val => console.log(val))
```

I try to inspect into the source and i found these two lines:

https://github.com/ReactiveX/rxjs/blob/6.3.2/src/internal/operators/multicast.ts#L66-L67

So in order to make it correct, it may be re-ordered like this:

```jsx
const proxySub = source.subscribe(subject)
const subscription = selector(subject).subscribe(subscriber);
subscription.add(proxySub);
```

Is it correct or am i missing something? Is there any reason behind this? 🤔

Sincerely

**Comment by cartant** [comment]
You're expectation is incorrect. The `share` operator reference counts subscriptions to the shared source. Some time ago, I wrote a blog article to explain the `publish` and `share` operators and their variant. You can find it [here](https://blog.angularindepth.com/rxjs-understanding-the-publish-and-share-operators-16ea2f446635).

**Comment by clitetailor** [comment]
@cartant I'm not talking about `publish` and its variant because it use the same implementation of `multicast`. I purpose is not multicast or unicast by the way.

Can you explain clearly because in the example of Ben Lesh. Two method `makeHotRefCounted` and `share` have the same meaning but got two different outputs ?!?!?!

**Comment by clitetailor** [comment]
For more clearly i will show you my JSBin version: http://jsbin.com/voruhow/22/edit?html,js,console,output

And it works exactly what i expected!

**Comment by clitetailor** [comment]
The real reason i post this thread is because i want to clean up the history of an observable. And i remember the article of Ben Lesh about the Hot and the Cold. First i think it about side effects and sharing state between stream (multicast or unicast). But when i apply to my case it turn out the technique of adding a Subject proxy between a RelaySubject and your subscription is to forget it previous history of actions. It turns out the technique of making a cold stream to be hot is for optimization.  But in the above example. `of(1, 2, 3)` is a cold stream it values have been emitted. So it should be forget. When we add `delay(1000)` the value is add at the duration 1s after we turn it to hot. So its value is emitted.

The controversal here is what is origin coordinates of the timeline when turning a cold stream into a hot stream. If the 0s milestone is from the time you turn it to hot. So all the values should be forget each time you subscribe to that stream, the multicast really take into its meaning, previous values haven't been subscribed will be forgetted. If the 0s milestone is from the time you subscribe, it means that you totally mirror the cold stream. So we can not called it hot, because such a mirror need ReplaySubject, we gain no benefit from this. Consider my comment below your article too!

https://medium.com/@clitetailor/whether-or-not-an-observable-is-capable-of-multicasting-depends-upon-whether-that-observable-is-1a37a26506fe

**Comment by clitetailor** [comment]
For example, if you use ReplaySubject the result will actually what you think about, not the current implementation of `multicast`:

http://jsbin.com/qilaza/2/edit?html,js,console,output

```js
multicast(() => new ReplaySubject())
````

**Comment by cartant** [comment]
StackOverflow is the preferred forum for these sorts of questions. You are likely to receive more timely help if you post general RxJS questions there.
