### ISSUE TITLE
Space between function/operator name and labels 

### ISSUE THREAD

**Issue by dzhavat** [ReactiveX/rxjs#4200]
### Documentation Related To Component:

All.

### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue
It's a very tiny thing but (I think) it would be better if there was a little space between the function/operator name and the label next to it. Like there's space between the two labels.

![image](https://user-images.githubusercontent.com/1096332/46200973-4d17cb00-c313-11e8-897d-71eb0bc41ac0.png)

**Comment by pertrai1** [comment]
Thanks, @dzhavat. I thought that I had fixed that but it looks as though I did not. Will get that so it is easier to read the name without the label hugging it
