### ISSUE TITLE
Docs: Passing an array to concat needs clarification

### ISSUE THREAD

**Issue by dzhavat** [ReactiveX/rxjs#4203]
### Documentation Related To Component:

[concat](https://rxjs-dev.firebaseapp.com/api/index/function/concat)

### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [x] documentation needs clarification
- [x] error(s) in example
- [ ] needs example

### Description Of The Issue

It says in the [description](https://rxjs-dev.firebaseapp.com/api/index/function/concat#description) that

> You can pass either an array of Observables, or put them directly as arguments.

The way I understand this is literally passing an array of Observables. There's also an example illustrating this - [Concatenate an array of 3 Observables](https://rxjs-dev.firebaseapp.com/api/index/function/concat#concatenate-an-array-of-3-observables).

In reality, however, it seems like passing an array doesn't work ([example on Stackblitz](https://stackblitz.com/edit/angular-hce1cn)). Instead of getting the values, I get back Observables. It only works if I pass an array of Observables and use the spread operator.

So is this a problem in the documentation or the implementation?

**Comment by cartant** [comment]
You have to use the spread syntax because an array is itself an `ObservableInput`. That is, an array is considered an observable source.

**Comment by dzhavat** [comment]
Thanks for the clarification. In that case the docs should be updated to reflect that.

**Comment by dzhavat** [comment]
Fixed in #4713
