### ISSUE TITLE
Deprecate and remove bufferWhen and windowWhen

### ISSUE THREAD

**Issue by benlesh** [ReactiveX/rxjs#4212]
It looks like `bufferWhen(() => a)` is the same as `buffer(defer(() => a))` and `windowWhen(() => a)` is the same as `window(defer(() => a))`.

`bufferWhen` and `windowWhen` exist because it was part of getting parody for RxJS v4 (at the time v2) functionality (while splitting `buffer` into different operators). It seems like these two operators are just bloat and unnecessary.

Alternatively, we could have `buffer` and `window` optionally accept functions as arguments, however, I'm generally against this.

**Comment by kwonoj** [comment]
If using defer achieves exact same behavior, I'm all for removing operator.

**Comment by PandaSandStudio** [comment]
My understanding is that in `bufferWhen(() => a)` is not the same as `buffer(defer(() => a))`, and that their behaviours are very different, as in `bufferWhen`, every time the `closingSelector` observable emits a value or completes, the `closingSelector` observable will be unsubscribed from, recreated and resubscribed to, whereas in `buffer`, the `closingNotifier` observable is only every subscribed to once

For example, `bufferWhen(() => a)` behaves vastly different to `buffer(defer(() => a))` in this example:

```js
import { interval, timer, defer } from "rxjs";
import { buffer, bufferWhen } from "rxjs/operators";

const a = timer(1000);
const source = interval(200);

source // buffer(defer(() => a))
  .pipe(buffer(defer(() => a)))
  .subscribe(
    value => console.log("using buffer with defer:", value),
    error => console.error("using buffer with defer:", error),
    complete => console.log("using buffer with defer:", "complete")
  );

// using buffer with defer: [0, 1, 2, 3]
// using buffer with defer: complete

source // bufferWhen(() => a)
  .pipe(bufferWhen(() => a))
  .subscribe(
    value => console.log("using buffer when:", value),
    error => console.error("using buffer when:", error),
    complete => console.log("using buffer when:", "complete")
  );

// using buffer when: [0, 1, 2, 3]
// using buffer when: [4, 5, 6, 7, 8, 9]
// using buffer when: [10, 11, 12, 13, 14]
// using buffer when: [15, 16, 17, 18, 19]
// ...
```

**Comment by benlesh** [comment]
Ben says he's wrong, Matt concurs.
