### ISSUE TITLE
Rx.range(0, NaN) results in infinite Observable instead of throwing an error

### ISSUE THREAD

**Issue by mikermcnally** [ReactiveX/rxjs#4223]
## Bug Report

**Current Behavior**
Calling Rx.range with anything other than a number as second the parameter results in an Observable that emits values indefinitely.

**Reproduction**
```js
Rx.range(0, NaN).subscribe(console.log);
```

**Expected behavior**
Doing so should result in an error. An infinite Observable makes sense if the second parameter is null or undefined but defined, nonnumerical values should be invalid inputs and throw errors.

**Environment**
- RxJS version: 6.3.3
- Javascript only

**Comment by kwonoj** [comment]
We do not validate input values for runtime, instead use type definition as api contract should be supplied into. But even in that case, this doesn't guarded since params are not strict to allow some unguarded values may have chances to improve it.

**Comment by kwonoj** [comment]
But `NaN` is valid type of `number`, not sure how to subtract those types.. 🤔

**Comment by cartant** [comment]
Given that JavaScript's implicit conversions are - to say the least - weird:

```js
1 >= []    // true
1 >= NaN   // false
1 >= ""    // true
1 >= "foo" // false
```

I'm closing this because it doesn't appear to be practical to - throughout the RxJS API - guard all parameters that ought to be numeric.
