### ISSUE TITLE
switchMap with conditions inside doesn't work correct

### ISSUE THREAD

**Issue by MateWW** [ReactiveX/rxjs#4241]
## Bug Report

**Current Behavior**
A clear and concise description of the behavior.

**Reproduction**
- REPL or Repo link:
https://stackblitz.com/edit/rxjs-qzfj1f?devtoolsheight=60

```ts
import { of } from 'rxjs'; 
import { switchMap } from 'rxjs/operators';

const obj1 = {
  foo: 'bar'
}
const obj2 = {
  bar: 'foo'
}

const source = of(false).pipe(
  switchMap((status) => status ? of(obj1): of(obj2))
);

source.subscribe(x => console.log(x));
```

**Expected behavior**
Problem exist when i want to dispatch relative to status 2 different actions. Typescript add type `Observable<{ foo: string; }> | Observable<{ bar: string; }>` 
when manualy set type to 
`Observable<{ foo: string; } | { bar: string; }>` 
it works fine. 

**Environment**
- Runtime: 69.0.3497.100
- RxJS version: 6.3.3
- Typescript: ^2.9.2

**Comment by cartant** [comment]
This is the same TypeScript limitation that caused a problem in https://github.com/ReactiveX/rxjs/issues/4168

The solution is to specify the return type in the arrow function:

```ts
(status: boolean): Observable<{ foo: 'bar' } | { bar: 'foo' }> => status ? of(obj1): of(obj2)
```

**Comment by cartant** [comment]
... which I just noticed you included in your issue. Anyway, the bottom line is it's a TypeScript limitation and you have to manually specify the type. As noted in the linked issue, it's a known TS problem that also manifests with promises.

**Comment by cartant** [comment]
Closing this because it's a TypeScript limitation.
