### ISSUE TITLE
RxJs Operators Unable to load internal structure of files

### ISSUE THREAD

**Issue by NishantThakkar** [ReactiveX/rxjs#4245]
**Bug:**
rxjs/operators is able to load index.js but inside index file there are internal references, which are unable to load .

**Environment:**
- Runtime: Node 8.12.0 , Chrome 69.0
- RxJS version: 6.3.3
- Angular v 6.0.0
- Loader, build configuration: SystemJs v0.21.5

**SystemJs configuration:**
```
map: {
'rxjs': 'npm:rxjs/bundles/rxjs.umd.js',    
 'rxjs/operators': 'npm:rxjs/operators/index.js',   
},
packages: {
 'rxjs': { defaultExtension: 'js' },
 'rxjs/operators': { defaultExtension: 'js'}, 
}
```
**Expected Behavior:**
rxjs/operators should be able to load its internal references.

**Additional context/Screenshots:**
Error:

![image](https://user-images.githubusercontent.com/5793534/46785308-fff21b00-cd4e-11e8-99ce-218c170caeed.png)

index.js of rxjs->operators:

![image](https://user-images.githubusercontent.com/5793534/46785472-7858dc00-cd4f-11e8-936f-86d11e6c7c0e.png)

Directory Structure:

![image](https://user-images.githubusercontent.com/5793534/46785382-34fe6d80-cd4f-11e8-9a10-44a7a232cc8a.png)

**Comment by benlesh** [comment]
I'm closing this, partly because it is pretty stale, but mostly because I'm not sure what the goal is or how to reproduce this. I don't know enough about SystemJS to know if this was a bug or something wrong with the SystemJS config. Probably a better question for Stackoverflow?
