### ISSUE TITLE
set debounceTime on empty observable

### ISSUE THREAD

**Issue by vh13294** [ReactiveX/rxjs#4262]
## Bug Report

**Current Behavior**
The debounceTime operator is not working on empty obervable. I tested on other operators such as delay and it is perfectly fine.

when I repeatedly subscribe with debounceTime(x) 
the complete function just executes reapeatly and immedietly.There is no "debounce" effect.

**Reproduction**
- REPL or Repo link:
https://stackblitz.com/edit/angular-8gdsau

```js
  debouceEmpty = empty().pipe(debounceTime(800));
  delayEmpty = empty().pipe(delay(1500));

  testDelay() {
    this.delayEmpty.subscribe({
      complete: () => console.log('delay Complete!')
    });
  }


  testDebounceTime() {
    this.debouceEmpty.subscribe({
      complete: () => console.log('debounceTime Complete!')
    });
  }
```

**Expected behavior**
It should wait 't' amount time before executing the complete function.

**Environment**
- Runtime: window 10,  chrome  69, angular 6.2
- RxJS version: 6.3.3

**Comment by kwonoj** [comment]
Related with https://github.com/ReactiveX/rxjs/issues/4249 - this is more about behavior of delay. There are some inconsistent semantics around completion notification delay. In case of debouncetime, it delays _value_, not completion.

**Comment by vh13294** [comment]
> Related with #4249 - this is more about behavior of delay. There are some inconsistent semantics around completion notification delay. In case of debouncetime, it delays _value_, not completion.

Any idea ? How can I use denounce on void without return value?

**Comment by kwonoj** [comment]
what usecases you'd like to delay completion via debounce on empty stream?

**Comment by kwonoj** [comment]
Can't say for sure without seeing full flows, but that doesn't sound like jobs of debounce operator of rx. If you'd like debounce event emission itself you'd need to convert event handler into observable, otherwise if you'd like function to be debounded that's not scope of rx. maybe `_.debounce` or something else is what you'd looking for instead.
