### ISSUE TITLE
Observable says it hasn't thrown an error, but stops updating

### ISSUE THREAD

**Issue by Dispersia** [ReactiveX/rxjs#4264]
## Bug Report

**Current Behavior**
 Observable says it hasn't thrown an error, but stops updating?

**Reproduction**
- REPL or Repo link:
https://stackblitz.com/edit/angular-u7swbg
^ the StatefulComponent

**Expected behavior**
The observable to say it has thrown an error.

**Additional context/Screenshots**
 Put 0 into the input, and the observable will throw - like expected (jsonplaceholder returns 404 because there is no item at index 0). However, the entire observable stops responding to changes from jsonHolderNumber$, and when checking the object it doesn't say it has thrown an error.
Picture of clicking the button before and after I make it throw:
https://i.imgur.com/4pOaIst.png

This may be a complete misunderstanding on my part, I'm still trying to learn rxjs and it's awesome, just some things I don't fully understand :). With that said, is there any way that even if it errors, the stream can continue to be updated? I thought it might be the throwError() but even with returning a blank observable it stops.

**Comment by kwonoj** [comment]
>  it doesn't say it has thrown an error

it's simply you are inspecting observable object, which doesn't have indication of if it's thrown or not.

> is there any way that even if it errors, the stream can continue to be updated?

There are couple of exception handling mechanism when error occurs. `catchError` is one of them, but in here problem is

- you did `throwError` : it's same as substituting one error to another, without handling it. imperatively it's same as
```
try {
 dosomething
} catch (e) {
 throw e;
}
```

- secondly, behavior of catchError is substitute original observable into something else when error occurs, so when outer observable hits this, original stream won't continue. For those cases, you could make inner observable to handler error to not bubble up error like 
```
switchMap(n => this.api.getTodo(n).pipe(
          catchError(() => of({}))
     )),
```
