### ISSUE TITLE
Transfer Pipeable Operator Documentation from 'old docs'

### ISSUE THREAD

**Issue by JWO719** [ReactiveX/rxjs#4266]
In the old docs ('/doc') there is a file called 'pipeable-operator.md'. This needs to be transfered to the new docs ('docs_app/content/guide/v6'). The content itself should be rxjs 6 related, so this might don't need any fixes. But one could consider improving styling and maybe the transfer results in broken links.
Maybe some of the examples should be changed to Typescript

**Comment by alivenotions** [comment]
Hi! Can I work on this one?

**Comment by JWO719** [comment]
Sure! If you need any kind of help, don't hesitate to ask me.

**Comment by alivenotions** [comment]
I have a question:

1. Why are files like `subject.md` and `subscription.md` outside the `docs_app/content/guide/v6` directory and why should the `pipeable-operator.md` supposed to be inside it?

**Comment by JWO719** [comment]
The docs_app folder is used for the new docs. /docs is deprecated but we want to transfer the content
