### ISSUE TITLE
Rx object not available in new documentation

### ISSUE THREAD

**Issue by trshafer** [ReactiveX/rxjs#4296]
### Documentation Related To Component:

New documentation: https://rxjs-dev.firebaseapp.com/api

### Please check those that apply

- [ ] typo
- [x] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue

In previous documentation http://reactivex.io/rxjs/class/es6/Subscriber.js~Subscriber.html, the `Rx` object was available to experiment with in the developer tools console. This allowed for quick testing of different observables, operators, etc. I could look at the documentation and then try it out right in the devtools console.

In the new documentation https://rxjs-dev.firebaseapp.com/api, the `Rx` object is not available. This makes it more challenging to quickly test out Rxjs.

**Comment by kwonoj** [comment]
Checkout pr https://github.com/ReactiveX/rxjs/pull/4261.

**Comment by trshafer** [comment]
Thanks. This is a duplicate.
