### ISSUE TITLE
throttle and throttleTime inconsistent with one another

### ISSUE THREAD

**Issue by benlesh** [ReactiveX/rxjs#4300]
`throttleTime(x, scheduler. config)` should be the same as `throttle(() => timer(x, scheduler), config)`, but it's not. The tests show the behavior is slightly different. We'll need to decide which is the correct behavior.

**Comment by pertrai1** [comment]
my 2 cents is that `throttle(() => timer(x, scheduler)` is the correct behavior.

**Comment by benlesh** [comment]
Core is is indifferent, no change to be made. :)
