### ISSUE TITLE
added a name to the forkjoin request item

### ISSUE THREAD

**Issue by qinxiaoxian** [ReactiveX/rxjs#4302]
It's good to use the forkJoin api to combine the http requests, but there still has one insufficient, the forkJoin api need a  array of requests or multiple requests as parameters and return a array of response, if we want to get the correct response we must order the index of the request item in the requests to accept it, it's too trouble when we delete one of requests, the other responses' index shoud be update or it will be wrong.

**Comment by cartant** [comment]
You can use array destructuring instead of indices. For example:

```ts
forkJoin(obsA, obsB, obsC).pipe(
  tap(([valA, valB, valC]) => { /* ... */ })
);
```

**Comment by kwonoj** [comment]
Closing as question's answered.
