### ISSUE TITLE
Pipeable operators.md code sample causing TS compliation errors out of the box

### ISSUE THREAD

**Issue by cmeyertons** [ReactiveX/rxjs#4314]
### Documentation Related To Component:

[pipeableOperators.md](https://github.com/ReactiveX/rxjs/blob/master/doc/pipeable-operators.md)

```
npm list rxjs
+-- @angular-devkit/build-angular@0.8.5
| +-- @angular-devkit/architect@0.8.5
| | `-- rxjs@6.2.2
| +-- @angular-devkit/build-webpack@0.8.5
| | `-- rxjs@6.2.2
| +-- @angular-devkit/core@0.8.5
| | `-- rxjs@6.2.2
| +-- @ngtools/webpack@6.2.5
| | `-- rxjs@6.2.2
| `-- rxjs@6.2.2
+-- @angular/cli@6.2.5
| +-- @angular-devkit/schematics@0.8.5
| | `-- rxjs@6.2.2
| +-- @schematics/update@0.8.5
| | `-- rxjs@6.2.2
| `-- rxjs@6.2.2
`-- rxjs@6.3.3
```

### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [x] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue

Current example is causing Typescript errors:

```
const starter = of(1);

const takeEveryNthSimplest = (n: number) => filter((value, index) => index % n === 0);

const takeEveryNthSimple = (n: number) => <T>(source: Observable<T>) =>
  source.pipe(filter((value, index) => index % n === 0 ));

starter.pipe(
  takeEveryNthSimplest(1),
  takeEveryNthSimple(2)
);
```

result:

![image](https://user-images.githubusercontent.com/19917677/47814350-71543680-dd1b-11e8-974b-a1e1cc1abe89.png)

simplest doesn't work in my case because i'm try to create a superset operator that encapsulates a few sub-operators

**Comment by jgbpercy** [comment]
Might be missing something but this seems to work ok to me in stackblitz:

https://stackblitz.com/edit/rxjs-kk8bq1

Are you able to post a stackblitz that reproduces the issue?

Failing that I'm guessing this could be Typescript version related... What version of TS are you on?

**Comment by martinsik** [comment]
@cmeyertons Can you share the code where you tried this? It looks like you have just wrong imports.

**Comment by kqadem** [comment]
May you check in tsconfig if the `noStrictGenericChecks` flag is set?
We experienced a similar issue and traced it down to this. While this flag was set, TypeScript was not able to infer the typings, instead the return type was an empty object, `{ }`.
We are using typescript 2.9.2
