### ISSUE TITLE
Errors caught with catchError can't be caught elsewhere with try catch

### ISSUE THREAD

**Issue by TheeRFG** [ReactiveX/rxjs#4315]
So in previous versions of RxJS, when operators were chained together I could succesfully swallow errors burried withing void function return types with the typical JavaScript `try {} catch() {}` block...

I've found that after upgrading to RxJS and switching to the pipeable operators I am no longer able to swallow these errors and they punch a hole through the side of my test framework with extremely cryptic errors. 

**RxJS version:**
6.3.3

**Code to reproduce:**
```
import { Observable, of, throwError } from 'rxjs/index';
import { tap, catchError } from 'rxjs/internal/operators';
import { HttpErrorResponse } from '@angular/common/http';

export class NestedErrorThrower {
  constructor() {}

  private nestedFunction(): Observable<any> {

    // Mock error throw for testing
    return throwError(new HttpErrorResponse({
          status: 409, 
          statusText: ''
      }));
  }

  doSomething(): void {
    this.nestedFunction().pipe(
      catchError((response: Response) => {
        // log the error
        console.log('error has been logged');
        throw response; //rethrow error
      }),
      tap((stream) => {
        // do stuff with the stream
        console.log('stream has been tapped');
      })
    ).subscribe(() => {
      // do more stuff
      console.log('subscribed');
    });
  }
}

```
```
import { NestedErrorThrower } from './nested-error-thrower';

const nestedErrorThrower = new NestedErrorThrower();

describe('catchError', () => {
  it('breaks try catch block', () => {
    let errorWasCaught = false;
    
    try {
      nestedErrorThrower.doSomething();
    } catch (err) {
      errorWasCaught = true;
    }

    expect(errorWasCaught).toBeTruthy();

    // test other stuff after
  });
});
```

**Expected behavior:**
In the past by chaining 
```
this.nestedFunction()
.catch((response: Response) => {
  // log the error
  console.log('error has been logged');
  throw response; //rethrow error
})
.do((stream) => {
  // do stuff with the stream
  console.log('stream has been tapped');
})
.subscribe(() => {
  // do more stuff
  console.log('subscribed');
});
```
This would actually successfully be caught in the test framework with 
`try catch`

I would expect this to still work, but this is no longer the case. 

**Actual behavior:**
I end up with a test failure for `HttpErrorResponse: Http failure response for (unknown url): 409 `

**Additional information:**

What I'm really trying to test is that elsewhere in my code base my error was handled/logged/whatever and then bubbled back up the stack, but I don't have direct access to wherever it is directly bubbled to. I would like to test that `catchError` and the events within it handled everything correctly without punching a hole through the side of my test framework, but my inability to catch this deep error with try/catch prevents me from doing this. 

If there's a better way to catch errors that occur deep within my code that would otherwise be inaccessible to my test framework directly, I am open to hear it.

**Comment by cartant** [comment]
This is by design. It's mentioned in the [migration document](https://github.com/ReactiveX/rxjs/blob/master/docs_app/content/guide/v6/migration.md#synchronous-error-handling).

There is a video - from NgConf - in which Ben Lesh explains the reasoning for the decision. I'll try to find a link for you, later.

**Comment by cartant** [comment]
Here's the link: https://youtu.be/JCXZhe6KsxQ?t=294

**Comment by TheeRFG** [comment]
So in my case where I don't have direct access to this observable being called, I only have access to a void return type wrapper/calling method, there's nothing I can do but refactor my current error handling logic?

**Comment by TheeRFG** [comment]
So I watched through the video and I think the changes make sense.
In fact the very issue it enables that he describes is what made this issue such a headache for me to track down to begin with, but I'm still left with my ultimate problem in the end.


I'm not subscribing to anything at the point I'm doing the testing in my test framework.
I'm trying to call and test the logic of a void return type that opens an unexposed subscription chain which has an error in it.
The error is handled in catchError but I'm required to rethrow the error back up to my void function... I'm not left with anywhere that I can catch off a subscribe block.

**Comment by TheeRFG** [comment]
So I have currently fixed this by implementing 
```
config.useDeprecatedSynchronousErrorHandling = true;

try {
  component.saveLineItem();
  tick(1000);
} catch (error) {

}
expect(errorDisplayed).toBeTruthy();

config.useDeprecatedSynchronousErrorHandling = false;
```

I don't see anyway around this without some ability to tap into the asynchronous error caching and telling it's okay if this one test errors...
