### ISSUE TITLE
shareReplay can't unsubscribe

### ISSUE THREAD

**Issue by aniiantt** [ReactiveX/rxjs#4316]
## Bug Report

**Reproduction**

```js
const observable = Observable.create(observer => () => console.log('unsubscribe')).pipe(shareReplay(1))
const sub = observable.subscribe(v => console.log(v));
sub.unsubscribe()
```

not log unsubscribe

**Expected behavior**
log unsubscribe

**Environment**
- RxJS version: 6.3.3

**Possible Solution**
rxjs5 is work

**Comment by cartant** [comment]
Closing this because it's a known issue and has been addressed, but the PR has not yet been merged. See https://github.com/ReactiveX/rxjs/pull/4059
