### ISSUE TITLE
Add typed errors by catching and encapsulating code that throws

### ISSUE THREAD

**Issue by hrajchert** [ReactiveX/rxjs#4317]
## Feature Request

**Is your feature request related to a problem? Please describe.**
In the current version of rxjs the errors are typed as `any`. This complicates having different error handling logic depending on the error and being type safe. For example, if an AJAX call fails it would be reasonable to retry if the error was a 500 or a timeout, but it would be futile if it's because of a 404, a rate limit or a json parse error.

There are two reasons why we type the error as `any`. First, TypeScript doesn't have [typed exceptions](https://github.com/Microsoft/TypeScript/issues/13219), and second, the current Observable specification says that if a function inside an operator throws, the error should be propagated as is through the error chain. So, because we can throw `any`thing, the error is typed as `any`.

**Describe the solution you'd like**
It may be a while until we get typed exceptions in typescript, so our only option to get errors correctly typed right now is to slightly modify the Observable specification.

The idea is to promote the idiomatic way of error handling, which is returning an already failed observable using the [throwError](https://rxjs-dev.firebaseapp.com/api/index/function/throwError) operator. If for some reason a function inside an operator throws (and we can't prevent that from happening), we can wrap the thrown value inside a special class called `UnknownError`. That class can expose the thrown error using the type `unknown` instead of `any`.

This is a breaking change and if we decide to do it, it should be included in a major release.

**Describe alternatives you've considered**
Another solution to get typed errors in userland could be to use an Either object and make use of the pipable operators to modify all operators to work with an Observable<Either<T, E>>. But that includes a lot of overhead and is more error prone.

**Additional context**
There is an older related PR: https://github.com/ReactiveX/rxjs/issues/2646

I've also created a library to do this for single async values called [@ts-task/task](https://github.com/ts-task/task), and here is a [small video](https://www.youtube.com/watch?v=T7O1T1wmw00) introducing why I use it instead of promises and with a real example from our companys codebase in which we show the value of having the errors correctly typed.

**Comment by cartant** [comment]
I'm not in favour of this:

> so our only option to get errors correctly typed right now is to slightly modify the Observable specification.

IMO, the error parameters should be typed as `unknown` once TypeScript 3 becomes the minimum-supported version for RxJS.

I don't think it should be taken further unless support for declaring what can be thrown is added to TypeScript.

**Comment by kwonoj** [comment]
I agree with @cartant here in general. We'd like to solve this problem in compiler side and that was reason this hasn't changed long time to get proper compiler support via min version.

**Comment by cartant** [comment]
Closing this in favour of the referenced issue: https://github.com/ReactiveX/rxjs/issues/2646
