### ISSUE TITLE
Callbacks are fired too early if observable is created from synchronous source

### ISSUE THREAD

**Issue by Tohntobshi** [ReactiveX/rxjs#4318]
RxJS version: 6.3.3

Code to reproduce:
`
const subscription = of(0).subscribe(() => console.log(subscription)); // undefined
console.log(subscription); // Subscriber`

Expected behavior: I expected to have access to subscription on callback, no matter how observable was created. (for example to unsubscribe after receiving first value)

Actual behavior: If observable is created from synchronous source, subscription is undefined when callback is fired.

Additional information:
however this works fine
`
const subscription = timer(0).subscribe(() => console.log(subscription)); // Subscriber`

**Comment by cartant** [comment]
It's synchronous, so `subscription` cannot be assigned until after `subscribe` calls the passed `next` handler. To unsubscribe from within `subscribe` for a synchronous observable, you need to use `this`. See this comment: https://github.com/ReactiveX/rxjs/pull/3230#issuecomment-361113247

However, it's best to avoid the situation entirely.

**Comment by Tohntobshi** [comment]
I didn't know `this` in callback points at subscription. Thank for this clarification. Indeed `take(1)` seems legit for taking one value. But wouldn't it be better if callbacks for observables created from synchronous sources were placed immediately into queue of event loop like `timer(0)` did, so behavior would be more consistent?

**Comment by Tohntobshi** [comment]
For example
```
Promise.resolve(0).then(() => console.log('one'));
console.log('two');
```
will produce output two , one
and it's consistent behavior

but
```
of(0).subscribe(() => console.log('one'));
console.log('two');
```
produces one, two
which is not that consistent

**Comment by Tohntobshi** [comment]
Ok. Thank you guys for explanation.
