### ISSUE TITLE
Moving isEmpty() operator?

### ISSUE THREAD

**Issue by kwonoj** [ReactiveX/RxJS#433]
Related with operator `every` (https://github.com/ReactiveX/RxJS/pull/432).

`isEmpty` operator can be easily replicated via `source.every(function(_) { return false; })`, case of .net implementation operator itself is even deprecated( [introtoRx](http://www.introtorx.com/Content/v1.0.10621.0/06_Inspection.html#All) / [list of .net api, does not include isEmpty] (https://msdn.microsoft.com/en-us/library/system.reactive.linq.observable_methods(v=vs.103).aspx) )

What about moving `isEmpty` to `Rx.KitchenSink`, or deprecate to reduce api?

**Comment by staltz** [comment]
Sounds good to me.

**Comment by blesh** [comment]
I agree.

**Comment by staltz** [comment]
We could close this issue.
