### ISSUE TITLE
Add array support to observableMerge

### ISSUE THREAD

**Issue by drweb86-work** [ReactiveX/rxjs#4335]
## Feature Request

I would like to be able to pass to observableMerge array of observables.

Currently i have to do this
const observable1 = osevableOf(1);
const observable2 = osevableOf(2);
const observable3 = osevableOf(3);

const allObservables = [observable1, observable2, observable3];

observableMerge(...allObservables)

I would like to make it 
a) either possible that way observableMerge(allObservables)
b) OR throw exception that you are not supporting that, because code is compiled but doesn't work.

Thank you.

**Comment by cartant** [comment]
It works as intended because an array is a valid `ObservableInput`.

**Comment by drweb86-work** [comment]
But it misleading that if i pass an array of observables inside observableMerge, it will not work for them

See. If i do this

        const watchEvents: Observable<Event>[] = [];
            watchEvents.push(observableFromEvent(window, 'click'));
            watchEvents.push(observableFromEvent(window, 'keydown'));

        observableMerge(watchEvents)
                .pipe(throttleTime(15000))
                .subscribe(() => {
                    console.log('Hi!');
                });

it won't work.

So i have to do in other way

 const watchEvents: Observable<Event>[] = [];
            watchEvents.push(observableFromEvent(window, 'click'));
            watchEvents.push(observableFromEvent(window, 'keydown'));

        observableMerge(...watchEvents)
                .pipe(throttleTime(15000))
                .subscribe(() => {
                    console.log('Hi!');
                });

That's not obvious, right?

**Comment by cartant** [comment]
This feature is by design.

If you want to merge an array of observables, use the spread syntax. Or, after passing an array of observables - a higher-order observable, as an array itself is an `ObservableInput` - use the `mergeAll` operator.

**Comment by drweb86-work** [comment]
Thank you.
