### ISSUE TITLE
Schedulers don't show up in the API reference

### ISSUE THREAD

**Issue by voithos** [ReactiveX/rxjs#4336]
### Documentation Related To Component:

- `asapScheduler`
- `asyncScheduler`
- `queueScheduler`
- `animationFrameScheduler`

### Please check those that apply

- [ ] typo
- [x] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue

When looking at the API docs (https://rxjs-dev.firebaseapp.com/api), none of the schedulers (`asapScheduler`, `asyncScheduler`, etc) appear to be listed, even though they are [exported in the index](https://github.com/ReactiveX/rxjs/blob/01a09789a0a9484c368b7bd6ed37f94d25490a00/src/index.ts#L15).

**Comment by JWO719** [comment]
You will find the Scheduler in the defined constants, e.g. https://rxjs-dev.firebaseapp.com/api/index/const/asapScheduler. But you are right it's not very intuitive. Definetly a thing we should improve in some ways. Thanks for creating the issue

**Comment by benlesh** [comment]
It seems we just need to publish the latest docs. This has been updated. Closing for now.
