### ISSUE TITLE
Reconnect WebSocketSubject.prototype._subscribe() TypeError: subscriber.add is not a function

### ISSUE THREAD

**Issue by rudzikdawid** [ReactiveX/rxjs#4338]
## Bug Report
The only way to reconnect ws connection based on `WebSocketSubject` after websocket server restart is using `_subscribe()` method.
With `rxjs@6.3.3`: method `_subscribe()` throws error:
```
core.js:12584 ERROR TypeError: subscriber.add is not a function
    at WebSocketSubject.push../node_modules/rxjs/internal/observable/dom/WebSocketSubject.js.WebSocketSubject._subscribe (WebSocketSubject.js:217)
    at websocket.service.ts:33
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:14134)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:420)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:188)
    at push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask (zone.js:496)
    at ZoneTask.invoke (zone.js:485)
    at timer (zone.js:2054)
```
Version 6.2.2 doesn't have this issue

**Current Behavior**

```typescript
import { webSocket } from 'rxjs/internal/observable/dom/webSocket';
...

wsSubscriber = {
  next: (msg) => {
    console.log('message recived', msg);
  },
  error: this.errorHandler.bind(this),
  complete: () => {
    console.warn('complete');
  }
};

errorHandler(error) {
  setTimeout(() => {
    this.ws$._subscribe(this.wsSubscriber);
  }, 5000);
}

connect() {
  this.ws$ = webSocket('ws://0.0.0.0:8080');
  this.ws$.subscribe(this.wsSubscriber);
}
```

restart of websocket server triggers `error` callback with `CloseEvent`
To reconnect with ws server i've used `this.ws$._subscribe(this.wsSubscriber);`
It's work but throws error on version 6.3.x
Using version 6.2.x this error doesn't appear

**Expected behavior**
`_subscribe()` call without error, or new `reconnect()` method to reconnect websocket.

**Environment**
- Runtime: Chrome 70.0.3538.67
- RxJS version: 6.3.3

**Comment by kwonoj** [comment]
(in a perspective of public interface) I do not consider this as a end user facing bug, as `_subscribe` is not a public interface and should not be used at all: https://github.com/ReactiveX/rxjs/blob/master/src/internal/Observable.ts#L271-L275 .

Probably this need to be reshaped into question for `how to reconnect` part only.

**Comment by benlesh** [comment]
`_subscribe` isn't a public API.
