### ISSUE TITLE
bufferTime throw heap out of memory error in TestScheduler

### ISSUE THREAD

**Issue by reabreu** [ReactiveX/rxjs#4342]
## Bug Report

**Current Behavior**
I'm trying to test a very basic pipeline with a bufferTime operator using the info on the marble testing document.
I've stumbled into a problem and I'm not sure if either my implementation is wrong or its an issue with the bufferTime operator.
It's throwing a "JavaScript heap out of memory" error.

**Reproduction**
- REPL or Repo link:
https://jsfiddle.net/reabreu/kt9Lwsov/

```js
const {
  bufferTime
} = rxjs.operators;
const {
  TestScheduler
} = rxjs.testing;

const scheduler = new TestScheduler((actual, expected) => {
  console.log(JSON.stringify(actual, null, 4));
  console.log(JSON.stringify(expected, null, 4));
});

scheduler.run((helpers) => {
  const {
    hot,
    expectObservable
  } = helpers;
  const e1 = hot('-a-b-c');
  // Assume x = ['a', 'b', 'c']
  const expected = '2s x';
  const stream$ = e1.pipe(bufferTime(2000));

  expectObservable(stream$).toBe(expected);
});
```

**Expected behavior**
Should correctly output stream values.

**Environment**
- Runtime: Chrome 70
- RxJS version:
- 6.3.3

**Additional context/Screenshots**
<img width="1673" alt="screen shot 2018-11-15 at 12 20 46" src="https://user-images.githubusercontent.com/4553101/48552632-1d2b8380-e8d1-11e8-93ad-5340d85cb0ba.png">

Thanks

**Comment by kwonoj** [comment]
`bufferTime` internally emits new observable per given time by collecting sources in time period. 

```
const e1 = hot('-a-b-c');
```

this source emits then never completes, as it'll make buffertime creates new observable continuously, will stack up memory eventually. Either completes source, or use operators like `take` to control subscription.

**Comment by reabreu** [comment]
That helped! My understanding of how bufferTime works was wrong. 
Thanks a lot for the support!
