### ISSUE TITLE
Add Scheduler that schedules work on React's internal scheduler.

### ISSUE THREAD

**Issue by bordoley** [ReactiveX/rxjs#4352]
## Feature Request

React internally uses a work scheduler to schedule work based upon priority. Though the API is not yet finalized, the library is available via npm: https://www.npmjs.com/package/scheduler

Integrating with React's scheduler allows for more fine grain integration when using RxJS for state management in React applications. The api allows for the scheduling of work depending upon the priority of the work vs other ui tasks for instance.

**Describe the solution you'd like**

I attempted to implement a Scheduler solution myself, but in the version of RxJS I'm using (5.5), it does not appear that the external API of the library is designed to enable third party implementations (the base classes are not available, only scheduler instances).

A first order solution would be to expose these base classes, such that third party implementation of schedulers are possible. Alternatively including a scheduler implementation backed by the scheduler package would also be valuable.

**Comment by kwonoj** [comment]
> it does not appear that the external API of the library is designed to enable third party implementations (the base classes are not available, only scheduler instances)

This is not correct and rx exports scheduler interface for custom scheduler. Check https://github.com/kwonoj/rxjs-requestidlecallback-scheduler for example, (while it uses async scheduler for base, but any other scheduler is possible)

I think this is interest idea and would like to see 3rd party implementation based on current scheduler interface for further discussion. We could discuss if it need to be in core or not then.

**Comment by cartant** [comment]
It's likely possible for you to do what you want in user-land. You likely don't need to extend `Scheduler`. Have a look at the zone schedulers in [`rxsj-etc`](https://github.com/cartant/rxjs-etc/tree/master/source/scheduler) - they just implement `SchedulerLike`.

**Comment by bordoley** [comment]
@kwonoj Thanks for the pointer, I wasn't totally clear on how to do so, and found myself hitting some roadblocks. Let me try it out.

**Comment by kwonoj** [comment]
@cartant huh, at least in v5 it was accessible. While it's not frequently used, I think class itself may need to be expsed? (Not need to be top level maybe but shouldn't be hidden in `internal`)

**Comment by cartant** [comment]
@kwonoj Yeah, I agree. I've been considering - out of curiosity - implementing a depth-first equivalent of the `QueueScheduler` - a `StackScheduler` - to use the heap rather than the stack for depth-first traversals. I'd like to see them exported.

**Comment by bordoley** [comment]
@kwonoj: I ran into the issue that the scheduler classes are not exposed via the main entry point (index.d.ts). We use a compiled version of rxjs, so this may be a limitation specific to our environment and not a general limitation. Thanks for the pointers (@cartant too)!!!
