### ISSUE TITLE
WebsocketSubject support dynamic url

### ISSUE THREAD

**Issue by callmez** [ReactiveX/rxjs#4355]
## Feature Request

```js
import { WebSocketSubject } from 'rxjs/webSocket';

export class SomeService  {

     public async getUrl() {
         const token = await otherSerivce.getTokenFromServer();
         return `wss://some.host/ws/${token}`;
     }

     public get websocket$() {
          return new WebSocketSubject(this.getUrl());
     }
}

cosnt serveice = new SomeService();

const websocket$ = serveice.websocket$;
websocket$.subscribe(...);
```

**Is your feature request related to a problem? Please describe.**

In some scenarios need to dynamically get the url when using websocket. 
Is there some solution that can get url before create `WebSocket ?

do it by promise before `new WebSocketSubject(...)` is not good way for getter. right?

**Comment by luillyfe** [comment]
Related, https://github.com/ReactiveX/rxjs/issues/4197

**Comment by cartant** [comment]
[This SO answer](https://stackoverflow.com/a/51147023/6680611) of mine seems related.

**Comment by luillyfe** [comment]
@cartant  **I think that SO answer is an awesome approach to this issue**, however I do still considering that having to re-subscribe every time you get the url, it still feels like a hack. **Given the chance to compute the url in async before make any subscription will be wonderful.**

**Comment by cartant** [comment]
@luillyfe You can use the same concept with an observable source that emits the URL instead of explicit calls to `reset`, etc. I think the bottom line is that extending `WebSocketSubject` to support a 'dynamic URL' is unnecessary. It can be handled in user-land code.

**Comment by luillyfe** [comment]
> you'd be using a caller-specifed observable instead of the example's internal resetter subject.

No way, if we give the user the change **to compute the url in async**, he can use whatever approach he wants to get that url, let's  say **obsevable, promise, async/await, callback**. It nas not to be attached to one observable/subject. This will give to the developer better flexibility. 
Let's say that the service that computes that url is already written, with the **observable/subject** approach, that service would has to be re-written.

**Comment by cartant** [comment]
@luillyfe The user can use `from` for those things. Regardless, I don't agree that `WebSocketSubject` should be extended to support a 'dynamic URL'.

RxJS offers the necessary tools to do this if you need it. I don't believe it's worth the additional complexity. Interestingly, early versions of `AngularFire2` supported dynamic queries. These were removed due to their complexity, that fact that they weren't often used and because users who did need them could achieve the same outcome using RxJS.
