### ISSUE TITLE
Module not found: Error: Can't resolve 'rxjs-compat/BehaviorSubject' in '/node_modules/rxjs'

### ISSUE THREAD

**Issue by watjs** [ReactiveX/rxjs#4361]
## Bug Report
I'm using RxJs version "^6.3.3" with Angular 6

After removing rxjs-compat from package.json i see this message 

> Module not found: Error: Can't resolve 'rxjs-compat/BehaviorSubject' in '/node_modules/rxjs'

**rxjs-compat** is unnecessary, you don't really need it from version 6 and above (according to official migration guide). so after migrating to version 6 i can get rid off **rxjs-compat**

node_modules/rxjs/BehaviorSubject.d.ts has the following import
> export * from 'rxjs-compat/BehaviorSubject';

node_modules/rxjs/BehaviorSubject.d.ts need to be fixed,  if rxjs does not rely on rxjs-compat

rxjs-compat imports are in all typing files. so i must include rxjs-compat in package.json?

Thank you in Advance

**Comment by cartant** [comment]
If you are seeing that error, you are trying to import from `rxjs/BehaviorSubject`.

Don't.

Import like this instead:

```ts
import { BehaviorSubject } from "rxjs";
```

What you are seeing is the expected behaviour.
