### ISSUE TITLE
RxJS 6: switchMap not unsubscribing depending on import of Observable

### ISSUE THREAD

**Issue by brunojcm** [ReactiveX/rxjs#4363]
## Bug Report

I can still observe the same problem reported in #3306, but using RxJS 6, contrary to what is stated in https://github.com/ReactiveX/rxjs/issues/3306#issuecomment-374346659.

As #3306 is blocked for new comments, I'm reporting a new one to see if there is any action that can be taken.

**Current Behavior**
I have a typescript file creating an observable (merge) based on a few other observables, nothing out of the ordinary:

```js
const merged$ = merge(
  a$.pipe(tap(() => console.log("side effect!"))),
  b$,
  c$
).pipe(
  ...
)
return merged$
```

For some weird reason, the rxjs-related imported were as follows:

```js
import { Observable } from 'rxjs/internal/Observable'
import { merge, Subject } from 'rxjs/index'
import { Subscription } from 'rxjs/internal/Subscription'
```

This returned observable was then handled to a component, which would `switchMap()` a lot of times over the same instance of the returned observable. With the imports stated above, though, `switchMap()` was not unsubscribing properly, so on every `switchMap()`'s "switch", the previous subscribed observable (`merged$`) was still producing side effects, even after it was supposed to be unsubscribed, producing n+1 side effects for each `a$`'s emission after each "switch".

**Expected behavior**
`switchMap()` should properly unsubscribe the previous observable before subscribing to the next one. After changing the imports (see below), everything started working as expected.

**Environment**
- Runtime: e.g. Node v10.4.0, Chrome v70.0.3538.77
- RxJS version: 6.3.3

**Possible Solution**
Use the official import way stated in the docs:
```js
import { merge, Observable, Subject, Subscription } from 'rxjs'
```

**Comment by kwonoj** [comment]
first, it may need reproducible code. Moreover, importing from `internal` is already red flag: that is not supported in any way, so we won't likely able to suggest workaround based on current import. What makes imports from unsupported internal scope and reason can't to properly imports?

**Comment by kareljuricka** [comment]
Confirming this issue. Last two days I spend on searching memory leaks in app. 
I'm using combineLatest operators and after destroying of components, memory stayed uncleaned. When I was totally crazy about reasons (tried everything to unsubscribe), I found this new issue and it saved my ass.

**Comment by cartant** [comment]
@kareljuricka If you have confirmed it, please provide a minimal reproduction.

**Comment by brunojcm** [comment]
@cartant I can try to reproduce as well, I just didn't do that beforehand because it's going to be very hard and time consuming, and it seems using internal imports is not supported anyway, so I'm wondering it's worth doing.

**Comment by cartant** [comment]
@brunojcm One thing you could do is provide the code that shows the internal import being used. You mention in the issue some internal imports, but you don't show them being used.

**Comment by benlesh** [comment]
This appears to be resolved as "bad imports". Closing.
