### ISSUE TITLE
deferred observable is not replayable when using retryWhen

### ISSUE THREAD

**Issue by bene-starzengruber** [ReactiveX/rxjs#4368]
## Bug Report

**Current Behavior**
If a deferred observable is shared and retried, it is only really sharing the source if it is not synchronous.

![image](https://user-images.githubusercontent.com/18653151/48843763-4f892500-ed98-11e8-8a3d-e20fec128c97.png)

**Reproduction**
https://stackblitz.com/edit/rxjs-8jmdxm

**Expected behavior**
Observable is shared and errors are the same for all subscribers. So for two subscribers, it should look like this (retried once):

![image](https://user-images.githubusercontent.com/18653151/48843822-88c19500-ed98-11e8-8cc0-de6a43d7d7c3.png)

**Current behavior**
Different subscribers are getting different errors
![image](https://user-images.githubusercontent.com/18653151/48843866-a68efa00-ed98-11e8-9426-8852995510e0.png)

**Environment**
Chrome Latest

**Comment by cartant** [comment]
`shareReplay` doesn't replay errors, so this looks like the expected behaviour, to me.

**Comment by cartant** [comment]
Because using a scheduler allows multiple subscribers to subscribe before the `shareReplay` operator receives the error. Without the scheduler, the error is effected as part of the subscription, as it's synchronous.
