### ISSUE TITLE
Links in Operators are all broken in doc/operators.md

### ISSUE THREAD

**Issue by ApolloTang** [ReactiveX/rxjs#4373]
### Documentation Related To Component:

doc/operators.md

### Please check those that apply

- [ ] typo
- [x] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue

For example: 
In page 
https://github.com/ReactiveX/rxjs/blob/5.5.12/doc/operators.md
LInk to 'fromEvent' 
https://github.com/ReactiveX/rxjs/blob/5.5.12/class/es6/Observable.js~Observable.html#static-method-fromEvent
does not exist

same for v6.3.3:
https://github.com/ReactiveX/rxjs/blob/6.3.3/class/es6/Observable.js~Observable.html#static-method-fromEvent

**Comment by benlesh** [comment]
I think this was mostly addressed in #6380. Either way, this is sort of a vague issue.
