### ISSUE TITLE
typing of Subject pipe should return a Subject type instead of Observable

### ISSUE THREAD

**Issue by aitboudad** [ReactiveX/rxjs#4379]
## Bug Report

**Current Behavior**
when creating a Subject wih pipe operator the returned type should be Subject:
```ts
search$ = (new Subject<string>()).pipe();
```
with the current behavior we cannot call `next` method as it raise the following error:
```ts
search$.next();
// Property 'next' does not exist on type 'Observable...
```

updating the Observable declaration into the following code seems to fix that issue:

```ts
export declare class Observable<T> implements Subscribable<T> {
  pipe<A extends Observable<T>>(): A;
}
```

**Comment by kwonoj** [comment]
Due to designed behavior of observable, once operator chained in pipe it should return observable. What usecases you need to invoke `pipe` without any operator?

**Comment by aitboudad** [comment]
for example, whenever a search is called I want to reset some config so instead of:
```ts
inputField$: Subject<number> = new Subject<number>();
search$ = inputField$.pipe(
    tap(page => this.page = 0),
);
```
we can just define a single variable for that:
```ts
search$ = (new Subject<number>()).pipe(
  tap(page => this.page = 0),
);
```
another usecases can be found here: https://github.com/aitboudad/ngx-loading-bar/blob/master/packages/core/src/loading-bar.service.ts#L9

**Comment by kwonoj** [comment]
That involved `tap` operator already. As said above, each operator creates new observable, so just updating type doesn't achieve what you desired. Afaik there are couple of dupe issue discussed around `lift` and this behavior, so far I don't think we'll change major design in v6 (and potentially v7 as well).
