### ISSUE TITLE
Move retry and retryWhen to kitchensink?

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#438]
This one is debatable, but currently you can accomplish both of these trivially with `catch()`...

retry:
```js
obs.catch((err, source) => source);
```

retryWhen:
```js
obs.catch((err, source) => Observable.timer(1000).concat(source));
```

I say this is "debatable" because `.retry()` is pretty readable. Also, trying to do `retry(count)` with `catch()` would mean introducing some state on the part of the user... again, it would be trivial, but it's not *quite* as friendly.

**Comment by staltz** [comment]
I believe it is quite common to use `retry` with a `count`, and it's better to have a dedicated operator than to always teach how to accomplish it with state, so I'd vote for keeping it as core. Just my two cents.

**Comment by blesh** [comment]
You're probably right. I'll leave this open for a another week or so, then close it.

**Comment by mattpodwysocki** [comment]
@blesh retry is super common especially with regards to any data access application, so removing that, you might as well remove catch and finally

**Comment by staltz** [comment]
@blesh time to close this little fellow?
