### ISSUE TITLE
[docs]: Create a design system for marble diagrams - a standard for marble diagrams

### ISSUE THREAD

**Issue by BioPhoton** [ReactiveX/rxjs#4382]
# (UPDATE): I started to collect all outcome and questions here:    
# [Rx-Marble-Design-System](https://github.com/BioPhoton/Rx-Marble-Design-System) 

- [ X ] documentation doesn't exist
- [ X ] documentation needs clarification

### Description Of The Issue

Why is this important?

Marble diagrams where ever since a very practical and easy way to explain the behavior of streams in a visual way. There are a lot of diagrams out there, but they are not fully explaining the complex behavior or more important internal workflows. Also, there are different scenarios for some operators that are only possible to explain in diagrams if we would have internal workflows visible.
Furthermore, there is a lack of a standard for these diagrams. 

What I want to create is:
A public open source standard of drawing marble diagrams
An easy and more important quick way for everyone to create marble diagrams 
If the standard is done I will create diagrams for all operators and their different scenarios

Here is where I started with: https://docs.google.com/presentation/d/1LlVmTEcoc1LRV00Tp-rDp4kopI-NobC9S2w-w5pC_JA/edit?usp=sharing

As you can see there are a lot of questions to answer.
What I would need is people that help me to discuss several edge cases to generate this standard.
Also if the standard is finished I would need a second pair of eyes that help me to double check the drawings for all the operators.

**Comment by kwonoj** [comment]
This is quite interesting but I am bit unsure if we can define something. We define semantics of marbles, but does not define how does it visualized: i.e even in ascii marble we allow all chars as marble tokens vice versa. Also even if we have something not sure if we can enforce to everyone use those instead of each user's page design.

**Comment by JWO719** [comment]
Hey there, 
I really love that idea, especially for the docs web page. Ideally it comes with consistency and clarity. 

@kwonoj Maybe I get you toally wrong, and for sure we can't enforce anyone to use this kind of semantic, but is your point really just about semantic? I think we can define some kind of standard. I think we already did in some way (see http://reactivex.io/rxjs/manual/overview.html#marble-diagrams)

Anyway I definetly think, that this is a topic we should discuss at the next core team meeting!

**Comment by kwonoj** [comment]
@JWO719 I don't think what we represented in http://reactivex.io/rxjs/manual/overview.html#marble-diagrams is same as proposal here. i.e `font`, `lines`, `color`, `shaping` and vice versa design aspects are something we don't define - in our diagram what we defines is just semantics. i.e we use `x` as error in attached pics, but in ascii marble we do use `#` instead, etcs. We don't enforce what kind of visual representation as long as it's described to follow our semantics.

**Comment by JWO719** [comment]
For sure we can't enforce this level of consistency across all users of rxjs. Maybe I'm a bit newbie to oss for those kind of stuff. But in my point of view, this is a thing we (core team) should agree on and spread it. So that maybe at some point the community will stick to it. I just think that most of the marble diagramms hide the complexicity of operators. Maybe that's good for some use cases (operator- or target group wise) but in general we should make things as clear as possible.

**Comment by kwonoj** [comment]
> But in my point of view, this is a thing we (core team) should agree on and spread it.

If this is only for semantics, I would agree and it's widely accepted already. I would disagree for whole scope of proposal as something we'd encourage, like design elements. I don't feel we'll introduce some guidelines like `fonts`, `element design` and vice versa. In short, I believe given proposal's scope is too broad for core.

For semantics, we do already have it https://github.com/ReactiveX/rxjs/blob/master/doc/marble-testing.md#marble-syntax (and some extended proposal here https://github.com/kwonoj/rx-sandbox#observable-marble-diagram-token-description).

**Comment by BioPhoton** [comment]
@kwonoj 
About your schemantics:
You can also create a design manual for ascii marbles: https://docs.google.com/presentation/d/1UqVkGH_mZ10WvbPqEAUE0nsJUkbvfvGXfFEWghbA4RA/edit?usp=sharing

The "standard" should help to draw and understand these diagrams. ascii marbles dont give much options to show internal workflows ect. 

Here are some operators I tested to draw:
![retry](https://user-images.githubusercontent.com/10064416/48985647-f4459280-f109-11e8-971b-5e3b36fae6b2.gif)
![exhaustmap](https://user-images.githubusercontent.com/10064416/48985650-f90a4680-f109-11e8-86c5-873d97491bd7.gif)

**Comment by BioPhoton** [comment]
> I don't feel we'll introduce some guidelines like fonts, element design and vice versa. 
> In short, I believe given proposal's scope is too broad for core.

Don't stick too much with font, and exact sices. The idea of a design system is way more than the design aspect. It's a set of standard elements (like your ascii marbles) that can be used to create a diagram in a way you don't have to think about spacing, what to use for unsubscribe or if your colors are also good for colorblind ppl.

if you explain marbles in tge docs (which is the case) you should think it through, consider edge cases, test it against complex problems and sume up everything at obe place for ppl to read.
This is the idea of the design system. 😀

**Comment by srounce** [comment]
<img width="200" alt="screenshot 2018-11-26 at 14 50 23" src="https://user-images.githubusercontent.com/60792/49021539-c2c0db80-f18a-11e8-8191-03915b69e71d.png">
This is not a Hexagon.

**Comment by BioPhoton** [comment]
@srounce Thanks a lot for your feedback!!
>This is not a hexagon.

FIXED

>Possible bike-shedding/out of scope with regard to typefaces. Perhaps simply specifying, that description typefaces are monospace, and providing an em-height scale relative to the block size would be more helpful.
I created some notes for the fonts to elaborate that the actual font family is irrelevant but mono-space and so on..

Could you help me to create the right content for the "font related" slide? 

>A set of rules around hand-written notation would arguably be more useful, also they would also be a better guide to the high-fidelity versions you're currently working on.

Most of the diagrams will consist of only basic blocks and complexity. The examples are just here to show how details it could go and where the end is. ;-)

> Having special border styles for an observeOn/subscribeOn stage dependant on the scheduler won't work.

Removed this option! Thanks

>How does this combine with operators like delay for instance?
ATM I don't know. If context would be the border I would do something like this for delay:
![image](https://user-images.githubusercontent.com/10064416/49046449-75695c00-f1d4-11e8-9041-7f546574f2ab.png)

But the scheduler is also a "nice to have level detail" and nothing i would draw in every diagram.

**Comment by pertrai1** [comment]
I think that this is a great idea and if flushed out more, it could be of huge help in getting people more into using RxJS.

**Comment by BioPhoton** [comment]
@LayZeeDK Thanks for your feedback!
Could you help in providing some tools to check the colors? 

It would be also amazing if you could take a quick look at slide 5,6,7 and 33 [here](https://docs.google.com/presentation/d/1LlVmTEcoc1LRV00Tp-rDp4kopI-NobC9S2w-w5pC_JA/edit?usp=sharing)

And share your thoughts on it.

**Comment by LayZeeDK** [comment]
> Could you help in providing some tools to check the colors?
I have previously used Chrome extensions. If I remember correctly, [Spectrum](https://chrome.google.com/webstore/detail/spectrum/ofclemegkcmilinpcimpjkfhjfgmhieb) is a good one.

**Comment by BioPhoton** [comment]
Thank you so much for thoughts @LayZeeDK !

Atm I'm implement the feedback that I got about fonts and sizes. 
I'll insert some notes in the document about your thoughts on colors and shapes. 

> To be honest, I am not sure that using different colors provide enough value compared to the visual noise that they create. Different shapes are enough and there are a lot to choose from.
> 
> If you are absolutely certain that we need value colors, ...

Im not certain of anything. At the moment it is an adventure for me. 
I'm trying to find out what the different informations in marble diagrams are and how I can create a design system to make it easy for everyone to create them. 
Further more I try to answer several questions like what purpose serve different shapes or colors, or how to present subscribe, connect, unsubscribe in an intuitive way. 

If you like we can work on some examples that colors are less relevant or show some rare use cases where they are needed. Later we can ask ppl what they think and how they see it.

Here are some ways to use colors that I have created to reason about. Do you have any other ideas for examples? It's also on the [design system doc](https://docs.google.com/presentation/d/1LlVmTEcoc1LRV00Tp-rDp4kopI-NobC9S2w-w5pC_JA/edit#slide=id.g494cce4516_0_4450) on slide number 34.
![draft - rx marbles diagrams design manual](https://user-images.githubusercontent.com/10064416/49504030-29c04d80-f879-11e8-90c5-58a9c4d15ed1.jpg)

**Comment by BioPhoton** [comment]
@srounce I included all your feedback regarding font sizes in em in the doc under [fonts](https://docs.google.com/presentation/d/1LlVmTEcoc1LRV00Tp-rDp4kopI-NobC9S2w-w5pC_JA/edit#slide=id.g33a2ef545a_0_84)  and and later in [description](https://docs.google.com/presentation/d/1LlVmTEcoc1LRV00Tp-rDp4kopI-NobC9S2w-w5pC_JA/edit#slide=id.g4949e1b8ea_1_361) .

My em is related to 1 block. I also limited font size and style for specific use. 
At the moment I have the question if I should have only one font-size for values.
Maybe you can have a look and give a last feedback on this question here again the [link](https://docs.google.com/presentation/d/1LlVmTEcoc1LRV00Tp-rDp4kopI-NobC9S2w-w5pC_JA/edit#slide=id.g4949e1b8ea_1_361)  to my section with the question

**Comment by srounce** [comment]
Thanks dude, will have a look, I plan on taking some time this weekend to add more detailed thoughts on this.

**Comment by BioPhoton** [comment]
@LayZeeDK 
> (On a side note, I have actually got a SCSS mixin somewhere that calculates whether a light or dark foreground color should be used on a background color to provide enough contrast).

Could you please provide it in some way?

**Comment by LayZeeDK** [comment]
I will try to get around to looking it through before making it public. Maybe during the holidays.

**Comment by LayZeeDK** [comment]
> @LayZeeDK
> 
> > (On a side note, I have actually got a SCSS mixin somewhere that calculates whether a light or dark foreground color should be used on a background color to provide enough contrast).
> 
> Could you please provide it in some way?

[YIQ Color Contrast (sass-yiq)](https://www.npmjs.com/package/sass-yiq)

**Comment by BioPhoton** [comment]
The design tokens and components are almost done. :-)
One last problem with visualizing the operator context is missing. 

Thx again to all the feedback and I hope for some more!
Here you can check out the current status: 
[Marble Design System](https://docs.google.com/presentation/d/1LlVmTEcoc1LRV00Tp-rDp4kopI-NobC9S2w-w5pC_JA/edit#slide=id.g4a86eb9f3a_1_39)

@srounce Also the font related problems are solved. You may want to have a look. :-)
 
![rx marble design system - teaser v1](https://user-images.githubusercontent.com/10064416/50119882-52225180-0254-11e9-9c9f-01f128dd71e1.jpeg)

**Comment by benlesh** [comment]
There's a lot of great discussion here. However, I'm not sure the team has the bandwidth to support this sort of effort (as evidenced by the lack of traction here). I'm going to close this one for now, just to clean things up. But thanks again for the awesome input and thoughts, @BioPhoton. This is definitely something I'd love to see in userland to see how well it works out.
