### ISSUE TITLE
combineLatest typings does not reflects on its behaviour

### ISSUE THREAD

**Issue by dkosasih** [ReactiveX/rxjs#4384]
## Bug Report

**Current Behavior**
combineLatest operator does not infer correctly for `ObservableInput<T>[]` signature

**Reproduction**
```js
      const a = of(1, 2, 3);
      const b = [of('a', 'b', 'c')];
      const res = a.pipe(combineLatest(b, (a, b) => b)); // $ExpectType Observable<[number, string]>    
```

**Expected behavior**
The above code should be passing. However, it infers `Observable<Observable<string>>`.

**Additional context/Screenshots**
Please refer to @cartant comment [here](https://github.com/ReactiveX/rxjs/pull/4371#discussion-diff-236068126R104)

Please note that this is also apply for merge operator the signature is similar and it would be great if we could get it fix together.

**Comment by cartant** [comment]
Closing this 'cause - in v7, at least - the inference is correct.
