### ISSUE TITLE
RXJS 5.5 - Path Mapping for ES2015 broken ?

### ISSUE THREAD

**Issue by nadavsinai** [ReactiveX/rxjs#4389]
## Bug Report

**Current Behavior**
I have a dual build system for ES5/2015. ES5 works fine with the path alias.
in ES2015 build, The build completes but the application crashes in initial load with
````
ScalarObservable.js:7 Uncaught ReferenceError: Observable is not defined
```
I've tried to removed Angular Build optimizer, Uglify, and all other plugins in my build and narrowed the problem to ES2015 path mapping of rxjs I am using as documented in your docs.
when I remove the path mapping alias it works.
when I mean es2015 build I mean that webpack prefers es2015 field in package.json on module, browser, main. and that I compile my typescript to es2015, set my uglify-es to work in ecma:6 etc..
````
I manged to workaround the issue using this:
````
const rxPathsEs5 = require("rxjs/_esm5/path-mapping");
const rxPaths = require("rxjs/_esm2015/path-mapping");
... webpack config... {
resolve: {
				alias: {
					...(legacy ? rxPathsEs5() : rxPaths()),
					"rxjs/observable/ScalarObservable": root("./node_modules/rxjs/observable/ScalarObservable"),
					"rxjs/observable/ArrayObservable": root("./node_modules/rxjs/observable/ArrayObservable"),
				},
			},
````

but then (perhaps obviously )  in source-map-explorer I get "two versions" of rxjs - one of es5 (with all the operators) and one of es2015 (with some used operators)

The weirdest part of this (really I've seen a few, I'm in charge of the build of ~20 apps here) is that if I come back to the broken version and remove sourcemapping I can see that all names are managled (via uglify) but that Observable stays Observable and is not mapped to some one letter variable that is defined by calling n(000) (runtime webpack require with module ID).
This is at least the case in ScalarObservable, three frames down the stack chain - we're in @angular/core importing merge operator and there we DO have observable --> look at the scope of the frame in the attached screen shots
from there we go to ArrayObserbale (which doesn't have Observable)
and finally to ScalarObservable which explodes.

I've looked hard into my rxjs imports and couldn't find anything strange, all using proper 
rxjs/Observable rxjs/Subject etc (with the capitalized letter ) for the base classes, using imports from 'rxjs/operators' for operators and 'rxjs/observable/<creation>' for creation methods like "of" etc..

I know you're deep in v7 work and other more modern stuff and probably don't want any v5 issues bugging you, just to comfort you that I've already put a days work into that before contacting you, and that i'll be happy to submit a PR if I find anything myself, however I do wanted to raise your attention on the matter and check if you have any clues to what may be causing the issue.

**Expected behavior**
Path mapping should allow whole ES2015 rxjs for better tree-shaking without including any ES5 code

**Environment**
- Runtime: Node 9.10.1, Chrome 70.
- RxJS version: 5.5.12
- Webpack : 4.16.4,
- @ngtools/webpack": "6.2.3

**Possible Solution**
 some missing path in es2015 map? bad internal import?

**Additional context/Screenshots**

![runtime](https://user-images.githubusercontent.com/2870816/49139529-b2c80980-f2fa-11e8-89f0-4dc8856425fc.png)
![runtime1](https://user-images.githubusercontent.com/2870816/49139530-b360a000-f2fa-11e8-8ba7-607c3768e1d0.png)
![runtime2](https://user-images.githubusercontent.com/2870816/49139532-b360a000-f2fa-11e8-8e7e-d262d3d8c16a.png)
![sourcemap](https://user-images.githubusercontent.com/2870816/49139533-b360a000-f2fa-11e8-960b-c48a3bbe3f7a.png)

** stacktrace (modified to remove bloat of webpack require)**
````````
ScalarObservable.js.pre-build-optimizer.js:7 Uncaught ReferenceError: Observable is not defined
    at Object.<anonymous> (ScalarObservable.js.pre-build-optimizer.js:7)
    at i (webpack require:159)
    at Object.<anonymous> (ArrayObservable.js.pre-build-optimizer.js:2)
    at i (webpack require:159)
    at Object.<anonymous> (merge.js.pre-build-optimizer.js:1)
    at i (webpack require:159)
    at Module.<anonymous> (core.js.pre-build-optimizer.js:1)
    at Module.<anonymous> (animation_metadata_wrapped.js:167)
    at i webpack require:159)
    at Object.<anonymous> (common.js.pre-build-optimizer.js:1)

**Comment by nadavsinai** [comment]
I have some progress. the issue is caused by angular_devkit/build_optimizer after all. 
I have it enabled as two loader rules, one for ts files (post optimize) and one for js files.
when I started researching I guess I only disabled the TS one, it was the js one that causes the issue.
since you're in the Angular team now, maybe you have an idea about who to ping about it.

I will now try to make a clean reproduction of the issue in stackBlitz .

I believe you can now close this issue here and we'll open a new one at @angular/cli (i guess this is the right place now, although my apps have nothing to do with the CLI)
please advice.

**Comment by nadavsinai** [comment]
yep the app works without build optimizer BUT
I still see that rxjs code is doubled!
both the es2015 code and es5 code. something is still missing from path mapping afterall ?
![image](https://user-images.githubusercontent.com/2870816/49170275-67d2e400-f344-11e8-96b1-6b32bf9b7e51.png)

**Comment by nadavsinai** [comment]
I think I should get webpack stats and get to understand the dependency tree. i'll post a stats file or findings when I do

**Comment by nadavsinai** [comment]
made the webpack stats (60+ mb) so not attaching...
the bad import was in a library importing something from 'rxjs'
we'll make a PR and fix it.
can't the es2015 path mapping redirect the root import site to rxjs/_es2015 ?

**Comment by benlesh** [comment]
Hi, @nadavsinai, is this still an issue for you? Webpack configurations and module resolutions are a little out of my area of expertise. Pinging @jasonaden who worked on compat and publishes, maybe he can help.
