### ISSUE TITLE
isDefined Operator

### ISSUE THREAD

**Issue by oleersoy** [ReactiveX/rxjs#4399]
## Feature Request

```
pipe(isDefined) //Returns and Observable(true) if the value is defined / not null, otherwise Observable(false)
```
https://stackoverflow.com/questions/53575909/pipe-operator-that-returns-a-boolean-valued-observable/53579914#53579914

**Comment by kwonoj** [comment]
Stackoverflow answer already explains crux of ooerator behavior and it can be trivially implemented via existing operator. I do not think this would require core api surface but more for using existing operator or userland module if needed.
