### ISSUE TITLE
AsyncIterable support in from() in 6.x minor version?

### ISSUE THREAD

**Issue by felixfbecker** [ReactiveX/rxjs#4404]
I saw https://github.com/ReactiveX/rxjs/issues/1624 is already implemented in an experimental branch. Since it's a feature, could we release it in 6.x?

**Comment by benlesh** [comment]
I had to roll it back due to some incompatibilities. It's planned, and it's even in the experimental branch, there's just other high-priority work that needs to happen first.

**Comment by benlesh** [comment]
This is supported in 7.x now.
