### ISSUE TITLE
Partition operator example throws typescript error

### ISSUE THREAD

**Issue by luckylooke** [ReactiveX/rxjs#4419]
### Documentation Related To Component:

partition operator
https://www.learnrxjs.io/operators/transformation/partition.html
https://github.com/ReactiveX/rxjs/blob/master/src/internal/operators/partition.ts

### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [ ] documentation needs clarification
- [x] error(s) in example
- [ ] needs example

### Description Of The Issue

Opening the [example in Stackblitz](https://stackblitz.com/edit/typescript-gr3ljs?file=index.ts&devtoolsheight=100) we are getting typescript error:
```
Argument of type 'UnaryFunction<Observable<number>, [Observable<number>, Observable<number>]>' is not assignable to parameter of type 'OperatorFunction<any, any>'.
  Type '[Observable<number>, Observable<number>]' is not assignable to type 'Observable<any>'.
    Property '_isScalar' is missing in type '[Observable<number>, Observable<number>]'.
```
typescript is not complaining about this usage:
```
const [evens, odds] = partition((val: number) => val % 2 === 0)(source);
```
Result is the same.

I did not check other example or other online editors but IMHO it would be the same.

I do not have more time for making PR, also I am not sure about whether implementation should be fixed not to confuse typescript or syntax in examples should follow the usage I have provided here.
Sorry.

Thank you for your time and happy coding :)

EDIT:
I have just check jsBin and jsFiddle. I have find out that they are not relevant as they does not support typescript errors. I have tested `const num: Number = 'text';` and they both did not complain at all.

**Comment by jgbpercy** [comment]
That error is the "correct" error. Partition isn't usable within pipe because it's not really an operator, for the reason I explained in 4119:

Partition returns a UnaryFunction, not an OperatorFunction, and pipe only takes OperatorFunctions as arguments. It seems like partition was broken (at least when used in pipe) with the move to pipeable operators, but the clean up work to deprecate/replace it hasn't been priority as partition isn't that widely used. See these issues:

https://github.com/ReactiveX/rxjs/issues/3797
https://github.com/ReactiveX/rxjs/issues/2995
https://github.com/ReactiveX/rxjs/issues/3807

So TS is right to complain about partition being used in pipe, but you can still use partition as a function in its own right, I believe.

**Comment by luckylooke** [comment]
Ok, so then examples should be fixed as they use partition as pipe now:
```
const [evens, odds] = source.pipe(partition(val => val % 2 === 0));
```
:)

**Comment by benlesh** [comment]
Partition should really have been a static function, and not an operator. That's the real solution here. And also updating the docs.

**Comment by dkosasih** [comment]
I'll grab this one if no one has started working on this?

**Comment by DaSchTour** [comment]
I wonder who made the statistics that tell that partition isn't widely used. I think there are valid scenarios where you want to have to safetly partitioned Observables where you know that they will never emit the same value. My current solution is really extremely ugly and verbose.
```
this.isMobileLayout = this.breakpointObserver.observe([Breakpoints.Handset]).pipe(map((result) => result.matches));
        this.isDesktopLayout = this.isMobileLayout.pipe(map((value) => !value));
```

**Comment by szalonna** [comment]
Hello,
Is there any update related to this or what is the current situation with the `partition` operator?

**Comment by jgbpercy** [comment]
`partition` as an operator used within `pipe` does not make sense and is deprecated.

`partition` as a [stand alone "creation function"](https://github.com/ReactiveX/rxjs/blob/6.x/src/internal/observable/partition.ts) can be used just fine.

**Comment by benlesh** [comment]
This has been resolved by providing a static `partition` function and deprecating the operator version for removal in version 8. Other use cases could be met with `groupBy`. Closing this issue.

```ts
import 
const [evens$, odds$] = partition(of(1, 2, 3, 4, 5), n => x % 2 === 0);
```
