### ISSUE TITLE
Expose isPromise similarly to how isObservable was exposed

### ISSUE THREAD

**Issue by ChrisDahmCS** [ReactiveX/rxjs#4424]
## Feature Request

isPromise is currently an internal method, but isObservable was recently (6.1) exposed out of internal.

**Describe the solution you'd like**
Similarly to isObservable, isPromise could be exposed instead of being kept internal. 

**Describe alternatives you've considered**
Other teams/groups have basically copied the code from this method to check for isPromise [like the Angular team](https://github.com/angular/angular/blob/master/packages/core/src/util/lang.ts#L14-L18).

**Comment by benlesh** [comment]
As described in my comments on the PR, we don't want to expose `isPromise` and be on the hook for maintaining that for all users. Closing this one. Thanks you for the suggestion!
