### ISSUE TITLE
`zip()` has definitions which doesn't work

### ISSUE THREAD

**Issue by hshn** [ReactiveX/rxjs#4431]
## Bug Report

**Current Behavior**

`zip()` with `array: Observable<T>[]` argument doesn't work, but the function has still the definitions.

https://github.com/ReactiveX/rxjs/blob/6885f4c9a5c075d2d89c44305a732b3e8ede849f/src/internal/observable/zip.ts#L33-L34

related to #3347

**Reproduction**
- REPL or Repo link: https://stackblitz.com/edit/rxjs-nekdf4

```js
import { of, zip } from 'rxjs'; 
import { map } from 'rxjs/operators';

const source1 = zip([
  of('hello'),
  of('world'),
]);

// nothing is happen
source1.subscribe(x => console.log('source 1', x));

const source2 = zip(...[
  of('hello'),
  of('world'),
]);

// it works as expected
source2.subscribe(x => console.log('source 2', x));
```

**Expected behavior**

raising compilation error, or supporting `array: Observable<T>[]` argument without spread operator would be better.

**Environment**
- Runtime: Node v10.14.0
- RxJS version: `6.3.3`

**Possible Solution**

erase the function definitions of `zip<T>(array: ObservableInput<T>[]): Observable<T[]>`, or fix method to support array observables without spread operator.

**Additional context/Screenshots**

**Comment by ajcrites** [comment]
The type `export function zip<T>(...observables: Array<ObservableInput<T>>): Observable<T[]>;` can be satisfied by `zip(arrayValue)` as well as `zip(...arrayValue)`. This is arguably a bug in TypeScript.

We could still remove the other type definitions since they seemingly work the same, but this won't prevent users from providing an array argument.

**Comment by sjyn** [comment]
Hi, I've come across this issue as I've been learning rxjs. It looks like passing the array does **not** work, but passing with the spread does.

https://stackblitz.com/edit/rxjs-f6wqpp

**Comment by hshn** [comment]
@ajcrites 

Oh.. I didn't know about the bug.

I'd like to remove the type definition, because there is still possibility to notice that I was writing was wrong if there isn't the type definition.

**Comment by dmayerdesign** [comment]
+1-ing this as it's eroded my trust in your type definitions! Is anyone able to confirm whether or not it's a TypeScript bug?

**Comment by squidfunk** [comment]
Just ran into this. I think that those lines should be removed:

https://github.com/ReactiveX/rxjs/blob/388c4852948660abcff22d7b82ccb0a29c77428c/src/internal/observable/zip.ts#L33-L36

If I now pass an array of observables without the spread operator, `tip` will treat the array as observable input, and construct an observable of observables. TypeScript will now show than `zip` will emit an array of observables, which will correctly be indicated as an error.

**Comment by cartant** [comment]
Closing this as the types/signatures for `zip` have been updated and it now has these signatures:

https://github.com/ReactiveX/rxjs/blob/4805a7fecfa5d9732e0329fb463e11d62c219238/src/internal/observable/zip.ts#L9-L19
