### ISSUE TITLE
subscribeOn has missing description.

### ISSUE THREAD

**Issue by hassam7** [ReactiveX/rxjs#4436]
### Documentation Related To Component:

subscribeOn operator

### Please check those that apply

- [ ] typo
- [x] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue

The subscribeOn operator has missing documentation [description](https://rxjs-dev.firebaseapp.com/api/operators/subscribeOn).

![asdzxc](https://user-images.githubusercontent.com/10061444/50372477-b5afd480-05f0-11e9-905a-babf42306492.PNG)

**Comment by Spetastian** [comment]
I wanted to learn more about schedulers in RxJS. I did so and created a PR for this here: https://github.com/ReactiveX/rxjs/pull/4600

**Comment by Spetastian** [comment]
This issue can be closed now since the PR has been merged i guess? If you guys are happy with the result in the docs.

**Comment by JWO719** [comment]
I'm super happy with it. Thanks again for the contribution!
