### ISSUE TITLE
bootstrapping rxjs

### ISSUE THREAD

**Issue by swedebugia** [ReactiveX/rxjs#4443]
I would like to package rxjs with Guix. 
This means bootstrapping from zero.
Will this work?
6.3.3
^
5.5.7
^
rxjs 5.0.0
^
rx 4.1.0

**Comment by kwonoj** [comment]
Please provide details to understand what problem you're experiencing.

**Comment by swedebugia** [comment]
Its not a problem per se. I'm wondering how to bootstrap rxjs from scratch and I see that rxjs 5.5.7 appear in the devdependencies of the latest rxjs. In the package.json of rxjs 5.0.0 no rxjs appear but rx is there.
Is it correctly understood that rxjs needs an earlier version of itself to be built?

**Comment by kwonoj** [comment]
> Is it correctly understood that rxjs needs an earlier version of itself to be built
>  I see that rxjs 5.5.7 appear in the devdependencies of the latest rxjs

No. RxJS repo itself have devdependencies to itself for some testing purpose only, This is not related with any application level dependency usage / or building rxjs itself. Same applies to other version (i.e 5.x you mentioned).
