### ISSUE TITLE
WebSocketSubject failing to close underlying socket

### ISSUE THREAD

**Issue by rsikdar** [ReactiveX/rxjs#4447]
## Bug Report

**Current Behavior**
If the WebSocketSubject is unsubscribed before the connection is in the open state (readyState = 1), it does not close the socket connection, and resets the subject state.

This happens both from calling unsubscribe directly on the subject, and when the last subscriber calls unsubscribe on their subscription.
https://github.com/ReactiveX/rxjs/blob/master/src/internal/observable/dom/WebSocketSubject.ts#L279
https://github.com/ReactiveX/rxjs/blob/master/src/internal/observable/dom/WebSocketSubject.ts#L290

**Reproduction**
An example of both scenarios is shown in the testing changes in #4446 

**Expected behavior**
If there are no longer any subscribers, the socket should be terminated as soon as it's finished connecting.

**Environment**
- Runtime: all
- RxJS version: 6.3.3

**Possible Solution**
Created PR #4446 as a possible solution.

**Comment by benlesh** [comment]
This is closed by #4863
