### ISSUE TITLE
Multicast lacks overload

### ISSUE THREAD

**Issue by Austaras** [ReactiveX/rxjs#4451]
## Bug Report

**Current Behavior**
multicast operator lacks following typing

```ts
export declare function multicast<T>(subject: Subject<T>, selector?: MonoTypeOperatorFunction<T>): MonoTypeOperatorFunction<T>;
```

**Expected behavior**
```ts
multicast(new Subject<number>, sub => sub) 
```
should compile

**Environment**
- Runtime: typescript 3.2.2
- RxJS version: 6

**Possible Solution**
add this overload

**Comment by cartant** [comment]
Is this not the signature you are looking for?

https://github.com/ReactiveX/rxjs/blob/6.3.3/src/internal/operators/multicast.ts#L11
