### ISSUE TITLE
Types on AjaxRequest are too strong.

### ISSUE THREAD

**Issue by EvanCarroll** [ReactiveX/rxjs#4455]
Platform: **Node.JS**

Currently in order to make a CORS request you have to provide a builder `createXHR`. This is documented in the #3978 I'm using `xmlhttprequest-ts` which is a package that provides the typescript types for xmlhttprequest. The RXJS types though are too strong to accept it; it raises an error 

```
lib/www.ts:7:14 - error TS2345: Argument of type '{ createXHR: () => XMLHttpRequest; url: string; crossDomain: true; responseType: string; withCredentials: false; }' is not assignable to parameter of type 'string | AjaxRequest'.
  Type '{ createXHR: () => XMLHttpRequest; url: string; crossDomain: true; responseType: string; withCredentials: false; }' is not assignable to type 'AjaxRequest'.
    Types of property 'createXHR' are incompatible.
      Type '() => import("/home/ecarroll/code/toponym-esque/node_modules/xmlhttprequest-ts/src/XMLHttpRequest").XMLHttpRequest' is not assignable to type '() => XMLHttpRequest'.
        Type 'XMLHttpRequest' is missing the following properties from type 'XMLHttpRequest': responseType, responseURL, upload, overrideMimeType, onprogress

  7  return ajax({
                 ~
  8     createXHR,
    ~~~~~~~~~~~~
... 
 12     withCredentials: false
    ~~~~~~~~~~~~~~~~~~~~~~~~
 13  });
    ~~
```

If I don't have `xmlhttprequest-ts` and instead try `xmlhttprequest`, I get

```
error TS7016: Could not find a declaration file for module 'xmlhttprequest'. XMLHttpRequest.js' implicitly has an 'any' type.
```

There is no `@types/xmlhttprequest`

**Comment by kwonoj** [comment]
I agree with @cartant , most of strict type in createXHR is used in implementaion of ajaxobservable.

> If I don't have xmlhttprequest-ts and instead try xmlhttprequest, I get

This is super odd and I feel this is crux of your problem. type `XMLHttpRequest` should exist in default typescript compiler's `dom` lib type and it is expected to not having such `@types/xhr` cause it's default types.

**Comment by EvanCarroll** [comment]
I'm confused, what more information can provide to help resolve the issue? Node doesn't ship with an `xmlhttprequest` so you have to install one, right? When I say `xmlhttprequest`, I'm referring to the [npm ` `package`](https://www.npmjs.com/package/xmlhttprequest) That package will otherwise work, but it doesn't have types.

**Comment by kwonoj** [comment]
> Node doesn't ship with an xmlhttprequest so you have to install one, right?

Typescript does ship those types.

https://github.com/Microsoft/TypeScript/blob/master/lib/lib.dom.d.ts#L16798 

and check `--lib` option for it: https://www.typescriptlang.org/docs/handbook/compiler-options.html

I'd strongly suggest to look up typescript documentation first, cause specific dom type we use (`XMLHttpRequest`) is exactly from typescript compiler and we do not use any 3rd party types for it.

**Comment by kwonoj** [comment]
So more information we need is why you can't use `XMLHttpRequest` type but trying to rely on 3rd party types instead, and what cases loosening type will help when we actually require those properties for XHR creation method.

**Comment by EvanCarroll** [comment]
Because there is no XMLHttpRequest implementation for Node.JS. And, i suppose it just so happens to be that all of the implementations are either lacking a type-definition for the module (like `xmlhttprequest`), or are typed with non-core types, which I'm inclined to agree in light of the core types is **very** stupid.

**Comment by kwonoj** [comment]
> XMLHttpRequest implementation for Node.JS

this is true, but in that case polyfill you supplied must fulfill browser side properties use.

I am failed to understand this request, cause we *do use* those properties in our implementation, so as @cartant said just loosening type only will raise runtime error in later. What do we specifically want to resolve here?

**Comment by kwonoj** [comment]
So trying to clarify my statement above,

1. our createXHR accepts either polyfill or native browser impl, but it requires specific properties we do use in our implementation.
2. if polyfill's provided, it should suffice those properties. If 3rd party module you used satisfies it in runtime but only in compile time or vice versa, it need to be cared in 3rd party and we do need to satisfy `XMLHttpRequest` type to be fulfilled

3. What I don't get in this issue is: is this just asking to not check types? or asking to loose runtime behavior? or anything I miss other than those?

**Comment by EvanCarroll** [comment]
I'm in agreement. At this point I'm just complaining because there is no polyfil for node that implements those types. One of the polyfills is untyped, the other is typed stupidly. Thanks for helping me grasp the problem's domain. This isn't on rxjs and fixing it here seems like a shit idea.

**Comment by kwonoj** [comment]
@EvanCarroll lastly, just fyi if you're looking for isomorphic ajax impl, you can check mine https://github.com/kwonoj/oxid for those purpose which uses node's `http` as backend for node.js side instead of using polyfills.

**Comment by EvanCarroll** [comment]
Actually, one more question @cartant  and @kwonoj . Sorry, was just looking into this again. It seems this is the confusion. There are two specs for xmlhttprequest,

* mozdevdoc, https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest
* w3c, https://xhr.spec.whatwg.org/#request

They're not the same and they seem to be incompatible. It seems TypeScript is breaking the w3c spec by going with the MozDev article that specifies that the `XMLHttpRequest` has an implementation of `XMLHttpRequest.responseText `. That's the problem, it's not with a lack of implementation -- it seems to be more logical that TypeScript should implement the w3c spec (which `xmlhttprequest-ts` is doing).

**Comment by EvanCarroll** [comment]
I filed a bug on this issue with TypeScript to use the w3c types instead. When we saw the TypeScript types we assumed everyone should be using them. The nuance that I didn't get was that the TypeScript types are not to the w3c spec. They're based on the docs on mdn, instead.
