### ISSUE TITLE
npm install rxjs@6.3.3 hangs forever on extract

### ISSUE THREAD

**Issue by laprice** [ReactiveX/rxjs#4456]
## Bug Report

**Current Behavior**
npm install of rxjs hangs indefinitely.

**Reproduction**
```

$ npm install --verbose rxjs@6.3.3
npm info it worked if it ends with ok
npm verb cli [ '/data/larry/nvm/v11.6.0/bin/node',
npm verb cli   '/home/larry/.nvm/v11.6.0/bin/npm',
npm verb cli   'install',
npm verb cli   '--verbose',
npm verb cli   'rxjs@6.3.3' ]
npm info using npm@6.5.0-next.0
npm info using node@v11.6.0
npm verb npm-session 0dad4d17396a84ef
npm http fetch GET 200 https://registry.npmjs.org/rxjs 20ms (from cache)
npm timing stage:loadCurrentTree Completed in 139ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 1ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 979ms
npm timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 2233ms
npm timing stage:loadIdealTree Completed in 3886ms
npm timing stage:generateActionsToTake Completed in 654ms
npm verb correctMkdir /home/larry/.npm/_locks correctMkdir not in flight; initializing
npm verb lock using /home/larry/.npm/_locks/staging-863575f20a31dd00.lock for /data/larry/code/mattermost/mattermost-webapp/node_modules/.staging
npm timing audit compress Completed in 142ms
npm info audit Submitting payload of 120343bytes
npm timing audit submit Completed in 909ms
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 909ms
npm timing audit body Completed in 0ms
[            ......] | extract:rxjs: sill extract rxjs@6.3.3 extracted to /data/larry/code/mattermost/mattermost-webapp/node_modules/.staging/rxjs-f0d3d488 (5136ms)

```

**Expected behavior**
Successful installation of rxjs in `node_modules/`

**Environment**
- Runtime: node v11.6.0  npm 6.5.0-next.0
- RxJS version: 6.3.3

**Possible Solution**
If a file is being created on extraction that has incorrect permissions and cannot be created unless npm is running as root that should be found and fixed.

**Additional context/Screenshots**
Posting with just the latest version of node and npm, found it several versions back.

It would appear that I am not the only person who has run into this.

- [while installing angular-cli](https://github.com/angular/angular-cli/issues/9942) 
- and [with Dreamweaver](https://forums.adobe.com/thread/2483942)

**Comment by cartant** [comment]
What is the behaviour if you use the current, stable release of npm?

```
npm dist-tag ls npm
...
latest: 6.5.0
```

**Comment by kwonoj** [comment]
I don't think this is package's problem. Shouldn't this be reported to npm upstream?

**Comment by kwonoj** [comment]
> If a file is being created on extraction that has incorrect permissions and cannot be created unless npm is running as root

especially this sounds like exactly npm's behavior issue. RxJS package itself doesn't contain specific permissions to each file afaik.

**Comment by laprice** [comment]
It does seem to be behavior that is caused by the artifact rxjs delivers to npm. 

It is consistent even if I clear the cache and blow away the node_modules/ directory.

I've tried to systematically eliminate anything specific to this machine.

**Comment by kwonoj** [comment]
If you think this is rxjs behavior,

1. manually extracting tar of rxjs lists out any specific permissions?
2. are all of machines having this issue or only occurs on specific machines?
3. is it happening on all npm / node versions or on specific npms?

afaik 1 is not the case and would like to verify it first before pin to our package.

**Comment by laprice** [comment]
So. I have definitely eliminated rxjs as the cause of this issue ( or at least the direct cause; it seems to be more prone to this than others ). 

My issue appears to be dependent on the contents of the `package-lock.json` / `package.json` and thus not your concern.

Closing. But you may want to see why so many have this issue with this library. I think it may be a cross-dependency of some sort.
