### ISSUE TITLE
onErrorResumeNext allows function to be passed, but doesn't use it

### ISSUE THREAD

**Issue by benlesh** [ReactiveX/rxjs#4477]
The type signature is incorrect here, it allows a function to be passed, but doesn't actually accept or use a mapping function of any sort.

[Here is the line in question](https://github.com/ReactiveX/rxjs/blob/b7b4a91834d4cf5a601485fa7dea78362057589d/src/internal/observable/onErrorResumeNext.ts#L79)

**Comment by Spetastian** [comment]
Is this what you meant: https://github.com/ReactiveX/rxjs/pull/4603 ?

**Comment by BioPhoton** [comment]
@benlesh as this issue is solved by PR https://github.com/ReactiveX/rxjs/pull/4603 we can close it.
