### ISSUE TITLE
`merge` operator does not need that many signature overloads

### ISSUE THREAD

**Issue by dkosasih** [ReactiveX/rxjs#4480]
## Bug Report
This is not a bug - I guess this is just a refactor for remove unnecessary signature overloads

**Current Behavior**
It has six overloads to support `ObservableInput`, the inference still behave the same without those overloads.  

These signatures seems to be enough to cover 
```js
export function merge<T>(...observables: (ObservableInput<T> | SchedulerLike | number)[]): Observable<T>;
export function merge<T, R>(...observables: (ObservableInput<any> | SchedulerLike | number)[]): Observable<R>;
```

**Expected behavior**
Code should behave exactly the same after this change.

**Environment**
- RxJS version: 6.3.3

**Possible Solution**
We could potentially remove the first six overloads with its `concurrent` and `scheduler` support signatures.

**Comment by cartant** [comment]
This seems pretty closely related to https://github.com/ReactiveX/rxjs/pull/4474

I suspect whether or not those signatures are required also depends upon the TypeScript version. ATM, v6 needs to support TypeScript 2.8. The some of the changes in the linked PR require a minimum of TypeScript 3.0.

**Comment by dkosasih** [comment]
So I guess we can leave it as is and still do the dtslint test as per current implementation until it's changed in the future?

**Comment by benlesh** [comment]
We can close this one. We've improved the types, but until the deprecated signatures are removed, I don't think we can reduce the number. After they're removed, I think there will just be one or two type signatures.
