### ISSUE TITLE
Allow multiple keys on distinctUntilKeyChanged 

### ISSUE THREAD

**Issue by EloB** [ReactiveX/rxjs#4486]
## Feature Request

Extend the current implementation of `distinctUntilKeyChanged` to be able to listen multiple key changes.

**Is your feature request related to a problem? Please describe.**
I really like the `distinctUntilKeyChanged` operator but I would say that it's more often that I need to listen to multiple keys than listen to one key.

**Describe the solution you'd like**
Allow the first argument to be either a string (to not break backward compatibility) or array of `key(s)`.

**Describe alternatives you've considered**
`distinctUntilKeyChanged` is just `distinctUntilChanged` with predefined arguments. I could of course use  `distinctUntilChanged` and do this myself but it's really annoying that we already have `distinctUntilKeyChanged` and it could be a lot better if it supported both one or multiple keys.

**(If this is new operator request) describe reason it should be core operator**
It's already part of the core but adding this feature would only be a minor change to current codebase.

**Additional context**
I have zero knowledge about typescript but adding this code in pure javascript would be super simple and would not be more than 1-2 lines of code.

```js
const arg1String = 'hello'
const arg1Array = ['hello', 'world']

[].concat(arg1String) // ['hello']
[].concat(arg1Array) // ['hello', 'world']
```

Then just run `.every()` for the comparison.

Related but as another operator: https://github.com/ReactiveX/rxjs/issues/2773

**Comment by cartant** [comment]
IMO, this should be closed for the same reasons the linked issue was closed. `distinctUntilChanged` exposes enough functionality for this to be easily implemented as a user-land operator.

**Comment by EloB** [comment]
@cartant but why not remove `distinctUntilKeyChanged` from core than? It's just a sugared function of `distinctUntilChanged`.

**Comment by cartant** [comment]
Because that would be a breaking change. And the fact that it is now difficult to remove said operator is a demonstration of why there is a reluctance to add operators - or to add functionality and overload signatures to existing operators.

**Comment by EloB** [comment]
@cartant How is this a breaking change? It still takes the first argument as `string` and nothing changes.

`distinctUntilKeyChanged('someKey')`
`distinctUntilKeyChanged(['someKey', 'someOtherKey'])`

This isn't a breaking change.

**Comment by EloB** [comment]
I've added a PR to prove it's one liner change.

**Comment by EloB** [comment]
@kwonoj If it's getting deprecated I'm fine without any changes else I believe it's pretty stupid.

**Comment by kwonoj** [comment]
Some of implementation we have had constraint with legacy and existing userbases, which we don't easily bring breaking changes. You may feel it's somewhat stupid but we are trying to make it better eventually.

**Comment by EloB** [comment]
One of the big reason why I don't want this in user land is because it's so close to core and the direction now when you have to manually import every single operator for pipe. Makes your import section really big (that makes your file less readable) and having to import another function or operator from another lib feels really annoying. Since tree shaking I don't mind bigger libraries. It helps the madness of 1000 of dependencies.
