### ISSUE TITLE
Composite subsciptions

### ISSUE THREAD

**Issue by toughpheeckouse** [ReactiveX/rxjs#4490]
## Bug Report

**Current Behavior**
Different behavior is observed when you use a subscription as a composite subscription in cases when you create a separate subscription object and use an object that returns a function subscribe of observable.
Please see spec code.

Is similar behavior possible? I could not find explanation in documentation.

**Reproduction**
```js
import { fakeAsync, tick } from '@angular/core/testing';
import { of, Subscription } from 'rxjs';
import { delay } from 'rxjs/operators';
import 'zone.js/dist/zone-patch-rxjs-fake-async';


describe('', () => {
    it('Subscriprion from observable as composite subscription', fakeAsync( () => {
        const first$ = of('first').pipe( delay(500) );
        const second$ = of('second').pipe( delay(1000) );

        let first: string;

        // Use subscription of first observable as composite subscription
        const compositeSubscription = first$.subscribe( v => first = v );

        let second: string;

        compositeSubscription.add(second$.subscribe( v => second = v ));

        tick(500); // fire first observable

        // works good
        expect(first).toEqual('first');

        tick(500); // fire second observable

        // 'Error: Expected undefined to equal 'second'' because compositeSubscription was
        // unsubscribed after first observable has been completed
        expect(second).toEqual('second');
    } ));

    it('Standalone subscriprion as composite subscription', fakeAsync( () => {
        const first$ = of('first').pipe( delay(500) );
        const second$ = of('second').pipe( delay(1000) );

        // Use standalone subscription
        const compositeSubscription = new Subscription();

        let first: string;

        compositeSubscription.add(first$.subscribe( v => first = v ));

        let second: string;

        compositeSubscription.add(second$.subscribe( v => second = v ));

        tick(500); // fire first observable

        // works good
        expect(first).toEqual('first');

        tick(500); // fire second observable

        // works good
        expect(second).toEqual('second');
    } ));
});

```

**Expected behavior**
I think that when you use a subscription obtained from a function to subscribe, the behavior should be the same as if you create a subscription object separately.

Correct me if I wrong

**Environment**
- Runtime: [e.g. Node v${x}, Chrome v${x}]
- RxJS version: 6.3.3
- (If bug is related) Loader, build configuration: [e.g webpack, angular-cli version, config]

**Comment by cartant** [comment]
Nope. This behaviour is by design. In the first test, the subscription to the second observable is unsubscibed when the first observable completes - as all subscriptions within the subscription to the first observable will be unsubscribed.

This doesn't happen in the second test because the stand-alone subscription is not unsubscribed upon completion of the first observable.

**Comment by benlesh** [comment]
Yes, this is expected behavior. In a lot of async cases, the first test you posted would work fine, but it's still not the recommended approach.

**Comment by toughpheeckouse** [comment]
Ok. Thank you guys. I've got it.
