### ISSUE TITLE
iif Observable static function does not infer EMPTY Observable when no parameters is passed

### ISSUE THREAD

**Issue by dkosasih** [ReactiveX/rxjs#4494]
## Bug Report

**Current Behavior**
`const a = iif(()=> true) `
The above code infer `Observable<{}>`

**Expected behavior**
The sample code in Current Behaviour section should infer `Observable<never>`

**Environment**
- RxJS version: 6.3.3

**Comment by OliverJAsh** [comment]
Just ran into this! The PRs for it seem to have stalled. What's currently blocking the fix? Anything I can help with?

**Comment by cartant** [comment]
@OliverJAsh I would imagine they were stalled because the changes and the tests were in separate PRs. I've combined them: #5176
