### ISSUE TITLE
decision-tree-generator/package-lock.json contans vulnerable flatmap-stream-0.1.1.tgx package

### ISSUE THREAD

**Issue by sbehrens** [ReactiveX/rxjs#4500]
## Bug Report

**Current Behavior**
The decision-tree-generator is locked to a vulnerable version of the flatmap-stream project.  you can read about this here: https://medium.com/intrinsic/compromised-npm-package-event-stream-d47d08605502

**Reproduction**
Click the following link:
https://github.com/ReactiveX/rxjs/blob/master/docs_app/tools/decision-tree-generator/package-lock.json  - L1589

**Possible Solution**
Update to the non-vulnerable version.

**Comment by jsonberry** [comment]
@sbehrens cool thanks for the heads up, will get this in later tonight 🙏

**Comment by sbehrens** [comment]
Thank you!
