### ISSUE TITLE
of Observable cannot accept more than 9 parameters

### ISSUE THREAD

**Issue by dkosasih** [ReactiveX/rxjs#4502]
## Bug Report

**Current Behavior**
Currently, `of` observable more than 9 parameters would throw error.

```js
const a = of(1, 2, 3, 4, 5, 6, 7, 8, 9, 0); // $ExpectType Observable<{}>
```

**Expected behavior**
The above code should infer `Observable<{}>`, instead, it throws error.

**Environment**
- RxJS version: 6.3.3
- (If bug is related) Loader, build configuration: [e.g webpack, angular-cli version, config]

**Comment by benlesh** [comment]
This has been resolved for a bit.
