### ISSUE TITLE
`npm run info` does not work.

### ISSUE THREAD

**Issue by zwcloud** [ReactiveX/rxjs#4503]
## Bug Report

**Current Behavior**
`npm run info` invokes error:
> npm ERR! missing script: info
>
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\xxxx\AppData\Roaming\npm-cache\_logs\2019-01-29T02_48_18_069Z-debug.log

**Reproduction**
1. download rxjs from github as a zip file
2. extract it
3. run `npm run info` in the uncompressed folder

**Expected behavior**
No error happens and *npm run info will list available scripts (there are a lot LOL)* as described in [ReadMe](https://github.com/ReactiveX/rxjs#buildingtesting).

**Environment**
- Runtime: Win10, npm 5.6.0, node v8.11.3
- RxJS version: commit: https://github.com/ReactiveX/rxjs/commit/8253ccd6757bd0a8f7902ae1be8bb6ba343ca838

**Additional context/Screenshots**
![image](https://user-images.githubusercontent.com/6965758/51880920-1c749a80-23b4-11e9-8553-8c96261a2b12.png)

**Comment by zwcloud** [comment]
I just want to know the meaning of every build script, such as `build_esm5`, `build_esm5_for_rollup`, `build_legacy_reexport`, etc. What's them?

**Comment by cartant** [comment]
The `info` script was removed in https://github.com/ReactiveX/rxjs/pull/3587

If you look at what was displayed, you'll see that the information was little different to the names of the scripts.

The mention of `npm run info` should be removed from the `README.md`. If you want to find out what each script does, use the name of the script as a guide and then have a look at the underlying command.
