### ISSUE TITLE
merge function names collides

### ISSUE THREAD

**Issue by yurireeis** [ReactiveX/rxjs#4509]
## Bug Report

Hello everyone!

I'm a newcomer to RXJS world and I want to register: I'm very happy with the lib results. The issue that I'm reporting right now have some workarounds, but I'm think that could be a little bit messy for the future (in other words, it's not a critical problem)

**Current Behavior**

1) The developers wants to merge two Observables in two distincts situation:
1.1) Directly, calling merge from 'rxjs';
1.2) As operator, inside pipe function
1.3) The merge function name collides

**Expected behavior**

1) The developers wants to merge two Observables in two distincts situations:
1.1) Directly, calling merge (from 'rxjs');
1.2) As operator, inside pipe function (from 'rxjs/observables)
1.3) The function name won't collides

**Reproduction**
- REPL or Repo link: https://stackblitz.com/edit/typescript-aeoiyf

**Environment**
- Runtime: all browsers
- RxJS version: 6.3.3

**Possible Solution**
We have two workarounds to this problem:

1) import rxjs as wildcard:
`import * as rxjs from 'rxjs';`

2) import one of them with alias:
`import { merge as mergeOperator } from 'rxjs/operators';`

**Comment by cartant** [comment]
Related: https://github.com/ReactiveX/rxjs/issues/3927.

**Comment by BioPhoton** [comment]
@yurireeis 
As this issue is already in progress and the related issue is already mentioned here I would suggest closing this issue.

You can also reopen it (if necessary) at any tie

**Comment by yurireeis** [comment]
@BioPhoton ok, I'll Do it. Thanks.
