### ISSUE TITLE
ERROR in node_modules/rxjs/internal/types.d.ts

### ISSUE THREAD

**Issue by monukanyal2017** [ReactiveX/rxjs#4511]
## Bug Report

**Current Behavior**
I am getting following errror after using npm start or ng build --prod

ERROR in node_modules/rxjs/internal/types.d.ts(81,44): error TS1005: ';' expected.
node_modules/rxjs/internal/types.d.ts(81,74): error TS1005: ';' expected.
node_modules/rxjs/internal/types.d.ts(81,77): error TS1109: Expression expected. 

**Expected behavior**
npm start or ng build command should run without any error.

**Environment**
- Runtime: Node {8.9.0} NPM{6.4.0}
- RxJS version:6.4.0

**Comment by kwonoj** [comment]
What's typescript version / and is there reproducible repo?

**Comment by monukanyal2017** [comment]
"typescript": "~2.7.0"

**Comment by kwonoj** [comment]
Per this (https://github.com/ReactiveX/rxjs/pull/4405#pullrequestreview-196802187) change, it requires 2.8 version of typescript compiler.

**Comment by monukanyal2017** [comment]
@kwonoj  should i change it 2.7.0 to 2.8.0? angular version is 6.0.0

**Comment by kwonoj** [comment]
@monukanyal2017 we are trying to figure out which part is actually affects this, I or @cartant will fill bit more detail here.

**Comment by cartant** [comment]
We've investigated the issue and the problem is that some versions of projects generated using Angular CLI have an RxJS dependency of `^6.0.0` and a TypeScript dependency of `~2.7.2`.

RxJS version 6.4 uses a conditional type to facilitate some improvements to its types and conditional types were introduced in TypeScript 2.8. We are currently looking into the best way of addressing the problem.

**Comment by ErxrilOwl** [comment]
Same issue

**Comment by sachin-dbox** [comment]
I am also facing the same issue . updated rxjs to 6.3.3, still getting the same issue.

**Comment by benlesh** [comment]
I've created a new issue to track this problem here https://github.com/ReactiveX/rxjs/issues/4512.

**Comment by benlesh** [comment]
@sachin-dbox, if you can create a minimum reproduction of that, please file a new issue and link in there. Happy to help if we can.

**Comment by NdumisoMthembu** [comment]
Updating type script worked for me npm install -g typescript@latest

**Comment by cartant** [comment]
Locking this. Refer to #4512
