### ISSUE TITLE
Link to documentation

### ISSUE THREAD

**Issue by dzhavat** [ReactiveX/rxjs#4517]
### Documentation Related To Component:

Link to documentation

### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue

Now that there's [rxjs.dev](https://rxjs.dev/), will the [rxjs-dev.firebaseapp.com](https://rxjs-dev.firebaseapp.com/) redirect to it at some point? And is it a good idea to update those links where `rxjs-dev.firebaseapp` is used to `rxjs.dev` (there are a couple of them in the repo)? If that's fine, I can quickly change them.

**Comment by cartant** [comment]
Sounds like a good idea, to me.
