### ISSUE TITLE
expectObservable runs asynchronously

### ISSUE THREAD

**Issue by whiteinge** [ReactiveX/rxjs#4521]
## Bug Report

**Current Behavior**

`expectObservable` runs asynchronously.

**Reproduction**

```js
const scheduler = new TestScheduler((actual, expected) => {
    console.log('TestScheduler', {actual, expected});
})

scheduler.run(({hot, expectObservable}) => {
    expectObservable(hot('a')).toBe('a');
    console.log('This is run before expectObservable.');

    setTimeout(() => console.log('This is run after expectObservable.'), 0);
});
```

**Expected behavior**

That the whole test suite will run synchronously.

**Environment**

- RxJS 6.4.0

**Additional context/Screenshots**

This caused a confusing problem with a mocked function in Jest that boiled down to the following:

```js
expectObservable(aStreamThatFlatMapsMyMockedFunction$).toBe(result);
expect(myMockedFunction).toHaveBeenCalled();
```

The second assertion runs first and since Jest short-circuits on failures the stream is never subscribed, which leads to very confusing error messages.

Workarounds:

- Call `flush()` after `expectObservable()`.
- Wrap subsequent assertions in a `setTimeout(() => {...assertions...}, 0)` to cause the event loop to turn once first.

**Comment by whiteinge** [comment]
I'm (re-)rereading the docs on `expectObservable` and `flush` now and perhaps this is expected behavior. If so, I think they could benefit from more detail. I'd be happy to make those additions since I currently have a newcomer perspective on `TestScheduler`. I'd appreciate it if someone could clarify the following questions:

- There's a [suggestion that flush need not be explicitly called](https://github.com/ReactiveX/rxjs/blob/master/doc/marble-testing.md#behavior-is-different-outside-of-testschedulerruncallback) if using `run()`.
  - Does that mean that non-Rx assertions are better called outside of `run()`?
  - If so, is it safe to assume that `run()` will always be synchronous?
  - If not, are non-Rx assertions inside of run expected that language should be relaxed a bit?
- Is the use-case for calling `flush()` multiple times inside a single `run()` to avoid the ceremony of multiple tests, each with their own `run()`?

**Comment by cartant** [comment]
Testing with the `TestScheduler` is entirely synchronous. IIRC, there is an implicit call to `flush` after the callback passed to `run` returns. If you think the docs can be improved, a PR with your suggested improvements will always be appreciated.

**Comment by whiteinge** [comment]
Thanks for the clarification.

**Comment by benlesh** [comment]
:) You're BOTH RIGHT!!!

What's "asynchronous" or "synchronous" is relative to any given execution context.
