### ISSUE TITLE
shareReplay({refCount: true}) doesn't behave same way as publishReplay() + refCount()

### ISSUE THREAD

**Issue by jacksnipe24** [ReactiveX/rxjs#4530]
## Bug Report

**Current Behavior**
Currently `shareReplay({refCount: true})` and `publishReplay(), refCount()` behave differently in some situations.  

**Reproduction**
- https://stackblitz.com/edit/angular-qjwdez

How ` shareReplay({refCount: true})` works
```js
this.source = interval(1000).pipe(
     shareReplay({refCount: true, bufferSize: 1}), 
);

const sub1 = this.source.subscribe(x => console.log('sub 1', x));

 setTimeout(() => {
     sub1.unsubscribe();
   }, 3000);

setTimeout(() => {
     const sub2 = this.source.subscribe(x => console.log('sub 2', x));
   }, 6000);
```
"sub 1" will get three values and unsubscribe. After  another 3 seconds "sub 2" will subscribe  again, the result will be 
sub 1 - 0
sub 1 - 1
sub 1 - 2
_--after 3 seconds--_
sub 2 - 0
sub 2 - 1
sub 2 -2
.....

same code with `publishReplay(), refCount()`
```js
this.source = interval(1000).pipe(
    publishReplay(1),
    refCount()
);
```
"sub 1" will get three values and unsubscribe. After another 3 seconds "sub 2" will get the last N values specified in publishReplay()  and subscribe to interval again, the result will be
sub 1 - 0
sub 1 - 1
sub 1 - 2
_--after 3 seconds--_
**sub 2 - 2**
sub 2 - 0
sub 2 - 1
sub 2 -2
.....

**Expected behavior**
They either should behave same way always or if they are designed to behave differently it needs to be clarified more

**Environment**
- RxJS version: 6.4.0

**Comment by thekiba** [comment]
Has the same behavior
https://stackblitz.com/edit/rxjs-share-replay-ref-count-bug

![ezgif-2-8eebeb23c0e5](https://user-images.githubusercontent.com/1910515/52180436-f78a8800-27f6-11e9-9cea-d18245ccf547.gif)

**Comment by cartant** [comment]
The differences in behaviour - which do not appear to have been described in this issue - are by design.

The two are not the same, as `shareReplay` (and `share`) can be retried.

With `shareReplay`, when an error is emitted, a new subject is created and subsequent subscriptions to the shared observable will effect a resubscription to the source.

With `publishReplay(), refCount()`, when an error is emitted, no new subject is created and subsequent subscriptions to the shared observable will replay the error - they will not effect a resubscription to the source

**Comment by jacksnipe24** [comment]
@cartant Can you confirm, that 

In the spec [file](https://github.com/ReactiveX/rxjs/blob/master/spec/operators/publishReplay-spec.ts#L306) of ` publishReplay() + refCount()`  it says 

> should emit replayed values and resubscribe to the source when reconnected without source completion

so when refCount drops to 0 any new subscriber will get replayed values and if source has not completed yet, it will also re-subscribe to the source again

when as for `shareReplay({refCount: true})` [specs](https://github.com/ReactiveX/rxjs/blob/master/spec/operators/shareReplay-spec.ts#L189) says

> should restart due to unsubscriptions if refCount is true

in fact it will indeed restart the subscription, but only if source has not completed. If source has completed it will just emit replayed values and do not restart the subscription.

can you explain why they behave differently. i completely understand why `publish() + refCount()` and `share()` are not the same because first one uses Subject instance in `multicast()`, and the other one uses factory function which gives Subject instance. 

Do shareReplay and publishReplay behave differently because of publishReplay using same ReplaySubject() instance as it is shown in [source code](https://github.com/ReactiveX/rxjs/blob/master/src/internal/operators/publishReplay.ts#L22) ?  and shareReplay({refCount: true})  [re-creating](https://github.com/ReactiveX/rxjs/blob/master/src/internal/operators/shareReplay.ts#L117) new ReplaySubject instance every time

**Comment by cartant** [comment]
The `shareReplay` spec saying

> should restart due to unsubscriptions if refCount is true

is not wrong; it's just not complete - if you pardon the pun - description.

> Do shareReplay and publishReplay behave differently because of publishReplay using same ReplaySubject() instance as it is shown in source code ? and shareReplay({refCount: true}) re-creating new ReplaySubject instance every time

Yes. The difference between `publish` - and its variants - and `share` is that `publish` passes a subject instance to `multicast` and `share` passes a factory.

`shareReplay` is not implemented using `multicast`, but it uses a factory internally and if ref counted and the ref count drops to zero (without source completion) or if an error occurs, a new subject is created. The primary motivator the difference in behaviour is so a source observable can be made hot and retriable. `publish` - and its variants - are not retriable, as they just replay the error.
