### ISSUE TITLE
Rxjs Ajax not working in Android 4.2.1

### ISSUE THREAD

**Issue by omidnikrah** [ReactiveX/rxjs#4533]
## Bug Report

**Current Behavior**
I'm using Rxjs Ajax but it not working in android 4.2.1. Is it supported by Rxjs?

**Environment**
- Runtime: Android 4.2.1
- RxJS version: 6.2.2

**Comment by kwonoj** [comment]
I'm closing this issue for now due to lacks of detail to determine furtuer.
