### ISSUE TITLE
Ambient const enums are not allowed when the '--isolatedModules' flag is provided (with typescript)

### ISSUE THREAD

**Issue by steabert** [ReactiveX/rxjs#4538]
## Bug Report

**Current Behavior**
When compiling a typescript file that imports something from `rxjs` with the `isolatedModules` option for typescript set to true, the following error occurs:

```
node_modules/rxjs/internal/Notification.d.ts:3:27 - error TS1209: Ambient const enums are not allowed when the '--isolatedModules' flag is provided.

3 export declare const enum NotificationKind {
```

**Reproduction**

Create minimal project
```shell
yarn add --dev typescript rxjs
ts 
```
Create `test.ts`:
```ts
import {Observable} from 'rxjs'
```

Run Typescript compiler
```shell
yarn tsc --lib esnext --isolatedModules test.ts
```

**Expected behavior**
No error.

**Environment**
- Runtime: Node v10.15.0
- RxJS version: 6.4.0
- (If bug is related) Loader, build configuration: typescript 3.3.1

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by cartant** [comment]
I'm not familiar with the error, but I have a hunch that it might be addressed by the enum being exported in this PR: https://github.com/ReactiveX/rxjs/pull/4514

**Comment by BrianMitchL** [comment]
This also causes compilation errors with @babel/plugin-transform-typescript (the TypeScript compiler used in create-react-app), which [does not support const enums](https://babeljs.io/docs/en/babel-plugin-transform-typescript#caveats).

**Comment by cartant** [comment]
@BrianMitchL Although it also pertains to const enums, your issue is unrelated to this one. Please open an issue and fill out the template - including all relevant version information.

IIRC, TypeScript 2.4 is the version in which const enums were introduced, so I'd be more than a little surprised if the current version of the transform does not support them.

Anyway, please move all discussion to a new issue.

**Comment by am17torres** [comment]
@steabert I just ran into this issue after running a `yarn upgrade`

```
./node_modules/rxjs/internal/Notification.d.ts
Type error: Ambient const enums are not allowed when the '--isolatedModules' flag is provided.  TS1209

    1 | import { PartialObserver } from './types';
    2 | import { Observable } from './Observable';
  > 3 | export declare const enum NotificationKind {
      |                           ^
    4 |     NEXT = "N",
    5 |     ERROR = "E",
    6 |     COMPLETE = "C"
```
Downgrading rxjs from 6.4.0 to 6.3.3 removed that error.
This looks like the problem line https://github.com/ReactiveX/rxjs/compare/6.4.0...master#diff-f41e9d04a45c83f3b6f6e630f10117feR27

**Comment by cartant** [comment]
@am17torres Yeah, exporting won't solve this. See [this comment](https://github.com/ReactiveX/rxjs/issues/4555#issuecomment-462179882).

**Comment by mrmckeb** [comment]
We're facing this issue too, and I think it's going to affect a lot of people sadly.

Any ideas for workarounds? For now we're forcing the last release (using Yarn's `resolutions`). 

Would the quick fix be to remove `const`?

**Comment by cartant** [comment]
@mrmckeb I think pinning your resolution to 6.3.3 would be the quickest, simplest solution, for now.
