### ISSUE TITLE
TimeoutError and other *Error util classes should use the return of Error.call()

### ISSUE THREAD

**Issue by lemoinem** [ReactiveX/rxjs#4539]
## Bug Report

**Current Behavior**
Currently `TimeoutError` and other Error "classes" do not use the value returned by `Error.call(this)`.
This means, among other things, that some properties (such as `.stack`) do not get initialized on some browsers.

**Reproduction**
- REPL or Repo link:
https://stackblitz.com/edit/rxjs-xp2tfx

**Expected behavior**
Both tests (with `Error` and with `TimeoutError`) should display a stacktrace.

**Environment**
- Runtime: Chrome v72.0.3626.81, Firefox 65.0, Opera 58.0.3135.53
- RxJS version: 6.4.0

IE 11 is not impacted as the stackTrace isn't populated until the error is thrown.
Edge 42.17134.1.0 (EdgeHTML 17.17134) is not impacted as the stackTrace is re-populated when the error is thrown.

**Possible Solution**
The `*Error` "classes" should use the return value of `Error.call(this)` as the new value for `this`.
Fixing the prototype chain might be required (https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#extending-built-ins-like-error-array-and-map-may-no-longer-work)

**Additional context/Screenshots**
N/A

**Comment by benlesh** [comment]
This has been resolved in version 7.
