### ISSUE TITLE
`from` behaviour seems incorrect.  Emits no values.

### ISSUE THREAD

**Issue by bjohnson-va** [ReactiveX/rxjs#4541]
## Bug Report

**Current Behavior**
Using the `from` function to generate an observable from a promise seems to, instead, generate an empty observable.

**Reproduction**
https://github.com/bjohnson-va/rxjs-bug/blob/master/src/test.ts

```
git clone https://github.com/bjohnson-va/rxjs-bug
cd rxjs-bug
npm install
jest
```

**Expected behavior**
Calling `from`, with a Promise that immediately resolves, should generate an observable that emit's the Promise's value.

**Environment**
- Runtime: Node v8.11.3
- RxJS version: 6.4.0

**Additional context/Screenshots**
![image](https://user-images.githubusercontent.com/8963131/52450415-80a80480-2b00-11e9-9815-5230fdef8306.png)

**Comment by kwonoj** [comment]
Testscheduler cannot support promise based observables as we can't schedule them synchronously. Please update repro snippet without testscheduler for triaging.

**Comment by bjohnson-va** [comment]
Ah, if it's just an incompatibility with TestScheduler I suppose there's no bug here.
I'll try to find an alternative utility for testing my async code. 👍

**Comment by bjohnson-va** [comment]
Ah, if it's just an incompatibility with TestScheduler I suppose there's no bug here.
I'll try to find an alternative utility for testing my async code. :
