### ISSUE TITLE
`from` examples

### ISSUE THREAD

**Issue by dzhavat** [ReactiveX/rxjs#4542]
### Documentation Related To Component:

[from](https://rxjs.dev/api/index/function/from)

### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [ ] documentation needs clarification
- [x] error(s) in example
- [ ] needs example

### Description Of The Issue

I was looking at the docs about `from` and noticed that the examples can be improved a bit. 

E.g. `from` is imported from `rxjs/observable/from`.

I thought of making a PR but then noticed that in the third example, `async` is imported from a weird place. Is this still correct?

```js
import { async } from 'rxjs/scheduler/async';
```

Shouldn't it be just `import { async } from 'rxjs';`? 

But then looking at the docs about `async`, I noticed that the examples there import `asyncScheduler` and use it in a different way? This confused me a bit.

So I'm up for making a PR but can you please clarify the third example for me.

**Comment by cartant** [comment]
> Shouldn't it be just `import { async } from 'rxjs';`?

Not quite, it should be:

```ts
import { asyncScheduler } from 'rxjs';
```

See [this export](https://github.com/ReactiveX/rxjs/blob/6.4.0/src/index.ts#L16).

**Comment by dzhavat** [comment]
Got it. Thanks :)
