### ISSUE TITLE
ShareReplay doesn't send immediate sync events to the subscriber

### ISSUE THREAD

**Issue by KwintenP** [ReactiveX/rxjs#4558]
## Bug Report

**Current Behavior**
When applying the `shareReplay` operator to an `Observable` that (immediately) synchronously sends multiple values, the resulting `Observable` only gets the last value that was sent. 

**Reproduction**
- REPL or Repo link:
https://stackblitz.com/edit/rxjs-3oq6pe

```js
const source$ = of(1, 2, 3, 4, 5).pipe(
  shareReplay(1)
);

source$.subscribe(val => console.log('value received is ', val));

Result: 
// value received is 5
```

**Expected behavior**
The `shareReplay` operator should send all values to the subscriber that it received (even if immediately sent synchronously).
The resulting log should be:
```js
// value received is 1
// value received is 2
// value received is 3
// value received is 4
// value received is 5
```

**Environment**
- Runtime: Node 10.13.0
- RxJS version: 6.3.3

**Possible Solution**
https://github.com/ReactiveX/rxjs/blob/master/src/internal/operators/shareReplay.ts#L96-L110

The subscription to the source in the `shareReplay` operator is happening before the subscriber to the shared `Observable` is subscribing to the `ReplaySubject`. This causes the bug.
Moving:
`const innerSub = subject.subscribe(this);`
directly after:
`subject = new ReplaySubject<T>(bufferSize, windowTime, scheduler);`

should fix the bug. (happy to send a PR for this!).

**Comment by benlesh** [comment]
This has been resolved in rxjs 6 and 7
