### ISSUE TITLE
AnonymousSubject with different in and out types

### ISSUE THREAD

**Issue by armpogart** [ReactiveX/rxjs#4560]
First `AnonymousSubject` isn't documented anywhere. But there is a clear example of it's usage in library itself (`WebSocketSubject`). As I see from the code `AnonymousSubject` creates bidirectional flow.

Now the problem is I need similar subject, but which will have different in and out types so that subscribers and observers will get different type of data. You can see similar issue here #2602. And it's currently impossible in TypeScript to extend the `Subject` or `AnonymousSubject` classes to get that functionality because `next` method will be incompatible with it's parent class.

My use case is creating something similar to `WebSocketSubject` but for the WebSocket server, so that the subscribers to the subject will receive Object with socket and the message, but `next` method will broadcast just message to all sockets.

**Comment by cartant** [comment]
IMO, `AnonymousSubject` is an internal, implementation detail.

**Comment by PaulLeCam** [comment]
I have similar use cases in various libraries and projects, leveraging `AnonymousSubject` in a similar way as a Node.js duplex stream.
Is there a specific reason it shouldn't be exposed as public API with support for different input and output types please?

**Comment by kwonoj** [comment]
> First `AnonymousSubject` isn't documented anywhere

as @cartant said, it is internal impl and not to be exposed in public api. We only do use it for managing some internal state around operator, and it's likely changing very frequently internally including name (`AnonymousSubject` name itself already brings some confusion, which'll likely change) and potentially semantics as well. 

In short, we do not supports out-consumer usage than internal of rxjs itself. If similar behavior is required, it is recommended to create own subject impl.
