### ISSUE TITLE
`race` documentation incorrectly states it "mirrors the first source Observable to emit an item"

### ISSUE THREAD

**Issue by aquark** [ReactiveX/rxjs#4561]
## Bug Report

This is a duplicate of https://github.com/ReactiveX/rxjs/issues/2641 which was closed prematurely.

**Current Behavior**

`race` completes the first time any of its observables emits an item, completes, or errors. The documentation says "emits an item" which (based on previous issue) is widely misinterpreted to mean "publishes a value" not including completion. This bit my team because we were expecting the implementation to match the documentation.

The [ReactiveX Amb operator](http://reactivex.io/documentation/operators/amb.html) which is equivalent to `race` clearly documents the conditions that cause `race` to complete.

**Comment by cartant** [comment]
Yeah. Updating the documentation to replace "emits an item" with "emits a notification" would better describe the behaviour.

**Comment by cartant** [comment]
Closed by #4584.
