### ISSUE TITLE
throwIfEmpty doesn't throw on retry

### ISSUE THREAD

**Issue by bgotink** [ReactiveX/rxjs#4565]
## Bug Report

**Current Behavior**

`throwIfEmpty` doesn't throw when the source observable completes without any value after it's re-subscribed to.

**Reproduction**
- https://stackblitz.com/edit/rxjs-2nbh1q?file=index.ts

```ts
source$.pipe(
  throwIfEmpty(),
  someOperatorThatMightThrow(),
  retry(),
).subscribe(value => console.log('got value', value));
```

If `source$` emits a value, the `someOperatorThatMightThrow()` operator throws, and `source$` completes on the second subscription without emitting any value, the `throwIfEmpty()` doesn't throw.

**Expected behavior**

I'd expect the `throwIfEmpty` to result in a failure.

**Environment**
- Runtime: Chrome v71
- RxJS version: 6.4.x

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by benlesh** [comment]
This is resolve in the latest 6.x and 7.x releases.
