### ISSUE TITLE
skipUntil operator is missing description content

### ISSUE THREAD

**Issue by queeniema** [ReactiveX/rxjs#4567]
### Documentation Related To Component:

[`skipUntil`](https://rxjs-dev.firebaseapp.com/api/operators/skipUntil)

### Please check those that apply

- [ ] typo
- [X] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue

"Description" section is missing content.

<img width="1323" alt="screen shot 2019-02-14 at 4 38 59 pm" src="https://user-images.githubusercontent.com/2454818/52826784-25818f00-3077-11e9-9301-eb2a75e7cd28.png">

**Comment by cartant** [comment]
Closing this 'cause the v6 and v7 docs don't appear to have this problem.

https://rxjs.dev/api/operators/skipUntil

https://v6.rxjs.dev/api/operators/skipUntil
