### ISSUE TITLE
Flow example in RxJS documentation throws error 

### ISSUE THREAD

**Issue by arfordweb** [ReactiveX/rxjs#4570]
### Documentation Related To Component:
https://rxjs-dev.firebaseapp.com/guide/overview

### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [ ] documentation needs clarification
- [X] error(s) in example
- [ ] needs example

### Description Of The Issue

If you view the "Flow" section at https://rxjs-dev.firebaseapp.com/guide/overview , the RxJS version of click throttling doesn't work.  When I click the `open_in_new` icon for the example, I see:

![image](https://user-images.githubusercontent.com/1002408/52876148-579cfa80-3124-11e9-8bc5-910ecf1c0757.png)

**Comment by benlesh** [comment]
Seems to be working now. Thanks for reporting
