### ISSUE TITLE
GroupBy does not support key re-use

### ISSUE THREAD

**Issue by kingces95** [ReactiveX/rxjs#4571]
## Bug Report

**Current Behavior**
When groupBy encounters a new key it emits a group. If I unsubscribe from that group then any subsequent encounters with that key do not result in groupBy emitting a group.

**Expected behavior**
When groupBy encounters a new key it emits a group. If I unsubscribe from that group then resources associated with that group are freed. If groupBy encounters that key again then it emits a group as if it were seeing the key for the first time.

**Comment by cartant** [comment]
Please include an example of what it is that you are doing.

**Comment by kwonoj** [comment]
I'm closing this issue for now due to lacks of detail to determine furtuer.
