### ISSUE TITLE
Outdated operator-creation.md doc

### ISSUE THREAD

**Issue by martinsik** [ReactiveX/rxjs#4574]
### Documentation Related To Component:

`/doc/operator-creation.md`

### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [X] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue

There's one outdated document at [`/doc/operator-creation.md`](https://github.com/ReactiveX/rxjs/blob/master/doc/operator-creation.md). It was last updated on Dec 15th 2017 and still recommends patching `Observable.prototype`. Someone on StackOverflow mentioned that when you google for "rxjs custom operator" this is the first result.

It seems like most of its content is already covered in https://github.com/ReactiveX/rxjs/blob/master/doc/pipeable-operators.md#build-your-own-operators-easily.

**Comment by JWO719** [comment]
So in the new docs we have the guides about operators in general, see https://github.com/ReactiveX/rxjs/blob/master/docs_app/content/guide/operators.md#creating-custom-observables. I just took a quick look at the content of this chapter and it looks quite good for me. If you have any suggestions to improve this, just let me know

**Comment by martinsik** [comment]
I was mostly concerned about this part: https://github.com/ReactiveX/rxjs/blob/master/doc/operator-creation.md#adding-the-operator-to-observable

It mentions for example this which is obsolete now:

> Patch `Observable.prototype` directly:
> ```Observable.prototype.mySimpleOperator = mySimpleOperator;```

**Comment by benlesh** [comment]
#5592 deals with this.

**Comment by jakovljevic-mladen** [comment]
The entire `/doc` folder is removed with the PR #5338. The content of that folder was used for the old docs site. It is now replaced with the new app which is located under `/docs_app` folder. Much like @niklas-wortmann said [in this comment](https://github.com/ReactiveX/rxjs/issues/4574#issuecomment-470407175), the guide for creating custom operators is now moved to this file: [/docs_app/content/guide/operators.md](https://github.com/ReactiveX/rxjs/blob/master/docs_app/content/guide/operators.md).

That file does not mention anything related to the problem described in this issue, so I'm gonna close this as outdated. Thanks for reporting.
