### ISSUE TITLE
Update changelog to include deprecations

### ISSUE THREAD

**Issue by dzhavat** [ReactiveX/rxjs#4577]
### Documentation Related To Component:
CHANGELOG

### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [x] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue

v6.4.0 introduced some deprecations but only one of them is in the changelog. And even that one is kind of buried in the bug fixes.

It'd be helpful if all deprecations were in there preferably in a separate section so people are aware of them.

**Comment by BioPhoton** [comment]
@dzhavat i really like the idea. IMHO conventional changelog is used and thete is the oprion to create/extend the topics.

@cartant could you please give some feedback here. 🙏🙏🙏

**Comment by cartant** [comment]
Related (and on my TODO list) https://github.com/ReactiveX/rxjs/issues/4776

**Comment by cartant** [comment]
See also https://github.com/ReactiveX/rxjs/issues/4776#issuecomment-501496944

**Comment by benlesh** [comment]
I don't think we have the bandwidth to do this in an automated way. It's a good idea, but we're going to have to stick to what we have for now.
