### ISSUE TITLE
Chainable Subscriptions

### ISSUE THREAD

**Issue by marcelcremer** [ReactiveX/rxjs#4579]
## Feature Request
Hey guys,

**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I need to return Observables or Subscriptions.

For example let's say we have something like:

```typescript
refresh() {
  this.httpClient.get('...').subscribe(data => this.data = data);
}
```

This refresh-method is referenced about 50 times in the code and everything is fine. However, at the 51st time calling the method, I need to wait until it has completed its job. Since .subscribe returns a Subscription, I now have to change the call to subscribe() into .pipe() to get an Observable:

```typescript
refresh() {
  return this.httpClient.get('...').pipe(tap(data => this.data = data));
}
```

Since now all references to the refresh method don't actually subscribe to the Observable anymore, I have to change every

```typescript
foo.refresh();
```

into

```typescript
foo.refresh().subscribe();
```

So that's 50 times changing the code, just because a .subscribe() is not chainable. Even worse: If in the original subscribe had some kind of error handling, the error handling now needs to move into the reference calling locations. 

And from there, each of those 50 references is becoming a good candidate for a future "subscribe to change into pipe", because other logic could probably rely on it.

**Describe the solution you'd like**
I'd love if the Subscription Object would just contain an internal Observable, that emits every time the original Subscription emits a value.

Original Observable -> subscribe() -> Subscription(with new Observable) -> subscribe() on Subscription-Observable

So we could do something like:

```typescript
let subscription  = this.httpClient.get('...').subscribe();
// as we're subscribing on the Subscription-internal observable, we can use it in a chain:
subscription.pipe(tap(...)).subscribe(foo => console.log(foo));

```

The "internal" Observable will be created on the calling of Subscription.subscribe() and also subscribes on the parent Observable. It needs to make sure, that it does re-emit, re-fail, re-complete and auto-unsubscribe on the parent. Because it's created upon calling Subscription.subscribe(), the chain of Observables will somewhen end.

**Describe alternatives you've considered**
I haven't found something more "clever" to achieve what I need to. All questions on the net about chaining seem to be answered with "change subscribe with pipe" which (as I hopefully could transfer) can be a lot of pain and work.

Also, it looks like comparing to Promises (which could be chained infinitely and therefore just returned in my refresh example), Observables create much overhead because they can't be chained.

**Comment by jgbpercy** [comment]
I believe you can achieve what you want pretty easily right now:
- Just add a new method:
```
refreshCold(): Observable<any> {
  return this.httpClient.get('...').pipe(tap(data => this.data = data));
}
```
- And change refresh to be:
```
refresh(): void {
  this.refreshCold().subscribe();
}
```
Your existing code continues to call `refresh` with the same behavior, and your new call site calls `refreshCold` and gets what it wants?

It's not particularly "pretty", but then to be completely honest what you're trying to do overall seems a bit suspect. Without knowing what your whole app does I can't say for sure, but you probably either want to have the service _always_ return the cold observable and let the consumers _always_ manage the value (and whether they are waiting for the value), or you want to have the service manage the value properly inside something like a `BehaviorSubject`, and have the "loading state" (i.e. whether the call is currently in flight) managed within or alongside that in the service.

The way you're describing it now seems like the service owns the value, but you want (some) consumers to own/manage the "loading state", which is a problem imo.

Also, and people from the core team can agree or disagree if it matters, but I find the ungodly mix between a chainable `map`-like thing and a side-effect-having `subscribe`-like thing that is `.then` on Promises to be _really_ ugly, confusing and unhelpful. I think part of the strength of RxJS to be the separation of these things and the ability to have clearly hot and cold streams...

**Comment by marcelcremer** [comment]
Hey,

sorry I was on a business trip for a few days and could answer just now.

Your suggestion to change ".subscribe()" to ".pipe()" and change every caller to call ".subscribe()" afterwards is exactly what I wrote and in my opinion is frustrating and ugly about Observables. If you design an application that has a decent size, it's not possible to foresee all the uses of the Observable upfront. 

Over the time, different layers of abstraction grow about each other to encapsulate complexity. And if you have something that is managed at a "high" layer, but need to wait for this on a deeper layer (which usually pops up half a year + after you wrote the original code), you have to touch many places that aren't related with the current change you want to implement. 

If you have 50+ places calling this method, it's even possible that someone forgets to add a .subscribe() call at one reference, which could have huge impact if it goes into production.

> Also, and people from the core team can agree or disagree if it matters, but I find the ungodly mix between a chainable `map`-like thing and a side-effect-having `subscribe`-like thing that is `.then` on Promises to be _really_ ugly, confusing and unhelpful. I think part of the strength of RxJS to be the separation of these things and the ability to have clearly hot and cold streams...

What about it is particular ugly in your opinion? I tried to find something before answering you, but I could not find downsides of the thenable-chain (especially since async / await is available for Promises). The only thing that i see is, that it doesn't allow to get the actual "Subscription" to cancel / retry the operation in between.

That's why I suggested to make a Subscription subscribable too...

**Comment by martinsik** [comment]
@marcelcremer I think you can do what you need already:

> However, at the 51st time calling the method, I need to wait until it has completed its job.

Subscribe returns an instance of `Subscription` that has `add()` method that adds another dispose handler. This is like using the `finalize()` operator. So you can do:

```
refresh().add(() => console.log('done'))
```

Just be aware that this is called when the source both completes or errors. `add()` obviously doesn't receive any notifications.  

What you describe later seems like you want `refresh()` to return something that behaves like an observer and Observable at the same time and that's what Subjects do already. You could do for example:

```
refresh(): Observable<any> {
  const subject = new Subject();
  this.httpClient.get('...').pipe(tap(data => this.data = data)).subscribe(subject);
  return subject;
}

...

refresh().pipe(...).subscribe();
```

I've seen similar questions on StackOverflow and usually the confusing part is that people don't know they can use `.subscribe().add()` because it's not obvious what `add()` does. Maybe there could be an alias for `add()` called `finalize()` that would do the same thing just for better readability?

Similarly people in general don't expect `finalize()` to be used as an operator inside a chain which comes I guess from using `try - catch - finally` blocks.

**Comment by marcelcremer** [comment]
@martinsik That really sounds great. 

> I've seen similar questions on StackOverflow and usually the confusing part is that people don't know they can use `.subscribe().add()` because it's not obvious what `add()` does.

To be honest - I also saw .add() in the description, but thought it's only usefuly for some rxjs-internal mechanism, because as far as I understand

http://reactivex.io/rxjs/class/es6/MiscJSDoc.js~TeardownLogicDoc.html

the function does not get any parameters. 

Maybe it's possible to add the last emitted value and /  or the error message (if any) to the callback? That would make it useful and opens up several new Options (e.g. re-emitting on a new subject, creating a Promise out of it, doing some callback thing, ...)

In my case, it was all about https-requests that are handled by Observables, but I didn't want to make this request too special.

P.S.: .finalize() sounds like a pretty good name :)

**Comment by jgbpercy** [comment]
> Your suggestion to change ".subscribe()" to ".pipe()" and change every caller to call ".subscribe()" afterwards is exactly what I wrote
>
Sorry if I didn't explain it well enough, but that's exactly what I _didn't_ suggest... If you read my suggestion closely I'm saying you add a new method called `refreshCold`, change the internal implementation of `refresh`, **leave all existing call sites as they are**, and have your new call site call `refreshCold` (and subscribe). Your existing and new call sites shouldn't really be calling the same method anyway - they want different things.

@martinsik's Subject suggestion also seems fine.

Without wanting to side-track into a discussion about it (this is the last I'll say), my problems with Promise `then` are briefly:
- that it's for pure functions that just map values without side effects, _and_ it's for having side effects with values produced by the promise. Imo it's better if these are separate, and if APIs encourage that.
- because it's both these things, it would be more awkward to have the concept of a "cold" promise that wont begin processing until something asks for the value. The separation of subscribe from operators in RxJS allows this naturally, and it's a big strength for anything close to advanced use.

**Comment by marcelcremer** [comment]
Hey @jgbpercy ,

> Sorry if I didn't explain it well enough, but that's exactly what I _didn't_ suggest... If you read my suggestion closely I'm saying you add a new method called `refreshCold`, change the internal implementation of `refresh`, **leave all existing call sites as they are**, and have your new call site call `refreshCold` (and subscribe). Your existing and new call sites shouldn't really be calling the same method anyway - they want different things.

No I'm sorry - either I didn't read it close enough, or I just didn't get what you meant. Of course this is also a possibility.

Also thanks for your your insights about promises - I will think some more about it (even if it didn't bother me yet in practise).

I still think it would be a good idea to make .add() somewhat more usable - even if it might be somewhat opinionated. I think it was added with something in mind, which might be not too obvious (as @martinsik wrote, there are other questions on StackOverflow that point into the same direction).

**Comment by kwonoj** [comment]
Most crux has been explained above - `Subscription` itself is compositable, reason why it have `add` method: it should accept any subscription, one common pattern is having reference to parent subscription have all child subscription which'll unsubscribe at all, not only accepting just function to be called later.

There were some chat about subscription interfaces but none of them are concretely evolved, and I believe for now subscription composition itself is sufficient. While it's deprecated from v5 it'll be helpful to see v4's subscription as well (https://github.com/Reactive-Extensions/RxJS/tree/master/doc/api/disposables) all of them are fairly easy to implement if it's needed.
