### ISSUE TITLE
no such package available : @reactivex/rxjs

### ISSUE THREAD

**Issue by spboyer** [ReactiveX/RxJS#458]
Getting this when trying to install `npm install @reactivex/rxjs` directly or as a dependency of `npm install angular2`

**Comment by staltz** [comment]
This library is still a tagged version (i.e. `M.m.p-tag` and not `M.m.p`), so you need to explicitly mention the full version: `npm install @reactivex/rxjs@5.0.0-alpha.2` and not `npm install @reactivex/rxjs` because there still isn't any untagged version of this library published.

**Comment by spboyer** [comment]
@igorminar

**Comment by staltz** [comment]
I would close this issue and reopen if it persists.

**Comment by spboyer** [comment]
This is an issue with internal or some enterprise proxies. What happens is the `/` is url-encoded as `%2` in the http request and gets a 404. Straight request to npm is fine even without having to request specific version. Closing issue.

**Comment by eliashdezr** [comment]
I´m having this issue:
```
npm install @reactivex/rxjs@5.0.0-alpha.10

npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code E404

npm ERR! 404 no such package available : @reactivex/rxjs
npm ERR! 404
npm ERR! 404 '@reactivex/rxjs' is not in the npm registry.
```

**Comment by blesh** [comment]
@eliashdezr try updating your version of npm.

**Comment by staltz** [comment]
@eliashdezr I executed the same command using npm `v2.14.7` and it worked. Maybe there was some firewall or offline network connection?

**Comment by eliashdezr** [comment]
I updated to `npm v2.14.12` and it worked. Thanks!
