### ISSUE TITLE
[docs]: Rename/Aliasing the combineAll operator to combineLatestAll

### ISSUE THREAD

**Issue by BioPhoton** [ReactiveX/rxjs#4590]
**Current Behavior**
All good! Just the naming might be confusing.

**Possible Solution**
I would expect the name of combineAll to be combineLatestAll.

**Additional context/Screenshots**
If you take a look to the "naming convention" you will realize that all the other operators like switchAll, mergeAll, zipAll etc. process higher order observables and follow the patterns [operatorName]All.

Therefore I consider the naming as inconsistent. For me it implies a different behavior.

I would suggest to implement it as an alias.

**Comment by kwonoj** [comment]
`combineLatest` operator does different to `combine` does. How does `combinelatestAll` matches semantics to combine behavior?

**Comment by BioPhoton** [comment]
As far as I know, there is no `combine` operator. Please correct me if I'm wrong.

Let me reference the docs to give a more tangible input why I believe the renaming makes sense:
[combineAll](https://github.com/ReactiveX/rxjs/blob/6e5f77367c2ca33560ff0d2e586ef8ebd6b5d8ee/src/internal/operators/combineAll.ts#L10)

**Comment by kwonoj** [comment]
Yes, there isn't combine operator. My q is if combineAll goes combineLatestAll, it'll not be aligned with existing combineLatest operator.

I am not necessarily agreed your argument: internally it calls combineLatest yes, but it's special kind of projection and not transparent forwarding to combineLatest.

Also worth note we are trying to reduce alias at all cost, not expanding it. We have observed amount of confusion by one operator have different names and do not want to bring additional.

**Comment by BioPhoton** [comment]
Thanks for further elaboration @kwonoj I appreciate that you take you time! 

Here is a overview that shows the foundation for my suggestion of renaming `combineAll` as well as `exhaustAll` #4573. 

It's a naming matrix for operators. 
![rxjs-operator-naming-matrix](https://user-images.githubusercontent.com/10064416/53351847-078f1680-3922-11e9-83ae-98f6ad1feeac.jpg)
It should be obvious to realize the system behind it...

Regarding aliases:
>Also worth note we are trying to reduce alias at all cost, not expanding it. We have observed amount of confusion by one operator have different names and do not want to bring additional.

I would suggest a renaming in version 7 as there are anyway breaking changes. 
We could easyly incluse this changes in a tool like [rxjs-tslint](https://github.com/ReactiveX/rxjs-tslint) and do the renaming automatically.

------

In my opinion consistency in naming is most important to learn all the different operators. I have even more suggestions that would fix inconsistencies in naming and would help people to learn.

If there is Interest cc @benlesh @cartant @JWO719 I can try to deliver a fully fleshed suggestion for consistent naming of all operators in the next 2-3 weeks. 

As I sayed, creating a *naming matrix* and have *consisten naming* would help the comminity a lot in learning.
In every training the feedback from my attendees is the same regarding operator naming and grouping of operators. It's just feedback from aproximately 400 - 500 people but I guess worth to at least have a think about...

**Comment by BioPhoton** [comment]
Another reason why renaming/aliasing should be doable:
https://github.com/ReactiveX/rxjs/issues/3927
It's done anyway a lot...

**Comment by benlesh** [comment]
From core team meeting: We should alias `combineAll` as `combineLatestAll` and deprecate the old one.
