### ISSUE TITLE
Shouldn't the buffer operator be named bufferUntil

### ISSUE THREAD

**Issue by BioPhoton** [ReactiveX/rxjs#4591]
**Current Behavior**
All good! Just the naming could more aligned with the "convention".

**Possible Solution**
I would expect the name of `buffer` to be `bufferUntil`.

**Additional context/Screenshots**
If you take a look at the "naming convention" you will realize that all the other operators like `skipUntil`, `takeUntil` etc. take an observable as param which triggers inner behavior.
Also, the docs use the `until` word to describe the behavior see: [buffer](https://github.com/ReactiveX/rxjs/blob/6.4.0/src/internal/operators/buffer.ts#L10)

Therefore I consider the naming as inconsistent.

I would suggest to implement it as an alias.

**Comment by kwonoj** [comment]
*until operator shortcurcuits source observable. Buffer is not, it's intended to create inner observable. While most of these naming comes from consistency between other language binding, this specific case I don't think it is not consistent.

**Comment by BioPhoton** [comment]
I can see your point. `buffer` does not complete if the passed observable fires, it just emits the buffered values. 
Anyway, I believe there is a tight relation in the behavior. I will reconsider my opinion! 

Thanks for your time!

**Comment by BioPhoton** [comment]
You convinced me.
Thanks for your time to explain to me your view!
