### ISSUE TITLE
TS inference produces Observable<T> when using rxjs flattening operators

### ISSUE THREAD

**Issue by tomachalek** [ReactiveX/rxjs#4596]
TS type inference when using *flatMap*/*mergeMap*/*concatMap*/*exhaustMap* produces `Observable<T>`.

```js
import { of } from 'rxjs'; 
import { mergeMap } from 'rxjs/operators';
of(1, 2, 3).pipe(mergeMap(p => of({value: p}))).subscribe(
    (item) => {
        console.log(item.value);
    }
);

// produces error: Property 'value' does not exist on type 'T'
```

**Expected behavior**
the "flattening" methods above should produce a proper type inference.

**Environment**
- Runtime:  Node v8.10.0 + TS 3.3.3333 (also VSCode with TS 3.3.1)
- RxJS version: 6.4.0 (also tested 6.3.3, 6.2.2 with the same result)

**Comment by cartant** [comment]
I cannot reproduce the problem using your snippet. The type inference works fine, for me.

**Comment by tomachalek** [comment]
I've investigated this further and it looks like the problem is my `tsconfig`. 
The version producing the error:

```json
{
  "compilerOptions": {
    "rootDir": ".",
    "module": "commonjs",
    "target": "es5"
  },
  "files": [
    "index.ts"
   ]
}
```

Once I add `"lib": [ "es2015", "dom" ]` to the `compilerOptions` (or change whole target to a newer version) the problem seems to be gone.

**Comment by cartant** [comment]
Certain ES2015 features - [`Iterable`](https://github.com/ReactiveX/rxjs/blob/6.4.0/src/internal/types.ts#L52) and [`Symbol`](https://github.com/ReactiveX/rxjs/blob/6.4.0/src/internal/types.ts#L57) - are used in RxJS's typings. Their not being present is not supported.
