### ISSUE TITLE
Add SVG version to logo resources

### ISSUE THREAD

**Issue by BioPhoton** [ReactiveX/rxjs#4597]
### Description Of The Issue

I created an SVG version of the Rx logo 4c (four colors) and some versions for 1c (one color).

I would like to contribute this to the official repo. 
Here some questions arise:
- Can I do it legal wise? There are for sure some licenses or other restrictions law wise.
- I would love to create customizations of the logo. I.e. Angular meetups have their own version of the angular logo. Here we may need to adopt the current license to enable it in a legal way.

I attached the svg files for review...
![rxjs-logo_v1](https://user-images.githubusercontent.com/10064416/53419310-eb4eb080-39d9-11e9-92f0-f402f33fe4fd.jpg)
![rxjs-logo_v4](https://user-images.githubusercontent.com/10064416/53419311-eb4eb080-39d9-11e9-9221-68b7a739f425.jpg)
![rxjs-logo_v3](https://user-images.githubusercontent.com/10064416/53419312-ebe74700-39d9-11e9-9422-246ad290d9b6.jpg)
![rxjs-logo_v2](https://user-images.githubusercontent.com/10064416/53419313-ebe74700-39d9-11e9-8368-325b23b1cd4f.jpg)

[RxJS-svg-logovariations.pdf](https://github.com/ReactiveX/rxjs/files/2905875/RxJS-svg-logovariations.pdf)

**Comment by benlesh** [comment]
Interesting. I'm not sure we'd use the variations, but an SVG of the original would be good. I had one somewhere, but I'm not sure where it is... Maybe @mattpodwysocki has one?

**Comment by benlesh** [comment]
Found it!

https://drive.google.com/file/d/1309VbFpxs4dho3c8qZDd2Wpfq4qiI2OA/view?usp=sharing

**Comment by benlesh** [comment]
@BioPhoton I think it's a _great_ idea to just add this to the repo. IMaybe put together a PR to add the svg logo to the root folder or something? After that I'll just compare whatever you submit with whatever one I have and we can take the better of the two (I don't have any personal feelings about it)

**Comment by BioPhoton** [comment]
I also don't care which one gets used!
😉

Will do when I'm back home...

**Comment by gilbarbara** [comment]
@BioPhoton version is much better than in terms of number of paths and color! 👍🏻
