### ISSUE TITLE
concatMap documentation sample is incorrect

### ISSUE THREAD

**Issue by dkosasih** [ReactiveX/rxjs#4599]
### Documentation Related To Component:
concatMap

### Please check those that apply
- [x] typo
- [ ] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue
The example on Stackblitz link is broken.
There is a missing `)` in the code

**Comment by martinsik** [comment]
You mean this line? https://github.com/ReactiveX/rxjs/blob/master/src/internal/operators/concatMap.ts#L44

**Comment by dkosasih** [comment]
Yes. It's very simple change 😊
I was thinking of doing a PR some time today

**Comment by dzhavat** [comment]
@dkosasih Sorry, couldn't resist 😜
