### ISSUE TITLE
Two versions of the doc

### ISSUE THREAD

**Issue by alanyinjs** [ReactiveX/rxjs#4604]
### Documentation Related To Component:

N/A

### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [x] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue

There are currently two versions of the official doc that are both available through Google search: 

- Old version: reactivex.io
/rxjs/manual/overview.html#introduction

-New version: https://rxjs.dev/guide/overview

These versions have slightly different content. In terms of SEO, I found the old version ranks higher.

**Comment by JWO719** [comment]
So http://rxjs.dev is the current version of the rxjs docs. The other one is the documentation for rxjs 5. I don't know if we can do anything to improve the seo ranking for the new docs?!

**Comment by benlesh** [comment]
We can remove/delete the old docs, honestly.

**Comment by BioPhoton** [comment]
@JWO719 please please clise this issue or remove the old docs and close it later.
Could you please give a quick status update on this? 🙏
