### ISSUE TITLE
Prefix internal operator functions to avoid bad imports

### ISSUE THREAD

**Issue by yjaaidi** [ReactiveX/rxjs#4608]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Importing operators & observables from the wrong path (`rxjs/internal/operators/...` instead `rxjs/operators`) of  seems to be a common issue.
Cf. https://github.com/ReactiveX/rxjs/issues/4363 _switchMap not unsubscribing depending on import of Observable_

**Describe the solution you'd like**
Would that make sense to prefix these functions and classes with some special character (`_` or `ø`) to avoid bad imports?
If yes, I'll be glad to contribute.

Thanks!

**Comment by kwonoj** [comment]
@cartant doesn't `rxjst-tslint` have some rules prevents internal import already?

**Comment by cartant** [comment]
There is an `rxjs-no-internal` rule in [`rxjs-tslint-rules`](https://github.com/cartant/rxjs-tslint-rules).

**Comment by cartant** [comment]
Regarding a prefix, I'm :-1:

The `internal` directory itself is intended to be a guard against importing from the incorrect location. And the operators themselves are not internal - only the import location is internal.

If it doesn't function well enough as a guard - and I think it works just fine - I would propose adopting an more in-your-face name for that directory. Perhaps a name that's along the lines of the names that the React team seems to favour for internals: `do-not-import-from-here-or-you-will-be-sacked`.

**Comment by yjaaidi** [comment]
Hi everyone,

Thanks for the feedback.

Actually, the name doesn’t solve the problem as the typical use case is
"auto-import" and for some random reason, it happens that IDEs pick the
“internals”.

Concerning the tslint rules, it’s interesting but the idea here is to think
about people who are new to RxJS so they probably don’t have a linter setup
yet.

**Comment by cartant** [comment]
IMO, the effort required to add prefixes would be better applied elsewhere.

I would favour abandoning the `"rxjs/operators"` import location altogether and using `"rxjs"` for everything. This will be a possibility if the conflicting names - like `concat` and `merge` - are resolved either via the removal of deprecated operators or the renaming of the operators to `mergeWith`, etc.

**Comment by kwonoj** [comment]
We may need some reorg in future major versions eventually, but I don't think we'll apply this kind of prefix at least. Will closing and improve over version changes.
