### ISSUE TITLE
changing signature of startWith() to accept scheduler as last parameter?

### ISSUE THREAD

**Issue by kwonoj** [ReactiveX/RxJS#461]
While other operators like `throttle`, `timeout`, `delay`, etcs are accepting `scheduler` as last parameter, [`startWith`] (https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/startwith.md) accept scheduler as first parameter. 

```
Rx.Observable.prototype.startWith([scheduler] ...args)
Rx.Observable.prototype.timeout(dueTime, [other], [scheduler])
Rx.Observable.prototype.throttle(windowDuration, [scheduler])
```

Maybe better to align signature of `startWith` to accept scheduler as last parameter also?

**Comment by staltz** [comment]
I agree

**Comment by blesh** [comment]
Yes... schedulers should always be the last argument. At least according the the [Rx Design Guidelines from Microsoft, Article 6.11](http://blogs.msdn.com/b/rxteam/archive/2010/10/28/rx-design-guidelines.aspx)

**Comment by kwonoj** [comment]
OK, seems I can update currently opened PR directly instead of creating new one.

**Comment by staltz** [comment]
I guess we can close this.
