### ISSUE TITLE
A behaviour in mergeMap which I can not understand while processing big files in Node

### ISSUE THREAD

**Issue by EnricoPicci** [ReactiveX/rxjs#4610]
I am processing a big file in Node (more than 2 mil lines), using fs.readline as underlying mechanism, but transforming it into an Observable via the following code

```
const readLineObs = (filePath: string) : Observable<string> => {
    return Observable.create((observer: Observer<string>): TeardownLogic => {
        const rl = readline.createInterface({
            input: fs.createReadStream(filePath),
            crlfDelay: Infinity
        });

        rl.on('line', (line: string)  => {
            observer.next(line);
        });
        rl.on('close', ()  => {
            observer.complete();
        });
    })
};
```

For each line read I need to perform some asynchronous processing which introduces a certain delay, which I simulate with the `delay()`. So my code eventually is the following:

```
import { mergeMap, map, delay, tap } from "rxjs/operators";
import { of } from "rxjs";

const filePath = '/the/path/to/my-big-file.txt';

const DELAY = 10000;
const CONCURRENCY = 10000;

let readCounter = 0;

readLineObs(filePath)
.pipe(
    tap(() => {
        readCounter++;
        if (readCounter > 0 && readCounter % 100000 === 0) {
            console.log('readCounter', readCounter)
        }
    }),
    mergeMap(line => 
        of(line)
        .pipe(
            delay(DELAY)
        ),
    CONCURRENCY),
)
.subscribe()
```

If I set CONCURRENCY to null, the execution of the code causes a javascript error (out of memory) which makes sense, since there a significant delay (10.000 ms) and so readline tries to read more that javascript allows in terms of memory.

If I set CONCURRENCY to a value like 10000, what I see is that the `readCounter` stops increasing at around 190.000 and then apparently all Observables buffered with mergeMap start being executed. When the buffer of mergeMap is empty, then `readCounter` starts again increasing for about 200.000 additional lines before stopping again and letting the buffer of merge map being worked.

I have looked into the code of mergeMap but I am not able to find an explanation to this behaviour.
 Any explanation would be appreciated.

**Comment by benlesh** [comment]
Sorry for the delayed response. It's hard to say without having a real example to play with. It might even depend on the version of Node you're using... however, I'd strongly recommend that you use `concatMap` for any operation where the order of the values matters, like with reading lines. It's also possible that there's some sort of lock on the underlying stream that you're hitting while attempting to read from it multiple times concurrently. I really don't know.

Given that this is an old issue, I'm going to close it. But I hope this answer helps... even though it's slow.
