### ISSUE TITLE
[docs]: Operator `toArray` is missing documentation

### ISSUE THREAD

**Issue by BioPhoton** [ReactiveX/rxjs#4613]
- [ ] typo
- [x] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [x] needs example

### Description Of The Issue

There is no documentation for toArray. This is a duplicate from #3111 #3113. As both of them are closed without any changes to the docs I resubmitt this issue

**Comment by niklas-wortmann** [comment]
closed by #4775
