### ISSUE TITLE
[docs]: Operator `every` is missing the description

### ISSUE THREAD

**Issue by BioPhoton** [ReactiveX/rxjs#4614]
### Please check those that apply

- [ ] typo
- [x] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue

The description block of the `every` operator is missing. We might provide some description to fix this.

**Comment by hardikpthv** [comment]
I belive, this can be closed.

**Comment by jakovljevic-mladen** [comment]
I believe #4777 fixed the problem described in the issue. Closing for now.
