### ISSUE TITLE
[docs]: Operator `single` is missing the description, and examples

### ISSUE THREAD

**Issue by BioPhoton** [ReactiveX/rxjs#4616]
### Please check those that apply

- [ ] typo
- [x] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [x] needs example

### Description Of The Issue
The description and example section is missing for the `single` operator

**Comment by weitalu** [comment]
I would like to help with this issue, created a local commit, 

but I could not submit the PR because I don't have enough access to create a remote branch.

What should I do ?

(Was following this guideline https://github.com/ReactiveX/rxjs/blob/master/CONTRIBUTING.md#submitting-a-pull-request-pr)

**Comment by JWO719** [comment]
@weitalu  I think the confusing point here is (also not mentioned in the document), you need to fork the rxjs repo, push to a branch of your private forked repository and afterwards github will propose you to create a merge request for that branch to the rxjs repo. This should basically work. When there is anything unclear or still not working, feel free to contact me! Thanks for helping out with this!

**Comment by niklas-wortmann** [comment]
closed by #4623
