### ISSUE TITLE
[docs]: Operator `ignoreElements` is missing the description, and examples

### ISSUE THREAD

**Issue by BioPhoton** [ReactiveX/rxjs#4618]
### Please check those that apply

- [ ] typo
- [x] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [x] needs example

### Description Of The Issue
The `ignoreElements` operator is missing the description. 
Furthermore, there is a bug in the example. In the imports there is a typo in line 2: Rename `ifnoreElements` to `ignoreElements`

**Comment by jschwarty** [comment]
👋 @BioPhoton 
Created a PR 😎

Looks like the **typo** issue was already resolved in a different commit a while ago:
https://github.com/ReactiveX/rxjs/commit/3eafdcbd39a45f24de42b4953ee4d2412e00f1e5#diff-f29a1f7a528e56b8b40ec8af2a8820c9

**Comment by niklas-wortmann** [comment]
closed by #5074
