### ISSUE TITLE
Operator `isEmpty` is missing the short description, description, and examples

### ISSUE THREAD

**Issue by BioPhoton** [ReactiveX/rxjs#4619]
### Please check those that apply

- [ ] typo
- [x] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [x] needs example

### Description Of The Issue
The `isEmpty` operator is missing the short description, description, and examples.   
We might want to implement this.

**Comment by martinsik** [comment]
This should be already there because of #4580.

**Comment by JWO719** [comment]
It's just not deployed yet. Therefore I will close this issue for now.

**Comment by BioPhoton** [comment]
Next time I will take a better look at the PR's. 🙈
