### ISSUE TITLE
[docs]: The "Edit in StackBlitz" button opens snippets in wrong format causing many examples to break

### ISSUE THREAD

**Issue by BioPhoton** [ReactiveX/rxjs#4621]
### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [ ] documentation needs clarification
- [X] error(s) in example
- [ ] needs example

### Description Of The Issue
As all examples are written in TypeScript and the "Edit in StackBlitz" button opens all snippest in JavaScript format many examples do not work.

**Comment by JWO719** [comment]
Well spotted! Thanks for that. So the issue occurs when the code example is labeled as javascript code,

e.g. 
```markdown
```javascript
import { Observable } from 'rxjs';

const observable = new Observable(subscriber => {
  subscriber.next(1);
  subscriber.next(2);
  subscriber.next(3);
  setTimeout(() => {
    subscriber.next(4);
    subscriber.complete();
  }, 1000);
});
```

such examples will produce a js stackblitz.

What we basically need to do is replace those javascript hightlighting with ts. AFAIK most of the examples uses typescript so it should be quite safe to replace javascript with typescript here, but it might break some of the examples

**Comment by BioPhoton** [comment]
Is there a standard for code snippets in this reop?
I saw some examples using `var` so this would be a thing to replace too if replacing "```javascript" with "```ts".

Or are just all snippets in the src folder in ts? 
If not already you might mention it in some fitting place.

**Comment by BioPhoton** [comment]
Hi @JWO719 as the related PR is merged, (and shipped?) we can close it. 
Also #4605 could be closed.

Please reopen if I'm wrong
