### ISSUE TITLE
[docs]: Operator `retryWhen` is missing the description, and examples

### ISSUE THREAD

**Issue by BioPhoton** [ReactiveX/rxjs#4626]
### Please check those that apply

- [ ] typo
- [x] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [x] needs example

### Description Of The Issue
We might wanna add a detailed description as well as an example here

**Comment by PDavid** [comment]
Hi,

I opened a PR to fix this issue: https://github.com/ReactiveX/rxjs/pull/5097
Can you please have a look maybe? I'd appreciate any feedback.

Thanks!

**Comment by JWO719** [comment]
closed by #5097
