### ISSUE TITLE
rxjs 7 - ideas to be taken from the fastest and smallest alternative

### ISSUE THREAD

**Issue by brucou** [ReactiveX/rxjs#4629]
I was just acquainted with the Rxjs 7 design document. I was wondering if you knew about this library which is the equivalent to Rxjs of what Preact is to React, i.e. same API but faster and smaller : https://github.com/langhuihui/rx4rx/tree/master/stdlib

Last time I checked it, the library was 4k. There is also a speed-optimized version based on classes (and that one happens to have a README in english) : https://github.com/langhuihui/rx4rx/tree/master/highlib. Speed-wise it beats anything.

I am bringing to your knowledge under the hypothesis that you may find there some extra ideas (once you get past the chinese language - the code reads as usual) to reduce size and increase speed of rxjs.

**Comment by benlesh** [comment]
Thanks for pointing this out. I've seen this one before. It's really not great that this person decided to take the "rx" name, honestly. It implies some sort of affiliation.

Myself (and I'm sure most of the core team) have rolled tons of small toy version of reactive libraries featuring things like observables. You can make them really, really small. But there are a TON of trade-offs. The library in question here has no handling of errors in user-provided functions, no guaranteed resource tear down (memory leaks if you mess up), no accounting for producer interference on shared sources, etc. RxJS is trying to provide a more comprehensive, production-ready set of functionality.

That said, I do love looking at these things (and rolling my own, over and over again). RxJS, by version 8, from all experiments, should be substantially smaller (~50-60% of the size) while retaining all it's current safety and features.

**Comment by brucou** [comment]
Thanks for a quick answer Ben. Yes, I totally believe that rxjs has a set of requirements that contrains it. I was brought to send you this after reading the v7 document because, with this library:

- it is damn easy to add new operators
- this shows classes (in highlib) can get you faster (at least with V8) implementation than a functional approach (in stdlib). Most.js also use classes among other things to get its superlative speed

I could not figure out however if schedulers could be added on top rather than within the observable design. Just like most.js this library does not seem to do much in the sense of scheduling. 

Anyways, you already looked at it, and came to some conclusions so all is good.
