### ISSUE TITLE
[docs]: Replace JQuery to be library agnostic

### ISSUE THREAD

**Issue by BioPhoton** [ReactiveX/rxjs#4630]
### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [x] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue

In the docs of the bindCallback is an example for JQuery. 
https://github.com/ReactiveX/rxjs/blob/master/src/internal/observable/bindCallback.ts#L113

We should replace it with a more modern lib. i.e. axios

**Comment by BioPhoton** [comment]
Ok, I realized that the example is for bindCallback axios will not work. 
Most of the modern technologies are at least promise based. 

I'm happy to implement any suggestion. Just don't know what I should aim for.

**Comment by benlesh** [comment]
This issue is no longer relevant.
