### ISSUE TITLE
Identify all tests that have not been updated to proper imports and "run mode"

### ISSUE THREAD

**Issue by benlesh** [ReactiveX/rxjs#4633]
# Just a list, not the fixes.

The work here is simple: Create a list or spreadsheet we can edit that tracks all of the tests in our suite that need to be updated in two different ways:

1. Imports need to be "modernized"
2. TestScheduler usage needs to be using "run mode".

### Identify tests without "modernized" imports

A lot of work was already done here, but there's still some work that needs to be done.  Basically, we need to update tests to make sure they are all importing from `rxjs`, `rxjs/operators`, `rxjs/testing`, etc, and **NOT** importing like `import * as Rx from 'rxjs'`. 

We also need to make sure all operator usage is "pipeable". There are still a few tests where they're being "dot-chained" which isn't what we want.

### Identify tests that need to use "run mode"

Run mode is testing with `TestScheduler.prototype.run` like so:

```ts
let testScheduler: TestScheduler;

beforeEach(() => {
  // "defaultObservableComparar" isn't a real thing, I forgot what it's called :P haha.
  testScheduler = new TestScheduler(defaultObservableComparer); 
});

it('should be a test like this', () => {
  testScheduler.run(({ hot, cold, expectObservable }) => {
     const source = hot('---a--b--c--d--|');
     const subs = '     -----^----------!';
     const expected = '      --b--c--d--|';
     expect(source, subs).toBe(expected);
  });
});
```

### Expected result

A list we can use to track progress on updating these files.

### Impact

It will drive a *LOT* of work for people, particularly people new to contributing to the code base. This work will enable us to more cleanly move to RxJS v 7 and beyond!

Moving to using "run mode" will enable us to use a code formatter (such as Prettier or Clang format) on the library, because we won't have to worry about jacking up marble diagrams anymore (because we can use spaces in the strings more effectively). This will help others contribute to the codebase by making it more readable.

**Comment by artem-galas** [comment]
I've created a list of all (I hope) **NOT "modernized" imports**.
Here it's.

## NOT "modernized" imports
### Spec Root folder
- [ ] exports-spec.ts [link](https://github.com/ReactiveX/rxjs/tree/master/spec/exports-spec.ts)
- [ ] Notification-spec.ts [link](https://github.com/ReactiveX/rxjs/tree/master/spec/Notification-spec.ts)
- [ ] Observable-spec.ts [link](https://github.com/ReactiveX/rxjs/tree/master/spec/Observable-spec.ts)
- [ ] root-module-spec.ts [link](https://github.com/ReactiveX/rxjs/tree/master/spec/root-module-spec.ts)
- [ ] Subject-spec.ts [link](https://github.com/ReactiveX/rxjs/tree/master/spec/Subject-spec.ts)
- [ ] Subscription-spec.ts [link](https://github.com/ReactiveX/rxjs/tree/master/spec/Subscription-spec.ts)

### Spec dtslint
- [ ] partition-spec.ts [link](https://github.com/ReactiveX/rxjs/tree/master/spec-dtslint/operators/partition-spec.ts)

### Spec Helpers
- [ ] test-helper.ts [link](https://github.com/ReactiveX/rxjs/tree/master/spec/helpers/test-helper.ts)
- [ ] testScheduler-ui.ts [link](https://github.com/ReactiveX/rxjs/tree/master/spec/helpers/testScheduler-ui.ts)

### Spec Observables
- [ ] IteratorObservable-spec.ts [link](https://github.com/ReactiveX/rxjs/tree/master/spec/observables/IteratorObservable-spec.ts)

### Spec Operators
- [ ] defaultIfEmpty-spec.ts [link](https://github.com/ReactiveX/rxjs/tree/master/spec/operators/defaultIfEmpty-spec.ts)
- [ ] forkJoin-spec.ts [link](https://github.com/ReactiveX/rxjs/tree/master/spec/operators/forkJoin-spec.ts)
- [ ] let-spec.ts [link](https://github.com/ReactiveX/rxjs/tree/master/spec/operators/let-spec.ts)
- [ ] partition-spec.ts [link](https://github.com/ReactiveX/rxjs/tree/master/spec/operators/partition-spec.ts)

### Spec Subjects
- [ ] AsyncSubject-spec.ts [link](https://github.com/ReactiveX/rxjs/tree/master/spec/subjects/AsyncSubject-spec.ts)
- [ ] BehaviorSubject-spec.ts [link](https://github.com/ReactiveX/rxjs/tree/master/spec/subjects/BehaviorSubject-spec.ts)
- [ ] ReplaySubject-spec.ts [link](https://github.com/ReactiveX/rxjs/tree/master/spec/subjects/ReplaySubject-spec.ts)

### Spec Util
- [ ] subscribeToResult-spec.ts [link](https://github.com/ReactiveX/rxjs/tree/master/spec/util/subscribeToResult-spec.ts)
- [ ] UnsubscriptionError-spec.ts [link](https://github.com/ReactiveX/rxjs/tree/master/spec/util/UnsubscriptionError-spec.ts)

**Comment by artem-galas** [comment]
Try to find places where don't use `pipeable` operators. But I'm not sure how to find it in better way, maybe you know the most common `dot notation` operator? For the moment I try to find them by `.map`

WIP

## NOT pipeable
- [ ] switch-spec.ts [link](https://github.com/ReactiveX/rxjs/blob/master/spec/operators/switch-spec.ts#L35)
