### ISSUE TITLE
Wanted: Slick solutions for dynamically adding operators to Observable

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#464]
So right now we're kind of hacking together the core operators on Observable in the `Rx.ts` output file.

Ideally, people would be able to use just the operators they care about in their app, and not at all include any of the operators they don't need.

There are a ton of possible solutions for this, but I'd love to hear any and all ideas around this.

**Comment by blesh** [comment]
### Idea: Build-Time Plugins

One option would be to create some sort of TypeScript and/or Babel plugin/addon that statically analyzed operator use, and included or excluded those operators from the output Observable build. Something like RxJS specific tree-shaking... but it's more like "operator-shaking", because it wouldn't be general.

**Comment by staltz** [comment]
Another idea is similar to ESLint configurations: allow people to publish a subset of RxJS operators they like most. Then include that as `import Rx from 'myFavoriteRxFlavor;`.

**Comment by jeremymwells** [comment]
@blesh - I really like the tree-shaking idea. A consuming app could have something like `rx.json`, which could allow them to build out their particular rx flavor(s) however they want. It also buys shippable configurations similar to what we already know/use in RxJS such as [Main Libraries](https://github.com/Reactive-Extensions/RxJS#main-libraries), [Lite Libraries](https://github.com/Reactive-Extensions/RxJS#lite-libraries), [Core Libraries](https://github.com/Reactive-Extensions/RxJS#core-libraries).

**Comment by Rayman** [comment]
I saw something similar with lodash: https://github.com/megawac/lodash-modularize

It can detect which lodash functions you are using and then output a custom build.

**Comment by blesh** [comment]
There's a related discussion here: https://github.com/angular/angular/issues/4543#issuecomment-145955252

It's talking about rollup, specifically. I think that would work for the ES6 build of RxJS, but not for other usage.

**Comment by trxcllnt** [comment]
@blesh I've been writing a local `rx` module that imports just the operators (and Subjects, Schedulers, etc.) I need in my app:

```es6
// src/rx.js
import Rx from '@reactivex/rxjs/dist/cjs/Rx.minimal'; // a minimal empty namespace to share
import Observable from '@reactivex/rxjs/dist/cjs/Observable';
import { of as ofStatic } from '@reactivex/rxjs/dist/cjs/observables/ArrayObservable';
import mapProto from '@reactivex/rxjs/dist/cjs/operators/map';
Observable.of = ofStatic;
Observable.prototype.map = mapProto;
export Rx;
```

Then in my `index` module, require my `rx` module first.
```es6
// src/index.js
import Rx from './rx';
/* import everything else */
```

Then in the rest of my modules, I can just import the specific type I need instead of pulling in the whole Rx namespace (alternatively, I could import the `Rx.minimal` namespace since I seeded it in my local `rx` module):
```es6
// src/foo.js
import Observable from '@reactivex/rxjs/dist/cjs/Observable';
Observable
  .of("x", "y", "z")
  .map(x => x + " says hello")
  .subscribe(message => console.log(message));
```
