### ISSUE TITLE
[docs]: Rename/Alias `pairs` to `entries` to provide a more intuitive/JS-aligned API

### ISSUE THREAD

**Issue by BioPhoton** [ReactiveX/rxjs#4644]
## Bug Report

We could rename/alias pairs into entries as it is exactly what the js Object first-class function entries are doing.
As far as is know @benlesh implemented this operator. So maybe he knows best for what reason the naming is why it is.

Also, the source code could be improved as the API changed since it'S implementation and I believe we could go with `Object.entries`, but maybe this updating of the code should be a separate issue. 

I'll wait for feedback here. :)

Furthermore, the description section could be improved compared to the short description section.

**Current Behavior**
All good!

**Reproduction**
No bug present

**Expected behavior**
Behavior is perfect

**Possible Solution**
Introducing Alias 

**Additional context/Screenshots**

```ts
import {of} from 'rxjs';
import {pairs} from 'rxjs/operators';

const obj = {rxjs: 'amazing'};

// JS version
// Output: 
// [rxjs,'amazing']
console.log(Object.entries(obj));

// RxJS version
// Output: 
// [rxjs,'amazing']
of(obj).pipe(pairs()).subscribe(console.log);
```

**Comment by benlesh** [comment]
We are deprecating this function and removing it. People can get this by just: `from(Object.entries(obj))`.
