### ISSUE TITLE
Operator `mergeScan` is missing imports in the example

### ISSUE THREAD

**Issue by BioPhoton** [ReactiveX/rxjs#4648]
### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [ ] documentation needs clarification
- [x] error(s) in example
- [ ] needs example

### Description Of The Issue

We have to add the import for `mergeScan` to have a working example. Also, some comments should be fixed

**Comment by dzhavat** [comment]
#4638 is fixing the import issue. Maybe we can use the same PR to fix the comments as well? Which comments did you have in mind?

**Comment by BioPhoton** [comment]
The numbers firm the console logs at the bottom of the file are not commented out.

**Comment by BioPhoton** [comment]
Btw, I was just pushing my PR. But super happy that ppl get active so fast. 😁👌🙏🙏

**Comment by dzhavat** [comment]
It's @saxicek who opened the PR a few days ago. And it looks like it's his/her first contribution as well! I hope he/she will be happy to update his/her PR fixing those console logs. Can you leave that as a feedback on the PR? :)

**Comment by saxicek** [comment]
Hi, just added the comment lines to the example in PR #4638. Hope that is what was asked. ;-)

**Comment by dzhavat** [comment]
@saxicek Cool! Thanks for the contribution. 👍

**Comment by JWO719** [comment]
closed by #4638
