### ISSUE TITLE
The image in API doc cannot be displayed

### ISSUE THREAD

**Issue by xuemind** [ReactiveX/rxjs#4649]
### Documentation Related To Component:

The most of the images in API doc cannot be displayed in browser. such as [`switchMap`](https://rxjs.dev/api/operators/switchMap), [`find`](https://rxjs.dev/api/operators/find) and etc.
Browser report that `https://rxjs.dev/switchMap.png`, `https://rxjs.dev/find.png` were not found. 

### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue

The most of the images in API doc cannot be displayed in browser. such as [`switchMap`](https://rxjs.dev/api/operators/switchMap), [`find`](https://rxjs.dev/api/operators/find) and etc.
Browser report that `https://rxjs.dev/switchMap.png`, `https://rxjs.dev/find.png` were not found.

**Comment by dzhavat** [comment]
Related to #4366

**Comment by JWO719** [comment]
closed due to duplicate, please see #4366
