### ISSUE TITLE
Update ajax operator

### ISSUE THREAD

**Issue by paschalidi** [ReactiveX/rxjs#4652]
### Documentation Related To Component:

 [ajax](https://github.com/reactivex/rxjs/edit/master/src/internal/observable/dom/ajax.ts)

### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [x] needs example

### Description Of The Issue

I have the feeling that since `ajax` is one of the useful operators we have in Rxjs for making requests etc etc it would be nice if the documentation have more examples. Therefore I opened a PR that will add few examples on Stackblitz. Please have a look https://github.com/ReactiveX/rxjs/pull/4653

I would be happy to hear your feedback since now I am gonna work on that in order to have this documented even better.

**Comment by benlesh** [comment]
Closed by #4653
