### ISSUE TITLE
[docs]: Operator `onErrorResumeNext` description brings less value then short description

### ISSUE THREAD

**Issue by BioPhoton** [ReactiveX/rxjs#4654]
### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [x] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue

The short description brings way more value than the main description. I even think the main description is a little bit confusing. We might want to change this.

**Comment by JWO719** [comment]
What are you exactly referring to and what are you thinking of? Could you elaborate a bit here

**Comment by BioPhoton** [comment]
Sure!

In general, I believe the name let us focus too much on the word error. 
I guess a lot of people believe this operator only handles errors. In fact, it is an operator that concatenates all passed observables and catches eventually occurring errors. 
But the main logic/goal is concatenating observables.

We could consider a renaming or aliasing to something like `onEndResumeNext` or `catchErrorAndConcat`. Not really creative but I guess it shows the direction I'm thinking of.


**Short Description:**
> When any of the provided Observable emits an complete or error notification, 
> it immediately subscribes to the next one that was passed.

In the short description, we mention complete and error. Even if it is not really detailed we easily get the point. => `complete or error notification`.

**Description:** (Here I reffere to the text above the marmle diagram)
> Execute series of Observables no matter what, 
> even if it means swallowing errors.

The Description, however, is first of all shorter the short description and more cryptic. 
If we cscroll a bit and continue after the marble diagram we have a very nice description that contains alll edge cases as well as the int that it is kind of a concat operator. Very nice very detailed. 

We could baybejust remove the first sentence? => Execute series of Observables no matter what, even if it means swallowing errors.


If you need more elaboration just tell. I'm happy to text here! <3
