### ISSUE TITLE
Creation function `throwError` should align with other constants like `EMPTY`, `NEVER` 

### ISSUE THREAD

**Issue by BioPhoton** [ReactiveX/rxjs#4657]
### Description Of The Issue

As we have constants like `EMPTY`, `NEVER`  why not create `THROW` and be align with the rest and have a more consistent API?

**Comment by kwonoj** [comment]
empty / never is no-value constant while throwError needs value to be thrown. Mind elaborate how throw can be cobstant interface?

**Comment by BioPhoton** [comment]
You are right! I should stop creating issuea at 1:30 am.. :)
