### ISSUE TITLE
[docs]: Operator `timeInterval`  is missing the description

### ISSUE THREAD

**Issue by BioPhoton** [ReactiveX/rxjs#4661]
### Please check those that apply

- [ ] typo
- [x] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue

We may want to add description.

**Comment by martinsik** [comment]
This can be probably closed thanks to #4756.

**Comment by BioPhoton** [comment]
Thanks for the information!
