### ISSUE TITLE
[docs]: Operator `throwIfEmpty` in missing description, function signature and param description

### ISSUE THREAD

**Issue by BioPhoton** [ReactiveX/rxjs#4662]
### Please check those that apply

- [ ] typo
- [x] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue

We might want to add the following information:

- description
- function signature 
- param description

**Comment by benlesh** [comment]
This has been fixed for some time now.
