### ISSUE TITLE
[docs]: Operator `generate` need a total over whole of the documentation

### ISSUE THREAD

**Issue by BioPhoton** [ReactiveX/rxjs#4672]
### Please check those that apply

- [ ] typo
- [x] documentation doesn't exist
- [x] documentation needs clarification
- [x] error(s) in example
- [ ] needs example

### Description Of The Issue

The whole documentation of [generate](https://rxjs.dev/api/index/function/generate) is .... a mess :-p

I guess because it is not yet refactored to the new docs style. 

I would love to file a PR of this. Is there a good example of what to do where to start what structure or in which order all the different chapters should ideally be?

If this not exist yet I will create a doc for refactoring the docs :)

Please let me know how/where to get my missing info.

**Comment by JWO719** [comment]
For now there isn't such a document, but I think it would be really helpful for "first timers". I'm not sure what's the easiest way to add such a document and provide you with all the needed informations, but I would love to support you with this!

**Comment by niklas-wortmann** [comment]
closed by #5006
