### ISSUE TITLE
[docs]: Operator `repeat` is missing documentation, example, and see also

### ISSUE THREAD

**Issue by BioPhoton** [ReactiveX/rxjs#4675]
### Please check those that apply

- [ ] typo
- [x] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [x] needs example

### Description Of The Issue

This operator needs documentation, example and the see Alos section.
We might want to include it.

For See Also we could include `repeatWhen`

**Comment by JWO719** [comment]
done by #4681
