### ISSUE TITLE
[docs]: Operator `repeatWhen` is missing documentation, example, and see also

### ISSUE THREAD

**Issue by BioPhoton** [ReactiveX/rxjs#4676]
### Please check those that apply

- [ ] typo
- [x] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [x] needs example

### Description Of The Issue
This operator needs documentation, example and the see also section.
We might want to include it.

For See Also we could include repeat

**Comment by JWO719** [comment]
closed by #4703
