### ISSUE TITLE
New Contributor's Guide

### ISSUE THREAD

**Issue by dance-cmdr** [ReactiveX/rxjs#4678]
### Documentation Related To Component:

Contribution.md

### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [x] documentation needs clarification
- [ ] error(s) in example
- [x] needs example

### Description Of The Issue

Cheers everyone. 

I'm trying to crack into contributing but I'm really overwhelmed. My main problem might be silly, but, I'm basically afraid to pick an issue. I don't know where to start from. 

The Contribution.md covers the technical part but leaves completely open the matter of how to start. So, technically I understand how to make a contribution but I don't know what would be useful to contribute. Solving my own problems is not yet the case, as I didn't run into a bug or missing documentation yet. (Or I thought I got the idea of how it works and didn't make it my problem)

There is an attempt to cover this in Contribution.md, `Submitting a PR` section. However, simply checking for PRs implies that you have already decided what to work on.

So the subject boils down to that I might be conditoned with "Agile" Methodologies, and having a need of understanding who works on what and what has priority, but I think there are more like me out in th wild. 

Do current contributors follow a process when picking an issue and how do you know when something is not picked by someone else, or if the issue it's important at all to pick? If there is not 'set in stone' process how would you suggest picking issues from the list?

If there is a process, or the nececity to define one, it would be nice to have it documented into Contribution.md. If not, I feel using more often the labels  `WIP`, `priotity:*`, `target:*` and adding `good first issue` labels, would be nice and will make filtering easier.

Please let me know if you tried something similar and didn't work for you.

In a nutshell, I propose for: 
- [ ] **Labels** in issues to guide new contributors to pick things
  - [ ] **"For Noobs"** (or "Good First Issue" for simple tasks that would be easy for someone to start with)
  - [ ] **"WIP"** (use it more)
  - [ ] **"priority: High"**  (use it more)
  - [ ] **"priority"** (if we think having a 3 tier priority scale makes sense)
  - [ ] **"priority: low"** (deprecate it. If we tag with priority staff anything that is not tagged makes sense to be of low priority)
  
- [ ] Contribution.md
  - [ ] **New Contributors Guide**. A section that guides new contributors on how to pick their first issue and other useful tips for new contributors if you fancy.
  - [ ] **Labels** section explaining the definition of different labels in use and their difference, for example the diference between `target: Next Major` and `priority: high`.

Sorry for the wall of text!
I'd really love to hear your opinion on that and If there are resources covering this subject that I missed. Please point me towards thy direction.

**Comment by dzhavat** [comment]
I feel you on this one. I had the same feelings when I first started contributing. I wanted to do something but wasn't sure exactly what. Then one day I opened a new issue and volunteered to fix it.

My contributions so far have all been related to the documentation. I think that's an easy place to start. If you find a typo, broken or missing example, broken link or even a missing dot, don't hesitate to make a PR. At first, it might seem trivial and not worth the time but these small wins really do make a difference. You get familiar with the code and become more confident making bigger changes.

It's also worth mentioning here that contribution doesn't only mean opening PRs. Contributing can take different forms - opening an issue, participating in discussions, fixing a bug, reviewing PRs, adding examples to the docs, commenting on other people's issues and helping them get closed, etc.

What is important is taking the initiative. If you see an issue that you think is interesting and want to give it a try, just do it. If no one else has volunteered to take it, then write a comment saying you want it and go for it. :)

I just came across this [tweet](https://mobile.twitter.com/brandontroberts/status/1113528617760436225) by @brandonroberts who, together with @JWO719, with talk about how to contribute to NgRx and RxJS. It will be worth taking a look.

**Comment by dance-cmdr** [comment]
Thanks mate, really appreciate your answer!

I think this issue could make for a good conversation point to pin a few good Contributor tips and useful links.

Missed the live but I'm watching the YouTube video recoding https://www.youtube.com/watch?v=ug0c1tUegm4

**Comment by benlesh** [comment]
This is a pretty old issue, and it's been inactive for some time. Closing it. We should look at the contributor's guide again soon, but it's not a priority given everything else that needs done.
