### ISSUE TITLE
how to get all current (active) subscriptions

### ISSUE THREAD

**Issue by alanhg** [ReactiveX/rxjs#4679]
Is it possible to get all the "active" subscriptions without storing them manually?

I'd like to unsubscribe all of the "active" subscriptions 
---
* StackOverflow:https://stackoverflow.com/questions/47040664/rxjs-get-all-current-active-subscriptions

**Comment by kwonoj** [comment]
SO answer is describing in detail, you can manage via parent subscription or other ways. Observable itself doesn't expose to control it's subscriptions. Not sure what active means, but general recommended pattern is let subscription auto unsubscribe (i.e using limiter like take, takeUntil..) that you don't need to care about unsubscribe explicitly.
