### ISSUE TITLE
some example of docs can't not work, that is terrible to learners

### ISSUE THREAD

**Issue by ishowman** [ReactiveX/rxjs#4680]
### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [ ] documentation needs clarification
- [x] error(s) in example
- [ ] needs example

### Description Of The Issue
the code of [example](https://rxjs-dev.firebaseapp.com/api/index/class/Observable#cancel-a-subscription) will throw errors no matter at local or the stackblitz.There are many similar errors 
where using Rx.
Please fix them, it's really hard & terrible for learners.

**Comment by dzhavat** [comment]
Thanks for reporting it. A lot of these errors have already been fixed but will become live on the next release.

**Comment by ishowman** [comment]
@dzhavat Thanks.

**Comment by JWO719** [comment]
Thanks for the feedback. For now I will close this issue due to all the work that is already put into the examples. If you notice any additional issues after the next release, I would really appreciate if you reopen this issue and let us know about it. Thanks!
