### ISSUE TITLE
Remove repeated "runtime" code from global output.

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#469]
Currently the ES6 -> ES5 transpilation process is putting class assertion functions inline with each module file. We should get rid of that so those class related functions are only defined once.

cc/ @jeffbcross @vsavkin

**Comment by kwonoj** [comment]
I assume this can be closed by we're moving away from babel, what do you think? @blesh

**Comment by blesh** [comment]
I agree.
