### ISSUE TITLE
PausableBehaviorSubject or extending of BehaviorSubject

### ISSUE THREAD

**Issue by Yizhachok** [ReactiveX/rxjs#4692]
## Feature Request

**Is your feature request related to a problem? Please describe.**
I have protected route in Angular and I use BehaviorSubject to check if user authenticated or not.
After app is loaded and started I has user auth token for requests but I don't know if it usable or not.

Expected flow | Current flow
------------ | -------------
App init | App init
Send request to check token validity and pause BehaviorSubject at this time | Send request to check token validity
App route protection wait for paused BehaviorSubject | App route protection got initial value from BehaviorSubject (default auth value is false) and redirect to sign in page
Got final auth result and resume BehaviorSubject | Got final auth result and push it to BehaviorSubject
App route protection make needed actions based on result from BehaviorSubject | 

**Describe the solution you'd like**
```javascript
const authSubject = new PausableBehaviorSubject<boolean>(false);
authSubject.pause();
checkIfUserTokenIsValid(valid => {
    authSubject.next(valid);
    // Can be also flag resumeOnNext or we can resume manually
    authSubject.resume();
});
```
I think this can be added as extension to existing `BehaviorSubject`. I have implemented for my project such class `class PausableBehaviorSubject<T> extends BehaviorSubject<T>` as temp solution but `private _value: T` a little bit unuseful in `BehaviorSubject` and it can be `protected`.
Here is my suggestion how to modify existing `BehaviorSubject` to fit requirements:
```javascript
export class BehaviorSubject<T> extends Subject<T> {

  // NEW CODE
  private _paused: boolean = false;
  resumeOnNext: boolean = true;

  get paused() {
    return this._paused;
  }

  pause() {
    this._paused = true;
  }

  resume() {
    if (this._paused) {
      this._paused = false;
      super.next(this._value);
    }
  }
  // NEW CODE END

  next(value: T): void { // MODIFIED METHOD
    this._value = value;
    if (!this._paused) {
      super.next(value);
    }
    else if (this.resumeOnNext) {
      this.resume();
    }
  }

  constructor(private _value: T) {
    super();
  }

  get value(): T {
    return this.getValue();
  }

  /** @deprecated This is an internal implementation detail, do not use. */
  _subscribe(subscriber: Subscriber<T>): Subscription {
    const subscription = super._subscribe(subscriber);
    if (subscription && !(<SubscriptionLike>subscription).closed && !this._paused) { // Modified expresion
      subscriber.next(this._value);
    }
    return subscription;
  }

  getValue(): T {
    if (this.hasError) {
      throw this.thrownError;
    } else if (this.closed) {
      throw new ObjectUnsubscribedError();
    } else {
      return this._value;
    }
  }
}
```

**Describe alternatives you've considered**
```javascript
const
    subject = new Subject<boolean>(),
    behaviorSubject = new BehaviorSubject<number>(1);
setInterval(() => behaviorSubject.next(behaviorSubject.getValue() + 1), 2000);
subject
    .pipe(switchMap(paused => paused ? NEVER : behaviorSubject))
    .subscribe(num => console.log(num));
// Pause
subject.next(true);
// Resume
subject.next(false);
```

**Comment by benlesh** [comment]
Given the lack of other inquiries about this, I'm going to close the issue. A user-land implementation/library is welcome, and if it becomes popular enough we can explore including it in the core library. We need to be mindful of what we add, because that's more for us to maintain.
