### ISSUE TITLE
Performance of arithmetic Operations

### ISSUE THREAD

**Issue by Traxstar** [ReactiveX/rxjs#4707]
Hey everybody, 

i am facing some problems comparing some math operations between using RxJS and just using the default JavaScript capabilities. 

Here is what i am trying to do: 
I am trying to compare the performance of the reactive approach compared with an imperative JavaScript solution. Therefor i've created some tests and measure the execution time of them in both. 
Note: Both are using the same functions. 

I've created several examples that are executing in a similiar time. But one of them just needs much less time using the reactive approach, and i can't figure out why. 
I would assume that under the hood there is something happening that i do not understand. 
I was able to find the line that causes the problem. This is shown here

**Code to reproduce:**
`result = result - (Math.rand() * ("astring".length / "anotherstring".length));`

Running this code just imperative for a few strings leads to an execution time of about 8ms. Running the same code reactive leads to a time of about 1ms. 

I just can't understand how this is possible to get such a big difference in time. Any ideas? 

**RxJS version:**
6.4.0

**Expected behavior:**
Both run in similar times. 

**Actual behavior:**
The reactive approach runs much faster. 

Thanks for any help!

**Comment by kwonoj** [comment]
I think this is more appropriate q to stackoverflow. Meanwhile also, we can't comment anything without seeing actual code what you tried to do measure. _

**Comment by kwonoj** [comment]
I'm closing this issue for now due to lacks of detail to determine furtuer.
