### ISSUE TITLE
rxjs | websocket and WebSocketCtor

### ISSUE THREAD

**Issue by matth-c3** [ReactiveX/rxjs#4709]
We primarily use GitHub as an issue tracker; for usage and support questions, please check out these resources below. Thanks! 

---
* StackOverflow: https://stackoverflow.com/questions/tagged/rxjs using the tag `rxjs`
* Also have a look at the readme for more information, possibly can have some answers already:
- https://github.com/ReactiveX/rxjs/blob/master/README.md
- https://github.com/ReactiveX/rxjs/blob/master/MIGRATION.md
- https://github.com/ReactiveX/rxjs/blob/master/doc/pipeable-operators.md

Hello, 

Would it be possible to have more information on https://rxjs-dev.firebaseapp.com/api/webSocket/webSocket , WebSocketCtor and how to specify an SSL/TLS certificats ? 

Thanks

**Comment by kwonoj** [comment]
maybe I'm lacking knowledge but how do you do with raw websockets?

**Comment by matth-c3** [comment]
Hello @kwonoj , 

Thanks for your quick answer, usually you would use an HTTPS Agent to set the `key`, `cert` or `pfx` parameter like in this websocket test [here](https://github.com/websockets/ws/blob/14d9088391ac4495d04e64d76c3b83d4e75f80e2/test/websocket.test.js#L1670-L1687)

Thanks.

**Comment by kwonoj** [comment]
but that's node specific implementation, right? how does it work on browsers?

**Comment by matth-c3** [comment]
Hello @kwonoj , yes I use it with node on server side.

**Comment by kwonoj** [comment]
As we have to design our api should work across any platform, we don't currently expose 3rd-party specific api exposure yet. I.e afaik node doesn't provide ws by default, and relies on module as you've shared - and we are currently not deeply considering to expose module-specific paths.

**Comment by matth-c3** [comment]
Hello @kwonoj , 

ok no problem.  Thanks for looking at it. I will close the issue.
