### ISSUE TITLE
[feat] `rxjs/concat` : pass last value of previous Observable to the next one

### ISSUE THREAD

**Issue by NeekSandhu** [ReactiveX/rxjs#4711]
## Problem

The "master" subscriber needs values emitted by outer observable **"as they happen"**; and when it completes, should seamlessly switch over to the next observable in the chain. (the next in the chain also needs the last emitted value of prev/outer obs to compute its own result)

## Tried and failed

I tried using `concat` from `rxjs` but that doesn't pass the last value emitted by previous observable to the next one in chain.

I tried using `concatMap` from `rxjs/operators` but that "holds up" the emission until outer and inner observables are done. (I reckon its only good for preserving the order)

## Solution

```ts
type ObservableGenerator<T> = Observable<T> | ((v: T) => Observable<T>)

function chain<T>(seed: Observable<T>, ...obsGenerators: Array<ObservableGenerator<T>>) {
  return new Observable<T>(masterSubscriber => {
    let lastValueFromPrev: T
    let childSubscription: Subscription

    const switchTo = (obs: Observable<T>) => {
      childSubscription = obs.subscribe({
        next: v => {
          lastValueFromPrev = v
          masterSubscriber.next(v)
        },
        error: masterSubscriber.error,
        complete: () => {
          childSubscription.unsubscribe()
          const next = obsGenerators.shift()
          if(!next) {
            masterSubscriber.complete()
          } else {
            switchTo(typeof next === 'function' ? next(lastValueFromPrev) : next)
          }
        }
      })
    }

    switchTo(seed)

    return () => {
      childSubscription.unsubscribe()
    }
  })
}
```

And then it can be used like so:

_**EDIT:** Example removed._

Much better example below: https://github.com/ReactiveX/rxjs/issues/4711#issuecomment-483080247

**Comment by xRoker** [comment]
From your description it looks like what you want is:
```js
const a$ = of(1, 2, 3, 4, 5);
const b$ = of(6, 7);
const lastA$ = a$.pipe(takeLast(1));
const result$ = lastA$.pipe(concat(b$));
```
The result would be 5, 6, 7.

**Comment by NeekSandhu** [comment]
The use case isn't as simple as "concating" two synchronous streams of data, one after another. That too being quite deterministic.

Instead, its "chaining" two async streams where the value from each observable in chain depends upon the **runtime computed value of the previous one**. As the title describes.

Also each observable in chain must run to "completion" before moving on to the next one. However the root subsciber (`$result` in your example) shouldn't have to wait for all observables in chain to "complete", instead it should be fed right from the get go.

**Comment by NeekSandhu** [comment]
Here's a much better example:

Imagine we have an asynchronous image rendering pipeline. There are multiple filters/shaders in the said pipeline and each of them takes `ImageData` from the preceding filter/shader, transforms it, and passes it on to the next one.

Here's the tricky part; the user must see the process as it happens; live. Instead of just the final output. That way he can cancel the render midway if he notices some rendering artifacts during the render.

Each filter/shader can only process 128 pixel block at a time. Every 
 `requestAnimationFrame` cycle it'll `.next(...)` what it has computed so far, and then on to the next 128 pixel block. Accumulate, emit and repeat. `.complete()` when it is done.

Here's what it'll look like:

```ts

// each of the filters below will compute 128x128px block at a time
// computed block is "reduced" with existing ImageData
// upon every `requestAnimationFrame` cycle, filters will `.next` what they have

const removeHighlights: Observable<ImageData> = (imageData: ImageData) => { /* impl */ }
const removeShadows: Observable<ImageData> = (imageData: ImageData) => { /* impl */ }
const removeGlare: Observable<ImageData> = (imageData: ImageData) => { /* impl */ }
const applyGammaShift: Observable<ImageData> = (imageData: ImageData) => { /* impl */ }
const applyAntiAliasing: Observable<ImageData> = (imageData: ImageData) => { /* impl */ }
const applyPostFx: Observable<ImageData> = (imageData: ImageData) => { /* impl */ }

this.imageData$ = chain(
	this.imageInput$.pipe(map(this.convertToImageData) ),
    removeHighlights,
    removeShadows,
    removeGlare,
    applyGammaShift,
    applyAntiAliasing,
    applyPostFx
)

// called every time each filter process a 128x128 block (live preview that is)
this.imageData$.subscribe(this.ctx.drawImage)
```

**Comment by NeekSandhu** [comment]
The example above has been replicated over at StackBlitz. I hope it communicates what I'm trying to achieve.

https://stackblitz.com/edit/rxjs-ruj1m3

**Comment by kwonoj** [comment]
Please share some details

1. Does current implementation you shared in example doesn't work? or it is working but need some core's internal logic to achieve its feature? (doesn't look like so, but confirming)

2. What's main motivation this need to be in core's api surface but can't be in user-level implementation?

As our guideline recommends (https://github.com/ReactiveX/rxjs/blob/master/doc/operator-creation.md#publish-your-operator-as-a-separate-library), we do strongly ask to implement operator / or creating methods in a user level separate library and only consider to discuss to implement in core api surface if 1. feature can't be implemented without touch internals of core 2. should be impossible or non-trivial to compose via existing operator / creation method in core api surfce 3. should be widely used for general purpose.

from v5 to v6 and beyond, core team's general approach is suppress api surface as much and even considering remove some of specialized (or barely used) operators, also trying to encourage additional operators to live in user land ecosystem. (related: https://github.com/ReactiveX/rxjs/issues/4710)

**Comment by NeekSandhu** [comment]
The example I shared works as intended; just not with what's available in the core library.

The above example would work seamlessly, without me defining custom operators if only rxjs team would be happy to change the signature of `rxjs/concat` from:

```ts
concat<R>(...observables: (ObservableInput<any> | SchedulerLike)[]): Observable<R>
```

to

```ts
type ObservableGenerator<T> = Observable<T> | ((valueFromPrev: T) => Observable<T>)

concat<R>(seed: ObservableInput<any>, ...observables: (ObservableGenerator<R> | SchedulerLike)[]): Observable<R>
```

**Comment by kwonoj** [comment]
I don't believe we are considering to accept change signature of `concat` as suggested.

**Comment by NeekSandhu** [comment]
Mind sharing what's the stopping vector?

It is still backward compatible and doesn't break any existing implementations.

FTFY:

```ts
type ObservableGenerator<T> = ObservableInput<T> | ((valueFromPrev: T) => Observable<T>)
```

**Comment by kwonoj** [comment]
> core team's general approach is suppress api surface as much and even considering remove some of specialized (or barely used) operators, also trying to encourage additional operators to live in user land ecosystem

this also includes making polymorphic behavior of opeartor as well. Unless we are strongly believe it's wide usage across library users, we don't consider it. (Check v7 / v8's design as well, we are removing lot of polymorphic behavior from operators).

As mentioned above, we recommends to create userland operator first - that'll allows to see how frequent it's being used across users to determine we will include in core or not. Adding new things in core is easy, but after that make changes (breaking) or deprecating is extremely hard so we are trying to carefully evaluate what to be added in core.

**Comment by NeekSandhu** [comment]
Makes sense. Thanks for the explanation.
