### ISSUE TITLE
durationSelector documentation should mention emit and completion cases

### ISSUE THREAD

**Issue by 101100** [ReactiveX/rxjs#4716]
### Documentation Related To Component:

`audit`, but also any operator that takes a `durationSelector` like `debounce`, `buffer`, `window`, or `throttle`.

### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [x] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue

It is not clear from the documentation that a stream can complete _or_ emit a value to signal the end of a duration.  In addition, when looking at the tests for `audit`, none of the tests rely on an emitted value so it was not clear if that use case was possible.

**Comment by OlaviSau** [comment]
Hei, I want to add that audit is useful outside the durationSelector use case. That should be documented. I actually recently found that audit solves a operator PR that I recently posted.

**Comment by benlesh** [comment]
From what I can tell, this has been resolved.
