### ISSUE TITLE
unable compile with clear type, got `property 'data' does not exist on type 'T' `

### ISSUE THREAD

**Issue by SilverLeaves** [ReactiveX/rxjs#4718]
![图片](https://user-images.githubusercontent.com/31165554/56400934-05459a80-6289-11e9-810a-481389c77502.png)

``` typescript
import * as rxjs from "rxjs";
import axios from "axios"

interface res {
    data: any[],
    count: number
}

let promiseSource$ = rxjs.from(axios.get<res>("http://govapi.pinza.com.cn/newsList"))


promiseSource$.subscribe((res) => { console.log(res.data.count) })
```

**Comment by cartant** [comment]
It's working in the IDE - TypeScript is inferring the type of `data` - so the problem is most likely related to the version of TypeScript that you are using with `ts-node`, etc.

In short, this does not seem to be an issue with RxJS.
