### ISSUE TITLE
modelFromLatest creator function

### ISSUE THREAD

**Issue by SanderElias** [ReactiveX/rxjs#4721]
## Feature Request

I created a helper function,
```typescript
export function modelFromLatest<T>(modelBase: {[P in keyof T]: Observable<T[P]>}): Observable<T> {
  /** spread out the values into an array, and use combineLatest to "watch" for changes */
  return combineLatest(Object.values(modelBase)).pipe(
    map(values =>
      /** user reduce to reassemble the original structure, but then with the data */
      Object.keys(modelBase).reduce(
        (vm, key, i) => {
          vm[key] = values[i];
          return vm;
        },
        /** make sure it conforms to given types. */
        {} as T
      )
    )
  );
}
```

**Is your feature request related to a problem? Please describe.**
While creating models from diverse sources, I found myself doing a lot of:
```typescript
model$ = combineLatest([a,b,c]).pipe(
  map(([a,b,c]) => ({a,b,c}))
)
```
which is achieving the same goal. However, it's easy to make a mistake, and I had some trouble with the types. 

**Describe the solution you'd like**
Add the above function, (or something that suits the project)
Or integrate this functionality into combineLatest?

**Comment by kwonoj** [comment]
Thanks for the suggestion, I'm going to close this issue as same reason of https://github.com/ReactiveX/rxjs/issues/4711 . In short, we do strongly recommend to create operator as user level module (https://github.com/ReactiveX/rxjs/blob/master/doc/operator-creation.md#publish-your-operator-as-a-separate-library) and evaluate to include in core based on its usage.
