### ISSUE TITLE
deprecation warning when using of as intended

### ISSUE THREAD

**Issue by evertbouw** [ReactiveX/rxjs#4723]
## Bug Report

**Current Behavior**

I've got the tslint rule `"deprecation": true` enabled and it is now throwing warnings when using `of` without a scheduler.

**Reproduction**
```ts
import { of } from "rxjs"

of(4) // of is deprecated: use {@link scheduled} instead `scheduled([a, b, c], scheduler)` (deprecation)
```

**Expected behavior**
No warning

**Environment**
- Runtime: Node v11.13.0
- RxJS version: 6.5.1
- tslint version 5.16.0

**Comment by dmytro-gokun** [comment]
As described here, only the version of "of" which accepts a scheduler should be deprecated: https://github.com/ReactiveX/rxjs/pull/4595 So, it's definitely a bug.

**Comment by evertbouw** [comment]
I think these two lines should be moved to the bottom of the declaration file

```ts
/** @deprecated use {@link scheduled} instead `scheduled([a, b, c], scheduler)` */
export declare function of<T>(...args: (T | SchedulerLike)[]): Observable<T>;
```

**Comment by cartant** [comment]
@evertbouw Yes, they need to be placed below:

```ts
export function of<T>(...args: T[]): Observable<T>;
```

**Comment by cartant** [comment]
@evertbouw If you would like to open a PR, please let me know. Otherwise, I'll open one myself.

**Comment by evertbouw** [comment]
@cartant I can do it

**Comment by nlaplante** [comment]
I see the same problem with `startWith`

**Comment by cartant** [comment]
@nlaplante If there is a problem with `startWith` it would be better to open another issue. This one will be closed when the PR is merged. Anyway, if there is a problem with that operator's deprecations, it appears to be to be different to this issue, as the signature is [already in the correct place](https://github.com/ReactiveX/rxjs/blob/1dbbafad6abe4be5e0ff992014217c98389b300b/src/internal/operators/startWith.ts#L29-L30).

**Comment by imransilvake** [comment]
I have the same problem.

**Comment by imransilvake** [comment]
> I see the same problem with `startWith`

I had the probem with `startWith` when I was using `startWith(void 0)`. I changed it to `startWith(0)` and now it works without showing any deprecation warning.

**Comment by cartant** [comment]
@imransilvake As mentioned above, please open a new issue and fill out the issue template.

**Comment by yogeshgadge** [comment]
@nlaplante  Temporary workaround - use `startWith`  as below:-

```
startWith<string>(null)
```

Basically remove ambiguity. I would be great if we don;t have to do this though.

**Comment by jtbitt** [comment]
Has this been fixed? The part with the 'of' function? It's giving me the worst time when trying to implement it with my ngrx

`catchError(error => of({type: ErrorActionTypes.HANDLE_STATUS, payload: {status: error.status}}))`

**Comment by evertbouw** [comment]
@jtbitt the PR is still open. Should be fixed in the next release I think. Personally I disabled the tslint rule, you can also downgrade to the previous version.

**Comment by jtbitt** [comment]
@evertbouw Thanks

**Comment by dmytro-gokun** [comment]
Well, I might sound like a dick here. But ... it's a minor bug, that what fixed immediately after it's been spotted by (at least) hundreds ppl. 2 weeks passes and it's not released. I know, I know. Just  a bit frustrating.

**Comment by jdussouillez** [comment]
Related to https://github.com/palantir/tslint/issues/4676
