### ISSUE TITLE
clicks.debounceTime is not a function

### ISSUE THREAD

**Issue by hold-baby** [ReactiveX/rxjs#4728]
## Bug Report

**Current Behavior**
clicks.debounceTime is not a function

```js
import Rx from 'rx'

var clicks = Rx.Observable.fromEvent(document, 'click');
var result = clicks.debounceTime(1000);
result.subscribe(x => console.log(x));
```

**Environment**
- RxJS version: 6.5.1

**Comment by cartant** [comment]
Prototype-patching operators were removed in v6. See the [migration docs](https://github.com/ReactiveX/rxjs/blob/master/docs_app/content/guide/v6/migration.md).
