### ISSUE TITLE
fromFetch throws AbortError

### ISSUE THREAD

**Issue by strout** [ReactiveX/rxjs#4739]
## Bug Report

**Current Behavior**
`fromFetch` seems to fail with `AbortError` when I would expect it to succeed.

**Reproduction**
- REPL or Repo link:
[Here's an example using fromFetch(...) and from(fetch(...)) that I would expect to have the same result.](https://codepen.io/strout/pen/jRdrQq)

This code throws an AbortError:

```js
fromFetch('https://jsonplaceholder.typicode.com/todos/1')
  .pipe(switchMap(resp => resp.json()))
  .subscribe(json => console.log(json));
```

**Expected behavior**
The snippit above should complete and log the response to the console.

**Environment**
- Runtime: Chrome 74, Firefox 66
- RxJS version: 6.5.1

**Possible Solution**
In the definition of `fromFetch()`, don't call `controller.abort()` if it has already emitted a value. Perhaps set a flag (reuse/rename the `unsubscribed` flag) before calling `subscriber.next`.

**Comment by felixfbecker** [comment]
@cartant how does this happen? Shouldn't the AbortError be ignored if the Observable unsubscribed?

**Comment by cartant** [comment]
It aborts the promise returned by `resp.json()`, IIRC.

**Comment by felixfbecker** [comment]
So in that code sample provided in the issue description, why would that matter?

**Comment by cartant** [comment]
Try the StackBlitz and you'll see. Sometimes it works and sometimes it fails. Bottom line is that `abort` should not be called upon the normal unsubscription that follows completion. See also https://github.com/ReactiveX/rxjs/issues/4744.
