### ISSUE TITLE
Possible to build/release an "evergreen" version?

### ISSUE THREAD

**Issue by verydanny** [ReactiveX/rxjs#4747]
**Is it possible to have an `rxjs` version that supports newer ES features?**

My app currently has 3 bundles being shipped in production:

- Legacy
  - IE 11 support
  - Many poly-fills
  - Slow crappy JS
- LTS
  - Edge >= 12 <= 15, Firefox >= 40 <= 59, Chrome >= 40 <= 60, Opera <= 47, etc
- Evergreen
  - All browsers that support ES modules, and therefore async/await, etc.

I was wondering if it's possible to have a version that supports newer ES6/7 code. Or is it possible to build an evergreen package or somehow incorporate the latest `rxjs` code into a build process that creates multiple packages?

**Comment by kwonoj** [comment]
rxjs itself does not have lot of polyfilles required to support old browsers, only requires few of them and we do already provide cjs / esm / esm5 (cjs have esm export) which would serve most usecases (cjs for supporting majority of browser env, where esm nearly do not transpile but target latest as much).

Or in worst case though it is not recommended, rxjs ships src of code itself so you can configure build target as you want. But I don't think that's necessary.

esm: https://unpkg.com/rxjs@6.5.1/_esm2015/
esm5: https://unpkg.com/rxjs@6.5.1/_esm5/
cjs: https://unpkg.com/rxjs@6.5.1/
