### ISSUE TITLE
Error Creating Observable From MediaQueryList

### ISSUE THREAD

**Issue by daniel-nagy** [ReactiveX/rxjs#4749]
## Bug Report

**Current Behavior**
Creating an Observable from a `MediaQueryList` throws an Error in Safari.

> The new version of the MediaQueryList interface inherits methods from its parent interface, EventTarget.

In Safari `MediaQueryList` does not inherit from `EventTarget`.

The problem is this line of code, which calls `addListener` with the wrong arity for a `MediaQueryList`.
https://github.com/ReactiveX/rxjs/blob/cd5895d0e44008714ccd702af959ae40c8262f16/src/internal/observable/fromEvent.ts#L222

**Reproduction**
- REPL or Repo link:
(you can use https://stackblitz.com/ to create one to attach here)

```js
const mediaQuery = matchMedia('screen and (min-width: 768px)');
const mediaObserver = fromEvent<MediaQueryListEvent>(mediaQuery, 'change');
```

**Expected behavior**
Should correctly create an observable from the `MediaQueryList` **change** event.

**Environment**
- Runtime: Safari 12 (latest)
- RxJS version: 6.3.3

**Possible Solution**
Maybe check the `length` property before calling `addListener`? Another option might be to make the event name option.

```ts
// In Safari MediaQueryList.addListener.length is 0, which is wrong but less than 2
// In Chrome and FireFox MediaQueryList.addListener.length is 1, which is right
// In Node EventEmitter.addListener.length is 2
// 🤷‍♂️
if (sourceObj.addListener.length < 2) {
  sourceObj.addListener(handler as NodeEventHandler);
} else {
  sourceObj.addListener(eventName, handler as NodeEventHandler);
}

// or
if (!eventName) {
  sourceObj.addListener(handler as NodeEventHandler);
}

// then
const mediaObserver = fromEvent<MediaQueryListEvent>(mediaQuery);
```

**Comment by kwonoj** [comment]
So per https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList, it's safari & IE behavior doesn't inherit eventTarget, right? meanwhile `fromEvent` explicitly require *eventTarget-like* object to be passed. 

I feel in this case using `fromEventPattern` seems more feasible, instead of trying to add polymorphic behavior into `fromEvent` - afaik we don't expect to have known list of object to work in fromEvent but only accepts satisfying object, and recommend fromEventPattern for other object.

**Comment by daniel-nagy** [comment]
Didn't know about `fromEventPattern`. I'm ok with this.

```ts
const mediaObserver = fromEventPattern<MediaQueryListEvent>(
  mediaQuery.addListener.bind(mediaQuery),
  mediaQuery.removeListener.bind(mediaQuery)
);
```

Thanks @kwonoj!
