### ISSUE TITLE
Default observables like EMPTY

### ISSUE THREAD

**Issue by bovandersteene** [ReactiveX/rxjs#4753]
## Feature Request

It would be nice if we have some default observables for default values like false, true or undefined. This would make our code more readable.
I've already seen in a lot of project that you have something like 
```
return of(false);
return of(true);
return of(undefined);
```
it would be nicer if we had something like
```
return TRUE;
return FALSE;
return UNDEFINED;
```

I agree that you can define it yourselves but it would be nice if these are defined on a global place.

**Describe the solution you'd like**
```
const FALSE = of(false);
const TRUE = of(false);
const UNDEFINED = of(undefined);
```

**Additional context**

**Comment by kwonoj** [comment]
As already describes this can be defined trivially, and can be created as user level module if needed. Empty / never is special kind of observable also being used by some operators, while this is mostly defining constant.
