### ISSUE TITLE
Duplicate pipeable-operators.md

### ISSUE THREAD

**Issue by martinsik** [ReactiveX/rxjs#4754]
### Description Of The Issue

I've noticed there's `pipeable-operators.md` file twice in this repo that are almost the same:

- [docs_app/content/guide/v6/pipeable-operators.md](https://github.com/ReactiveX/rxjs/blob/master/docs_app/content/guide/v6/pipeable-operators.md)
- [doc/pipeable-operators.md](https://github.com/ReactiveX/rxjs/blob/master/doc/pipeable-operators.md)

 I'm not sure however which one is the correct one. Maybe the second one because it was updated more recently.

**Comment by martinsik** [comment]
I see there are actually much more duplicate docs, so this is probably in process of moving from `doc/` to `docs_app/`.

**Comment by JWO719** [comment]
For further clarification: you are absolutely right. There are some duplicates in the doc folder, which used to be used for the old docs.
