### ISSUE TITLE
Rxjs ^6.5 silent deprecation of value property

### ISSUE THREAD

**Issue by rebyul** [ReactiveX/rxjs#4758]
## Bug Report

**Current Behavior**
There 'value' property that was on the action object passed out of an observable has been removed and is causing redux to reject actions without a type property. I have a system where each redux action is a class and created via constructors. For this to work the following middleware is needed for redux to not throw an exception complaining about async actions.
Actions returned from epics passed on their destructed value property which had the 'type' property that redux expects. Since the 6.5 update, value isn't there which breaks the webapp.
Also, the returned actions are returning as non-scalar values, which I assume is causing them to lose their 'value' property. However the epics haven't changed.

```js
// Custom middleware that allows use of constructors in action creators
const constructorActionDestructingMiddleware = (api: MiddlewareAPI) => (
  next: Dispatch
) => (action: AnyAction) => {
  console.log(action);
  next(action && action._isScalar ? { ...action.value } : { ...action });
};
```
The custom middleware is loaded as the first middleware before routes and epic middleware.

**Expected behavior**
Documentation in the release logs that the value property has been deprecated/moved, or the value property to come back.

**Environment**
- Runtime: [e.g. Node v${x}, Chrome v${x}] Node v10
- RxJS version: ^6.5
- (If bug is related) Loader, build configuration: [e.g webpack, angular-cli version, config]

**Possible Solution**
Return the value property to the actions returned from the observable

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

logged actions in middleware rxjs^6.4
![rxjs](https://user-images.githubusercontent.com/2460325/57205481-0d386500-7013-11e9-930a-afa3237867a3.png)

logged actions in middleware rxjs6.5
![rxjs6 5](https://user-images.githubusercontent.com/2460325/57205594-c139f000-7013-11e9-8620-3e6e8c01e587.PNG)

**Comment by cartant** [comment]
IMO, you appear to have relied upon internal implementation details and there is no requirement for them to be documented or for them to remain unchanged between minor versions.

**Comment by kwonoj** [comment]
@cartant is correct. Please do not expect non-public interface to follow semver.

**Comment by kwonoj** [comment]
additionally, `_isScalar` is also non-public and should not be used (https://github.com/ReactiveX/rxjs/blob/master/src/internal/Observable.ts#L21-L22) though it's types marked as public, only due to lacks of `internal` scope in typescript.
