### ISSUE TITLE
Missing doOn* operators

### ISSUE THREAD

**Issue by luisgabriel** [ReactiveX/RxJS#476]
It seems that [doOnNext](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/doonnext.md), [doOnError](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/doonerror.md) and [doOnCompleted](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/dooncompleted.md) are not implemented here yet.

Is it intentional or should we add them?

**Comment by staltz** [comment]
`do(onNext, () => {}, () => {})`

`do(() => {}, onError, () => {})`

`do(() => {}, () => {}, onCompleted)`

**Comment by mattpodwysocki** [comment]
@staltz that's not quite right if you look at the implementation: https://github.com/Reactive-Extensions/RxJS/blob/master/src/core/perf/operators/tap.js#L55-L86

Since you're lacking the default behavior of the `do` semantics as well as lacking the `thisArg`

**Comment by blesh** [comment]
@mattpodwysocki I'd personally like to do away with `thisArg` in the library, since we're only targeting browsers that have `.bind()` now, and ES7 function bind is coming.

**Comment by mattpodwysocki** [comment]
@blesh that's fine but Function#bind is very slow and not likely to be much faster in the future, whereas the `thisArg` is rather performant in comparison.

**Comment by blesh** [comment]
@staltz @luisgabriel ... simpler (and perhaps more explicit) in ES6:

```js
obs.do({ error(err) { /* stuff */ } })
```

**Comment by blesh** [comment]
Related, though, we should make sure `do` handles observers and `null`/`undefined` values passed to it.

**Comment by IanVS** [comment]
The migration guide does not mention the removal of the convenience functions `doOnNext`, `doOnError`, and `doOnCompleted`.  Doesn't seem worth creating a new issue, but I thought I'd mention it here because it tripped me up a bit in my migration from 4.

**Comment by Karasuni** [comment]
The documentation http://reactivex.io/documentation/operators/do.html#collapseRxJS still mentions `doOnNext`, `doOnError` and `doOnCompleted` as part of `rx.js`.
