### ISSUE TITLE
fromFetch throws error for resolved request

### ISSUE THREAD

**Issue by NettaB** [ReactiveX/rxjs#4761]
## Bug Report

**Current Behavior**
fromFetch does not return results from successful requests, but throws error instead

**Reproduction**
this repo uses documentation example:
https://stackblitz.com/edit/rxjs-fromfetch?file=index.ts

**Expected behavior**
observable should emit response

**Comment by cartant** [comment]
This should have been fixed in https://github.com/ReactiveX/rxjs/pull/4742 but, AFAICT, a release that includes that PR's change has not been published.

**Comment by cartant** [comment]
Closing this 'cause it should be resolved in 6.5.2.
