### ISSUE TITLE
AJAX CORS Error PUT and POST

### ISSUE THREAD

**Issue by tuckerjt07** [ReactiveX/rxjs#4778]
## Bug Report

**Current Behavior**
AJAX PUT and POST requests both submit a successful OPTIONS request but then throw an error ```Access to XMLHttpRequest at 'http://localhost:8001/issue' from origin 'http://localhost:4200' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.``` before submitting the subsequent PUT or POST request. The API has CORS configures and is working with both the GET and the Angular HTTPClient PUT and POST.

**Reproduction**
- REPL or Repo link:
(you can use https://stackblitz.com/ to create one to attach here)

I've tried with the createXHR property both set and unset.
```js
ajax({
                        createXHR: function () {
                            return new XMLHttpRequest();
                        },
                        url: 'http://localhost:8001/issue',
                        crossDomain: true,
                        withCredentials: false,
                        method: 'PUT',
                        body: x,
                        })
                        .subscribe((result) => {
                            console.log(result);
                        })
```

**Expected behavior**
I expect for the PUT and POST requests to be submitted open successful completion of the OPTIONS request.
![image](https://user-images.githubusercontent.com/8493561/57594996-5b180600-7508-11e9-9abc-9f829b707797.png)

**Environment**
- Runtime: [e.g. Node v${x}, Chrome v${x}]
- RxJS version:
- (If bug is related) Loader, build configuration: [e.g webpack, angular-cli version, config]

**Possible Solution**

**Additional context/Screens
hots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

Adding screenshots for clarity: 
![image](https://user-images.githubusercontent.com/8493561/57594988-4dfb1700-7508-11e9-990c-a1c93c652f5f.png)
![image](https://user-images.githubusercontent.com/8493561/57595001-60755080-7508-11e9-9090-bdef0b34b5df.png)

**Comment by cartant** [comment]
AFAICT, there is zero information provided in this issue.

**Comment by tuckerjt07** [comment]
@cartant the template wigged out and reverted back to its unedited state on submit. That's why the edit went through so quickly I'd already typed it all once before. No clue why it decided to do that.

**Comment by benlesh** [comment]
I don't think this is an issue any longer in version 7.
