### ISSUE TITLE
ObservedValueOf docs incorrect

### ISSUE THREAD

**Issue by arielshaqed** [ReactiveX/rxjs#4794]
### Documentation Related To Component:

ObservedValueOf

### Please check those that apply

- [x] typo
- [x] documentation doesn't exist
- [x] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue

Documentation is incorrect, it says
```ts
type ObservedValueOf<O> = O;
```
but actually it is the `infer`red type of an `Observable`, per https://github.com/reactivex/rxjs/blob/master/src/internal/types.ts#L101

I'd be happy to fix but I couldn't find the source for this documentation.

**Comment by benlesh** [comment]
This appears to have been fixed.

![image](https://user-images.githubusercontent.com/1540597/119892773-29601500-bf00-11eb-99a7-791ad6a94924.png)
