### ISSUE TITLE
Source code of shareReplay could potentially get improved

### ISSUE THREAD

**Issue by BioPhoton** [ReactiveX/rxjs#4795]
## Bug Report

**Current Behavior**
From looking in the source code the question arose in me that the source code of shareReplay could be refactored. 

Here my view:
Technically sahreReplay should look something like that:

```typescript
export function shareReplay<T>(config: ShareReplayConfig): MonoTypeOperatorFunction<T> {
  if(config.refCount === false) {
    return (source: Observable<T>) => refCount()(multicast(replaySubjectFactory(config))(source)) as Observable<T>;
  }
  else {
    return (source: Observable<T>) => connectSourceToSubject(source, replaySubjectFactory(config))) as Observable<T>;
  }
}
```  

ShareReplay, in my opinion, should just reuse the `multicast` operator with a subject factory that returns a `ReplaySubject` that is configured over the config param and shared over `refCount`.

Furthermore I question the refCount option in shareReplay for 3 reasons:
- It is inconsistent because share, a more primitive operator uses always refCount and shareReplay which should be a more specific form of share cover this option.
- In the source, there is documented (This ability to replay values on subscription is what differentiates `share` and `shareReplay`.)[https://github.com/ReactiveX/rxjs/blob/master/src/internal/operators/shareReplay.ts#L27]
- It would be a more predictable behavior for the lib consumer that already know share.

**Expected behavior**
A clear and concise naming and behavior of operators and methods.

**Possible Solution**
I was trying different approaches. But I always fail at least 4 unit tests with my implementation.
This was my final approach:

```typescript
export class ShareReplayOperator<T, R> implements Operator<T, R> {

  subjectFactory: () => ReplaySubject<T>;

  constructor({
                bufferSize = Number.POSITIVE_INFINITY,
                windowTime = Number.POSITIVE_INFINITY,
                refCount: useRefCount,
                scheduler
              }: ShareReplayConfig) {
    this.subjectFactory = getReplaySubjectFactory(bufferSize, windowTime, scheduler)
  }

  call(subscriber: Subscriber<R>, source: any): any {
    const subject = this.subjectFactory();
    const subscription = subject.subscribe(subscriber as any);
    subscription.add(source.subscribe(subject));
    return subscription;
  }
}
```  

If my opinion is correct I would love to fix the remaining issues in my PR and push it.
If not I would be nice to correct my point of view!

**Comment by cartant** [comment]
I don't believe that it's possible to use `multicast` without changes to what `multicast` passes to the subject factory. The key test that you will not be able to have pass will be [this one](https://github.com/ReactiveX/rxjs/blob/6.5.2/spec/operators/shareReplay-spec.ts#L111-L126), IMO.

Note that when the source completes, any subscribers also complete and unsubscribe, dropping the reference count to zero. However, subsequent subscribers subscribe to the *same* `ReplaySubject` that replays the notifications received by the initial - now unsubscribed - subscribers.

The `refCount` property exists for historical reasons. For more information, see [this PR](https://github.com/ReactiveX/rxjs/pull/4059) - and the issues linked therein - and [this article](https://blog.angularindepth.com/rxjs-whats-changed-with-sharereplay-65c098843e95).

**Comment by BioPhoton** [comment]
I close this issue as it is correctly answered and the question is clearly not relevant
