### ISSUE TITLE
[docs]: The operator `multicast` is missing description and example

### ISSUE THREAD

**Issue by BioPhoton** [ReactiveX/rxjs#4798]
### Please check those that apply

- [ ] typo
- [x] documentation doesn't exist
- [x] documentation needs clarification
- [ ] error(s) in example
- [x] needs example

### Description Of The Issue

The description of multicast is missing. 

The current short description I not detailed enough to name all edge cases and optional params.

The example is missing. Here I would suggest examples for multiple subscriptions (overlapping and separated) and error and complete situations for:
- multicast(subject)
- multicast(subjectFactory)
- multicast(subjectFactory, selector)

Also, the marble diagram is not providing any useful information.

We might want to fix this.

**Comment by benlesh** [comment]
Multicast is deprecated and slated for removal. If anything, we probably need better docs for `share` and `connect`.
