### ISSUE TITLE
Throttle and Debounce may have been switched (again)

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#480]
I think I've implemented Throttle and Debounce backwards...

For clarification which of these is Throttle and Which is Debounce?

### A

```js
var source = hot('---^---x---x---x---x---x---x---x---------------');
var expected  =     '----x-----------x-----------x---------------';

source.somethingHere(90)
```

### B

```js
var source = hot('---^---x---x---x---x---x---x---x---------------');
var expected  =     '----------------------------x---------------';

source.somethingHere(90)
```

**Comment by paulpdaniels** [comment]
I believe `debounce` is the second one. Debounce has the cool down period (or what ever one would call it) before it will emit, so if another event comes in during that time it will reset the cool down. In the second instance since it is never firing that means each event is coming before the timer has expired.

`throttle` will only allow one event through during every period which looks like what the first one is doing.

**Comment by kwonoj** [comment]
> Debounce has the cool down period (or what ever one would call it) before it will emit, so if another   event comes in during that time it will reset the cool down

This seems similar to explanation of .net implementation of `throttle` described in https://msdn.microsoft.com/en-us/library/hh229400(v=vs.103).aspx, 
>The Throttle operator buffers an item from the sequence and wait for the time span specified by the dueTime parameter to expire. If another item is produced from the sequence before the time span expires, then that item replaces the old item in the buffer and the wait starts over. If the due time does expire before another item is produced in the sequence, them that item is observed through any subscriptions to the sequence.

which I was expected to behave when I use .net implementation.

**Comment by paulpdaniels** [comment]
@kwonoj There was a discussion about this some time ago Reactive-Extensions/RxJS, which at the time was implemented in the way you describe. It led to a great deal of confusion since those implementations counter to how the words are actually defined.

`throttle` = define a maximum number of times the event can be emitted over a period of time (1 / 100 ms).

`debounce`= enforce that a function not be called again until a certain amount of time has passed without it being called.

**Comment by kwonoj** [comment]
@paulpdaniels Thanks for clarification, I could look up those discussions - https://github.com/Reactive-Extensions/RxJS/pull/352 is this right one?

**Comment by paulpdaniels** [comment]
@kwonoj Yep! That's the one.

**Comment by trxcllnt** [comment]
@blesh shouldn't the second test look like this?

```js
var source = hot('---^---x---x---x---x---x---x---x---------------');
var expected  =     '-------------------------------x------------';

source.somethingHere(90)
```

**Comment by paulpdaniels** [comment]
@trxcllnt I think it would be at least two more dashes? The timer period needs to be at least 3 dashes since it hasn't fired during any of the previous intervals.

**Comment by trxcllnt** [comment]
@paulpdaniels my bad. I definitely left out at least one dash, assuming the debounce timeout is "three dashes." not sure about the second, but I could be wrong.

**Comment by staltz** [comment]
http://rxmarbles.com/#debounce

<img width="859" alt="screen shot 2015-10-08 at 10 04 20" src="https://cloud.githubusercontent.com/assets/90512/10359735/fb49c638-6da3-11e5-9a34-613674a6c86c.png">

**Comment by paulpdaniels** [comment]
Perhaps somewhat off topic but I would suggest more closely mirroring @staltz 's example. As it stands (assuming those marbles are actually the tests) they don't really tell you much about what the test is doing.

**Comment by staltz** [comment]
You mean, you don't think 

```js
var source = hot('---^---1-----2--3-4-5------6-----')
var e = source.debounce(90)
var expected  =     '-------1------------5------6--'
```

is informative? I do.

**Comment by paulpdaniels** [comment]
@staltz on the contrary I think _that_ is informative. I don't think

```javascript
var source = hot('---^---x---x---x---x---x---x---x---------------');
var expected  =     '-------------------------------x------------';
```

is as much so. But looking at this again in the morning I think I was being too greedy last night in suggesting that marble tests should test specific behavior *and* tell a totally unambiguous story of what exactly the operator is doing.

**Comment by blesh** [comment]
Okay, I think that we've reached a consensus.

... and it's that I've implemented them "backwards". Heh. I feel like I was doing whatever RxJS 2 was doing. But maybe I just lost my mind.

For verification that this is the idiom, I've checked lodash, and it seems to agree with the consensus of this thread. Sorry for any confusion.
