### ISSUE TITLE
[docs]: The operator `publish` needs an adoption of the description and example 

### ISSUE THREAD

**Issue by BioPhoton** [ReactiveX/rxjs#4800]
### Please check those that apply

- [ ] typo
- [x] documentation doesn't exist
- [x] documentation needs clarification
- [ ] error(s) in example
- [x] needs example

### Description Of The Issue
The description is missing.
An example without a selector should be provided.

We may want to fix this.

**Comment by benlesh** [comment]
This is deprecated and will be removed in favor of `connect`.
