### ISSUE TITLE
[docs]: The operator `publishBehavior` needs an adoption of the description and example

### ISSUE THREAD

**Issue by BioPhoton** [ReactiveX/rxjs#4801]
### Please check those that apply

- [ ] typo
- [x] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [x] needs example

### Description Of The Issue

The operator `publishBehavior` is missing:
- short description
- description for parameter [value]
- description
- examples

We may want to fix this.

**Comment by benlesh** [comment]
This is deprecated and will be removed in favor of `connect`.
