### ISSUE TITLE
[docs]: The operator `publishReplay` needs an adoption of the description and example

### ISSUE THREAD

**Issue by BioPhoton** [ReactiveX/rxjs#4802]
### Please check those that apply

- [ ] typo
- [x] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [x] needs example

### Description Of The Issue

The operator `publishReplay` is missing:
- short description
- description
- examples

We may want to fix this.

**Comment by benlesh** [comment]
This is deprecated and will be removed in favor of `connect`.
