### ISSUE TITLE
defer type doesn't handle void correctly

### ISSUE THREAD

**Issue by mhverbakel** [ReactiveX/rxjs#4804]
## Bug Report

**Current Behavior**
When using `defer` with a `() => void` factory, the return type will be `Observable<any>`.

**Reproduction**
https://stackblitz.com/edit/rxjs-gm1wy5

```ts
import { defer } from 'rxjs';

const example = defer(() => {});

// Type of example is Observable<any> but should be Observable<never>.
```

**Expected behavior**
When using `defer` with a `() => void` factory, the return type will be `Observable<never>`.

**Possible Solution**
Adding the following to the declaration:
```ts
function defer(observableFactory: () => void): Observable<never>;
```

**Comment by cartant** [comment]
I don't agree with the expected behaviour. `defer` should return an `ObservableInput` and `void` is not an `ObservableInput`.

**Comment by mhverbakel** [comment]
Fine with me, but then `| void` should be removed from https://github.com/ReactiveX/rxjs/blob/6.5.2/src/internal/observable/defer.ts#L55.

**Comment by cartant** [comment]
Yikes. I didn't even realise that was there. This should definitely have two signatures.
