### ISSUE TITLE
Complex object is not deep copied

### ISSUE THREAD

**Issue by DashanWang1** [ReactiveX/rxjs#4805]
## Bug Report

**Current Behavior**
If modify one property in a nested Object after get return from subscription `.subscrib((res)=>{  res.filed1.array.reverse();}), this property get modified in another subscription.

**Reproduction**
https://stackblitz.com/edit/rxjs-vxltka?devtoolsheight=60
```
const source = new ReplaySubject(1);
const obj = {
  content: {
    array:[1,2,3,4,5,6,7,8,9]
  }
}
source.next(obj);
source.subscribe(x => {
  if(x){
    console.log('1: ',x);
    x.content.array.reverse();
  }

});

source.subscribe(x => {
  if(x){
    console.log('2: ',x);
  }
});
```

The `content.array` get reversed in `console.log('2: ',x); 
![image](https://user-images.githubusercontent.com/44011899/58198927-62c07300-7c9d-11e9-9b23-ebbc76421dc6.png)

**Expected behavior**
`x.content.array` still has original order.

**Possible Solution**
Before subject emit the value, do a deep copy.

**Comment by cartant** [comment]
This behaviour is by design and is not a bug. It is not a responsibility of RxJS to ensure that mutations made by subscribers are isolated.
