### ISSUE TITLE
Big Bundle size - Tree shaking not working for operators

### ISSUE THREAD

**Issue by sandinosaso** [ReactiveX/rxjs#4811]
## Bug Report

**Current Behavior**
When creating a minimal project using rxjs the bundle size for that project is very heavy
even when using just one or two operators (**+600Kb uncompressed**)

**Reproduction**
- Here I show you a minimal repo where I am just using ONE operator (map operator)
and the bundle size is big: https://github.com/sandinosaso/rxjs-big-bundle-bug

```js
import { Observable } from 'rxjs/internal/Observable';
import { map } from 'rxjs/operators';
let x = Observable.create();
x.pipe(
  map((v) => v++)
)
```

**Expected behavior**
I expect the bundle size to be only related to the number of operators I import in this case should be **7.5 Kb** and not **577 Kb**

**Environment**
- Runtime: [e.g. Node v${x}, Chrome v${x}]
- RxJS version: 6.5.2
- Webpack 4.32.2

**Possible Solution**
Not sure I thought by the docs that tree shaking should work out of the box for this project. Not sure how to help with this.

**Additional context/Screenshots**
Before importing operators the bundle size is ( ** 36.8 Kb ** ):
<img width="773" alt="Screen Shot 2019-05-27 at 11 21 48 PM" src="https://user-images.githubusercontent.com/466105/58449117-25624800-80d8-11e9-9745-22ea3e94e628.png">

After import just **map** operator the bundle size is ( ** 577 Kb ** ):
<img width="740" alt="Screen Shot 2019-05-27 at 11 31 33 PM" src="https://user-images.githubusercontent.com/466105/58449106-18ddef80-80d8-11e9-89bb-dc29a8e4d4a1.png">

**Comment by kwonoj** [comment]
![image](https://user-images.githubusercontent.com/1210596/58449789-10c68580-80c1-11e9-8eed-521fe2d83637.png)

run `build:prod` correctly tree shake necessary operators only.

Webpack *DOES NOT DO TREE SHAKE ON NON-PROD BUILD*, so you can't check bytesize of tree shaking via build without `--production`.

![image](https://user-images.githubusercontent.com/1210596/58449882-4ff4d680-80c1-11e9-9804-c792b5fad7ea.png)

**Comment by sandinosaso** [comment]
Thank for the help that was the problem at least for the minimal project I pointed out.
I turned out production mode for webpack but I am having big RxJS bundle, have you any idea what may be causing it?

<img width="658" alt="Screen Shot 2019-05-28 at 12 33 15 AM" src="https://user-images.githubusercontent.com/466105/58451201-71b18600-80e0-11e9-9e09-d6620f466aa9.png">

**Comment by cartant** [comment]
You should *NOT* be importing from internal locations. Your screen shots indicated you are importing from `rxjs/internal/Observable`, etc. Your doing so is not supported.

**Comment by cartant** [comment]
https://github.com/ReactiveX/rxjs/blob/master/docs_app/content/guide/v6/migration.md#import-paths

**Comment by sandinosaso** [comment]
Thanks @cartant for your comments I changed to import Observable directly from 'rxjs'.
However, my bundle size issue remains the same :(
Appreciate your help, can you point where to ask this kind of question, it would be better StackOverflow question? or is there any channel that people frequently use?
