### ISSUE TITLE
docs: update scan definition

### ISSUE THREAD

**Issue by ladyleet** [ReactiveX/rxjs#4814]
### Documentation Related To Component:

https://rxjs.dev/api/operators/scan

### Please check those that apply

[ x ] documentation needs clarification

### Description Of The Issue

scan needs to be updated from Applies an accumulator function over the source Observable, and returns each intermediate result, with an optional seed value.

change to "reducer function" vs accumulator function to make it clearer.

**Comment by ladyleet** [comment]
@benlesh and i were going through docs this am, and we should do this! :)

**Comment by BioPhoton** [comment]
@benlesh @ladyleet   
Is this still wanted? Even if I am not the same option I would implement it in the next days if you give a ok here.

**Comment by jakovljevic-mladen** [comment]
Looks like this is fixed with commit [f93fb9c1](https://github.com/ReactiveX/rxjs/commit/f93fb9c1fb7434c97e1d156370756159c5f2b077). I'm gonna close this issue.
