### ISSUE TITLE
switchMap operator keeps the values from previous observable sequence.

### ISSUE THREAD

**Issue by RaduBuciuceanu** [ReactiveX/rxjs#4821]
## Bug Report

**Current Behavior**
When I use the `switchMap` operator twice, it keeps the values from the first one.

**Reproduction**
```js
import { of, from } from 'rxjs'
import { switchMap, tap } from 'rxjs/operators'

of({})
  .pipe(switchMap(() => from([1, 2, 3])))
  .pipe(switchMap(() => from([4, 5, 6])))
  .pipe(tap(number => console.log(number)))
  .subscribe()

/* 
As a result, we get the following console output:
4
5
6
4
5
6
4
5
6
*/
```

**Expected behavior**
```js
/*
The console output should be:
4
5
6
*/
```

**Environment**
- Runtime: Node v10.15.3
- RxJS version: 6.5.2

**Additional context/Screenshots**
![image](https://user-images.githubusercontent.com/39530866/58629808-2668c480-82e6-11e9-90fe-f063a7958480.png)

![image](https://user-images.githubusercontent.com/39530866/58629757-033e1500-82e6-11e9-8589-bfd4aaba2e5c.png)

**Comment by cartant** [comment]
This is the expected behaviour.

**Comment by RaduBuciuceanu** [comment]
Sorry, my bad. To get the expected described, expected behaviour, this is the right code: 
```js
import { of, from } from 'rxjs'
import { switchMap, tap, toArray } from 'rxjs/operators'

of({})
  .pipe(switchMap(() => from([1, 2, 3])))
  .pipe(toArray())
  .pipe(switchMap(() => from([4, 5, 6])))
  .pipe(tap(number => console.log(number)))
  .subscribe()
```

Thx you.
