### ISSUE TITLE
Proposal: Add TypeGuard support for (static) `partition`

### ISSUE THREAD

**Issue by ericzhangjx** [ReactiveX/rxjs#4826]
## Feature Request (related to #2340)

Just like operator `filter`, could we also add support for TypeGuard in static `partition`?

Below is a demo that also works with the highlight in WebStorm:
[https://stackblitz.com/edit/rxjs-rzlrwb](https://stackblitz.com/edit/rxjs-rzlrwb)

The key code is the function signature (declared as `partition2` in demo):
```typescript
function partition<T, S extends T>(
  source: ObservableInput<T>,
  predicate: (value: T, index: number) => value is S,
  thisArg?: any,
): [Observable<S>, Observable<Exclude<T, S>>];
```
where `Exclude<>` is introduced in TS 2.8, there should be no compatibility issue.

There do is a problem that I'm not sure how to combine this signature with the existing operator in file `rxjs/src/internal/observable/partition.ts`. I think adding this signature as function reload should work.

**Comment by cartant** [comment]
Closed by https://github.com/ReactiveX/rxjs/pull/5756
