### ISSUE TITLE
iif Observable executes function when condition is not met.

### ISSUE THREAD

**Issue by BertDuyck** [ReactiveX/rxjs#4828]
## Bug Report

**Current Behavior**
When using the iif() Observable and use function inside witch does something and returns a stream it will always do something and return the stream on condition.

**Reproduction**
- REPL or Repo link:
https://stackblitz.com/edit/rxjs-geyrvn?devtoolsheight=60

**Expected behavior**
I would expect the function only to run when the condition is met.

**Environment**
- RxJS version: 6.5.1

**Comment by kwonoj** [comment]
I'm bit lost in q, what's problem in here? your console statement (`console.log('i should only log on false');` is not caused by `iif`, you just executed it in line 11: `getSomeStream()`. There's no way operator involves already executed function.

**Comment by kwonoj** [comment]
iif accepts observable for truthy / falsey and subscribe into, so it's expected to not emitting `false` here and I believe it behaves expected.

**Comment by BertDuyck** [comment]
Ok, I probably had some misunderstanding how the iif works then.
I was surprised that the iif also executes the getSomeStream() without the condition being met.
Its just not emitting.
Thanks for the quick reply and sorry for the misunderstanding.
