### ISSUE TITLE
[docs] urls being case sensitive

### ISSUE THREAD

**Issue by ladyleet** [ReactiveX/rxjs#4829]
### Description Of The Issue

Opening this to get some commentary around the fact that our docs URLs are case sensitive. 

Is there any way we can fix this? Do we want to?

Examples: 

This url works => https://rxjs.dev/api/operators/switchMap

This url does not https://rxjs.dev/api/operators/switchmap

**Comment by prabhavgupta** [comment]
One way to fix this will be to save routes in lowercase only. So route for switchmap will be stored.
Now anytime the request comes like 'SwitchMap' or 'switchMap', it will pass this part of the url as lowercase to achieve the defined route.

**Comment by JWO719** [comment]
I see serious problems when targeting this issue. My main concern is to make such a change backward-compatible for all the urls that are already out there. From my point of view, most people are using the search or the api overview (just my personal feeling, without any proof), so I don't this is worth the effort. Therefore I'm going to close this, for now If one disagrees with me, I'm happy to keep discussing that.
