### ISSUE TITLE
After updating rxjs 6.4.0 to 6.5.2 code getting an error in switchMap

### ISSUE THREAD

**Issue by Domainv** [ReactiveX/rxjs#4834]
After updating rxjs 6.4.0 to 6.5.2 code getting an error in switchMap
```
$source.pipe(
      switchMap((workspaceTree: any) => {
        return runner.runExternalSchematicAsync('@schematics/angular', 'application',
          {...appOptions, name: 'my-app'}, workspaceTree)
      })
    ).subscribe()
```

Could you show an example of right new format for switchMap operator?

**Comment by cartant** [comment]
https://codeburst.io/save-time-and-money-by-writing-useful-bug-reports-8f501ff00bb3

**Comment by kwonoj** [comment]
closing as lacks of info.
