### ISSUE TITLE
Filter operator not called in test

### ISSUE THREAD

**Issue by prumand** [ReactiveX/rxjs#4837]
## Bug Report

**Current Behavior**
the filter operator is not called in tests (using jest). In the browser it works as expected (see repo for details).

**Reproduction**
- https://github.com/prumand/jest-marbles-merge-map

```typescript
 // code
export default function basicMergeMapObs(
    action$: Observable<Action>
) : Observable<any> {
    return action$.pipe(
        filter((val: Action) => {
            throw new Error('We stop here')
        }),
        map((val: Action) => ({
            type: 'WE_FINISH',
        })),
        catchError(() => of({
            type: 'MY_NEW_ERROR',
        }))
    )
}

// test
it('should yield an MY_ERROR', () => {
    const source = of({
        type: 'TEST',
        status: 'NEW'
    })

    getScheduler().run(helpers => {
        const { expectObservable, cold } = helpers
        expectObservable(
            basicMergeMapObs(
                source
            )
        ).toBe(
            '(t|)',
            {
                t: { type: 'MY_NEW_ERROR' }
            }
        )
    })
})

function getScheduler() {
    return new TestScheduler((actual, expected) => {
        expect(actual).toMatchObject(expected);
    });
}
```

**Expected behavior**
Since I always throw an error, I never want WE_FINISH as output.

**Environment**
- Runtime: Windows, Node v10.15.3
- RxJS version: 6.5.2

**Additional context/Screenshots**
![jest output](https://user-images.githubusercontent.com/8741693/59093978-71519000-8915-11e9-92c6-b8ac01237b44.png)

**Comment by cartant** [comment]
This works fine, for me:

```ts
it("temp", () => {
  const testScheduler = new TestScheduler((a, b) => { expect(a).to.deep.equal(b); });
  testScheduler.run(({ cold, expectObservable }) => {
    const source = cold("a");
    const result = source.pipe(
      filter(() => { throw new Error("kaboom!"); }),
      map(() => of("m")),
      catchError(() => of("c"))
    );
    expectObservable(result).toBe("(c|)");
  });
});
```

**Comment by cartant** [comment]
For this to be a an actionable bug report, it needs a minimal reproduction that uses either a `hot` or a `cold` `TestScheduler`-created observable as a source.

**Comment by prumand** [comment]
thx for the example. I'll try that and update, but only in two weeks time. I'm off for one week.

**Comment by prumand** [comment]
thx for the example. Did you try it with typescript? I updated the example, but it still doesn't work.

**Comment by prumand** [comment]
When I compile this example to js, and run it in the browser, it works as expected (also part of the example repo).

**Comment by cartant** [comment]
The example is TypeScript.

**Comment by prumand** [comment]
I just run your code, with ts. Still don't why my sample fails. thx anyways

**Comment by prumand** [comment]
Last update I have for this issue. This seems to only fail on my windows machine, not in docker `node:latest`.
