### ISSUE TITLE
[docs]: Update angular to version 8

### ISSUE THREAD

**Issue by BioPhoton** [ReactiveX/rxjs#4845]
### Preconditions

Before we can start with this one we have to solve issue #4687. There is already a PR present here #4688

### Documentation Related To Component:

The whole docs project.

### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [ ] documentation needs clarification
- [X] error(s) in example
- [ ] needs example

### Description Of The Issue

We should update the docs app to version 8 of angular.
Suggested steps are using the angular CLI for it: `ng update`
Then run the tests inside the `docs_app` to see if the PR would pass: `npm run test`

**Comment by kanafghan** [comment]
I would like to provide a PR when it's ready.

**Comment by JWO719** [comment]
I extended the referenced pr to do also the migration to angular 8. I highly appreciate any manual testing on that. Thanks in advance!

**Comment by BioPhoton** [comment]
@JWO719 Is there anything left to do?

**Comment by JWO719** [comment]
From my point of view it is done, it just needs an approval

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by JWO719** [comment]
closed by #4688
