### ISSUE TITLE
windowTime race condition

### ISSUE THREAD

**Issue by Velenir** [ReactiveX/rxjs#4847]
## Bug Report

**Current Behavior**
`windowTime` for some parameter values  throws

```
Error in /turbo_modules/rxjs@6.5.2/internal/operators/windowTime.js (105:27)
Cannot read property 'closed' of undefined
```

Couldn't figure out the exact relation between parameters, but basically it reliably broke for me with `windowTimeSpan > windowCreationInterval && maxWindowSize > 2`,

**Reproduction**
https://stackblitz.com/edit/rxjs-gajdpw?devtoolsheight=60

```js
import { interval } from 'rxjs';
import { windowTime, mergeAll } from 'rxjs/operators';

const timer = interval(200)
const result = timer.pipe(
  windowTime(1000, 600, 4),
  mergeAll(),
);
result.subscribe(x => console.log(x));
```

**Expected behavior**
Not breaking. Not sure as to exact console output, though. Same as with `bufferTime`? I am pretty new to RxJS, just experimenting with operators.

**Environment**
- Runtime: Chrome 76.0.3806.1 (Official Build) dev (64-bit)
- RxJS version: 6.5.2

**Additional context/Screenshots**
I'm assuming `windowTime` tries to close a window stream before it creates one, so a race condition?

**Comment by githubxiaowen** [comment]
check the [rxViz](https://rxviz.com/v/9J9zyRG8) here.

Frame:0
windows: [w1]
w1: [0]

Frame:1
windows: [w1]
w1:[0,1]

Frame: 2
windows: [w1,w2]
w1: [0,1,2]
w2:[2]

Frame: 3
w1:[0,1,2,3]
w2: [ 2, 3]

``` ts
  protected _next(value: T): void {
    const windows = this.windows;
    const len = windows.length;
    for (let i = 0; i < len; i++) {
      const window = windows[i];
      if (!window.closed) {
        window.next(value);
        if (window.numberOfNextedValues >= this.maxWindowSize) {
          this.closeWindow(window);
        }
      }
    }
  }
```
so , after w1 emitted the value 3, it will do the action closeWindow(window)， and remove the w1 window from windows。

``` ts
  public closeWindow(window: CountedSubject<T>): void {
    window.complete();
    const windows = this.windows;
    windows.splice(windows.indexOf(window), 1);
```
now back the `_next` method， since the windows changed to [w2]， look at our code

```ts
// i ==> 1
const window = windows[i]
```
now our ` window` gets `undefined'`, and the code emits an error`Cannot read property 'closed' of undefined`.


it's unusual for forks to call `windowTime` feeding with the weired parameters like above, but indeed it's a  bug 


i give it a slice to fix that, that's the easiest way to fix(BTW, bufferTime has the same problem)

@cartant request to review.

**Comment by githubxiaowen** [comment]
or we can use a `while` and `shift` to fixed that instead of using slice

**Comment by cartant** [comment]
Hmm. I'd like to avoid having to copy the array of windows upon each received `next` notification. Maybe something like this?

```
    for (let i = 0; i < len;) {
      const window = windows[i];
      if (!window.closed) {
        window.next(value);
        if (window.numberOfNextedValues >= this.maxWindowSize) {
          this.closeWindow(window);
          continue;
        }
      }
      ++i;
    }
```

**Comment by cartant** [comment]
@githubxiaowen If you are interested in contributing a PR to fix this, could you include a failing test in the PR, please?

**Comment by kschaefe** [comment]
As the original reporter suggested, I can confirm that `bufferTime` is dropping events when you are using positive values for all three parameters.  Do you need a different issue report for that?

**Comment by cartant** [comment]
@kschaefe Thanks for confirming. Given that `bufferTime` is mentioned in the issue, that the two operators are closely related, that the causes are likely related and that this issue is open, I don't think we need to open a separate issue for `bufferTime`.

**Comment by cartant** [comment]
@kschaefe

> Do you need a different issue report for that?

I've not been able to reproduce this easily with `bufferTime`, so if you could open another issue - complete with a minimal reproduction - that would be appreciated.
