### ISSUE TITLE
ReplaySubject toPromise

### ISSUE THREAD

**Issue by Serg-Mois** [ReactiveX/rxjs#4855]
For now when we call toPromise on subject - there is used method from parent Observable.
Do we have any chance to convert ReplaySubject toPromise and then use it in async/await style?
I expected resolved promise with the last value from ReplaySubject, or wait till the first emited value.  
For example something like:

 public toPromise(): Promise<T> {
    return new Promise<T>((resolve): void => {
        this.subscribe((value) => {
          resolve(value);
        });
    });
  }

**Comment by cartant** [comment]
Closing this 'cause `toPromise` is deprecated in v7 and that version includes the `firstValueFrom` and `lastValueFrom` APIs.
