### ISSUE TITLE
set is not a function

### ISSUE THREAD

**Issue by EarthyOrange** [ReactiveX/rxjs#4859]
## Bug Report

**Current Behavior**
```
java.lang.RuntimeException: undefined:47434: TypeError: set is not a function
        return set(boundArgs ? function () {
06-14 17:31:49.632 8959-8959/com.paypal.retailsdktestapp W/System.err:            ^
    TypeError: set is not a function
        at <anonymous>:47434:12
        at Object.hostReportError (<anonymous>:151834:5)
        at SafeSubscriber.error (<anonymous>:143163:39)
        at Subscriber._error (<anonymous>:143078:26)
        at Subscriber.error (<anonymous>:143058:18)
        at Observable._trySubscribe (<anonymous>:142503:22)
        at Observable.subscribe (<anonymous>:142481:22)
        at attach (<anonymous>:4667:50)
```

We have our source written in node.js v6.11.4 which we babelify to ES5 code so that we can run it in our Android application (Using PayPal's manticore). The problem is that when I run the below js code snippet I get the above error. The definitions of global.setTimeout and global.setInterval exist as functions, but for some reason I guess that they don't when the wrap function is invoked.

```js
interval(100, asyncScheduler).subscribe(val => Log.debug('Message @ async interval', val));
```

The error happens at
```
var wrap = function (set) {
  return function (fn, time /* , ...args */) {
    var boundArgs = arguments.length > 2;
    var args = boundArgs ? slice.call(arguments, 2) : false;
    return set(boundArgs ? function () { // This line is the culprit
      // eslint-disable-next-line no-new-func
      (typeof fn == 'function' ? fn : Function(fn)).apply(this, args);
    } : fn, time);
  };
};

$({ global: true, bind: true, forced: MSIE }, {
  setTimeout: wrap(global.setTimeout),
  setInterval: wrap(global.setInterval)
});
```

**Environment**
- Runtime: Node 6.11.4
- RxJS version: ^6.5.0
- (If bug is related) Loader, build configuration: babel

**Comment by kwonoj** [comment]
I'm bit confused, that `wrap` function doesn't look like inside of `rxjs`, am I missing something? Error says `set` is not avail in those `wrap` fn.

**Comment by EarthyOrange** [comment]
Oops, sorry, this definition actually comes from core-js

**Comment by kwonoj** [comment]
So as error says `set` is not available in runyime and it comes from outside of rx, not sure if this is issue of rxjs.

**Comment by EarthyOrange** [comment]
That 'set' also seems to be the second point of failure. In the error stack, a subscription is attempted first, which seems to have errored out. The error logic then goes on to try to call the 'set'. Can you let me know if that is right please?

**Comment by kwonoj** [comment]
In stack I can't see `set` is second error: for me this looks subscribe try to access globals with scheduler and hit those. If there's other error, what is it and why do you think rx raised it?

**Comment by EarthyOrange** [comment]
Do you mean the function passed to the subscribe is causing the problem?

Does subscribe access these globals? If so then that could be causing the subscription failure. Can you please confirm that? :)

I am looking for the answer to the "What raised the error?" Question :) and was hoping to get some help with the why.

**Comment by kwonoj** [comment]
> Can you please confirm tha
We can't confirm as we don't have reproducible way  and your enviroment does do downlevel transpilation. I can only speculate with given stack message. 

For futher investigavation if you beoieve this is rxjs issue, please provide reproducible repo doesn't involve other libraries. You can either reopen / or create new issue freely.
