### ISSUE TITLE
TypeScript: `startWith`: multiple generics

### ISSUE THREAD

**Issue by OliverJAsh** [ReactiveX/rxjs#4866]
## Bug Report

**Reproduction**

```ts
declare const foo$: Observable<{ foo: number }>
// Expected type: { foo: number }
// Actual type: { foo: number } | { foo: number }
const bar$ = foo$.pipe(startWith({ foo: 1 }))
```

Although the expected/actual types are compatible, it's slightly irritating to deal with a union type `T | T` instead of a consolidated type `T`, as it makes type inspection in VS Code much more difficult (especially when the types are large or deeply nested).

Is there a way to tell `startWith` to consolidate its generics if they are the same? I tried adding an overload with just one generic, but then other tests started to fail.

**Comment by cartant** [comment]
I've confirmed that this dtslint expectation fails:

```ts
const o = of<{ foo: number }>().pipe(startWith({ foo: 1 })); // $ExpectType Observable<{ foo: number; }>
```
```
ERROR: 5:3  expect  Expected type to be:
  Observable<{ foo: number; }>
got:
  Observable<{ foo: number; } | { foo: number; }>
```

And this one passes:

```ts
const v = { foo: 1 };
const o = of<typeof v>().pipe(startWith(v)); // $ExpectType Observable<{ foo: number; }>
```

However, I'd suggest that this is a TypeScript issue and for that reason I'd be reluctant to implement - what would be, IMO - a workaround.

I cannot see the reason for TypeScript's not consolidating a union of identical shapes.

**Comment by cartant** [comment]
I guess performance would be a good-enough reason, but, if that's the case, I'd still be reluctant to implement a workaround. Particularly, as this mechanism is used extensively throughout RxJS's types.

**Comment by OliverJAsh** [comment]
If you're interested, this overload (added as the first) provides a workaround:

```ts
export function startWith<T, D extends T>(v1: D): OperatorFunction<T, T | D>;
```

> I cannot see the reason for TypeScript's not consolidating a union of identical shapes.

I can file an issue and ask.

**Comment by cartant** [comment]
> If you're interested, this overload (added as the first) provides a workaround ...

Hmm. Maybe. But to 'fix' it for all of the signatures will involve a lot of typing (pun intended).

Also, I'm not sure how this will affect the typings that will be coming in v7 that allow for the inference of N-arguments, etc. Maybe the `D extends T` approach can be used - or something similar can be incorporated into a conditional type. IDK. Will have to think about it.

Also, there will be a bunch of other operators that have this problem.

**Comment by benlesh** [comment]
This should no longer be an issue in version 7

**Comment by cartant** [comment]
This is still an issue with RxJS 7.1 and TypeScript 4.3, but, IMO, this could still be closed as TypeScript quirk. I note that the [related TypeScript issue](https://github.com/microsoft/TypeScript/issues/31955) is still open.
