### ISSUE TITLE
Imports from multiple "rxjs" cases increases build file size

### ISSUE THREAD

**Issue by WhitWaldo** [ReactiveX/rxjs#4873]
## Bug Report

**Current Behavior**
I previously reported [an issue](https://github.com/ReactiveX/rxjs/issues/3765) in seeing large bundle sizes when building rxjs with webpack and typescript. 

![image](https://user-images.githubusercontent.com/2238529/59727574-b5893e00-91fb-11e9-9332-b6f7a8b71e90.png)

While diving back down this road to shrink the overall bundle, I noticed that it seemed that I had multiple sets of rxjs imports. Lo and behold, despite having only the one installed rxjs package, I had a typo in my project that pulled from "Rxjs" instead of "rxjs" in the import statement.

Correcting the case of the import shrunk the pre-minifcation size of the bundle by 40 KB and results in just the one section.
![image](https://user-images.githubusercontent.com/2238529/59727897-490f3e80-91fd-11e9-8f68-e54b940a264d.png)

I'm not well-versed in all the variations of import statements these days (except to be thankful that they Just Work in my IDE) so I'm not entirely sure if there's anything you can do about this, but ideally you should only be able to import from "rxjs" and not other permutations of the case.

A clear and concise description of the behavior.

**Reproduction**
- REPL or Repo link:
[https://stackblitz.com/edit/rxjs-d4xgv9](https://stackblitz.com/edit/rxjs-d4xgv9)

Note that with the mixed case, Stackblitz will complain, but putting the same in my local VS Code instance will build without error (and show that unexpected bundling).

import { of } from "rxjs";
versus
import { of } from "Rxjs";

**Expected behavior**
I would expect that a warning be thrown indicating that there appears to be more than one case used across different imports of the same thing (though this may also be something better reserved for a linter) or, ideally, it Just Works and automatically uses the same case for all imports.

**Environment**
- Runtime: Chrome 75.0.3770.90 64-bit
- RxJS version: 6.3.3
- Webpack: 4.28.2

**Possible Solution**
Tell me to go file this under tslint's project instead or perhaps as a bug for VS Code (given that Stackblitz properly catches the mismatched import names).

**Additional context/Screenshots**
See inlined image above.

**Comment by kwonoj** [comment]
I don't think who exports (rxjs) can control imports site (like Rxjs): this would be probably same across any import you do (i.e Lodash vs lodash). When we exports we can't prohibit other way around. Also weird to hear compiler doesn't catch it: as you noted stackblitz says message about it, this is more like compiler / bundler's job.

**Comment by cartant** [comment]
Perhaps TypeScript's `forceConsistentCasingInFileNames` compiler option would help prevent this sort of thing. I agree with @kwonoj: this is not a problem that RxJS can solve.
