### ISSUE TITLE
Import static methods missing when bundled with webpack production mode

### ISSUE THREAD

**Issue by Yxwww** [ReactiveX/rxjs#4876]
## Bug Report

Hi there, Thanks in advance for taking a look! 
I am very inexperienced in terms of the internals of rxjs and how bundling works. As I was trying to support my team to migrate from rxjs 5 to 6, following the docs I tried to utilize `rxjs-compat` such that we don't have to change all of the source code right away. However, I ran into following issue during webpack production build. Not sure if it's intended or I am missing some configs. 

**Current Behavior**
Importing static methods not working when bundling with webpack production mode and TypeScript loader. 
According to bundle analyzer, it seems all of the rxjs code are not bundled in production mode. Could it be webpack tree-shaking too effective 🤔 ? 

**Reproduction**
- REPL or Repo link:
https://github.com/Yxwww/rxjs-static-import-missing-in-webpack-production-build

```js
import { Observable } from 'rxjs'
import 'rxjs/add/observable/of';
import 'rxjs/add/operator/switchMap';

console.log('switchMap: ', (Observable.of({})).switchMap);
// output:
// switchMap: E.of is not a function
```

**Expected behavior**
Expect to printout switchMap function
```js
// output:
// switchMap:  function switchMap(project) {
//    return operators_1.switchMap(project)(this);
// }
```

**Environment**
- Runtime: Node v10.16.0
- RxJS version: 6.5.2 , `rxjs-compat`: 6.5.2 [packge.json](https://github.com/Yxwww/rxjs-static-import-missing-in-webpack-production-build/blob/master/package.json)
- `webpackv4.34.0` [webpack.config.js](https://github.com/Yxwww/rxjs-static-import-missing-in-webpack-production-build/blob/master/webpack.config.js) , `TSv3.5.2` [tsconfig.json](https://github.com/Yxwww/rxjs-static-import-missing-in-webpack-production-build/blob/master/tsconfig.json)

**Comment by roman-lyubimov** [comment]
@Yxwww I have the same problem.. Do you have / find some workaround?

**Comment by Yxwww** [comment]
@roman-lyubimov  Unfortunately, no sir.

**Comment by roman-lyubimov** [comment]
@Yxwww I find solution this night... you need to manually update RxJS package.json file "sideEffects" to "true": [https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free](url). This looks like a dirty hack but it works with WebPack production mode.

**Comment by Yxwww** [comment]
Just tried turning off "sideEffects" worked for me as well. Gotta find some time reading about `sideEffect` option. 

Thanks a lot. Closing this ticket for now.
