### ISSUE TITLE
Refactor code base of Subject, BehaviorSubject and ReplaySubject

### ISSUE THREAD

**Issue by BioPhoton** [ReactiveX/rxjs#4880]
## Bug Report

**Current Behavior**
The functionality is completely fine. This issue is related to some refactoring work that could be done.

The following issue is related to the following files:
- [src/internal/Subject.ts](https://github.com/ReactiveX/rxjs/blob/b24d3ea85d33b893e4c020fb4fa9f6fa4d05dc0b/src/internal/Subject.ts)
- [src/internal/BehaviorSubject.ts](https://github.com/ReactiveX/rxjs/blob/b24d3ea85d33b893e4c020fb4fa9f6fa4d05dc0b/src/internal/BehaviorSubject.ts)
- [src/internal/ReplaySubject.ts](https://github.com/ReactiveX/rxjs/blob/b24d3ea85d33b893e4c020fb4fa9f6fa4d05dc0b/src/internal/ReplaySubject.ts)
- [src/internal/WebSocketSubject.ts](https://github.com/ReactiveX/rxjs/blob/a9fa9d421d69e6e07aec0fa835b273283f8a034c/src/internal/observable/dom/WebSocketSubject.ts#L151)

**Suggested changes**

_Subject.ts:_

- [x] Referencing a class property consistently. Also, referencing properties over `this` instead of destruction `this`.

A good example of inconsistency in referencing class properties is here:
https://github.com/ReactiveX/rxjs/blob/b24d3ea85d33b893e4c020fb4fa9f6fa4d05dc0b/src/internal/Subject.ts#L165-L170

Switching to referencing properties over `this` would take away the mental load of understanding object destruction and is applicable through the whole file.

- [x] Using array first-class functions instead of for loops.

To iterate through the observers of the subject a for loops is used. This could be improved by using array first-class functions. As a side-effect of this refactoring, we can get rid of multiple constants.

A good example could is the `next` method:
https://github.com/ReactiveX/rxjs/blob/b24d3ea85d33b893e4c020fb4fa9f6fa4d05dc0b/src/internal/Subject.ts#L66-L71

- [x] Get rid of `Symbol`. As it is internal stuff there is no need for depreciation, we can just delete it.
Detailed information can be found here: [Why check RxSubscriberSymbol in toSubscriber](https://stackoverflow.com/questions/54487471/in-rxjs-why-check-rxsubscribersymbol-in-tosubscriber/54488020#54488020)

https://github.com/ReactiveX/rxjs/blob/b24d3ea85d33b893e4c020fb4fa9f6fa4d05dc0b/src/internal/Subject.ts#L30

As described in the mentioned StackOverflow answer we could remove it from the code:

> rxSubscriberSymbol is used in Subscriber and in Subject, but now that it is a private symbol, it no 
> longer serves a purpose and is unnecessary.

Based on the following explanation we will remove `rxSubscriberSymbol ` from `Subscriber`:

> It's used in Subscriber is not necessary, as the instanceof Subscriber check will identify Subscriber
> instances. 

Here we can just delete the public property form `Subscriber`.  
The line to remove is [here](https://github.com/ReactiveX/rxjs/blob/c44734755d220ea50412a1486d7bd100a7694aef/src/internal/Subscriber.ts#L21)

Based on the following explanation we will remove `rxSubscriberSymbol ` from `Subject`:

> And it's use in Subject is unnecessary, as the rxSubscriberSymbol property in [Subject](https://github.com/ReactiveX/rxjs/blob/b24d3ea85d33b893e4c020fb4fa9f6fa4d05dc0b/src/internal/Subject.ts#L30-L32) - does nothing other than wrap the Subject in a Subscriber - which is what would happen in toSubscriber without the check.

Here we can just delete the public property form `Subject` [here](https://github.com/ReactiveX/rxjs/blob/b24d3ea85d33b893e4c020fb4fa9f6fa4d05dc0b/src/internal/Subject.ts#L30-L32) as the chack in `toSubscriber` [here](https://github.com/ReactiveX/rxjs/blob/b24d3ea85d33b893e4c020fb4fa9f6fa4d05dc0b/src/internal/util/toSubscriber.ts#L16-L18)
as well as remove a check [here](https://github.com/ReactiveX/rxjs/blob/b24d3ea85d33b893e4c020fb4fa9f6fa4d05dc0b/src/internal/util/toSubscriber.ts#L11)

_BehaviorSubject.ts:_
- [x] We could remove typing of subscription as it not needed. `super._subscriber` already returns `Subscription`.
https://github.com/ReactiveX/rxjs/blob/b24d3ea85d33b893e4c020fb4fa9f6fa4d05dc0b/src/internal/BehaviorSubject.ts#L26

_ReplaySubject.ts:_
- [x] Replacing `ReplayEvent` class with an interface as it does not bring any additional value and it's also less performant.

https://github.com/ReactiveX/rxjs/blob/b24d3ea85d33b893e4c020fb4fa9f6fa4d05dc0b/src/internal/ReplaySubject.ts#L50
https://github.com/ReactiveX/rxjs/blob/b24d3ea85d33b893e4c020fb4fa9f6fa4d05dc0b/src/internal/ReplaySubject.ts#L133-L136

_WebSocketSubject.ts:_

- [x] Referencing a class property consistently. Also, referencing properties over `this` instead of destruction `this`.

An example of referencing class properties over this is here:
https://github.com/ReactiveX/rxjs/blob/c44734755d220ea50412a1486d7bd100a7694aef/src/internal/observable/dom/WebSocketSubject.ts#L278

**Possible Solution**

I'm in progress of preparing a PR for this. The current status can be found here:
https://github.com/BioPhoton/rxjs/commit/b7a7b61a7bea76aa8ad9b951dbca42d8538aa78c

**Comment by martinsik** [comment]
I'm just curious what is the plan with `BehaviorSubject.getValue()`? I think there was a discussion whether it should be deprecated because it encourages "imperative" approach but I can't find it anywhere now.

**Comment by BioPhoton** [comment]
@cartant 

Do you think it is a good decision to remove the Symbol?

> Get rid of Symbol. As it is internal stuff there is no need for depreciation, we can just delete it.
> Detailed information can be found here: [Why check RxSubscriberSymbol in toSubscriber](https://stackoverflow.com/questions/54487471/in-rxjs-why-check-rxsubscribersymbol-in-tosubscriber/54488020#54488020)

**Comment by benlesh** [comment]
Just so you know:

1. It's more efficient to pull properties out into variables to prevent duplicate property lookups. 
2. `for` loops are more efficient for iterating arrays, and we never want to use `forEach` (or really even `for...of`) to iterate over arrays.
3. The symbol stuff is indeed a breaking change at our scale. I guarantee *someone* is using it. So it needs to be documented as such and included in a major revision.

I appreciate all of the thought here, but we might want to discuss this sort of thing before you dive in next time :)

**Comment by benlesh** [comment]
Also for this:

```ts
if (nextOrObserver) {
    if (nextOrObserver instanceof Subscriber) {
      return (<Subscriber<T>>nextOrObserver);
    }
    if ((nextOrObserver as any).constructor
      && (nextOrObserver as any).constructor.name.indexOf('Subject') !== -1) {
       return new SubjectSubscriber(nextOrObserver as Subject<T>) as Subscriber<T>;
    }
  }
```

The new version is going to be vastly less efficient. It's the difference between a single property lookup and two property lookups plus searching a string. This isn't to mention that part of the reason we had that check was to ensure that the instance we had was actually _from this instance of the library_. I know that sounds weird, but there are plenty of cases in node development where there is more than one version or copy of rxjs in node_modules, and we need to differentiate. This change would break those cases.

RxJS is hot-path code for folks, so micro optimizations here actually matter.

**Comment by benlesh** [comment]
I'm sorry I didn't see this issue until now. We really should have discuss this before you set out on this. I feel really bad closing it, as you've clearly put in a lot of thought and effort.

So sorry, @BioPhoton. ❤️
