### ISSUE TITLE
Missing debounceTime behavior on completion

### ISSUE THREAD

**Issue by EnzoMolion** [ReactiveX/rxjs#4881]
### Documentation Related To Component:

debounceTime operator 
### Please check those that apply

- [ ] typo
- [x] documentation doesn't exist
- [x] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

#### Context 
It tried to understand the behavior of the debounceTime operator. I used the following resources: 
* https://www.learnrxjs.io/concepts/time-based-operators-comparison.html
* https://www.learnrxjs.io/operators/filtering/debouncetime.html
* https://reactive.how/throttletime

Which tremendously helped me. 

#### Issue

I did not manage to find the behavior of this operation on completion. It [turns out](https://github.com/ReactiveX/rxjs/blob/master/src/internal/operators/debounceTime.ts#L24) that it emits the last received value if it's holding one at completion time. 

I was  unable to find this answer in [your documentation](https://rxjs.dev/api/operators/debounceTime) (nor on mentioned resources, obviously) and had to go into implementation to find this out. 

I have seen that a [recent commit](https://github.com/ReactiveX/rxjs/commit/b24d3ea85d33b893e4c020fb4fa9f6fa4d05dc0b) documented this. So, how come is this not on the [debounceTime documentation page](https://rxjs.dev/api/operators/debounceTime) ?

**Comment by BioPhoton** [comment]
Hi @EnzoMolion!

Nice catch! I will open an issue tomorrow and implement missing documentation

The mentioned behavior is already included in the new diagrams for both, debounce as well as debounceTime. 
https://github.com/ReactiveX/rxjs/pull/4786

**Comment by BioPhoton** [comment]
@EnzoMolion coming back with more information.

The reason it doesn't show up is because of the v7/master and v6 setup.

There is already an issue open that explains it and it's on the teams Roadmap.

If it helped, please consider closing this issue to keep the open issues relevant.

If it does not help please let me know what information is missing.
