### ISSUE TITLE
Infinite loop when `catchError` used in conjunction with `materialize`

### ISSUE THREAD

**Issue by sroucheray** [ReactiveX/rxjs#4885]
**Current Behavior**
Piping a stream to `catchError` then `materialize` starts an infinite loop

**Reproduction**
```typescript
const letters = of('a', 'b', 13, 'd');
const upperCase = letters.pipe(map(x => x.toUpperCase()));
const materialized = upperCase.pipe(
  catchError((error, caught) => caught),
  materialize(),
);
materialized.subscribe(x => console.log(x));
// Logs indefinitely 
```

- https://stackblitz.com/edit/typescript-e9e2yb (I added a `take(100)` to avoid the browse to freeze)

**Expected behavior**
The log should be called 5 times with respective `Notification` (next, next, error, next, complete).

**Environment**
- Runtime: Chrome / Firefox
- RxJS: tested on 6.5.2 and 5.5.12

**Comment by cartant** [comment]
I don't believe this is a bug. When you return `caught`, you are asking the implementation of `catchError` to re-subscribe to the source observable and it will, of course, error again.

**Comment by sroucheray** [comment]
Thanks @cartant for your answer. You are right and I missed it in the doc https://rxjs.dev/api/operators/catchError.

I must admit that this behavior of `catchError` is not intuitive to me.

I would have guessed that `catchError((error, caught) => caught)` does a kind of **bypass** while it actually does a **retry**.
