### ISSUE TITLE
Add custom headers to WebSocketSubject

### ISSUE THREAD

**Issue by batousik** [ReactiveX/rxjs#4887]
How could I add something like an Authorization http header?

**Comment by JacobChang** [comment]
AFAIK, you can't do this. [WebSocket Api](https://html.spec.whatwg.org/multipage/web-sockets.html#network) doesn't support modify http headers.

**Comment by batousik** [comment]
Fair enough. Had to authorise messages through websockets. Will leave my example here: got spring boot + swagger + angular architecture (using rest controllers). on the side got a websocket, with the first message after connect, im sending jwt token and then keep the map of sessions to authorised users.

**Comment by pshem** [comment]
@batousik I'm facing a similar problem - need to send an authentication message before I receive any responses via the webSocket. Did you manage to queue this via `openObserver`? I tried that, but it failed

```typescript
openObserver: {
        next: function () {
           () => this.authenticateSocket();
        }
      },
```

Running `authenticateSocket()` manually via a `(click)="authenticateSocket()"` event works, so I'm wondering if maybe I'm sending this too early.
