### ISSUE TITLE
Unable to assert subscriptions on tested observable

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#489]
I was unable to get this to assert:

```js
  it('should handle disposing of source', function() {
    var e1 =         hot('--a--^---b---c---d---e---f---g---h------|')
    var e1disp =         '-----^--------------------!';
    var e2 = cold(            '---------------(s|)');
    //                                        ---------------(s|)
    var expected =            '---------------x-----';
    var sourceSubs =     '-----^-------------------!';
    var values = {
      x: ['b','c','d'],
      y: ['e','f','g','h'],
      z: []
    };

    var source = e1.bufferWhen(function () { return e2; });
    expectObservable(source, e1disp).toBe(expected, values);
    expectSubscriptions(source.subscriptions).toBe(sourceSubs);
  });
```

In `expectSubscriptions(source.subscriptions).toBe(sourceSubs);`, it was complaining that `subscriptions` was `undefined`. Which sort of makes sense, because it's not a test observable type.. however, it seems like we could patch the `subscriptions` values onto the tested source during the test without any serious problems.

Thoughts, @staltz?

**Comment by staltz** [comment]
I bumped into the same problem, but then I notice what I actually want to do is

```js
expectSubscriptions(e1.subscriptions).toBe(sourceSubs);
```

And not

```js
expectSubscriptions(e1.bufferWhen(cb).subscriptions).toBe(sourceSubs);
```

Would be easy to do the fix you suggested, but anyway it also makes sense to test the subscription to the underlying "original" Observable.

**Comment by blesh** [comment]
I believe this has been resolved. Closing for now.

**Comment by staltz** [comment]
Yes, resolved.
