### ISSUE TITLE
refactor(combineLatest): Remove overloads in favor of more concise general types

### ISSUE THREAD

**Issue by Eddie-CooRo** [ReactiveX/rxjs#4894]
## Refactor types

I was just looking over the documentation where I found out that there are many overloads for each function with just different number of parameters (which doesn't support every case though); So I thought we would be able to replace them with some more concise type signatures (especially with the help of features introduced in *typescript@3.0.0*).
BTW, here is a very tiny representation of what I came up with: https://github.com/Eddie-CooRo/rxjs/pull/1
But unfortunately, I don't know any way to test if this type is exactly the same as the previous type with the overloads (Although I think it is) except for checking that it doesn't break types written with the previous types. I would appreciate if someone could check over it and let me know that if it worths working on.

**Comment by cartant** [comment]
Closing this because in v7, `combineLatest` and its related operators have simplified types with fewer overload signatures.
