### ISSUE TITLE
Add Operator for last "x" emitted values

### ISSUE THREAD

**Issue by dannibje** [ReactiveX/rxjs#4899]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Need to do some data filtering based on previous values from a stream.  These values need to be consistently the last x values from the stream. 

**Describe the solution you'd like**
An operator that returns the current value as well as the last x values emitted in an array.  Like PairWise, but for as many values as the user wants.  

**Describe alternatives you've considered**
Currently adding the latest value to an array outside of the observables and using the last x values of the array as data for the stream

**(If this is new operator request) describe reason it should be core operator**
Accessing previously emitted values is key to doing mathematical functions related to data streams.

**Comment by cartant** [comment]
Isn't [`bufferCount`](https://rxjs.dev/api/operators/bufferCount) what you are looking for? Or, at least, very close to what you are looking for?

**Comment by dannibje** [comment]
bufferCount is not exactly what I am looking for, pretty close though.  BufferCount collects x-amount of values and then emits them as 1 array.  But it does not emit every time a value comes through the stream, bufferCount(10) would emit an array of 10 values every 10 ticks.
What I need is a continuous stream of the last 10 values.  F.ex. to calculate an exponential moving average for a data stream.

**Comment by cartant** [comment]
Have a closer look at its second argument.

**Comment by dannibje** [comment]
Boom, thank you, can't believe I didn't notice that before.  No amount of googling mentioned this.
Guess that closes this issue.
