### ISSUE TITLE
doc problem for operator first

### ISSUE THREAD

**Issue by SamMaxwell** [ReactiveX/rxjs#4900]
### Documentation Related To Component:

https://rxjs.dev/guide/operators

### Please check those that apply

- [x] typo
- [ ] documentation doesn't exist
- [ ] documentation needs clarification
- [x] error(s) in example
- [ ] needs example

### Description Of The Issue

the example code that has this in it ...

   first()(of(1, 2, 3).subscribe((v) => console.log(`value: ${v}`));

is missing a parenthesis, and should rather be ...

  first()(of(1, 2, 3)).subscribe((v) => console.log(`value: ${v}`));

**Comment by Niladri24dutta** [comment]
@SamMaxwell this was fixed in master by #4813 . @benlesh It seems the updated version is still not deployed yet.

**Comment by cartant** [comment]
Closing 'cause, AFAICT, the examples have been updated.
