### ISSUE TITLE
Add exhaustMapTo

### ISSUE THREAD

**Issue by pauldraper** [ReactiveX/rxjs#4901]
Similar to mapTo, switchMapTo, mergeMapTo

**Comment by kwonoj** [comment]
As our issue template / guideline (https://github.com/ReactiveX/rxjs/blob/master/doc/operator-creation.md#publish-your-operator-as-a-separate-library) recommends, I'd like to suggest to publish as userlevel module first. We can discuss to include into core based on usecases later.
