### ISSUE TITLE
Decision tree working backwards from operator

### ISSUE THREAD

**Issue by NickLydon** [ReactiveX/rxjs#4906]
The operator decision tree is quite useful and I repeatedly recommend it to my colleagues. A suggestion would be to either include the text from the final step as part of the documentation for the selected operator, e.g. on the page for _timeout_

> I have one existing Observable, and after a period of inactivity I want to throw an error...

or to be able to work backwards seeing the choices that would lead the user there.

**Comment by JWO719** [comment]
Uh that's a very cool idea! Definetly like it. It also might help to make the decision tree more autogenerated.

@jsonberry What do you think about it?

**Comment by jsonberry** [comment]
I like the idea. It would give a similar vibe to what Brian has done on
learnrxjs.

We would perhaps give the user two options to start with: start “upstream”
or “downstream” - start with the “source” or the “operator”.

Extracting the summary and adding to the doc of the operator would be an
simple lift.

As far as I’ve thought it through (which isn’t far yet! 😉) I don’t see how
it would relieve the build process of the tree of manual maintenance. The
tree is really _ran_ by yml, the build uses that plus the output of the
docs json to connect the tree with working links. That outputs json which
is used by the frontend on the docs site.

I think this could be achieved without touching the generation of the tree
and by just updating the frontend Angular code that runs the interactive
part.

**Comment by benlesh** [comment]
Given the lack of traction on this issue. I'm going to close it. It's a good idea, but clearly we don't have the time to implement it or maintain it at the moment.
