### ISSUE TITLE
Marbles Testing: Missing create TestScheduler assertion causes silent fail of .run() tests

### ISSUE THREAD

**Issue by tomwhite007** [ReactiveX/rxjs#4908]
## Bug Report

**Current Behavior**
A boilerplate assertion is required inside the callback from a creation of a TestScheduler object. 
```ts
  const testScheduler = new TestScheduler((actual, expected) => {
    expect(actual).toEqual(expected);
  });
```
If this is missed out by someone looking to remove unnecessary boilerplate (like me), Marbles Testing assertions inside testScheduler.run() pass **or fail** silently because the external test framework (in my case Jasmine), doesn't wrap them as part of its tests. They become orphan functions that just run and report nothing.

**Reproduction**

```ts
  it('test should fail but actually passes', () => {
    const testScheduler = new TestScheduler(() => {});

    testScheduler.run(({ expectObservable, cold }) => {
      const obs$ = cold('--a--b|', { a: 'x', b: 'y' });

      expectObservable(obs$).toBe('-|');
    });
  });
```

**Expected behavior**
Ideally an error would be thrown if this assertion was missed, but I assume that's not possible. So, couldn't there be a lint rule to do it instead?

**Environment**
- Test framework: Jasmine (but I'm pretty sure others behave the same)
- RxJS version: 6.5.2

**Comment by cartant** [comment]
I don't see how this is a bug. This implementation is deliberate; it's like this to avoid a dependency upon any particular test framework. And the documentation - IIRC - is clear on this point.

You've chosen to pass a noop.

**Comment by tomwhite007** [comment]
Hi @cartant 
You're right it isn't strictly a bug, but it is a vulnerability of sorts.
Just wanted to raise the topic as a conversation to help awareness.
Happy to close this off.
