### ISSUE TITLE
more useful error/warn msg in rxjs/src/internal/util/subscribeTo.ts in Rxjs 6

### ISSUE THREAD

**Issue by geyuqiu** [ReactiveX/rxjs#4915]
## Feature Request

I misstyped imports of observable in one source file: "rxjs", other imports were from "rxjs/index", then I was encountering following warning / error in all browsers except Chrome, which means, my forkJoin / combineLatest is resolving in Chrome ONLY.

```js
const msg = `You provided ${value} where a stream was expected.`
      + ' You can provide an Observable, Promise, Array, or Iterable.';
```

**Describe the solution you'd like**
maybe an extra warning message: please watch out how you imported Observable / Combinelatest / forkJoin or whatever ?

**Comment by kwonoj** [comment]
This is similar to https://github.com/ReactiveX/rxjs/issues/4873 - as a lib, we can't control import site. It should be controlled by build / lint or anything else. In short, library can't know `how you imported` from which path.

**Comment by geyuqiu** [comment]
thanks for the link :) , how come it behaved differently in different browsers?

**Comment by kwonoj** [comment]
it's likely possible based on runtime behavior different or build config or lot of other possibilities out there.

**Comment by geyuqiu** [comment]
But you do agree it is hard to debug, right?

**Comment by kwonoj** [comment]
The issue in here is not about the easiness of debugging, what we can do as a lib. Import site control is not something lib can do at all.
