### ISSUE TITLE
Question about `distinctUntilKeyChanged` performance

### ISSUE THREAD

**Issue by verschmelzen** [ReactiveX/rxjs#4916]
**RxJS version:**
Current [master](https://github.com/ReactiveX/rxjs/commit/af20916db55fb917ffb9e86d61ab07ff873d1c74) branch af20916db55fb917ffb9e86d61ab07ff873d1c74

**Code to reproduce:**
None

**Expected behavior:**
Ternary operator can resolve on operator creation once,
```
export function distinctUntilKeyChanged<T, K extends keyof T>(key: K, compare?: (x: T[K], y: T[K]) => boolean): MonoTypeOperatorFunction<T> {
  return distinctUntilChanged(compare ? (x: T, y: T) => compare(x[key], y[key]) : (x: T, y: T) => x[key] === y[key]);
}
```

**Actual behavior:**
it resolves on every item emission.
https://github.com/ReactiveX/rxjs/blob/4dd0be0a446a7d5fec7a15001e7ba56d4962346f/src/internal/operators/distinctUntilKeyChanged.ts#L84-L86

**Additional information:**
Could this change improve performance?

**Comment by martinsik** [comment]
You can test the change locally and see how much it improves performance: https://github.com/ReactiveX/rxjs#performance-tests

**Comment by cartant** [comment]
Closing this because no evidence of a meaningful performance improvement was forthcoming.
