### ISSUE TITLE
withLatestFrom without source observable

### ISSUE THREAD

**Issue by kekel87** [ReactiveX/rxjs#4917]
## Feature Request

Hello, we use NGRX in my team and we are often confronted to this case:

```ts
this.actions$.pipe(
  ofType(MY_ACTIONS),
  withLatestFrom(
    this.store.pipe(select(selector1)),
    this.store.pipe(select(selector2)),
  ),
  map(([, res1, res2]: [never, TypingRes1, TypingRes2]) => doSometing(res1, res2))
)
```
As you can see, we do not need the action (source).

**Describe the solution you'd like**
We would like to have an operator that behaves like `withLatestFrom`, but without the source in output.

With the case management of a single observable does not return a table, but directly the answer:
```ts
export function latestFrom<T, T1>(v1: ObservableInput<T1>): OperatorFunction<T, T1>;
export function latestFrom<T, T1>(v1: ObservableInput<T1>, v2: ObservableInput<T2>): OperatorFunction<T, [T1, T2]>;
...
```

We already look at `sample`, but it only accepts one onservable and it does not exactly do the same.

**Describe alternatives you've considered**
I try to do a custom operator like this : 

```ts
export function latestFrom<T, R>(...args: Array<ObservableInput<any>>): OperatorFunction<T, R> {
  return pipe(
    withLatestFrom.apply(null, args),
    map(([, ...results]) => (results.length === 1 ? results[0] : results)),
  );
}
```
But I can not solve the typing...

**Comment by cartant** [comment]
I think you do need the source. AFAICT, you are doing something *when the action occurs*, even though you are ignoring the action's payload.

**Comment by yunuseon** [comment]
Correct me if I'm wrong but it seems what you're looking for is combineLatest?

**Comment by kekel87** [comment]
@cartant Yes sorry, I mis explained. I need the source to trigger the result. It's just that I would not want to have the value of the source in the output (the payload of the action in this case).

@yunuseon No I tried `combinesLatest` but it does not fit (with `switchMap` and first).

```
withLastestFrom
source: ---a-- 's'
  obs1: -a---- '1'
  obs2: -a---- '2'
output: ---a-- ['s', '1', '2']

withLastestFrom with late observables (as expected)
source: -a---- 's'
  obs1: ---a-- '1'
  obs2: ---a-- '2'
output: ------

source.pipe(switchMap(() => combinesLatest(obs1, obs2).pipe(first())))
combinesLatest with late observables
source: -a---- 's'
  obs1: ---a-- '1'
  obs2: ---a-- '2'
output: ---(a|)--  ['1', '2']

wath we need :
lastesdFrom
source: ---a-- 's'
  obs1: -a---- '1'
  obs2: -a---- '2'
output: ---a-- ['1', '2']
```

**Comment by cartant** [comment]
I would type it like this:

```ts
import { MonoTypeOperatorFunction, Observable, ObservedValueOf, OperatorFunction } from "rxjs";
import { map, withLatestFrom } from "rxjs/operators";

type ObservedValuesOf<A> = { [K in keyof A]: ObservedValueOf<A[K]> };

function latestFrom<T, O extends Observable<unknown>[]>(
  ...observables: O
): OperatorFunction<T, ObservedValuesOf<O>> {
  return source =>
    source.pipe(
      // This assertion is only necessary because withLatestFrom doesn't (yet) have a
      // signature that infers for N parameters.
      withLatestFrom(...observables) as MonoTypeOperatorFunction<any>,
      map(([, ...rest]) => rest)
    );
}
```

However, IMO, this should be a user-land operator. I don't see a compelling reason for its inclusion in the core and I don't see a reason for this to be treated any differently to other operator proposals.

IMO, the code in the issue unnecessarily specifies the parameter types for the arrow function. TypeScript is perfectly capable of inferring these and, IMO, it is good practice to rely upon TypeScript's inference - over explicit typing - wherever possible. Doing so would result in this code:

```ts
this.actions$.pipe(
  ofType(MY_ACTIONS),
  withLatestFrom(
    this.store.pipe(select(selector1)),
    this.store.pipe(select(selector2)),
  ),
  map(([, res1, res2]) => doSometing(res1, res2))
)
```

IMO, it's not worth introducing a new operator to avoid the ` ,` that's needed to ignore the action payload.
