### ISSUE TITLE
static concat is marked as deprecated

### ISSUE THREAD

**Issue by ddannenb** [ReactiveX/rxjs#4918]
### Documentation Related To Component:

concat.ts javadoc
### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [x ] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue

The concat operator in rxjs/operators is deprecated saying to use the static version of concat.  The static version is deprecated with reference to scheduled and concatAll.  What is the intention here?

**Comment by martinsik** [comment]
Related to https://github.com/ReactiveX/rxjs/issues/3798 and https://github.com/ReactiveX/rxjs/issues/3927.
