### ISSUE TITLE
create-react-app freezes at extracting "rxjs"

### ISSUE THREAD

**Issue by NamanKhurana** [ReactiveX/rxjs#4920]
![image](https://user-images.githubusercontent.com/44221538/61538506-29b33d80-aa57-11e9-9fa0-18365f811b36.png)
#ITS NOW SHOWING TWO LOADERS CAN U PLEASE HELP ME WITH IT ????
![image](https://user-images.githubusercontent.com/44221538/61538540-3a63b380-aa57-11e9-8fb7-78b8f29b2bb5.png)
##ITS NOW 2 DAYS BUT THIS ISSUE IS COMING UP AGAIN AND AGAIN .
Please help ...

**Comment by cartant** [comment]
`npx create-react-app` works just fine - using either `npm` or `yarn` - on my computer and from that I can surmise that there's something different on yours and that this is not sort of problem suited to resolution via a GitHub issue. Other than suggesting you ensure you are using the latest version of `npm` and have cleared its cache, etc. I don't see that there is any way in which we can reasonably be expected to help.
