### ISSUE TITLE
[docs]: Example for 'bindCallback' broken

### ISSUE THREAD

**Issue by Enuvid** [ReactiveX/rxjs#4927]
### Documentation Related To Component:

Component: [bindCallback](https://github.com/ReactiveX/rxjs/blob/master/src/internal/observable/bindCallback.ts)
Example: [https://github.com/ReactiveX/rxjs/blob/af20916db55fb917ffb9e86d61ab07ff873d1c74/src/internal/observable/bindCallback.ts#L124-L138](https://github.com/ReactiveX/rxjs/blob/af20916db55fb917ffb9e86d61ab07ff873d1c74/src/internal/observable/bindCallback.ts#L124-L138)

### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [ ] documentation needs clarification
- [x] error(s) in example
- [ ] needs example

### Description Of The Issue

In this example:
```js
import { bindCallback } from 'rxjs';
 
const someFunction = (a, b, c) => {
  console.log(a); // 5
  console.log(b); // 'some string'
  console.log(c); // {someProperty: 'someValue'}
};
 
const boundSomeFunction = bindCallback(someFunction);
boundSomeFunction().subscribe(values => {
  console.log(values) // [5, 'some string', {someProperty: 'someValue'}]
});
```
`next` callback of `subscribe` will never be executed. Function `someFunction` will be runned with `[handler: (...args) => void, undefined, undefined]` params and `handler` will never been executed.

Thus, this example does not show how this method works.

**We can replace example to something like this:**
```js
import { bindCallback } from 'rxjs';
 
const someFunction = (a, b, callback) => {
  console.log(a); // 12
  console.log(b); // 10
  callback(a + b, a - b);
};
 
const boundSomeFunction = bindCallback(someFunction);
boundSomeFunction(12, 10).subscribe(values => {
  console.log(values); // [22, 2]
});
```

**Comment by cartant** [comment]
Thanks. You are correct. Would you be willing to create a PR for your suggested change?

**Comment by Enuvid** [comment]
Done
