### ISSUE TITLE
Nitpick: Shouldn't Rx.pipe with no arguments return identity instead of noop?

### ISSUE THREAD

**Issue by leewz** [ReactiveX/rxjs#4933]
https://github.com/ReactiveX/rxjs/blob/6.5.2/src/internal/util/pipe.ts#L25
```ts
if (!fns) {
    return noop as UnaryFunction<any, any>;
}
```

The composition of zero things should be the identity under composition, which is `Rx.identity`, not `Rx.noop`. That allows `pipe(pipe(), pipe(f))` to be equivalent to `pipe([].concat([], [f])`, which is equivalent to `f`.

I'm new to RxJS, so I don't know if people rely on this behavior.

**Comment by cartant** [comment]
Yes, you're right. It should be `identity`, IMO, too.

**Comment by cartant** [comment]
Would you be able to open a PR with the fix?

**Comment by leewz** [comment]
Actually, the conditional in my issue is not a check for the empty array, but for no array at all.

There is no test for `pipeFromArray(undefined)` = `noop`. The function is marked as `@internal`. The conditional is actually unreachable from client code.
