### ISSUE TITLE
node_modules/rxjs/util/isNumeric"' has no exported member 'isNumeric'

### ISSUE THREAD

**Issue by amitgandole** [ReactiveX/rxjs#4941]
**Angular CLI: 7.2.4
Node: 10.16.0
isnumeric@0.3.3**

In previous version of rxjs there was an line included in isNumeric.ts :
`export declare function isNumeric(val: any): val is number;`

but in updated version of isNumeric.ts there is no such line instead of this there is only : 
`export * from 'rxjs-compat/util/isNumeric';`

which is giving me error 

> `/node_modules/rxjs/util/isNumeric"' has no exported member 'isNumeric'`

If I manually put `export declare function isNumeric(val: any): val is number;`
in newer version of isNumeric.ts then there is no error.

**Comment by cartant** [comment]
`isNumeric` is not part of the public API.

**Comment by amitgandole** [comment]
@cartant I didnt understand. Plz explain.

**Comment by kwonoj** [comment]
Please share minimal reproducible code, also confirm if you're using `isNumeric` somewhere in your code. It's non-public and shouldn't be used in application code.

**Comment by amitgandole** [comment]
```
 if( isNumeric(line.substring(line.length-2)) ) 
        {  console.log("num"); }
```
this is how I am using it in service of txtoJSON

**Comment by cartant** [comment]
> It's non-public and shouldn't be used in application code.

**Comment by amitgandole** [comment]
> > It's non-public and shouldn't be used in application code.

but it was working before update

**Comment by cartant** [comment]
> but it was working before update

That's the point of not using non-publish APIs. They can break.

**Comment by kwonoj** [comment]
@cartant is correct. Those are not public and not gauranteed to work across versions.
