### ISSUE TITLE
filter<T> typeguard fails in strict mode

### ISSUE THREAD

**Issue by snebjorn** [ReactiveX/rxjs#4947]
## Bug Report
I'm trying to use `filter` as a TypeGuard when compiling in strict mode.
This might be an issue with typescript itself, but not sure. I encountered the issue in rxjs so reporting here.

**Current Behavior**
`filter<T>(event => event instanceof T)` fails when typescript is set to strict mode.

**Reproduction**
This is an example in Angular using `filter` as a TypeGuard for the Router events.

- REPL or Repo link: can't do stackblitz as doesn't compile in strict mode.
Here is one anyway, but it works https://stackblitz.com/edit/angular-2xu4tm (not strict mode)

```ts
constructor(router: Router) {
    router.events // (property) Router.events: Observable<Event>
      .pipe(filter<NavigationEnd>(event => event instanceof NavigationEnd))
      .subscribe(event => {});
  }
```
Fails in strict mode with:
```
Argument of type 'MonoTypeOperatorFunction<NavigationEnd>' is not assignable to parameter of type 'OperatorFunction<Event, NavigationEnd>'.
  Types of parameters 'source' and 'source' are incompatible.
    Type 'Observable<Event>' is not assignable to type 'Observable<NavigationEnd>'.
      Type 'Event' is not assignable to type 'NavigationEnd'.
        Property 'urlAfterRedirects' is missing in type 'RouterEvent' but required in type 'NavigationEnd'.ts(2345)
```
**Expected behavior**
Same behavior as when not in strict mode.

**Environment**
- Runtime: Node v12.4.0
- RxJS version: 6.5.2

```
Angular CLI: 8.2.0
Node: 12.4.0
OS: win32 x64
Angular: 8.2.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.802.0
@angular-devkit/build-angular     0.802.0
@angular-devkit/build-optimizer   0.802.0
@angular-devkit/build-webpack     0.802.0
@angular-devkit/core              7.3.9
@angular-devkit/schematics        8.2.0
@angular/cdk                      8.1.2
@ngtools/webpack                  8.2.0
@schematics/angular               8.2.0
@schematics/update                0.802.0
rxjs                              6.5.2
typescript                        3.5.3
webpack                           4.38.0
```

**Comment by cartant** [comment]
You've passed an ordinary, garden-variety arrow function. You've not passed a user-defined type guard. To pass the latter, you would need something like:

```ts
pipe(filter((event: /* whatever */): event is NavigationEnd => event instanceof NavigationEnd))
```

Also, IMO, it's bad practice to supply explicit type parameters in the value space, like this:

```ts
filter<NavigationEnd>
```

I'd suggest you avoid that wherever possible.

**Comment by snebjorn** [comment]
Uh many thanks!

`pipe(filter((event: /* whatever */): event is NavigationEnd => event instanceof NavigationEnd))`

works.

I agree that `filter<NavigationEnd>` should be avoided. It was an attempt to make it compile as

`pipe(filter((event) => event instanceof NavigationEnd))`

Would return an `Observable<Event>` and not the desired `Observable<NavigationEnd>`

copy/paste from the type without the trick above.
`(alias) filter<Event>(predicate: (value: Event, index: number) => boolean, thisArg?: any): MonoTypeOperatorFunction<Event> (+1 overload)`

**Comment by cartant** [comment]
I'm guessing this can be closed, now?
