### ISSUE TITLE
docs: Buffer example image 404s

### ISSUE THREAD

**Issue by biltongza** [ReactiveX/rxjs#4948]
The example image for [buffer](https://rxjs-dev.firebaseapp.com/api/operators/buffer) 404s.

As of right now it is pointing to `content/img/buffer.png`.

![image](https://user-images.githubusercontent.com/2845704/62476681-c855d300-b7a7-11e9-90eb-79b32228a9f8.png)

**Comment by Georift** [comment]
This was fixed and merged in PR #4789.

**Comment by JWO719** [comment]
the image for buffer is still broken.
