### ISSUE TITLE
[docs]: Renaming suggestion for publishLast

### ISSUE THREAD

**Issue by BioPhoton** [ReactiveX/rxjs#4949]
### Documentation Related To Component:

The `publishLast` operator: 
[publishLast.ts](https://github.com/ReactiveX/rxjs/blob/b24d3ea85d33b893e4c020fb4fa9f6fa4d05dc0b/src/internal/operators/publishLast.ts)

### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [x] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue

Publish operators are named after their used Subject. This helps the API consumer to understand intuitively and quickly what the operator will do. An exception is the `publishLast` operator.

See a list of `publish` operators and their Subjects here:
- publish => Subject
- publishBehavior => BehaviorSubject
- publishReplay => RpleaySubject
- publishLast => AsyncSubject

My suggestion now is to rename `publishLast` to `publishAsync` . This would make the whole naming consistent.

**Comment by BioPhoton** [comment]
Just remembered that there is also [this renaming](https://github.com/ReactiveX/rxjs/pull/4838).

This will change the situation a bit. But the issue is still valid because we would have to adopt the naming of the publish operators too.

**Comment by cartant** [comment]
Closing this because `publishLast` is deprecated in v7.
