### ISSUE TITLE
Observable pipe() take(1) type mismatch

### ISSUE THREAD

**Issue by Ketec** [ReactiveX/rxjs#4951]
```
Argument type MonoTypeOperatorFunction is not assignable to parameter type OperatorFunction
  Type unknown is not assignable to type IDestination[]
    Type unknown is not assignable to type Array unknown idestination idestination
```
`this.getDestinations().pipe(take(1)).subscribe()`
with return type `Observable<IDestination[]>`

**Comment by cartant** [comment]
Please fill out the issue template.

**Comment by dicbrus** [comment]
I observe similar error: 

```
const totalSubject  = new Subject<number>();
totalSubject.pipe(takeUntil(this.componentDestroyed));
```

this code produces tslint error: 
Argument type MonoTypeOperatorFunction<unknown> is not assignable to parameter type OperatorFunction<number, unknown>

**Comment by cartant** [comment]
Closing as stale. There is insufficient information in this issue for it to be an actionable bug report - the template has not been filled out and no additional information has been provided within the last four weeks.
