### ISSUE TITLE
Huge file size in angular build

### ISSUE THREAD

**Issue by KishoreBarik** [ReactiveX/rxjs#4952]
## Bug Report

**Current Behavior**
Source Map Explorer shows huge rxjs file size if polyfills are commented in angular project.
 **Before commenting polyfills**
![image](https://user-images.githubusercontent.com/13726932/62605210-38369b80-b917-11e9-9d1e-55d68b619626.png)

**After commenting polyfills** 
![image](https://user-images.githubusercontent.com/13726932/62603510-ada06d00-b913-11e9-9774-6cfdb2014c23.png)

**Environment**
![image](https://user-images.githubusercontent.com/13726932/62603543-c3159700-b913-11e9-9bbc-acab3e8583a3.png)

**Additional context/Screenshots**
Angular polyfill.ts commented
![image](https://user-images.githubusercontent.com/13726932/62631762-e27de580-b94e-11e9-8903-de5decba442e.png)

As mentioned in some places `modules` is already set to **es6** in tsconfig.json -> compilerOptions

**Comment by kwonoj** [comment]
We don't have `pre-build-optimizer.js` for argumentoutofrangeerror. This seems bundler / or ng config affects to downlevel rxjs modules.

**Comment by KishoreBarik** [comment]
@kwonoj 

Yes `pre-build-optimizer.js` might be being added by bundler. As I can see it to be present in all of the external(library) js files. But there is also difference in size if polyfills are added back

![image](https://user-images.githubusercontent.com/13726932/62647591-7f9c4680-b96e-11e9-9e61-4979e65125f2.png)

**Comment by kwonoj** [comment]
I feel like this is bundler config specific issue, not an issue of library itself: any specific reason you think this is rx side issues need to be resolved?

**Comment by kwonoj** [comment]
closing as lacks of additional info. As stated above, I believe this should belong bundler config issue. Feel free to reopen / create new issue if you have details related with rx core.
