### ISSUE TITLE
External CSS - missing objects

### ISSUE THREAD

**Issue by termitek12** [ReactiveX/rxjs#4974]
var ss = document.styleSheets;

However ss is missing some fields.. like href for example (I tested this with chrome and ff and there always is href). Why is that? Will this be fixed?

**Comment by kwonoj** [comment]
rx does not have access to document or stylesheets. If you think there is problem is rx core still, feel free to create new issues with fill out bug template.

**Comment by termitek12** [comment]
ohh sorry it is a wrong project... I did download rxjs when issuing other project and mislead the pages...

sorry for trouble.
