### ISSUE TITLE
Documentation Redirect to 404 page

### ISSUE THREAD

**Issue by terrymight** [ReactiveX/rxjs#4980]
### Please check those that apply

- [ ] 404 error 

### Description Of The Issue
The documentation on the distinctKey operator when followed from /guide/operators link redirects to a 404 page.

**Comment by ilyaryabchinski** [comment]
Hi guys!
If this issue is not taken yet I would like to contribute.

**Comment by JWO719** [comment]
Hi @ilyaryabchinski . I would highly appreciate if you could take care of this. If you need any kind of help, just let me know 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ilyaryabchinski** [comment]
Guys could u also take a look at my PR #4987 ?

**Comment by cartant** [comment]
Closing this 'cause the related PR has been merged.
