### ISSUE TITLE
Perf regression in `zip` operator

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#499]
Micro perf tests are now showing `zip` to be 75% slower than Rx 4. I'm not sure what happened there.

There are a few possibilities:

1. Changes made to `zip` to support iterators caused the regression, but weren't noticed.
2. Rx 4.0.0 has improved `zip` since I've last run the tests against it, and it's quite a bit faster.
3. Both?

Either way, we need to get it back up to speed

**Comment by mattpodwysocki** [comment]
@blesh pretty safe to say I did a lot of perf work for 4.x to beat 5.x to challenge us all

**Comment by kwonoj** [comment]
Seems v4 did quite optimization,  

>old zip() with immediate scheduler x 96,348 ops/sec ±3.19% (83 runs sampled)
new zip() with immediate scheduler x 51,863 ops/sec ±3.46% (84 runs sampled)
        85.77% slower than Rx v 4.0.0

>old zip() with immediate scheduler x 7,586 ops/sec ±2.89% (86 runs sampled)
new zip() with immediate scheduler x 56,612 ops/sec ±2.74% (82 runs sampled)
        646.22% faster than Rx v 3.1.2

**Comment by blesh** [comment]
Cool, @mattpodwysocki!  Well I guess it's not a "regression" then.

**Comment by blesh** [comment]
... but still, we need it to be faster.

**Comment by blesh** [comment]
It seems there are some bugs in the 4.0 zip implementation. Closing this until we're sure 4.0 zip is working properly.
