### ISSUE TITLE
toPromise(), two new parameters takeFirst and throwIfComplete

### ISSUE THREAD

**Issue by captainbackfire** [ReactiveX/rxjs#4993]
## Feature Request

**Problem:**
toPromise() is confusing in that it takes the last event from an eventstream. This is not always the expected behaviour. Especially on an eventstream that is never closed. For instance in angular: 

```js
someEventEmitter$.toPromise().then(x =>{console.log('that will never happen')})
```
will actually never return unless the eventEmitter is completed.
whereas 
```js
someEventEmiter$.pipe(first).toPromise().then(x =>{console.log('will happen')})
```
....the above will do what was expected i.e. , wait for the first event and continue.

**Solution:**
I suggest that two parameters are added to the toPromise method.
Parameter 1: takeFirst
This would indicate that the above behaviour is prefered. That is, the promise will return with the first event. The existence of this option also serves as documentation of the different behaviors. This is certainly a big part of the benefit since it took us quite some investigation to conclude what was going on.

Parameter 2: throwIfComplete
Indicates if the promise should throw an exception if the eventstream is already complete.
So the call I suggest to be supported is as below:
```js
someEventEmiter$.toPromise(true, true).then(x =>{console.log('will happen')})
```

**Comment by Airblader** [comment]
Both of these options exist in the shape of first() and throwIfEmpty(). What's the actual benefit of extending toPromise here? It's *marginally* fewer characters to type, and in essence exactly the same.

**Comment by cartant** [comment]
I'm not in favour of this for two reasons:

* as stated above, there are existing operators that can be used to achieve the desired functionality; and
* we would like to avoid APIs in which boolean parameters are passed. IMO, this:

        source.pipe(first()).toPromise()

    is much easier to understand than this:

        source.toPromise(true, true)

    I rarely use `toPromise`, so it's unlikely I'll know what behaviour those `true` arguments effect.

Also, note that `first` (and `last`) will throw if the stream is empty.

**Comment by Airblader** [comment]
To add to @cartant's last point, if you want first but without an error for empty streams, use `take(1)` instead.

**Comment by captainbackfire** [comment]
First of, thanks for you thoughts on this. 
To be clear, my suggestion does not aim to save a few keystrokes. It aims to save hours.
It took me and a colleague an hour to realize why the promise delivered by the toPromise() was not fulfilled. The case at hand was to implement a modal dialog. The dialog implements a output parameter in the shape of an EvenEmitter. When we made a promise by dialogResult$.toPromise() we expected to get a  promise that was fulfilled when an event was emitted to dialogResult$. 
We are fairly seasoned developers. In the hope of saving time for others, I suggest parameters.
It serves the purpose of indicating the functionality. 
I know that if there had been parameters, two hours would have been saved. If the documentation had covered this situation with perhaps an example of the pipe(first()) then I estimate that one hour would have been saved. In my opinion this is not a "beauty of code" or "purity" issue. It is a suggestion with the ambition of getting things done efficiently. 
.

**Comment by cartant** [comment]
> If the documentation had covered this situation...

Yes, this is a docs issue. The documentation for `toPromise` is less than ideal:

https://rxjs.dev/api/index/class/Observable#topromise-

The API should not be changed, IMO. The behaviour you need it already expressible via operators and the operators offer more flexibility: `first`, `last`, `single`, etc.

**Comment by cartant** [comment]
AFAICT, this is closed by https://github.com/ReactiveX/rxjs/pull/5295
