### ISSUE TITLE
Is extending rxjs and using custom function is possible?

### ISSUE THREAD

**Issue by dholakiyaankit** [ReactiveX/rxjs#4994]
I have recently upgraded in my angular project.
`"rxjs": "^6.5.2",`

What I want to achieve is to extend the Observable and create my own function and return promise from that.

In short 
```
class CustomObservableSubscribe<T> extends Observable<T> {    
    customOperator = () {
        //this should subscribe and return promise
    }
}
```
So, I have been looking into documents but all the Observable operators expecting the return type as Observable.

I have gone through 
[https://github.com/ReactiveX/rxjs/blob/master/doc/operator-creation.md#adding-the-operator-to-observable](https://github.com/ReactiveX/rxjs/blob/master/doc/operator-creation.md#adding-the-operator-to-observable)

[https://stackoverflow.com/questions/44599304/extending-observable-with-custom-functionality](https://stackoverflow.com/questions/44599304/extending-observable-with-custom-functionality)

[https://github.com/ReactiveX/rxjs/issues/1124](https://github.com/ReactiveX/rxjs/issues/1124)

With no luck.  I want to ask if this is possible? and how?

**Comment by cartant** [comment]
`Observable` already has a method that does that: [`toPromise`](https://rxjs.dev/api/index/class/Observable#topromise-).

And, now, by definition, anything that returns a `Promise` isn't going to be an operator. Operators return a function that accepts an `Observable` and returns an `Observable`.

**Comment by dholakiyaankit** [comment]
@cartant I understand it has toPromise() but what I want is to subscribe and handle response.  Is it possible the way I want?

**Comment by captainbackfire** [comment]
How about subscribe and then handle response.
Like this: someEventEmiter$.pipe(first).toPromise().then(x =>{console.log('Handle response')})

**Comment by dholakiyaankit** [comment]
@captainbackfire Can you share more details about the first?

**Comment by imsingh** [comment]
@dholakiyaankit  if you want to perform an action before passing the subscription down the chain, you can use tap operator. 

```stream$.pipe(tap(response) => { // do whatever here }).toPromise();```

Can you elaborate more on what you want to achieve?

**Comment by captainbackfire** [comment]
@dholakiyaankit Perhaps I misunderstood what your end goal was. My impression was that you wanted to use the toPromise() with something like a request response scenario with an EventEmitter. My resent experience has been that when dealing with things like EventEmitter, the toPromise() delivers the last event. If the stream is not closed, then you will never know what the last event is and hence never get an event) If what you want is to get the first event (witch you do when waiting on a response scenario)  you need to do the .pipe(first) thing.

**Comment by dholakiyaankit** [comment]
@captainbackfire  I agree with you. The main goal was to achieve the scenario where I do not have to handle the errors in the controller I will have only `.then` and I can handle the errors in middle ware like @imsingh  suggested. I have used the same and seems working.
