### ISSUE TITLE
docs(reference): 

### ISSUE THREAD

**Issue by mathieucaroff** [ReactiveX/rxjs#4996]
### Documentation Related To Component:
the generate function

### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example
- ---
- [x] error in the annotation syntax used for the examples

### Description Of The Issue

The old-style example annotations of
https://github.com/ReactiveX/rxjs/blob/master/src/internal/observable/generate.ts
should be updated to use markdown, as they are not (no longer?) correctly interpreted by the documentation generator, see https://rxjs-dev.firebaseapp.com/api/index/function/generate.

An example of good documentation example can be found in about every other page of the documentation, for instance, in:
https://github.com/ReactiveX/rxjs/blob/master/src/internal/observable/from.ts
resulting in:
https://rxjs-dev.firebaseapp.com/api/index/function/from

Note: I'm very new to the project. I haven't checked the documentation generation tool. This is why I post an issue rather than a pull request.

**Comment by JWO719** [comment]
@mathieucaroff thanks for reporting this issue, I really appreciate it! If you would like to take over this one, feel free to contact me. I'm happy to help you out if you want to!

**Comment by Ore4444** [comment]
Can close thanks to #5006

**Comment by niklas-wortmann** [comment]
closed by #5006
