### ISSUE TITLE
RXJS UMD doesn't seem to have Operator

### ISSUE THREAD

**Issue by aaomidi** [ReactiveX/rxjs#4997]
Latest rxjs here: https://unpkg.com/browse/rxjs@6.5.2/bundles/rxjs.umd.js

There is no `Operator`, there is no `Operator.prototype.share`. I'm guessing this is a bug, but there might be some reason for it?

**Comment by cartant** [comment]
Operators just don't work like that in v6 - and in v5 they were patched into `Observable.prototype` - so it's difficult to see what it is that you think is the problem. Also, you've not filled out the issue template.

**Comment by aaomidi** [comment]
The issue template didn't really make sense in this because I wasn't using it in code necessarily. 

I'm using Angular's UMD ([which doesn't pack rxjs because it's a peer dependency](https://github.com/angular/angular/blob/4.1.x/packages/core/package.json#L12)) and I'm trying to satisfy all the node require calls.

One of the calls are to rxjs/operator/share, and it's used here:

https://github.com/angular/angular/blob/4.1.x/packages/core/src/application_ref.ts#L478

I fed in the Rx.js (version 5.5.6): https://unpkg.com/browse/rxjs@5.5.6/bundles/Rx.js but was unable to satisfy that node require call. It's not found in the Rx.js. I guess if it's different in version 6 theres not much I can do other than build a version 5 UMD which includes 'rxjs/operator/share'.

**Comment by cartant** [comment]
The template has a section on versions and that is there for a reason. You cannot expect there to be no compatibility issues between major versions. If Angular 4 uses RxJS version 5, you should be using RxJS version 5.

**Comment by cartant** [comment]
https://github.com/ReactiveX/rxjs/blob/master/docs_app/content/guide/v6/migration.md

**Comment by aaomidi** [comment]
I did use RXJS version 5. Problem is even that version doesn't have rxjs/operator/share: 

https://unpkg.com/browse/rxjs@5.0.1/bundles/Rx.js

https://github.com/angular/angular/blob/4.1.x/packages/core/src/application_ref.ts#L13

**Comment by cartant** [comment]
Line 11431 - in the file you [linked above](https://unpkg.com/browse/rxjs@5.0.1/bundles/Rx.js) - has:

```
Observable.prototype.share = share;
```

So I have no idea what you are talking about. Without a repro - as requested in the template - this is unactionable.

**Comment by aaomidi** [comment]
> Observable.prototype.share = share;

> import {share} from 'rxjs/operator/share';

As mentioned in https://github.com/angular/angular/blob/4.1.x/packages/core/src/application_ref.ts#L13

Any chance angular is consuming it incorrectly?

Also I apologize for not being able to give a repro :/ (I'm a developer myself and I understand how difficult it is to convey this through text). It's a big mix of NDAs, etc.

**Comment by kwonoj** [comment]
I feel like this is issue of trying to consume umd as dep while ng code is written to consum plain cjs / esm module: both exports same, but export site is different as umd cannot allow to import individual module site from subpath - it only can be accessed globally exposed rx. namespace.

Main q in here is why you're trying to use umd as peerdep here - afaik ng's peerdep requires you to install package of rxjs, and it'll automatically consume cjs / esm per your bundle configuration unless you have explicit build pipeline not to do so.

**Comment by kwonoj** [comment]
Per above reason (umd / cjs have different export site) I don't think this is bug, more application configuration issue but really can't tell anything if there's no repo we can try to peek into. Best suggestion is try to follow peerdep resolution per ng to use non-umd module.

**Comment by aaomidi** [comment]
> Main q in here is why you're trying to use umd as peerdep here - afaik ng's peerdep requires you to install package of rxjs, and it'll automatically consume cjs / esm per your bundle configuration unless you have explicit build pipeline not to do so.

I'm going to use it on the web and I can't use webpack or any of the popular bundlers for this project.

Might just end up rebundling angular 4.1.x with rxjs included to get around this.

**Comment by kwonoj** [comment]
> I'm going to use it on the web and I can't use webpack or any of the popular bundlers for this project. Have a weird custom loader.

if you want to bend over dep issue with non-known module resolution, you may encounter hard time to conformant node.js module resolution based module import syntax. 

Your best bet is using ng itself as umd (so rx can be used as umd as well) or use ng as cjs / esm and rxjs also cjs / esm. Two different module resolution in single configuration doesn't play well together unless you write own module resolver by yourself.

This is obviously neither bug of rx or bug of ng, it's issue of your application build pipeline issue.

**Comment by aaomidi** [comment]
Yeah sounds good, just wanted to understand if there is a reason there wasn't a `Operator.prototype.share` in the Rx.js.

Thanks!
