### ISSUE TITLE
issues when using rxjs/fetch in create-react-app or webpack

### ISSUE THREAD

**Issue by kambing86** [ReactiveX/rxjs#4999]
## Bug Report

**Current Behavior**

the default behaviour of using
```ts
import { Observable } from "rxjs";
```

it will be using the source file in `./node_modules/rxjs/_esm5/index.js` because of the `module` defined in `./node_modules/rxjs/package.json`

but if we are using some other stuffs like
```ts
import { fromFetch } from "rxjs/fetch";
```

it will be using the source file in `./node_modules/rxjs/fetch/index.js`

this is causing a lot of bugs which I filed it here https://github.com/ReactiveX/rxjs/issues/4820

I have to use
```ts
import { fromFetch } from "rxjs/_esm5/fetch";
```

then everything works fine

**Reproduction**
https://github.com/kambing86/test-from-fetch
fix repo https://github.com/kambing86/test-from-fetch/tree/fix/import-fromFetch

**Expected behavior**
should be using just one type of source?

**Environment**
- Runtime: Node 10 / 12, Chrome 76
- RxJS version: 6.5.2
- (If bug is related) Loader, build configuration: create-react-app
- built in macOS High Sierra / WSL in Windows10

**Comment by kambing86** [comment]
it seems like using `rxjs/operators` is fine, most likely because they are just pure functions without state

```ts
import { finalize, mergeMap, share } from "rxjs/operators";
```

but `fromFetch` is returning the `Observable` class which is stateful, and this causes a lot of weird issues

**Comment by cartant** [comment]
@benlesh It seems likely that the problem is related to `fetch` not being included here:

https://github.com/ReactiveX/rxjs/blob/388172338a989c9eaa5d9c5c7b1081bcae6c43a2/.make-packages.js#L135-L140

**Comment by kambing86** [comment]
thanks @cartant for pointing out the root cause, I tried to fix it in my local and it works

create a PR for this https://github.com/ReactiveX/rxjs/pull/5001
