### ISSUE TITLE
Missing changelog for 6.5.3 

### ISSUE THREAD

**Issue by rakishii13** [ReactiveX/rxjs#5003]
## Bug Report

**Current Behavior**
Ran a yarn upgrade on my project and it got 6.5.3, however the changelog.md file on this github repo shows only upto 6.5.2 

**Reproduction**
Just do a `yarn add rxjs` and it will download 6.5.3

**Expected behavior**
Missing update on changelog.md I guess....

**Environment**
- Runtime: [e.g. Node v8.16.0, yarn v1.16.0]
- RxJS version: 6.5.3
- (If bug is related) Loader, build configuration: [e.g webpack, angular-cli version, config]

**Possible Solution**
N/A

**Additional context/Screenshots**
```yarn add v1.16.0
warning package.json: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.7: The platform "linux" is incompatible with this module.
info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "laravel-mix > img-loader@3.0.1" has unmet peer dependency "imagemin@^5.0.0 || ^6.0.0".
warning " > less-loader@4.1.0" has unmet peer dependency "webpack@^2.0.0 || ^3.0.0 || ^4.0.0".
[4/4] Building fresh packages...

success Saved lockfile.
success Saved 2 new dependencies.
info Direct dependencies
└─ rxjs@6.5.3
info All dependencies
├─ rxjs@6.5.3
└─ tslib@1.10.0
Done in 15.09s.
```

**Comment by bschmidtke** [comment]
Missing tag and release as well.

**Comment by MeLlamoPablo** [comment]
Any news on this? We will not upgrade until a changelog entry is released, or at least this issue is acknowledged by a maintainer!

**Comment by cartant** [comment]
@benlesh ?

**Comment by benlesh** [comment]
Fixed. I just didn't push up the changes to the changelog.
