### ISSUE TITLE
Documentation about Third Party Libraries

### ISSUE THREAD

**Issue by niklas-wortmann** [ReactiveX/rxjs#5005]
I think it would be valuable for the community if we have a dedicated page within the rxjs docs for third-party tools. So that we have a recommendation for tools like:

 - rxjs tslint
 - rxjs spy
 - redux observables
...

**Comment by kwonoj** [comment]
I think we can collect via https://github.com/ReactiveX/rxjs/discussions/categories/show-and-tell . Not sure that'd be suffecient, or we want separate pages.

**Comment by cartant** [comment]
Closing because we now have: http://rxjs.xyz/
