### ISSUE TITLE
Confusion when looking for the right documentation

### ISSUE THREAD

**Issue by edbzn** [ReactiveX/rxjs#5007]
### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [X] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue

Hi, 

I noticed that you're linking [rxjs.dev](https://rxjs.dev/) in the repository. I expect this to be the final documentation. 

However when I look for the documentation using search engines I only find [rxjs-dev.firebaseapp.com](https://rxjs-dev.firebaseapp.com) which seems to be for dev purpose.

I suggest to add an environment "flag" to the UI (e.g: navbar to be visible everywhere) to prevent users using the wrong documentation and help them to go to the right place.

I know there are related issues about this, but I'm actually unable to find them. Feel free to close this if the subject was already treated.

**Comment by edbzn** [comment]
Hi, it's been a long time ... I know that @niklas-wortmann has made some work on the documentation SEO, does it's suffisant to close this? What about the UI flag?

Thank in advance.

**Comment by niklas-wortmann** [comment]
So just to get it clear. Both URLs are pointing to the same firebase instance. So it barely matters. Additionally we improved this a while back. I will close this for now. Feel free to reopen.
