### ISSUE TITLE
How to reset timer before auto complete?

### ISSUE THREAD

**Issue by karthicktkm** [ReactiveX/rxjs#5011]
Hi Guys,
I'm using one function using timer in angular7. If I clicked some other function it will also call that same time and previous timer count.

For example.
I set timer = 10sec.
Initially loaded page then I clicked other function but now it's just 8sec over, now timer also will call.
After I clicked function timer will actually reload the function after 10th sec. but it will reload 2th sec of page loading and 10th seconds of function click.

Please tell me guys what can I do?

**Comment by kwonoj** [comment]
closing as lacks of info. I'd like to suggest to provide reproducible code snippet, and discuss it in stackoverflow or similar places.
