### ISSUE TITLE
Property 'toPromise' does not exist on type 'AjaxObservable'.

### ISSUE THREAD

**Issue by deanius** [ReactiveX/rxjs#5013]
## Bug Report

**Current Behavior**
When run with the following npm deps:
```
    "ts-loader": "6.1.0",
    "typescript": "3.6.3",
```

we get a  error upon 

```
import { ajax } from 'rxjs/ajax';

  return ajax
    .post(`${url}${index}`, query, {
      Authorization: 'Basic ' + btoa(userinfo),
      'Content-Type': 'application/json'
    })
    .toPromise()
```

That looks like:
```

ERROR in /Users/dradcliffe/src/ue/webpack/assets/javascripts/reviews/components/utils/productSearchUtils.ts
./webpack/assets/javascripts/reviews/components/utils/productSearchUtils.ts
[tsl] ERROR in /Users/dradcliffe/src/ue/webpack/assets/javascripts/reviews/components/utils/productSearchUtils.ts(133,6)
      TS2339: Property 'toPromise' does not exist on type 'AjaxObservable'.
```

**Expected behavior**
Since AjaxObservable extends Observable, it should not be a TS error to refer to `toPromise` should it?

**Environment**
- Runtime: Storybook (`"@storybook/react": "5.1.4"`)
- RxJS version: 6.5.2

Webpack: 
```
{
    test: /\.(ts|tsx)$/,
    use: { loader: 'ts-loader' }
  }
```

**Comment by cartant** [comment]
I would suggest that you look closely at the imports you are using. The exported types don't use `AjaxObservable` as a return type, so precisely what is going on in your situation is unclear:

https://github.com/ReactiveX/rxjs/blob/fc3d4264395d88887cae1df2de1b931964f3e684/src/internal/observable/dom/AjaxObservable.ts#L58-L66

**Comment by deanius** [comment]
I edited to include the import I was using. Should I be importing get/post directly ?

**Comment by cartant** [comment]
> Should I be importing get/post directly?

No. The import is correct.

My concern is that it's unclear how that particular error message could be effected, as the `ajax` import's type does not use `AjaxObservable` (see above). IMO, you need to make a more minimal reproduction - e.g. without Storybook, etc.

**Comment by kwonoj** [comment]
Closing as no further clarification update.
