### ISSUE TITLE
Streams of type Observable<x> | Observable<y> does not work

### ISSUE THREAD

**Issue by ricsam** [ReactiveX/rxjs#5015]
## Bug Report

**Current Behavior**
You cannot apply any operators to a stream of type `Observable<x> | Observable<y>`.
The stream `Observable<x | y>` works as expected.

**Reproduction**
Look in src/index.ts and uncomment the error part
https://codesandbox.io/s/dazzling-waterfall-rcp91

**Environment**
- RxJS version: 6.5.3

**Possible Solution**
To solve the issue I do the following:
```ts
export type InnerUnion<T> = Observable<T extends Observable<infer U> ? U : never>;
// InnerUnion<Observable<x> | Observable<y>> = Observable<x | y>
```

**Comment by cartant** [comment]
This isn't an RxJS issue. This is a TypeScript limitation. When TypeScript sees `Observable<x> | Observable<y>` it will limit the methods to those that are common to both `Observable<x>` and `Observable<y>` which means that the only `pipe` signature that matches both is `pipe()`.

**Comment by ricsam** [comment]
Ah, I see. That makes sense. Thank you
