### ISSUE TITLE
Support dictionary in combineLatest

### ISSUE THREAD

**Issue by Akxe** [ReactiveX/rxjs#5022]
## Feature Request

`combineLatest` should accept dictionary/object same as `forkJoin`. Implementation in `forkJoin` #4640 

```
combineLatest({
  width: this.width$,
  height: this.height$,
}).pipe(
  tap(({width, height}) => console.log(`dimensions: ${width}x${height}`))
)
```

### Reasoning
It is much easier to mess up when deconstructing array than deconstructiong object. Thus this change would enable developer to name their streams, reducing the potential for error.

**Comment by benlesh** [comment]
This is something we're planning, but I'm not sure we can do until the deprecated versions of `combineLatest` are removed in version 8.

**Comment by intellix** [comment]
This would be awesome in Angular when transitioning to observable values the view can get real messy. Would be nice to just use a single async pipe at the top and use values like they're not async

**Comment by amakhrov** [comment]
Currently a workaround is to use array-based `combineLatest` followed by `map()`:
```
const abc$ = combineLatest([a$, b$, c$]).pipe(
  map(([a, b, c]) => ({a, b, c}))
)
```
It's not too bad, but it results it repeating code (also error-prone, as @Akxe has pointed out)

Also it's probably not too hard to create a custom wrapper to implement that in your project.

**Comment by rraziel** [comment]
Is there any plan on implementing this, or at least would a pull request be considered for merging?

**Comment by Goobles** [comment]
You can create your own operator functions in the meantime as a workaround:
https://gist.github.com/Goobles/45f0b3027d31884dba0b164ee2cc50ea

**Comment by Akxe** [comment]
@rraziel I belive this can now be closed, right?

**Comment by rraziel** [comment]
@Akxe this is available in rxjs 7 yes

**Comment by tmtron** [comment]
[RxJs7 docs: Combine a dictionary of Observables](https://rxjs.dev/api/index/function/combineLatest#combine-a-dictionary-of-observables)
