### ISSUE TITLE
Error in operator `switchMap`'s docs

### ISSUE THREAD

**Issue by shengnoyi** [ReactiveX/rxjs#5023]
### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [ ] documentation needs clarification
- [x] error(s) in example
- [ ] needs example

### Description Of The Issue

ref: https://rxjs-dev.firebaseapp.com/api/operators/switchMap

I believe that the count of '30' in [example image](https://rxjs-dev.firebaseapp.com/assets/images/marble-diagrams/switchMap.png) should be 3 instead of 2.It makes me confused.

**Comment by JWO719** [comment]
The marble diagram is correct. Switchmap unsubscribes from the inner observable as soon as there is another notification by the source observable. In this example the ‘5’ notification is emitted before the inner observable could emit the last notification.
