### ISSUE TITLE
TypeScript error in config.ts: Conversion of type 'undefined' to type 'PromiseConstructorLike' may be a mistake

### ISSUE THREAD

**Issue by kostrse** [ReactiveX/rxjs#5025]
RxJS: 6.5.3
TS: 3.6.2

**src/internal/config.ts**

```ts
export const config = {
  /**
   * The promise constructor used by default for methods such as
   * {@link toPromise} and {@link forEach}
   */
  Promise: undefined as PromiseConstructorLike,
```
Fails with compilation error:
> TypeScript error in D:/Dev/OpDashBoard/FrontEnd/ClientApp/node_modules/rxjs/src/internal/config.ts(12,12):
Conversion of type 'undefined' to type 'PromiseConstructorLike' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.  TS2352

I think the fix would be to define it as:
```ts
  Promise: undefined as unknown as PromiseConstructorLike
```
Or maybe another, cleaner way.

[Repro in Playground](http://www.typescriptlang.org/play/index.html#code/KYDwDg9gTgLgBAYwgOwM7ycgZgSwOZwC8cA3gFBxwD0AVDRZTXACoAWwcYUEAtjqh0zooAVwQxocEQIAmcAEYBPODOBYAhiIA28LJJ7AYrCDNRxUY1nHWoGcJiQACWnMgDWcCQAVufAQF9rZDknF3c4PSgAUXUEVn87GioGH15+YAAuKWC1V2A5GzhUv2AAYRRhMQkoABkcN2AyBKA)

**Comment by kostrse** [comment]
I got this error when accidentally imported a RxJS file under `src/internal/` into my project

**Comment by cartant** [comment]
In the interim, you could - should, IMO - specify `skipLibCheck` in the compiler options in your `tsconfig.json`. There really is little point in having TypeScript check the internals of packages within `node_modules` when those packages contains `.d.ts` files that have already passed through the TypeScript compiler.

**Comment by cartant** [comment]
I'm going to close this as it's a sub-case of a known issue: the TypeScript compiler options used to build RxJS are insufficiently strict. In particular, `strictNullChecks` is `false`. See https://github.com/ReactiveX/rxjs/issues/4968
