### ISSUE TITLE
shareReplay with refCount and finite observable doesn't resubscribe

### ISSUE THREAD

**Issue by ArielGueta** [ReactiveX/rxjs#5029]
## Bug Report

**Current Behavior**
When using shareReplay with refCount, if the source observable completed and refCount is zero, if we subscribe again, it doesn't resubscribe to the source.

**Reproduction**
https://stackblitz.com/edit/rxjs-34njuv

```js
const source = interval(1000).pipe(
  take(1),
  shareReplay({ refCount: true, bufferSize: 1 })
)

const a = source.subscribe(x => console.log(x));

setTimeout(() => { 
  // refCount: 0
  a.unsubscribe();

  // refCount: 1 
  // should subscribe again to source
  source.subscribe(x => console.log(x))
}, 2000);
```

**Expected behavior**
I would expect the source to be subscribed again when using refCount. After all, I can resubscribe to a completed source:

```js
const source = interval(1000).pipe(
  tap(() => console.log('ex')),
  take(1),
  // shareReplay({ refCount: true, bufferSize: 1 })
)

const a = source.subscribe(x => console.log(x));

setTimeout(() => { 
  // refCount: 0
  a.unsubscribe();

  // refCount: 1 
  // should subscribe again to source
  source.subscribe(x => console.log(x))
}, 2000);
```

I see this behavior in the [source](https://github.com/ReactiveX/rxjs/blob/master/src/internal/operators/shareReplay.ts#L114) code, but I can't understand if it's a bug or this is the desired behavior. If it does, can you explain why it difference? It's confusing.

Thanks!

**Comment by ArielGueta** [comment]
I understand. It is because the Subject is stopped and we cannot reuse a Subject.

**Comment by cartant** [comment]
> I understand. It is because the Subject is stopped and we cannot reuse a Subject.

Yeah. It's because the source completed. It's a deliberate decision to not re-subscribe in that situation.

So if the source completes. the completed subject is used for future subscribers. The reason being that this is the behaviour that most callers seeking to share a source would want. If the implementation were to resubscribe to sources that complete, callers expecting a shared/cached stream might be a little surprised.

**Comment by ArielGueta** [comment]
So when we use a source that completes, for example, HTTP, there is no difference between `shareReplay(1)` and  `shareReplay({ refCount: true, bufferSize: 1 })`.

**Comment by cartant** [comment]
> So when we use a source that completes, for example, HTTP, there is no difference between `shareReplay(1)` and `shareReplay({ refCount: true, bufferSize: 1 })`.

There is a small difference. The HTTP request is async and takes some time, so subscribers have an opportunity to unsubscribe **before** completion. And if a subscriber unsubscribes **before** completion, `shareReplay({ refCount: true, bufferSize: 1 })` will unsubscribe from the source - cancelling the HTTP request - whereas `shareReplay(1)` will not.

**Comment by ArielGueta** [comment]
Thanks!
