### ISSUE TITLE
Wrong import path in typing file "scheduled.d.ts"

### ISSUE THREAD

**Issue by stefano-mariani** [ReactiveX/rxjs#5048]
## Bug Report

> node_modules/@reactivex/rxjs/dist/package/internal/scheduled/scheduled.d.ts:1:60 - error TS2307: Cannot find module 'rxjs'.
> 1 import { ObservableInput, SchedulerLike, Observable } from 'rxjs';

**Current Behavior**
Error while building.

**Reproduction**
I've found this because I'm trying to use the UMD module js with a global window variable since I do not have a module loader ("module": "none" in tsconfig) but only a server-side bundler (legacy app).

If this can be useful I have a ".d.ts" file like this
```
/// <reference path="../node_modules/@reactivex/rxjs/dist/package/index.d.ts" />
import * as Rx from 'node_modules/@reactivex/rxjs/dist/package/index';
declare global {
	var rxjs: (typeof Rx);
}
```

**Expected behavior**
No Errors.

**Environment**
- Runtime: NodeJs 8.1.2, Typescript 3.5.1
- RxJS version: 6.5.3

**Possible Solution**
The pull request https://github.com/ReactiveX/rxjs/pull/4832 fixed correctly the import paths  but the "typings" file was not fixed.

```
import { ObservableInput, SchedulerLike, Observable } from 'rxjs';
```
Fix the imports as
```
import { Observable } from '../Observable';
import { ObservableInput, SchedulerLike } from '../types';
```

I would try to fix it but I couldn't understand how you generate (??) the "typings" since they are not committed in the repository.

Thanks.

**Comment by kwonoj** [comment]
looks like fix is checked into master and not published to 6.5.x branch? /cc @benlesh for confirmation.

**Comment by stefano-mariani** [comment]
Hi,
after further investigation I have discovered that importing `package/index` was missing the `rxjs.operators.*` (and other) properties/types so it is probably the wrong way to do it.
Maybe this is why nobody else was having this error.

A different import statement seems to be more complete in this regard:
```
/// <reference path="../node_modules/@reactivex/rxjs/dist/package/internal/Rx.d.ts" />
import * as Rx from 'node_modules/@reactivex/rxjs/dist/package/internal/Rx';
```

As a side effect, using this declaration, seems to avoid the compilation error (probably because it does not reference that file in the dependency chain).

I'm still not sure that this is the correct way to do it but, at least, seems to be an ok workaround.

**Comment by benlesh** [comment]
Long resolved. Closing.
