### ISSUE TITLE
Bug: Rxjs module not found issue

### ISSUE THREAD

**Issue by macdevign** [ReactiveX/rxjs#5049]
Hi, 
After installing rxjs (npm install rxjs, and package.json did reference that ), I still unable to run the sample code. Strange that I don't have any problem running other node.js library, only this rxjs seems to have problem running and I wonder what is wrong as  rxjs is certainly been installed.  Can anyone identify what is wrong  ?

thank

![image](https://user-images.githubusercontent.com/6662383/65931450-4b0fad00-e43c-11e9-835f-5fa66e2c299d.png)

**Comment by kwonoj** [comment]
https://github.com/ReactiveX/rxjs/issues/4416

Rxjs does not suppoer standard esm yet. Do not use --experimental-worker flag.
