### ISSUE TITLE
Page Not Found after clicking Observable link

### ISSUE THREAD

**Issue by diegodesouza** [ReactiveX/rxjs#5053]
### Documentation Related To Component:

Observable - Multiple - Observable

### Please check those that apply

- [ ] typo
- [x] documentation doesn't exist
- [ ] documentation needs clarification
- [x] error(s) in example
- [ ] needs example

### Description Of The Issue

Upon clicking on the `Observable` link
![Screen Shot 2019-10-02 at 5 04 38 PM](https://user-images.githubusercontent.com/7575914/66081779-bdfd4e80-e536-11e9-8fc7-886fdfe60f3c.png)

I get the following screen 

![Screen Shot 2019-10-02 at 5 05 15 PM](https://user-images.githubusercontent.com/7575914/66081836-de2d0d80-e536-11e9-9670-db7a4a07404a.png)

**Comment by Xapuu** [comment]
This is fixed by #4882 .

**Comment by JWO719** [comment]
thanks for the info. Closed by #4882
