### ISSUE TITLE
accepting promise for forkJoin()?

### ISSUE THREAD

**Issue by kwonoj** [ReactiveX/RxJS#507]
RxJS4's [`forkJoin`](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/forkjoin.md) accepts promise as well as observables

`args (Arguments | Array): An array or arguments of Observable sequences or Promises to collect the last elements for.`

while current implementation does not. Is this intended design to drop promise? If promise can be accepted, PR https://github.com/ReactiveX/RxJS/pull/506 might need to be updated to include it as well as updating implementation.

**Comment by blesh** [comment]
Debatable. As long as it doesn't affect performance, I'm okay with it.

**Comment by blesh** [comment]
`forkJoin` should also accept "lowercase-o" observables... Meaning any object with an `[Symbol.observable]` method on it that returns an object with a `subscribe` function that accepts an `observer`.

**Comment by kwonoj** [comment]
I'll try to add to accept `promise` as start with performance benchmarking.

**Comment by blesh** [comment]
@kwonoj I don't recall.. did this get done?

**Comment by kwonoj** [comment]
It's WIP in my stash, but haven't completed yet while creating other PRs. I'll complete and create PR.

**Comment by blesh** [comment]
No hurry. Just checking
