### ISSUE TITLE
[docs]: @link index/EMPTY not working

### ISSUE THREAD

**Issue by bastienmoulia** [ReactiveX/rxjs#5070]
### Documentation Related To Component:

EMPTY

### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue

The link to the EMPTY page `{@link index/EMPTY}` redirect to a 404 (https://rxjs-dev.firebaseapp.com/EMPTY) instead of https://rxjs-dev.firebaseapp.com/api/index/const/EMPTY

https://github.com/ReactiveX/rxjs/blob/69f7c6df073f5fac949e873b090746d16db787e6/src/internal/observable/empty.ts#L60

**Comment by dan-auth0** [comment]
WebStorm was telling me that `empty()` was deprecated and to look into the docs for a better alternative. I also found that broken link on this page:

https://rxjs.dev/api/index/function/empty

Clicking on the suggested `EMPTY` leads to this page, which shows a `PAGE NOT FOUND` error:

https://rxjs.dev/EMPTY

Is the right link this one?

https://rxjs.dev/api/index/const/EMPTY

**Comment by cartant** [comment]
> Is the right link this one?

Yes, but the type is not `any`:

https://github.com/ReactiveX/rxjs/blob/ab6e9fc32c19c1f14f8f59459db75312e75b9351/src/internal/observable/empty.ts#L4-L8

**Comment by hiepxanh** [comment]
so empty is despricated or not? should we use or not?

**Comment by cartant** [comment]
Closing this 'cause `empty` is shown in the v6 and v7 docs:

https://rxjs.dev/api/index/function/empty

https://v6.rxjs.dev/api/index/function/empty
