### ISSUE TITLE
[docs]: Renaming suggestion for scheduler constants 

### ISSUE THREAD

**Issue by BioPhoton** [ReactiveX/rxjs#5073]
### Documentation Related To Component:

The following constants are considered:
- `queue`  [queue.ts](https://github.com/ReactiveX/rxjs/blob/865b7d36c1fc59d065072e7026e959c3a0e01ce7/src/internal/scheduler/queue.ts#L71)
- `async`  [async.ts](https://github.com/ReactiveX/rxjs/blob/865b7d36c1fc59d065072e7026e959c3a0e01ce7/src/internal/scheduler/async.ts#L55)
- `asap`  [asap.ts](https://github.com/ReactiveX/rxjs/blob/865b7d36c1fc59d065072e7026e959c3a0e01ce7/src/internal/scheduler/asap.ts#L42)
- `animationFrame`  [animationFrame.ts](https://github.com/ReactiveX/rxjs/blob/865b7d36c1fc59d065072e7026e959c3a0e01ce7/src/internal/scheduler/animationFrame.ts#L40)

### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [x] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue

Constants are IMHO written with an uppercase style.

If we take a look at [`EMPTY`](https://github.com/ReactiveX/rxjs/blob/865b7d36c1fc59d065072e7026e959c3a0e01ce7/src/internal/observable/empty.ts#L8) or [`NEVER`](https://github.com/ReactiveX/rxjs/blob/865b7d36c1fc59d065072e7026e959c3a0e01ce7/src/internal/observable/never.ts#L34) we see they are names and created the same way as scheduler constants. I.e. [`async`](https://github.com/ReactiveX/rxjs/blob/865b7d36c1fc59d065072e7026e959c3a0e01ce7/src/internal/scheduler/async.ts#L55)or  [`animationFrame`](https://github.com/ReactiveX/rxjs/blob/865b7d36c1fc59d065072e7026e959c3a0e01ce7/src/internal/scheduler/animationFrame.ts#L40).

My suggestion now is to rename the scheduler constants to the following:
- `queue` => `QUEUE`
- `async` => `ASYNC`
- `animationFrame` => `ANIMATION_FRAMT`
-  `asap` => `ASAP`

**Comment by cartant** [comment]
Closing this 'cause IDK that there's much to be gained from renaming these. It'll just inconvenience people. `EMPTY` got the name it has because it had to co-exist with the deprecated `empty`. It's also arguable that the schedulers are not constants; they have internal, changing state. `EMPTY` and `NEVER` have no internal state. They are completely cold. Anyway, that's my argument. I just don't think it's worthwhile changing the case.
