### ISSUE TITLE
Is it a BUG?

### ISSUE THREAD

**Issue by neroishero** [ReactiveX/rxjs#5083]
## Bug Report

**Current Behavior**
`of(10).pipe(
  filter(i => i>10),
  delay(5000)
).subscribe(
  n => console.log("_____ next", n), 
  e=> {}, 
  ()=>{ console.log("___ complete")
});`
output delay 5secs then "___complete";
why there is a delay, there shouldnt be any delay after the filter, right?

**Comment by neroishero** [comment]
Rx.from([10, 11]).pipe(
  RxOp.filter(i => i!=11),
  RxOp.delay(5000)
).subscribe(
  n => console.log("_____ next", n), e=> {}, ()=>{ console.log("___ complete") });

but this code only delay once, compare the code to my last comment, it should delay twice? Very confused...

**Comment by kwonoj** [comment]
Delay operator delays whole emission including completion.  https://github.com/ReactiveX/rxjs/blob/master/spec/operators/delay-spec.ts#L106
