### ISSUE TITLE
Feature Request: startWith that only emits a value after a timeout

### ISSUE THREAD

**Issue by aeb-sia** [ReactiveX/rxjs#5086]
## Feature Request

**Is your feature request related to a problem? Please describe.**
I need an easy way to define a conditional startWith that only emits if a timeout is reached.
The use case is to have a waiting state that is not always triggered.

**Describe the solution you'd like**
This is a working solution:
```
function startWithAfterTimeout<T, V>(
        o: Observable<T>, value: V, timeout: number = 2000): Observable<T | V> {
    const privateValue = Symbol('Just need a value to compare to');
    return merge(o, of(privateValue).pipe(delay(timeout)))
        .pipe(
            distinctUntilChanged((oldValue, newValue) => 
                !(oldValue === privateValue || newValue !== privateValue)),
            map(v => v === privateValue ? value: v)
        );
}

```
**Describe alternatives you've considered**
Another way of achieving this would be:
```
merge(of(value).pipe(delay(timeout), takeUntil(o)), o)
```
But I'm unsure if this has any side effects. I guess the observable should be at least shared, and I have no idea if there could be any race conditions.

**(If this is new operator request) describe reason it should be core operator**
I'm frankly a little astonished this is not already a core operator

If you have improvements to my current proposal I'd very much appreciate them.
I'm ok with this being closed if you think this shouldn't be included in core.

**Comment by kwonoj** [comment]
Not sure if I understood your requirement correctly, any reason `timeout` doesn't work? i.e

```
const start = (o: Observable<any>, due: number, value: any) => 
  o.pipe(timeoutWith(due, o.pipe(startWith(value))));
```

Regardless above pseudo works for you or not, I don't think this should be variant of `startWith` and probably appropriate for userland operator. Mostly cause of this operator might not need core's internal access to achieve this behavior.

**Comment by aeb-sia** [comment]
yeah that does work. 
I'm wondering if your solution has any issues with race conditions (like my second option) because the same observable is used multiple times. Do I have the guarantee that no values are lost/emitted twice?

**Comment by cartant** [comment]
@aeb-sia This can be done in userland pretty easily. Have a look at: https://github.com/cartant/rxjs-etc/blob/master/source/operators/startWithTimeout.ts

The problem of using the source observable twice can be solved using `publish` (with a selector).

**Comment by aeb-sia** [comment]
thank you. I learned something :-)

**Comment by kwonoj** [comment]
@cartant welp I forgot race, that indeed sounds better.
