### ISSUE TITLE
The marble diagram of the "buffer" operator is unavilable

### ISSUE THREAD

**Issue by thomaszdxsn** [ReactiveX/rxjs#5095]
### Please check those that apply

- [ ] typo
- [x] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue

I think this is a MDN or server issue, but no way can report it

**Comment by thomaszdxsn** [comment]
<img width="1346" alt="WeChat9460151df767a9a14a38f12e9781cdc1" src="https://user-images.githubusercontent.com/23616426/67136978-dc668800-f260-11e9-9a04-1c75e1a29826.png">

**Comment by JWO719** [comment]
closed by #5113

**Comment by JWO719** [comment]
closed by #5113
