### ISSUE TITLE
static generate needs deprecation of resultSelector

### ISSUE THREAD

**Issue by BioPhoton** [ReactiveX/rxjs#5111]
## Bug Report

As all other resultSelector got deprecated I assume this one was just missed out.
I suggest to deprecate it with the next release to have all resultSelector deprecations in v6.

https://github.com/ReactiveX/rxjs/blob/6.5.3/src/internal/observable/generate.ts#L68

**Comment by cartant** [comment]
Closing because of https://github.com/ReactiveX/rxjs/issues/5824.
