### ISSUE TITLE
Runaway promise

### ISSUE THREAD

**Issue by TrejGun** [ReactiveX/rxjs#5114]
## Bug Report

Hi there! I want to reopen issue #2343. It is still actual after 2 years

```
(node:85010) Warning: a promise was created in a handler at ~/node_modules/rxjs/internal/operators/mergeMap.js:59:18 but was not returned from it, see http://goo.gl/rRqMUw
```

```
(node:84851) Warning: a promise was created in a handler at ~/node_modules/rxjs/internal/util/subscribeToArray.js:5:20 but was not returned from it, see http://goo.gl/rRqMUw
```

**Comment by cartant** [comment]
IMO, that is not a bug. You cannot pass a promise to `finally`/`finalize`, it's not expecting one and will ignore it. (I'm presuming that a 'runaway' promise is an ignored promise.)

**Comment by cartant** [comment]
Something like that or exactly that?

IMO, very few people will be using Bluebird and RxJS and to get any traction with this you're going to have to minimize the time that someone is going to have to devote to looking into this. In particular:

* supply an exact, minimal reproduction of the problem;
* details the versions that are involved;
* explain what 'runaway' means; and
* explain why this is a problem for you - if this is just a warning that going to affect only a small percentage of users, why does this need to be fixed?

**Comment by TrejGun** [comment]
@cartant while I was preparing minimal example for you I was able to fix my code, it appears I had one more `concat` and try/catch block so I was loosing promise it that try/catch and then outer `concat` was reported as a source.

`runaway` means you are not waining for promise result
```
Promise.resolve(1)
  .then(x => {
    Promise.resolve(2) // this is runaway promise
  })
  .then(y => {
    return y === void 0 === true
  })
```

Thanks for your help
