### ISSUE TITLE
IE11 Error Handling ajax 

### ISSUE THREAD

**Issue by JackHowa** [ReactiveX/rxjs#5117]
## Bug Report

**Current Behavior**
There's an unhandled error on IE11

**Expected behavior**
I'd expect the error to be handled. I've updated to the latest `5.5.12`, per suggestion https://github.com/ReactiveX/rxjs/issues/3949#issuecomment-407834167. 

**Environment**
- Runtime: IE 11 on Windows 81 Emulator 

```
    "react": "^16.9.0",
    "react-dom": "^16.9.0",
    "react-redux": "^6.0.0",
    "react-redux-promise-listener": "^1.0.0",
    "react-router": "^5.0.1",
    "react-router-dom": "^5.0.1",
    "redux": "^4.0.1",
    "redux-observable": "^0.18.0",
    "redux-promise-listener": "^1.1.1",
    "rxjs": "5.5.12",
```

**Additional context/Screenshots**
- This is working for other browsers, including Edge 

<img width="331" alt="Screen Shot 2019-10-30 at 3 47 02 PM" src="https://user-images.githubusercontent.com/5950956/67898825-0ce6d580-fb2f-11e9-8434-a9cda6add904.png">

**Comment by cartant** [comment]
This is not actionable without an explanation of how the error is effected and a minimal reproduction.
