### ISSUE TITLE
When using Subscribables compositionally, types are lost

### ISSUE THREAD

**Issue by alshdavid** [ReactiveX/rxjs#5119]
## Bug Report

**Current Behavior**
When using a subscribable compositionally inside a TypeScript class, type information is lost.

In the snippet below, TypeScript should be able to infer the type for `Consumer.subscribe`

```typescript
class Consumer {
    get subscribe() {
        return this.thing.subscribe.bind(this.thing)
    }

    constructor(
        private thing: Observable<string>
    ){}
}
```

**Reproduction**
- REPL or Repo link:
http://www.typescriptlang.org/play/#code/JYWwDg9gTgLgBAbzgeQEYGcCmUBuBDVAG0zgF84AzKCEOAcigA8ArdOgKHYGNC9104AYQgA7dAFcQ2ROzhy4Ac0zwJGLlGCpMACgCUM+YbhRl4qCLgwAFsHQA6a8BEK7q9Os2Y7qJwBNtjvaOzrqy8qSchlyi6DBQ4lww0NphRnBgGvgwJMEKAFwoGNj4RJgAPLEazgB8qXC6CBER3DHwEHAAvHAimADuhVi4BMQVcU4K1XotYvBcnd19QjGS2NoQoewA9JtwAKKMYJiJcABEOCeW7VpwEBSWAJ6Hp5XjJ9yu4moaWto4ndUGeTRMQQYh2QgQBS-UKkDZAA

**Expected behavior**
The `subscribe` method on the parent class should have properly inferred type information.

**Environment**
- Runtime: TypeScript playground
- RxJS version: Lastest (I think)
- (If bug is related) Loader, build configuration: No

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by alshdavid** [comment]
In addition, composition the old way doesn't work either

```typescript
import { Observable } from 'rxjs'

const o = new Observable<string>()
const c = { 
    ...o
}

// Expect "v" to be of type "string"
c.subscribe(v => {
    console.log(v)
})

```

http://www.typescriptlang.org/play/#code/JYWwDg9gTgLgBAbzgeQEYGcCmUBuBDVAG0zgF84AzKCEOAcigA8ArdOgKE4GMIA7deBDgBeOL0wB3FBmz4imADwCowXgHMAfAAoAlOx794XEYjjs4FuADobEdqU4B6R3ACijMJi7wARDh9wMEKoJBAUgQCennA+yqpqPvpW6ACuGFwqIVo4IhqI5pYG6BDEVoQQatl6pHrsQA

**Comment by cartant** [comment]
Unlikely to be an RxjS issue. Check out the TypeScript `strictBindCallApply` compiler option.

**Comment by alshdavid** [comment]
Nice one, thanks for that.

https://codesandbox.io/s/sweet-mirzakhani-ebr7q
