### ISSUE TITLE
Receiver AbortController not defined when use in jest testing environment

### ISSUE THREAD

**Issue by dcs3spp** [ReactiveX/rxjs#5120]
## Bug Report

**Current Behavior**
Hi I trying to learn ```rxjs/fetchFrom``` within a typescript node environment. When I run a test I receive
**AbortController not defined** when use in jest testing environment. Not sure if this is a bug. If not are there any documentation or guidelines available for using this from testing environment.

**Reproduction**
- REPL or Repo link:
(you can use https://stackblitz.com/ to create one to attach here)
https://github.com/dcs3spp/rxjs_fromFetch_test

```typescript
import { Observable } from 'rxjs';
import { of } from 'rxjs';
import { catchError, switchMap, tap } from 'rxjs/operators';
import { fromFetch } from 'rxjs/fetch';


export type HttpError = {
  code?: string;
  message: string;
  stack?: string;
};

export class APIService<Model> {
  private fetch: (
    input: string | Request,
    init?: RequestInit,
  ) => Observable<Response>;

  /**
   * Constructor
   * To facilitate testing allow dependency injection of fetchFrom
   * @param fetch
   */
  constructor(
    fetchDependency: (
      input: string | Request,
      init?: RequestInit,
    ) => Observable<Response> = fromFetch,
  ) {
    this.fetch = fetchDependency;
  }

  all(url: string): Observable<Model[] | HttpError> {
    return this.fetch(url).pipe(
      /**
       * fetch does not trigger catchError for http error status codes returned by the server
       * fetch triggers a catchError when errors occur client side
       */
      tap(response => {
        console.log(`Fetch response is ${response}`);
      }),
      switchMap(response => {
        if (response.ok) {
          return response.json() as Promise<Model[]>;
        } else {
          return of({
            message: `Error ${response.statusText}`,
            code: `Error ${response.status}`,
          });
        }
      }),
      tap(data =>
        console.log(`APIService data => ${JSON.stringify(data, null, 2)}`),
      ),
      catchError(err => {
        // Errors such as network connection errors, timeout etc caught here
        console.error(err);
        return of({ message: err.message });
      }),
    );
  }
}
```
**test**
``` typescript
import { APIService } from './service';

import { Observable } from 'rxjs';

describe('course services', () => {
  test('generic course service', () => {
    console.log('generic course service spec');
    const api: APIService<string> = new APIService<string>();
    api.all('https://localhost:3000').subscribe(
      data => {
        console.log(`Test all data => ${JSON.stringify(data, null, 2)}`);
      },
      err => {
        console.error(`Test all err => ${JSON.stringify(err, null, 2)}`);
      },
    );
  });
});
```
**Expected behavior**
No AbortController exception defined message displayed

**Environment**
- Runtime: [e.g. Node v${x}, Chrome v${x}]: Node v10.16.0 and Typescript 3.6.4
- RxJS version: 6.5.2
- (If bug is related) Loader, build configuration: [e.g webpack, angular-cli version, config]

**Possible Solution**

Document configuring fetchFrom within test environment, such as jest

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by kwonoj** [comment]
`AbortController` is not available in nodejs yet. Same as `ajax`, all interface provided under `dom/` can use browser-only api and it's up to consumers responsibility to use necessary polyfill if required.

**Comment by dcs3spp** [comment]
> `AbortController` is not available in nodejs yet. Same as `ajax`, all interface provided under `dom/` can use browser-only api and it's up to consumers responsibility to use necessary polyfill if required.

Many thanks @kwonoj for your help. Appreciated....

I am now using rxjs with [axios](https://github.com/axios/axios):
1. Can run in nodejs with no additional polyfills.
2. Network connection errors are explicitly reported for status code 0. 
3. Clear distinction between Http error response and errors setting up the response with no additional boilerplate code required.
