### ISSUE TITLE
Observable and class inheritance

### ISSUE THREAD

**Issue by TrejGun** [ReactiveX/rxjs#5122]
I would know the best practive for my case because I used to write this code all the time but i really dont like it. I'm going carefully describe how I come to this so be patien adn dont close the issue before you finish)

In the simplest case I have classes A and B

```js
class A {
  method(bool: boolean): boolean {
    return bool;
  }
}

class B extends A{
  public method(bool: boolean): boolean {
    return bool;
  }
}
```

Then I deciced to make my calculation async

```js
import {Observable, from} from "rxjs";

class A {
  method(bool: boolean): boolean | Promise<boolean> | Observable<boolean> {
    return bool;
  }
}

class B extends A {
  public method(bool: boolean): Observable<boolean> {
    return from([bool]);
  }
}

class C extends A {
  public async method(bool: boolean): Promise<boolean> {
    return Promise.resolve(bool);
  }
}
```

And in the final step B.method has to be async and return Observable

```js
class B extends A {
  public async method(bool: boolean): Promise<Observable<boolean>> {
    const result = await Promise.resolve(!bool);
    return from([result]);
  }
}
```

But there is not much sence to have Promise<Observable<boolean>> so I want to flatten it to just 
Observable<boolean> and I ended up with 

```js
class B extends A {
  public method(bool: boolean): boolean | Promise<boolean> | Observable<boolean> {
    return concat(
      from(
        Promise.resolve(!bool).then(result => from([result]))
      ),
    ).pipe(mergeAll());
  }
}
``` 

which i don't really like. So is there more elegant way to convert Promise<Observable<boolean>> to just Observable<boolean> ?

**Comment by cartant** [comment]
In all seriousness, I think the best practice would be to not do stuff like this:

```ts
method(bool: boolean): boolean | Promise<boolean> | Observable<boolean>
```

**Comment by TrejGun** [comment]
@cartant I agree with you on bad signature. But the problem still exists. 

This signature is not something invented by me yesterday, here is an example of this problem in one of the most used typescript frameworks

https://github.com/nestjs/nest/blob/master/packages/common/interfaces/features/can-activate.interface.ts#L22

**Comment by cartant** [comment]
My understanding is that you have a solution that you don't like. I'm not convinced that the lack of an 'elegant' - in your opinion - solution to your situation is a problem.

**Comment by TrejGun** [comment]
yeah I can always use `any` :)
