### ISSUE TITLE
expectObservable() gives unexpected result 

### ISSUE THREAD

**Issue by andkh** [ReactiveX/rxjs#5130]
Hi there,

I face with issue when **expectObservable()** gives unexpected result when I try to test asynchronous func. Maybe I'm missing something.
When I use **expect().toBeObservable()** everything is fine. But I want to use **TestScheduler** as well.
Should we use and why we should use **expectSubscriptions()** or **subscriptionMarbles**? What I did wrong?

**Errors:**
> First case RestClient > responseHandle() > should return result:
> Expected $[0].frame = 3 to equal 1.
> Expected $[1].frame = 4 to equal 2.

> Second case RestClient > responseHandle() > should return error message if some Error
> Expected $[0].frame = 5 to equal 1.

Here is code example.
```
...
export class RestClient extends HttpClient {
  responseHandle<T>(response: Observable<T>, config): Observable<T> {
    return response
      .pipe(
          map(response => this.responseSuccess<T>(response, config)),
          catchError(error => this.responseError(error, config))
    );
  }
}
...

describe('RestClient', () => {
  const testScheduler = new TestScheduler((actual, expected) => {
    expect(actual).toEqual(expected);
  });

  let service: RestClient;

  beforeEach(() => {
    TestBed.configureTestingModule({
      imports: [HttpClientTestingModule],
      providers: [
        RestClient,
      ]
    });
    service = TestBed.get(RestClient);
  });

 describe('responseHandle()', () => {
    it('should return success result', () => {
      testScheduler.run((helpers) => {
        const { cold, expectObservable } = helpers;
        const marbleValues = { a: { name: 'TestName', age: 28 } };
        const observable = cold('-a|',  marbleValues);

        const responseSuccessSpyOn = spyOn(service, 'responseSuccess');
        responseSuccessSpyOn.and.callFake((response) => response);

        expectObservable(service.responseHandle(observable, {})).toBe('-a|', marbleValues);
        responseSuccessSpyOn.calls.reset();
      });
    });

    it('should return error message if some Error', () => {
      testScheduler.run((helpers) => {
        const { cold, expectObservable } = helpers;
        const observable = cold('-#', null, 'error');

        const responseErrorSpyOn = spyOn(service, 'responseError');
        responseErrorSpyOn.and.callFake(error => error);

        expectObservable(service.responseHandle(observable, {})).toBe('-#', null, 'error');
        responseErrorSpyOn.calls.reset();
      });
    });
  });
});
```

Best regards, 
Andrii

**Comment by cartant** [comment]
> when I try to test asynchronous func

I'm not familiar with testing HTTP functionality in Angular, but the `TestScheduler` does not support testing asynchronous code.

**Comment by andkh** [comment]
@cartant , thank you for quick response.

So, now we can test only sync code or **timers, like delay/debounceTime**  as described in documentation? https://rxjs-dev.firebaseapp.com/guide/testing/marble-testing.
If we want to test **async** code like **Observables**, we will use **jasmine-marbles** or **jest-marbles**. Correct?

> We can test our **asynchronous** RxJS code synchronously and deterministically by virtualizing time using the TestScheduler. At this time the TestScheduler can only be used to test code that uses **timers, like delay/debounceTime/etc (i.e. it uses AsyncScheduler with delays > 1)**. If the code consumes a Promise or does scheduling with AsapScheduler/AnimationFrameScheduler/etc it cannot be reliably tested with TestScheduler

Best regards,
Andrii

**Comment by cartant** [comment]
The `TestScheduler` can only test asynchrony that's introduced via an RxJS scheduler. If there is some other form of asynchrony - e.g. a promise or a `setTimeout` call or whatever - it cannot be tested with the `TestScheduler`.

I had another look at your code and there doesn't seem to involve any non-scheduler asynchronous code. I think the problem is that you are calling `responseErrorSpyOn.calls.reset();` before returning from the `run` callback. Be aware that the `TestScheduler` calls `flush` implicitly once the `run` callback returns - by which time you've reset your spies. Try calling `flush` before you reset:

```ts
const { cold, expectObservable, flush } = helpers;
// ...
flush();
responseErrorSpyOn.calls.reset();
```

**Comment by andkh** [comment]
Everything is clear. Thank you for the clarifications. I think issue can be closed.
