### ISSUE TITLE
shareReplay docs are missing

### ISSUE THREAD

**Issue by jgbpercy** [ReactiveX/rxjs#5133]
### Documentation Related To Component:

shareReplay operator docs: https://rxjs.dev/api/operators/shareReplay

### Issue

Documentation doesn't exist

### Description Of The Issue

The [shareReplay docs](https://rxjs.dev/api/operators/shareReplay) don't seem to have any content. This might just be a bug, given this has [been raised in the past](https://github.com/ReactiveX/rxjs/issues/3819)? Edit: Is this just because the [JSDoc comment precedes the overloads rather than the actual function](https://github.com/ReactiveX/rxjs/blob/8cc6491771fcbf44984a419b7f26ff442a5d58f5/src/internal/operators/shareReplay.ts#L58)? 

shareReplay is a useful and commonly used operator. It can also be [complex and confusing](https://github.com/ReactiveX/rxjs/issues?utf8=%E2%9C%93&q=is%3Aissue+%22sharereplay%22+in%3Atitle+), especially around [whether the operator reference counts by default and when it unsubscribes from the source](https://blog.angularindepth.com/rxjs-whats-changed-with-sharereplay-65c098843e95), so good docs here would add a lot of value.

**Comment by dzhavat** [comment]
It looks like this is due to the docs generally being "behind" the repo. The docs were last updated on Sep 3rd (when v6.5.3 was released). And the latest changes to the shareReplay source file are from Oct 19th. 

So the issue should be fixed with the next release.

**Comment by dzhavat** [comment]
Or maybe the same changes from #5068 should be applied to `6.x` branch as well?

**Comment by markonyango** [comment]
The docs were expanded by me some time ago and the changes are in the master branch:
https://github.com/ReactiveX/rxjs/blob/master/src/internal/operators/shareReplay.ts

Could this be a deployment issue?

**Comment by dzhavat** [comment]
It's probably not a deployment issue. Your changes were merged in `master` branch which is used for working on v7. So your changes will first land in the docs after v7 is released.

**Comment by markonyango** [comment]
Then applying it to the current 6.x branch might/should be a possible solution.

**Comment by cartant** [comment]
`shareReplay` is documented in the v7 docs. And in the updated v6 docs: https://v6.rxjs.dev/api/operators/shareReplay
