### ISSUE TITLE
Internal typing of "pipe" method

### ISSUE THREAD

**Issue by alshdavid** [ReactiveX/rxjs#5139]
## Feature Request

**Is your feature request related to a problem? Please describe.**

When trying to describe a type which has the ability to be piped, we use a large overloading chain.

![image](https://user-images.githubusercontent.com/12656294/68639457-bb8c0c80-0558-11ea-9167-3b34b100ff6d.png)

This is so we can have operators appear in sequence and the resulting type can be be reflected using type inferal.

```typescript
// observable is Observable<string>
const observable = new Observable()
  .pipe(
     map(v => 1),
     map(v => 'Hi'),
  )
```

The following syntax results in the same outcome

```typescript
// observable is Observable<string>
const observable = new Observable()
  .pipe(map(v => 1))
  .pipe(map(v => 'Hi'))
```

As a result the 'pipe' interface would just need to be:

```typescript
export interface Pipeable<T> {
  pipe<A>(op: OperatorFunction<T, A>): Observable<A>;
}
```

This would reduce the repetition in how `pipe` is described and also expose a useful interface `Pipeable`

**Comment by alshdavid** [comment]
To extend this, perhaps it's the job of an external function to handle combining pipes

```typescript
import { combinePipes } from 'rxjs'
import { map } from 'rxjs/operators'

const myPipe = combinePipes(
   map(v => 1),
   map(v => 'Hi'),
)

// observable is Observable<string>
const observable = new Observable()
  .pipe(myPipe)
```

**Comment by cartant** [comment]
> This would reduce the repetition in how `pipe` is described and also expose a useful interface Pipeable

Why is the typing of the `pipe` method an issue for you? Maybe others don't want to have `pipe` wrapped around each operator?

Regarding your using an interface, in TypeScript types are structural - not nominal - so there is nothing preventing you from doing this.

And there is already a static `pipe` that's the equivalent of `combinePipes`.

**Comment by kwonoj** [comment]
Closing as stale, as we believe internal implementation of pipe definition doesn't causes issues to actual consumer so far and haven't heard details yet.
