### ISSUE TITLE
combineSuccess - if first observable returns null/undefined, return value of second observable

### ISSUE THREAD

**Issue by pdancewicz** [ReactiveX/rxjs#5140]
## Feature Request

Proposal of a new operator which will subscribe return second observable if value returned from first one will be null or undefined.

**Describe the solution you'd like**
Pretty much selfexplonatory

**(If this is new operator request) describe reason it should be core operator**
IMHO it will be very helpful

**Additional context**
smth like:
`const combineSuccess = (firstObservable: Observable<any>, secondObservable: Observable<any>): Observable<any> => {
  return firstObservable.pipe(
    switchMap(value => {
      if (!value) {
        return secondObservable;
      }
      return of(value);
    })
  );
};`

**Comment by kwonoj** [comment]
As our issue template / guideline (/doc/operator-creation.md@master#publish-your-operator-as-a-separate-library ) recommends, I'd like to suggest to publish as userlevel module first. We can discuss to include into core based on usecases later.
