### ISSUE TITLE
Missing images in documentation

### ISSUE THREAD

**Issue by Undeadlol1** [ReactiveX/rxjs#5142]
### Documentation Related To Component:

tap, every

### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [x] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue
First, "tap" documentation page is not loading diagram image.
When i go to:
https://rxjs-dev.firebaseapp.com/api/operators/tap
This is what i see:
![image](https://user-images.githubusercontent.com/4124323/68677749-711d8680-057e-11ea-8fd7-81c6f54afb25.png)
Image url is https://rxjs-dev.firebaseapp.com/do.png (which doesn't exist).

Second, "every" is missing description.
![image](https://user-images.githubusercontent.com/4124323/68678150-3c5dff00-057f-11ea-90d8-b8e93886736f.png)
This seems to be an error because there is a proper description in "every.ts" file.

Also, when i tried to run project locally to submit a PR, i encountered some strange behavior.
After running "npm run serve-and-sync", project automatically generated missing images and loaded documentation without any errors.
![image](https://user-images.githubusercontent.com/4124323/68678635-20a72880-0580-11ea-8544-5c9fca14488f.png)

**Comment by jakovljevic-mladen** [comment]
The issue with `tap` is fixed in #4934. PR #4777 fixed an issue with `every` operator.

Closing for now, thanks for reporting @Undeadlol1.
