### ISSUE TITLE
interval() accumulates error

### ISSUE THREAD

**Issue by wereHamster** [ReactiveX/rxjs#5145]
## Bug Report

**Current Behavior**

Let's say I use the `interval()` function to generate an event every S seconds, and then take N of these events. The last event will be delivered much later than S*N, because the error (inherent how async events are delivered) is accumulated across all intervals.

The `interval()` function doesn't take into account that the async scheduler calls the callback with a slight delay, and doesn't adjust the next period accordingly.

**Reproduction**

The following observable should deliver the last event after ~1000s, but depending on how busy the system is, it may happen at much later time (in the order of dozens of seconds later).

```js
interval(1000).pipe(take(1000))
```

**Expected behavior**

The `interval()` function should take into account the delay between the desired delay and actual delay and adjust the next interval accordingly.

**Environment**
- Runtime: Node v12
- RxJS version: 6.5.3

**Comment by kwonoj** [comment]
I believe there was similar q somewhere but failed to search. @benlesh can double confirm - afaik this is expected, we try best to put an action in the queue with properly specified time but do not guarantee each action's margin bubbles up into queue execution time.

**Comment by wereHamster** [comment]
That makes `interval()` more like a recursive / recurring `setTimeout()` instead of a `setInterval()`… I think that is unfortunate since this makes it impossible to implement an accurate timer.

**Comment by cartant** [comment]
It should not be the case that the next period needs any adjustment. All of the async functionality is implemented using `setInterval` and when the period/duration is unchanged, `clearInterval` is not called and new interval is not created:

https://github.com/ReactiveX/rxjs/blob/5bbf0aae880052fc676868c3be716f7888c036a4/src/internal/scheduler/AsyncAction.ts#L77-L79

So the behaviour should be identical to using `setInterval` alone.

**Comment by wereHamster** [comment]
Alright. I'll investigate my code closer. I've previously had code in the form of `interval(1000).pipe(take(1000))` and I've changed it to something like this and it solved any unwanted delays:

```
merge(...Array.from({ length: N }).map((_, t) =>
  interval(((t + 1) * 1000).pipe(take(1), mapTo({ type: "VCLOCK" }))
)
```

Essentially generate N events, each emitted at a different interval.

**Comment by wereHamster** [comment]
Ok, it appears to be an issue with setInterval as well. I created this script which tests the drift of a single setTimeout, a setInterval which counts to the end, and an observable which uses interval().

```
const { interval } = require("rxjs");
const { endWith, mapTo, take } = require("rxjs/operators");

const HZ = 10;
const timeLeft = 60;

const obs = interval(1000 / HZ).pipe(
  take(timeLeft * HZ),
  mapTo({ type: "VCLOCK" }),
  endWith({ type: "END" })
);

const t0 = Date.now();

function log(s) {
  const t = Date.now();
  console.log(`[${((t - t0) / 1000).toFixed(3).toString().padStart(8)}]`, s);
}

log("start");
setTimeout(() => {
  log("setTimeout end");
}, timeLeft * 1000);

let counter = 0;
setInterval(() => {
  if (counter++ === timeLeft * HZ) {
    log("setInterval end");
  }
}, 1000 / HZ);

obs.subscribe(ev => {
  if (ev.type == "END") {
    log('observable interval end');
  }
});
``` 

The output indicates that setInterval and observable interval are delayed by almost two seconds:

```
[   0.000] start
[  60.016] setTimeout end
[  61.831] observable interval end
[  61.932] setInterval end
```

**Comment by kwonoj** [comment]
Js timer is not high resolution timer from beginning. Not sure about diff though.

**Comment by kwonoj** [comment]
Closing as this occurs in bare js.
