### ISSUE TITLE
Use Lerna for multi-package support

### ISSUE THREAD

**Issue by cartant** [ReactiveX/rxjs#5152]
My understanding is that, at some stage, we want to be able to publish multiple packages from this repository. In particular, we'd like this repo to also include packages containing ESLint rules (and, IMO, TSLint rules, as TSLint is going to be around from some time) for RxJS.

To do this, changes are going to need to be made to the repo. One possibility is to use [Lerna](https://github.com/lerna/lerna) to manage this. What will be involved in that and how we should go about it, IDK, but we can discuss it here.

@JWO719

**Comment by kwonoj** [comment]
fyi: https://github.com/atlassian/changesets

also recently I've started exploring bazel (https://bazel.build/) and it is actually quite good to organize build systems. We've talked about this few times while it never landed - maybe we could consider now since I can try to work on this.
