### ISSUE TITLE
Error in Operator Decision Tree for switchMap

### ISSUE THREAD

**Issue by Trildar** [ReactiveX/rxjs#5154]
### Documentation Related To Component:

Operator Decision Tree

### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [ ] documentation needs clarification
- [x] error(s) in example
- [ ] needs example

### Description Of The Issue

The Operator Decision Tree relating to switchMap appears to have some issue. It recommends exhaustMap before actually hitting a leaf node and is missing the option for "where the nested Observable is the same for every value". The below screenshot should clarify what I mean.
<img width="728" alt="image" src="https://user-images.githubusercontent.com/17514824/69226916-f24ace00-0bbb-11ea-9f12-5798a7e4930d.png">

**Comment by dzhavat** [comment]
Just tried to recreate this. I started the docs locally and this is what I get when I navigate to the same step:

![image](https://user-images.githubusercontent.com/1096332/69890240-0ba6f500-12f5-11ea-8719-321a3de9d952.png)

Can it be that the issue has already been fixed but it's still not deployed yet?

**Comment by Fallenstedt** [comment]
@jsonberry I think you worked on this right?

**Comment by jsonberry** [comment]
Yes

I was able to replicate on current deployment, not sure of the version

It’s possible that the only thing required is a fresh generation and
deployment of the JSON that runs the ODT, and not a version bump on the
docs app itself

Haven’t looked into actual debugging yet, will attempt to do that soon
unless someone else with deployment powers can take a look at it

**Comment by dzhavat** [comment]
@Trildar the docs were updated earlier today. Can you check if you still get that error? :)

**Comment by jsonberry** [comment]
On version `6.5.5-local+sha.7e4589a1` of the docs released to prod I'm unable to reproduce the bug, poked around a bit on it and haven't seen any issues.
<img width="720" alt="RxJS" src="https://user-images.githubusercontent.com/3082536/71536649-7af91000-28c6-11ea-9826-86ab1953188f.png">

**Comment by dzhavat** [comment]
If that's the case, can the issue be closed?

**Comment by Trildar** [comment]
Hi, sorry, forgot to check on this. Seems fine checking on my phone, albeit that's not what I used when I noticed the issue. Will try to check on that if I remember.

**Comment by Trildar** [comment]
Checked on the platform where I first encountered the issue. Seems to be fixed. Though I did have to reload the page once, likely due to cache.

**Comment by dzhavat** [comment]
In that case the issue can be closed :)
