### ISSUE TITLE
repeat() operator behavior

### ISSUE THREAD

**Issue by kwonoj** [ReactiveX/RxJS#516]
In some cases it seems resubscription does not triggered correctly. for example, 

`Rx.Observable.interval(40).take(2).repeat(2).subscribe(console.log, null, function(){console.log('completed')});`

*RxJS4*
>0
1
0
1
completed

*RxJS5*
>0 
1 
(does not complete)

**Comment by kwonoj** [comment]
I'll try to look into this as well as expanding test coverages of `repeat` operator.

**Comment by blesh** [comment]
It's possible that this and `catch` suffer from the same bugs `retry` and `retryWhen` do, as described here #546

**Comment by kwonoj** [comment]
I just gave a try quick code snippet like 

```
Observable.create(function (observer) {
  observer.error('bad');
  return function () {
    console.log('tear down');
  };
}).repeat(2).subscribe(console.log, console.log, function () {console.log('complete')});
```

which shows result as
>bad
tear down

between RxJS4 and this implementation both. Can this be considered as passing sign, or did I try it incorrectly?

**Comment by blesh** [comment]
Thanks @kwonoj.
