### ISSUE TITLE
Property 'lift' in type 'Subject<T>' is not assignable to the same property in base type 'Observable<T>'.

### ISSUE THREAD

**Issue by CoreySchnedl** [ReactiveX/rxjs#5162]
## Bug Report

**Current Behavior**
ng build error: 

ERROR in libs/rxjs/Subject.d.ts(24,5): error TS2416: Property 'lift' in type 'Subject<T>' is not assignable to the same property in base type 'Observable<T>'.
  Type '<R>(operator: Operator<T, R>) => Observable<T>' is not assignable to type '<R>(operator: Operator<T, R>) => Observable<R>'.
    Type 'Observable<T>' is not assignable to type 'Observable<R>'.
      Type 'T' is not assignable to type 'R'.
libs/rxjs/observable/dom/WebSocketSubject.d.ts(44,5): error TS2416: Property 'lift' in type 'WebSocketSubject<T>' is not assignable to the same property in base type 'AnonymousSubject<T>'.
  Type '<R>(operator: Operator<T, R>) => WebSocketSubject<R>' is not assignable to type '<R>(operator: Operator<T, R>) => Observable<T>'.
    Type 'WebSocketSubject<R>' is not assignable to type 'Observable<T>'.
      Types of property 'operator' are incompatible.
        Type 'Operator<any, R>' is not assignable to type 'Operator<any, T>'.
          Type 'R' is not assignable to type 'T'.

**Reproduction**
- REPL or Repo link:
typescript: "2.7.2"
rxjs: "6.2.1"
rxjs-compat: "^6.5.2"

**Expected behavior**
I am expecting the build to pass without error, but I get an error. Adding "skipLibCheck" fixes the issue, but I don't believe that should be necessary. Issue seems similar to https://github.com/ReactiveX/rxjs/issues/3355. 

**Environment**
- Runtime: using Node v12.13.0, npm 6.12.0, Angular CLI 6.0.8. 
- RxJS version: 6.2.1

**Comment by kwonoj** [comment]
Please ensure if there's no conflicting rxjs installation under node_modules, and please provide reproducible code.

**Comment by cartant** [comment]
Also, IIRC, TypeScript 2.8 is the minimum-supported version for RxJS v6.

**Comment by CoreySchnedl** [comment]
I have done a clean-install and still get the error. 

Unfortunately, I am not able to pinpoint the exact code that is causing the issue, because the stack trace doesn't give me any info pointing me towards code I can fix. I don't know if there is a way I can give code to reproduce as it is part of a pretty big code base. 

I am able to get the build to pass by adding either skipLibCheck or noStrictGenericsCheck. Just reporting this, because all the issues related to this seem to indicate to upgrade to v6, but I am getting this issue in v6 as well.

Any info would be greatly appreciated.

**Comment by CoreySchnedl** [comment]
> Also, IIRC, TypeScript 2.8 is the minimum-supported version for RxJS v6. And, FWIW, I always enable `skipLibCheck` and IMO it should default to `true`.

I was unaware that Typescript 2.8 is the minimum. It seems like I can't go to typescript 2.8 without upgrade to angular 7, which might be my final solution. In the meantime I will keep using skipLibCheck.
