### ISSUE TITLE
Guard operator to filter the undefined or null object with type safe

### ISSUE THREAD

**Issue by Zcating** [ReactiveX/rxjs#5163]
When I use `filter` operator to filter some null or undefined object, the next operator can't infer the object without null or undefined.
So I sincerely hope could support this feature as follow: 
``` typescript
const some = new BehaviorSubject<{name: string} | null>(null);

const notNullSome = some.pipe(
    guard(),
    tap((theSome) => {
        // will only print {name: 'tony'}
        console.log(theSome);
    })
)

some.next({name: 'tony'});
```

**Comment by cartant** [comment]
You should be able to use `filter(Boolean)` to do this. An additional operator is not warranted, IMO.

**Comment by Zcating** [comment]
However, the `filter` can't infer the RIGHT type in strict mode.
e.g :
```
const some = new BehaviorSubject<{name: string} | null>(null);

const notNullSome = some.pipe(
    filter(value => !!value),
    tap((theSome) => {
        // occur complie error 
        console.log(theSome.name);
    })
)

some.next({name: 'tony'});
```

**Comment by kwonoj** [comment]
What @cartant said is using `Boolean` fn, literally `filter(Boolean)` instead of truthy conversion `!!value`.

**Comment by Zcating** [comment]
It infer to any.

**Comment by kwonoj** [comment]
![image](https://user-images.githubusercontent.com/1210596/69697486-70fdaa80-1097-11ea-9e0d-0b3ea57ab2a2.png)

I believe it's version difference, rx@6 might not pick up these changes yet.

**Comment by cartant** [comment]
Yeah, it looks like the `Boolean` signature change has not been backported.

v6: https://github.com/ReactiveX/rxjs/blob/9f87505deae0aeae7dd53918e392487d6de7ab73/src/internal/operators/filter.ts#L6-L11

master/v7: https://github.com/ReactiveX/rxjs/blob/860fc34a1d1a5e030c3338936fac9eefdb5d6974/src/internal/operators/filter.ts#L6-L13

**Comment by Zcating** [comment]
What a weird thing, my rxjs version is 6.5.2.
![Screen Shot 2019-11-27 at 14 02 59](https://user-images.githubusercontent.com/13329558/69698040-2aec2980-111f-11ea-9b3e-ff1581eb6abc.png)

**Comment by Zcating** [comment]
Thx for helping me. @cartant @kwonoj

**Comment by cartant** [comment]
ATM, in v6, you can write your own user-defined type guard to get `filter` to behave the way you want. Have a look at: https://github.com/cartant/rxjs-etc/blob/5447f8901e390894acdb29623e88a3cc184b1f4d/source/util.ts#L15-L20
