### ISSUE TITLE
Searching for `empty` does not return `throwIfEmpty`

### ISSUE THREAD

**Issue by Dorus** [ReactiveX/rxjs#5165]
Searching for `empty` does not return `throwIfEmpty` on https://rxjs.dev/

**Comment by BioPhoton** [comment]
Very funny you are right. 

When i search for "empt" it shows up. 

In the [references](https://rxjs.dev/api?query=empty) it shows up properly.

**Comment by Dorus** [comment]
The cause might be because the whole description of `throwIfEmpty` does not contain the word 'empty' independent. On the other hand, `throwError` does shows up, possibly because 'empty' is mentioned under "See Also".

**Comment by Dorus** [comment]
Also `throwIfEmpty` is not listed on the Operator Decision Tree. (tree.yml)

**Comment by cartant** [comment]
This appears to be fixed in the v7 docs. (

**Comment by benelliott** [comment]
Hi @cartant - I think this issue has recurred. I noticed `retry` doesn't show when searching `retry` but the above issue with `empty` is also present.
