### ISSUE TITLE
CI script includes a build check for TypeScript 3.5

### ISSUE THREAD

**Issue by cartant** [ReactiveX/rxjs#5166]
The current CircleCI build script includes a build step that [uses TypeScript 3.5](https://github.com/ReactiveX/rxjs/blob/84706388b0e1db35f0ae443ed58de6a31253cea4/package.json#L148). However, the package's current version of [TypeScript is 3.7](https://github.com/ReactiveX/rxjs/blob/84706388b0e1db35f0ae443ed58de6a31253cea4/package.json#L148).

I can see that this relates to what we were checking for with v6 of RxJS - where the minimum supported version of TypeScript is 2.8, but we wanted to make sure it worked with TypeScript 3 - but would we be better off using `typescript@next` in this build check?

**Comment by kwonoj** [comment]
When we use travis we once had matrix to use @ next version and dropped, when we made ci fail for it there were lot unexpected failure / when we allowed it to fail we really didn't care even it fails.

I'm in for those idea in general but how to proactively notified & work forward is something to think about.

**Comment by cartant** [comment]
Maybe we just need a reminder to bump it so that it stays ahead of whatever the minimum for v7 is going to be, but isn't too experimental? It should be at least 3.7 ATM though, IMO.
