### ISSUE TITLE
`@deprecated` annotation used for `@internal` intent

### ISSUE THREAD

**Issue by edbzn** [ReactiveX/rxjs#5171]
Hi, 

I'm wondering if there is a good reason to use the `@depracated` doc annotation instead of `@internal` for internal code members usage. For example:

```ts
  /** @deprecated This is an internal implementation detail, do not use. */
  _subscribe(subscriber: Subscriber<T>) {
    return this.getSubject().subscribe(subscriber);
  }
```

Moreover using `@internal` in combination with:

```json
{
    "compilerOptions": {
        "stripInternal": true
    }
}
```
The annotated member is removed from generated `d.ts` file and consequently prevents package users from using internal implementation details.

**Comment by cartant** [comment]
I remember asking this, but I cannot recall the answer. I thought it might have had something to do with the Closure compiler, but [that doesn't seem to be the case](https://github.com/google/closure-compiler/blob/faa896e0de117ece80e96d64c68dcacb7217da03/src/com/google/javascript/jscomp/parsing/Annotation.java#L22-L83).

**Comment by edbzn** [comment]
I close the issue since v8 will solve this.
