### ISSUE TITLE
Wired Subject behavior

### ISSUE THREAD

**Issue by Brooooooklyn** [ReactiveX/rxjs#5173]
## Bug Report

**Current Behavior**
```js
const rxjs = require('rxjs')

const subject = new rxjs.Subject()

subject.subscribe({
  next: (v) => {
    if (v === 1) {
      subject.next(2)
    }
  }
})

subject.subscribe({
  next: (v) => {
    console.log(v)
  }
})

subject.next(1)

```

log 2
log 1

**Reproduction**
- REPL or Repo link:
https://stackblitz.com/edit/typescript-pw115w

```js
var your => (code) => here;
```

**Expected behavior**
log 1
log 2

**Environment**
- RxJS version: 6.5.3

**Comment by cartant** [comment]
It might seems weird, but this the expected behaviour. Subscribers are notified in the order in which they subscribe and your first subscriber effects another next notification - essentially re-entering the notification if the subscribers.

**Comment by kwonoj** [comment]
This is typical reentrant example and answer is well explained.
