### ISSUE TITLE
Unexpected synchronous behavior of map/switchMap

### ISSUE THREAD

**Issue by ivan7237d** [ReactiveX/rxjs#5174]
## Bug Report

**Current Behavior**
The following code outputs 1, then 0.

```js
const subject = new BehaviorSubject(0);
subject
  .pipe(
    map(value => {
      if (value === 0) {
        subject.next(1);
      }
      return value;
    }),
  )
  .subscribe(console.log);
```

**Reproduction**
https://stackblitz.com/edit/rxjs-mbgssc?devtoolsheight=60

**Expected behavior**
The expected behavior is that the order would be 0 then 1. 

**Environment**
- RxJS version: 6.5.2

**Additional context**
The actual, a little bit more complicated issue that I've run into IRL is reproduced by the following Stackblitz: https://stackblitz.com/edit/rxjs-ylzbfn?devtoolsheight=60. There, the switchMap operator is subscribed to two inner observables at the same time (console outputs 2 values every second, but should output only 1 value every second). While investigating that issue, I've run into the above-described unexpected behavior of the map() operator, so I thought I'd like to clear that one up first.

**Comment by kwonoj** [comment]
Coincidentally same q has asked in same crux : https://github.com/ReactiveX/rxjs/issues/5173

This is due to you're doing reentrant synchronosly and expected behavior. Generally you need to handle properly via scheduling / escaping if you want to control order of emission via reentrant.

**Comment by ivan7237d** [comment]
@kwonoj thanks for the answer, but how can it be expected behavior that the switchMap operator is subscribed simultaneously to two inner observables (as in the second Stackblitz)? 

Also, maybe it would be helpful to describe what actually happened in a real-life app. There is a switchMap operator that converts a URL into what the user sees on screen. Normally all works fine, except when the user opens a homepage URL, because instead of mapping that URL to some UI, we redirect the user to some other page (like the last previously opened document) by setting the URL to a different value via History API. So in this case the browser's `location` is the equivalent of a Subject, and the whole thing is also synchronous. The result? Even though I haven't done anything obviously criminal, I see my switchMap operator emitting values corresponding to both the current URL and some previous URL, and the UI shown to the user flickers between two different views. The problem also was that while debugging this, I automatically assumed that switchMap can only be subscribed to one inner observable at a time, so it was the last line of investigation I tried.

**Comment by kwonoj** [comment]
It's not about which operator you use, as long as source is synchronous and if operater chain doesn't escape reentrant either explicit schedule or async operaters (naturally involves schdeduler, like delay) you'll see this.

This still applies to your real world example - it's hard to can say more detail without actual code: but regardless of source (either browser's native like `history` or subject) reentrant behavior is very tricky and hars footgun like you said: it's not you doing criminal behavior, nature of reentrant requires lot of attention. I usually strongly recommend to avoid reentrabt for this reason, or you have to completely cobtrol & aware what you do. Also in short switchmap doesn't gaurantee innersubscription details fyi.

**Comment by ivan7237d** [comment]
Yes, I'll definitely work around this by just setting URL asynchronously, but to be honest I still don't get how switchMap acting as mergeMap is something that it's allowed to do under any conditions. I could live with switchMap subscribing and unsubscribing in some nontrivial order, but when it indefinitely keeps emitting values from two async streams... this is really strange!
