### ISSUE TITLE
Enum based fromEvent API

### ISSUE THREAD

**Issue by fireflysemantics** [ReactiveX/rxjs#5181]
Currently:
```
    fromEvent(window, 'resize')
        .pipe(takeUntil(this.onDestroy))
        .subscribe(() => this._topOffset = null);
```
Requested:
```
    // On resize, the toolbar might change height, so "invalidate" the top offset.
    fromEvent(WindowEvents.RESIZE)
        .pipe(takeUntil(this.onDestroy))
        .subscribe(() => this._topOffset = null);
```

**Comment by kwonoj** [comment]
Enum creates additional runtime code / and some compatibility reason we can't use const enum, so as core lib I don't think we'll pursue this. Also note fromevent accepts any eventemitter-like, so if we type event with enums we may encounter unexpected edge cases.

**Comment by kwonoj** [comment]
Probably best middleground is wrap those fn on userland with typed enum so user can use typrs but core not dependent to it.

**Comment by cartant** [comment]
> ... some compatibility reason we can't use const enum

@kwonoj I wrote this so that I can reference it in future: https://ncjamieson.com/dont-export-const-enums/
