### ISSUE TITLE
Strange behavior switchMap operator

### ISSUE THREAD

**Issue by ValentinNikin** [ReactiveX/rxjs#5184]
## Bug Report

**Current Behavior**
I found that the library works incorrectly if number of operators in chain exceeds 9.
In this case I've got the following error:

"Type 'Observable<{}>' is not assignable to type 'Observable<boolean>'.
  Type '{}' is not assignable to type 'boolean'.ts(2322)"

**Reproduction**
Here are simplified examples:

In this case the compilation is succeed:
```js
tempFunction(): Observable<boolean> {
    return of(true).pipe(
      switchMap((res: boolean) => of(res)),
      switchMap((res: boolean) => of(res)),
      switchMap((res: boolean) => of(res)),
      switchMap((res: boolean) => of(res)),
      switchMap((res: boolean) => of(res)),
      switchMap((res: boolean) => of(res)),
      switchMap((res: boolean) => of(res)),
      switchMap((res: boolean) => of(res)),
      switchMap((res: boolean) => of(res)),
    );
  }
```

In this case it had failed:
```js
tempFunction(): Observable<boolean> {
    return of(true).pipe(
      switchMap((res: boolean) => of(res)),
      switchMap((res: boolean) => of(res)),
      switchMap((res: boolean) => of(res)),
      switchMap((res: boolean) => of(res)),
      switchMap((res: boolean) => of(res)),
      switchMap((res: boolean) => of(res)),
      switchMap((res: boolean) => of(res)),
      switchMap((res: boolean) => of(res)),
      switchMap((res: boolean) => of(res)),
      switchMap((res: boolean) => of(res)),
    );
  }
```

**Environment**
- RxJS version: 6.5.3
- Angular CLI version: 8.3.10
- typescript version: 3.5.3

**Comment by kwonoj** [comment]
it's somewhat similar to https://github.com/ReactiveX/rxjs/issues/4502, our overload supports up to 9 params currently.

**Comment by cartant** [comment]
This has more to do with `pipe` than `switchMap`. Closing in favour of https://github.com/ReactiveX/rxjs/issues/5599
