### ISSUE TITLE
shareReplay keeps subscription alive even with 0 subscribers

### ISSUE THREAD

**Issue by rarmatei** [ReactiveX/rxjs#5191]
## Bug Report

**Current Behavior**

As far I understand, `shareReplay(1)` should function like `share()`, except it keeps track of the last emission, so when a new subscriber appears, it immediately emits it to that new subscriber.

For both `share()` and `shareReplay()`, I would expect the observable to be disposed when it reaches 0 subscribers. This works for `share()` but not for `shareReplay()`.

See the following example:

**Reproduction**

https://stackblitz.com/edit/rxjs-s2u1y1

```js
console.clear();

const source = interval(1000).pipe(
  shareReplay(1)
);

const subscription = source.subscribe(x => console.log(x));

setTimeout(() => {
  console.log("unsubscribing...");
  subscription.unsubscribe();
}, 4000);

setTimeout(() => {
  console.log("RE-subscribing...");
  source.subscribe(x => console.log(x));
}, 8000);
```

**Expected behavior**

I would expect to see:

```js
0
1
2
3
unsubscribing...
RE-subscribing...
0 (or maybe 3 - if the behaviour is to remember the last value, even with zero subs)
...
```
But instead of a 0 or 3, we see a 7 - an indication that the interval kept firing in the background and was not stopped.

If we use a `share()` in the same example, it works as expected and starts from 0.

**Environment**
- Runtime: 79.0.3945.88 (Official Build) (64-bit)
- RxJS version: 6.5.2
---
Have I missed something or would this be unexpected?

**Comment by cartant** [comment]
Not a bug. `shareReplay` defaults to not reference counting - for an explanation of the history behind this, see https://ncjamieson.com/whats-changed-with-sharereplay/

If you want the subscription to the source to be reference counted, use a config argument:

```ts
    shareReplay({
      bufferSize: 1,
      refCount: true,
    })
```

**Comment by rarmatei** [comment]
That's very interesting! I learned something today - thanks for sharing! I'll close this and appreciate the quick reply!
