### ISSUE TITLE
Operator to repeat the latest emitted value on trigger

### ISSUE THREAD

**Issue by gioragutt** [ReactiveX/rxjs#5196]
## Feature Request

Create an operator, that on trigger (aka: `next` from another observable, like `repeatWhen`),
Would re-emit the latest value emitted by an observable.

**Is your feature request related to a problem? Please describe.**

It's often related to the `refresh` feature, where you have for example some search that happened, and you want to refresh the results.
That means that you have to re-emit the latest value emitted by the search-input observable.

**Describe the solution you'd like**
I imagine it looking something like this:

```typescript
const refreshTrigger = new Subject<void>();

fromEvent(input, 'keyup').pipe(
  repeatLatestWhen(refreshTrigger),
  debounceTime(300),
  map(...),
  switchMap(...),
).subscribe(values => showInView(values));

```

You'd have a `Refresh` button that would `next` the `refreshTrigger`, which would cause the latest emitted value from the `fromEvent` observable to be `next`ed.

**Describe alternatives you've considered**
Some alternatives I've used for this behaviour were:
1. use `combineLatest` with `Subject` (requires usage of `BehaviourSubject` instead of `Subject`, or manually trigger the `Subject` once), and map to the first value.
1. Creating a `Subject` only for the search trigger, subscribing to the input changes, with the subject, and `tap`ing into the input changes to save lates value in a class member (in an Angular component), and upon trigger `next` the subject with the latest value.

**(If this is new operator request) describe reason it should be core operator**

Of course this can technically be a user-land module, but I think that this is pretty common use-case, which a lot of people face, which would be a great bonus if the library would come built in with.

At first I thought I could use `repeatWhen`, but it turns out that the source observable has to complete, and `repeat` would cause the entire stream to be emitted.

Having an operator that helps you do something similar but with living streams (not completed ones) is something that would make sense.

Another option would be that `repeatLatestWhen` could also receive amount latest items to emit, like `replay`.

**Additional context**

I've implemented a very basic version of the operator:

```typescript
import { MonoTypeOperatorFunction, Observable } from 'rxjs';

/**
 * @param notifier when emits value, will trigger the last value repetition
 */
export function repeatLatestWhen<T>(notifier: Observable<any>): MonoTypeOperatorFunction<T> {
  return (source: Observable<T>) => new Observable(subscriber => {
    let latestValue: T;
    let hasLatestValue = false;

    const subscription = source.subscribe({
      next: value => {
        latestValue = value;
        hasLatestValue = true;
        subscriber.next(value);
      },
      error: err => subscriber.error(err),
      complete: () => subscriber.complete()
    });

    const repeatSubscription = notifier.subscribe(() => {
      if (!hasLatestValue || subscription.closed) {
        return;
      }

      subscriber.next(latestValue);
    });

    return () => {
      latestValue = null;
      subscription.unsubscribe();
      repeatSubscription.unsubscribe();
    };
  });
}
```

It makes sure that:
1. the normal notifications are passed as usual.
2. repeats would only occur only if a value has already been received, AND the subscription is still alive.
3. when unsubscribed, it would unsubscribe from the repeat subscription as well.
4. also set the `latestValue` to `null`, to not hold on to the latest value reference and cause it not to be GC`ed.

**Comment by martinsik** [comment]
@gioragutt I think it's still easier to do with just `combineLatest`:

```
const repeatLatestWhen = <T>(notifier$: Observable<any>) =>
  (source: Observable<T>) =>
    combineLatest([
      source,
      notifier$.pipe(startWith(null)),
    ]).pipe(
      map(([val]) => val),
    );
```

**Comment by gioragutt** [comment]
Yes, most definitely simpler. Thanks for that!
