### ISSUE TITLE
Using from() with a void typed promise returns type Observable<unknown>

### ISSUE THREAD

**Issue by LachlanED** [ReactiveX/rxjs#5198]
**RxJS version: 6.4+, typescript version: 3.7.4**

**Code to reproduce:**

function returnVoid(): Observable< void>{
  const a: Promise< void>= new Promise< void>(resolve=>resolve())
  return  from(a);
};

**Expected behavior:**
Should not throw an error on compile

**Actual behavior:**
I get the error "Type 'Observable< unknown> ' is not assignable to type 'Observable< void> '."

**Additional information:**
Downgrading to rxjs 6.2.2 works fine.

**Comment by cartant** [comment]
Not a bug. This is one of the rare instances in which it's necessary to specify a type argument explicitly:

```ts
function returnVoid(): Observable<void> {
  const a = new Promise<void>(resolve => resolve());
  return from(a);
}
```

It's not possible for TypeScript to infer the type parameter for `Promise` here and it must be specified explicitly.

**Comment by LachlanED** [comment]
Oh sorry I forgot to add that in for me even if I explicitly put the <void> onto the promise, I will still receive the error, I have updated my original post

**Comment by cartant** [comment]
I see no TypeScript error in the snippet that I posted:

<img width="539" alt="promise" src="https://user-images.githubusercontent.com/3878593/71506215-c235cf80-28cb-11ea-92dd-2e8b9102ce21.png">

I would suggest your creating a minimal reproduction of the problem. You might even discover what the problem is when you do so.

**Comment by LachlanED** [comment]
Well that did give a little bit more info, so in the tsconfig, I changed the target to be es2015 instead of es5 and that appeared to resolve the issue although I will admit that I do not know what in particular could have caused that as there is a large difference between the 2. Unfortunately I can't remove the es5 target due to having to support IE (the bane of my existence as a developer) but I can work around it for now with a type assertion. Thanks for your help.

**Comment by cartant** [comment]
The `target` in the `tsconfig.json` should not matter. What likely does matter is the `lib` setting. I would imagine that it has to be at least `"lib": ["es2015"]` as that's where TypeScript's types for `Promise` are.

The `lib` setting has nothing to do with what you are targeting. It relates to the types that should be included for the language features you intend to use - and you are using `Promise`. This answer explains it: https://stackoverflow.com/a/39306295/6680611

**Comment by LachlanED** [comment]
That fixed my problem, thank you, I was unaware of that setting.
