### ISSUE TITLE
Should startWith() behave the same as startWith(undefined as void) ?

### ISSUE THREAD

**Issue by mikebolt** [ReactiveX/rxjs#5201]
I originally used `startWith()` in a chain of pipe operators where the observable type is void. Fortunately, my unit tests caught an issue, and I found out that I need to use `startWith(undefined as void)` because the former does nothing. I expected these two versions to behave the same way.

Why am I wrong?

**Comment by mikebolt** [comment]
rxjs considers `startWith()` to mean "start with an empty array of arguments" so it does nothing. If this behavior were changed then using the spread operator would not work correctly in `startWith(...items)` if items is an empty array.

So, keep using `startWith(undefined as void)`. If someone thinks that a `startWithVoid()` operator may be useful then I will gladly make a PR.

**Comment by dzhavat** [comment]
From what I can see, `startWith` [uses `concat` internally](https://github.com/ReactiveX/rxjs/blob/6.5.4/src/internal/operators/startWith.ts#L75) to concatenate the values with the values from the source observable. So if you send an empty array to `startWith`, it will not make any difference, the emit will start directly with the source.
