### ISSUE TITLE
6.5.4 is missing from CHANGELOG.md

### ISSUE THREAD

**Issue by JackCA** [ReactiveX/rxjs#5202]
### Documentation Related To Component:

[CHANGELOG.MD](https://github.com/ReactiveX/rxjs/blob/master/CHANGELOG.md)

### Please check those that apply

- [ ] typo
- [x] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue

The changelog entry for the `6.5.4` release appears to be missing.

**Comment by cartant** [comment]
It's in the `6.x` branch: https://github.com/ReactiveX/rxjs/blob/6.x/CHANGELOG.md

**Comment by JackCA** [comment]
Oh I missed that... Thank you! Should it be on master though?

**Comment by kwonoj** [comment]
Looks like it's resolved.
