### ISSUE TITLE
feat(operator): pass teardown function to refCount

### ISSUE THREAD

**Issue by thefliik** [ReactiveX/rxjs#5204]
## Feature Request

**Is your feature request related to a problem? Please describe.**

Sometimes, when sharing an observable (e.g. via `share()` operator), I wish to attach a cleanup function which is called when the last subscriber unsubscribes from the observable. As far as I can tell, currently this is not possible.

**Describe the solution you'd like**

Update the `refCount()` operator to accept a teardown function which is called whenever the last subscriber unsubscribes.

**Describe alternatives you've considered**

I cannot think of an alternative option. Currently, I've forked the `refCount()` operator and patched it to provide this functionality.

**(If this is new operator request) describe reason it should be core operator**

N/a

**Additional context**
N/a

**Comment by thefliik** [comment]
If this is change is accepted, I can put together a PR.

**Comment by cartant** [comment]
To do what you want, you should be able to place a `finalize` operator before the `share` operator.

**Comment by thefliik** [comment]
Oh that's much better! I didn't realize that `share()` completed the source observable when the last subscriber unsubscribed. Thanks!

**Comment by cartant** [comment]
`share` doesn't effect the completion of the source observable. Rather, `finalize` invokes its callback upon explicit unsubscription - not just upon complete or error notifications.

**Comment by thefliik** [comment]
@cartant thanks. That is an important distinction. Am I reading [the `finalize()` docs](https://rxjs-dev.firebaseapp.com/api/operators/finalize) wrong? It doesn't appear to say that.

**Comment by cartant** [comment]
The JSDoc mentions it. IDK why the generated docs don't:

https://github.com/ReactiveX/rxjs/blob/56e7cebd211d93b9958e1ec508052beb8927604a/src/internal/operators/finalize.ts#L8-L10

**Comment by thefliik** [comment]
@cartant strange. I just downloaded rxjs `v6.5.4` which has the following jsdoc

```ts
/**
 * Returns an Observable that mirrors the source Observable, but will call a specified function when
 * the source terminates on complete or error.
 * @param {function} callback Function to be called when source terminates.
 * @return {Observable} An Observable that mirrors the source, but will call the specified function on termination.
 * @method finally
 * @owner Observable
 */
export declare function finalize<T>(callback: () => void): MonoTypeOperatorFunction<T>;
```

I guess whatever PR added that comment hasn't been released yet.

**Comment by thefliik** [comment]
Anyway, thanks again for the info!
