### ISSUE TITLE
where is the source files of  document 

### ISSUE THREAD

**Issue by xp44mm** [ReactiveX/rxjs#5210]
i find some typos in document https://rxjs-dev.firebaseapp.com/, and i want to correct it with pr. but i could not find the source code. may i get the address of source?

**Comment by cartant** [comment]
I've only skimmed it, but I suspect you might find this helpful: https://dev.to/dzhavat/getting-started-with-contributing-to-rxjs-docs-2875

**Comment by xp44mm** [comment]
thank you, you give me that answer my need, the source is at `rxjs/docs_app/content`. and newest docs page is rooted at `https://rxjs.dev/`

**Comment by BioPhoton** [comment]
Hi @xp44mm if you need more help feel free to ask. Otherwise please close this issue to keep the number of open issues low.

Thanks
