### ISSUE TITLE
Subject.unsubscribe() doesn't trigger dispose functions

### ISSUE THREAD

**Issue by martinsik** [ReactiveX/rxjs#5217]
## Bug Report

**Current Behavior**
Dispose handlers added to a chain via operators (eg. `finalize()`) or calling `Subscription.add()` on a subscription object returned from `Subject.subscribe()` will be triggered when calling `Subscription.unsubscribe()`.

However, [Subjects have `unsubscribe()` method](https://github.com/ReactiveX/rxjs/blob/master/src/internal/Subject.ts#L105) as well. But calling this method will never trigger dispose handlers. It only empties the inner list of observers.

Maybe this is the intended behavior but it's a little confusing that the method is called `unsubscribe()` but works differently than `Subscription.unsubscribe()`.

**Reproduction**
- REPL or Repo link: https://stackblitz.com/edit/rxjs-zo5fs6

```js
import { Subject } from 'rxjs'; 
import { finalize } from 'rxjs/operators';

const subject = new Subject();
const sub = subject
  .pipe(
    finalize(() => console.log('done')),
  )
  .subscribe();

sub.add(() => console.log('done 2'));

// This won't trigger any dispose handlers.
subject.unsubscribe();
```

**Expected behavior**
`Subject.unsubscribe()` will call dispose handlers or if this is the expected behavior maybe it could have a doc block describing its use-case.

**Environment**
- Runtime: any
- RxJS version: 6.5.2

**Comment by cartant** [comment]
`Subject.unsubscribe` is something that should be removed, IMO. I don't think it can/should be made to forcibly unsubscribe its subscribers.

**Comment by cartant** [comment]
Closing this because unsubscription isn't arbitrarily effected by sources. Sinks unsubscribe themselves upon receipt of `complete` or `error` notifications.
