### ISSUE TITLE
skipWhile not working as expected

### ISSUE THREAD

**Issue by OmarioHasan** [ReactiveX/rxjs#5219]
## Bug Report

**Current Behavior**
In documentation say that it skips items from the source observable depending on condition it works well when i check with "x=>x<5" when i working with interval but other condition will fail like "x=>x>5".

```js
interval(1000)
      .pipe(skipWhile(i => i > 3))
      .subscribe(console.log);
```

**Expected behavior**
 i assume it will skip what is larger than 5 but it's not or this is not it's behaviour as i think.

- RxJS version: 5.5.4

**Additional context/Screenshots**

![image](https://user-images.githubusercontent.com/8146344/71869023-45032980-3119-11ea-96a4-6c533810197c.png)

**Comment by kwonoj** [comment]
https://github.com/ReactiveX/rxjs/blob/master/src/internal/operators/skipWhile.ts#L8

> emits all further source items as soon as the condition becomes false

so if predicate tries to check `x > 5`, first call to predicate will be false due to `x (0) > 5 === false` so skipwhile determines predicate condition now satisfied and will emit all rest of values.

**Comment by OmarioHasan** [comment]
> https://github.com/ReactiveX/rxjs/blob/master/src/internal/operators/skipWhile.ts#L8
> 
> > emits all further source items as soon as the condition becomes false
> 
> so if predicate tries to check `x > 5`, first call to predicate will be false due to `x (0) > 5 === false` so skipwhile determines predicate condition now satisfied and will emit all rest of values.

How to skip what is larger than 5 so

**Comment by kwonoj** [comment]
https://github.com/ReactiveX/rxjs/blob/master/src/internal/operators/takeWhile.ts#L11-L13

**Comment by OmarioHasan** [comment]
> https://github.com/ReactiveX/rxjs/blob/master/src/internal/operators/takeWhile.ts#L11-L13

for sorry it's not a clear answer but thnx for your reply
