### ISSUE TITLE
How to make skipWhile work with a toggle flag

### ISSUE THREAD

**Issue by rupamroy** [ReactiveX/rxjs#5223]
I have to unsubscribe and resubscribe to an observable based on if a form is in editMode or not. A similar experimentation that i did with the following code

```typescript
@Component({
  selector: "app-home",
  templateUrl: "./home.component.html",
  styleUrls: ["./home.component.css"]
})
export class HomeComponent {
  //emit every 1s
  source = interval(1000);

  messages = [];
  doNotRun = false;

  constructor() {
    let example = this.source.pipe(skipWhile(() => { return this.doNotRun === true}));
    //output: 5...6...7...8........
    example.subscribe(val => this.messages.push(val));
  }

  toggle(){
    this.doNotRun = !this.doNotRun;
  }
}
```

Here the toggle method is bound to the click event handler of a button. So on clicking the toggle button the subcription should stop and re-start. But that does not happen and the subscript never stops . How to make that happen?

**Comment by kwonoj** [comment]
We recommend use stackoverflow for general questions.

Btw maybe I'm misunderstanding something but is there reason have to use `skip` instead of plain `filter`?
