### ISSUE TITLE
scheduler.schedule is not a function

### ISSUE THREAD

**Issue by devblazer** [ReactiveX/rxjs#5225]
## Bug Report

**Current Behavior**
Some RXjs code of mine is throwing an internal error of some kind.

```
scheduleArray.js:8 Uncaught TypeError: scheduler.schedule is not a function
    at Observable._subscribe (scheduleArray.js:8)
    at Observable._trySubscribe (Observable.js:43)
    at Observable.subscribe (Observable.js:29)
    at subscribeToResult (subscribeToResult.js:13)
    at MergeMapSubscriber._innerSub (mergeMap.js:74)
    at MergeMapSubscriber._tryNext (mergeMap.js:68)
    at MergeMapSubscriber._next (mergeMap.js:51)
    at MergeMapSubscriber.Subscriber.next (Subscriber.js:53)
    at MergeMapSubscriber.notifyNext (mergeMap.js:84)
    at InnerSubscriber._next (InnerSubscriber.js:15)
```
Putting a break point in reveals that the value of 'scheduler' is a numeric 1.
I'll admit that the code is a little on the complicated side with some streams essentially even forming a loop.  
There is basically alot of rxjs code, but it is probably worth mentioning that nowhere am I making use of schedulers.

I have also been on the look out for anywhere where I might be passing in the wrong number of arguments to rxjs functions, but have not found anything yet.

**Reproduction**
- Dont know how to reproduce it yet, still trying to figure out that myself.  It's a large and private codebase.  When I start breaking things and shifting things around a bit, the error seems to occur at different times/locations, making it hard to pin point what's causing it.

**Environment**
- Runtime: Chrome v79.0.3945.88
- RxJS version: 6

**Comment by cartant** [comment]
> Dont know how to reproduce it yet.

Not much can be done without a repro.

**Comment by cartant** [comment]
Closing this as this isn't action able without a repro and, TBH, it sounds like a problem in the application code. Are you using TypeScript?

Anyway, this:

> the value of 'scheduler' is a numeric 1.

Suggest that this could be the problem:

> I have also been on the look out for anywhere where I might be passing in the wrong number of arguments to rxjs functions, but have not found anything yet.

I would suggest working backwards to see where `scheduleArray` is called. If you look at the source for `fromArray`, you'll see that there would be an avenue there for `scheduleArray` to be called with a value of `1` for the `scheduler` argument.
