### ISSUE TITLE
add generic type to ignoreElements() signature

### ISSUE THREAD

**Issue by mkurcius** [ReactiveX/rxjs#5236]
## Bug Report

**Current Behavior**
Current signature of ignoreElements() looks as follow:
`function ignoreElements(): OperatorFunction<any, never>`
this `any` as first generic type cause this code to compile:
```ts
interface SomeObject {
  x: number;
}

const source$: Observable<SomeObject> = of({x: 1}, {x: 2}, {x: 3});
source$.pipe(
  tap(obj => console.log(obj.y)),
  ignoreElements()
);
```
where it should fail because `SomeObject` does not have property `y`

if you remove `ignoreElements()` code does not compile as expected

**Reproduction**
```ts
interface SomeObject {
  x: number;
}

const source$: Observable<SomeObject> = of({x: 1}, {x: 2}, {x: 3});
source$.pipe(
  tap(obj => console.log(obj.y)),
  ignoreElements()
);
```

**Expected behavior**
Operators inside pipe should infer proper type

**Environment**
- RxJS version: verified on 6.4.0 but newer version should has same bug

**Possible Solution**
change signature to: `function ignoreElements<T>(): OperatorFunction<T, never>`

**Comment by cartant** [comment]
Not an RxJS bug, IMO. An error is effected for me, using TypeScript version 3.7.4. What version of TypeScript are you using?

**Comment by mkurcius** [comment]
Ok, it may be it, I am using Typescript 3.5.3 (version which comes with Angular 8)

**Comment by cartant** [comment]
Closing this as it does not appear to be an RxJS issue and because specifying a type parameter that is used only in the return type is deemed to be poor practice.
