### ISSUE TITLE
finalize not working as expected with streams from dependencies

### ISSUE THREAD

**Issue by cdanielw** [ReactiveX/rxjs#5237]
## Bug Report

**Current Behavior**
Given project `a` and `b`. When `a` subscribe to a stream from `b`, the `finalize` operator doesn't get called.

The below script outputs:
```
a finalized c
```

**Reproduction**
https://github.com/cdanielw/rxjs-finalize

```js
const {finalize, first} = require('rxjs/operators')
const anotherModule$ = require('b')
const sameModule$ = require('./c')

anotherModule$.pipe(
        // Stream from another module doesn't finalize
	finalize(() => console.log('a finalized b')),
	first()
).subscribe()

sameModule$.pipe(
        // Stream from same module finalize
	finalize(() => console.log('a finalized c')),
	first()
).subscribe()

```

**Expected behavior**
Script should output :
```
a finalized b
a finalized c
```

**Environment**
- Runtime: Node v10.14.2
- RxJS version: 6.5.4

**Comment by cdanielw** [comment]
I managed to workaround this by this:

```js
of(true).pipe(
    switchMap(() => anotherModule$),
    finalize(() => console.log('1. a finalized b')),
    first()
).subscribe()
```

But it's easy to forget to do this, leading to subtle bugs.

**Comment by cartant** [comment]
`from(anotherModule$)` should be used. I'll write an explanation when I'm less tired. Not a bug, IMO.

**Comment by cdanielw** [comment]
Having different code depending on how/where code has been required makes it very difficult to pull RxJS code into shared libraries. This is where my issue is coming from. 

Even if this wouldn't be considered a bug, I'd really like you to consider removing any differences in behaviour based on where streams/code creating streams have been required from.

**Comment by cartant** [comment]
Yeah. I was wrong; this is definitely a bug.

I guess I really was tired, last night, as I recently fixed a problem that was closely related to this - see https://github.com/ReactiveX/rxjs/pull/5059 and the associated cherry pick into v6.

That PR includes testing infrastructure that'll allow me to reproduce your problem in a failing test. After which, I'll fix it.

Thanks for opening the issue.
