### ISSUE TITLE
is there a way to catch sync error instead of useDeprecatedSynchronousErrorHandling

### ISSUE THREAD

**Issue by slashhuang** [ReactiveX/rxjs#5250]
## Bug Report

**Current Behavior**
we could not find call stack when catch error

**Reproduction**
it is a rxjs behavior,but makes developers hard to debugger

```js
rxjsConfig.useDeprecatedSynchronousErrorHandling = true;
from(Promise.resolve(1)).map(() => throw err).subscribe(console.log)
```

**Expected behavior**
show error stack,instead of just the error in settimout throw

**Environment**
- Runtime: [e.g. Node v${x}, Chrome v${x}]
- RxJS version:

**Possible Solution**
enable rxjs Config.useDeprecatedSynchronousErrorHandling = true;
or provide other ways

**Comment by cartant** [comment]
Maybe intsead of re-throwing the caught error, the caught error should be wrapped in another and that should be thrown? AFAICT, it's not really possible to handle the asynchronous, host-reported errors, so it seems unlikely that wrapping the caught error is going to be problematic.

That would provide access to the caught error's stack, but in terms of facilitating the synchronous handling of such errors: no, that's not going to happen.

**Comment by cartant** [comment]
For the reasoning behing the asynchronous throwning, see the video linked in this comment: https://github.com/ReactiveX/rxjs/issues/4315#issuecomment-434854412

**Comment by slashhuang** [comment]
I understand the philosophy behind the design of rxjs error throwing.
maybe considering the api design for error exposing , explicit is better than implicit

**Comment by cartant** [comment]
Closing because there are now - in v7 - two documented APIs for dealing with errors that weren't handled or cannot be reported:

https://github.com/ReactiveX/rxjs/blob/f132d0d74cb059db74748025d35e22b2b0570f42/src/internal/config.ts#L22-L43
