### ISSUE TITLE
Support from(asyncIterator)

### ISSUE THREAD

**Issue by Jack-Works** [ReactiveX/rxjs#5272]
`rxjs.from((async function * () {})())`

Expected: return an Observable

Actual: `Uncaught TypeError: You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.`

**Comment by dilame** [comment]
I vote for this. This could be very useful

**Comment by niklas-wortmann** [comment]
We agreed on implementing asyncIterator in a user-land library (implemented by ben lesh)
You can find it here: https://github.com/benlesh/rxjs-for-await

If this library gets popular we might consider moving it over to rxjs core

**Comment by Jack-Works** [comment]
I think the library you mentioned is not what I described. What I want is I have an async iterator and I want to turn it to an Observable. Your library is turn observable into async iterator

**Comment by niklas-wortmann** [comment]
Oh sorry my bad, but here you go: #5297
Is part of RxJS 7 Beta IIRC
