### ISSUE TITLE
CI often doesn't kick off for new PRs

### ISSUE THREAD

**Issue by cartant** [ReactiveX/rxjs#5276]
## Bug Report

Numerous PRs - at least three - that I opened last week did not kick off CI. And to make that happen, I had to push empty commits to the PR's branch.

**Comment by kwonoj** [comment]
gh actions are in, let's see if it works for us.

**Comment by cartant** [comment]
AFAICT, the GitHub actions work and Circle CI just sits there waiting to be kicked. 🤦‍♂ 

This was a PR that I opened about 40 minutes ago:

<img width="523" alt="CI" src="https://user-images.githubusercontent.com/3878593/73577792-99f05080-44c9-11ea-8b62-30dc6c7590ef.PNG">

Your change LGTM. Maybe we can get Circle CI switched off?

In the interim, I'll push some more empty commits.

**Comment by kwonoj** [comment]
Let's make circleci as non required to unblock check in and see few days if gh works reliablt?

**Comment by kwonoj** [comment]
Ok, swapped required check. If something looks odd, feel free to change in settings.
