### ISSUE TITLE
(re)consider dist strategery

### ISSUE THREAD

**Issue by robwormald** [ReactiveX/RxJS#528]
per the new changes in Typescript 1.6.2 and Angular2's support to change over to it, some structural issues i've run into while attempting to (properly) bring Rx into NG2 could be eased with some changes:

Having the `typings: "./dist/es6/cjs"` field in package.json is a good start (or will be, once a release ships) but this only allows usage of the root entry point, eg:
`import {Observable} from '@reactivex/rxjs' ` (and there's a mismatch between cjs/es6 paths here)

If I want to grab Observable from a TypeScript codebase, and leverage the generated type information, I can't: 

`import Observable from '@reactivex/rxjs/dist/cjs/Observable' `
fails because TS cannot find module, since .d.ts file isn't in this location.

`var Observable = require('@reactivex/rxjs/dist/cjs/Observable');`
"works" but can't find the typedefs, so it can't be subclassed / typechecked etc.

`import Observable from '@reactivex/rxjs/src/Observable'` "works" internally (eg, in the NG2 build process / typechecking) but fails immediately in public because that transpiles to `require('@reactivex/rxjs/src/Observable') //implied .js`

Suggestions:
- while I know you're using Babel to generate CJS because of defaults, it would be helpful to have the generated .d.ts end up in the same path. That would alleviate most of our issues.
- Add an index.ts file that simply `exports * from './src/Rx' `
- Consider using TS to transpile the src folder (in place) before shipping?

Happy to do any/all of the above but wanted to discuss before PR'ing.

cc @alexeagle as he's been dealing with the typings stuff in NG2

**Comment by blesh** [comment]
As long as it doesn't hurt the behavior of the library, specifically the issue around default exports in CJS, I don't see a problem with it.

**Comment by blesh** [comment]
Honestly, I was sort of waiting for issues like this to arise. I'm way more likely to use Babel with RxJS than TypeScript, personally. So I haven't really dog-fooded any typings issues.
