### ISSUE TITLE
Operator overload signatures are not shown in docs app

### ISSUE THREAD

**Issue by cartant** [ReactiveX/rxjs#5281]
### Description Of The Issue

In the docs app, overload signatures are shown for methods on `Observable` - e.g. five overload signatures are shown for `subscribe`.

However, overload signatures are not shown for operators. That makes documenting `shareReplay` somewhat difficult, as it has a number of signatures - including a signature that takes a single config object. The same problem exists for the config object signature added for `retry` in [this PR](https://github.com/ReactiveX/rxjs/pull/5280).

It's not clear what needs to be done to effect the showing of overload signatures for operators and I'm not sure what it is that effects them for `Observable#subscribe` - as  there doesn't seem to be anything specific to overloads in the TSDoc.

**Comment by dzhavat** [comment]
It might sound funny but I just added a 3rd signature function to the `shareReplay` operator, rebuild the docs, launched them, and now the Overloads section is there. 

![image](https://user-images.githubusercontent.com/1096332/73575716-0d1da680-4479-11ea-8f30-b10c9f01fc88.png)

![image](https://user-images.githubusercontent.com/1096332/73575851-57068c80-4479-11ea-950e-36501f038c52.png)

I did the opposite with the `mergeMap` operator. Deleted a signature function to just two (from three) and the Overloads section is not there. So there's something with having a specific number of signatures before they appear in the docs.

**Comment by cartant** [comment]
@dzhavat Nice find.

**Comment by dzhavat** [comment]
Looks like my observation above is correct. Here's how the Overloads section is build :) 

https://github.com/ReactiveX/rxjs/blob/5170728f0262d65ab43937da9cbd621d6a5b4739/docs_app/tools/transforms/templates/api/function.template.html#L19

**Comment by jakovljevic-mladen** [comment]
Closed in #7367.
