### ISSUE TITLE
Improved Debugging Features

### ISSUE THREAD

**Issue by craig-dae** [ReactiveX/rxjs#5289]
## Feature Request

I propose that, when an unhandled exception occurs in an rxjs pipe, a console log is produced that provides useful information to debug the problem. 

Examples of ideas I would like: 
1. Log the input for the pipe that failed. For example, if my input is `tap(([someNum, someArray]) => ...)`, and I get a null reference exception, I would like to know that `Input for tap was [3, null]` at time of error
2. If possible, also provide the chain of pipes up to the point of the error. 

Why? Build an rxjs pipe chain is easy and intuitive. Debugging a pipe chain that has failed, perhaps because the backend changed a data model, is frustrating.

Why? RXJS is powerful, but extremely unintuitive. For new developers trying to learn it, this debugging process will help them visualize pipes better, and they will learn more quickly.

Why? Sometimes problems happen in prod, in obfuscated code, and is difficult to reproduce in dev. RXJS could improve the process of debugging prod issues.

**Describe alternatives you've considered**
Alternatives are sprinkling `tap(x => console.log(x))` throughout my code. This is time-consuming, and litters my code with console.logs and import tap statements that I sometimes forget to remove when I'm finished.

**Comment by kwonoj** [comment]
Our own core member @cartant 's user land module https://github.com/cartant/rxjs-spy and some others trying to solve these kind of problems. I doubt core itself will have those features with given concerns of runtime size  / performance cost.

**Comment by cartant** [comment]
@craig-dae rxjs-spy will be replaced soon by a DevTools extension with which you'll be able to do what you want. There'll be no need to sprinkle `tap` operators throughout your app.

I had hoped to publish a beta some months ago, but the amount of time - it's a part-time project - that I've been able to devote to the tools has been limited and a refactor was necessary to reduce the amount of information transferred from the app under inspection to the tools.

My intention was to use rxjs-spy's internals - with as few changes as possible - in the instrumentation and then refactor after a beta release, but the amount of information transferred with that approach was too excessive for real-world apps.

Expect an announcement on Twitter when the beta is ready.

**Comment by kwonoj** [comment]
prolly side note but rxjs-spy have own use cases like deployed app in electron can't use devtools but want to log stream behavior?

**Comment by kwonoj** [comment]
any case, I'd suggest to track userland implementation.

**Comment by cartant** [comment]
> prolly side note but rxjs-spy have own use cases like deployed app in electron can't use devtools but want to log stream behavior?

Yeah. I've not completely forgotten about Node. The intention is the make the patcher - that's injected by the DevTools and is pretty much very similar to what rxjs-spy was/is - available to Node uses so that they can inject it manually and can direct output to the console or whatever.

**Comment by craig-dae** [comment]
The DevTools extension you have on the roadmap is perfect! Thanks for the response!

**Comment by craig-dae** [comment]
@cartant I want something a little quicker. I'm looking at rxjs-spy, and it looks good, but I have to embed a bunch of stuff in my code. 

I'm thinking about writing a TamperMonkey or GreaseMonkey script to do this in the short term, while waiting for DevTools. Any experience doing it this way, before I attempt to do it myself?

**Comment by cartant** [comment]
@craig-dae Nope. Sorry.
