### ISSUE TITLE
[Feature request]: Exposing isPromise to the public API

### ISSUE THREAD

**Issue by BioPhoton** [ReactiveX/rxjs#5292]
## Feature Request

This could help people that deal with converting asynchronous primitives to observables.
In such cases, the isObservable function is used a lot and the check for a `Promise has to get implemented manually.

A common snippet could look like that:
```typescript 
type potentialObservableValue<T> = Promise<T> | Observable<T> | undefined | null;
function isObservableValue<T>(nextValue: potentialObservableValue<T>): Observable<T> {
  if (nextValue === null || nextValue === undefined) {
    return of(undefined);
  }
  else if (isObservable(nextValue)) {
    return nextValue;
  } 
  else if (isPromise(nextValue)) {
    return from(nextValue);
  } 
  else {
    throw new Error('Wrong type!');
  }
}
```

Exposing [isPromise](https://github.com/ReactiveX/rxjs/blob/master/src/internal/util/isPromise.ts) to the public API can help a lot and come in very handy.

**Comment by cartant** [comment]
IMO, it would be simpler to not test for observables and promises and to just call `from`:

```ts
  if (nextValue === null || nextValue === undefined) {
    return of(undefined);
  }
  else {
    return from(nextValue);
  }
```
