### ISSUE TITLE
flatMap Docs show mergeMap

### ISSUE THREAD

**Issue by rsimpson2** [ReactiveX/rxjs#5293]
### Documentation Related To Component:

`flatMap`

### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [x] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue

I went to look into more information for `flatMap` and the marble diagram shows `mergeMap`. Then below that the example is for `mergeMap` along with overloads. Did not know if this is correct documentation for `flatMap`?

**Comment by cartant** [comment]
`flatMap` is an alias for `mergeMap`, but if the docs don't mention that, they ought to.

**Comment by rsimpson2** [comment]
Yeah, I don't see anything that sticks out to me that would indicate that the alias is used. This is the docs I am looking at: https://rxjs.dev/api/operators/flatMap

**Comment by martinsik** [comment]
I think `flatMap` should not even show in the list because this was one of the reasons for this PR https://github.com/ReactiveX/rxjs/pull/4733. I'm not sure if the docs on rxjs.dev is up to date.

**Comment by cartant** [comment]
@martinsik It appears that #4733 was merged only a few months ago and into `master`. The docs are built from the `v6` branch, so to be represented on the current site, the changes in the PR would need to be applied to the `v6` branch too.

**Comment by niklas-wortmann** [comment]
I will close this issue for now, if there's anything that needs to be done about this, feel free to reopen.
