### ISSUE TITLE
Unsubscription not working during synchronous execution of code

### ISSUE THREAD

**Issue by punithnpg** [ReactiveX/rxjs#5308]
## Bug Report

**Current Behavior**
Unsubscription not working during synchronous execution of code

**Reproduction**
- REPL or Repo link: https://stackblitz.com/edit/rxjs-unsubscribe-issue?file=index.ts

**Expected behavior**
Should unsubscribe like it does with asynchronous code

**Environment**
- RxJS version: 6.5.4

**Additional context/Screenshots**
![Screenshot 2020-02-12 at 10 41 54 AM](https://user-images.githubusercontent.com/10862627/74305085-e4ed4c00-4d84-11ea-9c97-96407ec4b9df.png)

**Comment by kwonoj** [comment]
You cannot reentrant synchronously, there are several other known behavior around reentrant (https://github.com/ReactiveX/rxjs/issues?q=is%3Aissue+reentrant+is%3Aclosed) and it's all works as expected: to enable reentrans, you should manage your subscription to avoid synchronous reentrant.

**Comment by cartant** [comment]
If you absolutely must explicilty unsuscbribe from a synchronous observable - within the `next` callback - you need to use the context: https://github.com/ReactiveX/rxjs/pull/3230#issuecomment-361113247

**Comment by kwonoj** [comment]
Personally I really would like to encourage not to try reentrant. lot of cases it becomes giant footgun later.
