### ISSUE TITLE
groupBy: possible memory leak

### ISSUE THREAD

**Issue by josepot** [ReactiveX/rxjs#5309]
## Bug Report

**Current Behavior**
If one of the output streams produced by `groupBy` completes, then the `groupBy` operator will stop creating new streams for that same key. That seems to indicate that it won't be until the source stream completes that the `groupBy` operator will release the references of the keys that have been used. IMO it would be best to release those references as soon as the output stream completes and create a new stream if that key appears again.

**Reproduction**
- I've created this example (see outputs in the console): https://stackblitz.com/edit/rxjs-ovqm2f?file=index.ts

**Expected behavior**
I would expect the following code:
```ts

const rawData: [string, number][] = [
  ["id1", 0],
  ["id1", 1],
  ["id1", 2],
  ["id1", 3],
  ["id1", 0],
  ["id1", 1],
];
const data = rawData.map(([id, count]) => ({ id, count }));

from(data)
  .pipe(
    concatMap(x => of(x).pipe(delay(500))),
    groupBy(x => x.id),
    mergeMap(group =>
      group.pipe(
        takeWhile(x => x.count < 3, true),
        scan((acc, { count }) => acc + count, 0),
        map(total => ({ id: group.key, total }))
      )
    )
  )
  .subscribe(({id, total}) => console.log(`ID: ${id}, total: ${total}`));
```
to output:
```bash
 ID: id1, total: 0
 ID: id1, total: 1
 ID: id1, total: 3
 ID: id1, total: 6
 ID: id1, total: 0
 ID: id1, total: 1
```
however, its output is:
```bash
 ID: id1, total: 0
 ID: id1, total: 1
 ID: id1, total: 3
 ID: id1, total: 6
```

**Environment**
- Runtime: Node v12.13.1, Chrome v 79.0.3945.130
- RxJS version: 6.5.4

**Possible Solution**

In order to circumvent this (possible) issue, I'm currently using the following operator instead:

```ts
const continuousGroupBy = <I, O>(mapper: (x: I) => O) => (
  stream: Observable<I>,
) =>
  new Observable<GroupedObservable<O, I>>(subscriber => {
    const groups: Map<O, Subject<I>> = new Map()

    return stream.subscribe(
      x => {
        const key = mapper(x)
        if (groups.has(key)) {
          return groups.get(key)!.next(x)
        }

        const subject = new BehaviorSubject<I>(x)
        groups.set(key, subject)

        const res = subject.pipe(
          finalize(() => groups.delete(key)),
          share(),
        ) as GroupedObservable<O, I>
        res.key = key

        subscriber.next(res)
      },
      e => {
        subscriber.error(e)
        groups.forEach(g => g.error(e))
      },
      () => {
        subscriber.complete()
        groups.forEach(g => g.complete())
      },
    )
  })
```

I'm aware that this ^ code can not be used for fixing/implementing the real `groupBy` operator. I'm just sharing it to illustrate the behaviour that IMO would be best.

Thanks a lot for maintaining this awesome library!

**Comment by cartant** [comment]
This looks to be a misunderstanding, to me.

> If one of the output streams produced by groupBy completes ...

It doesn't complete. The application of an operator won't complete the source - which is a subject.

**Comment by josepot** [comment]
Thanks @cartant for having a look at this issue and for getting back to me so quickly. It's clear to me now that I should have tried to explain myself a bit better 🙂 

I do understand that the output observables produced by `groupBy` are hot observables and I also understand that the source of those observables is a Subject (and that a Subject never completes).

However, I _think_ that what it is exposed to the consumer is not the Subject itself, but a hot observable derived from that Subject and that derived observable can complete. In other words, I think that it would be possible/desirable to do something like this:

```ts
const subject = new BehaviorSubject<I>(currentValue);
groups.set(key, subject);

const outputObservable = subject.pipe(
  finalize(() => groups.delete(key)),
  takeUntil(sourceSubscriptionEnd),
  share()
) as GroupedObservable<O, I>;

outputObservable.key = key;
subscriber.next(res);
```

So, that whenever the observable that it's being exposed to the consumer finalizes, then `groupBy` can "forget" about the source Subject that was used for producing the output Observable.

**Comment by cartant** [comment]
`groupBy` takes an optional subject selector, so you could experiment with that without the implementation having to change: `subjectSelector?: () => Subject<R>`

**Comment by josepot** [comment]
> groupBy takes an optional subject selector, so you could experiment with that without the implementation having to change: subjectSelector?: () => Subject<R>

Thanks @cartant ! I did try using that argument and I failed miserably... 😞 The thing is that the usage of that argument is not very well documented, but I did look at the source code and I couldn't figure out a way to accomplish this behaviour without changing the current implementation. I'm not saying that it's not possible, though, I'm saying that I couldn't figure out how to do it 😅 and that I'm not sure whether it is possible.

Can you think of a way to accomplish the behaviour that I'm describing without changing the current implementation? Do you think that perhaps I should close this issue and ask this question on stackoverflow?

**Comment by cartant** [comment]
I re-read your issue. I don't see why you consider it a problem for the implementation to hold a subject for each key that it sees for the life of the source stream. It also not clear whether that is your primary concern or if you actually want to unsubscribe and re-subscribe to the group observable for some reason.

**Comment by josepot** [comment]
> I don't see why you consider it a problem for the implementation to hold a subject for each key that it sees for the life of the source stream

Consider a nodeJs service that does something like this:

```ts
const games$ = mergeWithKey({  
  move: merge(recordedMoves$, incomingMoves$),
  termination: gameTimeOuts$, 
}).pipe( 
  groupBy(x => (x.key === 'termination' ? x.value : x.value.gameId)),
  mergeMap(group =>
    group.pipe(
      takeWhile(x => x.key !== 'termination'),
      map(x => x.value.move),
      playGame(group.key),
    )
  ),
  share()
);

games$
  .pipe(filter(({type}) => type === MessageType.RECEIVE))
  .subscribe(registerMove);

games$
  .pipe(filter(({type}) => type === MessageType.END))
  .subscribe(endGame);

games$
  .pipe(
    filter(({target}) =>
      target === TargetType.PLAYER_A || target === TargetType.BOTH
    ),
    withLatestFrom(activeConnections$)
  )
  .subscribe(sendMessage(TargetType.PLAYER_A));

games$
  .pipe(
    filter(({target}) =>
      target === TargetType.PLAYER_B || target === TargetType.BOTH
    ),
    withLatestFrom(activeConnections$)
  )
  .subscribe(sendMessage(TargetType.PLAYER_B));
```

I have these 4 top level subscriptions should always be open if the service is up and running. The `gameTimeOuts$` is a stream that will emit whenever the users of a given game have spent more than a certain time disconnected... But they can reconnect again a few days latter and continue playing their unfinished game.

Therefore, I want to make sure that whenever `gameTimeOuts$`emits I get rid of any references to that game. However, with the current implementation of `groupBy` that won't happen. In fact, if the users re-connect a few days latter, they won't be able to keep playing their unfinished game if the node instance that picks up the game is the same that was used previously.

In other words, a nodeJs service that uses `groupBy` like that ^ will experience a pretty annoying memory leak. However, if in that exact same code I replace `groupBy` with my `continuousGroupBy` custom operator, then the memory leak is gone and the players will be able to continue their game in the future 🙂.

I think that if the current behaviour is what's to be expected, then it should at least be carefully documented. I also think that it would be nice to have a way to opt-out of this behaviour, so that if the inner-observables complete, then `groupBy` forgets about their Subjects.

> It also not clear whether that is your primary concern or if you actually want to unsubscribe and re-subscribe to the group observable for some reason.

🤔 No, I don't want to unsubscribe and re-subscribe to the group observable, no, nothing like that... Hopefully the example that I just shared will help into clarifying what my concerns are with the current behaviour/implementation of `groupBy`.

Thanks a lot for your time and patience @cartant !

**Comment by josepot** [comment]
I had a look at the [ReactiveX documentation of the `groupBy` operator](http://reactivex.io/documentation/operators/groupby.html) and I noticed that in other implementations `groupBy` behaves in the way that I was expecting it to behave. For instance, the RxJava section states that:

> If you unsubscribe from one of the GroupedObservables, that GroupedObservable will be terminated. If the source Observable later emits an item whose key matches the GroupedObservable that was terminated in this way, groupBy will create and emit a new GroupedObservable to match the key.

Wouldn't it make sense for the RxJS implementation to behave like that as well?

I wouldn't mind trying to work on a PR to address this, but first I would like to know if this is something that we actually want to address and most importantly how:

1. Should we change/fix the behaviour of the current `groupBy` operator?
2. Should we create a different operator with this behaviour?
3. Should we add another overload to `groupBy`?
4. Others...

My preference would be option 1 and I would like to avoid option 3.

**Comment by cartant** [comment]
@josepot Maybe. The [RxJava docs](http://reactivex.io/RxJava/3.x/javadoc/io/reactivex/rxjava3/core/Observable.html#groupBy-io.reactivex.rxjava3.functions.Function-) have this to say:

> Each emitted `GroupedObservable` allows only a single `Observer` to subscribe to it during its lifetime and if this `Observer` calls `dispose()` before the source terminates, the next emission by the source having the same key will trigger a new `GroupedObservable` emission.

That is very different to anything else in RxJS, AFAICT. Also, the RxJava version buffers values within the `GroupedObservable`. The RxJS version of does not - by default - but you can pass a factory that returns a `ReplaySubject` to get that behaviour.

IDK what was discussed when `groupBy` was implemented - it was before my time here - but if you feel strongly about this, you could do some research yourself by reading through the issue/PR history (implementation decisions are often discussed):

https://github.com/ReactiveX/rxjs/search?o=asc&q=groupby&s=created&type=Issues

Also, I don't know what the RxJS version 4 behaviour was. That would be worth looking into, too:

https://github.com/Reactive-Extensions/RxJS

**Comment by josepot** [comment]
Hi @cartant 

I finally found the time to look into this: back in the days there were two different operators: `groupBy` and `groupByUntil` and eventually [they got merged into one](https://github.com/ReactiveX/rxjs/issues/165).

Looking at what happened there, I did realise that the memory-leak can be avoided by using the 3rd parameter of `groupBy`, the "duration selector". So, taking as a reference [the example that I provided in the original bug report](https://github.com/ReactiveX/rxjs/issues/5309#issue-564070089), we could avoid the "memory-leak" if the code was refactored like this:

```ts
from(data)
  .pipe(
    concatMap(x => of(x).pipe(delay(500))),
    groupBy(
      x => x.id,
      x => x,
      group.pipe(filter(x => x.count === 3)) // this line instead of the `takeWhile` that has been commented out
    ),
    mergeMap(group =>
      group.pipe(
//    takeWhile(x => x.count < 3, true),
        scan((acc, { count }) => acc + count, 0),
        map(total => ({ id: group.key, total }))
      )
    )
  )
  .subscribe(({id, total}) => console.log(`ID: ${id}, total: ${total}`));
```

So, I was wrong: there is a way to avoid the memory-leak.

That being said, I think that the `groupBy` operator doesn't need the "duration selector" argument, because IMO the termination of the "grouped observable" should be used as a signal that the group is no longer needed.

Is it too late to suggest this change for v7? Would it be worth it for me to send a PR with this breaking change for v7?

**Comment by cartant** [comment]
> Is it too late to suggest this change for v7?

Regardless of timing, I'm not in favour of what seems to be the suggested change. The solution should be to use the duration selector.

The `group` does not 'terminate'. The observable returned by the application of the `takeWhile` *completes* and that effects an unsubscription from the `group` observable. The `group` observable does not complete. I would not be in favour of any change that effected behaviour upon unsubscription from the `group` observable. It's too implicit. Consumers of notifications emitted by observable returned by the application of the `groupBy` operator are free to subscribe to and unsubscribe from the emitted observables as many times as they like. That's one of the reasons `groupBy` takes a subject factory. What would be the point of a factory returning a `ReplaySubject` if the underlying implementation threw it away upon the first unsubscription?

IMO, the using the duration selector is the way to go.

**Comment by cartant** [comment]
BTW, TIL that `groupBy` has a duration selector. 😅
