### ISSUE TITLE
subscribe(subject) different than subscribe(x => subject.next(x))

### ISSUE THREAD

**Issue by robstoll** [ReactiveX/rxjs#5313]
## Bug Report

**Current Behavior**
Seems like there is a different between
```
obs.subscribe( x => subject.next(x))
obs.subscribe(subject)
```
Though the docs imply IMO that they are equivalent: https://rxjs-dev.firebaseapp.com/guide/subject

**Reproduction**
- REPL or Repo link:
https://stackblitz.com/edit/angular-dtansk?file=src%2Fapp%2Fapp.component.ts

**Expected behavior**
I would expect that I see the same result, i.e. that `reload2: 4` is also shown

**Environment**
- RxJS version: ^6.5.2

**Possible Solution**
IMO either fix the docu or the implementation

**Comment by cartant** [comment]
The two calls are different because `next`, `error` and `complete` notifications will be forwarded to the subject in the second call.

**Comment by robstoll** [comment]
OK, that makes actually sense but why is the next call not emitted?

**Comment by robstoll** [comment]
ah... I think I see why. because the first reload1 call completes and in consequence the ReplaySubject completes as well. Correct?

**Comment by cartant** [comment]
I don't know; I didn't look at the StackBlitz project, as the difference is fundamental.

**Comment by robstoll** [comment]
I'll close it for now, i am pretty sure that's the case. Thanks for your help :+1:
