### ISSUE TITLE
6.5.4 Not included in changelog

### ISSUE THREAD

**Issue by bjohnson-va** [ReactiveX/rxjs#5314]
### Documentation Related To Component:

https://github.com/ReactiveX/rxjs/blob/master/CHANGELOG.md

### Please check those that apply

- [ ] typo
- [x] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue

The changelog jumps from 6.5.3 to 7.0.0 but 6.5.4 is a published version
https://www.npmjs.com/package/rxjs/v/6.5.4

**Comment by dzhavat** [comment]
The changelog for v6 is in the [6.x branch](https://github.com/ReactiveX/rxjs/blob/6.x/CHANGELOG.md) but I agree that it's a good idea to have it on `master` as well.

There's already a similar issue #5202

**Comment by kwonoj** [comment]
Guess this should be good: https://github.com/ReactiveX/rxjs/issues/5202#issuecomment-569475509
