### ISSUE TITLE
Export other types used by TestScheduler in 'rxjs/testing'

### ISSUE THREAD

**Issue by rafw87** [ReactiveX/rxjs#5319]
**RxJS version:**
rxjs@6.5.4

**Code to reproduce:**
```ts
import { Epic } from 'redux-observable';
import { TestScheduler } from 'rxjs/testing';
// This is BAD! Should be available in 'rxjs/testing' as part of TestScheduler interface
import { RunHelpers } from 'rxjs/internal/testing/TestScheduler';

export const testEpic = (epic: Epic, mockedDependencies: (helpers: RunHelpers) => object) => {
  const testScheduler = new TestScheduler((actual, expected) => {
    expect(actual).toEqual(expected);
  });
  testScheduler.run(helpers => {
    const deps = mockedDependencies(helpers);
    // ...
  });
};
```

**Expected behavior:**
'rxjs/testing' should have all types (in my case `RunHelpers`) used in public interface of `TestScheduler`, allowing to declare variable/parameter with this type.

**Actual behavior:**
'rxjs/testing' have only `TestScheduler` itself, if I want to declare `RunHelpers` in my code I need to import it from 'rxjs/internal/testing/TestScheduler' what is bad.

**Additional information:**
There are few workarounds, but none is perfect:
- Importing from 'rxjs/internal/testing/TestScheduler' - importing from internal is always bad idea
- Declaring `RunHelpers` in app - there are two different declarations which may eventually became inconsistent
- Using following expression to pick `RunHelpers` from `typeof TestScheduler.prototype.run`:
  ```ts
  type RunHelpers = Parameters<Parameters<typeof TestScheduler.prototype.run>[0]>[0];
  ```
  but it's complicated to understand and messed
- passing `TestScheduler` instance instead of `RunHelpers` - but it introduces different interface than `RunHelpers`.

**Comment by kwonoj** [comment]
Closing per comment https://github.com/ReactiveX/rxjs/pull/5323#issuecomment-608262542
