### ISSUE TITLE
From using Function

### ISSUE THREAD

**Issue by kevupton** [ReactiveX/rxjs#5321]
## Feature Request

With pipable operator, RxJS strongly recommends to create new features via pipable function and publish it as user-land module. If this feature request is

**Is your feature request related to a problem? Please describe.**

What is super frustrating is the conversion from Promises to Observables, but having to execute the Promise before returning an observable. This goes against the Observable pattern in my opinion as an observable is only executed when it has a subscriber. For this reason, I think that from should also cater for Function inputs, so that the observable can behave accordingly.

**Describe the solution you'd like**

My solution is simple and sweet:
```ts
import { from, Observable, ObservableInput } from 'rxjs';

export function fromFn<T>(fn: () => ObservableInput<T>): Observable<T> {
  return new Observable(subscriber => {
    return from(fn()).subscribe(subscriber);
  });
}
```

Either we create a new method which only accepts functions or extend the existing `from` method.

**Describe alternatives you've considered**

I have looked into `from` and `of` however neither have the desired behaviour. Please let me know if there is something which has this behaviour already.

**(If this is new operator request) describe reason it should be core operator**
A clear and concise description of reason it can't be achieved via user-land module.

I am not sure what a user-land module is. But I believe it would be of great benefit to have this in a library.

**Additional context**

This is especially helpful for dealing with libraries that use promises, (i.e. database libraries like mongoose), where you dont want to actually execute the request until it is subscribed to.

For example: 
```ts
fromFn(() => user.save()).pipe(
  // do something here.
)
```

**Comment by cartant** [comment]
AFAICT, [`defer`](https://rxjs.dev/api/index/function/defer) does exactly this. It's extremely useful for making `Promise`-based sources lazy.

**Comment by kevupton** [comment]
Oooo Awesome!! thanks :)
