### ISSUE TITLE
deprecation warning about combineLatest with "rxjs": "~6.5.4",

### ISSUE THREAD

**Issue by dalu** [ReactiveX/rxjs#5331]
Support Question:

```ts
import {combineLatest, Observable, Subject} from 'rxjs';

// later

somefunc() {
    this.community$.pipe(
      takeUntil(this.ngDestroyed$),
      switchMap(community => {
        return combineLatest(this.store.select(selectProfileByID(community && community.owner_id)), this.container$);
      }),
    ).subscribe(([profile, container]) => {
      if ((profile) && (container)) {
        const claims = this.oAuthService.getIdentityClaims();
        if (claims) {
          // @ts-ignore
          const sub = claims.sub;
          if (sub === profile.subject_id) {
            this.store.dispatch(setDrawerAdminNavigationItems({
              items: [
                {title: 'New Forum', route: ['/new/forum', container.id]}
              ]
            }));
          }
        }
      } else {
        this.store.dispatch(setDrawerAdminNavigationItems({items: undefined}));
      }
    });
}
```
webstorm complains that `combineLatest` is deprecated
```ts
        return combineLatest(this.store.select(selectProfileByID(community && community.owner_id)), this.container$);
```

Do I have to be afraid or very afraid? j/k but what's going on? I'm aware of the migration document. It's a static function, the import is correct. Is this just Webstorm acting up?

**Comment by cartant** [comment]
> Do I have to be afraid or very afraid?

Neither. I'd ask for you to be patient, instead. :slightly_smiling_face: The deprecations and the deprecation messages need some work and they are receiving it now.

**Comment by dalu** [comment]
Alright :) Someone on Stackoverflow commented that for combineLatest to not be considered deprecated one would have to wrap the parameters in `[]`.

https://stackoverflow.com/questions/60455775/join-2-observable-streams-but-have-distinct-accessors/60455776?noredirect=1#comment106963653_60455776

I can't verify that claim right now but have no reason to belive it to be false, it makes sense.
I'll close this here. Thanks for the response.
