### ISSUE TITLE
[docs]: Top menu on external resources page has ‘position: absolute’

### ISSUE THREAD

**Issue by looshch** [ReactiveX/rxjs#5336]
## Bug Report

**Current Behavior**
Top menu on external resources page has ‘position: absolute’ so it goes away on scrolling.

**Reproduction**
Go to [resources page](https://rxjs.dev/resources), make sure your display area is wider than 481px and scroll down, top menu disappears.

**Expected behavior**
Top menu remains on top as on any other page.

**Screenshots**
![Screen Shot 2020-03-02 at 10 34 11 PM](https://user-images.githubusercontent.com/45432373/75715451-18f9c400-5cd6-11ea-91f6-f208e8209dec.png)

**Comment by niklas-wortmann** [comment]
closed by #5337
