### ISSUE TITLE
The Deprecations missing `partition` link

### ISSUE THREAD

**Issue by doggy8088** [ReactiveX/rxjs#5343]
### Documentation Related To Component:

`deprecations.md`

### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [x] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue

In [Deprecations](https://rxjs.dev/api/deprecations) page, there is a link missing.

![image](https://user-images.githubusercontent.com/88981/75963894-44142b80-5f01-11ea-9f50-e620955cd527.png)

**Comment by cartant** [comment]
Closing this 'cause that link now exists in the v7 docs and also because the docs are being tweaked and this page is going to change.
