### ISSUE TITLE
Deno support

### ISSUE THREAD

**Issue by FrancescoBorzi** [ReactiveX/rxjs#5350]
This has already been asked here: https://github.com/ReactiveX/rxjs/issues/4937

and the answer from @kwonoj was:

> We will eventually consider deno as support runtime, but will not have actual implementation until we see stable version of deno released.

Now, [it has been announced](https://github.com/denoland/deno/issues/2473#issue-453631188) that Deno 1.0 will be released the 13rd of May 2020.

So maybe it's time to reconsider this?

**Comment by kwonoj** [comment]
Answer's pretty same as before: consideration does not mean we'll release support when deno have its stable release. Please note we even can't support native esm on node.js due to several blocker's we are seeing at this moment - and supporting deno's module resolution won't happen in day 1. 

It's on our radar but there's no specific date we can provide at this moment.

**Comment by benlesh** [comment]
I think we should discuss these issues at the next meeting. Deno is a run time with growing usage, and I think we should support it.

**Comment by kwonoj** [comment]
@benlesh we had discussed in prev core meeting (when you couldn't attend). Tl:dr story is import site support to conform both (node / deno) is not trivial, and supporting node's esm is higher priority at this point but even supporting esm is not viable in short timeframe. I agree we will / may support deno one day but not something we'll actively plan for now.

**Comment by benlesh** [comment]
Well, given that the popularity of Deno has risen quite a bit, maybe we should discuss again what it entails at the next meeting.

**Comment by kwonoj** [comment]
We have dupe (https://github.com/ReactiveX/rxjs/discussions/5971) and since both requests are exactly same, don't think we need open both. We _will_ evaluate this eventually, but other priorities like esm is much higher and we couldn't solve that problem yet even.
