### ISSUE TITLE
6.5.4 vs IE11

### ISSUE THREAD

**Issue by nihilenz** [ReactiveX/rxjs#5358]
## Bug Report

**Current Behavior**
6.5.4 version is not working on IE11. You get an error `'Promise' is undefined`. This issue is only related to 6.5.4 version.

**Reproduction**
You can just test the example on README on IE11:
```
<html>
<html>
<head>
  <script type="text/javascript" src="https://unpkg.com/rxjs/bundles/rxjs.umd.min.js"></script>
</head>
<body>
  <script>
    const { range } = rxjs;
    const { map, filter } = rxjs.operators;
    range(1, 200)
      .pipe(
        filter(x => x % 2 === 1),
        map(x => x + x)
      )
      .subscribe(x => console.log(x));
  </script>
</body>
</html>
```

**Environment**
- Runtime: IE 11.719.18362.0
- RxJS version: 6.5.4

**Comment by cartant** [comment]
This is not a bug.

IE11 [does not support `Promise`](https://en.wikipedia.org/wiki/Internet_Explorer_11). If you want to use RxJS in a application that has to support IE11, you will have to polyfill `Promise` yourself. It is not the responsibility of packages - like RxJS - to polyfilll features that were incorporated into the JavaScript language in 2015.
