### ISSUE TITLE
throttle tests - some description and their implementation are inconsistent

### ISSUE THREAD

**Issue by BioPhoton** [ReactiveX/rxjs#5360]
## Bug Report

**Current Behavior**
In the specs of throttle described here:
https://github.com/ReactiveX/rxjs/blob/master/spec/operators/throttle-spec.ts#L384
and implemented here:
https://github.com/ReactiveX/rxjs/blob/master/spec/operators/throttle-spec.ts#L411

as well as here:
https://github.com/ReactiveX/rxjs/blob/master/spec/operators/throttle-spec.ts#L385 
and implemented here:
https://github.com/ReactiveX/rxjs/blob/master/spec/operators/throttle-spec.ts#L397

It should test against `{ leading: false, trailing: true }` but does test against `{ leading: true, trailing: true }`

If I put false the test fails, which means there is an inconsistency.

**Expected behavior**
The test should pass and the description and implementation should be consistent.

**Possible Solution**
I suggest implementing the right behavior in the throttle implementation.

**Additional context/Screenshots**
![throttle-inconsistent-test](https://user-images.githubusercontent.com/10064416/77230157-8f316e00-6b92-11ea-84db-d670fbda138c.PNG)

**Comment by BioPhoton** [comment]
@cartant if this is a bug I would have the proper fix and could make a PR for the suggested change.

**Comment by cartant** [comment]
I doubt it's a bug, as that test's marble sources and expectation is identical to the test - further above it  - with same description. If `leading` is changed to `true`, the expectation is going to have to change.

It looks to me like the test was copied and not updated.

**Comment by BioPhoton** [comment]
Single values witl leading false trailing true  don't pass. 
Thought this is what should happen.

**Comment by cartant** [comment]
> Single values witl leading false trailing true don't pass.

I don't understand. What does this have to do with what you raised in the issue? AFAICT, you linked to two tests with different descriptions that have identical marbles and expectations. If that's the case, the expectations need to be changed as well as the code. If it's not the case, a more thorough explanation is needed, as I don't understand your comment.
