### ISSUE TITLE
Mocking webSocket typescript 3.7

### ISSUE THREAD

**Issue by kekel87** [ReactiveX/rxjs#5366]
## Bug Report

**Current Behavior**

I use `rxjs/webSocket` in my Angular project.
For testing my wrapping service around `webSocket`, I used `spyOnProperty` to mocked like that :
```typescript
import * as rxjsWS from 'rxjs/webSocket';

spyOnProperty(rxjsWS, 'webSocket', 'get').and.returnValue(webSocketSpy);
```

This is work fine in Angular 8 and Typescript 3.6.

But after the Angular 9 and Typescript 3.7 upgrade, I've got this message : 
`Error: webSocket is not declared configurable`.

After some research, I think it could be the new Typescript [flag](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#the-usedefineforclassfields-flag-and-the-declare-property-modifier). And the fact that `Object.defineProperty()` has its `configurable` parameter set to `false` by default.

I'm not sure I posted this in the right place (between jasmine, angular, typescript or here RXJS). But the initial problem is that I couldn't find any documentation on how to test `rxjs/webSocket`.

**Environment**
- Runtime: Angular 9, Typescript 3.7
- RxJS version: 6.5.3

**Comment by kolodny** [comment]
I think this is due to the way TS compiles exports to not allow overriding exports. If you're using jest you can use `jest.mock`. https://github.com/jasmine/jasmine/issues/1414 can give you more info about this

**Comment by cartant** [comment]
`rxjsWS` is not an object; it's a `ImportNamespaceSpecifier`. That its 'properties' cannot be assigned is not surprising. As Moshe has pointed out, preventing such assignments is not enforced by TypeScript compilation. In any case, I'm closing this as it isn't an RxJS issue.
