### ISSUE TITLE
returns wrong type from filter operator

### ISSUE THREAD

**Issue by vyacheslavzhabitsky** [ReactiveX/rxjs#5368]
## Bug Report

**Current Behavior**
when I'm trying to filter via filter(Boolean) it returns ```Observable<unknown>```
**Reproduction**
https://stackblitz.com/edit/rxjs-nywjdc?file=index.ts

```js
const source = of(true).pipe(
  filter(Boolean)
);
// Observable<unknown>
```

**Expected behavior**
I expected to get type of source ```Observable<true>``` or ```Observable<boolean>```

**Environment**
- RxJS version: 6.5.2

**Possible Solution**
maybe that issue on typescript side or I'm just doing bad practice.

**Comment by niklas-wortmann** [comment]
This is fixed in the alpha of rxjs 7 and will land in the next major release.
