### ISSUE TITLE
bufferTime drops buffer frames, possibly due to not accounting for re-entrance 

### ISSUE THREAD

**Issue by gawicks** [ReactiveX/rxjs#5374]
## Bug Report

**Current Behavior**
bufferTime drops buffer frames, possibly due to not accounting for re-entrance? In the repro the observable only emits 'async' values.

**Reproduction**
- REPL or Repo link:
https://stackblitz.com/edit/rxjs-nfym2w
```js

let i = 0;
let j = 0;

const subject = new Subject();
subject.pipe(bufferTime(2000))
.subscribe((x) => {
  console.log(x);
  subject.next(`sync ${i++}`);
  setTimeout(() => subject.next(`async ${j++}`));
});
```
**Expected behavior**
should emit 'sync' values
- RxJS version: 6.5.4

**Comment by kwonoj** [comment]
This is expected, we don't gaurantee any synchronous reentrant. https://github.com/ReactiveX/rxjs/issues/2155#issuecomment-263715419

**Comment by gawicks** [comment]
@kwonoj Thanks but do you mean you don't guarantee for reentrancy for any operator? Also is this well known limitation documented somewhere ?

**Comment by gawicks** [comment]
@kwonoj  Thanks but do you mean you don't guarantee for reentrancy for any operator? Also is this well known limitation possibly documented somewhere ?

**Comment by gawicks** [comment]
@kwonoj  I understand why subjects wouldn't be protected against reentrancy, and get somewhat unexpected ordering of emissions. But in this case emissions don't happen *at all*. Is this really correct behavior?
