### ISSUE TITLE
skipUntil(s$) doesn't complete when s$ completes

### ISSUE THREAD

**Issue by akarelas** [ReactiveX/rxjs#5379]
## Bug Report

**Current Behavior**
The `skipUntil(x$)` operator does not cause the resulting observable to complete when `x$` completes before it emits a value.

**Reproduction**
- REPL or Repo link: https://jsfiddle.net/u30anr78/10/

```js
let { interval, EMPTY } = rxjs; 
let { skipUntil, tap, delay } = rxjs.operators;

let stopper$ = EMPTY.pipe(delay(2000));

let s$ = interval(600).pipe(
    tap(v => print('tapping...')),
    skipUntil(stopper$),
);

s$.subscribe(
    null, null,
    () => print('s$ complete')
);

stopper$.subscribe(
    null, null,
    () => print('stopper$ complete')
);

function print(text) {
    let el = document.getElementById('output');
    el.innerHTML = el.innerHTML + text + '\n';
}
```

**Expected behavior**
I would expect `s$` to complete as soon as stopper$ completes, and display `s$ complete` on the browser window immediately after `stopper$ complete` shows. `s$` could have many subscribers, and a heavy source observable, and I think that it not competing causes a completely useless waste of resources.

**Environment**
- Runtime: all
- RxJS version: 6.5.5

**Additional context/Screenshots**

Output of the above script:
```text
tapping...
tapping...
tapping...
stopper$ complete
tapping...
tapping...
tapping...
tapping...
tapping...
tapping...
tapping...
tapping...
```

**Comment by cartant** [comment]
If the notifying observable completes before emitting a notification, it should not complete the observable to which the operator has been applied, so this looks to be the correct behaviour, to me.

There are other issues related to this, as the behaviour of some other operators differs and is incorrect. Changes to make operators that use notifier behave in a consistent manner are going to be made in the next major version and I've listed some in this issue: https://github.com/ReactiveX/rxjs/issues/5372

**Comment by kwonoj** [comment]
Fyi it's documented behavior: https://github.com/ReactiveX/rxjs/blob/master/src/internal/operators/skipUntil.ts#L13

**Comment by benlesh** [comment]
this is expected behavior.

The notifier must notify. An observable that completes without emitting a value is "empty" and will never notify. In fact, it's an `Observable<never>`. ;)
