### ISSUE TITLE
RXJS startWith() of Subject<void>() is not working as expected

### ISSUE THREAD

**Issue by rubmz** [ReactiveX/rxjs#5393]
**RxJS version:** 6.5.3

**Code to reproduce:**
```
const s$ = new Subject<void>();

const a = s$.pipe(
  startWith(),
  tap(() => console.log('event!');
).subscribe();

```
**Expected behavior:**
Expecting the subject to fire! Or at least I expect the RXJS library to allow me to do this somehow reasonably.

**Actual behavior:**
There is no event fired.

**Additional information:**
If you put something inside the **void** startWith() such as: `startWith(7)` it **will** work. Just, not very expected that you **would** have to do that. And, someone in my team just might "fix" it...

Is <void> Subjects a bad practice?

Is there another nicer way to startWith()?

**Comment by martinsik** [comment]
Nothing will happen until you subscribe. Or are you looking for `BehaviorSubject`?

**Comment by rubmz** [comment]
> Nothing will happen until you subscribe. Or are you looking for `BehaviorSubject`?

Nope. Updated the question with a subscribe. The point is not having a behavior subject, as sometimes you need to use an existing Subject(). 

BTW you simply cannot initialize a new BehaviorSubject<void>(); you must give it a value (which isn't a void...) Nevertheless this is not the case here.

**Comment by rubmz** [comment]
Actually Managed :)

`const d = new BehaviorSubject<void>(undefined);`

Still not the point... 

Anyway, this is not a hugely important BUG, just a point to made clear if anyone needs a Subject<void>, and make sure it emits a start signal.

**Comment by cartant** [comment]
`startWith` has a [varargs](https://github.com/ReactiveX/rxjs/blob/dfa239d41b97504312fa95e13f4d593d95b49c4b/src/internal/operators/startWith.ts#L62) signature and when called with no arguments, there are no values with which the stream is to start, so this is the expected behaviour. If you want to use it with `Subject<void>`, use `startWith(undefined)`.

**Comment by rubmz** [comment]
As said, I put that here so it's clearer if anyone bump the same wall. Note that it is not very common to pass 'undefined' as variable, so this is confusing.
