### ISSUE TITLE
UB | Subscription data modifies other subscriptions data. 

### ISSUE THREAD

**Issue by baesparza** [ReactiveX/rxjs#5398]
## Bug Report

**Current Behavior**
I'm using Angular9, Rxjs, and AngularFire. I've created an observable that fetch some users, and use ShareReplay(1), so only fetch the db once. The UB is that I subscribe 2 times to this observable, in one I order the values and splice the top 5, in the other one I group users. These are 2 different subscriptions to the same observable and when I subscribe to the second one the data incoming is missing the spliced users from the first one. Thanks in advance.

**Reproduction**
- REPL or Repo link:
https://github.com/InDevelopmentCompany/SGM-Frontend/blob/develop/projects/webapp/src/app/mentors/list-mentors/list-mentors.page.ts
```ts
// obserbable I've created
 private mentorsCollection = this.route.params
    .pipe(
      this.perf.trace('list mentors'),
      map(params => this.db.collection('academic-periods').doc(params.periodId).ref),
      map(periodRef => this.db.collection<FirestoreMentor>('mentors', r => r
        .where('period.reference', '==', periodRef)
        .orderBy('displayName')
      )),
      switchMap(collection => collection.valueChanges()),
      shareReplay(1),
      tap(mentors => console.log(mentors.length))                /** <=========== this logs 68 */
    );

// first subscription
 private getBestMentors() {
    this.subs.sink = this.mentorsCollection
      .subscribe(mentors => {
        console.log(mentors.length);                                             /** <=========== this logs 68 */

        this.bestMentors = mentors
          .sort((m1, m2) => m2.stats.accompanimentsCount - m1.stats.accompanimentsCount)
          .splice(0, 5)
      });
  }

// second subscription
private groupMentorsByArea() {
    this.subs.sink = this.mentorsCollection
      .subscribe(mentors => {
        console.log(mentors.length);                             /** <=========== this logs 63 */

        const mentorPerArea: Map<AreasIds, AreaStat> = new Map();

        // for each mentor, store it in corresponding area entry
        mentors.forEach(mentor => {
          const areaId = mentor.area.reference.id as AreasIds;


          // Increment the data already stored
          if (mentorPerArea.has(areaId)) {
// more code ================
```

**Expected behavior**
Subscription internal data should not modify the observable or other subscriptions

**Environment**
- RxJS version: ~6.5.4

**Additional context/Screenshots**
![image](https://user-images.githubusercontent.com/24482939/79696454-70ca9b00-8242-11ea-9ef6-f3c937f140c9.png)

**Comment by cartant** [comment]
> Subscription internal data should not modify the observable or other subscriptions

No, this behaviour should not be expected. This isn't a bug. What you are seeing is the expected behaviour.

The value that flows through the composed observable is not internal and ensuring that mutations made to it by subscribers are isolated is not this library's responsibility. Implementing this would be far too inefficient.

If you want this behaviour, add a `map` after the `shareReplay` and clone or proxy the value there.

**Comment by baesparza** [comment]
Thanks a lot, have a great day.
