### ISSUE TITLE
Comprehensive marble tests for concatMap

### ISSUE THREAD

**Issue by staltz** [ReactiveX/RxJS#540]
(I didn't find tests for concatMap, maybe we should have it)

**Comment by blesh** [comment]
Yes we should. I just found that same thing for scan: #555. I think we need to go back to @trxcllnt's original mega-pr and make sure we have all of the operators created at that point tested.

**Comment by staltz** [comment]
I'll take this one.

**Comment by staltz** [comment]
Found a potential bug.

RxJS 4 does this:

```js
var e1 = hot(    '--a---b---c---|');
var inner = cold(  '-1-2-3-4|    ');
var expected =   '---1-2#        ';

var result = e1.concatMap(value => {
  if (value === 'b') {
    throw 'error';
  }
  return inner;
});
```

while RxJS Next does this:

```js
var e1 = hot(    '--a---b---c---|');
var inner = cold(  '-1-2-3-4|    ');
var expected =   '---1-2-3-4#    ';

var result = e1.concatMap(value => {
  if (value === 'b') {
    throw 'error';
  }
  return inner;
});
```

If we are to mirror RxJS 4's functionality, then it's a bug. But we might also be redefining how concatMap should work.

Feedback? @blesh ?

**Comment by trxcllnt** [comment]
@staltz not a bug, just an artifact of changing the default scheduling model from trampolining to recursive. Try your first example in Rx 4 using the ImmediateScheduler and you'll get the same results as the Rx Next example.

**Comment by staltz** [comment]
Good to know

**Comment by staltz** [comment]
Can be closed.
