### ISSUE TITLE
rjxs-compat undeclared dependency on rxjs

### ISSUE THREAD

**Issue by pelmers** [ReactiveX/rxjs#5406]
Package.json of `rxjs-compat` lists no dependencies:
https://github.com/ReactiveX/rxjs/blob/daf37f64ee8e2070d2c260b5f723eda7f4b83579/compat/package.json#L1-L7

However in the first executable line of `Rx.ts` it imports 'rxjs':

https://github.com/ReactiveX/rxjs/blob/daf37f64ee8e2070d2c260b5f723eda7f4b83579/compat/Rx.ts#L5

Why doesn't the package.json of `rxjs-compat` declare `rxjs` as a dependency?

**Comment by bestander** [comment]
I think it should declare rx.js as peerDependency so that npm complains if developer forgot to include it.

**Comment by cartant** [comment]
With npm version 7, using `peerDependencies` introduces its own problems.

IMO, it's pretty clear what `rxjs-compat` does and - given that it's not going to be supported in RxJS version 7 and has been out in the wild for about three years without this being a major issue - I'm closing this.
