### ISSUE TITLE
how can i get fromPromise from rxjs.umd.js?

### ISSUE THREAD

**Issue by dunhuang** [ReactiveX/rxjs#5408]
## Bug Report

**Current Behavior**
Not able to get 'fromPromise' from rxjs.umd.js.

**Reproduction**
- REPL or Repo link:
(you can use https://stackblitz.com/ to create one to attach here)

```js
var your => (code) => here;
```

**Expected behavior**
A clear and concise description of what you expected to happen (or code).

**Environment**
- Runtime: [e.g. Node v${x}, Chrome v${x}]
- RxJS version:
- (If bug is related) Loader, build configuration: [e.g webpack, angular-cli version, config]

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by kwonoj** [comment]
`from` accepts promise.

```
rxjs.from(Promise.resolve(4)).subscribe(console.log.bind(console));
```
