### ISSUE TITLE
forkjoin marbel diagram is wrong.

### ISSUE THREAD

**Issue by eng-dibo** [ReactiveX/rxjs#5416]
in [forkJoin](https://rxjs.dev/api/index/function/forkJoin) doc, the documentation says that the output observable emmits values in the same order of the input observables.

but in the attached marbel diagram, it dosen't.
the output value is (e ,4 ,j)
i.e: values emitted by obs1, obs3, obs2 (not obs1, obs2, obs3)

the expected result is: (e, j, 4) and not (e, 4, j)

![image](https://user-images.githubusercontent.com/57308531/81299268-40726180-9076-11ea-86ea-bcd20e38ae31.png)

**Comment by sijusamson** [comment]
@cartant is anyone assigned for this ?

**Comment by cartant** [comment]
@sijusamson No, but I doubt this can be fixed ATM because the marble diagram generation is currently being changed.

**Comment by sijusamson** [comment]
So do i need to work on this ?

**Comment by cartant** [comment]
@sijusamson see the links in this comment and the PR in which it was made. The marble diagram generation is being completely replaced, so I don't think there's anything that you can do, ATM. However, if you want to acquaint yourself with Swirly - see #5019 - it's highly likely that you'll be able to help with the generation of the new diagrams soon, if that's something you'd be interested in. If that is the case, keep an eye on #5422.

**Comment by jakovljevic-mladen** [comment]
Closing as fixed in #4940.
