### ISSUE TITLE
[docs] flatMap page almost completely refers to mergeMap

### ISSUE THREAD

**Issue by zrev2220** [ReactiveX/rxjs#5418]
### Documentation Related To Component:

[flatMap](https://rxjs-dev.firebaseapp.com/api/operators/flatMap), [mergeMap](https://rxjs-dev.firebaseapp.com/api/operators/mergeMap)

### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [ ] documentation needs clarification
- [X] error(s) in example
- [ ] needs example

### Description Of The Issue

The documentation page for the `flatMap` operator is almost 100% identical to the page for `mergeMap`—the only differences I can tell are the **title** and the **function signature name** at the top of the page (on `flatMap`'s page it correctly says "flatMap", and on the `mergeMap` page they say "mergeMap").

Besides this, the entire page for `flatMap` consistently refers to `mergeMap`, including in the:
* [Marble diagram](https://rxjs-dev.firebaseapp.com/api/operators/flatMap#description)
* [Code example](https://rxjs-dev.firebaseapp.com/api/operators/flatMap#example)
* [Overload signatures](https://rxjs-dev.firebaseapp.com/api/operators/flatMap#overloads)

The [See Also](https://rxjs-dev.firebaseapp.com/api/operators/flatMap#see-also) section is even identical.

It seems the docs for `mergeMap` were copied with the intent to edit to describe `flatMap`, but very little actually got changed.

**Comment by cartant** [comment]
FWIW, `flatMap` is an alias for `mergeMap`: https://github.com/ReactiveX/rxjs/blob/6.5.5/src/internal/operators/index.ts#L46

The docs are generated from the TSDoc comments and there are none for `flatMap`.

**Comment by robations** [comment]
Related: in my IDE it flags the `flatMap` operator as deprecated, but in the docs https://rxjs.dev/api/operators/flatMap (assuming they are up to date) it makes no mention of this, which is confusing. Maybe aliases and deprecated functions should be flagged more clearly in online help?

This doesn't seem to make its way into the documentation:

```typescript
/**
 * @deprecated renamed. Use {@link mergeMap}
 */
export const flatMap = mergeMap;
```

**Comment by cartant** [comment]
Closing this, as the v7 docs now show:

> Renamed to `mergeMap`. Will be removed in v8.
