### ISSUE TITLE
Make schedulers compatible with babel-plugin-transform-imports

### ISSUE THREAD

**Issue by hlehmann** [ReactiveX/rxjs#5421]
## Feature Request

All methods are compatible with `babel-plugin-transform-imports` except schedulers due to their renaming.

```
# index.js
export { asap as asapScheduler } from './internal/scheduler/asap';
export { async as asyncScheduler } from './internal/scheduler/async';
export { queue as queueScheduler } from './internal/scheduler/queue';
export { animationFrame as animationFrameScheduler } from './internal/scheduler/animationFrame';
``` 

`babel-plugin-transform-imports` allow some build/dev time improvements but require to keep the same name for reexported variables (or to use `default`) and that's the case for almost all exports.

Would it be possible in future version to avoid this renaming ?

**Comment by cartant** [comment]
Sounds reasonable to me.

**Comment by cartant** [comment]
> Would it be possible in future version to avoid this renaming ?

In version 7, both names are exported:

https://github.com/ReactiveX/rxjs/blob/b50926274d748c563b8371fa46e80f68250b762e/src/internal/scheduler/asap.ts#L39-L44

https://github.com/ReactiveX/rxjs/blob/b50926274d748c563b8371fa46e80f68250b762e/src/index.ts#L16

I'm presuming that doing so will address this issue, so I'm closing it.
