### ISSUE TITLE
mixed Symbol.observable and @@observable import order

### ISSUE THREAD

**Issue by laszlokorte** [ReactiveX/rxjs#5423]
## Bug Report

**Current Behavior**
When defining Symbol.observable after parts of RxJs have already been loaded, those operators/observables that have already been loaded use the "@@observable" fallback. Operators loaded afterwards/observables created afterwards use the `Symbol.observable`.

That causes `TypeError: invalid object where a stream was expected` when mixing those objects.

**Reproduction**

```js
import {mapTo, switchMap} from 'rxjs/internal/operators'; // uses @@ observable
import 'symbol-observable'; // or other dependency which transitively imports the ponyfil
import {timer} from 'rxjs'; // uses the now available Symbol.observable

timer(0,1000).pipe(mapTo("x")) // error TypeError: invalid object where a stream was expected
```

**Expected behavior**
Import order should not matter. RxJs should use  **either** @@ **or** symbol consistently.

**Environment**

- RxJS version: 6.5.4

**Possible Solution**
Cache the decision made here: https://github.com/ReactiveX/rxjs/blob/master/src/internal/symbol/observable.ts#L11

once '@@observable' is used as fallback it should keep being used for the entire runtime of the application

**Comment by cartant** [comment]
I cannot reproduce this and I cannot see how that assignment to the constant can be evaluated more than once - unless you have multiple `rxjs` installations in `node_modules`.

Run `npm list rxjs` or `yarn why rxjs` to see what's installed.

Unrelated, but don't import from `rxjs/internal` either.

**Comment by laszlokorte** [comment]
Hm you are right. Then it's probably a problem with the bundler because actually I see the same file being imported two times:

```
./node_modules/rxjs/_esm5/internal/symbol/observable.js
./node_modules/rxjs/internal/symbol/observable.js
```

Do you have any idea why that would be? I will dig into it.

**Comment by cartant** [comment]
Never import from an internal location.

**Comment by laszlokorte** [comment]
Those are not imports I declared myself but both files resulting in the final bundle.

**Comment by cartant** [comment]
Nevertheless, you should ensure that none of your imports - **anywhere in the app** - import from `rxjs/internal`, as I can see how that would mess up a bundler.

**Comment by laszlokorte** [comment]
You are right. It's working now. Thank your for your patience!

**Comment by cartant** [comment]
No worries.
