### ISSUE TITLE
Share() doesn't prevent the source from executing multiple times

### ISSUE THREAD

**Issue by antonkatz** [ReactiveX/rxjs#5425]
## Bug Report

**Current Behavior**
Subscribing to a source created with `from` executes it multiple times, even when using `share`

**Reproduction**
https://stackblitz.com/edit/rxjs-ijuwzu?devtoolsheight=60

```js
import { from, partition, merge } from 'rxjs'; 
import { tap, share } from 'rxjs/operators';


const source = from([1,2,3]).pipe(
  tap(console.log),
  share()
);

const [odd, even] = partition(source, x => !!(x % 2))

merge(odd,even).subscribe(x => console.log(x));
```

**Expected behavior**
The output should be `1,2,3` in any order, but without repeats

**Environment**
- Runtime: Node 14.1
- RxJS version: 6.5.5

**Additional context/Screenshots**
Using `publish` followed by `refCount` works
Possibly similar to this https://github.com/ReactiveX/rxjs/issues/4981

**Comment by kwonoj** [comment]
I think this is dupe of https://github.com/ReactiveX/rxjs/issues/5386.

**Comment by tonivj5** [comment]
> I think this is dupe of #5386.

I think so too. And I think @cartant explains it perfectly:
> This is the expected behaviour because subscription to a **synchronous** source that completes will see all notifications from that source received and an unsubscription occur **before** `subscribe` returns.


If you become your observable to asynchronous, it'll work as you expected:
```ts
const source = from([1,2,3], asapScheduler /* or asyncScheduler */).pipe(...
....
```

**Comment by antonkatz** [comment]
Thank you guys! This explains my issue entirely, and why I don't necessarily see it in other places.
