### ISSUE TITLE
Observable that is created by a generator can't repeat

### ISSUE THREAD

**Issue by miyamonz** [ReactiveX/rxjs#5428]
## Bug Report

**Current Behavior**
Observable that is created by a generator can't repeat.

**Reproduction**
- REPL or Repo link: https://codesandbox.io/s/stupefied-hermann-5o802?file=/src/index.js

of course it works
```js
from([0, 1, 2])
  .pipe(repeat(3))
  .subscribe(console.log);
```
but below doesn't work

```js
function* gen() {
  let i = 0;
  while (true) {
    yield i++;
    if (i > 2) return;
  }
}
from(gen())
  .pipe(repeat(3))
  .subscribe(console.log);
```

**Expected behavior**
`from(someGeneratorObject).pipe(repeat(3))` also should repeat.

**Environment**
- Runtime: Node v12.9.1, Chrome v81.0.4044.138
- RxJS version: 6.5.5

**Comment by tonivj5** [comment]
I think this is the expected behavior and it's how iterators work:
```ts
const iterator = gen();
iterator.next(); // 0
iterator.next(); // 1
iterator.next(); // 2
iterator.next(); // undefied, iterator is done
iterator.next(); // undefied, iterator is done
...
```

If you want to get a new iterator with each new subscription, you can use `defer`:
```ts
defer(() => gen()) //or  from(defer(() => gen()))
  .pipe(repeat(3))
  .subscribe(console.log);
```

It works as you expected

**Comment by cartant** [comment]
As Toni has explained, what you are seeing is the expected behaviour.
