### ISSUE TITLE
groupBy should support typeguards

### ISSUE THREAD

**Issue by benlesh** [ReactiveX/rxjs#5439]
I'm not even sure this is possible, but it would be great if this "just worked":

```ts
function isNumber(input: any): input is number {
   return typeof input === 'number';
}

of('a', 1, 'b', 2).pipe(
   groupBy(isNumber),
   mergeMap(group => {
     if (group.key) {
         return group; // Observable<number>
     } else {
         return group; // Observable<string>
     }
   });
)
```

**Comment by cartant** [comment]
This sounds like `splitBy` - see #3807 - which I implemented [here](https://github.com/cartant/rxjs-etc/blob/master/source/operators/splitBy.ts) but I didn't open a PR for it - I guess I wasn't entirely happy with it. I can take another look.

**Comment by cartant** [comment]
Hmm, this is a little weird. It would seem that adding this signature should do it:

```ts
  export function groupBy<T, K extends T>(
    keySelector: (value: T) => value is K
  ): OperatorFunction<T, GroupedObservable<true, K> | GroupedObservable<false, T>>;
```

And the `key` property needs to be made `const`:

https://github.com/ReactiveX/rxjs/blob/f5c6332b6098ec5c302f8034ad2273106e301275/src/internal/operators/groupBy.ts#L281

However, the type is only narrowed within the `if` and not the `else` - which is weird:

```ts
of("a", 1, "b", 2).pipe(
  groupBy(isNumber),
  mergeMap(group => {
    if (group.key) {
      return group; // GroupedObservable<true, number>
    } else {
      return group; // GroupedObservable<true, number> | GroupedObservable<false, any>
    }
  })
);
```
