### ISSUE TITLE
ignoreElements forces to "any" the type of the input variable of a preceding operator

### ISSUE THREAD

**Issue by EnricoPicci** [ReactiveX/rxjs#5460]
## Bug Report

**Current Behavior**
When `ignoreElements()` is used after an operator which expects an input, the type of the input of the preceding operator is forced to `any`

**Reproduction**
- https://stackblitz.com/edit/rxjs-3zaonl

In the following code, the type inferred for the variable `data` is `any` while it should be `string`

```js
  let obs$: Observable<string>
  obs$.pipe(
    tap(data => {
    }),
    ignoreElements()
  );
```

**Expected behavior**
The inferred type of the variable of the variable should not change

**Possible Solution**
The solution is to use generics to define the type of `ignoreElements()` like 

```js
export declare function ignoreElements<T>(): OperatorFunction<T, never>;
```

I tried to create a PR but was not able to push the branch to https://github.com/ReactiveX/rxjs.git/

**Comment by cartant** [comment]
It should infer `never`. It does for me:

<img width="484" alt="ignoreElements" src="https://user-images.githubusercontent.com/3878593/83145077-9d25e100-a137-11ea-8802-d19f6979deba.png">

https://github.com/ReactiveX/rxjs/blob/3d6e4c5bf2ba2eec31fdf2498a9fcc9ad364511f/src/internal/operators/ignoreElements.ts#L33

**Comment by tonivj5** [comment]
I think what @EnricoPicci is reporting is that `data` is inferred as `any` when `ignoreElements` operator is used.

From its stackblitz:

```ts
  obs$.pipe(
    tap(data /* <--- is any */ => {
    }),
    ignoreElements()
  );

  obs$.pipe(
    tap(data /* <--- is string */ => {
    }),
  );
```

**Comment by cartant** [comment]
With the latest versions of RxJS and TypeScript, it's fine in VS code, so IMO this is not an RxJS issue:

<img width="503" alt="ignored" src="https://user-images.githubusercontent.com/3878593/83149379-589d4400-a13d-11ea-870c-4837f86956af.png">

**Comment by tonivj5** [comment]
You're right @cartant :+1:

It works in other platfroms (using latest) https://codesandbox.io/s/great-surf-f7bi5?file=/src/index.ts

**Comment by EnricoPicci** [comment]
Thanks, it is clearly not an rxjs issue
