### ISSUE TITLE
tap does not pass in the index of the tapped resource

### ISSUE THREAD

**Issue by paulferaud** [ReactiveX/rxjs#5461]
## Bug Report

**Current Behavior**
`tap` does not pass in the index of the tap’ed element, the way `map` does.

**Reproduction**

```js
myObservable.pipe(
    tap((arg, i) => {
        ....
    }),
);
or
myObservable.pipe(
    tap({
        next: (arg, i) => {
            ....
        },
    }),
);
```

**Expected behavior**
I’d have expected the index of the tapped event to be passed.

**Possible Solution**
Pass the index the way `map` does.

**Workaround**
If you only care about the next events, you can use `map`, and return the current value, but it’s kind of clunky. It also does not work if you plan to tap errors/completion.

**Comment by cartant** [comment]
This is not a bug. `tap` mirrors `subscribe`'s interface, not `map`'s. And `subscribe` accepts an observer - the `next` method of which cannot be passed an index.

**Comment by paulferaud** [comment]
Yeah, actually that makes sense. Thanks.
