### ISSUE TITLE
Make sure that operations in pipes do not modify "original"/subject values via memory

### ISSUE THREAD

**Issue by Carnageous** [ReactiveX/rxjs#5466]
## Feature Request

**Is your feature request related to a problem? Please describe.**
This is related to a [question](https://stackoverflow.com/questions/61745849/difference-between-returning-a-copy-or-manipulating-original-objects-in-array-pr) I asked on StackOverflow. I did not find any similar issues, so sorry if this was in fact discussed erlier.

I want to do unit conversion for an array of objects that are stored in an BehaviorSubject. For that I am using a setup like this: (Angular 9, 3xjs 6.5.5).

```typescript
private _sequences: BehaviorSubject<Sequence[]> = new BehaviorSubject(null);

public readonly sequences: Observable<Sequence[]> = combineLatest([this._sequences, this.unitService.preferredWeightUnit]).pipe(
    // This pipe is where all unit conversions for sequences is happening!
   // It should return a an array of objects similar to _sequences, except the units should be converted.

    // For every sequence, convert Price and inventory into the preferred display unit
    map(([sequences, preferredWeightUnit]) =>
      sequences?.map(sequence => this.convertSequenceUnits(sequence, "kg", preferredWeightUnit))
    )
  );
```
in "this.convertSequenceUnits" the only thing happening is some values are multplied by certain factors.

Generally the above works, but if you have a look at this [stackblitz](https://stackblitz.com/edit/ng-rxjs-pipe-question) you will see that when subscribing and unsubscribing to the observable, the values are converted multiple times. The answer to the linked SO question suggests this is because the subject values are modified directly because the map function is applied to the arrays stored in the subjects - so through a reference in memory. I don't know if this is a bug but it was very unsuspected to me - **I thought the subject's value could not be modified just by calling .pipe().**

**Describe the solution you'd like**
In the linked SO question, the answer says deep-cloning the object/array that should be modified is enough to fix this, so what I am doing at the moment is a simple `JSON.parse(JSON.stringify(obj))`, but I think this is just wrong. I feel like the subject should never be modified except `.next()` is called on it (though I am for sure no expert in reactive programming or rxjs). I think rxjs should make sure that the values are not modified through array references. So the "bug" that rounding is done multiple times when subscribing to the piped subject should be fixed.

**Describe alternatives you've considered**
For me the only alternative is to manually deep-clone objects inside the pipe.

I hope I did not miss any important architektural decision that leads to this behavior. As I said I'm sure that you designed rxjs very carefully and well.

Thank you and have a great day!

**Comment by Carnageous** [comment]
Follow up question: If this behavior is in fact expected I would be interested in **why** there are cases where subjects can be modified "directly" and if there is a list of cases **where** this rule applies.

**Comment by cartant** [comment]
IMO, this is not the library's responsibility: https://github.com/ReactiveX/rxjs/issues/5398#issuecomment-616208179

**Comment by kwonoj** [comment]
Observable chain passes forward references to its emitted value so as explained above it is expected. For the following answer, any observable consumer should not expect observable contract will be honored as soon as trying to mutate values across subscriber chain.

> why there are cases where subjects can be modified "directly"

I don't think this is true, for some primitive value it _may_ possible to work like that but it's only cause those values are primitive doesn't affect by modification to reference. In any case, consumer should not rely on it.
