### ISSUE TITLE
Test Case examples in docs for each operator in RXJS 

### ISSUE THREAD

**Issue by arjunkesava** [ReactiveX/rxjs#5467]
### Documentation Related To Component:

All operators in RXJS

### Please check those that apply

- [ ] typo
- [x] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [x] needs example

### Description Of The Issue

First of all, thanks for building RXJS.

Second, there is no documentation about the test cases examples for each operator.
For example, I feel happy to use flatMap or switchMap, but I'm unable to write test cases for such operators.

I recommend to add a section in every document page (ex: https://rxjs.dev/api/operators/flatMap)
to have code for running test cases on that specific operator.

Something similar to this: https://ngrx.io/guide/effects/testing

**Comment by cartant** [comment]
Unlike NgRx and Angular, RxJS is not a framework. Indeed, it is application framework and test framework agnostic.

If you are testing RxJS-specific functionality, documentation on testing with marble diagrams is here: https://rxjs.dev/guide/testing/marble-testing

If you are testing application functionality, you should use whatever assertions/expectations your test framework provides. It's this library's responsibility to tell you how to do that, IMO.
