### ISSUE TITLE
Fix Promise dependency that breaks library in IE11

### ISSUE THREAD

**Issue by kirk-l** [ReactiveX/rxjs#5470]
## Bug Report

**Current Behavior**
Starting with v6.5.4, RxJS no longer works in IE11 without a Promise polyfill. The error is caused by the change in #5183.

https://github.com/ReactiveX/rxjs/blob/743c00bc520d7890e2782616f35503d57ae12441/src/internal/util/Immediate.ts#L2

`Promise.resolve()` is executed as soon as the library loads, preventing the use of RxJS without a Promise polyfill.

**Reproduction**
You can recreate this in a modern browser with:
```html
<script>
  window.Promise = undefined;
</script>
<script src="https://unpkg.com/rxjs@6.5.5/bundles/rxjs.umd.js"></script>
```
And get a TypeError:

> Uncaught TypeError: can't access property "resolve", Promise is undefined

**Expected behavior**
I would expect RxJS to work in IE11, as long as I don't call functions that use Promise.

**Environment**
- Runtime: Internet Explorer 11
- RxJS version: 6.5.5 (last worked in 6.5.3)

**Possible Solution**
Switch back to using `Promise.resolve()`—and not a constant (`RESOLVED`)—in `Immediate.setImmediate`.

**Comment by cartant** [comment]
> RxJS no longer works in IE11 without a Promise polyfill.

AFAICT, prior to that change you would still have needed a polyfill, as RxJS does not provide one. The change you referenced necessitates that `Promise` needs to be polyfilled before RxJS is loaded, but that is what applications should be doing anyway, so IMO this is not a bug.
