### ISSUE TITLE
Discuss deprecation and removal of `publishLast` and `AsyncSubject`

### ISSUE THREAD

**Issue by benlesh** [ReactiveX/rxjs#5474]
I want to discuss the removing `publishLast` and `AsyncSubject` in upcoming versions of RxJS. I, personally, have never found them useful. I think they add weight to the library, and what they do can be accomplished with `publishReplay` and `takeLast(1)`.

**Comment by cartant** [comment]
`AsyncSubject` is used in the implementation on `bindCallback` and `bindNodeCallback`, so those would need to be reimplemented - which is fine - and if that happens, some consideration should/could be given to having the implementation store their state on a per-subscription basis. See https://github.com/ReactiveX/rxjs/issues/1401

**Comment by benlesh** [comment]
Core team meeting: Revisit this at a later time.
