### ISSUE TITLE
TimestampProviders and TestScheduler "run mode"

### ISSUE THREAD

**Issue by benlesh** [ReactiveX/rxjs#5475]
Currently, `TestScheduler` "run mode" will patch all schedulers by default. This means that everywhere we were only using schedulers as `TimestampProvider`s, will use the test scheduler's currently time when `now()` is called.

However... we're going to be breaking people's tests with a move to use `Date` or `performance` as default `TimestampProviders`.

I see two solutions:

1. Have `TestScheduler` temporarily monkey patch `Date.now` and `performance.now` to accommodate bare uses of things like `animationFrames`, etc.
2. Create _very, very light_ wrappers around `Date.now` and `Performance.now` that are used internally (but not exported, yet) that we monkey patch when we are in run mode.

I'm inclined to say that #2 is the best answer, and the least likely to break others.

**Comment by cartant** [comment]
Pretty sure this is closed by #5607.
