### ISSUE TITLE
first/tap operators should unsubscribe before emit next value

### ISSUE THREAD

**Issue by Enuvid** [ReactiveX/rxjs#5487]
## Bug Report

**Current Behavior**

Currently, we are unsubscribing from source observables after emit the last message next to the chain. In some cases, it can raise incorrect and unexpected behavior (it seems to me).
In example below, we are still have processing new messages second observable in `merge` after `first` have emitted the first message. But expected behavior is that `first` operator must unsubscribe from all sources on receiving the first message.

Also, we have strange behavior: we can emit error from second observable and this exception will go through `first` operator and handle (in my example)  in `catchError`, but if we try to pass just a value through `first`, this operator (actually `tap` operator inside of `first`) will omit this message.

**Reproduction**

```js
const notificator = new Subject();

merge(
  timer(1)
    .pipe(
      tap((m) => console.log('value from first: ', m)),
    ),
  notificator.pipe(
    tap(() => console.log('value from notificator')),
    switchMap(() => throwError(new Error('Some error'))),
))
  .pipe(
    first(),
    catchError((err) => {
      console.log('Catching error: ', err)
      return throwError('Continue receive error after first value');
    }),
    tap((value) => {
      console.log('value: ', value);
      notificator.next(null);
    })
  ).subscribe(
    (value) => console.log('Next value: ', value),
    (err) => console.log('Error: ', err),
  );
```
Output:
```
value from first: 0
value: 0
value from notificator
Catching error: Error {}
Error: Continue receive error after first value
```

You can try it [here](https://stackblitz.com/edit/rxjs-etniuk).

**Expected behavior**

As I told before, I think that we shouldn't get any effects (include errors) from source observables after the limit of allowed values in stream reached. And more, we should unsubscribe from them, to prevent any calculations inside source chain, we should unsubscribe before passing the last value next.

**Environment**
- Runtime: Chrome/83.0.4103.97
- RxJS version: 6.5.2

**Possible Solution**

In `take` operator we overriding next handler to: 

https://github.com/ReactiveX/rxjs/blob/3f3c614d8b86c68d271a1db995ff11c61842e757/src/internal/operators/take.ts#L79-L89

I suggest changing them to make unsubscribe stuff before emitting next value. Also, this will allow us to omit ```if (count <= total)``` this strange check, because if we already unsubscribed from source that we will no longer receive a message.

If this change can affect something (backward compatibility), I think we should at least override `_error` handler to prevent passing errors. But I think, more correct just unsubscribe before next.

I will be glad to make a pull request if you agree with my arguments.

**Comment by backbone87** [comment]
this behavior is kind of expected.

a workaround is to use a scheduler:
```ts
notificator.pipe(
  observeOn(asapScheduler),
  tap(() => console.log('value from notificator')),
  switchMap(() => throwError(new Error('Some error'))),
)
```

**Comment by Enuvid** [comment]
I am not sure that it kind of expected that a simple operator, which should control values number in the stream, can emit more messages (even errors) than specified.

It's also strange that it works with errors, but not works with messages. Maybe nice to `this.unsubscribe()` (because we don't need this stream anymore) before put value `next`.

**Comment by benlesh** [comment]
Well @cartant has other opinions. So I'm reopening this to hear him out.

**Comment by benlesh** [comment]
I suspect the argument is that the `first` operator should close after it gets the nexted value? That's an interesting thing to think about... I'll think about it more... perhaps you're right. It's certainly a weird case though.

**Comment by benlesh** [comment]
I see the issue, and I can fix it. Shouldn't be too bad. `first`, `take`, `takeWhile`, et al, will need to be addressed.

**Comment by benlesh** [comment]
Unfortunately, the fix for this is a breaking change, and we're unable to have it until v8.
