### ISSUE TITLE
supporting absoluteTime, selector for delay() operator?

### ISSUE THREAD

**Issue by kwonoj** [ReactiveX/RxJS#549]
Current implementation of `delay` operator supports only relative time delay as stated in signature

`delay(delay: number, scheduler: Scheduler)`

compare to RxJS4, which supports `absoluteTime` also `delayDurationSelector`.

would like to ask if it's planned to expand current implementation to support rest of behaviors.

Personally, since it has somewhat polymorphic behavior would like to separate surface such as below (course function name could be different)

```
delay(delay: number | Date, scheduler: Scheduler)
delayWhen(delayDurationSelector: function, subscriptionDelay:Observable)
```

**Comment by kwonoj** [comment]
Would like to take this one if this reaches agreement, since I'm working on expanding marble test for this operator.

**Comment by blesh** [comment]
That seems reasonable. I'm on mobile, does delayWhen align with bufferWhen? If so, it sounds good to me

**Comment by kwonoj** [comment]
somewhat similar, but not exactly. Major difference is `bufferWhen` accepts observable directly as closing selector, while above `delayWhen` simply mimic RxJS4 signature to accept `function` as selector. If it's to be aligned, signature will be looks like

`delayWhen(delayDurationSelector: Observable, subscriptionDelay?:Observable)`

not sure if selector observable can get rid of `subscriptionDelay` completely.

**Comment by luisgabriel** [comment]
`Observable.timer()` in RxJS 4 also accepts absolute time: https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/timer.md

Should we add this behavior to RxJS Next?

**Comment by blesh** [comment]
> Should we add this behavior to RxJS Next?

@luisgabriel yes we should... closing this issue though because it's done. I'll open another.
