### ISSUE TITLE
TestScheduler: Should support *lack* of subscriptions in expectSubscriptions`

### ISSUE THREAD

**Issue by benlesh** [ReactiveX/rxjs#5499]
Currently, there is no way to properly test a _lack_ of subscription, AFAICT. (Maybe I'm wrong? haha)

So let's say I want to test something like this:

```ts
testScheduler.run(({ cold, expectObservable, expectSubscriptions }) => {
  const source = cold('  ---a---b---c---d---|');
  const expected = '     --------------------';
  const subscriptions = '--------------------';
  const result = source.pipe(subscribeOn(testScheduler, Infinity));
  expectObservable(result).toBe(expected);
  expectSubscriptions(source.subscriptions).toBe(subscriptions);
});
```

Ran into this while trying to test a bug in `subscribeOn`.

**Comment by cartant** [comment]
Can you pass an empty array?

```ts
expectSubscriptions(source.subscriptions).toBe([]);
```

**Comment by benlesh** [comment]
@cartant ... yes, that's a valid workaround. I think this issue is confusing enough that we should make sure that `.toBe('   ')` and `.toBe('-------')` work the same way as `.toBe([])`.

Further, it's plausible that people will have tests that expect subscriptions like `['^---!', '----', '---^--!']` or the like.  I think what we need to do is just take the `{ subscribed: null, unsubscribed: null }` (or whatever that outputs), and filter them out of the resulting arrays. Then everything should "just work" as expected.
