### ISSUE TITLE
`race` emits values from two observables

### ISSUE THREAD

**Issue by xiaody** [ReactiveX/rxjs#5503]
## Bug Report

**Current Behavior**
In some condition, `race(a$, b$)` emits values from both observables.

**Reproduction**
- REPL or Repo link:
https://stackblitz.com/edit/rxjs-race-subject?file=index.ts

```js
const a$ = new Subject();
const b$ = of('b').pipe(
  tap(() => a$.next('a')),
)
race(
  a$, 
  b$
).subscribe(x => console.log(x)) // outputs a b
```

**Expected behavior**
Outputs `a`. Because `a$` wins.

**Environment**
- Runtime: Chrome 83.0.4103.97
- RxJS version: 6.5.5

**Possible Solution**
Not sure.

**Additional context/Screenshots**
None.

**Comment by kwonoj** [comment]
This is pretty much expected afaik with current RxJS behavior, since both observable is synchronous and second observable trying to entrant to first observable's value.

**Comment by xiaody** [comment]
The official doc says `race()`
> Returns an Observable that mirrors the first source Observable to emit an item.

I don't expect current result in this example. The returned observable mirrors none of the inputs.

Maybe you call it a known limitation, but not an expected behavior.

**Comment by kwonoj** [comment]
Since both are synchonous observable and you're trying to entrant one from another, in this case emission happens in same time synchronously. Synchronous obsverables design works as expected and it also meets doc since both emits same time. This is not limitation.
