### ISSUE TITLE
Rxjs Library

### ISSUE THREAD

**Issue by ersimont** [ReactiveX/rxjs#5518]
Sorry to send this in an issue request; I'm not sure how else to reach out. Over the weekend I watched Ben Lesh's ng-conf talk. At the end he said if we're building a library around rxjs to reach out & let you know about it (https://youtu.be/OC6g4yFsw0w?t=1876). Here it is: https://github.com/simontonsoftware/s-rxjs-utils. I'd be happy to take any advice if there something in there I could have done better.

It's just a small collection of operators I've wanted in the past & couldn't find built in. Some of them I do end up using somewhat frequently, like `cache()` and `logValues()`.

Another library I am more excited about is https://github.com/simontonsoftware/ng-app-state, but that's more built around `@ngrx/store` so I'm not sure if that's the kind of thing Ben was looking to hear about.

**Comment by cartant** [comment]
A short while ago, I created a site that has a listing of community RxJS packages. You're welcome to open a PR in that repo to add yours to the list.

https://github.com/cartant/rxjs-xyz/blob/main/CONTRIBUTING.md
