### ISSUE TITLE
MapTo returns prematurely / does not wait for observable to emit a value before returning

### ISSUE THREAD

**Issue by vorong** [ReactiveX/rxjs#5525]
## Bug Report

**Current Behavior**
MapTo returns prematurely, i.e. before the observable has emitted a value. It seems that because mapTo ignores the value, it is also ignoring whether or not the observable has returned. As far as I understand, mapTo(mappedValue) should be equivalent to map(ignoredValue => mappedValue), but in this case it is not.

**Reproduction**
- REPL or Repo link: https://stackblitz.com/edit/map-vs-mapto

**Expected behavior**
I would expect both getContentWithMap() and getContentWithMapTo() to function identically in the stackblitz example.

**Comment by kwonoj** [comment]
> As far as I understand, mapTo(mappedValue) should be equivalent to map(ignoredValue => mappedValue)

this is incorrect. MapTo always map to eager evaluation of value directly to avoid evaluating value per each time emission as `map` does, and that's purpose. If you'd like fixed value but per emission, `map(() => fixed)` is way to go.
