### ISSUE TITLE
Errors suppressed in jest

### ISSUE THREAD

**Issue by joshribakoff** [ReactiveX/rxjs#5530]
## Bug Report

**Current Behavior**
When run under jest, the following passes w/ no error output. If you comment out the it() block & run the same inner block of code with Node, the error "test" is correctly output. If you add the it() block & run it with jest again, and uncomment the lines after "these work:", you see it doesn't appear to be a jest problem.

**Reproduction**
- REPL or Repo link:
(you can use https://stackblitz.com/ to create one to attach here)

```js
var Rx = require('rxjs');
var RxOps = require('rxjs/operators')

it('', () => {    
    const effect = () =>
        Rx.defer(() => Promise.reject("rejected")).pipe(
            RxOps.catchError(() => {
                throw new Error("test");
                // return of(null);
            })
        );

    const stream$ = new Rx.Subject();
    stream$.pipe(RxOps.mergeMap(effect)).subscribe((val) => {
        console.log(val);
    });
    stream$.next("foo");

    // these work:
    // throw new Error('test')
    // console.error('test')
})
```

**Expected behavior**
NodeJS error output should also show up in Jest.

**Environment**
- Runtime: browser & node
- RxJS version: 6.5.5
- (If bug is related) Loader, build configuration: [e.g webpack, angular-cli version, config]

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by kwonoj** [comment]
jest does not gaurantee any async operation to complete & collect its output if test is set to sync and there's async code running.

You specified to throw error in async 


```
.defer(() => Promise.reject("rejected")).pipe(
            RxOps.catchError(() => {
                throw new Error("test");
                // return of(null);
            })
        );
```

then test runs in sync, so jest does not collect leftover error.

Change test to this

```
it('', (done) => {
    const effect = () =>
      Rx.defer(() => Promise.reject("rejected")).pipe(
        RxOps.catchError(() => {
          throw new Error("test");
          // return of(null);
        })
      );

    const stream$ = new Rx.Subject();
    stream$.pipe(RxOps.mergeMap(effect)).subscribe((val) => {
      console.log(val);
    });
    stream$.next("foo");
  })
```

Note `done` is not even being used assertion: then it'll collect error properly.

![image](https://user-images.githubusercontent.com/1210596/85626023-3b1aa780-b621-11ea-845c-bc3048edcb07.png)

We can't control test runner's behavior, so if you think this should be handled I believe you need to file an issue to jest itself.

**Comment by joshribakoff** [comment]
happens if you make the test async & await, too. I think you're wrong.

**Comment by joshribakoff** [comment]
ah no you were right, this works:

```
it('', async () => {    
    const effect = () =>
        Rx.defer(() => Promise.reject("rejected")).pipe(
            RxOps.catchError(() => {
                throw new Error("test");
                // return of(null);
            })
        );

    const stream$ = new Rx.Subject();
    stream$.pipe(RxOps.mergeMap(effect)).subscribe((val) => {
        console.log(val);
    });
    stream$.next("foo");

    // these work:
    // throw new Error('test')
    // console.error('test2')

    await new Promise(()=>{})
})
```

alright something else is going on in my prod code, will keep looking. sorry for false alarm.

**Comment by kwonoj** [comment]
no worries :+1:

**Comment by joshribakoff** [comment]
ya this fails silently still fyi:

```
it(()=>{
const s = new Subject();
      s.error('foo');
      s.subscribe();
})
```

This is pretty bad DX to me.

**Comment by joshribakoff** [comment]
This also passes silently:

```
it('', () => {
      const s = new Subject();
      s.error('foo');
      s.pipe(
        catchError(() => {
          throw new Error('foo2');
        })
      ).subscribe();
})
```

If its not a bug, can we re-open as a feature request?

**Comment by kwonoj** [comment]
it's all cause of same reason: we don't throw error synchronously, so if any runtime / env / runner decide to ignore thrown error that should be reported in upstream. I don't think we'll have specific to honor jest's own behavior.

**Comment by kwonoj** [comment]
i.e if runner supposed to ignore thrown error, what we can do? in later example there's proper subscription and we throw error correctly, but jest ignored it.

**Comment by joshribakoff** [comment]
yep, you're right again :)

``` 
it('',()=>{
 setTimeout(()=>throw new Error('test'),0)
})
```

this shows the same issue :/ This is purely bad DX on jest's end. If you know of a better runner, lemme know :) thanks again!

**Comment by joshribakoff** [comment]
for anyone else who may have the issues, fyi: https://github.com/facebook/jest/issues/10198 `--detectOpenHandles not working in jest 23`
