### ISSUE TITLE
Can a Subject unsubscribe itself from its source upon completion

### ISSUE THREAD

**Issue by alaboudi** [ReactiveX/rxjs#5534]
### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [x] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue

Consider the example below:
```
const source$: Observable<any>  = //;
const subject$ = new Subject();

const someSubscription = source$.subscribe(subject$); ---> talking about this subscription

subject$.complete();
// is someSubscription unsubscribed?
```
since the subscription is to `source$`, will the `subject$` know that it should unsubscribe itself? should I still call `.unsubscribe` I don't believe the documentation goes into that detail.

**Comment by cartant** [comment]
No. The subject has no relationship with the subscription. Like any other observer, it will be automatically unsubscribed if the source errors or completes, but that's it. An explicit call to the subject's `complete` method will automatically unsubscribe any observers that have subscribed to the subject - not to the source.

**Comment by alaboudi** [comment]
Thank you for the clarification @cartant
