### ISSUE TITLE
Faster unit tests, ability to run a command to compile & watch only changed files

### ISSUE THREAD

**Issue by joshribakoff** [ReactiveX/rxjs#5536]
## Feature Request

The `package.json` has scripts for `compile` & `test`, the latter depends on the former. We re-compile the entire code base on every test run, even if the developer is only working on a single operator.

What I'm more used to is using the test runner's affordances for preprocessing files, I know jest has this ability. This allows you to run the test runner in watch mode, make changes, and get very quick feedback.

This issue is to discuss making overhaul(s) necessary for a faster feedback loop, within whatever constraints this project has (I'm sure there are objections & tradeoffs to be discussed...)

Normally in jest I can do `npm t -- --only-changed --watch` and start developing really quickly. With this project, development is slow & therefore feels clunky & it involves manually running commands between changes and waiting a non trivial amount of time for feedback.

**Describe alternatives you've considered**
A command that runs tsc in watch / incremental mode in a separate process from the test runner.

**Comment by kwonoj** [comment]
Current unit test is intentionally designed to split compile to utilize tsc's incremental compilation, so it is incorrect we do recompile whole everytime per each unit test. Total running time of this test is not huge offender, I do not have plan to revise everything unless there's significant overhead we can improve over. I do use jest in most of places, and jest's warmup time and chaining tsc into jest brings constant overhead for size of this test's speed.

you can already run tsc watch via `npm run compile -- --watch`, we are trying to reduce numbers of script.

**Comment by joshribakoff** [comment]
If by jest's warmup time, you mean the time it takes to preprocess files, we pay that cost now by running tsc.

> you can already run tsc watch via npm run compile -- --watch

How does this solve the problem of not having a working "watch" mode that can isolate a test?

Personally I see this a deterrent to contributing. Having a watch mode that allows isolating tests is pretty standard in today's day & age. I'm not sure how to feel about the knee jerk reaction [closing the issue] to my suggestion, either. I'm not asking you to overhaul anything, I was going to do the work.

**Comment by kwonoj** [comment]
Apologize if it sounded like deterrent. I've been managing build / testing update in this project mostly, and I have a sufficient amount of different suggestion / opinion / PRs to change those in a different way for their best practices. 

We've discussed and changed these flow from time to time, and after giving some consideration we settled down to the current way and make a single recommended way to run tests. At this moment, I believe we hit enough spot between test time and simplicity (that you just remember `npm test`, nothing else) and we won't be going to evaluate other changes anytime soon.

You may say watching test is pretty standard and I do see indeed some project offer it, but it's not mandatory requirement for test script to provide and with few change cycles we took out most of them for some time ago. We may eventually revisit those, but same as above not in a visible timeframe.

**Comment by joshribakoff** [comment]
So what about at least having something in the project setup / contributor guide that explains the choices you've made, why you made them, and the workaround thats being imposed for users who want watch mode (eg. open 2 separate terminals, and run 2 commands).

After you've explained it does use `tsc --incremental` mode, I concede that the slow initial build is not a major issue (although jest would still be nicer)

What still is an issue is that it isn't accessible, I for example have RSI, so manually switching focus & running commands is painful. For people that don't yet have RSI, manually running your tests is a great way to get it :/
