### ISSUE TITLE
observableCompleted operator

### ISSUE THREAD

**Issue by joshribakoff** [ReactiveX/rxjs#5538]
## Feature Request

Adding a observableCompleted operator

**Is your feature request related to a problem? Please describe.**

This is useful for unit testing a stream that ends with `.repeat()`. Eg. in `redux-observable`:

```ts
const epic = (a$, s$) => a$.pipe(
  ofType('foo'),
  switchMap(...),
  doStuff(...),
  takeUntil(...),
  repeat(),
  takeUntil(observableCompleted(a$))
)
```

**Describe the solution you'd like**
I'd like to contribute an operator that takes a notifier observable as an argument, and when that notifier completes, the operator emits.

**Describe alternatives you've considered**

It could go to a third party repo like https://github.com/cartant/rxjs-etc/ but it feels more "core" to me...

**(If this is new operator request) describe reason it should be core operator**

The operator could live anywhere, but it seems pretty core to me to be able to change nexts to completions & vice versa, not sure if there is another way to do this now?

**Comment by cartant** [comment]
The implementation would be trivial: https://github.com/cartant/rxjs-etc/blob/main/source/operators/hasCompleted.ts

IMO, the core would become bloated if easily-derived operators - or observables - like this were to be added.

**Comment by joshribakoff** [comment]
It was not trivial to me, at all. Especially not your elegant solution, I had come up with something far uglier, and only after hours of struggling. Lack of certain affordances in RxJs have made RxJs very difficult to adopt for me, because what were in my eyes key building blocks were missing from the core.

I actually didn't notice that rxjs-etc already has it. I personally do not think the operators being bloated are the issues with RxJs, it's more like lack of "real world" examples, but people just say "there are too many operators". I actually think having more operators (with more real world & visual examples) will make RxJs more approachable.

As it stands today, there are operators that are equally as "easily" derived, which I could go cherry pick...

Maybe this issue could be reframed to give more visibility to the 3rd party offerings?

FWIW, I think converting from "next" to "completed" & vice versa is one of those things that's really important for people to grok, and its not right now. It's like those algorithm challenges where you validate a tree, or check if its symmetrical. It teaches you to think about how to control the computer. Having "easily derived" operators teaches people who may not be as smart, like me, so they can derive them by "borrowing" ideas from smarter people like yourself. It would be great to get more visibility, if not hoisting the operator to the core, perhaps more docs about doing these kinds of operations yourself, or links to 3rd party libs like yours would be great :)

**Comment by cartant** [comment]
> Maybe this issue could be reframed to give more visibility to the 3rd party offerings?

https://ncjamieson.com/rxjs-community-packages/

**Comment by joshribakoff** [comment]
A post on your personal blog does not solve the visibility problem with the main docs glossing over a lot of important concepts / operators, which makes rxjs hard to approach. Most likely people will give up & continue to program imperatively instead of searching for your blog post.
