### ISSUE TITLE
test command is outputting errors on latest master

### ISSUE THREAD

**Issue by joshribakoff** [ReactiveX/rxjs#5542]
## Bug Report

**Current Behavior**
Running `npm t` outputs a bunch of typescript errors about jest.

**Reproduction**
- REPL or Repo link:
Clone, pull latest master, run `npm ci` to use *exact* versions in the lock file (as opposed to whatever you have in your node_modules currently), then run `npm t`

**Expected behavior**
No errors

**Environment**
- Runtime: nodeJS 12.13.1
- RxJS version: master

**Possible Solution**
skipLibCheck: true in tsconfig

**Additional context/Screenshots**
```
 node_modules/@types/mocha/index.d.ts:2752:13
    2752 declare var afterEach: Mocha.HookFunction;
                     ~~~~~~~~~
    'afterEach' was also declared here.

../node_modules/@types/jest/index.d.ts:38:13 - error TS2403: Subsequent variable declarations must have the same type.  Variable 'describe' must be of type 'SuiteFunction', but here has type 'Describe'.

38 declare var describe: jest.Describe;
               ~~~~~~~~

  node_modules/@types/mocha/index.d.ts:2768:13
    2768 declare var describe: Mocha.SuiteFunction;
                     ~~~~~~~~
    'describe' was also declared here.

../node_modules/@types/jest/index.d.ts:40:13 - error TS2403: Subsequent variable declarations must have the same type.  Variable 'xdescribe' must be of type 'PendingSuiteFunction', but here has type 'Describe'.

40 declare var xdescribe: jest.Describe;
               ~~~~~~~~~

  node_modules/@types/mocha/index.d.ts:2789:13
    2789 declare var xdescribe: Mocha.PendingSuiteFunction;
                     ~~~~~~~~~
    'xdescribe' was also declared here.

../node_modules/@types/jest/index.d.ts:41:13 - error TS2403: Subsequent variable declarations must have the same type.  Variable 'it' must be of type 'TestFunction', but here has type 'It'.

41 declare var it: jest.It;
               ~~
```

**Comment by kwonoj** [comment]
our actions does same thing https://github.com/ReactiveX/rxjs/blob/master/.github/workflows/ci_main.yml#L25 

and we don't have `@types/jest` in our pkg lock: 

![image](https://user-images.githubusercontent.com/1210596/85955782-fd29c600-b935-11ea-8abc-13e0535ea559.png)

Now sure how did those types got in in your case.

**Comment by joshribakoff** [comment]
`../node_modules/@types`

Sorry, I should have noticed it was coming from `../`.
