### ISSUE TITLE
Japanese Translation

### ISSUE THREAD

**Issue by xyzpda** [ReactiveX/rxjs#5546]
Hi, I'm Hiroshi from Japan.

Would you mind if I translate this repo into Japanese?

**Comment by kwonoj** [comment]
we have long hanging discussion about translation https://github.com/ReactiveX/rxjs/issues/4388 and honestly, I don't think we made a concrete decision on this. /cc @niklas-wortmann for visibility.

**Comment by jaeleeps** [comment]
Is there anyone still willing to dig into this issue?

**Comment by niklas-wortmann** [comment]
Right now there is no-one working towards this. Mainly for the reason that this requires a lot of initial effort but it basically increase also ever other doc change later on as we have to ensure that all translations stay in sync. If anyone has any good idea on how to tackle this problem in general, I am very happy to discuss approaches

**Comment by niklas-wortmann** [comment]
there are more and more community translations popping up these days, maybe we want to consider linking those maybe with some kind of disclaimer or whatever
