### ISSUE TITLE
Deprecate `shareReplay` in favor of `shareLatest` and `replayLatest`

### ISSUE THREAD

**Issue by josepot** [ReactiveX/rxjs#5556]
## Feature Request

**Is your feature request related to a problem? Please describe.**

I think that the operator `shareReplay` is too confusing:

- Its default behavior doesn't resemble the behavior of `share`, in the sense that by default it doesn't have a `refCount`, which is a key piece of `share`.

- I think that it conflates 2 different behaviors.

- I think that its overloads can be confusing, and [some "share-replay" behaviors](https://github.com/ReactiveX/rxjs/issues/5455) can't be accomplished using this operator, which [can make it look like some behaviors are "arbitrary"](https://github.com/ReactiveX/rxjs/issues/5455).

- I think that because of these reasons its implementation is a bit convoluted and prone to errors.

- And last but not least, I think these are the reasons why I've seen so many developers (myself included) inadvertently shooting themselves in the foot with this operator.

**Describe the solution you'd like**

I would like to suggest that (in a future major release) it gets deprecated in favor of the following 2 operators:

- `shareLatest` that it would behave like this:

```ts
const shareLatest = <T>(bufferSize = 1) => (
  source$: Observable<T>
): Observable<T> =>
  source$.pipe(
    multicast(() => new ReplaySubject<T>(bufferSize)),
    refCount()
  );
```

- `replayLatest` that it would behave like this:

```ts
const replayLatest = <T>(bufferSize = 1) => (
  source$: Observable<T>
): Observable<T> =>
  source$.pipe(
    publishReplay(bufferSize),
    refCount()
  );
```

**Describe alternatives you've considered**

I no longer use `shareReplay` myself and I use custom versions of those 2 operators instead. Personally, I think that they are better primitives to work with because they are less ambiguous.

For instance in react-rxjs -generally speaking- the behavior that we want for the observables that are being consumed from react components is the following:

```ts
const sharedForReact$ = concat(source$, NEVER).pipe(shareLatest());
```

I'm currently working on some docs that explain why that should be the default way of sharing observable that are meant to be consumed within react components in order to avoid memory-leaks and unexpected behaviors... Notice how what that does could be seen as one way of sharing and replaying? However, AFAIK there is no way to accomplish that behavior with the `shareReplay` operator.

If on the other hand, we had 2 different operators that did "less", then it would be easier to understand what's the best way to leverage them.

**Comment by benlesh** [comment]
Sadly, both of the operators you're showing there are not retry-able or repeat-able.

`shareReplay` as it stands is a tricky thing because it's all about the intent with how it is used. `ReplaySubject` by design, is meant to cache values if it completes, and be kept around and reused. However, in most cases, if there's an error, you probably don't want to replay that. The original goal of `shareReplay` was to be used on calls that were expensive, and you wanted to complete. Which is why the default behavior is the way it is.

The `refCount` behavior was added later, because the community was split 50/50 on what they wanted. With that behavior, the developer is saying that the call isn't expensive, and they don't care to let it complete.

**Comment by josepot** [comment]
Thanks @benlesh for your reply.

> Sadly, both of the operators you're showing there are not retry-able or repeat-able.

:thinking: Why are they not repeat-able? Also, the `shareLatest` operator that I suggested it is retry-able, right?

Although, I can see why the `replayLatest` should also be retry-able, for sure... and you are right: the one that I suggested in my initial comment it's not retry-able, my bad! So, taking that into account, the implementation that I would like to suggest for the `replayLatest` operator would be:

```ts
const retryablePublishReplay = <T>(bufferSize: number) => (source$: Observable<T>) => {
  let subject = new ReplaySubject<T>(bufferSize);
  return multicast(() => {
    if (subject.hasError) {
      return (subject = new ReplaySubject<T>(bufferSize));
    }
    return subject;
  })(source$);
};

const replayLatest = <T>(bufferSize = 1) => (
  source$: Observable<T>
): Observable<T> =>
  source$.pipe(
    retryablePublishReplay(bufferSize),
    refCount()
  );
```

Please have a look at [this stackblitz](https://stackblitz.com/edit/rxjs-6azpbd?devtoolsheight=60). That would make it retry-able and repeat-able, right?

**Comment by josepot** [comment]
I've been thinking a bit more about this and I've come to realize that the behaviour that `shareReplay` provides for the `refCount` overload makes more sense than the behaviour that I originally suggested in my first comment for the `shareLatest` operator. Therefore, I think that `shareLatest` operator should return an observable that once the source has completed, if there is a new subscriber, then it replays the latest emitted values (and then completes). 

However, I still think that it could be a good idea to separate the 2 different behaviours of `shareReplay` in 2 different operators like `replayLatest` and `shareLatest`. The potential benefits of this change would be:

- Having a default `bufferSize` of `1` would make it more obvious to the user the potential issues of an infinite buffer size. Meaning that IMO more often than not an infinite buffer can (and probably should) be avoided. In other words, I think that having an operator that has a default buffer-size of one would make the usage of an infinite buffer-size less appealing. 

- The second benefit has to do with having operators that better express their behaviour. I guess that this is quite subjective, but I do think that the name `shareReplay` is a bit misleading and that the names that I'm suggesting are better at expressing those behaviours.

I want to say that I understand that this is a bold request because while it's unclear whether these changes would make things easier for RxJS newbies, what's for sure is that it would make the migration to that major version more complicated for the current users of RxJS. So, if this proposal succeeded, then I wouldn't mind to work on a codemod that would make the transition easier.

**Comment by josepot** [comment]
I'm closing this because I just wanted to share this idea and I have nothing else to add. Also, I understand that it's probably not worth it to deprecate an operator just for the sake of splitting its functionality in two different ones.
