### ISSUE TITLE
Constant for Observable<void>

### ISSUE THREAD

**Issue by hoi4** [ReactiveX/rxjs#5569]
## Feature Request

Thank you for your great work!
I have a frequent usecase where I need to return an Observable of type void.

With promises, you can do the following:
```typescript
const conditionalAsyncOp = () = {
  if (someCondition) {
    return asyncOp()
  } else {
    return Promise.resolve();
  }
}

function asyncOp(): Promise<void> {
  return new Promise(resolve => {
    // do some asynchronous work
    setTimeout(resolve, 1000)
  })
}
```

Using `EMPTY` or `of()` are breaking the chain because they complete which is not desired here.

The equivalent of `Promise.resolve()` for observables would be:
```typescript
new Observable<void>(observer => observer.next())
```

I would love to have a constant similar to [EMPTY](https://github.com/ReactiveX/rxjs/blob/f1d59727af1bafff950c9b4f6edb52be85cb4b8d/src/internal/observable/empty.ts#L28) which is a shortcut of the above code.

**Comment by josepot** [comment]
@hoi4 if I understood you correctly: you are looking for a constant that behave like `EMPTY` but that never completes, correct? If that's the case, then I think that what you are looking for is the [constant `NEVER`](https://rxjs-dev.firebaseapp.com/api/index/const/NEVER) :slightly_smiling_face:

**Comment by hoi4** [comment]
@josepot Thank you for your answer.

I cannot use `NEVER` because like `EMPTY` it also breaks the observable chain (as it is not emitting anything). I need the observable to emit `void` (by calling `next` without any parameters) and to not complete.

What I would like to have is the following:
```typescript
export const VOID = new Observable<void>(observer => observer.next());
```

Of course, I could just define this constant for myself, but I thought that maybe others have the same usecase. 🤔

**Comment by kwonoj** [comment]
I do not think core will include those - `empty`, `never` are specific edge-case observable previously backed by operator. What you're mentioning in here is a plain observable emits value which is `undefined`, I recommend to create user land values instead.

Few things meanwhile: first, not sure what `breaks the observable chain` means: all observables properly run to completion. secondly, `The equivalent of Promise.resolve()` cannot be what you mentioned - promise runs to completion, so if you want to create equivalent it should complete too.

**Comment by hoi4** [comment]
@kwonoj Thank you for your answer.

Just to clearify what I mean:

I created a very small [stackblitz](https://stackblitz.com/edit/typescript-rx-playground-observable-void) to illustrate the use case:
```typescript
const VOID = new Observable<void>(observer => observer.next());

function asyncOp(value: number): Promise<void> {
  return new Promise(resolve => {
    setTimeout(() => {
      console.log(`resolving for value`, value);
      resolve();
    }, 2000);
  });
}

function conditionalAsyncOp(value: number): Observable<void> {
  if (value % 2 === 0) {
    return defer(() => asyncOp(value))
  } else {
    // When replacing VOID with EMPTY or NEVER, the second tap below is not executed
    return VOID; 
  }
}

of(1).pipe(
  tap(value => console.log(`VALUE`, value)),
  switchMap((value) => conditionalAsyncOp(value)),
  tap(() => console.log(`Observable pipe still running`))
).subscribe()
```
The `tap` operator following the `switchMap` is not executed if `conditionalAsyncOp` does not emit any value (`NEVER`) or completes (`EMPTY`).

Maybe there is a better way of implementing such a behaviour in which case I would be very glad about some guidance. Thank you!
