### ISSUE TITLE
Is there a similiar "if" and "else" syntax statement for Rxjs for angular?

### ISSUE THREAD

**Issue by jt4000** [ReactiveX/rxjs#5577]
Hello,

Is there a similiar "if" and "else" syntax statement for Rxjs for angular?

If possible, can you provide a sample?

Thank you!

**Comment by kwonoj** [comment]
It is bit unclear what you're looking for - if you would like to check available operators please check out our docs page https://rxjs-dev.firebaseapp.com/ .

**Comment by benlesh** [comment]
There is the `iif` creation operator.

Given an `Observable<boolean>` you can switch between to possible observables.

```ts
import { iif, of } from 'rxjs';

const maybe$ = of(Math.random() > 0.5);

iif(maybe$, of('it was true'), of('it was false')).subscribe(console.log)
```

I'm guessing that's what you mean? Either way, this is a question that is better for stackoverflow.com with an example.
