### ISSUE TITLE
distinctUntilChanged not working with array

### ISSUE THREAD

**Issue by RiZerMan** [ReactiveX/rxjs#5578]
## Bug Report

**Current Behavior**
I'm currently building with Angular a advanced multistep form where a root component checks the validity on a change in the form to disable and activate the next button, to prevent a infinite loop i use a distinctUntilChanged() on the valuechanges of the form.

But when trying to update a array in the form the distinctUntilChanged wil say that there is no change.

```js
this.registerService.form.valueChanges.pipe(distinctUntilChanged((a, b) => JSON.stringify(a) === JSON.stringify(b)))
    .subscribe(() => {
        this.currentStepValid = this.registerService.checkValid(this.activeStep);
});
```

**Expected behavior**
I would expect the distinctUntilChanged to fire when an array has been updated

**Environment**
- Runtime: [e.g. Node v${x}, Chrome v${x}]
- RxJS version: 6.6.0
- Angular: 8.1.2

**Additional context/Screenshots**
When logging a and b from the distinctUntilChanged it seems that adding a value will not see a change but removing will:

Output when adding:
a: '{"exampleArray": [3, 4]}'
a: '{"exampleArray": [3, 4]}'

Output when removing:
a: '{"exampleArray": [3, 4]}'
a: '{"exampleArray": [4]}'

**Comment by kwonoj** [comment]
Please provide reproducible code without involving app code to clarify if this is rx core issue.
