### ISSUE TITLE
Strategies for more accurate code coverage report

### ISSUE THREAD

**Issue by kwonoj** [ReactiveX/RxJS#558]
Related with PR https://github.com/ReactiveX/RxJS/pull/557

Current code coverage report (i.e, [build 823] (https://coveralls.io/builds/3868169)) is indicating coverage of source points to transpiled results from original typescript based sources. Due to this reason it does not reports accurate coverage percentage also does not allows navigation to coverage detail, makes bit hassle to triage when coverage number goes down.

##### Coverage report shows coverage against transpiled
![image](https://cloud.githubusercontent.com/assets/1210596/10557176/298d7f54-7456-11e5-9006-70d1bc73e2af.png)

##### Not able to navigate actual source detail
![image](https://cloud.githubusercontent.com/assets/1210596/10557180/449bfeb0-7456-11e5-8309-f72b2acc20f2.png)

PR https://github.com/ReactiveX/RxJS/pull/557 partially resolves this issue by enabling coverage remapping via sourcemaps. Still it doesn't give right coverage to original source but es6 transpiled source because of current build mechanism,

1. tsc compiles into ES6
2. babel uses compiled ES6 and compiles into commonjs

since test cases are using commonjs output from 2, even after enabling sourcemap remapping coverage report shows result against ES6 output from 1 instead of original source doesn't give right accuracy of test coverage along with lacks of navigation. (example report can be found at [here](https://coveralls.io/builds/3868743))

##### source map enabled
![image](https://cloud.githubusercontent.com/assets/1210596/10557235/79b2e27e-7458-11e5-92b7-251ae467deb6.png)

##### detail's still not available
![image](https://cloud.githubusercontent.com/assets/1210596/10557197/1e83fbb4-7457-11e5-83a0-14e5616601d8.png)

Could think of few options to resolve this issues,

~~1. build commonjs module via typescript compiler~~
: Not considerable due to https://github.com/ReactiveX/RxJS/issues/248
~~2. leave current build mechanism as-is, build commonjs module once again via typescript compiler only for test coverage~~
: Though this can work, still bit hacky since it requires build couple, or triple for same build.
~~3. it's ok to live with current coverage status, let's leave as-is.~~
4. Maybe some other way I couldn't think of

I have tried option 2, could create test coverage shows quite different number than what we're currently having against transpiled results. (example report can be found at [here](https://coveralls.io/builds/3869129))

##### Ideal coverage report, shows accurate coverage to source
![image](https://cloud.githubusercontent.com/assets/1210596/10557219/d871dfa0-7457-11e5-9d0b-920ad4198173.png)

##### detailed navigation is available
![image](https://cloud.githubusercontent.com/assets/1210596/10557224/06ea48a4-7458-11e5-9364-ebd6ab2cacb6.png)

Personally though it's bit hacky way, would like to suggest 2. (rebuild cjs via tsc only for coverage), does not hurt actual output also get detailed coverage to actual code.

Update: disposed above options by looking composing sourcemap as hinted.

**Comment by blesh** [comment]
It seems like there are ways to compose the sourcemaps. LIke sourcemap to ES6 source map again to Babel.

**Comment by kwonoj** [comment]
That seems quite feasible solution. I'll try to look for some references.

**Comment by kwonoj** [comment]
Spend some time and could able to list up some options.

##### using `babel --inputSourceMap`
: babel supports to have 'base' sourcemap to generate sourcemap of transpiled results to corresponds original source. This works, but . 

- Cons : only supported for **inline source map**, inline source map is probably not acceptable. also options itself is sort of [**undocumented option**] (https://github.com/babel/babel/blob/369b9fdc4bf541933f24184a7e8ad7ec0776d600/packages/babel/src/transformation/file/options/config.json#L15)

##### using `gulp-sourcemaps`
: gulp has [plugin](https://www.npmjs.com/package/gulp-sourcemaps) to stream staged transpilation and generate source maps from those. Most simple, straightforward way. 

- Cons : need to introduce new build system other than npm script.

##### using `multi-stage-sourcemap` module
: [multi-stage-sourcemap module] (https://www.npmjs.com/package/multi-stage-sourcemap) supports staged conversion of sourcemap.

- Cons : module has known issue (https://github.com/azu/multi-stage-sourcemap/issues/3), but code is not updated quite while. + requires to create separate script to handle source map conversion.

**Comment by kwonoj** [comment]
Order of personal preference is 1.gulp 2.multi-stage-sourcemap (inline source map with babel is out of option for me). 

Of course using gulp will require additional effort to replace existing npm based build scripts, but it'll bring some additional side effect of better windows support (specifically dealing with cross-platform environment variable, file glob) along with streamlined source map support using ready made plugin. Build script for current repo is not yet very complex, so it won't require huge effort to create new scripts for build (and I'm willing to take this effort if it's going to happen).

Thoughts? or any other suggestions for tooling support would be appreciated.

**Comment by kwonoj** [comment]
After give few more try, seems `gulp-sourcemap` also has some issues. Given aspect of coverage check failure affects PR, I'll add changes based on current build script with multi stage sourcemap first.
