### ISSUE TITLE
partition duplicates source observable

### ISSUE THREAD

**Issue by jesperp** [ReactiveX/rxjs#5581]
https://github.com/ReactiveX/rxjs/blob/886b4fc8216ec002a8ddaa024996ede8dc4a7d7e/src/internal/observable/partition.ts#L64-L65

Is this the intentional behaviour for `partition`? 
As a user I expected the source not to be duplicated like this. I was doing a simple web request pipeline and using partition now duplicates my requests.

Simplified code that I am working on now, expecting the responses to be split into two new observables, which does happen, but the request for each url is sent twice.
```
const responses = from(urls).pipe(
   map( str => new URL(str) ),
   mergeMap( url => from(axios.get(url)) ),
)
const [html, other] = partition(responses, resp => resp.header['content-type'] == 'text/html')
```

**Comment by benlesh** [comment]
Yes. This behavior is intentional. You can always compose in a multicast behavior with `share()`.

```ts
const [html, other] = partition(responses.pipe(share()), resp => resp.header['content-type'] == 'text/html')
```
