### ISSUE TITLE
feat: from ReadableStream

### ISSUE THREAD

**Issue by william-lohan** [ReactiveX/rxjs#5583]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Getting an Observable from a ReadableStream

**Describe the solution you'd like**
You could add: `src/internal/util/subscribeToStream.ts`

```ts
export const subscribeToStream = <T>(stream: ReadableStream<T>) => (subscriber: Subscriber<T>) => {
  stream.pipeTo(new WritableStream({
      write: chunk => {
        subscriber.next(chunk);
      },
      abort: error => {
        subscriber.error(error);
      },
      close: () => {
        subscriber.complete(); 
      }
    }));
};
```

then consume that in `src/internal/util/subscribeTo.ts` giving `from()` the ability to handle Web Streams API

**Describe alternatives you've considered**
Using this factory

```ts
function observableFromStream<T>(stream: ReadableStream<T>): Observable<T> {
  return new Observable(subscriber => {
    stream.pipeTo(new WritableStream({
      write: chunk => {
        subscriber.next(chunk);
      },
      abort: error => {
        subscriber.error(error);
      },
      close: () => {
        subscriber.complete(); 
      }
    }));
    return () => {
      if (!stream.locked) {
        stream.cancel();
      }
    }
  });
}
```

**(If this is new operator request) describe reason it should be core operator**
A clear and concise description of reason it can't be achieved via user-land module.

**Additional context**

**Comment by tanepiper** [comment]
@william-lohan I know it's not core, but I've created two new operators in my own library (`fromReadableStream` and `toWritableStream`) to provide some interop between them and RxJS - https://rxjs.ninja/modules/utility.html#fromreadablestream https://rxjs.ninja/modules/utility.html#towritablestream

**Comment by kwonoj** [comment]
Closing as userland implementation suggested. RxJS core trying to reduce core api surface. If there's need to discuss further around core api surface, please use https://github.com/ReactiveX/rxjs/discussions/categories/ideas-feature-request .
