### ISSUE TITLE
Use variadic tuple types from TS v4

### ISSUE THREAD

**Issue by Akxe** [ReactiveX/rxjs#5586]
## Feature Request

Use [variadic tuple types](https://devblogs.microsoft.com/typescript/announcing-typescript-4-0-beta/#variadic-tuple-types) to simplify function types.

**Is your feature request related to a problem? Please describe.**
It is related to a lot of operators since they only process the first 10 or so arguments.

**Describe the solution you'd like**
When variadic tuple types would be used, this problem might be eliminated for most use cases.

**Describe alternatives you've considered**
The current solution as it was standard even in TS core libs.

**Comment by kwonoj** [comment]
https://github.com/ReactiveX/rxjs/issues/5541

Core team internally tracking it but to maintain compatibility trying to find right time to release.
