### ISSUE TITLE
Typo in timeoutWith operator

### ISSUE THREAD

**Issue by bojjakaseenadhreddy** [ReactiveX/rxjs#5588]
### Documentation Related To Component:

timeoutWith operator in https://rxjs-dev.firebaseapp.com/api/operators/timeoutWith
### Please check those that apply

- [1] typo
- [2] error(s) in example

### Description Of The Issue
There is typo in example which is embedded from stackBiltz. 
###Accidentally imported intrerval insted of interval.

**Comment by jakovljevic-mladen** [comment]
This is fixed with #4884. I think the fix will land with v7.
