### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by resynth1943** [ReactiveX/rxjs#5590]
## Remove Google Analytics

If you must have an analytics system, might I suggest either:
- Plausible: https://plausible.io (offers a 50% discount for FOSS projects)
- Goatcounter: https://goatcounter.com
- Matomo: https://matomo.org
- Fathom: https://usefathom.org

These solutions are all well-tested and open-source. This, of course, means they
can be independently audited for privacy and security. Instead of using a proprietary
nonfree system such as Google Analytics, perhaps we could work together to replace
it with something slightly more ethical?

Furthermore, the majority of privacy features in evergreen browsers *block* Google
Analytics from being run. I can not say the same for solutions such as Plausible,
which suggests they are trusted for their privacy by independent persons.

If you need any more information, please contact me!

**Comment by benlesh** [comment]
This is a good suggestion, and I appreciate it. However, Google (and Firebase) have donated the hosting and analytics to this project, so we don't have to pay. (Which I'm very grateful for).

Thank you so much for taking the time to make this suggestion, I appreciate it!

**Comment by resynth1943** [comment]
At what price? That's a shame. 

Anyway, best of luck!
