### ISSUE TITLE
Check API guardian in against a single version of TS

### ISSUE THREAD

**Issue by cartant** [ReactiveX/rxjs#5608]
## Bug Report

It seems that API guardian cannot be made to work with all version combinations. We should pick a single version and perform the API guardian checks with that version only. IMO, it the checks should be run against whatever the version in master are using.

The problem is highlighted here:

<img width="540" alt="api-guardian" src="https://user-images.githubusercontent.com/3878593/88618450-86bae800-d0dc-11ea-886d-85284ef7a530.PNG">

Note that between versions, the union in the return type is either `0 | 1 | -1` or `1 | 0 | -1`.

<img width="639" alt="failures" src="https://user-images.githubusercontent.com/3878593/88618583-d4cfeb80-d0dc-11ea-8d71-27c58524270c.PNG">

**Comment by cartant** [comment]
FWIW, I've not looked into this, so whether or not it's the TS version or the version of the Node types, IDK.

**Comment by kwonoj** [comment]
fyi, our gh action have pinned ts version and ts@latest action doesn't run api_guardian, so there's no combination for ts version across CI. (plus we don't have different @types/node across CI even? https://github.com/ReactiveX/rxjs/blob/master/package.json#L105)

**Comment by cartant** [comment]
It seems the problem was that I needed to recompile. Regarding what it was between compiles that effected the different output ... 🤷‍♂️
