### ISSUE TITLE
Wrong typings with `tap` operator (for the observer overload)

### ISSUE THREAD

**Issue by josepot** [ReactiveX/rxjs#5614]
## Bug Report

**Current Behavior**
The typings of the observer overload of the `tap` operator can incorrectly return partial observable

**Reproduction**
- REPL or Repo link:
https://codesandbox.io/s/nice-varahamihira-vuf19?file=/src/index.ts

```ts
const test$ = new Subject<number>();                             
const one$: Observable<number> = of(1);                          
const somethingIsWrong$ = one$.pipe(tap(test$));
```
the inferred type of `somethingIsWrong$` is `Observable<number | undefined>`

**Expected behavior**
~If the observer is not a "PartialObserver", then the returned Observable shouldn't be partial.~
`tap` should always return the same type as its source.

**Environment**
- Runtime: All
- RxJS version: 6.6.0

**Comment by josepot** [comment]
As @cartant pointed out in [this comment](https://github.com/ReactiveX/rxjs/pull/5615#issuecomment-666817460) this issue happens because of an issue with the types of `Subject`.

For instance, in v6 when defining a `new Subject<number>()` the types of `next` look like this `Subject<number>.next(value?: number | undefined): void`, which it's something that has been addressed on v7.

However, the `tap` operator should always return the same type as its source and that's an issue that also affects v7. For instance consider [the following code](https://codesandbox.io/s/busy-hawking-r27c5?file=/src/index.ts:0-268):

```ts
import { Observable, of } from "rxjs";
import { tap } from "rxjs/operators";

const one$: Observable<number> = of(1);

const result$: Observable<number> = one$.pipe(
  tap({
    next(value: string | number) {
      console.log(value);
    }
  })
);
result$.subscribe()
```

`result$`'s type should be `Observable<number>` rather than `Observable<string | number>`.

Therefore, we have 2 different issues:
- the types of `tap` which affects v6 and v7
- the types of `Subject`.

After thinking a bit more about it, I think that the actual fix for solving the issue with the types of the `tap` operator should be to change [this line](https://github.com/ReactiveX/rxjs/blob/3db2eaa5d6bfe0188b0c4da3626123c8eefedf98/src/internal/operators/tap.ts#L17) like this:

```ts
export function tap<T, P extends T>(observer: PartialObserver<P>): MonoTypeOperatorFunction<T>;
```

I will try to send a PR with that change before the end of the weekend.

**Comment by cartant** [comment]
IMO, this is a TS inference quirk and I would expect this to affect numerous other operators. FWIW, I'm not at all convinced this is something that needs to be fixed.

**Comment by josepot** [comment]
> IMO, this is a TS inference quirk and I would expect this to affect numerous other operators. FWIW, I'm not at all convinced this is something that needs to be fixed.

I don't know, maybe it doesn't _need_ to be fixed, but wouldn't it be better if we could make the following dtslint tests pass?

```ts
it("should not alter the type of the source", () => {
  const a = of(1).pipe(tap({ next: (x: number | string) => {} })); // $ExpectType Observable<number>
  const b = of(1).pipe(tap((x: number | string) => {})); // $ExpectType Observable<number>
  const c = of(1).pipe(
    tap((x: number | string) => {}, (e: any) => {}, () => {})
  ); // $ExpectType Observable<number>
});
```

#5616 accomplishes that while not breaking any of the previous tests. So, IMO it's an improvement. Is there a dtslint test that wouldn't pass because of those changes?

**Comment by josepot** [comment]
Ok, I'm closing this issue, let's finish this discussion on #5616, sorry about that :grimacing:

**Comment by josepot** [comment]
T u 5 yc to x5
