### ISSUE TITLE
Front page does not represent the tool

### ISSUE THREAD

**Issue by Dragas** [ReactiveX/rxjs#5629]
Seems the current page of https://rxjs.dev does not represent the tool, but instead some unrelated articles. Do you mind removing them in favor of showing what is rxjs and why would someone stumbling upon it want to use it?

**Comment by kwonoj** [comment]
it is intended representation and we'll evaluate those over time.

**Comment by Dragas** [comment]
Intended representation of unrelated topic? I am not sure how does that help rxjs.
