### ISSUE TITLE
Why exhaustMap completes Observable?

### ISSUE THREAD

**Issue by alvipeo** [ReactiveX/rxjs#5630]
I have this observable:
```
    const latestStatus$ = interval(5000).pipe(
      tap(() => this._workInProgress$.next(true)),
      exhaustMap(() => of(true).pipe(delay(50))),
      tap(status => {
        this._status$.next(status);
        this._workInProgress$.next(false);
        this.addToLog(`latestStatus: ${status}`);
      }),
      finalize(() => this.addToLog("the end."))
    );
```
and when I subscribe I only get `the end.`. Now, if I remove `delay(50)` everything works as expected. Is this a bug or what am I missing here?

RxJS 6.6.2

**Comment by benlesh** [comment]
It's more appropriate to put these questions on [stackoverflow](https://stackoverflow.com).

However, looking at it, I would suspect there's an error thrown in one of those `tap` calls, and it has nothing to do with the `exhaustMap`.

**Comment by cartant** [comment]
Further to what Ben had said, this isn't an actionable bug report, as it does not include a minimal reproduction of the problem - snippets that include references to application code are not reproductions.

FWIW, this behaves as expected:

```ts
const source = interval(500).pipe(
  exhaustMap(() => of(true).pipe(delay(50))),
  finalize(() => console.log("done")),
  take(3)
);
source.subscribe((value) => console.log(value));
```

**Comment by alvipeo** [comment]
I was actually trying to simulate angular app working with back-end here - https://stackblitz.com/edit/exhaustmap-problem. If you run it you will see I get `the end.` in the log.

I made it work in another stackblitz though - https://stackblitz.com/edit/manage-device, which is different.

But anyway, I'd like to know why it completes so soon in my 1st example.
Thank you!
