### ISSUE TITLE
Closable or less loud BLM banner

### ISSUE THREAD

**Issue by shelacek** [ReactiveX/rxjs#5632]
Hello,
Is it really necessary to have a big BLM banner on the rxjs.dev home page? Leaving aside the obviously racist tone of the message (what about other lives?), it's quite annoying. Many of the more sane websites have only a narrow bar at the top.

Disclaimer: I'm not American, and we've never had a problem with slavery in my country, so maybe I don't understand the fuss about BLM. However, I do not understand why it annoys even people who are not interested.

**Comment by niklas-wortmann** [comment]
Thanks for your opinion, but it is placed the way it is very intentional. Everyone can still use the docs without any restrictions and for now there is no plan to revert the homepage. 

Sidenote: If you consider this message racist, you might consider educating yourself on this matter.
