### ISSUE TITLE
Unsubscribe is slow when observers number > 10000

### ISSUE THREAD

**Issue by zxch3n** [ReactiveX/rxjs#5638]
Both of `indexOf` and `splice` are slow. Why not use a Set to store `observers`? 

https://github.com/ReactiveX/rxjs/blob/40b32d8fadeb1c0ef752fa4281aff20fa3a2c18b/src/internal/SubjectSubscription.ts#L17-L39

**Comment by benlesh** [comment]
Makes sense. I have other, related thoughts to this, so I've started a new issue and I'm closing this one in favor of that. Thanks, @zxch3n 

https://github.com/ReactiveX/rxjs/issues/6400
