### ISSUE TITLE
Websocket syntax error in IE11

### ISSUE THREAD

**Issue by Tinnitus95** [ReactiveX/rxjs#5640]
When trying to open a websocket I get a Syntax error in IE 11.
The code works perfectly in Chrome.

I have been able to find the code that is throwing the error using the debugger in IE.

```
try {
o=t?new l(i,t):new l(i),this._socket=o,r&&(this._socket.binaryType=r)
} catch(s){
return void u.error(s)
}
```
**o=t?new l(i,t):new l(i)** is marked by the debugger as the issue

**RxJS version:**
6.5.3

**Code to reproduce:**
Just trying to open the socket causes the problem. 
`this.signingSocket$ = webSocket(socketUrl);`
I return this observable and subscribe to it later.
 
**Expected behavior:**
Open the socket

**Actual behavior:**
Errors out

**Additional information:**
I tried to add the entire core-js to see if it was a polyfill issue to no awail.

**Comment by cartant** [comment]
You've not indicated how you are building the code you are running in IE11. However, I can see that the only minified code that we distribute in 6.5.3 looks like this, from `rxjs.umd.min.js`:

```js
try{this._socket=k=f?new e(g,f):new e(g),c&&(this._socket.binaryType=c)}catch(r){h.error(r);return}
```

That leads me to believe that you are bundling and minifying your application yourself. So the fact that the result of said bundling and minification effect problems in IE11 is outside of out control. So I'm closing this.
