### ISSUE TITLE
Incompatible typings when multiple versions of RxJS are in use

### ISSUE THREAD

**Issue by joshribakoff** [ReactiveX/rxjs#5648]
![Screen Shot 2020-08-16 at 11 07 25 AM](https://user-images.githubusercontent.com/4021306/90341243-d6415500-dfb2-11ea-8178-fe4752eefb74.png)

I have an app w/ `rxjs@6.6.2`, consuming a lib that has `dependency` of `"rxjs": "^6.5.5"`. The typings do no inter-operate, because the internals appear to be part of the resolved types. Neither the lib or the app are importing Rx internals. I did fix my lib to use a peer dependency, fixing the original issue of having multiple versions of Rx, but it seems like ideally if you had multiple versions the typings would inter-operate, or if they don't then it would actually be a breaking change?

**Comment by cartant** [comment]
Closed by #6215. Internals are now stripped from the public API  in v7.
