### ISSUE TITLE
using two animationFrameSchedulers in a row

### ISSUE THREAD

**Issue by chrisguttandin** [ReactiveX/rxjs#5664]
## Bug Report

**Current Behavior**

I'm using `audit()` in combination with the `animationFrameScheduler` in order to make sure a particular observable only emits once per animation frame. If I'm not mistaken that implicitly means that any emission of the source observable will be delayed by one animation frame since the scheduler uses requestAnimationFrame internally.

The code looks like this:

```js
source
    .pipe(
        audit(() => scheduled([0], animationFrameScheduler))
    );
```

However I noticed that when I have two of these operators in a row the second one will actually emit the value within the same animation frame. 
```js
source
    .pipe(
        audit(() => scheduled([0], animationFrameScheduler)),
        someOtherOperators(),
        audit(() => scheduled([0], animationFrameScheduler)),
        someMoreOperators()
    );
```

I would expect `someOtherOperators()` and `someMoreOperators()` to be called in consecutive animation frames. But they are called in the same animation frame. 

**Reproduction**

This example uses scroll events and maps them to numbers. It logs them together with the number of the current animation frame.

https://stackblitz.com/edit/rxjs-yea628?file=index.ts

**Expected behavior**

I created the same example with `animationFrame()` from `subscribable-things` and the new `animationFrames()` function from RxJS. They both work as expected.

https://stackblitz.com/edit/rxjs-bfx168?file=index.ts
https://stackblitz.com/edit/rxjs-t25bhv?file=index.ts

**Environment**
- RxJS version: 7.0.0-beta.4

**Possible Solution**

Maybe this isn't a bug and just me misunderstanding the scheduler. It could be related to #4972 and #5397.

**Comment by elpddev** [comment]
Saw this and it was interesting to explore. I'm not familiar with rxjs code and not a maintainer. 

1. looking at the [AnimationFrameScheduler](https://github.com/ReactiveX/rxjs/blob/78032157f5c1655436829017bbda787565b48c30/src/internal/scheduler/AnimationFrameScheduler.ts#L5), it seems its based on `AsyncScheduler` with overriding only the `flush` method. The difference is that is does not ask if its active or not, but try to do all actions in one burst. 
2. At [AnimationFrameAction](https://github.com/ReactiveX/rxjs/blob/78032157f5c1655436829017bbda787565b48c30/src/internal/scheduler/AnimationFrameAction.ts#L27) is seems the `flush` is done in an animation frame request. 

I dont think using [requestAnimationFrame](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame) ensure that each callback will be called next frame. If I understand correctly, it is possible that requesting animation frame will give the same next animation frame if it has not happened yet.

**Comment by elpddev** [comment]
I don't have much experience in rxjs and am not a maintainer. It seems the issues you have mentioned have fixes for them in the latest master of 7 beta. The branch 6.6.2 that the stackblitz examples uses does not have this fix.

Maybe the fix to the  counter calculation in the AnimationFrameScheduler `flush` method is related.
If I change the version to 7.0.0-beta.8 it seems to work.

```
0 tap 86
0 subscribe 87
```

https://github.com/ReactiveX/rxjs/commit/33c9c8cf7e247d4ad4d7318bfd02e8e5bedb0f40#

https://github.com/ReactiveX/rxjs/blame/master/src/internal/scheduler/AnimationFrameScheduler.ts

https://github.com/ReactiveX/rxjs/blame/6.6.2/src/internal/scheduler/AnimationFrameScheduler.ts

**Comment by chrisguttandin** [comment]
Hi @elpddev, thanks a lot for checking this with the v7 release. I can confirm that it works as expected now. I'll go ahead and close the issue then.
