### ISSUE TITLE
Change homepage setting in package.json to the official docs site

### ISSUE THREAD

**Issue by BioPhoton** [ReactiveX/rxjs#5668]
### Documentation Related To Component:

The `package.json` file.

### Please check those that apply

- [x] typo
- [ ] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue

The `package.json` file contains a `homepage` property that points to the github docs. IMO this should point to `https://rxjs.dev`

**Comment by cartant** [comment]
Closed by https://github.com/ReactiveX/rxjs/pull/5669
