### ISSUE TITLE
buffer with reduce-like operator

### ISSUE THREAD

**Issue by Thaina** [ReactiveX/rxjs#5672]
## Feature Request

Currently now `buffer` can only batch a bunch of object as an array to pass to next operator. But sometimes we don't actually need all those values. Instead we might have custom logic to pick value that arrived into buffer

So I think we should have operator like `buffer` that also take a parameter in reduce manner

```js
buffer<T,V>(closingSelector: () => Observable<V>,reducer: (seed: V,value: T,index: int) => V): OperatorFunction<T,V>
```

And so, suppose I would want the minimum of some value from object

```js
observable.buffer(() => anotherObservable.map(() => null),(seed,obj) => {
    return seed == null || obj.value < seed.value ? obj : seed;
});
```

Then, with each batch, it will only have single object with minimum value passed to next operator instead of the whole array. We could use any custom reduce logic we need here easily and more efficient. While the default buffer is `array.push`

Is this possible or it already possible?

**Comment by josepot** [comment]
I'm not sure if I understood the question/proposal correctly, but I _think_ that the operator that you are looking for is `scan`. Maybe what you are trying to do is something more or less like this?

```ts
const someObservable$: Observable<{ value: number }> = interval(1000).pipe(
  map(() => ({ value: Math.floor(Math.random() * 1000) }))
);

const minValue$: Observable<number> = someObservable$.pipe(
  scan((acc, current) => Math.min(acc, current.value), Infinity)
);

const clicks$ = fromEventPattern(
  handler => document.addEventListener("click", handler),
  handler => document.removeEventListener("click", handler)
);

clicks$
  .pipe(withLatestFrom(minValue$))
  .subscribe(([clickEvent, latestMinVal]) => {
    // TODO: your logic
  });
```
I hope this helps, and sorry if I misunderstood the question.

**Comment by Thaina** [comment]
@josepot Thank you but this miss a point a little bit. From my example I don't actually want min value of all time, I just want the min value of each buffer

The closest thing I expect from this operator is the `buffer` itself, then just take the min value of each batch

```ts
someObservable$.buffer(clicks$).map((items) => items.minBy((item) => item.value));
```

My point is, instead of making array and do operation after buffered. I think we should be able to run reduce function and create the expected output of buffer immediately

```ts
// same output as above, but not create array
someObservable$.buffer(clicks$.map((_) => null /* this become initial seed */),(seed,value) => (seed,obj) => {
    return seed == null || obj.value < seed.value ? obj : seed;
});
```

**Comment by cartant** [comment]
I'm closing this because, in general, we don't want to be adding operators to the RxJS core. Instead, we encourage developers to [write their own user-land operators](https://ncjamieson.com/rxjs-community-packages/). Also, it seems that the operator you've described could be composed using `buffer` and `map` - [as  you've done yourself](https://github.com/ReactiveX/rxjs/issues/5672#issuecomment-679437903).
