### ISSUE TITLE
CombineLatest and ForkJoin to return object of type

### ISSUE THREAD

**Issue by BoshJeckerleg** [ReactiveX/rxjs#5680]
First of all. Just want to say thanks for an awesome library that makes my working life a lot easier and enables me to write much cooler code than I could do on my own. 

## Feature Request

I find combination observables extremely useful when working with multiple observable streams that I need to either combine into a response object or listen to and use the latest value of each property if one has changed. 

A practical use case is making multiple API calls for each response object key and then formatting the response object with each value. Like this;

```
      return forkJoin([getPropertyOneData(), getPropertyTwoData(), getPropertyThreeData()]).pipe(
            map(([propertyOneData, propertyTwoData, propertyThreeData]) => ({
                one: propertyOneData,
                two: propertyTwoData,
                three: propertyThreeData,
            })),
        );
```

Or listening to multiple observable streams and then each time one changes, using the latest value of each for an API call.

```
        return combineLatest([getPropertyOneData(), getPropertyTwoData(), getPropertyThreeData()]).pipe(
            switchMap(([propertyOneData, propertyTwoData, propertyThreeData]) =>
                apiCall(propertyOneData, propertyTwoData, propertyThreeData),
            ),
        );
```

**Is your feature request related to a problem? Please describe.**
The problem is that sometimes when this becomes more complicated and more and more data gets involved, the array destructuring and object creation gets quite bloated and simple errors can be made in this process if the ordering or key naming is incorrect.

**Describe the solution you'd like**
A way of providing an object input to combineLatest and forkJoin that has the correct key values for the response object and a corresponding observable for each value.

The operator then emits the response object as a whole. Without the need for this repetitive manipulation. 

**Describe alternatives you've considered**
Listed above. I guess this is more of a nice to have.

**(If this is new operator request) describe reason it should be core operator**
I think if I've experienced this problem, then others have as well. I think it is a simple enough solution and would reduce errors/code bloat when implemented.

It also has the helpful side effect of increased type checking when creating the observable as I've just found that Typescript seems to keep up with this a lot better than array destructuring etc.

**Additional context**
Something like this and then another for combineLatest

```
    public forkJoinToObject<T extends object>(obj: {[K in keyof T]: Observable<T[K]>}): Observable<T> {
        return combineLatest(
            Object.entries(obj).map(([key, observable]: [string, Observable<any>]) => {
                return observable.pipe(map((value) => ({ [key]: value})));
            })
        ).pipe(
            map((observableKeyValues: {[K in keyof T]: T[K]}[]): T => {
                return observableKeyValues.reduce((result: T, keyValue: Partial<T>) => {
                    return Object.assign(result, keyValue);
                }, {} as T);
            })
        )
    }
```

This way you can do something like this 

```
return forkJoinToObject({
  one: getPropertyOneData,
  two: getPropertyTwoData,
  three: getPropertyThreeData
});
```

Likewise, if I am going wrong somewhere and there is a simpler solution that I am not using, please let me know.

**Comment by rraziel** [comment]
@BoshJeckerleg 
`forkJoin` can work with objects:

```typescript
forkJoin({
  a: $1,
  b: $2,
  c: $3
}) // Observable<{ a, b, c }>
```

`combineLatest` has the same feature starting with rxjs 7

**Comment by BoshJeckerleg** [comment]
@rraziel Nice.
