### ISSUE TITLE
docs reference deprecated API

### ISSUE THREAD

**Issue by joshribakoff** [ReactiveX/rxjs#5684]
### Documentation Related To Component:

https://github.com/ReactiveX/rxjs/blob/master/docs_app/content/guide/v6/pipeable-operators.md

### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [x ] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue

This references `toPromise` but it is deprecated according to the code, and this doc https://github.com/ReactiveX/rxjs/blob/master/docs_app/content/guide/glossary-and-semantics.md

**Comment by josepot** [comment]
That is a link to the docs of v6, in v6 `toPromise` is not deprecated. The code that your are linking to is for the `master` branch which [currently represents the beta version of v7](https://github.com/ReactiveX/rxjs#versions-in-this-repository)

**Comment by joshribakoff** [comment]
Ah sorry. I read the search results wrong when doing a code search on github thanks for pointing that out
