### ISSUE TITLE
Black Lives Matter banner geotargeting

### ISSUE THREAD

**Issue by egorvinogradov** [ReactiveX/rxjs#5685]
Hello,

Is there an option to show the Black Lives Matter banner based on the location? E.g. show it only in the U.S. or other related countries? This can be achieved by using a free IP API e.g. http://ip-api.com/json/

Here in Russia, it just looks ridiculous, as there has never been a history of black slavery. It's like if you were advocating Rwanda's Tutsis minority here - while this itself might be a tough issue, it's not a priority for most of the local population, and most people don't know much about it.

I don't understand why the historical problem of a particular country should interfere with the daily routine of developers across the rest of the world.

Thank you

**Comment by kwonoj** [comment]
We don't consider region-based offering at this moment. Core team will internally discuss, this thread is locked to prevent other comments meanwhile.
