### ISSUE TITLE
retryWhen notifier emission can't be used to create an Observable

### ISSUE THREAD

**Issue by niklas-wortmann** [ReactiveX/rxjs#5693]
I was stumbling across this behavior today in my daily work. The notifier emission of `retryWhen` is the error object. But I can't use this emission to create an Observable from it. I built a small stackblitz to demonstrate this behavior:
https://stackblitz.com/edit/rxjs-f58qa3?devtoolsheight=60

```ts
const error = throwError({error: 'sfaoh'});
const source = error.pipe(retryWhen(notifier => {
  return notifier.pipe(
    delay(3000),
    tap(console.log),
    switchMap(x => {
      return from(x);
    }),
    take(2)
  );
}));
```

From my perspective this should work, but it is throwing an error?
```
You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.
```

**Comment by cartant** [comment]
The notifier [emits the effected error](https://github.com/ReactiveX/rxjs/blob/7.0.0-beta.5/src/internal/operators/retryWhen.ts#L117) - not an observable or observable input - so you'd need to use `of(x)`.

**Comment by niklas-wortmann** [comment]
Memo to myself: Clarify in the docs and check source code  :D. Thanks @cartant for clarification
