### ISSUE TITLE
pluck results in and `unknown` type

### ISSUE THREAD

**Issue by klemenoslaj** [ReactiveX/rxjs#5701]
## Bug Report

**Current Behavior**

Using a `pluck` operator over the object with optional nested object can result in `unknown` type.
This can be particularly dangerous when using `filter` function with type narrowing type guards `filter((result): Result is T => ...)`

**Reproduction**
- REPL or Repo link:
https://stackblitz.com/edit/rxjs-9zehnm

```TS
interface Result {
  data?: {
    obj: {
      value: string
    }
  }
};

const result: Result = { data: { obj: { value: '' } } };

of(result)
  .pipe(pluck('data', 'obj'))
  .subscribe(obj => console.log(obj.value)); // Object is of type 'unknown'.
```

Now if we add `filter` into the mix, this get's even more interesting:

```TS
of(result)
  .pipe(
    pluck('data', 'obj'),
    filter((obj): obj is number => !!obj), // Narrowed to `number` type 😱
  )
  .subscribe(obj => console.log(obj.value)); // Property 'value' does not exist on type 'number'.
```

**Expected behavior**

Type safety should not be lost when using the `pluck` operator. The result we're getting with `map` operator is correct:

```TS
of(result)
  .pipe(
    map(result => result.data && result.data.obj),
    filter((obj): obj is number => !!obj), // A type predicate's type must be assignable to its parameter's type. Type 'number' is not assignable to type '{ value: string; } | undefined'.
  )
  .subscribe(obj => console.log(obj.value));
```

**Environment**
- Runtime: Chrome v85
- RxJS version: 6.6.3

**Comment by cartant** [comment]
FWIW, `pluck` will be [deprecated](https://github.com/ReactiveX/rxjs/blob/795ea6afa2e95d8901bf3e8f8ca5cabd402e39b2/src/internal/operators/pluck.ts#L44) in v7 and will be removed in v8. Now that JavaScript has optional chaining, it's recommended to use `map` instead:

```ts
map(result => result?.data.obj),
```

IMO, there's little point introducing more complicated types to make this work when it's not something that's going to be recommended or - eventually - supported.

**Comment by klemenoslaj** [comment]
@cartant thanks for a quick reply. I completely missed its `deprecated`.
In that case this should be closed :+1:
