### ISSUE TITLE
Npm version 3 support

### ISSUE THREAD

**Issue by jesperronn** [ReactiveX/RxJS#572]
I am using Npm 3 to build an Angular 2 project (`"angular2": "2.0.0-alpha.44"`). 

In this project's `package.json` there is a line defining it only works with Npm version 2. See https://github.com/ReactiveX/RxJS/blob/2c958911d28244db328b63523bf2d16003000b18/package.json#L95

My question: can we safely update to Npm 3? If so, do you want a pull-request, or do it yourself?

My (private) project issues a warning in the logfile when building. But it still works.

```
$ npm install
npm WARN engine @reactivex/rxjs@5.0.0-alpha.4: wanted: {"npm":"~2.0.0"} (current: {"node":"4.1.0","npm":"3.3.8"})
```

**Comment by kwonoj** [comment]
As you've mentioned, so far I know package definition won't block when system is using npm 3, as I use npm 3 daily without issue. Is there particular cases worrying about, or problem you're experiencing with?

**Comment by jesperronn** [comment]
@kwonoj I see no problem either. Only a warning when running NPM 3 

during npm install (for project with rxjs dependency):
```
npm WARN engine @reactivex/rxjs@5.0.0-alpha.7: wanted: {"npm":"~2.0.0"} (current: {"node":"4.1.2","npm":"3.3.3"})
```

Since we both know that it works with npm 3, then let's remove the warning. I can create a pull-request?
