### ISSUE TITLE
bug(audit): Does not end audit period and emit when source completes

### ISSUE THREAD

**Issue by benlesh** [ReactiveX/rxjs#5730]
I would expect that with `audit`, if the source closes before the duration ends, we'd get the last value it captured. For whatever reason we decided not to do that ages ago, and I can't imagine why.

When the source completes, I think it should either:

1. If it has seen a value, wait for the duration to end, then emit the value and complete the result.

OR

2. Immediately emit the last value it saw (if any), then complete the result.

I'm inclined to say #1 makes the most sense. It's also the behavior of throttle.

**Comment by alexsherekin** [comment]
> 1. If it has seen a value, wait for the duration to end, then emit the value and complete the result.

This would mean, that we never emit and never complete if the duration is `never` or just neither emits nor completes. Is it the desired behavior?
