### ISSUE TITLE
BLM Full page statement - Questions 

### ISSUE THREAD

**Issue by fendorio** [ReactiveX/rxjs#5734]
Whilst no decent human would disagree that a black persons life matters, I am scratching my head as to why RXJS has now got a full page statement endorsing the Black Lives Matter political group. 

The BLM political group's objectives are not solely to protest racism, they have much broader objectives than that.  Here are a few things one can easily seek out as to the political group's views/objectives:

The BLM political group's objectives include "dismantling capitalism".  Does RXJS support this? If so that seems ludicrous, given the capitalistic nature of the majority of projects that use RXJS, and software projects in general.

BLM also has stated that as a political group, they see climate change as racist, they tweeted as such in 2016 "Climate crisis is a racist crisis" in response to comments regarding their protests at Heathrow airport. Do the RXJS administrators support this message? 

BLM have also stated that "unemployment is violence". Do the RXJS administrators support this message?

Lastly, to reiterate, no decent human would disagree that a black persons life matters - I am however wondering why the RXJS administrators are displaying a full page introduction on their documentation, endorsing this political group - who's objectives are not solely that of fighting against racism, yet your full page display only references that particular objective of the political group. 

Perhaps you agree with all that the BLM political group are working towards, if that's the case then perhaps you should make that clear on your documentation as well, or perhaps review the stance, much like many other companies have done, many of which have removed endorsements to the BLM political group, partially due to their political goals.

**Comment by benlesh** [comment]
> The BLM political group's objectives include "dismantling capitalism". 

A appreciate that you've spent a lot of time on that post. Does RxJS support "dismantling capitalism"? Nope. But you've presented no proof that BLM, presumably the organization linked with a donation link, does either. In fact, there is absolutely nothing on their site that I can see that outlines that as one of their goals.

In fact, the only mentions of capitalism they have ever made on their site are from ]November of 2017, in which they are calling on people to disavow consumerism and "boycott white capitalism"](https://blacklivesmatter.com/make-this-christmas-a-black-xmas/). I personally find those words cringey, to say the least, however I don't think that jives with group "objectives of dismantling capitalism", and I can't say that I disagree with the sentiment.

The only goals, [outlined in very plain language on their about page](https://blacklivesmatter.com/about/), which I'll screenshot incase they change are:

![image](https://user-images.githubusercontent.com/1540597/93691372-eebcf780-faa9-11ea-93f4-2550bf7b9ea9.png)

If they change their goals to something other than helping an oppressed minority, and something more nefarious, I'll gladly remove the link. But I seriously doubt that is going to happen.

Someday the links will go down, or perhaps get moved around a bit.... but given recent events, today is not that day, and tomorrow probably won't be either.

Honestly, every issue or email like this just makes me want to leave it up longer.
