### ISSUE TITLE
Type error with subject example code

### ISSUE THREAD

**Issue by changhoi** [ReactiveX/rxjs#5735]
### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [ ] documentation needs clarification
- [x] error(s) in example
- [ ] needs example

### Description Of The Issue

```ts
import { Subject, from } from "rxjs";

const subject = new Subject<number>();

subject.subscribe({
  next: (v) => console.log(`observerA: ${v}`),
});
subject.subscribe({
  next: (v) => console.log(`observerB: ${v}`),
});

const observable = from([1, 2, 3]);

observable.subscribe(subject); // You can subscribe providing a Subject

// Logs:
// observerA: 1
// observerB: 1
// observerA: 2
// observerB: 2
// observerA: 3
// observerB: 3
```

there is a type error which is about overload at `observable.subscribe(subject)`

**Comment by cartant** [comment]
I don't see any type errors in RxJS 6.6.3 and you haven't filled out the issue template, so IDK what version you are using.

**Comment by changhoi** [comment]
I use RxJS 6.6.3, typescript 4.0.2, ts-node 9.0.0

When I used `ts-node`, there was below error.
<img width="653" alt="스크린샷 2020-09-19 오후 2 58 40" src="https://user-images.githubusercontent.com/34329147/93660326-9cb7aa00-fa88-11ea-9ca0-d024e17e5b42.png">

and tsc compile had this error.
<img width="643" alt="스크린샷 2020-09-19 오후 3 01 18" src="https://user-images.githubusercontent.com/34329147/93660356-fb7d2380-fa88-11ea-97e3-5285f914e79c.png">

So, I add `es2020` and `dom` in `lib` option of tsconfig. then ts-node error is solved. but there are same error with tsc compile

**Comment by cartant** [comment]
From [the docs](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#using-tsconfigjson-or-jsconfigjson):

> When input files are specified on the command line, `tsconfig.json` files are ignored.
