### ISSUE TITLE
BLM page

### ISSUE THREAD

**Issue by f-ricci** [ReactiveX/rxjs#5738]
#5734 

@benlesh 

I'm not here to discuss any political because this is not the place since you have the option to stop the conversation whenever you want.

I want to remark the fact that you are imposing your personal beliefs, **no matter how genuine and noble they might be**, on a community that cannot change it and whilst developing with Angular can be done without the use of this library anybody can't deny how much it helps.

OpenSource software should not be political, should not take a stance for this or for that because then you go down a rabbit-hole in which not supporting another cause makes you discriminate that cause? You can't support all the causes, there is no time and place to support the whole but if you do make stance, on what beliefs are making your stance?

I would also like to take this moment to thank you and the team behind rxjs for the efforts and great work on the library that helps many of us daily in our work.

**Comment by benlesh** [comment]
I'm sorry I've inconvenienced you by making you ignore a message on our homepage. I hereby issue you a full refund of the RxJS purchase price of $0 American. Enjoy.
