### ISSUE TITLE
Policy for External Resources

### ISSUE THREAD

**Issue by niklas-wortmann** [ReactiveX/rxjs#5778]
My personal take on external resources would be to delete the whole page. 
Taken from google analytics: the /resources page was viewed roughly 2000 times in August (rank 57)

I don't think it adds a lot of value but a lot of effort to review content and keep it up to date. 

I would still keep promoting conferences on the main site, just because there is a different financial risk involved for the conference organizers. 

closes #5504

**Comment by benlesh** [comment]
Core Team Meeting: Remove the resources page for the time being.
