### ISSUE TITLE
ReplaySubject memory leak

### ISSUE THREAD

**Issue by roganov** [ReactiveX/RxJS#578]
`ReplaySubject` would clear its cache of events only when a new observable subscribes, otherwise the array of events grows indefinitely.

Steps to reproduce:
```js
var rs = new ReplaySubject(1);
while (true) {rs.next(1)};
```
Apparently introduced by this https://github.com/ReactiveX/RxJS/commit/488ac2e4708665b71fbd3f3b109766c0e70f3689 commit.

**Comment by trxcllnt** [comment]
@roganov good catch, I knew there was a reason we need to trim on each `next`. @blesh @staltz comments?

**Comment by staltz** [comment]
Yeah you can blame me for taking it out. Certainly looked fishy, perhaps a refactor could help clarify it's not just "getting" the events.

**Comment by blesh** [comment]
@staltz ... has this been fixed?

**Comment by staltz** [comment]
Not yet. I'll do it.

**Comment by blesh** [comment]
Okay, thanks @staltz ... I wasn't asking you to do it, I was just quickly checking to see if I missed that this needed to be closed.

**Comment by kwonoj** [comment]
Closing this issue by PR https://github.com/ReactiveX/RxJS/pull/742 now merged.
