### ISSUE TITLE
URL handling for different versions of the docs

### ISSUE THREAD

**Issue by niklas-wortmann** [ReactiveX/rxjs#5794]
From my point of view we need the following "environments":
next => currently master, specific docs for next major version
stable => currently in the 6.x branch (this should always point to https://rxjs.dev)
all past versions => soo this will be the 6.x  

We basically have two different options how to structure the urls. We can use either subdomains of rxjs.dev or we use subfolders.

Pro and cons:

subdomains (v6.rxjs.dev:
+ toolchain already in place from angular.io (low effort)
+ allows changes to older versions (likely not happening though)
- dedicated deployments
- major release cause some effort to setup the docs properly
- firebase needs a dns entry configuration

subfolder (rxjs.dev/v6):
+ easy deployment
- html 5 routing might be a bit tricky as every subfolder is an own app
- compiled artifacts of archived versions have to be checked in in github
- toolchain needs to be changed (a little bit more effort in the beginning)

related to #5793 & #5792

**Comment by benlesh** [comment]
Core Team Meeting: Generally okay with the path-of-least-resistance and using the sub-domain.

**Comment by cartant** [comment]
Closing this 'cause, AFAICT, the v6 subdomain is now a thing.
