### ISSUE TITLE
`find` still emits `undefined` in case of no match 

### ISSUE THREAD

**Issue by devyetii** [ReactiveX/rxjs#5800]
- My Trial
```js
    of([1], [2]).pipe(
      find((arr) => {
        const res: boolean = arr.length < 1;
        console.log(res);
        return res;
      }),
    ).subscribe(
      console.log,
      console.error,
      () => { console.log('complete') }
    );
```
- Console Output
```console
> false
> false
> undefined
> complete
```

- Closed issues I think related :
    - #2515
    - #2538
According to the mentioned issues, this behavior is changed in this MR
https://github.com/ReactiveX/rxjs/pull/2538/files#diff-cb6135b6e3563fab5be108053b313e3c

Also this behaviour is not mentioned in the documentation

> find searches for the first item in the source Observable that matches the specified condition embodied by the predicate, and returns the first occurrence in the source. Unlike first, the predicate is required in find, and does not emit an error if a valid value is not found.
https://rxjs-dev.firebaseapp.com/api/operators/find

Source Code : 
https://github.com/ReactiveX/rxjs/blob/73fa910cb62eccbccc4b4249f9b2606095704328/src/internal/operators/find.ts#L81

**Comment by cartant** [comment]
The type say that `undefined` will be emitted, so if the docs don't say that, this is a docs issue, IMO.

And the emission of `undefined` is a behaviour that's expected in the tests:

https://github.com/ReactiveX/rxjs/blob/f9ecdf96a01c6cf38998c1ade4109ebd0c45a3b0/spec/operators/find-spec.ts#L36-L45

**Comment by cartant** [comment]
Closing in favour of #6117.
