### ISSUE TITLE
Link to Russian translation of the documentation

### ISSUE THREAD

**Issue by mephistorine** [ReactiveX/rxjs#5802]
### Documentation Related To Component:

Documentation

### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [x] needs example

### Description Of The Issue

Hello there! I am translating the RxJS documentation into Russian. The documentation is posted on the [rxjs.fun](https://rxru.fun) website and [waliot/rxjs-ru](https://github.com/waliot/rxjs-ru) repository. Can I add a link to the site on the [external resources](https://rxjs.dev/resources) page?

**Comment by binakot** [comment]
I think you can add the label `hacktoberfest` 😃 
It will boost the solving of the issue :octocat:

**Comment by mephistorine** [comment]
@binakot I suggest the rxjs repository is not involved in Hacktoberfest

**Comment by benlesh** [comment]
This looks REALLY cool... but I don't stand a chance at verifying the content. Haha.

**Comment by mephistorine** [comment]
@benlesh I understand and its so sad :)

**Comment by niklas-wortmann** [comment]
Translations, in general, have been on our todo list for quite a while now. We started a discussion a while back, see #4388. Unfortunately, we don't have enough time to properly take care of translations. Therefore I will close this for now, please create a new issue if you have an idea how translations could be implemented and maintained in a reasonable manner. I am very happy about any kind of suggestion
