### ISSUE TITLE
.d.ts files in dist have .d.ts.map files

### ISSUE THREAD

**Issue by cartant** [ReactiveX/rxjs#5808]
I've only just noticed that the `.d.ts` type declarations included in `dist/types` have accompanying `.d.ts.map` files.

<img width="179" alt="d ts map" src="https://user-images.githubusercontent.com/3878593/95419389-e5260180-097c-11eb-87ae-228168f58703.PNG">

There are around 230 of them and they total 380,928 bytes in size. Do source maps for the type declarations actually serve a purpose? Should we switch off the generation of these maps to save a little space with the `node_modules` install?

**Comment by kwonoj** [comment]
I have intentionally included it for better dev experience: with declaration map, tsc server can navigate into *source* code when user clicks definition. Without it, it'll show d.ts directly with interface only.
