### ISSUE TITLE
'immediate' Observale.interval failure

### ISSUE THREAD

**Issue by kwonoj** [ReactiveX/RxJS#582]
Snippet below (duplication is intended, single execution works fine)

```
Rx.Observable.interval(0).take(6).subscribe(console.log);
Rx.Observable.interval(0).take(6).subscribe(console.log);
```

leads into unexpected failure in nexttick scheduler like below.

```
\NextTickAction.js:39
                _this.scheduler.scheduled = false;
                                          ^
TypeError: Cannot set property 'scheduled' of undefined
    at Immediate._onImmediate (Z:\github\RxJS\dist\cjs\schedulers\NextTickAction.js:39:43)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
```

Creating issue while try to triage root cause for this.

**Comment by trxcllnt** [comment]
@kwonoj looks like it's caused by [this check](https://github.com/ReactiveX/RxJS/blob/master/src/schedulers/NextTickAction.ts#L40). We should move lines 43-46 from within the conditional to below it.

**Comment by kwonoj** [comment]
Thanks for tips. I'll try to create PR based on suggestion.
