### ISSUE TITLE
`fromEvent` type error: Should it be thrown at Subscription time?

### ISSUE THREAD

**Issue by benlesh** [ReactiveX/rxjs#5823]
Currently, we have a behavior where if you provide an object to `fromEvent` that is _not_ a valid target, it does not error until you try to subscribe to the result. I submit that this is probably a bad behavior, and we should notify the developer as soon as we know it's incorrect.

We have three choices:

1. Throw on subscribe (as is)
2. Throw when `fromEvent` is called.
3. Don't throw at all and let things just fail.

I suspect that 2 is the proper choice here.

**Comment by benlesh** [comment]
@cartant says "Number two" 💩

**Comment by KamilSocha91** [comment]
@benlesh So this is resolved discussion and number 2 should be implemented?
