### ISSUE TITLE
Reinstating *some* of the resultSelectors

### ISSUE THREAD

**Issue by benlesh** [ReactiveX/rxjs#5824]
Currently we have deprecated resultSelectors on the following:

- bindCallback
- bindNodeCallback
- combineLatest
- forkJoin
- fromEvent
- fromEventPattern
- zip
- concatMap
- concatMapTo
- exhaustMap
- mergeMap
- mergeMapTo
- switchMap
- swithMapTo

The reasons for this were two fold:

1. It added size to every operator.
2. It meant that, in some cases, "outer values" from "outer sources" would need to be retained in memory for the lifetime of inner subscriptions. Causing memory pressure.

Given that I think recently the cost of 1 has gotten to be substantially less, I think we may want to revisit the operators where 2 is not the case (basically anything that isn't a map-and-flatten operator).

I'd propose that we can probably "undeprecate" the resultSelector argument for these creation functions:

- bindCallback
- bindNodeCallback
- combineLatest
- forkJoin
- fromEvent
- fromEventPattern
- zip

This is providing that they are not encumbered by issues 1 and 2 above. (I'm sure that 2 is not an issue, but 1 may or may or may not be true). I think this is especially okay if we're getting rid of "n-args" for sources for `forkJoin`, `combineLatest`, and (probably) `zip`.

**Comment by benlesh** [comment]
Also worth noting: The secondary function/mapping argument is a little confusing to read, IMO: `mergeMap(fn, fn2)`.  If we can eliminate the confusing UX there, and mitigate 1 and 2, I might be okay with undeprecating all resultSelectors. Just a thought. 

While we have until v8 to make this decision, I think we should try to decide quickly so we can get our messaging across sooner rather than later.

**Comment by niklas-wortmann** [comment]
I remember that @cartant wanted to discuss some of the deprecations as well, this is probably a good time to do this
