### ISSUE TITLE
Proposal: overload of BehaviorSubject

### ISSUE THREAD

**Issue by roganov** [ReactiveX/RxJS#583]
While building apps with Rx, I have quite often had a need for an observable that remembers its latest value, but doesn't have an initial value. Now this can be achieved by using `ReplaySubject(1)`, but `ReplaySubject` is 'heavier'.
What I'm proposing is to extend `BehaviorSubject` so that when it didn't get passed and initial value, it would wait for first value to come in before emitting anything.
```js
const bs = new BehaviourSubject();
bs.subscribe(::console.log); // would print 'undefined'
```
Proposal:
```js
const bs1 = new BehaviourSubject();
bs1.subscribe(::console.log); // wouldn't print anything, waiting for the first event
const bs2 = new BehaviourSubject(1);
bs2.subscribe(::console.log); // would print '1'
```

This, to my understanding, is implemented, in [RxJava's BehaviorSubject](http://reactivex.io/RxJava/javadoc/rx/subjects/BehaviorSubject.html):
```java
public static <T> BehaviorSubject<T> create()
public static <T> BehaviorSubject<T> create(T defaultValue)
```

**Comment by kwonoj** [comment]
Seems [RxJS4](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/subjects/behaviorsubject.md#rxbehaviorsubjectinitialvalue) also have it, maybe simply not migrated yet?

**Comment by mattpodwysocki** [comment]
:-1: we have been over this in RxJS and declined it then

**Comment by trxcllnt** [comment]
@mattpodwysocki I know this is a dup of my [pull](https://github.com/Reactive-Extensions/RxJS/pull/27) from ~2 years ago, but perhaps we can introduce a new type, `LatestSubject` maybe?

**Comment by mattpodwysocki** [comment]
@trxcllnt yes, as I said before in the old PR that I was perfectly willing to make a new Subject type but was unwilling to change the meaning of the BehaviorSubject due to its downstream dependencies with publishValue etc

**Comment by roganov** [comment]
Yeah a new subject type would be OK. Or we could probably make `ReplaySubject(1)` fast (treat it as a special case).

**Comment by paulpdaniels** [comment]
Couldn't we just make all bounded buffers a special case and implement a circular buffer instead of doing splicing?

**Comment by staltz** [comment]
Actually you can hack around BehaviorSubject if you don't want the first init event.
```js
const bs1 = new BehaviourSubject('ignore me');
const interface = bs1.filter(x => x !== 'ignore me');
interface.subscribe(::console.log); // wouldn't print anything, waiting for the first event
```

But I also think something like `LatestSubject` would be helpful. Maybe we could bikeshed on that name still, we could consider `HoldSubject` or `KeepSubject`, taking a bit of inspiration from [Sodium which has the `hold` function](https://github.com/SodiumFRP/sodium/blob/master/denotational/Denotational%20Semantics%20of%20Sodium.pdf), a bit similar to `publishBehavior`.

**Comment by staltz** [comment]
> Yeah a new subject type would be OK. Or we could probably make ReplaySubject(1) fast (treat it as a special case).

@roganov ReplaySubject and BehaviorSubject have different semantics for observers after they complete. See https://github.com/ReactiveX/RxJS/issues/453

**Comment by ghetolay** [comment]
So I came to the exact same conclusion when I needed to use a `publishReplay(1)` but seems too heavy compared to a `publishBehavior()` + `filter()`.

Is the idea of a new Subject dropped or are we just waiting for a PR ?
