### ISSUE TITLE
Can't read documentation from mobile

### ISSUE THREAD

**Issue by real-artswan** [ReactiveX/rxjs#5835]
When I open site https://rxjs-dev.firebaseapp.com on Android phone I just see non closable BLM screen. 
wtf? I appreciate your desire to help somebody, but I'm from Ukraine we're here don't care about black or white in the US (we're here don't care about skin colot at all) and I'm sure as well as people in the Russia, or China, or Turkie, or in the many of the Africa countries. To me, BLM it is the local US issue. 
So why I can not open the documentation on the mobile?

**Comment by kwonoj** [comment]
![Screenshot_20201017-123421_Chrome](https://user-images.githubusercontent.com/1210596/96352035-22714a00-1075-11eb-96e4-7d46a191bfbd.jpg)
Please use menu button. Even before blm banner we had front page and there was menu to access document.

**Comment by real-artswan** [comment]
Thanks and nice, but any way is not obvious, you might be better in the UX

**Comment by eduardoturconi** [comment]
Perhaps would improve UX if the message is "ALL LIVES MATTER", instead of a portion of human lives
