### ISSUE TITLE
Generic type inference failure when multiple type provided (with typescript)

### ISSUE THREAD

**Issue by kwonoj** [ReactiveX/RxJS#584]
Writing below code via ES5 with commonjs,

`Rx.Observable.of(1, 'a').subscribe(console.log);`

will be executed with below results
>1 
a

though some editors might complain by type inference failure. 

if same code is written in typescript, now those complaint becomes build time failure
> error TS2453: The type argument for type parameter 'T' cannot be inferred from the usage. Consider specifying the type arguments explicitly.
  Type argument candidate 'number' is not a valid type argument because it is not a supertype of candidate 'string'.

Somewhat related to issue https://github.com/ReactiveX/RxJS/issues/581, not directly though.

**Comment by kwonoj** [comment]
I'm looking into this to try resolve.

**Comment by kwonoj** [comment]
Course caller can explicitly cast like 
`Rx.Observable.of(<any>1,<any>'a').subscribe(console.log);`
, but seems bit hassle.

**Comment by staltz** [comment]
Can you write `Rx.Observable.of<any>(1, a').subscribe(console.log);` instead?

**Comment by kwonoj** [comment]
Yes, that works too. Snippet I took is exaggerated examples of casting hassle. Still it'd be better wouldn't require explicit casting, not sure if it's achievable along with generic based type-safety.

**Comment by roganov** [comment]
I don't think that `Rx.Observable.of<any>(1, 'a')` is a hassle, IMO it's perfectly reasonable TypeScript. It also makes you think whether you really want to mix types.

**Comment by kwonoj** [comment]
Ok, closing now.
