### ISSUE TITLE
Provide a V7 migration script (e.g. rxjs-6-to-7-migrate)

### ISSUE THREAD

**Issue by yjaaidi** [ReactiveX/rxjs#5843]
## Feature Request
It would be nice to provide a migration script like `rxjs-5-to-6-migrage` to help migrating to V7.
For instance, it could transform `source$.toPromise()` to `lastValueFrom(source$)`.

## Why

The script should not cover breaking changes only; it should also cover recommendations and deprecations for the following reasons:
1. migration scripts are not just a way of avoiding breaking changes; they are a way to discover, learn and quickly enjoy the latest features,
2. what can be automated should be automated if not too expensive and fragile,
3. most of us won't fix deprecations until they become breaking changes (e.g. on V8 for example) and that's when we get stuck with V7.

## What

Which features should be covered by this migration script? Please help me fill this list 🙏

- [ ] replace `toPromise` by `lastValueFrom`
- [ ] TODO

## How

Should the rules be implemented for both eslint & tslint to https://github.com/cartant/rxjs-tslint-rules and https://github.com/cartant/eslint-plugin-rxjs?
Or  should we make a script like `rx-5-to-6-migrate` (Cf. https://github.com/ReactiveX/rxjs-tslint) based on eslint? 🤔

## When

Should this be added to the V7 roadmap: https://github.com/ReactiveX/rxjs/issues/5795?

**Comment by BioPhoton** [comment]
To figure out the deprecations u can run https://github.com/ts-chore/deprecation-manager. What is missing ATM is detection of breaking changes...

**Comment by benlesh** [comment]
This would be fantastic. But we don't have the engineering hours to support an effort like this. Development here is 100% volunteer. The last time we had migration scripts and compat packages, it was largely provided by contractors and employees paid by Google (via the generosity of the Angular team).

**Comment by benlesh** [comment]
Also, it is worth noting that most of the breaking changes here are related to the generics and types we're using. So most of any migration anyone would need to do would involve no longer using explicit generics (incorrectly)... Like: `map<number>(fn)`, or `const s = new Subject<number>(); s.next(); // bad`. etc.

**Comment by samal-rasmussen** [comment]
Can we still do a 6-to-7 migration guide though?

**Comment by yjaaidi** [comment]
Thank you @BioPhoton for the tip.
Thank you @benlesh for the feedback.
Actually, I would like to help and contribute with the migration script. I was just wondering if the right way would be to extend https://github.com/cartant/eslint-plugin-rxjs or should that be a dedicated script.

**Comment by undsoft** [comment]
For anybody coming here looking on an easy way to migrate, you can use [prefer-observer](https://github.com/cartant/eslint-plugin-rxjs/blob/main/docs/rules/prefer-observer.md) from eslint-plugin-rxjs with. automatic fixer.
