### ISSUE TITLE
Lazy version of withLatestFrom

### ISSUE THREAD

**Issue by david-shortman** [ReactiveX/rxjs#5845]
## Feature Request

**Is your feature request related to a problem? Please describe.**
There are many use cases for delaying evaluation of the arguments to `withLatestFrom`. A common example is in NgRx, where there might be effect like so:

```typescript
createEffect(() => this.actions$.pipe(
  ofType(c),
  withLatestFrom(this.store.select(getSelectedBookId)),
  switchMap(([action, selectedBookId]) => this.bookService.getDetails(selectedBookId).pipe(
    map(...),
    catchError(...)
  )
);
```

When the arguments to `pipe` are evaluated, so is `this.store.select`. In NgRx, performing a select has memory and performance implications. 

Ideally, then, because we don't care about the values from the observable produced by `this.store.select(getSelectedBookId)` until we receive an action of type `this.store.select(getSelectedBookId)`, we could do something like:

```typescript
createEffect(() => this.actions$.pipe(
  ofType(c),
  concatMap(action =>
      of(action).pipe(
      withLatestFrom(store.select(someThing))),
  withLatestFrom(this.store.select(getSelectedBookId)),
  switchMap(([action, selectedBookId]) => this.bookService.getDetails(selectedBookId).pipe(
    map(...),
    catchError(...)
  )
);
```

**Describe the solution you'd like**
Create an operator which is functionality equivalent to the solution above to delay evaluation of `withLatestFrom`.

**(If this is new operator request) describe reason it should be core operator**
I'm not confident it should be. The use case may be too specific to NgRx, hence why https://github.com/ngrx/platform/issues/2222 is open on their platform.

However, if it is common that other types of observables should be delayed when using `withLatestFrom`, then this may be worthy of a core operator.

**Comment by david-shortman** [comment]
Also fitting this use case is this potential operator: https://gist.github.com/sod/a34fc7705b396f61d0ef00713b807209

**Comment by david-shortman** [comment]
Introduced a PR to NgRx for now. If it looks like it belongs here instead, tell me https://github.com/ngrx/platform/pull/2760

**Comment by benlesh** [comment]
I think all you want to do is put your "other sources" in a `defer`:

```ts
createEffect(() => this.actions$.pipe(
  ofType(c),
  withLatestFrom(defer(() => this.store.select(getSelectedBookId))), // <---- here
  switchMap(([action, selectedBookId]) => this.bookService.getDetails(selectedBookId).pipe(
    map(...),
    catchError(...)
  )
);
```

I'll close this for now, but feel free to reopen if that's not what you're after.

**Comment by david-shortman** [comment]
@benlesh `defer` only delays evaluation until subscription. The purpose of the operator is to defer evaluation until the last moment it is needed, when the operator is called to transform some value. This spec defines the desired behavior: https://github.com/ngrx/platform/pull/2760/files#diff-65f81e5d2793f31b4cc23991c7068b1dcd0a8b327be69f0c195aebc1f5c96ea3R24-R36
