### ISSUE TITLE
delay operator doesn't affect finalized operator prior to it

### ISSUE THREAD

**Issue by KingMario** [ReactiveX/rxjs#5858]
## Bug Report

**Current Behavior**
by adding a delay operator, the calling of the finalized operator is not delayed at all.

**Reproduction**

https://stackblitz.com/edit/rxjs-yngnhf?

**Expected behavior**
the finalized operator should be called after the delay.

**Environment**
- RxJS version: v6

**Comment by Airblader** [comment]
The docs pretty clearly and specifically talk about the fact that `delay` only affects emissions, and completing an observable is not an emission.

**Comment by KingMario** [comment]
@Airblader thx for the explain. will close this issue.

**Comment by Airblader** [comment]
If you do want to delay the completion you can concatenate your observable with a delayed observable which has ignoreElements piped into it, something like `timer(1000).pipe(ignoreElements())`. This can easily be written as a custom operator, too.
