### ISSUE TITLE
windowWhen case spelling wrong on the official website operators document

### ISSUE THREAD

**Issue by MurakamiKennzo** [ReactiveX/rxjs#5887]
in the [official website operators link](https://rxjs-dev.firebaseapp.com/guide/operators):

![image](https://user-images.githubusercontent.com/28294081/98494965-201b9d80-2279-11eb-8c65-994fcf497918.png)

**Comment by elpddev** [comment]
Hi @MurakamiKennzo . I'm not a maintainer, just looking. It does not seems there is a wrong case from the pic. If there is, you can open a PR for the doc. the doc is at https://github.com/ReactiveX/rxjs/blob/master/docs_app/content/guide/operators.md.
