### ISSUE TITLE
Indication whether a stream of composed observables has action/progress/activity in it

### ISSUE THREAD

**Issue by elpddev** [ReactiveX/rxjs#5889]
## Feature Request

I am trying to determine if an observable stream has some activity going on in it. 

I have [asked on stackoverflow](https://stackoverflow.com/questions/64739146/determine-if-an-observable-stream-is-in-progress-and-present-a-loader-based-on-i) but I don't think this is a usage question but a feature, unless I'm mistaken of course. 

**Is your feature request related to a problem? Please describe.**

For an example use case - An entity (ex. customer) stream that get updated from several actions like loading, updating, and socket update listening. Each time the stream is doing something like loading or updating for example, I would like to show a spinner.

```js
class CustomerService {
  customerStreamInProgress$ = /* how to calculate it */

  customer$ = this.streamCustomer();
  // ...
  streamCustomer() {
    return rx.pipe(
      () => merge(
        this.streamCustomerFromLoad(),
        this.streamCustomerFromUpdate(),
        this.streamCustomerFromSocket(),
      ),
      shareReplay(/* refcount 1*/),
    )(null):
  }

  streamCustomerFromLoad() {
    return rx.pipe(
      () => this.loadCustomerAction$,
      switchMap(cusotmerId => this.customerRestApi.fetchCustomer(customerId)),
    )(null);
  }

  // ... other methods the same design pattern.

  loadCustomer(id: number) {
    this.loadCustomerAction$.next(id);
  }
}
```

**Describe the solution you'd like**

It would be a lot more easier if an observable could expose on it an observable property `inProgress$` that one can subscribe on. The library itself will take care while combining observables to notify upstream the in-progress state.

Other way could be to expose another type of signal on top of `next`, `error`, and `complete`. `inProgress` signal.

I am not saying this is a good idea, just what I'm feeling is missing in current architecture. Some way to observe a structure like a river and tell if water started/stopped flowing in at least one of it sections/branches. Some way to know if it is alive or not doing anything at the moment.

**Describe alternatives you've considered**
1. Currently, the way to solve this is by using manual behavior subject `isMyModelInProgress$` that get set as true/false in each sub streams before and after actions start and end. 

This is very verbose and cumbersome. I am trying to find a better aspect oriented way of solving this.

2. I have tried to hack some operators to include and provide a custom property `inProgress$` on the observables they return, but it is very hacky.

An augmented `mergeMap` operator for example:

```js
function ipMergeMap(project) {
  const inProcesSelf$ = new BehaviorSubject(false);
  const inProcessSelfSources$ = new Subject();

  return (source$) => {
    const resultOperatorObs$ = mergeMap((...args) => {
      inProcesSelf$.next(true);
      const result$ = project(...args);
      inProcesSelf$.next(false);
      inProcessSelfSources$.next(result$);
      return result$;
    })(source$);

    const inProcess$ = combineLatest(
      inProcesSelf$,
      source$.inProcess$ || new BehaviorSubject(false),
      inProcessSelfSources$.pipe(
        mergeMap((src$) => {
          return src$.inProcess$ || new BehaviorSubject(false);
        })
      )
    ).pipe(map((list) => list.some((inProcess) => !!inProcess)));

    resultOperatorObs$.inProcess$ = inProcess$;

    return resultOperatorObs$;
  };
}
```

3. I have tried looking into the scheduler functionally, maybe constructing a custom scheduler that can be given to the specific streams and use it to capture whether there is something going on at all or none. I do not know if a custome scheduler can be given to all desired piped operators for instance. I have tried looking into overriding the `schedule` method and augmenting the `work` with something that will notify start/end of the work but I'm limited at this time by my knowledge of schedulers mechanism and architecture.

**(If this is new operator request) describe reason it should be core operator**
This is not a new operator request.

**Additional context**
A more full expample of what I tried as the second solution and I do not think is the right way but is interesting:
https://codesandbox.io/s/github/elpdcore/rxjs-experiments-in-proces-observables/tree/master/?file=/src/1.1_create_an_observable.js

**Comment by cartant** [comment]
I'm closing this because I don't see how a feature like this would fit within the RxJS core.

Observables already have a mechanism for indicating whether or not a stream has activity in it: the `complete` notification. If a subscriber has not received a `complete` notification, then there is still 'something happening'. If the feature needs information more specific than that, I don't think it would be a good fit for the core.

In general, we encourage proposals to be built as user-land libraries - to provide some validation that the feature is generally useful.

> I have asked on stackoverflow ...

You might have better luck opening a [discussion](https://github.com/ReactiveX/rxjs/discussions) in this repo, to seek input from others.
