### ISSUE TITLE
[Symbol.observer] is unergonomic for people that know what they're doing.

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#59]
Observable is a functional programming thing. In pure functional programming, there is no "Zalgo". So anyone that is using Observable properly will want to always use `[Symbol.observer]()` to subscribe to the observable. I think it's safe to say that I know exactly zero heavy users of Observable, at Netflix at least, that *want* to do this. (I'll go so far as to say that list probably includes @jhusain. haha) Just playing with it hurts and I find myself wanting to override the whole thing like: `Observable.prototype.subscribe = Observable.prototype[Symbol.observer]` just to enjoy using the type.

I understand that Zalgo is a footgun for people who are coding imperatively, so we need to build libraries around this defensively. I guess I feel hiding it under `[Symbol.observer]` is just a little too much. 

I'd like to propose that `[Symbol.observer]` change to either:

- `subscribe` - back to the good old days of RxJS, maybe make the "safe" version be named `when`.
- `forEach` - because the name alone makes it sound like sync behavior, honestly.
- `observe` - because it's less annoying to type over and over than `[Symbol.observer]`.

At some point people are going to have to put on their big-boy pants about Zalgo. If you're programming functionally, it's really all or nothing, or you better know what you're doing. Observables are not promises. They're not a stateful construct for async imperative programming, they're a functional programming paradigm.

**Comment by blesh** [comment]
Haha... looking at the wrong repo when I submitted this...

**Comment by BerkeleyTrue** [comment]
Which repo where you looking at? I would like to join the conversation.

**Comment by blesh** [comment]
http://github.com/zenparsing/es-observable   ... good luck, there are some strong wills in that their repo. ;)

**Comment by BerkeleyTrue** [comment]
Hmmm... heated discussion going on there. Will this version of RxJS be async subscription? I seem to remember talk of making the default scheduler asynchronous.

**Comment by blesh** [comment]
@BerkeleyTrue I'd rather it not be, but I'd like it to conform to the spec. There are some issues with asynchronous subscription, and there are needs within the various organizations contributing to this repository to consider. Preliminarily, I'm going to say "no". But I will say the what's currently in master is made to conform to the es-observable spec (as it was 2-3 weeks ago)

**Comment by BerkeleyTrue** [comment]
:+1:
