### ISSUE TITLE
export 'Subject' (imported as 'Subject') was not found in 'rxjs'

### ISSUE THREAD

**Issue by drfbwilliams** [ReactiveX/rxjs#5908]
## Bug Report

Regardless of how I install, the library is failing in all cases. The code is built - no errors, but a package npm script to build simply fails with errors as soon as I reference the component below in my application.

App is 

asp.net core 3.1 MVP, React, typescript

copy of package.json

`
{
  "name": "integratetest5",
  "version": "1.0.0",
  "description": "",
  "scripts": {
    "build": "webpack --config webpack.config.js",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@types/react": "^17.0.0",
    "@types/react-dom": "^17.0.0",
    "css-loader": "^5.0.1",
    "framer": "^1.2.10",
    "framer-motion": "^2.9.4",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-marquee-slider": "^1.1.2",
    "react-router-dom": "^5.2.0",
    "react-scripts": "^4.0.1",
    "rxjs": "^6.6.3",
    "source-map-loader": "^1.1.2",
    "style-loader": "^2.0.0",
    "ts-loader": "^8.0.11",
    "webpack": "^5.6.0",
    "webpack-cli": "^4.2.0"
  },
  "dependencies": {
    "botframework-directlinejs": "^0.11.6",
    "typescript": "^4.0.5"
  }
}

`

As you can see here - all internals also fail on Rxjs when this occurs as well:

![image](https://user-images.githubusercontent.com/69192966/100448494-f40b7380-30e4-11eb-9369-442f3e1167bd.png)

```js

import { Component } from 'react'
import { Subject, Subscription } from 'rxjs'


// The Main Subject/Stream to be listened on.
const DRFMainSubject = new Subject()

// This function is used to publish data to the Subject via next().
export const DRFMessagePublisher = (data) => DRFMainSubject.next(data)

interface HeaderProps {

}

interface HeaderStates {
    newMessageData: any
}

export class DRFObserverService extends Component<HeaderProps, HeaderStates> {
    // Used for unsubscribing when our component unmounts
    unsub: any = {}

    constructor(props) {
        super(props)

        this.state = {
            newMessageData: {}
        }

        this.unsub = DRFMainSubject.subscribe(data => this.setState({ newMessageData: data }))
    }

    getObserver() {
        return DRFMainSubject;
    }


    componentWillUnmount() {
        this.unsub.unsubscribe()
    }

    render() {
        return (this.state.newMessageData);
    }
}


```

**Expected behavior**
Expected to work - as it has previously

**Environment**
- RxJS version:
V - 6.6.3

**Comment by kwonoj** [comment]
Attached error message is inside of webpack, which we can't able to tell since it's due to application's webpack configurations. Please check webpack configuration, if you think this is a bug in rxjs itself please create new issue with reproducible code or use github discussions for further questions.
