### ISSUE TITLE
RxJS 5 "extensions" - where should they live?

### ISSUE THREAD

**Issue by robwormald** [ReactiveX/RxJS#591]
So I've found myself needing recently a couple of the extensions from earlier versions of Rx.DOM and Rx.Node (stuff like requestAnimationFrameScheduler and Observable.fromStream) - do you want PR's here for these things, or should there be a @reactivex/rxjs-extensions repo or? 

I'd err on the side of them living in here, as you can (theoretically) pluck the things you want out, but wanted to check first...

**Comment by trxcllnt** [comment]
@robwormald I should have the new RAF Scheduler finished this weekend. Since everything's modular now, I'm fine committing it to the main project and importing it as necessary.

**Comment by robwormald** [comment]
Awesome, thanks.

**Comment by roganov** [comment]
As I understood RAF scheduler is going to be available in this repo. What about others things such as `Rx.DOM.ajax`?

**Comment by blesh** [comment]
@roganov that's the plan at this point. Since everything is modular, we can include other RxJS utilities in this repo. Ajax, web sockets, rxify helpers, etc.

**Comment by LongLiveCHIEF** [comment]
I've been working to update the `rx-node` package that @mattpodwysocki broke out during the `rx v2` days, and I can submit a PR for this.  One question, is if I should add these operators to a `node` folder, at the same level as the `DOM` operators, or if they should just go in with the normal operators?
