### ISSUE TITLE
extend ReplaySubject to observe just its buffer

### ISSUE THREAD

**Issue by backbone87** [ReactiveX/rxjs#5910]
## Feature Request

**Is your feature request related to a problem? Please describe.**
ReplaySubject could be used as a cache/memoize with timeout by just making the buffer observable, but this requires a rather cumbersome construct right now (see below). The usage simplifies, if it would be possible to observe a ReplaySubject's internal buffer only (complete/error after buffer was replayed). This would also align with BehaviorSubject's getValue

**Describe the solution you'd like**
Add (readonly) property `ReplaySubject.buffer$` which contains an observable that behaves like `new ReplaySubject().pipe(takeUntil(timer(0)))`. To be more in line with BehaviorSubject, it could also be a method returning the buffer: `ReplaySubject.getBuffer`.
A separate Subject implementation could also be considered.

**Describe alternatives you've considered**
```
const value$ = new ReplaySubject(1, 60000);
const memoized$ = concat(
  value$.pipe(takeUntil(timer(0))),
  defer(() => produceNewValue()).pipe(tap(value$.next.bind(value$))),
).pipe(take(1));
```

**Comment by cartant** [comment]
Closing this because I don't believe the core team has any desire to expose internals in this way.
