### ISSUE TITLE
Google Search results highlight firebaseapp.com

### ISSUE THREAD

**Issue by abraham** [ReactiveX/rxjs#5918]
### Documentation Related To Component:

rxjs.dev

### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [x] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue

If you search Google for "rxjs" the first two results are for `rxjs-dev.firebaseapp.com` when I would expec them to be `rxjs.dev`.

<img width="1072" alt="Screen Shot 2020-12-07 at 10 42 52" src="https://user-images.githubusercontent.com/3341/101381836-dd9baf80-387c-11eb-8b84-594eaa37511d.png">

This could probably be fixed with one of the solutions on [Consolidate duplicate URLs](https://developers.google.com/search/docs/advanced/crawling/consolidate-duplicate-urls).

**Comment by niklas-wortmann** [comment]
Thanks a lot for the suggestion. I guess #5777 should fix the problem. It's not deployed yet. Can you double check if there's anything else we can do to improve this situation?

**Comment by abraham** [comment]
That looks like it should take care of it and it appears setting canonical in JS does work. https://www.searchviu.com/en/javascript-canonical-tags/
