### ISSUE TITLE
7.0.0-beta.9 conflicts symbol.observable to redux (and other have old symbol-observable version)

### ISSUE THREAD

**Issue by kwonoj** [ReactiveX/rxjs#5919]
## Bug Report

**Current Behavior**
A clear and concise description of the behavior.

repro at https://github.com/kwonoj/rxjs-symbol-test, `npm i && npm run build` will raise compilation error.

![image](https://user-images.githubusercontent.com/1210596/101386427-08ccd180-3872-11eb-990a-12c550a45033.png)

https://github.com/ReactiveX/rxjs/pull/5874 introduces changes to symbol, which also updated in `symbol-observable` to support this (https://github.com/benlesh/symbol-observable/blob/master/CHANGELOG.md#300-2020-11-02). But some of packages, for examble redux (https://github.com/reduxjs/redux/blob/v4.0.5/package.json#L53) relies on older version of `symbol-observable` conflicts with latest rxjs changes.

This is particularly tricky as there's no easy workaround instead of trying to mutate module resolution somehow.

**Expected behavior**
A clear and concise description of what you expected to happen (or code).

**Environment**
- Runtime: [e.g. Node v${x}, Chrome v${x}]
- RxJS version:
- (If bug is related) Loader, build configuration: [e.g webpack, angular-cli version, config]

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by benlesh** [comment]
Ugh. I guess we can change it back to `symbol`. I'm just not sure how we can ever get that type right. I guess we can't. :\

**Comment by benlesh** [comment]
Or we could upstream other changes... maybe deprecate `symbol-observable` and try to get people to move to 3.x of that library?

**Comment by kwonoj** [comment]
> get people to move to 3.x of that library

That's only pass I can see as well, since I don't see easy workaround. But problem is it's really long tail, i.e we can't say for sure how long will it take the majority of `redux` user upgrade to latest to get away with old symbol-observable.

Maybe it's worth to ask `redux` upstream at least to publish latest version to remove / or update symbol-observable? Not immediate solution but will help.

**Comment by kwonoj** [comment]
>  redux upstream at least to publish latest version to remove / or update symbol-observable? Not immediate solution but will help.

at least if we have published version we can recommend to upgrade redux as well.

**Comment by benlesh** [comment]
Well, really the issue is if they're using `redux` AND `rxjs`, (so perhaps worth pulling in @jayphelps because `redux-observable`).

**Comment by kwonoj** [comment]
`redux-observable` is safe. I specifically meant redux cause latest release have symbol-observable (https://github.com/reduxjs/redux/blob/v4.0.5/package.json#L53) and looks like master seems safe from it (https://github.com/reduxjs/redux/blob/master/package.json#L53), but there isn't version published with these changes.

**Comment by benlesh** [comment]
At this point I think maybe the best answer is that RxJS just sort of "shadow supports" `Symbol.observable`. In other words, since it's a crap shoot that TypeScript will even figure out the right thing to do, perhaps we don't add the type or type handling, and instead we only handle the proper runtime behavior. I just don't know.

I seriously doubt anyone has ever gotten this working properly in TypeScript haha.

**Comment by benlesh** [comment]
> `redux-observable` is safe. I specifically meant redux cause latest release have symbol-observable (https://github.com/reduxjs/redux/blob/v4.0.5/package.json#L53) and looks like master seems safe from it (https://github.com/reduxjs/redux/blob/master/package.json#L53), but there isn't version published with these changes.

Specifically, I mean people using `redux-observable` will have this issue because they're definitely using both `redux` and `rxjs`.

**Comment by jayphelps** [comment]
If redux is willing to patch, I don't personally see it as a particularly egregious issue that people would have to update their redux to be able to use the latest rxjs. Things like that happen.

**Comment by kwonoj** [comment]
>  I mean people using redux-observable will have this issue because they're definitely using both redux and rxjs

that is true. it was my case 😭

**Comment by jayphelps** [comment]
Yeah, certainly not ideal if it can be avoided. I don't have full background to comment on that, though.

**Comment by benlesh** [comment]
We should revert to whatever we were doing before. Which is just having `symbol` and not `unique symbol`. ... `symbol-observable` will also need to be rolled back.
