### ISSUE TITLE
Update docs application to Angular 11

### ISSUE THREAD

**Issue by paulmojicatech** [ReactiveX/rxjs#5920]
### Documentation Related To Component:

package.json
.spec.ts (Updated some test files to TestBed.inject)
doc-viewer.component.ts
custom-icon-registry.ts

### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue
Update docs app to Angular 11

Currently the app is on version 9.1.  This PR is to update the version to 11.  Changes that were made were:
- Update tests to use TestBed.inject instead of TestBed.get
- Remove entryComponents from all the modules
- Update the doc-viewer.component to address Typescript issue due to strict mode
- Update custom-icon-registry to address compile error when extending MatIconRegistry

**Comment by jakovljevic-mladen** [comment]
Hi @paulmojicatech. Did you want to create a PR? The description looks like you already worked on updating Angular version, but it appears that you created an issue instead of a PR.

**Comment by paulmojicatech** [comment]
@jakovljevic-mladen Sorry for that. I created the issue but wasn't sure how to submit my PR. @niklas-wortmann was able to help me and my PR is now created. Thanks for the feedback.

**Comment by jakovljevic-mladen** [comment]
Closing as outdated and fixed in #6566.
