### ISSUE TITLE
[Proposal]: enable github discussions, switch issues to core team backlog

### ISSUE THREAD

**Issue by kwonoj** [ReactiveX/rxjs#5925]
Rxjs core team uses `issues` (https://github.com/ReactiveX/rxjs/issues) as backlog for core team agenda. But also meanwhile it was public place to collect feature request / bug report / other suggestions makes core team hard to manage own issues.

Github discussions beta (https://github.com/ReactiveX/rxjs/discussions) is enabled for rxjs repo recently, and I would like to suggest to use it for generic discussions to switch issues for core team backlog. 

My current proposal is:

- core team will use `issues` as own backlog to keep any bug / roadmap items
- any contributor report bugs uses `issues` as well: but it is strictly required to follow template / provide repro case, otherwise core team will redirect to use `discussions/q&a`
- `discussions` will be place to freely post any q&a / feature request / etcs, depends on roadmap it'll be moved into `issues` 
- `Show and tell` (or to be renamed) will be used to share any user-land implementations
- Categories in discussions will likely to be change over time.

/cc @benlesh @cartant @niklas-wortmann thoughts?

**Comment by cartant** [comment]
:+1:

**Comment by kwonoj** [comment]
As core team member has agreed, I'll proceed in these order

- close this issue
- create new issue to be pinned to instruct to use `discussions`

over time, will collect feedback in discussions to update its categories.
