### ISSUE TITLE
Usage in Browser

### ISSUE THREAD

**Issue by ziaukhan** [ReactiveX/RxJS#593]
Instructions for usage in browser are not provided, while usage instructions for Node.js are provided?

**Comment by robwormald** [comment]
`npm install @reactivex/rxjs` would be the preferred method (as mentioned) but it also gives you a ./dist folder with a few others (including a global build you can simply include in the browser).

Would be helpful to have in the readme I suppose.

**Comment by baio** [comment]
I've tried for browser and it's not working

```
<html>
  <head>
    <script src="../node_modules/@reactivex/rxjs/dist/global/Rx.js"></script>
    <script>
      Observable.of("test");
    </script>
  </head>
  <body>
  </body>
</html>

Uncaught ReferenceError: Observable is not defined
```

**Comment by Frikki** [comment]
@baio Don’t you need to prefix with `Rx`? Like `Rx.Observable.of("test")`?

**Comment by baio** [comment]
@Frikki Thanks, working!
