### ISSUE TITLE
rxjs-dev.firebaseapp.com/guide request for document failed

### ISSUE THREAD

**Issue by jensboer** [ReactiveX/rxjs#5938]
### Documentation Related To Component:

rxjs-dev.firebaseapp.com/guide
found on https://rxjs-dev.firebaseapp.com/guide/operators?_sm_au_=iVVnPs2T0RHP432NVjBBvK7f1Gkf3

### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue

I googled 'rxjs pipe' and visited https://rxjs-dev.firebaseapp.com/guide/operators?_sm_au_=iVVnPs2T0RHP432NVjBBvK7f1Gkf3

I've cleared my browsers cache but that didnt work.

![image](https://user-images.githubusercontent.com/1236102/102465300-ca8f9900-404d-11eb-96e1-5fe724209a64.png)
![image](https://user-images.githubusercontent.com/1236102/102465372-dc713c00-404d-11eb-9d23-5e97b351a441.png)

**Comment by benlesh** [comment]
This no longer seems to be an issue.
