### ISSUE TITLE
forkJoin operator doesn't accept an array of observables

### ISSUE THREAD

**Issue by sumigoma** [ReactiveX/RxJS#594]
ForkJoin doesn't seem to maintain the behavior from Rx4 of supporting both .forkJoin(a,b,c) and .forkJoin([a,b,c]). If you try to do the latter (an array of observables) it gives the exception 
```
TypeError: observables[i].subscribe is not a function
    at ForkJoinObservable.execute.ForkJoinObservable._subscribe (ForkJoinObservable.ts:19)
```

**Comment by endash** [comment]
I'm just gonna comment here because my issue is virtually identical. This is also an issue with `combineLatest`. In Rx4 you could pass an array of observables followed by a projection function. In Rx5 you can only use the arguments list. It is very common to have an array of observables rather than a set number of variables of type Observable.

**Comment by trxcllnt** [comment]
@blesh I also think this is a concern. Unfortunately, TypeScript isn't exactly helpful in this regard. The only solution is to splat the Array when you call forkJoin/combineLatest, which you can only do in es6/ typescript.

I would be ok with a call to "flatten" arguments into a flat list of Observables, no matter how deeply-nested.

**Comment by kwonoj** [comment]
I was thinking about this bit, as @trxcllnt mentioned it requires some additional code to make it work with typescript. Trying to create some changes to trigger perf comparison to see if it's not hurting.

**Comment by blesh** [comment]
I'm sort of indifferent about this one.

We can try adding the checks and see how it affects the performance. If it's a hit, then I say we don't do it, and people can just use `.apply` like they would on any other function in JavaScript.

**Comment by kwonoj** [comment]
>  how it affects the performance

: That's I'd like to verify :) if changes does not hurt performance, supporting this would be good. I should come up with numbers.

**Comment by kwonoj** [comment]
Initial attempt blocked due to same reason as https://github.com/ReactiveX/RxJS/issues/660, property based stub does not allow overload.
