### ISSUE TITLE
There is a problem in finalize operator page

### ISSUE THREAD

**Issue by donqq** [ReactiveX/rxjs#5946]
**Problem : 
//output: 0,1,2,3,4,5....
Fix
//output: 0,1,2,3,4....**

https://www.learnrxjs.io/learn-rxjs/operators/utility/finalize
https://i.imgur.com/XHq1PHv.png

**Comment by KamilSocha91** [comment]
I believe this is official docs: [finalize](https://rxjs.dev/api/operators/finalize)

So Author of what you have found there is [Brian Troncone](https://github.com/btroncone)
