### ISSUE TITLE
Documentation Request: Add naming conventions

### ISSUE THREAD

**Issue by xiaoxiangmoe** [ReactiveX/rxjs#5948]
### Please check those that apply

- [ ] typo
- [x] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [x] needs example

### Description Of The Issue

Related doc: [Angular: Naming conventions for observables](https://angular.io/guide/rx-library#naming-conventions-for-observables)

Angular doc provide the naming conventions for observables.

Maybe we should add naming conventions docs here.

Below I list some possible naming conventions. I don't know which one is recommended.

* observables  (`foo$`)
* subject (`fooSubject` or `foo$`)?
* function name for function return observable (`const foo$ = getFoo$()`, `const foo$ = getFooObservable()` or `const foo$ = getFoo()`, `const {foo$} = getFoo()`, etc.)
* function parameter's names for observable

It would be great if we can reach an agreement and list it in official docs website

**Comment by tonivj5** [comment]
More related docs: [CycleJS, what is the $ convention?](https://cycle.js.org/basic-examples.html#basic-examples-increment-a-counter-what-is-the-convention)

**Comment by highestop** [comment]
Naming convention is necessary for cooperation.

Function naming convention might be something we're looking for, like what discussed here <https://stackoverflow.com/a/43083604>. And I think `const foo$ = getFoo$()` might be a good choice.

- When a function returns stream in some cases, I can see the naming convention `getFoo$()` is good, indicating that you can get a stream after calling it.
- Symbol conventions are better than text conventions in some ways. Some would like to use `getFooObservable()` while others might prefer `getFooRx()`. It's hard to meet an agreement, which leads to another additional complexity, small though.

**Comment by xiaoxiangmoe** [comment]
@cartant I found eslint has an rule [suffix-subjects](https://github.com/cartant/eslint-plugin-rxjs/blob/main/docs/rules/suffix-subjects.md). Do you have any suggestions for naming conventions?

**Comment by cartant** [comment]
@xiaoxiangmoe Nope. Someone else created that rule. I don't have any strong opinions regarding naming conventions.

**Comment by kwonoj** [comment]
While $-based convention is popular across, I do not believe we have specific guidelines around naming conventions as well as core team do not have strong position around those. Please feel free to discuss further in discussions, while I'll close this issue itself as we won't introduce immediate change at this moment. If there's some consensus and demand we may able to discuss further.
