### ISSUE TITLE
missing exports of operations functions from index.d.ts

### ISSUE THREAD

**Issue by mhamri** [ReactiveX/rxjs#5950]
https://github.com/microsoft/TypeScript/issues/42247

Please have a look at the thread in the typescript repo. appreciate your input on this.

from the discussion 

>rxjs ships its own index.d.ts file, which in turn doesn't load in any files from operators/. Auto-import doesn't import from unrelated files, which is what operators/index.d.ts appears to be in this configuration.

**Comment by benlesh** [comment]
I'm sorry, I couldn't quite get the context of what the bug is with rxjs that we need to fix? I haven't noticed or had any problems with typings from the rxjs package in VisualStudio or elsewhere.

**Comment by mhamri** [comment]
@benlesh the problem is the current index.ts doesn't work with typescript recommendation to get IntelliSense for the second level index.ts that are in `rxjs/operators` 

so, first I opened a bug with the vscode about the lack of IntelliSense, and they reopened the bug with the typescript team, and typescript team mentioned it's something the lib owner needs to fix by following this method. 

https://github.com/microsoft/TypeScript/issues/42247#issuecomment-758863988

hope this help to clear the confusion
