### ISSUE TITLE
combineLatest([]) broken in 7.x

### ISSUE THREAD

**Issue by benlesh** [ReactiveX/rxjs#5962]
It should return `EMPTY`, it instead returns `NEVER`.

Tnis is the cause of breakage in Angular router when updating to rxjs@7.

cc @leggechr

**Comment by jakovljevic-mladen** [comment]
@benlesh I tried `beta.9` couple of weeks ago on my Angular project and I all I was getting was the white screen. I never went digging deeper. `beta.10` successfully solved the issue. Thanks a lot!
