### ISSUE TITLE
conflicting types with @types/node v12

### ISSUE THREAD

**Issue by jsaguet** [ReactiveX/rxjs#5964]
## Bug Report

I don't know if there is a solution for this since it seems to be linked with `@types/node` version but I'm reporting it anyway just in case.

**Current Behavior**
When running karma tests in an angular project using `@types/node` v12, I get the following conflicting types error:
```
Error: node_modules/rxjs/dist/types/internal/types.d.ts:17:18 - error TS2717: Subsequent property declarations must have the same type.  Property 'observable' must be of type 'symbol', but here has type 'unique symbol'.

         readonly observable: unique symbol;


  node_modules/@types/node/globals.d.ts:146:14
         readonly observable: symbol;

    'observable' was also declared here.
```

When switching to `@types/node` >=13.1.0 there is no error anymore.

**Expected behavior**
Error should not be present.

**Environment**
- Runtime: Node v12
- RxJS version: 7.0.0-beta.10
- `@types/node` ^12.0.0

**Comment by kwonoj** [comment]
It's breaking change listed in https://github.com/ReactiveX/rxjs/blob/master/CHANGELOG.md#700-beta9-2020-12-07 and partially leftover issue is filed at https://github.com/ReactiveX/rxjs/issues/5919 .

**Comment by jsaguet** [comment]
Damn, I read the changelog and missed this item. Thanks for pointing that out
