### ISSUE TITLE
somthing wrong with guide/testing/marble-testing#time-progression-syntax

### ISSUE THREAD

**Issue by kemplaw** [ReactiveX/rxjs#5977]
## Bug Report

**Current Behavior**
`'a 9ms b 9s c|'`: on frame 0 emit a, on frame 10 emit b, on frame 10,012 emit c, then on on frame 10,013 complete.

**Expected behavior**
`'a 9ms b 9s c|'`: on frame 0 emit a, on frame 10 emit b, on frame 9,012 emit c, then on on frame 9,013 complete.

**Comment by jakovljevic-mladen** [comment]
Closing as fixed in #5988.
