### ISSUE TITLE
Remove `/** @prettier */` annotations

### ISSUE THREAD

**Issue by benlesh** [ReactiveX/rxjs#5982]
To be nice to our friends at Google, we need to try to remove the `/** @prettier */` annotations from the library files. We can probably leave them in the tests (as we can't auto format some of those without ruining the marbles, until they're converted to Run Mode).

This is because, apparently, within Google, the `/** @prettier */` annotation breaks Closure Compiler. ... I'll let that soak in for a second. haha. Anyhow, it's not a big deal, I think we can just reconfigure prettier a bit and remove those comments under `src/`.

cc @leggechr @MichaelJamesParsons

**Comment by leggechr** [comment]
Yes only the src files need to be removed. Once this sync is done I can look into adding the exception in the closure compiler if `@prettier` is important.
