### ISSUE TITLE
Only white supremecist and dumb people support BLM. It is a rich white people hate group.

### ISSUE THREAD

**Issue by MarcGodard** [ReactiveX/rxjs#5992]
## Bug Report

**Current Behavior**
A clear and concise description of the behavior.

**Expected behavior**
A clear and concise description of what you expected to happen (or code).

**Reproduction**

** Please provide repro code does not involves framework, or other setups to address this bug is specific to rxjs core **

- REPL or Repo link:
(you can use https://stackblitz.com/ to create one to attach here)

```js
var your => (code) => here;
```

**Environment**
- Runtime: [e.g. Node v${x}, Chrome v${x}]
- RxJS version:
- (If bug is related) Loader, build configuration: [e.g webpack, angular-cli version, config]

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by benlesh** [comment]
@MarcGodard given that you've repeatedly abused our Issues system to promote nonsense, I have no choice but to ban you from the community.

![image](https://user-images.githubusercontent.com/1540597/106504034-05c61a00-648c-11eb-9bf4-c6534dd2cc2f.png)
