### ISSUE TITLE
Passing BehaviorSubject to tap breaks subsequent subscriptions

### ISSUE THREAD

**Issue by roelkok** [ReactiveX/rxjs#5995]
## Bug Report

**Current Behavior**
When passing a `BehaviorSubject` directly to the `tap` operator, subsequent subscriptions to the subject break. Using a function that calls `.next` instead for `tap` doesn't cause this problem.

**Expected behavior**
Passing a `BehaviorSubject` to `tap` should not break subsequent subscriptions to that subject. 

**Reproduction**

- Repo link:
https://stackblitz.com/edit/typescript-fe4rat?file=index.ts

```js
const subject = new BehaviorSubject(0);
subject.subscribe(v => console.log("sub a", v));

from([1])
  .pipe(
    tap(subject) // <- this breaks sub b
    // tap(v => subject.next(v)) // <- this doesn't
  )
  .subscribe();

subject.subscribe(v => console.log("sub b", v));
```

**Environment**
- RxJS version: 6.6.3

**Comment by cartant** [comment]
This is the intended behaviour. The complete notification from the source completes the subject. If you want only the next notifications use `tap(value => subject.next(value))`.
