### ISSUE TITLE
Scheduler design - Input needed

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#6]
I spent a little time talking with @trxcllnt yesterday about scheduler design. I've also glossed over this briefly with @jhusain and @benjchristensen 

I have a REALLY, REALLY primitive impl in the codebase now, but it needs work. In particular it needs a better design.

Right now it's a global scheduler. But you'll notice I added a dispose() method to it. This is because I initially created it as a class, and thought scheduling might be instance based. This would make scheduling more flexible. However, global scheduling is *very* useful for things like Framework lifecycles (@igorminar, @machty).

I'm looking for input as to how to make this flexible but easy to understand for authors.

**Comment by blesh** [comment]
Also, PLEASE tell me if I'm doing something stupid. lol

**Comment by blesh** [comment]
... and I do realize the primitive scheduler I've put in place is an "execute until done" sort of scheduler. Meaning it doesn't provide gaps for other code execution. This is a bare-metal simplistic impl. I think for most browser-based use cases, adding gaps ala MicroTask scheduling probably isn't completely necessary because the event stream sources themselves will be async, but there's definitely a need for that type of scheduler.

**Comment by machty** [comment]
@blesh sounds like you meant to provide a link to the code, no?

**Comment by blesh** [comment]
Closing this for now. I feel like the Scheduling is in an okay place.
