### ISSUE TITLE
(bug) map and of  operator import in angular app is producing CommonJSAMD warnings

### ISSUE THREAD

**Issue by webmandman** [ReactiveX/rxjs#6000]
## Bug Report

**Behavior**
In my angular project, the auto complete adds this import. 
`import { map } from 'rxjs/internal/operators/map';`

When Compiling the app, I get the CommonJs warning for bailouts:
`WARNING: ..\mycomponent.ts depends on 'rxjs/internal/operators/map'. CommonJS or AMD dependencies can cause optimization bailouts.`

HOW do I get rid of these warnings? 
WHICH is better: 'rxjs/operators' or 'rxjs/internal/operators/map'? Does one provide better tree shaking?
I do not think either should give me this warning.

**Example use of map**

```js
  post(message: string): Observable<any>{
    const payload = {message};
    return this.http.post<any>(this.endpoint, payload)
      .pipe(
        map( result => result.data)
      );
  }
```

**Environment**
- Runtime: 
   VS CODE
   Version: 1.53.0 (user setup)
   Commit: 8490d3dde47c57ba65ec40dd192d014fd2113496
   Date: 2021-02-03T20:36:38.611Z
   Electron: 11.2.1
   Chrome: 87.0.4280.141
   Node.js: 12.18.3
   V8: 8.7.220.31-electron.0
   OS: Windows_NT x64 10.0.17763
   
   Angular: 11.0.6

**- RxJS version: 6.6.0**

**Sample Autocomplete**
The definition states it will auto import from 'rxjs/operators', but what actually gets imported is the 'rxjs/internal/operators/map'.
![MicrosoftTeams-image](https://user-images.githubusercontent.com/991677/107130166-c6c70880-687f-11eb-8f86-82f748165d9a.png)

**Comment by kwonoj** [comment]
internal is private and should not be used as import path. 

Also, given warning is related how bundler picks up specific module between cjs / other and its optimizations. Please check bundler configurations.

**Comment by webmandman** [comment]
@kwonoj, help a brother out. where can I learn more about bundler configurations? I've never heard or read about that. I don't know what that is. 

And thanks. 'rxjs/operators' does not generate those warnings.
