### ISSUE TITLE
Feat: Support ReadableStream as an ObservableInput

### ISSUE THREAD

**Issue by benlesh** [ReactiveX/rxjs#6006]
Although RxJS gets a LOT of use in Node, RxJS's primary space has been in the browser. Based off of discussion [in this Twitter thread about fetch streaming](https://twitter.com/BenLesh/status/1358874655076077569?s=20)

We might want to support duck-typing `ReadableStream<T>` as an `ObservableInput<T>`.

If we did this, it might be beneficial, especially in the `fetch` API. But it's probably worth investigating what all use cases might exist.

I definitely think if it's added to `from`, `schedule`, and internally, `innerFrom`, it would need to be the absolute _last_ thing checked. The presence of `asyncIterator` or `iterator` should definitely beat out a check for `typeof o.getReader === 'function'`. 

This would be a lightweight and powerful add, IMO.

@jayphelps generously volunteered to do the work.

**Comment by jayphelps** [comment]
> The presence of asyncIterator or iterator should definitely beat out a check for typeof o.getReader === 'function'.

Agreed.

---

I'll hold off until there is true consensus that this would want to be landed, since while it's not "hard" it's also not a 5 minute thing to PR.

**Comment by benlesh** [comment]
General approval from the core team 👍
