### ISSUE TITLE
Remove `ArrayLike` from `ObservableInput`

### ISSUE THREAD

**Issue by benlesh** [ReactiveX/rxjs#6011]
Related to this issue here: https://github.com/ReactiveX/rxjs/issues/4563

The problem is that this is true:

```ts
const x: ArrayLike<any> = () => {}
```

But at runtime, our check makes sure it's not a function:
```ts
export const isArrayLike = (<T>(x: any): x is ArrayLike<T> => 
    x && typeof x.length === 'number' && typeof x !== 'function');
```

This, combined with the fact that any "array-like" I know of has implemented `Symbol.iterator` now, means that this type is mostly worthless. I doubt many people are like:

```ts
const source$ = from({
   length: 2,
   "0": "wee",
   "1": "I'm weird!"
})
```

**Comment by benlesh** [comment]
One alternative is to just enforce, via TypeScript, that there's at least a `0` index on the `ArrayLike`:

```ts
interface ArrayLike<T> {
    readonly length: number;
    readonly 0: T;
    readonly [n: number]: T;
}
```

This shouldn't break anything, because `arguments`, which IIRC was the primary driver for including `ArrayLike` to begin with, implements `[Symbol.iterator]`, so it should still be allowed.

**Comment by benlesh** [comment]
Okay, this gets weirder and weirder... in TS 4.1.3:

```ts
interface ArrayLike<T> {
    readonly length: number;
    // readonly 0: T;
    readonly [n: number]: T;
}

function works(arg: ArrayLike<any>) {}

works(() => {});

function doesNotWork<T>(arg: ArrayLike<T>) { }

doesNotWork(() => {});
```

I'm not totally sure what to make of that... [playground here](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgIJSnAngGWAawgB4AVAPmQG8BYAKGQeSgjgBMB7EAGy2S4hABzMAAsAXMhABXALYAjaAG46jZAHo1TFh268ADBJLL6jZm049kAbRATp86AF1DxgL506MKSARhgnZAB3dih8AGcACjgoQQl0TFwCYjgQLDIASip3Wjpg0MiIzIBeCkpXdONPb19-EGQOCDCAOXYwAHUQ-FIyKJi4jGw8Qm7MymRsugbm1o7QiMLkEqyKoA)

**Comment by cartant** [comment]
Related TS issue: https://github.com/microsoft/TypeScript/issues/18757

**Comment by benlesh** [comment]
We probably shouldn't do this for now... this PR in TypeScript is of interest: https://github.com/microsoft/TypeScript/pull/41660
