### ISSUE TITLE
alternative to finalize for detecting ONLY unsubscription?

### ISSUE THREAD

**Issue by arnotes** [ReactiveX/rxjs#6026]
hello guys.
im looking for an alternative to finalize() operator.
i need something that says "do something if observable is not complete, did not die from error but was unsubscribed"
something that sounds like `.pipe(tapWhenUnsubscribed(x => console.log('i got unsubscribed')))`

**Comment by josepot** [comment]
What about:?

```ts
const tapWhenUnsubscribed = <T>(source$: Observable<T>) => (
  fn: (x: T) => void
) =>
  new Observable<T>(observer => {
    let closedFromSource = false;
    const subscription = source$.subscribe(
      x => {
        observer.next(x);
      },
      e => {
        closedFromSource = true;
        observer.error(e);
      },
      () => {
        closedFromSource = true;
        observer.complete();
      }
    );

    return () => {
      if (!closedFromSource) fn();
      subscription.unsubscribe();
    };
  });
```

**Comment by arnotes** [comment]
thanks! i can definitely make use of this.

**Comment by martinsik** [comment]
@arnotes Also see this https://github.com/ReactiveX/rxjs/issues/2823. You're not the first one asking for this feature :).
