### ISSUE TITLE
`throttle` operator throws error `RangeError: Maximum call stack size exceeded`

### ISSUE THREAD

**Issue by OliverJAsh** [ReactiveX/rxjs#6034]
**RxJS version:**
6.6.3 (latest at time of writing)

**Code to reproduce:**

https://stackblitz.com/edit/rxjs-compat-ywrxqr

```ts
import * as Rx from "rxjs";
import { throttle } from "rxjs/operators";

const source = Rx.of(1).pipe(
  throttle(() => Rx.EMPTY, { leading: false, trailing: true })
);

source.subscribe(x => console.log(x));
```

**Expected behavior:**
It logs `1` once.

**Actual behavior:**
It logs `1` many times and then errors with `RangeError: Maximum call stack size exceeded`.

![image](https://user-images.githubusercontent.com/921609/108502200-54f0b500-72aa-11eb-9d24-3d1f1ce1e77a.png)

**Additional information:**

The reduced test case is a bit contrived. In practice my duration selector has a bit more logic:

```ts
throttle(n => n === 10 ? Rx.timer(100) : Rx.EMPTY, { leading: false, trailing: true })
```

**Comment by OliverJAsh** [comment]
I was hoping I could workaround it like so:

```diff
-throttle(() => Rx.EMPTY, { leading: false, trailing: true })
+throttle(() => Rx.scheduled(Rx.EMPTY, Rx.async), { leading: false, trailing: true })
```

… so it completes asynchronously rather than synchronously. However IIUC this doesn't work because of another bug with `throttle`: https://github.com/ReactiveX/rxjs/issues/5732.

**Comment by OliverJAsh** [comment]
Note this issue only occurs when `trailing: true`. Example that uses `trailing: false`: https://stackblitz.com/edit/rxjs-compat-mygu4y.

**Comment by OliverJAsh** [comment]
In RxJS v7 beta, the behaviour is different but still incorrect (at least in my mind): https://stackblitz.com/edit/rxjs-compat-mmjf6c. This never logs anything.

**Comment by josepot** [comment]
> In RxJS v7 beta, the behaviour is different but still incorrect (at least in my mind): https://stackblitz.com/edit/rxjs-compat-mmjf6c. This never logs anything.

That's the behavior that I would expect: given the fact that `leading` is set to `false` and that the source is a sync observable that emits once and completes in the same tick.

What's the behavior that you were expecting?

**Comment by OliverJAsh** [comment]
My understanding was that if `trailing` is set to `true`, the throttled Observable should always emit the last value that the source emitted before completion.

https://github.com/ReactiveX/rxjs/issues/5732

**Comment by josepot** [comment]
> My understanding was that if `trailing` is set to `true`, the throttled Observable should always emit the last value that the source emitted before completion.
> 
> #5732

I could be completely wrong, of course, but I would expect from `trailing` set to `true` is for the resulting observable to emit the latest value that the source emitted while the `durationSelector` observable was "active". In the case of a sync observable that emits and completes synchronously, the `durationSelector` can't capture any values, so that's why that's what I would expect. Again, I could be completely wrong, of course. I'm just saying how I understood this operator.

**Comment by OliverJAsh** [comment]
Another weird discovery: in v7.0.0-beta.10 this doesn't throw an error but it does still log `1` over 1000 times.

```ts
import * as Rx from "rxjs";
import { throttle } from "rxjs/operators";

const source = Rx.of(1).pipe(
  throttle(() => Rx.of(1), { leading: false, trailing: true })
);

source.subscribe(x => console.log(x));
```

https://stackblitz.com/edit/rxjs-compat-vswz6n

---

> In RxJS v7 beta, the behaviour is different but still incorrect (at least in my mind): https://stackblitz.com/edit/rxjs-compat-mmjf6c. This never logs anything.

Ah, I believe this is because of this change: https://github.com/reactivex/rxjs/commit/4af022753d6dd4e94bcfcf0cc6082bb2312a3f02—in my example the duration selector never emits anything, it only completes. That makes sense.

**Comment by benlesh** [comment]
The original bug is fixed in 7.0.0.

However, the bug [reported here](https://github.com/ReactiveX/rxjs/issues/6034#issuecomment-782839412) is still outstanding.

It begs the question "why would anyone do this?" but it still needs to be fixed.

**Comment by benlesh** [comment]
Closing this, as it's fixed in 7. I'm uncertain that this needs fixed in 6, as it's sort of an edge case, but I'm happy to reopen it and take anyone's PR on the matter if they want to put in the time.

**Comment by benlesh** [comment]
Other issue is here: https://github.com/ReactiveX/rxjs/issues/6058
