### ISSUE TITLE
`ajax` regression in 7.0.0-beta.11: default `responseType` has changed from `'json'` to `''`

### ISSUE THREAD

**Issue by OliverJAsh** [ReactiveX/rxjs#6052]
## Bug Report

**Current Behavior**
https://github.com/ReactiveX/rxjs/commit/873e52d0d67b0f8470e6290c6fbc35c571464aaf#diff-700d20a43f740146f5a6f8544b7035b0d0a03d074d7fa1d551a9b44977effa1fL318-R323

- 7.0.0-beta.10: `responseType: 'json' as XMLHttpRequestResponseType,`
- 7.0.0-beta.11: `responseType: '' as XMLHttpRequestResponseType,`

Because of this change, my JSON responses are no longer parsed to JSON.

To workaround this I have to specify `responseType: 'json'` manually when calling `ajax`.

I believe this is not intended because it was not mentioned in the changelog as a known breaking change.

**Comment by benlesh** [comment]
It looks like this was missed because the test harness was incorrectly setting `responseType` on the XHR mock during the return. That doesn't happen in the real XHR.
