### ISSUE TITLE
ajax.getJSON returns a string instead of an object.

### ISSUE THREAD

**Issue by vuolen** [ReactiveX/rxjs#6061]
## Bug Report

**Current Behavior**
A request with ajax.getJSON returns a value of type string.

**Expected behavior**
I expected to receive an object.

**Reproduction**

https://codesandbox.io/s/rxjs-playground-forked-l0z1f?file=/src/index.js

**Environment**
- RxJS version: 7.0.0-beta.11

You can change the version in CodeSandbox on the panel to the left and see that this is unique to the latest version.

**Comment by benlesh** [comment]
This is fixed in #6056
