### ISSUE TITLE
Expand test coverage for base / utility implementations?

### ISSUE THREAD

**Issue by kwonoj** [ReactiveX/RxJS#607]
Now test coverage reflects actual source code's test coverage shows most of operator implementation is being covered. Most of 'missing' coverage comes from underlying base, or utility function implementations such as `src\util\*` - Is it recommended to create test cases over it? It'll be pretty much basic test cases for functionality though.

**Comment by staltz** [comment]
I'd say yes. That's just unit tests.

**Comment by kwonoj** [comment]
Personally I thought so too, reason to create issue to get some agreement :)

**Comment by blesh** [comment]
I agree 100%. I was thinking about just this. The Scheduling types are also woefully under-tested last I looked as well.

**Comment by blesh** [comment]
As this is such a generic issue. I'm closing it. Ideally more specific issues will be filed around specific types that need more testing.
