### ISSUE TITLE
BehaviorSubject Value Indirectly Changed By Array.from

### ISSUE THREAD

**Issue by Fallenstedt** [ReactiveX/rxjs#6078]
## Bug Report

**Current Behavior**
* Obtaining the value from a BehaviorSubject the first time retrieves the value. The second attempt shows no value

**Expected behavior**
* Every time I get the value from a BehaviorSubject, it should be there

**Reproduction**
* Here is a reproduction. I am logging out the values of a JS Map, and the BehaviorSubject, twice. The logs show the Map's values are not affected, but the BehaviorSubject's value is. 

- REPL or Repo link:

https://stackblitz.com/edit/what-the-fuck-2?file=index.ts

```js
import { of } from "rxjs";
import { BehaviorSubject, Observable } from "rxjs";

/**
 * Observable Cache can publish new values to subscribers
 * when an item is set, deleted or when the cache is cleares.
 */
class ObservableCache<Key extends string | Symbol, Value> {
  private readonly cache = new Map<Key, Value>();
  private readonly valuesSubject = new BehaviorSubject<IterableIterator<Value>>(
    this.cache.values()
  );
  public readonly values: Observable<
    IterableIterator<Value>
  > = this.valuesSubject.asObservable();

  public set(key: Key, value: Value): void {
    this.cache.set(key, value);
    this.publish();
  }

  public has(key: Key): boolean {
    return this.cache.has(key);
  }

  public size() {
    return this.cache.size;
  }

  public __debugValues() {
    console.log(
      "Array From BehaviorSubject Value",
      Array.from(this.valuesSubject.value)
    );
    console.log("Array From Cache Values", Array.from(this.cache.values()));
  }

  private publish(): void {
    this.valuesSubject.next(this.cache.values());
  }
}

// BUILD CACHE
const cache = new ObservableCache<
  string,
  { i: string; element: Observable<string>; started: Observable<string> }
>();

// FILL CACHE
const video = {
  i: "1",
  element: of("element1"),
  started: of("started1")
};

const video2 = {
  i: "2",
  element: of("element2"),
  started: of("started2")
};
cache.set(video.i, video);
cache.set(video2.i, video2);

cache.__debugValues();
cache.__debugValues();

```

**Environment**
- Runtime: All Browsers
- RxJS version: 6.62

**Additional context/Screenshots**
Is the Array.from somehow manipulating the BehaviorSubject's value indirectly?

**Comment by kwonoj** [comment]
You emit `values()` which returns iterator https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/values, and iterator should change when you iterate, i.e `Array.from`.

**Comment by Fallenstedt** [comment]
❤️  Now I see what is happening. Sheesh. Thank you @kwonoj . Wrapping the call to values in a function produces the expected behavior. https://stackblitz.com/edit/what-the-fuck?file=index.ts
