### ISSUE TITLE
Update type declarations in codebase

### ISSUE THREAD

**Issue by kwonoj** [ReactiveX/RxJS#608]
Such as PR https://github.com/ReactiveX/RxJS/pull/585, https://github.com/ReactiveX/RxJS/pull/597, some of type declaration signature in codebase need to be checked & revised if required.

**Comment by kwonoj** [comment]
`repeat` also need to be updated, does not have default value for parameter.

![image](https://cloud.githubusercontent.com/assets/1210596/10953635/ea3bc228-82fd-11e5-8418-119170200f8b.png)

**Comment by blesh** [comment]
Since this is such a generic issue, I'm going to close it for now. Ideally, we'll find more specific issues around typing and file them individually for specific files or something. "Update types in the whole library" isn't something easily resolved in a few commits.
