### ISSUE TITLE
This is bad and not good: omitting an error in ONE subscriber affects OTHER subscxribers

### ISSUE THREAD

**Issue by bingomanatee** [ReactiveX/rxjs#6104]
If you fail to subscribe to errors in one subscriber the error in a subject is thrown.

I DO NOT AGREE THAT THIS IS GOOD OR EXPECTED BEHAVIOR. 

Streams aren't expected to leak errors into the general flow and listening is not a thing people expect to change this fact. the error method is supposed to catch and report errors not scream them up the stack. 

BUT EVEN IF YOU THINK THIS IS TRUE

OTHER subscribers even if they DO catch errors may be taken down and NOT get error signals because ONE subscriber f'd up and forgot to listen to errors. 

AGAIN this is not a good thing and adds to the sense that RXJS is a thing with a huge learning curve and is too dangerous to use with novice developers.

**Comment by cartant** [comment]
Closing this because no attempt was made to follow the issue template.

Regarding the behaviour: see https://github.com/ReactiveX/rxjs/blob/9e9064b7513aec4c365e792beac211f9d12bd7b9/docs_app/content/guide/glossary-and-semantics.md#producer-interference and https://youtu.be/JCXZhe6KsxQ?t=321
