### ISSUE TITLE
Ensure signatures with `thisArg` or `source` observable are deprecated in predicates and projection functions

### ISSUE THREAD

**Issue by benlesh** [ReactiveX/rxjs#6143]
Just what it says. `filter(fn, obj)` is more readable as `filter(fn.bind(obj))`, because the former doesn't really tell us what `obj` is for. This exists in various parts of the library. We also have signatures where the `source` observable is provided in the predicate. That is supremely silly, as I can't even think of a use case there, and a simple closure would have worked (for example, `every` has both an `thisArg` and a `source`).

**Comment by OliverJAsh** [comment]
+100. I just shipped a bug to production because I accidentally passed an operator as `thisArg`. Very easy mistake to make:

```ts
import { Observable } from 'rxjs';
import { map, shareReplay } from 'rxjs/operators';

declare const ob$: Observable<number>;
// Oops, shareReplay is in the wrong place:
ob$.pipe(map((x) => x + 1, shareReplay()));
// Should have been:
ob$.pipe(map((x) => x + 1), shareReplay());
```

**Comment by benlesh** [comment]
Core team approval.
