### ISSUE TITLE
v7: `ajax`: include progress events in return type

### ISSUE THREAD

**Issue by OliverJAsh** [ReactiveX/rxjs#6145]
## Bug Report

**Current Behavior**
Extracted from PR comment: https://github.com/ReactiveX/rxjs/pull/6001#discussion_r582870259

```ts
import { ajax } from 'rxjs/ajax';

// Expected return type: Observable<AjaxUploadProgressEvents | AjaxDownloadCompleteEvent | AjaxResponse<T>>
// Actual return type: Observable<AjaxResponse<unknown>>
const ob$ = ajax({
    method: 'POST',
    url: 'https://httpbin.org/post',
    includeUploadProgress: true,
});

ob$.subscribe(value => {
    // Expected type: AjaxUploadProgressEvents | AjaxDownloadCompleteEvent | AjaxResponse<T>
    // Actual type: AjaxResponse<unknown>
    value;
})
```

**Expected behavior**
See comments in code above.

**Reproduction**
See above.

**Comment by cartant** [comment]
@benlesh Beyond the `includeUploadProgress`-related types, there are types mentioned in the docs that don't exist (`AjaxProgressEvents` and `AjaxDownloadCompleteEvent`):

https://github.com/ReactiveX/rxjs/blob/105bf99d27144a24100b211116af1341c5263738/src/internal/ajax/types.ts#L181-L188

and the docs for `includeUploadProgress` mention download events, etc.:

https://github.com/ReactiveX/rxjs/blob/105bf99d27144a24100b211116af1341c5263738/src/internal/ajax/types.ts#L190-L197

**Comment by benlesh** [comment]
This merged PR is related: https://github.com/ReactiveX/rxjs/pull/6233

**Comment by cartant** [comment]
AFAICT, the consumer always receives an `AjaxResponse` and the `type` of the response can be inspected to see whether it's a progress event or whatever.

https://github.com/ReactiveX/rxjs/blob/6ef272508ce50894705845c8b1d65ce9491d4b7e/src/internal/ajax/ajax.ts#L409-L417

https://github.com/ReactiveX/rxjs/blob/6ef272508ce50894705845c8b1d65ce9491d4b7e/src/internal/ajax/AjaxResponse.ts#L80-L93

However, I've ascertained this by reading the code. The `ajax` observable is something that I've not used in a long while. I'm guessing this can be closed now?

**Comment by OliverJAsh** [comment]
Ah, this comment is what lead me to believe the observable could emit types other than `AjaxResponse`.

https://github.com/ReactiveX/rxjs/pull/6001/files#diff-3345eb17e0a6c80853bd0dfb6dd88d6775cc0dac8c5a4bd4d7113942db4ddfa6R191-R195

It looks like that comment has since been updated: https://github.com/ReactiveX/rxjs/commit/40206e52aba4977cb552c278fa9e056bc064c9be#diff-3345eb17e0a6c80853bd0dfb6dd88d6775cc0dac8c5a4bd4d7113942db4ddfa6L182

I'll close this 😄
