### ISSUE TITLE
withLatestFrom operator freezes on highload

### ISSUE THREAD

**Issue by Asondo** [ReactiveX/rxjs#6150]
## Bug Report

**Current Behavior**
Abstract case using nestjs controller: 
```
const user$ = this.grpcUserService.getUser(params);

return user$.pipe(
    mergeMap(user => this.grpcDeviceService.getUserDevice(user)),
    withLatestFrom(user$),
    mergeMap(([device, user]) => this.generateAuthToken(user, device)),
);
```

Such code works ok on unit & integrational tests, when we manually use this method from frontend, BUT when we start to load this method with jmeter the method freezes in 20% of requests. In logs I found, that all freezes is while withLatestFrom, it is not return any value sometimes. After I remove this operator and start to use local variable with `tap` operator to presave user value the freezes are gone. So, the problem is exactly in withLatestFrom operator and it is very difficult to reproduce this behavior, because in most of cases it works ok.

**Expected behavior**
No freezes

**Reproduction**
Try to write some code using withLatestFrom to use previously requested value in rx chain & then try to ddos this method with jmeter.

P.S. using ghz tool cause freezes only when we load service via envoy server, may be the reason is that not enough load produces, I really don't know.

So, currently we decided to replace all withLatestFrom operators with alternatives like tap with local variable.

**Comment by josepot** [comment]
> In logs I found, that all freezes is while withLatestFrom, it is not return any value sometimes.

That's probably because the way that the `user$` observable behaves when it has 2 different subscribers. It's hard to say without knowing what `getUser` returns... One thing that could be happening is that `getUser` returns a cold observable, and then the side-effect is being triggered twice and one subscriber receives the value before the other one... Again, it's hard to say without knowing more about the `user$` observable.

Although, there is no need for using `withLatestFrom`, you could do this instead:

```ts
return user$.pipe(
  mergeMap(user =>
    this.grpcDeviceService
      .getUserDevice(user)
      .pipe(map(device => [device, user]))
  ),
  mergeMap(([device, user]) => this.generateAuthToken(user, device))
);
```

Or if `getUserDevice` returns a Promise, then:

```ts
return user$.pipe(
  mergeMap(user =>
    this.grpcDeviceService.getUserDevice(user).then(device => [device, user])
  ),
  mergeMap(([device, user]) => this.generateAuthToken(user, device))
);
```

**Comment by Asondo** [comment]
We're using withLatestFrom only in cases, where we want to make code more simple, readable & beatiful, more flat, without any kind of pipe-hell. So, as I see, we shouldn't use withLatestFrom now, because we cannot predict its behavior in different situations & it is not a bug, but some kind of strange feature)

Now I do it this way:
```
let insecureUser: InsecureUser;

return user$.pipe(
  tap(user => {
    insecureUser = user;
  }),
  ... and so on
);
```
