### ISSUE TITLE
Fix Disposal Behavior - Generators No Longer Supported

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#62]
Currently, in `master` the disposal behavior meets the older ES7 Observable spec proposal, so it triggers `return` (aka completed) when `subscription.dispose()` is called. This is so Observable could support a primed Generator as an Observer to subscribe.

This needs to be removed as it's no longer supported by the ES7 Observable spec. Again, this spec is settling down, but more importantly so is this library.  The plan is to change the behavior back to the good ol' RxJS 2 -esque behavior we know and love; Where `dispose()`-ing a subscription does not trigger the completed handler.

All references to the `disposeHandler` in Observer will also be removed.

**Comment by BerkeleyTrue** [comment]
I'm glad this project and the proposal are sticking to expect rxjs 2.0.0 behavior. Generators and zalgo behavior fixes felt goofy and forced (dare I say, unnatural!).

**Comment by blesh** [comment]
This is done in master now due to #68
