### ISSUE TITLE
Confusion with `.subscribe()` deprecation notes

### ISSUE THREAD

**Issue by beck** [ReactiveX/rxjs#6225]
[subscribe-arguments.md](https://github.com/ReactiveX/rxjs/blob/6fa819beb91ba99dadd6262d6c13f7ddfd9470c5/docs_app/content/deprecations/subscribe-arguments.md) says:

```js
// deprecated
of([1,2,3]).subscribe(null, null, console.info); // difficult to read
// suggested change
of([1,2,3]).subscribe({complete: console.info});
```

My interpretation is that these are equivalent calls.

Anecdotally that does not seem to be the case (at least, not with EMPTY):

```js
// complete is called
EMPTY.subscribe({
  complete: () => console.info("Complete!")
});

// nothing called
EMPTY.subscribe(null, null, () => console.info("Complete!"));
```

It seems as though `.subscribe` does not unpack the first arg as kwargs but instead accepts it as a NextObserver.

I'm sure I'm confused somehow?

**Comment by voliva** [comment]
To me it works with both overloads: https://stackblitz.com/edit/rxjs-t7syfq for both rxjs@latest and rxjs@next

**Comment by beck** [comment]
@voliva my mistake. Trying again with contemporary versions and am seeing the same.
Thank you.
