### ISSUE TITLE
Export all core APIs from `rxjs` module directly.

### ISSUE THREAD

**Issue by benlesh** [ReactiveX/rxjs#6242]
Given the issue #6067 seems to be fairly difficult to solve, and given that we have renamed everything such that there are no conflicts between things like `concat` the creation function, and `concat` the operator, etc. Maybe it's time we talk about exporting all primary APIs from `rxjs` proper.

1. It's a non-breaking change.
2. It's the direction we've all discussed going _many_ times.
3. It's easier to deal with, overall.

I'm talking about:

```ts
import { of, interval, take, concatWith, map } from 'rxjs';

interval(1000).pipe(
  take(3),
  concatWith(of('done')),
  map(x => `Tick: ${x}`)
)
```

**Comment by benlesh** [comment]
Oh, and to be clear, I'm not talking about `rxjs/ajax` or `rxjs/fetch` or `rxjs/webSocket` or `rxjs/testing`. Overtime maybe those should be their own modules I'm not sure. For now, though, I wouldn't include them in this. I'm just talking about creation functions, subjects, operators, and schedulers.

**Comment by benlesh** [comment]
@kolodny we'd only move the newer name of the `concat` operator, which is `concatWith`.

**Comment by LayZeeDK** [comment]
Any notable effect on tree-shaking or overall TypeScript compilation speed?

**Comment by benlesh** [comment]
Core Team Meeting: General core team approval

**Comment by tmair** [comment]
Just as a side note. This change could also enable the use of [API Extractor](https://api-extractor.com/) at least for the `rxjs` import location. The tool might help to automate detection of changes to the API surface of the library.
