### ISSUE TITLE
RxJS 7: ReadableStream from fetch not compatible with current type signature

### ISSUE THREAD

**Issue by benlesh** [ReactiveX/rxjs#6290]
See the following screenshot from [this StackBlitz](https://stackblitz.com/edit/gptqgq?file=index.ts)

![image](https://user-images.githubusercontent.com/1540597/116588443-311ca180-a8e1-11eb-842e-e806beb39bc7.png)

**Comment by benlesh** [comment]
This *might* have something to do with the version of TypeScript that StackBlitz is using. I'm trying to find out. cc @ericsimons

**Comment by benlesh** [comment]
I can't validate this anywhere else. I think it has something to do with StackBlitz.

**Comment by cartant** [comment]
Yeah, I'm closing this as it's a TypeScript version issue.

In TypeScript 4.1, the `ReadableStream` interface looks like this:

```ts
interface ReadableStream<R = any> {
    readonly locked: boolean;
    cancel(reason?: any): Promise<void>;
    getReader(options: { mode: "byob" }): ReadableStreamBYOBReader;
    getReader(): ReadableStreamDefaultReader<R>;
    pipeThrough<T>( // ...
```

And in 4.2 it looks like this:

```ts
interface ReadableStream<R = any> {
    readonly locked: boolean;
    cancel(reason?: any): Promise<void>;
    getReader(): ReadableStreamDefaultReader<R>;
    pipeThrough<T>( // ...
```

Note the `getReader` difference. Our minimum-supported TS version is 4.2, so this isn't an issue that we need to resolve.
