### ISSUE TITLE
v7 breaking changes guide is missing notes about `debounce`

### ISSUE THREAD

**Issue by OliverJAsh** [ReactiveX/rxjs#6298]
The changelog describes a breaking change to `debounce` but this is not mentioned [in the guide](https://rxjs.dev/deprecations/breaking-changes).

https://github.com/ReactiveX/rxjs/blob/master/CHANGELOG.md#:~:text=debounce%3A%20the%20observable%20returned%20by%20the%20debounce%20

> debounce: the observable returned by the debounce operator's duration selector must emit a next notification to end the duration. Complete notifications no longer end the duration.

This broke our application in a non-trivial way so I think it's worth mentioning in the guide. WDYT?

**Comment by cartant** [comment]
Yes. That's an oversight. And it's not just that operator. All notifiers now have to emit a next notification.

**Comment by cartant** [comment]
I've opened two PRs that bring _all_ of the v7 breaking changes listed in the CHANGELOG into the summary document. Thanks for opening the issue.
