### ISSUE TITLE
"export 'Unsubscribable' was not found in 'rxjs'

### ISSUE THREAD

**Issue by blueiceprj** [ReactiveX/rxjs#6304]
## Bug Report

**Current Behavior**
"export 'Unsubscribable' was not found in 'rxjs'

**Expected behavior**

This interface will be exported

**Reproduction**

** Please provide repro code does not involves framework, or other setups to address this bug is specific to rxjs core **

**Environment**
- Runtime: [e.g. Node v${16}, Chrome v${90.xxx}]
- RxJS version: 7.0.0
- Angular 11.2.XXX

**Possible Solution**
Add to index.ts file

**Additional context/Screenshots**

**Comment by jakovljevic-mladen** [comment]
This seems to be working fine. Please check [this example](https://stackblitz.com/edit/kj6lfq?file=index.ts). Closing for now. If you think that this issue still exists, please open a new issue or leave a comment here.
