### ISSUE TITLE
rxjs 7.0.0 has error

### ISSUE THREAD

**Issue by xp44mm** [ReactiveX/rxjs#6315]
when i upgrade rxjs 7.0.0, use webpack has error:

WARNING in ./node_modules/rxjs/dist/esm5/internal/Subscriber.js 122:34-47
export '__spreadArray' (imported as '__spreadArray') was not found in 'tslib'
....

and have a lot of  error same as above. Although it is a warning, the program does not execute correctly and will be interrupted.

change rxjs version back to 6.6.7 the work properly again. my code too much to ditermine where is the problem.

**Comment by cartant** [comment]
Needs a minimal reproduction, as `__spreadArray` is definitely exported the version of `tslib` in this package's `package.json`:

https://github.com/ReactiveX/rxjs/blob/4dda357319a175ab1461f42bd080ef2d136bc665/package.json#L129-L131

https://github.com/microsoft/tslib/blob/2.1.0/tslib.js#L206-L210

**Comment by xp44mm** [comment]
i search in website, and found this : https://github.com/microsoft/tslib/issues/149

**Comment by cartant** [comment]
That issue has no reproduction either, so if anything is to be done about here, one will need to be provided.

In any case, it's clear that the export was added in the version of `tslib` upon which this package depends: https://github.com/microsoft/tslib/releases/tag/2.1.0

**Comment by xp44mm** [comment]
a reproduction: https://github.com/xp44mm/hyperscript-rxjs-test

just execute `npm start` on both 6.6.7 and 7.0.0 of rxjs.

**Comment by cartant** [comment]
Please provide a repro that does not contain packages published from what appears to be a private repo. This is on npm, but the GitHub projects are private:

https://www.npmjs.com/package/hyperscript-rxjs

I won't be installing it. Please provide a minimal repro that uses only well-known **open-source** packages.

**Comment by cartant** [comment]
FWIW, I've tweaked a small CRA-based harness that I have on this notebook to use RxJS 7.0.0 and have confirmed that it is installed with `tslib` 2.1.0 and - when type checked with TypeScript 4.2.4 and compiled with `react-scripts` 3.4.1 - it works fine. That leads me to believe that any problem is specific to your build process or to the tool versions used in said process. I don't believe that there is a problem that can be addressed here, in RxJS.

**Comment by xp44mm** [comment]
I'm using pure **js** instead of **ts**, I've added dependency packages `tslib` into package.json, and the problem is solved.

**Comment by cartant** [comment]
It's something with your configuration. CRA builds using Babel, not TypeScript. It should not be necessary to add `tslib` when it's added as an RxJS dependency.
