### ISSUE TITLE
Codesandbox: "Cannot find module 'rxjs'"

### ISSUE THREAD

**Issue by josepot** [ReactiveX/rxjs#6320]
## Bug Report

**Current Behavior**
When creating a new Sandbox on codesandbox.io, while using the latest Vanilla TS template (which uses `typescript@4.2.3`) I'm unable to import anything from `rxjs` because I get the following error: 

> Cannot find module 'rxjs' or its corresponding type declarations.ts(2307)

I guess that there must be a setting on the tsconfig that needs to be setup, but I can't find any mention to that on the [docs of the breaking changes](https://rxjs-dev.firebaseapp.com/deprecations/breaking-changes).

**Reproduction**

https://codesandbox.io/s/dawn-glitter-s1rdb?file=/src/index.ts

**Environment**
- RxJS version: 7.0.0

**Additional context/Screenshots**

`rxjs@7.0.0-rc.3` doesn't have this issue.

**Comment by cartant** [comment]
> I guess that there must be a setting on the tsconfig that needs to be setup

If 7.0.0-rc.3 doesn't have the problem, I doubt it.

https://github.com/ReactiveX/rxjs/compare/7.0.0-rc.3...7.0.0

My bet is that it's another problem that relates to: https://github.com/ReactiveX/rxjs/pull/6276

**Comment by josepot** [comment]
I'm closing this, because it's the same as #6350
