### ISSUE TITLE
`debounceTime` does not emit with `jasmine.clock.tick` in v7

### ISSUE THREAD

**Issue by dpurp** [ReactiveX/rxjs#6382]
## Bug Report
\cc @leggechr 

**Current Behavior**
In v7, `debounceTime` does not emit any values when installing the jasmine clock and using `tick`. (This works in v6)

**Expected behavior**
rxjs is compatible with jasmine.clock, or there is a documented workaround.

**Reproduction**
Note the reproductions below contain examples using the jasmine clock (which fails in v7) and the native clock (which succeeds).

v7: https://stackblitz.com/edit/rxjs-v7-debouncetime?file=test.ts
v6: https://stackblitz.com/edit/rxjs-v6-debouncetime?file=test.ts

```ts
describe('failing time tests with jasmine clock', () => {
  beforeEach(() => {
    jasmine.clock().install();
  });

  afterEach(() => {
    jasmine.clock().uninstall();
  });

  it('debounces time', async () => {
    const duration = 10;
    const source = new Subject<string>();
    const debouncedSource$ = source.pipe(
      debounceTime(duration),
      shareReplay(1)
    );
    debouncedSource$.subscribe();

    source.next('should not be emitted');
    source.next('expected value');
    jasmine.clock().tick(duration + 1); // Wait for debounce to happen.

    expect(await firstValueFrom(debouncedSource$)).toEqual('expected value');
  });
});
```

**Comment by cartant** [comment]
Thanks. This is a bug - 'cause it's an inadvertent breaking change - as `setInterval` is captured in the interval provider:

https://github.com/ReactiveX/rxjs/blob/53ef49459b03819022c2c81e57650c1cdc42fedc/src/internal/scheduler/intervalProvider.ts#L18-L25

Instead, the provider should obtain the `setInterval` and `clearInterval` functions via `globalThis`.

**Comment by cartant** [comment]
Nope. That's not the problem. The `debounceTime` implementation now uses the scheduler's `now` function:

https://github.com/ReactiveX/rxjs/blob/53ef49459b03819022c2c81e57650c1cdc42fedc/src/internal/operators/debounceTime.ts#L84-L86

and

https://github.com/ReactiveX/rxjs/blob/53ef49459b03819022c2c81e57650c1cdc42fedc/src/internal/operators/debounceTime.ts#L99-L100

So the issue is that Jasmine purports to mock the clock, but it does not patch `Date.now`.

@benlesh

**Comment by cartant** [comment]
Apparently, Jasmine now has a [`mockDate` method](https://jasmine.github.io/api/edge/Clock.html#mockDate):

```ts
beforeEach(() => {
  jasmine.clock().install()
  jasmine.clock().mockDate();
});
```

Calling that resolves the issue.

**Comment by benlesh** [comment]
Ugh. Jasmine. There's a reason we stopped using it on this project. Haha.

**Comment by dpurp** [comment]
Thanks for figuring this out for me. I confirmed it worked on a subset of tests and am rolling out the fix to the rest of the codebase.

**Comment by matheo** [comment]
@benlesh the operator is broken in `jest` too?
something can be done over here to fix the failing tests please?

**Comment by ortegamarcel** [comment]
@matheo @avast-ye found a work around for it: change `debounceTime(x)` to `debounce(() => interval(x))`. 

You can also mock it inside your tests:

```typescript
import { interval } from 'rxjs';
import { debounce } from 'rxjs/operators';
import * as rxjsOperators from 'rxjs/operators';

// inside beforeEach
jest.spyOn(rxjsOperators, 'debounceTime').mockImplementation((timeout) => debounce(() => interval(timeout)));
```

Found [here](https://github.com/angular/angular/issues/44351).

**Comment by villanuevadani** [comment]
Hey @AntonioEduardo1998 @ortegamarcel , thank you a lot for these ideas! Do you know if there is any recent approach that is able as well to use fakeAsync with `debounceTime` or something?
