### ISSUE TITLE
`subscribe` should be synchronous

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#64]
Based on discussions on the [es-observable spec repo](/zenparsing/es-observable), it's been collectively determined that subscription and observation *must* be synchronous by default for performance reasons.

One of the lead examples was `groupBy`, as pointed out by @trxcllnt... if subscription is always async, you'll potentially have to buffer an unbounded number of values that could be synchronously pushed at newly created "Grouped" Observables.

There's also a smaller matter of incurring extra turns for no real gain if this functional programming type is being used purely functionally.

The danger here is to those that are using mutable state and imperative programming. In those situations, there might be some strange behaviors. It is my view that this should simply be taught to people via warnings and best practices.

**Comment by blesh** [comment]
cc/ @vsavkin @jeffbcross @igorminar

FWIW: For concerns about Zalgo when creating a library such as Angular's data access, the library implementor could use `subscribeOn` on any observable it returns from itself in order to force an async subscription behavior without effecting the ergonomics for the end user developer.

**Comment by headinthebox** [comment]
That is why `subscribeOn` and `observeOn` exist!

**Comment by BerkeleyTrue** [comment]
Yay! That makes my life easier.

**Comment by blesh** [comment]
Done in master.
