### ISSUE TITLE
Discuss open source fund raising

### ISSUE THREAD

**Issue by benlesh** [ReactiveX/rxjs#6402]
Since this has been "in the news" for tech twitter recently, I'd like to discuss this at the core team meeting.

What I'm okay with using this for:

1. Getting the core team together in the same physical location once a year
2. Swag purchases for giveaways or just for core team members, etc.

What I'm _not_ okay with using this for:

1. Paying individuals.
2. Conference travel. (conferences should be paying for this)
3. Pretty much anything where it's benefitting a single person more than the group.

If we had a surplus, which is extraordinarily doubtful, I think we could give the remainder to charity or something.

Possible sources for this are basically just from donations. Which, I'm sure would be generally so small that maybe this is a non-issue.

Posting this as an issue, so I can make it an agenda item.

**Comment by kwonoj** [comment]
1. I suggest lock conversation to internalize this for core team discussion.
2. This was brought before and we have opencollective account even. But at the moment the majority of members agreed we don't have explicit usage even if we get sponsor / funding, while it potentially makes harder for project management perspective. I still stand on this.
3. For me, suggested usecase 1/2 seems pretty thin and for those (or other arbitary purpose) I don't see good benefit to get external funding. Even more, I am bit in doubt if we could have amount of funds to use.

4. Slightly derailing topic, in my opinion OSS-approved non-funding support (i.e tooling have oss license / discount, some CI for OSS - we had saucelabs for this - ) are more valuable in terms of our team size or more some organizational help or vice versa. Not sure direct funding is something we want even - that's reason we discussed this back in the days and arrived 2.
