### ISSUE TITLE
Proposal: `singleUse` operator on ConnectableObservable

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#644]
This is related to #453 ... the idea is to provide an operator for backward compatibility.

```js
const myObs = source.share().singleUse(); 
myObs.repeat(100).subscribe(::console.log);  // will only run once, no errors.
```

This way people can "opt-in" to the RxJS 4 behavior around `share`, `shareReplay` and `shareBehavior`. Even better, the behavior is explicit. There's no question as to why the observable can't be replayed or retried.

cc/ @staltz @trxcllnt

**Comment by staltz** [comment]
How about `recycleable()`. Opt-out instead of opt-in.

**Comment by blesh** [comment]
I'm not a fan of leaving the behavior the way it is in RxJS 4... It was an apparent oversight from a long time ago, and other than "backwards compatibility", which isn't a compelling argument for this particular library, I haven't seen any major reasons it should stay the way it was.

**Comment by blesh** [comment]
I think you should have to opt-in to any behavior that breaks `retry` and `repeat` for Observable.

**Comment by trxcllnt** [comment]
@blesh why not `shareOnce`, `shareReplayOnce` etc.? I'm primarily concerned that `singleUse` would require us to return something other than an Observable or ConnectableObservable

**Comment by mattpodwysocki** [comment]
I'm with @staltz here that it should be opt-out instead of opt-in.  After all, RxJS v4.1 will already have shims in place for unsubscribe being an alias for dispose, etc

**Comment by blesh** [comment]
I actually like the other proposal here better:

https://github.com/ReactiveX/RxJS/issues/453#issuecomment-153806139

I'm closing this one for now, to see how that proposal goes over.

**Comment by staltz** [comment]
`shareOnce` / `shareReplayOnce` sounds great actually, but nevermind, issue solved anyway.
