### ISSUE TITLE
Could not find a declaration file for module 'rxjs'

### ISSUE THREAD

**Issue by eliasm307** [ReactiveX/rxjs#6455]
## Bug Report

**Current Behavior**
Trying to build a Typescript project that uses Rxjs and I get the following error:
![image](https://user-images.githubusercontent.com/13420359/120911217-4e315680-c67d-11eb-9711-f821dd9c5f8f.png)

**Expected behavior**
Should build without type errors as these are built into the rxjs package.

**Reproduction**

Try to build a project that imports types from Rxjs

**Environment**
- Runtime:  Node v15.0.1
- RxJS version: 7.1.0 
- 
**Possible Solution**
What fixed it for me was to change [this line](https://github.com/ReactiveX/rxjs/blob/c90242c66ea9c0f2ed0e7f0f0d7dcd7cf011c694/package.json#L8)
![image](https://user-images.githubusercontent.com/13420359/120911296-3a3a2480-c67e-11eb-8322-59dfb658bc0e.png)

to

![image](https://user-images.githubusercontent.com/13420359/120911353-cc422d00-c67e-11eb-9ba9-a730c111ea5a.png)

ie: "types": "./dist/types/index.d.ts", 

I am not sure what the intent was but the index.d.ts referenced for the typings doesn't seem to exist and/or the "typesVersions" field doesn't seem to produce intended results if its meant to allow types to be specified by the package version.

**Comment by kwonoj** [comment]
What's the version of typescript you're using?
