### ISSUE TITLE
Can't create custom operator with the new operate function

### ISSUE THREAD

**Issue by akanass** [ReactiveX/rxjs#6459]
## Bug Report

**Current Behavior**
The new [operate](https://github.com/ReactiveX/rxjs/blob/master/src/internal/util/lift.ts) function is not exported so we can't create custom operator with the new way to do it.

**Expected behavior**
Export the `operate` function then we'll be allowed to use it to create custom operators.  Else we won't be able to create custom operators in the future as the old way is deprecated.

**Reproduction**

Try to create an operator with the `operate` function and you will see the typing doesn't exist.

**Environment**
- RxJS version: 7.1.0

**Comment by backbone87** [comment]
what do you mean by "the old way is deprecated"?

i know of 2 ways to create custom operators and afair none is deprecated:
- use existing operators combined with `pipe` (the function, not the method on Observable)
- by using `(source$) => new Observable((subscriber) => { /* subscribe to source$, process and forward to subscriber */ })`

`operate` is basically syntactical sugar around the latter (yes ok there is a little bit more going on behind the scenes)

see also https://rxjs.dev/guide/operators

**Comment by akanass** [comment]
@backbone87 The "old school" was to use `source.lift` function like this:

```ts
export function myOperator<T>(param: any): OperatorFunction<T, R> {
  return (source: Observable<T>) => <Observable<R>> source.lift(new MyOperator(param));
}

class MyOperator<R> implements Operator<T, R> {
  constructor(private _param: any) {}

  call(subscriber: Subscriber<R>, source: Observable<T>): any {
    return source.subscribe(new MySubscriber(subscriber, this._param));
  }
}

class MySubscriber<R> extends Subscriber<T> {
  constructor(destination: Subscriber<R>, private _param: any) {
    super(destination);
  }

  protected _next(result: R): void {
    this.destination.next();
  }
}
```

Now, if we are looking at the internal operators like [map](https://github.com/ReactiveX/rxjs/blob/master/src/internal/operators/map.ts#L46) by example, `operate` function is used and it's very helpful.

That's why I wanted to use this method as well instead of doing `new Observable` but it's pretty the same I agree.

**Comment by voliva** [comment]
I think that was the way operators were implemented internally - none of the documentation ever mentioned this way of building new operators.

A library made by one of the members (and also a main contributor) of rxjs where it exposes a collection of useful operators https://github.com/cartant/rxjs-etc also uses the regular `pipe` or `source => new Observable(...`.

The way I read it, `operate` is an internal function to help build the standard operators, it's not meant to be used externally. I guess you could raise this as a suggestion or question in github discussions, but IMO it's not a bug, but something that was designed as such.

**Comment by sod** [comment]
Looking at the source of `operate` and https://github.com/ReactiveX/rxjs/blob/master/src/internal/Observable.ts#L213-L239, it seems like `operate` only exists, so people that tapped into non-public internal implementation details, to not break it.

For custom operators, there seems to be no difference/downsides in just doing the `source => new Observable(...` way. So we kinda already got our `operate` function with rxjs@6.
