### ISSUE TITLE
"types" in package.json does not resolve to a file by default

### ISSUE THREAD

**Issue by orta** [ReactiveX/rxjs#6466]
## Bug Report

[7.1.0 Package JSON](https://www.unpkg.com/rxjs@7.1.0/package.json)

```
  "types": "index.d.ts",
  "typesVersions": {
    ">=4.2": {
      "*": [
        "dist/types/*"
      ]
    }
  },

```

Goes to [`index.d.ts`](https://www.unpkg.com/rxjs@7.1.0/index.d.ts) which doesn't exist.

**Current Behavior**
I haven't implemented the `typesVersion` resolving in the playground, and so it NOOPs ( https://github.com/microsoft/TypeScript-Website/issues/1316 ). Perhaps if you plan on supporting TS 4.2 and below you could use [downlevel-dts](https://github.com/sandersn/downlevel-dts).

**Comment by cartant** [comment]
The value used for the `types` property is what was recommended [here](https://github.com/microsoft/TypeScript/issues/43034#issuecomment-823423227). Also, there are no plans to support TypeScript versions below 4.2, as the types were massively refactored using recent TypeScript features.

**Comment by orta** [comment]
Ouch TIL'd - I guess the playground would need to support that resolution path too 👍🏻
