### ISSUE TITLE
IE9/IE10 - Observable's static methods are not defined on Subject

### ISSUE THREAD

**Issue by mlaval** [ReactiveX/RxJS#647]
It happens because IE9 and IE10 do not support [Object.setPrototypeOf](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Object/setPrototypeOf) which is used by Babel for [class inheritance](https://github.com/babel/babel/blob/8ab4a5df433accf65a127dfe357dae8ffd6f498b/packages/babel/src/transformation/templates/helper-inherits.js#L13). It seems to be a known limitation: https://github.com/babel/babel/issues/2450

Issue spotted thanks to https://github.com/angular/angular/issues/5072

**Comment by blesh** [comment]
@mlaval ... thanks for pointing this out.

**Comment by blesh** [comment]
cc/ @robwormald @jeffbcross

**Comment by mlaval** [comment]
If I'm correct, the only way is to manually copy the properties from `Observable` to `Subject`.
It could be done with some kind of util function. WDYT ?

**Comment by robwormald** [comment]
Does Typescript handle it properly? Maybe we could convince @blesh to let us add a dist/ts-cjs distro if it handles it properly :sob: - that would at least remove the need to manually copy the typings from es6 => cjs like we do now.

**Comment by blesh** [comment]
I'm starting to lean toward not using `export default` in any of our files, build everything solely with TSC. I think most CJS users on Node will import everything via `var Rx = require('@reactivex/rxjs')`, with little care about modularity, and we can come up with better distribution patterns to account for the operators.

**Comment by robwormald** [comment]
Let me know if you decide to do this, i have 14 hours on an airplane on saturday and this is the perfect kind of brain numbing repetitive task that will keep me sane. :+1: from me for that.

**Comment by robwormald** [comment]
Does this actually make sense, now that I think about it? The Angular2 API check is complaining about statics like `fromEvent` etc not showing up on Subject - the question is, *should* they?

Now that TS is doing the compilation, I only see "create" added as a static to Subject, which is (in hindsight) what I would expect. Once Rx releases a bump with TS build I can investigate further.

**Comment by blesh** [comment]
> the question is, should they?

No, `Subject.fromEvent` doesn't make any sense. I filed an issue with TypeScript (https://github.com/Microsoft/TypeScript/issues/4628) a while back about inheritance and statics complaining. I'm not sure what they're going to do about it. I totally understand the issue they're faced with, but it *is* crappy because it's a JavaScript idiom to have a static `create` methods on a class that are specific to that class and not it's super.

**Comment by trxcllnt** [comment]
`Subject.create` is specific to the Subject constructor, not Observable.

**Comment by blesh** [comment]
I don't think the original issue is an issue any longer. Closing for now. @mlaval please feel free to reopen if you're still having these issues with 5.0.0-beta.1.
