### ISSUE TITLE
Support absolute time on `Observable.timer`

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#648]
Just what it says. We should be supporting absolute time on Observable.timer in a similar fashion to RxJS 4.

**Comment by luisgabriel** [comment]
I can work on this one.

**Comment by kwonoj** [comment]
I just couple of minutes late than @luisgabriel to work on this ;)

**Comment by luisgabriel** [comment]
@kwonoj feel free to take this one then. I'm not sure how soon I'll be able to work on it. ;)

**Comment by kwonoj** [comment]
@luisgabriel no, it's completely ok. :)

**Comment by blesh** [comment]
Do you two need a tie breaker? Because I'll just do what I do with my kids and say @luisgabriel was "here first."

**Comment by kwonoj** [comment]
Took this one to close opened issues.
