### ISSUE TITLE
Could not find a declaration file for module 'rxjs

### ISSUE THREAD

**Issue by fookoo** [ReactiveX/rxjs#6480]
Version 7.10 seems to have problem with typescript

**RxJS version:**
7.10

**Code to reproduce:**
`import { Subject } from 'rxjs';
 const tmp = new Subject();`

**Expected behavior:**
To be working

**Actual behavior:**
 Could not find a declaration file for module 'rxjs'. 'node_modules/rxjs/dist/cjs/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/rxjs` if it exists or add a new declaration (.d.ts) file containing `declare module 'rxjs';`

**Additional information:**
The same code was working with 6.6.6 version

**Comment by kwonoj** [comment]
Please confirm typescript version: https://github.com/ReactiveX/rxjs/issues/6350

**Comment by kwonoj** [comment]
If you're experiencing issue with ts 4.2 and above, please provide reproducible repo.

**Comment by fookoo** [comment]
Ok, sorry, my global typescript was 4.2.4 but in project i had 4.1.3 let me update and see if it helps
