### ISSUE TITLE
debounce operator is not unsubscribing debounceSelector observable properly

### ISSUE THREAD

**Issue by ud1** [ReactiveX/rxjs#6498]
`
var s = new Rx.Subject();
var s2 = new Rx.Subject();
var b = Rx.Observable.of("").concat(s2).finally(() => console.log("FIN")); // "FIN" is not logged
//var b = Rx.Observable.of("").delay(100).concat(s2).finally(() => console.log("FIN")); // this works properly
s.debounce(str => b).subscribe(str => console.log(str));

console.log("Start");
s.next("Test");
`

`
"Start"
"Test"
`

**Current Behavior**
debounce operator is not unsubscribing debounceSelector observable immediately after it emits value, if it emits immediately on subscribe. In the above example line "FIN" is not logged. It works properly if observable emits value with delay.

**Expected behavior**
debounce operator unsubscribes debounceSelector observable immediately after it emits value.

**Reproduction**
Expected output for example above is:
`
"Start"
"FIN"
"Test"
`

**Comment by martinsik** [comment]
@ud1 Could you please provide a reproducible demo on [stackblitz](https://stackblitz.com/)? It seems like you're using a very very old RxJS version still using prototypical operators (or whatever its name was :))?

**Comment by Ayudh** [comment]
@ud1, As @martinsik pointed out you are in a very old version of RxJS.
[https://stackblitz.com/edit/rxjs-crqvcf?devtoolsheight=60&file=index.ts](https://stackblitz.com/edit/rxjs-crqvcf?devtoolsheight=60&file=index.ts)

I tried to reproduce it. It is working as expected. Please check once.

**Comment by ud1** [comment]
OK, thank you.
