### ISSUE TITLE
Figure out why the TypeScript build is so sloooooooowwww... 

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#650]
I'm not sure when or why it happened, but it seems like the ES6 build in particular got much, much slower over the last few weeks to the point where it's getting a little silly.

@jeffbcross @IgorMinar @robwormald ... have you run into this with Angular?

**Comment by kwonoj** [comment]
Just did quick analysis, seems typescript nightly was root cause..

```
λ tsc -v && tsc --diagnostics 
message TS6029: Version 1.6.2 
Files:             165        
Lines:           27640        
Nodes:          123087        
Identifiers:     41646        
Symbols:         30154        
Types:           48914        
Memory used:   154028K        
I/O read:        0.06s        
I/O write:       1.49s        
Parse time:      0.68s        
Bind time:       0.45s        
Check time:     11.76s        
Emit time:       2.11s        
Total time:     15.00s 
```

```
λ node .\node_modules\typescript\lib\tsc -v && node .\node_modules\typescript\lib\tsc --diagnostics
message TS6029: Version 1.8.0-dev.20151017
Files:             165
Lines:           27569
Nodes:          122883
Identifiers:     41598
Symbols:        216795
Types:          117409
Memory used:   208083K
I/O read:        0.06s
I/O write:       1.40s
Parse time:      0.74s
Bind time:       0.49s
Check time:     40.39s
Emit time:       2.16s
Total time:     43.77s
``` 

I think we can go back to release version of typescript until if it's really necessary to use ambient declaration merging, which was reason to bump up to nightly. What do you think?

**Comment by blesh** [comment]
We can leave it for now and report the issue to the TypeScript folks.. Thanks @kwonoj

**Comment by vladima** [comment]
out of curiosity what version of node do you use?

**Comment by kwonoj** [comment]
travis runs 0.12.7, and my system (which output those diagnostics results) also same.

**Comment by vladima** [comment]
we have noticed that node 0.12 has a serious performance issues with typescript compiler. Can you try to upgrade to node 4 and see if problem still exists>

**Comment by kwonoj** [comment]
I'll try kick off travis with v4 quickly.

**Comment by vladima** [comment]
I've tried to repro the issue locally
```
// 1.6.2
Files:             165
Lines:           27640
Nodes:          123087
Identifiers:     41646
Symbols:         30154
Types:           48914
Memory used:    80177K
I/O read:        0.04s
I/O write:       0.96s
Parse time:      0.56s
Bind time:       0.30s
Check time:      2.48s
Emit time:       1.38s
Total time:      4.72s 
```
```
/// latest bits in master
Files:             165
Lines:           27629
Nodes:          123503
Identifiers:     41846
Symbols:       4598525
Types:          117863
Memory used:   123786K
I/O read:        0.05s
I/O write:       1.23s
Parse time:      0.51s
Bind time:       0.32s
Check time:      3.73s
Emit time:       1.67s
Total time:      6.22s
```

**Comment by vladima** [comment]
and it it definitely depends on the version of node
```
vladima@vladima-OptiPlex-990:~/Sources/bugs/RxJS$ node --version && node ../../TypeScript/built/local/tsc.js --diagnostics
v4.2.1
Files:             165
Lines:           27629
Nodes:          123503
Identifiers:     41846
Symbols:       4598525
Types:          117863
Memory used:   229430K
I/O read:        0.01s
I/O write:       0.03s
Parse time:      0.37s
Bind time:       0.24s
Check time:      2.85s
Emit time:       0.42s
Total time:      3.88s
vladima@vladima-OptiPlex-990:~/Sources/bugs/RxJS$ nvm use v0.12.7
Now using node v0.12.7 (npm v2.11.3)
vladima@vladima-OptiPlex-990:~/Sources/bugs/RxJS$ node --version && node ../../TypeScript/built/local/tsc.js --diagnostics
v0.12.7
Files:             165
Lines:           27629
Nodes:          123503
Identifiers:     41846
Symbols:       4598525
Types:          117863
Memory used:   226743K
I/O read:        0.01s
I/O write:       0.05s
Parse time:      0.38s
Bind time:       0.40s
Check time:     14.39s
Emit time:       0.56s
Total time:     15.73s

```

**Comment by kwonoj** [comment]
Thanks for triage. Yes it seems node v4 resolves

```
rm -rf dist/es6 && tsc src/Rx.ts src/Rx.KitchenSink.ts --outDir dist/es6 --sourceMap --target ES6 -d --diagnostics
Files:             165
Lines:           27569
Nodes:          122883
Identifiers:     41598
Symbols:        216795
Types:          117409
Memory used:   192011K
I/O read:        0.02s
I/O write:       0.05s
Parse time:      0.89s
Bind time:       0.54s
Check time:      5.33s
Emit time:       0.91s
Total time:      7.67s
```

on [travis](https://travis-ci.org/kwonoj/RxJS/builds/89344370) also.

I'll prepare PR to bump up travis configuration at least resolves CI turnaround time.

**Comment by vladima** [comment]
cool, good to know that

**Comment by blesh** [comment]
... but... I'm scared to upgrade 😰

I guess I'll have to jump in.

**Comment by kwonoj** [comment]
@blesh I was tried node v4 quite before when it first released, and encountered some issues with module requires native compilation. Just beware what's coming after upgrade...

**Comment by blesh** [comment]
@kwonoj ... so like node-sass I guess?

**Comment by kwonoj** [comment]
@blesh you can see it's happening it live on travis with pr https://github.com/ReactiveX/RxJS/pull/653, in this case `selenium-webdriver`.

**Comment by blesh** [comment]
@kwonoj ... I see. Thanks for the heads up. I thought you were talking about other projects.

**Comment by kwonoj** [comment]
I think any other project having native build (which properly did not resolves or upgrades to support v4) will have similar cases. PR shows one good example on that.

**Comment by IgorMinar** [comment]
@blesh I upgrade angular/angular to node v4 primarily to deal with v0.12.x performance regressions affecting typescript. I suggest you do the same.
