### ISSUE TITLE
Searching for "fromEvent" shows wrong/random results

### ISSUE THREAD

**Issue by martinsik** [ReactiveX/rxjs#6500]
## Bug Report

**Current Behavior**
When I go to https://rxjs.dev/ and use the search field in the top right corner to search for "fromEvent" it's suggesting wrong/incomplete results.

![rxjs-frome](https://user-images.githubusercontent.com/238765/123928498-4029d980-d98e-11eb-9ce7-996aa882b943.png)
![rxjs-fromev](https://user-images.githubusercontent.com/238765/123928499-40c27000-d98e-11eb-9723-4150c04d9958.png)
![rxjs-fromeven](https://user-images.githubusercontent.com/238765/123928501-415b0680-d98e-11eb-8582-14fc27567de0.png)
![rxjs-fromevent](https://user-images.githubusercontent.com/238765/123928502-415b0680-d98e-11eb-93b5-a8cfd72b2049.png)

**Expected behavior**

When typing into the search field I should see smaller and smaller subset of search results probably ending with `fromEvent` and `fromEventPattern`.

**Comment by tmair** [comment]
I had a quick look at this issue and it seems that keyword generation for the search index is not working correctly. 

In your case `fromEvent` is used in many Examples and somehow the content of the examples are included within the keywords of the document. Searching for `click` will also return many documents.

**Comment by martinsik** [comment]
I was investigating this a little and there's something wrong with lunr.js I think. When I search for `fromeven` it searches for `"titleWords:*fromeven* fromeven"` which should find both `fromEvent()` and `fromEventPattern()`. When I try the same query `"name:*Shepar* Shepard"` at https://olivernn.github.io/moonwalkers/ it works as expected.
