### ISSUE TITLE
Interface for ConnectableObservableLike is not exposed

### ISSUE THREAD

**Issue by DaSchTour** [ReactiveX/rxjs#6529]
## Bug Report

**Current Behavior**
Interface for ConnectableObservableLike is not exposed

**Expected behavior**
Interface for ConnectableObservableLike is exposed.

**Reproduction**

Try to add type definition to the example from docs.

```ts
import { connectable, timer } from 'rxjs';
// suggested refactor
const tick$ = connectable(timer(1_000), {
  connector: () => new Subject<number>(),
  resetOnDisconnect: false
});
```

First try
```ts
import { connectable, timer, ConnectableObservableLike } from 'rxjs';
// suggested refactor
const tick$: ConnectableObservableLike<number> = connectable(timer(1_000), {
  connector: () => new Subject<number>(),
  resetOnDisconnect: false
});
```
Result: `TS2305: Module '"rxjs"' has no exported member 'ConnectableObservableLike'.`

Second try
```ts
import { connectable, timer, ConnectableObservable } from 'rxjs';
// suggested refactor
const tick$: ConnectableObservable<number> = connectable(timer(1_000), {
  connector: () => new Subject<number>(),
  resetOnDisconnect: false
});
```
Result: `TS2740: Type 'ConnectableObservableLike ' is missing the following properties from type 'ConnectableObservable ': subjectFactory, _subject, _refCount, _connection, and 3 more.`

**Environment**
- RxJS version: 7.2.0

**Comment by benlesh** [comment]
As a workaround, you can always define it locally. We'll discuss it at the core team meeting. Ideally, long-term, I'd like it to be `ConnectableObservable`. I need to think of a plan to get us there.

**Comment by benlesh** [comment]
Really, you shouldn't need to explicitly type `tick$`, however, if you absolutely must, a workaround would be to use `ReturnType`:

```ts
import { connectable, timer } from 'rxjs';

const tick$: ReturnType<typeof connectable> = connectable(timer(1_000), {
  connector: () => new Subject<number>(),
  resetOnDisconnect: false
});
```

Ideally, long term, I'd love to have `ConnectableObservableLike` just be `ConnectableObservable`... Mostly because I don't like the name. For now, I guess we'll have to figure something else out.

Perhaps we can just rename `ConnectableObservableLike` to `Connectable` and expose it. 🤔

**Comment by DaSchTour** [comment]
Okay. In this example it might work. But what if I'm in a class?

```ts
class Sample {
  // that's not a nice solution?
  public $tick: any;

  init() {
    this.tick$ = connectable(timer(1_000), {
      connector: () => new Subject<number>(),
      resetOnDisconnect: false
    });
  }
  
   connect() {
     this.tick$.connect():
   }
}
```
