### ISSUE TITLE
IE11: ajax.getJSON returns string response

### ISSUE THREAD

**Issue by johnhunter** [ReactiveX/rxjs#6532]
## Bug Report

**Current Behavior**
With IE11 `ajax.getJSON` returns the response string

**Expected behavior**
With IE11 `ajax.getJSON` should return an object as other browsers do

**Reproduction**

** Please provide repro code does not involves framework, or other setups to address this bug is specific to rxjs core **

- REPL or Repo link:
https://johnhunter.github.io/rxjs-ie11-getJSON-issue/

```js
// Global rxjs from unpkg.com/rxjs@7.2.0/dist/bundles/rxjs.umd.js
var ajax = rxjs.ajax.ajax;

var url = 'https://api.github.com/users?per_page=2';

var users = ajax.getJSON(url);
var subscribe = users.subscribe(
  function(res) { console.log(typeof res, res) },
  function(err) { console.error(err) }
);
```
- IE11 `typeof res` is "string"
- Chrome `typeof res` is "object" as expected

**Environment**
- Runtime: Browser IE11
- RxJS version: 7.2.0

**Comment by benlesh** [comment]
Seems like a workaround for now would be to check the type and `JSON.parse`:

```ts
const obj = typeof res === 'string' ? JSON.parse(res) : res;
```

**Comment by johnhunter** [comment]
Thanks @benlesh. I know that all IE support will be removed in v8 but do you think this regression will be patched in v7? 

From PR https://github.com/ReactiveX/rxjs/pull/5661 it looks like this might have always been the behaviour with v7 (we were upgrading from 6.x.x).

**Comment by johnhunter** [comment]
Closing, version 8 is almost out and I no longer have to support IE.
