### ISSUE TITLE
After upgrade to 7.2.0 mapTo(true) violates and shows @typescript-eslint/no-unsafe-argument error

### ISSUE THREAD

**Issue by vitalyiegorov** [ReactiveX/rxjs#6536]
## Bug Report
We have migrated our codebase from 6.6.6 to 7.2.0 and have a  an issue for `mapTo(true)` operator from eslint:

```
ESLint: Unsafe argument of type `OperatorFunction<any, boolean>` assigned to a parameter of type `OperatorFunction<DeleteResult, boolean>`.(@typescript-eslint/no-unsafe-argument)
```

Investigating the [sources](https://github.com/ReactiveX/rxjs/blob/master/src/internal/operators/mapTo.ts):
```
export function mapTo<R>(value: R): OperatorFunction<any, R>;
/** @deprecated Do not specify explicit type parameters. Signatures with type parameters that cannot be inferred will be removed in v8. */
export function mapTo<T, R>(value: R): OperatorFunction<T, R>;
```

**Current Behavior**
ESLint error is shown, without providing generics for mapTo operator.

**Expected behavior**
No ESLint errors, without additional generics for mapTo operator.

**Reproduction**
```
mapTo(true)
```

**Environment**
- Runtime: Node v16.1.0
- RxJS version: 7.2.0

**Possible Solution**
Seems like the problem is with `any`, changing the type to use generics, fixes the issue, and you can use it in your code without specifying them:
```ts
export declare function mapTo<T, R>(value: R): OperatorFunction<T, R>;
```

**Comment by cartant** [comment]
`T` serves no purpose in the signature - as mentioned in the deprecation comment - and it would be incorrect to use it. (The general rule is that a type parameter should be used more than once in a signature.)

`any` could - indeed _should_ - be replaced with `unknown`. Replacing the uses of `any` - throughout the API - with `unknown` is some that will be (eventually) be done.

**Comment by benlesh** [comment]
@cartant are we tracking the change for `any` to `unknown` anywhere? It seems like that's a version 8 thing. (Also we can probably close this)

**Comment by cartant** [comment]
@benlesh

> ... are we tracking the change for any to unknown anywhere?

Added it to #6367

**Comment by rassie** [comment]
So what is the solution here, why is this closed? No matter which signature I'd use, I'll get an ESlint warning, either for deprecation or for unsafe arguments.

**Comment by manbearwiz** [comment]
Its clunky, but you can use a type assertion to specify the return type as `unknown` instead of `any` until they handle it internally. This removes the error for me. Replace

```ts
switchMapTo(this.service.isAlive())
```

with

```ts
switchMapTo(this.service.isAlive()) as OperatorFunction<unknown, boolean>
```

**Comment by benlesh** [comment]
Does `map(() => true)`  work for you? (That's all that `mapTo` does internally)

**Comment by lukket** [comment]
> Does `map(() => true)` work for you? (That's all that `mapTo` does internally)

Seems to work also for `switchMapTo`.
