### ISSUE TITLE
Docs around new operators export site

### ISSUE THREAD

**Issue by jakovljevic-mladen** [ReactiveX/rxjs#6544]
Hi,

I have two questions and I would like to check if it's worth investing my time for creating PRs.

As of recently, operators are exported from a top level export site (`'rxjs'`). However, the old export site has still remained (`'rxjs/operators'`) and that is now creating "problems" because many documentation docs are now being duplicated. For example, `map` operator documentation can be accessed from http://rxjs.dev/api/operators/map and from http://rxjs.dev/api/index/function/map (this link doesn't work because docs site is still using old version, but once rxjs.dev is updated, it will start working). The first URL is the standard one that has existed ever since `'rxjs/operators'` export site has been introduced. The later is the new one (as of RxJS v7.2.0).

Well, what's the difference? There is really no difference in the generated documentation content. However, documentation links that look like this `{@link map}` can't point to both URLs, but a new [disambiguator had to be created](https://github.com/ReactiveX/rxjs/pull/6540) to exclude those that come from `operators` module. So, if mentioned PR is approved and merged, all links that look like `{@link map}` will point to http://rxjs.dev/api/index/function/map. Using links that have this syntax is good because a warning is raised when building docs - when something happens to the original document, for example, when one of the deprecated APIs gets removed in V8, all links that point to the removed class/interface/function will stop working and warnings will start appearing. This is how such links will be discovered quite easily because of this.

In the end, `'rxjs/operators'` export site will be removed eventually, thus, an update to the documentation will have to be made. For now, many `.md` documents don't use `{@link map}` syntax to create links, but rather use standard markup syntax, that goes like this: [`[map](/api/operators/map)`](https://github.com/ReactiveX/rxjs/blob/6f0e853a86e6db1ab321ff077c95e6b1d88fd3df/docs_app/content/guide/operators.md#L161). For this reason, once `'rxjs/operators'` export site is removed, `[map](/api/operators/map)` link will stop working - it will produce 404 error because there won't be a document at that path. My question is: shall I create a PR to replace links that look like `[map](/api/operators/map)` to the ones that look like `{@link map}`?

Also, since operators are just functions, the new URL does not indicate that `/api/index/function/map` is an operator. There is no distinction between `map` and for example `isObservable`, both are functions. I wanted to add a label to top, next to other labels. Something like this:
![image](https://user-images.githubusercontent.com/28087049/127749040-af527aab-f59e-43fe-8536-9b860db8479c.png)
Shall I do that as well? It will only show `OPERATOR` label on the operators, other functions like `/api/index/function/isObservable` won't have them. Also, having to cover both cases (`/api/operators/map` and `/api/index/function/map`) will be a bit tricky, but it shouldn't be too hard.

**Comment by tmair** [comment]
One additional consideration to make is, that there are probably many links pointint to the old operator import site (e.g. http://rxjs.dev/api/operators/map). We might also consider to add redirects to the new location in the Docs, so the old links will still work.

**Comment by jakovljevic-mladen** [comment]
> We might also consider to add redirects to the new location in the Docs, so the old links will still work.

They will work as long as 'rxjs/operators' export site is present. After this is removed, I agree that there should be a redirect to the new location, so the old links still work - there might be a lot of other sites pointing the [soon to be removed] docs, like links from this issue. The way to do it is to add some objects to [`docs_app/firebase.json`](https://github.com/ReactiveX/rxjs/blob/c52ff2e3aae19cd0877adb63182c03b79427de96/docs_app/firebase.json) to the `"redirects"` array.

Also, there are so many code examples that should be updated.

**Comment by jakovljevic-mladen** [comment]
Although the first part of the ticket is merged to master (#6563), I have a plan to work on the second one: to replace links that look like this `[map](/api/operators/map)` to the ones that look like this `{@link map}` wherever possible. As it looks, it's gonna be a huge PR, so I'm gonna keep this issue open. At least, that PR is gonna [help with the dead links](https://github.com/ReactiveX/rxjs/blob/0b2495f72e/docs_app/tools/transforms/links-package/services/getLinkInfo.js#L58) (for example, `[map](/api/operators/map)` is gonna become dead once `'rxjs/operators'` export site gets removed).
Though, what Thomas [suggested](https://github.com/ReactiveX/rxjs/issues/6544#issuecomment-892412484) should be considered also, but I guess that it should be part of another issue/PR.

**Comment by jakovljevic-mladen** [comment]
On the second thought, when I check the issue title, it makes sense to close this issue as the main reason for opening it was merged with #6563. For this other part (moving away from `[link](/path/to/file)` to `{@link /path/to/file link}` syntax), we don't really need a ticket for that. And, related to the proposal from Thomas, we may not need to think about this until `'rxjs/operators'` is really removed, which probably won't happen soon.
