### ISSUE TITLE
Proposal: debounceTimeWith() - Ability to set debounce time based on submitted function

### ISSUE THREAD

**Issue by crash83k** [ReactiveX/rxjs#6551]
Is there any interest in creating a `debounceTime` operator (and possibly other time operators) that can take a function to return the debounce time specific to the request?

My idea would be to tap the pipe value as the parameter for the supplied function, and allow the function to return a number to set the debounce for that particular subscribed event.

Something like:
```typescript
observable.pipe( debounceTimeWith( (tapValue: any) => number ) ) 
```

So this could be used like:
```typescript
observable.pipe( debounceTimeWith( value => value === true ? 0 : 500 ) )
```
I'm pretty sure I could write this as a custom operator, but I'm wondering if any others feel this would be useful enough to create a PR for RxJs to include this functionality.

**Comment by voliva** [comment]
I think the `debounce` operator already would cover this (please, correct me if I'm wrong)

```ts
observable.pipe(
  debounce(value => timer(value === true ? 0 : 500))
)
```

**Comment by crash83k** [comment]
You're right. I'm not sure why I never noticed that. Thanks!

(Closing this.)
