### ISSUE TITLE
(Likely) Scheduled action leaks

### ISSUE THREAD

**Issue by cartant** [ReactiveX/rxjs#6561]
It seems likely to me that some - if not all - of the following `scheduler.schedule` calls will leak actions that are added to another subscription - similar to the leak that was fixed in #6559:

https://github.com/ReactiveX/rxjs/blob/5d0e41ee46337f56dba6d9a1ef938002b261ccac/src/internal/observable/combineLatest.ts#L296

https://github.com/ReactiveX/rxjs/blob/5d0e41ee46337f56dba6d9a1ef938002b261ccac/src/internal/operators/bufferTime.ts#L120

https://github.com/ReactiveX/rxjs/blob/5d0e41ee46337f56dba6d9a1ef938002b261ccac/src/internal/operators/bufferTime.ts#L128-L133

https://github.com/ReactiveX/rxjs/blob/5d0e41ee46337f56dba6d9a1ef938002b261ccac/src/internal/operators/mergeInternals.ts#L117

https://github.com/ReactiveX/rxjs/blob/5d0e41ee46337f56dba6d9a1ef938002b261ccac/src/internal/operators/windowTime.ts#L139

https://github.com/ReactiveX/rxjs/blob/5d0e41ee46337f56dba6d9a1ef938002b261ccac/src/internal/operators/windowTime.ts#L147-L152

https://github.com/ReactiveX/rxjs/blob/5d0e41ee46337f56dba6d9a1ef938002b261ccac/src/internal/scheduled/scheduleAsyncIterable.ts#L11-L25

https://github.com/ReactiveX/rxjs/blob/5d0e41ee46337f56dba6d9a1ef938002b261ccac/src/internal/scheduled/scheduleObservable.ts#L9-L16

https://github.com/ReactiveX/rxjs/blob/5d0e41ee46337f56dba6d9a1ef938002b261ccac/src/internal/scheduled/schedulePromise.ts#L9-L14

https://github.com/ReactiveX/rxjs/blob/5d0e41ee46337f56dba6d9a1ef938002b261ccac/src/internal/util/caughtSchedule.ts#L11-L18

Some of these might leak only a few actions, but any leaked actions will have a closure that could be referencing a resource.

@benlesh

**Comment by benlesh** [comment]
I have some plans for this I think. 🤔
