### ISSUE TITLE
TestScheduler doesn't work with promise-based observables

### ISSUE THREAD

**Issue by CertainlyAria** [ReactiveX/rxjs#6565]
## Bug Report

**Current Behavior**
When using promise-based observables with `TestScheduler`, `assertDeepEqual` function always receives always receives an empty array `[]` as its first parameter. `assertDeepEqual` is `TestScheduler`'s constructor parameter.

**Expected behavior**
`assertDeepEqual` should receive values just like other observables.

**Reproduction**
- REPL or Repo link:
Reproducible repo: [certainlyAria/rxjs-test-scheduler-promise-bug](https://github.com/CertainlyAria/rxjs-test-scheduler-promise-bug)

**Environment**
- Runtime: Node v16.6.1
- RxJS version: 7.3.0

**Possible Solution**

**Additional context/Screenshots**

**Comment by cartant** [comment]
The docs explicitly state that "RxJS code that consumes Promises cannot be directly tested":

https://github.com/ReactiveX/rxjs/blob/master/docs_app/content/guide/testing/marble-testing.md#known-issues

**Comment by ceroy-ak** [comment]
@cartant Is there a way to test Observables that are using `from` for API calls by stubbing that `Promise` using Sinon?
