### ISSUE TITLE
Confusing "Bug report" issue template

### ISSUE THREAD

**Issue by Chealer** [ReactiveX/rxjs#6568]
**RxJS version:** _This bug is not in the RxJS product._

**Code to reproduce:** _This does not report a behavioral bug._

**Expected behavior:** _This does not report a behavioral bug._

**Actual behavior:** _This does not report a behavioral bug._

**Additional information:**
[The issue reporting form](https://github.com/ReactiveX/rxjs/issues/new/choose) offers a template simply titled "Bug report". The template is unfortunately only appropriate for reporting behavioral bugs, as the description indicates.
This could be solved either by making the template more general, or by giving it a more specific title like "Behavioral bug report".

**Comment by kwonoj** [comment]
This is expected, rxjs core team uses gh issues as team's backlog tracking with any code side behavior bug report only. https://github.com/ReactiveX/rxjs/issues/5970

For other topics, please use discussions.

**Comment by Chealer** [comment]
@kwonoj I don't know what you mean by "team's backlog tracking", but this is certainly not expected. When we see a ticket template called _Bug report_, the expectation is that it allows reporting any bug.

**Comment by kwonoj** [comment]
Our issue template also include instructions

> If you believe there is a bug in rxjs core need to be fixed, please fill out all template for repro, otherwise
core team may move issues into discussions. Also, all other non-bug report may closed without followup.

Word may not be clear and we may polish it later, but we do recommend to use discussions for non-code bug report and other discussions.

**Comment by Chealer** [comment]
@kwonoj that's indeed far from being clear, and this ticket is not about discussions. It is about issue reports. If developers even get to see that template's content, that's because they chose the incorrect template because they were confused in the first place.

**Comment by Chealer** [comment]
This unfortunately persists, but I unfortunately [will not be the one driving this further](https://www.philippecloutier.com/blogpost178).
