### ISSUE TITLE
Overview: confusing observation terminology (emission, push, return)

### ISSUE THREAD

**Issue by Chealer** [ReactiveX/rxjs#6571]
**RxJS version:** _This bug is not in the RxJS product._

**Code to reproduce:** _This does not report a behavioral bug._

**Expected behavior:** _This does not report a behavioral bug._

**Actual behavior:** _This does not report a behavioral bug._

**Additional information:**
[The _Creating Observables_ section of the _Observable_ page of _Overview_](https://rxjs.dev/guide/observable#creating-observables) contains:

> The following example creates an Observable to emit the string 'hi' every second to a subscriber.

That is the first time the overview talks about an Observable _emitting_ something, which can be confusing. Yet, [Observable's specification](https://rxjs.dev/api/index/class/Observable) seems to confirm emitting is a correct and probably even the canonical term to describe that. Prior to that point, the overview seems to use the terms _returning_ and _pushing_ synonymously. If my understanding is correct, current documentation uses all of the following interchangeably:

> emitting
> returning
> pushing
> nexting

Given the topic is already quite complicated, it would help to either be more consistent or explicitly indicate that the above do not refer to different concepts (if that is the case).

**Comment by kwonoj** [comment]
Hi, thanks for the opinions, As pinned https://github.com/ReactiveX/rxjs/issues/5970 , we use gh issues as core team's tracking backlog & code-side bug report only. For further tracking, I'll moving these into discussions page.
