### ISSUE TITLE
Websocket completes after sending first message

### ISSUE THREAD

**Issue by dsl400** [ReactiveX/rxjs#6585]
## Bug Report

**Current Behavior**
websocket completes after sending first message

**Expected behavior**
connection should not complete

**Reproduction**

** Please provide repro code does not involves framework, or other setups to address this bug is specific to rxjs core **

- REPL or Repo link:
(you can use https://stackblitz.com/ to create one to attach here)

```js
export class WebsocketService {

  private socket: WebSocketSubject<any>;
  
  constructor() {
    this.connect()
  }

  private connect(){
    this.socket = webSocket("ws://localhost:8765");
    this.socket.subscribe(
      msg => console.log('message received: ',msg),
      error => console.error('ws error: ',error),
      ()=>console.log('ws completed')
    )
  }

  public send_message(message:string){
    this.socket.next({'message':message});
  }

}


websocketService.send_message('some message');
```

**Environment**
- Runtime: [e.g. Node v12.18.0 , Chrome v92.0.4515.159 ]
- RxJS version: ~6.6.0
- (If bug is related) Loader, build configuration: [e.g webpack, angular-cli version, config]

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by dsl400** [comment]
updated to 
node v14.17.6, 
chrome  93.0.4577.63
rxjs ~6.6.0

problem still the same, after sending the first message the websocket connection is closed

**Comment by dsl400** [comment]
same behavior with "rxjs": "^7.3.0"

**Comment by voliva** [comment]
I'm using websocket subject on 7.3.0 (and previously on v6) in my project and it works alright. From your test code I can't see anything that looks wrong at first sight.

Can you verify it's not the server closing the connection?
