### ISSUE TITLE
extending the Observable makes the TS compiler complain

### ISSUE THREAD

**Issue by rolandjitsu** [ReactiveX/RxJS#659]
If I try to extend the `Observable` class:
```js
class MyCustomObservable extends Observable<any> {}
```
I get `error TS2507: Type 'typeof "/Users/rolandjitsu/Projects/ng2-lab/node_modules/@reactivex/rxjs/dist/cjs/Observable"' is not a constructor function type.` in the TS compiler output.

**Comment by kwonoj** [comment]
I gave it a try stub code like below

```
///<reference path="../RxJS/typings/es6-shim/es6-shim.d.ts" />
import * as Rx from '../RxJS/dist/cjs/Rx';

class StubObservable<T> extends Rx.Observable<T> {
  constructor(private value: T) {
    super();
  }

  _subscribe(subscriber: Rx.Subscriber<any>) {
    subscriber.next(this.value);
  }
}

new StubObservable(42).subscribe(console.log);
```

which compiles and emits value - would you give a try above stub does works?

**Comment by rolandjitsu** [comment]
@kwonoj that seems to do the trick, do you know why is this happening though if I import the `Observable` directly?

**Comment by kwonoj** [comment]
@rolandjitsu Would you able to share whole code snippet tried originally (including imports)

**Comment by rolandjitsu** [comment]
Of course:
```js
import * as Observable from '@reactivex/rxjs/dist/cjs/Observable';

const FIREBASE_AUTH_PROVIDERS = [
	'password',
	'github',
	'google',
	'facebook',
	'twitter'
];

export enum FirebaseAuthProviders {
	Password,
	Github,
	Google,
	Facebook,
	Twitter
}

function authOptionsDefaults (remember?: boolean): any {
	return {
		remember: typeof remember === 'boolean' && !remember ? 'sessionOnly' : 'default'
	};
}

export class AuthClient extends Observable<FirebaseAuthData> {
	private _firebaseRef: Firebase;
	constructor(firebaseRef: Firebase) {
		this._firebaseRef = firebaseRef;
		super((observer) => {
			let callback = (auth: FirebaseAuthData) => {
				observer.next(auth);
			};
			this._firebaseRef.onAuth(callback);
			return () => {
				this._firebaseRef.offAuth(callback)
			};
		});
	}
	get session(): FirebaseAuthData {
		return this._firebaseRef.getAuth();
	}
	register(credentials: FirebaseCredentials): Promise<FirebaseAuthData | any> {
		return new Promise((resolve, reject) => {
			this._firebaseRef.createUser(credentials, (error) => {
				if (error) reject(error);
				else this.loginWithCredentials(credentials).then((auth: FirebaseAuthData) => {
					resolve(auth);
				});
			});
		});
	}
	// [User Authentication]{@link https://www.firebase.com/docs/web/guide/user-auth.html}
	// [Email & Password]{@link https://www.firebase.com/docs/web/guide/login/password.html}
	loginWithCredentials(credentials: FirebaseCredentials, remember?: boolean): Promise<FirebaseAuthData | any> {
		let opts = authOptionsDefaults(remember);
		return new Promise((resolve, reject) => {
			this._firebaseRef.authWithPassword(
				credentials,
				(error, auth: FirebaseAuthData) => { // https://www.firebase.com/docs/web/guide/login/password.html#section-logging-in
					if (error) reject(error);
					else resolve(auth);
				},
				opts
			);
		});
	}
	// [Github]{@link https://www.firebase.com/docs/web/guide/login/github.html}
	// [Scopes]{@link https://developer.github.com/v3/oauth/#scopes}
	// [Google]{@link https://www.firebase.com/docs/web/guide/login/google.html}
	// [Scopes]{@link https://developers.google.com/+/web/api/rest/oauth#scopes}
	// [Facebook]{@link https://www.firebase.com/docs/web/guide/login/facebook.html}
	// [Scopes]{@link https://developers.facebook.com/docs/facebook-login/permissions/v2.5}
	// [Twitter]{@link https://www.firebase.com/docs/web/guide/login/twitter.html}
	loginWithProvider(provider: FirebaseAuthProviders, remember?: boolean, scope?: any): Promise<any> {
		let opts = authOptionsDefaults(remember);
		if (scope && provider !== FirebaseAuthProviders.Twitter) opts.scope = scope;
		return new Promise((resolve, reject) => {
			this._firebaseRef.authWithOAuthRedirect(
				FIREBASE_AUTH_PROVIDERS[provider],
				(error) => {
					if (error) reject(error);
				},
				opts
			);
		});
	}
	resetPassword(credentials: FirebaseResetPasswordCredentials): Promise<any> {
		return new Promise((resolve, reject) => {
			this._firebaseRef.resetPassword(credentials, (error) => {
				if (error) reject(error);
				else resolve();
			});
		});
	}
	changePassword(credentials: FirebaseChangePasswordCredentials): Promise<any> {
		return new Promise((resolve, reject) => {
			this._firebaseRef.changePassword(credentials, (error) => {
				if (error) reject(error);
				else resolve();
			});
		});
	}
	isAuthenticated(): boolean {
		return this.session !== null;
	}
	logout(): void {
		this._firebaseRef.unauth();
	}
}
```

**Comment by kwonoj** [comment]
OK, it wasn't work cause `Observable` exports it as default.

try this: 

```
import Observable from '......../cjs/Observable';

class ... extends Observable<any> {
rest of code
```

**Comment by rolandjitsu** [comment]
At this point I am using the bundled Rx with Angular 2, so that wouldn't work. After they move to removing Rx from their bundles I will be able to do that.

**Comment by blesh** [comment]
cc/ @robwormald

**Comment by robwormald** [comment]
next release of angular2 fixes a lot of the shenanigans regarding Rx, so going forward you'll be able to just 
```
import {Observable} from 'angular2/angular2' 
```
and that'll give you access. That said, (and I'm no expert) but extending Observable feels like a strange use case to me here. It's also my understanding that to properly subclass it, you need to override the `lift` method, as the first time you use an operator you'll get back the original Observable vs your extended one.

**Comment by rolandjitsu** [comment]
Sounds great. I extend it because creating an instance should give me an observable object that changes over time. This seemed to be a good way to do it, but if you have other suggestions I would be happy to hear them :)

I think I've also read that somewhere in the source code comments of `Observable.ts`, but I wasn't sure what exactly I should be doing in the `lift` method.

**Comment by robwormald** [comment]
Personally, I'd just have something like `authStatus` as a property of your service, and make that Observable. I dunno. @blesh?

**Comment by blesh** [comment]
I would agree. It's best to think of Observable as a primitive type like a function. If there is a lot of related logic, you probably don't need to subclass Observable. I'd reserve subclassing Observable for when you need to alter something about it, like add custom operators, or force a multicast behavior.

**Comment by rolandjitsu** [comment]
@robwormald and @blesh thanks for the input. Makes sense not to extend the Observable, I think the reason I did it was because I wanted to have the `subscribe` directly on the auth. But I will probably just have a method on the class and internally a private property that will be an observable.

**Comment by robwormald** [comment]
One thing that's neat about the collection-likeness of Observables is you can treat them like a collection. So whereas with a promise you'd do something like 
```js
getAuth(){ return doPromiseyThing() } 
```
with an Observable you can do
```js
this.authStatus = doObservableyThing();
```
and then simply subscribe to it externally. You might want to consider sharing it as well (so that you get a single observable rather than re-executing the logic each time you subscribe.)

**Comment by rolandjitsu** [comment]
@robwormald yes, I know, and I like that too about it :) When you say `sharing it as well` you mean expose the property as a public?
