### ISSUE TITLE
forkJoin usage with concatMap

### ISSUE THREAD

**Issue by wokier** [ReactiveX/rxjs#6593]
## Bug Report

**Current Behavior**
when `forkJoin` is used with observables using `concatMap`, the observer is not called.

**Expected behavior**
the observer should be called at the end of all sources of the `forkJoin`

**Reproduction**
https://github.com/ReactiveX/rxjs/blob/2c10f7d7002871026b09727cb9bedfbdafd77e89/spec/observables/forkJoin-spec.ts#L651
3 tests have been marked as ignored with `xit`

**Environment**
- Runtime: Node v15.8.0 
- RxJS version: 7.3.0

**Possible Solution**
The workaround i used in my project code is to add `.pipe(first())` right after each concatMap
I reproduced similar workarounds in the tests using `mergeAll`, `zipAll` or `combineAll` after the `forkJoin`, but this alter the structure of the return. It may not match what the dev want to do.

**Comment by josepot** [comment]
Hi @wokier ! I've had a quick look at this and I think that `forkJoin` is working fine.

The test, on the other hand, looks a bit off. If you replace `results.push(+value)` with `results.push(...value)` then the test passes. Keep in mind that `forkJoin` only emits once (with an Array of the latest values) and then completes.

**Comment by benlesh** [comment]
I left a comment on the PR. Thanks again @wokier for doing the right thing and reporting the issue with failing tests. Unfortunately, there were some issues with the tests, and I couldn't confirm that there was a bug when I tried replicating the issue in a [Stackblitz](https://stackblitz.com/edit/rxjs-n6ygx4?file=index.ts). 

I'm going to close this for now, but if you do end up finding the bug you think you found again, please don't hesitate to file a new issue!

Thanks again!
