### ISSUE TITLE
forkJoin documentation

### ISSUE THREAD

**Issue by victororlyk** [ReactiveX/rxjs#6599]
## Bug Report

**Current Behavior**
documentation from code in webstorm is showing that forkJoin can accept only array, but we can pass {};

A clear and concise description of the behavior.

**Expected behavior**
The docs should not show that it is depreaced

A clear and concise description of what you expected to happen (or code).

**Reproduction**
```js
import {of, forkJoin} from "rxjs";
import {delay} from "rxjs/operators";

const number$ = of(1, 2, 3);
const s$ = of('a', 'b', 'c').pipe(delay(7000))

forkJoin({
    number$,
    s$
}).subscribe(console.log)
```

**Environment**
- Runtime: [e.g. Node v${16.8.0}, Chrome v${93.0}]
- RxJS version: 7.3.0
- Webstorm 2021.2.1

**Additional context/Screenshots**
here is  {} syntax
<img width="682" alt="Screenshot 2021-09-15 at 16 59 48" src="https://user-images.githubusercontent.com/33072590/133448041-7b76cca8-5725-4716-a0e3-bcd3f41a8034.png">
here is [] syntax
<img width="589" alt="Screenshot 2021-09-15 at 17 07 13" src="https://user-images.githubusercontent.com/33072590/133448727-b0ba9389-b0a1-4734-b78e-0424c0a980dd.png">

**Comment by jakovljevic-mladen** [comment]
I think this is the WebStorm bug. Please find [more info here](https://youtrack.jetbrains.com/issue/WEB-51889).

**Comment by jakovljevic-mladen** [comment]
As this is the IDE bug reported to the official IDE issue tracking site, I will close this issue.
