### ISSUE TITLE
Property stub based type definition does not support parameter default value

### ISSUE THREAD

**Issue by kwonoj** [ReactiveX/RxJS#660]
Some of operators allows default value if it's not specified like below,

```
function repeat<T>(count: number = -1);
function defaultIfEmpty<T, R>(defaultValue: R = null);
```

and `Observable` has property stub to create prototype in module like 
`repeat: <T>(count: number) => Observable<T>`
default value for parameter is not allowed, end result causes typescript compiler complains without parameter.

```
Rx.Observable.of(42).defaultIfEmpty();
error TS2346: Supplied parameters do not match any signature of call target.
```

related with https://github.com/ReactiveX/RxJS/issues/608, and https://github.com/ReactiveX/RxJS/pull/643 for remove property based stubs.

**Comment by blesh** [comment]
> repeat: <T>(count: number) => Observable<T>

It should probably just be `repeat: <T>(count?: number) => Observable<T>` in the stub, then.

`?` will make the difference, I think.

**Comment by kwonoj** [comment]
Yes, you're correct. Completely forgot it somehow even staring optional operators all time.

**Comment by kwonoj** [comment]
Will update PR and close this one.
