### ISSUE TITLE
Remove rxjs.dev console playground

### ISSUE THREAD

**Issue by benlesh** [ReactiveX/rxjs#6604]
I'm talking about this: 

![image](https://user-images.githubusercontent.com/1540597/133911963-7cc35d75-97fb-4007-a27b-df791b1cbed0.png)

There's two problems:

1. "ondoc rednered" LMAO... what is that?! hahahaha
2. The playground requires we load the entire UMD version of rxjs in an <script/> tag, that's a lot of extra stuff to load given I doubt many people use that, when they can just click a button and go play in Stackblitz. If anything we should just add a link to the Stackblitz playground.

**Comment by niklas-wortmann** [comment]
"ondoc rednered" sounds very much like a console log I would do 😅

I do agree though I think we can get rid of both of that

**Comment by jakovljevic-mladen** [comment]
This is fixed by #6609 and #6610.
