### ISSUE TITLE
package.json incorrectly defines location of Typescript types

### ISSUE THREAD

**Issue by mmakrzem** [ReactiveX/rxjs#6611]
## Bug Report

**Current Behavior**
Installed rxjs into my TypeScript project.  Tried using rxjs but the TypeScript compiler gave me an error message saying 

Could not find a declaration file for module 'rxjs'.
           'D:/myWork/node_modules/rxjs/dist/cjs/index.js' implicitly has an 'any'
           type.Try `npm i --save-dev @types/rxjs` if it exists or add a new declaration (.d.ts) file containing
           `declare module 'rxjs';`

**Expected behavior**
TypeScript should be able to find the types defined inside the rxjs project.  

**Environment**
- RxJS version: 7.3.0
- TypeScript v4.4.3 
- npm v7.18.1 
- node v14.15.3

**Possible Solution**
I had a look in rxjs's package.json file and I see 
```"types": "index.d.ts"```

This is incorrect.   If I change this line to the following then everything starts working again.

```"types": "./dist/types/index.d.ts"```

I don't know why the "typesVersions" settings don't work.

**Comment by kwonoj** [comment]
It is not incorrect: https://github.com/ReactiveX/rxjs/issues/6466#issuecomment-859186944

If you see this issue on tsc > 4.2.4, please provide reproducible repo.

**Comment by kwonoj** [comment]
Closing as inactive.
