### ISSUE TITLE
No error information on Uncaught TypeError: Cannot read properties of undefined (reading 'isStopped')

### ISSUE THREAD

**Issue by JosepAlacid** [ReactiveX/rxjs#6623]
When this issue is launched there's no additional information anywhere, just this buch of unreadable content dumped from the stack: 

Uncaught TypeError: Cannot read properties of undefined (reading 'isStopped')

callHook @ \node_modules\@angular\core\fesm2015\core.js:2526
callHooks @ \node_modules\@angular\core\fesm2015\core.js:2495
executeInitAndCheckHooks @ \node_modules\@angular\core\fesm2015\core.js:2446
refreshView @ \node_modules\@angular\core\fesm2015\core.js:9480
renderComponentOrTemplate @ \node_modules\@angular\core\fesm2015\core.js:9579
tickRootContext @ \node_modules\@angular\core\fesm2015\core.js:10810
detectChangesInRootView @ \node_modules\@angular\core\fesm2015\core.js:10835
detectChanges @ \node_modules\@angular\core\fesm2015\core.js:22854
tick @ \node_modules\@angular\core\fesm2015\core.js:29678
_loadComponent @ \node_modules\@angular\core\fesm2015\core.js:29716
bootstrap @ \node_modules\@angular\core\fesm2015\core.js:29652
<anonymous> @ \node_modules\@angular\core\fesm2015\core.js:29330
_moduleDoBootstrap @ \node_modules\@angular\core\fesm2015\core.js:29330
<anonymous> @ \node_modules\@angular\core\fesm2015\core.js:29300
invoke @ \node_modules\zone.js\fesm2015\zone.js:372
onInvoke @ \node_modules\@angular\core\fesm2015\core.js:28672
invoke @ \node_modules\zone.js\fesm2015\zone.js:371
run @ \node_modules\zone.js\fesm2015\zone.js:134
<anonymous> @ \node_modules\zone.js\fesm2015\zone.js:1276
invokeTask @ \node_modules\zone.js\fesm2015\zone.js:406
onInvokeTask @ \node_modules\@angular\core\fesm2015\core.js:28659
invokeTask @ \node_modules\zone.js\fesm2015\zone.js:405
runTask @ \node_modules\zone.js\fesm2015\zone.js:178
drainMicroTaskQueue @ \node_modules\zone.js\fesm2015\zone.js:582
◀ Promise.then ▶
scheduleMicroTask @ \node_modules\zone.js\fesm2015\zone.js:565
scheduleTask @ \node_modules\zone.js\fesm2015\zone.js:396
scheduleTask @ \node_modules\zone.js\fesm2015\zone.js:221
scheduleMicroTask @ \node_modules\zone.js\fesm2015\zone.js:241
scheduleResolveOrReject @ \node_modules\zone.js\fesm2015\zone.js:1266
then @ \node_modules\zone.js\fesm2015\zone.js:1410

**Expected behavior**
A clear and concise description of the error whatever the layer could be.

**Environment**
- RxJS version: 7.2.0

**Comment by cartant** [comment]
Without a minimal reproduction demonstrating the problem, this isn't actionable. Issue templates exist for a reason.

**Comment by JosepAlacid** [comment]
There's no minimal reproduction because there's no information on the error message.
And so is RXJS <-> Angular <-> VSCode  relation.
And so it's better to keep on promises and callback hell.

**Comment by kwonoj** [comment]
So far our experiences, majority of this error is coming from application configuration / runtime / bundler or other surroundings.

We'd like to investigate further, but there's 0 way we can without additional information. If you believe this is core rxjs bugs please provide some more context other wise team member cannot try to reproduce, or debug.

**Comment by JosepAlacid** [comment]
@kwonoj I can't be more grateful of the simple clue you gifted me in so little words.
On times where compassion is a depleted value, when an anonymous empathetic  is patient and kind, you get a great knowledge of who is who in this business.
Your apparently small attention just encouraged me to share all the information I can on this matter.
Let me show you my gratitude one more time.
