### ISSUE TITLE
Enable clang-format (or similar) for code style consistency

### ISSUE THREAD

**Issue by kwonoj** [ReactiveX/RxJS#665]
@robwormald 's suggestion to have style formatter over source code seems quite helpful for contributors as well as other automated tools like `lint`, `commitizen`, etcs.

Angular 2 uses [`clang-format`](https://github.com/angular/angular/blob/master/DEVELOPER.md#formatting-with-clang-format) for those purpose, might be good candidate for RxJS also.

**Comment by kwonoj** [comment]
Originated from https://github.com/ReactiveX/RxJS/pull/664#issuecomment-154325144

**Comment by blesh** [comment]
I'm on the fence about this one. I feel like we're in a good place with what we're already doing.

Can you describe how you think this will benefit us? I'm worried it will become another thing to slow down the build and hassle contributors.

**Comment by kwonoj** [comment]
I'm currently considering it as evaluation phases, instead of creating PR to be merged directly. As you mentioned, it need to be verified in aspect of

- does not impact current build
- should evaluate populated results

This is somewhat low priority. I'm ok this to be closed for now and reopened if it becomes more necessary.

**Comment by robwormald** [comment]
i don't love it in angular2, but it does keep stuff consistent. we enforce it on CI only - the expectation would be you don't have it as part of the build step at all, run it as a precommit hook, it reformats code, and then it checks and enforces formatting on CI. shouldn't have any impact on build time.

**Comment by blesh** [comment]
[Relevant information about clang-format with git pre-commit hooks in Angular 2](https://github.com/angular/angular/blob/c70e07fd1f672eb1fb70a12d08614979cd1e137f/DEVELOPER.md#formatting-with-clang-format)

**Comment by blesh** [comment]
Since the discussion has died out, I'm closing this for now.
