### ISSUE TITLE
Very slow comparative performance

### ISSUE THREAD

**Issue by vitaly-t** [ReactiveX/rxjs#6657]
I was adding RXJS support into my [prime-lib] library, and ran into some unexpected performance-related issues...

* Changing from a regular `for-of` for an iterable to `from(iterable)` results in huge > 100x times performance drop.
* Changing from an index iteration to a manual RXJS observable results again in ~20x performance loss.

I'm not sure what performance overhead RXJS is expected to create in its latest version, but I thought the figures that I got are way on the outside,  that's why I decided to open this issue.

**Here's complete test code:**

```ts
import {from, Observable} from 'rxjs';
import {cachePrimes} from 'prime-lib';

const cache = cachePrimes(1e7);

function test1() {
    const start = Date.now();
    let prime;
    const {fastIndex} = cache;
    for (let i = 0; i < fastIndex.length; i++) {
        prime = fastIndex.get(i);
    }
    console.log('test1 - index loop:', Date.now() - start);
}

function test2() {
    const start = Date.now();
    let prime;
    for (const p of cache) {
        prime = p;
    }
    console.log('test2 - for-of loop:', Date.now() - start);
}

function test3() {
    const start = Date.now();
    let p;
    from(cache).subscribe(a => {
        p = a;
    });
    console.log('test3/rxjs - from(cache):', Date.now() - start);
}

function test4() {
    const primes = new Observable(obs => {
        const {get, length} = cache.fastIndex;
        for (let i = 0; i < length; i++) {
            obs.next(get(i));
        }
        obs.complete();
    });
    const start = Date.now();
    let p;
    primes.subscribe(a => {
        p = a;
    });
    console.log('test4/rxjs - primes:', Date.now() - start);
}

test1();
test2();
test3();
test4();
```

**Output:**

```sh
test1 - index loop: 36
test2 - for-of loop: 27
test3/rxjs - from(cache): 3431
test4/rxjs - primes: 711
```

**Test Environment:**

* RXJS v7.4.0
* TypeScript v4.4.4
* prime-lib v0.4.1
* OS: Windows 10
* NodeJS: v16.13.0
* CPU: Ryzen 9, 5900X, 3.7Ghz

[prime-lib]:https://github.com/vitaly-t/prime-lib

**UPDATE**

And if we increase the number of items to 100mln at the top: `cachePrimes(1e8)`, then the results are these:

```sh
test1 - index loop: 346
test2 - for-of loop: 262
test3/rxjs - from(cache): 42118
test4/rxjs - primes: 6475
```

i.e. `from(iterable)` is 160 😮  times slower than `for-of` for the same iterable. And custom RXJS observable is 18 times slower than the same loop directly.

**Comment by vitaly-t** [comment]
Out of curiosity, I did a re-run of the above tests with the last v6.x of RXJS, for `1e8` items:

```sh
test1 - index loop: 307
test2 - for-of loop: 262
test3/rxjs - from(cache): 27612
test4/rxjs - primes: 1657
```

It shows us that v7 is ~2x slower processing a regular iterable, and ~4x slower processing a manual iterable, than v6.x

**Comment by voliva** [comment]
I changed the  test removing external dependencies, and also writing a test that represents "what I think Observable should minimally do as a black box" to better compare when closures & stuff is in the middle.

```ts
import { from } from 'rxjs';

function* myGenerator() {
  for (let i = 0; i < 1e7; i++) {
    yield i
  }
}

function test1() {
  const start = Date.now()
  let prime
  for (const p of myGenerator()) {
    prime = p
  }
  console.log('test2 - for-of loop:', Date.now() - start)
}

function test2() {
  const wrapIterable = <T extends any>(iterable: Iterable<T>) => {
    return {
      subscribe: (callback: (value: T) => void) => {
        for (const p of iterable) {
          callback(p)
        }
      },
    }
  }

  const start = Date.now()
  let p
  wrapIterable(myGenerator()).subscribe(a => {
    p = a
  })
  console.log('test5/custom - wrapIterable:', Date.now() - start)
}

function test3() {
  const start = Date.now()
  let p
  from(myGenerator()).subscribe(a => {
    p = a
  })
  console.log('test3/rxjs - from(cache):', Date.now() - start)
}

test1()
test2()
test3()
```

![image](https://user-images.githubusercontent.com/5365487/139818648-17e31d6d-aec4-445d-b711-d79e4dc4b3fd.png)

I think something worth noting here though is that we're talking about 10,000,000 synchronous emissions here. Any tiny overhead will definitely add up to a few milliseconds, and Observables do have some overhead.

**Comment by vitaly-t** [comment]
> I think something worth noting here though is that we're talking about 10,000,000 synchronous emissions here. Any tiny overhead will definitely add up to a few milliseconds

Worth noting (from my perspective):

* RXJS is designed to handle infinite streams, and it shouldn't chock on 1e7 data emissions.
* That tiny overhead, reaching over 100x times in performance loss, doesn't look so tiny.
* Getting 2x - 4x worse performance for my tests by going from v6 to v7 of RXJS looks bad

**Comment by voliva** [comment]
Sorry if I didn't express myself correctly - I was just pointing out that even a tiny overhead per message on that scale is going to have a large impact on the overall duration.

A microsecond of overhead per emission on a 10M-emission test would result in 10 seconds of total overhead.

On my machine, running against 10M emissions it adds an overhead of about 1 second (490 on for loop vs 1400 on RxJS), which means it's a 10th-million of a second of overhead per each emission: around 100 nanoseconds per emission. I agree that's a lot of overhead on applications where you need to deal with milions of events per second.

On another note,

> RXJS is designed to handle infinite streams, and it shouldn't chock on 1e7 data emissions. Consider piping data from a large file.

I'd say RxJS was more designed to work with I/O (e.g. asynchronous calls, which have lots of overhead per notification) rather than fast and efficient computing. Synchronous observables are often a pain point of RxJS.

Also, reading data from a large file has a way longer overhead than what RxJS have. I just tested reading a large file with node's file `createReadStream` default chunk size of 64KB, it takes 1300ms on my machine to read a 15259-chunk file (1GB). Imagine now a file with 10 milion chunks, it would probably take around 15 minutes, compared to the second of overhead that RxJS would add on that case.

**Comment by vitaly-t** [comment]
That's god to know :)

In the meantime, since a lot of time passed from when I asked, I wrote my own processor for iterables - [iter-ops](https://github.com/vitaly-t/iter-ops), is what I've been using in my projects. But I'm still using RXJS with Angular, because it is part of it.
