### ISSUE TITLE
"distinctUntilChanged", "retry" and "timeoutWith" docs are not rendered properly

### ISSUE THREAD

**Issue by jakovljevic-mladen** [ReactiveX/rxjs#6660]
- [ ] The [`distinctUntilChanged`](https://rxjs.dev/api/operators/distinctUntilChanged) operator docs is not being rendered properly. Please check the image:

  ![distinctUntilChanged](https://user-images.githubusercontent.com/28087049/139929309-79250117-de16-4a38-9c9a-26a19a79af9d.png)

  The operator [implementation](https://github.com/ReactiveX/rxjs/blob/62aca850a3/src/internal/operators/distinctUntilChanged.ts), however, contains the documentation, but for some reason, it is spread across multiple overloaded functions, so this might be causing the problems.

  Proposed fix in #6756.

- [x] The same case is with [`retry`](https://rxjs.dev/api/operators/retry) operator:

  ![retry](https://user-images.githubusercontent.com/28087049/141097084-a0ab706d-1694-44e2-8ccb-e202ec48897e.png)

  Fixed in #6850.

- [x] And [`timeoutWith`](https://rxjs.dev/api/operators/timeoutWith) operator:

  ![image](https://user-images.githubusercontent.com/28087049/141779741-674feb2c-3f88-41ed-b956-0de69ea5de2a.png)

  Fixed in #6858.

**Comment by yousafnawaz** [comment]
@jakovljevic-mladen any update on this? I still see no documentation for some operators..

**Comment by jakovljevic-mladen** [comment]
@yousafnawaz Nothing yet. I proposed a fix for  
`distinctUntilChanged` in #6756, but that PR is still in review.

I don't yet have fixes for the other two operators. I will work on them, but I can't promise when.

**Comment by jakovljevic-mladen** [comment]
@yousafnawaz, these issues are fixed and deployed to the [rxjs.dev](https://rxjs.dev) site. If you notice another issue, feel free to open new ticket.
