### ISSUE TITLE
Typescript eslint warning @typescript-eslint/no-unsafe-argument when using switchMapTo

### ISSUE THREAD

**Issue by prabh-62** [ReactiveX/rxjs#6665]
## Bug Report

**Current Behavior**
Using `switchMapTo` with @typescript-eslint gives `no-unsafe-argument` warning.

> Unsafe argument of type `OperatorFunction<any, number>` assigned to a parameter of type `OperatorFunction<number, number>`.eslint@typescript-eslint/no-unsafe-argument

**Expected behavior**
Using `switchMapTo` should not produce any `@typescript-eslint ` warnings.

**Reproduction**
- `npx @angular/cli@13 new web-apps --create-application false`
- `cd web-apps`
- `yarn ng g app admin-console --prefix ac --style css --routing`
-  `yarn ng add @angular-eslint/schematics@next`
- Add `.eslintrc.json` file at root manually
```json
{
  "root": true,
  "ignorePatterns": ["projects/**/*"],
  "plugins": [],
  "overrides": [
    {
      "files": ["*.ts"],
      "parserOptions": {
        "project": ["tsconfig.json"],
        "createDefaultProgram": true
      },
      "extends": [
        "eslint:recommended",
        "plugin:@typescript-eslint/recommended",
        "plugin:@typescript-eslint/recommended-requiring-type-checking",
        "plugin:@angular-eslint/all"
      ],
      "rules": {
        "@angular-eslint/sort-ngmodule-metadata-arrays": "off",
        "@typescript-eslint/no-unused-vars": "off",
        "@angular-eslint/use-injectable-provided-in": "off"
      }
    },
    {
      "files": ["*.html"],
      "extends": ["plugin:@angular-eslint/template/all"],
      "rules": {
        "@angular-eslint/template/i18n": "off"
      }
    }
  ]
}
```
- Edit `projects/admin-console/src/app/app.component.ts` and add
```ts
public complexFn() {
    console.log(lastValueFrom(interval(1000).pipe(switchMapTo(of(1)))));
  }
```
- `yarn ng lint --project admin-console`

- REPL or Repo link:
NA

```js
console.log(lastValueFrom(interval(1000).pipe(switchMapTo(of(1)))));
```

**Environment**
- Runtime: [e.g. Node v16, Chrome v95]
- RxJS version: 7.4.0
- (If bug is related) Loader, build configuration: [e.g webpack, angular-cli version, config] Angular CLI 13

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.
<img width="1166" alt="eslint_no_unsafe_switchmapTo" src="https://user-images.githubusercontent.com/13006107/140555828-a04971ad-2d0b-4f99-87fb-9349f497af08.png">

**Comment by cartant** [comment]
See https://github.com/ReactiveX/rxjs/issues/6536
