### ISSUE TITLE
new CDN URL for 7.x.x

### ISSUE THREAD

**Issue by fabioemoutinho** [ReactiveX/rxjs#6688]
**RxJS version:**
7.x

**Code to reproduce:**
go to docs https://rxjs.dev/guide/installation

**Expected behavior:**
there should be a link for 7.x.x CDN

**Actual behavior:**
there is no link for 7.x.x

**Additional information:**
I was able to find the url here: https://unpkg.com/rxjs@7.4.0/dist/bundles/rxjs.umd.js, it is different folder structure from 6.x.x

**Comment by jakovljevic-mladen** [comment]
Hi there. This is fixed in #6426, but the latest docs app version is not yet publicly available.
