### ISSUE TITLE
Support tslib 2.3.0+

### ISSUE THREAD

**Issue by wSedlacek** [ReactiveX/rxjs#6689]
## Bug Report

**Current Behavior**
https://github.com/ReactiveX/rxjs/blob/c2b3e88b9c2dbb9965833ca130b60d6466ef9552/package.json#L143
`tslib` is set to `~2.1.0` which conflicts with `^2.3.0` used in other projects causing duplicate tslib modules

```
├─┬ @ngrx/component-store@13.0.1
│ └── tslib@2.3.1 deduped
├─┬ @ngrx/effects@13.0.1
│ └── tslib@2.3.1 deduped
├─┬ @ngrx/entity@13.0.1
│ └── tslib@2.3.1 deduped
├─┬ @ngrx/router-store@13.0.1
│ └── tslib@2.3.1 deduped
├─┬ @ngrx/store-devtools@13.0.1
│ └── tslib@2.3.1 deduped
├─┬ @ngrx/store@13.0.1
│ └── tslib@2.3.1 deduped
├─┬ ng-packagr@13.0.8
│ ├─┬ injection-js@2.4.0
│ │ └── tslib@2.3.1 deduped
│ ├─┬ rxjs@6.6.7
│ │ └── tslib@1.14.1
│ └── tslib@2.3.1 deduped
├─┬ rxjs@7.4.0
│ └── tslib@2.1.0
├── tslib@2.3.1
```

This duplication is adds ~0.6 Kb to a compiled project.

**Expected behavior**
`tslib` to be versioned such that there are not conflicts with other commonly used packages.

See:
https://github.com/ng-packagr/ng-packagr/issues/2174#issuecomment-979220267

**Environment**
- RxJS version: `~7.4.0`

**Possible Solution**
Perhaps a version of `^2.1.0` would be suitable to continue supporting older versions of packages (like Angular 12) but also supporting Angular 13

**Comment by benlesh** [comment]
> Perhaps a version of ^2.1.0 would be suitable to continue supporting older versions of packages (like Angular 12) but also supporting Angular 13

This solution seems reasonable to me on it's face. I'm not sure if there are other implications. Generally TypeScript libraries aren't the best about honoring semver. 🤔

**Comment by wSedlacek** [comment]
Thank you for the timely resolution!

**Comment by benlesh** [comment]
I have a lot of stuff to go through, so the next release may not be until the end of the week or later. Thank you for your contribution!
