### ISSUE TITLE
Chrome doesn't display console.log after Observable completes

### ISSUE THREAD

**Issue by destus90** [ReactiveX/rxjs#6706]
### Describe the bug

Something interesting happens when you bind `console.log` of your browser as a callback for an Observable complete. Seems like it is not called since my logging container message is empty. The issue is not happening in Firefox (v94.0.2).

### Expected behavior

Console.log should be called.

### Reproduction URL

https://stackblitz.com/edit/rxjs-ziufsu?devtoolsheight=60

### Version

7.4.0

### Environment

Chrome v96.0.4664.45

**Comment by voliva** [comment]
Complete calls the function without passing in any parameter. Running `console.log()` on Chrome doesn't do anything, while on Firefox it does log an empty message.
