### ISSUE TITLE
ts-api-guardian is apparently dead.

### ISSUE THREAD

**Issue by benlesh** [ReactiveX/rxjs#6732]
The Angular team killed ts-api-guardian: https://github.com/angular/angular/pull/42735

It's no longer supported. Not sure what they're using now, but there's pretty much no way I'd ever use anything alpha for this again.

So:

1. We have to remove ts-api-guardian eventually
2. What should we replace it with, if anything? Does the tool have value?

Side note: I'm pretty ticked about this on a personal level because I was shamed into adding this and then support was just dropped without warning.

**Comment by benlesh** [comment]
This is one option: https://api-extractor.com/pages/setup/invoking/

**Comment by cartant** [comment]
FYI, I looked (briefly) at api-extractor when I was dealing with the internal bits - see [this comment](https://github.com/ReactiveX/rxjs/pull/6215#issuecomment-818632903) and something to be aware of is: https://api-extractor.com/pages/setup/configure_rollup/#an-important-limitation

**Comment by benlesh** [comment]
@cartant am I to understand that `rxjs/testing`, `rxjs/ajax`, `rxjs/operators`, et al, will not work properly with api-extractor? That's what it seems like, reading that. If that's the case, I guess we can't use it until we figure out what we're going to do there.

**Comment by benlesh** [comment]
Core Team: Still and issue... punting.

**Comment by tmair** [comment]
> @cartant am I to understand that `rxjs/testing`, `rxjs/ajax`, `rxjs/operators`, et al, will not work properly with api-extractor? That's what it seems like, reading that. If that's the case, I guess we can't use it until we figure out what we're going to do there.

When i looked into api-explorer for the handling of `@internal` that limitation came up too: https://github.com/ReactiveX/rxjs/issues/5768#issuecomment-703135265

**Comment by benlesh** [comment]
I really hate this issue. :\

Maybe just a straight diff-tool over .d.ts files would work? This is super annoying. I can't update packages with `npm audit fix` because of this dead package.

**Comment by cartant** [comment]
>  I can't update packages with `npm audit fix` because of this dead package.

Can we remove it as a dep and run it in the script via npx or something? That's pretty nasty, but 🤷‍♂️

**Comment by benlesh** [comment]
We removed it.
