### ISSUE TITLE
Marble diagram for delay() is incorrect in documentation

### ISSUE THREAD

**Issue by martinsik** [ReactiveX/rxjs#6741]
### Describe the bug

I'm preparing some RxJS guide for Angular devs and I've noticed that the marble diagram image for [`delay()`](https://rxjs.dev/api/operators/delay) is wrong. It looks like it delays also the `complete` notification which it shouldn't.
![](https://rxjs.dev/assets/images/marble-diagrams/delay.png)

I tested this also on stackblitz to make sure it doesn't delay `complete` notification: https://stackblitz.com/edit/rxjs-rtppth?devtoolsheight=60
The same scenario as in the marble diagram seems to be in unit tests where it doesn't expect `complete` to be delayed. https://github.com/ReactiveX/rxjs/blob/master/spec/operators/delay-spec.ts#L18

I've noticed that marble diagrams are now generated using [`swirly`](https://github.com/timdp/swirly) and should be defined in txt files in [docs_app/tools/marbles/diagrams](https://github.com/ReactiveX/rxjs/tree/master/docs_app/tools/marbles/diagrams) (?) but I guess I don't know how the process works any more (last time I checked it was generated from unit tests :)). The images in the docs come from [docs_app/src/assets/images/marble-diagrams](https://github.com/ReactiveX/rxjs/tree/master/docs_app/src/assets/images/marble-diagrams) so I guess they are 2 years old and might be outdated (?).

### Expected behavior

Marble diagram for `delay()` should reflect expected behavior as in unit tests https://github.com/ReactiveX/rxjs/blob/master/spec/operators/delay-spec.ts#L23

### Reproduction URL

https://stackblitz.com/edit/rxjs-rtppth?devtoolsheight=60

### Version

latest docs

**Comment by loadingwyn** [comment]
I just wasted one hour on it, and then I realized this is a mistake... 🤣
