### ISSUE TITLE
ignoreElements breaks inferred types in proceeding operators

### ISSUE THREAD

**Issue by robmcm** [ReactiveX/rxjs#6765]
### Describe the bug

Using the ignoreElements operator seems to break the type inference in operators preceding it. It looks like in version 7 the inferred type is now unknown, where as before it was any, causing the issue to now be more noticeable. 

Example: https://codesandbox.io/s/epic-dijkstra-79vsv?file=/src/index.ts:23-462 

### Expected behavior

Types shouldn't be broken when using ignoreElements.

### Reproduction code

```typescript
import { ignoreElements, tap } from "rxjs/operators";
import { of, merge } from "rxjs";

type TestObject = { payload: string };
const testInstance: TestObject = { payload: "test" };

const test$ = of(testInstance);

const output$ = merge(
  test$.pipe(
    tap((x) => x.payload), // x is typed as unknown here
    ignoreElements()
  ),
  test$.pipe(
    tap((x) => x.payload) // x is TestObject here
  )
);

output$.subscribe(console.log);
```

### Reproduction URL

https://codesandbox.io/s/epic-dijkstra-79vsv?file=/src/index.ts:23-462

### Version

7+

**Comment by robmcm** [comment]
I noticed a similar issue was reported in May last year (https://github.com/ReactiveX/rxjs/issues/5460) with version 6.5.5. This seems to be reproducible in codesandbox when updating to rxjs:7.5.2 and typescript: 4.5.4.

The resolution wasn't clear if it was indeed a non-issue with rxjs cc   @EnricoPicci @tonivj5 @cartant

**Comment by tonivj5** [comment]
@robmcm it's related to Typescript config and strictness:

- [Same error than your codesandbox](https://www.typescriptlang.org/play?strictFunctionTypes=false&isolatedModules=true#code/JYWwDg9gTgLgBAbzhAZgGjsA5gO2gUwFEAbfEfHGAZwxgEMw4BfOFKCEOAIigA8ArKlwDcAKFGoAFFwCeEAK5cMXesQDWwHFiXcYEHV3JcAlKLhwAdGGBh8ks+bj0wkycBhljcALwA+OADGEDhUEKQWxBBYbh4gFnoAqmC2UADCdFR2xtloDubYeFBEpOSUVJKm5pWWVPIARlQBUMB1dgh5cDj4vDAAXHCSAO7QACZefoHBoeGR0cNQY7mOcPhQ7FD9kqtQ4-5BIWH4EVHS29C9OtvGS45B4KQem7uTBzMnKgAW+Cs4IyYOTGMYiAA)
- [Without error](https://www.typescriptlang.org/play?isolatedModules=true#code/JYWwDg9gTgLgBAbzhAZgGjsA5gO2gUwFEAbfEfHGAZwxgEMw4BfOFKCEOAIigA8ArKlwDcAKFGoAFFwCeEAK5cMXesQDWwHFiXcYEHV3JcAlKLhwAdGGBh8ks+bj0wkycBhljcALwA+OADGEDhUEKQWxBBYbh4gFnoAqmC2UADCdFR2xtloDubYeFBEpOSUVJKm5pWWVPIARlQBUMB1dgh5cDj4vDAAXHCSAO7QACZefoHBoeGR0cNQY7mOcPhQ7FD9kqtQ4-5BIWH4EVHS29C9OtvGS45B4KQem7uTBzMnKgAW+Cs4IyYOTGMYiAA)


Difference:
![image](https://user-images.githubusercontent.com/7110786/149319361-f5ddfe75-a27f-4342-b67d-d643995772fa.png)
__`StrictFunctionTypes`__ is enabled

**Comment by cartant** [comment]
Closing this because if this is the way that TypeScript behaves with one of its `strict` is relaxed there's not much we can - or should - do about it, IMO.

**Comment by rgant** [comment]
[The docs say](https://www.typescriptlang.org/tsconfig#strictFunctionTypes):
> **Default:** `true` if [strict](https://www.typescriptlang.org/tsconfig#strict),,`false` otherwise.

Both the code sandboxes have strict enabled... so I would expect both should have `strictFunctionTypes` enabled. 

Regardless changing this setting in my tsconfig has no effect on my actual code. So I guess it's just a ` // eslint-disable-line @typescript-eslint/no-unsafe-argument` on those rare Observables I want to ignore emissions of. :-(
