### ISSUE TITLE
Internal implementation detail, do not use directly. Will be made internal in v8

### ISSUE THREAD

**Issue by ofirrifo** [ReactiveX/rxjs#6787]
### Describe the bug

I'm using angular 13 with rxjs 7.
I'm using the `observers.length` on the  angular @Output EventEmitter property in order to decide if
to show Close button.

```html
 <button *ngIf="closeClicked?.observers?.length" (click)="closeClicked.emit()">X</button>
```

I start to see in my code it going to be deprecated with RXJS 8 .
But now what are the alternative to check if Subject is has any subscriptions ?

### Expected behavior

- To have alternative way to check if Subject is has one or more subscriptions
- It should be documented as well 

Currently is just say -> deprecated Internal implementation detail, do not use directly. Will be made internal in v8
```typescript
export declare class Subject<T> extends Observable<T> implements SubscriptionLike {
    /** @deprecated Internal implementation detail, do not use directly. Will be made internal in v8. */
    observers: Observer<T>[];
```

### Version

7

**Comment by ajafff** [comment]
There's now a getter named `observed` that does the same:

https://github.com/ReactiveX/rxjs/blob/123a0f256e0022e87dfa249c895670ee745def53/src/internal/Subject.ts#L101-L103
