### ISSUE TITLE
retry(n) behavior

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#679]
This is a continuation of discussion at #674, focused solely on `retry`:

** DO NOT look at what currently happens in RxJS 4 or RxJS 5 **...

Given the following scenarios what should happen in your mind?

1. `Observable.of('x').concat(Observable.throw('bad')).retry(1)`
2. `Observable.of('x').concat(Observable.throw('bad')).retry(3)`

**Comment by staltz** [comment]
1. `(xx#)`
2. `(xxxx#)`

**Comment by blesh** [comment]
I think:

"try and if it fails retry once"
```
(xx#)
```

"try and if it fails retry three times"
```
(xxxx#)
```

**Comment by kwonoj** [comment]
I also would assume similar, try first + retry n as specified.

**Comment by Frikki** [comment]
`x + n * x`

**Comment by jinroh** [comment]
1. `(xx#)`
2. `(xxxx#)`

**Comment by roganov** [comment]
- (xx#)
- (xxxx#)

**Comment by blesh** [comment]
Okay, I think we can close this one as it seems we all agree that the current behavior of RxJS 5 is correct.
