### ISSUE TITLE
Subject<never> should not require a value when calling next()

### ISSUE THREAD

**Issue by mediantiba** [ReactiveX/rxjs#6791]
### Describe the bug

When using a subject to emit signals without any arguments, using `Subject<void>` works as expected; however, using `Subject<never>` doesn't compile and yields an error instead.

This works correctly!
```
const sub = new Subject<void>();
sub.next(); // OK
```
However, the following code doesn't compile!
```
const sub = new Subject<never>();
sub.next(); // Error: An argument for 'value' was not provided.
```

### Expected behavior

`Subject<never>` should not require a value when calling `next()`.
```
const sub = new Subject<never>();
sub.next();
```
The `never` type indicates that a value will never occur, hence it is a good type for such a use case where you only want to emit signals from subjects without actual values.

### Version

7.0.0

### Environment

- Runtime: Chrome V8
- RxJS: 7.0.0

**Comment by grimly** [comment]
There are no value that may match the `never` type, not even `undefined` which matches `void`.

A `(param: never) => unknown` function should simply not be able to be called.

**Comment by josepot** [comment]
> The never type indicates that a value will never occur

precisely because of this reason, a `Subject<never>` shouldn't be callable.

> hence it is a good type for such a use case where you only want to emit signals from subjects without actual values

I disagree. `void` is the correct type for emitting such signals.

Notice that when you define a function that receives an argument of type `never`, that function is not callable. E.g, this function is not callable:

```ts
function test(arg: never) {}
```

The same applies to a `Subject<never>`.

**Comment by mediantiba** [comment]
I see. Thanks for clarifying that. It makes sense to use `void` in that case.

Just to clarify, this was working prior to RxJS 7. We had `Subject<never>` in our codebase and we were using it to emit signals without passing a value.

Of course, this stopped working after updating to RxJS 7, that's why I raised this issue in the first place.
