### ISSUE TITLE
repeat(n) behavior

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#680]
a continuation of discussion at #674 

** DO NOT look at RxJS 4 or RxJS 5 behaviors ** 

What do you think should happen in the following scenarios?

1. `Observable.of('x').repeat(1)`
2. `Observable.of('x').repeat(3)`

**Comment by blesh** [comment]
"repeat 1 time"
```
(x)
```

"repeat 3 times"
```
(xxx)
```

**Comment by trxcllnt** [comment]
I vote (xx) and (xxxx) respectively. I read this as, "do x and repeat it once," and "do x and repeat it three times." reasonable people can disagree with this interpretation.

**Comment by staltz** [comment]
1. `(xx|)`
2. `(xxxx|)`

Here's my rationale why. I read it `foo.repeat(3)` as "*take foo and repeat it 3 times*" because it makes no assumption of what `foo` is. For instance, take the case where `foo` is `source.repeat(2)`. So `foo.repeat(3)` is actually `source.repeat(2).repeat(3)`. How many times should source happen? 5 times in total? Or 12?

I see it as 
`source.repeat(2) = '(xxx|)'`
Hence `'(xxx|)'.repeat(3)` is `(xxxxxxxxxxxx|)` (That's 12 x's)

**Comment by staltz** [comment]
Curiously, with the current RxJS 5 implementation, `source.repeat(2).repeat(3)` makes source happen **6 times** in total! That would definitely break the "*n in repeat(n) specifies how many times does the source happen in total*" argument.

**Comment by staltz** [comment]
I do recognize `2 * 3 = 6` though. *sigh*

**Comment by roganov** [comment]
ES6 defines `String.prototype.repeat` with semantics that yield `'abc'.repeat(2) === 'abcabc'`. It would probably make sense to align.

**Comment by staltz** [comment]
@roganov makes a lot of sense.

**Comment by blesh** [comment]
> ES6 defines String.prototype.repeat with semantics that yield 'abc'.repeat(2) === 'abcabc'. It would probably make sense to align.

That is an interesting and valid point. Thanks @roganov for pointing that out! I wasn't even thinking that way.

**Comment by trxcllnt** [comment]
>>ES6 defines String.prototype.repeat with semantics that yield 'abc'.repeat(2) === 'abcabc'. It would probably make sense to align.

>That is an interesting and valid point. Thanks @roganov for pointing that out! I wasn't even thinking that way.

I agree that it's interesting, but I'm not sure the same behavior should apply. Observable's `repeat()` (with no arguments) will repeat infinitely, but `String` repeat can't, since it's not lazy.

Ultimately it seems strange to me that `repeat(1)` is essentially the identity operation (`source.subscribe()` and `source.repeat(1).subscribe()` are identical).

**Comment by staltz** [comment]
I think "repeat(1)" reads as "repeat the source once", which in everyone's default mind is "abcabc".

PS: I'm not adamant about my opinions, I'm just pointing out some details.

**Comment by Frikki** [comment]
`x + n * x`

`repeat(0)` = `x + 0 * x`
`repeat(1)` = `x + 1 * x`
`repeat(3)` = `x + 3 * x`

Of course, `repeat(0)` is the same as leaving the operator off, thus, `repeat(1)` means it is _repeated_ once. Your suggestion, @blesh, is illogical because you suggest that `repeat(0)` and `repeat(1)` are the same.

**Comment by roganov** [comment]
@Frikki It's not "of course", it's just your opinion. IMO `repeat(0)` should either return `empty()` or throw error.

**Comment by Frikki** [comment]
@roganov Absolutely not. The meaning of _repeat_ is not an opinion. _Repeat_ is a definition, and it goes like this:

> to do, make, or perform again: to repeat an action.

If I ask you to _repeat once_ what you just said, how many times would you have said it in total? Once or twice?

**Comment by Frikki** [comment]
The operator that you are defining, @blesh, is called _times_ and not _repeat_. See, for example, http://underscorejs.org/#times

**Comment by roganov** [comment]
@Frikki
```
const me = ...
const meRepeating = me.repeat(1)
me.subscribe(observer2)  # saying
meRepeating.subscribe(observer2)  # saying
```
"How many times I said" depends on the observer. If ```observer1 === observer2```, then for this observer I said twice.

**Comment by trxcllnt** [comment]
@Frikki has a point. perhaps `1` is the identity for `times` (multiplication), but `0` is the identity for `repeat` (addition). @blesh @mattpodwysocki thoughts?

**Comment by Frikki** [comment]
@roganov
```js
const you = Observable.of(`hi`)
const youRepeating = you.repeat(1)
you.subscribe(me) // hi
youRepeating.subscribe(ben) // hi hi
```
How many items are emitted depends on the observable, not the observer. What the observer decides to observe is irrelevant to the observable.

**Comment by roganov** [comment]
@Frikki 
Me and you are having a discussion while Ben is not around.
Ben comes in and asks me to repeat my last argument.
And now "how many times I said my last argument" depends on the observer:
- for you, it's twice
- for Ben, just once.

**Comment by trxcllnt** [comment]
@roganov That may be true, but not for Observables.

**Comment by Frikki** [comment]
@roganov Actually, if you hadn’t already said it, how could Ben ask you to repeat it? Thus, said twice, in any case.

**Comment by roganov** [comment]
@trxcllnt 
Could you please elaborate? In my understanding, when I'm asked to repeat once, *counting from this moment* I'll have said the phrase once. To hear me say twice you have to be "subscribed" to both me saying first time and me repeating.
@Frikki 
When you're asked to repeat once, *new observers* which didn't hear you first time don't expect you to say the phrase twice.
It also IMO natural to reason about.
```
const me = Observable.of('hi');
const meAndMeRepeatingOnce = me.concat(me.repeat(1));
meAndMeRepeatingOnce.subscribe(observer)
```
You're arguing that `observer` should see `'hi', 'hi', 'hi'`, what I think is weird.

**Comment by trxcllnt** [comment]
@roganov but Observables are immutable, so it doesn't matter when you subscribe to them, or what Observables you've created from them. Since they don't share subscription side-effects, the `repeat` Observable isn't affected by the prior subscription to the original Observable.

**Comment by roganov** [comment]
@trxcllnt 
That's what I meant, but obviously failed to explain myself. When an `observable1` is asked to repeat once, it yields `observable2`, and for an observer to hear twice it must be subscribe to both `observable1` and `observable2`. But there may as well be other observers which would subscribe to either `observable1` or `observable2` and will hear only once.

**Comment by trxcllnt** [comment]
@roganov I still don't think that's correct, but maybe I don't follow.

**Comment by blesh** [comment]
> Your suggestion, @blesh, is illogical because you suggest that repeat(0) and repeat(1) are the same.

`repeat(0)` would be an empty observable.

**Comment by blesh** [comment]
FWIW..

1. Currently `repeat` aligns with the `String.prototype.repeat` semantics. 
2. Currently `repeat` aligns with RxJS 4.

I think we can probably leave it like it is.

**Comment by Frikki** [comment]
I’ll remember that next time somebody asks me to repeat what I just said. I’ll just say: "I already said it once, therefore I have repeated it." ;) Long live semantics. *erherm* I mean, long live repeating previous non-semantic implementations. Guess that the arguments presented by @staltz , @trxcllnt and myself doesn’t count much. I’m with @blesh, let’s leave it as is.

**Comment by trxcllnt** [comment]
@blesh I strongly suspect `0` is the correct identity for `repeat` (e.g.: "given `source.repeat(n)`, what value of `n` would yield an identical Observable to `source`?"), but I'm fine with leaving it the same as RxJS 4 for the sake of consistency.

**Comment by blesh** [comment]
> Guess that the arguments presented by @staltz , @trxcllnt and myself doesn’t count much

They definitely count, and I actually love "I already said it once, therefore I have repeated it.". I LOL'ed

if this were defined as `repeat(repetitions)`, I think it would be more clear. 0 repetitions is 0 times.

**Comment by trxcllnt** [comment]
@blesh yes, but in the same way that `n + 0 = n` is true, `source.repeat(0) = source` would also be true. that's what i mean by, 'zero is the identity for `repeat`'. anyway, I'm still fine either way.

**Comment by Frikki** [comment]
@blesh All good.

**Comment by blesh** [comment]
Okay, I'm going to close this then.

<3 <3 <3
