### ISSUE TITLE
Type definition error in release 7.X

### ISSUE THREAD

**Issue by don-hover** [ReactiveX/rxjs#6822]
### Describe the bug

We're trying to upgrade from rxjs v6.6.7 to 7.5.

When we do this, we're seeing TS errors in our build, like this:
```
src/lib/GraphqlClient.ts:18:39 - error TS7016: Could not find a declaration file for module 'rxjs'. '/node_modules/rxjs/dist/cjs/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/rxjs` if it exists or add a new declaration (.d.ts) file containing `declare module 'rxjs';`

18 import { Subject, Subscription } from 'rxjs';
                                         ~~~~~~
```

We don't see errors like this in v6.X.  It seems that the type definition file location has moved, and may not be correctly specified to be found by the TS compiler.

### Expected behavior

We should be able to import `rxjs` module with no TS errors.

### Reproduction code

```typescript
See above.
```

### Version

7.5.4

**Comment by kwonoj** [comment]
What version of typescript do you use? Is this same as pinned issue https://github.com/ReactiveX/rxjs/issues/6350?

**Comment by don-hover** [comment]
@kwonoj 
Typescript version: 4.1.5

Does version 7.X of `rxjs` require TS >=4.2?
That sounds like a breaking change, and I checked the README and changelog, and didn't see any reference to TS requirements changing.

**Comment by kwonoj** [comment]
it is clearly breaking change and we have explicitly listed those:

https://rxjs.dev/deprecations/breaking-changes

![image](https://user-images.githubusercontent.com/1210596/153520128-fdcef851-60ca-4bc1-9f00-95bf42101e59.png)

**Comment by don-hover** [comment]
@kwonoj 
OK, thank you for providing that link.

I'm used to seeing Breaking Changes listed in release notes as well, and didn't see this listed there.

Thanks.

**Comment by kwonoj** [comment]
It is not. This has been discussed several time already and please find closed issues for why. Simpliest reason - sine 7 uses 4.2 and above syntax you'll still get compiler error if you try to use old version.

I believe this has answered, closing.
