### ISSUE TITLE
mapTo etc deprecated in 7.5.5?

### ISSUE THREAD

**Issue by karptonite** [ReactiveX/rxjs#6884]
### Describe the bug

On updating to the latest rxjs, I'm getting deprecation warnings in my linter for some of the map functions. Was it intentional to deprecate these in a point release?

### Expected behavior

 Since they are being removed in 9.0, I would have expected the deprecation to come in the 8.0 release.

### Version

7.5.5

### Additional context

Not sure this counts as a bug, but since it wasn't in the release notes, I thought there was at least a chance it was added to 7.5.5 unintentionally.

**Comment by benlesh** [comment]
Yup. that's intentional. https://github.com/ReactiveX/rxjs/issues/6399
