### ISSUE TITLE
Proposal: Implement CompositeSubscription behavior in Subscription, remove other Subscription types

### ISSUE THREAD

**Issue by trxcllnt** [ReactiveX/RxJS#69]
Realistically, we can model all subscription logic with CompositeSubscription. Promoting composite behavior to the Subscription base class will reduce file size and complexity.

We can reduce the number of Subscription allocations by sharing a single Subscription instance between all intermediate Observers per subscribe call. Some operators don't allocate resources that need to be disposed. The ones that do (the flattening, splitting, and coincidence strategies) can add their inner Subscriptions to the Subscription shared between all Observers. This also reduces complexity inside those operators, as they don't have to worry about removing their inner subscriptions from the shared Subscription, because they'll be cleaned up when the shared Subscription is disposed (on throw, return, or dispose).

This is probably only feasible if Subscriptions store their inner subscriptions in a HashSet for O(1) insertion and removal.

**Comment by blesh** [comment]
Is this still necessary/possible now that Observer and Subscription have merged?

**Comment by blesh** [comment]
I believe after our in-person discussion, @trxcllnt, we agreed this approach probably wasn't possible with the merged Observer and Subscription. Closing for now, happy to reopen if we change our minds.
