### ISSUE TITLE
BUG: nextTick scheduler throwing when calling setImmediate in Chrome

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#690]
Looks like an oversight on my part. Here is a [JSBin](http://jsbin.com/bezugabeji/1/edit?html,js,console) demoing the broken behavior.

**Comment by blesh** [comment]
It's still a problem. :\

**Comment by kwonoj** [comment]
Is it repro on all chrome instances? I've able to repro with attached JSBin onetime, and following attempt does not shows same results.

**Comment by blesh** [comment]
@kwonoj I've got it fixed now. I could reproduce it in JSBin. It was a silly mistake. All better now.
