### ISSUE TITLE
Anatomy of a Marble Diagram svg is a dead link

### ISSUE THREAD

**Issue by alirezaghey** [ReactiveX/rxjs#6906]
### Describe the bug

On page [https://rxjs.dev/guide/operators](https://rxjs.dev/guide/operators) where a Marble Diagram is described the linked to svg image is not available.

Below line is the part in the repo where I suspect this needs to be amended.
https://github.com/ReactiveX/rxjs/blob/ef416f0b1139a0be013245e5058002b40fbbfe04/docs_app/content/guide/operators.md?plain=1#L106

### Expected behavior

The link were live and one could see it on the page.

### Version

7

### Additional context

I could send a PR if I knew where the correct svg is :D

**Comment by jakovljevic-mladen** [comment]
This is duplicate of #6534. Please read [this comment](https://github.com/ReactiveX/rxjs/pull/6894#issuecomment-1067300727) as well. Thanks for reporting.
