### ISSUE TITLE
Closure compiler warnings

### ISSUE THREAD

**Issue by kwonoj** [ReactiveX/RxJS#692]
This might not be big issue..

after PR https://github.com/ReactiveX/RxJS/pull/664, closure compiler gives warning like below

```
./dist/global/Rx.js:7401: WARNING - Keywords and reserved words are not allowed as unquoted property names in older versions of JavaScript. If you are targeting newer versions of JavaScript, set the appropriate language_in option.
    if (typeof root_1.root.Symbol.for === 'function') {
```

Assume some of generated codes are not supported old version of runtime.

**Comment by blesh** [comment]
No, I think it has to do with our Symbol polyfills. We're setting up `Symbol.for` and it wants us to set up `Symbol['for']`. We can do that, it's not a high priority though.

**Comment by robwormald** [comment]
it also doesn't like `.do`, `.throw`, etc. Meh.

**Comment by blesh** [comment]
Yeah... `switch`, `do`, `throw`, `for` etc.

**Comment by kwonoj** [comment]
Related with https://github.com/ReactiveX/RxJS/issues/733, if we're targeting IE9+ which supports ES5 (http://kangax.github.io/compat-table/es5/), what about suppress this warning for ES3 (https://github.com/google/closure-compiler/wiki/FAQ#i-get-invalid-property-id-errors-but-it-works-on-firefox) by targeting closure compiler to ES5?

**Comment by blesh** [comment]
>what about suppress this warning for ES3 (https://github.com/google/closure-compiler/wiki/FAQ#i-get-invalid-property-id-errors-but-it-works-on-firefox) by targeting closure compiler to ES5?

I'm fine with that.
