### ISSUE TITLE
`delay` regression after update to v7

### ISSUE THREAD

**Issue by Azbesciak** [ReactiveX/rxjs#6932]
### Describe the bug

Delay operator does not delay for the given time after some threshold. For shorter values like 12 hours, it works well.

### Expected behavior

delay is the same as expected

### Reproduction code

```typescript
import {of} from "rxjs";
import {delay, tap} from "rxjs/operators";

 let start: number;
  of(null).pipe(
    tap(() => {
      console.log("ASSIGNED");
      start = new Date().getTime();
    }),
    delay(63158404179),
  )
    .subscribe(() => console.log("DELAYED", new Date().getTime() - start));

// result like DELAYED 965
```

### Version

7.5.5

### Environment

Angular CLI: 13.3.2                                   
Node: 16.14.2                                         
Package Manager: npm 8.5.0                            
OS: win32 x64                                         
                                                      
Angular:                                              
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1303.2 (cli-only)      
@angular-devkit/core         13.3.2 (cli-only)        
@angular-devkit/schematics   13.3.2 (cli-only)        
@schematics/angular          13.3.2 (cli-only)

**Comment by kwonoj** [comment]
Since rxjs uses native browser runtime's timer, the maximum allowed value was always same for any time related operator. see https://github.com/ReactiveX/rxjs/issues/3015 for dupe, which was having same beahavior since v5.

**Comment by Azbesciak** [comment]
Not really, I have tested it on my previous 6.7 version and it did not finished "so fast". Of course, I did not wait 2 years, but it behaved in a different way. This is a regression.
