### ISSUE TITLE
fromEvent is not work

### ISSUE THREAD

**Issue by cieldon32** [ReactiveX/rxjs#6993]
### Describe the bug

Except for window and document， any NodeList,  cant be work

### Expected behavior

const $test1 = document.querySelectorAll("div[name=test1]");
    const test1Click = fromEvent($test1, "click").pipe(
      map(() => ({
        background: "red"
      }))
    );

hope this observable can be work

### Reproduction URL

https://codesandbox.io/s/nostalgic-sun-1kxy8m?file=/src/App.tsx

### Version

7.5.5

**Comment by voliva** [comment]
It does work correctly - On your sandbox your elements have attribute `data-name="test1"`, but your selector query is `[name="test1"]` instead.

If you console log the result of your query, you will see no elements were matched. Either change the attribute to be `name="test1"`, or change the selector to `[data-name="test1"]`

**Comment by kwonoj** [comment]
Your example, `$test1` returnes empty nodelist selector doesn't return target to choose. 

![image](https://user-images.githubusercontent.com/1210596/173326699-6eba7d61-758f-4dd2-9af0-0aca8efc889d.png)

This is not a rxjs issue. Please ensure there's correct target to attach.

**Comment by cieldon32** [comment]
sorry for these error, but in my projects, $test1 is ok, but the  fromEvent is not work
