### ISSUE TITLE
2 subscribe cause the source to be executed twice

### ISSUE THREAD

**Issue by wokier** [ReactiveX/rxjs#6998]
### Describe the bug

in 7.0.0-alpha.0 version
in angular, using httpclient, having 2 calls to subscribe on the observable, causes the http call to be done twice

### Expected behavior

do only 1 call

### Version

7.0.0-alpha.0

### Environment

"dependencies": {
    "@angular/animations": "~13.3.7",
    "@angular/cdk": "~13.3.7",
    "@angular/common": "~13.3.7",
    "@angular/compiler": "~13.3.7",
    **"@angular/core": "~13.3.7",**
    "@angular/forms": "~13.3.7",
    "@angular/localize": "~13.3.7",
    "@angular/material": "~13.3.7",
    "@angular/platform-browser": "~13.3.7",
    "@angular/platform-browser-dynamic": "~13.3.7",
    "@angular/router": "~13.3.7",
    "@ng-bootstrap/ng-bootstrap": "^12.1.2",
    "@ngx-translate/core": "^14.0.0",
    "@ngx-translate/http-loader": "^7.0.0",
    "@popperjs/core": "~2.11.5",
    **"@reactivex/rxjs": "~7.0.0-alpha.0",**
    "@types/crypto-js": "^4.1.1",
    "@types/lodash": "^4.14.180",
    "autoprefixer": "^10.4.7",
    "bootstrap": "~5.1.3",
    "bootswatch": "^5.1.3",
    "codelyzer": "~6.0.2",
    "crypto-js": "^4.1.1",
    "font-awesome": "^4.7.0",
    "lodash": "^4.17.21",
    "moment": "^2.29.3",
    "ngx-permissions": "~13.0.1",
    "primeflex": "^3.2.1",
    "tslib": "^2.3.0",
    "zone.js": "~0.11.6"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~13.3.6",
    "@angular/cli": "~13.3.6",
    "@angular/compiler-cli": "~13.3.6",
    "@types/jasmine": "~3.10.0",
    "@types/node": "^12.20.54",
    "jasmine-core": "~4.0.0",
    "karma": "^6.3.20",
    "karma-chrome-launcher": "^3.1.1",
    "karma-coverage": "~2.1.0",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "~1.7.0",
    "karma-sonarqube-unit-reporter": "^0.0.23",
    "puppeteer": "^14.4.1",
    "tslint": "~6.1.3",
    **"typescript": "~4.6.2"**
  }

### Additional context

rxjs now exists in 7.5.5 but i did'nt found a way to use it in a typescript context

**Comment by kwonoj** [comment]
Please provide correct repro codes isolated to rxjs to determine if this is core issue.

**Comment by kwonoj** [comment]
You should use rxjs pkg, those @reactivex scoped pkg is discontinued and no longer used. It is nothing related to typescript.

**Comment by wokier** [comment]
Your documentation keeps refering to it.
[https://rxjs.dev/guide/installation](https://rxjs.dev/guide/installation)
I had trouble finding the correct @types packages for typescript

**Comment by kwonoj** [comment]
Document is outdated for those. As said, please use rxjs package.

As this issue is diverged to original title and I believe package should provide necessary support, let me close this issue and recommend to use rxjs. If there is a core rxjs bug, please file a new issue.
