### ISSUE TITLE
concat documentation not showing up on rxjs.dev

### ISSUE THREAD

**Issue by carltheperson** [ReactiveX/rxjs#7009]
### Describe the bug

Some awesome documentation exists in the file [`src/internal/observable/concat.ts`](https://github.com/ReactiveX/rxjs/blob/master/src/internal/observable/concat.ts) as JSDoc.

However, it's not present on [rxjs.dev](https://rxjs.dev/api/index/function/concat).

What it currently looks like:
<img width="637" alt="image" src="https://user-images.githubusercontent.com/22200293/177014592-00024d38-9ce6-4646-a6be-4821faedbd68.png">

### Expected behavior

I expect the documentation to show up on [rxjs.dev](https://rxjs.dev/api/index/function/concat).

It would look like this:

<img width="637" alt="image" src="https://user-images.githubusercontent.com/22200293/177014617-15ecc933-7338-4974-884d-0e1692b15e6b.png">

### Reproduction code

```typescript
# Non-local: 
- Go to: https://rxjs.dev/api/index/function/concat

# Local:
- cd docs_app
- npm run docs
- npm run start
- Go to: http://localhost:4200/api/index/function/concat
```

### Reproduction URL

https://rxjs.dev/api/index/function/concat

### Version

7.5.5

### Additional context

I have narrowed the problem down to the TypeScript package in [dgeni-packages](https://github.com/angular/dgeni-packages#typescript-package).

It produces wrong information about the function overloads. I should probably open an issue there, but I want to know what you think about this first. Maybe I'm totally off. Also, I think you'll be quicker to respond and might be interested in the temporary fix I have.

## How to test this.

I wrote this function to debug this issue:

```js
function analyzeTypes(filename, docs) {
  const relavantDocs = docs.reduce((acc, doc) => {
    if (!doc.fileInfo?.relativePath?.includes(filename)) {
      return acc;
    }

    return [
      ...acc,
      {
        id: doc.id,
        docType: doc.docType,
        type: doc.type,
        // Note: These line numbers don't seem to match *exactly* with the file.
        // Not sure why. They almost match though.
        startingLine: doc.startingLine,
        endingLine: doc.endingLine,
        overloads: doc.overloads?.map((doc) => doc.id),
      },
    ];
  }, []);
  console.log();
  console.log(`-- TYPE ANALYSIS ${filename} --`);
  console.log();
  console.log(relavantDocs);
  console.log();
}
```

It can be defined and called in `docs_app/tools/transforms/angular-api-package/processors/filterContainedDocs.js`. Here is where and how I call it:

```js
// ...
$process: function (docs) {
      var docTypes = this.docTypes; // line 11
      analyzeTypes('internal/observable/concat.ts', docs);
// ...
```

The key information it logs is the `docType` of the docs array elements. Context: `filterContainedDocs` filters away certain docTypes; One being `'function-overload'`

## Current output of my function:

```js
[
  {
    id: 'index/concat',
    docType: 'function',
    type: '',
    startingLine: 5,
    endingLine: 6,
    overloads: [ 'index/concat()', 'index/concat(...args: any[])' ]
  },
  {
    id: 'index/concat()',
    docType: 'function-overload',
    type: '',
    startingLine: 7,
    endingLine: 7,
    overloads: undefined
  },
  {
    id: 'index/concat(...args: any[])',
    docType: 'function-overload',
    type: 'Observable<unknown>',
    startingLine: 10,
    endingLine: 114,
    overloads: undefined
  },
  {
    id: 'index/concat~args',
    docType: 'parameter',
    type: 'any[]',
    startingLine: 113,
    endingLine: 112,
    overloads: undefined
  }
]
```
Notice the third element with id `index/concat(...args: any[])`. It got a docType of `'function-overload'` (clearly wrong. It's not an overload) resulting in it being filtered away.

## Quickfix

I'm still not exactly sure **why** this happens. I do know one fast way to fix it though: change the order of the overloads.

[`src/internal/observable/concat.ts`](https://github.com/ReactiveX/rxjs/blob/master/src/internal/observable/concat.ts) contains two overloads at the beginning of the file. If we move them to the bottom of the file we now get another output from my function -

## Quickfix output of my function:

```js
[
  {
    id: 'index/concat',
    docType: 'function',
    type: 'Observable<unknown>',
    startingLine: 5,
    endingLine: 109,
    overloads: [ 'index/concat()', 'index/concat()' ]
  },
  {
    id: 'index/concat~args',
    docType: 'parameter',
    type: 'any[]',
    startingLine: 108,
    endingLine: 107,
    overloads: undefined
  },
  {
    id: 'index/concat()',
    docType: 'function-overload',
    type: '',
    startingLine: 110,
    endingLine: 111,
    overloads: undefined
  },
  {
    id: 'index/concat()',
    docType: 'function-overload',
    type: '',
    startingLine: 112,
    endingLine: 112,
    overloads: undefined
  }
]
```

It's now correct! (this produces the beautiful docs in the screenshot from "**Expected behavior**" )

I would be more than happy to submit a PR with this fix. I think a few other operators has this problem. I could run through them all to make sure the ordering allows for expected docs.

**Comment by jakovljevic-mladen** [comment]
> Also, I think you'll be quicker to respond and might be interested in the temporary fix I have.

Oh, I really hope that our quick response wasn't too late 😄

I wonder how this works in every other override we have? 🤔

E.g. [share()](https://github.com/ReactiveX/rxjs/blob/7.5.6/src/internal/operators/share.ts) operator also has two overloads: [`share<T>()`](https://github.com/ReactiveX/rxjs/blob/718be5bb8db5bb07ec9e4da8b5741e579bba6e62/src/internal/operators/share.ts#L49) and [`share<T>(options: ShareConfig<T>)`](https://github.com/ReactiveX/rxjs/blob/718be5bb8db5bb07ec9e4da8b5741e579bba6e62/src/internal/operators/share.ts#L51), but it seems that it [works as expected](https://rxjs.dev/api/index/function/share). Both of them are declared above the function implementation and JSDocs.

Can you please write here the output of your `analyzeTypes` for `share` operator?

Thanks a lot for the report and thorough explanation of the issue.

**Comment by carltheperson** [comment]
Found two other operators with this problem. This is the list so far:

- [`concat`](https://github.com/ReactiveX/rxjs/blob/718be5bb8db5bb07ec9e4da8b5741e579bba6e62/src/internal/observable/concat.ts)
- [`bindNodeCallback`](https://github.com/ReactiveX/rxjs/blob/718be5bb8db5bb07ec9e4da8b5741e579bba6e62/src/internal/observable/bindNodeCallback.ts)
- [`race`](https://github.com/ReactiveX/rxjs/blob/718be5bb8db5bb07ec9e4da8b5741e579bba6e62/src/internal/observable/race.ts)

I suspect the issue might have something to do with spread parameters.

### `analyzeTypes` results

<details><summary><b>concat</b></summary>

We want `id: 'index/concat(...args: any[])',` to be of type `function`

```
[
  {
    id: 'index/concat',
    docType: 'function',
    type: '',
    startingLine: 5,
    endingLine: 6,
    overloads: [ 'index/concat()', 'index/concat(...args: any[])' ]
  },
  {
    id: 'index/concat()',
    docType: 'function-overload',
    type: '',
    startingLine: 7,
    endingLine: 7,
    overloads: undefined
  },
  {
    id: 'index/concat(...args: any[])',
    docType: 'function-overload',
    type: 'Observable<unknown>',
    startingLine: 10,
    endingLine: 114,
    overloads: undefined
  },
  {
    id: 'index/concat~args',
    docType: 'parameter',
    type: 'any[]',
    startingLine: 113,
    endingLine: 112,
    overloads: undefined
  }
]
```

</details>

<details><summary><b>bindNodeCallback</b></summary>

We want `id: 'index/bindNodeCallback(callbackFunc: (args_0: any[], args_1: (err: any, ...res: any) => void) => void, resultSelector?: SchedulerLike | ((...args: any[]) => any), scheduler?: SchedulerLike)',` to be of type `function`

```
[
  {
    id: 'index/bindNodeCallback',
    docType: 'function',
    type: '',
    startingLine: 10,
    endingLine: 12,
    overloads: [
      'index/bindNodeCallback(callbackFunc: (...args: any[]) => void, resultSelector: (...args: any[]) => any, scheduler?: SchedulerLike)',
      'index/bindNodeCallback(callbackFunc: (args_0: any[], args_1: (err: any, ...res: any) => void) => void, resultSelector?: SchedulerLike | ((...args: any[]) => any), scheduler?: SchedulerLike)'
    ]
  },
  {
    id: 'index/bindNodeCallback(callbackFunc: (...args: any[]) => void, resultSelector: (...args: any[]) => any, scheduler?: SchedulerLike)',
    docType: 'function-overload',
    type: '(...args: any[]) => Observable<any>',
    startingLine: 4,
    endingLine: 9,
    overloads: undefined
  },
  {
    id: 'index/bindNodeCallback~callbackFunc',
    docType: 'parameter',
    type: '(...args: any[]) => void',
    startingLine: 6,
    endingLine: 6,
    overloads: undefined
  },
  {
    id: 'index/bindNodeCallback~resultSelector',
    docType: 'parameter',
    type: '(...args: any[]) => any',
    startingLine: 7,
    endingLine: 7,
    overloads: undefined
  },
  {
    id: 'index/bindNodeCallback~scheduler',
    docType: 'parameter',
    type: 'SchedulerLike',
    startingLine: 8,
    endingLine: 8,
    overloads: undefined
  },
  {
    id: 'index/bindNodeCallback(callbackFunc: (args_0: any[], args_1: (err: any, ...res: any) => void) => void, resultSelector?: SchedulerLike | ((...args: any[]) => any), scheduler?: SchedulerLike)',
    docType: 'function-overload',
    type: '(...args: any[]) => Observable<any>',
    startingLine: 16,
    endingLine: 127,
    overloads: undefined
  },
  {
    id: 'index/bindNodeCallback~callbackFunc',
    docType: 'parameter',
    type: '(args_0: any[], args_1: (err: any, ...res: any) => void) => void',
    startingLine: 122,
    endingLine: 122,
    overloads: undefined
  },
  {
    id: 'index/bindNodeCallback~resultSelector',
    docType: 'parameter',
    type: 'SchedulerLike | ((...args: any[]) => any)',
    startingLine: 123,
    endingLine: 123,
    overloads: undefined
  },
  {
    id: 'index/bindNodeCallback~scheduler',
    docType: 'parameter',
    type: 'SchedulerLike',
    startingLine: 124,
    endingLine: 124,
    overloads: undefined
  }
]

```

</details>

<details><summary><b>race</b></summary>

We want ` id: 'index/race(...sources: (Observable<T> | InteropObservable<T> | AsyncIterable<T> | PromiseLike<T> | ArrayLike<T> | Iterable<T> | ReadableStreamLike<T> | ObservableInput<T>[])[])',` to be of type `function`


```
[
  {
    id: 'index/race',
    docType: 'function',
    type: '',
    startingLine: 7,
    endingLine: 8,
    overloads: [
      'index/race()',
      'index/race(...sources: (Observable<T> | InteropObservable<T> | AsyncIterable<T> | PromiseLike<T> | ArrayLike<T> | Iterable<T> | ReadableStreamLike<T> | ObservableInput<T>[])[])'
    ]
  },
  {
    id: 'index/race()',
    docType: 'function-overload',
    type: '',
    startingLine: 9,
    endingLine: 9,
    overloads: undefined
  },
  {
    id: 'index/race(...sources: (Observable<T> | InteropObservable<T> | AsyncIterable<T> | PromiseLike<T> | ArrayLike<T> | Iterable<T> | ReadableStreamLike<T> | ObservableInput<T>[])[])',
    docType: 'function-overload',
    type: 'Observable<any>',
    startingLine: 10,
    endingLine: 54,
    overloads: undefined
  },
  {
    id: 'index/race~sources',
    docType: 'parameter',
    type: '(Observable<T> | InteropObservable<T> | AsyncIterable<T> | PromiseLike<T> | ArrayLike<T> | Iterable<T> | ReadableStreamLike<T> | ObservableInput<T>[])[]',
    startingLine: 51,
    endingLine: 50,
    overloads: undefined
  }
]

```

</details>

<details><summary><b>share (works)</b></summary>

We want `   id: 'operators/share(options: ShareConfig<T>)',` to be of type `function`

```
[
  {
    id: 'index/share',
    docType: 'function',
    type: 'MonoTypeOperatorFunction<T>',
    startingLine: 52,
    endingLine: 238,
    overloads: [ 'index/share()', 'index/share(options: ShareConfig<T>)' ]
  },
  {
    id: 'index/share~options',
    docType: 'parameter',
    type: 'ShareConfig<T>',
    startingLine: 144,
    endingLine: 143,
    overloads: undefined
  },
  {
    id: 'index/share()',
    docType: 'function-overload',
    type: 'MonoTypeOperatorFunction<T>',
    startingLine: 48,
    endingLine: 49,
    overloads: undefined
  },
  {
    id: 'index/share(options: ShareConfig<T>)',
    docType: 'function-overload',
    type: 'MonoTypeOperatorFunction<T>',
    startingLine: 50,
    endingLine: 51,
    overloads: undefined
  },
  {
    id: 'index/share~options',
    docType: 'parameter',
    type: 'ShareConfig<T>',
    startingLine: 52,
    endingLine: 51,
    overloads: undefined
  },
  {
    id: 'operators/share',
    docType: 'function',
    type: 'MonoTypeOperatorFunction<T>',
    startingLine: 52,
    endingLine: 238,
    overloads: [ 'operators/share()', 'operators/share(options: ShareConfig<T>)' ]
  },
  {
    id: 'operators/share~options',
    docType: 'parameter',
    type: 'ShareConfig<T>',
    startingLine: 144,
    endingLine: 143,
    overloads: undefined
  },
  {
    id: 'operators/share()',
    docType: 'function-overload',
    type: 'MonoTypeOperatorFunction<T>',
    startingLine: 48,
    endingLine: 49,
    overloads: undefined
  },
  {
    id: 'operators/share(options: ShareConfig<T>)',
    docType: 'function-overload',
    type: 'MonoTypeOperatorFunction<T>',
    startingLine: 50,
    endingLine: 51,
    overloads: undefined
  },
  {
    id: 'operators/share~options',
    docType: 'parameter',
    type: 'ShareConfig<T>',
    startingLine: 52,
    endingLine: 51,
    overloads: undefined
  }
]

```

</details>

# Solution

Putting the overloads below the actual function works like a charm. I would be happy to open up a PR with this @jakovljevic-mladen ? Let's get all this great docs back! Otherwise, I can open an issue on [dgeni-packages](https://github.com/angular/dgeni-packages#typescript-package).

I'll leave you with some before and after pics.

# Before

<img width="570" alt="image" src="https://user-images.githubusercontent.com/22200293/188284484-36058179-8f20-4e34-b421-70722eb076c2.png">

<img width="524" alt="image" src="https://user-images.githubusercontent.com/22200293/188284574-7792231e-e24b-4386-89e2-3442b010c1f1.png">


<img width="409" alt="image" src="https://user-images.githubusercontent.com/22200293/188284466-8e0059e2-bc23-4632-ab17-88a2e605b572.png">


# After

<img width="500" alt="image" src="https://user-images.githubusercontent.com/22200293/188284374-903f8501-49dc-444b-9641-4a8ed8cc7b9f.png">

<img width="500" alt="image" src="https://user-images.githubusercontent.com/22200293/188284582-bd76edda-dcd6-4b08-9a29-261d40795e1d.png">


<img width="500" alt="image" src="https://user-images.githubusercontent.com/22200293/188284519-0d96a9dc-aa8f-48a8-a9d5-cc28013139e7.png">

**Comment by jakovljevic-mladen** [comment]
> Putting the overloads below the actual function works like a charm.

Hmm, I wanted to try it myself before writing anything. I was afraid of the TS wanting to have overload implementation in the last overload declaration, which is the case here. `race` produces another error if we put it two overload from the top to bottom:

<img width="1170" alt="image" src="https://user-images.githubusercontent.com/28087049/188964655-f35f4dae-e572-4eed-9132-dfe664eda1b2.png">

The same happens with `concat`.

Also, `race` doesn't have proper types. The proper type includes `ObservableInput` which in case of `race` gets unwound to `Observable<T> | InteropObservable<T> | AsyncIterable<T> | PromiseLike<T> | ArrayLike<T> | Iterable<T> | ReadableStreamLike<T>` which is not correct either. Please take a look:

<img width="1012" alt="image" src="https://user-images.githubusercontent.com/28087049/188965050-4baaa8c1-e6e1-4318-b81e-dc1160585e18.png">

I'm not against having this issue temporarily fixed, but I'm afraid that this fix won't work due to TS errors.

Is there a way to open an issue on [dgeni-packages](https://github.com/angular/dgeni-packages), link this issue there and tag me so I can follow up?

Thanks a lot for bringing this up to our attention.

**Comment by jakovljevic-mladen** [comment]
The fix is now deployed to the [rxjs.dev](https://rxjs.dev/api/index/function/concat) app. Thanks for reporting.
