### ISSUE TITLE
Idea: TestScheduler to support marble diagrams for promises

### ISSUE THREAD

**Issue by staltz** [ReactiveX/RxJS#701]
It's annoying to have to fallback to timers and timeouts when testing code that needs to use Promises. Would be good to be able to write

```js
var e1 = promise('---|', 'theResolveValue'); // or ---#
```
just like we can write
```js
var e1 = cold('---(a|)', {a: 'someValue'});
```

As a by-product, test execution might get a bit faster.

**Comment by blesh** [comment]
I'm for it. But would this mean writing our own thennable pseudo-promise?  Or is there a promise  impl we can use that supports schedulers we can shoehorn?

**Comment by staltz** [comment]
I was hoping a regular virtual time `action.execute()` to resolve the promise would do the trick. Do you think it's possible?

**Comment by blesh** [comment]
That's not a bad idea. I like it.

**Comment by staltz** [comment]
See #745 for the reasons why I'm closing this issue.
