### ISSUE TITLE
[shareReplay] is not working as expected.

### ISSUE THREAD

**Issue by nandin-borjigin** [ReactiveX/rxjs#7012]
### Describe the bug

`shareReplay` is not working as expected.

### Expected behavior

`shareReplay` should preserve the last emitted value and notify the subsequent subscribers.

### Reproduction code

```typescript
import { Subject, shareReplay } from 'rxjs';

const a = new Subject<number>();
const b = a.pipe(shareReplay(1));

// uncommenting below line will make the output correct.
// but it's not desirable because the very reason for using
// shareReplay is to be able to subscribe lately and get the latest
// value notified.

// b.subscribe();

a.next(1); // this value should be preserved by `shareReplay`
b.subscribe(console.log); // this subscriber should be notified of 1, while it isn't.
a.next(2);

/**
Expected:
1
2

Actual:
2
*/
```

### Reproduction URL

https://stackblitz.com/edit/rxjs-49j31n?file=index.ts

### Version

7.5.5

**Comment by voliva** [comment]
> It seems like the underlying ReplaySubject subscribes to the source only when the resulting observable is being subscribed. This is not desirable, because shareReplay is expected to replay the last value from source upon subscription.

The problem is that observables are lazy, so essentially `const b = a.pipe(shareReplay(1));` does nothing, it will not subscribe to `a` until you tell it to.

You probably need something like `connectable`:

```ts
const a = new Subject<number>();
const b = connectable(a, {
  connector: () => new ReplaySubject(1)
});
b.connect(); // In here you tell `b` to subscribe to `a`, and use the internal `ReplaySubject` to replay the last value to every new observer
```

In essence is the same as having a `shareReplay` + subscribing, but it's maybe a bit more idiomatic.

**Comment by nandin-borjigin** [comment]
Thanks! @voliva
