### ISSUE TITLE
The second emit of [interval] is not reliable

### ISSUE THREAD

**Issue by nandin-borjigin** [ReactiveX/rxjs#7014]
### Describe the bug

Second emit of `interval` often comes earlier than expected.

### Expected behavior

`interval` should emit values at given frequency (within acceptable variation of course).

### Reproduction code

```typescript
interval(100)
  .pipe(
    map(() => Date.now()),
    bufferCount(2),
    take(10)
  )
  .subscribe(([a, b]) => console.log(b - a));
// above code logs the time difference between every 2 emits of `interval`
// please run multiple times to observe that the first different is often less than expected.
```

### Version

7.5.5

**Comment by kwonoj** [comment]
https://github.com/ReactiveX/rxjs/issues/530

Interval uses timer internally, so essentially same issue. We do not gaurantee precisions for the timer related codes as it relies on scheduler (user code) + native timer function. There can be some possible theories why second looks coming eariler, such as initial scheduling takes some time while second kicks in inside of scheduler.

In any case, we try our best to schedule as close. But we don't have guaranteed spec for those precisions.

**Comment by nandin-borjigin** [comment]
Is it possible to start the timer after initial setup is complete? So that the intervals between two emits are as close to the expected as possible, instead of receiving a mysterious second emit earlier.
