### ISSUE TITLE
ESM bundle is not usable in browser

### ISSUE THREAD

**Issue by muratcorlu** [ReactiveX/rxjs#7029]
### Describe the bug

ESM bundle files uses `import`s without file extentions. Check https://cdn.jsdelivr.net/npm/rxjs@7.5.6/dist/esm/index.js

As a result of this it's not possible to use ESM bundle directly in the browser. They all respond `404 Not Found`.

### Expected behavior

File imports in ESM bundles should include `.js` file extentions.

### Reproduction code

```html
<script type="module">
import { Observable } from "https://cdn.jsdelivr.net/npm/rxjs@7.5.6/dist/esm/index.js";

console.log(Observable);
</script>
```

Then you will see many network errors.

### Reproduction URL

https://jsfiddle.net/bh4y70fs/

### Version

7.5.6

**Comment by kwonoj** [comment]
Dupe: https://github.com/ReactiveX/rxjs/issues/4416
