### ISSUE TITLE
Testing BehaviorSubject with RxJS Marble

### ISSUE THREAD

**Issue by wazio** [ReactiveX/rxjs#7032]
### Describe the bug

I have an error testing BehaviorSubject using rxjs marbles.

Expected $.length = 1 to equal 2.
Expected $[0].notification.value = 2 to equal 1.

### Expected behavior

It shouldn't throw error. 

### Reproduction code

```typescript
const scheduler = new TestScheduler((actual, expected) => expect(actual).toEqual(expected));
scheduler.run(({ expectObservable }) => {
    const response$ = new BehaviorSubject(1);
    expectObservable(response$).toBe('ab', { a: 1, b: 2 });
    response$.next(2);
});
```

### Version

7.5.6

**Comment by benlesh** [comment]
The code is incorrect. `2` would arrive on the same frame, not the next frame.

In any case, I wouldn't recommend testing this in this manner.

```ts
const scheduler = new TestScheduler((actual, expected) => expect(actual).toEqual(expected));
scheduler.run(({ expectObservable }) => {
    const response$ = new BehaviorSubject(1);
    expectObservable(response$).toBe('(ab)', { a: 1, b: 2 });
    response$.next(2);
});
```
