### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by tamtakoe** [ReactiveX/rxjs#7033]
### Describe the bug

I've updated rxjs since 6 to 7 version in my module https://github.com/tamtakoe/oi-angular-resource

And now if I do test `npm test` in my demo project https://github.com/tamtakoe/nx-demo-angular-nest which is used this module

I see:
```
...//nx-demo-angular-nest/node_modules/rxjs/dist/types/internal/Subject.d.ts:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import { Operator } from './Operator';
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      at Runtime.createScriptFromCode (../../node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (../../node_modules/oi-angular-resource/fesm2015/oi-angular-resource-core.mjs:2:34)
```

### Expected behavior

No error during the test

### Reproduction code

```typescript
Run `npm test` inside demo project https://github.com/tamtakoe/nx-demo-angular-nest
```

### Version

7+

**Comment by kwonoj** [comment]
First, this is likely related with your module publish setup & build setup for the consumer. If you believe this is a core bug, please create a repro does not involve build tools & other framework.

Secondly, the error comes from https://github.com/tamtakoe/oi-angular-resource/blob/c96e5f8121cfd00a838fb9f6a0c74a2b53bc2141/projects/angular-resource/core/src/lib/reactive-resource.ts#L2 where you try to use internal api surface. RxJS strictly does not provide any gaurantee to try to import subpath under `/internal`, as it is named it is not a public interface. We do not block  importing it, but if you'd like to use it you may need to troubleshoot as well.

**Comment by tamtakoe** [comment]
@kwonoj Thx for explanation. Can I get AnonymousSubject from some public place?

**Comment by tamtakoe** [comment]
I implement AbstractObserver manually from http://reactivex.io/rxjs/file/es6/Subject.js.html#lineNumber119. I works with tests, but will be good to have a way to use it from library
