### ISSUE TITLE
webpack 5, ts-loader, rxjs 7 console warnings

### ISSUE THREAD

**Issue by Kishimy** [ReactiveX/rxjs#7047]
### Describe the bug

Using Rxjs 7+ with webpack and ts-loader got a bunch of warnings 

![image](https://user-images.githubusercontent.com/8350798/186879415-d1e1be38-edb2-4ef7-9911-1f90f6bece67.png)

### Expected behavior

No warnings at all

### Reproduction URL

https://github.com/Kishimy/rxjs_webpack_ts_warn_reproduce

### Version

7.5.6

### Environment

"rxjs": "^7.5.6"
"ts-loader": "9.3.1"
"typescript": "4.8.2"
"webpack": "5.74.0"

**Comment by kwonoj** [comment]
I do not believe this is a bug, RxJS exports can contain some of non-runtime (types) etcs webpack may try to resolve. If you believe this is a bug and RxJS have missing exports, please provide repro without webpack involved.
