### ISSUE TITLE
Update micro perf benchmark to get correct measurements

### ISSUE THREAD

**Issue by kwonoj** [ReactiveX/RxJS#705]
As discussed in PR https://github.com/ReactiveX/RxJS/pull/670 , https://github.com/ReactiveX/RxJS/pull/699, some of micro perf benchmark tests are using operators such as `map` other than operator to be tested. May need to update those test cases to reflect better, accurate results.

**Comment by blesh** [comment]
@kwonoj can we file more specific issues around this? I'm going to close this one for now because it's too generic to be actionable I think.

**Comment by kwonoj** [comment]
Definitely. Will open issues per specific if I could find.
