### ISSUE TITLE
Subject next method failed if it's called without parentheses 

### ISSUE THREAD

**Issue by maxsurgithub** [ReactiveX/rxjs#7053]
### Describe the bug

When `next` method of a `subject` was called without parentheses this error happens :

`Subject.ts:62 Uncaught TypeError: _this._throwIfClosed is not a function`

### Expected behavior

Both syntaxes are supposed to have the same behavior. I don't understand why when I call the `next` method with a simplified syntax, it crashes.

### Reproduction code

```typescript
// crash
    readonly loggedIn = new Subject<boolean>()

    constructor() {
        this.myUseCase.myObservableNextABooleen().subscribe({
            next: this.loggedIn.next, // <- crash here
            error: this.handleError, // <- works when error happens
        })
    }

    // works
    readonly loggedIn = new Subject<boolean>()

    constructor() {
        this.myUseCase.myObservableNextABooleen().subscribe({
            next: (loggedIn: boolean) => this.loggedIn.next(loggedIn),
            error: this.handleError,
        })
    }
```

### Version

7.5.5

### Environment

Browser

**Comment by kwonoj** [comment]
Those 2 are techinically different. Since subject is class, when you pass fn as param it loses context to this belongs to class instance. Using it via arrow fn is correct, or you may manually bind context via `bind`, or `call` .https://developer.mozilla.org/en-US/docs/web/javascript/reference/global_objects/function/bind

**Comment by maxsurgithub** [comment]
Oh, I finally understand why it crashes! It makes so much sense now. Thank you a lot for this reminder.
