### ISSUE TITLE
setTimeout in my project now has an incorrect type 

### ISSUE THREAD

**Issue by NogaMan** [ReactiveX/rxjs#7072]
### Describe the bug

After update to `7.5.7` every call of `setTimeout` in my project now has invalid return type
It used to be inherited from typescript's `lib.dom.d.ts`, being`number`
Now it's somehow inherited from `rxjs`, changing to `number | NodeJS.Timeout`

Not reproducing in `7.5.6`

### Expected behavior

The type should not change

### Version

7.5.7

**Comment by JeanMeche** [comment]
This has been fixed by ReactiveX/rxjs@c1a07b7 and shipped in 7.6 !
