### ISSUE TITLE
lastValueFrom will throw EmptyError if the Observable is complete BEFORE lastValueFrom is called

### ISSUE THREAD

**Issue by air2** [ReactiveX/rxjs#7116]
### Describe the bug

If I call `lastValueFrom` after the complete is called, it will fail

### Expected behavior

I expect `lastValueFrom` to give me the last value even if the Observable is complete before `lastValueFrom` from is called.

### Reproduction code

```typescript
it('test lastValueFrom', async () => {
    const ob = new BehaviorSubject<string>('')
    ob.next('value')
    ob.complete()
    const val = await lastValueFrom(ob)
    expect(val).toEqual('value') //this will fail
  })

  it('test lastValueFrom 2', async () => {
    const ob = new BehaviorSubject<string>('')
    ob.next('value')
    const val = lastValueFrom(ob)
    ob.complete()
    expect(await val).toEqual('value')
  })
```
```


### Reproduction URL

_No response_

### Version

7.5.7

### Environment

_No response_

### Additional context

_No response_

**Comment by voliva** [comment]
I don't think this is a bug. Completing a subject essentially closes it, so it will lose whatever value it has, and you won't be able to push new ones anymore:

```ts
const subject = new BehaviorSubject(1);
subject.next(2);
subject.complete();

subject.subscribe({
  next: v => console.log('value', v), 
  complete: () => console.log('complete')
});
// Only "complete" is logged
```

`lastValueFrom` can't get the value from an observable that just completes, so throwing EmptyError is correct.

**Comment by kwonoj** [comment]
https://rxjs.dev/api/index/function/lastValueFrom

> If the observable stream completes before any values were emitted, the returned promise will reject with [EmptyError](https://rxjs.dev/api/index/interface/EmptyError) or will resolve with the default value if a default was specified.

It is documented clearly as very first sentence.

**Comment by air2** [comment]
Yes, but values ARE emitted, so the documentation is not clear about this situation. In other words, you have to initiate `lastValueFrom` BEFORE the observable completes to get its last value. This is not stated anywhere. I would like the `lastValueFrom` to return the value of the observable if it is completed and there is a value, if there is not value it should indeed return a promise that rejects with `EmptyError`

**Comment by air2** [comment]
This issue should not be closed, it is not solved, the documentation is not clear IMHO. It only states that the promise rejects when there are NO values emitted. But that is not the case here.

**Comment by kwonoj** [comment]
No, values are _not_ emitted. Observable's fundamental contract is it works lazely for the each subscription. If you have an observable, but if there aren't any subscription, there is no actual value emission occurs. So if there is a observable have value then completes without subscription it is essentially does nothing. Once it's completed, subscribing it won't able to give any values for those reason.

We do not describe observable itself's behavior in each operator document. I believe doc for the operator suffeciently describes its behavior.
