### ISSUE TITLE
Cannot pass options to function wrapped inside RxJS.bindNodeCallback

### ISSUE THREAD

**Issue by adellamaggiora** [ReactiveX/rxjs#7118]
### Describe the bug

I want to use fs.readFile that has the current signature:
`fs.readFile: (path: number | fs.PathLike, options: { encoding: string, flag: string }, callback: Function) => void;`
but when I wrap it inside bindNodeCallback
`const customRead: (path: number | fs.PathLike) => Observable<Buffer> = bindNodeCallback(fs.readFile);`
I got this signature that doesn't allow me to pass options to fs.readFile function.

I would like to close this discussion.
[https://github.com/ReactiveX/rxjs/discussions/7075](url)
because this seems more a bug than a discussion.

### Expected behavior

Be able to pass options to the wrapped function.

### Version

7.5.6

**Comment by kwonoj** [comment]
You are keep creating dupe https://github.com/ReactiveX/rxjs/issues/7076 . Please do not. Also there are previous discussions like https://github.com/ReactiveX/rxjs/issues/5942 already. 

Core team member / community members read both places - not getting response does not mean you can create same questions in the different places.

**Comment by adellamaggiora** [comment]
IYou canceled the issue and keep the discussion open and nobody cares.
  
I don't want to dupe but the problem is still there.
  

  
Regards

**Comment by kwonoj** [comment]
issue and discussion is no difference in terms of visibility. Your question is already discussed in the closed issue.
