### ISSUE TITLE
UglifyJS `evaluate` options impacts Subscriber

### ISSUE THREAD

**Issue by robwalch** [ReactiveX/rxjs#7124]
### Describe the bug

Applying Rollup terser and uglify minification to rxjs 7 dependency breaks Subscriber stop notifications.

This issue was discovered after upgrading to v7. It does not occur with v6. I found that disabling the uglify `evaluate` option in our rollup config is a valid workaround. This diff image shows where Subscriber was impacted by uglifyjs with `evaluate` enabled by default:

![image](https://user-images.githubusercontent.com/333258/204360096-e2310da3-2973-4da8-abe9-5d69607a902e.png)

Arguments appear to be removed from `handleStoppedNotification`:

https://github.com/ReactiveX/rxjs/blob/fce9aa12931796892673581761bba1f7ceafabff/src/internal/Subscriber.ts#L71-L108

From UglifyJS project README https://github.com/mishoo/UglifyJS#compress-options:

> evaluate (default: true) — Evaluate expression for shorter constant representation. Pass "eager" to always replace function calls whenever possible, or a positive integer to specify an upper bound for each individual evaluation in number of characters.

### Expected behavior

Minified rxjs works as expected (stop notification not impacted).

### Reproduction code

rollup.config.ts
```typescript

import commonjs from '@rollup/plugin-commonjs';
import json from '@rollup/plugin-json';
import { terser } from 'rollup-plugin-terser';
import typescript from 'rollup-plugin-typescript2';

const { uglify } = require('rollup-plugin-uglify');

export default {
  input: 'src/main.js',
  output: {
    file: 'dist.js',
    name: 'Lib',
    exports: 'default',
    format: 'umd'
  },
  treeshake: {
    preset: 'smallest',
  },
  plugins: [
    typescript(),
    json(),
    commonjs(),
    nodeResolve({
      preferBuiltins: false,
      mainFields: ['jsnext:main', 'module', 'main'],
    }),
    terser({ compress: { passes: 3 } }),
    uglify({ compress: { evaluate: false } },
  ]
};
```

### Version

v7.5.7

### Additional context

I recognize this is likely an issue with UglifyJS. I'm sharing it here for transparency and in case there is interest in finding a workaround in the implementation.

**Comment by kwonoj** [comment]
I believe this should go uglifyjs upstream. We can't predict every minifier / optimizations specific optimization behavior, which tool itself should provide gaurantee normally written js to work with it.

**Comment by robwalch** [comment]
It seems that upon evaluation `config.onStoppedNotification` is null, and `handleStoppedNotification` would never evaluate in a way that would run the timeout. So, this code is eliminated from minified output:

```ts
function handleStoppedNotification(notification: ObservableNotification<any>, subscriber: Subscriber<any>) {
  const { onStoppedNotification } = config;
  onStoppedNotification && timeoutProvider.setTimeout(() => onStoppedNotification(notification, subscriber));
}
```
