### ISSUE TITLE
Infinete extraction of rxjs for nuxt

### ISSUE THREAD

**Issue by DrigaNicolai** [ReactiveX/rxjs#7135]
### Describe the bug

When I try to init nuxt project and it comes to extract rxjs I am getting stucked
![Screenshot_1](https://user-images.githubusercontent.com/90197647/209480056-f392547c-dd16-4839-93bf-2a369b72262b.png)

I tried to install rxjs appart and it was installed successfully with no error, but this step didn't help

### Expected behavior

Successfully extracted

### Version

rxjs@6.4.0

**Comment by kwonoj** [comment]
This looks like either nuxt or npm side issue. Any particular reason you think rxjs is the culprit?

**Comment by DrigaNicolai** [comment]
Another packages were extracted successfully and iy took not more than a few seconds for this. Also, I tried to use two different npm versions

**Comment by kwonoj** [comment]
Please ensure npm verbose logs and confirm this isn't npm side issue. After all published rxjs package is plain tgz installed by npm, we don't have any control over. If you can confirm this is really not npm issue, please create a codesandbox or similar to reproduce and file a new issue.
