### ISSUE TITLE
ShareReplayConfig['refCount'] typing does not accept a function

### ISSUE THREAD

**Issue by yastanotheruser** [ReactiveX/rxjs#7138]
### Describe the bug

According to the [docs](https://rxjs.dev/api/operators/shareReplay#reference-counting), `shareReplay` configuration should accept a function `refCount` that allows controlling unsubscription, but the `ShareReplayConfig` interface defines `refCount` as `boolean` only.

https://github.com/ReactiveX/rxjs/blob/630d2b009b5ae4e8f2a62d9740738c1ec317c2d5/src/internal/operators/shareReplay.ts#L5-L10

### Expected behavior

`ShareReplayConfig['refCount']` should have the same type as `ShareConfig['resetOnRefCountZero']`.

### Reproduction code

```typescript
// Typing issue, functionality is not affected.
```

### Version

7.8.0

**Comment by kwonoj** [comment]
> According to the [docs](https://rxjs.dev/api/operators/shareReplay#reference-counting)

Not sure which part of the docs refers it. Mind elaborate?

**Comment by yastanotheruser** [comment]
It doesn't explicitly mention what signature but this part is what I'm referring to:

> As of RXJS version 6.4.0 a new overload signature was added to allow for manual control over what happens when the operators internal reference counter drops to zero.

Since `refCount` is actually passed as a `resetOnRefCountZero` property to `share`, their types should be identical.

**Comment by kwonoj** [comment]
That sentence is backed up by

> If refCount is true, the source will be unsubscribed from once the reference count drops to zero, i.e. the inner [ReplaySubject](https://rxjs.dev/api/index/class/ReplaySubject) will be unsubscribed. All new subscribers will receive value emissions from a new [ReplaySubject](https://rxjs.dev/api/index/class/ReplaySubject) which in turn will cause a new subscription to the source observable.

Nothing explicilty said config will accept user function.

**Comment by yastanotheruser** [comment]
Boolean values don't allow to define manual control of the unsubscription, which is allowed by `share` (as shown in this [https://rxjs.dev/api/operators/share#example-with-notifier-factory-delayed-reset](example)) but not by `shareReplay`.

**Comment by Evertt** [comment]
@kwonoj why did you close this issue? This issue is totally valid. It's totally valid to wish to have the same configuration options that the `share()` operator offers. I would also like to be able to use `shareReplay()` and configure it to `resetOnRefCountZero` using a delay of a couple seconds.
