### ISSUE TITLE
Property 'currentObservers' is missing in type rxjs

### ISSUE THREAD

**Issue by baronkoko** [ReactiveX/rxjs#7145]
### Describe the bug

A typescript error occurs when using the `Subject` as a type. Can someone help with this, please?
```typescript
Argument of type '(subscription: Subject<void>) => void' is not assignable to parameter of type '(value: { closed: boolean; observers: { next: (value: void) => void; error: (err: any) => void; complete: () => void; }[]; isStopped: boolean; hasError: boolean; thrownError: any; lift: <R>(operator: Operator<void, R>) => Observable<...>; ... 11 more ...; toPromise: { ...; }; }, index: number, array: { ...; }[]) => ...'.
  Types of parameters 'subscription' and 'value' are incompatible.
    Property 'currentObservers' is missing in type '{ closed: boolean; observers: { next: (value: void) => void; error: (err: any) => void; complete: () => void; }[]; isStopped: boolean; hasError: boolean; thrownError: any; lift: <R>(operator: Operator<void, R>) => Observable<...>; ... 11 more ...; toPromise: { ...; }; }' but required in type 'Subject<void>'.
```
![image](https://user-images.githubusercontent.com/27996386/211334174-519b1c70-7cfd-4e6b-bdc4-41204b77fd1d.png)

### Expected behavior

When using the `Subject` as a type, typescript errors should not occur

### Reproduction URL

https://stackblitz.com/edit/nuxt-starter-hvcakf?file=app.vue

### Version

7.8.0

**Comment by kwonoj** [comment]
https://stackblitz.com/edit/rxjs-tpwmt9?file=index.ts 

Using rxjs only works fine. This seems related with `this` context in nuxt with its defining components for inner context values, which rxjs cannot control over. 

If you still think this is rxjs side issue, please create a repro without nuxt involved.
