### ISSUE TITLE
Add ES7 Observable Spec start event to Observer interface and trigger it

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#716]
It's an event that needs to be triggered _synchronously_ when subscription starts.

Basically:

```js
myObservable.subscribe({
  start(subscription) { console.log('subscription started'); }
});
```
Related #65 #266 #678

**Comment by trxcllnt** [comment]
@blesh I think I have a local branch with this in it. If not, I'm still happy to take this on.

**Comment by blesh** [comment]
I've already got the work underway, @trxcllnt... but I really appreciate the offer.

**Comment by blesh** [comment]
Closing this because it looks like it's not going to happen in the spec, and it's not necessary for anything in this lib at the moment.
