### ISSUE TITLE
DistinctUntilChanged callback doesn't behave as expected

### ISSUE THREAD

**Issue by daniel-seitz** [ReactiveX/rxjs#7179]
### Describe the bug

Referring to issue #7117 and despite this being closed I think this needs some further discussion because its either not working = bug or it is not intuitive enough.

I would assume that in the callback we need to determine if there is a difference between the previous and the current value in order to proceed or not.

The current implementation however seems like it is only using the last value that proceeded (after distinctUntilChanged) instead of the last value that was being emitted (incoming, before distinctUntilChanged) and hence some values for 'prev' are being swallowed.

### Expected behavior

I'd argue that 'prev' should always be the real incoming value. And that others would also intuitively assume so.

Alternatively an option could provide value. I'd definitively prefer the incoming one though.

#### !! Please have a sharp eye on the difference between previous and current in the console output !!
_Hint: previous is not the previous value_

```typescript
import { fromEvent, scan, Subject, of, tap, distinctUntilChanged } from "rxjs";

let myState = {
  userId: 1,
  isSaving: false
};
const state = new Subject();
state
  .pipe(
    tap((before) => console.log("incoming", JSON.stringify(before))),
    distinctUntilChanged((prev, curr) => {
      console.log("previous", JSON.stringify(prev));
      console.log("current ", JSON.stringify(curr));

      const isUserDifferent = prev.userId !== curr.userId;
      const isSavingFinished =
        prev.isSaving !== false && curr.isSaving === false;

      const shouldContinue = isUserDifferent || isSavingFinished;
      return !shouldContinue; // switched because false continues
    }),
    tap((after) => console.log("continued...", JSON.stringify(after)))
  )
  .subscribe((result) => {});

console.clear();

console.log("\n%cshould continue: (INITIAL)", 'color: green');
state.next(myState); // initial, should

console.log("\n%cshould continue: (user was changed)", 'color: red');
myState.userId = 2;
state.next(myState); // user changed, should

console.log("\n%cshould NOT continue: (just a save)", 'color: red');
myState.isSaving = true;
state.next(myState); // save, should not

console.log("\n%cshould continue: (save finished)", 'color: red');
myState.isSaving = false;
state.next(myState); // save finished, should


```
Also see the example on referred issue.

### Reproduction URL

[See issue here and look at the output in the console](https://codesandbox.io/embed/rxjs-playground-forked-x8xriv?fontsize=14&hidenavigation=1&theme=dark)
[Or have a look here](https://codesandbox.io/s/wonderful-thunder-6usy6z?file=/src/index.ts)
### Version

7.5.7

**Comment by kwonoj** [comment]
As original issue said, doc clearly refers how distinctuntilchanged behaves:

https://rxjs.dev/api/index/function/distinctUntilChanged

> if they are distinct in comparison to the last value the result observable emitted.

You should be able to create custom operator to have specific behavior you desire, instead of creating breaking changes to existing operator has been used for a long time.
