### ISSUE TITLE
DistinctUntilChanged passing same object reference leads to wrong previous value

### ISSUE THREAD

**Issue by daniel-seitz** [ReactiveX/rxjs#7180]
### Describe the bug

Nexting on a Subject the same object but with different properties into distinctUntilChanged doesn't lead to the expected outcome.

### Expected behavior

Things are checked by comparer, previous should have userId 1

### Reproduction code

```typescript
import { fromEvent, scan, Subject, of, tap, distinctUntilChanged } from "rxjs";

const state = new Subject();
state
  .pipe(
    tap((before) => console.log(JSON.stringify(before), "incoming")),
    distinctUntilChanged((prev, curr) => {
      console.log(
        JSON.stringify(prev),
        "previous, USERID is wrong <--- here is the error, userId has to be 1 !"
      );
      console.log(JSON.stringify(curr), "current ");

      // actually not the cause of the problem, doesnt matter what to do here
      return prev.userId === curr.userId;
    }),
    tap((after) => console.log("all good"))
  )
  .subscribe();

console.clear();

let myState = { userId: 1 };

console.log("\n%cINITIAL, emit 1, everything is good", "color: green");
state.next(myState);

console.log("\n%cBUG: emit 2 - (user was changed)", "color: red");
myState.userId = 2;
state.next(myState);
```

### Reproduction URL

https://codesandbox.io/s/rxjs-playground-forked-oiwzkv?file=/src/index.js

### Version

7.5.7

### Additional context

Please look into this before just closing the issue, this is really a bug.

**Comment by kwonoj** [comment]
It is not a bug. Rxjs observable does not allow mutated value for the same references. You should pass a new value to trigger emission.

**Comment by daniel-seitz** [comment]
@kwonoj a bit of discussion would be welcome before just closing all the issues here. 

I filed this issue because the comparator in distinctUntilChanged is supposed to be exactly for this kind of task:

To identify if its a new or the same value. Reference doesnt matter.

Hence I really consider this as a bug, the Object is different.
I assume that all state management libs pass the same reference - I could be mistaken though. Using ngxs here and got into tough with them as well.

**Comment by kwonoj** [comment]
All of the `issues` you created are basically dupe and have been either discussed or raised before. These aren't new, and we can't repeat same discussion each time new user have misunderstandings how operator suppose to work.

**Comment by daniel-seitz** [comment]
Did some refactoring and created an operator which does the job **comparing against incoming values**:

```
import { filter, map, Observable } from 'rxjs';

export const continueIfChanged = <T>(compare: (prev: T, curr: T) => boolean) => {
    return (source: Observable<T>): Observable<T> => {
      let prev: T; // last value

      return source.pipe(
        map((curr: T) => JSON.parse(JSON.stringify(curr))), // prevent mutating state
        filter((curr: T) => {
          if (!prev) {
            prev = curr;  // remember initial value
            return true;  // always continue when initial
          }
          
          const shouldContinue = compare(prev, curr); // evaluate passed condition
          prev = curr; // remember new value
          
          return shouldContinue; // continue if necessary
        }),
      );
  }
}
```

usage:
```
output$ = this.incoming$.pipe(
    continueIfChanged<YourType>((prev, curr) => {
          const shouldContinue = prev.id !== curr.id; // do your custom comparison
          return shouldContinue;
    }),
)
```
