### ISSUE TITLE
asapScheduler: Scheduling inside of an executing action only works once

### ISSUE THREAD

**Issue by benlesh** [ReactiveX/rxjs#7196]
Originally reported here: https://github.com/ReactiveX/rxjs/issues/6747#issuecomment-1360958245

Failing test:
```ts
  it('scheduling inside of an executing action more than once should work', (done) => {
    const results: any[] = [];

    asapScheduler.schedule(() => {
      results.push(1)
      asapScheduler.schedule(() => results.push(2));
      asapScheduler.schedule(() => results.push(3));
    });

    setTimeout(() => {
      // This should always fire after two recursively scheduled microtasks.
      expect(results).to.deep.equal([1, 2, 3]);
      done() 
    })
  })
```

**Comment by Dedicatus546** [comment]
it seems that `animateFrameScheduler` has the same problem, its source code is similar to `asapScheduler` , but when i execute the follow code:

```javascript
animationFrameScheduler.schedule(() => {
  results.push(1);
  animationFrameScheduler.schedule(() => results.push(2));
  animationFrameScheduler.schedule(() => results.push(3));
  animationFrameScheduler.schedule(() => results.push(4));
  animationFrameScheduler.schedule(() => results.push(5));
});
```

it can't get the `results` with `[1, 2, 3, 4, 5]`

![image](https://github.com/ReactiveX/rxjs/assets/48575405/5427887c-3aab-4594-aee3-b6e709336b8d)

but the native method is work well. 

![image](https://github.com/ReactiveX/rxjs/assets/48575405/0745fb8d-be07-44c3-a452-2699e161630d)

is it a bug ?

**Comment by Blafasel3** [comment]
> it seems that `animateFrameScheduler` has the same problem, its source code is similar to `asapScheduler` , but when i execute the follow code:
> 
> ```js
> animationFrameScheduler.schedule(() => {
>   results.push(1);
>   animationFrameScheduler.schedule(() => results.push(2));
>   animationFrameScheduler.schedule(() => results.push(3));
>   animationFrameScheduler.schedule(() => results.push(4));
>   animationFrameScheduler.schedule(() => results.push(5));
> });
> ```
> 
> it can't get the `results` with `[1, 2, 3, 4, 5]`
> 
> ![image](https://private-user-images.githubusercontent.com/48575405/279329977-5427887c-3aab-4594-aee3-b6e709336b8d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzMzQxOTAsIm5iZiI6MTcwMTMzMzg5MCwicGF0aCI6Ii80ODU3NTQwNS8yNzkzMjk5NzctNTQyNzg4N2MtM2FhYi00NTk0LWFlZTMtYjZlNzA5MzM2YjhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDA4NDQ1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxZmU1ZjEzYTZjYjk2ODM1MWE2ZDZlNjAxOGRmMTJiMzMwNDE0YzQzMGNiZWY0ODc3ZjE4MDI0ZGRkOTc0MWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q7X7PCddn-_ADXYRfuHo3Ig0TUN573WjYygirYfzX0c)
> 
> but the native method is work well.
> 
> ![image](https://private-user-images.githubusercontent.com/48575405/279330102-0745fb8d-be07-44c3-a452-2699e161630d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzMzQxOTAsIm5iZiI6MTcwMTMzMzg5MCwicGF0aCI6Ii80ODU3NTQwNS8yNzkzMzAxMDItMDc0NWZiOGQtYmUwNy00NGMzLWE0NTItMjY5OWUxNjE2MzBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDA4NDQ1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1NjBjYjg5YmNkNjEwZDhlNWZkNDIxODg2YjJlNzg3NWI5ODlkY2QyZGU4ZTIwNWI1MTA2MjkyNWUzMDc0YWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9RHYU24HGOCbQU5zQXwUNumrxJR4aZ9bxDdllSx-_yg)
> 
> is it a bug ?

It seems our team ran into this issue regarding the `animationFrameScheduler `as well. We are using the ng-scrollbar library and when scrolling to an particular element, it just happens sometimes that the callback scheduled in the following line https://github.com/MurhafSousli/ngx-scrollbar/blob/master/projects/ngx-scrollbar/smooth-scroll/src/smooth-scroll-manager.ts#L136 is never executed. It just seems to die and only hard refreshing (CTRL+F5) the page actually fixes the issue.
