### ISSUE TITLE
Update Generics/Typing for TypeScript

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#72]
I really half-assed the typings in the library so far (currently in the `lift` branch). It would be good to make a pass through this and perhaps add proper TypeScript generics to Observable. It's just not a priority because it's sugar.

**Comment by trxcllnt** [comment]
I can do this.

**Comment by blesh** [comment]
:+1:

**Comment by xgrommx** [comment]
@blesh Basically `flatMap` is combination from `merge(Infinity)` and `map` =)

**Comment by Yshayy** [comment]
:+1:

**Comment by trxcllnt** [comment]
WIP on [generics](https://github.com/trxcllnt/RxJS/tree/generics) branch. Will be adding interfaces and organizing the source like [RxJava](https://github.com/ReactiveX/RxJava/tree/1.x/src/main/java/rx).

**Comment by blesh** [comment]
Noted. Thanks @trxcllnt
