### ISSUE TITLE
www.benlesh.com -> https://benlesh.com/

### ISSUE THREAD

**Issue by pelikhan** [ReactiveX/rxjs#7210]
### Describe the bug

Looks like the www. does not redirect. This one works https://benlesh.com/

### Expected behavior

Open bio page

### Version

docs

**Comment by jakovljevic-mladen** [comment]
Hi, thanks for reporting.

Since the personal site of our team lead is out of scope of this project, I will close this issue as irrelevant.

**Comment by tmair** [comment]
I guess what @pelikhan ment, is the link on the Team page (https://rxjs.dev/team?group=Core%20Team) linking to the homepage of Ben.

**Comment by jakovljevic-mladen** [comment]
Oh, sorry, makes sense now. The original report didn't mention this page. I'll reopen.
