### ISSUE TITLE
Bike-shedding: switchFirst and switchMapFirst names

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#722]
Given that we've migrated to `strategy` and `strategyMap` names, do the names `switchFirst` and `switchMapFirst` make sense?  Should it be `switchFirstMap`?

Furthermore is the strategy name `switchFirst` the best choice?

**Comment by staltz** [comment]
I'd also try to find a name other than `switchFirst`. I actually couldn't figure out what it does, and similarity with `switch` didn't help.

I'll just brainstorm some names to get us kickstarted:
- `proceed` and `proceedMap`
- `finish` and `finishMap`
- `thorough` and `thoroughMap`
- `deal` and `dealMap`
- `entire` and `entireMap`
- `switchEntire` and `switchEntireMap`
- `ignoreUntilComplete` and `ignoreUntilCompleteMap`
- `persist` and `persistMap`
- `drag` and `dragMap`

...

**Comment by blesh** [comment]
> deal

Haha... just "deal"

**Comment by blesh** [comment]
BUMP: I think we still need to come up with something here.

**Comment by staltz** [comment]
Wait a minute, how is switchFirst different to mergeAll with concurrency=1?

**Comment by blesh** [comment]
> Wait a minute, how is switchFirst different to mergeAll with concurrency=1?

it drops all incoming observables until the first one it receives completes.

**Comment by staltz** [comment]
And I just noticed we don't have tests for the concurrency parameter given to mergeAll. But you see what I mean right? With concurrency=1, mergeAll ignores all incoming observable until the active(s) one(s) complete.

**Comment by staltz** [comment]
Alright, I noticed the difference. `mergeAll(1)` doesn't drop incoming observables, `switchFirst` does.

**mergeAll(1)**
```js
    var x = hot(   '--------a---b---c--|               ');
    var y = hot(   '--------------d--e---f---|      ');
    var z = hot(   '-----------------------g--h---i---|');
    var e1 = hot(  '------x----y--------z-------------|', { x: x, y: y, z: z });
    var expected = '--------a---b---c----f----h---i---|';

    expectObservable(e1.mergeAll(1)).toBe(expected);
```

**switchFirst**
```js
    var x = hot(   '--------a---b---c--|               ');
    var y = hot(   '--------------d--e---f---|      ');
    var z = hot(   '-----------------------g--h---i---|');
    var e1 = hot(  '------x----y--------z-------------|', { x: x, y: y, z: z });
    var expected = '--------a---b---c------g--h---i---|';

    expectObservable(e1.switchFirst()).toBe(expected);
```
