### ISSUE TITLE
Inconsistent iif type checking behavior in typescript 5.0.2

### ISSUE THREAD

**Issue by moniuch** [ReactiveX/rxjs#7225]
### Describe the bug

Given the below snippet 
```ts
const source$ = from([{ firstName: 'Brian', lastName: 'Smith' }, null]);
const err = new Error('my error');

const final$ = source$.pipe(
  switchMap((o) =>
    iif(
      () => !o,
      throwError(() => err),
      of(`${o.firstName} ${o.lastName}`)
    )
  )
);
```

I'm getting different results depending on IDE, and I am not sure I'm using the operators correctly
(rxjs 7.8.0 and -  typescript 5.0.2 in both cases)

**VSCode** (complains about `o` being possibly `null`)
![image](https://user-images.githubusercontent.com/681956/226199778-9bcc4095-4463-4121-9ea9-59a1dc7198cf.png)

**Stackblitz** 
![image](https://user-images.githubusercontent.com/681956/226199902-1226dd78-da01-4215-a818-3970ddb862da.png)

In both cases `final$` is reported as `Observable<string>`

### Expected behavior

Given that we catch the null condition in `iif` the typescript should not complain in the truthy execution branch

### Reproduction code

```typescript
import { of, switchMap, from, throwError, iif } from 'rxjs';


const source$ = from([{ firstName: 'Brian', lastName: 'Smith' }, null]);
const err = new Error('my error');

const final$ = source$.pipe(
  switchMap((o) =>
    iif(
      () => !o,
      throwError(() => err),
      of(`${o.firstName} ${o.lastName}`)
    )
  )
);
```
```


### Reproduction URL

_No response_

### Version

7.8.0

### Environment

_No response_

### Additional context

_No response_

**Comment by demensky** [comment]
There are no errors on stackblitz because TypeScript does not run in strict mode on it by default:

<img width="842" src="https://user-images.githubusercontent.com/10235949/226201065-df2ee54a-e96f-4222-b040-9ae85c03e7d6.png">

I recommend simplifying to this:

```ts
import { of, switchMap, from } from 'rxjs';

const source$ = from([{ firstName: 'Brian', lastName: 'Smith' }, null]);

const final$ = source$.pipe(
  switchMap((o) => {
    if (!o) {
      throw new Error('my error');
    }

    return of(`${o.firstName} ${o.lastName}`);
  })
);
```

Or even to this:

```ts
import { from, map } from 'rxjs';

const source$ = from([{ firstName: 'Brian', lastName: 'Smith' }, null]);
const err = new Error('my error');

const final$ = source$.pipe(
  map((o) => {
    if (!o) {
      throw new Error('my error');
    }

    return `${o.firstName} ${o.lastName}`;
  })
);
```

**Comment by moniuch** [comment]
Ah ok, thanks for this `strict: true` lesson, I wasn't aware of it. Closing then. Sorry for the noise.

**Comment by demensky** [comment]
The most appropriate code for your version:

```ts
const source$ = from([{firstName: 'Brian', lastName: 'Smith'}, null]);
const err = new Error('my error');

const final$ = source$.pipe(
  switchMap((o) =>
    !o
      ? throwError(() => err)
      : of(`${o.firstName} ${o.lastName}`),
  )
);
```
