### ISSUE TITLE
Not all flavors of anonymous observers work properly.

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#723]
I noticed that in some scenarios, if you pass an incomplete anonymous observer, which should totally work, it throw errors... for example:

```js
Observable.of(1).subscribe({ next(x) { console.log(x); } });
```

Also, I've noticed that the Observer interface doesn't allow for optional handlers, so we need to adjust for that.

**Comment by trxcllnt** [comment]
@blesh I thought we used to have the same logic in the `Subscriber` constructor as we do in the static `create` method?

**Comment by blesh** [comment]
It's just silly bugs around not checking to see if destination actually has a `complete` before calling it, for example.
