### ISSUE TITLE
FromEvent Docs: No overload matches this call. 

### ISSUE THREAD

**Issue by sumitrawat10** [ReactiveX/rxjs#7245]
### Describe the bug

As per the https://rxjs.dev/api/index/function/fromEvent in order to use this operator with capture option we can pass the three arguments to it. 
![image](https://user-images.githubusercontent.com/47861908/230757028-1862d9c2-b525-4ae1-beef-804e3356a63e.png)
But LSP is showing the following error.
![image](https://user-images.githubusercontent.com/47861908/230757050-26cb865a-a883-4fb2-8d20-e2303ded1da1.png)

### Expected behavior

As per the documentation.
**DOM EventTarget**

This is an object with addEventListener and removeEventListener methods.

In the browser, addEventListener accepts - apart from event type string and event handler function arguments - **optional third parameter, which is either an object or boolean, both used for additional configuration how and when passed function will be called.** When [fromEvent](https://rxjs.dev/api/index/function/fromEvent) is used with event target of that type, you can provide this values as third parameter as well.

### Reproduction code

```typescript
Open the following example in Docs using StackBlitz "Use addEventListener with capture option" (https://rxjs.dev/api/index/function/fromEvent)
```

### Version

~7.5.0

**Comment by demensky** [comment]
The problem is not in `EventTarget` but in the last argument.

<img width="374" alt="Example" src="https://user-images.githubusercontent.com/10235949/230764518-7a324a1e-8064-4d51-858f-b042dce2d265.png">

**Comment by sumitrawat10** [comment]
@demensky in the documentation it says that third argument is either or boolean or an object. If it's changed now ... Should I make ammendment in the docs and send a PR ?

**Comment by demensky** [comment]
@sumitrawat10
I can't find it in [the official documentation](https://rxjs.dev/api/index/function/fromEvent). Maybe you are confused with [the native method `addEventListener`](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener) in which it is once possible to pass `boolean`?

**Comment by sumitrawat10** [comment]
![Screenshot_20230409-232958.jpg](https://user-images.githubusercontent.com/47861908/230788887-77cd2474-47bf-42a6-b9a5-462a85bb6c58.jpg)

 In line 3.

Though at the top it says 'Use addEventListener with capture option'.
