### ISSUE TITLE
Type definition with Observable.of

### ISSUE THREAD

**Issue by kwonoj** [ReactiveX/RxJS#725]
Below snippet

`Rx.Observable.of(25, Rx.Scheduler.immediate);`

will raise complains 
```
error TS2453: The type argument for type parameter 'T' cannot be inferred from the usage. Consider specifying the type arguments explicitly.
  Type argument candidate 'number' is not a valid type argument because it is not a supertype of candidate 'ImmediateScheduler'.
```

with typescript compiler, by current definition for `static of` is specified as 
`<T>(...values: Array<T | Scheduler>) => Observable<T>;`

Scheduler is also considered as one of value parameter candidate of type inference. Using rest parameter makes hard to have scheduler as separate parameter like

`(...value:Array<any>, scheduler?:any)` since rest parameter should be last parameter of function.

**Comment by blesh** [comment]
I feel like you're not allowed to have rest parameters as the first argument in TypeScript, but perhaps I'm wrong. Because if you were, this wouldn't have been a problem to begin with.

Because of that current limitation of TypeScript, users will probably have to explicitly set the generic type: `Observable.of<number>(25, Rx.Scheduler.immediate)`

**Comment by kwonoj** [comment]
> I feel like you're not allowed to have rest parameters as the first argument

: that is correct. Above 'rest parameter should be last..` is constraint of typescript.

`error TS1014: A rest parameter must be last in a parameter list.`

**Comment by kwonoj** [comment]
> users will probably have to explicitly set the generic type

: I think this'll work for now until find out some way to resolve this. Writing issue for reference anyone who'll meet this to have understandings.

I'll close issue for now, will reopen if there's way to resolve it.
