### ISSUE TITLE
Observer function called twice with "lastValueFrom"

### ISSUE THREAD

**Issue by Zagrios** [ReactiveX/rxjs#7251]
### Describe the bug

I've experienced some strange behaviors, so I decided to add logs in the observer function passed to the "Observable" constructor. Surprisingly, some of the logs are logged twice.

Here are the logs I got at the end:

```
CREATE OBSERVABLE
SUBSCRIBE
SUBSCRIBE
1
CHECK
CHECK
2
CHECK
CHECK
...
```

This not appen if i remove "lastValueFrom" at the end (see the Reproduction code)

### Expected behavior

The expected behavior is to not execute the observer function twice, so the desired log output should look like this:

```
CREATE OBSERVABLE
SUBSCRIBE
1
CHECK
2
CHECK
...
````

### Reproduction code

```typescript
console.log("CREATE OBSERVABLE")
const obs = new Observable<number>(obs => {
    console.log("SUBSCRIBE");
    let i = 0;
    setInterval(() => {
        i++;
        obs.next(i);
        console.log("CHECK");
    }, 1000);
});

obs.subscribe({
    next: v => console.log(v),
    complete: () => console.log("completed")
});

lastValueFrom(obs).then(v => console.log(v));
```

### Version

7.8.0

**Comment by kwonoj** [comment]
It is answered well - you're doing 2 subscriptions via .subscribe and calling lastValueFrom.
