### ISSUE TITLE
Invalid name: "@reactivex/rxjs"

### ISSUE THREAD

**Issue by ol3j** [ReactiveX/RxJS#727]
Hi, 

I have problem with npm install 

```
npm WARN package.json @ No repository field.
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "@reactivex/rxjs"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7

npm ERR! Invalid name: "@reactivex/rxjs"
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/lukaszolejarczuk/Projects/ionic-conference-app/npm-debug.log
```

What is wrong or what is missing?

**Comment by kwonoj** [comment]
It seems someone experience exactly same issue for scoped named packages with npm, https://github.com/npm/npm/issues/10344 on same system, node, npm version. Would you able to provide npm logs into those issues to those npm issues for diagnose? other than known failures with scoped packages, this error message seems need additional investigation with logs.

**Comment by staltz** [comment]
`npm install @reactivex/rxjs` is still impossible, because there is no stable version released yet. You have to do `npm install @reactivex/rxjs@5.0.0-alpha.10`, i.e. explicitly name the unstable version "5.0.0-alpha.10".

**Comment by kwonoj** [comment]
interesting, I just tried without version and

```
λ npm install @reactivex/rxjs
rxtest@1.0.0 D:\github\test
└── @reactivex/rxjs@5.0.0-alpha.10  extraneous

npm WARN EPACKAGEJSON rxtest@1.0.0 No description
npm WARN EPACKAGEJSON rxtest@1.0.0 No repository field.
```

it was actually installed module. It's node 5.0.0 / npm 3.4.0 currently.

**Comment by staltz** [comment]
Oh, you're living on the edge, maybe it changed with npm 3. I'm still on npm 2, and so is @ol3j .

**Comment by kwonoj** [comment]
That may give glimpses of failure. @ol3j , would you try to install package with specific version as @staltz suggested? if it works, it maybe concluded as @staltz mentioned above.

**Comment by ol3j** [comment]
@kwonoj @staltz thanks! 
I have updated npm version from 2 to 3 and everything is OK.
