### ISSUE TITLE
Documentation site down

### ISSUE THREAD

**Issue by arobinson** [ReactiveX/rxjs#7276]
### Describe the bug

Cannot load any documentation page. Only get the error:
```
REQUEST FOR DOCUMENT FAILED.
```

Example broken URL:
https://rxjs.dev/api/index/function/lastValueFrom

### Expected behavior

Documentation should load.

### Reproduction code

```typescript
https://rxjs.dev/api/index/function/lastValueFrom
```

### Reproduction URL

https://rxjs.dev/api/index/function/lastValueFrom

### Version

7.8.0

### Environment

rxjs.dev web site

**Comment by arobinson** [comment]
![image](https://github.com/ReactiveX/rxjs/assets/93213/47d345a4-ee96-4358-9420-b781b1e2013d)

**Comment by kwonoj** [comment]
https://github.com/ReactiveX/rxjs/discussions/7274
