### ISSUE TITLE
the complete callback cannot be executed with mergeMap operation.

### ISSUE THREAD

**Issue by Mr-OldWang** [ReactiveX/rxjs#7289]
### Describe the bug

I used angular interceptor to intercept http request just like this below, the complete callback not executed with mergeMap:
return this.ac.getToken().pipe( take(1), mergeMap(() => next.handle(this.authHeader(req)))
I searched the solution and said use  take(1) to let it know the request is complete . It works on angular 15.1.X .
But when I upgrade to angular 15.2.8 ,the complete callback cannot be executed again, I wanna ask what the reason is related to angular version as it is rxjs issue.
Is there any solution about this.

### Expected behavior

the complete callback can be executed

### Version

v7.8.1

**Comment by kwonoj** [comment]
https://github.com/ReactiveX/rxjs/discussions/7288
