### ISSUE TITLE
ReplaySubject?

### ISSUE THREAD

**Issue by staltz** [ReactiveX/RxJS#73]
Will RxJS Next get ReplaySubject? I've been lately using ReplaySubject with a 1-buffer instead of BehaviorSubject, and I think it's redundant to have both Behavior and Replay as primitives. BehaviorSubject can be achieved with ReplaySubject.

**Comment by blesh** [comment]
I don't see why not, or at least, I don't have a formulated opinion on the matter. Can you present a few use cases and propose a straw man?

**Comment by staltz** [comment]
**ReplaySubject**
- User specifies buffer size
- Observer sees replayed values if it subscribed even after onCompleted
- Doesn't need an initial value, but can have initial values

**BehaviorSubject**
- User doesn't specify buffer size, it's implicitly `1` always
- Observer does **not** see replayed values if subscribed after onCompleted
- Requires an initial value

## ReplaySubject emulating BehaviorSubject

Except from the semantics of replayed values after onCompleted, ReplaySubject can emulate a BehaviorSubject.

```js
let behavior = new Rx.BehaviorSubject('foo');
behavior.subscribe(x => console.log(`behavior: ${x}`));
behavior.onNext('bar');
behavior.onNext('baz');
```
equivalent to 
```js
let replay = new Rx.ReplaySubject(1);
replay.onNext('foo');
replay.subscribe(x => console.log(`replay: ${x}`));
replay.onNext('bar');
replay.onNext('baz');
```
Console:
```
"behavior: foo"
"behavior: bar"
"behavior: baz"
"replay: foo"
"replay: bar"
"replay: baz"
```

## Cold Observable to hot replayed

When converting an Observable to a "value that changes over time", you can either do `.startWith(initialValue).replay(null, 1).refCount()` or `.publishValue(initialValue)`. `replay()` is a multicast using ReplaySubject and `publishValue` is a multicast using BehaviorSubject. `publishValue(initial)` is `.behave(initialValue).refCount()`, where behave() does not exist in RxJS 2. I don't like this asymmetry, where we have

- `publish()`, multicast of Subject
- `replay()`, multicast of ReplaySubject
- **NO** `behave()`, multicast of BehaviorSubject

## Separate the replay-after-onCompleted feature

If it weren't for the semantics of onNext emissions after onCompleted, we could replace all our BehaviorSubjects with ReplaySubjects. I do not know how often people need replayed onNext events after the subject has completed, but I have never legitimately needed it.

Why not make it a parameter of ReplaySubject? `keep` as true will replay the buffer when observer is subscribed after onCompleted, otherwise it won't.

```js
class ReplaySubject extends Subject {
  constructor(bufferSize: number, keep: boolean, scheduler: Scheduler) {

  }
}
```

This way it would be possible to implement BehaviorSubject as a subclass of ReplaySubject, if someone really wants BehaviorSubject.

**Comment by blesh** [comment]
So the only thing I can think of for why we would want both would be that BehaviorSubject would be more optimized for a single value, since it wouldn't allocate an array when you only want one value. I highly suspect this would have performance implications when a single-value buffered subject is needed.

It's my opinion that there is a use case for both.

**Comment by blesh** [comment]
If I'm honest, I have to say I don't have any strong opinions about ReplaySubject, perhaps @trxcllnt  or @benjchristensen would like to chime in?

**Comment by mattpodwysocki** [comment]
@staltz @blesh I would also argue for keeping both as the `BehaviorSubject` is good enough for holding a single constant value.  `ReplaySubject` in @staltz's definition is missing a number of things including the buffer size according to relative time.  `ReplaySubject` is a much more expensive object to create whereas `BehaviorSubject` is quite light because of all the trimming.  That and the fact that the `BehaviorSubject` exposes the `value` property which allows people to peek in to get the current value.

**Comment by headinthebox** [comment]
+1 for @mattpodwysocki (personally I avoid replaysubject like the plague)

**Comment by staltz** [comment]
>  That and the fact that the BehaviorSubject exposes the value property which allows people to peek in to get the current value. 

`getValue()` isn't a feature we should be proud about maintaining, and it doesn't chime in nicely with the rest of Rx.

I can yield to the performance argument that BehaviorSubject is lighter (curious to how much, though), but names could have been more helpful (perhaps LightReplaySubject?). Anyways, this is just a minor rant because now is probably too late for such a change.

- - -

Back to this issue for RxJS Next, I'm guessing that yes it should have ReplaySubject (besides BehaviorSubject), but what about the `behave(initial)` (a.k.a. `multicast(new BehaviorSubject(initial)`) operator? It would need a better name. In general RxJS needs some "normalization" of the operators.

**Comment by blesh** [comment]
> behave(initial) (a.k.a. multicast(new BehaviorSubject(initial)) 

FWIW: `publish` is now `source.multicast(() => new Subject())` because `source.multicast(someSubject)` was a footgun, as people could pass the same subject instance to N multicasts, which doesn't make any sense. They could still *technically* do that, I guess, but it's more obvious that they're doing something wrong at that point. Also this makes ConnectableObservable "resubscribable", avoiding the need for the `.singleInstance()` operator altogether.

So, your proposal is to have: `source.behave(initial)` map to `source.multicast(() => new BehaviorSubject(initial))`. Are there definitive use cases where this is required? (I'm not against it, just want to identify the usefulness). Is this something that gets used so often that we should ship it with the library?

**Comment by staltz** [comment]
> Are there definitive use cases where this is required?

Yes there are, I've been using `source.replay(null, 1)` a good number of times. [E.g. in RxMarbles](https://github.com/staltz/rxmarbles/blob/master/src/components/diagram/diagram-model.js#L90). The use case is generally: "I have an Observable which gets mapped to something that is fundamentally a *value changing over time*, and when future observers subscribe to it, they need to see the *current* value."

**Comment by blesh** [comment]
`multicastAsBehavior(init)`? `publishBehavior(init)`? I mean, at this point you're taking *some observable* and your (sort of) creating a behavior out of it, or at least attempting to, right? even `behavior(init)` maybe?

**Comment by blesh** [comment]
The whole `BehaviorSubject` vs FRP "Behavior" thing is a little cloudy to me. I *sort* of see how they relate, but I feel like it's a stretch. I'm sure @mattpodwysocki or @headinthebox can straighten me out.

**Comment by headinthebox** [comment]
> The whole BehaviorSubject vs FRP "Behavior" thing is a little cloudy to me.

FRP vs Rx is not an issue I like to discuss because it confuses people like crazy. In any case, it is necessarily a cloudy comparison because Rx is discrete, and FRP is continuous, but conceptually a BehaviorSubject in Rx and a behavior in FRP are the similar: a (single) value that changes over time. Which itself conceptually very different from replaying some subset of past events when you subscribe.

**Comment by staltz** [comment]
> multicastAsBehavior(init)? publishBehavior(init)? I mean, at this point you're taking some observable and your (sort of) creating a behavior out of it, or at least attempting to, right? even behavior(init) maybe?

RxJava had PublishSubject, so the `publish()` name was convenient to remind its related to PublishSubject. In RxJS (vcurrent and vnext) it is just "Subject". So "publish" wouldn't anymore refer to PublishSubject, but rather to "multicast this with a Subject". That's why I think these would make sense as names:

- `publish()` as `multicast(() => new Subject())`
- `publishBehavior(init)` as `multicast(() => new BehaviorSubject(init))`
- `publishReplay(bufferSize, window?)` as `multicast(() => new ReplaySubject(bufferSize, window?))`

**Comment by headinthebox** [comment]
Note that .NET also has no `PublishSubject`, but uses `Subject` for that. So why not keep the names consistent with .NET.

**Comment by blesh** [comment]
I think keeping the Subject class names consistent with .Net is a good idea.

As for operators for `publishBehavior` `publishReplay` etc. Are they common enough use cases to add to the library? (I don't have an opinion) I can't say that I personally have run into many reasons to do this.

That said, I wouldn't mind adding *modules* to the library, whether or not they're included in the global output file is up for debate, though.

**Comment by staltz** [comment]
I use `publish.refCount()` almost daily. I know that others do as well, I've been seeing that in the Cycle.js community. If you want a sample how often it appears, there are [22 StackOverflow RxJS questions](http://stackoverflow.com/search?q=[rxjs]+publish) mentioning publish, out of a total of 235 questions, so about 10%. And for RxJava, [64](http://stackoverflow.com/search?q=[rx-java]+publish) out of [649](http://stackoverflow.com/questions/tagged/rx-java), so also 10%.

- - -

A bit tangential topic to this is the amount of alias operators in RxJS. I'm hoping we could minimize the set of core operators. E.g. `.share()` is an alias to `.publish().refCount()` which is an alias to `.multicast(new Subject()).refCount()`. IMO we could get rid of `.share()`.

- - -

> That said, I wouldn't mind adding modules to the library, whether or not they're included in the global output file is up for debate, though.

If ES6 modules are done right, we might not need to worry anymore about that. See [rollup](https://github.com/rollup/rollup).

**Comment by blesh** [comment]
@staltz Oh, `publish().refCount()` I definitely agree is a common use case. I'm speaking specifically of the `publishBehavior` and `publishReplay` operators. I'm unsure if those are common enough use-cases to export as part of a global library, however the might be interesting adds as modules? I just don't know if they're compelling enough to clutter the API with.

**Comment by blesh** [comment]
... I think I can shorten this thread a little though:

Yes, I think RxJS Next will have a ReplaySubject, as I don't see any replacement for it even if I don't use it terribly often.

We can probably close this thread and add an issue to add ReplaySubject?

**Comment by staltz** [comment]
>We can probably close this thread and add an issue to add ReplaySubject?

Yes

>  I'm speaking specifically of the publishBehavior and publishReplay operators. I'm unsure if those are common enough use-cases to export as part of a global library, however the might be interesting adds as modules?

Oh, I also use `replay.refCount()` as often as I use `publish().refCount()` and I don't think I'm alone: http://stackoverflow.com/search?q=[rxjs]+replay

**Comment by thejameskyle** [comment]
`ReplaySubject` [now exists](https://github.com/ReactiveX/RxJS/blob/b5a0704314c3cb61936eb8f338895da36b6611ca/src/subjects/ReplaySubject.ts), this can be closed.
