### ISSUE TITLE
webSocket docs are contradictory

### ISSUE THREAD

**Issue by skelly-energid** [ReactiveX/rxjs#7309]
### Describe the bug

https://rxjs.dev/api/webSocket/webSocket contains this text:

" next sends a value to the server, so bear in mind that this value will not be serialized beforehand. Because of This, JSON.stringify will have to be called on a value by hand, before calling next with a result."

It also contains this text:

"Note that both messages will be sent as returned by the functions, they are by default serialized using JSON.stringify, just as messages pushed via next."

This is a contradiction. 

I'm new to RxJs, but as far as I know, the first claim in the docs is wrong.

### Expected behavior

Correct docs

### Version

latest

**Comment by kwonoj** [comment]
You are mixing text in sections for websocketsubject and multiplex operator's.

**Comment by rob4226** [comment]
@skelly-energid is right, the docs for `webSocket` say you must call `JSON.stringify` on the value passed to `.next()` but the docblock on `WebSocketSubjectConfig.serializer`  says `JSON.stringy` is called by default: `A serializer used to create messages from passed values before the messages are sent to the server. Defaults to JSON.stringify.`

`webSocket` docs:
https://github.com/ReactiveX/rxjs/blob/c66657469dc17fbed992e273d7d121e51c00d671/packages/rxjs/src/internal/observable/dom/webSocket.ts#L30-L33

`WebSocketSubject` docs:
https://github.com/ReactiveX/rxjs/blob/c66657469dc17fbed992e273d7d121e51c00d671/packages/rxjs/src/internal/observable/dom/WebSocketSubject.ts#L109-L113

So the [WebSocketSubject](https://rxjs.dev/api/webSocket/WebSocketSubject) returned by [`webSocket`](https://rxjs.dev/api/webSocket/webSocket) calls `JSON.stringify` by default. I found by using `webSocket` that the `next()` function does indeed call `JSON.stringify` for you.
