### ISSUE TITLE
Observable docs are confusing

### ISSUE THREAD

**Issue by skelly-energid** [ReactiveX/rxjs#7310]
### Describe the bug

The docs at https://rxjs.dev/guide/observable explain how to use `new Observable` with arrow functions. 

Later the docs exclaim 

"It is not a coincidence that `observable.subscribe` and `subscribe` in `NEVER BEFORE SEEN PATTERN` have the same name."

the never-before-seen-pattern could be a remnant of a previous iteration of the docs which did use the pattern instead of arrow functions above. If that's the case then this should be removed because it is confusing.

### Expected behavior

Not-confusing docs

### Version

latest

**Comment by voliva** [comment]
The first example in [creating observables](https://rxjs.dev/guide/observable#creating-observables), which is just above the line you are referring to, is using the `function` "pattern".

And RxJS doesn't really care if you use `function` or arrow functions either, so that's completely irrelevant.

**Comment by skelly-energid** [comment]
As far as I can tell, the name is irrelevant. Is that correct? If it's irrelevant, then the confusing line should just be removed.
