### ISSUE TITLE
Subject docs depend on deprecated operator

### ISSUE THREAD

**Issue by skelly-energid** [ReactiveX/rxjs#7311]
### Describe the bug

The Subject docs https://rxjs.dev/guide/subject explain multicasting with reference to a deprecated `multicast` operator. That operator seems to be deprecated. The explanation should refer to something not deprecated instead (if the new API works the same way "under the hood").

### Expected behavior

Clear docs that reference relevant further material.

### Version

latest

**Comment by kwonoj** [comment]
multicast _will_ be deprecated, not already deprecated. https://github.com/ReactiveX/rxjs/blob/9db65635b0b26b25c35b3470885c6f02abd54122/src/operators/index.ts#L58

**Comment by skelly-energid** [comment]
Surely that means newcomers should not use it. Why direct newcomers to it as a comparison if they should not use it?
