### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by staltz** [ReactiveX/RxJS#733]
**What is the "lowest common denominator" that RxJS 5 will target?**

Do we support only ES6? Do we support ES5?

These questions came up when I was working on getting coverage for #732, and noticed how in Node 4.2.1 the code related to polyfilling ArrayIterator and StringIterator is never reached because of course, those exist already in Node 4.2.1.

Should we run tests using node v0.10.x? I tried that and many tests failed because of missing `Promise` etc.

**Comment by kwonoj** [comment]
Think ES5 need to be supported. Not sure about node - RxJS4 supports node 0.4+ but node has been updated quite amount - maybe support lowest stable version?

**Comment by blesh** [comment]
I think it's just:

Browser support: IE9+
Node Support: 0.12+ 

> Should we run tests using node v0.10.x? I tried that and many tests failed because of missing Promise etc.

Promise is being injected in those tests now for just that reason, I believe.

**Comment by blesh** [comment]
Really until we have these tests running in something like Karma, testing in multiple browsers is going to be difficult. Also, there are a lot of CI tools that integrate with Travis that will test against multiple browsers and platforms, we should definitely look into that.

Also, if we do that, we can use a library that polyfills Promise (I think Bluebird does this).

**Comment by staltz** [comment]
> Also, there are a lot of CI tools that integrate with Travis that will test against multiple browsers and platforms, we should definitely look into that.

saucelabs

**Comment by blesh** [comment]
I'm going to close this in favor of #998.

We're supporting IE9+, Node 0.12+, and as many modern mobile browsers as we can test.
