### ISSUE TITLE
Documentation Image Links empty

### ISSUE THREAD

**Issue by Gurran** [ReactiveX/rxjs#7345]
### Describe the bug

When rendering the description of a method in rxjs the redered markdown does not show any image.

Example in WebStorm:
![Screenshot from 2023-09-22 11-29-47](https://github.com/ReactiveX/rxjs/assets/42462633/b22b0849-6dd5-424a-acba-20d30525cfae)

The link to the image is empty in the source file *is* empty.

https://github.com/ReactiveX/rxjs/blob/0bd47eab10dec89f245b888f1f26e03cb36d2a78/packages/rxjs/src/internal/operators/take.ts#L12C1-L12C17

### Expected behavior

I would expect the image tag to not be empty and instead point to the same URL as the docs site uses for images. 
I this case https://rxjs.dev/assets/images/marble-diagrams/take.png

### Version

master

**Comment by jakovljevic-mladen** [comment]
We have an open discussion about this issue, please take a look [here](https://github.com/ReactiveX/rxjs/issues/5978).

I'm gonna close this because GitHub issues should be used only for the core library bugs. Thanks for reporting.

**Comment by Gurran** [comment]
Is that discussion active?

7 months since last message.

**Comment by jakovljevic-mladen** [comment]
It is active even though we don't currently work on the solution.
