### ISSUE TITLE
Specific subscriptions emitted in reverse order

### ISSUE THREAD

**Issue by ajakam** [ReactiveX/rxjs#7350]
### Describe the bug

Drastically simplified repro:

I have a pair of classes that interact recursively via Subjects. For the purposes of this repro we have an `Incrementer` and a `Consumer`.

The `Incrementer` class has `input$` and `output$` Subjects. Any value received on `input$` is incremented by one and emitted on `output$`

In this simplified example, the `Consumer` subscribes to the output of `Incrementer`, and sends the same value back into the `input$` Subject.  The `Consumer` initialises the entire interaction by setting an initial value on `input$`. A break is added in the consumer to stop infinite recursion.

The crux of the issue is: external subscriptions to the Subjects operated on by the above classes. In this example, you can see that an external subscription to the `input$` Subject doesn't fire until all recursion has completed and **emits values in reverse order!!**

Contrived example I know. In reality, our classes are reconciling a set of values based on logic & config specific to each.

I know this is probably related to the call stack, and the fact that the recursive interaction is synchronous - but shouldn't the external subscriptions also be synchronous? Also - why does the external `output$` subscription fire correctly?

### Expected behavior

Subscriptions should emit values in order. Log lines below after `BREAK!` should be in ascending order.

```
RecursiveUpdater:input$:fired 1
external:output$:fired 2
Consumer:output$:fired 2
RecursiveUpdater:input$:fired 2
external:output$:fired 3
Consumer:output$:fired 3
RecursiveUpdater:input$:fired 3
external:output$:fired 4
Consumer:output$:fired 4
RecursiveUpdater:input$:fired 4
external:output$:fired 5
Consumer:output$:fired 5
RecursiveUpdater:input$:fired 5
external:output$:fired 6
Consumer:output$:fired 6
BREAK!
external:input$:fired 5
external:input$:fired 4
external:input$:fired 3
external:input$:fired 2
external:input$:fired 1
```

### Reproduction code

```typescript
const { Subject } = require('rxjs');

class Incrementer {
  input$ = new Subject();
  output$ = new Subject();

  constructor() {
    this.input$.subscribe((a) => {
      console.log('incrementer:input$:fired', a);
      this.output$.next(a + 1);
    });
  }
}

const incrementer = new Incrementer();

class Consumer {
  incrementer;
  constructor() {
    this.incrementer = incrementer;
    this.incrementer.output$.subscribe((o) => {
      console.log('consumer:output$:fired', o);
      if (o > 5) {
        console.log('BREAK!');
        return;
      }

      this.incrementer.input$.next(o);
    });

    // set some initial value
    this.incrementer.input$.next(1);
  }
}

incrementer.output$.subscribe((c) => console.log('external:output$:fired', c));
incrementer.input$.subscribe((c) => console.log('external:input$:fired', c));

const a = new Consumer();
```

### Reproduction URL

https://stackblitz.com/edit/stackblitz-starters-ygyba4?file=index.js

### Version

7.8.1

**Comment by kwonoj** [comment]
This kind of question has been asked several times in this repo, in short you're creating circular references across source in a synchronous manner. It looks like you know the answer already. Rx does not magically trying to schedule things in asynchronouly, if you're intended to create such a circular relations you should accordingly schedule it to behave in specific scheduled order. After all, that's what schedulers are for.

Also there's no such `external` or `internal` distinction, you are creating multple subscriptions against a single source and one does circular, re-entrant and one not.
