### ISSUE TITLE
Wrong types path

### ISSUE THREAD

**Issue by PieterjanDeClippel** [ReactiveX/rxjs#7389]
### Describe the bug

![image](https://github.com/ReactiveX/rxjs/assets/9629574/fdc9301b-86d1-448a-89d3-b01b5f528f89)

### Expected behavior

Typescript intellisense

![image](https://github.com/ReactiveX/rxjs/assets/9629574/087769c2-5c99-4225-b28c-b595253a4220)

### Reproduction code

Shipped `package.json`

```
{
  "name": "rxjs",
  "version": "7.8.1",
  "description": "Reactive Extensions for modern JavaScript",
  "main": "./dist/cjs/index.js",
  "module": "./dist/esm5/index.js",
  "es2015": "./dist/esm/index.js",
  "types": "index.d.ts",
  "typesVersions": {
    ">=4.2": {
      "*": [
        "dist/types/*"
      ]
    }
  },
  "sideEffects": false,
  ...
}
```

### Version

7.8.1

### Environment

```
PS C:\Users\Pieterjan De Clippel> node -v
v18.17.1
PS C:\Users\Pieterjan De Clippel> npm -v
9.6.7
```

### Additional context

For some reason the `"types"` field in the `package.json` is wrong

**Comment by kwonoj** [comment]
https://github.com/ReactiveX/rxjs/pull/6293

**Comment by PieterjanDeClippel** [comment]
@kwonoj Thanks, yes it seems to be Visual Studio related.

> Could not find a declaration file for module 'rxjs'

Even VS Code manages to correctly determine the return type of `httpClient.post<xxxx>()`.
It's been working fine for the past 3 years, and now all of a sudden it seems to break down.
Angular CLI doesn't complain about it either.

**Comment by PieterjanDeClippel** [comment]
For some reason a new checkout of the repository with the same code doesn't show this problem. Probably something was off with the .angular folder or so
