### ISSUE TITLE
RxJs ships generators instead of native async/await

### ISSUE THREAD

**Issue by JeanMeche** [ReactiveX/rxjs#7422]
### Describe the bug

Talking about v7: 

Looking at files like `/rxjs/dist/esm/internal/observable/innerFrom.js`, it looks like `rxjs` is shipping code where native async/awaits are converted to generators. 

I don't think that's up to the lib to do that conversion. 

Soon, zoneless Angular apps should be able to build without using `@babel/plugin-transform-async-to-generator` (required by `zone.js`. So I would expect `rxjs` to ship native async/await and reduce its footprint. 

### Version

7.8.1

**Comment by kwonoj** [comment]
https://github.com/ReactiveX/rxjs/issues/5270

We won't make breaking changes to the target platform we support in v7. If we change transpilation target, consumer need to separately transpile 3rd party pkg (rxjs).
