### ISSUE TITLE
Issue with catchError

### ISSUE THREAD

**Issue by NarHakobyan** [ReactiveX/rxjs#7450]
### Describe the bug

Type declaration of catchError has been changed and caught was marked as required

```typescript
export function catchError<T, O extends ObservableInput<any>>(
  selector: (err: any, caught: Observable<T>) => O
): OperatorFunction<T, T | ObservedValueOf<O>>;
```

it breaks code where catchError receives only error as argument

### Expected behavior

caught must be optional so code like will work

```typescript
catchError((err: Error) => {

            return throwError(
              () => err,
            );
          })
```

### Version

7.8.1

**Comment by benlesh** [comment]
I'm unable to reproduce this. It seems to work with the latest RxJS and TypeScript:

https://www.typescriptlang.org/play?noUnusedLocals=true&noUnusedParameters=true&useUnknownInCatchVariables=true&exactOptionalPropertyTypes=true#code/JYWwDg9gTgLgBAbzhAZgGjgYwIY0wCwFEopoMZ9SB3Y0qOAXzhVJDgHIoAPAKwGd2AbgCwAKDGoAFAEYMAJgwBmAJQA6MMDABTSWLj6suArWiTJWksrgBeAHyI9Bp1C0wArlAB2cCtRNQzKzs4CyhlEVEnBmUxZSA
