### ISSUE TITLE
False positive in deprecation with mergMap

### ISSUE THREAD

**Issue by mcfdez** [ReactiveX/rxjs#7457]
### Describe the bug

When implementing the use of mergMap in Angular Ngrx effects, ESLint warns about the deprecated use of mergMap even if the operator is used correctly.

### Expected behavior

The deprecation message should not appear when the operator is used correctly.

### Reproduction code

```typescript
export const deleteAddon = createEffect(
    (actions$ = inject(Actions), repository: AddonsRepository = inject(ADDONS_REPOSITORY)) => {
        return actions$.pipe(
            ofType(DeleteAddon),
            // This mergeMap alerts for deprecation!!
            mergeMap(({ id }) => deleteAddonUseCase(repository, id).pipe(
                map(() => DeleteAddonSuccess()),
            )),
        );
    },
    { functional: true },
);
```

### Version

7.8.1

**Comment by benlesh** [comment]
I can't confirm this in 7.x or 8.x.
