### ISSUE TITLE
Support anonymous object to skip optional parameters?

### ISSUE THREAD

**Issue by kwonoj** [ReactiveX/RxJS#749]
Originated from https://github.com/ReactiveX/RxJS/pull/744

Some of operators such as `last` have optional parameters from first one, 
`last<T, R>(predicate?, resultSelector?, thisArg?, defaultValue?)` (simplified signature)

so trying to specify some optional parameter other than first will looks like this
`source.last(null, null, null, 'value');`

It can be considerable to support anonymous object as same as current `Observable.subscribe` does
like 
`source.subscribe({error: ... });` reduces to specify empty parameter per each.

Few things need to be considered at first sight
- Will it impact performance noticeably?
- What kind of operators need to be supported for this behavior? (All operators have >2 optional parameters? or some specific operators have >n optional parameters?)

**Comment by kwonoj** [comment]
cc @staltz

**Comment by staltz** [comment]
> Will it impact performance noticeably?

Because RxJS 5 is mainly about performance, I'd give priority to performance than to this anon object API. However, if it's a small impact, then I'd suggest it for all operators with >2 optional parameters.

**Comment by kwonoj** [comment]
Instead of dive into making changes immediately, I'll let this issue opened for a while to gather some opinions. (Pure personal opinion, I usually don't mind to explicitly specifying empty values to skip parameters)

**Comment by blesh** [comment]
I agree with @staltz here. I'd like to discourage people using objects to pass arguments for a few reasons:

1. operators will become polymorphic: Now you can call each operators two completely different ways. That's going to skip some optimizations afforded by some runtimes. Also, internally, you'll need to do some type checking to see what sorts of arguments are passed.
2. easier for the operator to create bugs: IIRC, RxJS-DOM oncee had an issue with `Rx.DOM.ajax` where the argument object being passed could be mutated in some instances. You end up needed to jump through some extra hoops internally to protect yourself from that.
3. Additional, unnecessary object allocations. Probably not a big deal, but still an issue.

**Comment by kwonoj** [comment]
Seems it's raised by @staltz himself, including himself, I, @blesh all not quite interested to push this :) I'll simply close this issue and reopen once there is more strong demand.

**Comment by blesh** [comment]
:+1:
