### ISSUE TITLE
False positive in deprecation with "of" function

### ISSUE THREAD

**Issue by egorkel-altexsoft** [ReactiveX/rxjs#7494]
### Describe the bug

When using the **of** function, ESLint warns about the deprecated usage.

### Expected behavior

The deprecation message should not appear when the function is used correctly.

### Reproduction code

```typescript
Just try `of([])` or `of(true)`
```

### Version

7.8.1

### Additional context

This definition causes the error
![image](https://github.com/user-attachments/assets/004f334e-eb20-418b-a2c5-07efebc7500b)

**Comment by niklas-wortmann** [comment]
This is a JetBrains Issue, not an RxJS issue
https://youtrack.jetbrains.com/issue/WEB-67651/Incorrect-overloads-selected-for-rxjs-of-when-using-types-from-server.
Please upvote the ticket linked here, this way you'll also be notified once it is fixed

**Comment by egorkel-altexsoft** [comment]
Thanks for your answer
