### ISSUE TITLE
Thoughts on static `mergeAll` and `concatAll` operators

### ISSUE THREAD

**Issue by blesh** [ReactiveX/rxjs#786]
So we currently have `Observable.merge`, and recently there was even a PR to make it accept an Array.

I've thought about this quite a bit, and I think `Observable.mergeAll` probably has some merit. In fact, it probably should have been the version of `Observable.merge` that accepts an Array.

`Observable.mergeAll` could accept (along with a concurrency limit and a Scheduler):

- `Observable<Observable<any>>`
- `Array<Observable<any>>`
- `Iterable<Observable<any>>`

In the case of `Iterable<Observable<any>>` it would only iterate out whatever the concurrency limit is. This means that an `Observable.concatAll` could take an `Iterable<Observable<any>>` as well. ... likewise, `repeat` and `retry` could leverage this:

```js
function repeat(count) {
  const source = this;
  return Observable.concatAll(function* () {
    for (let i = 0; i < count; i++) {
      yield source;
    }
  });
}
```

Retry would be a little more advanced, but the idea would be to create an iterator that completed if no errors occurred, but iterated again if an error did occur.

**Comment by staltz** [comment]
Looks neat, specially for implementing `repeat` and `retry`. But it also means we need to introduce static `mergeAll()` / `concatAll()` right? Currently we only have proto `mergeAll()`.

**Comment by blesh** [comment]
> But it also means we need to introduce static mergeAll() / concatAll() right?

Most likely, yes.

**Comment by masaeedu** [comment]
Is this fixed? It looks like we already have a `mergeAll` operator: https://github.com/ReactiveX/RxJS/blob/42bccedfa9d0f8b4de6bdd80e3876d8a3f7081e8/src/operator/mergeAll.ts

**Comment by blesh** [comment]
Closing this issue as stale.
