### ISSUE TITLE
expand missing scheduler argument

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#841]
I pointed out [here](https://github.com/ReactiveX/RxJS/issues/766#issuecomment-160740919), that we are missing a scheduler argument for `expand`. This is necessary for changing the behavior of when `expand` subscribes to observables returned by the selector.

It should default to no/null/undefined scheduler, which means immediate execution.

Related to #766 #788 #793

**Comment by luisgabriel** [comment]
I can work on this one.

**Comment by kwonoj** [comment]
@luisgabriel :+1:
