### ISSUE TITLE
Move Symbol shims into single file.

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#844]
Considering we're shimming `Symbol` and items on it frequently, I think it would be best to move it into a single file.

That would make this:

```js
import {$$iterator} from '../utils/Symbol_iterator';
import {$$observable} from '../utils/Symbol_observable';

const something = {
  [$$iterator]() { }
  [$$observable]() { }
};
```

... into this...

```js
import {Symbol} from '../utils/Symbol';

const something = {
  [Symbol.iterator]() { }
  [Symbol.observable]() { }
};
```

**Comment by kwonoj** [comment]
Typesciprt side support of es6 global symbol (https://github.com/Microsoft/TypeScript/issues/980) makes bit hard to use module name `Symbol`, causes name collision in es6 build like

```
192   [Symbol.iterator]() {                                                                                                
       ~~~~~~                                                                                                                                                                                                                                         
src/operators/zip-support.ts(192,4): error TS2470: 'Symbol' reference does not refer to the global Symbol constructor object.                                                                                                                         
                                                                                                                           
```
while other (cjs, etcs) are built. What about having different name for this module, maybe `SymbolPolyfill` or something else?

p.s : 
seems global symbol is supported for es6 only, using those global symbol and targeting es5 will simply raise lookup failure.

```
161   [Symbol.iterator]() {
       ~~~~~~
src/operators/zip-support.ts(161,4): error TS2304: Cannot find name 'Symbol'.
```

**Comment by blesh** [comment]
Sigh. TypeScript. LOL. We may have to go back to using Babel to target ES5.

TypeScript also doesn't allow generators in code targeting ES5. Which isn't a big issue so far, but I've hit it playing around.
