### ISSUE TITLE
rxjs and rxjs-es6 publishing issues

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#845]
1. Right now the package.json files that are being copied to the `dist/es6` and `dist/cjs` directories have a `prepublish` step that tries to build the source. That, of course, fails.

2. There are no READMEs for these two packages. So it looks bad/wrong on npmjs.org.

cc/ @robwormald

**Comment by robwormald** [comment]
fail.

**Comment by robwormald** [comment]
assign to me?

**Comment by blesh** [comment]
Can't you're not in the org. I'll assign to me, and pester you about it.

**Comment by robwormald** [comment]
also fix the license copy

**Comment by jeffbcross** [comment]
I'm taking this on
