### ISSUE TITLE
Update typing for TypeScript 1.7 "polymorphic this typing"

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#846]
Thanks to @trxcllnt for pointing this out:

http://blogs.msdn.com/b/typescript/archive/2015/11/30/announcing-typescript-1-7.aspx

Basically, since our operators can return different types due to the snazzy lift architecture, we should be returning `: this` and not `: Observable<T>` from them.

... this might get a little nutty when it comes to types that change the generic output, though. `map` for example.  `Observable<T>.prototype.map((x: T) => R): Observable<R>` would be `Observable<T>.prototype.map((x: T) => R): this` ... I'm not sure hot TypeScript will suss out that `this` should be generically typed to `R` and not `T`...

**Comment by kwonoj** [comment]
I was interested in this topic bit while ago when introduced 1.8 dev of typescript in RxJS, hit couple of roadblocks at the moment.

**: `lift` returns new instance**
`lift` does create new instance and returns it 
``` 
lift(): Observable {
 ...
 return new Observable();
}
```
causes compiler complains about type inferences like `Type 'Observable' is not assignable to type 'this'`

polymorphic `this` requires to return self, such as
```
public add(operand: number) {
    this.value += operand;
    return this;
}
```

**: polymorphic `this` works with instance method**
most of operator declaration in `Observable` is based on property stubs for modularity, such as 

`switch: <R>() => Observable<R>`

can't be converted to return `this`

`switch: () => this;`

**: type transformed output**
copy-paste from original comment.
>Observable<T>.prototype.map((x: T) => R): Observable<R> would be
Observable<T>.prototype.map((x: T) => R): this

Still, I'm feeling this is great feature and would explore way to adopt into RxJS.

bit more details about polymorphic this can be found at https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#this-typing

**Comment by kwonoj** [comment]
Note : it is completely possible I'm not fully knowledgeable about this feature and above comment could be wrong for some aspect. Above comments are based on my initial exploration.

**Comment by blesh** [comment]
That's too bad. I'll close this for now, then. And perhaps file an issue with TypeScript for our specific use case/needs.
