### ISSUE TITLE
Add AsyncSubject

### ISSUE THREAD

**Issue by mattpodwysocki** [ReactiveX/RxJS#850]
Add AsyncSubject to RxJS v5. Other subjects can be added in the future, but this one is tried and true and used by many community members.

**Comment by mattpodwysocki** [comment]
@blesh @staltz correct me if I'm wrong, but wouldn't it be as simple as this?

```typescript
import {Subject} from '../Subject';
import {Subscriber} from '../Subscriber';
import {Subscription} from '../Subscription';

export class AsyncSubject<T> extends Subject<T> {
  constructor () {
    super();
    this.value = void 0;
    this.hasNext = false;
  }

  _subscribe(subscriber: Subscriber<any>): Subscription<T> {
    const subscription = super._subscribe(subscriber);
    if (!subscription) {
      return;
    } else if (!subscription.isUnsubscribed && this.hasNext) {
      subscriber.next(this.value);
      subscriber.complete();
    }
    return subscription;
  }

  _next(value: T): void {
    this.value = value;
    this.hasNext = true;
  }
}
```

**Comment by blesh** [comment]
LGTM.

I think once this completes, you could set `_isScalar` to `true` on it and get some benefits from operators that fast-track scalar observables.

**Comment by architruc** [comment]
:+1:  for `AsyncSubject`, thanks!

Just one question: what would be the difference with `new ReplaySubject(1)` (if any)? I just learnt about this alternative from angular2 gitter.

**Comment by staltz** [comment]
@architruc very different. AsyncSubject does not emit next values before it completes. It only emits on completion, and after completion for late subscribers.

**Comment by architruc** [comment]
@staltz Okay, if I understand well `ReplaySubject` emits at each value (let's say each `next()` in the source), but `AsyncSubject` on `complete()` in the source, right?

Yes, it is different, seems I misunderstood, although `AsyncSubject` could still help in my usecase. Thanks!

**Comment by blesh** [comment]
This can be closed now, I think.
