### ISSUE TITLE
Move to just using Markdown docs (ala RxJS 4)?

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#851]
So, I find the documentation generation problematic. 

### Doc Gen (esdoc, et al)

PROS:
1. It maintains links between the source and the docs.
2. Inline docs can be helpful.
3. It's easier to remember to update docs when they're right next to the code your changing.

CONS:
1. it's really *that* much prettier/readable than markdown
2. it's not always straightforward to create just want you want to document.
3. I'd like a _lot_ more detail in the docs.
4. More painful to link docs that are external to what's being generated.

### Markdown Docs

PROS: 
1. @Widdershin's sweet tool can be run on the code inside of the docs
2. Much easier to get readable format and add lots of data/value without junking up source code
3. We might be able to straight port some of the RxJS 4 docs
4. Can more cleanly add in linked documentation that doesn't directly relate to source code. (how-tos, etc)

CONS:
1. Keeping links between docs and source becomes more difficult
2. Keeping them updated with code changes can be problematic because they're not next to the code. Out of sight, out of mind.
3. Doesn't have fancy searching functionality built in, really. There's GitHub search, but that's not quite the same.

**Comment by staltz** [comment]
I'm pretty optimistic about esdoc. In general I'm favorable of putting technical specs of each operator in esdoc, and then elaborating in more details at reactivex.io where we can put documentation not linked directly to source code.

**Comment by blesh** [comment]
> then elaborating in more details at reactivex.io where we can put documentation not linked directly to source code.

That's totally true. I'd lost sight of that when I made this issue. (I'm not sure why it's come up at Netflix a dozen times)

**Comment by Widdershin** [comment]
As I mentioned in the original markdown-doctest pull request, if we do opt for esdoc as the future, I will write almost definitely write `esdoctest` if nothing does that already, as I think having runnable examples as a CI enforced concept is quite important.

Don't let `markdown-doctest` sway you too much is all I'm saying.

**Comment by Widdershin** [comment]
Have any examples been written using `esdoc` so far? Would love to be pointed in the right direction if so.

**Comment by staltz** [comment]
>  I will write almost definitely write esdoctest if nothing does that already, as I think having runnable examples as a CI enforced concept is quite important.

That would be great!

**Comment by h13i32maru** [comment]
Hi! I am developing ESDoc. Thanks for using it :smile: 

ESDoc supports to integrate markdown file into documentation. Please see https://esdoc.org/feature.html#integration-manual for more information. this might help to you.

If you have feature requests for ESDoc, please tell me it.

Feel free this comment.
Thanks.

**Comment by staltz** [comment]
> ESDoc supports to integrate markdown file into documentation. Please see https://esdoc.org/feature.html#integration-manual for more information. this might help to you.

Perfect, then.

**Comment by blesh** [comment]
I think I'm 90% ready to close this issue... But how much description can we add in ESDoc? Can we embed little JSBins or anything like that?

**Comment by staltz** [comment]
> Can we embed little JSBins or anything like that? 

Can't even do that in markdown docs. :D

**Comment by blesh** [comment]
> Can't even do that in markdown docs. :D

I know you can't do this in comments, but this is true for .md files committed to the repo as well? Aww, man... 😕

**Comment by staltz** [comment]
E.g. I know you can't embed youtube videos in .md files, but you can embed images and gifs.

**Comment by Widdershin** [comment]
If we're going to do markdown + esdoc and there's a build step to compile
to html, I feel like we can totally do interactive examples. The code for
extracting code snippets already exists in markdown-doctest, we would just
need to browserify the code and embed an editor in the generated htnl.

I might take a crack at that soon, see what's possible

**Comment by blesh** [comment]
@Widdershin just blew my mind a little there. That sounds really cool

---

I think we can close this issue and stick with esdocs for now then.
