### ISSUE TITLE
Observable.of should be split into two operators

### ISSUE THREAD

**Issue by mattpodwysocki** [ReactiveX/RxJS#854]
In RxJS v4, we have two separate `of` operators, `of` and `ofWithScheduler` due to the fact that you could absolutely have the following which would incorrectly state the number of items in the Observable is **2** when it should be **3**:

```js
const obs = Observable.of(
  Scheduler.default,
  Scheduler.default,
  Scheduler.default
);

const subscription = obs.count().subscribe(x => console.log(x))
// => 2
```

Instead, I would suggest separating this into two operators:
```typescript
static of<T>(...array: Array<T>): Observable<T>;
static ofScheduled<T>(scheduler: Scheduler, ...array: Array<T>): Observable<T>
```

This way we could support having just about anything in the `of` operator instead of restricting it.

**Comment by blesh** [comment]
Currently, `Observable.of` does accept a Scheduler as the last argument.

If you needed to make an Observable of Schedulers for some reason, couldn't you just do: `Observable.from([Scheduler.animationFrame, Scheduler.immediate, Scheduler.nextTick])`?

**Comment by mattpodwysocki** [comment]
@blesh yes, I could, but we'd have to put a big disclaimer of **DON'T USE OF WITH SCHEDULERS** as part of the documentation which I find kind of distasteful, when in fact we could just have a prettier API for when scheduling is explicitly needed.  

Else, we could have a notion of a null scheduler, but I find that ugly as it's a magic value they'd have to remember to put at the end.

**Comment by blesh** [comment]
> we could have a notion of a null scheduler

#857 is basically that idea. The library probably needs it anyhow, for reasons outlined in the issue.

**Comment by blesh** [comment]
Rebooting discussion here #1196
