### ISSUE TITLE
Observable#startWith should be two separate methods

### ISSUE THREAD

**Issue by mattpodwysocki** [ReactiveX/RxJS#855]
Once again, `startWith` suffers from the same bug as #854 where if you have a list of `Scheduler` instances that it will pop the last argument as the `Scheduler` instance to use which once again would result in an incorrect answer of **2** items in the collection when there should be **3**.

```js
const obs = Observable.just(Scheduler.default).startWith(
  Scheduler.default,
  Scheduler.default
);

const subscription = obs.count().subscribe(x => console.log(x))
// => 2
```

My proposal is the following with once again having two operators, one without a scheduler, and one with an explicit scheduler.  That way we don't have to do any sniffing to determine whether they supplied a Scheduler or it's just another value.

```typescript
export function startWith<T>(...array: Array<T>): Observable<T>;
export function startWithScheduled<T>(scheduler: Scheduler, ...array: Array<T>): Observable<T>;
```

**Comment by blesh** [comment]
> That way we don't have to do any sniffing to determine whether they supplied a Scheduler or it's just another value.

We're already stuck doing that in most cases, because 1. it's generally an optional parameter. and 2. The Microsoft spec actually stipulates that Scheduler be the last argument. So that means in functions with "splat params" we're stuck with a little type checking up front.

This isn't so bad, because we're generally only doing it once when the Observable chain is set up. It would be worse if we had to make these checks in the Subscriber itself.

**Comment by mattpodwysocki** [comment]
@blesh yes, the spec says that, but we've had to make the exceptions of course with [`StartWith`](https://github.com/Reactive-Extensions/Rx.NET/blob/859e6159cb07be67fd36b18c2ae2b9a62979cb6d/Rx.NET/Source/System.Reactive.Linq/Reactive/Linq/QueryLanguage.Single.cs#L494-L497)

If you were to keep the scheduler as a parameter, I would suggest moving it to the first parameter just as we have it in RxJS v4.  Thus we could do the following easily, one specifying a scheduler, otherwise, not.

```js
const obs1 = Observable.just(4).startWith(null, 1, 2, 3);
const obs2 = Observable.just(4).startWith(Scheduler.default, 1, 2, 3);
```

**Comment by blesh** [comment]
@mattpodwysocki I think if we add `Scheduler.none`, this becomes a non-issue.

`Observable.of('something').startWith(Scheduler.sync, Scheduler.sync, Scheduler.sync, Scheduler.none);`

We can keep the scheduler to be used at the end, and in the unlikely event someone wants to create an unscheduled Observable of Schedulers, they can do so by passing `Scheduler.none` as the last argument.

**Comment by blesh** [comment]
Rebooting discussion here #1196
