### ISSUE TITLE
Unsubscribed Subjects should throw ObjectDisposedError if next, error or complete is called.

### ISSUE THREAD

**Issue by mattpodwysocki** [ReactiveX/RxJS#859]
In the current version of RxJS v4, [we check for disposal](https://github.com/Reactive-Extensions/RxJS/blob/master/src/modular/subject.js#L27) with [`Disposable.checkDisposed`](https://github.com/Reactive-Extensions/RxJS/blob/master/src/modular/disposable.js#L46) so any subsequent call to `onNext`, `onError` and `onCompleted` and even `subscribe` are guarded by throwing a specific error of `ObjectDisposedError`.

In RxJS v5, there is a change to simply return and do nothing in the [`Subject`](https://github.com/ReactiveX/RxJS/blob/52eea95cd37481718a79267437ae280b1d9e195f/src/Subject.ts#L85), is this intentional and if so why?  Yes, I realize this follows RxJava instead of RxJS, but at least what thought went into this would be good to know. 

cc @benjchristensen @headinthebox 

(EDIT (@blesh): updated link to "modern" equivalent of what _was_ linked, and pinned it to a SHA)

**Comment by blesh** [comment]
> is this intentional and if so why?

It's not intentional, as far as I can remember. I've actually just added an `ObjectUnsubscribedError` per conversation on #853
