### ISSUE TITLE
toPromise on Observable requires promise constructor argument

### ISSUE THREAD

**Issue by jeffbcross** [ReactiveX/RxJS#864]
https://github.com/ReactiveX/RxJS/blob/master/src/Observable.ts#L247

The constructor should be optional, as it is implemented in the operator itself https://github.com/ReactiveX/RxJS/blob/master/src/operator/toPromise.ts

**Comment by kwonoj** [comment]
Yes, seems so. I'll update this quickly.

**Comment by jeffbcross** [comment]
Awesome @kwonoj thanks!

**Comment by johnpapa** [comment]
thanks!

**Comment by robwormald** [comment]
Nice one OJ. This sort of thing would be caught with TS running type checks on a TS based test suite, so I'm definitely for that.

**Comment by kwonoj** [comment]
> This sort of thing would be caught with TS running type checks on a TS based test suite, so I'm definitely for that.

: totally agreed. Currently 2 proposals opened for this, https://github.com/ReactiveX/RxJS/pull/826 and https://github.com/ReactiveX/RxJS/pull/667. Once it's decided which way to go, test will be added along with updating existing type declarations if necessary.
