### ISSUE TITLE
Expose concurrency parameter of mergeScan

### ISSUE THREAD

**Issue by kwonoj** [ReactiveX/RxJS#868]
While `MergeScanOperator` has implementation to accept concurrency parameter

```js
constructor(private project: (acc: R, x: T) => Observable<R>,
              private seed: R,
              private concurrent: number = Number.POSITIVE_INFINITY)
```

type definition of `mergeScan` does not allow to use it.

`mergeScan<T, R>(project: (acc: R, x: T) => Observable<R>, seed: R)`.

Would it be better to expose concurrency parameter?

**Comment by blesh** [comment]
Probably, yes.

**Comment by kwonoj** [comment]
Cool, I'll try with expanding test coverage.

**Comment by kwonoj** [comment]
Maybe I'm incorrect, came to curious if `concurrency` of `mergeScan` is really being used compare to `merge`. @blesh , may I possibly ask to shed some light to my understandings?

**Comment by blesh** [comment]
`mergeScan` is definitely looking at the `concurrent` value, it's just not being set from the actual operator function.

https://github.com/ReactiveX/RxJS/blob/f1dc76494cd0b134cd4682503cc479fc6afcbf8c/src/operator/extended/mergeScan.ts#L45

**Comment by kwonoj** [comment]
> definitely looking at the concurrent value 

: Yes, that's part where I started this issue. I'll think bit more to bring up some code snippets if possible.

**Comment by kwonoj** [comment]
It's simply my dumb understandings about questions above for usage of concurrency :( will continue work on this, thanks @blesh .

**Comment by blesh** [comment]
I can't think of any use cases for changing the concurrency of this, really. But I can see the utility of it.

@trxcllnt, what's a use case for concurrency in mergeScan?

**Comment by trxcllnt** [comment]
@blesh same as the case for `merge`. `mergeScan(1)` is actually `concatScan()`.

**Comment by blesh** [comment]
@trxcllnt That's fair, I was just wondering more like "when would I use this"? That sort of use case.
