### ISSUE TITLE
package name wrong in CJS package.json after build_all

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#892]
It currently sets the name to `"name": "rxjs-es6" in the `dist/cjs/` directory. That needs to be `"name": "rxjs"` only.

In the `dist/es6/` directory, the name now needs to be set to `"name": "rxjs-es"`, it's also currently wrong.

**Comment by blesh** [comment]
cc/ @robwormald @jeffbcross

**Comment by jeffbcross** [comment]
https://github.com/ReactiveX/RxJS/pull/895

**Comment by jeffbcross** [comment]
FTR my change didn't introduce this behavior :).

**Comment by kwonoj** [comment]
I'm closing this issue since #895 is merged.
