### ISSUE TITLE
Observable.of and Observable.from must be on Observable

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#894]
Right now the Observable exported by `src/Observable` doesn't have `of` and `from` on it by default. It really should.

`from` is required for interop at the very least.

**Comment by blesh** [comment]
cc/ @robwormald @jeffbcross

**Comment by jeffbcross** [comment]
whatev

**Comment by kwonoj** [comment]
Closing this issue per discussion of #922, importing into Observable creates circular dependencies. For now will require manual import until better solution comes in.
