### ISSUE TITLE
Circular reference between Observable and others

### ISSUE THREAD

**Issue by kwonoj** [ReactiveX/RxJS#899]
*Observable.ts*

```
...
import {ConnectableObservable} from './observable/ConnectableObservable';
import {Subject} from './Subject'; --> import subject

...
if (observerOrNext instanceof Subscriber || observerOrNext instanceof Subject) {
```

*Subject.ts*
```
...
import {Observer} from './Observer';
import {Observable} from './Observable'; --> import observable
...
export class Subject<T> extends Observable<T>
...
```

ends up with below snippet

```
import {Observable} from 'dist/cjs/Observable';

Observable.of(1).subscribe(console.log);
```

```
 d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
                                                                   ^
TypeError: Cannot read property 'prototype' of undefined
    at __extends (D:\github\RxJS\dist\cjs\Subject.js:4:68)
    at D:\github\RxJS\dist\cjs\Subject.js:20:5
    at Object.<anonymous> (D:\github\RxJS\dist\cjs\Subject.js:135:3)
```

Subject does not resolves reference to Observable.

**Comment by kwonoj** [comment]
Not sure if https://github.com/ReactiveX/RxJS/issues/894 is related or not..

**Comment by blesh** [comment]
It's probably #894. TypeScript is pretty good about hoisting dependencies that would otherwise be circular.

`import {Observable} from 'dist/cjs/Observable';` will just get you the bare-bones Observable without `from` and `of` right now.

**Comment by kwonoj** [comment]
Did couple of try, seems #894 and this need to be updated both. even import `from` / `of` to observable, importing observable directly would not work due to this.

**Comment by kwonoj** [comment]
Changed subject to describe this more general, such as

- Observable <--> GroupedObservable
- Observable <--> CoreOperators <--> GroupedObservable ..(direction is not precise, just an example)

and lot of others.

This reference could possibly cause runtime reference resolve issue as described above and also noticeably increases build times.

Tried to solve this via simple ambient declaration but wasn't work as expected, ambient merging seems possible way but still need to prove.

**Comment by ntilwalli** [comment]
@kwonoj Just a quick comment, dunno if it's relevant, I introduced this circular import with https://github.com/ReactiveX/RxJS/pull/863 and to deal with it I updated the KitchenSink and Rx files to move the Subject import before Observable. I made a comment to that effect in the discussion and in the checkin notes.  Until I reordered these imports, I was seeing the same error.

**Comment by kwonoj** [comment]
@ntilwalli I assume top-level (Rx / Kitchensink) is also somewhat related, but not critical at this moment. This issue is specific for module-level import (i.e, import observable only, or something else) to make reference resolve failure to work with specific module. Once this is cleanly resolved, may able to visit top level module also using similar approaches.

**Comment by blesh** [comment]
@jeffbcross ran a circular dependency check on #912 and found it was green. So that PR is likely all we need to clear this issue.

Also, we're going to add some sort of circular dependency checking to the test build. (again, @jeffbcross)

**Comment by jeffbcross** [comment]
PR for ci check: https://github.com/ReactiveX/RxJS/pull/917

**Comment by kwonoj** [comment]
Cool news, then assume https://github.com/ReactiveX/RxJS/pull/909 can be close without merging? @blesh

**Comment by blesh** [comment]
#912 closes this.
