### ISSUE TITLE
Whitespace

### ISSUE THREAD

**Issue by gaearon** [ReactiveX/RxJS#9]
There's some mixed spacing in the files, I see both tabs and spaces. I know it's very early but it would be nice to pick one style and stick with it now, to avoid junk in history later.

Most JS projects follow two spaces as convention so I'd suggest that if you're open to it.

**Comment by BerkeleyTrue** [comment]
Would the RxJS team be open to using eslint instead of jshint as a way to enforce a code style?

**Comment by blesh** [comment]
LOL... @_jayphelps 

Sorry, guys, I've been having IDE issues. LOL ... I'll address this in a few.

**Comment by jayphelps** [comment]
trolololololo you guys have no idea. He's been going through hell lately with this. He is indeed a 2 space guy, when his editor lets him. I'm thinking about sneaking a git pre-commit hook on his system that prevents him from ever pushing tabs. :smiling_imp:

**Comment by blesh** [comment]
fixed... also added jshint (finally): https://github.com/ReactiveX/RxJS/commit/19c164ac864c8984f86181ddc6ad2f0d225684d8
