### ISSUE TITLE
Remove dist folder from source

### ISSUE THREAD

**Issue by jeffbcross** [ReactiveX/RxJS#90]
If we _must_ have dist as part of the repo, it should at least be something that only gets updated at each tag, so that deltas between branches are less drastic (and rebases are less difficult). But I propose keeping no build folders in the project, and just make a script that generates the npm distribution at publish-time. I can implement this script, similar to how we handle it in https://github.com/angular/angular/blob/master/scripts/publish/npm_publish.sh

@blesh

**Comment by blesh** [comment]
I think this is reasonable.

However, I was thinking of leaving `dist`, but setting the build target directory as `tmp` or something (which wouldn't be committed), then performance tests could be run against what's in `dist` and what's in `tmp` and compared.  I presume we're not going to want to perf test against RxJS 2 forever.

**Comment by blesh** [comment]
By that token, I suppose we can change the perf tests to pull down the latest version from npm and run against that... thoughts?

**Comment by jeffbcross** [comment]
The problem with the "run the same perf tests against two versions" idea is that APIs change often from version to version, and then the perf tests need to change from version to version. I think the best way to accomplish version comparison is to 0) keep tests consistent in spirit over time, but changing with APIs as they change (better to add new tests than to change existing ones), 1) check out each revision you want to compare, 3) build and run perf tests, compare results. Scripts could be made to make this easier.

We've discussed this problem on the angular team, and this is where I've ended up.

**Comment by blesh** [comment]
I agree. I think I prefer the "keep tests consistent in spirit over time" approach for this library. Considering that most of this is a known set of operators that can be used in expected ways, I think that should work well.

As for removing `dist/` another downside to doing this would be the inability to use at least rawgit.com as a CDN for jsbin hacking and the like.

**Comment by jeffbcross** [comment]
Yeah, there are a couple of valid use cases for wanting to quickly grab a dist to hack with:
 1. To build a demo, or experiment with something locally or jsbin.
 1. To make a reproduction to demonstrate a bug with a release in jsbin
    1. ...or against a specific revision of the library to demonstrate a problem before it is released (typically for more advanced contributors), or demonstrate that a specific revision fixes an issue.

For angular.js and angular, we just have a repository that distributions that get updated with each release, and also contain the latest snapshot of master: https://code.angularjs.org. This nicely satisfies the first two use cases, and provides a quick way to get access to any released version of the lib. There are also Google's CDN and third-party CDNs that provide the same service. 

To satisfy the 3rd use case, angular contributors build the library at the revision and upload the built file themselves to a code-sharing site (usually plunker for angular users). This is more work than just going to a revision on github and getting the rawgit url, but the use case applies to a small subset of advanced contributors, is far less common, and the benefit more than outweighs this inconvenience.

I think this flow is pretty nice for users and contributors. It's just a matter of setting up the infrastructure to automatically publish distributions.

**Comment by blesh** [comment]
> For angular.js and angular, we just have a repository that distributions that get updated with each release, and also contain the latest snapshot of master: https://code.angularjs.org.

What are you using to do this?

**Comment by jeffbcross** [comment]
We have a repository that auto-deploys each commit to our servers: https://github.com/angular/code.angularjs.org

We have a fully automated release process that creates the commit and pushes to that repo.
