### ISSUE TITLE
Bike-shedding: `switchMapFirst` and `switchMap`

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#915]
At the very least, we need to change `switchMapFirst` to `switchFirstMap` to match our naming scheme.

But `switchFirst` doesn't really seem to name what it's doing.

Basically it takes the first Observable it gets and merges it, dropping all subsequent Observables it gets until the first one is complete, _then_ it takes another one.

Ideas I've had so far:

1. `tailDrop` or `dropTail` - https://en.wikipedia.org/wiki/Tail_drop
2. `pick` - because it picks the first and drops the rest until the first is done.
3. `chooseFirst` - same as pick, really, but it chooses the first and drops the rest.

**Comment by blesh** [comment]
My initial thought is `pick`. I don't like `choose` right off, because it sounds like there should be some sort of predicate to decide whether or not to merge the incoming observable.  Also, `pick` is pretty terse.

The downside is I'm not sure `pick` describes anything much better than `switchFirst`, but at least it doesn't have the confusion of having "switch" in there.

**Comment by blesh** [comment]
NOTE: I'd like to get decisions on this very quickly, as I don't want to break the API after beta release, if we can avoid it.

**Comment by jeffbcross** [comment]
My gut says `chooseFirst`.

**Comment by jayphelps** [comment]
exhaust or drain.

**Comment by blesh** [comment]
it's so focused on whatever observable it has that it ignores all incoming observables until that one observable completes. Then it drops it like it never existed at all and focuses on the very next observable it sees. It's obsessed with whatever observable it gets, so much so that the world around it fades away. Even if the observable it has _never_ emits a value, it'll sit there, staring at it... waiting... watching...  But if that observable it gets blasts data at it, it takes it all. It's greedy and patient. It's focused. It doesn't care about just the "first" observable it gets... it cares that it has one, any one, to call it's own, until the observable's death do they part... then it moves on, it wants another.

**Comment by jayphelps** [comment]
`scumbagObservable()`

**Comment by blesh** [comment]
> At the very least, we need to change switchMapFirst to switchFirstMap to match our naming scheme.

This minimum thing has been done.

**Comment by staltz** [comment]
I liked `exhaust` that @jayphelps suggested. Another option is `stick` as in "stick with this fella until he ends". Other options: `loyal`, `steadfast`, `stay`.

I don't like `pick` alone because it has the same problem as `choose`: both sound like they expect a predicate. To get the "*picks the first and drops the rest until the first is done*" you'd need an additional word, like `pickFirst`. Same problem as `chooseFirst`.

**Comment by trxcllnt** [comment]
> @staltz: I liked exhaust that @jayphelps suggested. Another option is stick as in "stick with this fella until he ends". Other options: loyal, steadfast, stay.

`brungYa` as in, "dance with the one that brung ya."

**Comment by blesh** [comment]
LOL
