### ISSUE TITLE
Bike-shedding: throttle -> ?

### ISSUE THREAD

**Issue by michaelbpaulson** [ReactiveX/RxJS#916]
Using real-world idea of what a throttle is makes it very confusing for the first time using the operator as it _blocks until time_ as oppose to letting events through based on time limit passed in.  

I am fully ready to accept I am incorrect, but the first time I used throttle this is the expected behavior.

```javascript
mouse.
    movement.
    throttle(200).
    subscribe(...);
```
If the mouse was under continuous use then my expectation was 5 events / second.  If backwards compat is a requirement, then perhaps the method could be called `choke` (still drawing examples from engines).  

Thoughts @blesh.  If this is totally unreasonable, feel no need to humor me and just close the ticket. :)

**Comment by blesh** [comment]
> Using real-world idea of what a throttle is makes it very confusing for the first time using the operator as it blocks until time as oppose to letting events through based on time limit passed in.

I think that RxJS 5 already does this. Earlier version of RxJS had `debounce` and `throttle` switched around.

Here is a demonstration of RxJS 5's `throttleTime`:  http://jsfiddle.net/81hox6cy/

Is this satisfactory?

**Comment by michaelbpaulson** [comment]
http://i1.wp.com/i286.photobucket.com/albums/ll117/humaicons/GIFs/spongebobleaves.gif?resize=500%2C323

**Comment by blesh** [comment]
😄
