### ISSUE TITLE
Run perf tests against previous build/version of RxJS Next

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#93]
So rather than just test against RxJS 2, perhaps it would be better to also run against the most recent published and/or master builds of RxJS Next?

I think to do this, we'd have to change the build target directory to something like `tmp/` which we wouldn't commit. Then use what's in there for the "local" test, vs "latest", "master" and "Rx2". Thoughts?

Pertains to some comments here #90

**Comment by blesh** [comment]
I think this should definitely happen before we move to Beta. By the time we hit Beta, everything should be mostly stable and a new performance baseline can be established.

**Comment by ktrott** [comment]
I'd like to see this even sooner as without it, we don't know build over build if we're improving/regressing our performance.

**Comment by ktrott** [comment]
@trxcllnt going to look at the work that we did for Falcor and reuse some of that here.

**Comment by blesh** [comment]
@ktrott has any of that been OSS'ed yet?

**Comment by ktrott** [comment]
Still a private repo for the moment, but @trxcllnt has access

**Comment by blesh** [comment]
This should really be something for the initial beta... since we won't really have something to run against other than RxJS 2/3 until this library is published to npm as at least an `alpha` version.

**Comment by blesh** [comment]
@jeffbcross do you have anything you're doing on the angular team to do perf tests against previous versions of angular in a semi-contained environment? Can you use Travis for that?
