### ISSUE TITLE
Change RxNext namespace to just Rx

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#96]
The RxNext namespace was added back when we were just trying to get some tests to work. It stuck. I think for the global files, we should change it to be Rx, just to be consistent with other versions.

**Comment by jeremymwells** [comment]
I can take this.

**Comment by blesh** [comment]
Okay, thanks @jeremymwells.  Be sure that perf tests are updated and run. (Currently, there is just the flatMap perf test that uses the global file)

**Comment by blesh** [comment]
I'll assign myself and check back with you for progress.
