### ISSUE TITLE
Add documentation generation

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#99]
I've used YUIDoc in the past to generate docs, @jeffbcross has recommended [Dgeni](/angular/dgeni), which is maintained by @petebacondarwin

I'm fine with either, but I know very little about the latter of the two.

**Comment by petebacondarwin** [comment]
@blesh - in both cases you would document your code with jsdoc style comments so you are not blocked on beginning to create the content.

I don't have any experience with YUIDoc, but from looking at it briefly, I would imagine the main differences between the two are that YUIDoc is going to provide a better "out of the box" experience and has nice features like live updates to the doc site, while dgeni requires more effort to get it going and you have to provide your own hosting app but then is likely to be more flexible to accommodate unusual aspects of your code base and documentation website requirements.

I am happy to work with you to spike a dgeni implementation to help make this decision.

You might like to look at what we are doing in Angular2 with dgeni, https://github.com/angular/angular/blob/master/docs, our main documentation is built from the `angular.io-package` and currently the d.ts file for angular 2 is built with `typescript-definition-package`

**Comment by robwormald** [comment]
i had a crack at this today, and got the basic pipeline working (mostly) - see https://github.com/robwormald/RxJS/tree/doc-generation/docs

@petebacondarwin one thing that's kinda borked at the moment in the typescript package is default exports from modules - Rx is all default exports and so you end up with:
```
/partials
/partials/BehaviorSubject/index.html
/partials/BehaviorSubject/default/index.html
```
and files like
```html

<h1 class="id">BehaviorSubject <span class="type">module</span></h1>
<p>defined in <a href="https://github.com/ReactiveX/RxJS/tree/0.0.0-prealpha.1/modules/BehaviorSubject.ts#L1-L26">BehaviorSubject.ts (line 1)</a></p>
<p></p>


<h2>Exports</h2>
<ul>
  <li><a href="/BehaviorSubject/default"><strong>default</strong> class</a></li>
</ul>
```
Which makes sense when reading over the typescript-package processor but isn't exactly a good user experience. I started to refactor it a bit but wanted to see if you were planning on moving the TS package to it's own repo or under the dgeni-packages repo (I've just copied it into the rx docs folder for the moment) before doing too much. 

Happy to own this one as I've got some experience with dgeni and too much free time at the moment. @blesh any arguments with the documentation app being an angular1 app? I could do it with purely static files but having a framework drive it gives us stuff like being able to do quick searches and the like. There's currently an angular-material scaffold in my branch.

**Comment by blesh** [comment]
I have no objections to any framework provided there is little maintenance and it fits the bill.

**Comment by blesh** [comment]
Thank you @robwormwald. Keep us posted on your progress.

Attn @trxcllnt... Whenever your branch lands, this merge will be tricky

**Comment by petebacondarwin** [comment]
@robwormald - this is great. There is definitely room for improvement in the TypeScript parser and `readTypeScriptModules` processor in the current Angular 2 project. The main reason it has not been moved out the current repo is that we have had to evolve it quite rapidly over the last few weeks. (In fact, up until recently it wasn't even in its own dgeni package in the Angular repo).

Having it in its own repository makes it easier to reuse but makes developing it for the Angular 2 project more painful. You have to release a new version of `dgeni-packages` npm module every time you make a change and you have to muck around with `npm link` while testing.

If we feel it is stabilizing and has uses outside of Angular 2 then we should indeed pull it out so that it can be worked on and reused more easily. I guess the obvious place would be `dgeni-packages`.

**Comment by petebacondarwin** [comment]
@robwormald what was your plan regarding refactoring?

From a quick browse, I thought we should probably follow a similar pattern to what we use for constructor members of classes. I.E. we pull them out of the list of members and attach them to the class doc as a specific `constructorDoc` property, which can be dealt with specially in the template. In the case of default exports, we could have a `defaultExport` property on each module and modify the template accordingly.

Any thoughts?

**Comment by robwormald** [comment]
@petebacondarwin i hadn't gotten too far beyond the 'repeatedly messing with it until I got a decent set of results' stage, so I'm all ears. I do think a good first step would be having the readTypescriptModules first step be as unopinionated as possible. 

My second thought was that I immediately wanted to wrap it all in an Observable and map/reduce the whole thing, but I thought that was maybe a little meta to start with...

For Rx I think something along the lines of [lodash](https://lodash.com/docs#difference) is the right sort of thing for output - for most users the module (file) structure is basically immaterial once they're imported the "package" as `import Rx from 'rx'`- I also quite like the 'annotated source' idea from Backbone, which meshes nicely with TypeScript and ES6 modules which are sort of "self-documenting"

**Comment by petebacondarwin** [comment]
Are you saying that the 'end-user' only imports this file?https://github.com/ReactiveX/RxJS/blob/master/src/Rx.ts

If so then we should base the dgeni processing off the export of that file...

**Comment by blesh** [comment]
@robwormald you'll want to rebase after today's merges. There was one merge in particular this morning that reorganized some files. The API didn't change, but the code structure did.

**Comment by blesh** [comment]
self assigning mostly just to remind me to check in.

**Comment by robwormald** [comment]
Not necessarily, afaik its designed to be modular, but that's the complete package (and currently where all the operators are attached). Having TS walk that root module is basically where I ended up - it spits out a nice graph of the structure but of course it's circular and so needs a bit of massaging. 

@blesh noted, thanks

**Comment by trxcllnt** [comment]
Does anybody here have any opinions on [docco](https://github.com/jashkenas/docco)? Also, here's a nice [comparison](http://blog.fusioncharts.com/2013/12/jsdoc-vs-yuidoc-vs-doxx-vs-docco-choosing-a-javascript-documentation-generator/) of a few docs generation tools.

**Comment by blesh** [comment]
I personally like being able to search, and have in-depth descriptions of parameters to functions, as well as links to source code. Angular's docs have always been quite good. One of the features I've loved the most about Angular's docs was the multi-version support. @petebacondarwin, @robwormald, can Dgeni support multi-version docs for us OOTB?

**Comment by petebacondarwin** [comment]
Angular's multi-version support is actually pretty basic. We have a completely new application deployment for each version.

The latest is hosted at docs.angularjs.org but all the previous versions are hosted at code.angularjs.org, where there is a folder for each version. This is possible because what we dump into code.angularjs.org is a copy of the build artefacts, which happens to include a self contained angular docs app.

On top of that we have a simple version picker in the app, which is populated at build time by data we glean from git tags.

**Comment by petebacondarwin** [comment]
Regarding that last point there is a `git` dgeni package (https://github.com/angular/dgeni-packages/tree/master/git) which can get this info from git and make it available to your dgeni templates.

**Comment by blesh** [comment]
@robwormald any progress?
