### ISSUE TITLE
Type checking errors and perf

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#994]
### Type checks, if we do them, should fail as soon as possible

I came across this one today: https://github.com/ReactiveX/RxJS/blob/43af805aee3d8c54824331943cc6c29573da63ed/src/operator/every.ts#L72-L74

Basically, the `every` operator is checking to see if `predicate` is a function, but not until the source nexts a value at it. That's like saying `[].every('trololololo')` is valid because `[]` has no values.

`source.every('lol')` should've thrown immediately as it was called, totally outside of the subscribed Observable lifecycle. 

... but actually `every` probably shouldn't be doing that sort of type checking at all because...

### Perf

Given that performance is our primary goal. I'd like to eliminate these sorts of type checks entirely except for places where it makes sense. For example:

- doesn't make sense on `every`, because why would anyone not pass a function to `every`, a clear mistake.
- makes TOTAL sense on `map` because people might expect the `mapTo` behavior and pass something that's not a function.

### Request

Look through the operators and make sure that type checking is only being done where it makes sense.

**Comment by kwonoj** [comment]
I have been briefly go through operators, and seems this can be closed for now after applying refactoring above.

**Comment by blesh** [comment]
I think enough people have seen this now to get the idea.
