### ISSUE TITLE
Get rid of _isScalar property checking?

### ISSUE THREAD

**Issue by blesh** [ReactiveX/rxjs#997]
It would perform better if all special handling of operators for scalar observables was done on their respective types. The types that *can* be scalar and benefit from special handling are:

- `ScalarObservable` (obvious)
- `PromiseObservable`: once the promise is resolved, operators can shortcut off the cached `value`.
- `AsyncSubject`: once completed with a value, the stored `value` can be used to shortcut operators.

### Tricky stuff

There is some special handling sprinkled in to some of the inner subscription stuff to short cut some of those subscriptions. We'll still want to do some of those things. Perhaps another `symbol`-based solution like an `Rx.Symbol.rxScalar` would work in those cases... basically as follows:

```js
let scalar;
if (obs[rxScalar] && scalar = obs[rxScalar]()) {
  const value = scalar.value;
  // do something with value
}
```

Where the `rxScalar` symbol returns an object `{ value: any }` if it has a scalar value, and returns `void` if it does not have a scalar value.  This gives types like `PromiseObservable` that have a delayed scalar behavior the ability to determine whether or not they can be handled in a scalar fashion.

**Comment by blesh** [comment]
As an added benefit, it should reduce some dependencies in operators that are doing this sort of checking.

As a downside, it could add bulk to ScalarObservable, PromiseObservable, etc.

**Comment by trxcllnt** [comment]
@blesh I like the symbol approach better than the duck-typed pseudo-contract we have today. Total nitpick here, but I like the syntax:
```es6
if (obs[rxScalar]) {
  const {value} = obs[rxScalar]();
  // ... do something with value
}

**Comment by blesh** [comment]
@trxcllnt simply having the `rxScalar` symbol wouldn't mean you have a value. it also has to return something. Perhaps this is a sign my design doesn't read fluently.

How about this?

```js
if (obs[rxScalar]) {
  const { hasValue, value } = obs[rxScalar]();
  if (hasValue) {
    // ... do something with value
  }
}
```

**Comment by trxcllnt** [comment]
@blesh ah, I see. I misunderstood. How about...
```es6
if (obs[rxScalar]) {
  const {done, value} = obs[rxScalar]();
  if (done) {
    // ... do something with value
  }
}
```
:trollface:

**Comment by blesh** [comment]
`done` has other connotations. (IteratorResult for example). I like `hasValue`.

**Comment by blesh** [comment]
In retrospect, it might be better just to do `instanceof` checks for `ScalarObservable` and `PromiseObservable` and handle them accordingly. `instanceof` checks are generally faster than property checking, especially in some of the resource constrained devices we deal with at Netflix, according to @steveorsomethin

**Comment by trxcllnt** [comment]
@blesh @steveorsomethin but if we have to use `instanceof`, won't that defeat the purpose of allowing Observables to become scalar at runtime?

**Comment by blesh** [comment]
@trxcllnt the only observable that becomes scalar at runtime is the PromiseObservable, to my knowledge.

**Comment by trxcllnt** [comment]
@blesh what about [ArrayObservable](https://github.com/ReactiveX/RxJS/blob/master/src/observable/fromArray.ts#L58), AsyncSubject, RangeObservable(0, 1), etc.?

**Comment by blesh** [comment]
`ArrayObservable` and `RangeObservable` could just check length and return a `ScalarObservable` by implementation.

`AsyncSubject` could just be another one we `instanceof` check.

**Comment by trxcllnt** [comment]
@blesh how would ArrayObservable and RangeObservable do that in their constructors? or are you talking about a world where we have an `rxScalar` symbol?

**Comment by blesh** [comment]
@trxcllnt no I'm talking in `range`, `fromArray` and `from` methods. I think if you're creating an `ArrayObservable` with `new ArrayObservable` it's pretty specific that you _want_ an `ArrayObservable` and the behaviors that come with that. Most people aren't going to call those constructors directly.

**Comment by trxcllnt** [comment]
@blesh ah, I see. I vote for doing whatever's fastest, while also supporting the dynamic case. Intuitively I feel we shouldn't go with `instanceof` if the number of types we have to check is more than 2 (which it sounds like it is), but maybe @steveorsomethin can benchmark the ratio between `instanceof` checks and hash lookups. We also need to fix `from` to return Scalar or Empty Observables if you pass it an Array with 1 or 0 elements.

**Comment by blesh** [comment]
This issue has gone stale. Closing
