### ISSUE TITLE
Run tests in all major browsers and engines

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#998]
This needs to be run against:

- IE 9+,
- Chrome
- FF
- Safari
- Android
- iOS
- Node > 0.12

in an automated way. Currently we're only running against Node, and that's not good.

**Comment by luisgabriel** [comment]
The idea here is to use a CI like [saucelabs](http://saucelabs.com)?

**Comment by kwonoj** [comment]
Yes it is. I was trying this for some time but wanted to land https://github.com/ReactiveX/RxJS/pull/826 this before, so hold for a while. Requires two steps I assume,  

- setup test environment using runner like `karma` can do browser test with existing spec
- setup travis pipeline to saucelab to run node test on travis as ci process, rest of browser test being pipelined to saucelabs.

**Comment by kwonoj** [comment]
I'll try to spend couple of days to see if I can make land `karma` into current codebase quickly. That can be starting point.

**Comment by kwonoj** [comment]
Seems https://github.com/ReactiveX/RxJS/issues/733 is related.

**Comment by kwonoj** [comment]
As referenced in PR #1023 , it's required to create official RxJS saucelabs account (https://saucelabs.com/) and configure travis environment values. By saucelabs account requires email account when creating account and it should not be my personal one, asking @blesh to create one.

**Comment by kwonoj** [comment]
For some reason I thought email address was permanent login credential which is not actually and can be changed easily. I'm creating account by my own, change those information accordingly later to close out this issue.

**Comment by kwonoj** [comment]
#1187 is decoration change, so will close this issue by #1199 which now expands browser matrix. Each test failures will be tracked separately instead of using this broad issue.
