### ISSUE TITLE
Errors with SymbolShim in some browsers

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#999]
According the the Angular core Slack, there is an issue in some browsers when trying to call `Symbol.for`. Namely in Safari 8 and all versions of IE.

I haven't reproduced this yet, but I can see/understand where the issue is. Such is the danger with DIY polyfills.

You can see that [Symbol is supported](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol) in more browsers than [Symbol.for is](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/for).

**Comment by luisgabriel** [comment]
It seems to be the same problem as #988.
